DynoSAM: dyno::StateQuery< ValueType > Class Template Reference
dyno::StateQuery< ValueType > Class Template Reference
Represents an optional value with meta-data that is retrieved from the map.
#include <MapNodes.hpp>
Public Types
using Base = std::optional< ValueType >
Base type representing the existance of the query value.
using Status = StateQueryStatus
Status of the state query.
Public Member Functions
gtsam::Key key () const
Status status () const
StateQuery ()
StateQuery (gtsam::Key key, const ValueType &v)
StateQuery (gtsam::Key key, Status status)
const ValueType & get () const
bool isValid () const
Static Public Member Functions
static StateQuery InvalidMap ()
static StateQuery NotInMap (gtsam::Key key)
static StateQuery WasInMap (gtsam::Key key)
Public Attributes
gtsam::Key key_
Status status_
Detailed Description
template<typename ValueType>
class dyno::StateQuery< ValueType >
Represents an optional value with meta-data that is retrieved from the map.
Template Parameters
ValueType A value type stored in gtsam::Values
Definition at line 286 of file MapNodes.hpp.
Member Typedef Documentation
Base
template<typename ValueType > using dyno::StateQuery< ValueType >::Base = std::optional<ValueType>
Base type representing the existance of the query value.
Definition at line 289 of file MapNodes.hpp.
Status
template<typename ValueType > using dyno::StateQuery< ValueType >::Status = StateQueryStatus
Status of the state query.
Definition at line 293 of file MapNodes.hpp.
Constructor & Destructor Documentation
StateQuery() [1/3]
template<typename ValueType > dyno::StateQuery< ValueType >::StateQuery () inline
Definition at line 300 of file MapNodes.hpp.
{}
Referenced by dyno::StateQuery< ValueType >::InvalidMap(), dyno::StateQuery< ValueType >::NotInMap(), and dyno::StateQuery< ValueType >::WasInMap().
StateQuery() [2/3]
template<typename ValueType > dyno::StateQuery< ValueType >::StateQuery (gtsam::Key key, const ValueType & v) inline
Definition at line 301 of file MapNodes.hpp.
                                               : key_(key), status_(VALID) {
    Base::emplace(v);
  }
StateQuery() [3/3]
template<typename ValueType > dyno::StateQuery< ValueType >::StateQuery (gtsam::Key key, Status status) inline
Definition at line 304 of file MapNodes.hpp.
: key_(key), status_(status) {}
Member Function Documentation
get()
template<typename ValueType > const ValueType & dyno::StateQuery< ValueType >::get () const inline
Definition at line 308 of file MapNodes.hpp.
{
    if (!Base::has_value())
      throw DynosamException("StateQuery has no value for query type " +
                             type_name<ValueType>() + " with key " +
                             DynosamKeyFormatter(key_));
    return Base::value();
  }
References dyno::DynosamKeyFormatter(), and dyno::StateQuery< ValueType >::key_.
Referenced by dyno::HybridFormulation::computeInitialH(), dyno::AccessorT< MAP >::getDynamicLandmarkEstimates(), dyno::HybridAccessor::getDynamicLandmarkEstimates(), dyno::HybridAccessor::getDynamicLandmarkImpl(), dyno::HybridFormulation::getEstimatedMotion(), dyno::AccessorT< MAP >::getFullStaticMap(), dyno::ParallelObjectISAM::getKeyFramedMotion(), dyno::HybridAccessor::getLocalDynamicLandmarkEstimates(), dyno::HybridAccessor::getObjectMotion(), dyno::AccessorT< MAP >::getObjectMotionReferenceFrame(), dyno::AccessorT< MAP >::getObjectMotions(), dyno::HybridAccessor::getObjectPose(), dyno::AccessorT< MAP >::getObjectPoses(), dyno::getSafeQuery(), dyno::AccessorT< MAP >::getStaticLandmarkEstimates(), dyno::AccessorT< MAP >::hasObjectMotionEstimate(), dyno::AccessorT< MAP >::hasObjectPoseEstimate(), dyno::ParallelHybridBackendModule::logBackendFromEstimators(), dyno::Formulation< MAP >::logBackendFromMap(), dyno::VisionImuBackendModule< MODULE_TRAITS >::navState(), dyno::ParallelHybridBackendModule::nominalSpinImpl(), dyno::ParallelHybridBackendModule::nominalUpdateStaticEstimator(), and dyno::WorldPoseFormulation::objectUpdateContext().
InvalidMap()
template<typename ValueType > static StateQuery dyno::StateQuery< ValueType >::InvalidMap () inline static
Definition at line 318 of file MapNodes.hpp.
{
    return StateQuery(gtsam::Key{}, INVALID_MAP);
  }
References dyno::INVALID_MAP, and dyno::StateQuery< ValueType >::StateQuery().
Referenced by dyno::HybridAccessor::getObjectMotion(), dyno::HybridAccessor::getObjectPose(), dyno::WorldMotionAccessor::getObjectPose(), dyno::WorldPoseAccessor::getObjectPose(), and dyno::HybridAccessor::getSensorPose().
isValid()
template<typename ValueType > bool dyno::StateQuery< ValueType >::isValid () const inline
Definition at line 316 of file MapNodes.hpp.
{ return status_ == VALID; }
References dyno::StateQuery< ValueType >::status_, and dyno::VALID.
key()
template<typename ValueType > gtsam::Key dyno::StateQuery< ValueType >::key () const inline
Definition at line 297 of file MapNodes.hpp.
{ return key_; }
References dyno::StateQuery< ValueType >::key_.
Referenced by dyno::HybridFormulation::getEstimatedMotion(), dyno::ParallelHybridBackendModule::nominalUpdateStaticEstimator(), dyno::StateQuery< ValueType >::NotInMap(), and dyno::StateQuery< ValueType >::WasInMap().
NotInMap()
template<typename ValueType > static StateQuery dyno::StateQuery< ValueType >::NotInMap (gtsam::Key key) inline static
Definition at line 321 of file MapNodes.hpp.
{
    return StateQuery(key, NOT_IN_MAP);
  }
References dyno::StateQuery< ValueType >::key(), dyno::NOT_IN_MAP, and dyno::StateQuery< ValueType >::StateQuery().
Referenced by dyno::HybridAccessor::getDynamicLandmarkImpl(), dyno::HybridAccessor::getObjectMotion(), dyno::WorldPoseAccessor::getObjectMotion(), dyno::HybridAccessor::getObjectPose(), and dyno::test_hybrid::SmartStructurlessAccessor::queryPoint().
status()
template<typename ValueType > Status dyno::StateQuery< ValueType >::status () const inline
Definition at line 298 of file MapNodes.hpp.
{ return status_; }
References dyno::StateQuery< ValueType >::status_.
Referenced by dyno::HybridFormulation::getEstimatedMotion().
WasInMap()
template<typename ValueType > static StateQuery dyno::StateQuery< ValueType >::WasInMap (gtsam::Key key) inline static
Definition at line 324 of file MapNodes.hpp.
{
    return StateQuery(key, WAS_IN_MAP);
  }
References dyno::StateQuery< ValueType >::key(), dyno::StateQuery< ValueType >::StateQuery(), and dyno::WAS_IN_MAP.
Member Data Documentation
key_
template<typename ValueType > gtsam::Key dyno::StateQuery< ValueType >::key_
Definition at line 294 of file MapNodes.hpp.
Referenced by dyno::StateQuery< ValueType >::get(), dyno::AccessorT< MAP >::getObjectMotionReferenceFrame(), and dyno::StateQuery< ValueType >::key().
status_
template<typename ValueType > Status dyno::StateQuery< ValueType >::status_
Definition at line 295 of file MapNodes.hpp.
Referenced by dyno::AccessorT< MAP >::getObjectMotionReferenceFrame(), dyno::StateQuery< ValueType >::isValid(), and dyno::StateQuery< ValueType >::status().
The documentation for this class was generated from the following file:
dynosam_opt/include/dynosam_opt/MapNodes.hpp