DynoSAM: dyno::DynoPipelineManagerRos Class Reference
dyno::DynoPipelineManagerRos Class Reference
#include <PipelineRos.hpp>
Public Member Functions
DynoPipelineManagerRos (const rclcpp::NodeOptions &options=rclcpp::NodeOptions())
~DynoPipelineManagerRos ()=default
void initalisePipeline ()
bool spinOnce () override
Public Member Functions inherited from dyno::DynoNode
DynoNode (const std::string &node_name, const rclcpp::NodeOptions &options=rclcpp::NodeOptions())
virtual ~DynoNode ()=default
virtual bool spinOnce ()
std::string getStats () const
const DynoParams & getDynoParams ()
std::string getParamsPath ()
std::string getDatasetPath ()
Private Attributes
DynoPipelineManager::UniquePtr pipeline_
Additional Inherited Members
Protected Member Functions inherited from dyno::DynoNode
virtual dyno::DataProvider::Ptr createDataProvider ()
dyno::DataProvider::Ptr createOnlineDataProvider ()
dyno::DataProvider::Ptr createDatasetDataProvider ()
Protected Attributes inherited from dyno::DynoNode
bool is_online_
Detailed Description
Definition at line 94 of file PipelineRos.hpp.
Constructor & Destructor Documentation
DynoPipelineManagerRos()
dyno::DynoPipelineManagerRos::DynoPipelineManagerRos (const rclcpp::NodeOptions & options = rclcpp::NodeOptions()) explicit
Definition at line 159 of file PipelineRos.cc.
    : DynoNode("dynosam", options) {}
~DynoPipelineManagerRos()
dyno::DynoPipelineManagerRos::~DynoPipelineManagerRos () default
Member Function Documentation
initalisePipeline()
void dyno::DynoPipelineManagerRos::initalisePipeline ()
Definition at line 163 of file PipelineRos.cc.
{
  RCLCPP_INFO_STREAM(this->get_logger(), "Starting DynoPipelineManagerRos");
  // load data provider first as this could change some params to ensure
  // they match with the data-provider selected!
  auto data_loader = createDataProvider();
  auto params = getDynoParams();
  // setup display params
  DisplayParams display_params;
  display_params.camera_frame_id =
      ParameterConstructor(this, "camera_frame_id",
                           display_params.camera_frame_id)
          .description(
              "ROS frame id for the camera (ie. the measured odometry)")
          .finish()
          .get<std::string>();
  display_params.world_frame_id =
      ParameterConstructor(this, "world_frame_id",
                           display_params.world_frame_id)
          .description("ROS frame id for the static workd frame (ie. odometry)")
          .finish()
          .get<std::string>();
  auto frontend_display = std::make_shared<dyno::FrontendDisplayRos>(
      display_params, this->create_sub_node("frontend"),
      this->create_sub_node("ground_truth"));
  auto backend_display = std::make_shared<dyno::BackendDisplayRos>(
      display_params, this->create_sub_node("backend"));
  ExternalHooks::Ptr hooks = std::make_shared<ExternalHooks>();
  // if online then we are using OnlineDataProviderRos, which should collect the
  // timestamp from ROS anyway. Otherwise, the timestamp comes from the dynosam
  // DataLoaders and so we need to artifially tell the ROS network what the time
  // is
  if (!is_online_) {
    RCLCPP_INFO_STREAM(this->get_logger(),
                       "Update time external hook created. This will publish "
                       "internal dynosam timestamp's to /clock!");
    rclcpp::Publisher<rosgraph_msgs::msg::Clock>::SharedPtr clock_pub =
        this->create_publisher<rosgraph_msgs::msg::Clock>("/clock", 10);
    hooks->update_time = [clock_pub](Timestamp timestamp) -> void {
      auto msg = rosgraph_msgs::msg::Clock();
      msg.clock = utils::toRosTime(timestamp);
      CHECK_NOTNULL(clock_pub)->publish(msg);
    };
  }
  using RosBackendFactory = BackendFactory<BackendModulePolicyRos,
                                           RegularBackendModuleTraits::MapType>;
  // for now we just support regular backend ... in fact this design means we
  // should depricate any other map...
  //   auto factory =
  //   DefaultBackendFactory<RegularBackendModuleTraits::MapType>::Create(params.backend_type);
  //   auto this_node = this->shared_from_this();
  //   CHECK_NOTNULL(this_node);
  auto factory =
      RosBackendFactory::Create(params.backend_type, display_params, this);
  pipeline_ = std::make_unique<DynoPipelineManager>(
      params, data_loader, frontend_display, backend_display, factory, hooks);
}
References dyno::DisplayParams::camera_frame_id, dyno::DynoNode::createDataProvider(), dyno::ParameterConstructor::description(), dyno::ParameterConstructor::finish(), dyno::ParameterDetails::get(), dyno::DynoNode::getDynoParams(), dyno::DynoNode::is_online_, pipeline_, dyno::utils::toRosTime(), and dyno::DisplayParams::world_frame_id.
spinOnce()
bool dyno::DynoPipelineManagerRos::spinOnce () inline override virtual
Reimplemented from dyno::DynoNode.
Definition at line 102 of file PipelineRos.hpp.
{
    RCLCPP_INFO_STREAM_THROTTLE(this->get_logger(), *this->get_clock(), 2000,
                                getStats());
    return CHECK_NOTNULL(pipeline_)->spin();
  }
References dyno::DynoNode::getStats(), and pipeline_.
Member Data Documentation
pipeline_
DynoPipelineManager::UniquePtr dyno::DynoPipelineManagerRos::pipeline_ private
Definition at line 110 of file PipelineRos.hpp.
Referenced by initalisePipeline(), and spinOnce().
The documentation for this class was generated from the following files:
dynosam_ros/include/dynosam_ros/PipelineRos.hpp
dynosam_ros/src/PipelineRos.cc