DynoSAM: dyno::ByteObjectTracker Class Reference
dyno::ByteObjectTracker Class Reference
#include <ObjectTracker.hpp>
Public Member Functions
cv::Mat track (const cv::Mat &mask, FrameId frame_id) override
Public Member Functions inherited from dyno::ObjectTracker
virtual ~ObjectTracker ()=default
virtual cv::Mat track (const cv::Mat &mask, FrameId frame_id)=0
Private Attributes
byte_track::ByteTracker impl_tracker_
Detailed Description
Definition at line 44 of file ObjectTracker.hpp.
Member Function Documentation
track()
cv::Mat dyno::ByteObjectTracker::track (const cv::Mat & mask, FrameId frame_id) override virtual
Implements dyno::ObjectTracker.
Definition at line 37 of file ObjectTracker.cc.
{
  const ObjectIds instance_labels = vision_tools::getObjectLabels(masks);
  std::vector<byte_track::DetectionBase::Ptr> input_detections;
  for (auto instance_label : instance_labels) {
    cv::Rect bounding_box;
    if (vision_tools::findObjectBoundingBox(masks, instance_label,
                                            bounding_box)) {
      input_detections.push_back(
          std::make_shared<byte_track::Detection>(bounding_box, 1.0));
    } else {
      VLOG(30) << "Could not find bb for instance label " << instance_label
               << " at frame " << frame_id << " and therefore could not track!";
    }
  }
  auto object_tracks = impl_tracker_.update(input_detections, frame_id);
  CHECK_EQ(object_tracks.size(), input_detections.size());
  ObjectIds old_labels = instance_labels;
  ObjectIds new_labels;  // the new tracked labels from the EKF
  for (const auto& track : object_tracks) {
    new_labels.push_back(track->get_track_id());
  }
  // update tracking labels
  cv::Mat updated_masks;
  vision_tools::relabelMasks(masks, updated_masks, old_labels, new_labels);
  return updated_masks;
}
References dyno::vision_tools::findObjectBoundingBox(), dyno::vision_tools::getObjectLabels(), impl_tracker_, dyno::vision_tools::relabelMasks(), track(), and dyno::byte_track::ByteTracker::update().
Referenced by track().
Member Data Documentation
impl_tracker_
byte_track::ByteTracker dyno::ByteObjectTracker::impl_tracker_ private
Definition at line 49 of file ObjectTracker.hpp.
Referenced by track().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/frontend/vision/ObjectTracker.hpp
dynosam/src/frontend/vision/ObjectTracker.cc