DynoSAM: dyno::Frame Class Reference
dyno::Frame Class Reference
#include <Frame.hpp>
Public Types
template<typename RefType , typename CurType >
using ConstructCorrespondanceFunc = std::function< TrackletCorrespondance< RefType, CurType >(const Frame &, const Feature::Ptr &, const Feature::Ptr &)>
Functional alias that constructs a TrackletCorrespondance from a pair of features (tracked features in the previous and current frame respectively) and the previous frame. The function arguments are in the form previous frame, previous feature, current feature.
Public Member Functions
Frame (FrameId frame_id, Timestamp timestamp, Camera::Ptr camera, const ImageContainer &image_container, const FeatureContainer &static_features, const FeatureContainer &dynamic_features, std::optional< FeatureTrackerInfo > tracking_info={})
FrameId getFrameId () const
Timestamp getTimestamp () const
const Camera::Ptr & getCamera () const
const gtsam::Pose3 & getPose () const
Returns the pose of the sensor at this frame w.r.t the world frame i.e ^wT_c such that a point, p measured in the camera frame can be put in the world frame using this pose e.g. ^wp = ^wT_c * ^cp.
const std::map< ObjectId, DynamicObjectObservation > & getObjectObservations () const
std::map< ObjectId, DynamicObjectObservation > & getObjectObservations ()
const std::optional< FeatureTrackerInfo > & getTrackingInfo () const
size_t numStaticFeatures () const
Gets the total number of static features observed at this frame. Includes usables (inliers) and outliers.
size_t numStaticUsableFeatures ()
Gets the total number of static inlier features.
size_t numDynamicFeatures () const
Gets the total number of dynamic features observed at this frame. Includes usables (inliers) and outliers.
size_t numDynamicUsableFeatures ()
Gets the total number of dynamic inlier features.
size_t numTotalFeatures () const
Gets the total number of features (static + dynamic) in this frame. Includes usables (inliers) and outliers.
bool exists (TrackletId tracklet_id) const
Checks if a feature exists within this frame. Could be static or dynamic.
Feature::Ptr at (TrackletId tracklet_id) const
Gets a feature from its tracklet ID. Could be static or dynamic. Nullptr is returned if the feature does not exist.
bool isFeatureUsable (TrackletId tracklet_id) const
Returns true if the feature is usable (inlier). Throws std::runtime_error if the feature does not exist. Use in conjunction with Frame::exists.
FeaturePtrs collectFeatures (TrackletIds tracklet_ids) const
Collects a vector of feature pointers given a vector of tracklet ids. Features returned could be inliers or outliers. If a feature does not exist std::runtime_error.
Landmark backProjectToCamera (TrackletId tracklet_id) const
Project the feature into the camera frame and returns the 3D landmark. Currently requires the feature to have depth associated with it.
Landmark backProjectToWorld (TrackletId tracklet_id) const
Project the feature into the world frame using the frames pose (T_world_camera_) and returns the 3D landmark. Currently requires the feature to have depth associated with it.
Camera::CameraImpl getFrameCamera () const
Constructs a GTSAM camera for this frame using the current pose of this camera (T_world_camera)
ObjectIds getObjectIds () const
bool updateDepths ()
Update the depth values on all contained features. Clips the static and dynamic features (marking them invalid) accordingly.
cv::Mat drawDetectedObjectBoxes () const
From the detected list of objects (in Frame::object_observations_) draw the object masks as labelled bounding boxes.
Frame & setMaxBackgroundDepth (double thresh)
Frame & setMaxObjectDepth (double thresh)
void moveObjectToStatic (ObjectId instance_label)
void updateObjectTrackingLabel (const DynamicObjectObservation &observation, ObjectId new_tracking_label)
bool getCorrespondences (FeaturePairs &correspondences, const Frame &previous_frame, KeyPointType kp_type) const
Gets the set of tracked pairs between this frame and the previous frame. All correspondences will be usable (inliers). The correspondences will be in the form of feature pairs where first = feature in the previous frame and second = feature in this frame.
bool getDynamicCorrespondences (FeaturePairs &correspondences, const Frame &previous_frame, ObjectId object_id) const
Gets the set of tracked pairs between this frame and the previous frame for a tracked dynamic object seen in both frames.
ConstructCorrespondanceFunc< Landmark, Keypoint > landmarkWorldKeypointCorrespondance () const
Helper function that creates a ConstructCorrespondanceFunc which operates to return a TrackletCorrespondance where the ref type is a Landmark in the world frame and the cur type is a Keypoint in the current frame.
ConstructCorrespondanceFunc< Keypoint, Keypoint > imageKeypointCorrespondance () const
Helper function that creates a ConstructCorrespondanceFunc which operates to return a TrackletCorrespondance where both types are keypoints (in the ref and cur frame respectively).
ConstructCorrespondanceFunc< Landmark, gtsam::Vector3 > landmarkWorldProjectedBearingCorrespondance () const
Helper function that creates a ConstructCorrespondanceFunc which operates to return a TrackletCorrespondance where the ref type is a Landmark in the world frame and the curr type is a normalized bearing vector constructed from the corresponding Keypoint in the current frame.
ConstructCorrespondanceFunc< Landmark, Landmark > landmarkWorldPointCloudCorrespondance () const
Helper function ConstructCorrespondanceFunc which operates to return a TrackletCorrespondance where both types are Landmarks in the world frame (in the ref and cur frame respectively).
template<typename RefType , typename CurType >
bool getCorrespondences (GenericCorrespondences< RefType, CurType > &correspondences, const Frame &previous_frame, KeyPointType kp_type, const ConstructCorrespondanceFunc< RefType, CurType > &func) const
template<typename RefType , typename CurType >
bool getDynamicCorrespondences (GenericCorrespondences< RefType, CurType > &correspondences, const Frame &previous_frame, ObjectId object_id, const ConstructCorrespondanceFunc< RefType, CurType > &func) const
FeatureFilterIterator usableStaticFeaturesBegin ()
FeatureFilterIterator usableStaticFeaturesBegin () const
FeatureFilterIterator usableDynamicFeaturesBegin ()
FeatureFilterIterator usableDynamicFeaturesBegin () const
Public Attributes
const FrameId frame_id_
const Timestamp timestamp_
Camera::Ptr camera_
const ImageContainer image_container_
gtsam::Pose3 T_world_camera_ = gtsam::Pose3::Identity()
FeatureContainer static_features_
FeatureContainer dynamic_features_
std::optional< FeatureTrackerInfo > tracking_info_
std::map< ObjectId, DynamicObjectObservation > object_observations_
MotionEstimateMap motion_estimates_
Static Public Attributes
static ObjectId global_object_id {1}
Depricate as unused!
Protected Member Functions
bool getStaticCorrespondences (FeaturePairs &correspondences, const Frame &previous_frame) const
bool getDynamicCorrespondences (FeaturePairs &correspondences, const Frame &previous_frame) const
Private Member Functions
void constructDynamicObservations ()
Landmark getLandmarkFromCache (LandmarkMap &cache, Feature::Ptr feature, const gtsam::Pose3 &X_world) const
Static Private Member Functions
static void updateDepthsFeatureContainer (FeatureContainer &container, const ImageWrapper< ImageType::Depth > &depth, double max_depth)
Private Attributes
UndistorterRectifier::Ptr undistorter_
LandmarkMap landmark_in_camera_cache_
LandmarkMap landmark_in_world_cache_
double max_background_threshold_ = 40.0
Background points greater than this depth will be discarded.
double max_object_threshold_ = 25.0
Detailed Description
Definition at line 45 of file Frame.hpp.
Member Typedef Documentation
ConstructCorrespondanceFunc
template<typename RefType , typename CurType > using dyno::Frame::ConstructCorrespondanceFunc = std::function<TrackletCorrespondance<RefType, CurType>(const Frame&, const Feature::Ptr&, const Feature::Ptr&)>
Functional alias that constructs a TrackletCorrespondance from a pair of features (tracked features in the previous and current frame respectively) and the previous frame. The function arguments are in the form previous frame, previous feature, current feature.
We functionalise this operation so that we can define any type of TrackletCorrespondance for a set of tracked features via Frame::getCorrespondences which takes a ConstructCorrespondanceFunc as an argument.
Template Parameters
RefType Type to be used as the reference type in the TrackletCorrespondance
CurType Type to be used as the current type in the TrackletCorrespondance
Definition at line 322 of file Frame.hpp.
Constructor & Destructor Documentation
Frame()
dyno::Frame::Frame (FrameId frame_id, Timestamp timestamp, Camera::Ptr camera, const ImageContainer & image_container, const FeatureContainer & static_features, const FeatureContainer & dynamic_features, std::optional< FeatureTrackerInfo > tracking_info = {})
Definition at line 34 of file Frame.cc.
        :   frame_id_(frame_id),
            timestamp_(timestamp),
            camera_(camera),
            image_container_(image_container),
            static_features_(static_features),
            dynamic_features_(dynamic_features),
            tracking_info_(tracking_info)
        {
            constructDynamicObservations();
            // NOTE: no rectification, use camera matrix as P for cv::undistortPoints
            // see https://stackoverflow.com/questions/22027419/bad-results-when-undistorting-points-using-opencv-in-python
            //i mean, this could just be shared between frames?
            const CameraParams& cam_params = camera->getParams();
            cv::Mat P = cam_params.getCameraMatrix();
            cv::Mat R = cv::Mat::eye(3,3,CV_32FC1);
            undistorter_ = std::make_shared<UndistorterRectifier>(P, cam_params, R);
        }
References constructDynamicObservations(), dyno::CameraParams::getCameraMatrix(), and undistorter_.
Member Function Documentation
at()
Feature::Ptr dyno::Frame::at (TrackletId tracklet_id) const
Gets a feature from its tracklet ID. Could be static or dynamic. Nullptr is returned if the feature does not exist.
Parameters
tracklet_id TrackletId
Returns
Feature::Ptr
Definition at line 72 of file Frame.cc.
{
    if(!exists(tracklet_id)) {
        return nullptr;
    }
    if(static_features_.exists(tracklet_id)) {
        CHECK(!dynamic_features_.exists(tracklet_id));
        return static_features_.getByTrackletId(tracklet_id);
    }
    else {
        CHECK(dynamic_features_.exists(tracklet_id));
        return dynamic_features_.getByTrackletId(tracklet_id);
    }
}
References dynamic_features_, dyno::FeatureContainer::exists(), exists(), dyno::FeatureContainer::getByTrackletId(), and static_features_.
Referenced by backProjectToCamera(), backProjectToWorld(), collectFeatures(), dyno::RGBDInstanceFrontendModule::constructOutput(), and isFeatureUsable().
backProjectToCamera()
Landmark dyno::Frame::backProjectToCamera (TrackletId tracklet_id) const
Project the feature into the camera frame and returns the 3D landmark. Currently requires the feature to have depth associated with it.
Parameters
tracklet_id TrackletId
Returns
Landmark
Definition at line 114 of file Frame.cc.
{
    Feature::Ptr feature = at(tracklet_id);
    if(!feature) {
        throw std::runtime_error("Failed to backProjectToCamera - tracklet id " + std::to_string(tracklet_id) + " does not exist");
    }
    //if no depth, project to unitsphere?
    CHECK(feature->hasDepth());
    // Landmark lmk;
    return getLandmarkFromCache(landmark_in_camera_cache_, feature, gtsam::Pose3::Identity());
    // return lmk;
}
References at(), getLandmarkFromCache(), and landmark_in_camera_cache_.
backProjectToWorld()
Landmark dyno::Frame::backProjectToWorld (TrackletId tracklet_id) const
Project the feature into the world frame using the frames pose (T_world_camera_) and returns the 3D landmark. Currently requires the feature to have depth associated with it.
Parameters
tracklet_id TrackletId
Returns
Landmark
Definition at line 128 of file Frame.cc.
{
    Feature::Ptr feature = at(tracklet_id);
    if(!feature) {
        throw std::runtime_error("Failed to backProjectToWorld - tracklet id " + std::to_string(tracklet_id) + " does not exist");
    }
    //if no depth, project to unitsphere?
    CHECK(feature->hasDepth());
    // Landmark lmk;
    // camera_->backProject(feature->keypoint_, feature->depth_, &lmk, T_world_camera_);
    return getLandmarkFromCache(landmark_in_world_cache_, feature, T_world_camera_);
}
References at(), getLandmarkFromCache(), landmark_in_world_cache_, and T_world_camera_.
Referenced by landmarkWorldKeypointCorrespondance(), landmarkWorldPointCloudCorrespondance(), landmarkWorldProjectedBearingCorrespondance(), and dyno::vision_tools::trackDynamic().
collectFeatures()
FeaturePtrs dyno::Frame::collectFeatures (TrackletIds tracklet_ids) const
Collects a vector of feature pointers given a vector of tracklet ids. Features returned could be inliers or outliers. If a feature does not exist std::runtime_error.
Parameters
tracklet_ids TrackletIds
Returns
FeaturePtrs
Definition at line 98 of file Frame.cc.
{
    FeaturePtrs features;
    for(const auto tracklet_id : tracklet_ids) {
        Feature::Ptr feature = at(tracklet_id);
        if(!feature) {
            throw std::runtime_error("Failed to collectFeatures - tracklet id " + std::to_string(tracklet_id) + " does not exist");
        }
        features.push_back(feature);
    }
    return features;
}
References at().
constructDynamicObservations()
void dyno::Frame::constructDynamicObservations () private
Definition at line 367 of file Frame.cc.
{
    object_observations_.clear();
    //assumes that the mask gets updated with the tracking label
    const ObjectIds instance_labels = vision_tools::getObjectLabels(image_container_.get<ImageType::MotionMask>());
    auto inlier_iterator = dynamic_features_.beginUsable();
    for(const Feature::Ptr& dynamic_feature : inlier_iterator) {
        CHECK(!dynamic_feature->isStatic());
        CHECK(dynamic_feature->usable());
        const ObjectId instance_label = dynamic_feature->objectId();
        //this check is just for sanity!
        CHECK(std::find(instance_labels.begin(), instance_labels.end(), instance_label) != instance_labels.end())
            << "Missing " << instance_label << " in " << container_to_string(instance_labels);
        if(object_observations_.find(instance_label) == object_observations_.end()) {
            DynamicObjectObservation observation;
            observation.tracking_label_ = -1;
            observation.instance_label_ = instance_label;
            object_observations_[instance_label] = observation;
        }
        object_observations_[instance_label].object_features_.push_back(dynamic_feature->trackletId());
    }
    // now construct image masks from tracking mask
    // For each tracked object, find its id in the mask
    // and draw it.
    // We apply some eroding/dilation on it to make the resulting submask smoother
    // so that we can more easily fit an rectangle to it
    const cv::Mat& mask = image_container_.get<ImageType::MotionMask>();
    for(auto& object_observation_pair : object_observations_) {
        const ObjectId object_id = object_observation_pair.first;
        DynamicObjectObservation& obs = object_observation_pair.second;
        vision_tools::findObjectBoundingBox(mask, object_id, obs.bounding_box_);
    }
}
References dyno::FeatureContainer::beginUsable(), dyno::DynamicObjectObservation::bounding_box_, dyno::container_to_string(), dynamic_features_, dyno::vision_tools::findObjectBoundingBox(), dyno::ImageContainerSubset< ImageTypes >::get(), dyno::vision_tools::getObjectLabels(), image_container_, dyno::DynamicObjectObservation::instance_label_, object_observations_, and dyno::DynamicObjectObservation::tracking_label_.
Referenced by Frame().
drawDetectedObjectBoxes()
cv::Mat dyno::Frame::drawDetectedObjectBoxes () const
From the detected list of objects (in Frame::object_observations_) draw the object masks as labelled bounding boxes.
The function uses the MotionMask and RGBMono image types contained witin Frame::tracking_images_;
Returns
cv::Mat RGB image with drawn bounding boxes and labels
Definition at line 172 of file Frame.cc.
{
    cv::Mat rgb_objects;
    image_container_.cloneImage<ImageType::RGBMono>(rgb_objects);
    for(auto& object_observation_pair : object_observations_) {
        const ObjectId object_id = object_observation_pair.first;
        const cv::Rect& bb = object_observation_pair.second.bounding_box_;
        if(bb.empty()) { continue; }
        const cv::Scalar colour = Color::uniqueId(object_id).bgra();
        const std::string label = "Obj " + std::to_string(object_id);
        utils::drawLabeledBoundingBox(rgb_objects, label, colour, bb);
    }
    return rgb_objects;
}
References dyno::Color::bgra(), dyno::ImageContainerSubset< ImageTypes >::cloneImage(), dyno::utils::drawLabeledBoundingBox(), image_container_, object_observations_, and dyno::Color::uniqueId().
exists()
bool dyno::Frame::exists (TrackletId tracklet_id) const
Checks if a feature exists within this frame. Could be static or dynamic.
Parameters
tracklet_id TrackletId
Returns
true
false
Definition at line 61 of file Frame.cc.
{
    const bool result = static_features_.exists(tracklet_id) || dynamic_features_.exists(tracklet_id);
    //debug checking -> should only be in one feature container
    if(result) {
        CHECK(!(static_features_.exists(tracklet_id) &&  dynamic_features_.exists(tracklet_id)))
            << "Tracklet Id " <<  tracklet_id << " exists in both static and dynamic feature sets. Should be unique!";
    }
    return result;
}
References dynamic_features_, dyno::FeatureContainer::exists(), and static_features_.
Referenced by at().
getCamera()
const Camera::Ptr & dyno::Frame::getCamera () const inline
Definition at line 82 of file Frame.hpp.
{ return camera_; }
References camera_.
getCorrespondences() [1/2]
bool dyno::Frame::getCorrespondences (FeaturePairs & correspondences, const Frame & previous_frame, KeyPointType kp_type) const
Gets the set of tracked pairs between this frame and the previous frame. All correspondences will be usable (inliers). The correspondences will be in the form of feature pairs where first = feature in the previous frame and second = feature in this frame.
True is returned if the number of correspondences > 0
Parameters
correspondences FeaturePairs& vector of feature pairs
previous_frame const Frame&
kp_type KeyPointType
Returns
true
false
Definition at line 193 of file Frame.cc.
{
    if(kp_type == KeyPointType::STATIC) {
        return getStaticCorrespondences(correspondences, previous_frame);
    }
    else {
        return getDynamicCorrespondences(correspondences, previous_frame);
    }
}
References getDynamicCorrespondences(), getStaticCorrespondences(), and dyno::STATIC.
Referenced by getCorrespondences().
getCorrespondences() [2/2]
template<typename RefType , typename CurType > bool dyno::Frame::getCorrespondences (GenericCorrespondences< RefType, CurType > & correspondences, const Frame & previous_frame, KeyPointType kp_type, const ConstructCorrespondanceFunc< RefType, CurType > & func) const
Definition at line 32 of file Frame-inl.hpp.
{
    correspondences.clear();
    FeaturePairs feature_correspondences;
    const bool result = getCorrespondences(feature_correspondences, previous_frame, kp_type);
     if(!result) {
        return false;
    }
    for(const auto& pair : feature_correspondences) {
        const Feature::Ptr& prev_feature = pair.first;
        const Feature::Ptr& curr_feature = pair.second;
        CHECK(prev_feature);
        CHECK(curr_feature);
        CHECK_EQ(prev_feature->trackletId(), curr_feature->trackletId());
        CHECK_EQ(prev_feature->frameId(), previous_frame.getFrameId());
        CHECK_EQ(curr_feature->frameId(), getFrameId());
        correspondences.push_back(func(previous_frame, prev_feature, curr_feature));
    }
    return true;
}
References getCorrespondences(), and getFrameId().
getDynamicCorrespondences() [1/3]
bool dyno::Frame::getDynamicCorrespondences (FeaturePairs & correspondences, const Frame & previous_frame) const protected
Definition at line 319 of file Frame.cc.
{
    vision_tools::getCorrespondences(
        correspondences,
        previous_frame.dynamic_features_.beginUsable(),
        dynamic_features_.beginUsable()
    );
    return correspondences.size() > 0u;
}
References dyno::FeatureContainer::beginUsable(), dynamic_features_, and dyno::vision_tools::getCorrespondences().
getDynamicCorrespondences() [2/3]
bool dyno::Frame::getDynamicCorrespondences (FeaturePairs & correspondences, const Frame & previous_frame, ObjectId object_id) const
Gets the set of tracked pairs between this frame and the previous frame for a tracked dynamic object seen in both frames.
All correspondences will be usable (inliers). The correspondences will be in the form of feature pairs where first = feature in the previous frame and second = feature in this frame.
The object id is checked via the this frames Frame::object_observations_ map and is currently implemented as the object instance label (not tracking label).
True is returned if the number of correspondences > 0.
Parameters
correspondences FeaturePairs& vector of feature pairs
previous_frame const Frame&
object_id ObjectId
Returns
true
false
Definition at line 261 of file Frame.cc.
{
    if(object_observations_.find(object_id) == object_observations_.end()) {
        LOG(WARNING) << "Object object instance id " << object_id << " not found for frame " << frame_id_;
        return false;
    }
    // const DynamicObjectObservation& observation = object_observations_.at(object_id);
    // // TODO: need to put back on - if we have motion mask, we should just mark all objects as moving CHECK(observation.marked_as_moving_);
    // const TrackletIds& tracklets = observation.object_features_;
    // FeatureContainer feature_container;
    // for(const TrackletId tracklet : tracklets) {
    //     if(isFeatureUsable(tracklet)) {
    //         feature_container.add(this->at(tracklet));
    //     }
    // }
    auto current_dynamic_features_iterator = FeatureFilterIterator(
        const_cast<FeatureContainer&>(this->dynamic_features_),
        [object_id](const Feature::Ptr& f) -> bool {
            return Feature::IsUsable(f) && f->objectId() == object_id;
        });
    //make iterator for the previous dynamic features that ensure each feature is usable and has a matching instance label
    auto previous_dynamic_features_iterator = FeatureFilterIterator(
        const_cast<FeatureContainer&>(previous_frame.dynamic_features_),
        [object_id](const Feature::Ptr& f) -> bool {
            return Feature::IsUsable(f) && f->objectId() == object_id;
        });
    //get the correspondences from these two iterators
    //we iterate over the current feature container which should only contain features on the object
    //and compare against the container
    vision_tools::getCorrespondences(
        correspondences,
        previous_dynamic_features_iterator,
        //we iterate over the current feature container which should only contain features on the object
        current_dynamic_features_iterator
    );
    // LOG(INFO) << "Found " << correspondences.size() << " correspondences for object instance " << object_id << " " << (correspondences.size() > 0u);
    return correspondences.size() > 0u;
}
References dynamic_features_, frame_id_, dyno::vision_tools::getCorrespondences(), dyno::Feature::IsUsable(), and object_observations_.
Referenced by getCorrespondences(), and getDynamicCorrespondences().
getDynamicCorrespondences() [3/3]
template<typename RefType , typename CurType > bool dyno::Frame::getDynamicCorrespondences (GenericCorrespondences< RefType, CurType > & correspondences, const Frame & previous_frame, ObjectId object_id, const ConstructCorrespondanceFunc< RefType, CurType > & func) const
Definition at line 62 of file Frame-inl.hpp.
{
    FeaturePairs feature_correspondences;
    const bool result = getDynamicCorrespondences(feature_correspondences, previous_frame, object_id);
    if(!result) {
        return false;
    }
    //unncessary but just for sanity check
    for(const auto& feature_pairs : feature_correspondences) {
        const Feature::Ptr& prev_feature = feature_pairs.first;
        const Feature::Ptr& curr_feature = feature_pairs.second;
        CHECK_EQ(feature_pairs.first->objectId(), object_id);
        CHECK(feature_pairs.first->usable());
        CHECK_EQ(feature_pairs.second->objectId(), object_id);
        CHECK(feature_pairs.second->usable());
        CHECK_EQ(feature_pairs.second->trackletId(), feature_pairs.first->trackletId());
        correspondences.push_back(func(previous_frame, prev_feature, curr_feature));
    }
    return true;
}
References getDynamicCorrespondences().
getFrameCamera()
Camera::CameraImpl dyno::Frame::getFrameCamera () const
Constructs a GTSAM camera for this frame using the current pose of this camera (T_world_camera)
Returns
Camera::CameraImpl
Definition at line 143 of file Frame.cc.
{
    const CameraParams& camera_params = camera_->getParams();
    return Camera::CameraImpl(T_world_camera_, camera_params.constructGtsamCalibration<Camera::CalibrationType>());
}
References camera_, dyno::CameraParams::constructGtsamCalibration(), and T_world_camera_.
getFrameId()
FrameId dyno::Frame::getFrameId () const inline
Definition at line 80 of file Frame.hpp.
{ return frame_id_; }
References frame_id_.
Referenced by dyno::FeatureTrackerBase::computeImageTracks(), dyno::RGBDInstanceFrontendModule::constructOutput(), and getCorrespondences().
getLandmarkFromCache()
Landmark dyno::Frame::getLandmarkFromCache (LandmarkMap & cache, Feature::Ptr feature, const gtsam::Pose3 & X_world) const private
Definition at line 472 of file Frame.cc.
{
    //TODO: dont cache as we now update the optical flow and the depth in the frontend and cacheing it will not use the right values!!!
    // const auto& it = cache.find(feature->tracklet_id_);
    // if(it != cache.end()) {
    //     return it->second;
    // }
    Landmark lmk;
    camera_->backProject(feature->keypoint(), feature->depth(), &lmk, X_world);
    // cache.insert({feature->tracklet_id_, lmk});
    return lmk;
}
References camera_.
Referenced by backProjectToCamera(), and backProjectToWorld().
getObjectIds()
ObjectIds dyno::Frame::getObjectIds () const inline
Definition at line 222 of file Frame.hpp.
{
    ObjectIds object_ids;
    for (const auto& kv : object_observations_) {
      object_ids.push_back(kv.first);
    }
    return object_ids;
  }
References object_observations_.
getObjectObservations() [1/2]
std::map< ObjectId, DynamicObjectObservation > & dyno::Frame::getObjectObservations () inline
Definition at line 97 of file Frame.hpp.
{
    return object_observations_;
  }
References object_observations_.
getObjectObservations() [2/2]
const std::map< ObjectId, DynamicObjectObservation > & dyno::Frame::getObjectObservations () const inline
Definition at line 94 of file Frame.hpp.
{
    return object_observations_;
  }
References object_observations_.
getPose()
const gtsam::Pose3 & dyno::Frame::getPose () const inline
Returns the pose of the sensor at this frame w.r.t the world frame i.e ^wT_c such that a point, p measured in the camera frame can be put in the world frame using this pose e.g. ^wp = ^wT_c * ^cp.
Returns
const gtsam::Pose3&
Definition at line 91 of file Frame.hpp.
{ return T_world_camera_; }
References T_world_camera_.
getStaticCorrespondences()
bool dyno::Frame::getStaticCorrespondences (FeaturePairs & correspondences, const Frame & previous_frame) const protected
Definition at line 309 of file Frame.cc.
{
    vision_tools::getCorrespondences(
        correspondences,
        previous_frame.static_features_.beginUsable(),
        static_features_.beginUsable()
    );
    return correspondences.size() > 0u;
}
References dyno::FeatureContainer::beginUsable(), dyno::vision_tools::getCorrespondences(), and static_features_.
Referenced by getCorrespondences().
getTimestamp()
Timestamp dyno::Frame::getTimestamp () const inline
Definition at line 81 of file Frame.hpp.
{ return timestamp_; }
References timestamp_.
getTrackingInfo()
const std::optional< FeatureTrackerInfo > & dyno::Frame::getTrackingInfo () const inline
Definition at line 103 of file Frame.hpp.
{
    return tracking_info_;
  }
References tracking_info_.
imageKeypointCorrespondance()
Frame::ConstructCorrespondanceFunc< Keypoint, Keypoint > dyno::Frame::imageKeypointCorrespondance () const
Helper function that creates a ConstructCorrespondanceFunc which operates to return a TrackletCorrespondance where both types are keypoints (in the ref and cur frame respectively).
This is useful for 2D-2D correspondence types.
Returns
ConstructCorrespondanceFunc<Keypoint, Keypoint>
Definition at line 217 of file Frame.cc.
{
    auto func = [&](const Frame&, const Feature::Ptr& previous_feature, const Feature::Ptr& current_feature) {
        return TrackletCorrespondance(previous_feature->trackletId(), previous_feature->keypoint(), current_feature->keypoint());
    };
    return std::bind(func, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3);
}
isFeatureUsable()
bool dyno::Frame::isFeatureUsable (TrackletId tracklet_id) const
Returns true if the feature is usable (inlier). Throws std::runtime_error if the feature does not exist. Use in conjunction with Frame::exists.
Parameters
tracklet_id TrackletId
Returns
true
false
Definition at line 88 of file Frame.cc.
{
    const auto& feature = at(tracklet_id);
    if(!feature) {
        throw std::runtime_error("Failed to check feature usability - tracklet id " + std::to_string(tracklet_id) + " does not exist");
    }
    return feature->usable();
}
References at().
Referenced by dyno::RGBDInstanceFrontendModule::constructOutput().
landmarkWorldKeypointCorrespondance()
Frame::ConstructCorrespondanceFunc< Landmark, Keypoint > dyno::Frame::landmarkWorldKeypointCorrespondance () const
Helper function that creates a ConstructCorrespondanceFunc which operates to return a TrackletCorrespondance where the ref type is a Landmark in the world frame and the cur type is a Keypoint in the current frame.
This is useful for 3D-2D correspondence types.
Returns
ConstructCorrespondanceFunc<Landmark, Keypoint>
Definition at line 202 of file Frame.cc.
{
    auto func = [&](const Frame& previous_frame, const Feature::Ptr& previous_feature, const Feature::Ptr& current_feature) {
        if(!previous_feature->hasDepth()) {
            throw std::runtime_error("Error in constructing Landmark (w) -> keypoint correspondences - previous feature does not have depth!");
        }
        //eventuall map?
        Landmark lmk_w = previous_frame.backProjectToWorld(previous_feature->trackletId());
        return TrackletCorrespondance(previous_feature->trackletId(), lmk_w, current_feature->keypoint());
    };
    return std::bind(func, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3);
}
References backProjectToWorld().
landmarkWorldPointCloudCorrespondance()
Frame::ConstructCorrespondanceFunc< Landmark, Landmark > dyno::Frame::landmarkWorldPointCloudCorrespondance () const
Helper function ConstructCorrespondanceFunc which operates to return a TrackletCorrespondance where both types are Landmarks in the world frame (in the ref and cur frame respectively).
This is useful for 3D-3D correspondence types.
Returns
ConstructCorrespondanceFunc<Landmark, Landmark>
Definition at line 243 of file Frame.cc.
{
     auto func = [&](const Frame& previous_frame, const Feature::Ptr& previous_feature, const Feature::Ptr& current_feature) {
        if(!previous_feature->hasDepth()) {
            throw std::runtime_error("Error in constructing Landmark (w) -> keypoint correspondences - previous feature does not have depth!");
        }
        //eventuall map?
        Landmark lmk_w_k_1 = previous_frame.backProjectToWorld(previous_feature->trackletId());
        //eventuall map?
        Landmark lmk_w_k = backProjectToWorld(current_feature->trackletId());
        return TrackletCorrespondance(previous_feature->trackletId(), lmk_w_k_1, lmk_w_k);
    };
    return std::bind(func, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3);
}
References backProjectToWorld().
landmarkWorldProjectedBearingCorrespondance()
Frame::ConstructCorrespondanceFunc< Landmark, gtsam::Vector3 > dyno::Frame::landmarkWorldProjectedBearingCorrespondance () const
Helper function that creates a ConstructCorrespondanceFunc which operates to return a TrackletCorrespondance where the ref type is a Landmark in the world frame and the curr type is a normalized bearing vector constructed from the corresponding Keypoint in the current frame.
This is useful for 3D-2D correspondence types for the motion solver which expected correctly projected bearing vectors.
Returns
ConstructCorrespondanceFunc<Landmark, gtsam::Vector3>
Definition at line 226 of file Frame.cc.
{
    auto func = [&](const Frame& previous_frame, const Feature::Ptr& previous_feature, const Feature::Ptr& current_feature) {
        if(!previous_feature->hasDepth()) {
            throw std::runtime_error("Error in constructing Landmark (w) -> keypoint correspondences - previous feature does not have depth!");
        }
        //eventuall map?
        Landmark lmk_w = previous_frame.backProjectToWorld(previous_feature->trackletId());
        //TODO: what if image is already undistorted
        gtsam::Vector3 projected_versor = undistorter_->undistortKeypointAndGetProjectedVersor(current_feature->keypoint());
        return TrackletCorrespondance(previous_feature->trackletId(), lmk_w, projected_versor);
    };
    return std::bind(func, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3);
}
References backProjectToWorld(), and undistorter_.
moveObjectToStatic()
void dyno::Frame::moveObjectToStatic (ObjectId instance_label)
Definition at line 407 of file Frame.cc.
{
    auto it = object_observations_.find(instance_label);
    CHECK(it != object_observations_.end());
    DynamicObjectObservation& observation = it->second;
    observation.marked_as_moving_ = false;
    CHECK(observation.instance_label_ == instance_label);
    //go through all features, move them to from dynamic structure and add them to static
    for(TrackletId tracklet_id : observation.object_features_) {
        CHECK(dynamic_features_.exists(tracklet_id));
        Feature::Ptr dynamic_feature = dynamic_features_.getByTrackletId(tracklet_id);
        if(!dynamic_feature->usable()) {continue;}
        CHECK(!dynamic_feature->isStatic());
        CHECK_EQ(dynamic_feature->trackletId(), tracklet_id);
        CHECK_EQ(dynamic_feature->objectId(), instance_label);
        dynamic_feature->keypointType(KeyPointType::STATIC);
        dynamic_feature->objectId(background_label);
        // dynamic_feature->tracking_label_ = background_label;
        dynamic_features_.remove(tracklet_id);
        //Jesse: no, do not move points (these are dense) to static - instrad we need to mark the AREA
        //around the object as static and then retrack all points in there!!
        // static_features_.add(dynamic_feature);
    }
    object_observations_.erase(it);
}
References dyno::background_label, dynamic_features_, dyno::FeatureContainer::exists(), dyno::FeatureContainer::getByTrackletId(), dyno::DynamicObjectObservation::instance_label_, dyno::DynamicObjectObservation::marked_as_moving_, dyno::DynamicObjectObservation::object_features_, object_observations_, dyno::FeatureContainer::remove(), and dyno::STATIC.
numDynamicFeatures()
size_t dyno::Frame::numDynamicFeatures () const inline
Gets the total number of dynamic features observed at this frame. Includes usables (inliers) and outliers.
Returns
size_t
Definition at line 133 of file Frame.hpp.
{ return dynamic_features_.size(); }
References dynamic_features_, and dyno::FeatureContainer::size().
Referenced by numTotalFeatures().
numDynamicUsableFeatures()
size_t dyno::Frame::numDynamicUsableFeatures () inline
Gets the total number of dynamic inlier features.
Returns
size_t
Definition at line 140 of file Frame.hpp.
{
    auto iter = usableDynamicFeaturesBegin();
    return static_cast<size_t>(std::distance(iter.begin(), iter.end()));
  }
References usableDynamicFeaturesBegin().
numStaticFeatures()
size_t dyno::Frame::numStaticFeatures () const inline
Gets the total number of static features observed at this frame. Includes usables (inliers) and outliers.
Returns
size_t
Definition at line 113 of file Frame.hpp.
{ return static_features_.size(); }
References dyno::FeatureContainer::size(), and static_features_.
Referenced by numTotalFeatures().
numStaticUsableFeatures()
size_t dyno::Frame::numStaticUsableFeatures () inline
Gets the total number of static inlier features.
Returns
size_t
Definition at line 120 of file Frame.hpp.
{
    auto iter = usableStaticFeaturesBegin();
    // we have defined the std::distance operator for this iterator type using
    // std::iterator_traits.
    return static_cast<size_t>(std::distance(iter.begin(), iter.end()));
  }
References usableStaticFeaturesBegin().
numTotalFeatures()
size_t dyno::Frame::numTotalFeatures () const inline
Gets the total number of features (static + dynamic) in this frame. Includes usables (inliers) and outliers.
Returns
size_t
Definition at line 151 of file Frame.hpp.
{
    return numStaticFeatures() + numDynamicFeatures();
  }
References numDynamicFeatures(), and numStaticFeatures().
setMaxBackgroundDepth()
Frame & dyno::Frame::setMaxBackgroundDepth (double thresh)
Definition at line 159 of file Frame.cc.
{
    CHECK_GT(thresh, 0);
    max_background_threshold_ = thresh;
    return *this;
}
References max_background_threshold_.
setMaxObjectDepth()
Frame & dyno::Frame::setMaxObjectDepth (double thresh)
Definition at line 165 of file Frame.cc.
{
    CHECK_GT(thresh, 0);
    max_object_threshold_ = thresh;
    return *this;
}
References max_object_threshold_.
updateDepths()
bool dyno::Frame::updateDepths ()
Update the depth values on all contained features. Clips the static and dynamic features (marking them invalid) accordingly.
Returns false if the internal image container does not have a depth mat.
Returns
true
false
Definition at line 148 of file Frame.cc.
{
    if(!image_container_.hasDepth()) {
        return false;
    }
    const ImageWrapper<ImageType::Depth>& depth = image_container_.getImageWrapper<ImageType::Depth>();
    updateDepthsFeatureContainer(static_features_, depth, max_background_threshold_);
    updateDepthsFeatureContainer(dynamic_features_, depth, max_object_threshold_);
    return true;
}
References dynamic_features_, dyno::ImageContainerSubset< ImageTypes >::getImageWrapper(), dyno::ImageContainer::hasDepth(), image_container_, max_background_threshold_, max_object_threshold_, static_features_, and updateDepthsFeatureContainer().
updateDepthsFeatureContainer()
void dyno::Frame::updateDepthsFeatureContainer (FeatureContainer & container, const ImageWrapper< ImageType::Depth > & depth, double max_depth) static private
Definition at line 329 of file Frame.cc.
{
    // auto iter = container.beginUsable();
    // auto iter = container.begin();
    int count = 0;
    //iterate over all features
    for(Feature::Ptr feature : container) {
        // CHECK(feature->usable());
        // const Feature::Ptr& feature = *iter;
        // const int x = functional_keypoint::u(feature->keypoint_);
        // const int y = functional_keypoint::v(feature->keypoint_);
        // const Depth d = depth_mat.at<Depth>(y, x);
        const Depth d = functional_keypoint::at<Depth>(feature->keypoint(), depth);
        if(d > max_depth || d <= 0) {
            feature->markInvalid();
            feature->depth(Feature::invalid_depth);
            count++;
        }
        else {
            feature->depth(d);
        }
        //  //if now invalid or happens to be invalid from a previous frame, make depth invalid too
        // if(!feature->usable()) {
        //     feature->depth_ = Feature::invalid_depth;
        // }
        // else {
        //     feature->depth_ = d;
        // }
    }
    // LOG(INFO) << count << " features marked invalud due to depth out of " << container.size() << " with max depth " << max_depth;
}
References dyno::Feature::invalid_depth.
Referenced by updateDepths().
updateObjectTrackingLabel()
void dyno::Frame::updateObjectTrackingLabel (const DynamicObjectObservation & observation, ObjectId new_tracking_label)
Definition at line 439 of file Frame.cc.
{
    auto it = object_observations_.find(observation.instance_label_);
    CHECK(it != object_observations_.end());
    auto& obs = it->second;
    obs.tracking_label_ = new_tracking_label;
    //update all features
    for(TrackletId tracklet_id : obs.object_features_) {
        Feature::Ptr feature = dynamic_features_.getByTrackletId(tracklet_id);
        CHECK(feature);
        feature->objectId(new_tracking_label);
    }
}
References dynamic_features_, dyno::FeatureContainer::getByTrackletId(), dyno::DynamicObjectObservation::instance_label_, and object_observations_.
usableDynamicFeaturesBegin() [1/2]
FeatureFilterIterator dyno::Frame::usableDynamicFeaturesBegin ()
Definition at line 462 of file Frame.cc.
{
    return dynamic_features_.beginUsable();
}
References dyno::FeatureContainer::beginUsable(), and dynamic_features_.
Referenced by numDynamicUsableFeatures().
usableDynamicFeaturesBegin() [2/2]
FeatureFilterIterator dyno::Frame::usableDynamicFeaturesBegin () const
Definition at line 466 of file Frame.cc.
{
    return dynamic_features_.beginUsable();
}
References dyno::FeatureContainer::beginUsable(), and dynamic_features_.
usableStaticFeaturesBegin() [1/2]
FeatureFilterIterator dyno::Frame::usableStaticFeaturesBegin ()
Definition at line 454 of file Frame.cc.
{
    return static_features_.beginUsable();
}
References dyno::FeatureContainer::beginUsable(), and static_features_.
Referenced by dyno::RGBDInstanceFrontendModule::constructOutput(), and numStaticUsableFeatures().
usableStaticFeaturesBegin() [2/2]
FeatureFilterIterator dyno::Frame::usableStaticFeaturesBegin () const
Definition at line 458 of file Frame.cc.
{
    return static_features_.beginUsable();
}
References dyno::FeatureContainer::beginUsable(), and static_features_.
Member Data Documentation
camera_
Camera::Ptr dyno::Frame::camera_
Definition at line 51 of file Frame.hpp.
Referenced by getCamera(), getFrameCamera(), and getLandmarkFromCache().
dynamic_features_
FeatureContainer dyno::Frame::dynamic_features_
Definition at line 57 of file Frame.hpp.
Referenced by at(), dyno::FeatureTrackerBase::computeImageTracks(), constructDynamicObservations(), exists(), getDynamicCorrespondences(), moveObjectToStatic(), numDynamicFeatures(), dyno::vision_tools::trackDynamic(), updateDepths(), updateObjectTrackingLabel(), and usableDynamicFeaturesBegin().
frame_id_
const FrameId dyno::Frame::frame_id_
Definition at line 49 of file Frame.hpp.
Referenced by dyno::RGBDInstanceFrontendModule::constructOutput(), getDynamicCorrespondences(), and getFrameId().
global_object_id
ObjectId dyno::Frame::global_object_id {1} static
Depricate as unused!
information from the tracker that was used to created this frame
Definition at line 64 of file Frame.hpp.
image_container_
const ImageContainer dyno::Frame::image_container_
Definition at line 52 of file Frame.hpp.
Referenced by dyno::FeatureTrackerBase::computeImageTracks(), constructDynamicObservations(), drawDetectedObjectBoxes(), and updateDepths().
landmark_in_camera_cache_
LandmarkMap dyno::Frame::landmark_in_camera_cache_ mutable private
cached projections of each landmark depending on the frame to save speed Based off the initial 2d observation and depth from the feature
Definition at line 420 of file Frame.hpp.
Referenced by backProjectToCamera().
landmark_in_world_cache_
LandmarkMap dyno::Frame::landmark_in_world_cache_ mutable private
Definition at line 421 of file Frame.hpp.
Referenced by backProjectToWorld().
max_background_threshold_
double dyno::Frame::max_background_threshold_ = 40.0 private
Background points greater than this depth will be discarded.
Definition at line 424 of file Frame.hpp.
Referenced by setMaxBackgroundDepth(), and updateDepths().
max_object_threshold_
double dyno::Frame::max_object_threshold_ = 25.0 private
Definition at line 426 of file Frame.hpp.
Referenced by setMaxObjectDepth(), and updateDepths().
motion_estimates_
MotionEstimateMap dyno::Frame::motion_estimates_
Definition at line 70 of file Frame.hpp.
object_observations_
std::map<ObjectId, DynamicObjectObservation> dyno::Frame::object_observations_
Definition at line 68 of file Frame.hpp.
Referenced by dyno::FeatureTrackerBase::computeImageTracks(), constructDynamicObservations(), dyno::RGBDInstanceFrontendModule::constructOutput(), drawDetectedObjectBoxes(), getDynamicCorrespondences(), getObjectIds(), getObjectObservations(), moveObjectToStatic(), and updateObjectTrackingLabel().
static_features_
FeatureContainer dyno::Frame::static_features_
Definition at line 56 of file Frame.hpp.
Referenced by at(), dyno::FeatureTrackerBase::computeImageTracks(), exists(), getStaticCorrespondences(), numStaticFeatures(), updateDepths(), and usableStaticFeaturesBegin().
T_world_camera_
gtsam::Pose3 dyno::Frame::T_world_camera_ = gtsam::Pose3::Identity()
Definition at line 54 of file Frame.hpp.
Referenced by backProjectToWorld(), getFrameCamera(), and getPose().
timestamp_
const Timestamp dyno::Frame::timestamp_
Definition at line 50 of file Frame.hpp.
Referenced by dyno::RGBDInstanceFrontendModule::constructOutput(), and getTimestamp().
tracking_info_
std::optional<FeatureTrackerInfo> dyno::Frame::tracking_info_
Definition at line 60 of file Frame.hpp.
Referenced by getTrackingInfo().
undistorter_
UndistorterRectifier::Ptr dyno::Frame::undistorter_ private
Definition at line 416 of file Frame.hpp.
Referenced by Frame(), and landmarkWorldProjectedBearingCorrespondance().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/frontend/vision/Frame.hpp
dynosam/include/dynosam/frontend/vision/Frame-inl.hpp
dynosam/src/frontend/vision/Frame.cc