DynoSAM: dyno::DataInterfacePipelineImu Class Reference
dyno::DataInterfacePipelineImu Class Reference
#include <DataInterfacePipeline.hpp>
Public Member Functions
DataInterfacePipelineImu (const std::string &module_name)
virtual void fillImuQueue (const ImuMeasurements &imu_measurements)
virtual void fillImuQueue (const ImuMeasurement &imu_measurement)
Public Member Functions inherited from dyno::DataInterfacePipeline
DataInterfacePipeline (bool parallel_run=false)
virtual ~DataInterfacePipeline ()=default
virtual FrontendInputPacketBase::ConstPtr getInputPacket () override
virtual void fillImageContainerQueue (ImageContainer::Ptr image_container)
virtual void addGroundTruthPacket (const GroundTruthInputPacket &gt_packet)
virtual void registerImageContainerPreprocessor (const ImageContainerPreprocesser &func)
Public Member Functions inherited from dyno::MIMOPipelineModule< FrontendInputPacketBase, FrontendInputPacketBase >
MIMOPipelineModule (const std::string &module_name)
void registerOutputQueue (OutputQueue *output_queue)
OutputRegistra::Ptr getOutputRegistra ()
Constructs an output registra for the internal vector of output queues Basically provides a way to add queues to the pipeline separate to the pipeline itself. This is useful as the registra is only templated on the OUTPUT so we can simply any external templating which only concerns itself with output types.
Public Member Functions inherited from dyno::PipelineModule< INPUT, OUTPUT >
PipelineModule (const std::string &module_name)
virtual ~PipelineModule ()=default
PipelineBase::ReturnCode spinOnce () override
Spin the pipeline once.
void registerOnProcessCallback (const OnProcessCallback &callback)
Registers a function that will be called with the input and output data packets generated from a spinOnce() call.
Public Member Functions inherited from dyno::PipelineBase
PipelineBase (const std::string &module_name)
virtual ~PipelineBase ()=default
bool spin ()
Spins the pipeline via continuous calls to spinOnce until the pipeline is shutdown.
bool isWorking () const
Returns true if the pipeline is currently processing data or if these is still data to process. Checks is_thread_working_ and the overwritten hasWork() function.
bool isShutdown () const
Returns true if the pipeline has been shutdown by shutdown().
std::string getModuleName () const
Returns the given module name (for identifcation and debug printing)
virtual void shutdown ()
void registerOnFailureCallback (const OnPipelineFailureCallback &callback_)
Registers a callback to be triggered if spinOnce returns an invalid return code.
virtual void shutdownQueues ()=0
Virtual function that should shutdown all associated queues. Generally this should shutdown input queues.
virtual bool hasWork () const =0
Virtual function that should check if (any of the) input queues have work to do.
virtual ReturnCode spinOnce ()=0
Processes for one iteration of the pipeline.
Protected Member Functions
bool getTimeSyncedImuMeasurements (const Timestamp &timestamp, ImuMeasurements *imu_meas)
getTimeSyncedImuMeasurements Time synchronizes the IMU buffer with the given timestamp (this is typically the timestamp of a left img)
Protected Member Functions inherited from dyno::DataInterfacePipeline
virtual void onShutdown ()
Protected Member Functions inherited from dyno::MIMOPipelineModule< FrontendInputPacketBase, FrontendInputPacketBase >
bool pushOutputPacket (const OutputConstSharedPtr &output_packet) const override
virtual InputConstSharedPtr getInputPacket ()=0
virtual OutputConstSharedPtr process (const InputConstSharedPtr &input)=0
virtual bool pushOutputPacket (const OutputConstSharedPtr &output_packet) const =0
Private Attributes
ThreadsafeImuBuffer imu_buffer_
Timestamp timestamp_last_sync_ {0}
Additional Inherited Members
Public Types inherited from dyno::DataInterfacePipeline
using MIMO = MIMOPipelineModule< FrontendInputPacketBase, FrontendInputPacketBase >
using OutputQueue = typename MIMO::OutputQueue
using ImageContainerPreprocesser = std::function< ImageContainer::Ptr(ImageContainer::Ptr)>
Public Types inherited from dyno::MIMOPipelineModule< FrontendInputPacketBase, FrontendInputPacketBase >
using Base = PipelineModule< FrontendInputPacketBase, FrontendInputPacketBase >
using This = MIMOPipelineModule< FrontendInputPacketBase, FrontendInputPacketBase >
using OutputRegistra = QueueRegistra< FrontendInputPacketBase >
using OutputCallback = std::function< void(const OutputConstSharedPtr &output)>
using OutputConstSharedPtr = typename OutputTypeTraits::TypeConstSharedPtr
The output is instead a shared ptr, since many users might need the output.
using InputConstSharedPtr = typename InputTypeTraits::TypeConstSharedPtr
using InputQueue = typename InputTypeTraits::TypeQueue
using OutputQueue = typename OutputTypeTraits::TypeQueue
Public Types inherited from dyno::PipelineModule< INPUT, OUTPUT >
using InputTypeTraits = PipelineTypeTraits< INPUT >
using OutputTypeTraits = PipelineTypeTraits< OUTPUT >
using InputConstSharedPtr = typename InputTypeTraits::TypeConstSharedPtr
using OutputConstSharedPtr = typename OutputTypeTraits::TypeConstSharedPtr
The output is instead a shared ptr, since many users might need the output.
using InputQueue = typename InputTypeTraits::TypeQueue
using OutputQueue = typename OutputTypeTraits::TypeQueue
using OnProcessCallback = std::function< void(const InputConstSharedPtr &, const OutputConstSharedPtr &)>
Public Types inherited from dyno::PipelineBase
using OnPipelineFailureCallback = std::function< void(ReturnCode)>
Protected Attributes inherited from dyno::DataInterfacePipeline
ThreadsafeQueue< ImageContainer::Ptr > packet_queue_
std::atomic_bool parallel_run_
std::map< FrameId, GroundTruthInputPacket > ground_truth_packets_
ImageContainerPreprocesser image_container_preprocessor_
Protected Attributes inherited from dyno::PipelineBase
const std::string module_name_
std::atomic_bool is_thread_working_ { false }
Detailed Description
Definition at line 87 of file DataInterfacePipeline.hpp.
Constructor & Destructor Documentation
DataInterfacePipelineImu()
dyno::DataInterfacePipelineImu::DataInterfacePipelineImu (const std::string & module_name)
Member Function Documentation
fillImuQueue() [1/2]
virtual void dyno::DataInterfacePipelineImu::fillImuQueue (const ImuMeasurement & imu_measurement) inline virtual
Definition at line 97 of file DataInterfacePipeline.hpp.
{
        imu_buffer_.addMeasurement(imu_measurement.timestamp_,
                                            imu_measurement.acc_gyr_);
    }
References dyno::ImuMeasurement::acc_gyr_, dyno::ThreadsafeImuBuffer::addMeasurement(), imu_buffer_, and dyno::ImuMeasurement::timestamp_.
fillImuQueue() [2/2]
virtual void dyno::DataInterfacePipelineImu::fillImuQueue (const ImuMeasurements & imu_measurements) inline virtual
Definition at line 92 of file DataInterfacePipeline.hpp.
{
        imu_buffer_.addMeasurements(imu_measurements.timestamps_,
                                            imu_measurements.acc_gyr_);
    }
References dyno::ImuMeasurements::acc_gyr_, dyno::ThreadsafeImuBuffer::addMeasurements(), imu_buffer_, and dyno::ImuMeasurements::timestamps_.
Referenced by dyno::DataProvider::DataProvider().
getTimeSyncedImuMeasurements()
bool dyno::DataInterfacePipelineImu::getTimeSyncedImuMeasurements (const Timestamp & timestamp, ImuMeasurements * imu_meas) protected
getTimeSyncedImuMeasurements Time synchronizes the IMU buffer with the given timestamp (this is typically the timestamp of a left img)
False if synchronization failed, true otherwise.
Parameters
timestamp const Timestamp& for the IMU data to query
imu_meas ImuMeasurements* IMU measurements to be populated and returned
Returns
true
false
Definition at line 89 of file DataInterfacePipeline.cc.
{
  CHECK_NOTNULL(imu_meas);
  CHECK_LT(timestamp_last_sync_, timestamp)
      << "Timestamps out of order:\n"
      << " - Last Frame Timestamp = " << timestamp_last_sync_ << '\n'
      << " - Current Timestamp = " << timestamp;
  if (imu_buffer_.size() == 0) {
    VLOG(1) << "No IMU measurements available yet, dropping this frame.";
    return false;
  }
  // Extract imu measurements between consecutive frames.
  if (dyno::fpEqual(timestamp_last_sync_, 0.0)) {
    // TODO(Toni): wouldn't it be better to get all IMU measurements up to
    // this
    // timestamp? We should add a method to the IMU buffer for that.
    VLOG(1) << "Skipping first frame, because we do not have a concept of "
               "a previous frame timestamp otherwise.";
    timestamp_last_sync_ = timestamp;
    return false;
  }
  ThreadsafeImuBuffer::QueryResult query_result =
      ThreadsafeImuBuffer::QueryResult::kDataNeverAvailable;
  bool log_error_once = true;
  while (!MIMO::isShutdown() &&
         (query_result = imu_buffer_.getImuDataInterpolatedUpperBorder(
              timestamp_last_sync_, timestamp, &imu_meas->timestamps_,
              &imu_meas->acc_gyr_)) !=
             ThreadsafeImuBuffer::QueryResult::kDataAvailable) {
    VLOG(1) << "No IMU data available. Reason:\n";
    switch (query_result) {
      case ThreadsafeImuBuffer::QueryResult::kDataNotYetAvailable: {
        if (log_error_once) {
          LOG(WARNING) << "Waiting for IMU data...";
          log_error_once = false;
        }
        continue;
      }
      case ThreadsafeImuBuffer::QueryResult::kQueueShutdown: {
        LOG(WARNING)
            << "IMU buffer was shutdown. Shutting down DataInterfacePipeline.";
        MIMO::shutdown();
        return false;
      }
      case ThreadsafeImuBuffer::QueryResult::kDataNeverAvailable: {
        LOG(WARNING)
            << "Asking for data before start of IMU stream, from timestamp: "
            << timestamp_last_sync_ << " to timestamp: " << timestamp;
        // Ignore frames that happened before the earliest imu data
        timestamp_last_sync_ = timestamp;
        return false;
      }
      case ThreadsafeImuBuffer::QueryResult::kTooFewMeasurementsAvailable: {
        LOG(WARNING) << "No IMU measurements here, and IMU data stream already "
                        "passed this time region"
                     << "from timestamp: " << timestamp_last_sync_
                     << " to timestamp: " << timestamp;
        return false;
      }
      case ThreadsafeImuBuffer::QueryResult::kDataAvailable: {
        LOG(FATAL) << "We should not be inside this while loop if IMU data is "
                      "available...";
        return false;
      }
    }
  }
  timestamp_last_sync_ = timestamp;
  VLOG(10) << "////////////////////////////////////////// Creating packet!\n"
           << "STAMPS IMU rows : \n"
           << imu_meas->timestamps_.rows() << '\n'
           << "STAMPS IMU cols : \n"
           << imu_meas->timestamps_.cols() << '\n'
           << "STAMPS IMU: \n"
           << imu_meas->timestamps_ << '\n'
           << "ACCGYR IMU rows : \n"
           << imu_meas->acc_gyr_.rows() << '\n'
           << "ACCGYR IMU cols : \n"
           << imu_meas->acc_gyr_.cols() << '\n'
           << "ACCGYR IMU: \n"
           << imu_meas->acc_gyr_;
  return true;
}
References dyno::ImuMeasurements::acc_gyr_, dyno::fpEqual(), dyno::ThreadsafeImuBuffer::getImuDataInterpolatedUpperBorder(), imu_buffer_, dyno::PipelineBase::isShutdown(), dyno::ThreadsafeImuBuffer::kDataAvailable, dyno::ThreadsafeImuBuffer::kDataNeverAvailable, dyno::ThreadsafeImuBuffer::kDataNotYetAvailable, dyno::ThreadsafeImuBuffer::kQueueShutdown, dyno::ThreadsafeImuBuffer::kTooFewMeasurementsAvailable, dyno::PipelineBase::shutdown(), dyno::ThreadsafeImuBuffer::size(), timestamp_last_sync_, and dyno::ImuMeasurements::timestamps_.
Member Data Documentation
imu_buffer_
ThreadsafeImuBuffer dyno::DataInterfacePipelineImu::imu_buffer_ private
Definition at line 118 of file DataInterfacePipeline.hpp.
Referenced by fillImuQueue(), and getTimeSyncedImuMeasurements().
timestamp_last_sync_
Timestamp dyno::DataInterfacePipelineImu::timestamp_last_sync_ {0} private
Definition at line 120 of file DataInterfacePipeline.hpp.
Referenced by getTimeSyncedImuMeasurements().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/dataprovider/DataInterfacePipeline.hpp
dynosam/src/dataprovider/DataInterfacePipeline.cc