DynoSAM: dyno::BackendModuleType< MODULE_TRAITS > Class Template Reference
dyno::BackendModuleType< MODULE_TRAITS > Class Template Reference abstract
#include <BackendModule.hpp>
Public Types
using ModuleTraits = MODULE_TRAITS
using DerivedPacketType = typename ModuleTraits::DerivedPacketType
using DerivedPacketTypeConstPtr = typename ModuleTraits::DerivedPacketTypeConstPtr
using MeasurementType = typename ModuleTraits::MeasurementType
using This = BackendModuleType< ModuleTraits >
using Base = BackendModule
using MapType = typename ModuleTraits::MapType
using FormulationType = Formulation< MapType >
using InputConstPtr = DerivedPacketTypeConstPtr
using OutputConstPtr = Base::OutputConstPtr
Public Types inherited from dyno::BackendModule
using Base = ModuleBase< BackendInputPacket, BackendOutputPacket >
Public Types inherited from dyno::ModuleBase< BackendInputPacket, BackendOutputPacket >
enum State
using Input = BackendInputPacket
using Output = BackendOutputPacket
using InputConstPtr = typename INPUT::ConstPtr
using OutputConstPtr = typename OUTPUT::ConstPtr
ConstPtr to an INPUT type.
using This = ModuleBase< BackendInputPacket, BackendOutputPacket >
ConstPtr to an OUTPUT type.
using SpinReturn = std::pair< State, OutputConstPtr >
using InputCallback = std::function< void(InputConstPtr)>
using OutputCallback = std::function< void(OutputConstPtr)>
Public Member Functions
BackendModuleType (const BackendParams &params, ImageDisplayQueue *display_queue)
virtual ~BackendModuleType ()
const MapType::Ptr getMap ()
virtual std::pair< gtsam::Values, gtsam::NonlinearFactorGraph > getActiveOptimisation () const =0
Public Member Functions inherited from dyno::BackendModule
BackendModule (const BackendParams &params, ImageDisplayQueue *display_queue)
virtual ~BackendModule ()=default
const BackendParams & getParams () const
const NoiseModels & getNoiseModels () const
const BackendSpinState & getSpinState () const
virtual Accessor::Ptr getAccessor ()=0
Get the accessor the the underlying formulation, allowing the optimised values to be directly accessed.
void registerFrontendUpdateInterface (const FrontendUpdateInterface &cb)
Public Member Functions inherited from dyno::ModuleBase< BackendInputPacket, BackendOutputPacket >
ModuleBase (const std::string &name)
virtual ~ModuleBase ()=default
OutputConstPtr spinOnce (InputConstPtr input)
void registerInputCallback (const InputCallback &input_callback)
Registeres a function callback to be triggered prior to nominal/bootstrapSpin being called.
void registerOutputCallback (const OutputCallback &output_callback)
Registeres a function callback to be triggered after nominal/bootstrapSpin is called.
Protected Member Functions
virtual SpinReturn boostrapSpinImpl (InputConstPtr input)=0
virtual SpinReturn nominalSpinImpl (InputConstPtr input)=0
Protected Member Functions inherited from dyno::BackendModule
virtual void validateInput (const BackendInputPacket::ConstPtr &input) const override
void setFactorParams (const BackendParams &backend_params)
Protected Member Functions inherited from dyno::ModuleBase< BackendInputPacket, BackendOutputPacket >
virtual void validateInput (const InputConstPtr &input) const=0
Checks the state of the input before running any virtual spin (boostrap or nominal) functions.
virtual SpinReturn boostrapSpin (InputConstPtr input)=0
virtual SpinReturn nominalSpin (InputConstPtr input)=0
Protected Attributes
MapType::Ptr map_
Protected Attributes inherited from dyno::BackendModule
const BackendParams base_params_
ImageDisplayQueue * display_queue_ {nullptr}
BackendSpinState spin_state_
Optional display queue.
NoiseModels noise_models_
FrontendUpdateInterface frontend_update_callback_
Private Member Functions
SpinReturn boostrapSpin (Base::BaseInputConstPtr base_input) override
SpinReturn nominalSpin (Base::BaseInputConstPtr base_input) override
DerivedPacketTypeConstPtr attemptCast (Base::BaseInputConstPtr base_input)
Additional Inherited Members
Public Attributes inherited from dyno::SharedModuleInterface
SharedModuleInfo & shared_module_info = SharedModuleInfo::instance()
Protected Types inherited from dyno::BackendModule
using BaseInputConstPtr = Base::InputConstPtr
using BaseInput = Base::Input
Detailed Description
template<class MODULE_TRAITS>
class dyno::BackendModuleType< MODULE_TRAITS >
Definition at line 130 of file BackendModule.hpp.
Member Typedef Documentation
Base
template<class MODULE_TRAITS > using dyno::BackendModuleType< MODULE_TRAITS >::Base = BackendModule
Definition at line 139 of file BackendModule.hpp.
DerivedPacketType
template<class MODULE_TRAITS > using dyno::BackendModuleType< MODULE_TRAITS >::DerivedPacketType = typename ModuleTraits::DerivedPacketType
Definition at line 134 of file BackendModule.hpp.
DerivedPacketTypeConstPtr
template<class MODULE_TRAITS > using dyno::BackendModuleType< MODULE_TRAITS >::DerivedPacketTypeConstPtr = typename ModuleTraits::DerivedPacketTypeConstPtr
Definition at line 135 of file BackendModule.hpp.
FormulationType
template<class MODULE_TRAITS > using dyno::BackendModuleType< MODULE_TRAITS >::FormulationType = Formulation<MapType>
Definition at line 142 of file BackendModule.hpp.
InputConstPtr
template<class MODULE_TRAITS > using dyno::BackendModuleType< MODULE_TRAITS >::InputConstPtr = DerivedPacketTypeConstPtr
Definition at line 151 of file BackendModule.hpp.
MapType
template<class MODULE_TRAITS > using dyno::BackendModuleType< MODULE_TRAITS >::MapType = typename ModuleTraits::MapType
Definition at line 141 of file BackendModule.hpp.
MeasurementType
template<class MODULE_TRAITS > using dyno::BackendModuleType< MODULE_TRAITS >::MeasurementType = typename ModuleTraits::MeasurementType
Definition at line 137 of file BackendModule.hpp.
ModuleTraits
template<class MODULE_TRAITS > using dyno::BackendModuleType< MODULE_TRAITS >::ModuleTraits = MODULE_TRAITS
Definition at line 132 of file BackendModule.hpp.
OutputConstPtr
template<class MODULE_TRAITS > using dyno::BackendModuleType< MODULE_TRAITS >::OutputConstPtr = Base::OutputConstPtr
Definition at line 152 of file BackendModule.hpp.
This
template<class MODULE_TRAITS > using dyno::BackendModuleType< MODULE_TRAITS >::This = BackendModuleType<ModuleTraits>
Definition at line 138 of file BackendModule.hpp.
Constructor & Destructor Documentation
BackendModuleType()
template<class MODULE_TRAITS > dyno::BackendModuleType< MODULE_TRAITS >::BackendModuleType (const BackendParams & params, ImageDisplayQueue * display_queue) inline
Definition at line 154 of file BackendModule.hpp.
      : Base(params, display_queue), map_(MapType::create()) {}
~BackendModuleType()
template<class MODULE_TRAITS > virtual dyno::BackendModuleType< MODULE_TRAITS >::~BackendModuleType () inline virtual
Definition at line 158 of file BackendModule.hpp.
{}
Member Function Documentation
attemptCast()
template<class MODULE_TRAITS > DerivedPacketTypeConstPtr dyno::BackendModuleType< MODULE_TRAITS >::attemptCast (Base::BaseInputConstPtr base_input) inline private
Definition at line 180 of file BackendModule.hpp.
{
    DerivedPacketTypeConstPtr deriverd_input =
        safeCast<Base::BaseInput, DerivedPacketType>(base_input);
    checkAndThrow((bool)deriverd_input,
                  "Failed to cast " + type_name<Base::BaseInput>() + " to " +
                      type_name<DerivedPacketType>() + " in BackendModuleType");
    return deriverd_input;
  }
References dyno::checkAndThrow().
Referenced by dyno::BackendModuleType< MODULE_TRAITS >::boostrapSpin(), and dyno::BackendModuleType< MODULE_TRAITS >::nominalSpin().
boostrapSpin()
template<class MODULE_TRAITS > SpinReturn dyno::BackendModuleType< MODULE_TRAITS >::boostrapSpin (Base::BaseInputConstPtr base_input) inline override private virtual
Implements dyno::ModuleBase< BackendInputPacket, BackendOutputPacket >.
Definition at line 172 of file BackendModule.hpp.
{
    return boostrapSpinImpl(attemptCast(base_input));
  }
References dyno::BackendModuleType< MODULE_TRAITS >::attemptCast(), and dyno::BackendModuleType< MODULE_TRAITS >::boostrapSpinImpl().
boostrapSpinImpl()
template<class MODULE_TRAITS > virtual SpinReturn dyno::BackendModuleType< MODULE_TRAITS >::boostrapSpinImpl (InputConstPtr input) protected pure virtual
Referenced by dyno::BackendModuleType< MODULE_TRAITS >::boostrapSpin().
getActiveOptimisation()
template<class MODULE_TRAITS > virtual std::pair< gtsam::Values, gtsam::NonlinearFactorGraph > dyno::BackendModuleType< MODULE_TRAITS >::getActiveOptimisation () const pure virtual
Implemented in dyno::ParallelHybridBackendModule, and dyno::RegularBackendModule.
getMap()
template<class MODULE_TRAITS > const MapType::Ptr dyno::BackendModuleType< MODULE_TRAITS >::getMap () inline
Definition at line 160 of file BackendModule.hpp.
{ return map_; }
References dyno::BackendModuleType< MODULE_TRAITS >::map_.
Referenced by dyno::RegularBackendModule::setFormulation().
nominalSpin()
template<class MODULE_TRAITS > SpinReturn dyno::BackendModuleType< MODULE_TRAITS >::nominalSpin (Base::BaseInputConstPtr base_input) inline override private virtual
Implements dyno::ModuleBase< BackendInputPacket, BackendOutputPacket >.
Definition at line 176 of file BackendModule.hpp.
{
    return nominalSpinImpl(attemptCast(base_input));
  }
References dyno::BackendModuleType< MODULE_TRAITS >::attemptCast(), and dyno::BackendModuleType< MODULE_TRAITS >::nominalSpinImpl().
nominalSpinImpl()
template<class MODULE_TRAITS > virtual SpinReturn dyno::BackendModuleType< MODULE_TRAITS >::nominalSpinImpl (InputConstPtr input) protected pure virtual
Referenced by dyno::BackendModuleType< MODULE_TRAITS >::nominalSpin().
Member Data Documentation
map_
template<class MODULE_TRAITS > MapType::Ptr dyno::BackendModuleType< MODULE_TRAITS >::map_ protected
Definition at line 169 of file BackendModule.hpp.
Referenced by dyno::BackendModuleType< MODULE_TRAITS >::getMap(), dyno::RegularBackendModule::RegularBackendModule(), and dyno::RegularBackendModule::updateMapWithMeasurements().
The documentation for this class was generated from the following file:
dynosam/include/dynosam/backend/BackendModule.hpp