DynoSAM: dyno::FrontendDSDRos Class Reference
dyno::FrontendDSDRos Class Reference
#include <FrontendDSDRos.hpp>
Classes
struct GroundTruthPublishers
Public Member Functions
FrontendDSDRos (const DisplayParams params, rclcpp::Node::SharedPtr node, rclcpp::Node::SharedPtr ground_truth_node=nullptr)
~FrontendDSDRos ()=default
void spinOnceImpl (const VisionImuPacket::ConstPtr &frontend_output) override
Public Member Functions inherited from dyno::DisplayBase< INPUT >
DisplayBase ()
virtual ~DisplayBase ()
void spinOnce (const InputConstPtr &input)
Private Member Functions
void tryPublishDebugImagery (const VisionImuPacket::ConstPtr &frontend_output)
void tryPublishGroundTruth (const VisionImuPacket::ConstPtr &frontend_output)
void tryPublishVisualOdometry (const VisionImuPacket::ConstPtr &frontend_output)
void tryPublishPointClouds (const VisionImuPacket::ConstPtr &frontend_output)
void tryPublishObjects (const VisionImuPacket::ConstPtr &frontend_output)
void updateAccumulatedDataStructured (const VisionImuPacket::ConstPtr &frontend_output)
Private Member Functions inherited from dyno::DSDRos
DSDRos (const DisplayParams &params, rclcpp::Node::SharedPtr node)
void publishVisualOdometry (const gtsam::Pose3 &T_world_camera, Timestamp timestamp, const bool publish_tf)
void publishVisualOdometryPath (const gtsam::Pose3Vector &poses, Timestamp latest_timestamp)
CloudPerObject publishStaticPointCloud (const StatusLandmarkVector &landmarks, const gtsam::Pose3 &T_world_camera)
CloudPerObject publishDynamicPointCloud (const StatusLandmarkVector &landmarks, const gtsam::Pose3 &T_world_camera)
Private Attributes
image_transport::Publisher tracking_image_pub_
Image Transport for tracking image.
rclcpp::Publisher< sensor_msgs::msg::PointCloud2 >::SharedPtr dense_dynamic_cloud_pub_
std::optional< GroundTruthPublishers > ground_truth_publishers_
gtsam::Pose3Vector camera_poses_
Accumulated camera poses.
ObjectMotionMap object_motions_
Accumulated object motions.
ObjectPoseMap object_poses_
Accumulated object poses.
Private Attributes inherited from dyno::DSDRos
const DisplayParams params_
rclcpp::Node::SharedPtr node_
DSDTransport dsd_transport_
Dynamic SLAM display transport for estimated object odometry.
std::unique_ptr< tf2_ros::TransformBroadcaster > tf_broadcaster_
TF broadcaster for the odometry.
OdometryPub::SharedPtr vo_publisher_
PathPub::SharedPtr vo_path_publisher_
rclcpp::Publisher< sensor_msgs::msg::PointCloud2 >::SharedPtr static_points_pub_
rclcpp::Publisher< sensor_msgs::msg::PointCloud2 >::SharedPtr dynamic_points_pub_
Additional Inherited Members
Public Types inherited from dyno::DisplayBase< INPUT >
using Input = INPUT
using This = DisplayBase< INPUT >
using InputConstPtr = typename INPUT::ConstPtr
Public Attributes inherited from dyno::SharedModuleInterface
SharedModuleInfo & shared_module_info = SharedModuleInfo::instance()
Protected Member Functions inherited from dyno::DisplayBase< INPUT >
virtual void spinOnceImpl (const InputConstPtr &input)=0
Detailed Description
Definition at line 45 of file FrontendDSDRos.hpp.
Constructor & Destructor Documentation
FrontendDSDRos()
dyno::FrontendDSDRos::FrontendDSDRos (const DisplayParams params, rclcpp::Node::SharedPtr node, rclcpp::Node::SharedPtr ground_truth_node = nullptr)
Definition at line 40 of file FrontendDSDRos.cc.
    : FrontendDisplay(), DSDRos(params, node) {
  tracking_image_pub_ =
      image_transport::create_publisher(node.get(), "tracking_image");
  // const rclcpp::SensorDataQoS sensor_qos;
  dense_dynamic_cloud_pub_ =
      node->create_publisher<sensor_msgs::msg::PointCloud2>(
          "dense_labelled_cloud", rclcpp::SensorDataQoS());
  if (ground_truth_node) {
    RCLCPP_INFO_STREAM(node->get_logger(), "Creating ground truth publishers");
    ground_truth_publishers_ = GroundTruthPublishers(ground_truth_node);
  }
}
References dense_dynamic_cloud_pub_, ground_truth_publishers_, and tracking_image_pub_.
~FrontendDSDRos()
dyno::FrontendDSDRos::~FrontendDSDRos () default
Member Function Documentation
spinOnceImpl()
void dyno::FrontendDSDRos::spinOnceImpl (const VisionImuPacket::ConstPtr & frontend_output) override
Definition at line 67 of file FrontendDSDRos.cc.
{
  updateAccumulatedDataStructured(frontend_output);
  // publish debug imagery
  tryPublishDebugImagery(frontend_output);
  // // publish ground truth
  tryPublishGroundTruth(frontend_output);
  // publish odometry
  tryPublishVisualOdometry(frontend_output);
  tryPublishPointClouds(frontend_output);
  tryPublishObjects(frontend_output);
}
References tryPublishDebugImagery(), tryPublishGroundTruth(), tryPublishObjects(), tryPublishPointClouds(), tryPublishVisualOdometry(), and updateAccumulatedDataStructured().
tryPublishDebugImagery()
void dyno::FrontendDSDRos::tryPublishDebugImagery (const VisionImuPacket::ConstPtr & frontend_output) private
Definition at line 85 of file FrontendDSDRos.cc.
{
  if (!frontend_output->debugImagery()) return;
  const DebugImagery& debug_imagery = *frontend_output->debugImagery();
  if (debug_imagery.tracking_image.empty()) return;
  std_msgs::msg::Header hdr;
  sensor_msgs::msg::Image::SharedPtr msg =
      cv_bridge::CvImage(hdr, "bgr8", debug_imagery.tracking_image)
          .toImageMsg();
  tracking_image_pub_.publish(msg);
}
References dyno::DebugImagery::tracking_image, and tracking_image_pub_.
Referenced by spinOnceImpl().
tryPublishGroundTruth()
void dyno::FrontendDSDRos::tryPublishGroundTruth (const VisionImuPacket::ConstPtr & frontend_output) private
Definition at line 99 of file FrontendDSDRos.cc.
{
  if (!ground_truth_publishers_ || !frontend_output->groundTruthPacket() ||
      !frontend_output->debugImagery())
    return;
  const DebugImagery& debug_imagery = *frontend_output->debugImagery();
  const cv::Mat& rgb_image = debug_imagery.rgb_viz;
  const auto timestamp = frontend_output->timestamp();
  const auto frame_id = frontend_output->frameId();
  if (rgb_image.empty()) return;
  // collect gt poses and motions
  static ObjectPoseMap poses;
  static ObjectMotionMap motions;
  static FrameIdTimestampMap timestamp_map;
  // hack! recreate the timestamp since it is not in the frontend base packet!!
  timestamp_map.insert2(frame_id, timestamp);
  const GroundTruthInputPacket& gt_packet =
      frontend_output->groundTruthPacket().value();
  for (const auto& object_pose_gt : gt_packet.object_poses_) {
    // check we have a gt motion here
    // in the case that we dont, this might be the first time the object
    // appears...
    if (!object_pose_gt.prev_H_current_world_) {
      continue;
    }
    poses.insert22(object_pose_gt.object_id_, gt_packet.frame_id_,
                   object_pose_gt.L_world_);
    // motion in world k-1 to k
    Motion3ReferenceFrame gt_motion(
        *object_pose_gt.prev_H_current_world_, MotionRepresentationStyle::F2F,
        ReferenceFrame::GLOBAL, gt_packet.frame_id_ - 1u, gt_packet.frame_id_);
    motions.insert22(object_pose_gt.object_id_, gt_packet.frame_id_, gt_motion);
  }
  GroundTruthPublishers& ground_truth_pubs = ground_truth_publishers_.value();
  // will this result in confusing tf's since the gt object and estimated
  // objects use the same link?
  DSDTransport::Publisher publisher =
      ground_truth_pubs.dsd_transport_.addObjectInfo(
          motions, poses, params_.world_frame_id, timestamp_map, frame_id,
          timestamp);
  publisher.publishObjectOdometry();
  // publish ground truth odom
  const gtsam::Pose3& T_world_camera = gt_packet.X_world_;
  nav_msgs::msg::Odometry odom_msg;
  utils::convertWithHeader(T_world_camera, odom_msg, timestamp,
                           params_.world_frame_id, params_.camera_frame_id);
  ground_truth_pubs.vo_publisher_->publish(odom_msg);
  // odom path gt
  // make static variable since we dont build up the path anywhere else
  // and just append the last gt camera pose to the path msg
  static nav_msgs::msg::Path gt_odom_path_msg;
  static std_msgs::msg::Header header;
  geometry_msgs::msg::PoseStamped pose_stamped;
  utils::convertWithHeader(T_world_camera, pose_stamped, timestamp,
                           params_.world_frame_id);
  header.stamp = utils::toRosTime(timestamp);
  header.frame_id = params_.world_frame_id;
  gt_odom_path_msg.header = header;
  gt_odom_path_msg.poses.push_back(pose_stamped);
  ground_truth_pubs.vo_path_publisher_->publish(gt_odom_path_msg);
}
References dyno::DSDTransport::addObjectInfo(), dyno::DisplayParams::camera_frame_id, dyno::utils::convertWithHeader(), dyno::FrontendDSDRos::GroundTruthPublishers::dsd_transport_, dyno::F2F, dyno::GroundTruthInputPacket::frame_id_, dyno::GLOBAL, ground_truth_publishers_, dyno::GenericObjectCentricMap< VALUE >::insert2(), dyno::GenericObjectCentricMap< VALUE >::insert22(), dyno::GroundTruthInputPacket::object_poses_, dyno::DSDRos::params_, dyno::DSDTransport::Publisher::publishObjectOdometry(), dyno::DebugImagery::rgb_viz, dyno::utils::toRosTime(), dyno::FrontendDSDRos::GroundTruthPublishers::vo_path_publisher_, dyno::FrontendDSDRos::GroundTruthPublishers::vo_publisher_, dyno::DisplayParams::world_frame_id, and dyno::GroundTruthInputPacket::X_world_.
Referenced by spinOnceImpl().
tryPublishObjects()
void dyno::FrontendDSDRos::tryPublishObjects (const VisionImuPacket::ConstPtr & frontend_output) private
Definition at line 209 of file FrontendDSDRos.cc.
{
  // relies on correct accumulation of internal objects AND that the shared
  // module data is updated with timestamp/frame data (as in Display.hpp)
  const auto& object_motions = object_motions_;
  const auto& object_poses = object_poses_;
  const auto& timestamp_map = this->shared_module_info.getTimestampMap();
  DSDTransport::Publisher object_poses_publisher = dsd_transport_.addObjectInfo(
      object_motions, object_poses, params_.world_frame_id, timestamp_map,
      frontend_output->frameId(), frontend_output->timestamp());
  object_poses_publisher.publishObjectOdometry();
  object_poses_publisher.publishObjectTransforms();
  object_poses_publisher.publishObjectPaths();
}
References dyno::DSDTransport::addObjectInfo(), dyno::DSDRos::dsd_transport_, dyno::SharedModuleInfo::getTimestampMap(), object_motions_, object_poses_, dyno::DSDRos::params_, dyno::DSDTransport::Publisher::publishObjectOdometry(), dyno::DSDTransport::Publisher::publishObjectPaths(), dyno::DSDTransport::Publisher::publishObjectTransforms(), dyno::SharedModuleInterface::shared_module_info, and dyno::DisplayParams::world_frame_id.
Referenced by spinOnceImpl().
tryPublishPointClouds()
void dyno::FrontendDSDRos::tryPublishPointClouds (const VisionImuPacket::ConstPtr & frontend_output) private
Definition at line 184 of file FrontendDSDRos.cc.
{
  StatusLandmarkVector static_landmarks =
      frontend_output->staticLandmarkMeasurements();
  if (!static_landmarks.empty()) {
    this->publishStaticPointCloud(static_landmarks,
                                  frontend_output->cameraPose());
  }
  StatusLandmarkVector dynamic_landmarks =
      frontend_output->dynamicLandmarkMeasurements();
  if (!dynamic_landmarks.empty()) {
    this->publishDynamicPointCloud(dynamic_landmarks,
                                   frontend_output->cameraPose());
  }
  if (auto labelled_point_cloud = frontend_output->denseLabelledCloud();
      labelled_point_cloud) {
    sensor_msgs::msg::PointCloud2 pc2_msg;
    pcl::toROSMsg(*labelled_point_cloud, pc2_msg);
    pc2_msg.header.frame_id = params_.camera_frame_id;
    pc2_msg.header.stamp = utils::toRosTime(frontend_output->timestamp());
    dense_dynamic_cloud_pub_->publish(pc2_msg);
  }
}
References dyno::DisplayParams::camera_frame_id, dense_dynamic_cloud_pub_, dyno::DSDRos::params_, dyno::DSDRos::publishDynamicPointCloud(), dyno::DSDRos::publishStaticPointCloud(), and dyno::utils::toRosTime().
Referenced by spinOnceImpl().
tryPublishVisualOdometry()
void dyno::FrontendDSDRos::tryPublishVisualOdometry (const VisionImuPacket::ConstPtr & frontend_output) private
Definition at line 173 of file FrontendDSDRos.cc.
{
  // publish vo
  constexpr static bool kPublishOdomAsTf = true;
  this->publishVisualOdometry(frontend_output->cameraPose(),
                              frontend_output->timestamp(), kPublishOdomAsTf);
  // relies on correct accumulation of internal objects
  this->publishVisualOdometryPath(camera_poses_, frontend_output->timestamp());
}
References camera_poses_, dyno::DSDRos::publishVisualOdometry(), and dyno::DSDRos::publishVisualOdometryPath().
Referenced by spinOnceImpl().
updateAccumulatedDataStructured()
void dyno::FrontendDSDRos::updateAccumulatedDataStructured (const VisionImuPacket::ConstPtr & frontend_output) private
Definition at line 225 of file FrontendDSDRos.cc.
{
  camera_poses_.push_back(frontend_output->cameraPose());
  object_motions_.insert2(frontend_output->frameId(),
                          frontend_output->objectMotions());
  object_poses_.insert2(frontend_output->frameId(),
                        frontend_output->objectPoses());
}
References camera_poses_, dyno::GenericObjectCentricMap< VALUE >::insert2(), object_motions_, and object_poses_.
Referenced by spinOnceImpl().
Member Data Documentation
camera_poses_
gtsam::Pose3Vector dyno::FrontendDSDRos::camera_poses_ private
Accumulated camera poses.
Definition at line 82 of file FrontendDSDRos.hpp.
Referenced by tryPublishVisualOdometry(), and updateAccumulatedDataStructured().
dense_dynamic_cloud_pub_
rclcpp::Publisher<sensor_msgs::msg::PointCloud2>::SharedPtr dyno::FrontendDSDRos::dense_dynamic_cloud_pub_ private
Definition at line 77 of file FrontendDSDRos.hpp.
Referenced by FrontendDSDRos(), and tryPublishPointClouds().
ground_truth_publishers_
std::optional<GroundTruthPublishers> dyno::FrontendDSDRos::ground_truth_publishers_ private
Definition at line 79 of file FrontendDSDRos.hpp.
Referenced by FrontendDSDRos(), and tryPublishGroundTruth().
object_motions_
ObjectMotionMap dyno::FrontendDSDRos::object_motions_ private
Accumulated object motions.
Definition at line 84 of file FrontendDSDRos.hpp.
Referenced by tryPublishObjects(), and updateAccumulatedDataStructured().
object_poses_
ObjectPoseMap dyno::FrontendDSDRos::object_poses_ private
Accumulated object poses.
Definition at line 86 of file FrontendDSDRos.hpp.
Referenced by tryPublishObjects(), and updateAccumulatedDataStructured().
tracking_image_pub_
image_transport::Publisher dyno::FrontendDSDRos::tracking_image_pub_ private
Image Transport for tracking image.
Definition at line 75 of file FrontendDSDRos.hpp.
Referenced by FrontendDSDRos(), and tryPublishDebugImagery().
The documentation for this class was generated from the following files:
dynosam_ros/include/dynosam_ros/displays/dynamic_slam_displays/FrontendDSDRos.hpp
dynosam_ros/src/displays/dynamic_slam_displays/FrontendDSDRos.cc