DynoSAM: dyno::BackendExperimentsNode Class Reference
dyno::BackendExperimentsNode Class Reference
Public Member Functions
BackendExperimentsNode ()
~BackendExperimentsNode ()
bool spinOnce () override
Public Member Functions inherited from dyno::DynoNode
DynoNode (const std::string &node_name, const rclcpp::NodeOptions &options=rclcpp::NodeOptions())
virtual ~DynoNode ()=default
virtual bool spinOnce ()
std::string getStats () const
const DynoParams & getDynoParams ()
std::string getParamsPath ()
std::string getDatasetPath ()
Private Attributes
PipelineBase::UniquePtr frontend_pipeline_ {nullptr}
BackendPipeline::UniquePtr backend_pipeline_ {nullptr}
FrontendPipeline::OutputQueue backend_input_queue_
Additional Inherited Members
Protected Member Functions inherited from dyno::DynoNode
virtual dyno::DataProvider::Ptr createDataProvider ()
Protected Attributes inherited from dyno::DynoNode
bool is_online_
Detailed Description
Definition at line 49 of file backend_experiments_node.cc.
Constructor & Destructor Documentation
BackendExperimentsNode()
dyno::BackendExperimentsNode::BackendExperimentsNode () inline
Definition at line 51 of file backend_experiments_node.cc.
                           : DynoNode("dynosam_experiments") {
    RCLCPP_INFO_STREAM(this->get_logger(), "Starting BackendExperimentsNode");
    auto data_loader = this->createDataProvider();
    auto params = this->getDynoParams();
    CameraParams camera_params;
    if (params.preferDataProviderCameraParams() &&
        data_loader->getCameraParams().has_value()) {
      LOG(INFO) << "Using camera params from DataProvider, not the config in "
                   "the CameraParams.yaml!";
      camera_params = *data_loader->getCameraParams();
    } else {
      LOG(INFO) << "Using camera params specified in CameraParams.yaml!";
      camera_params = params.camera_params_;
    }
    Camera::Ptr camera = std::make_shared<Camera>(camera_params);
    using BackendModuleTraits = RegularBackendModule::ModuleTraits;
    LOG(INFO) << "Offline RGBD frontend";
    const std::string file_path =
        getOutputFilePath(kRgbdFrontendOutputJsonFile);
    using OfflineFrontend =
        FrontendOfflinePipeline<RegularBackendModule::ModuleTraits>;
    OfflineFrontend::UniquePtr offline_frontend =
        std::make_unique<OfflineFrontend>("offline-rgbdfrontend", file_path,
                                          FLAGS_ending_frame);
    // raw ptr type becuase we cannot copy the unique ptr!! This is only becuase
    // we need it in the lambda function which is a temporary solution
    OfflineFrontend* offline_frontend_ptr = offline_frontend.get();
    // TODO: make better params!!
    auto updater_type = static_cast<RegularBackendModule::UpdaterType>(
        FLAGS_backend_updater_enum);
    BackendModuleType<RGBDBackendModuleTraits>::Ptr backend = nullptr;
    if (updater_type == RGBDFormulationType::PARALLEL_HYBRID) {
      backend = std::make_shared<ParallelHybridBackendModule>(
          params.backend_params_, camera);
    } else {
      params.backend_params_.full_batch_frame = offline_frontend->endingFrame();
      backend = std::make_shared<RegularBackendModule>(params.backend_params_,
                                                       camera, updater_type);
    }
    // params.backend_params_.full_batch_frame =
    // offline_frontend->endingFrame();
    // auto backend =
    // std::make_shared<RegularBackendModule>(params.backend_params_,
    //                                                    camera, updater_type);
    backend_pipeline_ = std::make_unique<BackendPipeline>(
        "backend-pipeline", &backend_input_queue_, backend);
    backend_pipeline_->parallelRun(params.parallelRun());
    // also register connection between front and back
    offline_frontend_ptr->registerOutputQueue(&backend_input_queue_);
    // NO OUTPUT!!
    // convert pipeline to base type
    frontend_pipeline_ = std::move(offline_frontend);
  }
References backend_input_queue_, backend_pipeline_, dyno::DynoNode::createDataProvider(), frontend_pipeline_, dyno::DynoNode::getDynoParams(), dyno::getOutputFilePath(), dyno::kRgbdFrontendOutputJsonFile, and dyno::PARALLEL_HYBRID.
~BackendExperimentsNode()
dyno::BackendExperimentsNode::~BackendExperimentsNode () inline
Definition at line 122 of file backend_experiments_node.cc.
{
    // TODO: make shutdown hook!
    writeStatisticsSamplesToFile("statistics_samples.csv");
    writeStatisticsModuleSummariesToFile();
  }
References dyno::writeStatisticsModuleSummariesToFile(), and dyno::writeStatisticsSamplesToFile().
Member Function Documentation
spinOnce()
bool dyno::BackendExperimentsNode::spinOnce () inline override virtual
Reimplemented from dyno::DynoNode.
Definition at line 128 of file backend_experiments_node.cc.
{
    RCLCPP_INFO_STREAM_THROTTLE(this->get_logger(), *this->get_clock(), 2000,
                                getStats());
    if (frontend_pipeline_->isWorking()) {
      frontend_pipeline_->spinOnce();
      backend_pipeline_->spinOnce();
      return true;
    }
    return false;
  }
References backend_pipeline_, frontend_pipeline_, and dyno::DynoNode::getStats().
Member Data Documentation
backend_input_queue_
FrontendPipeline::OutputQueue dyno::BackendExperimentsNode::backend_input_queue_ private
Definition at line 142 of file backend_experiments_node.cc.
Referenced by BackendExperimentsNode().
backend_pipeline_
BackendPipeline::UniquePtr dyno::BackendExperimentsNode::backend_pipeline_ {nullptr} private
Definition at line 141 of file backend_experiments_node.cc.
Referenced by BackendExperimentsNode(), and spinOnce().
frontend_pipeline_
PipelineBase::UniquePtr dyno::BackendExperimentsNode::frontend_pipeline_ {nullptr} private
Definition at line 140 of file backend_experiments_node.cc.
Referenced by BackendExperimentsNode(), and spinOnce().
The documentation for this class was generated from the following file:
dynosam_ros/nodes/backend_experiments_node.cc