DynoSAM: dyno::WorldMotionFormulation Class Reference
dyno::WorldMotionFormulation Class Reference
#include <WorldMotionEstimator.hpp>
Public Types
using Base = WorldPoseFormulation
Public Types inherited from dyno::WorldPoseFormulation
using Base = Formulation< Map3d2d >
Public Types inherited from dyno::Formulation< Map3d2d >
using Map = Map3d2d
using This = Formulation< Map >
using MapTraitsType = MapTraits< Map >
using MeasurementType = typename MapTraitsType::MeasurementType
using MeasurementTraits = measurement_traits< MeasurementType >
using PointUpdateContextType = PointUpdateContext< Map >
using ObjectUpdateContextType = ObjectUpdateContext< Map >
using AccessorType = Accessor< Map3d2d >
using AccessorTypePointer = typename Accessor< Map3d2d >::Ptr
Public Member Functions
WorldMotionFormulation (const FormulationParams &params, typename Map::Ptr map, const NoiseModels &noise_models, const FormulationHooks &hooks)
void dynamicPointUpdateCallback (const PointUpdateContextType &context, UpdateObservationResult &result, gtsam::Values &new_values, gtsam::NonlinearFactorGraph &new_factors) override
void objectUpdateContext (const ObjectUpdateContextType &context, UpdateObservationResult &result, gtsam::Values &new_values, gtsam::NonlinearFactorGraph &new_factors) override
Public Member Functions inherited from dyno::WorldPoseFormulation
WorldPoseFormulation (const FormulationParams &params, typename Map::Ptr map, const NoiseModels &noise_models, const FormulationHooks &hooks)
virtual ~WorldPoseFormulation ()
void dynamicPointUpdateCallback (const PointUpdateContextType &context, UpdateObservationResult &result, gtsam::Values &new_values, gtsam::NonlinearFactorGraph &new_factors) override
void objectUpdateContext (const ObjectUpdateContextType &context, UpdateObservationResult &result, gtsam::Values &new_values, gtsam::NonlinearFactorGraph &new_factors) override
bool isDynamicTrackletInMap (const LandmarkNode3d2d::Ptr &lmk_node) const override
Public Member Functions inherited from dyno::Formulation< Map3d2d >
Formulation (const FormulationParams &params, typename Map::Ptr map, const NoiseModels &noise_models, const FormulationHooks &hooks=FormulationHooks())
virtual ~Formulation ()=default
Map::Ptr map () const
Get the map used by the formulation.
const gtsam::Values & getTheta () const
Get the current linearization point for this formulation. These values can be updated after external optimisation and are constructed by the derived formulation during update.
void setTheta (const gtsam::Values &linearization)
Sets the full set of theta values (overrides them). This is used after external optimisation to update the values for the accessor which has a internal reference (pointer) to theta.
void updateTheta (const gtsam::Values &linearization)
Updates and assigns new values to theta. This is used after external optimisation to update the values for the accessor which has a internal reference (pointer) to theta.
const gtsam::NonlinearFactorGraph & getGraph () const
Gets the current graph associated with the current theta and constructed by the derived formulation. Along theta, this should be used by an external optimisation routine.
const FormulationHooks & hooks () const
const NoiseModels & noiseModels () const
virtual gtsam::KeyFormatter formatter () const
Custom gtsam::Key formatter for this formulation. Defaults to DynoLikeKeyFormatter.
const std::string getFullyQualifiedName () const
Get the fully qualified name of this formulation which is derived from the loggerPrefix and optionally the FormulationParams::suffix if given.
AccessorType::Ptr accessorFromTheta () const
Public fucntion to access the Accessor for the derived formulation.
std::shared_ptr< Derived > derivedAccessor () const
BackendLogger::UniquePtr makeFullyQualifiedLogger () const
Makes a logger using the fully-qualified name for this formulation.
void addValuesFunctional (std::function< void(gtsam::Values &)> callback, gtsam::Values &new_values)
void addFactorsFunctional (std::function< void(gtsam::NonlinearFactorGraph &)> callback, gtsam::NonlinearFactorGraph &new_factors)
void addSensorPoseValue (const gtsam::Pose3 &X_W_k, FrameId frame_id_k, gtsam::Values &new_values)
void addSensorPosePriorFactor (const gtsam::Pose3 &X_W_k, gtsam::SharedNoiseModel noise_model, FrameId frame_id_k, gtsam::NonlinearFactorGraph &new_factors)
void setInitialPose (const gtsam::Pose3 &T_world_camera, FrameId frame_id_k, gtsam::Values &new_values)
Adds a gtsam::Pose3 as a value in the graph at frame k.
void setInitialPosePrior (const gtsam::Pose3 &T_world_camera, FrameId frame_id_k, gtsam::NonlinearFactorGraph &new_factors)
Adds a pose prior on a value in the graph at frame k using the given pose value as the prior's mean.
UpdateObservationResult updateStaticObservations (FrameId from_frame, FrameId to_frame, gtsam::Values &new_values, gtsam::NonlinearFactorGraph &new_factors, const UpdateObservationParams &update_params)
Update the static-point part of the factor graph between multiple frames. Internally makes several calls to updateStaticObservations(FrameId,gtsam::Values&,gtsam::NonlinearFactorGraph&,const UpdateObservationParams&) and returns the accumulated UpdateObservationResult.
UpdateObservationResult updateStaticObservations (FrameId frame_id_k, gtsam::Values &new_values, gtsam::NonlinearFactorGraph &new_factors, const UpdateObservationParams &update_params)
Updates the static-point part of the factor graph for frame k. This contains all the bookeeping logic to update the factor graph with static points.
UpdateObservationResult updateDynamicObservations (FrameId from_frame, FrameId to_frame, gtsam::Values &new_values, gtsam::NonlinearFactorGraph &new_factors, const UpdateObservationParams &update_params)
Update the dynamic-point part of the factor graph between multiple frames. Internally makes several calls to updateDynamicObservations(FrameId,gtsam::Values&,gtsam::NonlinearFactorGraph&,const UpdateObservationParams&) and returns the accumulated UpdateObservationResult.
UpdateObservationResult updateDynamicObservations (FrameId frame_id_k, gtsam::Values &new_values, gtsam::NonlinearFactorGraph &new_factors, const UpdateObservationParams &update_params)
Updates the dyanmic-point part of the factor graph for frame k. This contains all the big-boi bookeeping logic to update the factor graph with dyanmic points and objects. This is where the virtual dynamicPointUpdateCallback and objectUpdateContext functions are called.
void logBackendFromMap (const BackendMetaData &backend_info)
Logs all frames and values to file using Accessor and BackendLogger. The BackendMetaData provides meta-data and ground truth information for logging.
virtual void preUpdate (const PreUpdateData &)
Pre update hook called in the RegularBackend after the map is updated with new measurements but before new values/factors are constructed from this formulation.
virtual void postUpdate (const PostUpdateData &)
Post-update hook called in the RegulatBackend after graph construction and optimization!
Protected Member Functions
AccessorTypePointer createAccessor (const SharedFormulationData &shared_data) const override
Creates the associated Accessor for the derived formulation. The accessor will contain a pointer to This::theta_, so that when the values are updated the accessor has access to the latest values.
void postUpdate (const PostUpdateData &)
Post-update hook called in the RegulatBackend after graph construction and optimization!
std::string loggerPrefix () const override
Defines the base name of this formulation. This name will appear as part of the output logs and may be augmented with the FormulationParams::suffix, if given. To get the fully qualified name (the actual name that will appear in the logs), use This::getFullyQualifiedName().
Protected Member Functions inherited from dyno::WorldPoseFormulation
AccessorTypePointer createAccessor (const SharedFormulationData &shared_data) const override
Creates the associated Accessor for the derived formulation. The accessor will contain a pointer to This::theta_, so that when the values are updated the accessor has access to the latest values.
std::string loggerPrefix () const override
Defines the base name of this formulation. This name will appear as part of the output logs and may be augmented with the FormulationParams::suffix, if given. To get the fully qualified name (the actual name that will appear in the logs), use This::getFullyQualifiedName().
Protected Member Functions inherited from dyno::Formulation< Map3d2d >
virtual void dynamicPointUpdateCallback (const PointUpdateContextType &context, UpdateObservationResult &result, gtsam::Values &new_values, gtsam::NonlinearFactorGraph &new_factors)=0
Virtual function to be implemented by derived class and indicates that a specific landmark has new measurements and new values/factors should be added. Details on the landmark to be updated are provied by the context. In general, this is used to add projection/motion factors and initial values for landmarks.
virtual void objectUpdateContext (const ObjectUpdateContextType &context, UpdateObservationResult &result, gtsam::Values &new_values, gtsam::NonlinearFactorGraph &new_factors)=0
Virtual function to be implemented by derived class and indicates that a specific object j and time-step k has been observed and its dynamic points updated in the graph, and associated values/factors should be added. Details on the object to be updated are provied by the context. In general, this is used to add smoothing factors and initial values for object motion/pose.
virtual bool isDynamicTrackletInMap (const typename MapTraitsType::LandmarkNodePtr &lmk_node) const=0
Virtual function to be implemented by derived class and indicates that the specified landmark exists within the graph already. This is used as part of the internal bookeeping.
virtual std::string loggerPrefix () const=0
Defines the base name of this formulation. This name will appear as part of the output logs and may be augmented with the FormulationParams::suffix, if given. To get the fully qualified name (the actual name that will appear in the logs), use This::getFullyQualifiedName().
virtual AccessorType::Ptr createAccessor (const SharedFormulationData &shared_data) const=0
Creates the associated Accessor for the derived formulation. The accessor will contain a pointer to This::theta_, so that when the values are updated the accessor has access to the latest values.
gtsam::Pose3 getInitialOrLinearizedSensorPose (FrameId frame_id) const
void clearGraph ()
Private Attributes
std::shared_ptr< WorldMotionAccessor > derived_accessor_
Additional Inherited Members
Protected Attributes inherited from dyno::WorldPoseFormulation
gtsam::FastMap< TrackletId, bool > is_dynamic_tracklet_in_map_
Protected Attributes inherited from dyno::Formulation< Map3d2d >
const FormulationParams params_
Map::Ptr map_
const NoiseModels noise_models_
FormulationHooks hooks_
gtsam::FastMap< gtsam::Key, bool > is_other_values_in_map
gtsam::Values theta_
Current linearisation that will be associated with the current graph.
gtsam::NonlinearFactorGraph factors_
Detailed Description
Definition at line 71 of file WorldMotionEstimator.hpp.
Member Typedef Documentation
Base
using dyno::WorldMotionFormulation::Base = WorldPoseFormulation
Definition at line 73 of file WorldMotionEstimator.hpp.
Constructor & Destructor Documentation
WorldMotionFormulation()
dyno::WorldMotionFormulation::WorldMotionFormulation (const FormulationParams & params, typename Map::Ptr map, const NoiseModels & noise_models, const FormulationHooks & hooks) inline
Definition at line 80 of file WorldMotionEstimator.hpp.
      : WorldPoseFormulation(params, map, noise_models, hooks) {
    derived_accessor_ = derivedAccessor<WorldMotionAccessor>();
    CHECK_NOTNULL(derived_accessor_);
  }
References derived_accessor_.
Member Function Documentation
createAccessor()
AccessorTypePointer dyno::WorldMotionFormulation::createAccessor (const SharedFormulationData & shared_data) const inline override protected virtual
Creates the associated Accessor for the derived formulation. The accessor will contain a pointer to This::theta_, so that when the values are updated the accessor has access to the latest values.
Parameters
values const gtsam::Values*
Returns
AccessorType::Ptr
Implements dyno::Formulation< Map3d2d >.
Definition at line 98 of file WorldMotionEstimator.hpp.
{
    return std::make_shared<WorldMotionAccessor>(shared_data, this->map());
  }
References dyno::Formulation< Map3d2d >::map().
dynamicPointUpdateCallback()
void dyno::WorldMotionFormulation::dynamicPointUpdateCallback (const PointUpdateContextType & context, UpdateObservationResult & result, gtsam::Values & new_values, gtsam::NonlinearFactorGraph & new_factors) override
Definition at line 151 of file WorldMotionEstimator.cc.
{
  const auto lmk_node = context.lmk_node;
  const auto frame_node_k_1 = context.frame_node_k_1;
  const auto frame_node_k = context.frame_node_k;
  auto dynamic_point_noise = noise_models_.dynamic_point_noise;
  auto theta_accessor = this->accessorFromTheta();
  const gtsam::Key object_point_key_k_1 =
      lmk_node->makeDynamicKey(frame_node_k_1->frame_id);
  const gtsam::Key object_point_key_k =
      lmk_node->makeDynamicKey(frame_node_k->frame_id);
  bool add_point_from_previous = context.is_starting_motion_frame;
  bool does_previous_point_exist = new_values.exists(object_point_key_k_1) ||
                                   theta_accessor->exists(object_point_key_k_1);
  // check the case that the point exists at the previous frame
  // this only happens when we have non-consequative frames ie 2 3 4 5 6 7 10 11
  // and we are at frame 11!!
  //  logically this occurs becuase of the implementation of Formulation which
  //  checks for all the frames that the point has been observed in and only
  //  sets is_starting_motion_frame = true on the first pair of motions it does
  //  not account for inconsistencies in the frame order as pointed out...
  // Jesse: honestly this should NOT happen but we handle the case anyway...
  if (!add_point_from_previous && !does_previous_point_exist) {
    // we could do many things including re-initing this point OR removing it
    // from the tracked set
    CHECK(lmk_node->seenAtFrame(frame_node_k_1->frame_id));
    // if we think we shouldn't add the previous point but the previous point
    // does not exist, add it!@!
    add_point_from_previous = true;
  }
  // if first motion (i.e first time we have both k-1 and k), add both at k-1
  // and k
  if (add_point_from_previous) {
    CHECK(!theta_accessor->exists(object_point_key_k_1));
    new_factors.emplace_shared<PoseToPointFactor>(
        frame_node_k_1->makePoseKey(),  // pose key at previous frames
        object_point_key_k_1, lmk_node->getMeasurement(frame_node_k_1).landmark,
        dynamic_point_noise);
    if (result.debug_info)
      result.debug_info->getObjectInfo(context.getObjectId())
          .num_dynamic_factors++;
    result.updateAffectedObject(frame_node_k_1->frame_id,
                                context.getObjectId());
    // add landmark at previous frame
    const Landmark measured_k_1 =
        lmk_node->getMeasurement(frame_node_k_1->frame_id).landmark;
    Landmark lmk_world_k_1;
    getSafeQuery(lmk_world_k_1,
                 theta_accessor->query<Landmark>(object_point_key_k_1),
                 gtsam::Point3(context.X_k_1_measured * measured_k_1));
    new_values.insert(object_point_key_k_1, lmk_world_k_1);
    if (result.debug_info)
      result.debug_info->getObjectInfo(context.getObjectId())
          .num_new_dynamic_points++;
  }
  // previous point must be added by the previous iteration
  CHECK(new_values.exists(object_point_key_k_1) ||
        theta_accessor->exists(object_point_key_k_1))
      << "Key: " << this->formatter()(object_point_key_k_1)
      << " and seen at frames "
      << container_to_string(lmk_node->getSeenFrameIds());
  const Landmark measured_k = lmk_node->getMeasurement(frame_node_k).landmark;
  new_factors.emplace_shared<PoseToPointFactor>(
      frame_node_k
          ->makePoseKey(),  // pose key at this (in the iteration) frames
      object_point_key_k, measured_k, dynamic_point_noise);
  if (result.debug_info)
    result.debug_info->getObjectInfo(context.getObjectId())
        .num_dynamic_factors++;
  result.updateAffectedObject(frame_node_k->frame_id, context.getObjectId());
  Landmark lmk_world_k;
  getSafeQuery(lmk_world_k, theta_accessor->query<Landmark>(object_point_key_k),
               gtsam::Point3(context.X_k_measured * measured_k));
  new_values.insert(object_point_key_k, lmk_world_k);
  if (result.debug_info)
    result.debug_info->getObjectInfo(context.getObjectId())
        .num_new_dynamic_points++;
  const gtsam::Key object_motion_key_k =
      frame_node_k->makeObjectMotionKey(context.getObjectId());
  auto landmark_motion_noise = noise_models_.landmark_motion_noise;
  new_factors.emplace_shared<LandmarkMotionTernaryFactor>(
      object_point_key_k_1, object_point_key_k, object_motion_key_k,
      landmark_motion_noise);
  result.updateAffectedObject(frame_node_k_1->frame_id, context.getObjectId());
  result.updateAffectedObject(frame_node_k->frame_id, context.getObjectId());
  if (result.debug_info)
    result.debug_info->getObjectInfo(context.getObjectId())
        .num_motion_factors++;
  // mark as now in map
  is_dynamic_tracklet_in_map_.insert2(context.getTrackletId(), true);
}
References dyno::Formulation< Map3d2d >::accessorFromTheta(), dyno::container_to_string(), dyno::UpdateObservationResult::debug_info, dyno::NoiseModels::dynamic_point_noise, dyno::Formulation< Map3d2d >::formatter(), dyno::getSafeQuery(), dyno::WorldPoseFormulation::is_dynamic_tracklet_in_map_, dyno::NoiseModels::landmark_motion_noise, dyno::Formulation< Map3d2d >::noise_models_, and dyno::UpdateObservationResult::updateAffectedObject().
loggerPrefix()
std::string dyno::WorldMotionFormulation::loggerPrefix () const inline override protected virtual
Defines the base name of this formulation. This name will appear as part of the output logs and may be augmented with the FormulationParams::suffix, if given. To get the fully qualified name (the actual name that will appear in the logs), use This::getFullyQualifiedName().
Returns
std::string
Implements dyno::Formulation< Map3d2d >.
Definition at line 108 of file WorldMotionEstimator.hpp.
{ return "wcme"; }
objectUpdateContext()
void dyno::WorldMotionFormulation::objectUpdateContext (const ObjectUpdateContextType & context, UpdateObservationResult & result, gtsam::Values & new_values, gtsam::NonlinearFactorGraph & new_factors) override
Definition at line 259 of file WorldMotionEstimator.cc.
{
  auto frame_node_k = context.frame_node_k;
  const gtsam::Key object_motion_key_k =
      frame_node_k->makeObjectMotionKey(context.getObjectId());
  auto theta_accessor = this->accessorFromTheta();
  // skip if no motion pair availble
  if (!context.has_motion_pair) {
    return;
  }
  const auto frame_id = context.getFrameId();
  const auto object_id = context.getObjectId();
  if (!is_other_values_in_map.exists(object_motion_key_k)) {
    // when we have an initial motion
    Motion3 initial_motion = Motion3::Identity();
    constexpr static bool init_H_with_identity = false;
    if (!init_H_with_identity) {
      map()->hasInitialObjectMotion(frame_id, object_id, &initial_motion);
      LOG(INFO) << "Using motion from frontend " << initial_motion;
      initial_motion =
          gtsam::Pose3(gtsam::Rot3::Identity(), initial_motion.translation());
    }
    new_values.insert(object_motion_key_k, initial_motion);
    is_other_values_in_map.insert2(object_motion_key_k, true);
  }
  if (frame_id < 2) return;
  auto frame_node_k_1 = map()->getFrame(frame_id - 1u);
  if (!frame_node_k_1) {
    return;
  }
  if (FLAGS_use_smoothing_factor && frame_node_k_1->objectObserved(object_id)) {
    // motion key at previous frame
    const gtsam::Symbol object_motion_key_k_1 =
        frame_node_k_1->makeObjectMotionKey(object_id);
    auto object_smoothing_noise = noise_models_.object_smoothing_noise;
    CHECK(object_smoothing_noise);
    CHECK_EQ(object_smoothing_noise->dim(), 6u);
    {
      ObjectId object_label_k_1, object_label_k;
      FrameId frame_id_k_1, frame_id_k;
      CHECK(reconstructMotionInfo(object_motion_key_k_1, object_label_k_1,
                                  frame_id_k_1));
      CHECK(reconstructMotionInfo(object_motion_key_k, object_label_k,
                                  frame_id_k));
      CHECK_EQ(object_label_k_1, object_label_k);
      CHECK_EQ(frame_id_k_1 + 1, frame_id_k);  // assumes consequative frames
    }
    // if the motion key at k (motion from k-1 to k), and key at k-1 (motion
    // from k-2 to k-1) exists in the map or is about to exist via new values,
    // add the smoothing factor
    if (is_other_values_in_map.exists(object_motion_key_k_1) &&
        is_other_values_in_map.exists(object_motion_key_k)) {
      new_factors.emplace_shared<gtsam::BetweenFactor<gtsam::Pose3>>(
          object_motion_key_k_1, object_motion_key_k, gtsam::Pose3::Identity(),
          object_smoothing_noise);
      if (result.debug_info)
        result.debug_info->getObjectInfo(context.getObjectId())
            .smoothing_factor_added = true;
    }
  }
}
References dyno::Formulation< Map3d2d >::accessorFromTheta(), dyno::UpdateObservationResult::debug_info, dyno::Formulation< Map3d2d >::is_other_values_in_map, dyno::Formulation< Map3d2d >::map(), dyno::Formulation< Map3d2d >::noise_models_, dyno::NoiseModels::object_smoothing_noise, and dyno::reconstructMotionInfo().
postUpdate()
void dyno::WorldMotionFormulation::postUpdate (const PostUpdateData &) inline protected virtual
Post-update hook called in the RegulatBackend after graph construction and optimization!
Reimplemented from dyno::Formulation< Map3d2d >.
Definition at line 103 of file WorldMotionEstimator.hpp.
{
    // update pose cache in accessor
    CHECK_NOTNULL(derived_accessor_)->refreshPoseCache();
  }
References derived_accessor_.
Member Data Documentation
derived_accessor_
std::shared_ptr<WorldMotionAccessor> dyno::WorldMotionFormulation::derived_accessor_ private
Definition at line 111 of file WorldMotionEstimator.hpp.
Referenced by postUpdate(), and WorldMotionFormulation().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/backend/rgbd/WorldMotionEstimator.hpp
dynosam/src/backend/rgbd/WorldMotionEstimator.cc