DynoSAM: dyno::OpenCVImageDisplayQueue Class Reference
dyno::OpenCVImageDisplayQueue Class Reference
#include <Visualizer-Definitions.hpp>
Public Member Functions
OpenCVImageDisplayQueue (ImageDisplayQueue *display_queue, bool parallel_run)
void process ()
Private Attributes
ImageDisplayQueue * display_queue_
bool parallel_run_
Detailed Description
Definition at line 46 of file Visualizer-Definitions.hpp.
Constructor & Destructor Documentation
OpenCVImageDisplayQueue()
dyno::OpenCVImageDisplayQueue::OpenCVImageDisplayQueue (ImageDisplayQueue * display_queue, bool parallel_run)
Definition at line 39 of file Visualizer-Definitions.cc.
    : display_queue_(CHECK_NOTNULL(display_queue)),
      parallel_run_(parallel_run) {}
Member Function Documentation
process()
void dyno::OpenCVImageDisplayQueue::process ()
Definition at line 44 of file Visualizer-Definitions.cc.
{
  bool queue_state = false;
  if (parallel_run_) {
    ImageToDisplay image_to_display;
    queue_state = display_queue_->popBlockingWithTimeout(image_to_display, 2);
    if (queue_state) {
      // cv::namedWindow(image_to_display.name_);
      cv::imshow(image_to_display.name_, image_to_display.image_);
      cv::waitKey(1);  // Not needed because we are using startWindowThread()
    }
  } else {
    std::vector<ImageToDisplay> images_to_display;
    queue_state = display_queue_->popAll(images_to_display, 2);
    if (queue_state) {
      for (const auto& image_to_display : images_to_display) {
        cv::imshow(image_to_display.name_, image_to_display.image_);
      }
      cv::waitKey(1);
    }
  }
}
References display_queue_, dyno::ImageToDisplay::image_, dyno::ImageToDisplay::name_, parallel_run_, ThreadsafeQueue< T >::popAll(), and ThreadsafeQueue< T >::popBlockingWithTimeout().
Referenced by dyno::DynoPipelineManager::spinViz().
Member Data Documentation
display_queue_
ImageDisplayQueue* dyno::OpenCVImageDisplayQueue::display_queue_ private
Definition at line 54 of file Visualizer-Definitions.hpp.
Referenced by process().
parallel_run_
bool dyno::OpenCVImageDisplayQueue::parallel_run_ private
Definition at line 55 of file Visualizer-Definitions.hpp.
Referenced by process().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/visualizer/Visualizer-Definitions.hpp
dynosam/src/visualizer/Visualizer-Definitions.cc