DynoSAM: dyno::WorldMotionAccessor Class Reference
dyno::WorldMotionAccessor Class Reference
#include <WorldMotionEstimator.hpp>
Public Member Functions
WorldMotionAccessor (const SharedFormulationData &shared_data, MapVision::Ptr map)
StateQuery< gtsam::Pose3 > getObjectMotion (FrameId frame_id, ObjectId object_id) const override
Get an absolute object motion (_{k-1}^wH_k) from theta the requested time-step (k) and object (j).
StateQuery< gtsam::Pose3 > getObjectPose (FrameId frame_id, ObjectId object_id) const override
Get the pose (^wL_k) of an object (j) at time-step (k).
ObjectPoseMap getObjectPoses () const override
Collects all object poses for frame 0 to K. (Non-pure)Virtual function that may be overwritten - default implementation uses the pure-virtual getObjectPoses to collect all poses.
EstimateMap< ObjectId, gtsam::Pose3 > getObjectPoses (FrameId frame_id) const override
Collects all object poses at some time-step (k). See Accessor::getObjectPoses(FrameId)
void refreshPoseCache ()
Update the object pose (cache) estimation based on the latest set of estated values stored in theta!
Public Member Functions inherited from dyno::WorldPoseAccessor
WorldPoseAccessor (const SharedFormulationData &shared_data, MapVision::Ptr map)
virtual ~WorldPoseAccessor ()
StateQuery< gtsam::Pose3 > getSensorPose (FrameId frame_id) const override
Get the sensor pose (^wX_k) from theta at the requested time-step.
virtual StateQuery< gtsam::Pose3 > getObjectMotion (FrameId frame_id, ObjectId object_id) const override
Get an absolute object motion (_{k-1}^wH_k) from theta the requested time-step (k) and object (j).
virtual StateQuery< gtsam::Pose3 > getObjectPose (FrameId frame_id, ObjectId object_id) const override
Get the pose (^wL_k) of an object (j) at time-step (k).
StateQuery< gtsam::Point3 > getDynamicLandmark (FrameId frame_id, TrackletId tracklet_id) const override
Get a dynamic landmark (^wm_k) with tracklet id (i) at time-step (k).
Public Member Functions inherited from dyno::AccessorT< MapVision >
AccessorT (const SharedFormulationData &shared_data, typename Map::Ptr map, DerivedArgs &&... derived_args)
virtual ~AccessorT ()
virtual StateQuery< gtsam::Point3 > getStaticLandmark (TrackletId tracklet_id) const override
Get a static landmark (^wm) with tracklet id (i).
virtual EstimateMap< ObjectId, gtsam::Pose3 > getObjectPoses (FrameId frame_id) const override
Collects all object poses at some time-step (k). See Accessor::getObjectPoses(FrameId)
virtual ObjectPoseMap getObjectPoses () const override
Collects all object poses for frame 0 to K. (Non-pure)Virtual function that may be overwritten - default implementation uses the pure-virtual getObjectPoses to collect all poses.
MotionEstimateMap getObjectMotions (FrameId frame_id) const override
Collects all object motions (_{k-1}^wH_k) from time-step (k-1) to k. This is equivalent to \mathcal{H}_k. Uses the pure-virtual getObjectMotion function to collect all object motions.
virtual ObjectMotionMap getObjectMotions () const override
Collects all object motions from 1 to K (with the first motion being from k-1 to k).
StatusLandmarkVector getDynamicLandmarkEstimates (FrameId frame_id) const override
Get all dynamic landmarks for all objects (\mathcal{J}_k) at time-step k.
virtual StatusLandmarkVector getDynamicLandmarkEstimates (FrameId frame_id, ObjectId object_id) const override
Get all dynamic landmarks for object j at time-step k.
StatusLandmarkVector getStaticLandmarkEstimates (FrameId frame_id) const override
Get all static landmarks at time-step k.
StatusLandmarkVector getFullStaticMap () const override
Get all static landmarks from time-step 0 to k.
bool hasObjectMotionEstimate (FrameId frame_id, ObjectId object_id, Motion3 *motion=nullptr) const override
Check if there exists an estimate for object motion at time-step (k) for object id (j). If result is true and a motion is provided, return true and set the motion.
bool hasObjectPoseEstimate (FrameId frame_id, ObjectId object_id, gtsam::Pose3 *pose=nullptr) const override
Check if there exists an estimate for object pose at time-step (k) for object id (j). If result is true and a pose is provided, return true and set the pose.
gtsam::FastMap< ObjectId, gtsam::Point3 > computeObjectCentroids (FrameId frame_id) const override
Computes a the centroid of each object at this frame using the estimated dynamic points.
boost::optional< const gtsam::Value & > getValueImpl (const gtsam::Key key) const override
Gets the gtsam::Value object as an optional. The existance of the optional indicates existance of the value. We use this functionality as a replacement for the if(exists()) -> return at() paradigm so that the derived class can check and return the value as a single unit which reduces overhead.
Public Member Functions inherited from dyno::Accessor
Accessor ()=default
virtual ~Accessor ()
virtual StateQuery< gtsam::Pose3 > getSensorPose (FrameId frame_id) const =0
Get the sensor pose (^wX_k) from theta at the requested time-step.
virtual StateQuery< gtsam::Pose3 > getObjectMotion (FrameId frame_id, ObjectId object_id) const =0
Get an absolute object motion (_{k-1}^wH_k) from theta the requested time-step (k) and object (j).
virtual StateQuery< gtsam::Pose3 > getObjectPose (FrameId frame_id, ObjectId object_id) const =0
Get the pose (^wL_k) of an object (j) at time-step (k).
virtual StateQuery< gtsam::Point3 > getDynamicLandmark (FrameId frame_id, TrackletId tracklet_id) const =0
Get a dynamic landmark (^wm_k) with tracklet id (i) at time-step (k).
virtual StateQuery< gtsam::Point3 > getStaticLandmark (TrackletId tracklet_id) const =0
Get a static landmark (^wm) with tracklet id (i).
virtual EstimateMap< ObjectId, gtsam::Pose3 > getObjectPoses (FrameId frame_id) const =0
Collects all object poses at some time-step (k). This is equivalent to \mathcal{L}_k. Is a (non-pure) virtual function so may be overwritten - default implementation uses the pure-virtual getObjectPose function to collect all object poses.
virtual MotionEstimateMap getObjectMotions (FrameId frame_id) const =0
Collects all object motions (_{k-1}^wH_k) from time-step (k-1) to k. This is equivalent to \mathcal{H}_k.
virtual ObjectPoseMap getObjectPoses () const =0
Collects all object poses for frame 0 to K. (Non-pure)Virtual function that may be overwritten.
virtual ObjectMotionMap getObjectMotions () const =0
Collects all object motions from 1 to K (with the first motion being from k-1 to k). (Non-pure) Virtual function that may be overwritten - default implementation uses the pure-virtual getObjectPoses to collect all motions.
virtual StatusLandmarkVector getDynamicLandmarkEstimates (FrameId frame_id) const =0
Get all dynamic landmarks for all objects (\mathcal{J}_k) at time-step k.
virtual StatusLandmarkVector getDynamicLandmarkEstimates (FrameId frame_id, ObjectId object_id) const =0
Get all dynamic landmarks for object j at time-step k.
virtual StatusLandmarkVector getStaticLandmarkEstimates (FrameId frame_id) const =0
Get all static landmarks at time-step k.
virtual StatusLandmarkVector getFullStaticMap () const =0
Get all static landmarks from time-step 0 to k.
virtual bool hasObjectMotionEstimate (FrameId frame_id, ObjectId object_id, Motion3 *motion) const =0
Check if there exists an estimate for object motion at time-step (k) for object id (j). If result is true and a motion is provided, return true and set the motion.
virtual bool hasObjectPoseEstimate (FrameId frame_id, ObjectId object_id, gtsam::Pose3 *pose) const =0
Check if there exists an estimate for object pose at time-step (k) for object id (j). If result is true and a pose is provided, return true and set the pose.
virtual gtsam::FastMap< ObjectId, gtsam::Point3 > computeObjectCentroids (FrameId frame_id) const =0
Computes a the centroid of each object at this frame using the estimated dynamic points.
StatusLandmarkVector getLandmarkEstimates (FrameId frame_id) const
Get all landmarks (static and dynamic) at time-step k.
std::tuple< gtsam::Point3, bool > computeObjectCentroid (FrameId frame_id, ObjectId object_id) const
Computes the centroid of the requested object using the estimated dynamic points.
bool hasObjectPoseEstimate (FrameId frame_id, ObjectId object_id, gtsam::Pose3 &pose) const
Check if there exists an estimate for object pose at time-step (k) for object id (j). If result is true, pose reference value is set to the pose.
bool hasObjectMotionEstimate (FrameId frame_id, ObjectId object_id, Motion3 &motion) const
Check if there exists an estimate for object motion at time-step (k) for object id (j). If result is true, motion reference value is set to the motion.
StateQuery< Motion3ReferenceFrame > getObjectMotionReferenceFrame (FrameId frame_id, ObjectId object_id) const
Gets the absolute motion (_{k-1}^wH_k) from theta the requested time-step (k) and object (j) with the associated reference frame. Internally this uses getObjectMotion and constructs a Motion3ReferenceFrame using the global frame, k-1 and k. No checks are done on the underlying function call so it assumes that the virtual getObjectMotion function has been implemented correctly and returns a motion in the right representation.
bool exists (gtsam::Key key) const
Check if the key exists in the current theta. Utilises the derived Accessor::getValueImpl function to check the existance of the variable.
template<typename ValueType >
StateQuery< ValueType > query (gtsam::Key key) const
Access a key in the current theta. Utilises the derived Accessor::getValueImpl function to check the existance of the variable and get the value.
Private Attributes
ObjectPoseMap object_pose_cache_
Additional Inherited Members
Public Types inherited from dyno::AccessorT< MapVision >
using Map = MapVision
using This = AccessorT< Map, Accessor >
Protected Member Functions inherited from dyno::AccessorT< MapVision >
auto map () const
const gtsam::Values & values () const
const FormulationHooks & hooks () const
virtual boost::optional< const gtsam::Value & > getValueImpl (const gtsam::Key key) const =0
Gets the gtsam::Value object as an optional. The existance of the optional indicates existance of the value. We use this functionality as a replacement for the if(exists()) -> return at() paradigm so that the derived class can check and return the value as a single unit which reduces overhead.
Protected Attributes inherited from dyno::Accessor
std::mutex mutex_
Detailed Description
Definition at line 40 of file WorldMotionEstimator.hpp.
Constructor & Destructor Documentation
WorldMotionAccessor()
dyno::WorldMotionAccessor::WorldMotionAccessor (const SharedFormulationData & shared_data, MapVision::Ptr map) inline
Definition at line 42 of file WorldMotionEstimator.hpp.
      : WorldPoseAccessor(shared_data, map) {}
Member Function Documentation
getObjectMotion()
StateQuery< gtsam::Pose3 > dyno::WorldMotionAccessor::getObjectMotion (FrameId frame_id, ObjectId object_id) const override virtual
Get an absolute object motion (_{k-1}^wH_k) from theta the requested time-step (k) and object (j).
Parameters
frame_id FrameId
object_id ObjectId
Returns
StateQuery<gtsam::Pose3>
Reimplemented from dyno::WorldPoseAccessor.
Definition at line 38 of file WorldMotionEstimator.cc.
{
  const auto frame_node_k = map()->getFrame(frame_id);
  CHECK(frame_node_k);
  // from k-1 to k
  return this->query<gtsam::Pose3>(
      frame_node_k->makeObjectMotionKey(object_id));
}
References dyno::AccessorT< MapVision >::map().
getObjectPose()
StateQuery< gtsam::Pose3 > dyno::WorldMotionAccessor::getObjectPose (FrameId frame_id, ObjectId object_id) const override virtual
Get the pose (^wL_k) of an object (j) at time-step (k).
Parameters
frame_id FrameId
object_id ObjectId
Returns
StateQuery<gtsam::Pose3>
Reimplemented from dyno::WorldPoseAccessor.
Definition at line 47 of file WorldMotionEstimator.cc.
{
  const auto object_poses = getObjectPoses(frame_id);
  if (object_poses.exists(object_id)) {
    return StateQuery<gtsam::Pose3>(ObjectPoseSymbol(object_id, frame_id),
                                    object_poses.at(object_id));
  }
  return StateQuery<gtsam::Pose3>::InvalidMap();
}
References getObjectPoses(), dyno::StateQuery< ValueType >::InvalidMap(), and dyno::ObjectPoseSymbol().
getObjectPoses() [1/2]
ObjectPoseMap dyno::WorldMotionAccessor::getObjectPoses () const inline override virtual
Collects all object poses for frame 0 to K. (Non-pure)Virtual function that may be overwritten - default implementation uses the pure-virtual getObjectPoses to collect all poses.
Returns
ObjectPoseMap
Reimplemented from dyno::AccessorT< MapVision >.
Definition at line 51 of file WorldMotionEstimator.hpp.
{
    return object_pose_cache_;
  }
References object_pose_cache_.
Referenced by getObjectPose().
getObjectPoses() [2/2]
EstimateMap< ObjectId, gtsam::Pose3 > dyno::WorldMotionAccessor::getObjectPoses (FrameId frame_id) const override virtual
Collects all object poses at some time-step (k). See Accessor::getObjectPoses(FrameId)
Parameters
frame_id FrameId frame_id) const;
Returns
EstimateMap<ObjectId, gtsam::Pose3>
Reimplemented from dyno::AccessorT< MapVision >.
Definition at line 57 of file WorldMotionEstimator.cc.
{
  EstimateMap<ObjectId, gtsam::Pose3> object_poses;
  // for each object, go over the cached object poses and check if that object
  // has a pose at the query frame
  for (const auto& [object_id, pose] :
       object_pose_cache_.collectByFrame(frame_id)) {
    object_poses.insert2(object_id, ReferenceFrameValue<gtsam::Pose3>(
                                        pose, ReferenceFrame::GLOBAL));
  }
  return object_poses;
}
References dyno::GenericObjectCentricMap< VALUE >::collectByFrame(), dyno::GLOBAL, dyno::GenericObjectCentricMap< VALUE >::insert2(), and object_pose_cache_.
refreshPoseCache()
void dyno::WorldMotionAccessor::refreshPoseCache ()
Update the object pose (cache) estimation based on the latest set of estated values stored in theta!
Should be called after every successful optimisation
Definition at line 70 of file WorldMotionEstimator.cc.
{
  // this is pretty slow!!
  // update object_pose_cache_ with new values
  // this means we have to start again at the first frame and update all the
  // poses!!
  ObjectPoseMap object_poses;
  const auto frames = map()->getFrames();
  auto frame_itr = frames.begin();
  const auto& gt_packet_map = hooks().ground_truth_packets_request();
  // advance itr one so we're now at the second frame
  std::advance(frame_itr, 1);
  for (auto itr = frame_itr; itr != frames.end(); itr++) {
    auto prev_itr = itr;
    std::advance(prev_itr, -1);
    CHECK(prev_itr != frames.end());
    const auto [frame_id_k, frame_k_ptr] = *itr;
    const auto [frame_id_k_1, frame_k_1_ptr] = *prev_itr;
    CHECK_EQ(frame_id_k_1 + 1, frame_id_k);
    // collect all object centoids from the latest estimate
    gtsam::FastMap<ObjectId, gtsam::Point3> centroids_k =
        this->computeObjectCentroids(frame_id_k);
    gtsam::FastMap<ObjectId, gtsam::Point3> centroids_k_1 =
        this->computeObjectCentroids(frame_id_k_1);
    // collect motions from k-1 to k
    MotionEstimateMap motion_estimates = this->getObjectMotions(frame_id_k);
    // construct centroid vectors in object id order
    gtsam::Point3Vector object_centroids_k_1, object_centroids_k;
    // we may not have a pose for every motion, e.g. if there is a new object at
    // frame k, it wont have a motion yet! if we have a motion we MUST have a
    // pose at the previous frame!
    for (const auto& [object_id, _] : motion_estimates) {
      CHECK(centroids_k.exists(object_id));
      CHECK(centroids_k_1.exists(object_id));
      object_centroids_k.push_back(centroids_k.at(object_id));
      object_centroids_k_1.push_back(centroids_k_1.at(object_id));
    }
    PropogatePoseResult propogation_result;
    if (FLAGS_init_object_pose_from_gt) {
      if (!gt_packet_map)
        LOG(WARNING) << "FLAGS_init_object_pose_from_gt is true but gt_packet "
                        "map not provided!";
      dyno::propogateObjectPoses(
          object_poses, motion_estimates, object_centroids_k_1,
          object_centroids_k, frame_id_k, gt_packet_map, &propogation_result);
    } else {
      dyno::propogateObjectPoses(object_poses, motion_estimates,
                                 object_centroids_k_1, object_centroids_k,
                                 frame_id_k, std::nullopt, &propogation_result);
    }
    if (VLOG_IS_ON(20)) {
      // report on how many were propogated with motions for this frame only
      const auto propogation_type =
          propogation_result.collectByFrame(frame_id_k);
      std::stringstream ss;
      ss << "Propogation result: " << propogation_type.size()
         << " objects for frame " << frame_id_k;
      size_t n_used_motion = 0;
      for (const auto& [_, type] : propogation_type) {
        if (type == PropogateType::Propogate) {
          n_used_motion++;
        }
      }
      ss << " of which " << n_used_motion << " were motion propogated";
      VLOG(100) << ss.str();
    }
  }
  VLOG(50) << "Updated object pose cache";
  object_pose_cache_ = object_poses;
  LOG(INFO) << "ending MotionWorldAccessor::postUpdateCallback";
}
References dyno::GenericObjectCentricMap< VALUE >::collectByFrame(), dyno::AccessorT< MapVision >::computeObjectCentroids(), dyno::AccessorT< MapVision >::getObjectMotions(), dyno::FormulationHooks::ground_truth_packets_request, dyno::AccessorT< MapVision >::hooks(), dyno::AccessorT< MapVision >::map(), object_pose_cache_, dyno::Propogate, and dyno::propogateObjectPoses().
Member Data Documentation
object_pose_cache_
ObjectPoseMap dyno::WorldMotionAccessor::object_pose_cache_ private
Definition at line 67 of file WorldMotionEstimator.hpp.
Referenced by getObjectPoses(), and refreshPoseCache().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/backend/rgbd/WorldMotionEstimator.hpp
dynosam/src/backend/rgbd/WorldMotionEstimator.cc