DynoSAM: dyno::utils::Accumulator< SampleType, SumType, WindowSize > Class Template Reference
dyno::utils::Accumulator< SampleType, SumType, WindowSize > Class Template Reference
#include <Accumulator.hpp>
Public Types
using This = Accumulator< SampleType, SumType, WindowSize >
Public Member Functions
Accumulator ()
void Add (SampleType sample)
int total_samples () const
SumType sum () const
SumType Mean () const
SumType RollingMean () const
SampleType GetMostRecent () const
SumType max () const
SumType min () const
SumType median () const
SumType q1 () const
SumType q3 () const
SumType LazyVariance () const
SumType StandardDeviation () const
This OutlierRejectionStd (double threshold)
const std::vector< SampleType > & GetAllSamples () const
std::vector< SampleType >::iterator begin ()
const std::vector< SampleType >::iterator begin () const
std::vector< SampleType >::iterator end ()
const std::vector< SampleType >::iterator end () const
const std::vector< SampleType >::const_iterator cbegin () const
const std::vector< SampleType >::const_iterator cend () const
Private Attributes
std::vector< SampleType > samples_
int sample_index_
int total_samples_
SumType sum_
SumType window_sum_
SampleType min_
SampleType max_
SampleType most_recent_
Detailed Description
template<typename SampleType, typename SumType, int WindowSize>
class dyno::utils::Accumulator< SampleType, SumType, WindowSize >
Definition at line 79 of file Accumulator.hpp.
Member Typedef Documentation
This
template<typename SampleType , typename SumType , int WindowSize> using dyno::utils::Accumulator< SampleType, SumType, WindowSize >::This = Accumulator<SampleType, SumType, WindowSize>
Definition at line 81 of file Accumulator.hpp.
Constructor & Destructor Documentation
Accumulator()
template<typename SampleType , typename SumType , int WindowSize> dyno::utils::Accumulator< SampleType, SumType, WindowSize >::Accumulator () inline
Definition at line 82 of file Accumulator.hpp.
      : sample_index_(0),
        total_samples_(0),
        sum_(0),
        window_sum_(0),
        min_(std::numeric_limits<SampleType>::max()),
        max_(std::numeric_limits<SampleType>::lowest()),
        most_recent_(0) {
    CHECK_GT(WindowSize, 0);
    if (WindowSize < kInfiniteWindowSize) {
      samples_.reserve(WindowSize);
    }
  }
References dyno::utils::kInfiniteWindowSize, and dyno::utils::Accumulator< SampleType, SumType, WindowSize >::samples_.
Member Function Documentation
Add()
template<typename SampleType , typename SumType , int WindowSize> void dyno::utils::Accumulator< SampleType, SumType, WindowSize >::Add (SampleType sample) inline
Definition at line 97 of file Accumulator.hpp.
{
    most_recent_ = sample;
    if (sample_index_ < WindowSize) {
      samples_.push_back(sample);
      window_sum_ += sample;
      ++sample_index_;
    } else {
      SampleType& oldest = samples_.at(sample_index_++ % WindowSize);
      window_sum_ += sample - oldest;
      oldest = sample;
    }
    sum_ += sample;
    ++total_samples_;
    if (sample > max_) {
      max_ = sample;
    }
    if (sample < min_) {
      min_ = sample;
    }
  }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::max_, dyno::utils::Accumulator< SampleType, SumType, WindowSize >::min_, dyno::utils::Accumulator< SampleType, SumType, WindowSize >::most_recent_, dyno::utils::Accumulator< SampleType, SumType, WindowSize >::sample_index_, dyno::utils::Accumulator< SampleType, SumType, WindowSize >::samples_, dyno::utils::Accumulator< SampleType, SumType, WindowSize >::sum_, dyno::utils::Accumulator< SampleType, SumType, WindowSize >::total_samples_, and dyno::utils::Accumulator< SampleType, SumType, WindowSize >::window_sum_.
Referenced by dyno::utils::StatisticsMapValue::AddValue(), and dyno::utils::Accumulator< SampleType, SumType, WindowSize >::OutlierRejectionStd().
begin() [1/2]
template<typename SampleType , typename SumType , int WindowSize> std::vector< SampleType >::iterator dyno::utils::Accumulator< SampleType, SumType, WindowSize >::begin () inline
Definition at line 213 of file Accumulator.hpp.
{
    return samples_.begin();
  }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::samples_.
begin() [2/2]
template<typename SampleType , typename SumType , int WindowSize> const std::vector< SampleType >::iterator dyno::utils::Accumulator< SampleType, SumType, WindowSize >::begin () const inline
Definition at line 216 of file Accumulator.hpp.
{
    return samples_.begin();
  }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::samples_.
cbegin()
template<typename SampleType , typename SumType , int WindowSize> const std::vector< SampleType >::const_iterator dyno::utils::Accumulator< SampleType, SumType, WindowSize >::cbegin () const inline
Definition at line 225 of file Accumulator.hpp.
{
    return samples_.cbegin();
  }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::samples_.
cend()
template<typename SampleType , typename SumType , int WindowSize> const std::vector< SampleType >::const_iterator dyno::utils::Accumulator< SampleType, SumType, WindowSize >::cend () const inline
Definition at line 228 of file Accumulator.hpp.
{
    return samples_.cend();
  }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::samples_.
end() [1/2]
template<typename SampleType , typename SumType , int WindowSize> std::vector< SampleType >::iterator dyno::utils::Accumulator< SampleType, SumType, WindowSize >::end () inline
Definition at line 220 of file Accumulator.hpp.
{ return samples_.end(); }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::samples_.
end() [2/2]
template<typename SampleType , typename SumType , int WindowSize> const std::vector< SampleType >::iterator dyno::utils::Accumulator< SampleType, SumType, WindowSize >::end () const inline
Definition at line 221 of file Accumulator.hpp.
{
    return samples_.end();
  }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::samples_.
GetAllSamples()
template<typename SampleType , typename SumType , int WindowSize> const std::vector< SampleType > & dyno::utils::Accumulator< SampleType, SumType, WindowSize >::GetAllSamples () const inline
Definition at line 211 of file Accumulator.hpp.
{ return samples_; }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::samples_.
Referenced by dyno::utils::StatisticsMapValue::GetAllValues().
GetMostRecent()
template<typename SampleType , typename SumType , int WindowSize> SampleType dyno::utils::Accumulator< SampleType, SumType, WindowSize >::GetMostRecent () const inline
Definition at line 142 of file Accumulator.hpp.
{ return most_recent_; }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::most_recent_.
Referenced by dyno::utils::StatisticsMapValue::GetLastDeltaTime(), and dyno::utils::StatisticsMapValue::GetLastValue().
LazyVariance()
template<typename SampleType , typename SumType , int WindowSize> SumType dyno::utils::Accumulator< SampleType, SumType, WindowSize >::LazyVariance () const inline
Definition at line 172 of file Accumulator.hpp.
{
    if (samples_.size() < 2) {
      return 0.0;
    }
    SumType var = static_cast<SumType>(0.0);
    SumType mean = RollingMean();
    for (unsigned int i = 0; i < samples_.size(); ++i) {
      var += (samples_[i] - mean) * (samples_[i] - mean);
    }
    var /= samples_.size() - 1;
    return var;
  }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::RollingMean(), and dyno::utils::Accumulator< SampleType, SumType, WindowSize >::samples_.
Referenced by dyno::utils::StatisticsMapValue::LazyVariance(), dyno::utils::StatisticsMapValue::LazyVarianceDeltaTime(), and dyno::utils::Accumulator< SampleType, SumType, WindowSize >::StandardDeviation().
max()
template<typename SampleType , typename SumType , int WindowSize> SumType dyno::utils::Accumulator< SampleType, SumType, WindowSize >::max () const inline
Definition at line 145 of file Accumulator.hpp.
{ return max_; }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::max_.
Referenced by dyno::utils::StatisticsMapValue::Max(), and dyno::utils::StatisticsMapValue::MaxDeltaTime().
Mean()
template<typename SampleType , typename SumType , int WindowSize> SumType dyno::utils::Accumulator< SampleType, SumType, WindowSize >::Mean () const inline
Definition at line 125 of file Accumulator.hpp.
                       {
    return (total_samples_ < 1) ? 0.0
                                : sum_ / static_cast<SumType>(total_samples_);
  }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::sum_, and dyno::utils::Accumulator< SampleType, SumType, WindowSize >::total_samples_.
Referenced by dyno::utils::StatisticsMapValue::Mean(), dyno::utils::StatisticsMapValue::MeanCallsPerSec(), dyno::utils::StatisticsMapValue::MeanDeltaTime(), dyno::utils::Accumulator< SampleType, SumType, WindowSize >::OutlierRejectionStd(), and dyno::utils::Accumulator< SampleType, SumType, WindowSize >::RollingMean().
median()
template<typename SampleType , typename SumType , int WindowSize> SumType dyno::utils::Accumulator< SampleType, SumType, WindowSize >::median () const inline
Definition at line 151 of file Accumulator.hpp.
{
    CHECK_GT(samples_.size(), 0);
    return samples_.at(std::ceil(samples_.size() / 2) - 1);
  }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::samples_.
Referenced by dyno::utils::StatisticsMapValue::Median().
min()
template<typename SampleType , typename SumType , int WindowSize> SumType dyno::utils::Accumulator< SampleType, SumType, WindowSize >::min () const inline
Definition at line 148 of file Accumulator.hpp.
{ return min_; }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::min_.
Referenced by dyno::utils::StatisticsMapValue::Min(), and dyno::utils::StatisticsMapValue::MinDeltaTime().
OutlierRejectionStd()
template<typename SampleType , typename SumType , int WindowSize> This dyno::utils::Accumulator< SampleType, SumType, WindowSize >::OutlierRejectionStd (double threshold) inline
Definition at line 193 of file Accumulator.hpp.
{
    const auto mean = Mean();
    const auto std = StandardDeviation();
    const auto min_value = mean - threshold * std;
    const auto max_value = mean + threshold * std;
    This filtered;
    for (auto value : *this) {
      if (value > min_value && value < max_value) {
        filtered.Add(value);
      }
    }
    return filtered;
  }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::Add(), dyno::utils::Accumulator< SampleType, SumType, WindowSize >::Mean(), and dyno::utils::Accumulator< SampleType, SumType, WindowSize >::StandardDeviation().
q1()
template<typename SampleType , typename SumType , int WindowSize> SumType dyno::utils::Accumulator< SampleType, SumType, WindowSize >::q1 () const inline
Definition at line 159 of file Accumulator.hpp.
{
    CHECK_GT(samples_.size(), 0);
    return samples_.at(std::ceil(samples_.size() / 4) - 1);
  }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::samples_.
Referenced by dyno::utils::StatisticsMapValue::Q1().
q3()
template<typename SampleType , typename SumType , int WindowSize> SumType dyno::utils::Accumulator< SampleType, SumType, WindowSize >::q3 () const inline
Definition at line 166 of file Accumulator.hpp.
{
    CHECK_GT(samples_.size(), 0);
    return samples_.at(std::ceil(samples_.size() * 3 / 4) - 1);
  }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::samples_.
Referenced by dyno::utils::StatisticsMapValue::Q3().
RollingMean()
template<typename SampleType , typename SumType , int WindowSize> SumType dyno::utils::Accumulator< SampleType, SumType, WindowSize >::RollingMean () const inline
Definition at line 133 of file Accumulator.hpp.
{
    if (WindowSize < kInfiniteWindowSize) {
      return window_sum_ / std::min(sample_index_, WindowSize);
    } else {
      return Mean();
    }
  }
References dyno::utils::kInfiniteWindowSize, dyno::utils::Accumulator< SampleType, SumType, WindowSize >::Mean(), dyno::utils::Accumulator< SampleType, SumType, WindowSize >::sample_index_, and dyno::utils::Accumulator< SampleType, SumType, WindowSize >::window_sum_.
Referenced by dyno::utils::Accumulator< SampleType, SumType, WindowSize >::LazyVariance(), dyno::utils::StatisticsMapValue::RollingMean(), and dyno::utils::StatisticsMapValue::RollingMeanDeltaTime().
StandardDeviation()
template<typename SampleType , typename SumType , int WindowSize> SumType dyno::utils::Accumulator< SampleType, SumType, WindowSize >::StandardDeviation () const inline
Definition at line 189 of file Accumulator.hpp.
{ return std::sqrt(LazyVariance()); }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::LazyVariance().
Referenced by dyno::utils::Accumulator< SampleType, SumType, WindowSize >::OutlierRejectionStd().
sum()
template<typename SampleType , typename SumType , int WindowSize> SumType dyno::utils::Accumulator< SampleType, SumType, WindowSize >::sum () const inline
Definition at line 122 of file Accumulator.hpp.
{ return sum_; }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::sum_.
Referenced by dyno::utils::StatisticsMapValue::Sum().
total_samples()
template<typename SampleType , typename SumType , int WindowSize> int dyno::utils::Accumulator< SampleType, SumType, WindowSize >::total_samples () const inline
Definition at line 119 of file Accumulator.hpp.
{ return total_samples_; }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::total_samples_.
Referenced by dyno::utils::StatisticsMapValue::GetLastDeltaTime(), dyno::utils::StatisticsMapValue::GetLastValue(), and dyno::utils::StatisticsMapValue::TotalSamples().
Member Data Documentation
max_
template<typename SampleType , typename SumType , int WindowSize> SampleType dyno::utils::Accumulator< SampleType, SumType, WindowSize >::max_ private
Definition at line 239 of file Accumulator.hpp.
Referenced by dyno::utils::Accumulator< SampleType, SumType, WindowSize >::Add(), and dyno::utils::Accumulator< SampleType, SumType, WindowSize >::max().
min_
template<typename SampleType , typename SumType , int WindowSize> SampleType dyno::utils::Accumulator< SampleType, SumType, WindowSize >::min_ private
Definition at line 238 of file Accumulator.hpp.
Referenced by dyno::utils::Accumulator< SampleType, SumType, WindowSize >::Add(), and dyno::utils::Accumulator< SampleType, SumType, WindowSize >::min().
most_recent_
template<typename SampleType , typename SumType , int WindowSize> SampleType dyno::utils::Accumulator< SampleType, SumType, WindowSize >::most_recent_ private
Definition at line 240 of file Accumulator.hpp.
Referenced by dyno::utils::Accumulator< SampleType, SumType, WindowSize >::Add(), and dyno::utils::Accumulator< SampleType, SumType, WindowSize >::GetMostRecent().
sample_index_
template<typename SampleType , typename SumType , int WindowSize> int dyno::utils::Accumulator< SampleType, SumType, WindowSize >::sample_index_ private
Definition at line 234 of file Accumulator.hpp.
Referenced by dyno::utils::Accumulator< SampleType, SumType, WindowSize >::Add(), and dyno::utils::Accumulator< SampleType, SumType, WindowSize >::RollingMean().
samples_
template<typename SampleType , typename SumType , int WindowSize> std::vector<SampleType> dyno::utils::Accumulator< SampleType, SumType, WindowSize >::samples_ private
Definition at line 233 of file Accumulator.hpp.
Referenced by dyno::utils::Accumulator< SampleType, SumType, WindowSize >::Accumulator(), dyno::utils::Accumulator< SampleType, SumType, WindowSize >::Add(), dyno::utils::Accumulator< SampleType, SumType, WindowSize >::begin(), dyno::utils::Accumulator< SampleType, SumType, WindowSize >::cbegin(), dyno::utils::Accumulator< SampleType, SumType, WindowSize >::cend(), dyno::utils::Accumulator< SampleType, SumType, WindowSize >::end(), dyno::utils::Accumulator< SampleType, SumType, WindowSize >::GetAllSamples(), dyno::utils::Accumulator< SampleType, SumType, WindowSize >::LazyVariance(), dyno::utils::Accumulator< SampleType, SumType, WindowSize >::median(), dyno::utils::Accumulator< SampleType, SumType, WindowSize >::q1(), and dyno::utils::Accumulator< SampleType, SumType, WindowSize >::q3().
sum_
template<typename SampleType , typename SumType , int WindowSize> SumType dyno::utils::Accumulator< SampleType, SumType, WindowSize >::sum_ private
Definition at line 236 of file Accumulator.hpp.
Referenced by dyno::utils::Accumulator< SampleType, SumType, WindowSize >::Add(), dyno::utils::Accumulator< SampleType, SumType, WindowSize >::Mean(), and dyno::utils::Accumulator< SampleType, SumType, WindowSize >::sum().
total_samples_
template<typename SampleType , typename SumType , int WindowSize> int dyno::utils::Accumulator< SampleType, SumType, WindowSize >::total_samples_ private
Definition at line 235 of file Accumulator.hpp.
Referenced by dyno::utils::Accumulator< SampleType, SumType, WindowSize >::Add(), dyno::utils::Accumulator< SampleType, SumType, WindowSize >::Mean(), and dyno::utils::Accumulator< SampleType, SumType, WindowSize >::total_samples().
window_sum_
template<typename SampleType , typename SumType , int WindowSize> SumType dyno::utils::Accumulator< SampleType, SumType, WindowSize >::window_sum_ private
Definition at line 237 of file Accumulator.hpp.
Referenced by dyno::utils::Accumulator< SampleType, SumType, WindowSize >::Add(), and dyno::utils::Accumulator< SampleType, SumType, WindowSize >::RollingMean().
The documentation for this class was generated from the following file:
dynosam_common/include/dynosam_common/utils/Accumulator.hpp