DynoSAM: dyno::ClusterSlamAllLoader Class Reference
dyno::ClusterSlamAllLoader Class Reference
As there is so much interdependancy between the folders in the dataset, we just have the one loader so all the data can be accessed in the same class. This class then provides interfaces for each dyno::DataFolder<....> so that the Dynodataset can use it!
Public Member Functions
ClusterSlamAllLoader (const std::string &file_path)
Construct a new Cluster Slam Gt Loader object.
size_t size () const
cv::Mat getOpticalFlow (size_t idx) const
cv::Mat getRGB (size_t idx) const
cv::Mat getRightRGB (size_t idx) const
cv::Mat getInstanceMask (size_t idx) const
cv::Mat getDepthImage (size_t idx) const
const GroundTruthInputPacket & getGtPacket (size_t idx) const
const CameraParams & getLeftCameraParams () const
double getTimestamp (size_t idx)
Private Types
using LandmarksMap = gtsam::FastMap< int, Keypoint >
using LandmarksMapPerFrame = gtsam::FastMap< FrameId, LandmarksMap >
Private Member Functions
void loadFlowImagesAndSize (std::vector< std::string > &images_paths, size_t &dataset_size)
void loadImages (std::vector< std::string > &images_paths, const std::string &image_folder)
void loadInstanceMasksImages (std::vector< std::string > &images_paths)
void setIntrisics ()
cv::Mat denseStereoReconstruction (size_t frame) const
void loadLeftLandmarks (LandmarksMapPerFrame &detected_landmarks)
void loadLandMarkMapping (gtsam::FastMap< int, int > &landmark_mapping)
void associateDetectedBBWithObject (const cv::Mat &instance_mask, FrameId frame_id, cv::Mat &relabelled_mask) const
void setGroundTruthPacket (GroundTruthPacketMap &ground_truth_packets)
gtsam::Pose3Vector processPoseFile (const std::string &pose_file, GroundTruthPacketMap &ground_truth_packets)
Private Attributes
const std::string left_images_folder_path_
const std::string optical_flow_folder_path_
const std::string pose_folder_path_
const std::string left_landmarks_folder_
const std::string right_images_folder_path_
const std::string instance_masks_folder_
const std::string landmark_mapping_file_path_
const std::string intrinsics_file_path_
std::vector< std::string > left_rgb_image_paths_
std::vector< std::string > right_rgb_image_paths_
std::vector< std::string > optical_flow_image_paths_
std::vector< std::string > instance_masks_image_paths_
LandmarksMapPerFrame left_landmarks_map_
gtsam::FastMap< FrameId, cv::Mat > instance_masks_
gtsam::FastMap< int, int > landmark_mapping_
gtsam::Matrix33 K_cam_1
gtsam::Matrix33 K_cam_2
gtsam::Matrix34 projection_matrix_cam1_
gtsam::Matrix34 projection_matrix_cam2_
CameraParams left_camera_params_
StereoCamera::Ptr stereo_camera_
StereoMatcher::Ptr stereo_matcher_
GroundTruthPacketMap ground_truth_packets_
size_t dataset_size_
Detailed Description
As there is so much interdependancy between the folders in the dataset, we just have the one loader so all the data can be accessed in the same class. This class then provides interfaces for each dyno::DataFolder<....> so that the Dynodataset can use it!
Definition at line 56 of file ClusterSlamDataProvider.cc.
Member Typedef Documentation
LandmarksMap
using dyno::ClusterSlamAllLoader::LandmarksMap = gtsam::FastMap<int, Keypoint> private
Definition at line 356 of file ClusterSlamDataProvider.cc.
LandmarksMapPerFrame
using dyno::ClusterSlamAllLoader::LandmarksMapPerFrame = gtsam::FastMap<FrameId, LandmarksMap> private
Definition at line 357 of file ClusterSlamDataProvider.cc.
Constructor & Destructor Documentation
ClusterSlamAllLoader()
dyno::ClusterSlamAllLoader::ClusterSlamAllLoader (const std::string & file_path) inline
Construct a new Cluster Slam Gt Loader object.
File path is the full file path to a clusterslam folder, containing /images /pose....
Parameters
file_path const std::string&
Definition at line 69 of file ClusterSlamDataProvider.cc.
      : left_images_folder_path_(file_path + "/images/left"),
        right_images_folder_path_(file_path + "/images/right"),
        optical_flow_folder_path_(file_path + "/optical_flow"),
        pose_folder_path_(file_path + "/pose"),
        instance_masks_folder_(file_path + "/instance_masks"),
        left_landmarks_folder_(file_path + "/landmarks/left"),
        landmark_mapping_file_path_(file_path + "/landmark_mapping.txt"),
        intrinsics_file_path_(file_path + "/intrinsic.txt") {
    throwExceptionIfPathInvalid(left_images_folder_path_);
    throwExceptionIfPathInvalid(right_images_folder_path_);
    throwExceptionIfPathInvalid(optical_flow_folder_path_);
    throwExceptionIfPathInvalid(pose_folder_path_);
    throwExceptionIfPathInvalid(instance_masks_folder_);
    throwExceptionIfPathInvalid(left_landmarks_folder_);
    throwExceptionIfPathInvalid(landmark_mapping_file_path_);
    throwExceptionIfPathInvalid(intrinsics_file_path_);
    // first load images and size
    // the size will be used as a refernce for all other loaders
    // size is number of images
    // we use flow to set the size as for this dataset, there will be one less
    // optical flow as the flow ids index t to t+1 (which is gross, I know!!)
    loadFlowImagesAndSize(optical_flow_image_paths_, dataset_size_);
    // left
    loadImages(left_rgb_image_paths_, left_images_folder_path_);
    // right
    loadImages(right_rgb_image_paths_, right_images_folder_path_);
    CHECK_EQ(right_rgb_image_paths_.size(), left_rgb_image_paths_.size());
    loadInstanceMasksImages(instance_masks_image_paths_);
    loadLeftLandmarks(left_landmarks_map_);
    loadLandMarkMapping(landmark_mapping_);
    CHECK_EQ(optical_flow_image_paths_.size(),
             left_rgb_image_paths_.size() - 1);
    CHECK_EQ(instance_masks_image_paths_.size(),
             optical_flow_image_paths_.size());
    CHECK_EQ(size(), optical_flow_image_paths_.size());
    setGroundTruthPacket(ground_truth_packets_);
    setIntrisics();
  }
References dataset_size_, ground_truth_packets_, instance_masks_folder_, instance_masks_image_paths_, intrinsics_file_path_, landmark_mapping_, landmark_mapping_file_path_, left_images_folder_path_, left_landmarks_folder_, left_landmarks_map_, left_rgb_image_paths_, loadFlowImagesAndSize(), loadImages(), loadInstanceMasksImages(), loadLandMarkMapping(), loadLeftLandmarks(), optical_flow_folder_path_, optical_flow_image_paths_, pose_folder_path_, right_images_folder_path_, right_rgb_image_paths_, setGroundTruthPacket(), setIntrisics(), size(), and dyno::throwExceptionIfPathInvalid().
Member Function Documentation
associateDetectedBBWithObject()
void dyno::ClusterSlamAllLoader::associateDetectedBBWithObject (const cv::Mat & instance_mask, FrameId frame_id, cv::Mat & relabelled_mask) const inline private
Definition at line 449 of file ClusterSlamDataProvider.cc.
{
    const GroundTruthInputPacket& gt_packet = getGtPacket(frame_id);
    ObjectIds object_ids = vision_tools::getObjectLabels(instance_mask);
    const size_t n = object_ids.size();
    instance_mask.copyTo(relabelled_mask);
    if (n == 0) {
      return;
    }
    // sort kps map into a map of clusters -> [kps....]
    const LandmarksMap& kps_map = left_landmarks_map_.at(frame_id);
    // cluster id (track id -> all keypoints for that cluster)
    std::set<int> cluster_id_set;
    gtsam::FastMap<int, Keypoints> clustered_kps;
    for (const auto& [landmark_id, kp] : kps_map) {
      const auto cluster_id = landmark_mapping_.at(landmark_id);
      cluster_id_set.insert(cluster_id);
      if (!clustered_kps.exists(cluster_id)) {
        clustered_kps.insert2(cluster_id, Keypoints());
      }
      clustered_kps.at(cluster_id).push_back(kp);
    }
    std::vector<int> cluster_ids(cluster_id_set.begin(), cluster_id_set.end());
    // want to assign object ids to clusters
    const size_t m = cluster_ids.size();
    CHECK_EQ(m, clustered_kps.size());
    LOG(INFO) << n << " " << m;
    Eigen::MatrixXd cost;
    cost.resize(n, m);
    for (size_t rows = 0; rows < n; rows++) {
      ObjectId object_id = object_ids.at(rows);
      // get the binary mask just for this object, we will use this too find a
      // bounding box
      // and count how many kp's fall into this mask
      const cv::Mat object_mask = relabelled_mask == object_id;
      cv::Rect bb;
      if (!vision_tools::findObjectBoundingBox(instance_mask, object_id, bb)) {
        VLOG(10) << "No bb could be found for detected object " << object_id
                 << " at frame " << frame_id
                 << ". Skipping association and removing object from mask";
        relabelled_mask.setTo(cv::Scalar(0), object_mask);
        continue;
      }
      for (size_t cols = 0; cols < m; cols++) {
        int cluster_id = cluster_ids.at(cols);
        const Keypoints& kps = clustered_kps.at(cluster_id);
        //(inverse) cost for the object id with this cluster id
        // hack - make really small number so we divide by zero!!
        double object_count = 0.000001;
        for (const auto& kp : kps) {
          cv::Point2f pt(utils::gtsamPointToCv(kp));
          if (bb.contains(pt)) {
            object_count++;
          }
        }
        cost(rows, cols) = object_count;
      }
    }
    // apply scaling to the costs to turn the cost function from an argmax to an
    // argmin problem which the hungrian problem sovles ie we want the
    // assignment that maximuses the number of kp's in the object insancec
    Eigen::MatrixXd loged_costs =
        cost.unaryExpr([](double x) { return 1.0 / x * 10; });
    Eigen::VectorXi assignment;
    internal::HungarianAlgorithm().solve(loged_costs, assignment);
    // for(size_t i = 0; i < assignment.size(); i++) {
    //     int j = assignment[i];
    //     //the i-th object is assignment to the j-th cluster
    //     ObjectId object_id = object_ids.at(i);
    //     int assigned_custer = cluster_ids.at(j);
    //     const cv::Mat object_mask = relabelled_mask == object_id;
    //     relabelled_mask.setTo(cv::Scalar(assigned_custer), object_mask);
    // }
    ObjectIds old_labels = object_ids;
    ObjectIds new_labels;
    for (size_t i = 0; i < assignment.size(); i++) {
      int j = assignment[i];
      // //the i-th object is assignment to the j-th cluster
      // ObjectId instance_id = instance_ids.at(i);
      int assigned_custer = cluster_ids.at(j);
      new_labels.push_back(assigned_custer);
      // LOG(INFO) << "Relabelled " << instance_id << " to " <<
      // assigned_object_id;
      // const cv::Mat object_mask = relabelled_mask == instance_id;
      // relabelled_mask.setTo(cv::Scalar(assigned_object_id), object_mask);
    }
    vision_tools::relabelMasks(instance_mask, relabelled_mask, old_labels,
                               new_labels);
  }
References dyno::vision_tools::findObjectBoundingBox(), getGtPacket(), dyno::vision_tools::getObjectLabels(), dyno::utils::gtsamPointToCv(), landmark_mapping_, left_landmarks_map_, dyno::vision_tools::relabelMasks(), and dyno::internal::HungarianAlgorithm::solve().
Referenced by getInstanceMask().
denseStereoReconstruction()
cv::Mat dyno::ClusterSlamAllLoader::denseStereoReconstruction (size_t frame) const inline private
Definition at line 341 of file ClusterSlamDataProvider.cc.
{
    cv::Mat rgb_left = getRGB(frame);
    cv::Mat rgb_right = getRightRGB(frame);
    // this set of images are loaded as 8UC4
    CHECK_EQ(rgb_right.type(), CV_8UC4)
        << "Somehow the image type has changed...";
    cv::Mat depth_image;
    CHECK_NOTNULL(stereo_matcher_)
        ->denseStereoReconstruction(rgb_left, rgb_right, depth_image);
    return depth_image;
  }
References getRGB(), getRightRGB(), and stereo_matcher_.
Referenced by getDepthImage().
getDepthImage()
cv::Mat dyno::ClusterSlamAllLoader::getDepthImage (size_t idx) const inline
Definition at line 158 of file ClusterSlamDataProvider.cc.
{
    return denseStereoReconstruction(idx);
  }
References denseStereoReconstruction().
getGtPacket()
const GroundTruthInputPacket & dyno::ClusterSlamAllLoader::getGtPacket (size_t idx) const inline
Definition at line 162 of file ClusterSlamDataProvider.cc.
{
    return ground_truth_packets_.at(idx);
  }
References ground_truth_packets_.
Referenced by associateDetectedBBWithObject().
getInstanceMask()
cv::Mat dyno::ClusterSlamAllLoader::getInstanceMask (size_t idx) const inline
Definition at line 145 of file ClusterSlamDataProvider.cc.
{
    CHECK_LT(idx, left_rgb_image_paths_.size());
    CHECK_LT(idx, dataset_size_);
    cv::Mat mask, relabelled_mask;
    loadMask(instance_masks_image_paths_.at(idx), mask);
    CHECK(!mask.empty());
    associateDetectedBBWithObject(mask, idx, relabelled_mask);
    return relabelled_mask;
  }
References associateDetectedBBWithObject(), dataset_size_, instance_masks_image_paths_, left_rgb_image_paths_, and dyno::loadMask().
getLeftCameraParams()
const CameraParams & dyno::ClusterSlamAllLoader::getLeftCameraParams () const inline
Definition at line 166 of file ClusterSlamDataProvider.cc.
{
    return left_camera_params_;
  }
References left_camera_params_.
getOpticalFlow()
cv::Mat dyno::ClusterSlamAllLoader::getOpticalFlow (size_t idx) const inline
Definition at line 116 of file ClusterSlamDataProvider.cc.
{
    CHECK_LT(idx, optical_flow_image_paths_.size());
    cv::Mat flow;
    loadFlow(optical_flow_image_paths_.at(idx), flow);
    CHECK(!flow.empty());
    return flow;
  }
References dyno::loadFlow(), and optical_flow_image_paths_.
getRGB()
cv::Mat dyno::ClusterSlamAllLoader::getRGB (size_t idx) const inline
Definition at line 125 of file ClusterSlamDataProvider.cc.
{
    CHECK_LT(idx, left_rgb_image_paths_.size());
    cv::Mat rgb;
    loadRGB(left_rgb_image_paths_.at(idx), rgb);
    CHECK(!rgb.empty());
    return rgb;
  }
References left_rgb_image_paths_, and dyno::loadRGB().
Referenced by denseStereoReconstruction(), and setIntrisics().
getRightRGB()
cv::Mat dyno::ClusterSlamAllLoader::getRightRGB (size_t idx) const inline
Definition at line 135 of file ClusterSlamDataProvider.cc.
{
    cv::Mat rgb_right;
    CHECK_LT(idx, right_rgb_image_paths_.size());
    loadRGB(right_rgb_image_paths_.at(idx), rgb_right);
    CHECK(!rgb_right.empty());
    return rgb_right;
  }
References dyno::loadRGB(), and right_rgb_image_paths_.
Referenced by denseStereoReconstruction().
getTimestamp()
double dyno::ClusterSlamAllLoader::getTimestamp (size_t idx) inline
Definition at line 170 of file ClusterSlamDataProvider.cc.
{
    // we dont have a time? for now just make idx
    return static_cast<double>(idx);
  }
Referenced by setGroundTruthPacket().
loadFlowImagesAndSize()
void dyno::ClusterSlamAllLoader::loadFlowImagesAndSize (std::vector< std::string > & images_paths, size_t & dataset_size) inline private
Definition at line 176 of file ClusterSlamDataProvider.cc.
{
    std::vector<std::filesystem::path> files_in_directory =
        getAllFilesInDir(optical_flow_folder_path_);
    dataset_size = files_in_directory.size();
    CHECK_GT(dataset_size, 0);
    for (const std::string file_path : files_in_directory) {
      throwExceptionIfPathInvalid(file_path);
      images_paths.push_back(file_path);
    }
  }
References dyno::getAllFilesInDir(), optical_flow_folder_path_, and dyno::throwExceptionIfPathInvalid().
Referenced by ClusterSlamAllLoader().
loadImages()
void dyno::ClusterSlamAllLoader::loadImages (std::vector< std::string > & images_paths, const std::string & image_folder) inline private
Definition at line 189 of file ClusterSlamDataProvider.cc.
{
    std::vector<std::filesystem::path> files_in_directory =
        getAllFilesInDir(image_folder);
    for (const std::string file_path : files_in_directory) {
      throwExceptionIfPathInvalid(file_path);
      images_paths.push_back(file_path);
    }
  }
References dyno::getAllFilesInDir(), and dyno::throwExceptionIfPathInvalid().
Referenced by ClusterSlamAllLoader().
loadInstanceMasksImages()
void dyno::ClusterSlamAllLoader::loadInstanceMasksImages (std::vector< std::string > & images_paths) inline private
Definition at line 200 of file ClusterSlamDataProvider.cc.
{
    std::vector<std::filesystem::path> files_in_directory =
        getAllFilesInDir(instance_masks_folder_);
    for (const std::string file_path : files_in_directory) {
      throwExceptionIfPathInvalid(file_path);
      images_paths.push_back(file_path);
    }
  }
References dyno::getAllFilesInDir(), instance_masks_folder_, and dyno::throwExceptionIfPathInvalid().
Referenced by ClusterSlamAllLoader().
loadLandMarkMapping()
void dyno::ClusterSlamAllLoader::loadLandMarkMapping (gtsam::FastMap< int, int > & landmark_mapping) inline private
Definition at line 409 of file ClusterSlamDataProvider.cc.
{
    std::ifstream fstream;
    fstream.open(landmark_mapping_file_path_, std::ios::in);
    if (!fstream) {
      throw std::runtime_error(
          "Could not open file " + landmark_mapping_file_path_ +
          " when trying to load Cluster Slam landmarks mapping!");
    }
    // expected size of each line (landamrk_id cluster_id)
    constexpr static size_t kExpectedSize = 2u;
    while (!fstream.eof()) {
      std::vector<std::string> split_line;
      if (!getLine(fstream, split_line)) continue;
      CHECK_EQ(split_line.size(), kExpectedSize)
          << "Line present in landmark mapping file does not have the right "
             "length - "
          << container_to_string(split_line);
      const int landmark_id = std::stoi(split_line.at(0));
      // clusters start at 0 here, but that includes background label (which is
      // 0) since the  line ordering of the trajectories files determines the
      // label the camera pose is always first (line = 0), so any cluster that
      // is associated to an object and not the camera pose, should have idx > 0
      const int cluster_id = std::stoi(split_line.at(1));
      landmark_mapping.insert2(landmark_id, cluster_id);
    }
  }
References dyno::container_to_string(), dyno::getLine(), and landmark_mapping_file_path_.
Referenced by ClusterSlamAllLoader().
loadLeftLandmarks()
void dyno::ClusterSlamAllLoader::loadLeftLandmarks (LandmarksMapPerFrame & detected_landmarks) inline private
Definition at line 359 of file ClusterSlamDataProvider.cc.
{
    std::vector<std::filesystem::path> files_in_directory =
        getAllFilesInDir(left_landmarks_folder_);
    for (const std::filesystem::path& file_path : files_in_directory) {
      // this should be the file name which we will then decompose into the
      // frame id e.g. .../pose/0000.txt -> filename = 0000 -> frame id = int(0)
      const std::string file_name = file_path.filename();
      const int frame = std::stoi(file_name);
      std::ifstream fstream;
      fstream.open((std::string)file_path, std::ios::in);
      if (!fstream) {
        throw std::runtime_error(
            "Could not open file " + (std::string)file_path +
            " when trying to load Cluster Slam landmarks information!");
      }
      // check we've never processed this frame before
      CHECK(!detected_landmarks.exists(frame));
      LandmarksMap detected_lmks_this_frame;
      // expected size of each line (landamrk_id u v)
      constexpr static size_t kExpectedSize = 3u;
      while (!fstream.eof()) {
        std::vector<std::string> split_line;
        if (!getLine(fstream, split_line)) continue;
        CHECK_EQ(split_line.size(), kExpectedSize)
            << "Line present in landmarks file does not have the right length "
               "- "
            << container_to_string(split_line);
        const int landmark_id = std::stoi(split_line.at(0));
        const double u = std::stod(split_line.at(1));
        const double v = std::stod(split_line.at(2));
        detected_lmks_this_frame.insert2(landmark_id, Keypoint(u, v));
      }
      detected_landmarks.insert2(frame, detected_lmks_this_frame);
    }
    VLOG(20) << "Loaded " << detected_landmarks.size()
             << " detected landmarks...";
  }
References dyno::container_to_string(), dyno::getAllFilesInDir(), dyno::getLine(), and left_landmarks_folder_.
Referenced by ClusterSlamAllLoader().
processPoseFile()
gtsam::Pose3Vector dyno::ClusterSlamAllLoader::processPoseFile (const std::string & pose_file, GroundTruthPacketMap & ground_truth_packets) inline private
NOTE: the dataset claims that the format is x,y,z, qx, qy, qz, qw however this is not true!!! actual format is x,y,z, QW, qx, qy, qz
Definition at line 672 of file ClusterSlamDataProvider.cc.
{
    std::ifstream fstream;
    fstream.open(pose_file, std::ios::in);
    if (!fstream) {
      throw std::runtime_error(
          "Could not open file " + pose_file +
          " when trying to load Cluster Slam pose information!");
    }
    // expected size of each line (3 translation components + 4 for quaternion)
    constexpr static size_t kExpectedSize = 7u;
    auto construct_pose =
        [](const std::vector<std::string>& pose_string) -> gtsam::Pose3 {
      const double x = std::stod(pose_string.at(0));
      const double y = std::stod(pose_string.at(1));
      const double z = std::stod(pose_string.at(2));
      const double qw = std::stod(pose_string.at(3));
      const double qx = std::stod(pose_string.at(4));
      const double qy = std::stod(pose_string.at(5));
      const double qz = std::stod(pose_string.at(6));
      return gtsam::Pose3(gtsam::Rot3(qw, qx, qy, qz), gtsam::Point3(x, y, z));
    };
    gtsam::Pose3Vector poses;
    while (!fstream.eof()) {
      std::vector<std::string> split_line;
      if (!getLine(fstream, split_line)) continue;
      CHECK_EQ(split_line.size(), kExpectedSize)
          << "Line present in pose file does not have the right length - "
          << container_to_string(split_line);
      poses.push_back(construct_pose(split_line));
    }
    return poses;
  }
References dyno::container_to_string(), and dyno::getLine().
Referenced by setGroundTruthPacket().
setGroundTruthPacket()
void dyno::ClusterSlamAllLoader::setGroundTruthPacket (GroundTruthPacketMap & ground_truth_packets) inline private
Definition at line 560 of file ClusterSlamDataProvider.cc.
{
    // load the poses
    // first line contains camera pose
    // consequative lines contain object ids which are indexed from 0, but we
    // will index from 1 expect the file name to give us the frame we are
    // working with!!
    std::vector<std::filesystem::path> files_in_directory =
        getAllFilesInDir(pose_folder_path_);
    gtsam::Pose3 initial_pose = gtsam::Pose3::Identity();
    bool initial_frame_set = false;
    Eigen::Matrix3d R_carla_to_opencv;
    R_carla_to_opencv << 0, 0, 1, 1, 0, 0, 0, -1, 0;
    gtsam::Rot3 rot_carla_to_opencv(R_carla_to_opencv);
    gtsam::Pose3 T_carla_to_opencv(rot_carla_to_opencv, gtsam::Point3(0, 0, 0));
    for (const std::filesystem::path& pose_file_path : files_in_directory) {
      // this should be the file name which we will then decompose into the
      // frame id e.g. .../pose/0000.txt -> filename = 0000 -> frame id = int(0)
      const std::string file_name = pose_file_path.filename();
      const int frame = std::stoi(file_name);
      const gtsam::Pose3Vector poses =
          processPoseFile(pose_file_path, ground_truth_packets);
      // check we've never processed this frame before
      CHECK(!ground_truth_packets.exists(frame));
      if (frame > 0) {
        // check we have the previous frame!! (ie.e we process in order!)
        CHECK(ground_truth_packets.exists(frame - 1));
      }
      GroundTruthInputPacket gt_packet;
      gt_packet.frame_id_ = frame;
      gt_packet.timestamp_ = getTimestamp(frame);
      // Quoting the dataset home page:
      // For each trajectory file under pose/ directory, each line in each file
      // represents the pose of each cluster except for the first line - that
      // line represents the camera pose.
      gtsam::Pose3 original_camera_pose;
      gtsam::Pose3 aligned_camera_pose;
      for (size_t i = 0; i < poses.size(); i++) {
        // pose is in world coordinate convention so we put into camera
        // convention (the camera_to_world.inverse())
        //  gtsam::Pose3 pose = camera_to_world.inverse() * poses.at(i);
        gtsam::Pose3 pose = poses.at(i);
        // pose = T_carla_to_opencv.inverse() * pose * T_carla_to_opencv;
        // pose = T_carla_to_opencv *
        // gtsam::Pose3(toRightHandedRotation(pose.rotation()),
        // toRightHandedVector(pose.translation())); pose =
        // gtsam::Pose3(toRightHandedRotation(pose.rotation()),
        // toRightHandedVector(pose.translation())); pose =
        // gtsam::Pose3(rot_carla_to_opencv * pose.rotation(),
        // pose.translation()); translation(1) = -translation(1); pose =
        // gtsam::Pose3(rot_carla_to_opencv * pose.rotation(),
        // rot_carla_to_opencv * translation);
        // LOG(INFO) << pose;
        // pose = camera_to_world.inverse() * pose;
        // LOG(INFO) << pose;
        if (i == 0) {
          if (!initial_frame_set) {
            // expect very first pose (first frame, and first pose within that
            // frame) to be the first camera pose
            initial_pose = pose;
            initial_frame_set = true;
            LOG(INFO) << pose;
          }
          original_camera_pose = pose;
          // offset initial pose so we start at "0, 0, 0"
          aligned_camera_pose = initial_pose.inverse() * pose;
          gt_packet.X_world_ = aligned_camera_pose;
        } else {
          ObjectPoseGT object_pose_gt;
          object_pose_gt.frame_id_ = frame;
          object_pose_gt.object_id_ = i;
          Eigen::Matrix3d R_carla_to_opencv;
          R_carla_to_opencv << 1, 0, 0, 0, 0, 1, 0, -1, 0;
          gtsam::Rot3 rot_carla_to_opencv(R_carla_to_opencv);
          gtsam::Pose3 T_carla_to_opencv(rot_carla_to_opencv,
                                         gtsam::Point3(0, 0, 0));
          gtsam::Pose3 object_pose(rot_carla_to_opencv * pose.rotation(),
                                   pose.translation());
          // gtsam::Pose3 object_pose = pose;
          LOG(INFO) << "Processing object " << i;
          // construct relative object pose with original camera pose
          auto relative_object_pose =
              original_camera_pose.inverse() * object_pose;
          auto aligned_object_pose = gt_packet.X_world_ * relative_object_pose;
          object_pose_gt.L_camera_ = relative_object_pose;
          object_pose_gt.L_world_ = aligned_object_pose;
          gt_packet.object_poses_.push_back(object_pose_gt);
        }
      }
      if (frame > 0) {
        const GroundTruthInputPacket& previous_gt_packet =
            ground_truth_packets.at(frame - 1);
        gt_packet.calculateAndSetMotions(previous_gt_packet);
      }
      ground_truth_packets.insert2(frame, gt_packet);
    }
  }
References dyno::GroundTruthInputPacket::calculateAndSetMotions(), dyno::ObjectPoseGT::frame_id_, dyno::GroundTruthInputPacket::frame_id_, dyno::getAllFilesInDir(), getTimestamp(), dyno::ObjectPoseGT::L_camera_, dyno::ObjectPoseGT::L_world_, dyno::ObjectPoseGT::object_id_, dyno::GroundTruthInputPacket::object_poses_, pose_folder_path_, processPoseFile(), dyno::PipelinePayload::timestamp_, and dyno::GroundTruthInputPacket::X_world_.
Referenced by ClusterSlamAllLoader().
setIntrisics()
void dyno::ClusterSlamAllLoader::setIntrisics () inline private
Definition at line 212 of file ClusterSlamDataProvider.cc.
                      {
    std::ifstream fstream;
    fstream.open(intrinsics_file_path_, std::ios::in);
    if (!fstream) {
      throw std::runtime_error("Could not open file " + intrinsics_file_path_ +
                               " when trying to load Cluster Slam intrinsics!");
    }
    auto load_projection_matrix =
        [](std::ifstream& fstream, gtsam::Matrix34& projection_matrix) -> void {
      // read the first 3 liens of the projection matrix and populate camera
      // matrix
      for (size_t i = 0; i < 3; i++) {
        // std::vector<std::string> split_line;
        // hmmm my getline function does not seem to work here (maybe because
        // doubles so we'll do it manually!)
        // CHECK(getLine(fstream, split_line));
        // CHECK_EQ(split_line.size(), 4) << "Line was: " <<
        // container_to_string(split_line, ", ");
        std::string s;
        std::getline(fstream, s);
        std::stringstream ss;
        ss << s;
        LOG(INFO) << ss.str();
        for (size_t j = 0; j < 4; j++) {
          double tmp;
          ss >> tmp;
          projection_matrix(i, j) = tmp;
        }
      }
    };  // load_projection_matrix
    // intrinscis file is
    // 3 x 4 projection matrix, over 3 lines
    //  new line
    // 3 x 4 projection matrix, over 3 lines
    // populate camera 1 matrix
    load_projection_matrix(fstream, projection_matrix_cam1_);
    // read the line line
    std::string s;
    std::getline(fstream, s);
    // populate camera 2 matrix
    load_projection_matrix(fstream, projection_matrix_cam2_);
    // set K matrices
    K_cam_1 = projection_matrix_cam1_.topLeftCorner(3, 3);
    K_cam_2 = projection_matrix_cam2_.topLeftCorner(3, 3);
    double fx_left = K_cam_1(0, 0);
    double fy_left = K_cam_1(1, 1);
    double cu_left = K_cam_1(0, 2);
    double cv_left = K_cam_1(1, 2);
    double fx_right = K_cam_2(0, 0);
    double fy_right = K_cam_2(1, 1);
    double cu_right = K_cam_2(0, 2);
    double cv_right = K_cam_2(1, 2);
    // Projection_matrix = K * extrinsics
    gtsam::Pose3 extrinsics_left =
        gtsam::Pose3(K_cam_1.inverse() * projection_matrix_cam1_);
    gtsam::Pose3 extrinsics_right =
        gtsam::Pose3(K_cam_2.inverse() * projection_matrix_cam2_);
    // I think this dataset has the projection matrix in the local left frame
    // (i.e projection of 2 into 1) becuase the translation component of
    // extrinsics_right is negative we want extrinsice to be in the world frame
    // because this is what the camera params expect OR the dataset is in OpenCV
    // convention...
    extrinsics_right = extrinsics_right.inverse();
    LOG(INFO) << "left e " << extrinsics_left;
    LOG(INFO) << "right e " << extrinsics_right;
    left_camera_params_ = CameraParams(
        CameraParams::IntrinsicsCoeffs({fx_left, fy_left, cu_left, cv_left}),
        CameraParams::DistortionCoeffs({0, 0, 0, 0}), getRGB(0).size(),
        DistortionModel::RADTAN, extrinsics_left);
    CameraParams right_camera_params(
        CameraParams::IntrinsicsCoeffs(
            {fx_right, fy_right, cu_right, cv_right}),
        CameraParams::DistortionCoeffs({0, 0, 0, 0}), getRGB(0).size(),
        DistortionModel::RADTAN, extrinsics_right);
    DenseStereoParams dense_stereo_params;
    dense_stereo_params.use_sgbm_ = true;
    dense_stereo_params.post_filter_disparity_ = false;
    dense_stereo_params.median_blur_disparity_ = false;
    dense_stereo_params.pre_filter_cap_ = 31;
    dense_stereo_params.sad_window_size_ = 5;
    dense_stereo_params.min_disparity_ = 0;
    dense_stereo_params.num_disparities_ = 16 * 8;  // 128 disparities
    dense_stereo_params.uniqueness_ratio_ = 15;
    dense_stereo_params.speckle_range_ = 2;
    dense_stereo_params.speckle_window_size_ = 50;
    // BM parameters (ignored if using SGBM)
    dense_stereo_params.texture_threshold_ = 0;
    dense_stereo_params.pre_filter_type_ = cv::StereoBM::PREFILTER_XSOBEL;
    dense_stereo_params.pre_filter_size_ = 9;
    // SGBM parameters (compute from sad_window_size_)
    dense_stereo_params.p1_ = 8 * 1 * dense_stereo_params.sad_window_size_ *
                              dense_stereo_params.sad_window_size_;
    dense_stereo_params.p2_ = 32 * 1 * dense_stereo_params.sad_window_size_ *
                              dense_stereo_params.sad_window_size_;
    dense_stereo_params.disp_12_max_diff_ = 1;
    // Recommended: use MODE_SGBM_3WAY, so set this to false to avoid MODE_HH
    dense_stereo_params.use_mode_HH_ = true;
    // matching_params.sad_window_size_ = 4;
    stereo_camera_ = std::make_shared<StereoCamera>(left_camera_params_,
                                                    right_camera_params);
    stereo_matcher_ = std::make_shared<StereoMatcher>(
        stereo_camera_, StereoMatchingParams{}, dense_stereo_params);
  }
References dyno::DenseStereoParams::disp_12_max_diff_, getRGB(), intrinsics_file_path_, K_cam_1, K_cam_2, left_camera_params_, dyno::DenseStereoParams::median_blur_disparity_, dyno::DenseStereoParams::min_disparity_, dyno::DenseStereoParams::num_disparities_, dyno::DenseStereoParams::p1_, dyno::DenseStereoParams::p2_, dyno::DenseStereoParams::post_filter_disparity_, dyno::DenseStereoParams::pre_filter_cap_, dyno::DenseStereoParams::pre_filter_size_, dyno::DenseStereoParams::pre_filter_type_, projection_matrix_cam1_, projection_matrix_cam2_, dyno::RADTAN, dyno::DenseStereoParams::sad_window_size_, size(), dyno::DenseStereoParams::speckle_range_, dyno::DenseStereoParams::speckle_window_size_, stereo_camera_, stereo_matcher_, dyno::DenseStereoParams::texture_threshold_, dyno::DenseStereoParams::uniqueness_ratio_, dyno::DenseStereoParams::use_mode_HH_, and dyno::DenseStereoParams::use_sgbm_.
Referenced by ClusterSlamAllLoader().
size()
size_t dyno::ClusterSlamAllLoader::size () const inline
Definition at line 114 of file ClusterSlamDataProvider.cc.
{ return dataset_size_; }
References dataset_size_.
Referenced by ClusterSlamAllLoader(), and setIntrisics().
Member Data Documentation
dataset_size_
size_t dyno::ClusterSlamAllLoader::dataset_size_ private
Definition at line 757 of file ClusterSlamDataProvider.cc.
Referenced by ClusterSlamAllLoader(), getInstanceMask(), and size().
ground_truth_packets_
GroundTruthPacketMap dyno::ClusterSlamAllLoader::ground_truth_packets_ private
Definition at line 756 of file ClusterSlamDataProvider.cc.
Referenced by ClusterSlamAllLoader(), and getGtPacket().
instance_masks_
gtsam::FastMap<FrameId, cv::Mat> dyno::ClusterSlamAllLoader::instance_masks_ private
Definition at line 739 of file ClusterSlamDataProvider.cc.
instance_masks_folder_
const std::string dyno::ClusterSlamAllLoader::instance_masks_folder_ private
Definition at line 725 of file ClusterSlamDataProvider.cc.
Referenced by ClusterSlamAllLoader(), and loadInstanceMasksImages().
instance_masks_image_paths_
std::vector<std::string> dyno::ClusterSlamAllLoader::instance_masks_image_paths_ private
Definition at line 734 of file ClusterSlamDataProvider.cc.
Referenced by ClusterSlamAllLoader(), and getInstanceMask().
intrinsics_file_path_
const std::string dyno::ClusterSlamAllLoader::intrinsics_file_path_ private
Definition at line 727 of file ClusterSlamDataProvider.cc.
Referenced by ClusterSlamAllLoader(), and setIntrisics().
K_cam_1
gtsam::Matrix33 dyno::ClusterSlamAllLoader::K_cam_1 private
Definition at line 747 of file ClusterSlamDataProvider.cc.
Referenced by setIntrisics().
K_cam_2
gtsam::Matrix33 dyno::ClusterSlamAllLoader::K_cam_2 private
Definition at line 748 of file ClusterSlamDataProvider.cc.
Referenced by setIntrisics().
landmark_mapping_
gtsam::FastMap<int, int> dyno::ClusterSlamAllLoader::landmark_mapping_ private
Definition at line 744 of file ClusterSlamDataProvider.cc.
Referenced by associateDetectedBBWithObject(), and ClusterSlamAllLoader().
landmark_mapping_file_path_
const std::string dyno::ClusterSlamAllLoader::landmark_mapping_file_path_ private
Definition at line 726 of file ClusterSlamDataProvider.cc.
Referenced by ClusterSlamAllLoader(), and loadLandMarkMapping().
left_camera_params_
CameraParams dyno::ClusterSlamAllLoader::left_camera_params_ private
Definition at line 751 of file ClusterSlamDataProvider.cc.
Referenced by getLeftCameraParams(), and setIntrisics().
left_images_folder_path_
const std::string dyno::ClusterSlamAllLoader::left_images_folder_path_ private
Definition at line 720 of file ClusterSlamDataProvider.cc.
Referenced by ClusterSlamAllLoader().
left_landmarks_folder_
const std::string dyno::ClusterSlamAllLoader::left_landmarks_folder_ private
Definition at line 723 of file ClusterSlamDataProvider.cc.
Referenced by ClusterSlamAllLoader(), and loadLeftLandmarks().
left_landmarks_map_
LandmarksMapPerFrame dyno::ClusterSlamAllLoader::left_landmarks_map_ private
Definition at line 735 of file ClusterSlamDataProvider.cc.
Referenced by associateDetectedBBWithObject(), and ClusterSlamAllLoader().
left_rgb_image_paths_
std::vector<std::string> dyno::ClusterSlamAllLoader::left_rgb_image_paths_ private
Definition at line 730 of file ClusterSlamDataProvider.cc.
Referenced by ClusterSlamAllLoader(), getInstanceMask(), and getRGB().
optical_flow_folder_path_
const std::string dyno::ClusterSlamAllLoader::optical_flow_folder_path_ private
Definition at line 721 of file ClusterSlamDataProvider.cc.
Referenced by ClusterSlamAllLoader(), and loadFlowImagesAndSize().
optical_flow_image_paths_
std::vector<std::string> dyno::ClusterSlamAllLoader::optical_flow_image_paths_ private
Definition at line 733 of file ClusterSlamDataProvider.cc.
Referenced by ClusterSlamAllLoader(), and getOpticalFlow().
pose_folder_path_
const std::string dyno::ClusterSlamAllLoader::pose_folder_path_ private
Definition at line 722 of file ClusterSlamDataProvider.cc.
Referenced by ClusterSlamAllLoader(), and setGroundTruthPacket().
projection_matrix_cam1_
gtsam::Matrix34 dyno::ClusterSlamAllLoader::projection_matrix_cam1_ private
Definition at line 749 of file ClusterSlamDataProvider.cc.
Referenced by setIntrisics().
projection_matrix_cam2_
gtsam::Matrix34 dyno::ClusterSlamAllLoader::projection_matrix_cam2_ private
Definition at line 750 of file ClusterSlamDataProvider.cc.
Referenced by setIntrisics().
right_images_folder_path_
const std::string dyno::ClusterSlamAllLoader::right_images_folder_path_ private
Definition at line 724 of file ClusterSlamDataProvider.cc.
Referenced by ClusterSlamAllLoader().
right_rgb_image_paths_
std::vector<std::string> dyno::ClusterSlamAllLoader::right_rgb_image_paths_ private
Definition at line 732 of file ClusterSlamDataProvider.cc.
Referenced by ClusterSlamAllLoader(), and getRightRGB().
stereo_camera_
StereoCamera::Ptr dyno::ClusterSlamAllLoader::stereo_camera_ private
Definition at line 753 of file ClusterSlamDataProvider.cc.
Referenced by setIntrisics().
stereo_matcher_
StereoMatcher::Ptr dyno::ClusterSlamAllLoader::stereo_matcher_ private
Definition at line 754 of file ClusterSlamDataProvider.cc.
Referenced by denseStereoReconstruction(), and setIntrisics().
The documentation for this class was generated from the following file:
dynosam/src/dataprovider/ClusterSlamDataProvider.cc