DynoSAM: dyno::YamlParser Class Reference
dyno::YamlParser Class Reference
#include <YamlParser.hpp>
Public Member Functions
YamlParser (const std::string &filepath)
~YamlParser ()
template<class T >
bool getYamlParam (const std::string &id, T *output) const
template<class T >
bool getYamlParam (const std::string &id, T *output, T default_value) const
template<class T >
void getNestedYamlParam (const std::string &id, const std::string &id_2, T *output) const
template<class T >
void getNestedYamlParam (const std::string &id, const std::string &id_2, T *output, T default_value) const
Private Member Functions
void openFile (const std::string &filepath, cv::FileStorage *fs) const
void closeFile (cv::FileStorage *fs) const
Private Attributes
cv::FileStorage fs_
std::string filepath_
Detailed Description
Definition at line 48 of file YamlParser.hpp.
Constructor & Destructor Documentation
YamlParser()
dyno::YamlParser::YamlParser (const std::string & filepath) inline
Definition at line 52 of file YamlParser.hpp.
                                        : fs_(), filepath_(filepath) {
    utils::throwExceptionIfPathInvalid(filepath_);
    openFile(filepath, &fs_);
  }
References filepath_, fs_, openFile(), and dyno::utils::throwExceptionIfPathInvalid().
~YamlParser()
dyno::YamlParser::~YamlParser () inline
Definition at line 56 of file YamlParser.hpp.
{ closeFile(&fs_); }
References closeFile(), and fs_.
Member Function Documentation
closeFile()
void dyno::YamlParser::closeFile (cv::FileStorage * fs) const inline private
Definition at line 138 of file YamlParser.hpp.
{
    CHECK_NOTNULL(fs)->release();
  }
Referenced by ~YamlParser().
getNestedYamlParam() [1/2]
template<class T > void dyno::YamlParser::getNestedYamlParam (const std::string & id, const std::string & id_2, T * output) const inline
Definition at line 85 of file YamlParser.hpp.
{
    CHECK(!id.empty());
    CHECK(!id_2.empty());
    const cv::FileNode& file_handle = fs_[id];
    CHECK_NE(file_handle.type(), cv::FileNode::NONE)
        << "Missing parameter: " << id.c_str()
        << " in file: " << filepath_.c_str();
    const cv::FileNode& file_handle_2 = file_handle[id_2];
    CHECK_NE(file_handle_2.type(), cv::FileNode::NONE)
        << "Missing nested parameter: " << id_2.c_str() << " inside "
        << id.c_str() << '\n'
        << " in file: " << filepath_.c_str();
    CHECK(file_handle.isMap())
        << "I think that if this is not a map, we can't use >>";
    file_handle_2 >> *CHECK_NOTNULL(output);
  }
References filepath_, and fs_.
getNestedYamlParam() [2/2]
template<class T > void dyno::YamlParser::getNestedYamlParam (const std::string & id, const std::string & id_2, T * output, T default_value) const inline
Definition at line 104 of file YamlParser.hpp.
{
    CHECK(!id.empty());
    CHECK(!id_2.empty());
    const cv::FileNode& file_handle = fs_[id];
    CHECK_NE(file_handle.type(), cv::FileNode::NONE)
        << "Missing parameter: " << id.c_str()
        << " in file: " << filepath_.c_str();
    const cv::FileNode& file_handle_2 = file_handle[id_2];
    if (file_handle_2.type() == cv::FileNode::NONE) {
      *output = default_value;
    } else {
      T v;
      file_handle_2 >> v;
      file_handle_2 >> *output;
    }
  }
References filepath_, and fs_.
getYamlParam() [1/2]
template<class T > bool dyno::YamlParser::getYamlParam (const std::string & id, T * output) const inline
Definition at line 59 of file YamlParser.hpp.
{
    CHECK(!id.empty());
    CHECK_NOTNULL(output);
    const cv::FileNode& file_handle = fs_[id];
    CHECK_NE(file_handle.type(), cv::FileNode::NONE)
        << "Missing parameter: " << id.c_str()
        << " in file: " << filepath_.c_str();
    file_handle >> *output;
    return true;
  }
References filepath_, and fs_.
Referenced by dyno::KittiDataLoader::Params::fromYaml(), dyno::VirtualKittiDataLoader::Params::fromYaml(), and dyno::OMDOldAllLoader::setCameraParams().
getYamlParam() [2/2]
template<class T > bool dyno::YamlParser::getYamlParam (const std::string & id, T * output, T default_value) const inline
Definition at line 71 of file YamlParser.hpp.
{
    CHECK(!id.empty());
    CHECK_NOTNULL(output);
    const cv::FileNode& file_handle = fs_[id];
    if (file_handle.type() == cv::FileNode::NONE) {
      *output = default_value;
      return false;
    } else {
      file_handle >> *output;
      return true;
    }
  }
References fs_.
openFile()
void dyno::YamlParser::openFile (const std::string & filepath, cv::FileStorage * fs) const inline private
Definition at line 123 of file YamlParser.hpp.
{
    CHECK(!filepath.empty()) << "Empty filepath!";
    try {
      CHECK_NOTNULL(fs)->open(filepath, cv::FileStorage::READ);
    } catch (cv::Exception& e) {
      DYNO_THROW_MSG(DynosamException)
          << "Cannot open file: " << filepath << "\n"
          << "OpenCV error code: " + e.msg
          << " (remember that the first line should be: %YAML:1.0)!";
    }
    LOG_IF(FATAL, !fs->isOpened())
        << "Cannot open file in parseYAML: " << filepath
        << " (remember that the first line should be: %YAML:1.0)";
  }
References DYNO_THROW_MSG.
Referenced by YamlParser().
Member Data Documentation
filepath_
std::string dyno::YamlParser::filepath_ private
Definition at line 144 of file YamlParser.hpp.
Referenced by getNestedYamlParam(), getYamlParam(), and YamlParser().
fs_
cv::FileStorage dyno::YamlParser::fs_ private
Definition at line 143 of file YamlParser.hpp.
Referenced by getNestedYamlParam(), getYamlParam(), YamlParser(), and ~YamlParser().
The documentation for this class was generated from the following file:
dynosam_common/include/dynosam_common/utils/YamlParser.hpp