DynoSAM: dyno::DynoDatasetProvider< DataTypes > Class Template Reference
dyno::DynoDatasetProvider< DataTypes > Class Template Reference
#include <DatasetProvider.hpp>
Public Types
using BaseDynoDataset = DynoDataset< DataTypes... >
using This = DynoDatasetProvider< DataTypes... >
Public Types inherited from dyno::DynoDataset< DataTypes... >
using TypedGenericDataset = GenericDataset< DataTypes... >
using DefaultDataset = GenericDataset< Timestamp, cv::Mat, cv::Mat >
using Base = _DynoDatasetConstructor< Timestamp, cv::Mat, cv::Mat, DataTypes... >
using DynoDataTypesTuple = typename Base::DynoDataTypesTuple
using GenericDatasetType = typename TypedGenericDataset::DataType< I >
Index in Default Dataset.
using DefaultDatasetType = typename DefaultDataset::DataType< I >
The type stored at the tuple idnex of the DefaultDataset.
using This = DynoDataset< DataTypes... >
Public Types inherited from dyno::_DynoDatasetConstructor< Timestamp, cv::Mat, cv::Mat, DataTypes... >
using DynoDataTypesTuple = std::tuple< DynoDataTypes... >
using DataInputCallback = std::function< bool(size_t, const DynoDataTypes...)>
All the dyno datypes in one definition (default at the start and then the optional ones)
Public Types inherited from dyno::DataProvider
using ImageContainerCallback = std::function< void(ImageContainer::Ptr)>
using ImuSingleInputCallback = std::function< void(const ImuMeasurement &)>
using ImuMultiInputCallback = std::function< void(const ImuMeasurements &)>
using GroundTruthPacketCallback = std::function< void(const GroundTruthInputPacket &)>
Public Member Functions
DynoDatasetProvider (const fs::path &dataset_path)
virtual ~DynoDatasetProvider ()=default
void setStartingFrame (int starting_frame)
void setEndingFrame (int ending_frame)
void reset ()
Resets the dataset to the "start", such that the next call to spin will begin the dataset again from the starting frame id. The starting/ending id will return to whatever the last call to setStartingFrame/setEndingFrame set the values to, or default if they have not been called.
virtual int datasetSize () const override
Get the size of the dataset - if this is not valid (i.e. the provider is online) this function should return -1.
virtual bool spin () override
Spins the dataset for one "step" of the dataset.
size_t getActiveFrameId () const
size_t getEndingFrameId () const
Public Member Functions inherited from dyno::DynoDataset< DataTypes... >
DynoDataset (const fs::path &dataset_path)
Fully defined tuple type containing all the dataset types in order starting with the default types.
virtual ~DynoDataset ()
virtual void setLoaders (TimestampBaseLoader::Ptr timestamp_loader, dyno::DataFolder< cv::Mat >::Ptr rgb_loader, dyno::DataFolder< cv::Mat >::Ptr optical_flow_loader, typename DataFolder< DataTypes >::Ptr... data_folders)
bool isProviderValid () const
Returns true when setLoaders(...) has been called and the internal datasets have been constructed correctly After this point spin() and getDatasetSize() can be called as they use the laoded datasets.
virtual size_t getDatasetSize () const
const std::string getDatasetPath () const
bool processSingle (size_t frame_id)
auto getLoader ()
Public Member Functions inherited from dyno::_DynoDatasetConstructor< Timestamp, cv::Mat, cv::Mat, DataTypes... >
virtual ~_DynoDatasetConstructor ()
void setCallback (const DataInputCallback &data_input_callback)
Public Member Functions inherited from dyno::DataProvider
DataProvider ()=default
DataProvider (DataInterfacePipeline *module)
DataProvider (DataInterfacePipelineImu *module)
virtual ~DataProvider ()
void registerImuSingleCallback (const ImuSingleInputCallback &callback)
void registerImuMultiCallback (const ImuMultiInputCallback &callback)
void registerImageContainerCallback (const ImageContainerCallback &callback)
void registerGroundTruthPacketCallback (const GroundTruthPacketCallback &callback)
virtual ImageContainer::Ptr imageContainerPreprocessor (ImageContainer::Ptr image_container)
Virtual Image Container Preprocessor function that is registered to the data interface pipeline.
void registerOnFinishCallback (const std::function< void()> &callback)
virtual int datasetSize () const =0
Get the size of the dataset - if this is not valid (i.e. the provider is online) this function should return -1.
virtual bool spin ()=0
Spins the dataset for one "step" of the dataset.
virtual void shutdown ()
virtual CameraParams::Optional getCameraParams () const
Provides functionality to get camera paramters for the main pipeline, as these may be available from the dataset.
Protected Member Functions
void setLoaders (TimestampBaseLoader::Ptr timestamp_loader, dyno::DataFolder< cv::Mat >::Ptr rgb_loader, dyno::DataFolder< cv::Mat >::Ptr optical_flow_loader, typename DataFolder< DataTypes >::Ptr... data_folders) override
Protected Member Functions inherited from dyno::DataProvider
void emitOnFinishCallbacks ()
Private Member Functions
void setEndingFrameFromRequested ()
Private Attributes
size_t active_frame_id_ = 0u
size_t ending_frame_id_ = 0u
int requested_starting_frame_id_ {-1}
int requested_ending_frame_id_ {-1}
bool is_first_spin_ {true}
Additional Inherited Members
Public Attributes inherited from dyno::_DynoDatasetConstructor< Timestamp, cv::Mat, cv::Mat, DataTypes... >
DataInputCallback data_input_callback_
Static Public Attributes inherited from dyno::DynoDataset< DataTypes... >
static constexpr size_t TimestampFileIdx
All the dataypes declared in one tuple (Timestamp, cv::Mat, cv::Mat, ....)
static constexpr size_t RGBFolderIdx
static constexpr size_t OpticalFlowFolderIdx
Index in Default Dataset.
Protected Attributes inherited from dyno::DataProvider
ImageContainerCallback image_container_callback_
ImuSingleInputCallback imu_single_input_callback_
ImuMultiInputCallback imu_multi_input_callback_
GroundTruthPacketCallback ground_truth_packet_callback_
std::atomic_bool shutdown_ = {false}
Detailed Description
template<typename... DataTypes>
class dyno::DynoDatasetProvider< DataTypes >
Definition at line 258 of file DatasetProvider.hpp.
Member Typedef Documentation
BaseDynoDataset
template<typename... DataTypes> using dyno::DynoDatasetProvider< DataTypes >::BaseDynoDataset = DynoDataset<DataTypes...>
Definition at line 261 of file DatasetProvider.hpp.
This
template<typename... DataTypes> using dyno::DynoDatasetProvider< DataTypes >::This = DynoDatasetProvider<DataTypes...>
Definition at line 262 of file DatasetProvider.hpp.
Constructor & Destructor Documentation
DynoDatasetProvider()
template<typename... DataTypes> dyno::DynoDatasetProvider< DataTypes >::DynoDatasetProvider (const fs::path & dataset_path) inline
Definition at line 268 of file DatasetProvider.hpp.
        : BaseDynoDataset(dataset_path), DataProvider() {}
~DynoDatasetProvider()
template<typename... DataTypes> virtual dyno::DynoDatasetProvider< DataTypes >::~DynoDatasetProvider () virtual default
Member Function Documentation
datasetSize()
template<typename... DataTypes> virtual int dyno::DynoDatasetProvider< DataTypes >::datasetSize () const inline override virtual
Get the size of the dataset - if this is not valid (i.e. the provider is online) this function should return -1.
Returns
int
Implements dyno::DataProvider.
Definition at line 307 of file DatasetProvider.hpp.
{
        return (int)ending_frame_id_;
    }
References dyno::DynoDatasetProvider< DataTypes >::ending_frame_id_.
getActiveFrameId()
template<typename... DataTypes> size_t dyno::DynoDatasetProvider< DataTypes >::getActiveFrameId () const inline
Definition at line 334 of file DatasetProvider.hpp.
{ return active_frame_id_; }
References dyno::DynoDatasetProvider< DataTypes >::active_frame_id_.
getEndingFrameId()
template<typename... DataTypes> size_t dyno::DynoDatasetProvider< DataTypes >::getEndingFrameId () const inline
Definition at line 335 of file DatasetProvider.hpp.
{ return ending_frame_id_; }
References dyno::DynoDatasetProvider< DataTypes >::ending_frame_id_.
reset()
template<typename... DataTypes> void dyno::DynoDatasetProvider< DataTypes >::reset () inline
Resets the dataset to the "start", such that the next call to spin will begin the dataset again from the starting frame id. The starting/ending id will return to whatever the last call to setStartingFrame/setEndingFrame set the values to, or default if they have not been called.
Whatever changes to the dataset, ie. updating the starting and ending frames will take affect after reset is called
Definition at line 300 of file DatasetProvider.hpp.
                 {
        is_first_spin_ = true;
        active_frame_id_ = 0;
    }
References dyno::DynoDatasetProvider< DataTypes >::active_frame_id_, and dyno::DynoDatasetProvider< DataTypes >::is_first_spin_.
setEndingFrame()
template<typename... DataTypes> void dyno::DynoDatasetProvider< DataTypes >::setEndingFrame (int ending_frame) inline
Definition at line 282 of file DatasetProvider.hpp.
{
        if(ending_frame != -1)
            requested_ending_frame_id_ = ending_frame;
        LOG(WARNING) << "Updating ending frame" << requested_ending_frame_id_;
        setEndingFrameFromRequested();
    }
References dyno::DynoDatasetProvider< DataTypes >::requested_ending_frame_id_, and dyno::DynoDatasetProvider< DataTypes >::setEndingFrameFromRequested().
setEndingFrameFromRequested()
template<typename... DataTypes> void dyno::DynoDatasetProvider< DataTypes >::setEndingFrameFromRequested () inline private
Definition at line 353 of file DatasetProvider.hpp.
{
        //call base version - this will also check that the timestamp laoder is valid!
        const size_t dataset_size = BaseDynoDataset::getDatasetSize();
        // by default start dataset at 0
        size_t starting_frame = 0u;
        // by default end dataset at the last frame
        size_t ending_frame = dataset_size;
        if(requested_starting_frame_id_ >= 0) {
            starting_frame = requested_starting_frame_id_;
        }
        if(requested_ending_frame_id_ >= 0) {
            ending_frame = requested_ending_frame_id_;
        }
        //check ending frame first
        if(ending_frame > dataset_size) {
            throw DynoDatasetException("Requested ending frame is greater than the size of the dataset (" + std::to_string(ending_frame) + " > " + std::to_string(dataset_size));
        }
        if(starting_frame > ending_frame) {
            throw DynoDatasetException("Requested starting frame is invalid - either less than 0 or greater than the ending frame (starting frame= " + std::to_string(starting_frame) + ", ending frame= " + std::to_string(ending_frame));
        }
        //update varibles actually used in the spin
        active_frame_id_ = starting_frame;
        ending_frame_id_ = ending_frame;
    }
References dyno::DynoDatasetProvider< DataTypes >::active_frame_id_, dyno::DynoDatasetProvider< DataTypes >::ending_frame_id_, dyno::DynoDataset< DataTypes... >::getDatasetSize(), dyno::DynoDatasetProvider< DataTypes >::requested_ending_frame_id_, and dyno::DynoDatasetProvider< DataTypes >::requested_starting_frame_id_.
Referenced by dyno::DynoDatasetProvider< DataTypes >::setEndingFrame(), dyno::DynoDatasetProvider< DataTypes >::setLoaders(), and dyno::DynoDatasetProvider< DataTypes >::setStartingFrame().
setLoaders()
template<typename... DataTypes> void dyno::DynoDatasetProvider< DataTypes >::setLoaders (TimestampBaseLoader::Ptr timestamp_loader, dyno::DataFolder< cv::Mat >::Ptr rgb_loader, dyno::DataFolder< cv::Mat >::Ptr optical_flow_loader, typename DataFolder< DataTypes >::Ptr... data_folders) inline override protected virtual
Reimplemented from dyno::DynoDataset< DataTypes... >.
Definition at line 340 of file DatasetProvider.hpp.
    {
        BaseDynoDataset::setLoaders(timestamp_loader, rgb_loader, optical_flow_loader, data_folders...);
        //now we have a valid timestamp loader set the active/ending frame ids
        //using the requested starting/ending frames and the actual dataset size, which we get from
        //the base
        setEndingFrameFromRequested();
    }
References dyno::DynoDatasetProvider< DataTypes >::setEndingFrameFromRequested(), and dyno::DynoDataset< DataTypes... >::setLoaders().
Referenced by dyno::ClusterSlamDataLoader::ClusterSlamDataLoader(), dyno::OMDDataLoader::OMDDataLoader(), dyno::ProjectARIADataLoader::ProjectARIADataLoader(), and dyno::VirtualKittiDataLoader::VirtualKittiDataLoader().
setStartingFrame()
template<typename... DataTypes> void dyno::DynoDatasetProvider< DataTypes >::setStartingFrame (int starting_frame) inline
Definition at line 276 of file DatasetProvider.hpp.
{
        if(starting_frame != -1)
            requested_starting_frame_id_ = starting_frame;
        setEndingFrameFromRequested();
    }
References dyno::DynoDatasetProvider< DataTypes >::requested_starting_frame_id_, and dyno::DynoDatasetProvider< DataTypes >::setEndingFrameFromRequested().
Referenced by dyno::VirtualKittiDataLoader::VirtualKittiDataLoader().
spin()
template<typename... DataTypes> virtual bool dyno::DynoDatasetProvider< DataTypes >::spin () inline override virtual
Spins the dataset for one "step" of the dataset.
Returns true if the dataset still has data to process
Returns
true
false
Implements dyno::DataProvider.
Definition at line 311 of file DatasetProvider.hpp.
{
        if(!isProviderValid()) {
            LOG(ERROR) << "Cannot spin as provider is invalid";
            return false;
        }
        if(active_frame_id_ >= ending_frame_id_) {
            LOG_FIRST_N(INFO, 1) << "Finished dataset";
            emitOnFinishCallbacks();
            return false;
        }
        utils::TimingStatsCollector dataset_spin_timer("dataset_spin");
        if(!BaseDynoDataset::processSingle(active_frame_id_)) {
            LOG(ERROR) << "Processing single frame failed at frame id " << active_frame_id_;
            return false;
        }
        active_frame_id_++;
        return true;
    }
References dyno::DynoDatasetProvider< DataTypes >::active_frame_id_, dyno::DataProvider::emitOnFinishCallbacks(), dyno::DynoDatasetProvider< DataTypes >::ending_frame_id_, dyno::DynoDataset< DataTypes... >::isProviderValid(), and dyno::DynoDataset< DataTypes... >::processSingle().
Referenced by main().
Member Data Documentation
active_frame_id_
template<typename... DataTypes> size_t dyno::DynoDatasetProvider< DataTypes >::active_frame_id_ = 0u private
Definition at line 385 of file DatasetProvider.hpp.
Referenced by dyno::DynoDatasetProvider< DataTypes >::getActiveFrameId(), dyno::DynoDatasetProvider< DataTypes >::reset(), dyno::DynoDatasetProvider< DataTypes >::setEndingFrameFromRequested(), and dyno::DynoDatasetProvider< DataTypes >::spin().
ending_frame_id_
template<typename... DataTypes> size_t dyno::DynoDatasetProvider< DataTypes >::ending_frame_id_ = 0u private
Definition at line 386 of file DatasetProvider.hpp.
Referenced by dyno::DynoDatasetProvider< DataTypes >::datasetSize(), dyno::DynoDatasetProvider< DataTypes >::getEndingFrameId(), dyno::DynoDatasetProvider< DataTypes >::setEndingFrameFromRequested(), and dyno::DynoDatasetProvider< DataTypes >::spin().
is_first_spin_
template<typename... DataTypes> bool dyno::DynoDatasetProvider< DataTypes >::is_first_spin_ {true} private
Definition at line 391 of file DatasetProvider.hpp.
Referenced by dyno::DynoDatasetProvider< DataTypes >::reset().
requested_ending_frame_id_
template<typename... DataTypes> int dyno::DynoDatasetProvider< DataTypes >::requested_ending_frame_id_ {-1} private
Definition at line 389 of file DatasetProvider.hpp.
Referenced by dyno::DynoDatasetProvider< DataTypes >::setEndingFrame(), and dyno::DynoDatasetProvider< DataTypes >::setEndingFrameFromRequested().
requested_starting_frame_id_
template<typename... DataTypes> int dyno::DynoDatasetProvider< DataTypes >::requested_starting_frame_id_ {-1} private
Definition at line 388 of file DatasetProvider.hpp.
Referenced by dyno::DynoDatasetProvider< DataTypes >::setEndingFrameFromRequested(), and dyno::DynoDatasetProvider< DataTypes >::setStartingFrame().
The documentation for this class was generated from the following file:
dynosam/include/dynosam/dataprovider/DatasetProvider.hpp