DynoSAM: dyno::ImageContainerSubset< ImageTypes > Class Template Reference
dyno::ImageContainerSubset< ImageTypes > Class Template Reference
#include <ImageContainer.hpp>
Public Types
using This = ImageContainerSubset< ImageTypes... >
using ImageTypesTuple = std::tuple< ImageTypes... >
using WrappedImageTypesTuple = std::tuple< ImageWrapper< ImageTypes >... >
template<size_t I>
using ImageTypeStruct = std::tuple_element_t< I, ImageTypesTuple >
Alias for an ImageType (eg. RGBMono, Depth etc) which is the Ith element type of the parameter pack ImageTypes...
template<size_t I>
using WrappedImageTypeStruct = std::tuple_element_t< I, WrappedImageTypesTuple >
Corresponds to an alias for a type ImageWrapper<T> where T is the ImageTypeStruct, eg. RGBMono, Depth... at index I (or simply ImageTypeStruct)
Public Member Functions
ImageContainerSubset ()
ImageContainerSubset (const ImageWrapper< ImageTypes > &... input_image_wrappers)
virtual ~ImageContainerSubset ()=default
template<typename ImageType >
constexpr size_t index () const
Compile time index of the requested ImageType in the container instance.
template<typename... SubsetImageTypes>
ImageContainerSubset< SubsetImageTypes... > makeSubset (const bool clone=false) const
This clone () const
template<typename ImageType >
bool exists () const
Returns true if the corresponding image corresponding to the requested ImageType exists (i.e is not empty)
template<typename ImageType >
cv::Mat get () const
Gets the corresponding image (cv::Mat) corresponding to the requested ImageType. ImageType must be in the class parameter pack (ImageTypes...) or the code will fail to compile.
template<typename ImageType >
cv::Mat & get ()
template<typename ImageType >
const ImageWrapper< ImageType > & getImageWrapper () const
Gets the corresponding ImageWrapper corresponding to the ImageType. ImageType must be in the class parameter pack (ImageTypes...) or the code will fail to compile.
template<typename ImageType >
bool safeGet (cv::Mat &src) const
Safely Gets the corresponding image (cv::Mat) corresponding to the requested ImageType. If the requested image does not exist (empty), false will be returned.
template<typename ImageType >
bool cloneImage (cv::Mat &dst) const
Safely clones the corresponding image (cv::Mat) corresponding to the requested ImageType. If the requested image does not exist (empty), false will be returned.
Static Public Member Functions
template<typename ImageType >
static constexpr size_t Index ()
Compile time index of the requested ImageType in the container.
Static Public Attributes
static constexpr size_t N = sizeof...(ImageTypes)
Number of image types contained in this subset.
Protected Member Functions
virtual void validateSetup () const
Validates that the input images (if not empty) are the same size. Throws ImageContainerConstructionException if invalid.
Protected Attributes
WrappedImageTypesTuple image_storage_
Detailed Description
template<typename... ImageTypes>
class dyno::ImageContainerSubset< ImageTypes >
Definition at line 56 of file ImageContainer.hpp.
Member Typedef Documentation
ImageTypeStruct
template<typename... ImageTypes> template<size_t I> using dyno::ImageContainerSubset< ImageTypes >::ImageTypeStruct = std::tuple_element_t<I, ImageTypesTuple>
Alias for an ImageType (eg. RGBMono, Depth etc) which is the Ith element type of the parameter pack ImageTypes...
Template Parameters
I
Definition at line 69 of file ImageContainer.hpp.
ImageTypesTuple
template<typename... ImageTypes> using dyno::ImageContainerSubset< ImageTypes >::ImageTypesTuple = std::tuple<ImageTypes...>
Definition at line 59 of file ImageContainer.hpp.
This
template<typename... ImageTypes> using dyno::ImageContainerSubset< ImageTypes >::This = ImageContainerSubset<ImageTypes...>
Definition at line 58 of file ImageContainer.hpp.
WrappedImageTypeStruct
template<typename... ImageTypes> template<size_t I> using dyno::ImageContainerSubset< ImageTypes >::WrappedImageTypeStruct = std::tuple_element_t<I, WrappedImageTypesTuple>
Corresponds to an alias for a type ImageWrapper<T> where T is the ImageTypeStruct, eg. RGBMono, Depth... at index I (or simply ImageTypeStruct)
Template Parameters
I
Definition at line 79 of file ImageContainer.hpp.
WrappedImageTypesTuple
template<typename... ImageTypes> using dyno::ImageContainerSubset< ImageTypes >::WrappedImageTypesTuple = std::tuple<ImageWrapper<ImageTypes>...>
Definition at line 60 of file ImageContainer.hpp.
Constructor & Destructor Documentation
ImageContainerSubset() [1/2]
template<typename... ImageTypes> dyno::ImageContainerSubset< ImageTypes >::ImageContainerSubset () inline
Definition at line 88 of file ImageContainer.hpp.
{}
ImageContainerSubset() [2/2]
template<typename... ImageTypes> dyno::ImageContainerSubset< ImageTypes >::ImageContainerSubset (const ImageWrapper< ImageTypes > &... input_image_wrappers) inline explicit
Definition at line 89 of file ImageContainer.hpp.
      : image_storage_(input_image_wrappers...) {
    // this is (not-pure) virtual function could be overloaded. This means that
    // we're calling an overloaded function in the base constructor which leads
    // to undefined behaviour...?
    // validateSetup();
  }
~ImageContainerSubset()
template<typename... ImageTypes> virtual dyno::ImageContainerSubset< ImageTypes >::~ImageContainerSubset () virtual default
Member Function Documentation
clone()
template<typename... ImageTypes> This dyno::ImageContainerSubset< ImageTypes >::clone () const inline
Definition at line 142 of file ImageContainer.hpp.
{ return this->makeSubset<ImageTypes...>(true); }
References dyno::ImageContainerSubset< ImageTypes >::makeSubset().
cloneImage()
template<typename... ImageTypes> template<typename ImageType > bool dyno::ImageContainerSubset< ImageTypes >::cloneImage (cv::Mat & dst) const inline
Safely clones the corresponding image (cv::Mat) corresponding to the requested ImageType. If the requested image does not exist (empty), false will be returned.
ImageType must be in the class parameter pack (ImageTypes...) or the code will fail to compile.
Template Parameters
ImageType
Parameters
dst
Returns
true
false
Definition at line 226 of file ImageContainer.hpp.
{
    cv::Mat tmp;
    if (!This::safeGet<ImageType>(tmp)) {
      return false;
    }
    tmp.copyTo(dst);
    return true;
  }
exists()
template<typename... ImageTypes> template<typename ImageType > bool dyno::ImageContainerSubset< ImageTypes >::exists () const inline
Returns true if the corresponding image corresponding to the requested ImageType exists (i.e is not empty)
Template Parameters
ImageType
Returns
true
false
Definition at line 153 of file ImageContainer.hpp.
                      {
    return This::getImageWrapper<ImageType>().exists();
  }
get() [1/2]
template<typename... ImageTypes> template<typename ImageType > cv::Mat & dyno::ImageContainerSubset< ImageTypes >::get () inline
Definition at line 173 of file ImageContainer.hpp.
               {
    return std::get<Index<ImageType>()>(image_storage_).image;
  }
References dyno::ImageContainerSubset< ImageTypes >::image_storage_.
get() [2/2]
template<typename... ImageTypes> template<typename ImageType > cv::Mat dyno::ImageContainerSubset< ImageTypes >::get () const inline
Gets the corresponding image (cv::Mat) corresponding to the requested ImageType. ImageType must be in the class parameter pack (ImageTypes...) or the code will fail to compile.
No safety checks are done and so the returned image may be empty
Template Parameters
ImageType
Returns
cv::Mat
Definition at line 168 of file ImageContainer.hpp.
                    {
    return std::get<Index<ImageType>()>(image_storage_).image;
  }
References dyno::ImageContainerSubset< ImageTypes >::image_storage_.
getImageWrapper()
template<typename... ImageTypes> template<typename ImageType > const ImageWrapper< ImageType > & dyno::ImageContainerSubset< ImageTypes >::getImageWrapper () const inline
Gets the corresponding ImageWrapper corresponding to the ImageType. ImageType must be in the class parameter pack (ImageTypes...) or the code will fail to compile.
Template Parameters
ImageType
Returns
const ImageWrapper<ImageType>&
Definition at line 186 of file ImageContainer.hpp.
{
    constexpr size_t idx = This::Index<ImageType>();
    return std::get<idx>(image_storage_);
  }
References dyno::ImageContainerSubset< ImageTypes >::image_storage_.
Index()
template<typename... ImageTypes> template<typename ImageType > static constexpr size_t dyno::ImageContainerSubset< ImageTypes >::Index () inline static constexpr
Compile time index of the requested ImageType in the container.
eg. If ImageTypes... unpacks to Container = ImageContainerSubset<RGBMono, Depth, OpticalFlow>
If the requested ImageType is not in the class parameter pack, the code will fail to compile.
Container::Index<RGBMono>() == 0u Container::Index<Depth>() == 1u Container::Index<OpticalFlow>() == 2u
Template Parameters
ImageType
Returns
constexpr size_t
Definition at line 119 of file ImageContainer.hpp.
{
    return internal::tuple_element_index_v<ImageType, ImageTypesTuple>;
  }
index()
template<typename... ImageTypes> template<typename ImageType > constexpr size_t dyno::ImageContainerSubset< ImageTypes >::index () const inline constexpr
Compile time index of the requested ImageType in the container instance.
See Index()
Template Parameters
ImageType
Returns
constexpr size_t
Definition at line 133 of file ImageContainer.hpp.
{
    return This::Index<ImageType>();
  }
makeSubset()
template<typename... ImageTypes> template<typename... SubsetImageTypes> ImageContainerSubset< SubsetImageTypes... > dyno::ImageContainerSubset< ImageTypes >::makeSubset (const bool clone = false) const
Definition at line 32 of file ImageContainer-inl.hpp.
{
    //the tuple of image wrappers to construct for the subset class
    using Subset = ImageContainerSubset<SubsetImageTypes...>;
    using WrappedImageTypesTupleSubset = typename Subset::WrappedImageTypesTuple;
    static constexpr size_t SubN = Subset::N;
    //wrappers to populate from the current set? what about copying etc
    WrappedImageTypesTupleSubset subset_wrappers;
    for (size_t i = 0; i < SubN; i++) {
        //get the type at the new subset
        internal::select_apply<SubN>(i, [&](auto I) {
            using SubType = typename Subset::ImageTypeStruct<I>;
            //find this image type in the current container as the index may be different
            constexpr size_t current_index = This::Index<SubType>();
            //with the index i of the subset wrapper (corresponding with type SubType)
            //get the image wrapper in this container using the request (sub) type
            auto current_wrapped_image = std::get<current_index>(image_storage_);
            //if invalid but request, throw runtime error becuase whats the point of requesting an invalid image
            if(!current_wrapped_image.exists()) {
                throw std::runtime_error(
                    "Error constructing ImageContainerSubset - requested image type " + type_name<SubType>() + " is empty in parent container");
            }
            if(clone) {
                std::get<I>(subset_wrappers) = current_wrapped_image.clone();
            }
            else {
                std::get<I>(subset_wrappers) = current_wrapped_image;
            }
        });
    }
    //this is going to do a bunch of copies?
    auto construct_subset = [&](auto&&... args) { return Subset(args...); };
    return std::apply(construct_subset, subset_wrappers);
}
Referenced by dyno::ImageContainerSubset< ImageTypes >::clone().
safeGet()
template<typename... ImageTypes> template<typename ImageType > bool dyno::ImageContainerSubset< ImageTypes >::safeGet (cv::Mat & src) const inline
Safely Gets the corresponding image (cv::Mat) corresponding to the requested ImageType. If the requested image does not exist (empty), false will be returned.
ImageType must be in the class parameter pack (ImageTypes...) or the code will fail to compile.
Template Parameters
ImageType
Parameters
src
Returns
true
false
Definition at line 205 of file ImageContainer.hpp.
{
    if (!This::exists<ImageType>()) return false;
    src = This::get<ImageType>();
    return true;
  }
validateSetup()
template<typename... ImageTypes> void dyno::ImageContainerSubset< ImageTypes >::validateSetup protected virtual
Validates that the input images (if not empty) are the same size. Throws ImageContainerConstructionException if invalid.
Compares all non-empty images against the first image size
Can be overwritten.
Reimplemented in dyno::ImageContainerDeprecate.
Definition at line 71 of file ImageContainer-inl.hpp.
{
    cv::Size required_size;
    for (size_t i = 0; i < N; i++) {
        //get the type at the new subset
        internal::select_apply<N>(i, [&](auto stream_index) {
            using ImageTypeStruct = typename This::ImageTypeStruct<stream_index>;
            //only check if exists?
            if(This::exists<ImageTypeStruct>()) {
                //if required size is empty, then first check
                //set required size to be the image size and then compare against
                //this size on future iterations
                const bool is_first = required_size.empty();
                if(is_first) {
                    required_size = This::get<ImageTypeStruct>().size();
                }
                else {
                    //compare against required size
                    const cv::Size incoming_size = This::get<ImageTypeStruct>().size();
                    if(incoming_size != required_size) {
                        throw ImageContainerConstructionException(
                            "Non-empty images were not all the same size. First image (type: " +
                            type_name<This::ImageTypeStruct<0u>>() + ") was of size " + to_string(required_size) +
                            " and other image (type: " + type_name<ImageTypeStruct>() + ") was of size " + to_string(incoming_size)
                        );
                    }
                }
            }
        });
    }
}
References dyno::to_string(), and dyno::type_name().
Member Data Documentation
image_storage_
template<typename... ImageTypes> WrappedImageTypesTuple dyno::ImageContainerSubset< ImageTypes >::image_storage_ protected
Definition at line 249 of file ImageContainer.hpp.
Referenced by dyno::ImageContainerSubset< ImageTypes >::get(), and dyno::ImageContainerSubset< ImageTypes >::getImageWrapper().
N
template<typename... ImageTypes> constexpr size_t dyno::ImageContainerSubset< ImageTypes >::N = sizeof...(ImageTypes) static constexpr
Number of image types contained in this subset.
Definition at line 86 of file ImageContainer.hpp.
The documentation for this class was generated from the following files:
dynosam/include/dynosam/common/ImageContainer.hpp
dynosam/include/dynosam/common/ImageContainer-inl.hpp