DynoSAM: dyno::WorldPoseFormulation Class Reference
dyno::WorldPoseFormulation Class Reference
#include <WorldPoseEstimator.hpp>
Public Types
using Base = Formulation< MapVision >
Public Types inherited from dyno::Formulation< MapVision >
using Map = MapVision
using This = Formulation< Map >
using MapTraitsType = MapTraits< Map >
using MeasurementType = typename MapTraitsType::MeasurementType
using MeasurementTraits = measurement_traits< MeasurementType >
using PointUpdateContextType = PointUpdateContext< Map >
using ObjectUpdateContextType = ObjectUpdateContext< Map >
using AccessorType = AccessorT< MapVision >
using AccessorTypePointer = typename AccessorT< MapVision >::Ptr
Public Member Functions
WorldPoseFormulation (const FormulationParams &params, typename Map::Ptr map, const NoiseModels &noise_models, const Sensors &sensors, const FormulationHooks &hooks)
virtual ~WorldPoseFormulation ()
void dynamicPointUpdateCallback (const PointUpdateContextType &context, UpdateObservationResult &result, gtsam::Values &new_values, gtsam::NonlinearFactorGraph &new_factors) override
void objectUpdateContext (const ObjectUpdateContextType &context, UpdateObservationResult &result, gtsam::Values &new_values, gtsam::NonlinearFactorGraph &new_factors) override
bool isDynamicTrackletInMap (const typename MapTraitsType::LandmarkNodePtr &lmk_node) const override
Virtual function to be implemented by derived class and indicates that the specified landmark exists within the graph already. This is used as part of the internal bookeeping.
Public Member Functions inherited from dyno::Formulation< MapVision >
Formulation (const FormulationParams &params, typename Map::Ptr map, const NoiseModels &noise_models, const Sensors &sensors, const FormulationHooks &hooks=FormulationHooks())
virtual ~Formulation ()=default
Map::Ptr map () const
Get the map used by the formulation.
const gtsam::Values & getTheta () const
Get the current linearization point for this formulation. These values can be updated after external optimisation and are constructed by the derived formulation during update.
void setTheta (const gtsam::Values &linearization)
Sets the full set of theta values (overrides them). This is used after external optimisation to update the values for the accessor which has a internal reference (pointer) to theta.
void updateTheta (const gtsam::Values &linearization)
Updates and assigns new values to theta. This is used after external optimisation to update the values for the accessor which has a internal reference (pointer) to theta.
const gtsam::NonlinearFactorGraph & getGraph () const
Gets the current graph associated with the current theta and constructed by the derived formulation. Along theta, this should be used by an external optimisation routine.
const FormulationHooks & hooks () const
const NoiseModels & noiseModels () const
const Sensors & sensors () const
const FormulationParams & params () const
virtual gtsam::KeyFormatter formatter () const
Custom gtsam::Key formatter for this formulation. Defaults to DynosamKeyFormatter.
std::string format (const gtsam::Key &key) const
const std::string getFullyQualifiedName () const
Get the fully qualified name of this formulation which is derived from the loggerPrefix and optionally the FormulationParams::suffix if given.
AccessorType::Ptr accessorFromTheta () const
Public fucntion to access the Accessor for the derived formulation.
std::shared_ptr< Derived > derivedAccessor () const
BackendLogger::UniquePtr makeFullyQualifiedLogger () const
Makes a logger using the fully-qualified name for this formulation.
void addValuesFunctional (std::function< void(gtsam::Values &)> callback, gtsam::Values &new_values)
void addFactorsFunctional (std::function< void(gtsam::NonlinearFactorGraph &)> callback, gtsam::NonlinearFactorGraph &new_factors)
void addSensorPoseValue (const gtsam::Pose3 &X_W_k, FrameId frame_id_k, gtsam::Values &new_values)
void addSensorPosePriorFactor (const gtsam::Pose3 &X_W_k, gtsam::SharedNoiseModel noise_model, FrameId frame_id_k, gtsam::NonlinearFactorGraph &new_factors)
void setInitialPose (const gtsam::Pose3 &T_world_camera, FrameId frame_id_k, gtsam::Values &new_values)
Adds a gtsam::Pose3 as a value in the graph at frame k.
void setInitialPosePrior (const gtsam::Pose3 &T_world_camera, FrameId frame_id_k, gtsam::NonlinearFactorGraph &new_factors)
Adds a pose prior on a value in the graph at frame k using the given pose value as the prior's mean.
UpdateObservationResult updateStaticObservations (FrameId frame_id_k, gtsam::Values &new_values, gtsam::NonlinearFactorGraph &new_factors, const UpdateObservationParams &update_params)
Updates the static-point part of the factor graph for frame k. This contains all the bookeeping logic to update the factor graph with static points.
UpdateObservationResult updateDynamicObservations (FrameId frame_id_k, gtsam::Values &new_values, gtsam::NonlinearFactorGraph &new_factors, const UpdateObservationParams &update_params)
Updates the dyanmic-point part of the factor graph for frame k. This contains all the big-boi bookeeping logic to update the factor graph with dyanmic points and objects. This is where the virtual dynamicPointUpdateCallback and objectUpdateContext functions are called.
void logBackendFromMap (const BackendMetaData &backend_info)
Logs all frames and values to file using Accessor and BackendLogger. The BackendMetaData provides meta-data and ground truth information for logging.
virtual void preUpdate (const PreUpdateData &)
Pre update hook called in the RegularBackend after the map is updated with new measurements but before new values/factors are constructed from this formulation.
virtual void postUpdate (const PostUpdateData &)
Post-update hook called in the RegulatBackend after graph construction and optimization!
gtsam::Pose3 getInitialOrLinearizedSensorPose (FrameId frame_id) const
Protected Member Functions
AccessorTypePointer createAccessor (const SharedFormulationData &shared_data) const override
Creates the associated Accessor for the derived formulation. The accessor will contain a pointer to This::theta_, so that when the values are updated the accessor has access to the latest values.
std::string loggerPrefix () const override
Defines the base name of this formulation. This name will appear as part of the output logs and may be augmented with the FormulationParams::suffix, if given. To get the fully qualified name (the actual name that will appear in the logs), use This::getFullyQualifiedName().
Protected Member Functions inherited from dyno::Formulation< MapVision >
virtual void dynamicPointUpdateCallback (const PointUpdateContextType &context, UpdateObservationResult &result, gtsam::Values &new_values, gtsam::NonlinearFactorGraph &new_factors)=0
Virtual function to be implemented by derived class and indicates that a specific landmark has new measurements and new values/factors should be added. Details on the landmark to be updated are provied by the context. In general, this is used to add projection/motion factors and initial values for landmarks.
virtual void objectUpdateContext (const ObjectUpdateContextType &context, UpdateObservationResult &result, gtsam::Values &new_values, gtsam::NonlinearFactorGraph &new_factors)=0
Virtual function to be implemented by derived class and indicates that a specific object j and time-step k has been observed and its dynamic points updated in the graph, and associated values/factors should be added. Details on the object to be updated are provied by the context. In general, this is used to add smoothing factors and initial values for object motion/pose.
virtual bool isDynamicTrackletInMap (const typename MapTraitsType::LandmarkNodePtr &lmk_node) const=0
Virtual function to be implemented by derived class and indicates that the specified landmark exists within the graph already. This is used as part of the internal bookeeping.
virtual std::string loggerPrefix () const=0
Defines the base name of this formulation. This name will appear as part of the output logs and may be augmented with the FormulationParams::suffix, if given. To get the fully qualified name (the actual name that will appear in the logs), use This::getFullyQualifiedName().
virtual AccessorType::Ptr createAccessor (const SharedFormulationData &shared_data) const=0
Creates the associated Accessor for the derived formulation. The accessor will contain a pointer to This::theta_, so that when the values are updated the accessor has access to the latest values.
void clearGraph ()
Protected Attributes
gtsam::FastMap< TrackletId, bool > is_dynamic_tracklet_in_map_
Protected Attributes inherited from dyno::Formulation< MapVision >
const FormulationParams params_
Map::Ptr map_
const NoiseModels noise_models_
Sensors sensors_
FormulationHooks hooks_
gtsam::FastMap< gtsam::Key, bool > is_other_values_in_map
gtsam::Values theta_
Current linearisation that will be associated with the current graph.
gtsam::NonlinearFactorGraph factors_
Detailed Description
Definition at line 55 of file WorldPoseEstimator.hpp.
Member Typedef Documentation
Base
using dyno::WorldPoseFormulation::Base = Formulation<MapVision>
Definition at line 57 of file WorldPoseEstimator.hpp.
Constructor & Destructor Documentation
WorldPoseFormulation()
dyno::WorldPoseFormulation::WorldPoseFormulation (const FormulationParams & params, typename Map::Ptr map, const NoiseModels & noise_models, const Sensors & sensors, const FormulationHooks & hooks) inline
Definition at line 65 of file WorldPoseEstimator.hpp.
      : Base(params, map, noise_models, sensors, hooks) {}
~WorldPoseFormulation()
virtual dyno::WorldPoseFormulation::~WorldPoseFormulation () inline virtual
Definition at line 69 of file WorldPoseEstimator.hpp.
{}
Member Function Documentation
createAccessor()
AccessorTypePointer dyno::WorldPoseFormulation::createAccessor (const SharedFormulationData & shared_data) const inline override protected virtual
Creates the associated Accessor for the derived formulation. The accessor will contain a pointer to This::theta_, so that when the values are updated the accessor has access to the latest values.
Parameters
values const gtsam::Values*
Returns
AccessorType::Ptr
Implements dyno::Formulation< MapVision >.
Definition at line 87 of file WorldPoseEstimator.hpp.
{
    return std::make_shared<WorldPoseAccessor>(shared_data, this->map());
  }
References dyno::Formulation< MapVision >::map().
dynamicPointUpdateCallback()
void dyno::WorldPoseFormulation::dynamicPointUpdateCallback (const PointUpdateContextType & context, UpdateObservationResult & result, gtsam::Values & new_values, gtsam::NonlinearFactorGraph & new_factors) override
Definition at line 89 of file WorldPoseEstimator.cc.
{
  const auto lmk_node = context.lmk_node;
  const auto frame_node_k_1 = context.frame_node_k_1;
  const auto frame_node_k = context.frame_node_k;
  auto dynamic_point_noise = noise_models_.dynamic_point_noise;
  auto theta_accessor = this->accessorFromTheta();
  const gtsam::Key object_point_key_k_1 =
      lmk_node->makeDynamicKey(frame_node_k_1->frame_id);
  const gtsam::Key object_point_key_k =
      lmk_node->makeDynamicKey(frame_node_k->frame_id);
  // if first motion (i.e first time we have both k-1 and k), add both at k-1
  // and k
  if (context.is_starting_motion_frame) {
    auto [measured_point_local, measurement_covariance] =
        MeasurementTraits::pointWithCovariance(
            lmk_node->getMeasurement(frame_node_k_1));
    if (params_.makeDynamicMeasurementsRobust()) {
      measurement_covariance = factor_graph_tools::robustifyHuber(
          params_.k_huber_3d_points_, measurement_covariance);
    }
    new_factors.emplace_shared<PoseToPointFactor>(
        frame_node_k_1->makePoseKey(),  // pose key at previous frames
        object_point_key_k_1, measured_point_local, measurement_covariance);
    // object_debug_info.num_dynamic_factors++;
    result.updateAffectedObject(frame_node_k_1->frame_id,
                                context.getObjectId());
    if (result.debug_info)
      result.debug_info->getObjectInfo(context.getObjectId())
          .num_dynamic_factors++;
    // add landmark at previous frame
    Landmark lmk_world_k_1;
    getSafeQuery(lmk_world_k_1,
                 theta_accessor->query<Landmark>(object_point_key_k_1),
                 gtsam::Point3(context.X_k_1_measured * measured_point_local));
    new_values.insert(object_point_key_k_1, lmk_world_k_1);
    if (result.debug_info)
      result.debug_info->getObjectInfo(context.getObjectId())
          .num_new_dynamic_points++;
  }
  // previous point must be added by the previous iteration
  CHECK(new_values.exists(object_point_key_k_1) ||
        theta_accessor->exists(object_point_key_k_1));
  // const Landmark measured_k =
  // lmk_node->getMeasurement(frame_node_k).landmark;
  auto [measured_point_local, measurement_covariance] =
      MeasurementTraits::pointWithCovariance(
          lmk_node->getMeasurement(frame_node_k));
  if (params_.makeDynamicMeasurementsRobust()) {
    measurement_covariance = factor_graph_tools::robustifyHuber(
        params_.k_huber_3d_points_, measurement_covariance);
  }
  new_factors.emplace_shared<PoseToPointFactor>(
      frame_node_k
          ->makePoseKey(),  // pose key at this (in the iteration) frames
      object_point_key_k, measured_point_local, measurement_covariance);
  if (result.debug_info)
    result.debug_info->getObjectInfo(context.getObjectId())
        .num_dynamic_factors++;
  result.updateAffectedObject(frame_node_k->frame_id, context.getObjectId());
  Landmark lmk_world_k;
  getSafeQuery(lmk_world_k, theta_accessor->query<Landmark>(object_point_key_k),
               gtsam::Point3(context.X_k_measured * measured_point_local));
  new_values.insert(object_point_key_k, lmk_world_k);
  if (result.debug_info)
    result.debug_info->getObjectInfo(context.getObjectId())
        .num_new_dynamic_points++;
  const gtsam::Key object_pose_k_1_key =
      frame_node_k_1->makeObjectPoseKey(context.getObjectId());
  const gtsam::Key object_pose_k_key =
      frame_node_k->makeObjectPoseKey(context.getObjectId());
  auto landmark_motion_noise = noise_models_.landmark_motion_noise;
  new_factors.emplace_shared<LandmarkMotionPoseFactor>(
      object_point_key_k_1, object_point_key_k, object_pose_k_1_key,
      object_pose_k_key, landmark_motion_noise);
  result.updateAffectedObject(frame_node_k_1->frame_id, context.getObjectId());
  result.updateAffectedObject(frame_node_k->frame_id, context.getObjectId());
  if (result.debug_info)
    result.debug_info->getObjectInfo(context.getObjectId())
        .num_motion_factors++;
  // mark as now in map
  is_dynamic_tracklet_in_map_.insert2(context.getTrackletId(), true);
}
References dyno::Formulation< MapVision >::accessorFromTheta(), dyno::UpdateObservationResult::debug_info, dyno::NoiseModels::dynamic_point_noise, dyno::getSafeQuery(), is_dynamic_tracklet_in_map_, dyno::BackendParams::k_huber_3d_points_, dyno::NoiseModels::landmark_motion_noise, dyno::BackendParams::makeDynamicMeasurementsRobust(), dyno::Formulation< MapVision >::noise_models_, dyno::Formulation< MapVision >::params_, dyno::factor_graph_tools::robustifyHuber(), and dyno::UpdateObservationResult::updateAffectedObject().
isDynamicTrackletInMap()
bool dyno::WorldPoseFormulation::isDynamicTrackletInMap (const typename MapTraitsType::LandmarkNodePtr & lmk_node) const inline override virtual
Virtual function to be implemented by derived class and indicates that the specified landmark exists within the graph already. This is used as part of the internal bookeeping.
Parameters
lmk_node typename MapTraitsType::LandmarkNodePtr&. Pointer to a landmark node.
Returns
true
false
Implements dyno::Formulation< MapVision >.
Definition at line 80 of file WorldPoseEstimator.hpp.
{
    const TrackletId tracklet_id = lmk_node->tracklet_id;
    return is_dynamic_tracklet_in_map_.exists(tracklet_id);
  }
References is_dynamic_tracklet_in_map_.
loggerPrefix()
std::string dyno::WorldPoseFormulation::loggerPrefix () const inline override protected virtual
Defines the base name of this formulation. This name will appear as part of the output logs and may be augmented with the FormulationParams::suffix, if given. To get the fully qualified name (the actual name that will appear in the logs), use This::getFullyQualifiedName().
Returns
std::string
Implements dyno::Formulation< MapVision >.
Definition at line 92 of file WorldPoseEstimator.hpp.
{ return "wcpe"; }
objectUpdateContext()
void dyno::WorldPoseFormulation::objectUpdateContext (const ObjectUpdateContextType & context, UpdateObservationResult & result, gtsam::Values & new_values, gtsam::NonlinearFactorGraph & new_factors) override
Definition at line 189 of file WorldPoseEstimator.cc.
{
  auto frame_node_k = context.frame_node_k;
  const gtsam::Key object_pose_key_k =
      frame_node_k->makeObjectPoseKey(context.getObjectId());
  auto theta_accessor = this->accessorFromTheta();
  if (!is_other_values_in_map.exists(object_pose_key_k)) {
    FrameId frame_id_k_1 = context.getFrameId() - 1u;
    // try and propogate from previous initalisation
    StateQuery<gtsam::Pose3> pose_k_1_query =
        theta_accessor->getObjectPose(frame_id_k_1, context.getObjectId());
    // first frame the object is seen in
    const FrameId first_seen_frame = context.object_node->getFirstSeenFrame();
    // takes me from k-1 to k
    Motion3 motion;
    gtsam::Pose3 object_pose_k;
    // we have a motion from k-1 to k and a pose at k
    if (map()->hasInitialObjectMotion(context.getFrameId(),
                                      context.getObjectId(), &motion) &&
        pose_k_1_query) {
      object_pose_k = motion * pose_k_1_query.get();
      CHECK_NE(first_seen_frame, context.getFrameId());
    } else {
      // no motion or previous pose, so initalise with centroid translation and
      // identity rotation
      const auto [centroid_initial, result] =
          theta_accessor->computeObjectCentroid(context.getFrameId(),
                                                context.getObjectId());
      CHECK(result);
      gtsam::Pose3 initial_object_pose(gtsam::Rot3::Identity(),
                                       centroid_initial);
      getSafeQuery(object_pose_k,
                   theta_accessor->query<gtsam::Pose3>(object_pose_key_k),
                   initial_object_pose);
      // CHECK_EQ(first_seen_frame, context.getFrameId());
    }
    // for experiments and testing
    constexpr static bool init_LL_with_identity = false;
    constexpr static bool use_identity_rot_L_for_init = false;
    constexpr static bool corrupt_L_for_init = false;
    if (init_LL_with_identity && pose_k_1_query) {
      object_pose_k = pose_k_1_query.get();
    }
    if (use_identity_rot_L_for_init) {
      auto tmp_pose =
          gtsam::Pose3(gtsam::Rot3::Identity(), object_pose_k.translation());
      object_pose_k = tmp_pose;
    }
    if (corrupt_L_for_init) {
      object_pose_k = utils::perturbWithNoise<gtsam::Pose3>(object_pose_k, 0.2);
    }
    LOG(INFO) << "Adding object pose " << object_pose_k << " object id "
              << context.getObjectId();
    new_values.insert(object_pose_key_k, object_pose_k);
    is_other_values_in_map.insert2(object_pose_key_k, true);
    VLOG(50) << "Adding object pose key "
             << DynosamKeyFormatter(object_pose_key_k);
  }
  if (FLAGS_use_smoothing_factor) {
    const auto frame_id = context.getFrameId();
    const auto object_id = context.getObjectId();
    if (frame_id < 2) return;
    auto frame_node_k_2 = map()->getFrame(frame_id - 2u);
    auto frame_node_k_1 = map()->getFrame(frame_id - 1u);
    if (!frame_node_k_2 || !frame_node_k_1) {
      return;
    }
    // pose key at k-2
    const gtsam::Symbol object_pose_key_k_2 =
        frame_node_k_2->makeObjectPoseKey(object_id);
    // pose key at previous frame (k-1)
    const gtsam::Symbol object_pose_key_k_1 =
        frame_node_k_1->makeObjectPoseKey(object_id);
    auto object_smoothing_noise = noise_models_.object_smoothing_noise;
    CHECK(object_smoothing_noise);
    CHECK_EQ(object_smoothing_noise->dim(), 6u);
    {
      ObjectId object_label_k_2, object_label_k_1, object_label_k;
      FrameId frame_id_k_2, frame_id_k_1, frame_id_k;
      CHECK(reconstructPoseInfo(object_pose_key_k_2, object_label_k_2,
                                frame_id_k_2));
      CHECK(reconstructPoseInfo(object_pose_key_k_1, object_label_k_1,
                                frame_id_k_1));
      CHECK(reconstructPoseInfo(object_pose_key_k, object_label_k, frame_id_k));
      CHECK_EQ(object_label_k_2, object_label_k);
      CHECK_EQ(object_label_k_1, object_label_k);
      CHECK_EQ(frame_id_k_1 + 1, frame_id_k);    // assumes consequative frames
      CHECK_EQ(frame_id_k_2 + 1, frame_id_k_1);  // assumes consequative frames
    }
    // if the motion key at k (motion from k-1 to k), and key at k-1 (motion
    // from k-2 to k-1) exists in the map or is about to exist via new values,
    // add the smoothing factor
    if (is_other_values_in_map.exists(object_pose_key_k_1) &&
        is_other_values_in_map.exists(object_pose_key_k) &&
        is_other_values_in_map.exists(object_pose_key_k_2)) {
      new_factors.emplace_shared<LandmarkPoseSmoothingFactor>(
          object_pose_key_k_2, object_pose_key_k_1, object_pose_key_k,
          object_smoothing_noise);
      if (result.debug_info)
        result.debug_info->getObjectInfo(object_id).smoothing_factor_added =
            true;
      VLOG(50) << "Adding smoothing "
               << DynosamKeyFormatter(object_pose_key_k_2) << " -> "
               << DynosamKeyFormatter(object_pose_key_k);
    }
  }
}
References dyno::Formulation< MapVision >::accessorFromTheta(), dyno::UpdateObservationResult::debug_info, dyno::DynosamKeyFormatter(), dyno::StateQuery< ValueType >::get(), dyno::getSafeQuery(), dyno::Formulation< MapVision >::is_other_values_in_map, dyno::Formulation< MapVision >::map(), dyno::Formulation< MapVision >::noise_models_, dyno::NoiseModels::object_smoothing_noise, and dyno::reconstructPoseInfo().
Member Data Documentation
is_dynamic_tracklet_in_map_
gtsam::FastMap<TrackletId, bool> dyno::WorldPoseFormulation::is_dynamic_tracklet_in_map_ protected
Definition at line 100 of file WorldPoseEstimator.hpp.
Referenced by dyno::WorldMotionFormulation::dynamicPointUpdateCallback(), dynamicPointUpdateCallback(), and isDynamicTrackletInMap().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/backend/rgbd/WorldPoseEstimator.hpp
dynosam/src/backend/rgbd/WorldPoseEstimator.cc