DynoSAM: dyno::Accessor< MAP > Class Template Reference
dyno::Accessor< MAP > Class Template Reference abstract
Accessor defines the interface between the structured output of a BackendModule and any formulation used to construct the Dynamic SLAM problem.
#include <Accessor.hpp>
Public Types
using Map = MAP
using This = Accessor< Map >
Public Member Functions
Accessor (const SharedFormulationData &shared_data, typename Map::Ptr map)
virtual ~Accessor ()
virtual StateQuery< gtsam::Pose3 > getSensorPose (FrameId frame_id) const =0
Get the sensor pose (^wX_k) from theta at the requested time-step.
virtual StateQuery< gtsam::Pose3 > getObjectMotion (FrameId frame_id, ObjectId object_id) const =0
Get an absolute object motion (_{k-1}^wH_k) from theta the requested time-step (k) and object (j).
StateQuery< Motion3ReferenceFrame > getObjectMotionReferenceFrame (FrameId frame_id, ObjectId object_id) const
Gets the absolute motion (_{k-1}^wH_k) from theta the requested time-step (k) and object (j) with the associated reference frame. Internally this uses getObjectMotion and constructs a Motion3ReferenceFrame using the global frame, k-1 and k. No checks are done on the underlying function call so it assumes that the virtual getObjectMotion function has been implemented correctly and returns a motion in the right representation.
virtual StateQuery< gtsam::Pose3 > getObjectPose (FrameId frame_id, ObjectId object_id) const =0
Get the pose (^wL_k) of an object (j) at time-step (k).
virtual StateQuery< gtsam::Point3 > getDynamicLandmark (FrameId frame_id, TrackletId tracklet_id) const =0
Get a dynamic landmark (^wm_k) with tracklet id (i) at time-step (k).
virtual StateQuery< gtsam::Point3 > getStaticLandmark (TrackletId tracklet_id) const
Get a static landmark (^wm) with tracklet id (i).
virtual EstimateMap< ObjectId, gtsam::Pose3 > getObjectPoses (FrameId frame_id) const
Collects all object poses at some time-step (k). This is equivalent to \mathcal{L}_k. Is a (non-pure) virtual function so may be overwritten - default implementation uses the pure-virtual getObjectPose function to collect all object poses.
MotionEstimateMap getObjectMotions (FrameId frame_id) const
Collects all object motions from some time-step (k-1) to k. This is equivalent to \mathcal{H}_k. Uses the pure-virtual getObjectMotion function to collect all object motions.
EstimateMap< ObjectId, std::pair< Motion3, gtsam::Pose3 > > getObjectPrevPosePair (FrameId frame_id) const
Gets an estimate map of objects with their motion and and PREVIOUS pose. This will find motions and poses (using the internal API) and return a motion from k-1 to k and the associated pose at k-1.
EstimateMap< ObjectId, std::pair< Motion3, gtsam::Pose3 > > getObjectPosePair (FrameId frame_id) const
Gets an estimate map of objects with their motion and and CURRENT pose. This will find motions and poses (using the internal API) and return a motion from k-1 to k and the associated pose at k.
virtual ObjectPoseMap getObjectPoses () const
Collects all object poses for frame 0 to K. (Non-pure)Virtual function that may be overwritten - default implementation uses the pure-virtual getObjectPoses to collect all poses.
virtual ObjectMotionMap getObjectMotions () const
Collects all object motions from 1 to K (with the first motion being from k-1 to k). (Non-pure) Virtual function that may be overwritten - default implementation uses the pure-virtual getObjectPoses to collect all motions.
StatusLandmarkVector getDynamicLandmarkEstimates (FrameId frame_id) const
Get all dynamic landmarks for all objects (\mathcal{J}_k) at time-step k.
virtual StatusLandmarkVector getDynamicLandmarkEstimates (FrameId frame_id, ObjectId object_id) const
Get all dynamic landmarks for object j at time-step k.
StatusLandmarkVector getStaticLandmarkEstimates (FrameId frame_id) const
Get all static landmarks at time-step k.
StatusLandmarkVector getFullStaticMap () const
Get all static landmarks from time-step 0 to k.
StatusLandmarkVector getLandmarkEstimates (FrameId frame_id) const
Get all landmarks (static and dynamic) at time-step k.
bool hasObjectMotionEstimate (FrameId frame_id, ObjectId object_id, Motion3 *motion=nullptr) const
Check if there exists an estimate for object motion at time-step (k) for object id (j). If result is true and a motion is provided, return true and set the motion.
bool hasObjectMotionEstimate (FrameId frame_id, ObjectId object_id, Motion3 &motion) const
Check if there exists an estimate for object motion at time-step (k) for object id (j). If result is true, motion reference value is set to the motion.
bool hasObjectPoseEstimate (FrameId frame_id, ObjectId object_id, gtsam::Pose3 *pose=nullptr) const
Check if there exists an estimate for object pose at time-step (k) for object id (j). If result is true and a pose is provided, return true and set the pose.
bool hasObjectPoseEstimate (FrameId frame_id, ObjectId object_id, gtsam::Pose3 &pose) const
Check if there exists an estimate for object pose at time-step (k) for object id (j). If result is true, pose reference value is set to the pose.
gtsam::FastMap< ObjectId, gtsam::Point3 > computeObjectCentroids (FrameId frame_id) const
Computes a the centroid of each object at this frame using the estimated dynamic points.
std::tuple< gtsam::Point3, bool > computeObjectCentroid (FrameId frame_id, ObjectId object_id) const
Computes the centroid of the requested object using the estimated dynamic points.
bool exists (gtsam::Key key) const
Check if the key exists in the current theta.
template<typename ValueType >
StateQuery< ValueType > query (gtsam::Key key) const
Access a key in the current theta.
Protected Member Functions
auto map () const
const gtsam::Values & values () const
const FormulationHooks & hooks () const
Private Member Functions
EstimateMap< ObjectId, std::pair< Motion3, gtsam::Pose3 > > getRequestedObjectPosePair (FrameId motion_frame_id, FrameId pose_frame_id) const
Compute all pairs of object motions and poses at the requested time-steps. As usual, motion_frame_id is treated as k, and therefore motions from motion_frame_id-1 to motion_frame_id will be retrieved.
Private Attributes
const SharedFormulationData shared_data_
Map::Ptr map_
Detailed Description
template<class MAP>
class dyno::Accessor< MAP >
Accessor defines the interface between the structured output of a BackendModule and any formulation used to construct the Dynamic SLAM problem.
Each derived Accessor is associated with a derived Formulation and knows how to access the variables in that problem and convert them into the form expected by the backend. This is equivalent to constructing \mathbf{O}_k = [ ^wX_k, \othmotion{\worldf}{k-1}{\mathcal{H}}{k}, ^{\worldf}\mathcal{L}_{k} , {^\worldf\mathcal{M}_k}].
Template Parameters
MAP
Definition at line 52 of file Accessor.hpp.
Member Typedef Documentation
Map
template<class MAP > using dyno::Accessor< MAP >::Map = MAP
Definition at line 54 of file Accessor.hpp.
This
template<class MAP > using dyno::Accessor< MAP >::This = Accessor<Map>
Definition at line 55 of file Accessor.hpp.
Constructor & Destructor Documentation
Accessor()
template<class MAP > dyno::Accessor< MAP >::Accessor (const SharedFormulationData & shared_data, typename Map::Ptr map)
Definition at line 40 of file Accessor-impl.hpp.
    : shared_data_(shared_data), map_(map) {
  CHECK_NOTNULL(shared_data.values);
  CHECK_NOTNULL(shared_data.hooks);
}
References dyno::SharedFormulationData::hooks, and dyno::SharedFormulationData::values.
~Accessor()
template<class MAP > virtual dyno::Accessor< MAP >::~Accessor () inline virtual
Definition at line 60 of file Accessor.hpp.
{}
Member Function Documentation
computeObjectCentroid()
template<class MAP > std::tuple< gtsam::Point3, bool > dyno::Accessor< MAP >::computeObjectCentroid (FrameId frame_id, ObjectId object_id) const
Computes the centroid of the requested object using the estimated dynamic points.
Returns false (as part of the pair) if object cannot be found or has zero points.
Parameters
frame_id FrameId
object_id ObjectId
Returns
std::tuple<gtsam::Point3, bool>
Definition at line 330 of file Accessor-impl.hpp.
{
  const StatusLandmarkVector& dynamic_lmks =
      this->getDynamicLandmarkEstimates(frame_id, object_id);
  // convert to point cloud - should be a map with only one map in it
  CloudPerObject object_clouds =
      groupObjectCloud(dynamic_lmks, this->getSensorPose(frame_id).get());
  if (object_clouds.size() == 0) {
    VLOG(20) << "Cannot collect object clouds from dynamic landmarks of "
             << object_id << " and frame " << frame_id << "!! "
             << " # Dynamic lmks in the map for this object at this frame was "
             << dynamic_lmks.size();  //<< " but reocrded lmks was " <<
                                      // dynamic_landmarks.size();
    return {gtsam::Point3{}, false};
  }
  CHECK_EQ(object_clouds.size(), 1);
  CHECK(object_clouds.exists(object_id));
  const auto dynamic_point_cloud = object_clouds.at(object_id);
  pcl::PointXYZ centroid;
  pcl::computeCentroid(dynamic_point_cloud, centroid);
  // TODO: outlier reject?
  gtsam::Point3 translation = pclPointToGtsam(centroid);
  return {translation, true};
}
computeObjectCentroids()
template<class MAP > gtsam::FastMap< ObjectId, gtsam::Point3 > dyno::Accessor< MAP >::computeObjectCentroids (FrameId frame_id) const
Computes a the centroid of each object at this frame using the estimated dynamic points.
Internally, uses the overloaded std::tuple<gtsam::Point3, bool> computeObjectCentroid function and only includes centroids which are valid (ie returned with computeObjectCentroid()->second == true)
Parameters
frame_id FrameId
Returns
gtsam::FastMap<ObjectId, gtsam::Point3>
Definition at line 308 of file Accessor-impl.hpp.
{
  gtsam::FastMap<ObjectId, gtsam::Point3> centroids;
  const auto frame_node = map()->getFrame(frame_id);
  if (!frame_node) {
    return centroids;
  }
  const auto object_seen =
      frame_node->objects_seen.template collectIds<ObjectId>();
  for (ObjectId object_id : object_seen) {
    const auto [centroid, result] = computeObjectCentroid(frame_id, object_id);
    if (result) {
      centroids.insert2(object_id, centroid);
    }
  }
  return centroids;
}
exists()
template<class MAP > bool dyno::Accessor< MAP >::exists (gtsam::Key key) const
Check if the key exists in the current theta.
Parameters
key gtsam::Key
Returns
true
false
Definition at line 385 of file Accessor-impl.hpp.
{
  const gtsam::Values* theta = shared_data_.values;
  CHECK_NOTNULL(theta);
  return theta->exists(key);
}
getDynamicLandmark()
template<class MAP > virtual StateQuery< gtsam::Point3 > dyno::Accessor< MAP >::getDynamicLandmark (FrameId frame_id, TrackletId tracklet_id) const pure virtual
Get a dynamic landmark (^wm_k) with tracklet id (i) at time-step (k).
Parameters
frame_id FrameId
tracklet_id TrackletId
Returns
StateQuery<gtsam::Point3>
Implemented in dyno::HybridAccessor, and dyno::WorldPoseAccessor.
getDynamicLandmarkEstimates() [1/2]
template<class MAP > StatusLandmarkVector dyno::Accessor< MAP >::getDynamicLandmarkEstimates (FrameId frame_id) const
Get all dynamic landmarks for all objects (\mathcal{J}_k) at time-step k.
Parameters
frame_id FrameId
Returns
StatusLandmarkVector
Definition at line 154 of file Accessor-impl.hpp.
{
  const auto frame_node = map()->getFrame(frame_id);
  CHECK_NOTNULL(frame_node);
  StatusLandmarkVector estimates;
  const auto object_seen =
      frame_node->objects_seen.template collectIds<ObjectId>();
  for (ObjectId object_id : object_seen) {
    estimates += this->getDynamicLandmarkEstimates(frame_id, object_id);
  }
  return estimates;
}
getDynamicLandmarkEstimates() [2/2]
template<class MAP > StatusLandmarkVector dyno::Accessor< MAP >::getDynamicLandmarkEstimates (FrameId frame_id, ObjectId object_id) const virtual
Get all dynamic landmarks for object j at time-step k.
Parameters
frame_id FrameId
object_id ObjectId
Returns
StatusLandmarkVector
Reimplemented in dyno::HybridAccessor.
Definition at line 169 of file Accessor-impl.hpp.
{
  const auto frame_node = map()->getFrame(frame_id);
  CHECK_NOTNULL(frame_node);
  if (!frame_node->objectObserved(object_id)) {
    return StatusLandmarkVector{};
  }
  StatusLandmarkVector estimates;
  const auto& dynamic_landmarks = frame_node->dynamic_landmarks;
  for (auto lmk_node : dynamic_landmarks) {
    const auto tracklet_id = lmk_node->tracklet_id;
    if (object_id != lmk_node->object_id) {
      continue;
    }
    // user defined function should put point in the world frame
    StateQuery<gtsam::Point3> lmk_query =
        this->getDynamicLandmark(frame_id, tracklet_id);
    if (lmk_query) {
      estimates.push_back(LandmarkStatus::DynamicInGLobal(
          Point3Measurement(lmk_query.get()),  // estimate
          frame_id, tracklet_id,
          object_id)  // status
      );
    }
  }
  return estimates;
}
getFullStaticMap()
template<class MAP > StatusLandmarkVector dyno::Accessor< MAP >::getFullStaticMap
Get all static landmarks from time-step 0 to k.
Returns
StatusLandmarkVector
Definition at line 230 of file Accessor-impl.hpp.
{
  // dont go over the frames as this contains references to the landmarks
  // multiple times e.g. the ones seen in that frame
  StatusLandmarkVector estimates;
  const auto landmarks = map()->getLandmarks();
  for (const auto& [_, landmark_node] : landmarks) {
    if (landmark_node->isStatic()) {
      StateQuery<gtsam::Point3> lmk_query =
          getStaticLandmark(landmark_node->tracklet_id);
      if (lmk_query) {
        estimates.push_back(LandmarkStatus::StaticInGlobal(
            Point3Measurement(lmk_query.get()),  // estimate
            LandmarkStatus::MeaninglessFrame,
            landmark_node->getId()  // tracklet id
            )                       // status
        );
      }
    }
  }
  return estimates;
}
getLandmarkEstimates()
template<class MAP > StatusLandmarkVector dyno::Accessor< MAP >::getLandmarkEstimates (FrameId frame_id) const
Get all landmarks (static and dynamic) at time-step k.
Parameters
frame_id FrameId
Returns
StatusLandmarkVector
Definition at line 254 of file Accessor-impl.hpp.
{
  StatusLandmarkVector estimates;
  estimates += getStaticLandmarkEstimates(frame_id);
  estimates += getDynamicLandmarkEstimates(frame_id);
  return estimates;
}
getObjectMotion()
template<class MAP > virtual StateQuery< gtsam::Pose3 > dyno::Accessor< MAP >::getObjectMotion (FrameId frame_id, ObjectId object_id) const pure virtual
Get an absolute object motion (_{k-1}^wH_k) from theta the requested time-step (k) and object (j).
Parameters
frame_id FrameId
object_id ObjectId
Returns
StateQuery<gtsam::Pose3>
Implemented in dyno::HybridAccessor, dyno::WorldMotionAccessor, and dyno::WorldPoseAccessor.
getObjectMotionReferenceFrame()
template<class MAP > StateQuery< Motion3ReferenceFrame > dyno::Accessor< MAP >::getObjectMotionReferenceFrame (FrameId frame_id, ObjectId object_id) const
Gets the absolute motion (_{k-1}^wH_k) from theta the requested time-step (k) and object (j) with the associated reference frame. Internally this uses getObjectMotion and constructs a Motion3ReferenceFrame using the global frame, k-1 and k. No checks are done on the underlying function call so it assumes that the virtual getObjectMotion function has been implemented correctly and returns a motion in the right representation.
Parameters
frame_id FrameId
object_id ObjectId
Returns
StateQuery<Motion3ReferenceFrame>
Definition at line 76 of file Accessor-impl.hpp.
{
  StateQuery<Motion3> motion_query = this->getObjectMotion(frame_id, object_id);
  if (motion_query) {
    return StateQuery<Motion3ReferenceFrame>(
        motion_query.key_,
        Motion3ReferenceFrame(motion_query.get(),
                              Motion3ReferenceFrame::Style::F2F,
                              ReferenceFrame::GLOBAL, frame_id - 1u, frame_id));
  } else {
    return StateQuery<Motion3ReferenceFrame>(motion_query.key_,
                                             motion_query.status_);
  }
}
References dyno::StateQuery< ValueType >::get(), dyno::GLOBAL, dyno::StateQuery< ValueType >::key_, and dyno::StateQuery< ValueType >::status_.
getObjectMotions() [1/2]
template<class MAP > ObjectMotionMap dyno::Accessor< MAP >::getObjectMotions virtual
Collects all object motions from 1 to K (with the first motion being from k-1 to k). (Non-pure) Virtual function that may be overwritten - default implementation uses the pure-virtual getObjectPoses to collect all motions.
Returns
ObjectMotionMap
Definition at line 136 of file Accessor-impl.hpp.
{
  ObjectMotionMap object_motions;
  for (FrameId frame_id : map()->getFrameIds()) {
    MotionEstimateMap per_object_motions = this->getObjectMotions(frame_id);
    for (const auto& [object_id, motion] : per_object_motions) {
      if (!object_motions.exists(object_id)) {
        object_motions.insert2(object_id, ObjectMotionMap::NestedBase{});
      }
      auto& per_frame_motion = object_motions.at(object_id);
      per_frame_motion.insert2(frame_id, motion);
    }
  }
  return object_motions;
}
References dyno::GenericObjectCentricMap< VALUE >::at(), dyno::GenericObjectCentricMap< VALUE >::exists(), and dyno::GenericObjectCentricMap< VALUE >::insert2().
getObjectMotions() [2/2]
template<class MAP > MotionEstimateMap dyno::Accessor< MAP >::getObjectMotions (FrameId frame_id) const
Collects all object motions from some time-step (k-1) to k. This is equivalent to \mathcal{H}_k. Uses the pure-virtual getObjectMotion function to collect all object motions.
Parameters
frame_id FrameId
Returns
MotionEstimateMap
Definition at line 55 of file Accessor-impl.hpp.
{
  MotionEstimateMap motion_estimates;
  const auto frame_node = map()->getFrame(frame_id);
  if (!frame_node) {
    return motion_estimates;
  }
  const auto object_seen =
      frame_node->objects_seen.template collectIds<ObjectId>();
  for (ObjectId object_id : object_seen) {
    StateQuery<Motion3ReferenceFrame> motion_query =
        this->getObjectMotionReferenceFrame(frame_id, object_id);
    if (motion_query) {
      motion_estimates.insert2(object_id, motion_query.get());
    }
  }
  return motion_estimates;
}
getObjectPose()
template<class MAP > virtual StateQuery< gtsam::Pose3 > dyno::Accessor< MAP >::getObjectPose (FrameId frame_id, ObjectId object_id) const pure virtual
Get the pose (^wL_k) of an object (j) at time-step (k).
Parameters
frame_id FrameId
object_id ObjectId
Returns
StateQuery<gtsam::Pose3>
Implemented in dyno::HybridAccessor, dyno::WorldMotionAccessor, and dyno::WorldPoseAccessor.
getObjectPosePair()
template<class MAP > EstimateMap< ObjectId, std::pair< Motion3, gtsam::Pose3 > > dyno::Accessor< MAP >::getObjectPosePair (FrameId frame_id) const
Gets an estimate map of objects with their motion and and CURRENT pose. This will find motions and poses (using the internal API) and return a motion from k-1 to k and the associated pose at k.
Parameters
frame_id
Returns
EstimateMap<ObjectId, std::pair<Motion3, gtsam::Pose3>>
getObjectPoses() [1/2]
template<class MAP > ObjectPoseMap dyno::Accessor< MAP >::getObjectPoses virtual
Collects all object poses for frame 0 to K. (Non-pure)Virtual function that may be overwritten - default implementation uses the pure-virtual getObjectPoses to collect all poses.
Returns
ObjectPoseMap
Reimplemented in dyno::WorldMotionAccessor.
Definition at line 116 of file Accessor-impl.hpp.
{
  ObjectPoseMap object_poses;
  for (FrameId frame_id : map()->getFrameIds()) {
    EstimateMap<ObjectId, gtsam::Pose3> per_object_pose =
        this->getObjectPoses(frame_id);
    for (const auto& [object_id, pose] : per_object_pose) {
      if (!object_poses.exists(object_id)) {
        object_poses.insert2(object_id,
                             gtsam::FastMap<FrameId, gtsam::Pose3>{});
      }
      auto& per_frame_pose = object_poses.at(object_id);
      per_frame_pose.insert2(frame_id, pose);
    }
  }
  return object_poses;
}
References dyno::GenericObjectCentricMap< VALUE >::exists().
getObjectPoses() [2/2]
template<class MAP > EstimateMap< ObjectId, gtsam::Pose3 > dyno::Accessor< MAP >::getObjectPoses (FrameId frame_id) const virtual
Collects all object poses at some time-step (k). This is equivalent to \mathcal{L}_k. Is a (non-pure) virtual function so may be overwritten - default implementation uses the pure-virtual getObjectPose function to collect all object poses.
Parameters
frame_id FrameId frame_id) const;
Returns
EstimateMap<ObjectId, gtsam::Pose3>
Reimplemented in dyno::WorldMotionAccessor.
Definition at line 92 of file Accessor-impl.hpp.
{
  EstimateMap<ObjectId, gtsam::Pose3> pose_estimates;
  const auto frame_node = map()->getFrame(frame_id);
  if (!frame_node) {
    return pose_estimates;
  }
  const auto object_seen =
      frame_node->objects_seen.template collectIds<ObjectId>();
  for (ObjectId object_id : object_seen) {
    StateQuery<gtsam::Pose3> object_pose =
        this->getObjectPose(frame_id, object_id);
    if (object_pose) {
      pose_estimates.insert2(
          object_id, ReferenceFrameValue<gtsam::Pose3>(object_pose.get(),
                                                       ReferenceFrame::GLOBAL));
    }
  }
  return pose_estimates;
}
getObjectPrevPosePair()
template<class MAP > EstimateMap< ObjectId, std::pair< Motion3, gtsam::Pose3 > > dyno::Accessor< MAP >::getObjectPrevPosePair (FrameId frame_id) const
Gets an estimate map of objects with their motion and and PREVIOUS pose. This will find motions and poses (using the internal API) and return a motion from k-1 to k and the associated pose at k-1.
Parameters
frame_id FrameId
Returns
EstimateMap<ObjectId, std::pair<Motion3, gtsam::Pose3>>
getRequestedObjectPosePair()
template<class MAP > EstimateMap< ObjectId, std::pair< Motion3, gtsam::Pose3 > > dyno::Accessor< MAP >::getRequestedObjectPosePair (FrameId motion_frame_id, FrameId pose_frame_id) const private
Compute all pairs of object motions and poses at the requested time-steps. As usual, motion_frame_id is treated as k, and therefore motions from motion_frame_id-1 to motion_frame_id will be retrieved.
Parameters
motion_frame_id FrameId
pose_frame_id FrameId
Returns
EstimateMap<ObjectId, std::pair<Motion3, gtsam::Pose3>>
Definition at line 359 of file Accessor-impl.hpp.
{
  const MotionEstimateMap motions_k = this->getObjectMotions(motion_frame_id);
  const EstimateMap<ObjectId, gtsam::Pose3> poses_k =
      this->getObjectPoses(pose_frame_id);
  EstimateMap<ObjectId, std::pair<Motion3, gtsam::Pose3>> result;
  // collect common objects
  for (const auto& [object_id, _] : motions_k) {
    if (poses_k.exists(object_id)) {
      auto motion_reference_values = motions_k.at(object_id);
      auto pose_reference_values = poses_k.at(object_id);
      CHECK_EQ(motion_reference_values.frame_, pose_reference_values.frame_);
      ReferenceFrameValue<std::pair<Motion3, gtsam::Pose3>> estimate(
          std::make_pair(motion_reference_values.estimate_,
                         pose_reference_values.estimate_),
          motion_reference_values.frame_);
      result.insert2(object_id, estimate);
    }
  }
  return result;
}
getSensorPose()
template<class MAP > virtual StateQuery< gtsam::Pose3 > dyno::Accessor< MAP >::getSensorPose (FrameId frame_id) const pure virtual
Get the sensor pose (^wX_k) from theta at the requested time-step.
Parameters
frame_id FrameId
Returns
StateQuery<gtsam::Pose3>
Implemented in dyno::HybridAccessor, and dyno::WorldPoseAccessor.
getStaticLandmark()
template<class MAP > StateQuery< gtsam::Point3 > dyno::Accessor< MAP >::getStaticLandmark (TrackletId tracklet_id) const virtual
Get a static landmark (^wm) with tracklet id (i).
Parameters
tracklet_id TrackletId
Returns
StateQuery<gtsam::Point3>
Definition at line 48 of file Accessor-impl.hpp.
{
  const auto lmk = CHECK_NOTNULL(map()->getLandmark(tracklet_id));
  return this->query<gtsam::Point3>(lmk->makeStaticKey());
}
getStaticLandmarkEstimates()
template<class MAP > StatusLandmarkVector dyno::Accessor< MAP >::getStaticLandmarkEstimates (FrameId frame_id) const
Get all static landmarks at time-step k.
Parameters
frame_id FrameId
Returns
StatusLandmarkVector
Definition at line 202 of file Accessor-impl.hpp.
{
  // dont go over the frames as this contains references to the landmarks
  // multiple times
  // e.g. the ones seen in that frame
  StatusLandmarkVector estimates;
  const auto frame_node = map()->getFrame(frame_id);
  CHECK_NOTNULL(frame_node);
  for (const auto& landmark_node : frame_node->static_landmarks) {
    if (landmark_node->isStatic()) {
      StateQuery<gtsam::Point3> lmk_query =
          getStaticLandmark(landmark_node->tracklet_id);
      if (lmk_query) {
        estimates.push_back(LandmarkStatus::StaticInGlobal(
            Point3Measurement(lmk_query.get()),  // estimate
            LandmarkStatus::MeaninglessFrame,
            landmark_node->getId()  // tracklet id
            )                       // status
        );
      }
    }
  }
  return estimates;
}
hasObjectMotionEstimate() [1/2]
template<class MAP > bool dyno::Accessor< MAP >::hasObjectMotionEstimate (FrameId frame_id, ObjectId object_id, Motion3 & motion) const
Check if there exists an estimate for object motion at time-step (k) for object id (j). If result is true, motion reference value is set to the motion.
Parameters
frame_id FrameId
object_id ObjectId
motion Motion3&
Returns
true
false
Definition at line 279 of file Accessor-impl.hpp.
{
  return hasObjectMotionEstimate(frame_id, object_id, &motion);
}
hasObjectMotionEstimate() [2/2]
template<class MAP > bool dyno::Accessor< MAP >::hasObjectMotionEstimate (FrameId frame_id, ObjectId object_id, Motion3 * motion = nullptr) const
Check if there exists an estimate for object motion at time-step (k) for object id (j). If result is true and a motion is provided, return true and set the motion.
Parameters
frame_id FrameId
object_id ObjectId
motion Motion3*. Default value is nullptr. If provided (ie non-null) and motion exists, value is set.
Returns
true
false
Definition at line 263 of file Accessor-impl.hpp.
{
  const auto frame_node = map()->getFrame(frame_id);
  StateQuery<Motion3> motion_query = this->getObjectMotion(frame_id, object_id);
  if (motion_query) {
    if (motion) {
      *motion = motion_query.get();
    }
    return true;
  }
  return false;
}
References dyno::StateQuery< ValueType >::get().
hasObjectPoseEstimate() [1/2]
template<class MAP > bool dyno::Accessor< MAP >::hasObjectPoseEstimate (FrameId frame_id, ObjectId object_id, gtsam::Pose3 & pose) const
Check if there exists an estimate for object pose at time-step (k) for object id (j). If result is true, pose reference value is set to the pose.
Parameters
frame_id FrameId
object_id ObjectId
pose gtsam::Pose3&
Returns
true
false
Definition at line 302 of file Accessor-impl.hpp.
{
  return hasObjectPoseEstimate(frame_id, object_id, &pose);
}
hasObjectPoseEstimate() [2/2]
template<class MAP > bool dyno::Accessor< MAP >::hasObjectPoseEstimate (FrameId frame_id, ObjectId object_id, gtsam::Pose3 * pose = nullptr) const
Check if there exists an estimate for object pose at time-step (k) for object id (j). If result is true and a pose is provided, return true and set the pose.
Parameters
frame_id FrameId
object_id ObjectId
pose gtsam::Pose3* Default value is nullptr. If provided (ie non-null) and pose exists, value is set.
Returns
true
false
Definition at line 286 of file Accessor-impl.hpp.
{
  const auto frame_node = map()->getFrame(frame_id);
  StateQuery<gtsam::Pose3> pose_query =
      this->getObjectPose(frame_id, object_id);
  if (pose_query) {
    if (pose) {
      *pose = pose_query.get();
    }
    return true;
  }
  return false;
}
hooks()
template<class MAP > const FormulationHooks & dyno::Accessor< MAP >::hooks () const inline protected
Definition at line 344 of file Accessor.hpp.
{
    return *CHECK_NOTNULL(shared_data_.hooks);
  }
References dyno::SharedFormulationData::hooks, and dyno::Accessor< MAP >::shared_data_.
map()
template<class MAP > auto dyno::Accessor< MAP >::map () const inline protected
Definition at line 339 of file Accessor.hpp.
{ return map_; }
References dyno::Accessor< MAP >::map_.
query()
template<class MAP > template<typename ValueType > StateQuery< ValueType > dyno::Accessor< MAP >::query (gtsam::Key key) const
Access a key in the current theta.
Template Parameters
ValueType
Parameters
key gtsam::Key
Returns
StateQuery<ValueType>
Definition at line 393 of file Accessor-impl.hpp.
{
  const gtsam::Values* theta = shared_data_.values;
  CHECK_NOTNULL(theta);
  if (theta->exists(key)) {
    return StateQuery<ValueType>(key, theta->at<ValueType>(key));
  } else {
    return StateQuery<ValueType>::NotInMap(key);
  }
}
References dyno::StateQuery< ValueType >::NotInMap().
values()
template<class MAP > const gtsam::Values & dyno::Accessor< MAP >::values () const inline protected
Definition at line 341 of file Accessor.hpp.
{
    return *CHECK_NOTNULL(shared_data_.values);
  }
References dyno::Accessor< MAP >::shared_data_, and dyno::SharedFormulationData::values.
Member Data Documentation
map_
template<class MAP > Map::Ptr dyno::Accessor< MAP >::map_ private
Definition at line 367 of file Accessor.hpp.
Referenced by dyno::Accessor< MAP >::map().
shared_data_
template<class MAP > const SharedFormulationData dyno::Accessor< MAP >::shared_data_ private
Definition at line 366 of file Accessor.hpp.
Referenced by dyno::Accessor< MAP >::hooks(), and dyno::Accessor< MAP >::values().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/backend/Accessor.hpp
dynosam/include/dynosam/backend/Accessor-impl.hpp