DynoSAM: dyno::CsvWriter Class Reference
dyno::CsvWriter Class Reference
#include <CsvParser.hpp>
Public Member Functions
CsvWriter (const CsvHeader &header, const std::string &seperator=",")
~CsvWriter ()
CsvWriter & add (const char *str)
CsvWriter & add (char *str)
CsvWriter & add (const std::string &str)
template<typename T >
CsvWriter & add (const T &str)
template<typename T >
CsvWriter & operator<< (const T &t)
void operator+= (CsvWriter &csv)
std::string toString () const
CsvWriter & newRow ()
bool write (const std::string &filename) const
bool write (const std::string &filename, bool append) const
bool write (std::ostream &stream) const
void resetContent ()
Protected Attributes
const CsvHeader header_
const size_t column_number_
const std::string seperator_
size_t value_count_
std::stringstream ss_
Friends
std::ostream & operator<< (std::ostream &os, const CsvWriter &csv)
Detailed Description
Definition at line 266 of file CsvParser.hpp.
Constructor & Destructor Documentation
CsvWriter()
dyno::CsvWriter::CsvWriter (const CsvHeader & header, const std::string & seperator = ",")
Definition at line 85 of file CsvParser.cc.
    : header_(header),
      column_number_(header.size()),
      seperator_(seperator),
      value_count_(0),
      ss_() {
  checkAndThrow<InvalidCsvHeaderException>(
      (column_number_ > 0u), "CsvHeader cannot be empty! (size of 0)");
  ss_.precision(15);
}
References column_number_, and ss_.
~CsvWriter()
dyno::CsvWriter::~CsvWriter ()
Definition at line 96 of file CsvParser.cc.
{ resetContent(); }
References resetContent().
Member Function Documentation
add() [1/4]
CsvWriter & dyno::CsvWriter::add (char * str)
Definition at line 102 of file CsvParser.cc.
{ return this->add(std::string(str)); }
References add().
add() [2/4]
CsvWriter & dyno::CsvWriter::add (const char * str)
Definition at line 98 of file CsvParser.cc.
{
  return this->add(std::string(str));
}
References add().
Referenced by add(), and operator<<().
add() [3/4]
CsvWriter & dyno::CsvWriter::add (const std::string & str)
Definition at line 104 of file CsvParser.cc.
{
  std::string str_cpy = str;
  // if " character was found, escape it
  size_t position = str_cpy.find("\"", 0);
  bool foundQuotationMarks = position != std::string::npos;
  while (position != std::string::npos) {
    str_cpy.insert(position, "\"");
    position = str_cpy.find("\"", position + 2);
  }
  if (foundQuotationMarks) {
    str_cpy = "\"" + str_cpy + "\"";
  } else if (str_cpy.find(this->seperator_) != std::string::npos) {
    // if seperator_ was found and string was not escapted before, surround
    // string with "
    str_cpy = "\"" + str_cpy + "\"";
  }
  return this->add<std::string>(str_cpy);
}
add() [4/4]
template<typename T > CsvWriter & dyno::CsvWriter::add (const T & str) inline
Definition at line 278 of file CsvParser.hpp.
{
    // if autoNewRow is enabled, check if we need a line break
    if (this->value_count_ == this->column_number_) {
      this->newRow();
    }
    if (value_count_ > 0) this->ss_ << this->seperator_;
    this->ss_ << str;
    this->value_count_++;
    return *this;
  }
References column_number_, newRow(), seperator_, ss_, and value_count_.
newRow()
CsvWriter & dyno::CsvWriter::newRow ()
Definition at line 123 of file CsvParser.cc.
{
  ss_ << std::endl;
  value_count_ = 0;
  return *this;
}
References ss_, and value_count_.
Referenced by add().
operator+=()
void dyno::CsvWriter::operator+= (CsvWriter & csv) inline
Definition at line 296 of file CsvParser.hpp.
{ this->ss_ << std::endl << csv; }
References ss_.
operator<<()
template<typename T > CsvWriter & dyno::CsvWriter::operator<< (const T & t) inline
Definition at line 292 of file CsvParser.hpp.
{
    return this->add(t);
  }
References add().
resetContent()
void dyno::CsvWriter::resetContent ()
Definition at line 171 of file CsvParser.cc.
{
  const static std::stringstream initial;
  ss_.str(std::string());
  ss_.clear();
  ss_.copyfmt(initial);
}
References ss_.
Referenced by ~CsvWriter().
toString()
std::string dyno::CsvWriter::toString () const inline
Definition at line 298 of file CsvParser.hpp.
{ return ss_.str(); }
References ss_.
Referenced by write().
write() [1/3]
bool dyno::CsvWriter::write (const std::string & filename) const
Definition at line 129 of file CsvParser.cc.
{
  return write(filename, false);
}
References write().
Referenced by write(), dyno::utils::Statistics::WriteAllSamplesToCsvFile(), dyno::OfstreamWrapper::WriteOutCsvWriter(), dyno::utils::Statistics::WritePerModuleSummariesToCsvFile(), and dyno::utils::Statistics::WriteSummaryToCsvFile().
write() [2/3]
bool dyno::CsvWriter::write (const std::string & filename, bool append) const
Definition at line 133 of file CsvParser.cc.
{
  std::ofstream file;
  bool appendNewLine = false;
  if (append) {
    // check if last char of the file is newline
    std::ifstream fin;
    fin.open(filename);
    if (fin.is_open()) {
      fin.seekg(-1, std::ios_base::end);  // go to end of file
      int lastChar = fin.peek();
      if (lastChar != -1 &&
          lastChar !=
              '\n')  // if file is not empry and last char is not new line char
        appendNewLine = true;
    }
    file.open(filename.c_str(), std::ios::out | std::ios::app);
  } else {
    file.open(filename.c_str(), std::ios::out | std::ios::trunc);
  }
  if (!file.is_open()) return false;
  if (append && appendNewLine) file << std::endl;
  return write(file);
}
References write().
write() [3/3]
bool dyno::CsvWriter::write (std::ostream & stream) const
Definition at line 158 of file CsvParser.cc.
{
  if (!stream) {
    LOG(ERROR) << "Failed to write with CsVWriter as stream was not good!";
    return false;
  }
  stream << header_.toString(seperator_);
  stream << std::endl;
  stream.precision(15);
  stream << toString();
  return stream.good();
}
References header_, seperator_, toString(), and dyno::CsvHeader::toString().
Friends And Related Function Documentation
operator<<
std::ostream & operator<< (std::ostream & os, const CsvWriter & csv) friend
Definition at line 300 of file CsvParser.hpp.
{
    return os << csv.toString();
  }
Member Data Documentation
column_number_
const size_t dyno::CsvWriter::column_number_ protected
Definition at line 313 of file CsvParser.hpp.
Referenced by add(), and CsvWriter().
header_
const CsvHeader dyno::CsvWriter::header_ protected
Definition at line 312 of file CsvParser.hpp.
Referenced by write().
seperator_
const std::string dyno::CsvWriter::seperator_ protected
Definition at line 314 of file CsvParser.hpp.
Referenced by add(), and write().
ss_
std::stringstream dyno::CsvWriter::ss_ protected
Definition at line 316 of file CsvParser.hpp.
Referenced by add(), CsvWriter(), newRow(), operator+=(), resetContent(), and toString().
value_count_
size_t dyno::CsvWriter::value_count_ protected
Definition at line 315 of file CsvParser.hpp.
Referenced by add(), and newRow().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/utils/CsvParser.hpp
dynosam/src/utils/CsvParser.cc