DynoSAM: dyno::StereoMatcher Class Reference
dyno::StereoMatcher Class Reference
#include <StereoMatcher.hpp>
Public Member Functions
StereoMatcher (StereoCamera::Ptr stereo_camera, const StereoMatchingParams &stereo_params=StereoMatchingParams(), const DenseStereoParams &dense_stereo_params=DenseStereoParams())
virtual ~StereoMatcher ()=default
void denseStereoReconstruction (const cv::Mat &left_img, const cv::Mat &right_img, cv::Mat &depth_image) const
Dense stereo reconstruction from two (distored, non-rectified) images and produces a dense depth map.
Protected Member Functions
void disparityRectifiedReconstruction (const cv::Mat &rectified_left_img, const cv::Mat &rectified_right_img, cv::Mat &disparity_image, cv::Mat *disparity_viz=nullptr) const
Dense stereo reconstruction from two (undistored, rectified) images and produces a disparity map.
Protected Attributes
StereoCamera::ConstPtr stereo_camera_
Stereo camera shared that might be shared across modules.
const StereoMatchingParams stereo_matching_params_
Parameters for sparse stereo matching.
const DenseStereoParams dense_stereo_params_
Parameters for dense stereo matching.
cv::Ptr< cv::StereoMatcher > cv_stereo_matcher_
Stereo matcher. Maybe unused.
Static Private Member Functions
static cv::Ptr< cv::StereoMatcher > constructStereoMatcher (StereoCamera::ConstPtr stereo_camera, const StereoMatchingParams &stereo_param, const DenseStereoParams &dense_stereo_params)
Detailed Description
Definition at line 37 of file StereoMatcher.hpp.
Constructor & Destructor Documentation
StereoMatcher()
dyno::StereoMatcher::StereoMatcher (StereoCamera::Ptr stereo_camera, const StereoMatchingParams & stereo_params = StereoMatchingParams(), const DenseStereoParams & dense_stereo_params = DenseStereoParams())
Definition at line 30 of file StereoMatcher.cc.
    : stereo_camera_(stereo_camera),
      stereo_matching_params_(stereo_param),
      dense_stereo_params_(dense_stereo_params)
{
    CHECK_NOTNULL(stereo_camera);
    cv_stereo_matcher_ = constructStereoMatcher(
        stereo_camera_,
        stereo_matching_params_,
        dense_stereo_params_
    );
    CHECK_NOTNULL(cv_stereo_matcher_);
}
References constructStereoMatcher(), cv_stereo_matcher_, dense_stereo_params_, stereo_camera_, and stereo_matching_params_.
~StereoMatcher()
virtual dyno::StereoMatcher::~StereoMatcher () virtual default
Member Function Documentation
constructStereoMatcher()
cv::Ptr< cv::StereoMatcher > dyno::StereoMatcher::constructStereoMatcher (StereoCamera::ConstPtr stereo_camera, const StereoMatchingParams & stereo_param, const DenseStereoParams & dense_stereo_params) static private
Definition at line 125 of file StereoMatcher.cc.
{
    // Setup stereo matcher
    cv::Ptr<cv::StereoMatcher> cv_stereo_matcher;
    if (dense_stereo_params.use_sgbm_) {
        int mode;
        if (dense_stereo_params.use_mode_HH_) {
            LOG(INFO) << "Using mode = cv::StereoSGBM::MODE_HH for dense stereo reconstruction";
            mode = cv::StereoSGBM::MODE_HH;
        } else {
            LOG(INFO) << "Using mode = cv::StereoSGBM::MODE_SGBM for dense stereo reconstruction";
            mode = cv::StereoSGBM::MODE_SGBM;
        }
        cv_stereo_matcher =
            cv::StereoSGBM::create(dense_stereo_params.min_disparity_,
                                dense_stereo_params.num_disparities_,
                                dense_stereo_params.sad_window_size_,
                                dense_stereo_params.p1_,
                                dense_stereo_params.p2_,
                                dense_stereo_params.disp_12_max_diff_,
                                dense_stereo_params.pre_filter_cap_,
                                dense_stereo_params.uniqueness_ratio_,
                                dense_stereo_params.speckle_window_size_,
                                dense_stereo_params.speckle_range_,
                                mode);
    } else {
        LOG(INFO) << "Using StereoBM for dense stereo reconstruction";
        cv::Ptr<cv::StereoBM> sbm =
            cv::StereoBM::create(dense_stereo_params.num_disparities_,
                                dense_stereo_params.sad_window_size_);
        sbm->setPreFilterType(dense_stereo_params.pre_filter_type_);
        sbm->setPreFilterSize(dense_stereo_params.pre_filter_size_);
        sbm->setPreFilterCap(dense_stereo_params.pre_filter_cap_);
        sbm->setMinDisparity(dense_stereo_params.min_disparity_);
        sbm->setTextureThreshold(dense_stereo_params.texture_threshold_);
        sbm->setUniquenessRatio(dense_stereo_params.uniqueness_ratio_);
        sbm->setSpeckleRange(dense_stereo_params.speckle_range_);
        sbm->setSpeckleWindowSize(dense_stereo_params.speckle_window_size_);
        const cv::Rect& roi1 = stereo_camera->getROI1();
        const cv::Rect& roi2 = stereo_camera->getROI2();
        if (!roi1.empty() && !roi2.empty()) {
            sbm->setROI1(roi1);
            sbm->setROI2(roi2);
        } else {
            LOG(WARNING) << "ROIs are empty.";
        }
        cv_stereo_matcher = sbm;
    }
    CHECK_NOTNULL(cv_stereo_matcher);
    return cv_stereo_matcher;
}
References dyno::DenseStereoParams::disp_12_max_diff_, dyno::DenseStereoParams::min_disparity_, dyno::DenseStereoParams::num_disparities_, dyno::DenseStereoParams::p1_, dyno::DenseStereoParams::p2_, dyno::DenseStereoParams::pre_filter_cap_, dyno::DenseStereoParams::pre_filter_size_, dyno::DenseStereoParams::pre_filter_type_, dyno::DenseStereoParams::sad_window_size_, dyno::DenseStereoParams::speckle_range_, dyno::DenseStereoParams::speckle_window_size_, dyno::DenseStereoParams::texture_threshold_, dyno::DenseStereoParams::uniqueness_ratio_, dyno::DenseStereoParams::use_mode_HH_, and dyno::DenseStereoParams::use_sgbm_.
Referenced by StereoMatcher().
denseStereoReconstruction()
void dyno::StereoMatcher::denseStereoReconstruction (const cv::Mat & left_img, const cv::Mat & right_img, cv::Mat & depth_image) const
Dense stereo reconstruction from two (distored, non-rectified) images and produces a dense depth map.
The left/right images must match the specifics from the L/R cameras as part of the input stereo camera and the depth is is non-inverted and is in meters. The depth mat uses CV_64F (double) data-type.
Parameters
left_img const cv::Mat&
right_img const cv::Mat&
depth_image cv::Mat&
Definition at line 49 of file StereoMatcher.cc.
{
    CHECK_EQ(right_img.cols, left_img.cols);
    CHECK_EQ(right_img.rows, left_img.rows);
    CHECK_EQ(right_img.type(), left_img.type());
    cv::Mat left_rectified, right_rectified;
    stereo_camera_->undistortRectifyImages(left_rectified, right_rectified, left_img, right_img);
    cv::Mat disparity_img;
    disparityRectifiedReconstruction(left_rectified, right_rectified, disparity_img);
    constexpr auto depth_type = ImageType::Depth::OpenCVType;
    depth_image = cv::Mat::zeros(disparity_img.size(), depth_type);
    // Check
    // https://github.com/opencv/opencv/blob/master/samples/cpp/stereo_match.cpp
    // only if output is CV_16S
    cv::Mat disparity_float;
    disparity_img.convertTo(disparity_float, CV_32F, 1.0f / 16.0f);
    // disp_img.convertTo(floatDisp, CV_32F, 1.0f / 16.0f);
    disparity_img = disparity_float;
    const auto baseline = stereo_camera_->getBaseline();
    const auto fx = stereo_camera_->getStereoCameraCalibration().fx();
    // Get depth from disparity
    for (int i = 0u; i < disparity_img.rows; i++) {
        // Loop over rows
        const float* disp_ptr = disparity_img.ptr<float>(i);
        double* depth_ptr = depth_image.ptr<double>(i);
        for (int j = 0u; j < disparity_img.cols; j++) {
            // Loop over cols
            const double depth = (baseline * fx) / static_cast<double>(disp_ptr[j]);
            *(depth_ptr + j) = depth;
        }
    }
}
References disparityRectifiedReconstruction(), and stereo_camera_.
disparityRectifiedReconstruction()
void dyno::StereoMatcher::disparityRectifiedReconstruction (const cv::Mat & rectified_left_img, const cv::Mat & rectified_right_img, cv::Mat & disparity_image, cv::Mat * disparity_viz = nullptr) const protected
Dense stereo reconstruction from two (undistored, rectified) images and produces a disparity map.
This is the direct result computing the disparity from the cv_stereo_matcher_. The disparity_image is computed as 16SC1.
If a disparity_viz is provided (non-null), this will be set with a viz image from utils::getDisparityVis
Parameters
left_img const cv::Mat&
right_img const cv::Mat&
disparity_image cv::Mat&
disparity_viz cv::Mat*
Definition at line 94 of file StereoMatcher.cc.
{
    CHECK_EQ(rectified_right_img.cols, rectified_left_img.cols);
    CHECK_EQ(rectified_right_img.rows, rectified_left_img.rows);
    CHECK_EQ(rectified_right_img.type(), rectified_left_img.type());
    //input expects 8bit single channel
    cv::Mat rectified_left_mono = ImageType::RGBMono::toMono(rectified_left_img);
    cv::Mat rectified_right_mono = ImageType::RGBMono::toMono(rectified_right_img);
    CHECK_EQ(rectified_left_mono.channels(),  1);
    CHECK_EQ(rectified_right_mono.channels(), 1);
    // initially computed as 16SC1
    cv_stereo_matcher_->compute(
      rectified_left_mono, rectified_right_mono, disparity_image);
    CHECK_EQ(disparity_image.type(), CV_16S);
    if (dense_stereo_params_.median_blur_disparity_) {
        cv::medianBlur(disparity_image, disparity_image, 5);
    }
    if(disparity_viz) {
        utils::getDisparityVis(disparity_image, *disparity_viz);
    }
}
References cv_stereo_matcher_, dense_stereo_params_, dyno::utils::getDisparityVis(), dyno::DenseStereoParams::median_blur_disparity_, and dyno::ImageType::RGBMono::toMono().
Referenced by denseStereoReconstruction().
Member Data Documentation
cv_stereo_matcher_
cv::Ptr<cv::StereoMatcher> dyno::StereoMatcher::cv_stereo_matcher_ protected
Stereo matcher. Maybe unused.
Definition at line 104 of file StereoMatcher.hpp.
Referenced by disparityRectifiedReconstruction(), and StereoMatcher().
dense_stereo_params_
const DenseStereoParams dyno::StereoMatcher::dense_stereo_params_ protected
Parameters for dense stereo matching.
Definition at line 101 of file StereoMatcher.hpp.
Referenced by disparityRectifiedReconstruction(), and StereoMatcher().
stereo_camera_
StereoCamera::ConstPtr dyno::StereoMatcher::stereo_camera_ protected
Stereo camera shared that might be shared across modules.
Definition at line 95 of file StereoMatcher.hpp.
Referenced by denseStereoReconstruction(), and StereoMatcher().
stereo_matching_params_
const StereoMatchingParams dyno::StereoMatcher::stereo_matching_params_ protected
Parameters for sparse stereo matching.
Definition at line 98 of file StereoMatcher.hpp.
Referenced by StereoMatcher().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/frontend/vision/StereoMatcher.hpp
dynosam/src/frontend/vision/StereoMatcher.cc