DynoSAM: dyno::Map< MEASUREMENT > Class Template Reference
dyno::Map< MEASUREMENT > Class Template Reference
A container that holds all connected information about static and dynamic entities that is build from input measurements.
#include <Map.hpp>
Classes
struct Private
Public Types
using Measurement = MEASUREMENT
using This = Map< Measurement >
template<typename DERIVEDSTATUS >
using MeasurementStatusVector = GenericTrackedStatusVector< DERIVEDSTATUS, Measurement >
Alias to a GenericTrackedStatusVector using the templated Measurement type, specifying that StatusVector must contain the desired measurement type.
using ObjectNodeM = ObjectNode< Measurement >
Alias to an object node with typedefed measurement.
using FrameNodeM = FrameNode< Measurement >
Alias to an frame node with typedefed measurement.
using LandmarkNodeM = LandmarkNode< Measurement >
Alias to an landmark node with typedefed measurement.
Public Member Functions
Map (Private)
std::shared_ptr< This > getptr ()
template<typename DERIVEDSTATUS >
void updateObservations (const GenericTrackedStatusVector< DERIVEDSTATUS > &measurements)
Update the map structure given new measurements.
void updateSensorPoseMeasurement (FrameId frame_id, const Pose3Measurement &X)
Updates sensor pose for the given frame.
void updateObjectMotionMeasurements (FrameId frame_id, const MotionEstimateMap &motions)
Updates object motion measurements for the given frame. Does not make a new frame node if it does not exist and overwrites the existing motions if already set.
bool frameExists (FrameId frame_id) const
Check a frame exists at the requested frame id.
bool landmarkExists (TrackletId tracklet_id) const
Check a landmark exists with the requested tracklet id.
bool objectExists (ObjectId object_id) const
Check that an object exists with the requested object id.
ObjectNodeM::Ptr getObject (ObjectId object_id) const
Get the Object object. If the object does not exist, return nullptr.
FrameNodeM::Ptr getFrame (FrameId frame_id) const
Get the Frame object. If the frame does not exist, return nullptr.
LandmarkNodeM::Ptr getLandmark (TrackletId tracklet_id) const
Get the Landmark object. If the landmark does not exist, return nullptr.
const gtsam::FastMap< TrackletId, typename LandmarkNodeM::Ptr > & getLandmarks () const
Get the mapping of all tracklet id's to landmarks.
TrackletIds getStaticTrackletsByFrame (FrameId frame_id) const
Get all static tracklet's that were observed at the requested frame id.
bool hasInitialObjectMotion (FrameId frame_id, ObjectId object_id, Motion3ReferenceFrame *motion_frame=nullptr) const
bool hasInitialObjectMotion (FrameId frame_id, ObjectId object_id, Motion3 *motion) const
bool hasInitialSensorPose (FrameId frame_id, Pose3Measurement *X=nullptr) const
bool hasInitialSensorPose (FrameId frame_id, gtsam::Pose3 *X=nullptr) const
size_t numObjectsSeen () const
Get number of objects seen.
const FrameNodeM::Ptr lastFrame () const
Get the most recent frame object.
const FrameNodeM::Ptr firstFrame () const
Get the earliest (first) frame object.
FrameId lastFrameId () const
Get the most recent frame id.
FrameId firstFrameId () const
Get the earliest (first) frame id.
FrameId lastEstimateUpdate () const
bool getLandmarkObjectId (ObjectId &object_id, TrackletId tracklet_id) const
Get the (by output-argument) object id for some tracked point. Function returns false if the landmark does not exist.
ObjectIds getObjectIds () const
Get all object ids.
FrameIds getFrameIds () const
Get all frame numbers.
const auto getFrames () const
Static Public Member Functions
static std::shared_ptr< This > create ()
Private Member Functions
void addOrUpdateMapStructures (const Measurement &measurement, TrackletId tracklet_id, FrameId frame_id, ObjectId object_id, bool is_static)
Private Attributes
gtsam::FastMap< FrameId, typename FrameNodeM::Ptr > frames_
gtsam::FastMap< TrackletId, typename LandmarkNodeM::Ptr > landmarks_
gtsam::FastMap< ObjectId, typename ObjectNodeM::Ptr > objects_
FrameId last_estimate_update_ {0}
Detailed Description
template<typename MEASUREMENT = Keypoint>
class dyno::Map< MEASUREMENT >
A container that holds all connected information about static and dynamic entities that is build from input measurements.
Structured as a undirected graph, this map structure holds temporal, observation and measurement information about frames, objects and landmarks which are stored as nodes
From each node relevant information can be querired. No optimsiation information is held in the map, this is just used to hold the structure of information that can then be used to build a factor graph.
So that nodes can carry a pointer to the map, we structure the map using enable_shared_from_this (https://en.cppreference.com/w/cpp/memory/enable_shared_from_this), so that constructor is only usable by this class.
Template Parameters
MEASUREMENT measurement type made by the frontend.
Definition at line 67 of file Map.hpp.
Member Typedef Documentation
FrameNodeM
template<typename MEASUREMENT = Keypoint> using dyno::Map< MEASUREMENT >::FrameNodeM = FrameNode<Measurement>
Alias to an frame node with typedefed measurement.
Definition at line 85 of file Map.hpp.
LandmarkNodeM
template<typename MEASUREMENT = Keypoint> using dyno::Map< MEASUREMENT >::LandmarkNodeM = LandmarkNode<Measurement>
Alias to an landmark node with typedefed measurement.
Definition at line 87 of file Map.hpp.
Measurement
template<typename MEASUREMENT = Keypoint> using dyno::Map< MEASUREMENT >::Measurement = MEASUREMENT
Definition at line 71 of file Map.hpp.
MeasurementStatusVector
template<typename MEASUREMENT = Keypoint> template<typename DERIVEDSTATUS > using dyno::Map< MEASUREMENT >::MeasurementStatusVector = GenericTrackedStatusVector<DERIVEDSTATUS, Measurement>
Alias to a GenericTrackedStatusVector using the templated Measurement type, specifying that StatusVector must contain the desired measurement type.
Template Parameters
DERIVEDSTATUS
Definition at line 79 of file Map.hpp.
ObjectNodeM
template<typename MEASUREMENT = Keypoint> using dyno::Map< MEASUREMENT >::ObjectNodeM = ObjectNode<Measurement>
Alias to an object node with typedefed measurement.
Definition at line 83 of file Map.hpp.
This
template<typename MEASUREMENT = Keypoint> using dyno::Map< MEASUREMENT >::This = Map<Measurement>
Definition at line 72 of file Map.hpp.
Constructor & Destructor Documentation
Map()
template<typename MEASUREMENT = Keypoint> dyno::Map< MEASUREMENT >::Map (Private) inline
Definition at line 92 of file Map.hpp.
{}
Member Function Documentation
addOrUpdateMapStructures()
template<typename MEASUREMENT = Keypoint> void dyno::Map< MEASUREMENT >::addOrUpdateMapStructures (const Measurement & measurement, TrackletId tracklet_id, FrameId frame_id, ObjectId object_id, bool is_static) inline private
Definition at line 420 of file Map.hpp.
{
    typename LandmarkNodeM::Ptr landmark_node = nullptr;
    typename FrameNodeM::Ptr frame_node = nullptr;
    CHECK((is_static && object_id == background_label) ||
          (!is_static && object_id != background_label));
    if (!landmarkExists(tracklet_id)) {
      landmark_node = std::make_shared<LandmarkNodeM>(getptr());
      CHECK_NOTNULL(landmark_node);
      landmark_node->tracklet_id = tracklet_id;
      landmark_node->object_id = object_id;
      landmarks_.insert2(tracklet_id, landmark_node);
    }
    if (!frameExists(frame_id)) {
      frame_node = std::make_shared<FrameNodeM>(getptr());
      frame_node->frame_id = frame_id;
      frames_.insert2(frame_id, frame_node);
    }
    landmark_node = getLandmark(tracklet_id);
    frame_node = getFrame(frame_id);
    CHECK(landmark_node);
    CHECK(frame_node);
    CHECK_EQ(landmark_node->tracklet_id, tracklet_id);
    // this might fail of a tracklet get associated with a different object
    CHECK_EQ(landmark_node->object_id, object_id);
    CHECK_EQ(frame_node->frame_id, frame_id);
    landmark_node->add(frame_node, measurement);
    // add to frame
    if (is_static) {
      frame_node->static_landmarks.insert(landmark_node);
    } else {
      CHECK(object_id != background_label);
      typename ObjectNodeM::Ptr object_node = nullptr;
      if (!objectExists(object_id)) {
        object_node = std::make_shared<ObjectNodeM>(getptr());
        object_node->object_id = object_id;
        objects_.insert2(object_id, object_node);
      }
      object_node = getObject(object_id);
      CHECK(object_node);
      object_node->dynamic_landmarks.insert(landmark_node);
      frame_node->dynamic_landmarks.insert(landmark_node);
      frame_node->objects_seen.insert(object_node);
    }
  }
References dyno::background_label, dyno::Map< MEASUREMENT >::frameExists(), dyno::Map< MEASUREMENT >::frames_, dyno::Map< MEASUREMENT >::getFrame(), dyno::Map< MEASUREMENT >::getLandmark(), dyno::Map< MEASUREMENT >::getObject(), dyno::Map< MEASUREMENT >::getptr(), dyno::Map< MEASUREMENT >::landmarkExists(), dyno::Map< MEASUREMENT >::landmarks_, dyno::Map< MEASUREMENT >::objectExists(), and dyno::Map< MEASUREMENT >::objects_.
Referenced by dyno::Map< MEASUREMENT >::updateObservations().
create()
template<typename MEASUREMENT = Keypoint> static std::shared_ptr< This > dyno::Map< MEASUREMENT >::create () inline static
Definition at line 94 of file Map.hpp.
{
    return std::make_shared<This>(Private());
  }
firstFrame()
template<typename MEASUREMENT = Keypoint> const FrameNodeM::Ptr dyno::Map< MEASUREMENT >::firstFrame () const inline
Get the earliest (first) frame object.
Returns
const FrameNodeM::Ptr
Definition at line 351 of file Map.hpp.
{
    return frames_.cbegin()->second;
  }
References dyno::Map< MEASUREMENT >::frames_.
Referenced by dyno::Map< MEASUREMENT >::firstFrameId().
firstFrameId()
template<typename MEASUREMENT = Keypoint> FrameId dyno::Map< MEASUREMENT >::firstFrameId () const inline
Get the earliest (first) frame id.
Returns
FrameId
Definition at line 367 of file Map.hpp.
{ return this->firstFrame()->frame_id; }
References dyno::Map< MEASUREMENT >::firstFrame().
frameExists()
template<typename MEASUREMENT = Keypoint> bool dyno::Map< MEASUREMENT >::frameExists (FrameId frame_id) const inline
Check a frame exists at the requested frame id.
Parameters
frame_id FrameId
Returns
true
false
Definition at line 172 of file Map.hpp.
{
    return frames_.exists(frame_id);
  }
References dyno::Map< MEASUREMENT >::frames_.
Referenced by dyno::Map< MEASUREMENT >::addOrUpdateMapStructures(), and dyno::Map< MEASUREMENT >::getFrame().
getFrame()
template<typename MEASUREMENT = Keypoint> FrameNodeM::Ptr dyno::Map< MEASUREMENT >::getFrame (FrameId frame_id) const inline
Get the Frame object. If the frame does not exist, return nullptr.
Parameters
frame_id FrameId
Returns
FrameNodeM::Ptr
Definition at line 219 of file Map.hpp.
{
    if (frameExists(frame_id)) {
      return frames_.at(frame_id);
    }
    return nullptr;
  }
References dyno::Map< MEASUREMENT >::frameExists(), and dyno::Map< MEASUREMENT >::frames_.
Referenced by dyno::Map< MEASUREMENT >::addOrUpdateMapStructures(), dyno::Map< MEASUREMENT >::hasInitialObjectMotion(), dyno::Map< MEASUREMENT >::hasInitialSensorPose(), dyno::Map< MEASUREMENT >::updateObjectMotionMeasurements(), and dyno::Map< MEASUREMENT >::updateSensorPoseMeasurement().
getFrameIds()
template<typename MEASUREMENT = Keypoint> FrameIds dyno::Map< MEASUREMENT >::getFrameIds () const inline
Get all frame numbers.
Returns
FrameIds
Definition at line 409 of file Map.hpp.
{
    FrameIds frame_ids;
    for (const auto& [frame_id, _] : frames_) {
      frame_ids.push_back(frame_id);
    }
    return frame_ids;
  }
References dyno::Map< MEASUREMENT >::frames_.
getFrames()
template<typename MEASUREMENT = Keypoint> const auto dyno::Map< MEASUREMENT >::getFrames () const inline
Definition at line 417 of file Map.hpp.
{ return frames_; }
References dyno::Map< MEASUREMENT >::frames_.
getLandmark()
template<typename MEASUREMENT = Keypoint> LandmarkNodeM::Ptr dyno::Map< MEASUREMENT >::getLandmark (TrackletId tracklet_id) const inline
Get the Landmark object. If the landmark does not exist, return nullptr.
Parameters
tracklet_id TrackletId
Returns
LandmarkNodeM::Ptr
Definition at line 233 of file Map.hpp.
{
    if (landmarkExists(tracklet_id)) {
      return landmarks_.at(tracklet_id);
    }
    return nullptr;
  }
References dyno::Map< MEASUREMENT >::landmarkExists(), and dyno::Map< MEASUREMENT >::landmarks_.
Referenced by dyno::Map< MEASUREMENT >::addOrUpdateMapStructures(), and dyno::Map< MEASUREMENT >::getLandmarkObjectId().
getLandmarkObjectId()
template<typename MEASUREMENT = Keypoint> bool dyno::Map< MEASUREMENT >::getLandmarkObjectId (ObjectId & object_id, TrackletId tracklet_id) const inline
Get the (by output-argument) object id for some tracked point. Function returns false if the landmark does not exist.
Parameters
object_id ObjectId& (output-argument)
tracklet_id TrackletId
Returns
true
false
Definition at line 381 of file Map.hpp.
{
    const auto lmk = getLandmark(tracklet_id);
    if (!lmk) {
      return false;
    }
    object_id = lmk->getObjectId();
    return true;
  }
References dyno::Map< MEASUREMENT >::getLandmark().
getLandmarks()
template<typename MEASUREMENT = Keypoint> const gtsam::FastMap< TrackletId, typename LandmarkNodeM::Ptr > & dyno::Map< MEASUREMENT >::getLandmarks () const inline
Get the mapping of all tracklet id's to landmarks.
Returns
const gtsam::FastMap<TrackletId, typename LandmarkNodeM::Ptr>&
Definition at line 245 of file Map.hpp.
            {
    return landmarks_;
  }
References dyno::Map< MEASUREMENT >::landmarks_.
getObject()
template<typename MEASUREMENT = Keypoint> ObjectNodeM::Ptr dyno::Map< MEASUREMENT >::getObject (ObjectId object_id) const inline
Get the Object object. If the object does not exist, return nullptr.
Parameters
object_id ObjectId
Returns
ObjectNodeM::Ptr
Definition at line 205 of file Map.hpp.
{
    if (objectExists(object_id)) {
      return objects_.at(object_id);
    }
    return nullptr;
  }
References dyno::Map< MEASUREMENT >::objectExists(), and dyno::Map< MEASUREMENT >::objects_.
Referenced by dyno::Map< MEASUREMENT >::addOrUpdateMapStructures().
getObjectIds()
template<typename MEASUREMENT = Keypoint> ObjectIds dyno::Map< MEASUREMENT >::getObjectIds () const inline
Get all object ids.
Returns
ObjectIds
Definition at line 396 of file Map.hpp.
{
    ObjectIds object_ids;
    for (const auto& [object_id, _] : objects_) {
      object_ids.push_back(object_id);
    }
    return object_ids;
  }
References dyno::Map< MEASUREMENT >::objects_.
getptr()
template<typename MEASUREMENT = Keypoint> std::shared_ptr< This > dyno::Map< MEASUREMENT >::getptr () inline
Definition at line 98 of file Map.hpp.
{
    // dependant base so need to qualify name lookup with this
    return this->shared_from_this();
  }
Referenced by dyno::Map< MEASUREMENT >::addOrUpdateMapStructures(), and dyno::Map< MEASUREMENT >::updateSensorPoseMeasurement().
getStaticTrackletsByFrame()
template<typename MEASUREMENT = Keypoint> TrackletIds dyno::Map< MEASUREMENT >::getStaticTrackletsByFrame (FrameId frame_id) const inline
Get all static tracklet's that were observed at the requested frame id.
Parameters
frame_id FrameId
Returns
TrackletIds
Definition at line 257 of file Map.hpp.
{
    // if frame does not exist?
    TrackletIds tracklet_ids;
    auto frame_node = frames_.at(frame_id);
    for (const auto& landmark_node : frame_node->static_landmarks) {
      tracklet_ids.push_back(landmark_node->tracklet_id);
    }
    return tracklet_ids;
  }
References dyno::Map< MEASUREMENT >::frames_.
hasInitialObjectMotion() [1/2]
template<typename MEASUREMENT = Keypoint> bool dyno::Map< MEASUREMENT >::hasInitialObjectMotion (FrameId frame_id, ObjectId object_id, Motion3 * motion) const inline
Definition at line 294 of file Map.hpp.
{
    Motion3ReferenceFrame frame;
    if (hasInitialObjectMotion(frame_id, object_id, &frame)) {
      if (motion) *motion = frame;  // implicit cast
      return true;
    }
    return false;
  }
References dyno::Map< MEASUREMENT >::hasInitialObjectMotion().
hasInitialObjectMotion() [2/2]
template<typename MEASUREMENT = Keypoint> bool dyno::Map< MEASUREMENT >::hasInitialObjectMotion (FrameId frame_id, ObjectId object_id, Motion3ReferenceFrame * motion_frame = nullptr) const inline
Definition at line 268 of file Map.hpp.
{
    auto frame_node = this->getFrame(frame_id);
    if (!frame_node) {
      return false;
    }
    // motion map has not been set
    if (frame_node->motions) {
      const auto& motions = *frame_node->motions;
      // no motion for this object in map
      if (!motions.exists(object_id)) {
        return false;
      }
      if (motion_frame) {
        *motion_frame = motions.at(object_id);
      }
      return true;
    } else {
      return false;
    }
  }
References dyno::Map< MEASUREMENT >::getFrame().
Referenced by dyno::Map< MEASUREMENT >::hasInitialObjectMotion().
hasInitialSensorPose() [1/2]
template<typename MEASUREMENT = Keypoint> bool dyno::Map< MEASUREMENT >::hasInitialSensorPose (FrameId frame_id, gtsam::Pose3 * X = nullptr) const inline
Definition at line 321 of file Map.hpp.
{
    Pose3Measurement frame;
    if (hasInitialSensorPose(frame_id, &frame)) {
      if (X) *X = frame;  // implicit cast
      return true;
    }
    return false;
  }
References dyno::Map< MEASUREMENT >::hasInitialSensorPose().
hasInitialSensorPose() [2/2]
template<typename MEASUREMENT = Keypoint> bool dyno::Map< MEASUREMENT >::hasInitialSensorPose (FrameId frame_id, Pose3Measurement * X = nullptr) const inline
Definition at line 305 of file Map.hpp.
{
    auto frame_node = this->getFrame(frame_id);
    if (!frame_node) {
      return false;
    }
    if (frame_node->X_world) {
      const auto& pose = *frame_node->X_world;
      if (X) *X = pose;
      return true;
    } else {
      return false;
    }
  }
References dyno::Map< MEASUREMENT >::getFrame().
Referenced by dyno::Map< MEASUREMENT >::hasInitialSensorPose().
landmarkExists()
template<typename MEASUREMENT = Keypoint> bool dyno::Map< MEASUREMENT >::landmarkExists (TrackletId tracklet_id) const inline
Check a landmark exists with the requested tracklet id.
Parameters
tracklet_id TrackletId
Returns
true
false
Definition at line 183 of file Map.hpp.
{
    return landmarks_.exists(tracklet_id);
  }
References dyno::Map< MEASUREMENT >::landmarks_.
Referenced by dyno::Map< MEASUREMENT >::addOrUpdateMapStructures(), and dyno::Map< MEASUREMENT >::getLandmark().
lastEstimateUpdate()
template<typename MEASUREMENT = Keypoint> FrameId dyno::Map< MEASUREMENT >::lastEstimateUpdate () const inline
Definition at line 370 of file Map.hpp.
{ return last_estimate_update_; }
References dyno::Map< MEASUREMENT >::last_estimate_update_.
lastFrame()
template<typename MEASUREMENT = Keypoint> const FrameNodeM::Ptr dyno::Map< MEASUREMENT >::lastFrame () const inline
Get the most recent frame object.
Returns
const FrameNodeM::Ptr
Definition at line 342 of file Map.hpp.
{
    return frames_.crbegin()->second;
  }
References dyno::Map< MEASUREMENT >::frames_.
Referenced by dyno::Map< MEASUREMENT >::lastFrameId().
lastFrameId()
template<typename MEASUREMENT = Keypoint> FrameId dyno::Map< MEASUREMENT >::lastFrameId () const inline
Get the most recent frame id.
Returns
FrameId
Definition at line 360 of file Map.hpp.
{ return this->lastFrame()->frame_id; }
References dyno::Map< MEASUREMENT >::lastFrame().
numObjectsSeen()
template<typename MEASUREMENT = Keypoint> size_t dyno::Map< MEASUREMENT >::numObjectsSeen () const inline
Get number of objects seen.
Returns
size_t
Definition at line 335 of file Map.hpp.
{ return objects_.size(); }
References dyno::Map< MEASUREMENT >::objects_.
objectExists()
template<typename MEASUREMENT = Keypoint> bool dyno::Map< MEASUREMENT >::objectExists (ObjectId object_id) const inline
Check that an object exists with the requested object id.
Parameters
object_id ObjectId
Returns
true
false
Definition at line 194 of file Map.hpp.
{
    return objects_.exists(object_id);
  }
References dyno::Map< MEASUREMENT >::objects_.
Referenced by dyno::Map< MEASUREMENT >::addOrUpdateMapStructures(), and dyno::Map< MEASUREMENT >::getObject().
updateObjectMotionMeasurements()
template<typename MEASUREMENT = Keypoint> void dyno::Map< MEASUREMENT >::updateObjectMotionMeasurements (FrameId frame_id, const MotionEstimateMap< MEASUREMENT > & motions) inline
Updates object motion measurements for the given frame. Does not make a new frame node if it does not exist and overwrites the existing motions if already set.
Parameters
frame_id FrameId
motions const MotionEstimateMap&
Definition at line 158 of file Map.hpp.
{
    auto frame_node = this->getFrame(frame_id);
    CHECK_NOTNULL(frame_node);
    frame_node->motions = motions;
  }
References dyno::Map< MEASUREMENT >::getFrame().
updateObservations()
template<typename MEASUREMENT = Keypoint> template<typename DERIVEDSTATUS > void dyno::Map< MEASUREMENT >::updateObservations (const GenericTrackedStatusVector< DERIVEDSTATUS > & measurements) inline
Update the map structure given new measurements.
Template Parameters
DERIVEDSTATUS
Parameters
measurements const GenericTrackedStatusVector<DERIVEDSTATUS>&
Definition at line 110 of file Map.hpp.
{
    using DerivedMeasurement =
        typename GenericTrackedStatusVector<DERIVEDSTATUS>::Value;
    for (const DERIVEDSTATUS& status_measurement : measurements) {
      const TrackedValueStatus<DerivedMeasurement>& derived_status =
          static_cast<const TrackedValueStatus<DerivedMeasurement>&>(
              status_measurement);
      const TrackedValueStatus<MEASUREMENT>& status =
          derived_status.template asType<MEASUREMENT>();
      const MEASUREMENT& measurement = status_measurement.value();
      const TrackletId tracklet_id = status.trackletId();
      const FrameId frame_id = status.frameId();
      const ObjectId object_id = status.objectId();
      const bool is_static = status.isStatic();
      addOrUpdateMapStructures(measurement, tracklet_id, frame_id, object_id,
                               is_static);
    }
  }
References dyno::Map< MEASUREMENT >::addOrUpdateMapStructures(), dyno::TrackedValueStatus< VALUE >::frameId(), dyno::TrackedValueStatus< VALUE >::isStatic(), dyno::TrackedValueStatus< VALUE >::objectId(), and dyno::TrackedValueStatus< VALUE >::trackletId().
updateSensorPoseMeasurement()
template<typename MEASUREMENT = Keypoint> void dyno::Map< MEASUREMENT >::updateSensorPoseMeasurement (FrameId frame_id, const Pose3Measurement & X) inline
Updates sensor pose for the given frame.
Overwrites value if already exists. Makes a new frame node in the map the frame is new!
Parameters
frame_id FrameId
X const Pose3Measurement&
Definition at line 139 of file Map.hpp.
{
    auto frame_node = this->getFrame(frame_id);
    if (!frame_node) {
      frame_node = std::make_shared<FrameNodeM>(getptr());
      frame_node->frame_id = frame_id;
      frames_.insert2(frame_id, frame_node);
    }
    frame_node->X_world = X;
  }
References dyno::Map< MEASUREMENT >::frames_, dyno::Map< MEASUREMENT >::getFrame(), and dyno::Map< MEASUREMENT >::getptr().
Member Data Documentation
frames_
template<typename MEASUREMENT = Keypoint> gtsam::FastMap<FrameId, typename FrameNodeM::Ptr> dyno::Map< MEASUREMENT >::frames_ private
Definition at line 481 of file Map.hpp.
Referenced by dyno::Map< MEASUREMENT >::addOrUpdateMapStructures(), dyno::Map< MEASUREMENT >::firstFrame(), dyno::Map< MEASUREMENT >::frameExists(), dyno::Map< MEASUREMENT >::getFrame(), dyno::Map< MEASUREMENT >::getFrameIds(), dyno::Map< MEASUREMENT >::getFrames(), dyno::Map< MEASUREMENT >::getStaticTrackletsByFrame(), dyno::Map< MEASUREMENT >::lastFrame(), and dyno::Map< MEASUREMENT >::updateSensorPoseMeasurement().
landmarks_
template<typename MEASUREMENT = Keypoint> gtsam::FastMap<TrackletId, typename LandmarkNodeM::Ptr> dyno::Map< MEASUREMENT >::landmarks_ private
Definition at line 482 of file Map.hpp.
Referenced by dyno::Map< MEASUREMENT >::addOrUpdateMapStructures(), dyno::Map< MEASUREMENT >::getLandmark(), dyno::Map< MEASUREMENT >::getLandmarks(), and dyno::Map< MEASUREMENT >::landmarkExists().
last_estimate_update_
template<typename MEASUREMENT = Keypoint> FrameId dyno::Map< MEASUREMENT >::last_estimate_update_ {0} private
Definition at line 485 of file Map.hpp.
Referenced by dyno::Map< MEASUREMENT >::lastEstimateUpdate().
objects_
template<typename MEASUREMENT = Keypoint> gtsam::FastMap<ObjectId, typename ObjectNodeM::Ptr> dyno::Map< MEASUREMENT >::objects_ private
Definition at line 483 of file Map.hpp.
Referenced by dyno::Map< MEASUREMENT >::addOrUpdateMapStructures(), dyno::Map< MEASUREMENT >::getObject(), dyno::Map< MEASUREMENT >::getObjectIds(), dyno::Map< MEASUREMENT >::numObjectsSeen(), and dyno::Map< MEASUREMENT >::objectExists().
The documentation for this class was generated from the following file:
dynosam_opt/include/dynosam_opt/Map.hpp