DynoSAM: dyno::PipelineSpinner Class Reference
dyno::PipelineSpinner Class Reference
#include <PipelineSpinner.hpp>
Classes
struct AsynchronousSpinnerPair
struct SpinnerPair
struct SynchronousSpinnerPair
Public Member Functions
PipelineSpinner ()=default
virtual ~PipelineSpinner ()
void registerPipeline (PipelineBase::Ptr pipeline, bool parallel_run)
void launchAll ()
void spinOnceAll ()
Protected Member Functions
void shutdownAll ()
Private Member Functions
void appyAll (std::function< void(SpinnerPair::UniquePtr &)> apply)
Private Attributes
bool is_launched_ {false}
std::vector< std::string > ordering_
gtsam::FastMap< std::string, SpinnerPair::UniquePtr > pipelines_
Detailed Description
Definition at line 42 of file PipelineSpinner.hpp.
Constructor & Destructor Documentation
PipelineSpinner()
dyno::PipelineSpinner::PipelineSpinner () default
~PipelineSpinner()
dyno::PipelineSpinner::~PipelineSpinner () virtual
Definition at line 41 of file PipelineSpinner.cc.
{ shutdownAll(); }
References shutdownAll().
Member Function Documentation
appyAll()
void dyno::PipelineSpinner::appyAll (std::function< void(SpinnerPair::UniquePtr &)> apply) private
Definition at line 88 of file PipelineSpinner.cc.
{
  for (const std::string& name : ordering_) {
    SpinnerPair::UniquePtr& spinner_pair = pipelines_.at(name);
    apply(spinner_pair);
  }
}
References dyno::internal::apply(), ordering_, and pipelines_.
Referenced by launchAll(), shutdownAll(), and spinOnceAll().
launchAll()
void dyno::PipelineSpinner::launchAll ()
Definition at line 61 of file PipelineSpinner.cc.
{
  auto lambda = [](SpinnerPair::UniquePtr& spinner_pair) {
    spinner_pair->launch();
  };
  appyAll(lambda);
  is_launched_ = true;
}
References appyAll(), and is_launched_.
registerPipeline()
void dyno::PipelineSpinner::registerPipeline (PipelineBase::Ptr pipeline, bool parallel_run)
Definition at line 43 of file PipelineSpinner.cc.
{
  const std::string name = pipeline->getModuleName();
  checkAndThrow(!pipelines_.exists(name),
                "Cannot register pipeline with name " + name +
                    " as it has already been registered");
  if (parallel_run) {
    pipelines_.insert(
        {name, std::move(std::make_unique<AsynchronousSpinnerPair>(pipeline))});
  } else {
    pipelines_.insert(
        {name, std::move(std::make_unique<SynchronousSpinnerPair>(pipeline))});
  }
  ordering_.push_back(name);
}
References dyno::checkAndThrow(), ordering_, and pipelines_.
shutdownAll()
void dyno::PipelineSpinner::shutdownAll () protected
Definition at line 81 of file PipelineSpinner.cc.
{
  auto lambda = [](SpinnerPair::UniquePtr& spinner_pair) {
    spinner_pair->shutdown();
  };
  appyAll(lambda);
}
References appyAll().
Referenced by ~PipelineSpinner().
spinOnceAll()
void dyno::PipelineSpinner::spinOnceAll ()
Definition at line 69 of file PipelineSpinner.cc.
{
  if (!is_launched_) {
    LOG(WARNING)
        << "spinOnceAll called but the pipelines have not been launched yet!";
  }
  auto lambda = [](SpinnerPair::UniquePtr& spinner_pair) {
    spinner_pair->spinOnce();
  };
  appyAll(lambda);
}
References appyAll(), and is_launched_.
Member Data Documentation
is_launched_
bool dyno::PipelineSpinner::is_launched_ {false} private
Definition at line 86 of file PipelineSpinner.hpp.
Referenced by launchAll(), and spinOnceAll().
ordering_
std::vector<std::string> dyno::PipelineSpinner::ordering_ private
Definition at line 87 of file PipelineSpinner.hpp.
Referenced by appyAll(), and registerPipeline().
pipelines_
gtsam::FastMap<std::string, SpinnerPair::UniquePtr> dyno::PipelineSpinner::pipelines_ private
Enumeration order determines which order the pipelines will be spun in
Definition at line 90 of file PipelineSpinner.hpp.
Referenced by appyAll(), and registerPipeline().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/pipeline/PipelineSpinner.hpp
dynosam/src/pipeline/PipelineSpinner.cc