DynoSAM: dyno::FrontendInbuiltDisplayRos Class Reference
dyno::FrontendInbuiltDisplayRos Class Reference
#include <FrontendInbuiltDisplayRos.hpp>
Public Member Functions
FrontendInbuiltDisplayRos (const DisplayParams params, rclcpp::Node::SharedPtr node)
~FrontendInbuiltDisplayRos ()
void spinOnce (const FrontendOutputPacketBase::ConstPtr &frontend_output) override
Public Member Functions inherited from dyno::DisplayBase< INPUT >
DisplayBase ()
virtual ~DisplayBase ()
virtual void spinOnce (const InputConstPtr &input)=0
Private Member Functions
void processRGBDOutputpacket (const RGBDInstanceOutputPacket::ConstPtr &rgbd_frontend_output)
void publishOdometry (const gtsam::Pose3 &T_world_camera, Timestamp timestamp)
void publishDebugImage (const DebugImagery &debug_imagery)
void publishGroundTruthInfo (Timestamp timestamp, const GroundTruthInputPacket &gt_packet, const cv::Mat &rgb)
Private Member Functions inherited from dyno::InbuiltDisplayCommon
InbuiltDisplayCommon (const DisplayParams &params, rclcpp::Node::SharedPtr node)
virtual ~InbuiltDisplayCommon ()=default
virtual CloudPerObject publishPointCloud (PointCloud2Pub::SharedPtr pub, const StatusLandmarkVector &landmarks, const gtsam::Pose3 &T_world_camera)
virtual void publishOdometry (OdometryPub::SharedPtr pub, const gtsam::Pose3 &T_world_camera, Timestamp timestamp)
virtual void publishOdometryPath (PathPub::SharedPtr pub, const gtsam::Pose3Vector &poses, Timestamp latest_timestamp)
virtual void publishObjectPositions (MarkerArrayPub::SharedPtr pub, const ObjectPoseMap &object_positions, FrameId frame_id, Timestamp latest_timestamp, const std::string &prefix_marker_namespace, bool draw_labels=false, double scale=1.0)
virtual void publishObjectPaths (MarkerArrayPub::SharedPtr pub, const ObjectPoseMap &object_positions, FrameId frame_id, Timestamp latest_timestamp, const std::string &prefix_marker_namespace, const int min_poses=60)
virtual void publishObjectBoundingBox (MarkerArrayPub::SharedPtr aabb_pub, MarkerArrayPub::SharedPtr obb_pub, const CloudPerObject &cloud_per_object, Timestamp timestamp, const std::string &prefix_marker_namespace)
MarkerArray createCameraMarker (const gtsam::Pose3 &T_world_x, Timestamp timestamp, const std::string &ns, const cv::Scalar &colour, double marker_scale=1.0)
void publishCameraMarker (const gtsam::Pose3 &T_world_x, Timestamp timestamp, const std::string &ns, const cv::Scalar &colour, double marker_scale=1.0)
visualization_msgs::msg::Marker getDeletionMarker () const
Private Attributes
rclcpp::Publisher< sensor_msgs::msg::PointCloud2 >::SharedPtr static_tracked_points_pub_
rclcpp::Publisher< sensor_msgs::msg::PointCloud2 >::SharedPtr dynamic_tracked_points_pub_
rclcpp::Publisher< nav_msgs::msg::Odometry >::SharedPtr odometry_pub_
rclcpp::Publisher< nav_msgs::msg::Path >::SharedPtr odometry_path_pub_
nav_msgs::msg::Path odom_path_msg_
rclcpp::Publisher< visualization_msgs::msg::MarkerArray >::SharedPtr object_pose_path_pub_
std::map< ObjectId, gtsam::Pose3Vector > object_trajectories_
std::map< ObjectId, FrameId > object_trajectories_update_
rclcpp::Publisher< nav_msgs::msg::Path >::SharedPtr object_motion_pub_
rclcpp::Publisher< visualization_msgs::msg::MarkerArray >::SharedPtr object_pose_pub_
rclcpp::Publisher< visualization_msgs::msg::MarkerArray >::SharedPtr object_bbx_line_pub_
Propogated object poses using the motion estimate.
rclcpp::Publisher< visualization_msgs::msg::MarkerArray >::SharedPtr object_bbx_pub_
Draw object bounding boxes as line lists.
image_transport::Publisher tracking_image_pub_
Draw object bounding boxes as cubes.
rclcpp::Publisher< visualization_msgs::msg::MarkerArray >::SharedPtr gt_object_pose_pub_
rclcpp::Publisher< visualization_msgs::msg::MarkerArray >::SharedPtr gt_object_path_pub_
rclcpp::Publisher< nav_msgs::msg::Odometry >::SharedPtr gt_odometry_pub_
Path of objects with gt.
rclcpp::Publisher< nav_msgs::msg::Path >::SharedPtr gt_odom_path_pub_
nav_msgs::msg::Path gt_odom_path_msg_
image_transport::Publisher gt_bounding_box_pub_
std::unique_ptr< tf2_ros::TransformBroadcaster > tf_broadcaster_
std::unique_ptr< cv::VideoWriter > video_writer_
Private Attributes inherited from dyno::InbuiltDisplayCommon
const DisplayParams params_
rclcpp::Node::SharedPtr node_
MarkerArrayPub::SharedPtr camera_frustrum_pub_
Additional Inherited Members
Public Types inherited from dyno::DisplayBase< INPUT >
using Input = INPUT
using This = DisplayBase< INPUT >
using InputConstPtr = typename INPUT::ConstPtr
Static Private Member Functions inherited from dyno::InbuiltDisplayCommon
static void constructBoundingBoxeMarkers (const CloudPerObject &cloud_per_object, MarkerArray &aabb_markers, MarkerArray &obb_markers, Timestamp timestamp, const std::string &prefix_marker_namespace)
Constructs axis-aligned BB (AABB) and oriented BB (OBB) marker arrays from a set of point clouds which are coloured per object.
static void createAxisMarkers (const gtsam::Pose3 &pose, MarkerArray &axis_markers, Timestamp timestamp, const cv::Scalar &colour, const std::string &frame, const std::string &ns, double length=0.8, double radius=0.1)
Detailed Description
Definition at line 50 of file FrontendInbuiltDisplayRos.hpp.
Constructor & Destructor Documentation
FrontendInbuiltDisplayRos()
dyno::FrontendInbuiltDisplayRos::FrontendInbuiltDisplayRos (const DisplayParams params, rclcpp::Node::SharedPtr node)
Definition at line 53 of file FrontendInbuiltDisplayRos.cc.
    : InbuiltDisplayCommon(params, node) {
  const rclcpp::QoS& sensor_data_qos = rclcpp::SensorDataQoS();
  tracking_image_pub_ =
      image_transport::create_publisher(node.get(), "tracking_image");
  static_tracked_points_pub_ =
      node->create_publisher<sensor_msgs::msg::PointCloud2>("static_cloud", 1);
  dynamic_tracked_points_pub_ =
      node->create_publisher<sensor_msgs::msg::PointCloud2>("dynamic_cloud", 1);
  odometry_pub_ = node->create_publisher<nav_msgs::msg::Odometry>("odom", 1);
  object_pose_pub_ =
      node->create_publisher<visualization_msgs::msg::MarkerArray>(
          "composed_object_poses", 1);
  object_pose_path_pub_ =
      node->create_publisher<visualization_msgs::msg::MarkerArray>(
          "composed_object_paths", 1);
  odometry_path_pub_ =
      node->create_publisher<nav_msgs::msg::Path>("odom_path", 2);
  object_motion_pub_ =
      node->create_publisher<nav_msgs::msg::Path>("object_motions", 1);
  object_bbx_line_pub_ =
      node->create_publisher<visualization_msgs::msg::MarkerArray>(
          "object_bbx_viz", 1);
  object_bbx_pub_ =
      node->create_publisher<visualization_msgs::msg::MarkerArray>(
          "object_bounding_boxes", 1);
  // TODO: fix up gt publisher namespacing -? currently
  // dynosam/dynosam/ground_trut....
  gt_odometry_pub_ =
      node->create_publisher<nav_msgs::msg::Odometry>("~/ground_truth/odom", 1);
  gt_object_pose_pub_ =
      node->create_publisher<visualization_msgs::msg::MarkerArray>(
          "~/ground_truth/object_poses", 1);
  gt_object_path_pub_ =
      node->create_publisher<visualization_msgs::msg::MarkerArray>(
          "~/ground_truth/object_paths", 1);
  gt_odom_path_pub_ = node->create_publisher<nav_msgs::msg::Path>(
      "~/ground_truth/odom_path", 1);
  gt_bounding_box_pub_ = image_transport::create_publisher(
      node.get(), "~/ground_truth/bounding_boxes");
  tf_broadcaster_ = std::make_unique<tf2_ros::TransformBroadcaster>(*node_);
}
References dynamic_tracked_points_pub_, gt_bounding_box_pub_, gt_object_path_pub_, gt_object_pose_pub_, gt_odom_path_pub_, gt_odometry_pub_, dyno::InbuiltDisplayCommon::node_, object_bbx_line_pub_, object_bbx_pub_, object_motion_pub_, object_pose_path_pub_, object_pose_pub_, odometry_path_pub_, odometry_pub_, static_tracked_points_pub_, tf_broadcaster_, and tracking_image_pub_.
~FrontendInbuiltDisplayRos()
dyno::FrontendInbuiltDisplayRos::~FrontendInbuiltDisplayRos ()
Definition at line 99 of file FrontendInbuiltDisplayRos.cc.
{
  if (video_writer_) video_writer_->release();
}
References video_writer_.
Member Function Documentation
processRGBDOutputpacket()
void dyno::FrontendInbuiltDisplayRos::processRGBDOutputpacket (const RGBDInstanceOutputPacket::ConstPtr & rgbd_frontend_output) private
Definition at line 138 of file FrontendInbuiltDisplayRos.cc.
{
  CHECK(rgbd_frontend_output);
  publishPointCloud(static_tracked_points_pub_,
                    rgbd_frontend_output->static_landmarks_,
                    rgbd_frontend_output->T_world_camera_);
  // TODO: there is a bunch of repeated code in this function and in
  // groupObjectCloud we leave this as is becuase this function ALSO creates the
  // coloured point cloud (which groupObjectCloud does not) eventually, refactor
  // into one function or calcualte the coloured cloud in the
  // RGBDInstanceOutputPacket
  CloudPerObject clouds_per_obj = publishPointCloud(
      dynamic_tracked_points_pub_, rgbd_frontend_output->dynamic_landmarks_,
      rgbd_frontend_output->T_world_camera_);
  publishObjectPositions(object_pose_pub_,
                         rgbd_frontend_output->propogated_object_poses_,
                         rgbd_frontend_output->getFrameId(),
                         rgbd_frontend_output->getTimestamp(), "frontend");
  publishObjectPaths(object_pose_path_pub_,
                     rgbd_frontend_output->propogated_object_poses_,
                     rgbd_frontend_output->getFrameId(),
                     rgbd_frontend_output->getTimestamp(), "frontend", 60);
  // object bounding box using linelist and id text in rviz
  {
    visualization_msgs::msg::MarkerArray
        object_bbx_linelist_marker_array;  // using linelist
    visualization_msgs::msg::MarkerArray object_bbx_marker_array;  // using cube
    static visualization_msgs::msg::Marker delete_marker;
    delete_marker.action = visualization_msgs::msg::Marker::DELETEALL;
    object_bbx_linelist_marker_array.markers.push_back(delete_marker);
    object_bbx_marker_array.markers.push_back(delete_marker);
    for (const auto& [object_id, obj_cloud] : clouds_per_obj) {
      pcl::PointXYZ centroid;
      pcl::computeCentroid(obj_cloud, centroid);
      const cv::Scalar colour = Color::uniqueId(object_id);
      visualization_msgs::msg::Marker txt_marker;
      txt_marker.header.frame_id = "world";
      txt_marker.ns = "object_id";
      txt_marker.id = object_id;
      txt_marker.type = visualization_msgs::msg::Marker::TEXT_VIEW_FACING;
      txt_marker.action = visualization_msgs::msg::Marker::ADD;
      txt_marker.header.stamp = node_->now();
      txt_marker.scale.z = 2.0;
      txt_marker.color.r = colour(0) / 255.0;
      txt_marker.color.g = colour(1) / 255.0;
      txt_marker.color.b = colour(2) / 255.0;
      txt_marker.color.a = 1;
      txt_marker.text = "obj " + std::to_string(object_id);
      txt_marker.pose.position.x = centroid.x;
      txt_marker.pose.position.y = centroid.y - 2.0;
      txt_marker.pose.position.z = centroid.z - 1.0;
      object_bbx_linelist_marker_array.markers.push_back(txt_marker);
      pcl::PointCloud<pcl::PointXYZRGB>::Ptr obj_cloud_ptr =
          pcl::make_shared<pcl::PointCloud<pcl::PointXYZRGB> >(obj_cloud);
      ObjectBBX aabb = findAABBFromCloud<pcl::PointXYZRGB>(obj_cloud_ptr);
      ObjectBBX obb = findOBBFromCloud<pcl::PointXYZRGB>(obj_cloud_ptr);
      visualization_msgs::msg::Marker marker;
      marker.header.frame_id = "world";
      marker.ns = "object_bbx_linelist";
      marker.id = object_id;
      marker.type = visualization_msgs::msg::Marker::LINE_LIST;
      marker.action = visualization_msgs::msg::Marker::ADD;
      marker.header.stamp = node_->now();
      marker.scale.x = 0.1;
      marker.pose.orientation.x = 0;
      marker.pose.orientation.y = 0;
      marker.pose.orientation.z = 0;
      marker.pose.orientation.w = 1;
      marker.color.r = colour(0) / 255.0;
      marker.color.g = colour(1) / 255.0;
      marker.color.b = colour(2) / 255.0;
      marker.color.a = 1;
      for (const pcl::PointXYZ& this_line_list_point :
           findLineListPointsFromAABBMinMax(aabb.min_bbx_point_,
                                            aabb.max_bbx_point_)) {
        geometry_msgs::msg::Point p;
        p.x = this_line_list_point.x;
        p.y = this_line_list_point.y;
        p.z = this_line_list_point.z;
        marker.points.push_back(p);
      }
      object_bbx_linelist_marker_array.markers.push_back(marker);
      visualization_msgs::msg::Marker bbx_marker;
      bbx_marker.header.frame_id = "world";
      bbx_marker.ns = "object_bbx";
      bbx_marker.id = object_id;
      bbx_marker.type = visualization_msgs::msg::Marker::CUBE;
      bbx_marker.action = visualization_msgs::msg::Marker::ADD;
      bbx_marker.header.stamp = node_->now();
      bbx_marker.scale.x = obb.max_bbx_point_.x() - obb.min_bbx_point_.x();
      bbx_marker.scale.y = obb.max_bbx_point_.y() - obb.min_bbx_point_.y();
      bbx_marker.scale.z = obb.max_bbx_point_.z() - obb.min_bbx_point_.z();
      bbx_marker.pose.position.x = obb.bbx_position_.x();
      bbx_marker.pose.position.y = obb.bbx_position_.y();
      bbx_marker.pose.position.z = obb.bbx_position_.z();
      const gtsam::Quaternion& q = obb.orientation_.toQuaternion();
      bbx_marker.pose.orientation.x = q.x();
      bbx_marker.pose.orientation.y = q.y();
      bbx_marker.pose.orientation.z = q.z();
      bbx_marker.pose.orientation.w = q.w();
      bbx_marker.color.r = colour(0) / 255.0;
      bbx_marker.color.g = colour(1) / 255.0;
      bbx_marker.color.b = colour(2) / 255.0;
      bbx_marker.color.a = 0.2;
      object_bbx_marker_array.markers.push_back(bbx_marker);
    }
    object_bbx_line_pub_->publish(object_bbx_linelist_marker_array);
    object_bbx_pub_->publish(object_bbx_marker_array);
  }
  // Predict 3D object poses
  gtsam::FastMap<ObjectId, std::vector<gtsam::Pose3> > obj_predicted_poses;
  {
    int prediction_length = 3;
    const FrameId current_frame_id = rgbd_frontend_output->getFrameId();
    const ObjectPoseMap& obj_poses =
        rgbd_frontend_output->propogated_object_poses_;
    const MotionEstimateMap& obj_motions =
        rgbd_frontend_output->estimated_motions_;
    for (const auto& [object_id, this_obj_traj] : obj_poses) {
      if (this_obj_traj.exists(current_frame_id)) {
        gtsam::Pose3 current_obj_pose = this_obj_traj.at(current_frame_id);
        if (obj_motions.exists(object_id)) {
          gtsam::Pose3 current_obj_motion = obj_motions.at(object_id);
          gtsam::Pose3 last_object_pose = current_obj_pose;
          std::vector<gtsam::Pose3> predicted_poses;
          for (int i_prediction = 0; i_prediction < prediction_length;
               i_prediction++) {
            predicted_poses.push_back(last_object_pose);
            last_object_pose = current_obj_motion * last_object_pose;
            last_object_pose = current_obj_motion * last_object_pose;
            // last_object_pose = current_obj_motion * last_object_pose;
          }
          obj_predicted_poses.insert2(object_id, predicted_poses);
        }
      }
    }
  }
  // Write object motion to nav_msgs/Path and publish
  nav_msgs::msg::Path object_motions_msg;
  {
    const FrameId current_frame_id = rgbd_frontend_output->getFrameId();
    const MotionEstimateMap& obj_motions =
        rgbd_frontend_output->estimated_motions_;
    // object_motions_msg.header.seq = current_frame_id;
    object_motions_msg.header.stamp = node_->now();
    object_motions_msg.header.frame_id = params_.world_frame_id;
    for (const auto& [object_id, current_obj_motion] : obj_motions) {
      geometry_msgs::msg::PoseStamped current_obj_motion_msg;
      current_obj_motion_msg.header.stamp = node_->now();
      current_obj_motion_msg.header.frame_id = std::to_string(object_id);
      current_obj_motion_msg.pose.position.x =
          current_obj_motion.estimate_.translation().x();
      current_obj_motion_msg.pose.position.y =
          current_obj_motion.estimate_.translation().y();
      current_obj_motion_msg.pose.position.z =
          current_obj_motion.estimate_.translation().z();
      current_obj_motion_msg.pose.orientation.w =
          current_obj_motion.estimate_.rotation()
              .toQuaternion()
              .w();  // in w x y z form
      current_obj_motion_msg.pose.orientation.x =
          current_obj_motion.estimate_.rotation()
              .toQuaternion()
              .x();  // in w x y z form
      current_obj_motion_msg.pose.orientation.y =
          current_obj_motion.estimate_.rotation()
              .toQuaternion()
              .y();  // in w x y z form
      current_obj_motion_msg.pose.orientation.z =
          current_obj_motion.estimate_.rotation()
              .toQuaternion()
              .z();  // in w x y z form
      object_motions_msg.poses.push_back(current_obj_motion_msg);
    }
    object_motion_pub_->publish(object_motions_msg);
  }
  // 2D image visualisation using opencv (TODO: and check that camera is
  // given!!)
  if (rgbd_frontend_output->debug_imagery_) {
    cv::Mat rgb_with_bbx;
    rgbd_frontend_output->debug_imagery_->tracking_image.copyTo(rgb_with_bbx);
    const cv::Size rgb_size = rgb_with_bbx.size();
    const StatusKeypointVector& obj_px =
        rgbd_frontend_output->dynamic_keypoint_measurements_;
    for (const KeypointStatus& this_px : obj_px) {
      ObjectId object_id = this_px.objectId();
      const gtsam::Point2& px_coordinate = this_px.value();
      const cv::Scalar colour = Color::uniqueId(object_id).bgra();
      // const cv::Scalar colour_bgr(colour[2], colour[1], colour[0]);
      cv::Point centre(functional_keypoint::u(px_coordinate),
                       functional_keypoint::v(px_coordinate));
      int radius = 1;
      int thickness = 1;
      cv::circle(rgb_with_bbx, centre, radius, colour, thickness);
    }
    // object history and prediction
    const ObjectPoseMap& obj_poses =
        rgbd_frontend_output->propogated_object_poses_;
    const gtsam::Pose3& cam_pose = rgbd_frontend_output->T_world_camera_;
    int line_thinkness = 3;
    for (const auto& [object_id, this_obj_traj] : obj_poses) {
      cv::Scalar colour = Color::uniqueId(object_id).bgra();
      // const cv::Scalar colour_bgr(colour[2], colour[1], colour[0]);
      std::vector<cv::Point> cv_line;
      for (const auto& [frame_id, this_obj_pose] : this_obj_traj) {
        gtsam::Pose3 this_obj_pose_in_cam = cam_pose.inverse() * this_obj_pose;
        Landmark this_obj_position_in_cam = this_obj_pose_in_cam.translation();
        Keypoint this_obj_px_in_cam;
        bool is_lmk_contained =
            rgbd_frontend_output->camera_->isLandmarkContained(
                this_obj_position_in_cam, &this_obj_px_in_cam);
        if (is_lmk_contained) {
          cv_line.push_back(
              cv::Point(functional_keypoint::u(this_obj_px_in_cam),
                        functional_keypoint::v(this_obj_px_in_cam)));
        }
      }
      int line_length = cv_line.size();
      for (int i_line = 0; i_line < line_length - 1; i_line++) {
        cv::line(rgb_with_bbx, cv_line[i_line], cv_line[i_line + 1], colour,
                 line_thinkness, cv::LINE_AA);
      }
      if (!obj_predicted_poses.exists(object_id)) {
        continue;
      }
      cv_line.clear();
      std::vector<gtsam::Pose3> this_obj_predicted_poses =
          obj_predicted_poses.at(object_id);
      for (const auto& this_obj_pose : this_obj_predicted_poses) {
        gtsam::Pose3 this_obj_pose_in_cam = cam_pose.inverse() * this_obj_pose;
        Landmark this_obj_position_in_cam = this_obj_pose_in_cam.translation();
        Keypoint this_obj_px_in_cam;
        bool is_lmk_contained =
            rgbd_frontend_output->camera_->isLandmarkContained(
                this_obj_position_in_cam, &this_obj_px_in_cam);
        if (is_lmk_contained) {
          cv_line.push_back(
              cv::Point(functional_keypoint::u(this_obj_px_in_cam),
                        functional_keypoint::v(this_obj_px_in_cam)));
        }
      }
      line_length = cv_line.size();
      // TODO: removed prediction arrow for now!!
      //  for (int i_line = 0; i_line < line_length-1; i_line++){
      //      double alpha = (double) i_line / ((double) line_length);
      //      cv::Scalar grad_colour = colour;
      //      grad_colour[0] = (255.0 - colour[0]) * alpha + colour[0];
      //      grad_colour[1] = (255.0 - colour[0]) * alpha + colour[1];
      //      grad_colour[2] = (255.0 - colour[0]) * alpha + colour[2];
      //      cv::arrowedLine(rgb_with_bbx, cv_line[i_line], cv_line[i_line+1],
      //      grad_colour, line_thinkness-1, cv::LINE_AA, 0, 0.3);
      //  }
    }
    // cv::resize(rgb_with_bbx, rgb_with_bbx, cv::Size(1280, 720) , 0, 0,
    // CV_INTER_LINEAR); if(video_writer_)  {
    //     CHECK(video_writer_->isOpened());
    //     video_writer_->write(rgb_with_bbx);
    // }
    cv::imshow("RGB with object bounding boxes", rgb_with_bbx);
    int frame_id = rgbd_frontend_output->getFrameId();
    // cv::Mat rgb_objects;
    // rgbd_frontend_output->frame_.tracking_images_.cloneImage<ImageType::RGBMono>(rgb_objects);
    // cv::imwrite("/root/results/RSS/"+std::to_string(frame_id)+".png",
    // rgb_objects);
  }
  {
    visualization_msgs::msg::MarkerArray object_pred_marker_array;
    for (const auto& [object_id, this_obj_predicted_poses] :
         obj_predicted_poses) {
      const cv::Scalar colour = Color::uniqueId(object_id);
      int pose_length = this_obj_predicted_poses.size();
      for (int i_pose = 0; i_pose < pose_length - 1; i_pose++) {
        gtsam::Point3 point_0 = this_obj_predicted_poses[i_pose].translation();
        gtsam::Point3 point_1 =
            this_obj_predicted_poses[i_pose + 1].translation();
        visualization_msgs::msg::Marker arrow_marker;
        arrow_marker.header.frame_id = "world";
        arrow_marker.ns = "object_pred";
        arrow_marker.id = object_id * 10 + i_pose;
        arrow_marker.type = visualization_msgs::msg::Marker::ARROW;
        arrow_marker.action = visualization_msgs::msg::Marker::ADD;
        arrow_marker.header.stamp = node_->now();
        arrow_marker.scale.x = 0.3;
        arrow_marker.scale.y = 0.5;
        arrow_marker.scale.z = 0.8;
        double alpha = (double)i_pose / ((double)pose_length);
        arrow_marker.color.r =
            ((255.0 - colour[0]) * alpha + colour[0]) / 255.0;
        arrow_marker.color.g =
            ((255.0 - colour[1]) * alpha + colour[1]) / 255.0;
        arrow_marker.color.b =
            ((255.0 - colour[2]) * alpha + colour[2]) / 255.0;
        arrow_marker.color.a = 1;
        geometry_msgs::msg::Point p0, p1;
        p0.x = point_0.x();
        p0.y = point_0.y();
        p0.z = point_0.z();
        p1.x = point_1.x();
        p1.y = point_1.y();
        p1.z = point_1.z();
        arrow_marker.points.push_back(p0);
        arrow_marker.points.push_back(p1);
        object_pred_marker_array.markers.push_back(arrow_marker);
      }
    }
    object_bbx_line_pub_->publish(object_pred_marker_array);
  }
}
References dyno::GenericObjectCentricMap< VALUE >::at(), dyno::ObjectBBX::bbx_position_, dyno::Color::bgra(), dynamic_tracked_points_pub_, dyno::findLineListPointsFromAABBMinMax(), dyno::ObjectBBX::max_bbx_point_, dyno::ObjectBBX::min_bbx_point_, dyno::InbuiltDisplayCommon::node_, object_bbx_line_pub_, object_bbx_pub_, object_motion_pub_, object_pose_path_pub_, object_pose_pub_, dyno::ObjectBBX::orientation_, dyno::InbuiltDisplayCommon::params_, dyno::InbuiltDisplayCommon::publishObjectPaths(), dyno::InbuiltDisplayCommon::publishObjectPositions(), dyno::InbuiltDisplayCommon::publishPointCloud(), static_tracked_points_pub_, dyno::functional_keypoint::u(), dyno::Color::uniqueId(), dyno::functional_keypoint::v(), and dyno::DisplayParams::world_frame_id.
Referenced by spinOnce().
publishDebugImage()
void dyno::FrontendInbuiltDisplayRos::publishDebugImage (const DebugImagery & debug_imagery) private
Definition at line 521 of file FrontendInbuiltDisplayRos.cc.
{
  if (debug_imagery.tracking_image.empty()) return;
  // cv::Mat resized_image;
  // cv::resize(debug_image, resized_image, cv::Size(640, 480));
  std_msgs::msg::Header hdr;
  sensor_msgs::msg::Image::SharedPtr msg =
      cv_bridge::CvImage(hdr, "bgr8", debug_imagery.tracking_image)
          .toImageMsg();
  tracking_image_pub_.publish(msg);
}
References dyno::DebugImagery::tracking_image, and tracking_image_pub_.
Referenced by spinOnce().
publishGroundTruthInfo()
void dyno::FrontendInbuiltDisplayRos::publishGroundTruthInfo (Timestamp timestamp, const GroundTruthInputPacket & gt_packet, const cv::Mat & rgb) private
Definition at line 537 of file FrontendInbuiltDisplayRos.cc.
                      {
  // odometry gt
  const gtsam::Pose3& T_world_camera = gt_packet.X_world_;
  nav_msgs::msg::Odometry odom_msg;
  utils::convertWithHeader(T_world_camera, odom_msg, timestamp, "world",
                           "camera");
  gt_odometry_pub_->publish(odom_msg);
  const auto frame_id = gt_packet.frame_id_;
  // odom path gt
  geometry_msgs::msg::PoseStamped pose_stamped;
  utils::convertWithHeader(T_world_camera, pose_stamped, timestamp, "world");
  static std_msgs::msg::Header header;
  header.stamp = utils::toRosTime(timestamp);
  header.frame_id = "world";
  gt_odom_path_msg_.header = header;
  gt_odom_path_msg_.poses.push_back(pose_stamped);
  gt_odom_path_pub_->publish(gt_odom_path_msg_);
  // prepare display image
  cv::Mat disp_image;
  rgb.copyTo(disp_image);
  static ObjectPoseMap gt_object_poses;
  for (const auto& object_pose_gt : gt_packet.object_poses_) {
    gt_object_poses.insert22(object_pose_gt.object_id_, gt_packet.frame_id_,
                             object_pose_gt.L_world_);
  }
  publishObjectPositions(gt_object_pose_pub_, gt_object_poses, frame_id,
                         timestamp, "ground_truth");
  publishObjectPaths(gt_object_path_pub_, gt_object_poses, frame_id, timestamp,
                     "ground_truth", 60);
  // static std::map<ObjectId, gtsam::Pose3Vector> gt_object_trajectories;
  // //Used for gt path updating static std::map<ObjectId, FrameId>
  // gt_object_trajectories_update; // The last frame id that the object was
  // seen in
  // std::set<ObjectId> seen_objects;
  // //prepare gt object pose markers
  // visualization_msgs::msg::MarkerArray object_pose_marker_array;
  // visualization_msgs::msg::MarkerArray object_path_marker_array;
  // static visualization_msgs::msg::Marker delete_marker;
  // delete_marker.action = visualization_msgs::msg::Marker::DELETEALL;
  // object_pose_marker_array.markers.push_back(delete_marker);
  // object_path_marker_array.markers.push_back(delete_marker);
  // for(const auto& object_pose_gt : gt_packet.object_poses_) {
  //     // const gtsam::Pose3 L_world = T_world_camera *
  //     object_pose_gt.L_camera_; const gtsam::Pose3 L_world =
  //     object_pose_gt.L_world_; const ObjectId object_id =
  //     object_pose_gt.object_id_;
  //     seen_objects.insert(object_id);
  //     visualization_msgs::msg::Marker marker;
  //     marker.header.frame_id = "world";
  //     marker.ns = "ground_truth_object_poses";
  //     marker.id = object_id;
  //     marker.type = visualization_msgs::msg::Marker::CUBE;
  //     marker.action = visualization_msgs::msg::Marker::ADD;
  //     marker.header.stamp = node_->now();
  //     marker.pose.position.x = L_world.x();
  //     marker.pose.position.y = L_world.y();
  //     marker.pose.position.z = L_world.z();
  //     marker.pose.orientation.x = L_world.rotation().toQuaternion().x();
  //     marker.pose.orientation.y = L_world.rotation().toQuaternion().y();
  //     marker.pose.orientation.z = L_world.rotation().toQuaternion().z();
  //     marker.pose.orientation.w = L_world.rotation().toQuaternion().w();
  //     marker.scale.x = 0.5;
  //     marker.scale.y = 0.5;
  //     marker.scale.z = 0.5;
  //     marker.color.a = 1.0; // Don't forget to set the alpha!
  //     const cv::Scalar colour = Color::uniqueId(object_id);
  //     marker.color.r = colour(0)/255.0;
  //     marker.color.g = colour(1)/255.0;
  //     marker.color.b = colour(2)/255.0;
  //     visualization_msgs::msg::Marker text_marker = marker;
  //     text_marker.ns = "ground_truth_object_labels";
  //     text_marker.type = visualization_msgs::msg::Marker::TEXT_VIEW_FACING;
  //     text_marker.text = std::to_string(object_id);
  //     text_marker.pose.position.z += 1.0; //make it higher than the pose
  //     marker text_marker.scale.z = 0.7;
  //     object_pose_marker_array.markers.push_back(marker);
  //     object_pose_marker_array.markers.push_back(text_marker);
  //     //draw on bbox
  //     object_pose_gt.drawBoundingBox(disp_image);
  //     //update past trajectotries of objects
  //     auto it = gt_object_trajectories.find(object_id);
  //     if(it == gt_object_trajectories.end()) {
  //         gt_object_trajectories[object_id] = gtsam::Pose3Vector();
  //     }
  //     gt_object_trajectories_update[object_id] = frame_id;
  //     gt_object_trajectories[object_id].push_back(L_world);
  // }
  // //repeated code from publishObjectPositions function
  // //iterate over object trajectories and display the ones with enough poses
  // and the ones weve seen recently for(const auto& [object_id, poses] :
  // gt_object_trajectories) {
  //     const FrameId last_seen_frame =
  //     gt_object_trajectories_update.at(object_id);
  //     //if weve seen the object in the last 30 frames and the length is at
  //     least 2 if(poses.size() < 2u) {
  //         continue;
  //     }
  //     //draw a line list for viz
  //     visualization_msgs::msg::Marker line_list_marker;
  //     line_list_marker.type = visualization_msgs::msg::Marker::LINE_LIST;
  //     line_list_marker.header.frame_id = "world";
  //     line_list_marker.ns = "gt_frontend_composed_object_path";
  //     line_list_marker.id = object_id;
  //     line_list_marker.header.stamp = node_->now();
  //     line_list_marker.scale.x = 0.5;
  //     line_list_marker.pose.orientation.x = 0;
  //     line_list_marker.pose.orientation.y = 0;
  //     line_list_marker.pose.orientation.z = 0;
  //     line_list_marker.pose.orientation.w = 1;
  //     const cv::Scalar colour = Color::uniqueId(object_id);
  //     line_list_marker.color.r = colour(0)/255.0;
  //     line_list_marker.color.g = colour(1)/255.0;
  //     line_list_marker.color.b = colour(2)/255.0;
  //     line_list_marker.color.a = 1;
  //     //only draw the last 60 poses
  //     const size_t traj_size = std::min(60, static_cast<int>(poses.size()));
  //     // const size_t traj_size = poses.size();
  //     //have to duplicate the first in each drawn pair so that we construct a
  //     complete line for(size_t i = poses.size() - traj_size + 1; i <
  //     poses.size(); i++) {
  //         const gtsam::Pose3& prev_pose = poses.at(i-1);
  //         const gtsam::Pose3& curr_pose = poses.at(i);
  //         {
  //             geometry_msgs::msg::Point p;
  //             p.x = prev_pose.x();
  //             p.y = prev_pose.y();
  //             p.z = prev_pose.z();
  //             line_list_marker.points.push_back(p);
  //         }
  //         {
  //             geometry_msgs::msg::Point p;
  //             p.x = curr_pose.x();
  //             p.y = curr_pose.y();
  //             p.z = curr_pose.z();
  //             line_list_marker.points.push_back(p);
  //         }
  //     }
  //     object_path_marker_array.markers.push_back(line_list_marker);
  // }
  // Publish centroids of composed object poses
  // gt_object_pose_pub_->publish(object_pose_marker_array);
  // // Publish composed object path
  // gt_object_path_pub_->publish(object_path_marker_array);
  cv::Mat resized_image;
  cv::resize(disp_image, resized_image, cv::Size(640, 480));
  std_msgs::msg::Header hdr;
  sensor_msgs::msg::Image::SharedPtr msg =
      cv_bridge::CvImage(hdr, "bgr8", resized_image).toImageMsg();
  gt_bounding_box_pub_.publish(msg);
}
References dyno::utils::convertWithHeader(), dyno::GroundTruthInputPacket::frame_id_, gt_bounding_box_pub_, gt_object_path_pub_, gt_object_pose_pub_, gt_odom_path_msg_, gt_odom_path_pub_, gt_odometry_pub_, dyno::GenericObjectCentricMap< VALUE >::insert22(), dyno::GroundTruthInputPacket::object_poses_, dyno::InbuiltDisplayCommon::publishObjectPaths(), dyno::InbuiltDisplayCommon::publishObjectPositions(), dyno::utils::toRosTime(), and dyno::GroundTruthInputPacket::X_world_.
Referenced by spinOnce().
publishOdometry()
void dyno::FrontendInbuiltDisplayRos::publishOdometry (const gtsam::Pose3 & T_world_camera, Timestamp timestamp) private
Definition at line 488 of file FrontendInbuiltDisplayRos.cc.
{
  InbuiltDisplayCommon::publishOdometry(odometry_pub_, T_world_camera,
                                        timestamp);
  geometry_msgs::msg::TransformStamped t;
  // utils::convertWithHeader(T_world_camera, t, timestamp,
  // params_.world_frame_id, params_.camera_frame_id_); Send the transformation
  dyno::convert<gtsam::Pose3, geometry_msgs::msg::TransformStamped>(
      T_world_camera, t);
  t.header.stamp = node_->now();
  t.header.frame_id = params_.world_frame_id;
  t.child_frame_id = params_.camera_frame_id;
  tf_broadcaster_->sendTransform(t);
}
References dyno::DisplayParams::camera_frame_id, dyno::InbuiltDisplayCommon::node_, odometry_pub_, dyno::InbuiltDisplayCommon::params_, dyno::InbuiltDisplayCommon::publishOdometry(), tf_broadcaster_, and dyno::DisplayParams::world_frame_id.
Referenced by spinOnce().
spinOnce()
void dyno::FrontendInbuiltDisplayRos::spinOnce (const FrontendOutputPacketBase::ConstPtr & frontend_output) override
Definition at line 103 of file FrontendInbuiltDisplayRos.cc.
{
  // TODO: does frontend or backend publish tf transform?
  if (frontend_output->debug_imagery_)
    publishDebugImage(*frontend_output->debug_imagery_);
  if (frontend_output->gt_packet_ && frontend_output->debug_imagery_) {
    const auto& debug_imagery = *frontend_output->debug_imagery_;
    // TODO: put tracking images back into frontend output
    const cv::Mat& rgb_image = debug_imagery.rgb_viz;
    publishGroundTruthInfo(frontend_output->getTimestamp(),
                           frontend_output->gt_packet_.value(), rgb_image);
  }
  RGBDInstanceOutputPacket::ConstPtr rgbd_output =
      safeCast<FrontendOutputPacketBase, RGBDInstanceOutputPacket>(
          frontend_output);
  if (rgbd_output) {
    processRGBDOutputpacket(rgbd_output);
    // TODO:currently only with RGBDInstanceOutputPacket becuase camera poses is
    // in RGBDInstanceOutputPacket but should be in base
    // (FrontendOutputPacketBase)
    publishOdometryPath(odometry_path_pub_, rgbd_output->camera_poses_,
                        frontend_output->getTimestamp());
    publishOdometry(frontend_output->T_world_camera_,
                    frontend_output->getTimestamp());
    // publishCameraMarker(
    //     frontend_output->T_world_camera_,
    //     frontend_output->getTimestamp(),
    //     "frontend_camera_pose",
    //     cv::viz::Color::yellow()
    // );
  }
}
References odometry_path_pub_, processRGBDOutputpacket(), publishDebugImage(), publishGroundTruthInfo(), publishOdometry(), and dyno::InbuiltDisplayCommon::publishOdometryPath().
Member Data Documentation
dynamic_tracked_points_pub_
rclcpp::Publisher<sensor_msgs::msg::PointCloud2>::SharedPtr dyno::FrontendInbuiltDisplayRos::dynamic_tracked_points_pub_ private
Definition at line 76 of file FrontendInbuiltDisplayRos.hpp.
Referenced by FrontendInbuiltDisplayRos(), and processRGBDOutputpacket().
gt_bounding_box_pub_
image_transport::Publisher dyno::FrontendInbuiltDisplayRos::gt_bounding_box_pub_ private
Definition at line 113 of file FrontendInbuiltDisplayRos.hpp.
Referenced by FrontendInbuiltDisplayRos(), and publishGroundTruthInfo().
gt_object_path_pub_
rclcpp::Publisher<visualization_msgs::msg::MarkerArray>::SharedPtr dyno::FrontendInbuiltDisplayRos::gt_object_path_pub_ private
Definition at line 107 of file FrontendInbuiltDisplayRos.hpp.
Referenced by FrontendInbuiltDisplayRos(), and publishGroundTruthInfo().
gt_object_pose_pub_
rclcpp::Publisher<visualization_msgs::msg::MarkerArray>::SharedPtr dyno::FrontendInbuiltDisplayRos::gt_object_pose_pub_ private
Definition at line 105 of file FrontendInbuiltDisplayRos.hpp.
Referenced by FrontendInbuiltDisplayRos(), and publishGroundTruthInfo().
gt_odom_path_msg_
nav_msgs::msg::Path dyno::FrontendInbuiltDisplayRos::gt_odom_path_msg_ private
Definition at line 111 of file FrontendInbuiltDisplayRos.hpp.
Referenced by publishGroundTruthInfo().
gt_odom_path_pub_
rclcpp::Publisher<nav_msgs::msg::Path>::SharedPtr dyno::FrontendInbuiltDisplayRos::gt_odom_path_pub_ private
Definition at line 110 of file FrontendInbuiltDisplayRos.hpp.
Referenced by FrontendInbuiltDisplayRos(), and publishGroundTruthInfo().
gt_odometry_pub_
rclcpp::Publisher<nav_msgs::msg::Odometry>::SharedPtr dyno::FrontendInbuiltDisplayRos::gt_odometry_pub_ private
Path of objects with gt.
Definition at line 108 of file FrontendInbuiltDisplayRos.hpp.
Referenced by FrontendInbuiltDisplayRos(), and publishGroundTruthInfo().
object_bbx_line_pub_
rclcpp::Publisher<visualization_msgs::msg::MarkerArray>::SharedPtr dyno::FrontendInbuiltDisplayRos::object_bbx_line_pub_ private
Propogated object poses using the motion estimate.
Definition at line 98 of file FrontendInbuiltDisplayRos.hpp.
Referenced by FrontendInbuiltDisplayRos(), and processRGBDOutputpacket().
object_bbx_pub_
rclcpp::Publisher<visualization_msgs::msg::MarkerArray>::SharedPtr dyno::FrontendInbuiltDisplayRos::object_bbx_pub_ private
Draw object bounding boxes as line lists.
Definition at line 100 of file FrontendInbuiltDisplayRos.hpp.
Referenced by FrontendInbuiltDisplayRos(), and processRGBDOutputpacket().
object_motion_pub_
rclcpp::Publisher<nav_msgs::msg::Path>::SharedPtr dyno::FrontendInbuiltDisplayRos::object_motion_pub_ private
The last frame id that the object was seen in
Definition at line 91 of file FrontendInbuiltDisplayRos.hpp.
Referenced by FrontendInbuiltDisplayRos(), and processRGBDOutputpacket().
object_pose_path_pub_
rclcpp::Publisher<visualization_msgs::msg::MarkerArray>::SharedPtr dyno::FrontendInbuiltDisplayRos::object_pose_path_pub_ private
Definition at line 83 of file FrontendInbuiltDisplayRos.hpp.
Referenced by FrontendInbuiltDisplayRos(), and processRGBDOutputpacket().
object_pose_pub_
rclcpp::Publisher<visualization_msgs::msg::MarkerArray>::SharedPtr dyno::FrontendInbuiltDisplayRos::object_pose_pub_ private
Publish object motions per frame as an array of SE(3) transformations (a Path) where frame_id per pose is object id
Definition at line 96 of file FrontendInbuiltDisplayRos.hpp.
Referenced by FrontendInbuiltDisplayRos(), and processRGBDOutputpacket().
object_trajectories_
std::map<ObjectId, gtsam::Pose3Vector> dyno::FrontendInbuiltDisplayRos::object_trajectories_ private
Path of propogated object poses using the motion estimate
Definition at line 85 of file FrontendInbuiltDisplayRos.hpp.
object_trajectories_update_
std::map<ObjectId, FrameId> dyno::FrontendInbuiltDisplayRos::object_trajectories_update_ private
Definition at line 87 of file FrontendInbuiltDisplayRos.hpp.
odom_path_msg_
nav_msgs::msg::Path dyno::FrontendInbuiltDisplayRos::odom_path_msg_ private
Definition at line 80 of file FrontendInbuiltDisplayRos.hpp.
odometry_path_pub_
rclcpp::Publisher<nav_msgs::msg::Path>::SharedPtr dyno::FrontendInbuiltDisplayRos::odometry_path_pub_ private
Definition at line 79 of file FrontendInbuiltDisplayRos.hpp.
Referenced by FrontendInbuiltDisplayRos(), and spinOnce().
odometry_pub_
rclcpp::Publisher<nav_msgs::msg::Odometry>::SharedPtr dyno::FrontendInbuiltDisplayRos::odometry_pub_ private
Definition at line 77 of file FrontendInbuiltDisplayRos.hpp.
Referenced by FrontendInbuiltDisplayRos(), and publishOdometry().
static_tracked_points_pub_
rclcpp::Publisher<sensor_msgs::msg::PointCloud2>::SharedPtr dyno::FrontendInbuiltDisplayRos::static_tracked_points_pub_ private
Definition at line 74 of file FrontendInbuiltDisplayRos.hpp.
Referenced by FrontendInbuiltDisplayRos(), and processRGBDOutputpacket().
tf_broadcaster_
std::unique_ptr<tf2_ros::TransformBroadcaster> dyno::FrontendInbuiltDisplayRos::tf_broadcaster_ private
Definition at line 115 of file FrontendInbuiltDisplayRos.hpp.
Referenced by FrontendInbuiltDisplayRos(), and publishOdometry().
tracking_image_pub_
image_transport::Publisher dyno::FrontendInbuiltDisplayRos::tracking_image_pub_ private
Draw object bounding boxes as cubes.
Definition at line 101 of file FrontendInbuiltDisplayRos.hpp.
Referenced by FrontendInbuiltDisplayRos(), and publishDebugImage().
video_writer_
std::unique_ptr<cv::VideoWriter> dyno::FrontendInbuiltDisplayRos::video_writer_ private
Definition at line 117 of file FrontendInbuiltDisplayRos.hpp.
Referenced by ~FrontendInbuiltDisplayRos().
The documentation for this class was generated from the following files:
dynosam_ros/include/dynosam_ros/displays/inbuilt_displays/FrontendInbuiltDisplayRos.hpp
dynosam_ros/src/displays/inbuilt_displays/FrontendInbuiltDisplayRos.cc