DynoSAM: dyno::PipelineBase Class Reference
dyno::PipelineBase Class Reference abstract
#include <PipelineBase.hpp>
Classes
struct ReturnCode
Public Types
using OnPipelineFailureCallback = std::function< void(ReturnCode)>
Public Member Functions
PipelineBase (const std::string &module_name)
virtual ~PipelineBase ()=default
bool spin ()
Spins the pipeline via continuous calls to spinOnce until the pipeline is shutdown.
bool isWorking () const
Returns true if the pipeline is currently processing data or if these is still data to process. Checks is_thread_working_ and the overwritten hasWork() function.
bool isShutdown () const
Returns true if the pipeline has been shutdown by shutdown().
std::string getModuleName () const
Returns the given module name (for identifcation and debug printing)
virtual void shutdown ()
void registerOnFailureCallback (const OnPipelineFailureCallback &callback_)
Registers a callback to be triggered if spinOnce returns an invalid return code.
virtual void shutdownQueues ()=0
Virtual function that should shutdown all associated queues. Generally this should shutdown input queues.
virtual bool hasWork () const =0
Virtual function that should check if (any of the) input queues have work to do.
virtual ReturnCode spinOnce ()=0
Processes for one iteration of the pipeline.
Protected Attributes
const std::string module_name_
std::atomic_bool is_thread_working_ { false }
Private Member Functions
void notifyFailures (const ReturnCode &result)
Private Attributes
std::vector< OnPipelineFailureCallback > on_failure_callbacks_
std::atomic_bool is_shutdown_ { false }
Thread related members.
Detailed Description
Definition at line 29 of file PipelineBase.hpp.
Member Typedef Documentation
OnPipelineFailureCallback
using dyno::PipelineBase::OnPipelineFailureCallback = std::function<void(ReturnCode)>
Definition at line 58 of file PipelineBase.hpp.
Constructor & Destructor Documentation
PipelineBase()
dyno::PipelineBase::PipelineBase (const std::string & module_name) inline
Definition at line 62 of file PipelineBase.hpp.
                                             : module_name_(module_name)
  {
  }
~PipelineBase()
virtual dyno::PipelineBase::~PipelineBase () virtual default
Member Function Documentation
getModuleName()
std::string dyno::PipelineBase::getModuleName () const inline
Returns the given module name (for identifcation and debug printing)
Returns
std::string
Definition at line 99 of file PipelineBase.hpp.
{return module_name_;}
References module_name_.
hasWork()
virtual bool dyno::PipelineBase::hasWork () const pure virtual
Virtual function that should check if (any of the) input queues have work to do.
Returns
true
false
Implemented in dyno::DataInterfacePipeline, dyno::FrontendOfflinePipeline< MODULE_TRAITS >, dyno::SIMOPipelineModule< INPUT, OUTPUT >, and dyno::SIMOPipelineModule< INPUT, NullPipelinePayload >.
Referenced by isWorking().
isShutdown()
bool dyno::PipelineBase::isShutdown () const inline
Returns true if the pipeline has been shutdown by shutdown().
Returns
true
false
Definition at line 92 of file PipelineBase.hpp.
{ return is_shutdown_; }
References is_shutdown_.
Referenced by dyno::DataInterfacePipeline::getInputPacket(), and spin().
isWorking()
bool dyno::PipelineBase::isWorking () const
Returns true if the pipeline is currently processing data or if these is still data to process. Checks is_thread_working_ and the overwritten hasWork() function.
Returns
true
false
Definition at line 56 of file PipelineBase.cc.
{
    return is_thread_working_ || hasWork();
}
References hasWork(), and is_thread_working_.
notifyFailures()
void dyno::PipelineBase::notifyFailures (const ReturnCode & result) private
Definition at line 62 of file PipelineBase.cc.
{
    for (const auto& failure_callbacks : on_failure_callbacks_)
    {
        if (failure_callbacks)
        {
            failure_callbacks(result);
        }
        else
        {
            LOG(ERROR) << "Invalid OnFailureCallback for module: " << module_name_;
        }
    }
}
References module_name_, and on_failure_callbacks_.
registerOnFailureCallback()
void dyno::PipelineBase::registerOnFailureCallback (const OnPipelineFailureCallback & callback_)
Registers a callback to be triggered if spinOnce returns an invalid return code.
Parameters
callback_ const OnPipelineFailureCallback&
Definition at line 77 of file PipelineBase.cc.
{
    CHECK(callback_);
    on_failure_callbacks_.push_back(callback_);
}
References on_failure_callbacks_.
shutdown()
void dyno::PipelineBase::shutdown () virtual
Definition at line 49 of file PipelineBase.cc.
{
    LOG(INFO) << "Shutting down module " << module_name_;
    is_shutdown_ = true;
    shutdownQueues();
}
References is_shutdown_, module_name_, and shutdownQueues().
Referenced by dyno::FrontendOfflinePipeline< MODULE_TRAITS >::process().
shutdownQueues()
virtual void dyno::PipelineBase::shutdownQueues () pure virtual
Virtual function that should shutdown all associated queues. Generally this should shutdown input queues.
Implemented in dyno::DataInterfacePipeline, dyno::FrontendOfflinePipeline< MODULE_TRAITS >, dyno::SIMOPipelineModule< INPUT, OUTPUT >, and dyno::SIMOPipelineModule< INPUT, NullPipelinePayload >.
Referenced by shutdown().
spin()
bool dyno::PipelineBase::spin ()
Spins the pipeline via continuous calls to spinOnce until the pipeline is shutdown.
Blocking call
Returns
true
false
Definition at line 37 of file PipelineBase.cc.
  {
    LOG(INFO) << "Starting module " << module_name_;
    while (!isShutdown())
    {
      spinOnce();
    //   using namespace std::chrono_literals;
    //   std::this_thread::sleep_for(1ms);  // give CPU thread some sleep time... //TODO: only if threaded?
    }
    return true;
  }
References isShutdown(), module_name_, and spinOnce().
Referenced by dyno::PipelineSpinner::AsynchronousSpinnerPair::launch(), and dyno::DynoPipelineManager::launchSpinners().
spinOnce()
virtual ReturnCode dyno::PipelineBase::spinOnce () pure virtual
Processes for one iteration of the pipeline.
Pulls data from registetered input queues and sends the data to some output queues. Called by spin().
Returns
PipelineReturnStatus
Implemented in dyno::PipelineModule< INPUT, OUTPUT >, dyno::PipelineModule< FrontendInputPacketBase, FrontendInputPacketBase >, dyno::PipelineModule< INPUT, NullPipelinePayload >, and dyno::PipelineModule< NullPipelinePayload, FrontendOutputPacketBase >.
Referenced by spin().
Member Data Documentation
is_shutdown_
std::atomic_bool dyno::PipelineBase::is_shutdown_ { false } private
Thread related members.
Definition at line 143 of file PipelineBase.hpp.
Referenced by isShutdown(), and shutdown().
is_thread_working_
std::atomic_bool dyno::PipelineBase::is_thread_working_ { false } protected
Definition at line 135 of file PipelineBase.hpp.
Referenced by isWorking().
module_name_
const std::string dyno::PipelineBase::module_name_ protected
Definition at line 134 of file PipelineBase.hpp.
Referenced by getModuleName(), notifyFailures(), shutdown(), and spin().
on_failure_callbacks_
std::vector<OnPipelineFailureCallback> dyno::PipelineBase::on_failure_callbacks_ private
Definition at line 141 of file PipelineBase.hpp.
Referenced by notifyFailures(), and registerOnFailureCallback().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/pipeline/PipelineBase.hpp
dynosam/src/pipeline/PipelineBase.cc