DynoSAM: dyno::ThreadsafeImuBuffer Class Reference
dyno::ThreadsafeImuBuffer Class Reference
#include <ThreadSafeImuBuffer.hpp>
Public Types
enum class QueryResult {
kDataAvailable , kDataNotYetAvailable , kDataNeverAvailable , kQueueShutdown ,
kTooFewMeasurementsAvailable
}
Public Member Functions
ThreadsafeImuBuffer (const Timestamp &buffer_length_ns)
~ThreadsafeImuBuffer ()
void shutdown ()
Shutdown the queue and release all blocked waiters.
size_t size () const
void clear ()
bool isShutdown () const
void addMeasurement (const Timestamp &timestamp_nanoseconds, const ImuAccGyr &imu_measurement)
void addMeasurements (const Timestamps &timestamps_nanoseconds, const ImuAccGyrs &imu_measurements)
QueryResult getImuDataBtwTimestamps (const Timestamp &timestamp_ns_from, const Timestamp &timestamp_ns_to, Timestamps *imu_timestamps, ImuAccGyrs *imu_measurements, bool get_lower_bound=false)
QueryResult getImuDataInterpolatedBorders (const Timestamp &timestamp_from, const Timestamp &timestamp_to, Timestamps *imu_timestamps, ImuAccGyrs *imu_measurements)
Return a list of the IMU measurements between the specified timestamps. The IMU values get interpolated if the queried timestamp does not match a measurement.
QueryResult getImuDataInterpolatedUpperBorder (const Timestamp &timestamp_ns_from, const Timestamp &timestamp_ns_to, Timestamps *imu_timestamps, ImuAccGyrs *imu_measurements)
Return a list of the IMU measurements between the specified timestamps. ONLY the IMU newest value gets interpolated (if the queried timestamp does not match a measurement, otw no interpolation). The oldest IMU value is always an actual measurement (aka no interpolation for the lower border, ever).
void interpolateValueAtTimestamp (const Timestamp &timestamp_ns, ImuAccGyr *interpolated_imu_measurement)
QueryResult getImuDataInterpolatedBordersBlocking (const Timestamp &timestamp_ns_from, const Timestamp &timestamp_ns_to, long int wait_timeout_nanoseconds, Timestamps *imu_timestamps, ImuAccGyrs *imu_measurements)
Static Public Member Functions
static void linearInterpolate (const Timestamp &x0, const ImuAccGyr &y0, const Timestamp &x1, const ImuAccGyr &y1, const Timestamp &x, ImuAccGyr *y)
Linear interpolation between two imu measurements.
Private Types
typedef std::pair< const Timestamp, ImuMeasurement > BufferElement
typedef Eigen::aligned_allocator< BufferElement > BufferAllocator
typedef ThreadsafeTemporalBuffer< ImuMeasurement, BufferAllocator > Buffer
Private Member Functions
QueryResult isDataAvailableUpToImpl (const Timestamp &timestamp_ns_from, const Timestamp &timestamp_ns_to) const
Private Attributes
Buffer buffer_
std::mutex m_buffer_
std::condition_variable cv_new_measurement_
std::atomic< bool > shutdown_
Detailed Description
This buffering class can be used to store a history of IMU measurements. It allows to retrieve a list of measurements up to a given timestamp. The data is stored in the order it is added. So make sure to add it in correct time-wise order.
Definition at line 85 of file ThreadSafeImuBuffer.hpp.
Member Typedef Documentation
Buffer
typedef ThreadsafeTemporalBuffer<ImuMeasurement, BufferAllocator> dyno::ThreadsafeImuBuffer::Buffer private
Definition at line 213 of file ThreadSafeImuBuffer.hpp.
BufferAllocator
typedef Eigen::aligned_allocator<BufferElement> dyno::ThreadsafeImuBuffer::BufferAllocator private
Definition at line 212 of file ThreadSafeImuBuffer.hpp.
BufferElement
typedef std::pair<const Timestamp, ImuMeasurement> dyno::ThreadsafeImuBuffer::BufferElement private
Definition at line 211 of file ThreadSafeImuBuffer.hpp.
Member Enumeration Documentation
QueryResult
enum class dyno::ThreadsafeImuBuffer::QueryResult strong
Enumerator
kDataAvailable
Query was successful and the data is available.
kDataNotYetAvailable
The required data is not (yet) available. The query timestamp is above the last IMU sample's time.
kDataNeverAvailable
The queried timestamp lies before the first IMU sample in the buffer. This request will never succeed considering chronological ordering of the buffer input data.
kQueueShutdown
Queue shutdown.
kTooFewMeasurementsAvailable
Definition at line 89 of file ThreadSafeImuBuffer.hpp.
{
    kDataAvailable,
    kDataNotYetAvailable,
    kDataNeverAvailable,
    kQueueShutdown,
    kTooFewMeasurementsAvailable
  };
Constructor & Destructor Documentation
ThreadsafeImuBuffer()
dyno::ThreadsafeImuBuffer::ThreadsafeImuBuffer (const Timestamp & buffer_length_ns) inline explicit
Definition at line 104 of file ThreadSafeImuBuffer.hpp.
      : buffer_(buffer_length_ns), shutdown_(false) {}
~ThreadsafeImuBuffer()
dyno::ThreadsafeImuBuffer::~ThreadsafeImuBuffer () inline
Definition at line 107 of file ThreadSafeImuBuffer.hpp.
{ shutdown(); }
References shutdown().
Member Function Documentation
addMeasurement()
void dyno::ThreadsafeImuBuffer::addMeasurement (const Timestamp & timestamp_nanoseconds, const ImuAccGyr & imu_measurement) inline
Add IMU measurement in IMU frame. (Ordering: accelerations [m/s^2], angular velocities [rad/s])
Definition at line 77 of file ThreadSafeImuBuffer-inl.hpp.
{
  // Enforce strict time-wise ordering.
  ImuMeasurement last_value;
  if (buffer_.getNewestValue(&last_value)) {
    CHECK_GT(timestamp_nanoseconds, last_value.timestamp_)
        << "Timestamps not strictly increasing.";
  }
  buffer_.addValue(
      timestamp_nanoseconds,
      ImuMeasurement(timestamp_nanoseconds, imu_measurement));
  // Notify possibly waiting consumers.
  cv_new_measurement_.notify_all();
}
References dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::addValue(), buffer_, cv_new_measurement_, dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::getNewestValue(), and dyno::ImuMeasurement::timestamp_.
Referenced by addMeasurements(), and dyno::ImuInterfaceHandler::fillImuQueue().
addMeasurements()
void dyno::ThreadsafeImuBuffer::addMeasurements (const Timestamps & timestamps_nanoseconds, const ImuAccGyrs & imu_measurements) inline
Definition at line 94 of file ThreadSafeImuBuffer-inl.hpp.
{
  CHECK_EQ(timestamps_nanoseconds.cols(), imu_measurements.cols());
  size_t num_samples = timestamps_nanoseconds.cols();
  CHECK_GT(num_samples, 0u);
  for (size_t idx = 0u; idx < num_samples; ++idx) {
    addMeasurement(timestamps_nanoseconds(idx), imu_measurements.col(idx));
  }
}
References addMeasurement().
Referenced by dyno::ImuInterfaceHandler::fillImuQueue().
clear()
void dyno::ThreadsafeImuBuffer::clear () inline
Definition at line 106 of file ThreadSafeImuBuffer-inl.hpp.
{
  buffer_.clear();
}
References buffer_, and dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::clear().
getImuDataBtwTimestamps()
ThreadsafeImuBuffer::QueryResult dyno::ThreadsafeImuBuffer::getImuDataBtwTimestamps (const Timestamp & timestamp_ns_from, const Timestamp & timestamp_ns_to, Timestamps * imu_timestamps, ImuAccGyrs * imu_measurements, bool get_lower_bound = false)
Definition at line 121 of file ThreadSafeImuBuffer.cc.
{
  CHECK_NOTNULL(imu_timestamps);
  CHECK_NOTNULL(imu_measurements);
  DCHECK_LT(timestamp_ns_from, timestamp_ns_to);
  QueryResult query_result =
      isDataAvailableUpToImpl(timestamp_ns_from, timestamp_ns_to);
  if (query_result != QueryResult::kDataAvailable) {
    imu_timestamps->resize(Eigen::NoChange, 0);
    imu_measurements->resize(Eigen::NoChange, 0);
    return query_result;
  }
  // TODO can we avoid copying and have the temporal buffer store pairs of
  // timestamps/accgyr data?
  // Copy the data with timestamp_up_to <= timestamps_buffer from the buffer.
  Aligned<std::vector, ImuMeasurement> between_values;
  CHECK(buffer_.getValuesBetweenTimes(timestamp_ns_from, timestamp_ns_to,
                                      &between_values, get_lower_bound));
  if (between_values.empty()) {
    LOG(WARNING) << "No IMU measurements available strictly between time "
                 << timestamp_ns_from << "[ns] and " << timestamp_ns_to
                 << "[ns].";
    imu_timestamps->resize(Eigen::NoChange, 0);
    imu_measurements->resize(Eigen::NoChange, 0);
    return QueryResult::kTooFewMeasurementsAvailable;
  }
  const size_t num_measurements = between_values.size();
  imu_timestamps->resize(Eigen::NoChange, num_measurements);
  imu_measurements->resize(Eigen::NoChange, num_measurements);
  for (size_t idx = 0u; idx < num_measurements; ++idx) {
    (*imu_timestamps)(idx) = between_values[idx].timestamp_;
    (*imu_measurements).col(idx) = between_values[idx].acc_gyr_;
  }
  return query_result;
}
References buffer_, dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::getValuesBetweenTimes(), isDataAvailableUpToImpl(), kDataAvailable, and kTooFewMeasurementsAvailable.
Referenced by getImuDataInterpolatedBorders(), and getImuDataInterpolatedUpperBorder().
getImuDataInterpolatedBorders()
ThreadsafeImuBuffer::QueryResult dyno::ThreadsafeImuBuffer::getImuDataInterpolatedBorders (const Timestamp & timestamp_from, const Timestamp & timestamp_to, Timestamps * imu_timestamps, ImuAccGyrs * imu_measurements)
Return a list of the IMU measurements between the specified timestamps. The IMU values get interpolated if the queried timestamp does not match a measurement.
Parameters
[in] timestamp_from Try to get the IMU measurements from this time [ns].
[in] timestamp_to Try to get the IMU measurements up this time [ns].
[out] imu_timestamps List of timestamps. [ns]
[out] imu_measurements List of IMU measurements. (Order: [acc, gyro])
Returns
The return code signals if the buffer does not contain data up to the requested timestamp. In this case the output matrices will be of size 0.
Definition at line 200 of file ThreadSafeImuBuffer.cc.
{
  CHECK_NOTNULL(imu_timestamps);
  CHECK_NOTNULL(imu_measurements);
  // Get data.
  Timestamps imu_timestamps_tmp;
  ImuAccGyrs imu_measurements_tmp;
  QueryResult query_result =
      getImuDataBtwTimestamps(timestamp_ns_from, timestamp_ns_to,
                              &imu_timestamps_tmp, &imu_measurements_tmp);
  // Early exit if there is no data.
  if (query_result != QueryResult::kDataAvailable) {
    imu_timestamps->resize(Eigen::NoChange, 0);
    imu_measurements->resize(Eigen::NoChange, 0);
    return query_result;
  }
  // Interpolate lower border.
  ImuAccGyr interpolated_lower_border;
  interpolateValueAtTimestamp(timestamp_ns_from, &interpolated_lower_border);
  // Interpolate upper border.
  ImuAccGyr interpolated_upper_border;
  interpolateValueAtTimestamp(timestamp_ns_to, &interpolated_upper_border);
  DCHECK_EQ(imu_timestamps->rows(), 1);
  DCHECK_EQ(imu_measurements->rows(), 6);
  // The first and last measurements will correspond to the interpolated data.
  const size_t num_measurements = imu_timestamps_tmp.cols() + 2u;
  imu_timestamps->resize(Eigen::NoChange, num_measurements);
  imu_measurements->resize(Eigen::NoChange, num_measurements);
  // Prepend lower border.
  imu_timestamps->leftCols<1>()(0) = timestamp_ns_from;
  imu_measurements->leftCols<1>() = interpolated_lower_border;
  // Add measurements.
  imu_timestamps->middleCols(1, imu_timestamps_tmp.cols()) = imu_timestamps_tmp;
  imu_measurements->middleCols(1, imu_measurements_tmp.cols()) =
      imu_measurements_tmp;
  // Append upper border.
  imu_timestamps->rightCols<1>()(0) = timestamp_ns_to;
  imu_measurements->rightCols<1>() = interpolated_upper_border;
  return query_result;
}
References getImuDataBtwTimestamps(), interpolateValueAtTimestamp(), and kDataAvailable.
Referenced by getImuDataInterpolatedBordersBlocking(), and dyno::ImuInterfaceHandler::getTimeSyncedImuMeasurements().
getImuDataInterpolatedBordersBlocking()
ThreadsafeImuBuffer::QueryResult dyno::ThreadsafeImuBuffer::getImuDataInterpolatedBordersBlocking (const Timestamp & timestamp_ns_from, const Timestamp & timestamp_ns_to, long int wait_timeout_nanoseconds, Timestamps * imu_timestamps, ImuAccGyrs * imu_measurements)
Try to pop the requested IMU measurements for the duration of wait_timeout_nanoseconds. If the requested data is still not available when timeout has been reached, the method will return false and no data will be removed from the buffer.
Definition at line 267 of file ThreadSafeImuBuffer.cc.
{
  CHECK_NOTNULL(imu_timestamps);
  CHECK_NOTNULL(imu_measurements);
  // Wait for the IMU buffer to contain the required measurements within a
  // timeout.
  auto tic = utils::Timer::tic();
  QueryResult query_result;
  {
    std::unique_lock<std::mutex> lock(m_buffer_);
    while ((query_result =
                isDataAvailableUpToImpl(timestamp_ns_from, timestamp_ns_to)) !=
           QueryResult::kDataAvailable) {
      cv_new_measurement_.wait_for(
          lock, std::chrono::nanoseconds(wait_timeout_nanoseconds));
      if (shutdown_) {
        imu_timestamps->resize(Eigen::NoChange, 0);
        imu_measurements->resize(Eigen::NoChange, 0);
        return QueryResult::kQueueShutdown;
      }
      // Check if we hit the max. time allowed to wait for the required data.
      auto toc = utils::Timer::toc<std::chrono::nanoseconds>(tic);
      if (toc.count() >= wait_timeout_nanoseconds) {
        imu_timestamps->resize(Eigen::NoChange, 0);
        imu_measurements->resize(Eigen::NoChange, 0);
        LOG(WARNING) << "Timeout reached while trying to get the requested "
                     << "IMU data. Requested range: " << timestamp_ns_from
                     << " to " << timestamp_ns_to << ".";
        if (query_result == QueryResult::kDataNotYetAvailable) {
          LOG(WARNING) << "The relevant IMU data is not yet available.";
        } else if (query_result == QueryResult::kDataNeverAvailable) {
          LOG(WARNING) << "The relevant IMU data will never be available. "
                       << "Either the buffer is too small or a sync issue "
                       << "occurred.";
        } else {
          LOG(FATAL) << "Unknown query result error.";
        }
        return query_result;
      }
    }
  }
  return getImuDataInterpolatedBorders(timestamp_ns_from, timestamp_ns_to,
                                       imu_timestamps, imu_measurements);
}
References cv_new_measurement_, getImuDataInterpolatedBorders(), isDataAvailableUpToImpl(), kDataAvailable, kDataNeverAvailable, kDataNotYetAvailable, kQueueShutdown, m_buffer_, shutdown_, and dyno::utils::Timer::tic().
getImuDataInterpolatedUpperBorder()
ThreadsafeImuBuffer::QueryResult dyno::ThreadsafeImuBuffer::getImuDataInterpolatedUpperBorder (const Timestamp & timestamp_ns_from, const Timestamp & timestamp_ns_to, Timestamps * imu_timestamps, ImuAccGyrs * imu_measurements)
Return a list of the IMU measurements between the specified timestamps. ONLY the IMU newest value gets interpolated (if the queried timestamp does not match a measurement, otw no interpolation). The oldest IMU value is always an actual measurement (aka no interpolation for the lower border, ever).
Parameters
[in] timestamp_from Get the IMU measurements from this time [ns].
[in] timestamp_to Try to get the IMU measurements up this time [ns].
[out] imu_timestamps List of timestamps. [ns]
[out] imu_measurements List of IMU measurements. (Order: [acc, gyro])
Returns
The return code signals if the buffer does not contain data surrounding the requested timestamps (check function isDataAvailableUpToImpl). In this case the output matrices will be of size 0.
Definition at line 165 of file ThreadSafeImuBuffer.cc.
{
  CHECK_NOTNULL(imu_timestamps);
  CHECK_NOTNULL(imu_measurements);
  DCHECK_LT(timestamp_ns_from, timestamp_ns_to);
  // Get data.
  QueryResult query_result = getImuDataBtwTimestamps(
      timestamp_ns_from, timestamp_ns_to, imu_timestamps, imu_measurements,
      true);  // Get lower bound.
  // Early exit if there is no data.
  if (query_result != QueryResult::kDataAvailable) {
    imu_timestamps->resize(Eigen::NoChange, 0);
    imu_measurements->resize(Eigen::NoChange, 0);
    return query_result;
  }
  // Interpolate upper border.
  ImuAccGyr interpolated_upper_border;
  interpolateValueAtTimestamp(timestamp_ns_to, &interpolated_upper_border);
  DCHECK_EQ(imu_timestamps->rows(), 1);
  DCHECK_EQ(imu_measurements->rows(), 6);
  // The last measurement will correspond to the interpolated data.
  const size_t num_measurements = imu_timestamps->cols() + 1u;
  imu_timestamps->conservativeResize(Eigen::NoChange, num_measurements);
  imu_measurements->conservativeResize(Eigen::NoChange, num_measurements);
  // Append upper border.
  imu_timestamps->rightCols<1>()(0) = timestamp_ns_to;
  imu_measurements->rightCols<1>() = interpolated_upper_border;
  return query_result;
}
References getImuDataBtwTimestamps(), interpolateValueAtTimestamp(), and kDataAvailable.
interpolateValueAtTimestamp()
void dyno::ThreadsafeImuBuffer::interpolateValueAtTimestamp (const Timestamp & timestamp_ns, ImuAccGyr * interpolated_imu_measurement)
Definition at line 246 of file ThreadSafeImuBuffer.cc.
{
  CHECK_NOTNULL(interpolated_imu_measurement);
  Timestamp pre_border_timestamp, post_border_timestamp;
  ImuMeasurement pre_border_value, post_border_value;
  CHECK(buffer_.getValueAtOrBeforeTime(timestamp_ns, &pre_border_timestamp,
                                       &pre_border_value))
      << "The IMU buffer seems not to contain measurements at or before time: "
      << timestamp_ns;
  CHECK_EQ(pre_border_timestamp, pre_border_value.timestamp_);
  CHECK(buffer_.getValueAtOrAfterTime(timestamp_ns, &post_border_timestamp,
                                      &post_border_value))
      << "The IMU buffer seems not to contain measurements at or after time: "
      << timestamp_ns;
  CHECK_EQ(post_border_timestamp, post_border_value.timestamp_);
  linearInterpolate(pre_border_value.timestamp_, pre_border_value.acc_gyr_,
                    post_border_value.timestamp_, post_border_value.acc_gyr_,
                    timestamp_ns, interpolated_imu_measurement);
}
References dyno::ImuMeasurement::acc_gyr_, buffer_, dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::getValueAtOrAfterTime(), dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::getValueAtOrBeforeTime(), linearInterpolate(), and dyno::ImuMeasurement::timestamp_.
Referenced by getImuDataInterpolatedBorders(), and getImuDataInterpolatedUpperBorder().
isDataAvailableUpToImpl()
ThreadsafeImuBuffer::QueryResult dyno::ThreadsafeImuBuffer::isDataAvailableUpToImpl (const Timestamp & timestamp_ns_from, const Timestamp & timestamp_ns_to) const private
TODO I think this comment is deprecated: Is data available up to this timestamp? Note this function does not lock the buffers, the caller must hold the lock. TODO I believe it should be: a) checks that the requested interval of data is a subset of the data in the IMU buffer, returns: Ex. IMU buffer holds timestamps 2 3 4 5, then i) Query timestamp_ns_to > 5 (e.g. 7) , returns kDataNotYetAvailable. ii) Query from timestamp < 2 (e.g. 0) or timestamp to < 2 (e.g. 1) , returns kDataNeverAvailable. iii) Query from timestamp 3 to 4, returns kDataAvailable. And I don't think there is a need to lock any mutex, as buffer_ is already threadsafe...
Definition at line 78 of file ThreadSafeImuBuffer.cc.
{
  CHECK_LT(timestamp_ns_from, timestamp_ns_to);
  if (shutdown_) {
    return QueryResult::kQueueShutdown;
  }
  if (buffer_.empty()) {
    return QueryResult::kDataNotYetAvailable;
  }
  ImuMeasurement value;
  if (buffer_.getNewestValue(&value) && value.timestamp_ < timestamp_ns_to) {
    // This is triggered if the timestamp_ns_to requested exceeds the newest
    // IMU measurement, meaning that there is data still to arrive to reach the
    // requested point in time.
    return QueryResult::kDataNotYetAvailable;
  }
  if (buffer_.getOldestValue(&value) && timestamp_ns_from < value.timestamp_) {
    // This is triggered if the user requests data previous to the oldest IMU
    // measurement present in the buffer, meaning that there is missing data
    // from the timestamp_ns_from requested to the oldest stored timestamp.
    return QueryResult::kDataNeverAvailable;
  }
  return QueryResult::kDataAvailable;
}
References buffer_, dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::empty(), dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::getNewestValue(), dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::getOldestValue(), kDataAvailable, kDataNeverAvailable, kDataNotYetAvailable, kQueueShutdown, shutdown_, and dyno::ImuMeasurement::timestamp_.
Referenced by getImuDataBtwTimestamps(), and getImuDataInterpolatedBordersBlocking().
isShutdown()
bool dyno::ThreadsafeImuBuffer::isShutdown () const inline
Definition at line 113 of file ThreadSafeImuBuffer.hpp.
{ return shutdown_; }
References shutdown_.
Referenced by dyno::ImuInterfaceHandler::getTimeSyncedImuMeasurements().
linearInterpolate()
void dyno::ThreadsafeImuBuffer::linearInterpolate (const Timestamp & x0, const ImuAccGyr & y0, const Timestamp & x1, const ImuAccGyr & y1, const Timestamp & x, ImuAccGyr * y) static
Linear interpolation between two imu measurements.
Definition at line 108 of file ThreadSafeImuBuffer.cc.
{
  CHECK_NOTNULL(y);
  CHECK_LE(t0, t);
  CHECK_LE(t, t1);
  *y = t0 == t1 ? y0 :  // y0 if t0 == t1, interpolate otherwise:
           y0 + (y1 - y0) * static_cast<double>(t - t0) /
                    static_cast<double>(t1 - t0);
}
Referenced by interpolateValueAtTimestamp().
shutdown()
void dyno::ThreadsafeImuBuffer::shutdown () inline
Shutdown the queue and release all blocked waiters.
Definition at line 114 of file ThreadSafeImuBuffer-inl.hpp.
{
  shutdown_ = true;
  cv_new_measurement_.notify_all();
}
References cv_new_measurement_, and shutdown_.
Referenced by ~ThreadsafeImuBuffer().
size()
size_t dyno::ThreadsafeImuBuffer::size () const inline
Definition at line 110 of file ThreadSafeImuBuffer-inl.hpp.
{
  return buffer_.size();
}
References buffer_, and dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::size().
Referenced by dyno::ImuInterfaceHandler::getTimeSyncedImuMeasurements().
Member Data Documentation
buffer_
Buffer dyno::ThreadsafeImuBuffer::buffer_ private
Definition at line 215 of file ThreadSafeImuBuffer.hpp.
Referenced by addMeasurement(), clear(), getImuDataBtwTimestamps(), interpolateValueAtTimestamp(), isDataAvailableUpToImpl(), and size().
cv_new_measurement_
std::condition_variable dyno::ThreadsafeImuBuffer::cv_new_measurement_ private
Definition at line 217 of file ThreadSafeImuBuffer.hpp.
Referenced by addMeasurement(), getImuDataInterpolatedBordersBlocking(), and shutdown().
m_buffer_
std::mutex dyno::ThreadsafeImuBuffer::m_buffer_ mutable private
Definition at line 216 of file ThreadSafeImuBuffer.hpp.
Referenced by getImuDataInterpolatedBordersBlocking().
shutdown_
std::atomic<bool> dyno::ThreadsafeImuBuffer::shutdown_ private
Definition at line 218 of file ThreadSafeImuBuffer.hpp.
Referenced by getImuDataInterpolatedBordersBlocking(), isDataAvailableUpToImpl(), isShutdown(), and shutdown().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/frontend/imu/ThreadSafeImuBuffer.hpp
dynosam/include/dynosam/frontend/imu/ThreadSafeImuBuffer-inl.hpp
dynosam/src/frontend/imu/ThreadSafeImuBuffer.cc