DynoSAM: dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType > Class Template Reference
dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType > Class Template Reference
#include <ThreadSafeTemporalBuffer.hpp>
Public Types
typedef std::map< Timestamp, ValueType, std::less< Timestamp >, AllocatorType > BufferType
using This = ThreadsafeTemporalBuffer< ValueType, AllocatorType >
using Type = ValueType
Public Member Functions
ThreadsafeTemporalBuffer ()
ThreadsafeTemporalBuffer (Timestamp buffer_length_seonds)
ThreadsafeTemporalBuffer (const ThreadsafeTemporalBuffer &other)
ThreadsafeTemporalBuffer & operator= (const ThreadsafeTemporalBuffer &other)
void addValue (Timestamp timestamp, const ValueType &value)
void addValue (const Timestamp timestamp, const ValueType &value, const bool emit_warning_on_value_overwrite)
void insert (const ThreadsafeTemporalBuffer &other)
size_t size () const
Timestamp bufferLength () const
bool empty () const
void clear ()
bool getValueAtTime (Timestamp timestamp_ns, ValueType *value) const
bool deleteValueAtTime (Timestamp timestamp_ns)
bool getNearestValueToTime (Timestamp timestamp_ns, ValueType *value) const
bool getNearestValueToTime (Timestamp timestamp_ns, Timestamp maximum_delta_s, ValueType *value) const
bool getNearestValueToTime (Timestamp timestamp, Timestamp maximum_delta_s, ValueType *value, Timestamp *timestamp_at_value_s) const
bool getOldestValue (ValueType *value, Timestamp *timestamp_of_value) const
bool getNewestValue (ValueType *value, Timestamp *timestamp_of_value) const
bool getOldestValue (ValueType *value) const
bool getNewestValue (ValueType *value) const
Timestamp getOldestTimestamp () const
Timestamp getNewestTimestamp () const
bool getValueAtOrBeforeTime (Timestamp timestamp_ns, Timestamp *timestamp_ns_of_value, ValueType *value) const
bool getValueAtOrAfterTime (Timestamp timestamp_ns, Timestamp *timestamp_ns_of_value, ValueType *value) const
template<typename ValueContainerType >
bool getValuesBetweenTimes (Timestamp timestamp_lower_s, Timestamp timestamp_higher_s, ValueContainerType *values, const bool get_lower_bound=false) const
void lockContainer () const
void unlockContainer () const
const BufferType & buffered_values () const
bool operator== (const ThreadsafeTemporalBuffer &other) const
Protected Member Functions
void removeOutdatedItems ()
bool getIteratorAtTimeOrEarlier (Timestamp timestamp, typename BufferType::const_iterator *it_lower_bound) const
Protected Attributes
BufferType values_
Timestamp buffer_length_seconds_
std::recursive_mutex mutex_
Detailed Description
template<typename ValueType, typename AllocatorType = std::allocator<std::pair<const Timestamp, ValueType> >>
class dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >
Definition at line 23 of file ThreadSafeTemporalBuffer.hpp.
Member Typedef Documentation
BufferType
template<typename ValueType , typename AllocatorType = std::allocator<std::pair<const Timestamp, ValueType> >> typedef std::map<Timestamp, ValueType, std::less<Timestamp>, AllocatorType> dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::BufferType
Definition at line 26 of file ThreadSafeTemporalBuffer.hpp.
This
template<typename ValueType , typename AllocatorType = std::allocator<std::pair<const Timestamp, ValueType> >> using dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::This = ThreadsafeTemporalBuffer<ValueType, AllocatorType>
Definition at line 27 of file ThreadSafeTemporalBuffer.hpp.
Type
template<typename ValueType , typename AllocatorType = std::allocator<std::pair<const Timestamp, ValueType> >> using dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::Type = ValueType
Definition at line 28 of file ThreadSafeTemporalBuffer.hpp.
Constructor & Destructor Documentation
ThreadsafeTemporalBuffer() [1/3]
template<typename ValueType , typename AllocatorType > dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::ThreadsafeTemporalBuffer
Definition at line 20 of file ThreadSafeTemporalBuffer-inl.hpp.
    : buffer_length_seconds_(-1) {}
ThreadsafeTemporalBuffer() [2/3]
template<typename ValueType , typename AllocatorType > dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::ThreadsafeTemporalBuffer (Timestamp buffer_length_seonds) explicit
Definition at line 24 of file ThreadSafeTemporalBuffer-inl.hpp.
    : buffer_length_seconds_(buffer_length_seconds) {}
ThreadsafeTemporalBuffer() [3/3]
template<typename ValueType , typename AllocatorType > dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::ThreadsafeTemporalBuffer (const ThreadsafeTemporalBuffer< ValueType, AllocatorType > & other)
Definition at line 29 of file ThreadSafeTemporalBuffer-inl.hpp.
{
  // Lock both mutexes without deadlock.
  std::lock(mutex_, other.mutex_);
  values_ = other.values_;
  buffer_length_seconds_ = other.buffer_length_seconds_;
  mutex_.unlock();
  other.mutex_.unlock();
}
References dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::buffer_length_seconds_, dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::mutex_, and dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::values_.
Member Function Documentation
addValue() [1/2]
template<typename ValueType , typename AllocatorType > void dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::addValue (const Timestamp timestamp, const ValueType & value, const bool emit_warning_on_value_overwrite)
Definition at line 72 of file ThreadSafeTemporalBuffer-inl.hpp.
{
  std::lock_guard<std::recursive_mutex> lock(mutex_);
  const bool value_overwritten = values_.emplace(timestamp, value).second;
  LOG_IF(WARNING, value_overwritten && emit_warning_on_value_overwrite)
      << "A value in temporal buffer at time " << timestamp
      << " already exists!";
  removeOutdatedItems();
}
addValue() [2/2]
template<typename ValueType , typename AllocatorType > void dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::addValue (Timestamp timestamp, const ValueType & value)
Definition at line 65 of file ThreadSafeTemporalBuffer-inl.hpp.
{
  constexpr bool kEmitWarningOnValueOverwrite = false;
  addValue(timestamp, value, kEmitWarningOnValueOverwrite);
}
Referenced by dyno::ThreadsafeImuBuffer::addMeasurement(), and dyno::ViodeAllLoader::syncFilePathsWithGroundTruth().
buffered_values()
template<typename ValueType , typename AllocatorType = std::allocator<std::pair<const Timestamp, ValueType> >> const BufferType & dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::buffered_values () const inline
Definition at line 144 of file ThreadSafeTemporalBuffer.hpp.
{ return values_; }
References dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::values_.
Referenced by dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::insert().
bufferLength()
template<typename ValueType , typename AllocatorType = std::allocator<std::pair<const Timestamp, ValueType> >> Timestamp dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::bufferLength () const inline
Definition at line 80 of file ThreadSafeTemporalBuffer.hpp.
{
    std::lock_guard<std::recursive_mutex> lock(mutex_);
    return buffer_length_seconds_;
  }
References dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::buffer_length_seconds_, and dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::mutex_.
clear()
template<typename ValueType , typename AllocatorType = std::allocator<std::pair<const Timestamp, ValueType> >> void dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::clear () inline
Definition at line 89 of file ThreadSafeTemporalBuffer.hpp.
               {
    std::lock_guard<std::recursive_mutex> lock(mutex_);
    values_.clear();
  }
References dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::mutex_, and dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::values_.
Referenced by dyno::ThreadsafeImuBuffer::clear().
deleteValueAtTime()
template<typename ValueType , typename AllocatorType > bool dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::deleteValueAtTime (Timestamp timestamp_ns)
Definition at line 84 of file ThreadSafeTemporalBuffer-inl.hpp.
{
  std::lock_guard<std::recursive_mutex> lock(mutex_);
  return values_.erase(timestamp_ns) > 0u;
}
empty()
template<typename ValueType , typename AllocatorType = std::allocator<std::pair<const Timestamp, ValueType> >> bool dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::empty () const inline
Definition at line 85 of file ThreadSafeTemporalBuffer.hpp.
{
    std::lock_guard<std::recursive_mutex> lock(mutex_);
    return values_.empty();
  }
References dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::mutex_, and dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::values_.
Referenced by dyno::ThreadsafeImuBuffer::isDataAvailableUpToImpl().
getIteratorAtTimeOrEarlier()
template<typename ValueType , typename AllocatorType > bool dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::getIteratorAtTimeOrEarlier (Timestamp timestamp, typename BufferType::const_iterator * it_lower_bound) const protected
Definition at line 230 of file ThreadSafeTemporalBuffer-inl.hpp.
{
  CHECK_NOTNULL(it_lower_bound);
  std::lock_guard<std::recursive_mutex> lock(mutex_);
  // Return false if no values in buffer.
  if (empty()) {
    return false;
  }
  // Returns first element with a time that compares not less to timestamp.
  *it_lower_bound = values_.lower_bound(timestamp);
  if (*it_lower_bound != values_.end() &&
      (*it_lower_bound)->first == timestamp) {
    // It's an exact match.
    return true;
  }
  return false;
}
getNearestValueToTime() [1/3]
template<typename ValueType , typename AllocatorType > bool dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::getNearestValueToTime (Timestamp timestamp, Timestamp maximum_delta_s, ValueType * value, Timestamp * timestamp_at_value_s) const
Definition at line 296 of file ThreadSafeTemporalBuffer-inl.hpp.
{
  CHECK_NOTNULL(timestamp_at_value_s);
  CHECK_NOTNULL(value);
  std::lock_guard<std::recursive_mutex> lock(mutex_);
  if (empty()) {
    return false;
  }
  const typename BufferType::const_iterator it_lower =
      values_.lower_bound(timestamp);
  // Verify if we got an exact match.
  if (it_lower != values_.end() && it_lower->first == timestamp) {
    *value = it_lower->second;
    *timestamp_at_value_s = it_lower->first;
    return true;
  }
  // No exact match found so we need to examine lower and upper
  // bound on the timestamp.
  const typename BufferType::const_iterator it_upper =
      values_.upper_bound(timestamp);
  // If the lower bound points out of the array, we have to return the last
  // element.
  if (it_lower == values_.end()) {
    typename BufferType::const_iterator it_last = std::prev(values_.end());
    Timestamp delta_ns = std::abs(it_last->first - timestamp);
    if (delta_ns <= maximum_delta_ns) {
      *value = it_last->second;
      *timestamp_at_value_s = it_last->first;
      return true;
    } else {
      return false;
    }
  }
  // If the lower bound points to begin() and no exact match was found, we
  // have to return the first element.
  if (it_lower == values_.begin()) {
    typename BufferType::const_iterator it_first = values_.begin();
    Timestamp delta_ns = std::abs(it_first->first - timestamp);
    if (delta_ns <= maximum_delta_ns) {
      *value = it_first->second;
      *timestamp_at_value_s = it_first->first;
      return true;
    } else {
      return false;
    }
  }
  // Both iterators are within range so need to find out which of them is
  // closer to the timestamp.
  typename BufferType::const_iterator it_before = std::prev(it_lower);
  Timestamp delta_before_ns = std::abs(it_before->first - timestamp);
  Timestamp delta_after_ns = std::abs(it_upper->first - timestamp);
  if (delta_before_ns < delta_after_ns) {
    if (delta_before_ns <= maximum_delta_ns) {
      *value = it_before->second;
      *timestamp_at_value_s = it_before->first;
      return true;
    }
  } else {
    if (delta_after_ns <= maximum_delta_ns) {
      *value = it_upper->second;
      *timestamp_at_value_s = it_upper->first;
      return true;
    }
  }
  return false;
}
getNearestValueToTime() [2/3]
template<typename ValueType , typename AllocatorType > bool dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::getNearestValueToTime (Timestamp timestamp_ns, Timestamp maximum_delta_s, ValueType * value) const
Definition at line 373 of file ThreadSafeTemporalBuffer-inl.hpp.
{
  Timestamp timestamp_at_value_s;
  return getNearestValueToTime(timestamp, maximum_delta_ns, value,
                               &timestamp_at_value_s);
}
getNearestValueToTime() [3/3]
template<typename ValueType , typename AllocatorType > bool dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::getNearestValueToTime (Timestamp timestamp_ns, ValueType * value) const
Definition at line 167 of file ThreadSafeTemporalBuffer-inl.hpp.
{
  CHECK_NOTNULL(value);
  return getNearestValueToTime(timestamp, std::numeric_limits<Timestamp>::max(),
                               value);
}
Referenced by dyno::ViodeAllLoader::syncFilePathsWithGroundTruth().
getNewestTimestamp()
template<typename ValueType , typename AllocatorType > Timestamp dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::getNewestTimestamp
Definition at line 145 of file ThreadSafeTemporalBuffer-inl.hpp.
{
  ValueType value;
  Timestamp t;
  CHECK(getNewestValue(&value, &t));
  (void)value;
  return t;
}
getNewestValue() [1/2]
template<typename ValueType , typename AllocatorType > bool dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::getNewestValue (ValueType * value) const
Definition at line 127 of file ThreadSafeTemporalBuffer-inl.hpp.
{
  Timestamp t;
  return getNewestValue(value, &t);
}
getNewestValue() [2/2]
template<typename ValueType , typename AllocatorType > bool dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::getNewestValue (ValueType * value, Timestamp * timestamp_of_value) const
Definition at line 106 of file ThreadSafeTemporalBuffer-inl.hpp.
{
  CHECK_NOTNULL(value);
  CHECK_NOTNULL(timestamp_of_value);
  std::lock_guard<std::recursive_mutex> lock(mutex_);
  if (empty()) {
    return false;
  }
  *value = values_.rbegin()->second;
  *timestamp_of_value = values_.rbegin()->first;
  return true;
}
Referenced by dyno::ThreadsafeImuBuffer::addMeasurement(), and dyno::ThreadsafeImuBuffer::isDataAvailableUpToImpl().
getOldestTimestamp()
template<typename ValueType , typename AllocatorType > Timestamp dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::getOldestTimestamp
Definition at line 135 of file ThreadSafeTemporalBuffer-inl.hpp.
{
  ValueType value;
  Timestamp t;
  CHECK(getOldestValue(&value, &t));
  (void)value;
  return t;
}
getOldestValue() [1/2]
template<typename ValueType , typename AllocatorType > bool dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::getOldestValue (ValueType * value) const
Definition at line 120 of file ThreadSafeTemporalBuffer-inl.hpp.
{
  Timestamp t;
  return getOldestValue(value, &t);
}
getOldestValue() [2/2]
template<typename ValueType , typename AllocatorType > bool dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::getOldestValue (ValueType * value, Timestamp * timestamp_of_value) const
Definition at line 91 of file ThreadSafeTemporalBuffer-inl.hpp.
{
  CHECK_NOTNULL(value);
  CHECK_NOTNULL(timestamp_of_value);
  std::lock_guard<std::recursive_mutex> lock(mutex_);
  if (empty()) {
    return false;
  }
  *value = values_.begin()->second;
  *timestamp_of_value = values_.begin()->first;
  return true;
}
Referenced by dyno::ThreadsafeImuBuffer::isDataAvailableUpToImpl().
getValueAtOrAfterTime()
template<typename ValueType , typename AllocatorType > bool dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::getValueAtOrAfterTime (Timestamp timestamp_ns, Timestamp * timestamp_ns_of_value, ValueType * value) const
Definition at line 204 of file ThreadSafeTemporalBuffer-inl.hpp.
{
  CHECK_NOTNULL(timestamp_of_value);
  CHECK_NOTNULL(value);
  std::lock_guard<std::recursive_mutex> lock(mutex_);
  typename BufferType::const_iterator it_lower_bound;
  bool has_exact_match = getIteratorAtTimeOrEarlier(timestamp, &it_lower_bound);
  if (!has_exact_match) {
    // has_exact_match could be also false if the buffer is empty, check that.
    // Which would make it_lower_bound a nullptr, and raise an excetption when
    // being dereferenced later.
    if (empty() || it_lower_bound == values_.end()) {
      return false;
    }
  }
  *timestamp_of_value = it_lower_bound->first;
  *value = it_lower_bound->second;
  CHECK_GE(*timestamp_of_value, timestamp);
  return true;
}
Referenced by dyno::ThreadsafeImuBuffer::interpolateValueAtTimestamp().
getValueAtOrBeforeTime()
template<typename ValueType , typename AllocatorType > bool dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::getValueAtOrBeforeTime (Timestamp timestamp_ns, Timestamp * timestamp_ns_of_value, ValueType * value) const
Definition at line 175 of file ThreadSafeTemporalBuffer-inl.hpp.
{
  CHECK_NOTNULL(timestamp_of_value);
  CHECK_NOTNULL(value);
  std::lock_guard<std::recursive_mutex> lock(mutex_);
  typename BufferType::const_iterator it_lower_bound;
  const bool has_exact_match =
      getIteratorAtTimeOrEarlier(timestamp, &it_lower_bound);
  if (!has_exact_match) {
    // has_exact_match could be also false if the buffer is empty, check that.
    // Which would make it_lower_bound a nullptr, and raise an excetption when
    // being dereferenced later.
    if (empty() || it_lower_bound == values_.begin()) {
      return false;
    }
    --it_lower_bound;
  }
  *timestamp_of_value = it_lower_bound->first;
  *value = it_lower_bound->second;
  CHECK_LE(*timestamp_of_value, timestamp);
  return true;
}
Referenced by dyno::ThreadsafeImuBuffer::interpolateValueAtTimestamp().
getValueAtTime()
template<typename ValueType , typename AllocatorType > bool dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::getValueAtTime (Timestamp timestamp_ns, ValueType * value) const
Definition at line 154 of file ThreadSafeTemporalBuffer-inl.hpp.
{
  CHECK_NOTNULL(value);
  std::lock_guard<std::recursive_mutex> lock(mutex_);
  typename BufferType::const_iterator it = values_.find(timestamp);
  if (it != values_.end()) {
    *value = it->second;
    return true;
  }
  return false;
}
getValuesBetweenTimes()
template<typename ValueType , typename AllocatorType > template<typename ValueContainerType > bool dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::getValuesBetweenTimes (Timestamp timestamp_lower_s, Timestamp timestamp_higher_s, ValueContainerType * values, const bool get_lower_bound = false) const
Definition at line 255 of file ThreadSafeTemporalBuffer-inl.hpp.
{
  CHECK_NOTNULL(values)->clear();
  CHECK_GT(timestamp_higher_s, timestamp_lower_s);
  std::lock_guard<std::recursive_mutex> lock(mutex_);
  // Early exit if there are too few items.
  if (empty()) {
    return false;
  }
  const Timestamp oldest_timestamp = values_.begin()->first;
  const Timestamp latest_timestamp = values_.rbegin()->first;
  // TODO I don't see why only 100% overlapping query intervals are accepted.
  // Shouldn't it be oldest > higher || latest < lower ?
  // Or at least accept as well when timestamp_lower_s is smaller than
  // oldest_timestamp, such that we only return false if we are asking for
  // future msgs?
  if (oldest_timestamp > timestamp_lower_s ||
      timestamp_higher_s > latest_timestamp) {
    return false;
  }
  typename BufferType::const_iterator it =
      values_.lower_bound(timestamp_lower_s);
  for (; it != values_.end() && it->first < timestamp_higher_s; ++it) {
    CHECK(it != values_.end());
    // lower_bound includes the border so we need to skip them when there are
    // perfect matches, except if the user explicitly asked for it.
    if (it->first == timestamp_lower_s && !get_lower_bound) {
      continue;
    }
    values->emplace_back(it->second);
  }
  return true;
}
Referenced by dyno::ThreadsafeImuBuffer::getImuDataBtwTimestamps().
insert()
template<typename ValueType , typename AllocatorType > void dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::insert (const ThreadsafeTemporalBuffer< ValueType, AllocatorType > & other)
Definition at line 402 of file ThreadSafeTemporalBuffer-inl.hpp.
{
  values_.insert(other.buffered_values().begin(),
                 other.buffered_values().end());
}
References dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::buffered_values().
lockContainer()
template<typename ValueType , typename AllocatorType = std::allocator<std::pair<const Timestamp, ValueType> >> void dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::lockContainer () const inline
Definition at line 138 of file ThreadSafeTemporalBuffer.hpp.
{ mutex_.lock(); }
References dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::mutex_.
operator=()
template<typename ValueType , typename AllocatorType > ThreadsafeTemporalBuffer< ValueType, AllocatorType > & dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::operator= (const ThreadsafeTemporalBuffer< ValueType, AllocatorType > & other)
Definition at line 43 of file ThreadSafeTemporalBuffer-inl.hpp.
{
  // Guard self assignment
  if (this == &other) return *this;
  // Lock both mutexes without deadlock.
  std::lock(mutex_, other.mutex_);
  // if the values contained are pointers this will not transfter ownship of the
  // pointers and the lvalued buffer will not share a mutex with the rvalued
  // buffer. Hence, the values could be modofied by two different queues in a
  // non thread safe manner the user should have to manage this. This is the
  // same problem as in the custom copy constructor
  this->values_ = other.values_;
  this->buffer_length_seconds_ = other.buffer_length_seconds_;
  mutex_.unlock();
  other.mutex_.unlock();
  return *this;
}
References dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::buffer_length_seconds_, dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::mutex_, and dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::values_.
operator==()
template<typename ValueType , typename AllocatorType = std::allocator<std::pair<const Timestamp, ValueType> >> bool dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::operator== (const ThreadsafeTemporalBuffer< ValueType, AllocatorType > & other) const inline
Definition at line 146 of file ThreadSafeTemporalBuffer.hpp.
{
    return values_ == other.values_ &&
           buffer_length_seconds_ == other.buffer_length_seconds_;
  }
References dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::buffer_length_seconds_, and dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::values_.
removeOutdatedItems()
template<typename ValueType , typename AllocatorType > void dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::removeOutdatedItems protected
Definition at line 381 of file ThreadSafeTemporalBuffer-inl.hpp.
{
  std::lock_guard<std::recursive_mutex> lock(mutex_);
  if (empty() || buffer_length_seconds_ <= 0) {
    return;
  }
  const Timestamp newest_timestamp_s = values_.rbegin()->first;
  const Timestamp buffer_threshold_s =
      newest_timestamp_s - buffer_length_seconds_;
  if (values_.begin()->first < buffer_threshold_s) {
    typename BufferType::const_iterator it =
        values_.lower_bound(buffer_threshold_s);
    CHECK(it != values_.end());
    CHECK(it != values_.begin());
    values_.erase(values_.begin(), it);
  }
}
size()
template<typename ValueType , typename AllocatorType = std::allocator<std::pair<const Timestamp, ValueType> >> size_t dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::size () const inline
Definition at line 75 of file ThreadSafeTemporalBuffer.hpp.
{
    std::lock_guard<std::recursive_mutex> lock(mutex_);
    return values_.size();
  }
References dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::mutex_, and dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::values_.
Referenced by dyno::ThreadsafeImuBuffer::size().
unlockContainer()
template<typename ValueType , typename AllocatorType = std::allocator<std::pair<const Timestamp, ValueType> >> void dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::unlockContainer () const inline
Definition at line 139 of file ThreadSafeTemporalBuffer.hpp.
{ mutex_.unlock(); }
References dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::mutex_.
Member Data Documentation
buffer_length_seconds_
template<typename ValueType , typename AllocatorType = std::allocator<std::pair<const Timestamp, ValueType> >> Timestamp dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::buffer_length_seconds_ protected
Definition at line 160 of file ThreadSafeTemporalBuffer.hpp.
Referenced by dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::bufferLength(), dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::operator=(), dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::operator==(), and dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::ThreadsafeTemporalBuffer().
mutex_
template<typename ValueType , typename AllocatorType = std::allocator<std::pair<const Timestamp, ValueType> >> std::recursive_mutex dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::mutex_ mutable protected
Definition at line 161 of file ThreadSafeTemporalBuffer.hpp.
Referenced by dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::bufferLength(), dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::clear(), dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::empty(), dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::lockContainer(), dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::operator=(), dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::size(), dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::ThreadsafeTemporalBuffer(), and dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::unlockContainer().
values_
template<typename ValueType , typename AllocatorType = std::allocator<std::pair<const Timestamp, ValueType> >> BufferType dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::values_ protected
Definition at line 159 of file ThreadSafeTemporalBuffer.hpp.
Referenced by dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::buffered_values(), dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::clear(), dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::empty(), dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::operator=(), dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::operator==(), dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::size(), and dyno::ThreadsafeTemporalBuffer< ValueType, AllocatorType >::ThreadsafeTemporalBuffer().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/pipeline/ThreadSafeTemporalBuffer.hpp
dynosam/include/dynosam/pipeline/ThreadSafeTemporalBuffer-inl.hpp