DynoSAM: dyno::OccupandyGrid2D Class Reference
dyno::OccupandyGrid2D Class Reference
#include <OccupancyGrid2D.hpp>
Public Types
using Grid = std::vector< bool >
using FeatureGrid = Keypoints
Public Member Functions
OccupandyGrid2D (int cell_size, int n_cols, int n_rows)
OccupandyGrid2D (const OccupandyGrid2D &rhs)
~OccupandyGrid2D ()=default
void reset ()
size_t size ()
bool empty ()
bool isOccupied (const size_t cell_index)
void setOccupied (const size_t cell_index)
int numOccupied () const
template<typename Derived >
size_t getCellIndex (const Eigen::MatrixBase< Derived > &px) const
size_t getCellIndex (int x, int y, int scale=1) const
void fillWithKeypoints (const Keypoints &keypoints)
Static Public Member Functions
static int getNCell (const int n_pixels, const int size)
Public Attributes
const int cell_size
const int n_cols
const int n_rows
Grid occupancy_
FeatureGrid feature_occupancy_
Detailed Description
We divide the image into a grid of cells and try to find maximally one feature per cell. This is to ensure good distribution of features in the image. https://github.com/uzh-rpg/rpg_svo_pro_open/blob/master/svo_common/include/svo/common/occupancy_grid_2d.h
Definition at line 35 of file OccupancyGrid2D.hpp.
Member Typedef Documentation
FeatureGrid
using dyno::OccupandyGrid2D::FeatureGrid = Keypoints
Definition at line 39 of file OccupancyGrid2D.hpp.
Grid
using dyno::OccupandyGrid2D::Grid = std::vector<bool>
Definition at line 38 of file OccupancyGrid2D.hpp.
Constructor & Destructor Documentation
OccupandyGrid2D() [1/2]
dyno::OccupandyGrid2D::OccupandyGrid2D (int cell_size, int n_cols, int n_rows) inline
Definition at line 41 of file OccupancyGrid2D.hpp.
    : cell_size(cell_size)
    , n_cols(n_cols)
    , n_rows(n_rows)
    , occupancy_(n_cols * n_rows, false)
    , feature_occupancy_(n_cols * n_rows, Keypoint(0, 0))
  {
  }
OccupandyGrid2D() [2/2]
dyno::OccupandyGrid2D::OccupandyGrid2D (const OccupandyGrid2D & rhs) inline
Definition at line 50 of file OccupancyGrid2D.hpp.
    : cell_size(rhs.cell_size)
    , n_cols(rhs.n_cols)
    , n_rows(rhs.n_rows)
    , occupancy_(rhs.occupancy_)
    , feature_occupancy_(rhs.feature_occupancy_)
  {
  }
~OccupandyGrid2D()
dyno::OccupandyGrid2D::~OccupandyGrid2D () default
Member Function Documentation
empty()
bool dyno::OccupandyGrid2D::empty () inline
Definition at line 84 of file OccupancyGrid2D.hpp.
  {
    return occupancy_.empty();
  }
References occupancy_.
fillWithKeypoints()
void dyno::OccupandyGrid2D::fillWithKeypoints (const Keypoints & keypoints) inline
Definition at line 122 of file OccupancyGrid2D.hpp.
  {
    // TODO(cfo): could be implemented using block operations.
    for (size_t i = 0; i < keypoints.size(); ++i)
    {
      const Keypoint& keypoint = keypoints.at(i);
      const int int_x = static_cast<int>(keypoint(0));
      const int int_y = static_cast<int>(keypoint(1));
      const size_t idx = getCellIndex(int_x, int_y, 1);
      occupancy_.at(idx) = true;
      feature_occupancy_.at(idx) = Keypoint(keypoint(0), keypoint(1));
    }
  }
References feature_occupancy_, getCellIndex(), and occupancy_.
getCellIndex() [1/2]
template<typename Derived > size_t dyno::OccupandyGrid2D::getCellIndex (const Eigen::MatrixBase< Derived > & px) const inline
Definition at line 107 of file OccupancyGrid2D.hpp.
  {
    EIGEN_STATIC_ASSERT_MATRIX_SPECIFIC_SIZE(Derived, 2, 1);
    return std::floor(px(1) / cell_size) * n_cols + std::floor(px(0) / cell_size);
//    return static_cast<size_t>((px(1)) / cell_size * n_cols +
//                               (px(0)) / cell_size);
  }
References cell_size, and n_cols.
Referenced by fillWithKeypoints(), getCellIndex(), dyno::FeatureTracker::trackDynamic(), and dyno::ExternalFlowFeatureTracker::trackStatic().
getCellIndex() [2/2]
size_t dyno::OccupandyGrid2D::getCellIndex (int x, int y, int scale = 1) const inline
Definition at line 115 of file OccupancyGrid2D.hpp.
  {
    return getCellIndex(Eigen::Vector2d(scale * x, scale * y));
//    return static_cast<size_t>((scale * y) / cell_size * n_cols +
//                               (scale * x) / cell_size);
  }
References getCellIndex().
getNCell()
static int dyno::OccupandyGrid2D::getNCell (const int n_pixels, const int size) inline static
Definition at line 61 of file OccupancyGrid2D.hpp.
  {
    return std::ceil(static_cast<double>(n_pixels)
                      / static_cast<double>(size));
  }
References size().
isOccupied()
bool dyno::OccupandyGrid2D::isOccupied (const size_t cell_index) inline
Definition at line 89 of file OccupancyGrid2D.hpp.
  {
    CHECK_LT(cell_index, occupancy_.size());
    return occupancy_[cell_index];
  }
References occupancy_.
Referenced by dyno::FeatureTracker::trackDynamic(), and dyno::ExternalFlowFeatureTracker::trackStatic().
numOccupied()
int dyno::OccupandyGrid2D::numOccupied () const inline
Definition at line 101 of file OccupancyGrid2D.hpp.
  {
    return std::count(occupancy_.begin(), occupancy_.end(), true);
  }
References occupancy_.
reset()
void dyno::OccupandyGrid2D::reset () inline
Definition at line 74 of file OccupancyGrid2D.hpp.
  {
    std::fill(occupancy_.begin(), occupancy_.end(), false);
  }
References occupancy_.
Referenced by dyno::ExternalFlowFeatureTracker::trackStatic().
setOccupied()
void dyno::OccupandyGrid2D::setOccupied (const size_t cell_index) inline
Definition at line 95 of file OccupancyGrid2D.hpp.
  {
    CHECK_LT(cell_index, occupancy_.size());
    occupancy_[cell_index] = true;
  }
References occupancy_.
size()
size_t dyno::OccupandyGrid2D::size () inline
Definition at line 79 of file OccupancyGrid2D.hpp.
  {
    return occupancy_.size();
  }
References occupancy_.
Referenced by getNCell().
Member Data Documentation
cell_size
const int dyno::OccupandyGrid2D::cell_size
Definition at line 68 of file OccupancyGrid2D.hpp.
Referenced by getCellIndex().
feature_occupancy_
FeatureGrid dyno::OccupandyGrid2D::feature_occupancy_
Definition at line 72 of file OccupancyGrid2D.hpp.
Referenced by fillWithKeypoints().
n_cols
const int dyno::OccupandyGrid2D::n_cols
Definition at line 69 of file OccupancyGrid2D.hpp.
Referenced by getCellIndex().
n_rows
const int dyno::OccupandyGrid2D::n_rows
Definition at line 70 of file OccupancyGrid2D.hpp.
occupancy_
Grid dyno::OccupandyGrid2D::occupancy_
Definition at line 71 of file OccupancyGrid2D.hpp.
Referenced by empty(), fillWithKeypoints(), isOccupied(), numOccupied(), reset(), setOccupied(), size(), dyno::FeatureTracker::trackDynamic(), and dyno::ExternalFlowFeatureTracker::trackStatic().
The documentation for this class was generated from the following file:
dynosam/include/dynosam/frontend/vision/OccupancyGrid2D.hpp