DynoSAM: dyno::OpticalFlowAndPoseOptimizer Class Reference
dyno::OpticalFlowAndPoseOptimizer Class Reference
Joinly refines optical flow with with the given pose using the error term: e = [u,v]_{k_1} + f_{k-1, k} - \pi(X^{-1} \: m_k) where f is flow, [u,v]_{k-1} is the observed keypoint at k-1, X is the pose and m_k is the back-projected keypoint at k.
#include <MotionSolver.hpp>
Classes
struct Params
struct ResultType
Public Types
using Result = SolverResult< ResultType >
Public Member Functions
OpticalFlowAndPoseOptimizer (const Params &params)
template<typename CALIBRATION >
Result optimize (const Frame::Ptr frame_k_1, const Frame::Ptr frame_k, const TrackletIds &tracklets, const gtsam::Pose3 &initial_pose) const
Builds the factor-graph problem using the set of specificed correspondences (tracklets) in frame k-1 and k and the initial pose.
template<typename CALIBRATION >
Result optimizeAndUpdate (Frame::Ptr frame_k_1, Frame::Ptr frame_k, const TrackletIds &tracklets, const gtsam::Pose3 &initial_pose) const
Builds the factor-graph problem using the set of specificed correspondences (tracklets) in frame k-1 and k and the initial pose. Unlike the optimize only version this also update the features within the frames as outliers after optimisation. It will also update the feature data (depth keypoint etc...) with the refined flows.
Private Member Functions
void updateFrameOutliersWithResult (const Result &result, Frame::Ptr frame_k_1, Frame::Ptr frame_k) const
Private Attributes
Params params_
Detailed Description
Joinly refines optical flow with with the given pose using the error term: e = [u,v]_{k_1} + f_{k-1, k} - \pi(X^{-1} \: m_k) where f is flow, [u,v]_{k-1} is the observed keypoint at k-1, X is the pose and m_k is the back-projected keypoint at k.
The parsed tracklets are the set of correspondances with which to build the optimisation problem and the refined inliers will be a subset of these tracklets. THe number of refined flows should be the number of refined inliers and be a 1-to-1 match
Definition at line 130 of file MotionSolver.hpp.
Member Typedef Documentation
Result
using dyno::OpticalFlowAndPoseOptimizer::Result = SolverResult<ResultType>
Definition at line 149 of file MotionSolver.hpp.
Constructor & Destructor Documentation
OpticalFlowAndPoseOptimizer()
dyno::OpticalFlowAndPoseOptimizer::OpticalFlowAndPoseOptimizer (const Params & params) inline
Definition at line 151 of file MotionSolver.hpp.
: params_(params) {}
Member Function Documentation
optimize()
template<typename CALIBRATION > OpticalFlowAndPoseOptimizer::Result dyno::OpticalFlowAndPoseOptimizer::optimize (const Frame::Ptr frame_k_1, const Frame::Ptr frame_k, const TrackletIds & tracklets, const gtsam::Pose3 & initial_pose) const
Builds the factor-graph problem using the set of specificed correspondences (tracklets) in frame k-1 and k and the initial pose.
The optimisation joinly refines optical flow with with the given pose using the error term: e = [u,v]_{k_1} + f_{k-1, k} - \pi(X^{-1} \: m_k) where f is flow, [u,v]_{k-1} is the observed keypoint at k-1, X is the pose and m_k is the back-projected keypoint at k.
The parsed tracklets are the set of correspondances with which to build the optimisation problem and the refined inliers will be a subset of these tracklets. THe number of refined flows should be the number of refined inliers and be a 1-to-1 match
This is agnostic to if the problem is solving for a motion or a pose so the user must make sure the initial pose is in the right form.
Template Parameters
CALIBRATION
Parameters
frame_k_1
frame_k
tracklets
initial_pose
Returns
Result
Definition at line 90 of file MotionSolver-inl.hpp.
{
  utils::TimingStatsCollector timer("of_motion_solver.optimize");
  using Calibration = CALIBRATION;
  using Pose3FlowProjectionFactorCalib = Pose3FlowProjectionFactor<Calibration>;
  gtsam::NonlinearFactorGraph graph;
  gtsam::Values values;
  gtsam::SharedNoiseModel flow_noise =
      gtsam::noiseModel::Isotropic::Sigma(2u, params_.flow_sigma);
  gtsam::SharedNoiseModel flow_prior_noise =
      gtsam::noiseModel::Isotropic::Sigma(2u, params_.flow_prior_sigma);
  // robust noise model!
  flow_noise = gtsam::noiseModel::Robust::Create(
      gtsam::noiseModel::mEstimator::Huber::Create(params_.k_huber),
      flow_noise);
  const gtsam::Pose3 T_world_k_1 = frame_k_1->getPose();
  const gtsam::Symbol pose_key('X', 0);
  gtsam::Ordering ordering;
  // lambda to construct gtsam symbol from a tracklet
  auto flowSymbol = [](TrackletId tracklet) -> gtsam::Symbol {
    return gtsam::symbol_shorthand::F(static_cast<uint64_t>(tracklet));
  };
  auto gtsam_calibration = boost::make_shared<Calibration>(
      frame_k_1->getFrameCamera().calibration());
  // sanity check to ensure all tracklets are on the same object
  std::unordered_set<ObjectId> object_id;
  for (TrackletId tracklet_id : tracklets) {
    Feature::Ptr feature_k_1 = frame_k_1->at(tracklet_id);
    Feature::Ptr feature_k = frame_k->at(tracklet_id);
    object_id.insert(feature_k_1->objectId());
    object_id.insert(feature_k->objectId());
    CHECK_NOTNULL(feature_k_1);
    CHECK_NOTNULL(feature_k);
    CHECK(feature_k_1->hasDepth());
    CHECK(feature_k->hasDepth())
        << " with object id " << feature_k->objectId() << " and is valid "
        << feature_k->usable() << " and age " << feature_k->age()
        << " previous age " << feature_k_1->age() << " kp "
        << feature_k->keypoint();
    const Keypoint kp_k_1 = feature_k_1->keypoint();
    const Depth depth_k_1 = feature_k_1->depth();
    const gtsam::Point2 flow = feature_k_1->measuredFlow();
    CHECK(gtsam::equal(kp_k_1 + flow, feature_k->keypoint()))
        << gtsam::Point2(kp_k_1 + flow) << " " << feature_k->keypoint()
        << " object id " << feature_k->objectId() << " flow " << flow;
    gtsam::Symbol flow_symbol(flowSymbol(tracklet_id));
    auto flow_factor = boost::make_shared<Pose3FlowProjectionFactorCalib>(
        flow_symbol, pose_key, kp_k_1, depth_k_1, T_world_k_1,
        *gtsam_calibration, flow_noise);
    graph.add(flow_factor);
    // add prior factor on each flow
    graph.addPrior<gtsam::Point2>(flow_symbol, flow, flow_prior_noise);
    values.insert(flow_symbol, flow);
    ordering += flow_symbol;
  }
  // pose at frame k
  // put pose last and use custom ordering!
  values.insert(pose_key, initial_pose);
  ordering += pose_key;
  // check we only have one label
  CHECK_EQ(object_id.size(), 1u);
  Result result;
  result.best_result.object_id = *object_id.begin();
  // double error_before = graph.error(values);
  std::vector<double> post_errors;
  std::unordered_set<gtsam::Key> outlier_flows;
  // graph we will mutate by removing outlier factors
  gtsam::NonlinearFactorGraph mutable_graph = graph;
  gtsam::Values optimised_values = values;
  // number of all variables
  utils::StatsCollector("of_motion_solver.joint_of_pose_num_vars_all")
      .AddSample(optimised_values.size());
  gtsam::LevenbergMarquardtParams opt_params;
  // for speed
  opt_params.setMaxIterations(10);
  // this is basically a set of prior looking factors on a pose so we know we
  // need to eliminate the pose last to avoid fill in therefore we use our own
  // custom ordering that has the pose last
  // opt_params.setOrdering(ordering);
  if (VLOG_IS_ON(200))
    opt_params.verbosity = gtsam::NonlinearOptimizerParams::Verbosity::ERROR;
  {
    utils::TimingStatsCollector timer("of_motion_solver.LM_solve");
    optimised_values = gtsam::LevenbergMarquardtOptimizer(
                           mutable_graph, optimised_values, opt_params)
                           .optimize();
  }
  // double error_after = mutable_graph.error(optimised_values);
  // post_errors.push_back(error_after);
  gtsam::FactorIndices outlier_factors;
  // if we have outliers, enter iteration loop
  if (params_.outlier_reject) {
    utils::TimingStatsCollector timer("of_motion_solver.outlier_reject");
    outlier_factors = factor_graph_tools::determineFactorOutliers<
        Pose3FlowProjectionFactorCalib>(mutable_graph, optimised_values);
    if (outlier_factors.size() > 0) {
      for (size_t itr = 0; itr < 4; itr++) {
        // currently removing factors from graph makes them nullptr
        gtsam::NonlinearFactorGraph mutable_graph_with_null = mutable_graph;
        for (auto outlier_idx : outlier_factors) {
          auto factor = mutable_graph_with_null.at(outlier_idx);
          gtsam::Symbol flow_symbol = factor->keys()[0];
          CHECK_EQ(flow_symbol.chr(), 'f');
          outlier_flows.insert(flow_symbol.key());
          mutable_graph_with_null.remove(outlier_idx);
        }
        // now iterate over graph and add factors that are not null to ensure
        // all factors are ok
        mutable_graph.resize(0);
        for (size_t i = 0; i < mutable_graph_with_null.size(); i++) {
          auto factor = mutable_graph_with_null.at(i);
          if (factor) {
            mutable_graph.add(factor);
          }
        }
        optimised_values.update(pose_key, initial_pose);
        // do we use values or optimised values here?
        optimised_values = gtsam::LevenbergMarquardtOptimizer(
                               mutable_graph, optimised_values, opt_params)
                               .optimize();
        // error_after = mutable_graph.error(optimised_values);
        // post_errors.push_back(error_after);
        outlier_factors = factor_graph_tools::determineFactorOutliers<
            Pose3FlowProjectionFactorCalib>(mutable_graph, optimised_values);
        if (outlier_factors.size() == 0) {
          break;
        }
      }
    }
  }
  // size_t initial_size = graph.size();
  // size_t inlier_size = mutable_graph.size();
  // error_after = mutable_graph.error(optimised_values);
  // recover values
  result.best_result.refined_pose = optimised_values.at<gtsam::Pose3>(pose_key);
  // result.error_before = error_before;
  // result.error_after = error_after;
  // for each outlier edge, update the set of inliers
  for (TrackletId tracklet_id : tracklets) {
    const gtsam::Symbol flow_sym = flowSymbol(tracklet_id);
    const gtsam::Key flow_key = flow_sym.key();
    if (outlier_flows.find(flow_key) != outlier_flows.end()) {
      // still need to update the result as this is used to actually update the
      // outlier tracklets in the updateFrameOutliersWithResult
      result.outliers.push_back(tracklet_id);
    } else {
      gtsam::Point2 refined_flow = optimised_values.at<gtsam::Point2>(flow_sym);
      result.best_result.refined_flows.push_back(refined_flow);
      result.inliers.push_back(tracklet_id);
    }
  }
  // number of variables after outlier removal
  utils::StatsCollector("of_motion_solver.joint_of_pose_num_vars_inliers")
      .AddSample(result.inliers.size());
  CHECK_EQ(tracklets.size(), result.inliers.size() + result.outliers.size());
  return result;
}
References dyno::utils::StatsCollectorImpl::AddSample(), dyno::SolverResult< T >::best_result, dyno::factor_graph_tools::determineFactorOutliers(), dyno::OpticalFlowAndPoseOptimizer::Params::flow_prior_sigma, dyno::OpticalFlowAndPoseOptimizer::Params::flow_sigma, dyno::SolverResult< T >::inliers, dyno::OpticalFlowAndPoseOptimizer::Params::k_huber, dyno::OpticalFlowAndPoseOptimizer::Params::outlier_reject, dyno::SolverResult< T >::outliers, and params_.
optimizeAndUpdate()
template<typename CALIBRATION > OpticalFlowAndPoseOptimizer::Result dyno::OpticalFlowAndPoseOptimizer::optimizeAndUpdate (Frame::Ptr frame_k_1, Frame::Ptr frame_k, const TrackletIds & tracklets, const gtsam::Pose3 & initial_pose) const
Builds the factor-graph problem using the set of specificed correspondences (tracklets) in frame k-1 and k and the initial pose. Unlike the optimize only version this also update the features within the frames as outliers after optimisation. It will also update the feature data (depth keypoint etc...) with the refined flows.
It will NOT update the frame with the result pose as this could be any pose.
Template Parameters
CALIBRATION
Parameters
frame_k_1
frame_k
tracklets
initial_pose
Returns
Result
Definition at line 286 of file MotionSolver-inl.hpp.
{
  auto result =
      this->optimize<CALIBRATION>(frame_k_1, frame_k, tracklets, initial_pose);
  updateFrameOutliersWithResult(result, frame_k_1, frame_k);
  return result;
}
References updateFrameOutliersWithResult().
Referenced by dyno::ObjectMotionSovlerF2F::geometricOutlierRejection3d2d(), and dyno::RGBDInstanceFrontendModule::solveCameraMotion().
updateFrameOutliersWithResult()
void dyno::OpticalFlowAndPoseOptimizer::updateFrameOutliersWithResult (const Result & result, Frame::Ptr frame_k_1, Frame::Ptr frame_k) const private
Definition at line 301 of file MotionSolver.cc.
{
  utils::TimingStatsCollector timer("of_motion_solver.update_frame");
  // //original flow image that goes from k to k+1 (gross, im sorry!)
  // TODO: use flow_is_future param
  const cv::Mat& flow_image = frame_k->image_container_.opticalFlow();
  const cv::Mat& motion_mask = frame_k->image_container_.objectMotionMask();
  auto camera = frame_k->camera_;
  const auto& refined_inliers = result.inliers;
  const auto& refined_flows = result.best_result.refined_flows;
  // outliers from the result. We will update this vector with new outliers
  auto refined_outliers = result.outliers;
  for (size_t i = 0; i < refined_inliers.size(); i++) {
    TrackletId tracklet_id = refined_inliers.at(i);
    gtsam::Point2 refined_flow = refined_flows.at(i);
    const Feature::Ptr feature_k_1 = frame_k_1->at(tracklet_id);
    Feature::Ptr feature_k = frame_k->at(tracklet_id);
    CHECK_EQ(feature_k->objectId(), result.best_result.object_id);
    const Keypoint kp_k_1 = feature_k_1->keypoint();
    Keypoint refined_keypoint = kp_k_1 + refined_flow;
    // check boundaries?
    if (!camera->isKeypointContained(refined_keypoint)) {
      refined_outliers.push_back(tracklet_id);
      continue;
    }
    ObjectId predicted_label =
        functional_keypoint::at<ObjectId>(refined_keypoint, motion_mask);
    if (predicted_label != result.best_result.object_id) {
      refined_outliers.push_back(tracklet_id);
      // TODO: other fields of the feature does not get updated? Inconsistencies
      // as measured flow, predicted kp etc are no longer correct!!?
      continue;
    }
    // we now have to update the prediced keypoint using the original flow!!
    // TODO: code copied from feature tracker
    const int x = functional_keypoint::u(refined_keypoint);
    const int y = functional_keypoint::v(refined_keypoint);
    double flow_xe = static_cast<double>(flow_image.at<cv::Vec2f>(y, x)[0]);
    double flow_ye = static_cast<double>(flow_image.at<cv::Vec2f>(y, x)[1]);
    // the measured flow after the origin has been updated
    OpticalFlow new_measured_flow(flow_xe, flow_ye);
    feature_k->measuredFlow(new_measured_flow);
    // TODO: check predicted flow is within image
    Keypoint predicted_kp = Feature::CalculatePredictedKeypoint(
        refined_keypoint, new_measured_flow);
    feature_k->predictedKeypoint(predicted_kp);
    feature_k->keypoint(refined_keypoint);
  }
  // update tracks
  for (const auto& outlier_tracklet : refined_outliers) {
    Feature::Ptr feature_k_1 = frame_k_1->at(outlier_tracklet);
    Feature::Ptr feature_k = frame_k->at(outlier_tracklet);
    CHECK(feature_k_1->usable());
    CHECK(feature_k->usable());
    feature_k->markOutlier();
    feature_k_1->markOutlier();
  }
  // refresh depth information for each frame
  CHECK(frame_k->updateDepths());
}
References dyno::SolverResult< T >::best_result, dyno::Feature::CalculatePredictedKeypoint(), dyno::SolverResult< T >::inliers, dyno::SolverResult< T >::outliers, dyno::functional_keypoint::u(), and dyno::functional_keypoint::v().
Referenced by optimizeAndUpdate().
Member Data Documentation
params_
Params dyno::OpticalFlowAndPoseOptimizer::params_ private
Definition at line 210 of file MotionSolver.hpp.
Referenced by optimize().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/frontend/vision/MotionSolver.hpp
dynosam/include/dynosam/frontend/vision/MotionSolver-inl.hpp
dynosam/src/frontend/vision/MotionSolver.cc