DynoSAM: dyno::FeatureContainer Class Reference
dyno::FeatureContainer Class Reference
Basic container mapping tracklet id's to a feature (pointer).
#include <Feature.hpp>
Classes
struct vector_iterator_base
Internal iterator type allowing iteration over the features directly e.g for(Feature::Ptr : container). This type satisfies constraints for a filter_iterator_base as well as an std::iterator.
Public Types
using TrackletToFeatureMap = std::unordered_map< TrackletId, Feature::Ptr >
using ObjectToFeatureMap = FastUnorderedMap< ObjectId, std::unordered_set< TrackletId > >
using vector_iterator = vector_iterator_base< TrackletToFeatureMap::iterator, Feature::Ptr >
Vector-style iterator definition.
using const_vector_iterator = vector_iterator_base< TrackletToFeatureMap::const_iterator, const Feature::Ptr >
Vector-style const iterator definition.
using iterator = vector_iterator
Internal typedefs to allow FeatureContainer to satisfy the definitions of a std::iterator See: https://en.cppreference.com/w/cpp/iterator/iterator_traits.
using pointer = iterator::pointer
using const_iterator = const_vector_iterator
using const_pointer = const_iterator::pointer
using value_type = Feature::Ptr
using reference = Feature::Ptr &
using const_reference = const Feature::Ptr &
using difference_type = std::ptrdiff_t
using FilterIterator = internal::filter_iterator< FeatureContainer >
Typedefs for Filter iteratorss for the FeatureContainer allowing conditional iterators to be defined. Must be defined after the internal iterator, pointer.... typedefs as internal::filter_iterator<> expects the type defined to have a valid iterator.
using ConstFilterIterator = internal::filter_const_iterator< const FeatureContainer >
Public Member Functions
FeatureContainer ()
FeatureContainer (const FeaturePtrs feature_vector)
void add (const Feature &feature)
Adds a new feature to the container. Uses feature.trackletId() to set the tracklet key.
void add (Feature::Ptr feature)
Adds a new feature to the container. Uses feature->trackletId() to set the tracklet key.
void remove (TrackletId tracklet_id)
Removes a feature by tracklet id by using std::map::erase.
void clear ()
Clears the entire container.
void removeByObjectId (ObjectId object_id)
Removes all features with a particular object id.
TrackletIds collectTracklets (bool only_usable=true) const
Collects all feature tracklets. If only_usable is True, only features with Feature::usable() == true will be included. This is a short-hand way of collecting only inlier tracklets! Else, all features in the container will be included.
bool empty () const
If the container is empty.
void markOutliers (const TrackletIds &outliers)
Mark all features with the provided tracklet ids as outliers. If the present feature is already an outlier or does not exist, nothing happens ;)!
size_t size () const
Returns the number of features in the container.
size_t size (ObjectId object_id) const
Returns number of features in the container per object id.
Feature::Ptr getByTrackletId (TrackletId tracklet_id) const
Gets a feature given its tracklet id. If the feature does not exist, nullptr is returned.
bool exists (TrackletId tracklet_id) const
Returns true if a feature with the given tracklet id exists.
FeatureContainer & operator+= (const FeatureContainer &other)
TrackletIds getByObject (ObjectId) const
vector_iterator begin ()
const_vector_iterator begin () const
vector_iterator end ()
const_vector_iterator end () const
FilterIterator beginUsable ()
FilterIterator beginUsable () const
ObjectToFeatureMap::iterator beginObjectIterator ()
ObjectToFeatureMap::iterator endObjectIterator ()
ObjectToFeatureMap::const_iterator beginObjectIterator () const
ObjectToFeatureMap::const_iterator endObjectIterator () const
std::vector< cv::Point2f > toOpenCV (TrackletIds *tracklet_ids=nullptr, bool only_inliers=false) const
Converts the keypoints of all features in the container to cv::Point2f representation. This makes them compatible with OpenCV functions.
Private Attributes
TrackletToFeatureMap feature_map_
ObjectToFeatureMap object_feature_map_
Detailed Description
Basic container mapping tracklet id's to a feature (pointer).
Unlike a regular std::map, this container allows direct iteration over the feature's and modification of inliers/outliers etc.
Used regular in frames and other data-structures to add and maintain features in different stages of their construction.
Definition at line 442 of file Feature.hpp.
Member Typedef Documentation
const_iterator
using dyno::FeatureContainer::const_iterator = const_vector_iterator
Definition at line 501 of file Feature.hpp.
const_pointer
using dyno::FeatureContainer::const_pointer = const_iterator::pointer
Definition at line 502 of file Feature.hpp.
const_reference
using dyno::FeatureContainer::const_reference = const Feature::Ptr&
Definition at line 505 of file Feature.hpp.
const_vector_iterator
using dyno::FeatureContainer::const_vector_iterator = vector_iterator_base<TrackletToFeatureMap::const_iterator, const Feature::Ptr>
Vector-style const iterator definition.
Definition at line 492 of file Feature.hpp.
ConstFilterIterator
using dyno::FeatureContainer::ConstFilterIterator = internal::filter_const_iterator<const FeatureContainer>
Definition at line 513 of file Feature.hpp.
difference_type
using dyno::FeatureContainer::difference_type = std::ptrdiff_t
Definition at line 506 of file Feature.hpp.
FilterIterator
using dyno::FeatureContainer::FilterIterator = internal::filter_iterator<FeatureContainer>
Typedefs for Filter iteratorss for the FeatureContainer allowing conditional iterators to be defined. Must be defined after the internal iterator, pointer.... typedefs as internal::filter_iterator<> expects the type defined to have a valid iterator.
Definition at line 512 of file Feature.hpp.
iterator
using dyno::FeatureContainer::iterator = vector_iterator
Internal typedefs to allow FeatureContainer to satisfy the definitions of a std::iterator See: https://en.cppreference.com/w/cpp/iterator/iterator_traits.
Definition at line 499 of file Feature.hpp.
ObjectToFeatureMap
using dyno::FeatureContainer::ObjectToFeatureMap = FastUnorderedMap<ObjectId, std::unordered_set<TrackletId> >
Definition at line 446 of file Feature.hpp.
pointer
using dyno::FeatureContainer::pointer = iterator::pointer
Definition at line 500 of file Feature.hpp.
reference
using dyno::FeatureContainer::reference = Feature::Ptr&
Definition at line 504 of file Feature.hpp.
TrackletToFeatureMap
using dyno::FeatureContainer::TrackletToFeatureMap = std::unordered_map<TrackletId, Feature::Ptr>
Definition at line 444 of file Feature.hpp.
value_type
using dyno::FeatureContainer::value_type = Feature::Ptr
Definition at line 503 of file Feature.hpp.
vector_iterator
using dyno::FeatureContainer::vector_iterator = vector_iterator_base<TrackletToFeatureMap::iterator, Feature::Ptr>
Vector-style iterator definition.
Definition at line 489 of file Feature.hpp.
Constructor & Destructor Documentation
FeatureContainer() [1/2]
dyno::FeatureContainer::FeatureContainer ()
Definition at line 37 of file Feature.cc.
: feature_map_() {}
FeatureContainer() [2/2]
dyno::FeatureContainer::FeatureContainer (const FeaturePtrs feature_vector)
Definition at line 39 of file Feature.cc.
{
  for (size_t i = 0; i < feature_vector.size(); i++) {
    add(feature_vector.at(i));
  }
}
References add().
Member Function Documentation
add() [1/2]
void dyno::FeatureContainer::add (const Feature & feature)
Adds a new feature to the container. Uses feature.trackletId() to set the tracklet key.
Takes a copy of the feature.
Parameters
feature const Feature&
Definition at line 45 of file Feature.cc.
{
  auto feature_ptr = std::make_shared<Feature>(feature);
  add(feature_ptr);
}
References add().
Referenced by add(), dyno::KltFeatureTracker::detectFeatures(), FeatureContainer(), dyno::FeatureTracker::sampleDynamic(), dyno::FeatureTracker::trackDynamicKLT(), dyno::KltFeatureTracker::trackPoints(), and dyno::KltFeatureTracker::trackStatic().
add() [2/2]
void dyno::FeatureContainer::add (Feature::Ptr feature)
Adds a new feature to the container. Uses feature->trackletId() to set the tracklet key.
Parameters
feature Feature::Ptr feature
Definition at line 50 of file Feature.cc.
{
  CHECK(!exists(feature->trackletId()))
      << "Feailure in FeatureContainer::add - Tracklet Id "
      << feature->trackletId() << " already exists";
  feature_map_[feature->trackletId()] = feature;
  // TODO: what if object id is not valid!
  if (!object_feature_map_.exists(feature->objectId())) {
    object_feature_map_.insert2(feature->objectId(),
                                std::unordered_set<TrackletId>{});
  }
  object_feature_map_[feature->objectId()].insert(feature->trackletId());
}
References exists(), feature_map_, and object_feature_map_.
begin() [1/2]
vector_iterator dyno::FeatureContainer::begin () inline
Definition at line 635 of file Feature.hpp.
{
    return vector_iterator(feature_map_.begin());
  }
References feature_map_.
begin() [2/2]
const_vector_iterator dyno::FeatureContainer::begin () const inline
Definition at line 638 of file Feature.hpp.
{
    return const_vector_iterator(feature_map_.cbegin());
  }
References feature_map_.
beginObjectIterator() [1/2]
FeatureContainer::ObjectToFeatureMap::iterator dyno::FeatureContainer::beginObjectIterator ()
Definition at line 182 of file Feature.cc.
{
  return object_feature_map_.begin();
}
References object_feature_map_.
beginObjectIterator() [2/2]
FeatureContainer::ObjectToFeatureMap::const_iterator dyno::FeatureContainer::beginObjectIterator () const
Definition at line 191 of file Feature.cc.
{
  return object_feature_map_.begin();
}
References object_feature_map_.
beginUsable() [1/2]
FeatureContainer::FilterIterator dyno::FeatureContainer::beginUsable ()
Definition at line 169 of file Feature.cc.
{
  return FilterIterator(*this, [](const Feature::Ptr& f) -> bool {
    return Feature::IsUsable(f);
  });
}
References dyno::Feature::IsUsable().
Referenced by dyno::Frame::constructDynamicObservations(), dyno::FeatureTrackerBase::drawStereoMatches(), dyno::Frame::getDynamicCorrespondences(), dyno::Frame::getStaticCorrespondences(), dyno::KltFeatureTracker::trackStatic(), dyno::Frame::usableDynamicFeaturesBegin(), and dyno::Frame::usableStaticFeaturesBegin().
beginUsable() [2/2]
FeatureContainer::FilterIterator dyno::FeatureContainer::beginUsable () const
Definition at line 175 of file Feature.cc.
{
  FeatureContainer& t = const_cast<FeatureContainer&>(*this);
  return FilterIterator(
      t, [](const Feature::Ptr& f) -> bool { return Feature::IsUsable(f); });
}
References dyno::Feature::IsUsable().
clear()
void dyno::FeatureContainer::clear ()
Clears the entire container.
Definition at line 111 of file Feature.cc.
{
  feature_map_.clear();
  object_feature_map_.clear();
}
References feature_map_, and object_feature_map_.
Referenced by dyno::FeatureTracker::trackDynamic().
collectTracklets()
TrackletIds dyno::FeatureContainer::collectTracklets (bool only_usable = true) const
Collects all feature tracklets. If only_usable is True, only features with Feature::usable() == true will be included. This is a short-hand way of collecting only inlier tracklets! Else, all features in the container will be included.
Parameters
only_usable bool. Defaults to true.
Returns
TrackletIds
Definition at line 117 of file Feature.cc.
{
  TrackletIds tracklets;
  for (const auto& feature : *this) {
    if (only_usable && feature->usable()) {
      tracklets.push_back(feature->trackletId());
    } else if (!only_usable) {
      tracklets.push_back(feature->trackletId());
    }
  }
  return tracklets;
}
empty()
bool dyno::FeatureContainer::empty () const inline
If the container is empty.
Returns
true
false
Definition at line 579 of file Feature.hpp.
{ return size() == 0u; }
References size().
Referenced by dyno::KltFeatureTracker::trackPoints(), and dyno::KltFeatureTracker::trackStatic().
end() [1/2]
vector_iterator dyno::FeatureContainer::end () inline
Definition at line 643 of file Feature.hpp.
{ return vector_iterator(feature_map_.end()); }
References feature_map_.
end() [2/2]
const_vector_iterator dyno::FeatureContainer::end () const inline
Definition at line 644 of file Feature.hpp.
{
    return const_vector_iterator(feature_map_.cend());
  }
References feature_map_.
endObjectIterator() [1/2]
FeatureContainer::ObjectToFeatureMap::iterator dyno::FeatureContainer::endObjectIterator ()
Definition at line 186 of file Feature.cc.
{
  return object_feature_map_.end();
}
References object_feature_map_.
endObjectIterator() [2/2]
FeatureContainer::ObjectToFeatureMap::const_iterator dyno::FeatureContainer::endObjectIterator () const
Definition at line 195 of file Feature.cc.
{
  return object_feature_map_.end();
}
References object_feature_map_.
exists()
bool dyno::FeatureContainer::exists (TrackletId tracklet_id) const
Returns true if a feature with the given tracklet id exists.
Parameters
tracklet_id TrackletId
Returns
true
false
Definition at line 156 of file Feature.cc.
{
  return feature_map_.find(tracklet_id) != feature_map_.end();
}
References feature_map_.
Referenced by add(), dyno::Frame::at(), dyno::Frame::exists(), getByTrackletId(), dyno::vision_tools::getCorrespondences(), markOutliers(), and remove().
getByObject()
TrackletIds dyno::FeatureContainer::getByObject (ObjectId object_id) const
Definition at line 160 of file Feature.cc.
{
  if (object_feature_map_.exists(object_id)) {
    const auto& tracklets = object_feature_map_.at(object_id);
    return TrackletIds(tracklets.begin(), tracklets.end());
  } else {
    return TrackletIds{};
  }
}
References object_feature_map_.
getByTrackletId()
Feature::Ptr dyno::FeatureContainer::getByTrackletId (TrackletId tracklet_id) const
Gets a feature given its tracklet id. If the feature does not exist, nullptr is returned.
Parameters
tracklet_id TrackletId
Returns
Feature::Ptr
Definition at line 149 of file Feature.cc.
{
  if (!exists(tracklet_id)) {
    return nullptr;
  }
  return feature_map_.at(tracklet_id);
}
References exists(), and feature_map_.
Referenced by dyno::Frame::at(), dyno::FeatureTrackerBase::computeImageTracks(), dyno::vision_tools::getCorrespondences(), markOutliers(), remove(), dyno::FeatureTracker::stereoTrack(), dyno::FeatureTracker::trackDynamicKLT(), and dyno::KltFeatureTracker::trackPoints().
markOutliers()
void dyno::FeatureContainer::markOutliers (const TrackletIds & outliers)
Mark all features with the provided tracklet ids as outliers. If the present feature is already an outlier or does not exist, nothing happens ;)!
Parameters
outliers const TrackletIds&
Definition at line 130 of file Feature.cc.
{
  for (TrackletId tracklet_id : outliers) {
    CHECK(exists(tracklet_id));
    getByTrackletId(tracklet_id)->markOutlier();
  }
}
References exists(), and getByTrackletId().
Referenced by dyno::FeatureTracker::stereoTrack().
operator+=()
FeatureContainer & dyno::FeatureContainer::operator+= (const FeatureContainer & other) inline
Definition at line 625 of file Feature.hpp.
{
    feature_map_.insert(other.feature_map_.begin(), other.feature_map_.end());
    object_feature_map_.insert(other.object_feature_map_.begin(),
                               other.object_feature_map_.end());
    return *this;
  }
References feature_map_, and object_feature_map_.
remove()
void dyno::FeatureContainer::remove (TrackletId tracklet_id)
Removes a feature by tracklet id by using std::map::erase.
NOTE: This will directly modify the internal map, messing up any iterator that currently has a reference to this container (so any of the FilterIterator)!!
Parameters
tracklet_id TrackletId
Definition at line 67 of file Feature.cc.
{
  if (!exists(tracklet_id)) {
    throw std::runtime_error("Cannot remove feature with tracklet id " +
                             std::to_string(tracklet_id) +
                             " as feature does not exist!");
  }
  auto feature = this->getByTrackletId(tracklet_id);
  const auto object_id = feature->objectId();
  // check object id exists in map
  CHECK(object_feature_map_.exists(object_id));
  // remove tracklet id from tracklet set and if the set is now empty
  // remove object id entirely
  auto& tracklets_per_object = object_feature_map_.at(object_id);
  tracklets_per_object.erase(tracklet_id);
  if (tracklets_per_object.empty()) {
    object_feature_map_.erase(object_id);
  }
  // remove from main feature map
  feature_map_.erase(tracklet_id);
}
References exists(), feature_map_, getByTrackletId(), and object_feature_map_.
Referenced by removeByObjectId().
removeByObjectId()
void dyno::FeatureContainer::removeByObjectId (ObjectId object_id)
Removes all features with a particular object id.
Parameters
object_id ObjectId
Definition at line 91 of file Feature.cc.
{
  // collect all tracklets
  auto itr = FilterIterator(*this, [object_id](const Feature::Ptr& f) -> bool {
    return f->objectId() == object_id;
  });
  TrackletIds tracklets_to_remove;
  for (const auto& feature : itr) {
    CHECK_EQ(feature->objectId(), object_id);
    tracklets_to_remove.push_back(feature->trackletId());
  }
  for (const auto tracklet_id : tracklets_to_remove) {
    this->remove(tracklet_id);
  }
  // remove from object_feature_map_
  object_feature_map_.erase(object_id);
}
References object_feature_map_, and remove().
size() [1/2]
size_t dyno::FeatureContainer::size () const
Returns the number of features in the container.
Returns
size_t
Definition at line 138 of file Feature.cc.
{ return feature_map_.size(); }
References feature_map_.
Referenced by dyno::KltFeatureTracker::detectFeatures(), empty(), dyno::Frame::numDynamicFeatures(), dyno::Frame::numStaticFeatures(), dyno::FeatureTracker::requiresSampling(), dyno::FeatureTracker::trackDynamicKLT(), dyno::KltFeatureTracker::trackPoints(), and dyno::KltFeatureTracker::trackStatic().
size() [2/2]
size_t dyno::FeatureContainer::size (ObjectId object_id) const
Returns number of features in the container per object id.
Parameters
object_id ObjectId
Returns
size_t
Definition at line 140 of file Feature.cc.
{
  auto itr =
      ConstFilterIterator(*this, [object_id](const Feature::Ptr& f) -> bool {
        return f->objectId() == object_id;
      });
  return static_cast<size_t>(std::distance(itr.begin(), itr.end()));
}
toOpenCV()
std::vector< cv::Point2f > dyno::FeatureContainer::toOpenCV (TrackletIds * tracklet_ids = nullptr, bool only_inliers = false) const
Converts the keypoints of all features in the container to cv::Point2f representation. This makes them compatible with OpenCV functions.
If the argument TrackletIds* is provided (ie, tracklet_ids != nullptr), the vector will be filled with the associated tracklet'id of each feature. This will be a 1-to-1 match with the output vector, allowing the keypoints to be associated with their tracklet id.
Parameters
tracklet_ids TrackletIds*. Defaults to nullptr
only_inliers bool. Defaults to false
Returns
std::vector<cv::Point2f>
Definition at line 200 of file Feature.cc.
{
  if (tracklet_ids) tracklet_ids->clear();
  std::vector<cv::Point2f> keypoints_cv;
  for (const auto& feature : *this) {
    const Keypoint& kp = feature->keypoint();
    float x = static_cast<float>(kp(0));
    float y = static_cast<float>(kp(1));
    if (only_inliers && feature->usable()) {
      keypoints_cv.push_back(cv::Point2f(x, y));
      if (tracklet_ids) tracklet_ids->push_back(feature->trackletId());
    } else if (!only_inliers) {
      keypoints_cv.push_back(cv::Point2f(x, y));
      if (tracklet_ids) tracklet_ids->push_back(feature->trackletId());
    }
  }
  return keypoints_cv;
}
Referenced by dyno::FeatureTracker::requiresSampling(), dyno::FeatureTracker::stereoTrack(), dyno::FeatureTracker::trackDynamicKLT(), and dyno::KltFeatureTracker::trackPoints().
Member Data Documentation
feature_map_
TrackletToFeatureMap dyno::FeatureContainer::feature_map_ private
Definition at line 675 of file Feature.hpp.
Referenced by add(), begin(), clear(), end(), exists(), getByTrackletId(), operator+=(), remove(), and size().
object_feature_map_
ObjectToFeatureMap dyno::FeatureContainer::object_feature_map_ private
Definition at line 676 of file Feature.hpp.
Referenced by add(), beginObjectIterator(), clear(), endObjectIterator(), getByObject(), operator+=(), remove(), and removeByObjectId().
The documentation for this class was generated from the following files:
dynosam_cv/include/dynosam_cv/Feature.hpp
dynosam_cv/src/Feature.cc