DynoSAM: dyno::KltFeatureTracker Class Reference
dyno::KltFeatureTracker Class Reference
Static feature tracking that tracks sparse feature set using the iterative Lucas-Kanade method with pyramids.
#include <StaticFeatureTracker.hpp>
Public Member Functions
KltFeatureTracker (const TrackerParams &params, Camera::Ptr camera, ImageDisplayQueue *display_queue)
FeatureContainer trackStatic (Frame::Ptr previous_frame, const ImageContainer &image_container, FeatureTrackerInfo &tracker_info, const cv::Mat &detection_mask, const std::optional< gtsam::Rot3 > &R_km1_k={}) override
Track features between frames k-1 and the current set of images (at k).
Public Member Functions inherited from dyno::StaticFeatureTracker
StaticFeatureTracker (const TrackerParams &params, Camera::Ptr camera, ImageDisplayQueue *display_queue)
virtual ~StaticFeatureTracker ()
virtual FeatureContainer trackStatic (Frame::Ptr previous_frame, const ImageContainer &image_container, FeatureTrackerInfo &tracker_info, const cv::Mat &detection_mask, const std::optional< gtsam::Rot3 > &R_km1_k)=0
Base function to perform feature tracking on static points.
Public Member Functions inherited from dyno::FeatureTrackerBase
FeatureTrackerBase (const TrackerParams &params, Camera::Ptr camera, ImageDisplayQueue *display_queue)
cv::Mat computeImageTracks (const Frame &previous_frame, const Frame &current_frame, const ImageTracksParams &config=false) const
bool drawStereoMatches (cv::Mat &output_image, const Frame &current_frame) const
bool predictKeypointsGivenRotation (std::vector< cv::Point2f > &predicted_pts_k, const std::vector< cv::Point2f > &pts_km1, const gtsam::Rot3 &R_km1_k) const
Private Member Functions
void equalizeImage (const ImageContainer &image_container, cv::Mat &equialized_greyscale) const
Outputs a CLAHE equalized greyscale image from the input RGB, which will be used to detect and track features.
std::vector< cv::Point2f > detectRawFeatures (const cv::Mat &processed_img, int number_tracked, const cv::Mat &mask=cv::Mat())
Detects features on the input image using the feature detector.
bool detectFeatures (const cv::Mat &processed_img, const ImageContainer &image_container, const FeatureContainer &current_features, FeatureContainer &new_features, const cv::Mat &detection_mask)
bool trackPoints (const cv::Mat &current_processed_img, const cv::Mat &previous_processed_img, const ImageContainer &image_container, const FeatureContainer &previous_features, FeatureContainer &tracked_features, TrackletIds &outlier_previous_features, FeatureTrackerInfo &tracker_info, const cv::Mat &detection_mask, const std::optional< gtsam::Rot3 > &R_km1_k)
Tracks features using KLT tracker between the previous image and the current one.
cv::Mat geometricVerification (const std::vector< cv::Point2f > &good_old, const std::vector< cv::Point2f > &good_new) const
Geometric verification using homograph + RANSAC. Input vectors have the same size and are a 1-to-1 of feature correspondences between old (k-1) and new (k) featurs.
Feature::Ptr constructStaticFeatureFromPrevious (const Keypoint &kp_current, Feature::Ptr previous_feature, const TrackletId tracklet_id, const FrameId frame_id) const
A more concise static feature constructor that the one in ExternalFlowFeatureTracker.
Feature::Ptr constructNewStaticFeature (const Keypoint &kp_current, const FrameId frame_id) const
Construct a new static feature with a unique tracklet id.
Private Attributes
SparseFeatureDetector::Ptr detector_
cv::Ptr< cv::cuda::SparsePyrLKOpticalFlow > lk_cuda_tracker_
Additional Inherited Members
Protected Member Functions inherited from dyno::FeatureTrackerBase
bool isWithinShrunkenImage (const Keypoint &kp) const
Checks if a keypoint is within an image, taking into account the shrink row/col values in the params. If these values are zero, it just checks that the keypoint is within the image size, as given by the camera parameters.
bool isWithinShrunkenImage (const cv::Point2f &kp) const
Protected Attributes inherited from dyno::FeatureTrackerBase
const TrackerParams params_
const cv::Size img_size_
Camera::Ptr camera_
Expected image size from the camera.
ImageDisplayQueue * display_queue_
Detailed Description
Static feature tracking that tracks sparse feature set using the iterative Lucas-Kanade method with pyramids.
Definition at line 110 of file StaticFeatureTracker.hpp.
Constructor & Destructor Documentation
KltFeatureTracker()
dyno::KltFeatureTracker::KltFeatureTracker (const TrackerParams & params, Camera::Ptr camera, ImageDisplayQueue * display_queue)
Definition at line 222 of file StaticFeatureTracker.cc.
    : StaticFeatureTracker(params, camera, display_queue) {
  detector_ = std::make_shared<SparseFeatureDetector>(
      params, FunctionalDetector::FactoryCreate(params));
  static const cv::Size klt_window_size(21, 21);  // Window size for KLT
  static const int klt_max_level = 3;             // Max pyramid levels for KLT
  static const cv::TermCriteria klt_criteria = cv::TermCriteria(
      cv::TermCriteria::EPS | cv::TermCriteria::COUNT, 30, 0.03);
  // used as flags argument for calcOpticalFlowPyrLK - initially starts as
  // default (0) flag
  int klt_flags = 0;
  lk_cuda_tracker_ = cv::cuda::SparsePyrLKOpticalFlow::create(
      klt_window_size, klt_max_level, klt_criteria.maxCount);
  CHECK_NOTNULL(detector_);
}
References detector_, dyno::FunctionalDetector::FactoryCreate(), and lk_cuda_tracker_.
Member Function Documentation
constructNewStaticFeature()
Feature::Ptr dyno::KltFeatureTracker::constructNewStaticFeature (const Keypoint & kp_current, const FrameId frame_id) const private
Construct a new static feature with a unique tracklet id.
Parameters
kp_current
frame_id
Returns
Feature::Ptr
Definition at line 678 of file StaticFeatureTracker.cc.
{
  static const auto kAge = 0u;
  TrackletIdManager& tracked_id_manager = TrackletIdManager::instance();
  TrackletId tracklet_to_use = tracked_id_manager.getAndIncrementTrackletId();
  Feature::Ptr feature = std::make_shared<Feature>();
  (*feature)
      .objectId(background_label)
      .frameId(frame_id)
      .keypointType(KeyPointType::STATIC)
      .age(kAge)
      .markInlier()
      .trackletId(tracklet_to_use)
      .keypoint(kp_current);
  return feature;
}
References dyno::background_label, dyno::TrackletIdManager::getAndIncrementTrackletId(), dyno::TrackletIdManager::instance(), and dyno::STATIC.
Referenced by detectFeatures().
constructStaticFeatureFromPrevious()
Feature::Ptr dyno::KltFeatureTracker::constructStaticFeatureFromPrevious (const Keypoint & kp_current, Feature::Ptr previous_feature, const TrackletId tracklet_id, const FrameId frame_id) const private
A more concise static feature constructor that the one in ExternalFlowFeatureTracker.
Expects the current kp to already be checked (ie. lies within the image, lies on a static pixel etc). This function does the handling of the tracklet ids (ie. incrementing the id in the TrackletIdManager).
If the feature tracked age is greater than max_feature_track_age_, we relabel it with a new tracklet id to prevent massive observation growth in the backend.
Function will also update the measured flow in the previous feature (silly old API...)
As a result should never return nullptr
Parameters
kp_current
previous_feature
tracklet_id
frame_id
Returns
Feature::Ptr
Definition at line 640 of file StaticFeatureTracker.cc.
{
  CHECK(previous_feature);
  CHECK_EQ(previous_feature->trackletId(), tracklet_id);
  size_t age = previous_feature->age();
  age++;
  TrackletId tracklet_to_use = tracklet_id;
  // if age is too large, or age is zero, retrieve new tracklet id
  if (age > params_.max_feature_track_age) {
    // TrackletIdManager& tracked_id_manager = TrackletIdManager::instance();
    // tracklet_to_use = tracked_id_manager.getTrackletIdCount();
    // tracked_id_manager.incrementTrackletIdCount();
    // age = 0u;
    return nullptr;
  }
  // update previous keypoint
  previous_feature->measuredFlow(kp_current - previous_feature->keypoint());
  // This is so awful, but happens becuase the way the code was originally
  // written, we expect flow from k to k+1 (grrrr)
  previous_feature->predictedKeypoint(kp_current);
  Feature::Ptr feature = std::make_shared<Feature>();
  (*feature)
      .objectId(background_label)
      .frameId(frame_id)
      .keypointType(KeyPointType::STATIC)
      .age(age)
      .markInlier()
      .trackletId(tracklet_to_use)
      .keypoint(kp_current);
  return feature;
}
References dyno::background_label, dyno::TrackerParams::max_feature_track_age, dyno::FeatureTrackerBase::params_, and dyno::STATIC.
Referenced by trackPoints().
detectFeatures()
bool dyno::KltFeatureTracker::detectFeatures (const cv::Mat & processed_img, const ImageContainer & image_container, const FeatureContainer & current_features, FeatureContainer & new_features, const cv::Mat & detection_mask) private
Definition at line 330 of file StaticFeatureTracker.cc.
{
  const FrameId frame_k = image_container.frameId();
  const cv::Mat& motion_mask = image_container.objectMotionMask();
  // internal detection mask that is appended with new invalid pixels
  // this builds the static detection mask over the existing input mask
  cv::Mat detection_mask_impl;
  // If we are provided with an external detection/feature mask, initalise the
  // detection mask with this and add more invalid sections to it
  if (!detection_mask.empty()) {
    CHECK_EQ(motion_mask.rows, detection_mask.rows);
    CHECK_EQ(motion_mask.cols, detection_mask.cols);
    detection_mask_impl = detection_mask.clone();
  } else {
    detection_mask_impl = cv::Mat(motion_mask.size(), CV_8U, cv::Scalar(255));
  }
  CHECK_EQ(detection_mask_impl.type(), CV_8U);
  // create mask from object mask so that all pixels > 0 are ignored (by setting
  // the value in the new mask to 0 at these locations) start with an invalid
  // mask
  cv::Mat object_feature_mask = cv::Mat::zeros(motion_mask.size(), CV_8U);
  // Set background pixels (0 in motion_mask) -> valid (1 in
  // object_feature_mask)
  object_feature_mask.setTo(255, motion_mask == 0);
  // combine with existing mask information (from current features)
  cv::bitwise_and(detection_mask_impl, object_feature_mask,
                  detection_mask_impl);
  // slow
  // add mask over objects detected in the scene
  // TODO: should just be a masking operation but treating all non-zero pixels
  // as 1 (ie make binary) and then inveverting the mask so that object pixels
  // (originally 1) become 0, indicating they should not be used! for (int i =
  // 0; i < motion_mask.rows; i++) {
  //   for (int j = 0; j < motion_mask.cols; j++) {
  //     const ObjectId label = motion_mask.at<ObjectId>(i, j);
  //     if (label != background_label) {
  //       cv::circle(
  //           detection_mask_impl, cv::Point2f(j, i),
  //           params_.min_distance_btw_tracked_and_detected_static_features,
  //           cv::Scalar(0), cv::FILLED);
  //     }
  //   }
  // }
  // add mask over current static features
  for (const auto& feature : current_features) {
    const Keypoint kp = feature->keypoint();
    CHECK(feature->usable());
    cv::circle(detection_mask_impl, cv::Point2f(kp(0), kp(1)),
               params_.min_distance_btw_tracked_and_detected_static_features,
               cv::Scalar(0), cv::FILLED);
  }
  std::vector<cv::Point2f> detected_points;
  {
    utils::TimingStatsCollector timer("static_feature_track.detect_raw");
    detected_points = detectRawFeatures(processed_img, current_features.size(),
                                        detection_mask_impl);
  }
  for (const cv::Point2f& detected_point : detected_points) {
    Keypoint kp(static_cast<double>(detected_point.x),
                static_cast<double>(detected_point.y));
    const int x = functional_keypoint::u(kp);
    const int y = functional_keypoint::v(kp);
    if (!(camera_->isKeypointContained(kp) && isWithinShrunkenImage(kp))) {
      continue;
    }
    // with the detection mask this should never happen
    if (motion_mask.at<int>(y, x) != background_label) {
      continue;
    }
    Feature::Ptr feature = constructNewStaticFeature(kp, frame_k);
    if (feature) {
      new_features.add(feature);
    }
  }
  return true;
}
References dyno::FeatureContainer::add(), dyno::background_label, dyno::FeatureTrackerBase::camera_, constructNewStaticFeature(), detectRawFeatures(), dyno::ImageContainer::frameId(), dyno::FeatureTrackerBase::isWithinShrunkenImage(), dyno::TrackerParams::min_distance_btw_tracked_and_detected_static_features, dyno::ImageContainer::objectMotionMask(), dyno::FeatureTrackerBase::params_, dyno::FeatureContainer::size(), dyno::functional_keypoint::u(), and dyno::functional_keypoint::v().
Referenced by trackPoints(), and trackStatic().
detectRawFeatures()
std::vector< cv::Point2f > dyno::KltFeatureTracker::detectRawFeatures (const cv::Mat & processed_img, int number_tracked, const cv::Mat & mask = cv::Mat()) private
Detects features on the input image using the feature detector.
The features are then spaced out using adaptive non-maxima-supression and refined using subpixel refinement (via cornerSubPix).
The number of tracked points indicates how many currently tracked points we currently have; this is used to calculate how many more features we need to reach the minimum number features per frame.
Parameters
processed_img
number_tracked
mask
Returns
std::vector<cv::Point2f>
Definition at line 320 of file StaticFeatureTracker.cc.
{
  KeypointsCV keypoints;
  detector_->detect(processed_img, keypoints, number_tracked, mask);
  std::vector<cv::Point2f> points;
  cv::KeyPoint::convert(keypoints, points);
  return points;
}
References detector_.
Referenced by detectFeatures().
equalizeImage()
void dyno::KltFeatureTracker::equalizeImage (const ImageContainer & image_container, cv::Mat & equialized_greyscale) const private
Outputs a CLAHE equalized greyscale image from the input RGB, which will be used to detect and track features.
Parameters
image_container
equialized_greyscale
Definition at line 307 of file StaticFeatureTracker.cc.
{
  const ImageWrapper<ImageType::RGBMono>& rgb_wrapper = image_container.rgb();
  const cv::Mat& rgb = rgb_wrapper.toRGB();
  cv::Mat mono = ImageType::RGBMono::toMono(rgb_wrapper);
  CHECK(!mono.empty());
  mono.copyTo(equialized_greyscale);
  // CHECK(clahe_);
  // clahe_->apply(mono, equialized_greyscale);
}
References dyno::ImageContainer::rgb(), dyno::ImageType::RGBMono::toMono(), and dyno::ImageWrapper< IMAGETYPE >::toRGB().
Referenced by trackStatic().
geometricVerification()
cv::Mat dyno::KltFeatureTracker::geometricVerification (const std::vector< cv::Point2f > & good_old, const std::vector< cv::Point2f > & good_new) const private
Geometric verification using homograph + RANSAC. Input vectors have the same size and are a 1-to-1 of feature correspondences between old (k-1) and new (k) featurs.
Parameters
good_old const std::vector<cv::Point2f>&
good_new const std::vector<cv::Point2f>&
Returns
cv::Mat
Definition at line 626 of file StaticFeatureTracker.cc.
{
  if (good_old.size() >= 4) {  // Minimum number of points required for RANSAC
    cv::Mat mask;
    cv::findHomography(good_old, good_new, cv::RANSAC, 5.0, mask);
    return mask;
  } else {
    return cv::Mat::ones(
        good_old.size(), 1,
        CV_8U);  // If not enough points, assume all are inliers
  }
}
Referenced by trackPoints().
trackPoints()
bool dyno::KltFeatureTracker::trackPoints (const cv::Mat & current_processed_img, const cv::Mat & previous_processed_img, const ImageContainer & image_container, const FeatureContainer & previous_features, FeatureContainer & tracked_features, TrackletIds & outlier_previous_features, FeatureTrackerInfo & tracker_info, const cv::Mat & detection_mask, const std::optional< gtsam::Rot3 > & R_km1_k) private
Tracks features using KLT tracker between the previous image and the current one.
Once tracked, geometric outlier rejection is used to sample the inliers and, if not enough features are tracked, new features are detected to be tracked in the previous frame.
The input previous_features, is a container of INLIER features tracked from the previous frame and will be used to set the KLT tracker. The new tracks (and detections) are dumped into tracked_features and the features that were poorly tracked from the previous frame are identified in outlier_previous_features; this vector corresponds to features in previous_features.
Parameters
current_processed_img
previous_processed_img
image_container
previous_features
tracked_features
outlier_previous_features
tracker_info
detection_mask
R_km1_k
Returns
true
false
Definition at line 420 of file StaticFeatureTracker.cc.
{
  if (current_processed_img.empty() || previous_processed_img.empty() ||
      previous_features.empty()) {
    return false;
  }
  outlier_previous_features.clear();
  const cv::Mat& motion_mask = image_container.objectMotionMask();
  const FrameId frame_k = image_container.frameId();
  std::vector<uchar> klt_status;
  std::vector<float> err;
  // All tracklet ids from the set of previous features to track
  TrackletIds tracklet_ids;
  // cannot just get inliers (becuase in reality this is)
  std::vector<cv::Point2f> previous_pts =
      previous_features.toOpenCV(&tracklet_ids, true);
  CHECK_EQ(previous_pts.size(), previous_features.size());
  CHECK_EQ(previous_pts.size(), tracklet_ids.size());
  static const cv::Size klt_window_size(21, 21);  // Window size for KLT
  static const int klt_max_level = 3;             // Max pyramid levels for KLT
  static const cv::TermCriteria klt_criteria = cv::TermCriteria(
      cv::TermCriteria::EPS | cv::TermCriteria::COUNT, 30, 0.03);
  // used as flags argument for calcOpticalFlowPyrLK - initially starts as
  // default (0) flag
  int klt_flags = 0;
  std::vector<cv::Point2f> current_points;
  if (R_km1_k) {
    predictKeypointsGivenRotation(current_points, previous_pts, *R_km1_k);
    klt_flags = cv::OPTFLOW_USE_INITIAL_FLOW;
  } else {
    // as per documentation the vector must have the same size as the input
    current_points.resize(previous_pts.size());
  }
  CHECK_EQ(current_points.size(), previous_pts.size());
  {
    // utils::TimingStatsCollector timer("static_feature_track.calc_LK");
    // cv::cuda::GpuMat gpu_prev_img(previous_processed_img);
    // cv::cuda::GpuMat gpu_current_img(current_processed_img);
    // cv::cuda::GpuMat d_points1(previous_pts);    // upload points
    // cv::cuda::GpuMat d_points2(current_points);  // output points
    // cv::cuda::GpuMat d_status;                   // status of each point
    // cv::cuda::GpuMat d_err;                      // error for each point
    // lk_cuda_tracker_->calc(gpu_prev_img, gpu_current_img, d_points1,
    // d_points2,
    //                        d_status, d_err);
    // // Download results back to CPU
    // d_points2.download(current_points);
    // d_status.download(status);
    cv::calcOpticalFlowPyrLK(previous_processed_img, current_processed_img,
                             previous_pts, current_points, klt_status, err,
                             klt_window_size, klt_max_level, klt_criteria,
                             klt_flags);
    // if we used OPTFLOW_USE_INITIAL_FLOW check that we actually got good flow
    if (klt_flags == cv::OPTFLOW_USE_INITIAL_FLOW) {
      static constexpr int kMinSuccessTracks = 10;
      int succ_num = 0;
      for (size_t i = 0; i < klt_status.size(); i++) {
        if (klt_status[i]) succ_num++;
      }
      if (succ_num < kMinSuccessTracks) {
        LOG(WARNING) << "Using initial flow for KLT tracking failed: only "
                     << succ_num << " tracked!";
        cv::calcOpticalFlowPyrLK(previous_processed_img, current_processed_img,
                                 previous_pts, current_points, klt_status, err,
                                 klt_window_size, klt_max_level, klt_criteria);
      }
    }
    // check flow back
    std::vector<cv::Point2f> reverse_previous_feature_points = current_points;
    std::vector<uchar> klt_reverse_status;
    cv::calcOpticalFlowPyrLK(current_processed_img, previous_processed_img,
                             current_points, reverse_previous_feature_points,
                             klt_reverse_status, err, cv::Size(21, 21), 5);
    CHECK_EQ(klt_reverse_status.size(), tracklet_ids.size());
    auto distance = [](const cv::Point2f& pt1,
                       const cv::Point2f& pt2) -> float {
      float dx = pt1.x - pt2.x;
      float dy = pt1.y - pt2.y;
      return std::sqrt(dx * dx + dy * dy);
    };
    // update klt status based on result from flow
    for (size_t i = 0; i < klt_status.size(); i++) {
      const bool both_status_good =
          klt_status.at(i) && klt_reverse_status.at(i);
      const bool within_distance =
          distance(previous_pts.at(i), reverse_previous_feature_points.at(i)) <=
          0.5;
      if (both_status_good && within_distance) {
        klt_status.at(i) = 1;
      } else {
        klt_status.at(i) = 0;
      }
    }
  }
  CHECK_EQ(previous_pts.size(), current_points.size());
  CHECK_EQ(klt_status.size(), current_points.size());
  std::vector<cv::Point2f> good_current, good_previous;
  TrackletIds good_tracklets;
  // can also look at the err?
  for (size_t i = 0; i < klt_status.size(); i++) {
    if (klt_status[i]) {
      good_current.push_back(current_points.at(i));
      good_previous.push_back(previous_pts.at(i));
      good_tracklets.push_back(tracklet_ids.at(i));
    }
  }
  // Geometric verification using RANSAC
  const cv::Mat geometric_verification_mask =
      geometricVerification(good_previous, good_current);
  std::vector<cv::Point2f> verified_current, verified_previous;
  TrackletIds verified_tracklets;
  for (int i = 0; i < geometric_verification_mask.rows; ++i) {
    if (geometric_verification_mask.at<uchar>(i)) {
      verified_current.push_back(good_current.at(i));
      verified_previous.push_back(good_previous.at(i));
      verified_tracklets.push_back(good_tracklets.at(i));
    }
  }
  CHECK_EQ(verified_tracklets.size(), verified_current.size());
  // add to tracked features
  for (size_t i = 0; i < verified_tracklets.size(); i++) {
    TrackletId tracklet_id = verified_tracklets.at(i);
    const Feature::Ptr previous_feature =
        previous_features.getByTrackletId(tracklet_id);
    // TODO: check this is the same as the previos kp to guarnatee order?
    CHECK(previous_feature->usable());
    const cv::Point2f kp_cv = verified_current.at(i);
    Keypoint kp(static_cast<double>(kp_cv.x), static_cast<double>(kp_cv.y));
    const int x = functional_keypoint::u(kp);
    const int y = functional_keypoint::v(kp);
    if (motion_mask.at<int>(y, x) != background_label) {
      continue;
    }
    if (!(camera_->isKeypointContained(kp) && isWithinShrunkenImage(kp))) {
      continue;
    }
    Feature::Ptr feature = constructStaticFeatureFromPrevious(
        kp, previous_feature, tracklet_id, frame_k);
    if (feature) {
      tracked_features.add(feature);
    }
  }
  // Get the outliers associated with the previous_features container by taking
  // the set difference between the verified and total tracklets NOTE: verified
  // tracklets are not necessary the same as the tracklets in tracked_features
  // as tracked features may excluse some features (e.g. if not in the shrunken
  // image) or (will eventually) have new tracklets after a new detection takes
  // place we just want the set difference between the original features and
  // ones we KNOW are outliers
  {
    utils::TimingStatsCollector timer("static_feature_track.find_outliers");
    determineOutlierIds(verified_tracklets, tracklet_ids,
                        outlier_previous_features);
  }
  const auto& n_tracked = tracked_features.size();
  tracker_info.static_track_optical_flow = n_tracked;
  if (tracked_features.size() <
      static_cast<size_t>(params_.min_features_per_frame)) {
    utils::TimingStatsCollector timer("static_feature_track.detect");
    // if we do not have enough features, detect more on the current image
    detectFeatures(current_processed_img, image_container, tracked_features,
                   tracked_features, detection_mask);
    const auto n_detected = tracked_features.size() - n_tracked;
    tracker_info.static_track_detections += n_detected;
  }
  return true;
}
References dyno::FeatureContainer::add(), dyno::background_label, dyno::FeatureTrackerBase::camera_, constructStaticFeatureFromPrevious(), detectFeatures(), dyno::determineOutlierIds(), dyno::FeatureContainer::empty(), dyno::ImageContainer::frameId(), geometricVerification(), dyno::FeatureContainer::getByTrackletId(), dyno::FeatureTrackerBase::isWithinShrunkenImage(), dyno::TrackerParams::min_features_per_frame, dyno::ImageContainer::objectMotionMask(), dyno::FeatureTrackerBase::params_, dyno::FeatureTrackerBase::predictKeypointsGivenRotation(), dyno::FeatureContainer::size(), dyno::FeatureTrackerInfo::static_track_detections, dyno::FeatureTrackerInfo::static_track_optical_flow, dyno::FeatureContainer::toOpenCV(), dyno::functional_keypoint::u(), and dyno::functional_keypoint::v().
Referenced by trackStatic().
trackStatic()
FeatureContainer dyno::KltFeatureTracker::trackStatic (Frame::Ptr previous_frame, const ImageContainer & image_container, FeatureTrackerInfo & tracker_info, const cv::Mat & detection_mask, const std::optional< gtsam::Rot3 > & R_km1_k = {}) override virtual
Track features between frames k-1 and the current set of images (at k).
General algorithm is: If not previous frame (ie. is null)
preprocess input images (equalizeImage)
detect feature in image container (detectFeatures) Else
preprocess input images (equalizeImage)
Collect inlier Features from the previous frame
Track points (trackPoints)
apply KLT tracking algorithm
apply geometric verification to all features
add tracks and check all features are valid (e.g lie on static points etc..)
if number of tracks < threshold (max_features_per_frame_)
reapply feature detection NOTE: in a perfect world we would detect on the previous image and then re-track on the current image, but I didnt implement it like this and, in reality, we we will only drop below the threshold for one frame. As long as we're tracking a good number of features this does not effect the accuracy that much :)
Parameters
previous_frame Frame::Ptr. Previous frame (k-1) with filled-out features to be tracked.
image_container const ImageContainer&. Contains current (k) images which will be tracked from the previous frame.
tracker_info FeatureTrackerInfo&. Tracking metadata to be filled out.
detection_mask const cv::Mat& A detection mask in the opencv feature tracking form: CV_8UC1 where white pixels (255) are valid and black pixels (0) should not be detected on
Returns
FeatureContainer Contains all successsfully tracked features.
Implements dyno::StaticFeatureTracker.
Definition at line 244 of file StaticFeatureTracker.cc.
{
  // tracked features and new features
  FeatureContainer new_tracks_and_detections;
  cv::Mat current_equialized_greyscale;
  equalizeImage(image_container, current_equialized_greyscale);
  if (!previous_frame) {
    FeatureContainer previous_inliers;
    detectFeatures(current_equialized_greyscale, image_container,
                   previous_inliers, new_tracks_and_detections, detection_mask);
    tracker_info.static_track_detections = new_tracks_and_detections.size();
    return new_tracks_and_detections;
  } else {
    // we have previous tracks
    // we should have already calculated the processed rgb image from the
    // previous frame
    cv::Mat previous_equialized_greyscale;
    equalizeImage(previous_frame->image_container_,
                  previous_equialized_greyscale);
    FeatureContainer previous_inliers;
    auto iter = previous_frame->static_features_.beginUsable();
    for (const auto& inlier_feature : iter) {
      previous_inliers.add(inlier_feature);
    }
    // if we dont actually have any previous tracks
    // this may be in cases where we have an IMU and so we have some odometry
    // but no feature tracks from the previous frame!
    if (previous_inliers.empty()) {
      FeatureContainer previous_inliers;
      detectFeatures(current_equialized_greyscale, image_container,
                     previous_inliers, new_tracks_and_detections,
                     detection_mask);
      tracker_info.static_track_detections = new_tracks_and_detections.size();
      return new_tracks_and_detections;
    }
    // Tracklet ids associated with the set of previous inliers that are now
    // outliers
    TrackletIds previous_outliers;
    // track features from the previous frame and detect new ones if necessary
    CHECK(trackPoints(
        current_equialized_greyscale, previous_equialized_greyscale,
        image_container, previous_inliers, new_tracks_and_detections,
        previous_outliers, tracker_info, detection_mask, R_km1_k));
    // after tracking, mark features in the older frame as outliers
    // TODO: (jesse) actually not sure we HAVE to do this, but better to keep
    // things as consisent as possible
    previous_frame->static_features_.markOutliers(previous_outliers);
    return new_tracks_and_detections;
  }
}
References dyno::FeatureContainer::add(), dyno::FeatureContainer::beginUsable(), detectFeatures(), dyno::FeatureContainer::empty(), equalizeImage(), dyno::FeatureContainer::size(), dyno::FeatureTrackerInfo::static_track_detections, and trackPoints().
Member Data Documentation
detector_
SparseFeatureDetector::Ptr dyno::KltFeatureTracker::detector_ private
Definition at line 281 of file StaticFeatureTracker.hpp.
Referenced by detectRawFeatures(), and KltFeatureTracker().
lk_cuda_tracker_
cv::Ptr<cv::cuda::SparsePyrLKOpticalFlow> dyno::KltFeatureTracker::lk_cuda_tracker_ private
Definition at line 284 of file StaticFeatureTracker.hpp.
Referenced by KltFeatureTracker().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/frontend/vision/StaticFeatureTracker.hpp
dynosam/src/frontend/vision/StaticFeatureTracker.cc