DynoSAM: dyno::DataProvider Class Reference
dyno::DataProvider Class Reference abstract
A data provider is a module that actually gets the inididual image and/or IMU data from some source and packets it into a Frame and IMU form and sends it the the DataInterfacePipeline via callback functions where the data is synchronized and sent to the frontend.
#include <DataProvider.hpp>
Public Types
using ImageContainerCallback = std::function< void(ImageContainer::Ptr)>
using ImuSingleInputCallback = std::function< void(const ImuMeasurement &)>
using ImuMultiInputCallback = std::function< void(const ImuMeasurements &)>
using GroundTruthPacketCallback = std::function< void(const GroundTruthInputPacket &)>
Public Member Functions
DataProvider ()=default
DataProvider (DataInterfacePipeline *module)
DataProvider (DataInterfacePipelineImu *module)
virtual ~DataProvider ()
void registerImuSingleCallback (const ImuSingleInputCallback &callback)
void registerImuMultiCallback (const ImuMultiInputCallback &callback)
void registerImageContainerCallback (const ImageContainerCallback &callback)
void registerGroundTruthPacketCallback (const GroundTruthPacketCallback &callback)
virtual ImageContainer::Ptr imageContainerPreprocessor (ImageContainer::Ptr image_container)
Virtual Image Container Preprocessor function that is registered to the data interface pipeline.
void registerOnFinishCallback (const std::function< void()> &callback)
virtual int datasetSize () const =0
Get the size of the dataset - if this is not valid (i.e. the provider is online) this function should return -1.
virtual bool spin ()=0
Spins the dataset for one "step" of the dataset.
virtual void shutdown ()
virtual CameraParams::Optional getCameraParams () const
Provides functionality to get camera paramters for the main pipeline, as these may be available from the dataset.
Protected Member Functions
void emitOnFinishCallbacks ()
Protected Attributes
ImageContainerCallback image_container_callback_
ImuSingleInputCallback imu_single_input_callback_
ImuMultiInputCallback imu_multi_input_callback_
GroundTruthPacketCallback ground_truth_packet_callback_
std::atomic_bool shutdown_ = {false}
Private Attributes
std::vector< std::function< void()> > on_finish_callbacks_
Detailed Description
A data provider is a module that actually gets the inididual image and/or IMU data from some source and packets it into a Frame and IMU form and sends it the the DataInterfacePipeline via callback functions where the data is synchronized and sent to the frontend.
Definition at line 25 of file DataProvider.hpp.
Member Typedef Documentation
GroundTruthPacketCallback
using dyno::DataProvider::GroundTruthPacketCallback = std::function<void(const GroundTruthInputPacket&)>
Definition at line 37 of file DataProvider.hpp.
ImageContainerCallback
using dyno::DataProvider::ImageContainerCallback = std::function<void(ImageContainer::Ptr)>
Definition at line 33 of file DataProvider.hpp.
ImuMultiInputCallback
using dyno::DataProvider::ImuMultiInputCallback = std::function<void(const ImuMeasurements&)>
Definition at line 35 of file DataProvider.hpp.
ImuSingleInputCallback
using dyno::DataProvider::ImuSingleInputCallback = std::function<void(const ImuMeasurement&)>
Definition at line 34 of file DataProvider.hpp.
Constructor & Destructor Documentation
DataProvider() [1/3]
dyno::DataProvider::DataProvider () default
DataProvider() [2/3]
dyno::DataProvider::DataProvider (DataInterfacePipeline * module)
Definition at line 33 of file DataProvider.cc.
{
    CHECK_NOTNULL(module);
    registerImageContainerCallback(std::bind(&DataInterfacePipeline::fillImageContainerQueue, module, std::placeholders::_1));
    CHECK(image_container_callback_);
}
References dyno::DataInterfacePipeline::fillImageContainerQueue(), image_container_callback_, and registerImageContainerCallback().
DataProvider() [3/3]
dyno::DataProvider::DataProvider (DataInterfacePipelineImu * module)
Definition at line 50 of file DataProvider.cc.
                                                           : DataProvider(dynamic_cast<DataInterfacePipeline*>(module)) {
    CHECK_NOTNULL(module);
    registerImuMultiCallback(std::bind(
        static_cast<void(DataInterfacePipelineImu::*)(const ImuMeasurements&)>(&DataInterfacePipelineImu::fillImuQueue),
        module,
        std::placeholders::_1));
    registerImuSingleCallback(std::bind(
        static_cast<void(DataInterfacePipelineImu::*)(const ImuMeasurement&)>(&DataInterfacePipelineImu::fillImuQueue),
        module,
        std::placeholders::_1));
    CHECK(imu_multi_input_callback_);
    CHECK(imu_single_input_callback_);
}
References dyno::DataInterfacePipelineImu::fillImuQueue(), imu_multi_input_callback_, imu_single_input_callback_, registerImuMultiCallback(), and registerImuSingleCallback().
~DataProvider()
dyno::DataProvider::~DataProvider () virtual
Definition at line 40 of file DataProvider.cc.
{
    shutdown();
}
References shutdown().
Member Function Documentation
datasetSize()
virtual int dyno::DataProvider::datasetSize () const pure virtual
Get the size of the dataset - if this is not valid (i.e. the provider is online) this function should return -1.
Returns
int
Implemented in dyno::DynoDatasetProvider< DataTypes >, and dyno::DynoDatasetProvider< cv::Mat, cv::Mat, gtsam::Pose3, GroundTruthInputPacket >.
emitOnFinishCallbacks()
void dyno::DataProvider::emitOnFinishCallbacks () inline protected
Definition at line 118 of file DataProvider.hpp.
{
        for(auto cb : on_finish_callbacks_) cb();
    }
References on_finish_callbacks_.
Referenced by dyno::DynoDatasetProvider< DataTypes >::spin().
getCameraParams()
virtual CameraParams::Optional dyno::DataProvider::getCameraParams () const inline virtual
Provides functionality to get camera paramters for the main pipeline, as these may be available from the dataset.
By default returns std::nullopt but the derived data-provider can overwrite this and return the loaded params
Returns
CameraParams::Optional
Reimplemented in dyno::ClusterSlamDataLoader, dyno::KittiDataLoader, dyno::OMDDataLoader, dyno::ProjectARIADataLoader, and dyno::VirtualKittiDataLoader.
Definition at line 111 of file DataProvider.hpp.
{ return {}; }
imageContainerPreprocessor()
virtual ImageContainer::Ptr dyno::DataProvider::imageContainerPreprocessor (ImageContainer::Ptr image_container) inline virtual
Virtual Image Container Preprocessor function that is registered to the data interface pipeline.
By default does nothing and just returns the argument. This function is called (via callback) when a ImageContainer is sent to the pipeline via DataProvider::image_container_callback_ and enables each data-provider to implement their own data-preprocessing as necessary
Parameters
image_container
Returns
ImageContainer::Ptr
Reimplemented in dyno::KittiDataLoader.
Definition at line 75 of file DataProvider.hpp.
{
        return image_container;
    }
Referenced by dyno::DynoPipelineManager::DynoPipelineManager().
registerGroundTruthPacketCallback()
void dyno::DataProvider::registerGroundTruthPacketCallback (const GroundTruthPacketCallback & callback) inline
Definition at line 60 of file DataProvider.hpp.
{
        ground_truth_packet_callback_ = callback;
    }
References ground_truth_packet_callback_.
registerImageContainerCallback()
void dyno::DataProvider::registerImageContainerCallback (const ImageContainerCallback & callback) inline
Definition at line 56 of file DataProvider.hpp.
{
        image_container_callback_ = callback;
    }
References image_container_callback_.
Referenced by DataProvider().
registerImuMultiCallback()
void dyno::DataProvider::registerImuMultiCallback (const ImuMultiInputCallback & callback) inline
Definition at line 52 of file DataProvider.hpp.
{
        imu_multi_input_callback_ = callback;
    }
References imu_multi_input_callback_.
Referenced by DataProvider().
registerImuSingleCallback()
void dyno::DataProvider::registerImuSingleCallback (const ImuSingleInputCallback & callback) inline
Definition at line 47 of file DataProvider.hpp.
{
        imu_single_input_callback_ = callback;
    }
References imu_single_input_callback_.
Referenced by DataProvider().
registerOnFinishCallback()
void dyno::DataProvider::registerOnFinishCallback (const std::function< void()> & callback) inline
Definition at line 79 of file DataProvider.hpp.
{
        on_finish_callbacks_.push_back(callback);
    }
References on_finish_callbacks_.
shutdown()
void dyno::DataProvider::shutdown () virtual
Definition at line 44 of file DataProvider.cc.
{
    LOG(INFO) << "Shutting down data provider and associated module";
    shutdown_ = true;
}
References shutdown_.
Referenced by ~DataProvider().
spin()
virtual bool dyno::DataProvider::spin () pure virtual
Spins the dataset for one "step" of the dataset.
Returns true if the dataset still has data to process
Returns
true
false
Implemented in dyno::DynoDatasetProvider< DataTypes >, and dyno::DynoDatasetProvider< cv::Mat, cv::Mat, gtsam::Pose3, GroundTruthInputPacket >.
Member Data Documentation
ground_truth_packet_callback_
GroundTruthPacketCallback dyno::DataProvider::ground_truth_packet_callback_ protected
Definition at line 128 of file DataProvider.hpp.
Referenced by dyno::ClusterSlamDataLoader::ClusterSlamDataLoader(), dyno::KittiDataLoader::KittiDataLoader(), dyno::OMDDataLoader::OMDDataLoader(), registerGroundTruthPacketCallback(), and dyno::VirtualKittiDataLoader::VirtualKittiDataLoader().
image_container_callback_
ImageContainerCallback dyno::DataProvider::image_container_callback_ protected
Definition at line 124 of file DataProvider.hpp.
Referenced by dyno::ClusterSlamDataLoader::ClusterSlamDataLoader(), DataProvider(), dyno::KittiDataLoader::KittiDataLoader(), dyno::OMDDataLoader::OMDDataLoader(), dyno::ProjectARIADataLoader::ProjectARIADataLoader(), registerImageContainerCallback(), and dyno::VirtualKittiDataLoader::VirtualKittiDataLoader().
imu_multi_input_callback_
ImuMultiInputCallback dyno::DataProvider::imu_multi_input_callback_ protected
Definition at line 126 of file DataProvider.hpp.
Referenced by DataProvider(), and registerImuMultiCallback().
imu_single_input_callback_
ImuSingleInputCallback dyno::DataProvider::imu_single_input_callback_ protected
Definition at line 125 of file DataProvider.hpp.
Referenced by DataProvider(), and registerImuSingleCallback().
on_finish_callbacks_
std::vector<std::function<void()> > dyno::DataProvider::on_finish_callbacks_ private
Definition at line 134 of file DataProvider.hpp.
Referenced by emitOnFinishCallbacks(), and registerOnFinishCallback().
shutdown_
std::atomic_bool dyno::DataProvider::shutdown_ = {false} protected
Definition at line 131 of file DataProvider.hpp.
Referenced by shutdown().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/dataprovider/DataProvider.hpp
dynosam/src/dataprovider/DataProvider.cc