DynoSAM: dyno::byte_track::KalmanFilter Class Reference
dyno::byte_track::KalmanFilter Class Reference
#include <KalmanFilter.hpp>
Public Types
template<int rows, int cols>
using Matrix = Eigen::Matrix< float, rows, cols, Eigen::RowMajor >
Public Member Functions
KalmanFilter (float std_weight_position=1./20, float std_weight_velocity=1./160)
void initiate (const RectBase &measurement)
TlwhRect predict (bool mean_eight_to_zero)
TlwhRect update (const RectBase &measurement)
Private Member Functions
void project (Matrix< 1, 4 > &projected_mean, Matrix< 4, 4 > &projected_covariance)
Matrix< 1, 4 > rect_to_xyah (const RectBase &rect) const
TlwhRect xyah_to_tlwh (const Matrix< 1, 4 > &xyah) const
Private Attributes
float std_weight_position_
float std_weight_velocity_
Matrix< 8, 8 > motion_mat_
Matrix< 4, 8 > update_mat_
Matrix< 1, 8 > mean_
Matrix< 8, 8 > covariance_
Detailed Description
Definition at line 32 of file KalmanFilter.hpp.
Member Typedef Documentation
Matrix
template<int rows, int cols> using dyno::byte_track::KalmanFilter::Matrix = Eigen::Matrix<float, rows, cols, Eigen::RowMajor>
Definition at line 35 of file KalmanFilter.hpp.
Constructor & Destructor Documentation
KalmanFilter()
dyno::byte_track::KalmanFilter::KalmanFilter (float std_weight_position = 1. / 20, float std_weight_velocity = 1. / 160)
Definition at line 33 of file KalmanFilter.cc.
    : std_weight_position_(std_weight_position),
      std_weight_velocity_(std_weight_velocity) {
  motion_mat_ = Eigen::MatrixXf::Identity(8, 8);
  motion_mat_.block<4, 4>(0, 4) = Eigen::Matrix4f::Identity();
  update_mat_ = Eigen::MatrixXf::Identity(4, 8);
}
References motion_mat_, and update_mat_.
Member Function Documentation
initiate()
void dyno::byte_track::KalmanFilter::initiate (const RectBase & measurement)
Definition at line 41 of file KalmanFilter.cc.
{
  mean_.block<1, 4>(0, 0) = rect_to_xyah(measurement);
  mean_.block<1, 4>(0, 4) = Eigen::Vector4f::Zero();
  Matrix<1, 8> std;
  std(0) = 2 * std_weight_position_ * measurement.height();
  std(1) = 2 * std_weight_position_ * measurement.height();
  std(2) = 1e-2;
  std(3) = 2 * std_weight_position_ * measurement.height();
  std(4) = 10 * std_weight_velocity_ * measurement.height();
  std(5) = 10 * std_weight_velocity_ * measurement.height();
  std(6) = 1e-5;
  std(7) = 10 * std_weight_velocity_ * measurement.height();
  Matrix<1, 8> tmp = std.array().square();
  covariance_ = tmp.asDiagonal();
}
References covariance_, dyno::byte_track::RectBase::height(), mean_, rect_to_xyah(), std_weight_position_, and std_weight_velocity_.
Referenced by dyno::byte_track::Track::Track().
predict()
TlwhRect dyno::byte_track::KalmanFilter::predict (bool mean_eight_to_zero)
Definition at line 59 of file KalmanFilter.cc.
{
  if (mean_eight_to_zero) mean_[7] = 0;
  Matrix<1, 8> std;
  std(0) = std_weight_position_ * mean_(3);
  std(1) = std_weight_position_ * mean_(3);
  std(2) = 1e-2;
  std(3) = std_weight_position_ * mean_(3);
  std(4) = std_weight_velocity_ * mean_(3);
  std(5) = std_weight_velocity_ * mean_(3);
  std(6) = 1e-5;
  std(7) = std_weight_velocity_ * mean_(3);
  Matrix<1, 8> tmp = std.array().square();
  Matrix<8, 8> motion_cov = tmp.asDiagonal();
  mean_ = motion_mat_ * mean_.transpose();
  covariance_ =
      motion_mat_ * covariance_ * motion_mat_.transpose() + motion_cov;
  return xyah_to_tlwh(mean_.block<1, 4>(0, 0));
}
References covariance_, mean_, motion_mat_, std_weight_position_, std_weight_velocity_, and xyah_to_tlwh().
Referenced by dyno::byte_track::Track::predict().
project()
void dyno::byte_track::KalmanFilter::project (Matrix< 1, 4 > & projected_mean, Matrix< 4, 4 > & projected_covariance) private
Definition at line 99 of file KalmanFilter.cc.
{
  Matrix<1, 4> std{std_weight_position_ * mean_(3),
                   std_weight_position_ * mean_(3), 1e-1,
                   std_weight_position_ * mean_(3)};
  projected_mean = update_mat_ * mean_.transpose();
  projected_covariance = update_mat_ * covariance_ * update_mat_.transpose();
  Eigen::Matrix<float, 4, 4> diag = std.asDiagonal();
  projected_covariance += diag.array().square().matrix();
}
References covariance_, mean_, std_weight_position_, and update_mat_.
Referenced by update().
rect_to_xyah()
KalmanFilter::Matrix< 1, 4 > dyno::byte_track::KalmanFilter::rect_to_xyah (const RectBase & rect) const private
Definition at line 112 of file KalmanFilter.cc.
{
  return Matrix<1, 4>{rect.left() + rect.width() / 2,
                      rect.top() + rect.height() / 2,
                      rect.width() / rect.height(), rect.height()};
}
References dyno::byte_track::RectBase::height(), dyno::byte_track::RectBase::left(), dyno::byte_track::RectBase::top(), and dyno::byte_track::RectBase::width().
Referenced by initiate(), and update().
update()
TlwhRect dyno::byte_track::KalmanFilter::update (const RectBase & measurement)
Definition at line 80 of file KalmanFilter.cc.
{
  Matrix<1, 4> projected_mean;
  Matrix<4, 4> projected_cov;
  project(projected_mean, projected_cov);
  Eigen::Matrix<float, 4, 8> B =
      (covariance_ * update_mat_.transpose()).transpose();
  Eigen::Matrix<float, 8, 4> kalman_gain =
      (projected_cov.llt().solve(B)).transpose();
  Eigen::Matrix<float, 1, 4> innovation =
      rect_to_xyah(measurement) - projected_mean;
  const auto tmp = innovation * kalman_gain.transpose();
  mean_ = (mean_.array() + tmp.array()).matrix();
  covariance_ =
      covariance_ - kalman_gain * projected_cov * kalman_gain.transpose();
  return xyah_to_tlwh(mean_.block<1, 4>(0, 0));
}
References covariance_, mean_, project(), rect_to_xyah(), update_mat_, and xyah_to_tlwh().
Referenced by dyno::byte_track::Track::update().
xyah_to_tlwh()
TlwhRect dyno::byte_track::KalmanFilter::xyah_to_tlwh (const Matrix< 1, 4 > & xyah) const private
Definition at line 119 of file KalmanFilter.cc.
{
  float xyah_width = xyah(2) * xyah(3);
  return TlwhRect{xyah(1) - xyah(3) / 2, xyah(0) - xyah_width / 2, xyah_width,
                  xyah(3)};
}
Referenced by predict(), and update().
Member Data Documentation
covariance_
Matrix<8, 8> dyno::byte_track::KalmanFilter::covariance_ private
Definition at line 54 of file KalmanFilter.hpp.
Referenced by initiate(), predict(), project(), and update().
mean_
Matrix<1, 8> dyno::byte_track::KalmanFilter::mean_ private
Definition at line 53 of file KalmanFilter.hpp.
Referenced by initiate(), predict(), project(), and update().
motion_mat_
Matrix<8, 8> dyno::byte_track::KalmanFilter::motion_mat_ private
Definition at line 50 of file KalmanFilter.hpp.
Referenced by KalmanFilter(), and predict().
std_weight_position_
float dyno::byte_track::KalmanFilter::std_weight_position_ private
Definition at line 47 of file KalmanFilter.hpp.
Referenced by initiate(), predict(), and project().
std_weight_velocity_
float dyno::byte_track::KalmanFilter::std_weight_velocity_ private
Definition at line 48 of file KalmanFilter.hpp.
Referenced by initiate(), and predict().
update_mat_
Matrix<4, 8> dyno::byte_track::KalmanFilter::update_mat_ private
Definition at line 51 of file KalmanFilter.hpp.
Referenced by KalmanFilter(), project(), and update().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/common/byte_tracker/KalmanFilter.hpp
dynosam/src/common/byte_tracker/KalmanFilter.cc