DynoSAM: dyno::GenericObjectCentricMap< VALUE > Class Template Reference
dyno::GenericObjectCentricMap< VALUE > Class Template Reference
Generic mapping of Object Id to FrameId to VALUE within a nested gtsam::FastMap structure. This is a common datastrcture used to store temporal information about each object.
#include <Types.hpp>
Public Types
using Base = gtsam::FastMap< ObjectId, gtsam::FastMap< FrameId, VALUE > >
using NestedBase = gtsam::FastMap< FrameId, VALUE >
using EstimateMap = gtsam::FastMap< ObjectId, VALUE >
using This = GenericObjectCentricMap< VALUE >
using Value = VALUE
Public Member Functions
operator Base () const
operator typename Base::Base () const
bool insert22 (ObjectId object_id, FrameId frame_id, const Value &value)
Handy insert function allowing direct insertion to the nested map structure.
bool insert2 (FrameId frame_id, const EstimateMap &estimate_map)
bool exists (ObjectId object_id, FrameId frame_id) const
const Value & at (ObjectId object_id, FrameId frame_id) const
Value & at (ObjectId object_id, FrameId frame_id)
This & operator+= (const This &rhs)
gtsam::FastMap< ObjectId, Value > collectByFrame (FrameId frame_id) const
Collect all objects that appear in the query frame, as well as their value.
EstimateMap toEstimateMap (FrameId frame_id) const
ObjectIds gatherInvolvedObjects () const
FrameIds getInvovledFrameIds () const
Private Member Functions
bool existsImpl (ObjectId object_id, FrameId frame_id, size_t &out_of_range_flag) const
Helper function to determine if the query exists. Operates like a regular exists function but also sets out_of_range_flag to indicate which query (object_id or frame_id) is out of range: out_of_range_flag = 0, object_id out of range out_of_range_flag = 1, frame_id out of range out_of_range_flag = 2 both queries exist and the function should return true.
Static Private Member Functions
template<typename Container , typename Return >
static Return atImpl (Container *container, ObjectId object_id, FrameId frame_id)
Detailed Description
template<typename VALUE>
class dyno::GenericObjectCentricMap< VALUE >
Generic mapping of Object Id to FrameId to VALUE within a nested gtsam::FastMap structure. This is a common datastrcture used to store temporal information about each object.
We call it ObjectCentric map as we order by ObjectId first.
Template Parameters
VALUE Value type to be stored
Definition at line 523 of file Types.hpp.
Member Typedef Documentation
Base
template<typename VALUE > using dyno::GenericObjectCentricMap< VALUE >::Base = gtsam::FastMap<ObjectId, gtsam::FastMap<FrameId, VALUE> >
Definition at line 526 of file Types.hpp.
EstimateMap
template<typename VALUE > using dyno::GenericObjectCentricMap< VALUE >::EstimateMap = gtsam::FastMap<ObjectId, VALUE>
Definition at line 528 of file Types.hpp.
NestedBase
template<typename VALUE > using dyno::GenericObjectCentricMap< VALUE >::NestedBase = gtsam::FastMap<FrameId, VALUE>
Definition at line 527 of file Types.hpp.
This
template<typename VALUE > using dyno::GenericObjectCentricMap< VALUE >::This = GenericObjectCentricMap<VALUE>
Definition at line 530 of file Types.hpp.
Value
template<typename VALUE > using dyno::GenericObjectCentricMap< VALUE >::Value = VALUE
Definition at line 531 of file Types.hpp.
Member Function Documentation
at() [1/2]
template<typename VALUE > Value & dyno::GenericObjectCentricMap< VALUE >::at (ObjectId object_id, FrameId frame_id) inline
Definition at line 582 of file Types.hpp.
{
    return atImpl<This, Value&>(const_cast<This*>(this), object_id, frame_id);
  }
at() [2/2]
template<typename VALUE > const Value & dyno::GenericObjectCentricMap< VALUE >::at (ObjectId object_id, FrameId frame_id) const inline
Definition at line 578 of file Types.hpp.
{
    return atImpl<const This, const Value&>(this, object_id, frame_id);
  }
Referenced by dyno::DSDTransport::constructMultiObjectOdometryPaths(), dyno::DSDTransport::constructObjectOdometries(), dyno::GenericObjectCentricMap< VALUE >::existsImpl(), dyno::AccessorT< MAP, DerivedAccessor >::getObjectMotions(), dyno::AccessorT< MAP, DerivedAccessor >::getObjectPoses(), dyno::GenericObjectCentricMap< VALUE >::insert22(), dyno::FrontendInbuiltDisplayRos::processRGBDOutputpacket(), and dyno::propogateObjectPoses().
atImpl()
template<typename VALUE > template<typename Container , typename Return > static Return dyno::GenericObjectCentricMap< VALUE >::atImpl (Container * container, ObjectId object_id, FrameId frame_id) inline static private
Definition at line 638 of file Types.hpp.
{
    size_t out_of_range_flag;
    const bool result =
        container->existsImpl(object_id, frame_id, out_of_range_flag);
    if (result) {
      CHECK_EQ(out_of_range_flag, 2u);
      return container->at(object_id).at(frame_id);
    } else {
      std::stringstream ss;
      ss << "Index out of range: "
         << ((out_of_range_flag == 0) ? " object id " : " frame id")
         << " missing. Full query - (object id " << object_id << ", frame id "
         << frame_id << ").";
      throw std::out_of_range(ss.str());
    }
  }
collectByFrame()
template<typename VALUE > gtsam::FastMap< ObjectId, Value > dyno::GenericObjectCentricMap< VALUE >::collectByFrame (FrameId frame_id) const inline
Collect all objects that appear in the query frame, as well as their value.
Parameters
frame_id FrameId
Returns
gtsam::FastMap<ObjectId, Value>
Definition at line 601 of file Types.hpp.
{
    return this->toEstimateMap(frame_id);
  }
References dyno::GenericObjectCentricMap< VALUE >::toEstimateMap().
Referenced by dyno::RGBDInstanceFrontendModule::createTrackingImage(), dyno::WorldMotionAccessor::getObjectPoses(), and dyno::WorldMotionAccessor::refreshPoseCache().
exists()
template<typename VALUE > bool dyno::GenericObjectCentricMap< VALUE >::exists (ObjectId object_id, FrameId frame_id) const inline
Definition at line 573 of file Types.hpp.
{
    static size_t out_of_range_flag;
    return existsImpl(object_id, frame_id, out_of_range_flag);
  }
References dyno::GenericObjectCentricMap< VALUE >::existsImpl().
Referenced by dyno::DSDTransport::constructMultiObjectOdometryPaths(), dyno::DSDTransport::constructObjectOdometries(), dyno::GenericObjectCentricMap< VALUE >::existsImpl(), dyno::AccessorT< MAP, DerivedAccessor >::getObjectMotions(), dyno::AccessorT< MAP, DerivedAccessor >::getObjectPoses(), dyno::GenericObjectCentricMap< VALUE >::insert22(), and dyno::propogateObjectPoses().
existsImpl()
template<typename VALUE > bool dyno::GenericObjectCentricMap< VALUE >::existsImpl (ObjectId object_id, FrameId frame_id, size_t & out_of_range_flag) const inline private
Helper function to determine if the query exists. Operates like a regular exists function but also sets out_of_range_flag to indicate which query (object_id or frame_id) is out of range: out_of_range_flag = 0, object_id out of range out_of_range_flag = 1, frame_id out of range out_of_range_flag = 2 both queries exist and the function should return true.
Parameters
object_id
frame_id
out_of_range_flag
Returns
true
false
Definition at line 671 of file Types.hpp.
{
    if (!this->exists(object_id)) {
      out_of_range_flag = 0;
      return false;
    }
    const auto& frame_map = this->at(object_id);
    if (!frame_map.exists(frame_id)) {
      out_of_range_flag = 1;
      return false;
    } else {
      out_of_range_flag = 2;
      return true;
    }
  }
References dyno::GenericObjectCentricMap< VALUE >::at(), and dyno::GenericObjectCentricMap< VALUE >::exists().
Referenced by dyno::GenericObjectCentricMap< VALUE >::exists().
gatherInvolvedObjects()
template<typename VALUE > ObjectIds dyno::GenericObjectCentricMap< VALUE >::gatherInvolvedObjects () const inline
Definition at line 615 of file Types.hpp.
{
    ObjectIds object_ids;
    object_ids.reserve(this->size());
    for (const auto& [object_id, _] : *this) {
      object_ids.emplace_back(object_id);
    }
    return object_ids;
  }
getInvovledFrameIds()
template<typename VALUE > FrameIds dyno::GenericObjectCentricMap< VALUE >::getInvovledFrameIds () const inline
Definition at line 626 of file Types.hpp.
{
    FrameIds frame_ids;
    for (const auto& [_, frame_map] : *this) {
      for (const auto& [frame_id, _] : frame_map) {
        frame_ids.push_back(frame_id);
      }
    }
    return frame_ids;
  }
insert2()
template<typename VALUE > bool dyno::GenericObjectCentricMap< VALUE >::insert2 (FrameId frame_id, const EstimateMap & estimate_map) inline
Definition at line 565 of file Types.hpp.
{
    bool result = true;
    for (const auto& [object_id, estimate_value] : estimate_map) {
      result &= this->insert22(object_id, frame_id, estimate_value);
    }
    return result;
  }
References dyno::GenericObjectCentricMap< VALUE >::insert22().
Referenced by dyno::AccessorT< MAP, DerivedAccessor >::getObjectMotions(), dyno::AccessorT< MAP, DerivedAccessor >::getObjectPoses(), dyno::WorldMotionAccessor::getObjectPoses(), dyno::GenericObjectCentricMap< VALUE >::insert22(), dyno::propogateObjectPoses(), dyno::FrontendDSDRos::tryPublishGroundTruth(), and dyno::FrontendDSDRos::updateAccumulatedDataStructured().
insert22()
template<typename VALUE > bool dyno::GenericObjectCentricMap< VALUE >::insert22 (ObjectId object_id, FrameId frame_id, const Value & value) inline
Handy insert function allowing direct insertion to the nested map structure.
Parameters
object_id
frame_id
value
Returns
true
false
Definition at line 555 of file Types.hpp.
{
    if (!this->exists(object_id)) {
      this->insert2(object_id, NestedBase{});
    }
    NestedBase& frame_map = this->at(object_id);
    return frame_map.insert2(frame_id, value);
  }
References dyno::GenericObjectCentricMap< VALUE >::at(), dyno::GenericObjectCentricMap< VALUE >::exists(), and dyno::GenericObjectCentricMap< VALUE >::insert2().
Referenced by dyno::ParallelObjectISAM::getFrame2FrameMotions(), dyno::ParallelObjectISAM::getKeyFramedMotions(), dyno::GenericObjectCentricMap< VALUE >::insert2(), dyno::propogateObjectPoses(), dyno::FrontendInbuiltDisplayRos::publishGroundTruthInfo(), dyno::FrontendDSDRos::tryPublishGroundTruth(), dyno::ObjectMotionSovlerF2F::updateMotions(), dyno::ObjectMotionSolverFilter::updateMotions(), and dyno::ObjectMotionSolverFilter::updatePoses().
operator Base()
template<typename VALUE > dyno::GenericObjectCentricMap< VALUE >::operator Base () const inline
Conversion to a gtsam::FastMap container
Definition at line 539 of file Types.hpp.
{ return Base(this->begin(), this->end()); }
operator typename Base::Base()
template<typename VALUE > dyno::GenericObjectCentricMap< VALUE >::operator typename Base::Base () const inline
Definition at line 541 of file Types.hpp.
{
    return typename Base::Base(this->begin(), this->end());
  }
operator+=()
template<typename VALUE > This & dyno::GenericObjectCentricMap< VALUE >::operator+= (const This & rhs) inline
Definition at line 587 of file Types.hpp.
{
    for (const auto& [key, value] : rhs) {
      this->operator[](key).insert(value.begin(), value.end());
    }
    return *this;
  }
toEstimateMap()
template<typename VALUE > EstimateMap dyno::GenericObjectCentricMap< VALUE >::toEstimateMap (FrameId frame_id) const inline
Definition at line 605 of file Types.hpp.
{
    EstimateMap object_map;
    for (const auto& [object_id, frame_map] : *this) {
      if (frame_map.exists(frame_id)) {
        object_map.insert2(object_id, frame_map.at(frame_id));
      }
    }
    return object_map;
  }
Referenced by dyno::GenericObjectCentricMap< VALUE >::collectByFrame(), and dyno::RGBDInstanceFrontendModule::fillOutputPacketWithTracks().
The documentation for this class was generated from the following file:
dynosam_common/include/dynosam_common/Types.hpp