DynoSAM: dyno::Formulation< MAP > Class Template Reference
dyno::Formulation< MAP > Class Template Reference abstract
Base class for a formulation that defines the structure and implementation for a factor-graph based Dynamic SLAM solution. Derived formulations construct the specific factor-graph which are solved independandtly to the formulation. The formulation is responsible for the construction of a single factor-graph with a single set of initial values and has an associated Accessor which knows how to extract these values into a common format. In the DynoSAM paper, this is referred to as the \mathbf{O}_k, which is the output of the backend. See Accessor.hpp for more details.
#include <Formulation.hpp>
Public Types
using Map = MAP
using This = Formulation< Map >
using MapTraitsType = MapTraits< Map >
using MeasurementType = typename MapTraitsType::MeasurementType
using MeasurementTraits = measurement_traits< MeasurementType >
using PointUpdateContextType = PointUpdateContext< Map >
using ObjectUpdateContextType = ObjectUpdateContext< Map >
using AccessorType = Accessor< MAP >
using AccessorTypePointer = typename Accessor< MAP >::Ptr
Public Member Functions
Formulation (const FormulationParams &params, typename Map::Ptr map, const NoiseModels &noise_models, const FormulationHooks &hooks=FormulationHooks())
virtual ~Formulation ()=default
Map::Ptr map () const
Get the map used by the formulation.
const gtsam::Values & getTheta () const
Get the current linearization point for this formulation. These values can be updated after external optimisation and are constructed by the derived formulation during update.
void setTheta (const gtsam::Values &linearization)
Sets the full set of theta values (overrides them). This is used after external optimisation to update the values for the accessor which has a internal reference (pointer) to theta.
void updateTheta (const gtsam::Values &linearization)
Updates and assigns new values to theta. This is used after external optimisation to update the values for the accessor which has a internal reference (pointer) to theta.
const gtsam::NonlinearFactorGraph & getGraph () const
Gets the current graph associated with the current theta and constructed by the derived formulation. Along theta, this should be used by an external optimisation routine.
const FormulationHooks & hooks () const
const NoiseModels & noiseModels () const
virtual gtsam::KeyFormatter formatter () const
Custom gtsam::Key formatter for this formulation. Defaults to DynoLikeKeyFormatter.
const std::string getFullyQualifiedName () const
Get the fully qualified name of this formulation which is derived from the loggerPrefix and optionally the FormulationParams::suffix if given.
AccessorType::Ptr accessorFromTheta () const
Public fucntion to access the Accessor for the derived formulation.
template<typename Derived >
std::shared_ptr< Derived > derivedAccessor () const
BackendLogger::UniquePtr makeFullyQualifiedLogger () const
Makes a logger using the fully-qualified name for this formulation.
void addValuesFunctional (std::function< void(gtsam::Values &)> callback, gtsam::Values &new_values)
void addFactorsFunctional (std::function< void(gtsam::NonlinearFactorGraph &)> callback, gtsam::NonlinearFactorGraph &new_factors)
void addSensorPoseValue (const gtsam::Pose3 &X_W_k, FrameId frame_id_k, gtsam::Values &new_values)
void addSensorPosePriorFactor (const gtsam::Pose3 &X_W_k, gtsam::SharedNoiseModel noise_model, FrameId frame_id_k, gtsam::NonlinearFactorGraph &new_factors)
void setInitialPose (const gtsam::Pose3 &T_world_camera, FrameId frame_id_k, gtsam::Values &new_values)
Adds a gtsam::Pose3 as a value in the graph at frame k.
void setInitialPosePrior (const gtsam::Pose3 &T_world_camera, FrameId frame_id_k, gtsam::NonlinearFactorGraph &new_factors)
Adds a pose prior on a value in the graph at frame k using the given pose value as the prior's mean.
UpdateObservationResult updateStaticObservations (FrameId from_frame, FrameId to_frame, gtsam::Values &new_values, gtsam::NonlinearFactorGraph &new_factors, const UpdateObservationParams &update_params)
Update the static-point part of the factor graph between multiple frames. Internally makes several calls to updateStaticObservations(FrameId,gtsam::Values&,gtsam::NonlinearFactorGraph&,const UpdateObservationParams&) and returns the accumulated UpdateObservationResult.
UpdateObservationResult updateDynamicObservations (FrameId from_frame, FrameId to_frame, gtsam::Values &new_values, gtsam::NonlinearFactorGraph &new_factors, const UpdateObservationParams &update_params)
Update the dynamic-point part of the factor graph between multiple frames. Internally makes several calls to updateDynamicObservations(FrameId,gtsam::Values&,gtsam::NonlinearFactorGraph&,const UpdateObservationParams&) and returns the accumulated UpdateObservationResult.
UpdateObservationResult updateStaticObservations (FrameId frame_id_k, gtsam::Values &new_values, gtsam::NonlinearFactorGraph &new_factors, const UpdateObservationParams &update_params)
Updates the static-point part of the factor graph for frame k. This contains all the bookeeping logic to update the factor graph with static points.
UpdateObservationResult updateDynamicObservations (FrameId frame_id_k, gtsam::Values &new_values, gtsam::NonlinearFactorGraph &new_factors, const UpdateObservationParams &update_params)
Updates the dyanmic-point part of the factor graph for frame k. This contains all the big-boi bookeeping logic to update the factor graph with dyanmic points and objects. This is where the virtual dynamicPointUpdateCallback and objectUpdateContext functions are called.
void logBackendFromMap (const BackendMetaData &backend_info)
Logs all frames and values to file using Accessor and BackendLogger. The BackendMetaData provides meta-data and ground truth information for logging.
virtual void preUpdate (const PreUpdateData &)
Pre update hook called in the RegularBackend after the map is updated with new measurements but before new values/factors are constructed from this formulation.
virtual void postUpdate (const PostUpdateData &)
Post-update hook called in the RegulatBackend after graph construction and optimization!
Protected Member Functions
virtual void dynamicPointUpdateCallback (const PointUpdateContextType &context, UpdateObservationResult &result, gtsam::Values &new_values, gtsam::NonlinearFactorGraph &new_factors)=0
Virtual function to be implemented by derived class and indicates that a specific landmark has new measurements and new values/factors should be added. Details on the landmark to be updated are provied by the context. In general, this is used to add projection/motion factors and initial values for landmarks.
virtual void objectUpdateContext (const ObjectUpdateContextType &context, UpdateObservationResult &result, gtsam::Values &new_values, gtsam::NonlinearFactorGraph &new_factors)=0
Virtual function to be implemented by derived class and indicates that a specific object j and time-step k has been observed and its dynamic points updated in the graph, and associated values/factors should be added. Details on the object to be updated are provied by the context. In general, this is used to add smoothing factors and initial values for object motion/pose.
virtual bool isDynamicTrackletInMap (const typename MapTraitsType::LandmarkNodePtr &lmk_node) const =0
Virtual function to be implemented by derived class and indicates that the specified landmark exists within the graph already. This is used as part of the internal bookeeping.
virtual std::string loggerPrefix () const =0
Defines the base name of this formulation. This name will appear as part of the output logs and may be augmented with the FormulationParams::suffix, if given. To get the fully qualified name (the actual name that will appear in the logs), use This::getFullyQualifiedName().
virtual AccessorType::Ptr createAccessor (const SharedFormulationData &shared_data) const =0
Creates the associated Accessor for the derived formulation. The accessor will contain a pointer to This::theta_, so that when the values are updated the accessor has access to the latest values.
gtsam::Pose3 getInitialOrLinearizedSensorPose (FrameId frame_id) const
void clearGraph ()
Protected Attributes
const FormulationParams params_
Map::Ptr map_
const NoiseModels noise_models_
FormulationHooks hooks_
gtsam::FastMap< gtsam::Key, bool > is_other_values_in_map
gtsam::Values theta_
Current linearisation that will be associated with the current graph.
gtsam::NonlinearFactorGraph factors_
Private Member Functions
std::string setFullyQualifiedName () const
Private Attributes
AccessorType::Ptr accessor_theta_
std::optional< std::string > fully_qualified_name_ {std::nullopt}
Detailed Description
template<typename MAP>
class dyno::Formulation< MAP >
Base class for a formulation that defines the structure and implementation for a factor-graph based Dynamic SLAM solution. Derived formulations construct the specific factor-graph which are solved independandtly to the formulation. The formulation is responsible for the construction of a single factor-graph with a single set of initial values and has an associated Accessor which knows how to extract these values into a common format. In the DynoSAM paper, this is referred to as the \mathbf{O}_k, which is the output of the backend. See Accessor.hpp for more details.
The base formulation manages all high-level book keeping associated with any Dynamic SLAM factor graph and decided when points and objects should be added to the graph in a general sense (e.g. points must be seen multiple times, has this point already been added the graph in a general way). This is achieved in two ways:
Key virtual functions which provides the base formulation with some knowledge of the dervied formulations actions and
Access to the MAP which defines the structure of frames, objects and points directly from measurements.
At a high-level the formulation has the following functionalities:
Addition of odometry and pose priors
Static point updates (which adds factors and values for static points)
Dynamic point updates (which adds factors and values for dynamic points AND dynamic objects).
The derived class must implement the dynamicPointUpdateCallback and objectUpdateContext pure-virtual functions and updated the UpdateObservationResult,gtsam::Values and gtsam::NonlinearFactorGraph objects based on the additional context that is parsed in. The context is build by the base-formulation class as part of the high-level bookeeping and indicates that this dynamic point/object has new observations associated with it and therefore new values/factors should be added. The new values/factors will eventually be added to the base-formualtions internal theta_ and factors_. These virtual functions are called in the corresponding update static/dynamic observation functions when the base class has determined new obsevrations have occurned.
Template Parameters
MAP
Definition at line 215 of file Formulation.hpp.
Member Typedef Documentation
AccessorType
template<typename MAP > using dyno::Formulation< MAP >::AccessorType = Accessor<MAP>
Definition at line 226 of file Formulation.hpp.
AccessorTypePointer
template<typename MAP > using dyno::Formulation< MAP >::AccessorTypePointer = typename Accessor<MAP>::Ptr
Definition at line 227 of file Formulation.hpp.
Map
template<typename MAP > using dyno::Formulation< MAP >::Map = MAP
Definition at line 217 of file Formulation.hpp.
MapTraitsType
template<typename MAP > using dyno::Formulation< MAP >::MapTraitsType = MapTraits<Map>
Definition at line 219 of file Formulation.hpp.
MeasurementTraits
template<typename MAP > using dyno::Formulation< MAP >::MeasurementTraits = measurement_traits<MeasurementType>
Definition at line 222 of file Formulation.hpp.
MeasurementType
template<typename MAP > using dyno::Formulation< MAP >::MeasurementType = typename MapTraitsType::MeasurementType
Definition at line 220 of file Formulation.hpp.
ObjectUpdateContextType
template<typename MAP > using dyno::Formulation< MAP >::ObjectUpdateContextType = ObjectUpdateContext<Map>
Definition at line 225 of file Formulation.hpp.
PointUpdateContextType
template<typename MAP > using dyno::Formulation< MAP >::PointUpdateContextType = PointUpdateContext<Map>
Definition at line 224 of file Formulation.hpp.
This
template<typename MAP > using dyno::Formulation< MAP >::This = Formulation<Map>
Definition at line 218 of file Formulation.hpp.
Constructor & Destructor Documentation
Formulation()
template<typename MAP > dyno::Formulation< MAP >::Formulation (const FormulationParams & params, typename Map::Ptr map, const NoiseModels & noise_models, const FormulationHooks & hooks = FormulationHooks())
Definition at line 41 of file Formulation-impl.hpp.
    : params_(params), map_(map), noise_models_(noise_models), hooks_(hooks) {}
~Formulation()
template<typename MAP > virtual dyno::Formulation< MAP >::~Formulation () virtual default
Member Function Documentation
accessorFromTheta()
template<typename MAP > Formulation< MAP >::AccessorType::Ptr dyno::Formulation< MAP >::accessorFromTheta
Public fucntion to access the Accessor for the derived formulation.
Returns
AccessorType::Ptr
Definition at line 675 of file Formulation-impl.hpp.
{
  if (!accessor_theta_) {
    SharedFormulationData shared_data(&theta_, &hooks_);
    accessor_theta_ = createAccessor(shared_data);
  }
  return accessor_theta_;
}
Referenced by dyno::RegularBackendModule::constructOutputPacket(), and dyno::RegularBackendModule::nominalSpinImpl().
addFactorsFunctional()
template<typename MAP > void dyno::Formulation< MAP >::addFactorsFunctional (std::function< void(gtsam::NonlinearFactorGraph &)> callback, gtsam::NonlinearFactorGraph & new_factors)
Definition at line 106 of file Formulation-impl.hpp.
{
  gtsam::NonlinearFactorGraph internal_new_factors;
  callback(internal_new_factors);
  new_factors += internal_new_factors;
  factors_ += internal_new_factors;
}
addSensorPosePriorFactor()
template<typename MAP > void dyno::Formulation< MAP >::addSensorPosePriorFactor (const gtsam::Pose3 & X_W_k, gtsam::SharedNoiseModel noise_model, FrameId frame_id_k, gtsam::NonlinearFactorGraph & new_factors)
Definition at line 117 of file Formulation-impl.hpp.
{
  // keep track of the new factors added in this function
  // these are then appended to the internal factors_ and new_factors
  gtsam::NonlinearFactorGraph internal_new_factors;
  internal_new_factors.addPrior(CameraPoseSymbol(frame_id_k), X_W_k,
                                noise_model);
  new_factors += internal_new_factors;
  factors_ += internal_new_factors;
}
References dyno::CameraPoseSymbol().
addSensorPoseValue()
template<typename MAP > void dyno::Formulation< MAP >::addSensorPoseValue (const gtsam::Pose3 & X_W_k, FrameId frame_id_k, gtsam::Values & new_values)
Definition at line 85 of file Formulation-impl.hpp.
{
  gtsam::Values values;
  values.insert(CameraPoseSymbol(frame_id_k), X_W_k);
  new_values.insert_or_assign(values);
  theta_.insert_or_assign(values);
}
References dyno::CameraPoseSymbol().
addValuesFunctional()
template<typename MAP > void dyno::Formulation< MAP >::addValuesFunctional (std::function< void(gtsam::Values &)> callback, gtsam::Values & new_values)
Definition at line 96 of file Formulation-impl.hpp.
{
  gtsam::Values internal_new_values;
  callback(internal_new_values);
  new_values.insert_or_assign(internal_new_values);
  theta_.insert_or_assign(internal_new_values);
}
clearGraph()
template<typename MAP > void dyno::Formulation< MAP >::clearGraph () inline protected
Definition at line 569 of file Formulation.hpp.
{ factors_.resize(0); }
References dyno::Formulation< MAP >::factors_.
createAccessor()
template<typename MAP > virtual AccessorType::Ptr dyno::Formulation< MAP >::createAccessor (const SharedFormulationData & shared_data) const protected pure virtual
Creates the associated Accessor for the derived formulation. The accessor will contain a pointer to This::theta_, so that when the values are updated the accessor has access to the latest values.
Parameters
values const gtsam::Values*
Returns
AccessorType::Ptr
Implemented in dyno::HybridFormulation, dyno::test_hybrid::SmartStructurlessFormulation, dyno::WorldMotionFormulation, and dyno::WorldPoseFormulation.
derivedAccessor()
template<typename MAP > template<typename Derived > std::shared_ptr< Derived > dyno::Formulation< MAP >::derivedAccessor () const inline
Definition at line 421 of file Formulation.hpp.
{
    if (!accessor_theta_) {
      return nullptr;
    }
    return std::dynamic_pointer_cast<Derived>(accessor_theta_);
  }
References dyno::Formulation< MAP >::accessor_theta_.
dynamicPointUpdateCallback()
template<typename MAP > virtual void dyno::Formulation< MAP >::dynamicPointUpdateCallback (const PointUpdateContextType & context, UpdateObservationResult & result, gtsam::Values & new_values, gtsam::NonlinearFactorGraph & new_factors) protected pure virtual
Virtual function to be implemented by derived class and indicates that a specific landmark has new measurements and new values/factors should be added. Details on the landmark to be updated are provied by the context. In general, this is used to add projection/motion factors and initial values for landmarks.
This function is called when, for a frame k, a point has new measurements (from the front-end) and the point is well-tracked (e.g has been seen at least n times).
If the point is new the gtsam::Values should be updated and gtsam::NonlinearFactorGraph should be updated with new factors. Note that the PointUpdateContextType is constructed in-terms of a MOTION so that information is provided about the k-1 and k'th observation. In the case that this point is first observed, this construction means that the point has been seen twice (at k-1 and k).
UpdateObservationResult MUST also be updated if a new value or factor is added as this tells the base formulation that new information has been added to the graph. The result is used to determine which object's to then form a ObjectUpdateContextType for.
This function should also set any internal logic to ensure that after a new point has been initalised/added, isDynamicTrackletInMap returns true as this is used internally.
For all factor-graph construction functions, all functions additionally return (via out-args) all new factors and values added during the function. These new values/factors will ALSO be added to the internal theta_/factors_. This allows the Formulation to be used for batch optimisation, by accessing the full graph (getTheta(), getGraph()) or incremental optimisation by updating the incremental optimser using just the new values/factors returned from the update functions.
NOTE all point update callbacks are triggered before any objectUpdateContext, although the order is arbitrary.
Parameters
context const PointUpdateContextType&
result UpdateObservationResult&
new_values gtsam::Values&
new_factors gtsam::NonlinearFactorGraph&
formatter()
template<typename MAP > virtual gtsam::KeyFormatter dyno::Formulation< MAP >::formatter () const inline virtual
Custom gtsam::Key formatter for this formulation. Defaults to DynoLikeKeyFormatter.
Returns
gtsam::KeyFormatter
Definition at line 400 of file Formulation.hpp.
{ return DynoLikeKeyFormatter; }
References dyno::DynoLikeKeyFormatter().
getFullyQualifiedName()
template<typename MAP > const std::string dyno::Formulation< MAP >::getFullyQualifiedName () const inline
Get the fully qualified name of this formulation which is derived from the loggerPrefix and optionally the FormulationParams::suffix if given.
Returns
const std::string
Definition at line 409 of file Formulation.hpp.
{
    return fully_qualified_name_.value_or(setFullyQualifiedName());
  }
References dyno::Formulation< MAP >::fully_qualified_name_, and dyno::Formulation< MAP >::setFullyQualifiedName().
Referenced by dyno::RegularBackendModule::logIncrementalStats(), dyno::RegularBackendModule::nominalSpinImpl(), dyno::RegularBackendModule::updateBatch(), and dyno::RegularBackendModule::updateIncremental().
getGraph()
template<typename MAP > const gtsam::NonlinearFactorGraph & dyno::Formulation< MAP >::getGraph () const inline
Gets the current graph associated with the current theta and constructed by the derived formulation. Along theta, this should be used by an external optimisation routine.
Returns
const gtsam::NonlinearFactorGraph&
Definition at line 389 of file Formulation.hpp.
{ return factors_; }
References dyno::Formulation< MAP >::factors_.
Referenced by dyno::RegularBackendModule::updateBatch().
getInitialOrLinearizedSensorPose()
template<typename MAP > gtsam::Pose3 dyno::Formulation< MAP >::getInitialOrLinearizedSensorPose (FrameId frame_id) const protected
Definition at line 64 of file Formulation-impl.hpp.
{
  const auto accessor = this->accessorFromTheta();
  // sensor pose from a previous/current linearisation point
  StateQuery<gtsam::Pose3> X_k_theta = accessor->getSensorPose(frame_id);
  gtsam::Pose3 X_k_initial;
  CHECK(this->map()->hasInitialSensorPose(frame_id, &X_k_initial));
  // take either the query value from the map (if we have a previous
  // initalisation), or the estimate from the camera
  gtsam::Pose3 X_k;
  getSafeQuery(X_k, X_k_theta, X_k_initial);
  return X_k;
}
References dyno::getSafeQuery().
getTheta()
template<typename MAP > const gtsam::Values & dyno::Formulation< MAP >::getTheta () const inline
Get the current linearization point for this formulation. These values can be updated after external optimisation and are constructed by the derived formulation during update.
Returns
const gtsam::Values&
Definition at line 362 of file Formulation.hpp.
{ return theta_; }
References dyno::Formulation< MAP >::theta_.
Referenced by dyno::RegularBackendModule::updateBatch().
hooks()
template<typename MAP > const FormulationHooks & dyno::Formulation< MAP >::hooks () const inline
Definition at line 391 of file Formulation.hpp.
{ return hooks_; }
References dyno::Formulation< MAP >::hooks_.
isDynamicTrackletInMap()
template<typename MAP > virtual bool dyno::Formulation< MAP >::isDynamicTrackletInMap (const typename MapTraitsType::LandmarkNodePtr & lmk_node) const protected pure virtual
Virtual function to be implemented by derived class and indicates that the specified landmark exists within the graph already. This is used as part of the internal bookeeping.
Parameters
lmk_node typename MapTraitsType::LandmarkNodePtr&. Pointer to a landmark node.
Returns
true
false
logBackendFromMap()
template<typename MAP > void dyno::Formulation< MAP >::logBackendFromMap (const BackendMetaData & backend_info)
Logs all frames and values to file using Accessor and BackendLogger. The BackendMetaData provides meta-data and ground truth information for logging.
Parameters
backend_info const BackendMetaData&
Definition at line 601 of file Formulation-impl.hpp.
{
  // TODO:
  std::string logger_prefix = this->getFullyQualifiedName();
  const std::string suffix = backend_info.logging_suffix;
  // add suffix to name if required
  if (!suffix.empty()) {
    logger_prefix += ("_" + suffix);
  }
  BackendLogger::UniquePtr logger =
      std::make_unique<BackendLogger>(logger_prefix);
  typename Map::Ptr map = this->map();
  auto accessor = this->accessorFromTheta();
  CHECK(hooks().ground_truth_packets_request);
  const auto ground_truth_packets = hooks().ground_truth_packets_request();
  CHECK_NOTNULL(backend_info.backend_params);
  const auto& backend_params = *backend_info.backend_params;
  const ObjectPoseMap object_pose_map = accessor->getObjectPoses();
  for (FrameId frame_k : map->getFrameIds()) {
    // TODO: hack - only go up to frames < full batch so we actually only
    // include the optimised alues
    if (backend_params.use_use_full_batch_opt &&
        backend_params.full_batch_frame - 1 == (int)frame_k) {
      break;
    }
    std::stringstream ss;
    ss << "Logging data from map at frame " << frame_k;
    // get MotionestimateMap
    //  const MotionEstimateMap motions = map->getMotionEstimates(frame_k);
    {
      const MotionEstimateMap motions = accessor->getObjectMotions(frame_k);
      auto result =
          logger->logObjectMotion(frame_k, motions, ground_truth_packets);
      if (result)
        ss << " Logged " << *result << " motions from " << motions.size()
           << " computed motions.";
      else
        ss << " Could not log object motions.";
    }
    StateQuery<gtsam::Pose3> X_k_query = accessor->getSensorPose(frame_k);
    if (X_k_query) {
      logger->logCameraPose(frame_k, X_k_query.get(), ground_truth_packets);
    } else {
      LOG(WARNING) << "Could not log camera pose estimate at frame " << frame_k;
    }
    logger->logObjectPose(frame_k, object_pose_map, ground_truth_packets);
    if (map->frameExists(frame_k)) {
      auto static_map = accessor->getStaticLandmarkEstimates(frame_k);
      auto dynamic_map = accessor->getDynamicLandmarkEstimates(frame_k);
      CHECK(X_k_query);  // actually not needed for points in world!!
      logger->logPoints(frame_k, *X_k_query, static_map);
      logger->logPoints(frame_k, *X_k_query, dynamic_map);
    }
    LOG(INFO) << ss.str();
  }
  logger.reset();
}
References dyno::BackendMetaData::backend_params, dyno::StateQuery< ValueType >::get(), and dyno::BackendMetaData::logging_suffix.
Referenced by dyno::RegularBackendModule::~RegularBackendModule().
loggerPrefix()
template<typename MAP > virtual std::string dyno::Formulation< MAP >::loggerPrefix () const protected pure virtual
Defines the base name of this formulation. This name will appear as part of the output logs and may be augmented with the FormulationParams::suffix, if given. To get the fully qualified name (the actual name that will appear in the logs), use This::getFullyQualifiedName().
Returns
std::string
Implemented in dyno::HybridFormulation, dyno::test_hybrid::StructurelessDecoupledFormulation, dyno::test_hybrid::DecoupledFormulation, dyno::test_hybrid::StructurlessFormulation, dyno::test_hybrid::SmartStructurlessFormulation, dyno::WorldMotionFormulation, and dyno::WorldPoseFormulation.
makeFullyQualifiedLogger()
template<typename MAP > BackendLogger::UniquePtr dyno::Formulation< MAP >::makeFullyQualifiedLogger
Makes a logger using the fully-qualified name for this formulation.
Returns
BackendLogger::UniquePtr
Definition at line 80 of file Formulation-impl.hpp.
{
  return std::make_unique<BackendLogger>(getFullyQualifiedName());
}
map()
template<typename MAP > Map::Ptr dyno::Formulation< MAP >::map () const inline
Get the map used by the formulation.
Returns
Map::Ptr
Definition at line 353 of file Formulation.hpp.
{ return map_; }
References dyno::Formulation< MAP >::map_.
Referenced by dyno::RegularBackendModule::constructOutputPacket().
noiseModels()
template<typename MAP > const NoiseModels & dyno::Formulation< MAP >::noiseModels () const inline
Definition at line 392 of file Formulation.hpp.
{ return noise_models_; }
References dyno::Formulation< MAP >::noise_models_.
objectUpdateContext()
template<typename MAP > virtual void dyno::Formulation< MAP >::objectUpdateContext (const ObjectUpdateContextType & context, UpdateObservationResult & result, gtsam::Values & new_values, gtsam::NonlinearFactorGraph & new_factors) protected pure virtual
Virtual function to be implemented by derived class and indicates that a specific object j and time-step k has been observed and its dynamic points updated in the graph, and associated values/factors should be added. Details on the object to be updated are provied by the context. In general, this is used to add smoothing factors and initial values for object motion/pose.
This function is called when, for a frame k, the object has been seen at least m times and there is at least n points on this object that have new values/factors since the last iteration (as determined by the UpdateObservationResult from dynamicPointUpdateCallback).
NOTE this function is called independanly for all objects and is triggered after all dynamicPointUpdateCallback's been called.
Parameters
context const ObjectUpdateContextType& context
result UpdateObservationResult&
new_values gtsam::Values&
new_factors gtsam::NonlinearFactorGraph&
postUpdate()
template<typename MAP > virtual void dyno::Formulation< MAP >::postUpdate (const PostUpdateData &) inline virtual
Post-update hook called in the RegulatBackend after graph construction and optimization!
Reimplemented in dyno::WorldMotionFormulation, and dyno::RegularHybridFormulation.
Definition at line 564 of file Formulation.hpp.
{};
Referenced by dyno::RegularBackendModule::boostrapSpinImpl(), dyno::RegularBackendModule::nominalSpinImpl(), and dyno::RegularBackendModule::~RegularBackendModule().
preUpdate()
template<typename MAP > virtual void dyno::Formulation< MAP >::preUpdate (const PreUpdateData &) inline virtual
Pre update hook called in the RegularBackend after the map is updated with new measurements but before new values/factors are constructed from this formulation.
Reimplemented in dyno::RegularHybridFormulation.
Definition at line 557 of file Formulation.hpp.
{};
Referenced by dyno::RegularBackendModule::boostrapSpinImpl(), and dyno::RegularBackendModule::nominalSpinImpl().
setFullyQualifiedName()
template<typename MAP > std::string dyno::Formulation< MAP >::setFullyQualifiedName private
Definition at line 684 of file Formulation-impl.hpp.
{
  // get the derived name of the formulation
  std::string logger_prefix = this->loggerPrefix();
  const std::string suffix = params_.suffix;
  // add suffix to name if required
  if (!suffix.empty()) {
    logger_prefix += ("_" + suffix);
  }
  fully_qualified_name_ = logger_prefix;
  return *fully_qualified_name_;
}
Referenced by dyno::Formulation< MAP >::getFullyQualifiedName().
setInitialPose()
template<typename MAP > void dyno::Formulation< MAP >::setInitialPose (const gtsam::Pose3 & T_world_camera, FrameId frame_id_k, gtsam::Values & new_values)
Adds a gtsam::Pose3 as a value in the graph at frame k.
Parameters
T_world_camera const gtsam::Pose3&
frame_id_k FrameId
new_values gtsam::Values&
Definition at line 130 of file Formulation-impl.hpp.
{
  this->addSensorPoseValue(T_world_camera, frame_id_k, new_values);
}
setInitialPosePrior()
template<typename MAP > void dyno::Formulation< MAP >::setInitialPosePrior (const gtsam::Pose3 & T_world_camera, FrameId frame_id_k, gtsam::NonlinearFactorGraph & new_factors)
Adds a pose prior on a value in the graph at frame k using the given pose value as the prior's mean.
Parameters
T_world_camera const gtsam::Pose3&
frame_id_k FrameId
new_factors gtsam::NonlinearFactorGraph&
Definition at line 137 of file Formulation-impl.hpp.
{
  auto initial_pose_prior = noise_models_.initial_pose_prior;
  this->addSensorPosePriorFactor(T_world_camera, initial_pose_prior, frame_id_k,
                                 new_factors);
}
setTheta()
template<typename MAP > void dyno::Formulation< MAP >::setTheta (const gtsam::Values & linearization)
Sets the full set of theta values (overrides them). This is used after external optimisation to update the values for the accessor which has a internal reference (pointer) to theta.
Parameters
linearization const gtsam::Values&
Definition at line 48 of file Formulation-impl.hpp.
{
  theta_ = linearization;
  // TODO: comment backed in!!
  //  accessorFromTheta()->postUpdateCallback();
}
updateDynamicObservations() [1/2]
template<typename MAP > UpdateObservationResult dyno::Formulation< MAP >::updateDynamicObservations (FrameId frame_id_k, gtsam::Values & new_values, gtsam::NonlinearFactorGraph & new_factors, const UpdateObservationParams & update_params)
Updates the dyanmic-point part of the factor graph for frame k. This contains all the big-boi bookeeping logic to update the factor graph with dyanmic points and objects. This is where the virtual dynamicPointUpdateCallback and objectUpdateContext functions are called.
Parameters
frame_id_k
new_values
new_factors
update_params
Returns
UpdateObservationResult
At least three points on the object are required to solve otherise the system is indeterminate
Definition at line 323 of file Formulation-impl.hpp.
{
  typename Map::Ptr map = this->map();
  auto accessor = this->accessorFromTheta();
  // collect noise models to be used
  auto landmark_motion_noise = noise_models_.landmark_motion_noise;
  auto dynamic_point_noise = noise_models_.dynamic_point_noise;
  // keep track of the new factors added in this function
  // these are then appended to the internal factors_ and new_factors
  gtsam::NonlinearFactorGraph internal_new_factors;
  // keep track of the new values added in this function
  // these are then appended to the internal values_ and new_values
  gtsam::Values internal_new_values;
  UpdateObservationResult result(update_params);
  // constexpr static size_t kMinNumberPoints = 3u;
  const FrameId frame_id_k_1 = frame_id_k - 1u;
  VLOG(20) << "Add dynamic observations between frames " << frame_id_k_1
           << " and " << frame_id_k;
  const auto frame_node_k = map->getFrame(frame_id_k);
  const auto frame_node_k_1 = map->getFrame(frame_id_k_1);
  CHECK_NOTNULL(frame_node_k_1);
  // pose estimate from frontend
  // CHECK(parent_->initial_camera_poses_.exists(frame_id_k));
  // const gtsam::Pose3& T_world_camera_initial_k =
  // new_values.at<gtsam::Pose3>(CameraPoseSymbol(frame_id_k));
  utils::TimingStatsCollector dyn_obj_itr_timer(this->loggerPrefix() +
                                                ".dynamic_object_itr");
  for (const auto& object_node : frame_node_k->objects_seen) {
    DebugInfo::ObjectInfo object_debug_info;
    const ObjectId object_id = object_node->getId();
    // first check that object exists in the previous frame
    if (!frame_node_k->objectMotionExpected(object_id)) {
      continue;
    }
    // possibly the longest call?
    // landmarks on this object seen at frame k
    auto seen_lmks_k = object_node->getLandmarksSeenAtFrame(frame_id_k);
    // if we dont have at least N observations of this object in this frame AND
    // the previous frame
    if (seen_lmks_k.size() < params_.min_dynamic_observations ||
        object_node->getLandmarksSeenAtFrame(frame_id_k_1).size() <
            params_.min_dynamic_observations) {
      continue;
    }
    utils::TimingStatsCollector dyn_point_itr_timer(this->loggerPrefix() +
                                                    ".dynamic_point_itr");
    VLOG(10) << "Seen lmks at frame " << frame_id_k << " obj " << object_id
             << ": " << seen_lmks_k.size();
    // iterate over each lmk we have on this object
    for (const auto& obj_lmk_node : seen_lmks_k) {
      CHECK_EQ(obj_lmk_node->getObjectId(), object_id);
      // see if we have enough observations to add this lmk
      if (obj_lmk_node->numObservations() < params_.min_dynamic_observations) {
        continue;
      }
      TrackletId tracklet_id = obj_lmk_node->getId();
      // if does not exist, we need to go back and all the previous measurements
      // & factors & motions
      if (!isDynamicTrackletInMap(obj_lmk_node)) {
        // add the points/motions from the past
        auto seen_frames = obj_lmk_node->getSeenFrames();
        // assert frame observations are continuous?
        // start at the first frame we want to start adding points in as we know
        // have seen them enough times start from +1, becuase the motion index
        // is k-1 to k and there is no motion k-2 to k-1 but the first poitns we
        // want to add are at k-1
        // TODO: shouldnt this actually just be frame_id_k -
        // params_.min_dynamic_observations
        // TODO: how to handle the if starting_motion_frame < a frame actually
        // seen in!
        FrameId starting_motion_frame;
        if (update_params.do_backtrack) {
          starting_motion_frame =
              seen_frames.template getFirstIndex<FrameId>() +
              1u;  // as we index the motion from k
        } else {
          // start from the requested index, this will still mean that we will
          // add the previous frame as always add a motion between k-1 and k
          starting_motion_frame = frame_id_k;
          if (starting_motion_frame <
              seen_frames.template getFirstIndex<FrameId>() + 1u) {
            // if the requested starting frame is not the first frame + 1u of
            // the actul track (ie. the second seen frame) we cannot use it yet
            // as we have to index BACKWARDS from the starting motion frame if
            // we used frame_id_k as the starting_motion_frame, we would end up
            // with an iterator pointing to the end instead, we will have to get
            // it next frame!!!
            continue;
          }
        }
        auto starting_motion_frame_itr =
            seen_frames.find(starting_motion_frame);
        CHECK(starting_motion_frame_itr != seen_frames.end())
            << "Starting motion frame is " << starting_motion_frame
            << " but first frame is "
            << seen_frames.template getFirstIndex<FrameId>();
        std::stringstream ss;
        ss << "Going back to add point on object " << object_id
           << " at frames\n";
        // iterate over k-N to k (inclusive) and all all
        utils::TimingStatsCollector dyn_point_backtrack_timer(
            this->loggerPrefix() + ".dynamic_point_backtrack");
        for (auto seen_frames_itr = starting_motion_frame_itr;
             seen_frames_itr != seen_frames.end(); seen_frames_itr++) {
          auto seen_frames_itr_prev = seen_frames_itr;
          std::advance(seen_frames_itr_prev, -1);
          CHECK(seen_frames_itr_prev != seen_frames.end())
              << " For object  " << object_id;
          auto query_frame_node_k = *seen_frames_itr;
          auto query_frame_node_k_1 = *seen_frames_itr_prev;
          CHECK_EQ(query_frame_node_k->frame_id,
                   query_frame_node_k_1->frame_id + 1u);
          // add points UP TO AND INCLUDING the current frame
          if (query_frame_node_k->frame_id > frame_id_k) {
            break;
          }
          // point needs to be be in k and k-1 -> we have validated the object
          // exists in these two frames but not the points
          CHECK(obj_lmk_node->seenAtFrame(query_frame_node_k->frame_id));
          if (!obj_lmk_node->seenAtFrame(query_frame_node_k_1->frame_id)) {
            LOG(WARNING) << "Tracklet " << tracklet_id << " on object "
                         << object_id << " seen at "
                         << query_frame_node_k->frame_id << " but not "
                         << query_frame_node_k_1->frame_id;
            break;
          }  // this miay mean this this point never gets added?
          ss << query_frame_node_k_1->frame_id << " "
             << query_frame_node_k->frame_id << "\n";
          const gtsam::Pose3 T_world_camera_k_1 =
              getInitialOrLinearizedSensorPose(query_frame_node_k_1->frame_id);
          gtsam::Pose3 T_world_camera_k =
              getInitialOrLinearizedSensorPose(query_frame_node_k->frame_id);
          PointUpdateContextType point_context;
          point_context.lmk_node = obj_lmk_node;
          point_context.frame_node_k_1 = query_frame_node_k_1;
          point_context.frame_node_k = query_frame_node_k;
          point_context.X_k_measured = T_world_camera_k;
          point_context.X_k_1_measured = T_world_camera_k_1;
          // this assumes we add all the points in order and have continuous
          // frames (which we should have?)
          if (seen_frames_itr == starting_motion_frame_itr) {
            point_context.is_starting_motion_frame = true;
          }
          utils::TimingStatsCollector dyn_point_update_timer(
              this->loggerPrefix() + ".dyn_point_update_1");
          // the true set of values that are added from the update
          dynamicPointUpdateCallback(point_context, result, internal_new_values,
                                     internal_new_factors);
          // // update internal theta and factors
          // theta_.insert(local_new_values);
          // // add to the external new_values
          // new_values.insert(local_new_values);
        }
      } else {
        // these tracklets should already be in the graph so we should only need
        // to add the new measurements from this frame check that we have
        // previous point for this frame
        PointUpdateContextType point_context;
        point_context.lmk_node = obj_lmk_node;
        point_context.frame_node_k_1 = frame_node_k_1;
        point_context.frame_node_k = frame_node_k;
        point_context.X_k_1_measured =
            getInitialOrLinearizedSensorPose(frame_node_k_1->frame_id);
        point_context.X_k_measured =
            getInitialOrLinearizedSensorPose(frame_node_k->frame_id);
        point_context.is_starting_motion_frame = false;
        utils::TimingStatsCollector dyn_point_update_timer(
            this->loggerPrefix() + ".dyn_point_update_2");
        // the true set of values that are added from the update
        // gtsam::Values local_new_values;
        dynamicPointUpdateCallback(point_context, result, internal_new_values,
                                   internal_new_factors);
        // // update internal theta and factors
        // theta_.insert(local_new_values);
        // // add to the external new_values
        // new_values.insert(local_new_values);
      }
    }
  }
  // iterate over objects for which a motion was added
  // becuase we add lots of new points every frame, we may go over the same
  // object many times to account for backtracking over new points over this
  // object this is a bit inefficient as we do this iteration even if no new
  // object values are added becuuse we dont know if the affected frames are
  // becuase of old points as well as new points
  //  utils::TimingStatsCollector dyn_obj_affected_timer(this->loggerPrefix() +
  //  ".dyn_object_affected");
  for (const auto& [object_id, frames_affected] :
       result.objects_affected_per_frame) {
    VLOG(20) << "Iterating over frames for which a motion was added "
             << container_to_string(frames_affected) << " for object "
             << object_id;
    auto object_node = map->getObject(object_id);
    std::vector<FrameId> frames_affected_vector(frames_affected.begin(),
                                                frames_affected.end());
    // TODO: this is NO LONGER the case in the object centric case
    // TODO: should always have at least two frames (prev and current) as we
    // must add factors on this frame and the previous frame
    //  CHECK_GE(frames_affected_vector.size(), 2u);
    for (size_t frame_idx = 0; frame_idx < frames_affected_vector.size();
         frame_idx++) {
      const FrameId frame_id = frames_affected_vector.at(frame_idx);
      auto frame_node_k_impl = map->getFrame(frame_id);
      ObjectUpdateContextType object_update_context;
      // perform motion check on this frame -> if this is the first frame (of at
      // least 2) then there should be no motion at this frame (since it is k-1
      // of a motion pair and there is no k-2)
      if (frame_idx == 0) {
        object_update_context.has_motion_pair = false;
      } else {
        object_update_context.has_motion_pair = true;
      }
      object_update_context.frame_node_k = frame_node_k_impl;
      object_update_context.object_node = object_node;
      // gtsam::Values local_new_values;
      objectUpdateContext(object_update_context, result, internal_new_values,
                          internal_new_factors);
      // // update internal theta and factors
      // theta_.insert(local_new_values);
      // // add to the external new_values
      // new_values.insert(local_new_values);
    }
  }
  // this doesnt really work any more as debug info is meant to be per frame?
  if (result.debug_info && VLOG_IS_ON(20)) {
    for (const auto& [object_id, object_info] :
         result.debug_info->getObjectInfos()) {
      std::stringstream ss;
      ss << "Object id debug info: " << object_id << "\n";
      ss << object_info;
      LOG(INFO) << ss.str();
    }
  }
  factors_ += internal_new_factors;
  new_factors += internal_new_factors;
  // update internal theta and factors
  theta_.insert(internal_new_values);
  // add to the external new_values
  new_values.insert(internal_new_values);
  return result;
}
updateDynamicObservations() [2/2]
template<typename MAP > UpdateObservationResult dyno::Formulation< MAP >::updateDynamicObservations (FrameId from_frame, FrameId to_frame, gtsam::Values & new_values, gtsam::NonlinearFactorGraph & new_factors, const UpdateObservationParams & update_params)
Update the dynamic-point part of the factor graph between multiple frames. Internally makes several calls to updateDynamicObservations(FrameId,gtsam::Values&,gtsam::NonlinearFactorGraph&,const UpdateObservationParams&) and returns the accumulated UpdateObservationResult.
Parameters
from_frame FrameId
to_frame FrameId
new_values gtsam::Values&
new_factors gtsam::NonlinearFactorGraph&
update_params const UpdateObservationParams&
Returns
UpdateObservationResult
Definition at line 168 of file Formulation-impl.hpp.
{
  CHECK_LT(from_frame, to_frame);
  CHECK_GT(from_frame, this->map()->firstFrameId());
  UpdateObservationResult result;
  for (auto frame_id = from_frame; frame_id <= to_frame; frame_id++) {
    gtsam::NonlinearFactorGraph factors;
    result +=
        updateDynamicObservations(frame_id, new_values, factors, update_params);
    new_factors += factors;
  }
  return result;
}
Referenced by dyno::RegularBackendModule::nominalSpinImpl().
updateStaticObservations() [1/2]
template<typename MAP > UpdateObservationResult dyno::Formulation< MAP >::updateStaticObservations (FrameId frame_id_k, gtsam::Values & new_values, gtsam::NonlinearFactorGraph & new_factors, const UpdateObservationParams & update_params)
Updates the static-point part of the factor graph for frame k. This contains all the bookeeping logic to update the factor graph with static points.
Parameters
frame_id_k FrameId
new_values gtsam::Values&
new_factors gtsam::NonlinearFactorGraph&
update_params const UpdateObservationParams&
Returns
UpdateObservationResult
Definition at line 186 of file Formulation-impl.hpp.
{
  typename Map::Ptr map = this->map();
  auto accessor = this->accessorFromTheta();
  auto static_point_noise = CHECK_NOTNULL(noise_models_.static_point_noise);
  gtsam::SharedNoiseModel static_keypoint_noise =
      gtsam::noiseModel::Isotropic::Sigma(2u, 3);
  static_keypoint_noise = gtsam::noiseModel::Robust::Create(
      gtsam::noiseModel::mEstimator::Huber::Create(0.01),
      static_keypoint_noise);
  // keep track of the new factors added in this function
  // these are then appended to the internal factors_ and new_factors
  gtsam::NonlinearFactorGraph internal_new_factors;
  UpdateObservationResult result(update_params);
  // VIODE!!
  double fx = 376.0;
  double fy = 376.0;
  double cx = 376.0;
  double cy = 240.0;
  double skew = 0.0;  // assuming zero skew
  const auto K = boost::make_shared<gtsam::Cal3_S2>(fx, fy, skew, cx, cy);
  const auto frame_node_k = map->getFrame(frame_id_k);
  CHECK_NOTNULL(frame_node_k);
  // pose estimate from frontend
  gtsam::Pose3 T_world_camera_frontend;
  CHECK(
      this->map()->hasInitialSensorPose(frame_id_k, &T_world_camera_frontend));
  VLOG(20) << "Looping over " << frame_node_k->static_landmarks.size()
           << " static lmks for frame " << frame_id_k;
  for (const auto& lmk_node : frame_node_k->static_landmarks) {
    const gtsam::Key point_key = lmk_node->makeStaticKey();
    // check if lmk node is already in map (which should mean it is equivalently
    // in isam)
    if (is_other_values_in_map.exists(point_key)) {
      const Landmark measured = lmk_node->getMeasurement(frame_id_k).landmark;
      // const auto measured_keypoint =
      // lmk_node->getMeasurement(frame_id_k).keypoint;
      internal_new_factors
          .emplace_shared<gtsam::PoseToPointFactor<gtsam::Pose3, Landmark>>(
              frame_node_k->makePoseKey(),  // pose key for this frame
              point_key, measured, static_point_noise);
      // internal_new_factors
      //     .emplace_shared<GenericProjectionFactor>(
      //         measured_keypoint,
      //         static_keypoint_noise,
      //         frame_node_k->makePoseKey(),  // pose key for this frame
      //         point_key, K);
      if (result.debug_info) result.debug_info->num_static_factors++;
      result.updateAffectedObject(frame_id_k, 0);
    } else {
      // see if we have enough observations to add this lmk
      if (lmk_node->numObservations() < params_.min_static_observations) {
        continue;
      }
      // this condition should only run once per tracklet (ie.e the first time
      // the tracklet has enough observations) we gather the tracklet
      // observations and then initalise it in the new values these should then
      // get added to the map and map_->exists() should return true for all
      // other times
      const auto& seen_frames = lmk_node->getSeenFrames();
      for (const auto& seen_frame : seen_frames) {
        auto seen_frame_id = seen_frame->getId();
        // only iterate up to the query frame
        if ((FrameId)seen_frame_id > frame_id_k) {
          break;
        }
        // if we should not backtrack, only add the current frame!!!
        const auto do_backtrack = update_params.do_backtrack;
        if (!do_backtrack && (FrameId)seen_frame_id < frame_id_k) {
          continue;
        }
        const auto measured_keypoint =
            lmk_node->getMeasurement(seen_frame).keypoint;
        const Landmark& measured =
            lmk_node->getMeasurement(seen_frame).landmark;
        internal_new_factors.emplace_shared<PoseToPointFactor>(
            seen_frame->makePoseKey(),  // pose key at previous frames
            point_key, measured, static_point_noise);
        // internal_new_factors
        //   .emplace_shared<GenericProjectionFactor>(
        //       measured_keypoint,
        //       static_keypoint_noise,
        //       seen_frame->makePoseKey(),  // pose key for this frame
        //       point_key, K);
        if (result.debug_info) result.debug_info->num_static_factors++;
        result.updateAffectedObject(seen_frame_id, 0);
      }
      // pick the one in this frame
      const Landmark& measured =
          MeasurementTraits::point(lmk_node->getMeasurement(frame_id_k));
      // add initial value, either from measurement or previous estimate
      gtsam::Point3 lmk_world;
      getSafeQuery(lmk_world,
                   accessor->getStaticLandmark(lmk_node->tracklet_id),
                   gtsam::Point3(T_world_camera_frontend * measured));
      new_values.insert(point_key, lmk_world);
      is_other_values_in_map.insert2(point_key, true);
      if (result.debug_info) result.debug_info->num_new_static_points++;
      result.updateAffectedObject(frame_id_k, 0);
    }
  }
  // update internal data structures
  theta_.insert_or_assign(new_values);
  factors_ += internal_new_factors;
  new_factors += internal_new_factors;
  if (result.debug_info)
    LOG(INFO) << "Num new static points: "
              << result.debug_info->num_new_static_points
              << " Num new static factors "
              << result.debug_info->num_static_factors;
  return result;
}
updateStaticObservations() [2/2]
template<typename MAP > UpdateObservationResult dyno::Formulation< MAP >::updateStaticObservations (FrameId from_frame, FrameId to_frame, gtsam::Values & new_values, gtsam::NonlinearFactorGraph & new_factors, const UpdateObservationParams & update_params)
Update the static-point part of the factor graph between multiple frames. Internally makes several calls to updateStaticObservations(FrameId,gtsam::Values&,gtsam::NonlinearFactorGraph&,const UpdateObservationParams&) and returns the accumulated UpdateObservationResult.
Parameters
from_frame FrameId
to_frame FrameId
new_values gtsam::Values&
new_factors gtsam::NonlinearFactorGraph&
update_params const UpdateObservationParams&
Returns
UpdateObservationResult
Definition at line 146 of file Formulation-impl.hpp.
{
  CHECK_LT(from_frame, to_frame);
  CHECK_GT(from_frame, this->map()->firstFrameId());
  UpdateObservationResult result;
  for (auto frame_id = from_frame; frame_id <= to_frame; frame_id++) {
    // TODO: not sure we need this extra factors variable here now we use the
    // internal_new_factors
    gtsam::NonlinearFactorGraph factors;
    result +=
        updateStaticObservations(frame_id, new_values, factors, update_params);
    new_factors += factors;
  }
  return result;
}
Referenced by dyno::RegularBackendModule::nominalSpinImpl().
updateTheta()
template<typename MAP > void dyno::Formulation< MAP >::updateTheta (const gtsam::Values & linearization)
Updates and assigns new values to theta. This is used after external optimisation to update the values for the accessor which has a internal reference (pointer) to theta.
Parameters
linearization const gtsam::Values&
Definition at line 55 of file Formulation-impl.hpp.
{
  // theta_.update(linearization);
  // why would we need to assign new values?
  theta_.insert_or_assign(linearization);
  // TODO: comment backed in!!
  //  accessorFromTheta()->postUpdateCallback();
}
Referenced by dyno::RegularBackendModule::updateBatch(), dyno::RegularBackendModule::updateIncremental(), and dyno::RegularBackendModule::updateSlidingWindow().
Member Data Documentation
accessor_theta_
template<typename MAP > AccessorType::Ptr dyno::Formulation< MAP >::accessor_theta_ mutable private
Definition at line 587 of file Formulation.hpp.
Referenced by dyno::Formulation< MAP >::derivedAccessor().
factors_
template<typename MAP > gtsam::NonlinearFactorGraph dyno::Formulation< MAP >::factors_ protected
Definition at line 584 of file Formulation.hpp.
Referenced by dyno::Formulation< MAP >::clearGraph(), and dyno::Formulation< MAP >::getGraph().
fully_qualified_name_
template<typename MAP > std::optional<std::string> dyno::Formulation< MAP >::fully_qualified_name_ {std::nullopt} mutable private
Full name of the formulation and accounts for the additional configuration from the FormulationParams
Definition at line 590 of file Formulation.hpp.
Referenced by dyno::Formulation< MAP >::getFullyQualifiedName().
hooks_
template<typename MAP > FormulationHooks dyno::Formulation< MAP >::hooks_ protected
Definition at line 578 of file Formulation.hpp.
Referenced by dyno::Formulation< MAP >::hooks().
is_other_values_in_map
template<typename MAP > gtsam::FastMap<gtsam::Key, bool> dyno::Formulation< MAP >::is_other_values_in_map protected
the set of (static related) values managed by this updater. Allows checking if values have already been added over successive function calls
Definition at line 581 of file Formulation.hpp.
map_
template<typename MAP > Map::Ptr dyno::Formulation< MAP >::map_ protected
Definition at line 576 of file Formulation.hpp.
Referenced by dyno::Formulation< MAP >::map().
noise_models_
template<typename MAP > const NoiseModels dyno::Formulation< MAP >::noise_models_ protected
Definition at line 577 of file Formulation.hpp.
Referenced by dyno::Formulation< MAP >::noiseModels().
params_
template<typename MAP > const FormulationParams dyno::Formulation< MAP >::params_ protected
Definition at line 575 of file Formulation.hpp.
theta_
template<typename MAP > gtsam::Values dyno::Formulation< MAP >::theta_ protected
Current linearisation that will be associated with the current graph.
Definition at line 583 of file Formulation.hpp.
Referenced by dyno::Formulation< MAP >::getTheta().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/backend/Formulation.hpp
dynosam/include/dynosam/backend/Formulation-impl.hpp