DynoSAM: dyno::DataProviderRos Class Reference
dyno::DataProviderRos Class Reference
Base Dataprovider for ROS that implements common image processing functionalities.
#include <DataProviderRos.hpp>
Public Member Functions
DataProviderRos (rclcpp::Node::SharedPtr node)
virtual ~DataProviderRos ()=default
const cv::Mat readRgbRosImage (const sensor_msgs::msg::Image::ConstSharedPtr &img_msg) const
Convers a sensor_msgs::msg::Image to a cv::Mat while testing that the input has the correct datatype for an RGB image (as defined by ImageType::RGBMono).
const cv::Mat readDepthRosImage (const sensor_msgs::msg::Image::ConstSharedPtr &img_msg) const
Convers a sensor_msgs::msg::Image to a cv::Mat while testing that the input has the correct datatype for an Depth image (as defined by ImageType::Depth).
const cv::Mat readFlowRosImage (const sensor_msgs::msg::Image::ConstSharedPtr &img_msg) const
Convers a sensor_msgs::msg::Image to a cv::Mat while testing that the input has the correct datatype for an Optical Flow image (as defined by ImageType::OpticalFlow).
const cv::Mat readMaskRosImage (const sensor_msgs::msg::Image::ConstSharedPtr &img_msg) const
Convers a sensor_msgs::msg::Image to a cv::Mat while testing that the input has the correct datatype for an Motion Mask image (as defined by ImageType::MotionMask).
template<class Rep = int64_t, class Period = std::milli>
const CameraParams & waitAndSetCameraParams (const std::chrono::duration< Rep, Period > &time_to_wait=std::chrono::duration< Rep, Period >(-1), const std::string &topic="image/camera_info")
Gets CameraParams from a sensor_msgs::msg::CameraInfo recieved on the specified topic. This function is blocking until a message is recieved (or until the time_to_wait) elapses.
CameraParams::Optional getCameraParams () const override
Provides functionality to get camera paramters for the main pipeline, as these may be available from the dataset.
Public Member Functions inherited from dyno::DataProvider
DataProvider ()=default
DataProvider (DataInterfacePipeline *module)
DataProvider (DataInterfacePipelineImu *module)
virtual ~DataProvider ()
void registerImuSingleCallback (const ImuSingleInputCallback &callback)
void registerImuMultiCallback (const ImuMultiInputCallback &callback)
void registerImageContainerCallback (const ImageContainerCallback &callback)
void registerGroundTruthPacketCallback (const GroundTruthPacketCallback &callback)
virtual ImageContainer::Ptr imageContainerPreprocessor (ImageContainer::Ptr image_container)
Virtual Image Container Preprocessor function that is registered to the data interface pipeline.
void registerOnFinishCallback (const std::function< void()> &callback)
virtual int datasetSize () const =0
Get the size of the dataset - if this is not valid (i.e. the provider is online) this function should return -1.
virtual bool spin ()=0
Spins the dataset for one "step" of the dataset.
virtual void shutdown ()
virtual CameraParams::Optional getCameraParams () const
Provides functionality to get camera paramters for the main pipeline, as these may be available from the dataset.
Protected Member Functions
const cv_bridge::CvImageConstPtr readRosImage (const sensor_msgs::msg::Image::ConstSharedPtr &img_msg) const
Helper function to convert a ROS Image message to a CvImageConstPtr via the cv bridge.
template<typename IMAGETYPE >
const cv::Mat convertRosImage (const sensor_msgs::msg::Image::ConstSharedPtr &img_msg) const
Helper function to convert a sensor_msgs::msg::Image::ConstSharedPtr& to a cv::Mat with the right datatype.
Protected Member Functions inherited from dyno::DataProvider
void emitOnFinishCallbacks ()
Protected Attributes
rclcpp::Node::SharedPtr node_
CameraParams::Optional camera_params_
Protected Attributes inherited from dyno::DataProvider
ImageContainerCallback image_container_callback_
ImuSingleInputCallback imu_single_input_callback_
ImuMultiInputCallback imu_multi_input_callback_
GroundTruthPacketCallback ground_truth_packet_callback_
std::atomic_bool shutdown_ = {false}
Additional Inherited Members
Public Types inherited from dyno::DataProvider
using ImageContainerCallback = std::function< void(ImageContainer::Ptr)>
using ImuSingleInputCallback = std::function< void(const ImuMeasurement &)>
using ImuMultiInputCallback = std::function< void(const ImuMeasurements &)>
using GroundTruthPacketCallback = std::function< void(const GroundTruthInputPacket &)>
Detailed Description
Base Dataprovider for ROS that implements common image processing functionalities.
Definition at line 53 of file DataProviderRos.hpp.
Constructor & Destructor Documentation
DataProviderRos()
dyno::DataProviderRos::DataProviderRos (rclcpp::Node::SharedPtr node)
Definition at line 41 of file DataProviderRos.cc.
    : DataProvider(), node_(node) {}
~DataProviderRos()
virtual dyno::DataProviderRos::~DataProviderRos () virtual default
Member Function Documentation
convertRosImage()
template<typename IMAGETYPE > const cv::Mat dyno::DataProviderRos::convertRosImage (const sensor_msgs::msg::Image::ConstSharedPtr & img_msg) const inline protected
Helper function to convert a sensor_msgs::msg::Image::ConstSharedPtr& to a cv::Mat with the right datatype.
The datatype is specified from the template IMAGETYPE::OpenCVType and ensures the passed in image has the correct datatype for the desired IMAGETYPE.
ROS will be shutdown if the incoming image has an incorrect type.
Template Parameters
IMAGETYPE
Parameters
img_msg const sensor_msgs::msg::Image::ConstSharedPtr&
Returns
const cv::Mat
Definition at line 177 of file DataProviderRos.hpp.
{
    const cv_bridge::CvImageConstPtr cvb_image = readRosImage(img_msg);
    try {
      const cv::Mat img = cvb_image->image;
      image_traits<IMAGETYPE>::validate(img);
      return img;
    } catch (const InvalidImageTypeException& exception) {
      RCLCPP_FATAL_STREAM(node_->get_logger(),
                          image_traits<IMAGETYPE>::name()
                              << " Image msg was of the wrong type (validate "
                                 "failed with exception "
                              << exception.what() << "). "
                              << "ROS encoding type used was "
                              << cvb_image->encoding);
      rclcpp::shutdown();
      return cv::Mat();
    }
  }
References node_, and readRosImage().
getCameraParams()
CameraParams::Optional dyno::DataProviderRos::getCameraParams () const inline override virtual
Provides functionality to get camera paramters for the main pipeline, as these may be available from the dataset.
By default returns std::nullopt but the derived data-provider can overwrite this and return the loaded params
Returns
CameraParams::Optional
Reimplemented from dyno::DataProvider.
Definition at line 146 of file DataProviderRos.hpp.
{
    return camera_params_;
  }
References camera_params_.
readDepthRosImage()
const cv::Mat dyno::DataProviderRos::readDepthRosImage (const sensor_msgs::msg::Image::ConstSharedPtr & img_msg) const
Convers a sensor_msgs::msg::Image to a cv::Mat while testing that the input has the correct datatype for an Depth image (as defined by ImageType::Depth).
Parameters
img_msg const sensor_msgs::msg::Image::ConstSharedPtr&
Returns
const cv::Mat
Definition at line 49 of file DataProviderRos.cc.
{
  return convertRosImage<ImageType::Depth>(img_msg);
}
Referenced by dyno::OnlineDataProviderRos::imageSyncCallback().
readFlowRosImage()
const cv::Mat dyno::DataProviderRos::readFlowRosImage (const sensor_msgs::msg::Image::ConstSharedPtr & img_msg) const
Convers a sensor_msgs::msg::Image to a cv::Mat while testing that the input has the correct datatype for an Optical Flow image (as defined by ImageType::OpticalFlow).
Parameters
img_msg const sensor_msgs::msg::Image::ConstSharedPtr&
Returns
const cv::Mat
Definition at line 54 of file DataProviderRos.cc.
{
  return convertRosImage<ImageType::OpticalFlow>(img_msg);
}
Referenced by dyno::OnlineDataProviderRos::imageSyncCallback().
readMaskRosImage()
const cv::Mat dyno::DataProviderRos::readMaskRosImage (const sensor_msgs::msg::Image::ConstSharedPtr & img_msg) const
Convers a sensor_msgs::msg::Image to a cv::Mat while testing that the input has the correct datatype for an Motion Mask image (as defined by ImageType::MotionMask).
Parameters
img_msg const sensor_msgs::msg::Image::ConstSharedPtr&
Returns
const cv::Mat
Definition at line 59 of file DataProviderRos.cc.
{
  return convertRosImage<ImageType::MotionMask>(img_msg);
}
Referenced by dyno::OnlineDataProviderRos::imageSyncCallback().
readRgbRosImage()
const cv::Mat dyno::DataProviderRos::readRgbRosImage (const sensor_msgs::msg::Image::ConstSharedPtr & img_msg) const
Convers a sensor_msgs::msg::Image to a cv::Mat while testing that the input has the correct datatype for an RGB image (as defined by ImageType::RGBMono).
Parameters
img_msg const sensor_msgs::msg::Image::ConstSharedPtr&
Returns
const cv::Mat
Definition at line 44 of file DataProviderRos.cc.
{
  return convertRosImage<ImageType::RGBMono>(img_msg);
}
Referenced by dyno::OnlineDataProviderRos::imageSyncCallback().
readRosImage()
const cv_bridge::CvImageConstPtr dyno::DataProviderRos::readRosImage (const sensor_msgs::msg::Image::ConstSharedPtr & img_msg) const protected
Helper function to convert a ROS Image message to a CvImageConstPtr via the cv bridge.
Parameters
img_msg const sensor_msgs::msg::Image::ConstSharedPtr&
Returns
const cv_bridge::CvImageConstPtr
Definition at line 64 of file DataProviderRos.cc.
{
  CHECK(img_msg);
  cv_bridge::CvImageConstPtr cv_ptr;
  try {
    // important to copy to ensure that memory does not go out of scope (which
    // it seems to !!!)
    cv_ptr = cv_bridge::toCvCopy(img_msg);
  } catch (cv_bridge::Exception& exception) {
    RCLCPP_FATAL(node_->get_logger(), "cv_bridge exception: %s",
                 exception.what());
    rclcpp::shutdown();
  }
  return cv_ptr;
}
References node_.
Referenced by convertRosImage().
waitAndSetCameraParams()
template<class Rep = int64_t, class Period = std::milli> const CameraParams & dyno::DataProviderRos::waitAndSetCameraParams (const std::chrono::duration< Rep, Period > & time_to_wait = std::chrono::duration<Rep, Period>(-1), const std::string & topic = "image/camera_info") inline
Gets CameraParams from a sensor_msgs::msg::CameraInfo recieved on the specified topic. This function is blocking until a message is recieved (or until the time_to_wait) elapses.
While this function returns a const ref to the CameraParams it also sets the internal camera_params_. The camera params are then returned by the overwritten getCameraParams, allowing the PipelineManager to access the correct camera paramters.
Template Parameters
Rep int64_t,
Period std::milli
Parameters
time_to_wait const std::chrono::duration<Rep, Period>&
topic const std::string&. Defaults to "image/camera_info"
Returns
const CameraParams&
Definition at line 119 of file DataProviderRos.hpp.
{
    RCLCPP_INFO_STREAM(node_->get_logger(),
                       "Waiting for camera params on topic: " << topic);
    // it seems rclcpp::Adaptors do not work yet with wait for message
    sensor_msgs::msg::CameraInfo camera_info;
    if (rclcpp::wait_for_message<sensor_msgs::msg::CameraInfo, Rep, Period>(
            camera_info, node_, topic, time_to_wait)) {
      using Adaptor =
          rclcpp::TypeAdapter<dyno::CameraParams, sensor_msgs::msg::CameraInfo>;
      CameraParams camera_params;
      Adaptor::convert_to_custom(camera_info, camera_params);
      RCLCPP_INFO_STREAM(node_->get_logger(), "Received camera params: "
                                                  << camera_params.toString());
      camera_params_ = camera_params;
      return *camera_params_;
    } else {
      const auto milliseconds =
          std::chrono::duration_cast<std::chrono::milliseconds>(time_to_wait);
      throw DynosamException("Failed to receive camera params on topic " +
                             topic + " (waited with timeout " +
                             std::to_string(milliseconds.count()) + " ms).");
    }
  }
References camera_params_, node_, and dyno::CameraParams::toString().
Referenced by dyno::OnlineDataProviderRos::OnlineDataProviderRos().
Member Data Documentation
camera_params_
CameraParams::Optional dyno::DataProviderRos::camera_params_ protected
Definition at line 201 of file DataProviderRos.hpp.
Referenced by getCameraParams(), and waitAndSetCameraParams().
node_
rclcpp::Node::SharedPtr dyno::DataProviderRos::node_ protected
Definition at line 200 of file DataProviderRos.hpp.
Referenced by dyno::OnlineDataProviderRos::connect(), convertRosImage(), dyno::OnlineDataProviderRos::imageSyncCallback(), readRosImage(), dyno::OnlineDataProviderRos::shutdown(), and waitAndSetCameraParams().
The documentation for this class was generated from the following files:
dynosam_ros/include/dynosam_ros/DataProviderRos.hpp
dynosam_ros/src/DataProviderRos.cc