DynoSAM: dyno::VirtualKittiGenericInstanceSegFolder Class Reference
dyno::VirtualKittiGenericInstanceSegFolder Class Reference abstract
Public Member Functions
VirtualKittiGenericInstanceSegFolder (const std::string &path, VirtualKittiTextGtLoader::Ptr gt_loader)
virtual ~VirtualKittiGenericInstanceSegFolder ()=default
cv::Mat getItem (size_t idx) override
Get the Item at an index in the dataset.
Public Member Functions inherited from dyno::GenericVirtualKittiImageLoader
GenericVirtualKittiImageLoader (const std::string &full_path)
std::string getFolderName () const override
Public Member Functions inherited from dyno::DataFolder< cv::Mat >
DataFolder ()=default
virtual ~DataFolder ()
void initAbsolutePath (const fs::path &absolute_folder_path)
Set the Absolute Folder Path object to be used when an item is loaded This needs to be a setter function since we do not know the absolute path at the time of construction.
operator bool () const
Indicates that the absolute folder path has been set correctly with initAbsolutePath Same behaviour as is isAbsolutePathSet but can operate as a boolean operator.
bool isAbsolutePathSet () const
Checks if the absolute path has been set and the data folder is ready to get items.
fs::path getAbsolutePath () const
virtual std::string getFolderName () const=0
virtual cv::Mat getItem (size_t idx)=0
Get the Item at an index in the dataset.
Protected Member Functions
virtual cv::Mat loadImage (const std::string &file_path, FrameId frame, const GroundTruthInputPacket &gt_packet)=0
cv::Mat loadSemanticInstanceUnchanged (const std::string &file_path) const
Loads instance semantic mask from the file path.
Protected Member Functions inherited from dyno::DataFolder< cv::Mat >
virtual void onPathInit ()
Virtual function that is called once the absolute path to this folder is known This happens after construction as the dataset folder (the parent folder) is known by the DataFolderStructure which will set the path on its construction.
Protected Attributes
VirtualKittiTextGtLoader::Ptr gt_loader_
Additional Inherited Members
Public Types inherited from dyno::DataFolder< cv::Mat >
using This = DataFolder< cv::Mat >
using Type = cv::Mat
Public Attributes inherited from dyno::GenericVirtualKittiImageLoader
const std::string full_path_
Detailed Description
Definition at line 717 of file VirtualKittidataProvider.cc.
Constructor & Destructor Documentation
VirtualKittiGenericInstanceSegFolder()
dyno::VirtualKittiGenericInstanceSegFolder::VirtualKittiGenericInstanceSegFolder (const std::string & path, VirtualKittiTextGtLoader::Ptr gt_loader) inline
Definition at line 722 of file VirtualKittidataProvider.cc.
      : GenericVirtualKittiImageLoader(path),
        gt_loader_(CHECK_NOTNULL(gt_loader)) {}
~VirtualKittiGenericInstanceSegFolder()
virtual dyno::VirtualKittiGenericInstanceSegFolder::~VirtualKittiGenericInstanceSegFolder () virtual default
Member Function Documentation
getItem()
cv::Mat dyno::VirtualKittiGenericInstanceSegFolder::getItem (size_t idx) inline override virtual
Get the Item at an index in the dataset.
The idx should essentually correspond to the frame_id (starting at 0) for this datastream in the dataset.
Parameters
idx
Returns
T
Implements dyno::DataFolder< cv::Mat >.
Definition at line 728 of file VirtualKittidataProvider.cc.
{
    std::stringstream ss;
    ss << std::setfill('0') << std::setw(5) << idx;
    const std::string file_path =
        full_path_ + "/instancegt_" + ss.str() + ".png";
    utils::throwExceptionIfPathInvalid(file_path);
    const GroundTruthInputPacket& gt_packet = gt_loader_->getGTPacket(idx);
    return loadImage(file_path, idx, gt_packet);
  }
References dyno::GenericVirtualKittiImageLoader::full_path_, gt_loader_, loadImage(), and dyno::utils::throwExceptionIfPathInvalid().
loadImage()
virtual cv::Mat dyno::VirtualKittiGenericInstanceSegFolder::loadImage (const std::string & file_path, FrameId frame, const GroundTruthInputPacket & gt_packet) protected pure virtual
Implemented in dyno::VirtualKittiMotionSegFolder, and dyno::VirtualKittiInstanceSegFolder.
Referenced by getItem().
loadSemanticInstanceUnchanged()
cv::Mat dyno::VirtualKittiGenericInstanceSegFolder::loadSemanticInstanceUnchanged (const std::string & file_path) const inline protected
Loads instance semantic mask from the file path.
This loads the image using libpng++ since we need to load the image as an 8bit indexed PNG file (which opencv does not have functionality for). Keeping consistent with the ground truth indexing we use for VirtualKitti we do not need to modify the trackID's within the image since we want the trackID's to be indexed from 1
Parameters
file_path
Returns
cv::Mat
Definition at line 755 of file VirtualKittidataProvider.cc.
{
    png::image<png::index_pixel> index_image(file_path);
    cv::Size size(index_image.get_width(), index_image.get_height());
    cv::Mat semantic_image(size, ImageType::MotionMask::OpenCVType);
    for (size_t y = 0; y < index_image.get_height(); ++y) {
      for (size_t x = 0; x < index_image.get_width(); ++x) {
        const auto& pixel = index_image.get_pixel(x, y);
        // the semantic label
        int i_byte = static_cast<int>(pixel);
        semantic_image.at<int>(y, x) = i_byte;
      }
    }
    return semantic_image;
  }
References dyno::ImageType::MotionMask::OpenCVType.
Referenced by dyno::VirtualKittiMotionSegFolder::loadImage(), and dyno::VirtualKittiInstanceSegFolder::loadImage().
Member Data Documentation
gt_loader_
VirtualKittiTextGtLoader::Ptr dyno::VirtualKittiGenericInstanceSegFolder::gt_loader_ protected
Definition at line 774 of file VirtualKittidataProvider.cc.
Referenced by getItem().
The documentation for this class was generated from the following file:
dynosam/src/dataprovider/VirtualKittidataProvider.cc