DynoSAM: dyno::KittiObjectPoseFolder Class Reference
dyno::KittiObjectPoseFolder Class Reference
#include <KittiDataProvider.hpp>
Public Member Functions
KittiObjectPoseFolder (TimestampFile::Ptr timestamp_loader, KittiCameraPoseFolder::Ptr camera_pose_loader)
std::string getFolderName () const override
"object_pose.txt" as file name
GroundTruthInputPacket getItem (size_t idx) override
Get the Item at an index in the dataset.
Public Member Functions inherited from dyno::DataFolder< GroundTruthInputPacket >
DataFolder ()=default
virtual ~DataFolder ()
void initAbsolutePath (const fs::path &absolute_folder_path)
Set the Absolute Folder Path object to be used when an item is loaded This needs to be a setter function since we do not know the absolute path at the time of construction.
operator bool () const
Indicates that the absolute folder path has been set correctly with initAbsolutePath Same behaviour as is isAbsolutePathSet but can operate as a boolean operator.
bool isAbsolutePathSet () const
Checks if the absolute path has been set and the data folder is ready to get items.
fs::path getAbsolutePath () const
virtual std::string getFolderName () const=0
virtual GroundTruthInputPacket getItem (size_t idx)=0
Get the Item at an index in the dataset.
Private Member Functions
void onPathInit () override
Setup ifstream and read everything in the data vector.
GroundTruthInputPacket & constructGTPacketOnly (size_t idx)
ObjectPoseGT constructObjectPoseGT (const std::vector< double > &obj_pose_gt) const
Private Attributes
TimestampFile::Ptr timestamp_loader_
KittiCameraPoseFolder::Ptr camera_pose_loader_
std::vector< ObjectIds > object_ids_vector_
std::vector< ObjectPoseGT > object_poses_
gtsam::FastMap< FrameId, GroundTruthInputPacket > gt_packets_
gtsam::Pose3 initial_pose_
Additional Inherited Members
Public Types inherited from dyno::DataFolder< GroundTruthInputPacket >
using This = DataFolder< GroundTruthInputPacket >
using Type = GroundTruthInputPacket
virtual void onPathInit ()
Virtual function that is called once the absolute path to this folder is known This happens after construction as the dataset folder (the parent folder) is known by the DataFolderStructure which will set the path on its construction.
Detailed Description
Definition at line 98 of file KittiDataProvider.hpp.
Constructor & Destructor Documentation
KittiObjectPoseFolder()
dyno::KittiObjectPoseFolder::KittiObjectPoseFolder (TimestampFile::Ptr timestamp_loader, KittiCameraPoseFolder::Ptr camera_pose_loader) inline
Definition at line 101 of file KittiDataProvider.hpp.
      : timestamp_loader_(timestamp_loader),
        camera_pose_loader_(camera_pose_loader) {}
Member Function Documentation
constructGTPacketOnly()
GroundTruthInputPacket & dyno::KittiObjectPoseFolder::constructGTPacketOnly (size_t idx) inline private
Definition at line 179 of file KittiDataProvider.hpp.
{
    // no guarantee (by ordering) that camera_pose_loader has been inited
    // correctly before the get item so we add the data here and not in the
    // onPathInit
    CHECK(camera_pose_loader_);
    CHECK(camera_pose_loader_->isAbsolutePathSet());
    const gtsam::Pose3 camera_pose = camera_pose_loader_->getItem(idx);
    const Timestamp timestamp = timestamp_loader_->getItem(idx);
    // use cahce to avoid calculating every time
    if (gt_packets_.exists(idx)) {
      return gt_packets_.at(idx);
    }
    //  frame_id < nTimes - 1??
    GroundTruthInputPacket gt_packet;
    gt_packet.timestamp_ = timestamp;
    gt_packet.frame_id_ = idx;
    // add ground truths for this fid
    for (size_t i = 0; i < object_ids_vector_[idx].size(); i++) {
      ObjectPoseGT object_pose_gt = object_poses_[object_ids_vector_[idx][i]];
      object_pose_gt.L_world_ = camera_pose * object_pose_gt.L_camera_;
      gt_packet.object_poses_.push_back(object_pose_gt);
      // sanity check
      CHECK_EQ(gt_packet.object_poses_[i].frame_id_, idx);
    }
    gt_packet.X_world_ = camera_pose;
    gt_packets_.insert({idx, gt_packet});
    // must return the actual stored one
    return gt_packets_.at(idx);
  }
References camera_pose_loader_, dyno::GroundTruthInputPacket::frame_id_, gt_packets_, dyno::ObjectPoseGT::L_camera_, dyno::ObjectPoseGT::L_world_, object_ids_vector_, dyno::GroundTruthInputPacket::object_poses_, object_poses_, dyno::PipelinePayload::timestamp_, timestamp_loader_, and dyno::GroundTruthInputPacket::X_world_.
Referenced by getItem().
constructObjectPoseGT()
ObjectPoseGT dyno::KittiObjectPoseFolder::constructObjectPoseGT (const std::vector< double > & obj_pose_gt) const inline private
Definition at line 213 of file KittiDataProvider.hpp.
{
    // FrameID ObjectID B1 B2 B3 B4 t1 t2 t3 r1
    // Where ti are the coefficients of 3D object location **t** in camera
    // coordinates, and r1 is the Rotation around Y-axis in camera coordinates.
    // B1-4 is 2D bounding box of object in the image, used for visualization.
    CHECK(obj_pose_gt.size() == 10);
    ObjectPoseGT object_pose;
    object_pose.frame_id_ = obj_pose_gt[0];
    object_pose.object_id_ = obj_pose_gt[1];
    double b1 = obj_pose_gt[2];
    double b2 = obj_pose_gt[3];
    double b3 = obj_pose_gt[4];
    double b4 = obj_pose_gt[5];
    // convert to cv::Rect where image starts top right
    cv::Point tl(b1, b2);
    cv::Point br(b3, b4);
    object_pose.bounding_box_ = cv::Rect(tl, br);
    cv::Mat t(3, 1, CV_64FC1);
    t.at<double>(0) = obj_pose_gt[6];
    t.at<double>(1) = obj_pose_gt[7];
    t.at<double>(2) = obj_pose_gt[8];
    // from Euler to Rotation Matrix
    cv::Mat R(3, 3, CV_64FC1);
    // assign r vector
    double y = obj_pose_gt[9] + (3.1415926 / 2);  // +(3.1415926/2)
    double x = 0.0;
    double z = 0.0;
    // the angles are in radians.
    double cy = cos(y);
    double sy = sin(y);
    double cx = cos(x);
    double sx = sin(x);
    double cz = cos(z);
    double sz = sin(z);
    double m00, m01, m02, m10, m11, m12, m20, m21, m22;
    m00 = cy * cz + sy * sx * sz;
    m01 = -cy * sz + sy * sx * cz;
    m02 = sy * cx;
    m10 = cx * sz;
    m11 = cx * cz;
    m12 = -sx;
    m20 = -sy * cz + cy * sx * sz;
    m21 = sy * sz + cy * sx * cz;
    m22 = cy * cx;
    R.at<double>(0, 0) = m00;
    R.at<double>(0, 1) = m01;
    R.at<double>(0, 2) = m02;
    R.at<double>(1, 0) = m10;
    R.at<double>(1, 1) = m11;
    R.at<double>(1, 2) = m12;
    R.at<double>(2, 0) = m20;
    R.at<double>(2, 1) = m21;
    R.at<double>(2, 2) = m22;
    // construct 4x4 transformation matrix
    cv::Mat Pose = cv::Mat::eye(4, 4, CV_64F);
    Pose.at<double>(0, 0) = R.at<double>(0, 0);
    Pose.at<double>(0, 1) = R.at<double>(0, 1);
    Pose.at<double>(0, 2) = R.at<double>(0, 2);
    Pose.at<double>(0, 3) = t.at<double>(0);
    Pose.at<double>(1, 0) = R.at<double>(1, 0);
    Pose.at<double>(1, 1) = R.at<double>(1, 1);
    Pose.at<double>(1, 2) = R.at<double>(1, 2);
    Pose.at<double>(1, 3) = t.at<double>(1);
    Pose.at<double>(2, 0) = R.at<double>(2, 0);
    Pose.at<double>(2, 1) = R.at<double>(2, 1);
    Pose.at<double>(2, 2) = R.at<double>(2, 2);
    Pose.at<double>(2, 3) = t.at<double>(2);
    object_pose.L_camera_ = utils::cvMatToGtsamPose3(Pose);
    return object_pose;
  }
References dyno::ObjectPoseGT::bounding_box_, dyno::utils::cvMatToGtsamPose3(), dyno::ObjectPoseGT::frame_id_, dyno::ObjectPoseGT::L_camera_, and dyno::ObjectPoseGT::object_id_.
Referenced by onPathInit().
getFolderName()
std::string dyno::KittiObjectPoseFolder::getFolderName () const inline override virtual
"object_pose.txt" as file name
Returns
std::string
Implements dyno::DataFolder< GroundTruthInputPacket >.
Definition at line 111 of file KittiDataProvider.hpp.
{ return "object_pose.txt"; }
getItem()
GroundTruthInputPacket dyno::KittiObjectPoseFolder::getItem (size_t idx) inline override virtual
Get the Item at an index in the dataset.
The idx should essentually correspond to the frame_id (starting at 0) for this datastream in the dataset.
Parameters
idx
Returns
T
Implements dyno::DataFolder< GroundTruthInputPacket >.
Definition at line 112 of file KittiDataProvider.hpp.
{
    GroundTruthInputPacket& gt_packet = constructGTPacketOnly(idx);
    // if frame idx > 0 calcualte motions
    if (idx > 0) {
      const GroundTruthInputPacket& prev_gt_packet =
          constructGTPacketOnly(idx - 1);
      gt_packet.calculateAndSetMotions(prev_gt_packet);
    }
    return gt_packet;
  }
References dyno::GroundTruthInputPacket::calculateAndSetMotions(), and constructGTPacketOnly().
onPathInit()
void dyno::KittiObjectPoseFolder::onPathInit () inline override private virtual
Setup ifstream and read everything in the data vector.
Reimplemented from dyno::DataFolder< GroundTruthInputPacket >.
Definition at line 130 of file KittiDataProvider.hpp.
{
    std::ifstream object_pose_stream((std::string)getAbsolutePath(),
                                     std::ios::in);
    CHECK(object_pose_stream.good());
    // hmm we dont know the number of expected frames here...
    while (!object_pose_stream.eof()) {
      std::string s;
      getline(object_pose_stream, s);
      if (!s.empty()) {
        std::stringstream ss;
        ss << s;
        std::vector<double> object_pose_vec(10, 0);
        ss >> object_pose_vec[0] >> object_pose_vec[1] >> object_pose_vec[2] >>
            object_pose_vec[3] >> object_pose_vec[4] >> object_pose_vec[5] >>
            object_pose_vec[6] >> object_pose_vec[7] >> object_pose_vec[8] >>
            object_pose_vec[9];
        ObjectPoseGT object_pose = constructObjectPoseGT(object_pose_vec);
        object_poses_.push_back(object_pose);
      }
    }
    object_pose_stream.close();
    // no guarantee that the timestamp loader onPathInit() has been called first
    // (although in reality it will becuase) it is part of the default folder
    // structure check that it has been initalised and then use the timestamps
    // already loaded there to construct the gt packets
    CHECK(timestamp_loader_->isAbsolutePathSet())
        << "Timestamp laoder should be already initalised so we can get the "
           "timestamps from it since they are preloaded!!";
    const size_t n_times = timestamp_loader_->size();
    CHECK(n_times > 0u);
    object_ids_vector_.resize(
        n_times);  // only load up to the number of timestamps given
    for (size_t i = 0; i < object_poses_.size(); i++) {
      const ObjectPoseGT& obect_pose_gt = object_poses_[i];
      size_t frame_id = obect_pose_gt.frame_id_;
      if (frame_id >= object_ids_vector_.size()) {
        break;
      }
      object_ids_vector_[frame_id].push_back(i);
    }
  }
References constructObjectPoseGT(), dyno::ObjectPoseGT::frame_id_, dyno::DataFolder< GroundTruthInputPacket >::getAbsolutePath(), object_ids_vector_, object_poses_, and timestamp_loader_.
Member Data Documentation
camera_pose_loader_
KittiCameraPoseFolder::Ptr dyno::KittiObjectPoseFolder::camera_pose_loader_ private
Definition at line 298 of file KittiDataProvider.hpp.
Referenced by constructGTPacketOnly().
gt_packets_
gtsam::FastMap<FrameId, GroundTruthInputPacket> dyno::KittiObjectPoseFolder::gt_packets_ private
Definition at line 301 of file KittiDataProvider.hpp.
Referenced by constructGTPacketOnly().
initial_pose_
gtsam::Pose3 dyno::KittiObjectPoseFolder::initial_pose_ private
Definition at line 304 of file KittiDataProvider.hpp.
object_ids_vector_
std::vector<ObjectIds> dyno::KittiObjectPoseFolder::object_ids_vector_ private
Definition at line 299 of file KittiDataProvider.hpp.
Referenced by constructGTPacketOnly(), and onPathInit().
object_poses_
std::vector<ObjectPoseGT> dyno::KittiObjectPoseFolder::object_poses_ private
Definition at line 300 of file KittiDataProvider.hpp.
Referenced by constructGTPacketOnly(), and onPathInit().
timestamp_loader_
TimestampFile::Ptr dyno::KittiObjectPoseFolder::timestamp_loader_ private
Definition at line 297 of file KittiDataProvider.hpp.
Referenced by constructGTPacketOnly(), and onPathInit().
The documentation for this class was generated from the following file:
dynosam/include/dynosam/dataprovider/KittiDataProvider.hpp