DynoSAM: dyno::DataFolder< T > Class Template Reference
dyno::DataFolder< T > Class Template Reference abstract
Defines a set of datafiles within a folder to be laoded by a dataset (partially inspired by pytorch's dataset class). Each folder exists within a parent folder (defined by the dataset) and contains a number of files that need to be loaded by this class. As a number of different input image types (motion/instance segmenation, with and without depth etc.) exist the class is expected to handle the different types itself and return the loaded type.
#include <DatasetLoader.hpp>
Public Types
using This = DataFolder< T >
using Type = T
Public Member Functions
DataFolder ()=default
virtual ~DataFolder ()
void initAbsolutePath (const fs::path &absolute_folder_path)
Set the Absolute Folder Path object to be used when an item is loaded This needs to be a setter function since we do not know the absolute path at the time of construction.
operator bool () const
Indicates that the absolute folder path has been set correctly with initAbsolutePath Same behaviour as is isAbsolutePathSet but can operate as a boolean operator.
bool isAbsolutePathSet () const
Checks if the absolute path has been set and the data folder is ready to get items.
fs::path getAbsolutePath () const
virtual std::string getFolderName () const =0
virtual T getItem (size_t idx)=0
Get the Item at an index in the dataset.
Protected Member Functions
virtual void onPathInit ()
Virtual function that is called once the absolute path to this folder is known This happens after construction as the dataset folder (the parent folder) is known by the DataFolderStructure which will set the path on its construction.
Private Attributes
std::optional< fs::path > absolute_folder_path_ {std::nullopt}
Detailed Description
template<typename T = cv::Mat>
class dyno::DataFolder< T >
Defines a set of datafiles within a folder to be laoded by a dataset (partially inspired by pytorch's dataset class). Each folder exists within a parent folder (defined by the dataset) and contains a number of files that need to be loaded by this class. As a number of different input image types (motion/instance segmenation, with and without depth etc.) exist the class is expected to handle the different types itself and return the loaded type.
Template Parameters
T
Definition at line 53 of file DatasetLoader.hpp.
Member Typedef Documentation
This
template<typename T = cv::Mat> using dyno::DataFolder< T >::This = DataFolder<T>
Definition at line 57 of file DatasetLoader.hpp.
Type
template<typename T = cv::Mat> using dyno::DataFolder< T >::Type = T
Definition at line 58 of file DatasetLoader.hpp.
Constructor & Destructor Documentation
DataFolder()
template<typename T = cv::Mat> dyno::DataFolder< T >::DataFolder () default
~DataFolder()
template<typename T = cv::Mat> virtual dyno::DataFolder< T >::~DataFolder () inline virtual
Definition at line 61 of file DatasetLoader.hpp.
{}
Member Function Documentation
getAbsolutePath()
template<typename T = cv::Mat> fs::path dyno::DataFolder< T >::getAbsolutePath () const inline
Definition at line 106 of file DatasetLoader.hpp.
{
        if(!absolute_folder_path_) {
            throw std::runtime_error("Error accessing absolute folder path for DataFolder (" + getFolderName() + "). Has the path been set with initAbsolutePath()?");
        }
        return absolute_folder_path_.value();
    }
References dyno::DataFolder< T >::absolute_folder_path_, and dyno::DataFolder< T >::getFolderName().
getFolderName()
template<typename T = cv::Mat> virtual std::string dyno::DataFolder< T >::getFolderName () const pure virtual
Implemented in dyno::FunctionalDataFolder< T >, dyno::RGBDataFolder, dyno::OpticalFlowDataFolder, dyno::DepthDataFolder, dyno::InstantanceSegMaskFolder, dyno::MotionSegMaskFolder, dyno::TimestampFile, dyno::KittiCameraPoseFolder, dyno::KittiObjectPoseFolder, dyno::KittiClassSegmentationDataFolder, dyno::ClusterSlamTimestampLoader, dyno::OMMTimestampLoader, dyno::ProjectAriaTimestampLoader, dyno::GenericVirtualKittiImageLoader, dyno::VirtualKittiTimestampLoader, and dyno::VirtualKittiGTFolder.
Referenced by dyno::DataFolder< T >::getAbsolutePath().
getItem()
template<typename T = cv::Mat> virtual T dyno::DataFolder< T >::getItem (size_t idx) pure virtual
Get the Item at an index in the dataset.
The idx should essentually correspond to the frame_id (starting at 0) for this datastream in the dataset.
Parameters
idx
Returns
T
Implemented in dyno::FunctionalDataFolder< T >, dyno::RGBDataFolder, dyno::OpticalFlowDataFolder, dyno::DepthDataFolder, dyno::SegMaskFolder, dyno::TimestampFile, dyno::KittiCameraPoseFolder, dyno::KittiObjectPoseFolder, dyno::KittiClassSegmentationDataFolder, dyno::ClusterSlamTimestampLoader, dyno::OMMTimestampLoader, dyno::ProjectAriaTimestampLoader, dyno::VirtualKittiRGBDataFolder, dyno::VirtualKittiFlowDataFolder, dyno::VirtualKittiDepthDataFolder, dyno::VirtualKittiTimestampLoader, dyno::VirtualKittiGenericInstanceSegFolder, dyno::VirtualKittiClassSegmentationDataFolder, and dyno::VirtualKittiGTFolder.
initAbsolutePath()
template<typename T = cv::Mat> void dyno::DataFolder< T >::initAbsolutePath (const fs::path & absolute_folder_path) inline
Set the Absolute Folder Path object to be used when an item is loaded This needs to be a setter function since we do not know the absolute path at the time of construction.
Once set, the virtual onPathInit function is called, which can act like a constructor to the derived classes
In the context of a dataset laoder, this function is guaranteed to be called be
Parameters
absolute_folder_path
Definition at line 73 of file DatasetLoader.hpp.
{
        absolute_folder_path_ = absolute_folder_path;
        try {
            onPathInit();
        }
        catch(const std::exception& e) {
            LOG(FATAL) << "Exception caught when running virtual onPathInit for DataFolder with absolute path: " << absolute_folder_path
                << ". Error: " << e.what();
        }
    }
References dyno::DataFolder< T >::absolute_folder_path_, and dyno::DataFolder< T >::onPathInit().
isAbsolutePathSet()
template<typename T = cv::Mat> bool dyno::DataFolder< T >::isAbsolutePathSet () const inline
Checks if the absolute path has been set and the data folder is ready to get items.
Returns
true
false
Definition at line 102 of file DatasetLoader.hpp.
{
        return (bool)absolute_folder_path_;
    }
References dyno::DataFolder< T >::absolute_folder_path_.
Referenced by dyno::DataFolder< T >::operator bool().
onPathInit()
template<typename T = cv::Mat> virtual void dyno::DataFolder< T >::onPathInit () inline protected virtual
Virtual function that is called once the absolute path to this folder is known This happens after construction as the dataset folder (the parent folder) is known by the DataFolderStructure which will set the path on its construction.
The absolute folder path can be accessed This::getAbsolutePath
Reimplemented in dyno::TimestampFile, dyno::KittiCameraPoseFolder, and dyno::KittiObjectPoseFolder.
Definition at line 135 of file DatasetLoader.hpp.
{}
Referenced by dyno::DataFolder< T >::initAbsolutePath().
operator bool()
template<typename T = cv::Mat> dyno::DataFolder< T >::operator bool () const inline explicit
Indicates that the absolute folder path has been set correctly with initAbsolutePath Same behaviour as is isAbsolutePathSet but can operate as a boolean operator.
Returns
true
false
Definition at line 92 of file DatasetLoader.hpp.
{
        return isAbsolutePathSet();
    }
References dyno::DataFolder< T >::isAbsolutePathSet().
Member Data Documentation
absolute_folder_path_
template<typename T = cv::Mat> std::optional<fs::path> dyno::DataFolder< T >::absolute_folder_path_ {std::nullopt} private
Set when init is called since we need a default constructor. This will not have the ending "/" on it Initially set to nullopt so we can check that the folder has been properly initalised via initAbsoluteFolderPath
Definition at line 140 of file DatasetLoader.hpp.
Referenced by dyno::DataFolder< T >::getAbsolutePath(), dyno::DataFolder< T >::initAbsolutePath(), and dyno::DataFolder< T >::isAbsolutePathSet().
The documentation for this class was generated from the following file:
dynosam/include/dynosam/dataprovider/DatasetLoader.hpp