DynoSAM: dyno::DisplayBase< INPUT > Class Template Reference
dyno::DisplayBase< INPUT > Class Template Reference abstract
#include <Display.hpp>
Public Types
using Input = INPUT
using This = DisplayBase< INPUT >
using InputConstPtr = typename INPUT::ConstPtr
Public Member Functions
DisplayBase ()
virtual ~DisplayBase ()
void spinOnce (const InputConstPtr &input)
Protected Member Functions
virtual void spinOnceImpl (const InputConstPtr &input)=0
Additional Inherited Members
Public Attributes inherited from dyno::SharedModuleInterface
SharedModuleInfo & shared_module_info = SharedModuleInfo::instance()
Detailed Description
template<typename INPUT>
class dyno::DisplayBase< INPUT >
Definition at line 58 of file Display.hpp.
Member Typedef Documentation
Input
template<typename INPUT > using dyno::DisplayBase< INPUT >::Input = INPUT
Definition at line 60 of file Display.hpp.
InputConstPtr
template<typename INPUT > using dyno::DisplayBase< INPUT >::InputConstPtr = typename INPUT::ConstPtr
Definition at line 64 of file Display.hpp.
This
template<typename INPUT > using dyno::DisplayBase< INPUT >::This = DisplayBase<INPUT>
Definition at line 61 of file Display.hpp.
Constructor & Destructor Documentation
DisplayBase()
template<typename INPUT > dyno::DisplayBase< INPUT >::DisplayBase () inline
Definition at line 66 of file Display.hpp.
{}
~DisplayBase()
template<typename INPUT > virtual dyno::DisplayBase< INPUT >::~DisplayBase () inline virtual
Definition at line 67 of file Display.hpp.
{}
Member Function Documentation
spinOnce()
template<typename INPUT > void dyno::DisplayBase< INPUT >::spinOnce (const InputConstPtr & input) inline
Definition at line 69 of file Display.hpp.
{
    CHECK(input);
    auto [timestamp, frame_id] = internal::collectTemporalData<INPUT>(*input);
    this->shared_module_info.updateTimestampMapping(frame_id, timestamp);
    spinOnceImpl(input);
  }
References dyno::SharedModuleInterface::shared_module_info, dyno::DisplayBase< INPUT >::spinOnceImpl(), and dyno::SharedModuleInfo::updateTimestampMapping().
spinOnceImpl()
template<typename INPUT > virtual void dyno::DisplayBase< INPUT >::spinOnceImpl (const InputConstPtr & input) protected pure virtual
Referenced by dyno::DisplayBase< INPUT >::spinOnce().
The documentation for this class was generated from the following file:
dynosam/include/dynosam/visualizer/Display.hpp