DynoSAM: dyno::utils::TimingStatsCollector Class Reference
dyno::utils::TimingStatsCollector Class Reference
#include <TimingStats.hpp>
Public Member Functions
TimingStatsCollector (const std::string &tag)
~TimingStatsCollector ()
void reset ()
Resets the current tic_time and sets is_valid = true, such that when the collector tries to toc, the tic (comparison time) will be valid.
bool isValid () const
Private Member Functions
void tocAndLog ()
Creates a toc time to compare against the latest tic time and logs the diff as sample to the collector.
Private Attributes
Timer::TimePoint tic_time_
StatsCollector collector_
Time on creation (the time to compare against)
std::atomic_bool is_valid_
Detailed Description
Definition at line 104 of file TimingStats.hpp.
Constructor & Destructor Documentation
TimingStatsCollector()
dyno::utils::TimingStatsCollector::TimingStatsCollector (const std::string & tag)
Definition at line 42 of file TimingStats.cc.
    : tic_time_(Timer::tic()), collector_(tag + " [ms]") {}
~TimingStatsCollector()
dyno::utils::TimingStatsCollector::~TimingStatsCollector ()
Definition at line 45 of file TimingStats.cc.
{ tocAndLog(); }
References tocAndLog().
Member Function Documentation
isValid()
bool dyno::utils::TimingStatsCollector::isValid () const
Definition at line 52 of file TimingStats.cc.
{ return is_valid_; }
References is_valid_.
reset()
void dyno::utils::TimingStatsCollector::reset ()
Resets the current tic_time and sets is_valid = true, such that when the collector tries to toc, the tic (comparison time) will be valid.
Definition at line 47 of file TimingStats.cc.
{
  tic_time_ = Timer::tic();
  is_valid_ = true;
}
References is_valid_, dyno::utils::Timer::tic(), and tic_time_.
tocAndLog()
void dyno::utils::TimingStatsCollector::tocAndLog () private
Creates a toc time to compare against the latest tic time and logs the diff as sample to the collector.
Only logs if is_valid_ == true, after which is_valid will be set to false. The collector then needs to be reset to be used again
Definition at line 54 of file TimingStats.cc.
{
  if (is_valid_) {
    auto toc = Timer::toc<std::chrono::nanoseconds>(tic_time_);
    auto milliseconds =
        std::chrono::duration_cast<std::chrono::milliseconds>(toc);
    collector_.AddSample(static_cast<double>(milliseconds.count()));
    is_valid_ = false;
  }
}
References dyno::utils::StatsCollectorImpl::AddSample(), collector_, is_valid_, and tic_time_.
Referenced by ~TimingStatsCollector().
Member Data Documentation
collector_
StatsCollector dyno::utils::TimingStatsCollector::collector_ private
Time on creation (the time to compare against)
Definition at line 136 of file TimingStats.hpp.
Referenced by tocAndLog().
is_valid_
std::atomic_bool dyno::utils::TimingStatsCollector::is_valid_ private
Initial value:
{
      true}
Definition at line 138 of file TimingStats.hpp.
Referenced by isValid(), reset(), and tocAndLog().
tic_time_
Timer::TimePoint dyno::utils::TimingStatsCollector::tic_time_ private
Definition at line 135 of file TimingStats.hpp.
Referenced by reset(), and tocAndLog().
The documentation for this class was generated from the following files:
dynosam_common/include/dynosam_common/utils/TimingStats.hpp
dynosam_common/src/utils/TimingStats.cc