DynoSAM: dyno::DSDTransport::Publisher Class Reference
dyno::DSDTransport::Publisher Class Reference
Nested Publisher that publishes all the object odometries for a single frame/timestamp. Object odometries are set on construction. Functionality for publishing the object odom's themselves and broadcasting their position on the tf tree using the object current pose is addionally included.
#include <DSDCommonRos.hpp>
Public Member Functions
void publishObjectOdometry ()
Publish the contained object odometries.
void publishObjectTransforms ()
Broadcast the transform of each object using their pose. Transforms will be constructed between the Publisher::frame_id_link_ and object frame link (as the child_frame_id).
void publishObjectPaths ()
FrameId getFrameId () const
Get the frame id.
Timestamp getTimestamp () const
const std::string & getFrameIdLink () const
Get the (tf) frame id used as the parent of the tree.
Private Member Functions
Publisher (rclcpp::Node::SharedPtr node, ObjectOdometryPub::SharedPtr object_odom_publisher, MultiObjectOdometryPathPub::SharedPtr multi_object_odom_path_publisher, std::shared_ptr< tf2_ros::TransformBroadcaster > tf_broadcaster, const ObjectMotionMap &motions, const ObjectPoseMap &poses, const std::string &frame_id_link, const FrameIdTimestampMap &frame_timestamp_map, FrameId frame_id, Timestamp timestamp)
Construct a new Publisher object. Upon construction the publisher will broadcast to the 'object_odometry' topic under the effective namespace of the provided node.
Private Attributes
rclcpp::Node::SharedPtr node_
ObjectOdometryPub::SharedPtr object_odom_publisher_
MultiObjectOdometryPathPub::SharedPtr multi_object_odom_path_publisher_
std::shared_ptr< tf2_ros::TransformBroadcaster > tf_broadcaster_
std::string frame_id_link_
FrameId frame_id_
Timestamp timestamp_
ObjectOdometryMap object_odometries_
Object odometries for this frame.
MultiObjectOdometryPath object_paths_
Friends
class DSDTransport
Detailed Description
Nested Publisher that publishes all the object odometries for a single frame/timestamp. Object odometries are set on construction. Functionality for publishing the object odom's themselves and broadcasting their position on the tf tree using the object current pose is addionally included.
Definition at line 108 of file DSDCommonRos.hpp.
Constructor & Destructor Documentation
Publisher()
dyno::DSDTransport::Publisher::Publisher (rclcpp::Node::SharedPtr node, ObjectOdometryPub::SharedPtr object_odom_publisher, MultiObjectOdometryPathPub::SharedPtr multi_object_odom_path_publisher, std::shared_ptr< tf2_ros::TransformBroadcaster > tf_broadcaster, const ObjectMotionMap & motions, const ObjectPoseMap & poses, const std::string & frame_id_link, const FrameIdTimestampMap & frame_timestamp_map, FrameId frame_id, Timestamp timestamp) private
Construct a new Publisher object. Upon construction the publisher will broadcast to the 'object_odometry' topic under the effective namespace of the provided node.
Parameters
node rclcpp::Node::SharedPtr
object_odom_publisher ObjectOdometryPub::SharedPtr Object odom publisher to share between all Publishers.
multi_object_odom_path_publisher MultiObjectOdometryPathPub::SharedPtr
tf_broadcaster std::shared_ptr<tf2_ros::TransformBroadcaster> TF broadcaster to share between all Publishers.
motions const ObjectMotionMap& motions at time (... to k)
poses const ObjectPoseMap& poses at time (... to k)
frame_id_link const std::string& parent tf tree link (e.g. odom/world.)
frame_id FrameId current frame (k)
timestamp Timestamp
Definition at line 227 of file DSDCommonRos.cc.
    : node_(node),
      object_odom_publisher_(object_odom_publisher),
      multi_object_odom_path_publisher_(multi_object_odom_path_publisher),
      tf_broadcaster_(tf_broadcaster),
      frame_id_link_(frame_id_link),
      frame_id_(frame_id),
      timestamp_(timestamp),
      object_odometries_(DSDTransport::constructObjectOdometries(
          motions, poses, frame_id, timestamp, frame_id_link)),
      object_paths_(DSDTransport::constructMultiObjectOdometryPaths(
          motions, poses, timestamp, frame_timestamp_map, frame_id_link)) {}
Member Function Documentation
getFrameId()
FrameId dyno::DSDTransport::Publisher::getFrameId () const inline
Get the frame id.
Returns
FrameId
Definition at line 131 of file DSDCommonRos.hpp.
{ return frame_id_; }
References frame_id_.
getFrameIdLink()
const std::string & dyno::DSDTransport::Publisher::getFrameIdLink () const inline
Get the (tf) frame id used as the parent of the tree.
Returns
const std::string&
Definition at line 139 of file DSDCommonRos.hpp.
{ return frame_id_link_; }
References frame_id_link_.
getTimestamp()
Timestamp dyno::DSDTransport::Publisher::getTimestamp () const inline
Definition at line 132 of file DSDCommonRos.hpp.
{ return timestamp_; }
References timestamp_.
publishObjectOdometry()
void dyno::DSDTransport::Publisher::publishObjectOdometry ()
Publish the contained object odometries.
Definition at line 205 of file DSDCommonRos.cc.
{
  for (const auto& [_, object_odom] : object_odometries_)
    object_odom_publisher_->publish(object_odom);
}
References object_odom_publisher_, and object_odometries_.
Referenced by dyno::BackendDSDRos::spinOnceImpl(), dyno::FrontendDSDRos::tryPublishGroundTruth(), and dyno::FrontendDSDRos::tryPublishObjects().
publishObjectPaths()
void dyno::DSDTransport::Publisher::publishObjectPaths ()
Definition at line 223 of file DSDCommonRos.cc.
{
  multi_object_odom_path_publisher_->publish(object_paths_);
}
References dyno::DSDTransport::multi_object_odom_path_publisher_.
Referenced by dyno::BackendDSDRos::spinOnceImpl(), and dyno::FrontendDSDRos::tryPublishObjects().
publishObjectTransforms()
void dyno::DSDTransport::Publisher::publishObjectTransforms ()
Broadcast the transform of each object using their pose. Transforms will be constructed between the Publisher::frame_id_link_ and object frame link (as the child_frame_id).
Definition at line 210 of file DSDCommonRos.cc.
{
  for (const auto& [object_child_frame, object_odom] : object_odometries_) {
    geometry_msgs::msg::TransformStamped t;
    dyno::convert(object_odom.odom.pose.pose, t.transform);
    t.header.stamp = utils::toRosTime(timestamp_);
    t.header.frame_id = frame_id_link_;
    t.child_frame_id = object_child_frame;
    tf_broadcaster_->sendTransform(t);
  }
}
References dyno::convert(), dyno::DSDTransport::tf_broadcaster_, and dyno::utils::toRosTime().
Referenced by dyno::FrontendDSDRos::tryPublishObjects().
Friends And Related Function Documentation
DSDTransport
friend class DSDTransport friend
Definition at line 154 of file DSDCommonRos.hpp.
Member Data Documentation
frame_id_
FrameId dyno::DSDTransport::Publisher::frame_id_ private
Definition at line 147 of file DSDCommonRos.hpp.
Referenced by getFrameId().
frame_id_link_
std::string dyno::DSDTransport::Publisher::frame_id_link_ private
Definition at line 146 of file DSDCommonRos.hpp.
Referenced by getFrameIdLink().
multi_object_odom_path_publisher_
MultiObjectOdometryPathPub::SharedPtr dyno::DSDTransport::Publisher::multi_object_odom_path_publisher_ private
Definition at line 144 of file DSDCommonRos.hpp.
node_
rclcpp::Node::SharedPtr dyno::DSDTransport::Publisher::node_ private
Definition at line 142 of file DSDCommonRos.hpp.
object_odom_publisher_
ObjectOdometryPub::SharedPtr dyno::DSDTransport::Publisher::object_odom_publisher_ private
Definition at line 143 of file DSDCommonRos.hpp.
Referenced by publishObjectOdometry().
object_odometries_
ObjectOdometryMap dyno::DSDTransport::Publisher::object_odometries_ private
Object odometries for this frame.
Definition at line 151 of file DSDCommonRos.hpp.
Referenced by publishObjectOdometry().
object_paths_
MultiObjectOdometryPath dyno::DSDTransport::Publisher::object_paths_ private
Definition at line 152 of file DSDCommonRos.hpp.
tf_broadcaster_
std::shared_ptr<tf2_ros::TransformBroadcaster> dyno::DSDTransport::Publisher::tf_broadcaster_ private
Definition at line 145 of file DSDCommonRos.hpp.
timestamp_
Timestamp dyno::DSDTransport::Publisher::timestamp_ private
Definition at line 148 of file DSDCommonRos.hpp.
Referenced by getTimestamp().
The documentation for this class was generated from the following files:
dynosam_ros/include/dynosam_ros/displays/dynamic_slam_displays/DSDCommonRos.hpp
dynosam_ros/src/displays/dynamic_slam_displays/DSDCommonRos.cc