DynoSAM: dyno::utils::StatsCollectorImpl Class Reference
dyno::utils::StatsCollectorImpl Class Reference
#include <Statistics.hpp>
Public Member Functions
StatsCollectorImpl (size_t handle)
StatsCollectorImpl (std::string const &tag)
virtual ~StatsCollectorImpl ()=default
void AddSample (double sample) const
void IncrementOne () const
size_t GetHandle () const
Private Attributes
size_t handle_
Detailed Description
Definition at line 172 of file Statistics.hpp.
Constructor & Destructor Documentation
StatsCollectorImpl() [1/2]
dyno::utils::StatsCollectorImpl::StatsCollectorImpl (size_t handle) explicit
Definition at line 127 of file Statistics.cc.
: handle_(handle) {}
StatsCollectorImpl() [2/2]
dyno::utils::StatsCollectorImpl::StatsCollectorImpl (std::string const & tag) explicit
Definition at line 129 of file Statistics.cc.
    : handle_(Statistics::GetHandle(tag)) {}
~StatsCollectorImpl()
virtual dyno::utils::StatsCollectorImpl::~StatsCollectorImpl () virtual default
Member Function Documentation
AddSample()
void dyno::utils::StatsCollectorImpl::AddSample (double sample) const
Definition at line 133 of file Statistics.cc.
{
  Statistics::Instance().AddSample(handle_, sample);
}
References dyno::utils::Statistics::AddSample(), handle_, and dyno::utils::Statistics::Instance().
Referenced by dyno::DataInterfacePipeline::getInputPacket(), dyno::ParallelHybridBackendModule::nominalUpdateStaticEstimator(), dyno::OpticalFlowAndPoseOptimizer::optimize(), dyno::MotionOnlyRefinementOptimizer::optimize(), dyno::RegularBackendModule::updateBatch(), and dyno::ParallelObjectISAM::updateSmoother().
GetHandle()
size_t dyno::utils::StatsCollectorImpl::GetHandle () const
Definition at line 132 of file Statistics.cc.
{ return handle_; }
References handle_.
IncrementOne()
void dyno::utils::StatsCollectorImpl::IncrementOne () const
Definition at line 136 of file Statistics.cc.
{
  Statistics::Instance().AddSample(handle_, 1.0);
}
References dyno::utils::Statistics::AddSample(), handle_, and dyno::utils::Statistics::Instance().
Member Data Documentation
handle_
size_t dyno::utils::StatsCollectorImpl::handle_ private
Definition at line 183 of file Statistics.hpp.
Referenced by AddSample(), GetHandle(), and IncrementOne().
The documentation for this class was generated from the following files:
dynosam_common/include/dynosam_common/utils/Statistics.hpp
dynosam_common/src/utils/Statistics.cc