DynoSAM: dyno::TrackedValueStatus< VALUE > Class Template Reference
dyno::TrackedValueStatus< VALUE > Class Template Reference
#include <Types.hpp>
Public Types
using Value = VALUE
using This = TrackedValueStatus< Value >
Public Member Functions
TrackedValueStatus ()
TrackedValueStatus (const Value &value, FrameId frame_id, TrackletId tracklet_id, ObjectId label, ReferenceFrame reference_frame)
virtual ~TrackedValueStatus ()=default
template<typename U >
TrackedValueStatus< U > asType () const
Allows the casting of the internal value type to another using static casting.
const Value & value () const
Get value. Const version.
Value & value ()
Get value. Reference version.
TrackletId trackletId () const
Get tracklet id (i) for this status.
ObjectId objectId () const
Get object id (j) for this status.
FrameId frameId () const
Get frame id (k) for this status.
const ReferenceFrame & referenceFrame () const
Get the reference frame the value is in. Const version.
ReferenceFrame & referenceFrame ()
Get the reference frame the value is in.
ReferenceFrameValue< Value > & referenceFrameValue ()
Get the full reference frame and value.
const ReferenceFrameValue< Value > & referenceFrameValue () const
Get the full reference frame and value. Const version.
bool operator== (const This &other) const
bool isStatic () const
Returns true if the object lavel is equal to dyno::background_label.
bool isTimeInvariant () const
Returns true if frame_id is equal to MeaninglessFrame (e.g. std::numeric_limits<FrameId>::quiet_NaN) and should indicatate that the value represented by this TrackedValueStatus is time-invariant, e.g. for a static point which does not change overtime.
Static Public Attributes
static constexpr auto MeaninglessFrame = std::numeric_limits<FrameId>::max()
Protected Attributes
ReferenceFrameValue< Value > value_
FrameId frame_id_
TrackletId tracklet_id_
ObjectId label_
Friends
std::ostream & operator<< (std::ostream &os, const This &t)
Detailed Description
template<typename VALUE>
class dyno::TrackedValueStatus< VALUE >
Definition at line 281 of file Types.hpp.
Member Typedef Documentation
This
template<typename VALUE > using dyno::TrackedValueStatus< VALUE >::This = TrackedValueStatus<Value>
Definition at line 284 of file Types.hpp.
Value
template<typename VALUE > using dyno::TrackedValueStatus< VALUE >::Value = VALUE
Definition at line 283 of file Types.hpp.
Constructor & Destructor Documentation
TrackedValueStatus() [1/2]
template<typename VALUE > dyno::TrackedValueStatus< VALUE >::TrackedValueStatus () inline
Definition at line 295 of file Types.hpp.
{}
TrackedValueStatus() [2/2]
template<typename VALUE > dyno::TrackedValueStatus< VALUE >::TrackedValueStatus (const Value & value, FrameId frame_id, TrackletId tracklet_id, ObjectId label, ReferenceFrame reference_frame) inline
Definition at line 299 of file Types.hpp.
      : value_(value, reference_frame),
        frame_id_(frame_id),
        tracklet_id_(tracklet_id),
        label_(label) {}
~TrackedValueStatus()
template<typename VALUE > virtual dyno::TrackedValueStatus< VALUE >::~TrackedValueStatus () virtual default
Member Function Documentation
asType()
template<typename VALUE > template<typename U > TrackedValueStatus< U > dyno::TrackedValueStatus< VALUE >::asType () const inline
Allows the casting of the internal value type to another using static casting.
This allows sub measurements to be extracted if T has explict cast operators. e.g. struct Foo { operator Bar&(); }
we can use as type to construct a TrackedValueStatus<Bar> from TrackedValueStatus<Foo>: TrackedValueStatus<Foo> foo(...); TrackedValueStatus<Bar> bar = foo.asType<Bar>();
This will copy over all the meta-data (e.g. frame id, label etc) but replace the value with the cast Boo type. This is only possible since Foo contains an operator for Bar, allowing static casting to work.
This function exists to allow nested data-types for VALUE to be used, where each sub-value can be extracted using asType(), as long as the casting operating works.
Template Parameters
U
Returns
TrackedValueStatus
Definition at line 332 of file Types.hpp.
{
    const U& new_measurement = static_cast<const U&>(this->value());
    return TrackedValueStatus<U>(new_measurement, this->frameId(),
                                 this->trackletId(), this->objectId(),
                                 this->referenceFrame());
  }
References dyno::TrackedValueStatus< VALUE >::frameId(), dyno::TrackedValueStatus< VALUE >::objectId(), dyno::TrackedValueStatus< VALUE >::referenceFrame(), dyno::TrackedValueStatus< VALUE >::trackletId(), and dyno::TrackedValueStatus< VALUE >::value().
frameId()
template<typename VALUE > FrameId dyno::TrackedValueStatus< VALUE >::frameId () const inline
Get frame id (k) for this status.
Returns
FrameId
Definition at line 372 of file Types.hpp.
{ return frame_id_; }
References dyno::TrackedValueStatus< VALUE >::frame_id_.
Referenced by dyno::TrackedValueStatus< VALUE >::asType(), and dyno::Map< MEASUREMENT >::updateObservations().
isStatic()
template<typename VALUE > bool dyno::TrackedValueStatus< VALUE >::isStatic () const inline
Returns true if the object lavel is equal to dyno::background_label.
Returns
true
false
Definition at line 425 of file Types.hpp.
{ return label_ == background_label; }
References dyno::background_label, and dyno::TrackedValueStatus< VALUE >::label_.
Referenced by dyno::convert(), and dyno::Map< MEASUREMENT >::updateObservations().
isTimeInvariant()
template<typename VALUE > bool dyno::TrackedValueStatus< VALUE >::isTimeInvariant () const inline
Returns true if frame_id is equal to MeaninglessFrame (e.g. std::numeric_limits<FrameId>::quiet_NaN) and should indicatate that the value represented by this TrackedValueStatus is time-invariant, e.g. for a static point which does not change overtime.
Returns
true
false
Definition at line 435 of file Types.hpp.
{ return frame_id_ == MeaninglessFrame; }
References dyno::TrackedValueStatus< VALUE >::frame_id_, and dyno::TrackedValueStatus< VALUE >::MeaninglessFrame.
objectId()
template<typename VALUE > ObjectId dyno::TrackedValueStatus< VALUE >::objectId () const inline
Get object id (j) for this status.
Returns
ObjectId
Definition at line 365 of file Types.hpp.
{ return label_; }
References dyno::TrackedValueStatus< VALUE >::label_.
Referenced by dyno::TrackedValueStatus< VALUE >::asType(), dyno::convert(), and dyno::Map< MEASUREMENT >::updateObservations().
operator==()
template<typename VALUE > bool dyno::TrackedValueStatus< VALUE >::operator== (const This & other) const inline
Definition at line 404 of file Types.hpp.
{
    return gtsam::traits<Value>::Equals(this->value(), other.value()) &&
           frame_id_ == other.frame_id_ && tracklet_id_ == other.tracklet_id_ &&
           label_ == other.label_ &&
           this->referenceFrame() == other.referenceFrame();
  }
References dyno::TrackedValueStatus< VALUE >::frame_id_, dyno::TrackedValueStatus< VALUE >::label_, dyno::TrackedValueStatus< VALUE >::referenceFrame(), dyno::TrackedValueStatus< VALUE >::tracklet_id_, and dyno::TrackedValueStatus< VALUE >::value().
referenceFrame() [1/2]
template<typename VALUE > ReferenceFrame & dyno::TrackedValueStatus< VALUE >::referenceFrame () inline
Get the reference frame the value is in.
Returns
ReferenceFrame&
Definition at line 386 of file Types.hpp.
{ return value_; }
References dyno::TrackedValueStatus< VALUE >::value_.
referenceFrame() [2/2]
template<typename VALUE > const ReferenceFrame & dyno::TrackedValueStatus< VALUE >::referenceFrame () const inline
Get the reference frame the value is in. Const version.
Returns
const ReferenceFrame&
Definition at line 379 of file Types.hpp.
{ return value_; }
References dyno::TrackedValueStatus< VALUE >::value_.
Referenced by dyno::TrackedValueStatus< VALUE >::asType(), and dyno::TrackedValueStatus< VALUE >::operator==().
referenceFrameValue() [1/2]
template<typename VALUE > ReferenceFrameValue< Value > & dyno::TrackedValueStatus< VALUE >::referenceFrameValue () inline
Get the full reference frame and value.
Returns
ReferenceFrameValue<Value>&
Definition at line 393 of file Types.hpp.
{ return value_; }
References dyno::TrackedValueStatus< VALUE >::value_.
referenceFrameValue() [2/2]
template<typename VALUE > const ReferenceFrameValue< Value > & dyno::TrackedValueStatus< VALUE >::referenceFrameValue () const inline
Get the full reference frame and value. Const version.
Returns
const ReferenceFrameValue<Value>&
Definition at line 400 of file Types.hpp.
{
    return value_;
  }
References dyno::TrackedValueStatus< VALUE >::value_.
trackletId()
template<typename VALUE > TrackletId dyno::TrackedValueStatus< VALUE >::trackletId () const inline
Get tracklet id (i) for this status.
Returns
TrackletId
Definition at line 358 of file Types.hpp.
{ return tracklet_id_; }
References dyno::TrackedValueStatus< VALUE >::tracklet_id_.
Referenced by dyno::TrackedValueStatus< VALUE >::asType(), and dyno::Map< MEASUREMENT >::updateObservations().
value() [1/2]
template<typename VALUE > Value & dyno::TrackedValueStatus< VALUE >::value () inline
Get value. Reference version.
Returns
Value&
Definition at line 351 of file Types.hpp.
{ return value_; }
References dyno::TrackedValueStatus< VALUE >::value_.
value() [2/2]
template<typename VALUE > const Value & dyno::TrackedValueStatus< VALUE >::value () const inline
Get value. Const version.
Returns
const Value&
Definition at line 344 of file Types.hpp.
{ return value_; }
References dyno::TrackedValueStatus< VALUE >::value_.
Referenced by dyno::TrackedValueStatus< VALUE >::asType(), dyno::convert(), and dyno::TrackedValueStatus< VALUE >::operator==().
Friends And Related Function Documentation
operator<<
template<typename VALUE > std::ostream & operator<< (std::ostream & os, const This & t) friend
Definition at line 411 of file Types.hpp.
{
    os << type_name<Value>() << ": " << t.value() << "\n";
    os << "frame id: " << t.frameId() << "\n";
    os << "tracklet id: " << t.trackletId() << "\n";
    os << "object id: " << t.objectId() << "\n";
    return os;
  }
Member Data Documentation
frame_id_
template<typename VALUE > FrameId dyno::TrackedValueStatus< VALUE >::frame_id_ protected
Definition at line 439 of file Types.hpp.
Referenced by dyno::TrackedValueStatus< VALUE >::frameId(), dyno::TrackedValueStatus< VALUE >::isTimeInvariant(), and dyno::TrackedValueStatus< VALUE >::operator==().
label_
template<typename VALUE > ObjectId dyno::TrackedValueStatus< VALUE >::label_ protected
Definition at line 441 of file Types.hpp.
Referenced by dyno::TrackedValueStatus< VALUE >::isStatic(), dyno::TrackedValueStatus< VALUE >::objectId(), and dyno::TrackedValueStatus< VALUE >::operator==().
MeaninglessFrame
template<typename VALUE > constexpr auto dyno::TrackedValueStatus< VALUE >::MeaninglessFrame = std::numeric_limits<FrameId>::max() static constexpr
Definition at line 292 of file Types.hpp.
Referenced by dyno::TrackedValueStatus< VALUE >::isTimeInvariant().
tracklet_id_
template<typename VALUE > TrackletId dyno::TrackedValueStatus< VALUE >::tracklet_id_ protected
Definition at line 440 of file Types.hpp.
Referenced by dyno::TrackedValueStatus< VALUE >::operator==(), and dyno::TrackedValueStatus< VALUE >::trackletId().
value_
template<typename VALUE > ReferenceFrameValue<Value> dyno::TrackedValueStatus< VALUE >::value_ protected
Definition at line 438 of file Types.hpp.
Referenced by dyno::TrackedValueStatus< VALUE >::referenceFrame(), dyno::TrackedValueStatus< VALUE >::referenceFrameValue(), and dyno::TrackedValueStatus< VALUE >::value().
The documentation for this class was generated from the following file:
dynosam_common/include/dynosam_common/Types.hpp