DynoSAM: dyno::VirtualKittiClassSegmentationDataFolder Class Reference
dyno::VirtualKittiClassSegmentationDataFolder Class Reference
Public Member Functions
VirtualKittiClassSegmentationDataFolder (const std::string &path)
cv::Mat getItem (size_t idx) override
Get the Item at an index in the dataset.
Public Member Functions inherited from dyno::GenericVirtualKittiImageLoader
GenericVirtualKittiImageLoader (const std::string &full_path)
std::string getFolderName () const override
Public Member Functions inherited from dyno::DataFolder< cv::Mat >
DataFolder ()=default
virtual ~DataFolder ()
void initAbsolutePath (const fs::path &absolute_folder_path)
Set the Absolute Folder Path object to be used when an item is loaded This needs to be a setter function since we do not know the absolute path at the time of construction.
operator bool () const
Indicates that the absolute folder path has been set correctly with initAbsolutePath Same behaviour as is isAbsolutePathSet but can operate as a boolean operator.
bool isAbsolutePathSet () const
Checks if the absolute path has been set and the data folder is ready to get items.
fs::path getAbsolutePath () const
virtual std::string getFolderName () const=0
virtual cv::Mat getItem (size_t idx)=0
Get the Item at an index in the dataset.
Private Member Functions
cv::Mat loadClassSegmentation (const std::string &file_path) const
Additional Inherited Members
Public Types inherited from dyno::DataFolder< cv::Mat >
using This = DataFolder< cv::Mat >
using Type = cv::Mat
Public Attributes inherited from dyno::GenericVirtualKittiImageLoader
const std::string full_path_
Protected Member Functions inherited from dyno::DataFolder< cv::Mat >
virtual void onPathInit ()
Virtual function that is called once the absolute path to this folder is known This happens after construction as the dataset folder (the parent folder) is known by the DataFolderStructure which will set the path on its construction.
Detailed Description
Definition at line 752 of file VirtualKittidataProvider.cc.
Constructor & Destructor Documentation
VirtualKittiClassSegmentationDataFolder()
dyno::VirtualKittiClassSegmentationDataFolder::VirtualKittiClassSegmentationDataFolder (const std::string & path) inline
Definition at line 755 of file VirtualKittidataProvider.cc.
: GenericVirtualKittiImageLoader(path) {}
Member Function Documentation
getItem()
cv::Mat dyno::VirtualKittiClassSegmentationDataFolder::getItem (size_t idx) inline override virtual
Get the Item at an index in the dataset.
The idx should essentually correspond to the frame_id (starting at 0) for this datastream in the dataset.
Parameters
idx
Returns
T
Implements dyno::DataFolder< cv::Mat >.
Definition at line 756 of file VirtualKittidataProvider.cc.
{
        std::stringstream ss;
        ss << std::setfill('0') << std::setw(5) << idx;
        const std::string file_path = full_path_  + "/classgt_" + ss.str() + ".png";
        throwExceptionIfPathInvalid(file_path);
        return loadClassSegmentation(file_path);
    }
References dyno::GenericVirtualKittiImageLoader::full_path_, loadClassSegmentation(), and dyno::throwExceptionIfPathInvalid().
loadClassSegmentation()
cv::Mat dyno::VirtualKittiClassSegmentationDataFolder::loadClassSegmentation (const std::string & file_path) const inline private
Definition at line 766 of file VirtualKittidataProvider.cc.
{
        //TODO: for now just hardcode in road!!!
        png::image<png::rgb_pixel> rgb_image(file_path);
        cv::Size size(rgb_image.get_width(), rgb_image.get_height());
        cv::Mat class_segmentation(size, ImageType::ClassSegmentation::OpenCVType);
        for (size_t y = 0; y < rgb_image.get_height(); ++y)
        {
            for (size_t x = 0; x < rgb_image.get_width(); ++x)
            {
                const auto& pixel = rgb_image.get_pixel(x, y);
                const unsigned char red = (unsigned char)pixel.red;
                const unsigned char green = (unsigned char)pixel.green;
                const unsigned char blue = (unsigned char)pixel.blue;
                // class_segmentation_rgb.at<cv::Vec3b>(y, x)[0] = blue;
                // class_segmentation_rgb.at<cv::Vec3b>(y, x)[1] = green;
                // class_segmentation_rgb.at<cv::Vec3b>(y, x)[2] = red;
                //TODO: hardcoded road values from VKITTI2
                if(red == 100 && green == 60 && blue == 100) {
                    class_segmentation.at<int>(y, x) = ImageType::ClassSegmentation::Labels::Road;
                }
                else {
                    class_segmentation.at<int>(y, x) = ImageType::ClassSegmentation::Labels::Undefined;
                }
            }
        }
        return class_segmentation;
    }
References dyno::ImageType::ClassSegmentation::OpenCVType, dyno::ImageType::ClassSegmentation::Road, and dyno::ImageType::ClassSegmentation::Undefined.
Referenced by getItem().
The documentation for this class was generated from the following file:
dynosam/src/dataprovider/VirtualKittidataProvider.cc