DynoSAM: dyno::MotionOnlyRefinementOptimizer Class Reference
dyno::MotionOnlyRefinementOptimizer Class Reference
Jointly refined the motion of an object using the 3D-motion-residual.
#include <MotionSolver.hpp>
Classes
struct Params
Public Types
enum RefinementSolver { ProjectionError , PointError }
Public Member Functions
MotionOnlyRefinementOptimizer (const Params &params)
template<typename CALIBRATION >
Pose3SolverResult optimize (const Frame::Ptr frame_k_1, const Frame::Ptr frame_k, const TrackletIds &tracklets, const ObjectId object_id, const gtsam::Pose3 &initial_motion, const RefinementSolver &solver=RefinementSolver::ProjectionError) const
template<typename CALIBRATION >
Pose3SolverResult optimizeAndUpdate (Frame::Ptr frame_k_1, Frame::Ptr frame_k, const TrackletIds &tracklets, const ObjectId object_id, const gtsam::Pose3 &initial_motion, const RefinementSolver &solver=RefinementSolver::ProjectionError) const
Private Attributes
Params params_
Detailed Description
Jointly refined the motion of an object using the 3D-motion-residual.
Definition at line 219 of file MotionSolver.hpp.
Member Enumeration Documentation
RefinementSolver
enum dyno::MotionOnlyRefinementOptimizer::RefinementSolver
Enumerator
ProjectionError
PointError
Definition at line 229 of file MotionSolver.hpp.
{ ProjectionError, PointError };
Constructor & Destructor Documentation
MotionOnlyRefinementOptimizer()
dyno::MotionOnlyRefinementOptimizer::MotionOnlyRefinementOptimizer (const Params & params) inline
Definition at line 228 of file MotionSolver.hpp.
: params_(params) {}
Member Function Documentation
optimize()
template<typename CALIBRATION > Pose3SolverResult dyno::MotionOnlyRefinementOptimizer::optimize (const Frame::Ptr frame_k_1, const Frame::Ptr frame_k, const TrackletIds & tracklets, const ObjectId object_id, const gtsam::Pose3 & initial_motion, const RefinementSolver & solver = RefinementSolver::ProjectionError) const
Definition at line 293 of file MotionSolver-inl.hpp.
{
  gtsam::NonlinearFactorGraph graph;
  gtsam::Values values;
  // noise models are chosen arbitrarily :)
  gtsam::SharedNoiseModel landmark_motion_noise =
      gtsam::noiseModel::Isotropic::Sigma(3u, params_.landmark_motion_sigma);
  // TODO: this will break if we use 3d point error
  gtsam::SharedNoiseModel projection_noise =
      gtsam::noiseModel::Isotropic::Sigma(2u, params_.projection_sigma);
  // make robust (I mean, why not?)
  landmark_motion_noise = gtsam::noiseModel::Robust::Create(
      gtsam::noiseModel::mEstimator::Huber::Create(params_.k_huber),
      landmark_motion_noise);
  projection_noise = gtsam::noiseModel::Robust::Create(
      gtsam::noiseModel::mEstimator::Huber::Create(params_.k_huber),
      projection_noise);
  const gtsam::Key pose_k_1_key = CameraPoseSymbol(frame_k_1->getFrameId());
  const gtsam::Key pose_k_key = CameraPoseSymbol(frame_k->getFrameId());
  const gtsam::Key object_motion_key =
      ObjectMotionSymbol(object_id, frame_k->getFrameId());
  values.insert(pose_k_1_key, frame_k_1->getPose());
  values.insert(pose_k_key, frame_k->getPose());
  values.insert(object_motion_key, initial_motion);
  auto gtsam_calibration = boost::make_shared<CALIBRATION>(
      frame_k_1->getFrameCamera().calibration());
  auto pose_prior = gtsam::noiseModel::Isotropic::Sigma(6u, 0.00001);
  graph.addPrior(pose_k_1_key, frame_k_1->getPose(), pose_prior);
  graph.addPrior(pose_k_key, frame_k->getPose(), pose_prior);
  utils::ChronoTimingStats timer("motion_solver.object_nlo_refinement");
  for (TrackletId tracklet_id : tracklets) {
    Feature::Ptr feature_k_1 = frame_k_1->at(tracklet_id);
    Feature::Ptr feature_k = frame_k->at(tracklet_id);
    CHECK_NOTNULL(feature_k_1);
    CHECK_NOTNULL(feature_k);
    if (!feature_k_1->usable() || !feature_k->usable()) {
      continue;
    }
    CHECK(feature_k_1->hasDepth());
    CHECK(feature_k->hasDepth());
    const Keypoint kp_k_1 = feature_k_1->keypoint();
    const Keypoint kp_k = feature_k->keypoint();
    const gtsam::Point3 lmk_k_1_world =
        frame_k_1->backProjectToWorld(tracklet_id);
    const gtsam::Point3 lmk_k_world = frame_k->backProjectToWorld(tracklet_id);
    const gtsam::Point3 lmk_k_1_local =
        frame_k_1->backProjectToCamera(tracklet_id);
    const gtsam::Point3 lmk_k_local = frame_k->backProjectToCamera(tracklet_id);
    const gtsam::Key lmk_k_1_key =
        DynamicLandmarkSymbol(frame_k_1->getFrameId(), tracklet_id);
    const gtsam::Key lmk_k_key =
        DynamicLandmarkSymbol(frame_k->getFrameId(), tracklet_id);
    // add initial for points
    values.insert(lmk_k_1_key, lmk_k_1_world);
    values.insert(lmk_k_key, lmk_k_world);
    if (solver == RefinementSolver::PointError) {
      LOG(FATAL) << "RefinementSolver::PointError not implemented";
      // graph.emplace_shared<PoseToPointFactor>(
      //     pose_k_1_key, //pose key at previous frames
      //     lmk_k_1_key,
      //     lmk_k_1_local,
      //     projection_noise
      // );
      // graph.emplace_shared<PoseToPointFactor>(
      //         pose_k_key, //pose key at current frames
      //         lmk_k_key,
      //         lmk_k_local,
      //         projection_noise
      // );
    } else if (solver == RefinementSolver::ProjectionError) {
      graph.emplace_shared<GenericProjectionFactor>(
          kp_k_1, projection_noise, pose_k_1_key, lmk_k_1_key,
          gtsam_calibration, false, false);
      graph.emplace_shared<GenericProjectionFactor>(
          kp_k, projection_noise, pose_k_key, lmk_k_key, gtsam_calibration,
          false, false);
    }
    graph.emplace_shared<LandmarkMotionTernaryFactor>(
        lmk_k_1_key, lmk_k_key, object_motion_key, landmark_motion_noise);
  }
  double error_before = graph.error(values);
  std::vector<double> post_errors;
  gtsam::NonlinearFactorGraph mutable_graph = graph;
  gtsam::Values optimised_values = values;
  utils::StatsCollector("motion_solver.object_nlo_refinement_num_vars_all")
      .AddSample(optimised_values.size());
  gtsam::LevenbergMarquardtParams opt_params;
  opt_params.setMaxIterations(5);
  if (VLOG_IS_ON(200))
    opt_params.verbosity = gtsam::NonlinearOptimizerParams::Verbosity::ERROR;
  optimised_values = gtsam::LevenbergMarquardtOptimizer(
                         mutable_graph, optimised_values, opt_params)
                         .optimize();
  double error_after = mutable_graph.error(optimised_values);
  // post_errors.push_back(error_after);
  gtsam::FactorIndices outlier_factors =
      factor_graph_tools::determineFactorOutliers<LandmarkMotionTernaryFactor>(
          mutable_graph, optimised_values);
  std::set<TrackletId> outlier_tracks;
  // if we have outliers, enter iteration loop
  if (outlier_factors.size() > 0u && params_.outlier_reject) {
    for (size_t itr = 0; itr < 4; itr++) {
      // currently removing factors from graph makes them nullptr
      gtsam::NonlinearFactorGraph mutable_graph_with_null = mutable_graph;
      for (auto outlier_idx : outlier_factors) {
        auto factor = mutable_graph_with_null.at(outlier_idx);
        DynamicPointSymbol point_symbol = factor->keys()[0];
        outlier_tracks.insert(point_symbol.trackletId());
        mutable_graph_with_null.remove(outlier_idx);
      }
      // now iterate over graph and add factors that are not null to ensure all
      // factors are ok
      mutable_graph.resize(0);
      for (size_t i = 0; i < mutable_graph_with_null.size(); i++) {
        auto factor = mutable_graph_with_null.at(i);
        if (factor) {
          mutable_graph.add(factor);
        }
      }
      values.insert(object_motion_key, initial_motion);
      // do we use values or optimised values here?
      optimised_values = gtsam::LevenbergMarquardtOptimizer(
                             mutable_graph, optimised_values, opt_params)
                             .optimize();
      error_after = mutable_graph.error(optimised_values);
      post_errors.push_back(error_after);
      outlier_factors = factor_graph_tools::determineFactorOutliers<
          LandmarkMotionTernaryFactor>(mutable_graph, optimised_values);
      if (outlier_factors.size() == 0) {
        break;
      }
    }
  }
  const size_t initial_size = graph.size();
  const size_t inlier_size = mutable_graph.size();
  error_after = mutable_graph.error(optimised_values);
  Pose3SolverResult result;
  result.best_result = optimised_values.at<gtsam::Pose3>(object_motion_key);
  result.outliers = TrackletIds(outlier_tracks.begin(), outlier_tracks.end());
  result.error_before = error_before;
  result.error_after = error_after;
  // naming is confusing, but we already have the outliers but we can use the
  // same function to find the inliers
  determineOutlierIds(result.outliers, tracklets, result.inliers);
  for (auto outlier_tracklet : outlier_tracks) {
    Feature::Ptr feature_k_1 = frame_k_1->at(outlier_tracklet);
    Feature::Ptr feature_k = frame_k->at(outlier_tracklet);
    CHECK(feature_k_1->usable());
    CHECK(feature_k->usable());
    feature_k->markOutlier();
    feature_k_1->markOutlier();
  }
  // number of variables after outlier removal
  utils::StatsCollector("motion_solver.object_nlo_refinement_num_vars_inliers")
      .AddSample(result.inliers.size());
  // LOG(INFO) << "Object Motion refinement - error before: "
  //     << error_before << " error after: " << error_after
  //     << " with initial size " << initial_size << " inlier size " <<
  //     inlier_size;
  return result;
}
References dyno::utils::StatsCollectorImpl::AddSample(), dyno::SolverResult< T >::best_result, dyno::CameraPoseSymbol(), dyno::factor_graph_tools::determineFactorOutliers(), dyno::determineOutlierIds(), dyno::DynamicLandmarkSymbol(), dyno::SolverResult< T >::error_after, dyno::SolverResult< T >::error_before, dyno::SolverResult< T >::inliers, dyno::MotionOnlyRefinementOptimizer::Params::k_huber, dyno::MotionOnlyRefinementOptimizer::Params::landmark_motion_sigma, dyno::ObjectMotionSymbol(), dyno::MotionOnlyRefinementOptimizer::Params::outlier_reject, dyno::SolverResult< T >::outliers, params_, PointError, dyno::MotionOnlyRefinementOptimizer::Params::projection_sigma, ProjectionError, and dyno::DynamicPointSymbol::trackletId().
optimizeAndUpdate()
template<typename CALIBRATION > Pose3SolverResult dyno::MotionOnlyRefinementOptimizer::optimizeAndUpdate (Frame::Ptr frame_k_1, Frame::Ptr frame_k, const TrackletIds & tracklets, const ObjectId object_id, const gtsam::Pose3 & initial_motion, const RefinementSolver & solver = RefinementSolver::ProjectionError) const
currently no outlier rejection
Definition at line 498 of file MotionSolver-inl.hpp.
{
  auto result = this->optimize<CALIBRATION>(frame_k_1, frame_k, tracklets,
                                            object_id, initial_motion, solver);
  // TODO: update frame with outliers
  return result;
}
Referenced by dyno::ObjectMotionSovlerF2F::geometricOutlierRejection3d2d().
Member Data Documentation
params_
Params dyno::MotionOnlyRefinementOptimizer::params_ private
Definition at line 245 of file MotionSolver.hpp.
Referenced by optimize().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/frontend/vision/MotionSolver.hpp
dynosam/include/dynosam/frontend/vision/MotionSolver-inl.hpp