DynoSAM: dyno::ParameterConstructor Class Reference
dyno::ParameterConstructor Class Reference
Wrapper class to define paramter details. Using these details a ParameterDetails object can be created which declares the paramter with its associated node automatically and can be used to directly access the latest value.
#include <RosUtils.hpp>
Public Member Functions
ParameterConstructor (rclcpp::Node::SharedPtr node, const std::string &name)
Constructor with a node and param name. Default value is set to type rclcpp::PARAMETER_NOT_SET and the resulting ParameterDetails will throw an 'InvalidDefaultParameter' exception upon construction unless the user provides a default argument in the parameter overwrites.
ParameterConstructor (rclcpp::Node *node, const std::string &name)
template<typename ValueTypeT >
ParameterConstructor (rclcpp::Node::SharedPtr node, const std::string &name, ValueTypeT value)
Construct with a node, param name and default type. The he value type is determined by traits<ValueTypeT>::ros_parameter_type; and will be used as the default value if a parameter overwrite is not provided.
template<typename ValueTypeT >
ParameterConstructor (rclcpp::Node *node, const std::string &name, ValueTypeT value)
ParameterDetails finish () const
Constructs a ParameterDetails object from the details in this.
ParameterConstructor & description (const std::string &description)
Updates the paramters description and a returns a reference to this.
ParameterConstructor & read_only (bool read_only)
Updates the read only flag and a returns a reference to this.
ParameterConstructor & parameter_description (const rcl_interfaces::msg::ParameterDescriptor &parameter_description)
Updates the full internal paramter description and returns a reference to this.
const std::string & name () const
Name of the paramter.
operator rclcpp::ParameterValue () const
Casting operator and the internal storage for the parameter value.
operator rcl_interfaces::msg::ParameterDescriptor () const
Private Attributes
rclcpp::Node * node_
rclcpp::Parameter parameter_
rcl_interfaces::msg::ParameterDescriptor parameter_descriptor_
Detailed Description
Wrapper class to define paramter details. Using these details a ParameterDetails object can be created which declares the paramter with its associated node automatically and can be used to directly access the latest value.
Definition at line 295 of file RosUtils.hpp.
Constructor & Destructor Documentation
ParameterConstructor() [1/4]
dyno::ParameterConstructor::ParameterConstructor (rclcpp::Node::SharedPtr node, const std::string & name)
Constructor with a node and param name. Default value is set to type rclcpp::PARAMETER_NOT_SET and the resulting ParameterDetails will throw an 'InvalidDefaultParameter' exception upon construction unless the user provides a default argument in the parameter overwrites.
Parameters
node
name
Definition at line 252 of file RosUtils.cc.
    : ParameterConstructor(node.get(), name) {}
ParameterConstructor() [2/4]
dyno::ParameterConstructor::ParameterConstructor (rclcpp::Node * node, const std::string & name)
Definition at line 256 of file RosUtils.cc.
    : node_(node), parameter_(name) {
  CHECK_NOTNULL(node_);
  parameter_descriptor_.name = name;
  parameter_descriptor_.dynamic_typing = true;
}
References name(), node_, and parameter_descriptor_.
ParameterConstructor() [3/4]
template<typename ValueTypeT > dyno::ParameterConstructor::ParameterConstructor (rclcpp::Node::SharedPtr node, const std::string & name, ValueTypeT value)
Construct with a node, param name and default type. The he value type is determined by traits<ValueTypeT>::ros_parameter_type; and will be used as the default value if a parameter overwrite is not provided.
Template Parameters
ValueTypeT
Parameters
node
name
value
Definition at line 90 of file RosUtils-inl.hpp.
    : ParameterConstructor(node.get(), name, value) {}
ParameterConstructor() [4/4]
template<typename ValueTypeT > dyno::ParameterConstructor::ParameterConstructor (rclcpp::Node * node, const std::string & name, ValueTypeT value)
Definition at line 96 of file RosUtils-inl.hpp.
    : node_(node), parameter_(name, value) {
  CHECK_NOTNULL(node_);
  parameter_descriptor_.name = name;
  parameter_descriptor_.type = traits<ValueTypeT>::ros_parameter_type;
}
References name(), node_, and parameter_descriptor_.
Member Function Documentation
description()
ParameterConstructor & dyno::ParameterConstructor::description (const std::string & description)
Updates the paramters description and a returns a reference to this.
Internally, updates parameter_descriptor_.
Parameters
description const std::string
Returns
ParameterConstructor&
Definition at line 268 of file RosUtils.cc.
{
  parameter_descriptor_.description = description;
  return *this;
}
References description(), and parameter_descriptor_.
Referenced by dyno::DynoNode::createDataProvider(), description(), dyno::DynoNode::DynoNode(), dyno::DynoPipelineManagerRos::initalisePipeline(), and dyno::DynoNode::searchForPathWithParams().
finish()
ParameterDetails dyno::ParameterConstructor::finish () const
Constructs a ParameterDetails object from the details in this.
As per the ParameterDetails comments, upon constructio the parameter is declared in the associated node (from this) and is kept in the ParameterDetails as a shared pointer.
Returns
ParameterDetails
Definition at line 264 of file RosUtils.cc.
{
  return ParameterDetails(node_, parameter_, parameter_descriptor_);
}
References node_, parameter_, and parameter_descriptor_.
Referenced by dyno::DynoNode::createDataProvider(), dyno::DynoNode::DynoNode(), dyno::DynoPipelineManagerRos::initalisePipeline(), and dyno::DynoNode::searchForPathWithParams().
name()
const std::string & dyno::ParameterConstructor::name () const inline
Name of the paramter.
Returns
const std::string&
Definition at line 373 of file RosUtils.hpp.
{ return parameter_.get_name(); }
References parameter_.
Referenced by ParameterConstructor().
operator rcl_interfaces::msg::ParameterDescriptor()
dyno::ParameterConstructor::operator rcl_interfaces::msg::ParameterDescriptor () const inline
Definition at line 383 of file RosUtils.hpp.
{
    return parameter_descriptor_;
  }
References parameter_descriptor_.
operator rclcpp::ParameterValue()
dyno::ParameterConstructor::operator rclcpp::ParameterValue () const inline
Casting operator and the internal storage for the parameter value.
Returns
rclcpp::ParameterValue
Definition at line 379 of file RosUtils.hpp.
{
    return parameter_.get_parameter_value();
  }
References parameter_.
parameter_description()
ParameterConstructor & dyno::ParameterConstructor::parameter_description (const rcl_interfaces::msg::ParameterDescriptor & parameter_description)
Updates the full internal paramter description and returns a reference to this.
Parameters
parameter_description const rcl_interfaces::msg::ParameterDescriptor &
Returns
ParameterConstructor&
Definition at line 279 of file RosUtils.cc.
{
  parameter_descriptor_ = parameter_description;
  return *this;
}
References parameter_description(), and parameter_descriptor_.
Referenced by parameter_description().
read_only()
ParameterConstructor & dyno::ParameterConstructor::read_only (bool read_only)
Updates the read only flag and a returns a reference to this.
Internally, updates parameter_descriptor_.
Parameters
read_only bool
Returns
ParameterConstructor&
Definition at line 274 of file RosUtils.cc.
{
  parameter_descriptor_.read_only = read_only;
  return *this;
}
References parameter_descriptor_, and read_only().
Referenced by read_only().
Member Data Documentation
node_
rclcpp::Node* dyno::ParameterConstructor::node_ private
Definition at line 388 of file RosUtils.hpp.
Referenced by finish(), and ParameterConstructor().
parameter_
rclcpp::Parameter dyno::ParameterConstructor::parameter_ private
Definition at line 389 of file RosUtils.hpp.
Referenced by finish(), name(), and operator rclcpp::ParameterValue().
parameter_descriptor_
rcl_interfaces::msg::ParameterDescriptor dyno::ParameterConstructor::parameter_descriptor_ private
Definition at line 390 of file RosUtils.hpp.
Referenced by description(), finish(), operator rcl_interfaces::msg::ParameterDescriptor(), parameter_description(), ParameterConstructor(), and read_only().
The documentation for this class was generated from the following files:
dynosam_ros/include/dynosam_ros/RosUtils.hpp
dynosam_ros/include/dynosam_ros/RosUtils-inl.hpp
dynosam_ros/src/RosUtils.cc