DynoSAM: dyno::BackendDisplayRos Class Reference
dyno::BackendDisplayRos Class Reference
#include <BackendDisplayRos.hpp>
Public Member Functions
BackendDisplayRos (const DisplayParams params, rclcpp::Node::SharedPtr node)
void spinOnce (const BackendOutputPacket::ConstPtr &backend_output) override
Public Member Functions inherited from dyno::DisplayBase< INPUT >
DisplayBase ()
virtual ~DisplayBase ()
virtual void spinOnce (const InputConstPtr &input)=0
Private Attributes
rclcpp::Publisher< sensor_msgs::msg::PointCloud2 >::SharedPtr static_tracked_points_pub_
rclcpp::Publisher< sensor_msgs::msg::PointCloud2 >::SharedPtr dynamic_tracked_points_pub_
rclcpp::Publisher< sensor_msgs::msg::PointCloud2 >::SharedPtr dynamic_initial_points_pub_
rclcpp::Publisher< sensor_msgs::msg::PointCloud2 >::SharedPtr new_scaled_dynamic_points_pub_
rclcpp::Publisher< nav_msgs::msg::Odometry >::SharedPtr odometry_pub_
rclcpp::Publisher< nav_msgs::msg::Path >::SharedPtr odometry_path_pub_
rclcpp::Publisher< visualization_msgs::msg::MarkerArray >::SharedPtr object_pose_path_pub_
rclcpp::Publisher< visualization_msgs::msg::MarkerArray >::SharedPtr object_pose_pub_
Path of propogated object poses using the motion estimate.
rclcpp::Publisher< visualization_msgs::msg::MarkerArray >::SharedPtr object_aabb_pub_
Propogated object poses using the motion estimate.
Private Attributes inherited from dyno::DisplayRos
const DisplayParams params_
rclcpp::Node::SharedPtr node_
MarkerArrayPub::SharedPtr camera_frustrum_pub_
Additional Inherited Members
Public Types inherited from dyno::DisplayBase< INPUT >
using Input = INPUT
using This = DisplayBase< INPUT >
using InputConstPtr = typename INPUT::ConstPtr
Private Types inherited from dyno::DisplayRos
using PointCloud2 = sensor_msgs::msg::PointCloud2
using MarkerArray = visualization_msgs::msg::MarkerArray
using PointCloud2Pub = rclcpp::Publisher< sensor_msgs::msg::PointCloud2 >
Typedef for MarkerArray msg.
using OdometryPub = rclcpp::Publisher< nav_msgs::msg::Odometry >
using PathPub = rclcpp::Publisher< nav_msgs::msg::Path >
using MarkerArrayPub = rclcpp::Publisher< MarkerArray >
Private Member Functions inherited from dyno::DisplayRos
DisplayRos (const DisplayParams &params, rclcpp::Node::SharedPtr node)
virtual ~DisplayRos ()=default
virtual CloudPerObject publishPointCloud (PointCloud2Pub::SharedPtr pub, const StatusLandmarkVector &landmarks, const gtsam::Pose3 &T_world_camera)
virtual void publishOdometry (OdometryPub::SharedPtr pub, const gtsam::Pose3 &T_world_camera, Timestamp timestamp)
virtual void publishOdometryPath (PathPub::SharedPtr pub, const gtsam::Pose3Vector &poses, Timestamp latest_timestamp)
virtual void publishObjectPositions (MarkerArrayPub::SharedPtr pub, const ObjectPoseMap &object_positions, FrameId frame_id, Timestamp latest_timestamp, const std::string &prefix_marker_namespace, bool draw_labels=false, double scale=1.0)
virtual void publishObjectPaths (MarkerArrayPub::SharedPtr pub, const ObjectPoseMap &object_positions, FrameId frame_id, Timestamp latest_timestamp, const std::string &prefix_marker_namespace, const int min_poses=60)
virtual void publishObjectBoundingBox (MarkerArrayPub::SharedPtr aabb_pub, MarkerArrayPub::SharedPtr obb_pub, const CloudPerObject &cloud_per_object, Timestamp timestamp, const std::string &prefix_marker_namespace)
MarkerArray createCameraMarker (const gtsam::Pose3 &T_world_x, Timestamp timestamp, const std::string &ns, const cv::Scalar &colour, double marker_scale=1.0)
void publishCameraMarker (const gtsam::Pose3 &T_world_x, Timestamp timestamp, const std::string &ns, const cv::Scalar &colour, double marker_scale=1.0)
visualization_msgs::msg::Marker getDeletionMarker () const
Static Private Member Functions inherited from dyno::DisplayRos
static void constructBoundingBoxeMarkers (const CloudPerObject &cloud_per_object, MarkerArray &aabb_markers, MarkerArray &obb_markers, Timestamp timestamp, const std::string &prefix_marker_namespace)
Constructs axis-aligned BB (AABB) and oriented BB (OBB) marker arrays from a set of point clouds which are coloured per object.
static void createAxisMarkers (const gtsam::Pose3 &pose, MarkerArray &axis_markers, Timestamp timestamp, const cv::Scalar &colour, const std::string &frame, const std::string &ns, double length=0.8, double radius=0.1)
Detailed Description
Definition at line 41 of file BackendDisplayRos.hpp.
Constructor & Destructor Documentation
BackendDisplayRos()
dyno::BackendDisplayRos::BackendDisplayRos (const DisplayParams params, rclcpp::Node::SharedPtr node)
Definition at line 44 of file BackendDisplayRos.cc.
    : DisplayRos(params, node) {
  // const rclcpp::QoS& sensor_data_qos = rclcpp::SensorDataQoS();
  static_tracked_points_pub_ =
      node->create_publisher<sensor_msgs::msg::PointCloud2>("static_cloud", 1);
  dynamic_tracked_points_pub_ =
      node->create_publisher<sensor_msgs::msg::PointCloud2>("dynamic_cloud", 1);
  // dynamic_initial_points_pub_ =
  // node->create_publisher<sensor_msgs::msg::PointCloud2>("~/backend/dynamic_initial",
  // 1); new_scaled_dynamic_points_pub_ =
  // node->create_publisher<sensor_msgs::msg::PointCloud2>("~/backend/dynamic_newly_scaled",
  // 1);
  odometry_pub_ = node->create_publisher<nav_msgs::msg::Odometry>("odom", 1);
  object_pose_pub_ =
      node->create_publisher<visualization_msgs::msg::MarkerArray>(
          "composed_object_poses", 1);
  object_pose_path_pub_ =
      node->create_publisher<visualization_msgs::msg::MarkerArray>(
          "composed_object_paths", 1);
  object_aabb_pub_ =
      node->create_publisher<visualization_msgs::msg::MarkerArray>(
          "object_aabb", 1);
  odometry_path_pub_ =
      node->create_publisher<nav_msgs::msg::Path>("odom_path", 2);
}
References dynamic_tracked_points_pub_, object_aabb_pub_, object_pose_path_pub_, object_pose_pub_, odometry_path_pub_, odometry_pub_, and static_tracked_points_pub_.
Member Function Documentation
spinOnce()
void dyno::BackendDisplayRos::spinOnce (const BackendOutputPacket::ConstPtr & backend_output) override
Definition at line 74 of file BackendDisplayRos.cc.
{
  publishPointCloud(static_tracked_points_pub_,
                    backend_output->static_landmarks_,
                    backend_output->T_world_camera_);
  CloudPerObject clouds_per_obj = publishPointCloud(
      dynamic_tracked_points_pub_, backend_output->dynamic_landmarks_,
      backend_output->T_world_camera_);
  publishObjectBoundingBox(object_aabb_pub_, nullptr, /* no Obb publisher */
                           clouds_per_obj, utils::fromRosTime(node_->now()),
                           "backend");
  publishObjectPositions(
      object_pose_pub_, backend_output->composed_object_poses,
      backend_output->frame_id_, backend_output->timestamp_, "backend");
  publishObjectPaths(
      object_pose_path_pub_, backend_output->composed_object_poses,
      backend_output->frame_id_, backend_output->timestamp_, "backend", 60);
  {
    nav_msgs::msg::Odometry odom_msg;
    utils::convertWithHeader(backend_output->T_world_camera_, odom_msg,
                             backend_output->timestamp_, "world", "camera");
    odometry_pub_->publish(odom_msg);
  }
  {
    nav_msgs::msg::Path odom_path_msg;
    for (const gtsam::Pose3& T_world_camera :
         backend_output->optimized_poses_) {
      // optimized camera traj
      geometry_msgs::msg::PoseStamped pose_stamped;
      utils::convertWithHeader(T_world_camera, pose_stamped,
                               backend_output->timestamp_, "world");
      static std_msgs::msg::Header header;
      header.stamp = utils::toRosTime(backend_output->timestamp_);
      header.frame_id = "world";
      odom_path_msg.header = header;
      odom_path_msg.poses.push_back(pose_stamped);
    }
    odometry_path_pub_->publish(odom_path_msg);
  }
}
References dyno::utils::convertWithHeader(), dynamic_tracked_points_pub_, dyno::utils::fromRosTime(), dyno::DisplayRos::node_, object_aabb_pub_, object_pose_path_pub_, object_pose_pub_, odometry_path_pub_, odometry_pub_, dyno::DisplayRos::publishObjectBoundingBox(), dyno::DisplayRos::publishObjectPaths(), dyno::DisplayRos::publishObjectPositions(), dyno::DisplayRos::publishPointCloud(), static_tracked_points_pub_, and dyno::utils::toRosTime().
Member Data Documentation
dynamic_initial_points_pub_
rclcpp::Publisher<sensor_msgs::msg::PointCloud2>::SharedPtr dyno::BackendDisplayRos::dynamic_initial_points_pub_ private
Definition at line 50 of file BackendDisplayRos.hpp.
dynamic_tracked_points_pub_
rclcpp::Publisher<sensor_msgs::msg::PointCloud2>::SharedPtr dyno::BackendDisplayRos::dynamic_tracked_points_pub_ private
Definition at line 49 of file BackendDisplayRos.hpp.
Referenced by BackendDisplayRos(), and spinOnce().
new_scaled_dynamic_points_pub_
rclcpp::Publisher<sensor_msgs::msg::PointCloud2>::SharedPtr dyno::BackendDisplayRos::new_scaled_dynamic_points_pub_ private
Definition at line 51 of file BackendDisplayRos.hpp.
object_aabb_pub_
rclcpp::Publisher<visualization_msgs::msg::MarkerArray>::SharedPtr dyno::BackendDisplayRos::object_aabb_pub_ private
Propogated object poses using the motion estimate.
Definition at line 61 of file BackendDisplayRos.hpp.
Referenced by BackendDisplayRos(), and spinOnce().
object_pose_path_pub_
rclcpp::Publisher<visualization_msgs::msg::MarkerArray>::SharedPtr dyno::BackendDisplayRos::object_pose_path_pub_ private
Definition at line 58 of file BackendDisplayRos.hpp.
Referenced by BackendDisplayRos(), and spinOnce().
object_pose_pub_
rclcpp::Publisher<visualization_msgs::msg::MarkerArray>::SharedPtr dyno::BackendDisplayRos::object_pose_pub_ private
Path of propogated object poses using the motion estimate.
Definition at line 59 of file BackendDisplayRos.hpp.
Referenced by BackendDisplayRos(), and spinOnce().
odometry_path_pub_
rclcpp::Publisher<nav_msgs::msg::Path>::SharedPtr dyno::BackendDisplayRos::odometry_path_pub_ private
Definition at line 56 of file BackendDisplayRos.hpp.
Referenced by BackendDisplayRos(), and spinOnce().
odometry_pub_
rclcpp::Publisher<nav_msgs::msg::Odometry>::SharedPtr dyno::BackendDisplayRos::odometry_pub_ private
Definition at line 53 of file BackendDisplayRos.hpp.
Referenced by BackendDisplayRos(), and spinOnce().
static_tracked_points_pub_
rclcpp::Publisher<sensor_msgs::msg::PointCloud2>::SharedPtr dyno::BackendDisplayRos::static_tracked_points_pub_ private
Definition at line 48 of file BackendDisplayRos.hpp.
Referenced by BackendDisplayRos(), and spinOnce().
The documentation for this class was generated from the following files:
dynosam_ros/include/dynosam_ros/BackendDisplayRos.hpp
dynosam_ros/src/BackendDisplayRos.cc