DynoSAM: dyno::VirtualKittiTextGtLoader Class Reference
dyno::VirtualKittiTextGtLoader Class Reference
Classes
struct BBoxMetaData
Storing metadata from the bbox.txt.
Public Member Functions
VirtualKittiTextGtLoader (const std::string &file_path)
Construct a new Virtual Kitti Text Gt Laoder object.
const GroundTruthInputPacket & getGTPacket (size_t frame) const
size_t size () const
bool isMoving (FrameId frame, ObjectId object_id) const
Queries if an object is moving in the current frame.
Private Types
template<typename T >
using FrameObjectIDMap = std::map< FrameId, std::map< ObjectId, T > >
Nested map mapping frame id to a map of object ids to a type T Allows fast access of object per frame.
Private Member Functions
template<typename T >
bool checkExists (FrameId frame_id, ObjectId object_id, const FrameObjectIDMap< T > &map) const
template<typename T >
void addToFrameObjectMap (FrameId frame_id, ObjectId object_id, T t, FrameObjectIDMap< T > &map)
void loadBBoxMetaData (FrameObjectIDMap< BBoxMetaData > &bbox_metadata)
void loadPoseTxt (FrameObjectIDMap< ObjectPoseGT > &object_poses, const FrameObjectIDMap< BBoxMetaData > &bbox_metadata)
void loadCameraPoses (std::vector< gtsam::Pose3 > &camera_poses)
std::vector< GroundTruthInputPacket > constructGTPackets (const FrameObjectIDMap< ObjectPoseGT > &object_poses, const std::vector< gtsam::Pose3 > &camera_poses) const
Private Attributes
const std::string bbox_path
const std::string colors_path
const std::string extrinsic_path
const std::string info_path
const std::string intrinsic_path
const std::string pose_path
FrameObjectIDMap< ObjectPoseGT > object_poses_
FrameObjectIDMap< BBoxMetaData > bbox_data_
all object poses
std::vector< gtsam::Pose3 > camera_poses_
all object poses
std::vector< GroundTruthInputPacket > gt_packets_
camera poses in the world frame
Detailed Description
Definition at line 198 of file VirtualKittidataProvider.cc.
Member Typedef Documentation
FrameObjectIDMap
template<typename T > using dyno::VirtualKittiTextGtLoader::FrameObjectIDMap = std::map<FrameId, std::map<ObjectId, T> > private
Nested map mapping frame id to a map of object ids to a type T Allows fast access of object per frame.
Template Parameters
T
Definition at line 273 of file VirtualKittidataProvider.cc.
Constructor & Destructor Documentation
VirtualKittiTextGtLoader()
dyno::VirtualKittiTextGtLoader::VirtualKittiTextGtLoader (const std::string & file_path) inline
Construct a new Virtual Kitti Text Gt Laoder object.
File path is full file path to the textgt folder containing bbox.txt, colors.txt, ... pose.txt
Parameters
file_path
Definition at line 210 of file VirtualKittidataProvider.cc.
    :  bbox_path(file_path + "/bbox.txt"),
       colors_path(file_path + "/colors.txt"),
       extrinsic_path(file_path + "/extrinsic.txt"),
       info_path(file_path + "/info.txt"),
       intrinsic_path(file_path + "/intrinsic.txt"),
       pose_path(file_path + "/pose.txt")  {
        throwExceptionIfPathInvalid(bbox_path);
        throwExceptionIfPathInvalid(colors_path);
        throwExceptionIfPathInvalid(extrinsic_path);
        throwExceptionIfPathInvalid(info_path);
        throwExceptionIfPathInvalid(intrinsic_path);
        throwExceptionIfPathInvalid(pose_path);
        loadBBoxMetaData(bbox_data_);
        loadPoseTxt(object_poses_, bbox_data_);
        loadCameraPoses(camera_poses_);
        gt_packets_ = constructGTPackets(object_poses_, camera_poses_);
    }
References bbox_data_, bbox_path, camera_poses_, colors_path, constructGTPackets(), extrinsic_path, gt_packets_, info_path, intrinsic_path, loadBBoxMetaData(), loadCameraPoses(), loadPoseTxt(), object_poses_, pose_path, and dyno::throwExceptionIfPathInvalid().
Member Function Documentation
addToFrameObjectMap()
template<typename T > void dyno::VirtualKittiTextGtLoader::addToFrameObjectMap (FrameId frame_id, ObjectId object_id, T t, FrameObjectIDMap< T > & map) inline private
Definition at line 290 of file VirtualKittidataProvider.cc.
{
        if(map.find(frame_id) == map.end()) {
            map[frame_id] = std::map<ObjectId, T>();
        }
        map[frame_id][object_id] = t;
    }
Referenced by loadBBoxMetaData(), and loadPoseTxt().
checkExists()
template<typename T > bool dyno::VirtualKittiTextGtLoader::checkExists (FrameId frame_id, ObjectId object_id, const FrameObjectIDMap< T > & map) const inline private
Definition at line 277 of file VirtualKittidataProvider.cc.
{
        auto it = map.find(frame_id);
        if(it == map.end()) return false;
        const auto& inner_map = it->second;
        auto it_inner = inner_map.find(object_id);
        if(it_inner == inner_map.end()) return false;
        return true;
    }
Referenced by isMoving(), and loadPoseTxt().
constructGTPackets()
std::vector< GroundTruthInputPacket > dyno::VirtualKittiTextGtLoader::constructGTPackets (const FrameObjectIDMap< ObjectPoseGT > & object_poses, const std::vector< gtsam::Pose3 > & camera_poses) const inline private
Definition at line 616 of file VirtualKittidataProvider.cc.
    {
        std::vector<GroundTruthInputPacket> gt_packets;
        for(size_t frame_id = 0; frame_id < camera_poses.size(); frame_id++) {
            GroundTruthInputPacket gt_packet;
            gt_packet.frame_id_ = frame_id;
            gt_packet.X_world_ = camera_poses.at(frame_id);
            const auto& it = object_poses.find(frame_id);
            if(it != object_poses.end()) {
                auto& object_id_pose_map = it->second;
                for(auto& [object_id, object_pose_gt] : object_id_pose_map) {
                    //query for moving
                    // if(isMoving(frame_id, object_id)) {
                        // LOG(INFO) << "Added moving object " << frame_id << " " << object_id;
                        auto object_pose = object_pose_gt;
                        object_pose.L_world_ = gt_packet.X_world_ * object_pose.L_camera_;
                        gt_packet.object_poses_.push_back(object_pose);
                    // }
                }
            }
            //set motions
            if(frame_id > 0) {
                const GroundTruthInputPacket& previous_gt_packet = gt_packets.at(frame_id - 1);
                gt_packet.calculateAndSetMotions(previous_gt_packet);
            }
            gt_packets.push_back(gt_packet);
        }
        return gt_packets;
    }
References dyno::GroundTruthInputPacket::calculateAndSetMotions(), dyno::GroundTruthInputPacket::frame_id_, dyno::GroundTruthInputPacket::object_poses_, and dyno::GroundTruthInputPacket::X_world_.
Referenced by VirtualKittiTextGtLoader().
getGTPacket()
const GroundTruthInputPacket & dyno::VirtualKittiTextGtLoader::getGTPacket (size_t frame) const inline
Definition at line 233 of file VirtualKittidataProvider.cc.
{
        return gt_packets_.at(frame);
    }
References gt_packets_.
isMoving()
bool dyno::VirtualKittiTextGtLoader::isMoving (FrameId frame, ObjectId object_id) const inline
Queries if an object is moving in the current frame.
Unlike in Virtual kitti which indicates if movement is between frame t and t+1, we need to know if the object moved between t-1 and t (as we estimate for t-1 to t)
The frame argument is considered to be frame t and we requery the isMoving variable of the BBoxMetaData at t-1.
If object does not exist at frame return false?
Parameters
frame
object_id
Returns
true
false
Definition at line 256 of file VirtualKittidataProvider.cc.
{
        //check current frame and prev frame
        if(checkExists(frame, object_id, bbox_data_) && checkExists(frame-1, object_id, bbox_data_)) {
            return bbox_data_.at(frame - 1).at(object_id).is_moving;
        }
        return false;
    }
References bbox_data_, and checkExists().
loadBBoxMetaData()
void dyno::VirtualKittiTextGtLoader::loadBBoxMetaData (FrameObjectIDMap< BBoxMetaData > & bbox_metadata) inline private
Definition at line 308 of file VirtualKittidataProvider.cc.
{
        std::ifstream fstream;
        fstream.open(bbox_path, std::ios::in);
        if(!fstream) {
            throw std::runtime_error("Could not open file " + bbox_path + " when trying to load BBox metadata for Virtual Kitti dataset!");
        }
        LOG(INFO) << "Loading BBox metadta for virtual kitti datasetat path: " << bbox_path;
        static const std::map<std::string, int> header_map = {
            {"frame", 0},
            {"cameraID", 1},
            {"trackID", 2},
            {"left", 3},
            {"right", 4},
            {"top", 5},
            {"bottom", 6},
            {"number_pixels", 7},
            {"truncation_ratio", 8},
            {"occupancy_ratio", 9},
            {"isMoving", 10},
        };
        auto convert_string_bool = [](const std::string& string_bool) -> bool {
            if(string_bool == "True") return true;
            else if(string_bool == "False") return false;
            else throw std::runtime_error("Unknown string bool " + string_bool + " when attempting to covnert to bool type");
        };
        bool is_first = true; //to access header
        while (!fstream.eof()) {
            std::vector<std::string> split_line;
            if(!getLine(fstream, split_line)) continue;
            CHECK_EQ(split_line.size(), header_map.size()) << "Header map and the line present in the bbox.txt file do not have the same length - " << container_to_string(split_line);
            if(is_first) {
                //check header and validate
                for(const auto& [header_value, index] : header_map) {
                    const std::string value = split_line.at(index);
                    if(value != header_value) {
                        throw std::runtime_error("Header value mismatch - " + value + " != " + header_value);
                    }
                }
                is_first = false;
            }
            else {
                const int frame =  std::stoi(split_line.at(header_map.at("frame")));
                const int camera_id =  std::stoi(split_line.at(header_map.at("cameraID")));
                const int track_id = getTrackID(split_line, header_map.at("trackID"));
                const int left =  std::stoi(split_line.at(header_map.at("left")));
                const int right =  std::stoi(split_line.at(header_map.at("right")));
                const int top =  std::stoi(split_line.at(header_map.at("top")));
                const int bottom =  std::stoi(split_line.at(header_map.at("bottom")));
                // const int number_pixels =  std::stoi(split_line.at(header_map.at("number_pixels")));
                // const double truncation_ratio =  std::stod(split_line.at(header_map.at("truncation_ratio")));
                // const double occupancy_ratio =  std::stod(split_line.at(header_map.at("occupancy_ratio")));
                const bool is_moving =  convert_string_bool(split_line.at(header_map.at("isMoving")));
                if(camera_id != 0) {
                    continue; //hardcoded for only one camera atm
                }
                BBoxMetaData bbox_data;
                bbox_data.frame = frame;
                bbox_data.track_id = track_id;
                bbox_data.is_moving = is_moving;
                //convert to cv::Rect where image starts top right
                cv::Point tl(left, top);
                cv::Point br(right, bottom);
                bbox_data.bbox = cv::Rect(tl, br);
                addToFrameObjectMap(frame, track_id, bbox_data, bbox_metadata);
            }
        }
    }
References addToFrameObjectMap(), dyno::VirtualKittiTextGtLoader::BBoxMetaData::bbox, bbox_path, dyno::container_to_string(), dyno::VirtualKittiTextGtLoader::BBoxMetaData::frame, dyno::getLine(), dyno::getTrackID(), dyno::VirtualKittiTextGtLoader::BBoxMetaData::is_moving, and dyno::VirtualKittiTextGtLoader::BBoxMetaData::track_id.
Referenced by VirtualKittiTextGtLoader().
loadCameraPoses()
void dyno::VirtualKittiTextGtLoader::loadCameraPoses (std::vector< gtsam::Pose3 > & camera_poses) inline private
Definition at line 523 of file VirtualKittidataProvider.cc.
{
        std::ifstream fstream;
        fstream.open(extrinsic_path, std::ios::in);
        if(!fstream) {
            throw std::runtime_error("Could not open file " + extrinsic_path + " when trying to load camera exterinsics for Virtual Kitti dataset!");
        }
        LOG(INFO) << "Camera pose data for virtual kitti datasetat path: " << extrinsic_path;
        bool is_first = true;
        gtsam::Pose3 initial_pose = gtsam::Pose3::Identity();
        bool set_initial_pose = false;
        while (!fstream.eof()) {
            std::vector<std::string> split_line;
            if(!getLine(fstream, split_line)) continue;
            //frame camera_id, 3x4 camera pose (r11, r12, r13, t1....)
            //header: frame cameraID r1,1 r1,2 r1,3 t1 r2,1 r2,2 r2,3 t2 r3,1 r3,2 r3,3 t3 0 0 0 1
            constexpr static size_t kExtrinsicFileLength = 18u;
            CHECK_EQ(split_line.size(), kExtrinsicFileLength);
            if(is_first){
                is_first = false;
            }
            else {
                const int frame =  std::stoi(split_line.at(0));
                const int camera_id =  std::stoi(split_line.at(1));
                if(camera_id != 0) {
                    continue; //hardcoded for only one camera atm
                }
                //sanity check to ensure things are added in order and at the right index (frame is zero indexed)
                //check only after we check the camera id
                CHECK_EQ(frame, camera_poses.size());
                const double r11 =  std::stod(split_line.at(2));
                const double r12 =  std::stod(split_line.at(3));
                const double r13 =  std::stod(split_line.at(4));
                const double t1 =   std::stod(split_line.at(5));
                const double r21 =  std::stod(split_line.at(6));
                const double r22 =  std::stod(split_line.at(7));
                const double r23 =  std::stod(split_line.at(8));
                const double t2 =   std::stod(split_line.at(9));
                const double r31 =  std::stod(split_line.at(10));
                const double r32 =  std::stod(split_line.at(11));
                const double r33 =  std::stod(split_line.at(12));
                const double t3 =   std::stod(split_line.at(13));
                gtsam::Matrix33 rot;
                rot(0, 0) = r11;
                rot(0, 1) = r12;
                rot(0, 2) = r13;
                rot(1, 0) = r21;
                rot(1, 1) = r22;
                rot(1, 2) = r23;
                rot(2, 0) = r31;
                rot(2, 1) = r32;
                rot(2, 2) = r33;
                //last 4 values should be [0 0 0 1] for homogenous matrix form so we just check
                CHECK_EQ(std::stod(split_line.at(14)), 0);
                CHECK_EQ(std::stod(split_line.at(15)), 0);
                CHECK_EQ(std::stod(split_line.at(16)), 0);
                CHECK_EQ(std::stod(split_line.at(17)), 1);
                gtsam::Pose3 pose(gtsam::Rot3(rot), gtsam::Point3(t1, t2, t3));
                const static gtsam::Pose3 camera_to_world(gtsam::Rot3::RzRyRx(M_PI_2, 0, M_PI_2), gtsam::traits<gtsam::Point3>::Identity());
                //pose is in world coordinate convention so we put into camera convention (the camera_to_world.inverse())
                //the pose provided is actually world -> camera but we want camera -> world eg T_world_camera, so we apply the inverse transform
                pose = camera_to_world.inverse() * pose.inverse();
                if(!set_initial_pose) {
                    initial_pose = pose;
                    set_initial_pose = true;
                }
                // offset initial pose so we start at "0, 0, 0"
                pose = initial_pose.inverse() * pose;
                camera_poses.push_back(pose);
            }
        }
    }
References extrinsic_path, and dyno::getLine().
Referenced by VirtualKittiTextGtLoader().
loadPoseTxt()
void dyno::VirtualKittiTextGtLoader::loadPoseTxt (FrameObjectIDMap< ObjectPoseGT > & object_poses, const FrameObjectIDMap< BBoxMetaData > & bbox_metadata) inline private
Definition at line 387 of file VirtualKittidataProvider.cc.
{
        std::ifstream fstream;
        fstream.open(pose_path, std::ios::in);
        if(!fstream) {
            throw std::runtime_error("Could not open file " + pose_path + " when trying to load Object pose metadata for Virtual Kitti dataset!");
        }
        LOG(INFO) << "Loading Object pose metadta for virtual kitti datasetat path: " << pose_path;
        static const std::map<std::string, int> header_map = {
            {"frame", 0},
            {"cameraID", 1},
            {"trackID", 2},
            {"alpha", 3},
            {"width", 4},
            {"height", 5},
            {"length", 6},
            {"world_space_X", 7},
            {"world_space_Y", 8},
            {"world_space_Z", 9},
            {"rotation_world_space_y", 10},
            {"rotation_world_space_x", 11},
            {"rotation_world_space_z", 12},
            {"camera_space_X", 13},
            {"camera_space_Y", 14},
            {"camera_space_Z", 15},
            {"rotation_camera_space_y", 16},
            {"rotation_camera_space_x", 17},
            {"rotation_camera_space_z", 18},
        };
        bool is_first = true; //to access header
        while (!fstream.eof()) {
            std::vector<std::string> split_line;
            if(!getLine(fstream, split_line)) continue;
            CHECK_EQ(split_line.size(), header_map.size()) << "Header map and the line present in the pose.txt file do not have the same length";
             if(is_first) {
                //check header and validate
                for(const auto& [header_value, index] : header_map) {
                    CHECK_EQ(split_line.at(index), header_value);
                }
                is_first = false;
            }
            else {
                const int frame =  std::stoi(split_line.at(header_map.at("frame")));
                const int camera_id =  std::stoi(split_line.at(header_map.at("cameraID")));
                const int track_id = getTrackID(split_line, header_map.at("trackID"));
                if(camera_id != 0) {
                    continue; //hardcoded for only one camera atm
                }
                // const double alpha = std::stod(split_line.at(header_map.at("alpha")));
                const double width = std::stod(split_line.at(header_map.at("width")));
                const double height = std::stod(split_line.at(header_map.at("height")));
                const double length = std::stod(split_line.at(header_map.at("length")));
                // const double world_space_X =  std::stod(split_line.at(header_map.at("world_space_X")));
                // const double world_space_Y =  std::stod(split_line.at(header_map.at("world_space_Y")));
                // const double world_space_Z =  std::stod(split_line.at(header_map.at("world_space_Z")));
                // const double rotation_world_space_y =  std::stod(split_line.at(header_map.at("rotation_world_space_y")));
                // const double rotation_world_space_x =  std::stod(split_line.at(header_map.at("rotation_world_space_x")));
                // const double rotation_world_space_z =  std::stod(split_line.at(header_map.at("rotation_world_space_z")));
                const double camera_space_X =  std::stod(split_line.at(header_map.at("camera_space_X")));
                const double camera_space_Y =  std::stod(split_line.at(header_map.at("camera_space_Y")));
                const double camera_space_Z =  std::stod(split_line.at(header_map.at("camera_space_Z")));
                const double rotation_camera_space_y =  std::stod(split_line.at(header_map.at("rotation_camera_space_y")));
                const double rotation_camera_space_x =  std::stod(split_line.at(header_map.at("rotation_camera_space_x")));
                const double rotation_camera_space_z =  std::stod(split_line.at(header_map.at("rotation_camera_space_z")));
                ObjectPoseGT object_pose_gt;
                object_pose_gt.frame_id_ = frame;
                object_pose_gt.object_id_ = track_id;
                object_pose_gt.object_dimensions_ = gtsam::Vector3(width, height, length);
                {
                    // assign r vector
                    // double y = rotation_camera_space_y + (3.1415926 / 2);  // +(3.1415926/2)
                    double y = rotation_camera_space_y;  // +(3.1415926/2)
                    double x = rotation_camera_space_x;
                    double z = rotation_camera_space_z;
                    // the angles are in radians.
                    double cy = cos(y);
                    double sy = sin(y);
                    double cx = cos(x);
                    double sx = sin(x);
                    double cz = cos(z);
                    double sz = sin(z);
                    double m00, m01, m02, m10, m11, m12, m20, m21, m22;
                    m00 = cy * cz + sy * sx * sz;
                    m01 = -cy * sz + sy * sx * cz;
                    m02 = sy * cx;
                    m10 = cx * sz;
                    m11 = cx * cz;
                    m12 = -sx;
                    m20 = -sy * cz + cy * sx * sz;
                    m21 = sy * sz + cy * sx * cz;
                    m22 = cy * cx;
                    gtsam::Matrix33 rot;
                    rot(0, 0) = m00;
                    rot(0, 1) = m01;
                    rot(0, 2) = m02;
                    rot(1, 0) = m10;
                    rot(1, 1) = m11;
                    rot(1, 2) = m12;
                    rot(2, 0) = m20;
                    rot(2, 1) = m21;
                    rot(2, 2) = m22;
                    gtsam::Vector3 translation(camera_space_X, camera_space_Y, camera_space_Z);
                    object_pose_gt.L_camera_ = gtsam::Pose3(gtsam::Rot3(rot), translation);
                }
                CHECK(checkExists(frame, track_id, bbox_metadata));
                //check asociated bboxdata has the right info for this object
                const BBoxMetaData& bbox_data = bbox_metadata.at(frame).at(track_id);
                CHECK_EQ(bbox_data.frame, frame);
                CHECK_EQ(bbox_data.track_id, track_id);
                object_pose_gt.bounding_box_ = bbox_data.bbox;
                addToFrameObjectMap(frame, track_id, object_pose_gt, object_poses);
            }
        }
    }
References addToFrameObjectMap(), dyno::VirtualKittiTextGtLoader::BBoxMetaData::bbox, dyno::ObjectPoseGT::bounding_box_, checkExists(), dyno::VirtualKittiTextGtLoader::BBoxMetaData::frame, dyno::ObjectPoseGT::frame_id_, dyno::getLine(), dyno::getTrackID(), dyno::ObjectPoseGT::L_camera_, dyno::ObjectPoseGT::object_dimensions_, dyno::ObjectPoseGT::object_id_, pose_path, and dyno::VirtualKittiTextGtLoader::BBoxMetaData::track_id.
Referenced by VirtualKittiTextGtLoader().
size()
size_t dyno::VirtualKittiTextGtLoader::size () const inline
Definition at line 237 of file VirtualKittidataProvider.cc.
{
        return gt_packets_.size();
    }
References gt_packets_.
Member Data Documentation
bbox_data_
FrameObjectIDMap<BBoxMetaData> dyno::VirtualKittiTextGtLoader::bbox_data_ private
all object poses
Definition at line 666 of file VirtualKittidataProvider.cc.
Referenced by isMoving(), and VirtualKittiTextGtLoader().
bbox_path
const std::string dyno::VirtualKittiTextGtLoader::bbox_path private
Definition at line 658 of file VirtualKittidataProvider.cc.
Referenced by loadBBoxMetaData(), and VirtualKittiTextGtLoader().
camera_poses_
std::vector<gtsam::Pose3> dyno::VirtualKittiTextGtLoader::camera_poses_ private
all object poses
Definition at line 668 of file VirtualKittidataProvider.cc.
Referenced by VirtualKittiTextGtLoader().
colors_path
const std::string dyno::VirtualKittiTextGtLoader::colors_path private
Definition at line 659 of file VirtualKittidataProvider.cc.
Referenced by VirtualKittiTextGtLoader().
extrinsic_path
const std::string dyno::VirtualKittiTextGtLoader::extrinsic_path private
Definition at line 660 of file VirtualKittidataProvider.cc.
Referenced by loadCameraPoses(), and VirtualKittiTextGtLoader().
gt_packets_
std::vector<GroundTruthInputPacket> dyno::VirtualKittiTextGtLoader::gt_packets_ private
camera poses in the world frame
Definition at line 669 of file VirtualKittidataProvider.cc.
Referenced by getGTPacket(), size(), and VirtualKittiTextGtLoader().
info_path
const std::string dyno::VirtualKittiTextGtLoader::info_path private
Definition at line 661 of file VirtualKittidataProvider.cc.
Referenced by VirtualKittiTextGtLoader().
intrinsic_path
const std::string dyno::VirtualKittiTextGtLoader::intrinsic_path private
Definition at line 662 of file VirtualKittidataProvider.cc.
Referenced by VirtualKittiTextGtLoader().
object_poses_
FrameObjectIDMap<ObjectPoseGT> dyno::VirtualKittiTextGtLoader::object_poses_ private
Definition at line 665 of file VirtualKittidataProvider.cc.
Referenced by VirtualKittiTextGtLoader().
pose_path
const std::string dyno::VirtualKittiTextGtLoader::pose_path private
Definition at line 663 of file VirtualKittidataProvider.cc.
Referenced by loadPoseTxt(), and VirtualKittiTextGtLoader().
The documentation for this class was generated from the following file:
dynosam/src/dataprovider/VirtualKittidataProvider.cc