DynoSAM: dyno::KittiDataLoader Class Reference
dyno::KittiDataLoader Class Reference
#include <KittiDataProvider.hpp>
Classes
struct Params
Public Member Functions
KittiDataLoader (const fs::path &dataset_path, const Params &params)
Construct a new Kitti Data Loader object.
CameraParams::Optional getCameraParams () const override
Provides functionality to get camera paramters for the main pipeline, as these may be available from the dataset.
ImageContainer::Ptr imageContainerPreprocessor (ImageContainer::Ptr image_container) override
Virtual Image Container Preprocessor function that is registered to the data interface pipeline.
Public Member Functions inherited from dyno::DynoDatasetProvider< cv::Mat, cv::Mat, gtsam::Pose3, GroundTruthInputPacket >
DynoDatasetProvider (const fs::path &dataset_path)
virtual ~DynoDatasetProvider ()=default
void setStartingFrame (int starting_frame)
void setEndingFrame (int ending_frame)
void reset ()
Resets the dataset to the "start", such that the next call to spin will begin the dataset again from the starting frame id. The starting/ending id will return to whatever the last call to setStartingFrame/setEndingFrame set the values to, or default if they have not been called.
virtual int datasetSize () const override
Get the size of the dataset - if this is not valid (i.e. the provider is online) this function should return -1.
virtual bool spin () override
Spins the dataset for one "step" of the dataset.
size_t getActiveFrameId () const
size_t getEndingFrameId () const
Public Member Functions inherited from dyno::DynoDataset< DataTypes... >
DynoDataset (const fs::path &dataset_path)
virtual ~DynoDataset ()
virtual void setLoaders (TimestampBaseLoader::Ptr timestamp_loader, dyno::DataFolder< cv::Mat >::Ptr rgb_loader, dyno::DataFolder< cv::Mat >::Ptr optical_flow_loader, typename DataFolder< DataTypes >::Ptr... data_folders)
bool isProviderValid () const
Returns true when setLoaders(...) has been called and the internal datasets have been constructed correctly After this point spin() and getDatasetSize() can be called as they use the laoded datasets.
virtual size_t getDatasetSize () const
const std::string getDatasetPath () const
bool processSingle (size_t frame_id)
auto getLoader ()
Public Member Functions inherited from dyno::_DynoDatasetConstructor< Timestamp, cv::Mat, cv::Mat, DataTypes... >
virtual ~_DynoDatasetConstructor ()
void setCallback (const DataInputCallback &data_input_callback)
Public Member Functions inherited from dyno::DataProvider
DataProvider ()=default
virtual ~DataProvider ()
Calls the virtual DataProvider::shutdown() function.
void registerImuSingleCallback (const ImuSingleInputCallback &callback)
void registerImuMultiCallback (const ImuMultiInputCallback &callback)
void registerImageContainerCallback (const ImageContainerCallback &callback)
void registerGroundTruthPacketCallback (const GroundTruthPacketCallback &callback)
virtual ImageContainer::Ptr imageContainerPreprocessor (ImageContainer::Ptr image_container)
Virtual Image Container Preprocessor function that is registered to the data interface pipeline.
void registerOnFinishCallback (const std::function< void()> &callback)
virtual int datasetSize () const =0
Get the size of the dataset - if this is not valid (i.e. the provider is online) this function should return -1.
virtual bool spin ()=0
Spins the dataset for one "step" of the dataset.
virtual void shutdown ()
virtual CameraParams::Optional getCameraParams () const
Provides functionality to get camera paramters for the main pipeline, as these may be available from the dataset.
virtual ImuParams::Optional getImuParams () const
Private Member Functions
void setCameraParams (const fs::path &dataset_path)
Private Attributes
Params params_
CameraParams::Optional camera_params_
Additional Inherited Members
Public Types inherited from dyno::DynoDatasetProvider< cv::Mat, cv::Mat, gtsam::Pose3, GroundTruthInputPacket >
using BaseDynoDataset = DynoDataset< DataTypes... >
using This = DynoDatasetProvider< DataTypes... >
Public Types inherited from dyno::DynoDataset< DataTypes... >
using TypedGenericDataset = GenericDataset< DataTypes... >
using DefaultDataset = GenericDataset< Timestamp, cv::Mat, cv::Mat >
using Base = _DynoDatasetConstructor< Timestamp, cv::Mat, cv::Mat, DataTypes... >
using DynoDataTypesTuple = typename Base::DynoDataTypesTuple
using GenericDatasetType = typename TypedGenericDataset::DataType< I >
Index in Default Dataset.
using DefaultDatasetType = typename DefaultDataset::DataType< I >
The type stored at the tuple idnex of the DefaultDataset.
using This = DynoDataset< DataTypes... >
Public Types inherited from dyno::_DynoDatasetConstructor< Timestamp, cv::Mat, cv::Mat, DataTypes... >
using DynoDataTypesTuple = std::tuple< DynoDataTypes... >
using DataInputCallback = std::function< bool(size_t, const DynoDataTypes...)>
Public Types inherited from dyno::DataProvider
using ImageContainerCallback = std::function< void(ImageContainer::Ptr)>
using ImuSingleInputCallback = std::function< void(const ImuMeasurement &)>
using ImuMultiInputCallback = std::function< void(const ImuMeasurements &)>
using GroundTruthPacketCallback = std::function< void(const GroundTruthInputPacket &)>
Public Attributes inherited from dyno::_DynoDatasetConstructor< Timestamp, cv::Mat, cv::Mat, DataTypes... >
DataInputCallback data_input_callback_
Static Public Attributes inherited from dyno::DynoDataset< DataTypes... >
static constexpr size_t TimestampFileIdx
static constexpr size_t RGBFolderIdx
static constexpr size_t OpticalFlowFolderIdx
Index in Default Dataset.
Protected Member Functions inherited from dyno::DynoDatasetProvider< cv::Mat, cv::Mat, gtsam::Pose3, GroundTruthInputPacket >
void setLoaders (TimestampBaseLoader::Ptr timestamp_loader, dyno::DataFolder< cv::Mat >::Ptr rgb_loader, dyno::DataFolder< cv::Mat >::Ptr optical_flow_loader, typename DataFolder< DataTypes >::Ptr... data_folders) override
Protected Member Functions inherited from dyno::DataProvider
void emitOnFinishCallbacks ()
Protected Attributes inherited from dyno::DataProvider
ImageContainerCallback image_container_callback_
ImuSingleInputCallback imu_single_input_callback_
ImuMultiInputCallback imu_multi_input_callback_
GroundTruthPacketCallback ground_truth_packet_callback_
std::atomic_bool shutdown_ = {false}
Detailed Description
Definition at line 352 of file KittiDataProvider.hpp.
Constructor & Destructor Documentation
KittiDataLoader()
dyno::KittiDataLoader::KittiDataLoader (const fs::path & dataset_path, const Params & params) inline
Construct a new Kitti Data Loader object.
Path should be the full path to the set of folders /depth /flow /image_0 /motion /semantic /pixel_semantics (TODO: shoudl change semantic and pixel semantics to instance_mask and semantics) /object_pose.txt /pose_gt.txt /times.txt
Parameters
dataset_path
params
Definition at line 398 of file KittiDataProvider.hpp.
      : DynoDatasetProvider<cv::Mat, cv::Mat, gtsam::Pose3,
                            GroundTruthInputPacket>(dataset_path),
        params_(params) {
    TimestampFile::Ptr timestamp_file = std::make_shared<TimestampFile>();
    RGBDataFolder::Ptr rgb_folder = std::make_shared<RGBDataFolder>();
    CHECK(timestamp_file);
    CHECK(rgb_folder);
    SegMaskFolder::Ptr mask_folder = nullptr;
    if (params.mask_type == MaskType::MOTION) {
      mask_folder = std::make_shared<MotionSegMaskFolder>(rgb_folder);
      LOG(INFO) << "Using MaskType::MOTION for loading mask";
    } else if (params.mask_type == MaskType::SEMANTIC_INSTANCE) {
      mask_folder = std::make_shared<InstantanceSegMaskFolder>(rgb_folder);
      LOG(INFO) << "Using MaskType::SEMANTIC_INSTANCE for loading mask";
    } else {
      LOG(FATAL) << "Unknown MaskType for KittiDataLoader";
    }
    CHECK_NOTNULL(mask_folder);
    // KittiClassSegmentationDataFolder::Ptr pixel_level_semantics_folder =
    // std::make_shared<KittiClassSegmentationDataFolder>();
    KittiCameraPoseFolder::Ptr camera_pose_folder =
        std::make_shared<KittiCameraPoseFolder>();
    KittiObjectPoseFolder::Ptr object_pose_gt_folder =
        std::make_shared<KittiObjectPoseFolder>(timestamp_file,
                                                camera_pose_folder);
    CHECK(camera_pose_folder);
    CHECK(object_pose_gt_folder);
    // will also update the params!!
    setCameraParams(dataset_path);
    this->setLoaders(timestamp_file, rgb_folder,
                     // should really be called kitti optical flow and kitti
                     // depth data folder
                     std::make_shared<OpticalFlowDataFolder>(),
                     std::make_shared<DepthDataFolder>(), mask_folder,
                     // pixel_level_semantics_folder,
                     camera_pose_folder, object_pose_gt_folder);
    auto callback = [&](size_t frame_id, Timestamp timestamp, cv::Mat rgb,
                        cv::Mat optical_flow, cv::Mat depth,
                        cv::Mat instance_mask, gtsam::Pose3 camera_pose_gt,
                        GroundTruthInputPacket gt_object_pose_gt) -> bool {
      CHECK(camera_pose_gt.equals(gt_object_pose_gt.X_world_));
      CHECK(timestamp == gt_object_pose_gt.timestamp_);
      CHECK(ground_truth_packet_callback_);
      if (ground_truth_packet_callback_)
        ground_truth_packet_callback_(gt_object_pose_gt);
      ImageContainer image_container(frame_id, timestamp);
      image_container.rgb(rgb)
          .depth(depth)
          .opticalFlow(optical_flow)
          .objectMotionMask(instance_mask);
      // if (params_.mask_type == MaskType::MOTION) {
      //   image_container = ImageContainer::Create(
      //       timestamp, frame_id, ImageWrapper<ImageType::RGBMono>(rgb),
      //       ImageWrapper<ImageType::Depth>(depth),
      //       ImageWrapper<ImageType::OpticalFlow>(optical_flow),
      //       ImageWrapper<ImageType::MotionMask>(instance_mask));
      // } else {
      //   image_container = ImageContainer::Create(
      //       timestamp, frame_id, ImageWrapper<ImageType::RGBMono>(rgb),
      //       ImageWrapper<ImageType::Depth>(depth),
      //       ImageWrapper<ImageType::OpticalFlow>(optical_flow),
      //       ImageWrapper<ImageType::SemanticMask>(instance_mask));
      // }
      CHECK(image_container_callback_);
      if (image_container_callback_)
        image_container_callback_(
            std::make_shared<ImageContainer>(image_container));
      return true;
    };
    this->setCallback(callback);
  }
References dyno::DataProvider::ground_truth_packet_callback_, dyno::DataProvider::image_container_callback_, dyno::KittiDataLoader::Params::mask_type, dyno::MOTION, dyno::ImageContainer::rgb(), dyno::SEMANTIC_INSTANCE, dyno::_DynoDatasetConstructor< Timestamp, cv::Mat, cv::Mat, DataTypes... >::setCallback(), setCameraParams(), and dyno::DynoDatasetProvider< cv::Mat, cv::Mat, gtsam::Pose3, GroundTruthInputPacket >::setLoaders().
Member Function Documentation
getCameraParams()
CameraParams::Optional dyno::KittiDataLoader::getCameraParams () const inline override virtual
Provides functionality to get camera paramters for the main pipeline, as these may be available from the dataset.
By default returns std::nullopt but the derived data-provider can overwrite this and return the loaded params
Returns
CameraParams::Optional
Reimplemented from dyno::DataProvider.
Definition at line 484 of file KittiDataProvider.hpp.
{
    return camera_params_;
  }
References camera_params_.
Referenced by main().
imageContainerPreprocessor()
ImageContainer::Ptr dyno::KittiDataLoader::imageContainerPreprocessor (ImageContainer::Ptr image_container) inline override virtual
Virtual Image Container Preprocessor function that is registered to the data interface pipeline.
By default does nothing and just returns the argument. This function is called (via callback) when a ImageContainer is sent to the pipeline via DataProvider::image_container_callback_ and enables each data-provider to implement their own data-preprocessing as necessary
Parameters
image_container
Returns
ImageContainer::Ptr
Reimplemented from dyno::DataProvider.
Definition at line 488 of file KittiDataProvider.hpp.
{
    if (!image_container->hasDepth()) {
      throw std::runtime_error(
          "Cannot preprocess ImageContainer in Kitti dataset as no depth!");
    }
    const auto& base_line = params_.base_line;
    const auto& depth_scale_factor = params_.depth_scale_factor;
    const cv::Mat& const_disparity = image_container->depth();
    cv::Mat depth;
    const_disparity.copyTo(depth);
    for (int i = 0; i < const_disparity.rows; i++) {
      for (int j = 0; j < const_disparity.cols; j++) {
        if (const_disparity.at<double>(i, j) < 0) {
          depth.at<double>(i, j) = 0;
        } else {
          depth.at<double>(i, j) =
              base_line /
              (const_disparity.at<double>(i, j) / depth_scale_factor);
        }
      }
    }
    cv::Mat& disparity = image_container->depth();
    depth.copyTo(disparity);
    depth.convertTo(depth, CV_64F);
    return image_container;
  }
References dyno::KittiDataLoader::Params::base_line, dyno::KittiDataLoader::Params::depth_scale_factor, and params_.
setCameraParams()
void dyno::KittiDataLoader::setCameraParams (const fs::path & dataset_path) inline private
Definition at line 526 of file KittiDataProvider.hpp.
{
    std::string end_folder = dataset_path.parent_path().filename();
    LOG(INFO) << end_folder;
    int dataset_id;
    std::istringstream(end_folder) >> dataset_id;
    LOG(INFO) << "Loading KITTI camera params from dataset: " << dataset_id;
    if (dataset_id <= 13) {
      CameraParams::IntrinsicsCoeffs intrinsics(
          {721.5377, 721.5377, 609.5593, 172.8540});
      CameraParams::DistortionCoeffs distortion({0, 0, 0, 0});
      cv::Size image_size(1242, 375);
      camera_params_ =
          CameraParams(intrinsics, distortion, image_size, "radial_tangential");
      // IR projection of this dataset is 387.5744. IR = baseline * fx
      // (fx=721.5377)
      camera_params_->setDepthParams(0.57);
      params_.base_line = 387.5744;
    } else if (dataset_id >= 18 && dataset_id <= 20) {
      CameraParams::IntrinsicsCoeffs intrinsics(
          {718.8560, 718.8560, 607.1928, 185.2157});
      CameraParams::DistortionCoeffs distortion({0, 0, 0, 0});
      if (dataset_id == 18) {
        cv::Size image_size(1238, 374);
        camera_params_ = CameraParams(intrinsics, distortion, image_size,
                                      "radial_tangential");
      } else if (dataset_id == 20) {
        cv::Size image_size(1241, 376);
        camera_params_ = CameraParams(intrinsics, distortion, image_size,
                                      "radial_tangential");
      } else {
        LOG(WARNING) << "Unknown KITTI dataset when loading camera params. "
                        "Returning no camera params!";
      }
      params_.base_line = 388.1822;
      // IR projection of this dataset is 388.1822. IR = baseline * fx
      // (fx=718.8560)
      camera_params_->setDepthParams(0.5399);
    } else {
      LOG(WARNING) << "Unknown KITTI dataset when loading camera params. "
                      "Returning no camera params!";
    }
  }
References dyno::KittiDataLoader::Params::base_line, camera_params_, and params_.
Referenced by KittiDataLoader().
Member Data Documentation
camera_params_
CameraParams::Optional dyno::KittiDataLoader::camera_params_ private
Definition at line 578 of file KittiDataProvider.hpp.
Referenced by getCameraParams(), and setCameraParams().
params_
Params dyno::KittiDataLoader::params_ private
Definition at line 577 of file KittiDataProvider.hpp.
Referenced by imageContainerPreprocessor(), and setCameraParams().
The documentation for this class was generated from the following file:
dynosam/include/dynosam/dataprovider/KittiDataProvider.hpp