DynoSAM: dyno::DebugInfo Class Reference
dyno::DebugInfo Class Reference
#include <BackendDefinitions.hpp>
Classes
struct ObjectInfo
Public Member Functions
ObjectInfo & getObjectInfo (ObjectId object_id)
const ObjectInfo & getObjectInfo (ObjectId object_id) const
const gtsam::FastMap< ObjectId, ObjectInfo > & getObjectInfos () const
Public Attributes
int num_static_factors = 0
int num_new_static_points = 0
bool odometry_factor_added {false}
double update_static_time = 0
double update_dynamic_time = 0
double optimize_time = 0
double error_before = 0
double error_after = 0
size_t num_factors = 0
size_t num_values = 0
int num_elements_in_matrix = 0
int num_zeros_in_matrix = 0
Private Member Functions
auto & getObjectInfoImpl (ObjectId object_id) const
Private Attributes
gtsam::FastMap< ObjectId, ObjectInfo > object_info_ {}
Detailed Description
Definition at line 245 of file BackendDefinitions.hpp.
Member Function Documentation
getObjectInfo() [1/2]
DebugInfo::ObjectInfo & dyno::DebugInfo::getObjectInfo (ObjectId object_id)
Definition at line 328 of file BackendDefinitions.cc.
{
  return getObjectInfoImpl(object_id);
}
References getObjectInfoImpl().
getObjectInfo() [2/2]
const DebugInfo::ObjectInfo & dyno::DebugInfo::getObjectInfo (ObjectId object_id) const
Definition at line 332 of file BackendDefinitions.cc.
{
  return getObjectInfoImpl(object_id);
}
References getObjectInfoImpl().
getObjectInfoImpl()
auto & dyno::DebugInfo::getObjectInfoImpl (ObjectId object_id) const inline private
Definition at line 288 of file BackendDefinitions.hpp.
{
    if (!object_info_.exists(object_id)) {
      object_info_.insert2(object_id, ObjectInfo{});
    }
    return object_info_.at(object_id);
  }
References object_info_.
Referenced by getObjectInfo().
getObjectInfos()
const gtsam::FastMap< ObjectId, ObjectInfo > & dyno::DebugInfo::getObjectInfos () const inline
Definition at line 266 of file BackendDefinitions.hpp.
{
    return object_info_;
  }
References object_info_.
Member Data Documentation
error_after
double dyno::DebugInfo::error_after = 0
Definition at line 277 of file BackendDefinitions.hpp.
error_before
double dyno::DebugInfo::error_before = 0
Definition at line 276 of file BackendDefinitions.hpp.
num_elements_in_matrix
int dyno::DebugInfo::num_elements_in_matrix = 0
Definition at line 282 of file BackendDefinitions.hpp.
num_factors
size_t dyno::DebugInfo::num_factors = 0
Definition at line 279 of file BackendDefinitions.hpp.
num_new_static_points
int dyno::DebugInfo::num_new_static_points = 0
Definition at line 250 of file BackendDefinitions.hpp.
num_static_factors
int dyno::DebugInfo::num_static_factors = 0
Definition at line 249 of file BackendDefinitions.hpp.
num_values
size_t dyno::DebugInfo::num_values = 0
Definition at line 280 of file BackendDefinitions.hpp.
num_zeros_in_matrix
int dyno::DebugInfo::num_zeros_in_matrix = 0
Definition at line 283 of file BackendDefinitions.hpp.
object_info_
gtsam::FastMap<ObjectId, ObjectInfo> dyno::DebugInfo::object_info_ {} mutable private
Definition at line 286 of file BackendDefinitions.hpp.
Referenced by getObjectInfoImpl(), and getObjectInfos().
odometry_factor_added
bool dyno::DebugInfo::odometry_factor_added {false}
Definition at line 270 of file BackendDefinitions.hpp.
optimize_time
double dyno::DebugInfo::optimize_time = 0
Definition at line 274 of file BackendDefinitions.hpp.
update_dynamic_time
double dyno::DebugInfo::update_dynamic_time = 0
Definition at line 273 of file BackendDefinitions.hpp.
update_static_time
double dyno::DebugInfo::update_static_time = 0
Definition at line 272 of file BackendDefinitions.hpp.
The documentation for this class was generated from the following files:
dynosam/include/dynosam/backend/BackendDefinitions.hpp
dynosam/src/backend/BackendDefinitions.cc