DynoSAM: dyno::RGBDInstanceFrontendModule Class Reference
dyno::RGBDInstanceFrontendModule Class Reference
#include <RGBDInstanceFrontendModule.hpp>
Public Types
using SpinReturn = FrontendModule::SpinReturn
Public Types inherited from dyno::FrontendModule
using Base = ModuleBase< FrontendInputPacketBase, VisionImuPacket >
Public Types inherited from dyno::ModuleBase< FrontendInputPacketBase, VisionImuPacket >
enum State
using Input = FrontendInputPacketBase
using Output = VisionImuPacket
using InputConstPtr = typename INPUT::ConstPtr
using OutputConstPtr = typename OUTPUT::ConstPtr
ConstPtr to an INPUT type.
using This = ModuleBase< FrontendInputPacketBase, VisionImuPacket >
ConstPtr to an OUTPUT type.
using SpinReturn = std::pair< State, OutputConstPtr >
using InputCallback = std::function< void(InputConstPtr)>
using OutputCallback = std::function< void(OutputConstPtr)>
Public Member Functions
RGBDInstanceFrontendModule (const DynoParams &params, Camera::Ptr camera, ImageDisplayQueue *display_queue)
~RGBDInstanceFrontendModule ()
Public Member Functions inherited from dyno::FrontendModule
FrontendModule (const DynoParams &params, ImageDisplayQueue *display_queue=nullptr)
virtual ~FrontendModule ()
const FrontendParams & getFrontendParams () const
Public Member Functions inherited from dyno::ModuleBase< FrontendInputPacketBase, VisionImuPacket >
ModuleBase (const std::string &name)
virtual ~ModuleBase ()=default
OutputConstPtr spinOnce (InputConstPtr input)
void registerInputCallback (const InputCallback &input_callback)
Registeres a function callback to be triggered prior to nominal/bootstrapSpin being called.
void registerOutputCallback (const OutputCallback &output_callback)
Registeres a function callback to be triggered after nominal/bootstrapSpin is called.
Private Member Functions
ImageValidationResult validateImageContainer (const ImageContainer::Ptr &image_container) const override
Checks that the incoming ImageContainer meeets the minimum requirement for the derived module.
SpinReturn boostrapSpin (FrontendInputPacketBase::ConstPtr input) override
SpinReturn nominalSpin (FrontendInputPacketBase::ConstPtr input) override
bool solveCameraMotion (Frame::Ptr frame_k, const Frame::Ptr &frame_k_1, std::optional< gtsam::Rot3 > R_curr_ref={})
Solves PnP between frame_k-1 and frame_k using the tracked correspondances to estimate the frame of the current camera.
void fillOutputPacketWithTracks (VisionImuPacket::Ptr vision_imu_packet, const Frame &frame, const gtsam::Pose3 &T_k_1_k, const ObjectMotionMap &object_motions, const ObjectPoseMap &object_poses) const
void sendToFrontendLogger (const Frame::Ptr &frame, const VisionImuPacket::Ptr &vision_imu_packet)
cv::Mat createTrackingImage (const Frame::Ptr &frame_k, const Frame::Ptr &frame_k_1, const ObjectPoseMap &object_poses) const
Private Attributes
Camera::Ptr camera_
EgoMotionSolver motion_solver_
ObjectMotionSolver::UniquePtr object_motion_solver_
FeatureTracker::UniquePtr tracker_
RGBDFrontendLogger::UniquePtr logger_
ImuFrontend imu_frontend_
gtsam::NavState nav_state_
gtsam::NavState previous_nav_state_
FrameId last_imu_nav_state_update_ {0}
gtsam::Pose3 vo_velocity_
Additional Inherited Members
Public Attributes inherited from dyno::SharedModuleInterface
SharedModuleInfo & shared_module_info = SharedModuleInfo::instance()
Protected Member Functions inherited from dyno::FrontendModule
void validateInput (const FrontendInputPacketBase::ConstPtr &input) const override
virtual ImageValidationResult validateImageContainer (const ImageContainer::Ptr &image_container) const =0
Checks that the incoming ImageContainer meeets the minimum requirement for the derived module.
Protected Member Functions inherited from dyno::ModuleBase< FrontendInputPacketBase, VisionImuPacket >
virtual void validateInput (const InputConstPtr &input) const=0
Checks the state of the input before running any virtual spin (boostrap or nominal) functions.
virtual SpinReturn boostrapSpin (InputConstPtr input)=0
virtual SpinReturn nominalSpin (InputConstPtr input)=0
Protected Attributes inherited from dyno::FrontendModule
const DynoParams params_
ImageDisplayQueue * display_queue_
gtsam::Pose3Vector camera_poses_
Detailed Description
Definition at line 45 of file RGBDInstanceFrontendModule.hpp.
Member Typedef Documentation
SpinReturn
using dyno::RGBDInstanceFrontendModule::SpinReturn = FrontendModule::SpinReturn
Definition at line 51 of file RGBDInstanceFrontendModule.hpp.
Constructor & Destructor Documentation
RGBDInstanceFrontendModule()
dyno::RGBDInstanceFrontendModule::RGBDInstanceFrontendModule (const DynoParams & params, Camera::Ptr camera, ImageDisplayQueue * display_queue)
Definition at line 57 of file RGBDInstanceFrontendModule.cc.
    : FrontendModule(params, display_queue),
      camera_(camera),
      motion_solver_(params.frontend_params_.ego_motion_solver_params,
                     camera->getParams()),
      imu_frontend_(params.frontend_params_.imu_params) {
  CHECK_NOTNULL(camera_);
  tracker_ = std::make_unique<FeatureTracker>(getFrontendParams(), camera_,
                                              display_queue);
  if (FLAGS_use_frontend_logger) {
    LOG(INFO) << "Using front-end logger!";
    logger_ = std::make_unique<RGBDFrontendLogger>();
  }
  ObjectMotionSovlerF2F::Params object_motion_solver_params =
      getFrontendParams().object_motion_solver_params;
  // add ground truth hook
  object_motion_solver_params.ground_truth_packets_request = [&]() {
    return this->shared_module_info.getGroundTruthPackets();
  };
  object_motion_solver_params.refine_motion_with_3d = false;
  object_motion_solver_ = std::make_unique<ObjectMotionSovlerF2F>(
      object_motion_solver_params, camera->getParams());
}
References camera_, dyno::FrontendModule::getFrontendParams(), dyno::SharedModuleInfo::getGroundTruthPackets(), dyno::ObjectMotionSovlerF2F::Params::ground_truth_packets_request, logger_, object_motion_solver_, dyno::FrontendParams::object_motion_solver_params, dyno::ObjectMotionSovlerF2F::Params::refine_motion_with_3d, dyno::SharedModuleInterface::shared_module_info, and tracker_.
~RGBDInstanceFrontendModule()
dyno::RGBDInstanceFrontendModule::~RGBDInstanceFrontendModule ()
Definition at line 86 of file RGBDInstanceFrontendModule.cc.
{
  if (FLAGS_save_frontend_json) {
    LOG(INFO) << "Saving frontend output as json";
    const std::string file_path =
        getOutputFilePath(kRgbdFrontendOutputJsonFile);
    // JsonConverter::WriteOutJson(output_packet_record_, file_path,
    //                             JsonConverter::Format::BSON);
  }
}
References dyno::getOutputFilePath(), and dyno::kRgbdFrontendOutputJsonFile.
Member Function Documentation
boostrapSpin()
FrontendModule::SpinReturn dyno::RGBDInstanceFrontendModule::boostrapSpin (FrontendInputPacketBase::ConstPtr input) override private
Definition at line 103 of file RGBDInstanceFrontendModule.cc.
{
  ImageContainer::Ptr image_container = input->image_container_;
  Frame::Ptr frame = tracker_->track(input->getFrameId(), input->getTimestamp(),
                                     *image_container);
  CHECK(frame->updateDepths());
  return {State::Nominal, nullptr};
}
References tracker_.
createTrackingImage()
cv::Mat dyno::RGBDInstanceFrontendModule::createTrackingImage (const Frame::Ptr & frame_k, const Frame::Ptr & frame_k_1, const ObjectPoseMap & object_poses) const private
Definition at line 535 of file RGBDInstanceFrontendModule.cc.
{
  cv::Mat tracking_image = tracker_->computeImageTracks(
      *frame_k_1, *frame_k, getFrontendParams().image_tracks_vis_params);
  const auto& camera_params = camera_->getParams();
  const auto& K = camera_params.getCameraMatrix();
  const auto& D = camera_params.getDistortionCoeffs();
  const gtsam::Pose3& X_k = frame_k->getPose();
  // poses are expected to be in the world frame
  gtsam::FastMap<ObjectId, gtsam::Pose3> poses_k_map =
      object_poses.collectByFrame(frame_k->getFrameId());
  std::vector<gtsam::Pose3> poses_k_vec;
  std::transform(poses_k_map.begin(), poses_k_map.end(),
                 std::back_inserter(poses_k_vec),
                 [&X_k](const std::pair<ObjectId, gtsam::Pose3>& pair) {
                   // put object pose into the camera frame so it can be
                   // projected into the image
                   return X_k.inverse() * pair.second;
                 });
  // TODO: bring back when visualisation is unified with incremental solver!!
  //  utils::drawObjectPoseAxes(tracking_image, K, D, poses_k_vec);
  return tracking_image;
}
References camera_, dyno::GenericObjectCentricMap< VALUE >::collectByFrame(), dyno::FrontendModule::getFrontendParams(), and tracker_.
Referenced by nominalSpin().
fillOutputPacketWithTracks()
void dyno::RGBDInstanceFrontendModule::fillOutputPacketWithTracks (VisionImuPacket::Ptr vision_imu_packet, const Frame & frame, const gtsam::Pose3 & T_k_1_k, const ObjectMotionMap & object_motions, const ObjectPoseMap & object_poses) const private
Definition at line 375 of file RGBDInstanceFrontendModule.cc.
{
  CHECK(vision_imu_packet);
  const auto frame_id = frame.getFrameId();
  // construct image tracks
  const double& static_pixel_sigma =
      params_.backend_params_.static_pixel_noise_sigma;
  const double& static_point_sigma =
      params_.backend_params_.static_point_noise_sigma;
  const double& dynamic_pixel_sigma =
      params_.backend_params_.dynamic_pixel_noise_sigma;
  const double& dynamic_point_sigma =
      params_.backend_params_.dynamic_point_noise_sigma;
  gtsam::Vector2 static_pixel_sigmas;
  static_pixel_sigmas << static_pixel_sigma, static_pixel_sigma;
  gtsam::Vector2 dynamic_pixel_sigmas;
  dynamic_pixel_sigmas << dynamic_pixel_sigma, dynamic_pixel_sigma;
  auto& camera = *this->camera_;
  auto fill_camera_measurements =
      [&camera](FeatureFilterIterator it,
                CameraMeasurementStatusVector* measurements, FrameId frame_id,
                const gtsam::Vector2& pixel_sigmas, double depth_sigma) {
        std::shared_ptr<RGBDCamera> rgbd_camera = camera.safeGetRGBDCamera();
        for (const Feature::Ptr& f : it) {
          const TrackletId tracklet_id = f->trackletId();
          const Keypoint& kp = f->keypoint();
          const ObjectId object_id = f->objectId();
          CHECK_EQ(f->objectId(), object_id);
          CHECK(Feature::IsUsable(f));
          MeasurementWithCovariance<Keypoint> kp_measurement =
              MeasurementWithCovariance<Keypoint>::FromSigmas(kp, pixel_sigmas);
          CameraMeasurement camera_measurement(kp_measurement);
          // This can come from either stereo or rgbd
          if (f->hasDepth()) {
            // MeasurementWithCovariance<Landmark> landmark_measurement(
            //     // assume sigma_u and sigma_v are identical
            //     vision_tools::backProjectAndCovariance(
            //         *f, camera, pixel_sigmas(0), depth_sigma));
            // camera_measurement.landmark(landmark_measurement);
            Landmark landmark;
            camera.backProject(kp, f->depth(), &landmark);
            gtsam::Vector3 sigmas;
            sigmas << depth_sigma, depth_sigma, depth_sigma;
            MeasurementWithCovariance<Landmark> landmark_measurement =
                MeasurementWithCovariance<Landmark>::FromSigmas(landmark,
                                                                sigmas);
            camera_measurement.landmark(landmark_measurement);
          }
          if (f->hasRightKeypoint()) {
            CHECK(f->hasDepth())
                << "Right keypoint set for feature but no depth!";
            MeasurementWithCovariance<Keypoint> right_kp_measurement =
                MeasurementWithCovariance<Keypoint>::FromSigmas(
                    f->rightKeypoint(), pixel_sigmas);
            camera_measurement.rightKeypoint(right_kp_measurement);
          }
          // no right keypoint and has rgbd camera and has depth, project
          // keypoint into right camera
          else if (rgbd_camera && f->hasDepth()) {
            bool right_projection_result = rgbd_camera->projectRight(f);
            if (!right_projection_result) {
              // TODO: for now mark as outlier and ignore point
              f->markOutlier();
              continue;
            }
            CHECK(f->hasRightKeypoint());
            MeasurementWithCovariance<Keypoint> right_kp_measurement =
                MeasurementWithCovariance<Keypoint>::FromSigmas(
                    f->rightKeypoint(), pixel_sigmas);
            camera_measurement.rightKeypoint(right_kp_measurement);
          }
          if (f->keypointType() == KeyPointType::STATIC) {
            CHECK_EQ(object_id, background_label);
          } else {
            CHECK_NE(object_id, background_label);
          }
          measurements->push_back(
              CameraMeasurementStatus(camera_measurement, frame_id, tracklet_id,
                                      object_id, ReferenceFrame::LOCAL));
        }
      };
  // TODO: fill ttracking status?
  VisionImuPacket::CameraTracks camera_tracks;
  auto* static_measurements = &camera_tracks.measurements;
  fill_camera_measurements(frame.usableStaticFeaturesBegin(),
                           static_measurements, frame_id, static_pixel_sigmas,
                           static_point_sigma);
  camera_tracks.X_W_k = frame.getPose();
  camera_tracks.T_k_1_k = T_k_1_k;
  vision_imu_packet->cameraTracks(camera_tracks);
  // First collect all dynamic measurements then split them by object
  // This is a bit silly
  CameraMeasurementStatusVector dynamic_measurements;
  fill_camera_measurements(frame.usableDynamicFeaturesBegin(),
                           &dynamic_measurements, frame_id,
                           dynamic_pixel_sigmas, dynamic_point_sigma);
  VisionImuPacket::ObjectTrackMap object_tracks;
  // motions in this frame (ie. new motions!!)
  MotionEstimateMap motion_estimates = object_motions.toEstimateMap(frame_id);
  auto pose_estimates = object_poses.toEstimateMap(frame_id);
  // fill object tracks based on valid motions
  for (const auto& [object_id, motion_reference_estimate] : motion_estimates) {
    CHECK(pose_estimates.exists(object_id))
        << "Object pose missing " << info_string(frame_id, object_id)
        << " but frontend motion available";
    const auto& L_W_k = pose_estimates.at(object_id);
    VisionImuPacket::ObjectTracks object_track;
    object_track.H_W_k_1_k = motion_reference_estimate;
    object_track.L_W_k = L_W_k;
    object_tracks.insert2(object_id, object_track);
  }
  for (const auto& dm : dynamic_measurements) {
    const auto& object_id = dm.objectId();
    // throw out features detected on objects where the tracking failed
    if (object_tracks.exists(object_id)) {
      VisionImuPacket::ObjectTracks& object_track = object_tracks.at(object_id);
      object_track.measurements.push_back(dm);
    }
  }
  vision_imu_packet->objectTracks(object_tracks);
}
References dyno::DynoParams::backend_params_, dyno::background_label, camera_, dyno::BackendParams::dynamic_pixel_noise_sigma, dyno::BackendParams::dynamic_point_noise_sigma, dyno::MeasurementWithCovariance< T, D >::FromSigmas(), dyno::Frame::getFrameId(), dyno::Frame::getPose(), dyno::VisionImuPacket::ObjectTracks::H_W_k_1_k, dyno::info_string(), dyno::Feature::IsUsable(), dyno::VisionImuPacket::ObjectTracks::L_W_k, dyno::CameraMeasurement::landmark(), dyno::LOCAL, dyno::VisionImuPacket::Tracks::measurements, dyno::FrontendModule::params_, dyno::CameraMeasurement::rightKeypoint(), dyno::STATIC, dyno::BackendParams::static_pixel_noise_sigma, dyno::BackendParams::static_point_noise_sigma, dyno::VisionImuPacket::CameraTracks::T_k_1_k, dyno::GenericObjectCentricMap< VALUE >::toEstimateMap(), dyno::Frame::usableDynamicFeaturesBegin(), dyno::Frame::usableStaticFeaturesBegin(), and dyno::VisionImuPacket::CameraTracks::X_W_k.
Referenced by nominalSpin().
nominalSpin()
FrontendModule::SpinReturn dyno::RGBDInstanceFrontendModule::nominalSpin (FrontendInputPacketBase::ConstPtr input) override private
Definition at line 114 of file RGBDInstanceFrontendModule.cc.
{
  ImageContainer::Ptr image_container = input->image_container_;
  const bool has_imu = input->imu_measurements.has_value();
  const bool has_stereo = image_container->hasRightRgb();
  std::optional<gtsam::Rot3> R_curr_ref;
  ImuFrontend::PimPtr pim;
  if (has_imu) {
    pim = imu_frontend_.preintegrateImuMeasurements(
        input->imu_measurements.value());
    nav_state_ =
        pim->predict(previous_nav_state_, gtsam::imuBias::ConstantBias{});
    last_imu_nav_state_update_ = input->getFrameId();
    R_curr_ref =
        previous_nav_state_.attitude().inverse() * nav_state_.attitude();
  }
  Frame::Ptr frame = tracker_->track(input->getFrameId(), input->getTimestamp(),
                                     *image_container, R_curr_ref);
  Frame::Ptr previous_frame = tracker_->getPreviousFrame();
  CHECK(previous_frame);
  VLOG(1) << to_string(tracker_->getTrackerInfo());
  {
    // this will mark some points as invalid if they are out of depth range
    utils::TimingStatsCollector update_depths_timer("depth_updater");
    frame->updateDepths();
  }
  bool stereo_result = false;
  std::shared_ptr<RGBDCamera> rgbd_camera = camera_->safeGetRGBDCamera();
  if (has_stereo) {
    CHECK(rgbd_camera) << "Stereo imagery provided but rgbd camera is null!";
  }
  if (has_stereo) {
    const cv::Mat& left_rgb = image_container->rgb();
    const cv::Mat& right_rgb = image_container->rightRgb();
    auto usable_iterator = frame->static_features_.beginUsable();
    LOG(INFO) << "Counted intliers "
              << std::distance(usable_iterator.begin(), usable_iterator.end());
    FeaturePtrs stereo_features_1;
    stereo_result =
        tracker_->stereoTrack(stereo_features_1, frame->static_features_,
                              left_rgb, right_rgb, rgbd_camera->baseline());
  }
  // this includes the refine correspondances with joint optical flow
  // TODO: lots of internal logic around how the actual pose gets predicted.
  // should streamline this and tell backend how pose was selected!!
  if (!solveCameraMotion(frame, previous_frame, R_curr_ref)) {
    LOG(ERROR) << "Could not solve for camera";
  }
  if (has_stereo && stereo_result) {
    // need to match aagain after optical flow used to update the keypoints
    // wow this seems to make a pretty big difference!!
    const cv::Mat& left_rgb = image_container->rgb();
    const cv::Mat& right_rgb = image_container->rightRgb();
    FeaturePtrs stereo_features_2;
    stereo_result &=
        tracker_->stereoTrack(stereo_features_2, frame->static_features_,
                              left_rgb, right_rgb, rgbd_camera->baseline());
  }
  // VERY important calculation
  const gtsam::Pose3 T_k_1_k =
      previous_nav_state_.pose().inverse() * frame->T_world_camera_;
  vo_velocity_ = T_k_1_k;
  // we currently use the frame pose as the nav state - this value can come from
  // either the VO OR the IMU, depending on the result from the
  // solveCameraMotion this is only relevant since we dont solve incremental so
  // the backend is not immediately updating the frontend at which point we can
  // just use the best estimate in the case of the VO, the nav_state velocity
  // will be wrong (currently!!)
  previous_nav_state_ =
      gtsam::NavState(frame->T_world_camera_, nav_state_.velocity());
  // previous_nav_state_ = nav_state_;
  if (R_curr_ref) {
    imu_frontend_.resetIntegration();
  }
  // if (FLAGS_use_dynamic_track) {
  //   utils::TimingStatsCollector track_dynamic_timer("tracking_dynamic");
  //   vision_tools::trackDynamic(getFrontendParams(), *previous_frame, frame);
  // }
  const auto [object_motions, object_poses] =
      object_motion_solver_->solve(frame, previous_frame);
  VisionImuPacket::Ptr vision_imu_packet = std::make_shared<VisionImuPacket>();
  vision_imu_packet->frameId(frame->getFrameId());
  vision_imu_packet->timestamp(frame->getTimestamp());
  vision_imu_packet->pim(pim);
  vision_imu_packet->groundTruthPacket(input->optional_gt_);
  fillOutputPacketWithTracks(vision_imu_packet, *frame, T_k_1_k, object_motions,
                             object_poses);
  DebugImagery debug_imagery;
  debug_imagery.tracking_image =
      createTrackingImage(frame, previous_frame, object_poses);
  const ImageContainer& processed_image_container = frame->image_container_;
  debug_imagery.rgb_viz =
      ImageType::RGBMono::toRGB(processed_image_container.rgb());
  debug_imagery.flow_viz =
      ImageType::OpticalFlow::toRGB(processed_image_container.opticalFlow());
  debug_imagery.mask_viz = ImageType::MotionMask::toRGB(
      processed_image_container.objectMotionMask());
  debug_imagery.depth_viz =
      ImageType::Depth::toRGB(processed_image_container.depth());
  if (display_queue_) {
    display_queue_->push(
        ImageToDisplay("Tracks", debug_imagery.tracking_image));
    // cv::Mat stereo_matches;
    // if(tracker_->drawStereoMatches(stereo_matches, *frame)){
    //   display_queue_->push(
    //     ImageToDisplay("Stereo Matches", stereo_matches));
    // }
  }
  vision_imu_packet->debugImagery(debug_imagery);
  // // const cv::Mat& board_detection_mask =
  // tracker_->getBoarderDetectionMask(); PointCloudLabelRGB::Ptr
  // dense_labelled_cloud =
  //     frame->projectToDenseCloud(&board_detection_mask);
  PointCloudLabelRGB::Ptr dense_labelled_cloud = nullptr;
  // if (FLAGS_save_frontend_json)
  //   output_packet_record_.insert({output->getFrameId(), output});
  sendToFrontendLogger(frame, vision_imu_packet);
  // if (FLAGS_log_projected_masks)
  //   vision_tools::writeOutProjectMaskAndDepthMap(
  //       frame->image_container_.depth(),
  //       frame->image_container_.objectMotionMask(), *frame->getCamera(),
  //       frame->getFrameId());
  return {State::Nominal, vision_imu_packet};
}
References camera_, createTrackingImage(), dyno::ImageContainer::depth(), dyno::DebugImagery::depth_viz, dyno::FrontendModule::display_queue_, fillOutputPacketWithTracks(), dyno::DebugImagery::flow_viz, imu_frontend_, last_imu_nav_state_update_, dyno::DebugImagery::mask_viz, nav_state_, object_motion_solver_, dyno::ImageContainer::objectMotionMask(), dyno::ImageContainer::opticalFlow(), dyno::ImuFrontend::preintegrateImuMeasurements(), previous_nav_state_, ThreadsafeQueue< T >::push(), dyno::ImuFrontend::resetIntegration(), dyno::ImageContainer::rgb(), dyno::DebugImagery::rgb_viz, sendToFrontendLogger(), solveCameraMotion(), dyno::to_string(), dyno::ImageType::MotionMask::toRGB(), dyno::ImageType::RGBMono::toRGB(), tracker_, dyno::DebugImagery::tracking_image, and vo_velocity_.
sendToFrontendLogger()
void dyno::RGBDInstanceFrontendModule::sendToFrontendLogger (const Frame::Ptr & frame, const VisionImuPacket::Ptr & vision_imu_packet) private
Definition at line 518 of file RGBDInstanceFrontendModule.cc.
{
  if (logger_) {
    auto ground_truths = this->shared_module_info.getGroundTruthPackets();
    logger_->logCameraPose(frame->getFrameId(), vision_imu_packet->cameraPose(),
                           ground_truths);
    logger_->logObjectMotion(frame->getFrameId(),
                             vision_imu_packet->objectMotions(), ground_truths);
    logger_->logObjectPose(frame->getFrameId(),
                           vision_imu_packet->objectPoses(), ground_truths);
    logger_->logTrackingLengthHistogram(frame);
    logger_->logPoints(frame->getFrameId(), vision_imu_packet->cameraPose(),
                       vision_imu_packet->dynamicLandmarkMeasurements());
    logger_->logFrameIdToTimestamp(frame->getFrameId(), frame->getTimestamp());
  }
}
References dyno::SharedModuleInfo::getGroundTruthPackets(), logger_, and dyno::SharedModuleInterface::shared_module_info.
Referenced by nominalSpin().
solveCameraMotion()
bool dyno::RGBDInstanceFrontendModule::solveCameraMotion (Frame::Ptr frame_k, const Frame::Ptr & frame_k_1, std::optional< gtsam::Rot3 > R_curr_ref = {}) private
Solves PnP between frame_k-1 and frame_k using the tracked correspondances to estimate the frame of the current camera.
the pose of the Frame::Ptr (frame_k) is updated, and the features marked as outliers by PnP are set as outliers.
Depending on FrontendParams::use_ego_motion_pnp, a differnet solver will be used to estimate the pose
Parameters
frame_k
frame_k_1
Returns
true
false
Definition at line 270 of file RGBDInstanceFrontendModule.cc.
{
  utils::TimingStatsCollector timer("frontend.solve_camera_motion");
  Pose3SolverResult result;
  const auto& frontend_params = getFrontendParams();
  if (frontend_params.use_ego_motion_pnp) {
    result = motion_solver_.geometricOutlierRejection3d2d(frame_k_1, frame_k,
                                                          R_curr_ref);
  } else {
    // TODO: untested
    LOG(FATAL) << "Not tested";
    // result = motion_solver_.geometricOutlierRejection3d3d(frame_k_1,frame_k);
  }
  VLOG(15) << (frontend_params.use_ego_motion_pnp ? "3D2D" : "3D3D")
           << "camera pose estimate at frame " << frame_k->frame_id_
           << (result.status == TrackingStatus::VALID ? " success "
                                                      : " failure ")
           << ":\n"
           << "- Tracking Status: " << to_string(result.status) << '\n'
           << "- Total Correspondences: "
           << result.inliers.size() + result.outliers.size() << '\n'
           << "\t- # inliers: " << result.inliers.size() << '\n'
           << "\t- # outliers: " << result.outliers.size() << '\n';
  // collect all usable tracklets
  TrackletIds tracklets = frame_k->static_features_.collectTracklets();
  CHECK_GE(tracklets.size(),
           result.inliers.size() +
               result.outliers.size());  // tracklets shoudl be more (or same
                                         // as) correspondances as there will
                                         // be new points untracked
  frame_k->static_features_.markOutliers(result.outliers);
  // was 60!
  if (result.status != TrackingStatus::VALID || result.inliers.size() < 30) {
    // TODO: fix code structure - nav state should be passed in?
    // use nav state which we assume is updated by IMU
    std::stringstream ss;
    ss << "Number usable static feature < 30 or status is invalid. ";
    // check if we have a nav state update from the IMU (this is also a cheap
    // way of checking that we HAVE an imu). If we do we can use the nav state
    // directly to update the current pose as the nav state is the forward
    // prediction from the IMU
    if (last_imu_nav_state_update_ == frame_k->getFrameId()) {
      frame_k->T_world_camera_ = nav_state_.pose();
      ss << "Nav state was previous updated with IMU. Using predicted pose to "
            "set camera transform; k"
         << frame_k->getFrameId();
    } else {
      // no IMU for forward prediction, use constant velocity model to propogate
      // pose expect previous_nav_state_ to always be updated with the best
      // pose!
      frame_k->T_world_camera_ = previous_nav_state_.pose() * vo_velocity_;
      ss << "Nav state has no information from imu. Using constant velocity "
            "model to propofate pose; k"
         << frame_k->getFrameId();
    }
    VLOG(10) << ss.str();
    // if fails should we mark current inliers as outliers?
    // TODO: should almost definitely do this in future, but right now we use
    // measurements to construct a framenode in the backend so if there are no
    // measurements we get a frame_node null.... for now... make hack and set
    // all ages of inliers to 1!!! since we need n measurements in the backend
    // this will ensure that they dont get added to the
    //  optimisation problem but will get added to the map...
    for (const auto& inlier : result.inliers) {
      frame_k->static_features_.getByTrackletId(inlier)->age(1u);
    }
    // frame_k->static_features_.markOutliers(result.inliers);
    // for some reason using tracklets to mark all features gives error as a
    // tracklet id
    // seems to be not actually in static features. Dont know why
    // maybe remeber that tracklets (fromc collectTracklets) is actually just
    // the usable tracklets...?
    // frame_k->static_features_.markOutliers(tracklets);
    return false;
  } else {
    frame_k->T_world_camera_ = result.best_result;
    if (frontend_params.refine_camera_pose_with_joint_of) {
      VLOG(10) << "Refining camera pose with joint of";
      utils::TimingStatsCollector timer(
          "frontend.solve_camera_motion.of_refine");
      OpticalFlowAndPoseOptimizer flow_optimizer(
          frontend_params.object_motion_solver_params.joint_of_params);
      auto flow_opt_result = flow_optimizer.optimizeAndUpdate<CalibrationType>(
          frame_k_1, frame_k, result.inliers, result.best_result);
      frame_k->T_world_camera_ = flow_opt_result.best_result.refined_pose;
      VLOG(15) << "Refined camera pose with optical flow - error before: "
               << flow_opt_result.error_before.value_or(NaN)
               << " error_after: " << flow_opt_result.error_after.value_or(NaN);
    }
    return true;
  }
}
References dyno::SolverResult< T >::best_result, dyno::EgoMotionSolver::geometricOutlierRejection3d2d(), dyno::FrontendModule::getFrontendParams(), dyno::SolverResult< T >::inliers, last_imu_nav_state_update_, motion_solver_, dyno::NaN, nav_state_, dyno::OpticalFlowAndPoseOptimizer::optimizeAndUpdate(), dyno::SolverResult< T >::outliers, previous_nav_state_, dyno::SolverResult< T >::status, dyno::to_string(), dyno::VALID, and vo_velocity_.
Referenced by nominalSpin().
validateImageContainer()
FrontendModule::ImageValidationResult dyno::RGBDInstanceFrontendModule::validateImageContainer (const ImageContainer::Ptr & image_container) const override private virtual
Checks that the incoming ImageContainer meeets the minimum requirement for the derived module.
This is specifically to check that the right image types are contained with the container. If the result is false, InvalidImageContainerException is thrown with the requirements specified by the returned ImageValidationResult.
Parameters
image_container const ImageContainer::Ptr&
Returns
ImageValidationResult
Implements dyno::FrontendModule.
Definition at line 97 of file RGBDInstanceFrontendModule.cc.
{
  return ImageValidationResult(image_container->hasDepth(),
                               "Depth is required");
}
Member Data Documentation
camera_
Camera::Ptr dyno::RGBDInstanceFrontendModule::camera_ private
Definition at line 54 of file RGBDInstanceFrontendModule.hpp.
Referenced by createTrackingImage(), fillOutputPacketWithTracks(), nominalSpin(), and RGBDInstanceFrontendModule().
imu_frontend_
ImuFrontend dyno::RGBDInstanceFrontendModule::imu_frontend_ private
Definition at line 101 of file RGBDInstanceFrontendModule.hpp.
Referenced by nominalSpin().
last_imu_nav_state_update_
FrameId dyno::RGBDInstanceFrontendModule::last_imu_nav_state_update_ {0} private
Tracks when the nav state was updated using IMU, else VO in the front-end, when updating with VO, the velocity will (currently) be wrong!!
Definition at line 110 of file RGBDInstanceFrontendModule.hpp.
Referenced by nominalSpin(), and solveCameraMotion().
logger_
RGBDFrontendLogger::UniquePtr dyno::RGBDInstanceFrontendModule::logger_ private
Definition at line 58 of file RGBDInstanceFrontendModule.hpp.
Referenced by RGBDInstanceFrontendModule(), and sendToFrontendLogger().
motion_solver_
EgoMotionSolver dyno::RGBDInstanceFrontendModule::motion_solver_ private
Definition at line 55 of file RGBDInstanceFrontendModule.hpp.
Referenced by solveCameraMotion().
nav_state_
gtsam::NavState dyno::RGBDInstanceFrontendModule::nav_state_ private
Definition at line 102 of file RGBDInstanceFrontendModule.hpp.
Referenced by nominalSpin(), and solveCameraMotion().
object_motion_solver_
ObjectMotionSolver::UniquePtr dyno::RGBDInstanceFrontendModule::object_motion_solver_ private
Definition at line 56 of file RGBDInstanceFrontendModule.hpp.
Referenced by nominalSpin(), and RGBDInstanceFrontendModule().
previous_nav_state_
gtsam::NavState dyno::RGBDInstanceFrontendModule::previous_nav_state_ private
Definition at line 105 of file RGBDInstanceFrontendModule.hpp.
Referenced by nominalSpin(), and solveCameraMotion().
tracker_
FeatureTracker::UniquePtr dyno::RGBDInstanceFrontendModule::tracker_ private
Definition at line 57 of file RGBDInstanceFrontendModule.hpp.
Referenced by boostrapSpin(), createTrackingImage(), nominalSpin(), and RGBDInstanceFrontendModule().
vo_velocity_
gtsam::Pose3 dyno::RGBDInstanceFrontendModule::vo_velocity_ private
The relative camera pose (T_k_1_k) from the previous frame this is used as a constant velocity model when VO tracking fails and the IMU is not available!
Definition at line 115 of file RGBDInstanceFrontendModule.hpp.
Referenced by nominalSpin(), and solveCameraMotion().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/frontend/RGBDInstanceFrontendModule.hpp
dynosam/src/frontend/RGBDInstanceFrontendModule.cc