DynoSAM: dyno::OMDOldAllLoader Class Reference
dyno::OMDOldAllLoader Class Reference
Public Member Functions
OMDOldAllLoader (const std::string &file_path)
size_t size () const
double getTimestamp (size_t idx)
cv::Mat getRGB (size_t idx) const
cv::Mat getDepthImage (size_t idx) const
cv::Mat getOpticalFlow (size_t idx) const
cv::Mat getInstanceMask (size_t idx) const
GroundTruthInputPacket getGtPacket (size_t idx) const
void loadAll (const std::string &path_to_sequence)
const CameraParams & getLeftCameraParams () const
void setCameraParams (const std::string &file_path)
Private Attributes
std::vector< std::string > rgb_file_names_
std::vector< std::string > depth_file_names_
std::vector< std::string > flow_file_names_
std::vector< std::string > semantic_file_names_
std::vector< Timestamp > timestamps_
std::vector< gtsam::Pose3 > vPoseGT_
std::vector< ObjectPoseGT > vObjPoseGT_
std::vector< GroundTruthInputPacket > ground_truths_
cv::Size img_size_
CameraParams rgbd_camera_params_
double base_line_
Detailed Description
Definition at line 858 of file OMDDataProvider.cc.
Constructor & Destructor Documentation
OMDOldAllLoader()
dyno::OMDOldAllLoader::OMDOldAllLoader (const std::string & file_path) inline
Definition at line 863 of file OMDDataProvider.cc.
    {
        loadAll(file_path);
        setCameraParams(file_path);
    }
References loadAll(), and setCameraParams().
Member Function Documentation
getDepthImage()
cv::Mat dyno::OMDOldAllLoader::getDepthImage (size_t idx) const inline
Definition at line 888 of file OMDDataProvider.cc.
{
        CHECK_LT(idx, depth_file_names_.size());
        cv::Mat disp;
        loadDepth(depth_file_names_.at(idx), disp);
        CHECK(!disp.empty());
        constexpr auto depth_type = ImageType::Depth::OpenCVType;
        cv::Mat depth_image = cv::Mat::zeros(disp.size(), depth_type);
        const auto baseline = base_line_;
        const auto fx = rgbd_camera_params_.fx();
        // Get depth from disparity
        for (int i = 0u; i < disp.rows; i++) {
            // Loop over rows
            const double* disp_ptr = disp.ptr<double>(i);
            double* depth_ptr = depth_image.ptr<double>(i);
            for (int j = 0u; j < disp.cols; j++) {
                // Loop over cols
                const double depth = (baseline * fx) / (static_cast<double>(disp_ptr[j])/ 256.0);
                *(depth_ptr + j) = depth;
            }
        }
        return depth_image;
    }
References base_line_, depth_file_names_, dyno::CameraParams::fx(), dyno::loadDepth(), and rgbd_camera_params_.
getGtPacket()
GroundTruthInputPacket dyno::OMDOldAllLoader::getGtPacket (size_t idx) const inline
Definition at line 937 of file OMDDataProvider.cc.
{
        return ground_truths_.at(idx);
    }
References ground_truths_.
getInstanceMask()
cv::Mat dyno::OMDOldAllLoader::getInstanceMask (size_t idx) const inline
Definition at line 927 of file OMDDataProvider.cc.
{
        CHECK_LT(idx, semantic_file_names_.size());
        cv::Mat rgb;
        loadSemanticMask(semantic_file_names_.at(idx), img_size_, rgb);
        CHECK(!rgb.empty());
        return rgb;
    }
References img_size_, dyno::loadSemanticMask(), and semantic_file_names_.
getLeftCameraParams()
const CameraParams & dyno::OMDOldAllLoader::getLeftCameraParams () const inline
Definition at line 1215 of file OMDDataProvider.cc.
{
        return rgbd_camera_params_;
    }
References rgbd_camera_params_.
getOpticalFlow()
cv::Mat dyno::OMDOldAllLoader::getOpticalFlow (size_t idx) const inline
Definition at line 917 of file OMDDataProvider.cc.
{
        CHECK_LT(idx, flow_file_names_.size());
        cv::Mat rgb;
        loadFlow(flow_file_names_.at(idx), rgb);
        CHECK(!rgb.empty());
        return rgb;
    }
References flow_file_names_, and dyno::loadFlow().
getRGB()
cv::Mat dyno::OMDOldAllLoader::getRGB (size_t idx) const inline
Definition at line 877 of file OMDDataProvider.cc.
{
        CHECK_LT(idx, rgb_file_names_.size());
        cv::Mat rgb;
        loadRGB(rgb_file_names_.at(idx), rgb);
        CHECK(!rgb.empty()) << "Empty at  " << rgb_file_names_.at(idx);
        img_size_ = rgb.size();
        return rgb;
    }
References img_size_, dyno::loadRGB(), and rgb_file_names_.
getTimestamp()
double dyno::OMDOldAllLoader::getTimestamp (size_t idx) inline
Definition at line 873 of file OMDDataProvider.cc.
{
        return static_cast<double>(timestamps_.at(idx));
    }
References timestamps_.
loadAll()
void dyno::OMDOldAllLoader::loadAll (const std::string & path_to_sequence) inline
Definition at line 942 of file OMDDataProvider.cc.
{
        std::ifstream times_stream;
        std::string strPathTimeFile = path_to_sequence + "/times.txt";
        throwExceptionIfPathInvalid(strPathTimeFile);
        const gtsam::Pose3 T_cv_robotic = gtsam::Pose3(
            gtsam::Rot3(
                1, 0, 0,
                0, 0, -1,
                0, 1, 0),
            gtsam::traits<gtsam::Point3>::Identity());
        times_stream.open(strPathTimeFile.c_str());
        while (!times_stream.eof())
        {
            std::string s;
            getline(times_stream, s);
            if (!s.empty())
            {
                std::stringstream ss;
                ss << s;
                double t;
                ss >> t;
                timestamps_.push_back(t);
            }
        }
        times_stream.close();
        LOG(INFO) << "Loaded " << timestamps_.size() << " timestamps";
        // +++ image, depth, semantic and moving object tracking mask +++
        std::string strPrefixImage = path_to_sequence + "/image_0/";      // image  image_0
        std::string strPrefixDepth = path_to_sequence + "/depth/";        // depth_gt  depth  depth_mono_stereo
        std::string strPrefixSemantic = path_to_sequence + "/semantic/";  // semantic_gt  semantic
        std::string strPrefixFlow = path_to_sequence + "/flow/";          // flow_gt  flow
        // const int nTimes = timestamps_.size();
        // rgb_file_names_.resize(nTimes);
        // depth_file_names_.resize(nTimes);
        // semantic_file_names_.resize(nTimes);
        // flow_file_names_.resize(nTimes);
        loadPathsInDirectory(rgb_file_names_, strPrefixImage,
            [](const std::string& file) -> bool {
                return boost::algorithm::ends_with( &file[0], ".png");  // true
            });
        loadPathsInDirectory(depth_file_names_, strPrefixDepth,
            [](const std::string& file) -> bool {
                return boost::algorithm::ends_with( &file[0], ".png");  // true
            });
        loadPathsInDirectory(semantic_file_names_, strPrefixSemantic,
            [](const std::string& file) -> bool {
                return boost::algorithm::ends_with( &file[0], ".txt");  // true
            });
        loadPathsInDirectory(flow_file_names_, strPrefixFlow,
            [](const std::string& file) -> bool {
               return boost::algorithm::ends_with( &file[0], ".flo");  // true
            });
        const int nTimes = rgb_file_names_.size();
        LOG(INFO) << rgb_file_names_.back();
        LOG(INFO) << "Loaded " << nTimes;
        // for (int i = 0; i < nTimes; i++)
        // {
        //     std::stringstream ss;
        //     ss << std::setfill('0') << std::setw(6) << i;
        //     rgb_file_names_.push_back(strPrefixImage + ss.str() + ".png");
        //     depth_file_names_.push_back(strPrefixDepth + ss.str() + ".png");
        //     semantic_file_names_.push_back(strPrefixSemantic + ss.str() + ".txt");
        //     flow_file_names_.push_back(strPrefixFlow + ss.str() + ".flo");
        // }
        // +++ ground truth pose +++
        std::string strFilenamePose = path_to_sequence + "/pose_gt.txt";  //  pose_gt.txt  kevin_extrinsics.txt
        throwExceptionIfPathInvalid(strFilenamePose);
        // vPoseGT.resize(nTimes);
        std::ifstream fPose;
        fPose.open(strFilenamePose.c_str());
        LOG(INFO) << "OPened pose file";
        gtsam::Pose3 initial_pose;
        bool has_initial_pose = false;
        while (!fPose.eof())
        {
            std::string s;
            getline(fPose, s);
            if (!s.empty())
            {
                std::stringstream ss;
                ss << s;
                int t;
                ss >> t;
                cv::Mat Pose_tmp = cv::Mat::eye(4, 4, CV_64F);
                ss >> Pose_tmp.at<double>(0, 0) >> Pose_tmp.at<double>(0, 1) >> Pose_tmp.at<double>(0, 2) >>
                    Pose_tmp.at<double>(0, 3) >> Pose_tmp.at<double>(1, 0) >> Pose_tmp.at<double>(1, 1) >>
                    Pose_tmp.at<double>(1, 2) >> Pose_tmp.at<double>(1, 3) >> Pose_tmp.at<double>(2, 0) >>
                    Pose_tmp.at<double>(2, 1) >> Pose_tmp.at<double>(2, 2) >> Pose_tmp.at<double>(2, 3) >>
                    Pose_tmp.at<double>(3, 0) >> Pose_tmp.at<double>(3, 1) >> Pose_tmp.at<double>(3, 2) >>
                    Pose_tmp.at<double>(3, 3);
                // std::vector<double> vec(Pose_tmp.begin<double>(),Pose_tmp.end<double>());
                // vPoseGT_.push_back(parsePose(vec));
                gtsam::Pose3 pose = utils::cvMatToGtsamPose3(Pose_tmp);
                // pose = T_cv_robotic * pose * T_cv_robotic.inverse();
                if (!has_initial_pose) {
                    initial_pose = pose;
                    has_initial_pose = true;
                }
                // pose = initial_pose.inverse() * pose;
                vPoseGT_.push_back(pose);
            }
        }
        fPose.close();
        // +++ ground truth object pose +++
        std::string strFilenameObjPose = path_to_sequence + "/object_pose.txt";
        throwExceptionIfPathInvalid(strFilenameObjPose);
        std::ifstream fObjPose;
        fObjPose.open(strFilenameObjPose.c_str());
        LOG(INFO) << "Opened object pose file";
        while (!fObjPose.eof())
        {
            std::string s;
            getline(fObjPose, s);
            if (!s.empty())
            {
                std::stringstream ss;
                ss << s;
                std::vector<double> ObjPose_tmp(8, 0);
                ss >> ObjPose_tmp[0] >> ObjPose_tmp[1] >> ObjPose_tmp[2] >> ObjPose_tmp[3] >> ObjPose_tmp[4] >> ObjPose_tmp[5] >>
                    ObjPose_tmp[6] >> ObjPose_tmp[7];
                ObjectPoseGT object_pose;
                object_pose.frame_id_ = static_cast<size_t>(ObjPose_tmp[0]);
                object_pose.object_id_ = static_cast<size_t>(ObjPose_tmp[1]);
                const auto frame_id = object_pose.frame_id_;
                // assign t vector
                cv::Mat t(3, 1, CV_64F);
                t.at<double>(0) = ObjPose_tmp[2];
                t.at<double>(1) = ObjPose_tmp[3];
                t.at<double>(2) = ObjPose_tmp[4];
                // from axis-angle to Rotation Matrix
                cv::Mat R(3, 3, CV_64F);
                cv::Mat Rvec(3, 1, CV_64F);
                // assign r vector
                Rvec.at<double>(0, 0) = ObjPose_tmp[5];
                Rvec.at<double>(0, 1) = ObjPose_tmp[6];
                Rvec.at<double>(0, 2) = ObjPose_tmp[7];
                // *******************************************************************
                const double angle = std::sqrt(ObjPose_tmp[5] * ObjPose_tmp[5] + ObjPose_tmp[6] * ObjPose_tmp[6] + ObjPose_tmp[7] * ObjPose_tmp[7]);
                if (angle > 0)
                {
                    Rvec.at<double>(0, 0) = Rvec.at<double>(0, 0) / angle;
                    Rvec.at<double>(0, 1) = Rvec.at<double>(0, 1) / angle;
                    Rvec.at<double>(0, 2) = Rvec.at<double>(0, 2) / angle;
                }
                const double s = std::sin(angle);
                const double c = std::cos(angle);
                const double v = 1 - c;
                const double x = Rvec.at<double>(0, 0);
                const double y = Rvec.at<double>(0, 1);
                const double z = Rvec.at<double>(0, 2);
                const double xyv = x * y * v;
                const double yzv = y * z * v;
                const double xzv = x * z * v;
                R.at<double>(0, 0) = x * x * v + c;
                R.at<double>(0, 1) = xyv - z * s;
                R.at<double>(0, 2) = xzv + y * s;
                R.at<double>(1, 0) = xyv + z * s;
                R.at<double>(1, 1) = y * y * v + c;
                R.at<double>(1, 2) = yzv - x * s;
                R.at<double>(2, 0) = xzv - y * s;
                R.at<double>(2, 1) = yzv + x * s;
                R.at<double>(2, 2) = z * z * v + c;
                // construct 4x4 transformation matrix
                cv::Mat Pose = cv::Mat::eye(4, 4, CV_64F);
                Pose.at<double>(0, 0) = R.at<double>(0, 0);
                Pose.at<double>(0, 1) = R.at<double>(0, 1);
                Pose.at<double>(0, 2) = R.at<double>(0, 2);
                Pose.at<double>(0, 3) = t.at<double>(0);
                Pose.at<double>(1, 0) = R.at<double>(1, 0);
                Pose.at<double>(1, 1) = R.at<double>(1, 1);
                Pose.at<double>(1, 2) = R.at<double>(1, 2);
                Pose.at<double>(1, 3) = t.at<double>(1);
                Pose.at<double>(2, 0) = R.at<double>(2, 0);
                Pose.at<double>(2, 1) = R.at<double>(2, 1);
                Pose.at<double>(2, 2) = R.at<double>(2, 2);
                Pose.at<double>(2, 3) = t.at<double>(2);
                object_pose.L_world_ = utils::cvMatToGtsamPose3(Pose);
                // object_pose.L_world_ = T_cv_robotic * object_pose.L_world_ * T_cv_robotic.inverse();
                vObjPoseGT_.push_back(object_pose);
            }
        }
        fObjPose.close();
        LOG(INFO) << "Loaded object poses";
        // organise gt poses into vector of arrays
        std::vector<std::vector<size_t>> vObjPoseID(rgb_file_names_.size());
        for (size_t i = 0; i < vObjPoseGT_.size(); ++i)
        {
            size_t f_id = vObjPoseGT_[i].frame_id_;
            if (f_id >= rgb_file_names_.size())
            {
                break;
            }
            vObjPoseID[f_id].push_back(i);
        }
        LOG(INFO) << "Organised object poses";
        // now read image image and add grount truths
        for (size_t frame_id = 0; frame_id < nTimes - 1; frame_id++)
        {
            Timestamp timestamp = timestamps_[frame_id];
            GroundTruthInputPacket gt_packet;
            gt_packet.timestamp_ = timestamp;
            gt_packet.frame_id_ = frame_id;
            auto original_camera_pose = vPoseGT_[frame_id];
            auto aligned_camera_pose = initial_pose.inverse() * original_camera_pose;
            // auto aligned_camera_pose = initial_pose.inverse() * original_camera_pose;
            gt_packet.X_world_ = aligned_camera_pose;
            // add ground truths for this fid
            for (int i = 0; i < vObjPoseID[frame_id].size(); i++)
            {
                auto gt_object = vObjPoseGT_[vObjPoseID[frame_id][i]];
                auto relative_object_pose = original_camera_pose.inverse() * gt_object.L_world_;
                auto aligned_object_pose = aligned_camera_pose * relative_object_pose;
                gt_object.L_camera_ = relative_object_pose;
                gt_object.L_world_ = aligned_object_pose;
                gt_packet.object_poses_.push_back(gt_object);
                // sanity check
                CHECK_EQ(gt_packet.object_poses_[i].frame_id_, frame_id);
            }
            if (frame_id > 0) {
                auto& previous_gt = ground_truths_.at(frame_id - 1);
                gt_packet.calculateAndSetMotions(previous_gt);
            }
            ground_truths_.push_back(gt_packet);
        }
        LOG(INFO) << "Set GT";
    }
References dyno::GroundTruthInputPacket::calculateAndSetMotions(), dyno::utils::cvMatToGtsamPose3(), depth_file_names_, flow_file_names_, dyno::ObjectPoseGT::frame_id_, dyno::GroundTruthInputPacket::frame_id_, ground_truths_, dyno::ObjectPoseGT::L_world_, dyno::loadPathsInDirectory(), dyno::ObjectPoseGT::object_id_, dyno::GroundTruthInputPacket::object_poses_, rgb_file_names_, semantic_file_names_, dyno::throwExceptionIfPathInvalid(), dyno::PipelinePayload::timestamp_, timestamps_, vObjPoseGT_, vPoseGT_, and dyno::GroundTruthInputPacket::X_world_.
Referenced by OMDOldAllLoader().
setCameraParams()
void dyno::OMDOldAllLoader::setCameraParams (const std::string & file_path) inline
Definition at line 1219 of file OMDDataProvider.cc.
{
        std::string params_file = file_path + "oxford.yaml";
        YamlParser yaml_parser(params_file);
        std::vector<double> intrinsics_v(4);
        yaml_parser.getYamlParam<double>("Camera.fx", intrinsics_v.data());
        yaml_parser.getYamlParam<double>("Camera.fy", intrinsics_v.data() + 1);
        yaml_parser.getYamlParam<double>("Camera.cx", intrinsics_v.data() + 2);
        yaml_parser.getYamlParam<double>("Camera.cy", intrinsics_v.data() + 3);
        CameraParams::IntrinsicsCoeffs intrinsics;
        intrinsics.resize(4u);
        // Move elements from one to the other.
        std::copy_n(std::make_move_iterator(intrinsics_v.begin()),
                    intrinsics.size(),
                    intrinsics.begin());
        CameraParams::DistortionCoeffs distortion({0, 0, 0, 0});
        double width, height;
        yaml_parser.getYamlParam<double>("Camera.width", &width);
        yaml_parser.getYamlParam<double>("Camera.height", &height);
        cv::Size image_size(width, height);
        yaml_parser.getYamlParam<double>("Camera.baseline", &base_line_);
        auto model = CameraParams::stringToDistortion("radtan", "pinhole");
        rgbd_camera_params_ = CameraParams(
            intrinsics,
            distortion,
            image_size,
            model
        );
        LOG(INFO) << "Camera params " << rgbd_camera_params_.toString();
    }
References base_line_, dyno::YamlParser::getYamlParam(), rgbd_camera_params_, dyno::CameraParams::stringToDistortion(), and dyno::CameraParams::toString().
Referenced by OMDOldAllLoader().
size()
size_t dyno::OMDOldAllLoader::size () const inline
Definition at line 869 of file OMDDataProvider.cc.
{
        return rgb_file_names_.size();
    }
References rgb_file_names_.
Member Data Documentation
base_line_
double dyno::OMDOldAllLoader::base_line_ private
Definition at line 1273 of file OMDDataProvider.cc.
Referenced by getDepthImage(), and setCameraParams().
depth_file_names_
std::vector<std::string> dyno::OMDOldAllLoader::depth_file_names_ private
Definition at line 1261 of file OMDDataProvider.cc.
Referenced by getDepthImage(), and loadAll().
flow_file_names_
std::vector<std::string> dyno::OMDOldAllLoader::flow_file_names_ private
Definition at line 1262 of file OMDDataProvider.cc.
Referenced by getOpticalFlow(), and loadAll().
ground_truths_
std::vector<GroundTruthInputPacket> dyno::OMDOldAllLoader::ground_truths_ private
Definition at line 1269 of file OMDDataProvider.cc.
Referenced by getGtPacket(), and loadAll().
img_size_
cv::Size dyno::OMDOldAllLoader::img_size_ mutable private
Definition at line 1271 of file OMDDataProvider.cc.
Referenced by getInstanceMask(), and getRGB().
rgb_file_names_
std::vector<std::string> dyno::OMDOldAllLoader::rgb_file_names_ private
Definition at line 1260 of file OMDDataProvider.cc.
Referenced by getRGB(), loadAll(), and size().
rgbd_camera_params_
CameraParams dyno::OMDOldAllLoader::rgbd_camera_params_ private
Definition at line 1272 of file OMDDataProvider.cc.
Referenced by getDepthImage(), getLeftCameraParams(), and setCameraParams().
semantic_file_names_
std::vector<std::string> dyno::OMDOldAllLoader::semantic_file_names_ private
Definition at line 1263 of file OMDDataProvider.cc.
Referenced by getInstanceMask(), and loadAll().
timestamps_
std::vector<Timestamp> dyno::OMDOldAllLoader::timestamps_ private
Definition at line 1264 of file OMDDataProvider.cc.
Referenced by getTimestamp(), and loadAll().
vObjPoseGT_
std::vector<ObjectPoseGT> dyno::OMDOldAllLoader::vObjPoseGT_ private
Definition at line 1267 of file OMDDataProvider.cc.
Referenced by loadAll().
vPoseGT_
std::vector<gtsam::Pose3> dyno::OMDOldAllLoader::vPoseGT_ private
Definition at line 1266 of file OMDDataProvider.cc.
Referenced by loadAll().
The documentation for this class was generated from the following file:
dynosam/src/dataprovider/OMDDataProvider.cc