DynoSAM: dyno::DynoParams Class Reference
dyno::DynoParams Class Reference
#include <PipelineParams.hpp>
Classes
struct PipelineParams
Public Member Functions
DynoParams (const std::string &params_folder_path)
DynoParams ()
For I/O construction.
void printAllParams (bool print_glog_params=true) const
bool parallelRun () const
int dataProviderType () const
bool preferDataProviderCameraParams () const
Public Attributes
PipelineParams pipeline_params_
FrontendParams frontend_params_
BackendParams backend_params_
CameraParams camera_params_
FrontendType frontend_type_ = FrontendType::kRGBD
Detailed Description
Definition at line 43 of file PipelineParams.hpp.
Constructor & Destructor Documentation
DynoParams() [1/2]
dyno::DynoParams::DynoParams (const std::string & params_folder_path)
Definition at line 39 of file Pipeline-Definitions.cc.
    : DynoParams(params_folder_path + "/" + kPipelineFilename,
                 params_folder_path + "/" + kFrontendFilename,
                 params_folder_path + "/" + kBackendFilename,
                 params_folder_path + "/" + kCameraFilename)   {}
DynoParams() [2/2]
dyno::DynoParams::DynoParams () inline
For I/O construction.
Definition at line 52 of file PipelineParams.hpp.
{}
Member Function Documentation
dataProviderType()
int dyno::DynoParams::dataProviderType () const inline
Definition at line 68 of file PipelineParams.hpp.
{ return pipeline_params_.data_provider_type; }
References dyno::DynoParams::PipelineParams::data_provider_type, and pipeline_params_.
parallelRun()
bool dyno::DynoParams::parallelRun () const inline
Definition at line 67 of file PipelineParams.hpp.
{ return pipeline_params_.parallel_run;  }
References dyno::DynoParams::PipelineParams::parallel_run, and pipeline_params_.
Referenced by dyno::DynoPipelineManager::DynoPipelineManager(), dyno::DynoPipelineManager::launchSpinners(), dyno::DynoPipelineManager::loadPipelines(), and dyno::DynoPipelineManager::spin().
preferDataProviderCameraParams()
bool dyno::DynoParams::preferDataProviderCameraParams () const inline
Definition at line 69 of file PipelineParams.hpp.
{ return pipeline_params_.prefer_data_provider_camera_params; }
References pipeline_params_, and dyno::DynoParams::PipelineParams::prefer_data_provider_camera_params.
Referenced by dyno::DynoPipelineManager::DynoPipelineManager().
printAllParams()
void dyno::DynoParams::printAllParams (bool print_glog_params = true) const
Definition at line 54 of file PipelineParams.cc.
{
    LOG(INFO) << "Frontend Params: " << config::toString(frontend_params_);
    LOG(INFO) << "Pipeline Params: " << config::toString(pipeline_params_);
    //TODO: currently cannot print camera params becuase we use intermediate variables in the loading process!!
    // LOG(INFO) << "Camera Params: " << config::toString(camera_params_);
    if(print_glog_params) google::ShowUsageWithFlags("");
}
References frontend_params_, and pipeline_params_.
Referenced by main().
Member Data Documentation
backend_params_
BackendParams dyno::DynoParams::backend_params_
Definition at line 75 of file PipelineParams.hpp.
Referenced by dyno::DynoPipelineManager::loadPipelines().
camera_params_
CameraParams dyno::DynoParams::camera_params_
Definition at line 76 of file PipelineParams.hpp.
Referenced by dyno::DynoPipelineManager::DynoPipelineManager().
frontend_params_
FrontendParams dyno::DynoParams::frontend_params_
Definition at line 74 of file PipelineParams.hpp.
Referenced by dyno::DynoPipelineManager::loadPipelines(), and printAllParams().
frontend_type_
FrontendType dyno::DynoParams::frontend_type_ = FrontendType::kRGBD
Definition at line 78 of file PipelineParams.hpp.
Referenced by dyno::DynoPipelineManager::loadPipelines().
pipeline_params_
PipelineParams dyno::DynoParams::pipeline_params_
Definition at line 73 of file PipelineParams.hpp.
Referenced by dataProviderType(), parallelRun(), preferDataProviderCameraParams(), and printAllParams().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/pipeline/PipelineParams.hpp
dynosam/src/pipeline/Pipeline-Definitions.cc
dynosam/src/pipeline/PipelineParams.cc