DynoSAM: dyno::DSDTransport Class Reference
dyno::DSDTransport Class Reference
Class for managing the publishing and conversion of ObjectOdometry messages. DSD is shorthand for Dynamic SLAM Display.
#include <DSDCommonRos.hpp>
Classes
class Publisher
Nested Publisher that publishes all the object odometries for a single frame/timestamp. Object odometries are set on construction. Functionality for publishing the object odom's themselves and broadcasting their position on the tf tree using the object current pose is addionally included.
Public Member Functions
DSDTransport (rclcpp::Node::SharedPtr node)
Publisher addObjectInfo (const ObjectMotionMap &motions, const ObjectPoseMap &poses, const std::string &frame_id_link, const FrameIdTimestampMap &frame_timestamp_map, FrameId frame_id, Timestamp timestamp)
Create a object odometry Publisher given object state (motion and pose) information up to a given frame (k). The resulting publisher can then be used to published ObjectOdometry messages and update the tf tree with the object poses w.r.t to the parent frame id link.
Static Public Member Functions
static std::string constructObjectFrameLink (ObjectId object_id)
Construct object id tf link from an object id. This will be used as the link in the ROS tf tree and as the child frame id for the object odometry.
static ObjectOdometry constructObjectOdometry (const gtsam::Pose3 &e_H_k_world, const gtsam::Pose3 &pose_k, ObjectId object_id, FrameId frame_id_k, Timestamp timestamp_k, const std::string &frame_id_link, const std::string &child_frame_id_link)
static ObjectOdometryMap constructObjectOdometries (const ObjectMotionMap &motions, const ObjectPoseMap &poses, FrameId frame_id_k, Timestamp timestamp_k, const std::string &frame_id_link)
static MultiObjectOdometryPath constructMultiObjectOdometryPaths (const ObjectMotionMap &motions, const ObjectPoseMap &poses, Timestamp timestamp_k, const FrameIdTimestampMap &frame_timestamp_map, const std::string &frame_id_link, bool interpolate_missing_segments=true)
Private Attributes
rclcpp::Node::SharedPtr node_
ObjectOdometryPub::SharedPtr object_odom_publisher_
MultiObjectOdometryPathPub::SharedPtr multi_object_odom_path_publisher_
std::shared_ptr< tf2_ros::TransformBroadcaster > tf_broadcaster_
Detailed Description
Class for managing the publishing and conversion of ObjectOdometry messages. DSD is shorthand for Dynamic SLAM Display.
Contains an ObjectOdometry publisher on the topic "object_odometry" and a tf2_ros::TransformBroadcaster to broadcast the object odometry TF.
Definition at line 66 of file DSDCommonRos.hpp.
Constructor & Destructor Documentation
DSDTransport()
dyno::DSDTransport::DSDTransport (rclcpp::Node::SharedPtr node)
Definition at line 12 of file DSDCommonRos.cc.
                                                   : node_(node) {
  object_odom_publisher_ =
      node->create_publisher<ObjectOdometry>("object_odometry", 1);
  multi_object_odom_path_publisher_ =
      node->create_publisher<MultiObjectOdometryPath>("object_odometry_path",
                                                      1);
  tf_broadcaster_ = std::make_unique<tf2_ros::TransformBroadcaster>(*node_);
  VLOG(20) << "Constructed DSDTransport with effective namespace "
           << node_->get_effective_namespace();
}
References multi_object_odom_path_publisher_, node_, object_odom_publisher_, and tf_broadcaster_.
Member Function Documentation
addObjectInfo()
DSDTransport::Publisher dyno::DSDTransport::addObjectInfo (const ObjectMotionMap & motions, const ObjectPoseMap & poses, const std::string & frame_id_link, const FrameIdTimestampMap & frame_timestamp_map, FrameId frame_id, Timestamp timestamp)
Create a object odometry Publisher given object state (motion and pose) information up to a given frame (k). The resulting publisher can then be used to published ObjectOdometry messages and update the tf tree with the object poses w.r.t to the parent frame id link.
Parameters
motions_k const ObjectMotionMap& motions at time (... to k)
poses const ObjectPoseMap& poses at time (... to k)
frame_id_link const std::string& parent tf tree link (e.g. odom/world.)
frame_id FrameId current frame (k)
timestamp Timestamp
Returns
Publisher
Definition at line 248 of file DSDCommonRos.cc.
{
  return Publisher(node_, object_odom_publisher_,
                   multi_object_odom_path_publisher_, tf_broadcaster_, motions,
                   poses, frame_id_link, frame_timestamp_map, frame_id,
                   timestamp);
}
References multi_object_odom_path_publisher_, node_, object_odom_publisher_, and tf_broadcaster_.
Referenced by dyno::BackendDSDRos::spinOnceImpl(), dyno::FrontendDSDRos::tryPublishGroundTruth(), and dyno::FrontendDSDRos::tryPublishObjects().
constructMultiObjectOdometryPaths()
MultiObjectOdometryPath dyno::DSDTransport::constructMultiObjectOdometryPaths (const ObjectMotionMap & motions, const ObjectPoseMap & poses, Timestamp timestamp_k, const FrameIdTimestampMap & frame_timestamp_map, const std::string & frame_id_link, bool interpolate_missing_segments = true) static
Definition at line 89 of file DSDCommonRos.cc.
{
  MultiObjectOdometryPath multi_path;
  multi_path.header.stamp = utils::toRosTime(timestamp_k);
  multi_path.header.frame_id = frame_id_link;
  // TODO: right now dont have the motion for every timestep so... just leave
  // blank?
  for (const auto& [object_id, frame_pose_map] : poses) {
    const std::string child_frame_id_link = constructObjectFrameLink(object_id);
    // NOTE: cannot use FrameId for type (size_t)
    int previous_frame_id = -1;
    bool first = true;
    int path_segment = 0;
    std_msgs::msg::ColorRGBA colour_msg;
    convert(Color::uniqueId(object_id), colour_msg);
    // paths for this object, broken into segments
    gtsam::FastMap<int, ObjectOdometryPath> segmented_paths;
    for (const auto& [frame_id, object_pose] : frame_pose_map) {
      if (!motions.exists(object_id, frame_id)) {
        // LOG(WARNING)
        //     << "Cannot construct ObjectOdometry for object " << object_id
        //     << ", at frame " << frame_id
        //     << " for MultiObjectOdometryPath. Missing entry in
        //     ObjectMotionMap";
        continue;
      }
      const gtsam::Pose3& object_motion = motions.at(object_id, frame_id);
      if (!frame_timestamp_map.exists(frame_id)) {
        LOG(WARNING) << "Cannot construct ObjectOdometry for object "
                     << object_id << ", at frame " << frame_id
                     << " for MultiObjectOdometryPath. Missing entry in "
                        "FrameIdTimestampMap";
        continue;
      }
      const Timestamp& timestamp = frame_timestamp_map.at(frame_id);
      // if (!first && static_cast<int>(frame_id) != previous_frame_id + 1) {
      //   path_segment++;
      // }
      first = false;
      previous_frame_id = static_cast<int>(frame_id);
      // RIGHT NOW MOTION IDENTITY
      // timestamp is wrong
      gtsam::Pose3 motion;
      const ObjectOdometry object_odometry = constructObjectOdometry(
          object_motion, object_pose, object_id, frame_id, timestamp,
          frame_id_link, child_frame_id_link);
      if (!segmented_paths.exists(path_segment)) {
        ObjectOdometryPath path;
        path.colour = colour_msg;
        path.object_id = object_id;
        path.path_segment = path_segment;
        path.header = multi_path.header;
        segmented_paths.insert2(path_segment, path);
      }
      ObjectOdometryPath& path = segmented_paths.at(path_segment);
      path.object_odometries.push_back(object_odometry);
    }
    // TODO: make this a flag and the frame diff!
    if (interpolate_missing_segments) {
      // assume segmented paths are in order
      for (auto it = segmented_paths.begin();
           std::next(it) != segmented_paths.end(); ++it) {
        auto current_segment_id = it->first;
        auto next_segment_id = std::next(it)->first;
        CHECK_EQ(current_segment_id + 1, next_segment_id);
        const ObjectOdometryPath& current_path_segment = it->second;
        const ObjectOdometryPath& next_path_segment = std::next(it)->second;
        const auto begin_object_odom =
            current_path_segment.object_odometries.back();
        const auto end_object_odom =
            next_path_segment.object_odometries.front();
        // interpolate between end of current and start of next
        // less than 5 frames appart
        if (end_object_odom.sequence - begin_object_odom.sequence < 5) {
          ObjectOdometryPath interpolated_segment;
          interpolated_segment.colour = colour_msg;
          interpolated_segment.object_id = object_id;
          //-1 for path segment
          interpolated_segment.path_segment = -1;
          interpolated_segment.header = multi_path.header;
          // NOTE: this is not actually interpolating its just going to make
          // RVIZ draw a line between them!!
          interpolated_segment.object_odometries.push_back(begin_object_odom);
          interpolated_segment.object_odometries.push_back(end_object_odom);
          multi_path.paths.push_back(interpolated_segment);
        }
      }
    }
    for (const auto& [_, path] : segmented_paths) {
      multi_path.paths.push_back(path);
    }
  }
  return multi_path;
}
References dyno::GenericObjectCentricMap< VALUE >::at(), constructObjectFrameLink(), constructObjectOdometry(), dyno::convert(), dyno::GenericObjectCentricMap< VALUE >::exists(), dyno::utils::toRosTime(), and dyno::Color::uniqueId().
constructObjectFrameLink()
std::string dyno::DSDTransport::constructObjectFrameLink (ObjectId object_id) static
Construct object id tf link from an object id. This will be used as the link in the ROS tf tree and as the child frame id for the object odometry.
Parameters
object_id ObjectId
Returns
std::string
Definition at line 24 of file DSDCommonRos.cc.
{
  return "object_" + std::to_string(object_id) + "_link";
}
Referenced by constructMultiObjectOdometryPaths(), and constructObjectOdometries().
constructObjectOdometries()
ObjectOdometryMap dyno::DSDTransport::constructObjectOdometries (const ObjectMotionMap & motions, const ObjectPoseMap & poses, FrameId frame_id_k, Timestamp timestamp_k, const std::string & frame_id_link) static
Definition at line 51 of file DSDCommonRos.cc.
{
  // need to get poses for k-1
  // TODO: no way to ensure that the motions are for frame k
  // this is a weird data-structure to use and motions are per frame and
  // ObjectPoseMap is over all k to K
  //  const FrameId frame_id_k_1 = frame_id_k - 1u;
  ObjectOdometryMap object_odom_map;
  for (const auto& [object_id, per_frame_motions] : motions) {
    if (!per_frame_motions.exists(frame_id_k)) {
      // object does not exist at this frame.
      continue;
    }
    const gtsam::Pose3& e_H_k_world = per_frame_motions.at(frame_id_k);
    if (!poses.exists(object_id, frame_id_k)) {
      VLOG(30) << "Cannot construct ObjectOdometry for object " << object_id
               << ", at frame " << frame_id_k
               << " Missing entry in ObjectPoseMap (but object motion "
                  "entry found!!)";
      continue;
    }
    const gtsam::Pose3& pose_k = poses.at(object_id, frame_id_k);
    const std::string child_frame_id_link = constructObjectFrameLink(object_id);
    object_odom_map.insert2(
        child_frame_id_link,
        constructObjectOdometry(e_H_k_world, pose_k, object_id, frame_id_k,
                                timestamp_k, frame_id_link,
                                child_frame_id_link));
  }
  return object_odom_map;
}
References dyno::GenericObjectCentricMap< VALUE >::at(), constructObjectFrameLink(), constructObjectOdometry(), and dyno::GenericObjectCentricMap< VALUE >::exists().
constructObjectOdometry()
ObjectOdometry dyno::DSDTransport::constructObjectOdometry (const gtsam::Pose3 & e_H_k_world, const gtsam::Pose3 & pose_k, ObjectId object_id, FrameId frame_id_k, Timestamp timestamp_k, const std::string & frame_id_link, const std::string & child_frame_id_link) static
Definition at line 28 of file DSDCommonRos.cc.
{
  ObjectOdometry object_odom;
  // technically this shoudl be k-1
  gtsam::Point3 body_velocity = calculateBodyMotion(e_H_k_world, pose_k);
  nav_msgs::msg::Odometry odom_msg;
  utils::convertWithHeader(pose_k, odom_msg, timestamp_k, frame_id_link,
                           child_frame_id_link);
  object_odom.odom = odom_msg;
  // TODO: can check if correct representation?
  dyno::convert(e_H_k_world, object_odom.h_w_km1_k.pose);
  // NO velocity!!
  object_odom.object_id = object_id;
  object_odom.sequence = frame_id_k;
  return object_odom;
}
References dyno::calculateBodyMotion(), dyno::convert(), and dyno::utils::convertWithHeader().
Referenced by constructMultiObjectOdometryPaths(), and constructObjectOdometries().
Member Data Documentation
multi_object_odom_path_publisher_
MultiObjectOdometryPathPub::SharedPtr dyno::DSDTransport::multi_object_odom_path_publisher_ private
Definition at line 209 of file DSDCommonRos.hpp.
Referenced by addObjectInfo(), DSDTransport(), and dyno::DSDTransport::Publisher::publishObjectPaths().
node_
rclcpp::Node::SharedPtr dyno::DSDTransport::node_ private
Definition at line 207 of file DSDCommonRos.hpp.
Referenced by addObjectInfo(), and DSDTransport().
object_odom_publisher_
ObjectOdometryPub::SharedPtr dyno::DSDTransport::object_odom_publisher_ private
Definition at line 208 of file DSDCommonRos.hpp.
Referenced by addObjectInfo(), and DSDTransport().
tf_broadcaster_
std::shared_ptr<tf2_ros::TransformBroadcaster> dyno::DSDTransport::tf_broadcaster_ private
Definition at line 210 of file DSDCommonRos.hpp.
Referenced by addObjectInfo(), DSDTransport(), and dyno::DSDTransport::Publisher::publishObjectTransforms().
The documentation for this class was generated from the following files:
dynosam_ros/include/dynosam_ros/displays/dynamic_slam_displays/DSDCommonRos.hpp
dynosam_ros/src/displays/dynamic_slam_displays/DSDCommonRos.cc