DynoSAM: dyno::VirtualKittiFlowDataFolder Class Reference
dyno::VirtualKittiFlowDataFolder Class Reference
Public Member Functions
VirtualKittiFlowDataFolder (const std::string &path)
cv::Mat getItem (size_t idx) override
Get the Item at an index in the dataset.
Public Member Functions inherited from dyno::GenericVirtualKittiImageLoader
GenericVirtualKittiImageLoader (const std::string &full_path)
std::string getFolderName () const override
Public Member Functions inherited from dyno::DataFolder< cv::Mat >
DataFolder ()=default
virtual ~DataFolder ()
void initAbsolutePath (const fs::path &absolute_folder_path)
Set the Absolute Folder Path object to be used when an item is loaded This needs to be a setter function since we do not know the absolute path at the time of construction.
operator bool () const
Indicates that the absolute folder path has been set correctly with initAbsolutePath Same behaviour as is isAbsolutePathSet but can operate as a boolean operator.
bool isAbsolutePathSet () const
Checks if the absolute path has been set and the data folder is ready to get items.
fs::path getAbsolutePath () const
virtual std::string getFolderName () const=0
virtual cv::Mat getItem (size_t idx)=0
Get the Item at an index in the dataset.
Private Member Functions
cv::Mat vKittiPngToFlow (const std::string &path) const
Additional Inherited Members
Public Types inherited from dyno::DataFolder< cv::Mat >
using This = DataFolder< cv::Mat >
using Type = cv::Mat
Public Attributes inherited from dyno::GenericVirtualKittiImageLoader
const std::string full_path_
Protected Member Functions inherited from dyno::DataFolder< cv::Mat >
virtual void onPathInit ()
Virtual function that is called once the absolute path to this folder is known This happens after construction as the dataset folder (the parent folder) is known by the DataFolderStructure which will set the path on its construction.
Detailed Description
Definition at line 92 of file VirtualKittidataProvider.cc.
Constructor & Destructor Documentation
VirtualKittiFlowDataFolder()
dyno::VirtualKittiFlowDataFolder::VirtualKittiFlowDataFolder (const std::string & path) inline
Definition at line 94 of file VirtualKittidataProvider.cc.
      : GenericVirtualKittiImageLoader(path) {}
Member Function Documentation
getItem()
cv::Mat dyno::VirtualKittiFlowDataFolder::getItem (size_t idx) inline override virtual
Get the Item at an index in the dataset.
The idx should essentually correspond to the frame_id (starting at 0) for this datastream in the dataset.
Parameters
idx
Returns
T
Implements dyno::DataFolder< cv::Mat >.
Definition at line 97 of file VirtualKittidataProvider.cc.
{
    CHECK(idx > 0);
    std::stringstream ss;
    // index at frame -1 so that we get the flow from t-1 to t (where the idx is
    // t)
    ss << std::setfill('0') << std::setw(5) << idx - 1;
    const std::string file_path = full_path_ + "/flow_" + ss.str() + ".png";
    // const std::string file_path = full_path_  + "/backwardFlow_" + ss.str() +
    // ".png"; //specific to backwards flow
    throwExceptionIfPathInvalid(file_path);
    return vKittiPngToFlow(file_path);
  }
References dyno::GenericVirtualKittiImageLoader::full_path_, dyno::throwExceptionIfPathInvalid(), and vKittiPngToFlow().
vKittiPngToFlow()
cv::Mat dyno::VirtualKittiFlowDataFolder::vKittiPngToFlow (const std::string & path) const inline private
Definition at line 116 of file VirtualKittidataProvider.cc.
{
    // cv::Mat bgr = cv::imread(path, cv::IMREAD_ANYCOLOR |
    // cv::IMREAD_ANYDEPTH);
    cv::Mat bgr;
    loadRGB(path, bgr);
    CHECK(!bgr.empty());
    int h = bgr.rows;
    int w = bgr.cols;
    int c = bgr.channels();
    CHECK_EQ(bgr.type(), CV_16UC3) << "type was " << utils::cvTypeToString(bgr);
    CHECK_EQ(c, 3);
    cv::Mat bgr_channels[3];
    cv::split(bgr, bgr_channels);
    cv::Mat b_channel = bgr_channels[0];
    cv::Mat bgr_float;
    // float 32
    bgr.convertTo(bgr_float, CV_32F);
    // scaled to [0;2**16 – 1]
    cv::Mat unscaled_out_flow = 2.0 / (std::pow(2, 16) - 1.0) * bgr_float - 1;
    cv::Mat channels[2];
    // now only take g and r channels
    cv::split(unscaled_out_flow, channels);
    // g,r == flow_y,x normalized by height,width
    cv::Mat& flow_y = channels[1];
    cv::Mat& flow_x = channels[2];
    flow_x *= w - 1.0;
    flow_y *= h - 1.0;
    // re-order channels so x is first and then y
    cv::Mat x_y_ordered_channels[] = {flow_x, flow_y};
    cv::Mat out_flow;
    cv::merge(x_y_ordered_channels, 2, out_flow);
    // b == invalid flow flag == 0 for sky or other invalid flow
    cv::Mat invalid = (b_channel == 0);
    CHECK(!invalid.empty());
    out_flow.setTo(0, invalid);
    out_flow.convertTo(out_flow, CV_32F);
    return out_flow;
  }
References dyno::utils::cvTypeToString(), and dyno::loadRGB().
Referenced by getItem().
The documentation for this class was generated from the following file:
dynosam/src/dataprovider/VirtualKittidataProvider.cc