DynoSAM: dyno::ImageContainer Class Reference
dyno::ImageContainer Class Reference
#include <ImageContainer.hpp>
Public Types
using Base = ImageContainerSubset< ImageType::RGBMono, ImageType::Depth, ImageType::OpticalFlow, ImageType::SemanticMask, ImageType::MotionMask, ImageType::ClassSegmentation >
Public Types inherited from dyno::ImageContainerSubset< ImageType::RGBMono, ImageType::Depth, ImageType::OpticalFlow, ImageType::SemanticMask, ImageType::MotionMask, ImageType::ClassSegmentation >
using This = ImageContainerSubset< ImageTypes... >
using ImageTypesTuple = std::tuple< ImageTypes... >
using WrappedImageTypesTuple = std::tuple< ImageWrapper< ImageTypes >... >
using ImageTypeStruct = std::tuple_element_t< I, ImageTypesTuple >
Alias for an ImageType (eg. RGBMono, Depth etc) which is the Ith element type of the parameter pack ImageTypes...
using WrappedImageTypeStruct = std::tuple_element_t< I, WrappedImageTypesTuple >
Corresponds to an alias for a type ImageWrapper<T> where T is the ImageTypeStruct, eg. RGBMono, Depth... at index I (or simply ImageTypeStruct)
Public Member Functions
auto toBaseSubset (bool clone=false) const
cv::Mat getImage () const
Returns image. Could be RGB or greyscale.
cv::Mat getDepth () const
cv::Mat getOpticalFlow () const
cv::Mat getSemanticMask () const
cv::Mat getMotionMask () const
cv::Mat getClassSegmentation () const
bool isMonocular () const
Returns true if the set of input images does not contain depth and therefore should be used as part of a Monocular VO pipeline.
bool hasDepth () const
bool hasSemanticMask () const
bool hasMotionMask () const
bool hasClassSegmentation () const
bool isImageRGB () const
True if the image has 3 channels and is therefore expected to be RGB. The alternative is greyscale.
Timestamp getTimestamp () const
FrameId getFrameId () const
std::string toString () const
Public Member Functions inherited from dyno::ImageContainerSubset< ImageType::RGBMono, ImageType::Depth, ImageType::OpticalFlow, ImageType::SemanticMask, ImageType::MotionMask, ImageType::ClassSegmentation >
ImageContainerSubset ()
ImageContainerSubset (const ImageWrapper< ImageTypes > &... input_image_wrappers)
virtual ~ImageContainerSubset ()=default
constexpr size_t index () const
Compile time index of the requested ImageType in the container instance.
ImageContainerSubset< SubsetImageTypes... > makeSubset (const bool clone=false) const
This clone () const
bool exists () const
Returns true if the corresponding image corresponding to the requested ImageType exists (i.e is not empty)
cv::Mat get () const
Gets the corresponding image (cv::Mat) corresponding to the requested ImageType. ImageType must be in the class parameter pack (ImageTypes...) or the code will fail to compile.
cv::Mat & get ()
const ImageWrapper< ImageType > & getImageWrapper () const
Gets the corresponding ImageWrapper corresponding to the ImageType. ImageType must be in the class parameter pack (ImageTypes...) or the code will fail to compile.
bool safeGet (cv::Mat &src) const
Safely Gets the corresponding image (cv::Mat) corresponding to the requested ImageType. If the requested image does not exist (empty), false will be returned.
bool cloneImage (cv::Mat &dst) const
Safely clones the corresponding image (cv::Mat) corresponding to the requested ImageType. If the requested image does not exist (empty), false will be returned.
Static Public Member Functions
static ImageContainer::Ptr Create (const Timestamp timestamp, const FrameId frame_id, const ImageWrapper< ImageType::RGBMono > &img, const ImageWrapper< ImageType::Depth > &depth, const ImageWrapper< ImageType::OpticalFlow > &optical_flow, const ImageWrapper< ImageType::SemanticMask > &semantic_mask)
Construct an image container equivalent to RGBD + Semantic Mask input.
static ImageContainer::Ptr Create (const Timestamp timestamp, const FrameId frame_id, const ImageWrapper< ImageType::RGBMono > &img, const ImageWrapper< ImageType::Depth > &depth, const ImageWrapper< ImageType::OpticalFlow > &optical_flow, const ImageWrapper< ImageType::MotionMask > &motion_mask, const ImageWrapper< ImageType::ClassSegmentation > &class_segmentation)
Construct an image container equivalent to RGBD + Motion Mask input.
static ImageContainer::Ptr Create (const Timestamp timestamp, const FrameId frame_id, const ImageWrapper< ImageType::RGBMono > &img, const ImageWrapper< ImageType::Depth > &depth, const ImageWrapper< ImageType::OpticalFlow > &optical_flow, const ImageWrapper< ImageType::MotionMask > &motion_mask)
Construct an image container equivalent to RGBD + Motion Mask input.
static ImageContainer::Ptr RectifyImages (ImageContainer::Ptr images, const UndistorterRectifier &undistorter)
Static Public Member Functions inherited from dyno::ImageContainerSubset< ImageType::RGBMono, ImageType::Depth, ImageType::OpticalFlow, ImageType::SemanticMask, ImageType::MotionMask, ImageType::ClassSegmentation >
static constexpr size_t Index ()
Compile time index of the requested ImageType in the container.
Static Protected Member Functions
static ImageContainer::Ptr Create (const Timestamp timestamp, const FrameId frame_id, const ImageWrapper< ImageType::RGBMono > &img, const ImageWrapper< ImageType::Depth > &depth, const ImageWrapper< ImageType::OpticalFlow > &optical_flow, const ImageWrapper< ImageType::SemanticMask > &semantic_mask, const ImageWrapper< ImageType::MotionMask > &motion_mask, const ImageWrapper< ImageType::ClassSegmentation > &class_segmentation)
Static construction of a full image container and calls validateSetup on the resulting object.
Private Member Functions
ImageContainer (const Timestamp timestamp, const FrameId frame_id, const ImageWrapper< ImageType::RGBMono > &img, const ImageWrapper< ImageType::Depth > &depth, const ImageWrapper< ImageType::OpticalFlow > &optical_flow, const ImageWrapper< ImageType::SemanticMask > &semantic_mask, const ImageWrapper< ImageType::MotionMask > &motion_mask, const ImageWrapper< ImageType::ClassSegmentation > &class_segmentation)
void validateSetup () const override
Validates that the input images (if not empty) are the same size. Throws ImageContainerConstructionException if invalid.
Private Attributes
const Timestamp timestamp_
const FrameId frame_id_
Additional Inherited Members
Static Public Attributes inherited from dyno::ImageContainerSubset< ImageType::RGBMono, ImageType::Depth, ImageType::OpticalFlow, ImageType::SemanticMask, ImageType::MotionMask, ImageType::ClassSegmentation >
static constexpr size_t N
Number of image types contained in this subset.
virtual void validateSetup () const
Validates that the input images (if not empty) are the same size. Throws ImageContainerConstructionException if invalid.
Protected Attributes inherited from dyno::ImageContainerSubset< ImageType::RGBMono, ImageType::Depth, ImageType::OpticalFlow, ImageType::SemanticMask, ImageType::MotionMask, ImageType::ClassSegmentation >
WrappedImageTypesTuple image_storage_
Detailed Description
Definition at line 247 of file ImageContainer.hpp.
Member Typedef Documentation
Base
using dyno::ImageContainer::Base = ImageContainerSubset< ImageType::RGBMono, ImageType::Depth, ImageType::OpticalFlow, ImageType::SemanticMask, ImageType::MotionMask, ImageType::ClassSegmentation>
Definition at line 258 of file ImageContainer.hpp.
Constructor & Destructor Documentation
ImageContainer()
dyno::ImageContainer::ImageContainer (const Timestamp timestamp, const FrameId frame_id, const ImageWrapper< ImageType::RGBMono > & img, const ImageWrapper< ImageType::Depth > & depth, const ImageWrapper< ImageType::OpticalFlow > & optical_flow, const ImageWrapper< ImageType::SemanticMask > & semantic_mask, const ImageWrapper< ImageType::MotionMask > & motion_mask, const ImageWrapper< ImageType::ClassSegmentation > & class_segmentation) explicit private
Definition at line 82 of file ImageContainer.cc.
    :  Base(img, depth, optical_flow, semantic_mask, motion_mask, class_segmentation),
       timestamp_(timestamp),
       frame_id_(frame_id)
    { }
Member Function Documentation
Create() [1/4]
ImageContainer::Ptr dyno::ImageContainer::Create (const Timestamp timestamp, const FrameId frame_id, const ImageWrapper< ImageType::RGBMono > & img, const ImageWrapper< ImageType::Depth > & depth, const ImageWrapper< ImageType::OpticalFlow > & optical_flow, const ImageWrapper< ImageType::MotionMask > & motion_mask) static
Construct an image container equivalent to RGBD + Motion Mask input.
Parameters
timestamp
frame_id
img
depth
optical_flow
motion_mask
Returns
ImageContainer::Ptr
Definition at line 124 of file ImageContainer.cc.
{
    return Create(timestamp, frame_id, img, depth, optical_flow, ImageWrapper<ImageType::SemanticMask>(), motion_mask, ImageWrapper<ImageType::ClassSegmentation>());
}
References Create().
Create() [2/4]
ImageContainer::Ptr dyno::ImageContainer::Create (const Timestamp timestamp, const FrameId frame_id, const ImageWrapper< ImageType::RGBMono > & img, const ImageWrapper< ImageType::Depth > & depth, const ImageWrapper< ImageType::OpticalFlow > & optical_flow, const ImageWrapper< ImageType::MotionMask > & motion_mask, const ImageWrapper< ImageType::ClassSegmentation > & class_segmentation) static
Construct an image container equivalent to RGBD + Motion Mask input.
Parameters
timestamp
frame_id
img
depth
optical_flow
motion_mask
class_segmentation
Returns
ImageContainer::Ptr
Definition at line 136 of file ImageContainer.cc.
{
    return Create(timestamp, frame_id, img, depth, optical_flow, ImageWrapper<ImageType::SemanticMask>(), motion_mask, class_segmentation);
}
References Create().
Create() [3/4]
ImageContainer::Ptr dyno::ImageContainer::Create (const Timestamp timestamp, const FrameId frame_id, const ImageWrapper< ImageType::RGBMono > & img, const ImageWrapper< ImageType::Depth > & depth, const ImageWrapper< ImageType::OpticalFlow > & optical_flow, const ImageWrapper< ImageType::SemanticMask > & semantic_mask) static
Construct an image container equivalent to RGBD + Semantic Mask input.
Parameters
img
depth
optical_flow
semantic_mask
Returns
ImageContainer::Ptr
Definition at line 112 of file ImageContainer.cc.
{
    return Create(timestamp, frame_id, img, depth, optical_flow, semantic_mask, ImageWrapper<ImageType::MotionMask>(), ImageWrapper<ImageType::ClassSegmentation>());
}
References Create().
Referenced by dyno::ClusterSlamDataLoader::ClusterSlamDataLoader(), Create(), dyno::OnlineDataProviderRos::imageSyncCallback(), dyno::KittiDataLoader::KittiDataLoader(), dyno::OMDDataLoader::OMDDataLoader(), dyno::ProjectARIADataLoader::ProjectARIADataLoader(), and dyno::VirtualKittiDataLoader::VirtualKittiDataLoader().
Create() [4/4]
ImageContainer::Ptr dyno::ImageContainer::Create (const Timestamp timestamp, const FrameId frame_id, const ImageWrapper< ImageType::RGBMono > & img, const ImageWrapper< ImageType::Depth > & depth, const ImageWrapper< ImageType::OpticalFlow > & optical_flow, const ImageWrapper< ImageType::SemanticMask > & semantic_mask, const ImageWrapper< ImageType::MotionMask > & motion_mask, const ImageWrapper< ImageType::ClassSegmentation > & class_segmentation) static protected
Static construction of a full image container and calls validateSetup on the resulting object.
Used by each public Create function to construct the underlying ImageContainer. validateSetup must called after construction as it is a virtual function.
Parameters
timestamp
frame_id
img
depth
optical_flow
semantic_mask
motion_mask
class_segmentation
Returns
ImageContainer::Ptr
Definition at line 34 of file ImageContainer.cc.
{
    std::shared_ptr<ImageContainer> container(
        new ImageContainer(
            timestamp,
            frame_id,
            img,
            depth,
            optical_flow,
            semantic_mask,
            motion_mask,
            class_segmentation)
        );
    container->validateSetup();
    return container;
}
getClassSegmentation()
cv::Mat dyno::ImageContainer::getClassSegmentation () const inline
Definition at line 297 of file ImageContainer.hpp.
{ return Base::get<ImageType::ClassSegmentation>(); }
Referenced by hasClassSegmentation().
getDepth()
cv::Mat dyno::ImageContainer::getDepth () const inline
Definition at line 289 of file ImageContainer.hpp.
{ return Base::get<ImageType::Depth>(); }
Referenced by hasDepth().
getFrameId()
FrameId dyno::ImageContainer::getFrameId () const inline
Definition at line 326 of file ImageContainer.hpp.
{ return frame_id_; }
References frame_id_.
Referenced by dyno::KltFeatureTracker::detectFeatures(), dyno::KltFeatureTracker::trackPoints(), and dyno::ExternalFlowFeatureTracker::trackStatic().
getImage()
cv::Mat dyno::ImageContainer::getImage () const inline
Returns image. Could be RGB or greyscale.
Returns
cv::Mat
Definition at line 287 of file ImageContainer.hpp.
{ return Base::get<ImageType::RGBMono>(); }
Referenced by isImageRGB(), and validateSetup().
getMotionMask()
cv::Mat dyno::ImageContainer::getMotionMask () const inline
Definition at line 295 of file ImageContainer.hpp.
{ return Base::get<ImageType::MotionMask>(); }
Referenced by hasMotionMask(), and validateSetup().
getOpticalFlow()
cv::Mat dyno::ImageContainer::getOpticalFlow () const inline
Definition at line 291 of file ImageContainer.hpp.
{ return Base::get<ImageType::OpticalFlow>(); }
Referenced by validateSetup().
getSemanticMask()
cv::Mat dyno::ImageContainer::getSemanticMask () const inline
Definition at line 293 of file ImageContainer.hpp.
{ return Base::get<ImageType::SemanticMask>(); }
Referenced by hasSemanticMask(), and validateSetup().
getTimestamp()
Timestamp dyno::ImageContainer::getTimestamp () const inline
Definition at line 325 of file ImageContainer.hpp.
{ return timestamp_; }
References timestamp_.
hasClassSegmentation()
bool dyno::ImageContainer::hasClassSegmentation () const inline
Definition at line 312 of file ImageContainer.hpp.
{ return !getClassSegmentation().empty(); }
References getClassSegmentation().
Referenced by toString().
hasDepth()
bool dyno::ImageContainer::hasDepth () const inline
Definition at line 309 of file ImageContainer.hpp.
{ return !getDepth().empty(); }
References getDepth().
Referenced by isMonocular(), toString(), and dyno::Frame::updateDepths().
hasMotionMask()
bool dyno::ImageContainer::hasMotionMask () const inline
Definition at line 311 of file ImageContainer.hpp.
{ return !getMotionMask().empty(); }
References getMotionMask().
Referenced by toString(), and validateSetup().
hasSemanticMask()
bool dyno::ImageContainer::hasSemanticMask () const inline
Definition at line 310 of file ImageContainer.hpp.
{ return !getSemanticMask().empty(); }
References getSemanticMask().
Referenced by toString(), and validateSetup().
isImageRGB()
bool dyno::ImageContainer::isImageRGB () const inline
True if the image has 3 channels and is therefore expected to be RGB. The alternative is greyscale.
Returns
true
false
Definition at line 323 of file ImageContainer.hpp.
{ return getImage().channels() == 3; }
References getImage().
Referenced by toString().
isMonocular()
bool dyno::ImageContainer::isMonocular () const inline
Returns true if the set of input images does not contain depth and therefore should be used as part of a Monocular VO pipeline.
Returns
true
false
Definition at line 308 of file ImageContainer.hpp.
{ return !hasDepth(); }
References hasDepth().
RectifyImages()
ImageContainer::Ptr dyno::ImageContainer::RectifyImages (ImageContainer::Ptr images, const UndistorterRectifier & undistorter) static
Definition at line 60 of file ImageContainer.cc.
{
    //do deep copy (the underlying ImageWrapper class has a deep copy in its copy constructor so
    //the image data is cloned)
    ImageContainer::Ptr undistorted_images = std::make_shared<ImageContainer>(*images);
    static constexpr size_t N = ImageContainer::N;
    for (size_t i = 0; i < N; i++) {
        internal::select_apply<N>(i, [&](auto I){
            using ImageType = typename ImageContainer::ImageTypeStruct<I>;
            //get reference to image and modify in place
            //TODO: bug!!?
            cv::Mat& distorted_image = undistorted_images->template get<ImageType>();
            undistorter.undistortRectifyImage(distorted_image, distorted_image);
        });
    }
    return undistorted_images;
}
References dyno::ImageContainerSubset< ImageType::RGBMono, ImageType::Depth, ImageType::OpticalFlow, ImageType::SemanticMask, ImageType::MotionMask, ImageType::ClassSegmentation >::N, and dyno::UndistorterRectifier::undistortRectifyImage().
toBaseSubset()
auto dyno::ImageContainer::toBaseSubset (bool clone = false) const inline
Definition at line 268 of file ImageContainer.hpp.
{
    // auto construct_subset = [&](auto&&... args) { return Base::makeSubset(args..); };
    // return std::apply(construct_subset, subset_wrappers);
    //     return Base::makeSubset<Base::ImageTypesTuple...>(clone);
        return Base::makeSubset<ImageType::RGBMono,
                                ImageType::Depth,
                                ImageType::OpticalFlow,
                                ImageType::SemanticMask,
                                ImageType::MotionMask,
                                ImageType::ClassSegmentation>
                            (clone);
    }
References dyno::ImageContainerSubset< ImageType::RGBMono, ImageType::Depth, ImageType::OpticalFlow, ImageType::SemanticMask, ImageType::MotionMask, ImageType::ClassSegmentation >::clone(), and dyno::ImageContainerSubset< ImageType::RGBMono, ImageType::Depth, ImageType::OpticalFlow, ImageType::SemanticMask, ImageType::MotionMask, ImageType::ClassSegmentation >::makeSubset().
toString()
std::string dyno::ImageContainer::toString () const
Definition at line 97 of file ImageContainer.cc.
{
    std::stringstream ss;
    ss << "Timestamp: " << timestamp_ << "\n";
    ss << "Frame Id: " << frame_id_ << "\n";
    const std::string image_config = isImageRGB() ? "RGB" : "Grey";
    ss << "Configuration: " << image_config
        << " Depth (" << hasDepth() << ") Semantic Mask (" << hasSemanticMask()
        << ") Motion Mask (" << hasMotionMask()
        << ") Class Segmentation (" << hasClassSegmentation() << ")" << "\n";
    return ss.str();
}
References frame_id_, hasClassSegmentation(), hasDepth(), hasMotionMask(), hasSemanticMask(), isImageRGB(), and timestamp_.
validateSetup()
void dyno::ImageContainer::validateSetup () const override private virtual
Validates that the input images (if not empty) are the same size. Throws ImageContainerConstructionException if invalid.
Compares all non-empty images against the first image size
Can be overwritten.
Reimplemented from dyno::ImageContainerSubset< ImageType::RGBMono, ImageType::Depth, ImageType::OpticalFlow, ImageType::SemanticMask, ImageType::MotionMask, ImageType::ClassSegmentation >.
Definition at line 150 of file ImageContainer.cc.
{
    //check image sizes are the same
    Base::validateSetup();
    //TODO: shoudl eventually change to exception
    CHECK(!getImage().empty()) << "RGBMono image must not be empty!";
    CHECK(!getOpticalFlow().empty()) << "OPticalFlow image must not be empty!";
    //must have at least one of semantic mask or motion mask
    CHECK(!getSemanticMask().empty() || !getMotionMask().empty()) << "At least one of the masks (semantic or motion) must be valid. Both are empty";
    //should only provide one mask (for clarity - which one to use if both given?)
    if(hasSemanticMask()) {
        CHECK(!hasMotionMask()) << "Semantic mask has been provided, so motion mask should be empty!";
    }
    if(hasMotionMask()) {
        CHECK(!hasSemanticMask()) << "Motion mask has been provided, so semantic mask should be empty!";
    }
}
References getImage(), getMotionMask(), getOpticalFlow(), getSemanticMask(), hasMotionMask(), hasSemanticMask(), and dyno::ImageContainerSubset< ImageType::RGBMono, ImageType::Depth, ImageType::OpticalFlow, ImageType::SemanticMask, ImageType::MotionMask, ImageType::ClassSegmentation >::validateSetup().
Member Data Documentation
frame_id_
const FrameId dyno::ImageContainer::frame_id_ private
Definition at line 436 of file ImageContainer.hpp.
Referenced by getFrameId(), and toString().
timestamp_
const Timestamp dyno::ImageContainer::timestamp_ private
Definition at line 435 of file ImageContainer.hpp.
Referenced by getTimestamp(), and toString().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/common/ImageContainer.hpp
dynosam/src/common/ImageContainer.cc