DynoSAM: dyno::Spinner Class Reference
dyno::Spinner Class Reference
Class to handle the calling of a function within a thread. The spinner launches its own thread for each instance and is non-blocking.
#include <Spinner.hpp>
Public Types
using Evoke = std::function< void()>
Public Member Functions
Spinner (Evoke func, const std::string &name, bool auto_start=true)
Construct a new Spinner given a function which is blocking (ie. has a loop within the function method itself)
virtual ~Spinner ()
void start ()
Starts the function in a thread. If the spinner has already been started (i.e from auto_start), this function will do nothing. Non-blocking call.
virtual void shutdown ()
Shutdown the spinner - once stopped cannot be restarted. Used to ensure the thread closes safely. Be careful to avoid a race condition where you try and shutdown the spinner but your functional loop has not exited yet (depending on its condition) - in this case the shutdown function will block indefinitely.
bool isRunning () const
Checks if the thread is running. As much thread safety has been used to ensure that this bool is accurate.
Private Attributes
Evoke func_
const std::string name_
std::unique_ptr< std::thread > spin_thread_ { nullptr }
std::atomic< bool > is_running_ { false }
Detailed Description
Class to handle the calling of a function within a thread. The spinner launches its own thread for each instance and is non-blocking.
This version of the class expects the Evoke function to be within a while loop itself as the class will simply bind this to a thread and execute it. See LoopingSpinner to for a spinOnce style evoke function call.
Definition at line 49 of file Spinner.hpp.
Member Typedef Documentation
Evoke
using dyno::Spinner::Evoke = std::function<void()>
Definition at line 53 of file Spinner.hpp.
Constructor & Destructor Documentation
Spinner()
dyno::Spinner::Spinner (Evoke func, const std::string & name, bool auto_start = true) explicit
Construct a new Spinner given a function which is blocking (ie. has a loop within the function method itself)
Name is just used as a logging identifier. If auso start is true, the function will be envoked.
Parameters
func Evoke
name const std::string&
auto_start bool. Defaults to true
Definition at line 35 of file Spinner.cc.
                                                                   : func_(func), name_(name)
{
  VLOG(10) << "Creating spinner - " << name;
  if (auto_start)
  {
    VLOG(10) << "Auto starting spinner - " << name;
    start();
  }
}
References start().
~Spinner()
dyno::Spinner::~Spinner () virtual
Definition at line 46 of file Spinner.cc.
{
  shutdown();
}
References shutdown().
Member Function Documentation
isRunning()
bool dyno::Spinner::isRunning () const inline
Checks if the thread is running. As much thread safety has been used to ensure that this bool is accurate.
Returns
true
false
Definition at line 89 of file Spinner.hpp.
{
    return is_running_;
  }
References is_running_.
shutdown()
void dyno::Spinner::shutdown () virtual
Shutdown the spinner - once stopped cannot be restarted. Used to ensure the thread closes safely. Be careful to avoid a race condition where you try and shutdown the spinner but your functional loop has not exited yet (depending on its condition) - in this case the shutdown function will block indefinitely.
Reimplemented in dyno::LoopingSpinner.
Definition at line 60 of file Spinner.cc.
{
  if (spin_thread_ && spin_thread_->joinable())
  {
    VLOG(10) << "Spinner " << name_ << " shutting down";
    spin_thread_->join();
    is_running_ = false;
  }
  else
  {
    // VLOG(10) << "Spinner " << name_ << "already shutdown";
  }
}
References is_running_, name_, and spin_thread_.
Referenced by dyno::LoopingSpinner::shutdown(), and ~Spinner().
start()
void dyno::Spinner::start ()
Starts the function in a thread. If the spinner has already been started (i.e from auto_start), this function will do nothing. Non-blocking call.
Definition at line 51 of file Spinner.cc.
{
  if(!is_running_) {
    spin_thread_ = std::make_unique<std::thread>(func_);
    is_running_ = true;
  }
}
References func_, is_running_, and spin_thread_.
Referenced by dyno::LoopingSpinner::LoopingSpinner(), and Spinner().
Member Data Documentation
func_
Evoke dyno::Spinner::func_ private
Definition at line 94 of file Spinner.hpp.
Referenced by start().
is_running_
std::atomic<bool> dyno::Spinner::is_running_ { false } private
Definition at line 98 of file Spinner.hpp.
Referenced by isRunning(), shutdown(), and start().
name_
const std::string dyno::Spinner::name_ private
Definition at line 95 of file Spinner.hpp.
Referenced by shutdown().
spin_thread_
std::unique_ptr<std::thread> dyno::Spinner::spin_thread_ { nullptr } private
Definition at line 97 of file Spinner.hpp.
Referenced by shutdown(), and start().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/utils/Spinner.hpp
dynosam/src/utils/Spinner.cc