DynoSAM: dyno::JsonConverter Class Reference
dyno::JsonConverter Class Reference
#include <Logger.hpp>
Public Types
enum Format { NORMAL , BSON }
using json = nlohmann::json
Static Public Member Functions
template<typename T >
static void WriteOutJson (const T &value, const std::string &filepath, const Format &fmt=Format::BSON, bool append=false)
template<typename T >
static bool ReadInJson (T &value, const std::string &filepath, const Format &fmt=Format::BSON)
Static Private Member Functions
template<typename T >
static void WriteBson (const T &value, const std::string &filepath, bool append)
template<typename T >
static bool ReadBson (T &value, const std::string &filepath)
Detailed Description
Definition at line 165 of file Logger.hpp.
Member Typedef Documentation
json
using dyno::JsonConverter::json = nlohmann::json
Definition at line 167 of file Logger.hpp.
Member Enumeration Documentation
Format
enum dyno::JsonConverter::Format
Enumerator
NORMAL
BSON
Definition at line 169 of file Logger.hpp.
{ NORMAL, BSON };
Member Function Documentation
ReadBson()
template<typename T > static bool dyno::JsonConverter::ReadBson (T & value, const std::string & filepath) inline static private
Definition at line 216 of file Logger.hpp.
{
    VLOG(5) << "Reading bson data from filepath: " << filepath;
    std::ifstream file(filepath, std::ios::binary);
    if (!file.is_open()) {
      return false;
    }
    // Get the size of the file
    file.seekg(0, std::ios::end);
    const std::streamsize file_size = file.tellg();
    file.seekg(0, std::ios::beg);
    // Create a vector to store the file content
    std::vector<std::uint8_t> content;
    content.reserve(file_size);  // Reserve space to avoid reallocation
    // Read the file content into the vector
    content.insert(content.begin(), std::istreambuf_iterator<char>(file),
                   std::istreambuf_iterator<char>());
    const json json_instance_read = json::from_bson(content);
    value = json_instance_read["data"].template get<T>();
    return true;
  }
Referenced by ReadInJson().
ReadInJson()
template<typename T > static bool dyno::JsonConverter::ReadInJson (T & value, const std::string & filepath, const Format & fmt = Format::BSON) inline static
Definition at line 184 of file Logger.hpp.
{
    if (fmt == Format::BSON) {
      return ReadBson(value, filepath);
    } else {
      CHECK(false) << "normal json not implemented";
    }
  }
References BSON, and ReadBson().
Referenced by dyno::FrontendOfflinePipeline< MODULE_TRAITS >::FrontendOfflinePipeline().
WriteBson()
template<typename T > static void dyno::JsonConverter::WriteBson (const T & value, const std::string & filepath, bool append) inline static private
Definition at line 195 of file Logger.hpp.
{
    VLOG(5) << "Writing bson data to filepath: " << filepath;
    json j;
    j["data"] = value;
    auto v_bson = json::to_bson(j);
    std::ofstream bsonfile;
    if (!append) {
      bsonfile.open(filepath.c_str(), std::ios_base::out | std::ios::binary);
    } else {
      bsonfile.open(filepath.c_str(),
                    std::ios_base::app | std::ios_base::out | std::ios::binary);
    }
    bsonfile.write((char*)&v_bson[0], v_bson.size() * sizeof(v_bson[0]));
    bsonfile.close();
  }
WriteOutJson()
template<typename T > static void dyno::JsonConverter::WriteOutJson (const T & value, const std::string & filepath, const Format & fmt = Format::BSON, bool append = false) inline static
Definition at line 173 of file Logger.hpp.
{
    if (fmt == Format::BSON) {
      WriteBson<T>(value, filepath, append);
    } else {
      CHECK(false) << "normal json not implemented";
    }
  }
References BSON.
Referenced by dyno::ParallelHybridBackendModule::~ParallelHybridBackendModule(), dyno::RGBDFrontendLogger::~RGBDFrontendLogger(), and dyno::RGBDInstanceFrontendModule::~RGBDInstanceFrontendModule().
The documentation for this class was generated from the following file:
dynosam/include/dynosam/logger/Logger.hpp