DynoSAM: rangetree< point, data > Class Template Reference
rangetree< point, data > Class Template Reference
#include <ranget.h>
Classes
struct node
struct ptx
struct pty
Public Member Functions
rangetree (u32 estimatedTotal=1000, u32 estimatedResult=100)
~rangetree ()
int add (point x, point y, data *const ptr)
void finalize ()
u32 count (point xmin, point xmax, point ymin, point ymax) const
std::vector< data * > * search (point xmin, point xmax, point ymin, point ymax) const
void search (data **const arr, u32 &arrsize, point xmin, point xmax, point ymin, point ymax) const
Static Public Member Functions
static const char * version ()
Private Member Functions
u32 binarynext (const pty *const arr, const u32 ycount, const point goal) const
u32 binarynextx (const std::vector< ptx > &arr, const point goal) const
void build ()
node * build (const point min, const point max)
void nuke ()
void nuke (node *const n)
void findnodes (const node *const n, const point xmin, const point xmax, const node *list[], u32 &listcur) const
void mergekids (pty *&arr, u32 &ycount, node *const __restrict__ left, node *const __restrict__ right) const
void initpools (const u32 totalcount, const point maxrange)
node * newnode ()
pty * newpty (const u32 num) const
bool isnodepooled (const node *const n) const
bool isptypooled (const pty *const p) const
u32 u32min (const u32 a, const u32 b) const
void pswap (point &__restrict__ a, point &__restrict__ b) const
void * xcalloc (const size_t nmemb, const size_t size) const
Private Attributes
std::vector< ptx > xtmparray
std::vector< pty > ytmparray
u32 totalsize
node start
node * nodepool
u32 nodepoolcount
u32 nodepoolgiven
pty * ptypool
u32 ptypoolcount
u32 ptypoolgiven
u32 maxterminals
u32 mainreserve
u32 resultreserve
bool init
Detailed Description
template<class point, class data>
class rangetree< point, data >
Definition at line 50 of file ranget.h.
Constructor & Destructor Documentation
rangetree()
template<class point , class data > rangetree< point, data >::rangetree (u32 estimatedTotal = 1000, u32 estimatedResult = 100) inline
Definition at line 53 of file ranget.h.
                                                                   :
        nodepool(NULL), ptypool(NULL),
        mainreserve(estimatedTotal), resultreserve(estimatedResult), init(false) {
        xtmparray.reserve(mainreserve);
        ytmparray.reserve(mainreserve);
#ifdef LESSRAM64
        dataset = NULL;
#endif
    }
References rangetree< point, data >::mainreserve, rangetree< point, data >::xtmparray, and rangetree< point, data >::ytmparray.
~rangetree()
template<class point , class data > rangetree< point, data >::~rangetree () inline
Definition at line 65 of file ranget.h.
                 {
        nuke();
        delete [] nodepool;
        free(ptypool);
#ifdef LESSRAM64
        free(dataset);
#endif
    }
References rangetree< point, data >::nodepool, rangetree< point, data >::nuke(), and rangetree< point, data >::ptypool.
Member Function Documentation
add()
template<class point , class data > int rangetree< point, data >::add (point x, point y, data *const ptr) inline
Definition at line 74 of file ranget.h.
{
        if (init)
            return 1;
        ptx px;
        pty py;
        px.x = x;
        px.y = py.y = y;
        px.ptr = ptr;
#ifndef LESSRAM64
        py.ptr = ptr;
#else
        py.offset = -1;
#endif
        xtmparray.push_back(px);
        ytmparray.push_back(py);
        return 0;
    }
References rangetree< point, data >::init, rangetree< point, data >::ptx::ptr, rangetree< point, data >::ptx::x, rangetree< point, data >::xtmparray, rangetree< point, data >::ptx::y, and rangetree< point, data >::ytmparray.
binarynext()
template<class point , class data > u32 rangetree< point, data >::binarynext (const pty *const arr, const u32 ycount, const point goal) const inline private
Definition at line 319 of file ranget.h.
{
        if (ycount == 0)
            return 0;
        const u32 max = ycount - 1;
        // These have to be signed to avoid overflow. s64 to contain u32.
        s64 t, left = 0, right = max;
        do {
            t = (left + right) / 2;
            if (goal < arr[t].y)
                right = t - 1;
            else
                left = t + 1;
        } while (left <= right && goal != arr[t].y);
        // We might've landed in the middle. Linearly get the earliest.
        if (arr[t].y == goal) {
            while (t && arr[t-1].y == goal)
                t--;
            return t;
        }
        if (arr[t].y < goal)
            return t + 1;
        return t;
    }
Referenced by rangetree< point, data >::count(), and rangetree< point, data >::search().
binarynextx()
template<class point , class data > u32 rangetree< point, data >::binarynextx (const std::vector< ptx > & arr, const point goal) const inline private
Definition at line 353 of file ranget.h.
{
        if (arr.size() == 0)
            return 0;
        const u32 max = arr.size() - 1;
        // These have to be signed to avoid overflow. s64 to contain u32.
        s64 t, left = 0, right = max;
        do {
            t = (left + right) / 2;
            if (goal < arr[t].x)
                right = t - 1;
            else
                left = t + 1;
        } while (left <= right && goal != arr[t].x);
        // We might've landed in the middle. Linearly get the earliest.
        if (arr[t].x == goal) {
            while (t && arr[t-1].x == goal)
                t--;
            return t;
        }
        if (arr[t].x < goal)
            return t + 1;
        return t;
    }
Referenced by rangetree< point, data >::build().
build() [1/2]
template<class point , class data > void rangetree< point, data >::build () inline private
Definition at line 386 of file ranget.h.
                 {
        if (totalsize < 1) {
            return;
        }
#ifndef LESSRAM64
        start.ypoints = (pty *) xcalloc(totalsize, sizeof(pty));
        memcpy(start.ypoints, &ytmparray[0], totalsize * sizeof(pty));
        start.ycount = totalsize;
#endif
        ytmparray.clear();
        const u32 medianidx = totalsize / 2;
        const point median = xtmparray[medianidx].x;
        start.min = xtmparray[0].x;
        start.max = xtmparray[totalsize - 1].x;
        // Ok, divide it between everyone
        start.left = build(start.min, median);
        // If it's really small, it may not have a right branch..
        if (median != start.max)
            start.right = build(median + 1, start.max);
#ifdef LESSRAM64
        mergekids(start.ypoints, start.ycount, start.left, start.right);
#endif
    }
References rangetree< point, data >::build(), rangetree< point, data >::node::left, rangetree< point, data >::node::max, rangetree< point, data >::mergekids(), rangetree< point, data >::node::min, rangetree< point, data >::node::right, rangetree< point, data >::start, rangetree< point, data >::totalsize, rangetree< point, data >::xcalloc(), rangetree< point, data >::xtmparray, rangetree< point, data >::node::ycount, rangetree< point, data >::node::ypoints, and rangetree< point, data >::ytmparray.
Referenced by rangetree< point, data >::build(), and rangetree< point, data >::finalize().
build() [2/2]
template<class point , class data > node * rangetree< point, data >::build (const point min, const point max) inline private
Definition at line 415 of file ranget.h.
{
//      if (min > max)
//          abort();
        const u32 lower = binarynextx(xtmparray, min);
        const u32 upper = binarynextx(xtmparray, max + 1);
        // Quick check: if nothing below me, no need to create anything below
        if (lower == upper) {
            return NULL;
        }
        node * const n = newnode();
        n->min = xtmparray[lower].x;
        n->max = xtmparray[upper-1].x;
        // If no kids, create the array; otherwise, recurse
        if (n->min == n->max) {
            const u32 size = upper - lower;
            n->ypoints = newpty(size);
            u32 i;
            for (i = 0; i < size; i++) {
#ifdef LESSRAM64
                n->ypoints[i].offset = lower + i;
#else
                n->ypoints[i].ptr = xtmparray[lower + i].ptr;
#endif
                n->ypoints[i].y = xtmparray[lower + i].y;
            }
            n->ycount = size;
            std::sort(n->ypoints, n->ypoints + size);
        } else {
            const u32 median = (n->min + n->max) / 2;
            n->left = build(n->min, median);
            n->right = build(median + 1, n->max);
            // For faster builds, we merge our kids' arrays into ours
            mergekids(n->ypoints, n->ycount, n->left, n->right);
        }
        return n;
    }
References rangetree< point, data >::binarynextx(), rangetree< point, data >::build(), rangetree< point, data >::node::left, rangetree< point, data >::node::max, rangetree< point, data >::mergekids(), rangetree< point, data >::node::min, rangetree< point, data >::newnode(), rangetree< point, data >::newpty(), rangetree< point, data >::pty::ptr, rangetree< point, data >::node::right, rangetree< point, data >::xtmparray, rangetree< point, data >::pty::y, rangetree< point, data >::node::ycount, and rangetree< point, data >::node::ypoints.
count()
template<class point , class data > u32 rangetree< point, data >::count (point xmin, point xmax, point ymin, point ymax) const inline
Definition at line 123 of file ranget.h.
{
        if (!init)
            return 0;
        // If needed, swap arguments
        if (xmax < xmin)
            pswap(xmax, xmin);
        if (ymax < ymin)
            pswap(ymax, ymin);
        u32 sum = 0;
        const node * list[maxterminals];
        u32 listcur = 0;
        findnodes(&start, xmin, xmax, list, listcur);
        const u32 ncount = listcur;
        for (u32 k = 0; k < ncount; k++) {
            const node * const n = list[k];
            const u32 max = n->ycount;
            if (!max)
                continue;
            const u32 lower = binarynext(n->ypoints, n->ycount, ymin);
            const u32 upper = binarynext(n->ypoints, n->ycount, ymax + 1);
            sum += upper - lower;
        }
        return sum;
    }
References rangetree< point, data >::binarynext(), rangetree< point, data >::findnodes(), rangetree< point, data >::init, rangetree< point, data >::maxterminals, rangetree< point, data >::pswap(), rangetree< point, data >::start, rangetree< point, data >::node::ycount, and rangetree< point, data >::node::ypoints.
finalize()
template<class point , class data > void rangetree< point, data >::finalize () inline
Definition at line 97 of file ranget.h.
                    {
        totalsize = ytmparray.size();
        std::sort(xtmparray.begin(), xtmparray.end());
        std::sort(ytmparray.begin(), ytmparray.end());
#ifdef LESSRAM64
        dataset = (data **) xcalloc(totalsize, sizeof(data *));
        for (u32 i = 0; i < totalsize; i++) {
            dataset[i] = xtmparray[i].ptr;
        }
#endif
        const point maxrange = (xtmparray[totalsize-1].x - xtmparray[0].x) + 1;
        initpools(totalsize, maxrange);
        build();
        xtmparray.clear();
        // Must be last
        init = true;
    }
References rangetree< point, data >::build(), rangetree< point, data >::init, rangetree< point, data >::initpools(), rangetree< point, data >::totalsize, rangetree< point, data >::xcalloc(), rangetree< point, data >::xtmparray, and rangetree< point, data >::ytmparray.
findnodes()
template<class point , class data > void rangetree< point, data >::findnodes (const node *const n, const point xmin, const point xmax, const node * list[], u32 & listcur) const inline private
Definition at line 491 of file ranget.h.
{
        if (!n)
            return;
        // Fast outs
        if (xmin > n->max)
            return;
        if (xmax < n->min)
            return;
        if (!n->ycount)
            return;
        // Prefetch nodes to cache
        fetch(n->left);
        fetch(n->right);
        if (xmin <= n->min && xmax >= n->max) {
            list[listcur] = n;
            listcur++;
//          if (listcur >= maxterminals)
//              abort();
            return;
        }
        findnodes(n->left, xmin, xmax, list, listcur);
        findnodes(n->right, xmin, xmax, list, listcur);
    }
References fetch, rangetree< point, data >::findnodes(), rangetree< point, data >::node::left, rangetree< point, data >::node::max, rangetree< point, data >::node::right, and rangetree< point, data >::node::ycount.
Referenced by rangetree< point, data >::count(), rangetree< point, data >::findnodes(), and rangetree< point, data >::search().
initpools()
template<class point , class data > void rangetree< point, data >::initpools (const u32 totalcount, const point maxrange) inline private
Definition at line 603 of file ranget.h.
{
        const u32 amount = u32min(totalcount, maxrange);
        // If we have N points, the likely amount of nodes is 2N - 1.
        nodepoolcount = amount*2;
        nodepoolgiven = 0;
        const u32 log2ed = log2f(nodepoolcount) + 1;
        // Pre-allocate n*log(n) ptys
        ptypoolcount = totalcount * log2ed;
        ptypoolgiven = 0;
        // Given the estimated max, we can calculate the max number
        // of terminal nodes - it's at most 2 per level (proof in the papers).
        maxterminals = log2ed;
        maxterminals *= 2;
        nodepool = new node[nodepoolcount];
        ptypool = (pty *) xcalloc(ptypoolcount, sizeof(pty));
    }
References rangetree< point, data >::maxterminals, rangetree< point, data >::nodepool, rangetree< point, data >::nodepoolcount, rangetree< point, data >::nodepoolgiven, rangetree< point, data >::ptypool, rangetree< point, data >::ptypoolcount, rangetree< point, data >::ptypoolgiven, rangetree< point, data >::u32min(), and rangetree< point, data >::xcalloc().
Referenced by rangetree< point, data >::finalize().
isnodepooled()
template<class point , class data > bool rangetree< point, data >::isnodepooled (const node *const n) const inline private
Definition at line 646 of file ranget.h.
{
        if (!nodepool)
            return false;
        if (n >= &nodepool[0] && n <= &nodepool[nodepoolcount - 1])
            return true;
        return false;
    }
References rangetree< point, data >::nodepool, and rangetree< point, data >::nodepoolcount.
Referenced by rangetree< point, data >::nuke().
isptypooled()
template<class point , class data > bool rangetree< point, data >::isptypooled (const pty *const p) const inline private
Definition at line 656 of file ranget.h.
{
        if (!ptypool)
            return false;
        if (p >= &ptypool[0] && p <= &ptypool[ptypoolcount - 1])
            return true;
        return false;
    }
References rangetree< point, data >::ptypool, and rangetree< point, data >::ptypoolcount.
Referenced by rangetree< point, data >::nuke().
mergekids()
template<class point , class data > void rangetree< point, data >::mergekids (pty *& arr, u32 & ycount, node *const __restrict__ left, node *const __restrict__ right) const inline private
Definition at line 522 of file ranget.h.
{
        u32 l, r;
        const u32 lmax = left ? left->ycount : 0;
        const u32 rmax = right ? right->ycount : 0;
        arr = newpty(lmax + rmax);
        ycount = lmax + rmax;
        u32 cur = 0;
        for (l = 0, r = 0; l < lmax || r < rmax;) {
            // Special cases first: if one array is out
            if (l == lmax) {
                memcpy(&arr[cur], &right->ypoints[r],
                    (rmax - r) * sizeof(pty));
                break;
            } else if (r == rmax) {
                memcpy(&arr[cur], &left->ypoints[l],
                    (lmax - l) * sizeof(pty));
                break;
            } else {
                if (left->ypoints[l].y <= right->ypoints[r].y) {
                    arr[cur] = left->ypoints[l];
                    cur++;
                    l++;
                } else {
                    arr[cur] = right->ypoints[r];
                    cur++;
                    r++;
                }
            }
        }
    }
References rangetree< point, data >::newpty().
Referenced by rangetree< point, data >::build().
newnode()
template<class point , class data > node * rangetree< point, data >::newnode () inline private
Definition at line 626 of file ranget.h.
                     {
        if (nodepoolgiven < nodepoolcount) {
            node * const out = &nodepool[nodepoolgiven];
            nodepoolgiven++;
            return out;
        } else {
            return new node;
        }
    }
References rangetree< point, data >::nodepool, rangetree< point, data >::nodepoolcount, and rangetree< point, data >::nodepoolgiven.
Referenced by rangetree< point, data >::build().
newpty()
template<class point , class data > pty * rangetree< point, data >::newpty (const u32 num) const inline private
Definition at line 636 of file ranget.h.
{
        if (ptypoolgiven + num <= ptypoolcount) {
            pty * const out = &ptypool[ptypoolgiven];
            ptypoolgiven += num;
            return out;
        } else {
            return (pty *) xcalloc(num, sizeof(pty));
        }
    }
References rangetree< point, data >::ptypool, rangetree< point, data >::ptypoolcount, rangetree< point, data >::ptypoolgiven, and rangetree< point, data >::xcalloc().
Referenced by rangetree< point, data >::build(), and rangetree< point, data >::mergekids().
nuke() [1/2]
template<class point , class data > void rangetree< point, data >::nuke () inline private
Definition at line 466 of file ranget.h.
                {
        nuke(start.left);
        nuke(start.right);
        if (!isptypooled(start.ypoints))
            delete start.ypoints;
            //free(start.ypoints);
    }
References rangetree< point, data >::isptypooled(), rangetree< point, data >::node::left, rangetree< point, data >::nuke(), rangetree< point, data >::node::right, rangetree< point, data >::start, and rangetree< point, data >::node::ypoints.
Referenced by rangetree< point, data >::nuke(), and rangetree< point, data >::~rangetree().
nuke() [2/2]
template<class point , class data > void rangetree< point, data >::nuke (node *const n) inline private
Definition at line 475 of file ranget.h.
{
        if (!n)
            return;
        nuke(n->left);
        nuke(n->right);
        if (!isptypooled(n->ypoints))
            delete n->ypoints;
            //free(n->ypoints);
        if (!isnodepooled(n))
            delete n;
    }
References rangetree< point, data >::isnodepooled(), rangetree< point, data >::isptypooled(), rangetree< point, data >::node::left, rangetree< point, data >::nuke(), rangetree< point, data >::node::right, and rangetree< point, data >::node::ypoints.
pswap()
template<class point , class data > void rangetree< point, data >::pswap (point &__restrict__ a, point &__restrict__ b) const inline private
Definition at line 673 of file ranget.h.
{
        point tmp = a;
        a = b;
        b = tmp;
    }
Referenced by rangetree< point, data >::count(), and rangetree< point, data >::search().
search() [1/2]
template<class point , class data > void rangetree< point, data >::search (data **const arr, u32 & arrsize, point xmin, point xmax, point ymin, point ymax) const inline
Definition at line 198 of file ranget.h.
{
        if (!init)
            return;
        // If needed, swap arguments
        if (xmax < xmin)
            pswap(xmax, xmin);
        if (ymax < ymin)
            pswap(ymax, ymin);
        const node * list[maxterminals];
        u32 listcur = 0;
        findnodes(&start, xmin, xmax, list, listcur);
        const u32 ncount = listcur;
        u32 cur = 0;
        const u32 arrmax = arrsize;
        for (u32 k = 0; k < ncount; k++) {
            const node * const n = list[k];
            const u32 max = n->ycount;
            if (!max)
                continue;
            const u32 lower = binarynext(n->ypoints, n->ycount, ymin);
            const u32 upper = binarynext(n->ypoints, n->ycount, ymax + 1);
            for (u32 i = lower; i < upper; i++) {
                    if (cur < arrmax) {
#ifdef LESSRAM64
                        arr[cur] = dataset[n->ypoints[i].offset];
#else
                        arr[cur] = n->ypoints[i].ptr;
#endif
                    }
                    cur++;
            }
        }
        arrsize = cur;
    }
References rangetree< point, data >::binarynext(), rangetree< point, data >::findnodes(), rangetree< point, data >::init, rangetree< point, data >::maxterminals, rangetree< point, data >::pswap(), rangetree< point, data >::pty::ptr, rangetree< point, data >::start, rangetree< point, data >::node::ycount, and rangetree< point, data >::node::ypoints.
search() [2/2]
template<class point , class data > std::vector< data * > * rangetree< point, data >::search (point xmin, point xmax, point ymin, point ymax) const inline
Definition at line 157 of file ranget.h.
{
        if (!init)
            return NULL;
        // If needed, swap arguments
        if (xmax < xmin)
            pswap(xmax, xmin);
        if (ymax < ymin)
            pswap(ymax, ymin);
        std::vector<data *> * const res = new std::vector<data *>;
        res->reserve(resultreserve);
        const node * list[maxterminals];
        u32 listcur = 0;
        findnodes(&start, xmin, xmax, list, listcur);
        const u32 ncount = listcur;
        for (u32 k = 0; k < ncount; k++) {
            const node * const n = list[k];
            const u32 max = n->ycount;
            if (!max)
                continue;
            const u32 lower = binarynext(n->ypoints, n->ycount, ymin);
            const u32 upper = binarynext(n->ypoints, n->ycount, ymax + 1);
            for (u32 i = lower; i < upper; i++) {
#ifdef LESSRAM64
                    res->push_back(dataset[n->ypoints[i].offset]);
#else
                    res->push_back(n->ypoints[i].ptr);
#endif
            }
        }
        return res;
    }
References rangetree< point, data >::binarynext(), rangetree< point, data >::findnodes(), rangetree< point, data >::init, rangetree< point, data >::maxterminals, rangetree< point, data >::pswap(), rangetree< point, data >::pty::ptr, rangetree< point, data >::resultreserve, rangetree< point, data >::start, rangetree< point, data >::node::ycount, and rangetree< point, data >::node::ypoints.
u32min()
template<class point , class data > u32 rangetree< point, data >::u32min (const u32 a, const u32 b) const inline private
Definition at line 667 of file ranget.h.
{
        if (a < b)
            return a;
        return b;
    }
Referenced by rangetree< point, data >::initpools().
version()
template<class point , class data > static const char * rangetree< point, data >::version () inline static
Definition at line 244 of file ranget.h.
{
        return "librangetree 1.3.1";
    }
xcalloc()
template<class point , class data > void * rangetree< point, data >::xcalloc (const size_t nmemb, const size_t size) const inline private
Definition at line 679 of file ranget.h.
{
        void * const ptr = calloc(nmemb, size);
        if (!ptr)
            abort();
        return ptr;
    }
Referenced by rangetree< point, data >::build(), rangetree< point, data >::finalize(), rangetree< point, data >::initpools(), and rangetree< point, data >::newpty().
Member Data Documentation
init
template<class point , class data > bool rangetree< point, data >::init private
Definition at line 707 of file ranget.h.
Referenced by rangetree< point, data >::add(), rangetree< point, data >::count(), rangetree< point, data >::finalize(), and rangetree< point, data >::search().
mainreserve
template<class point , class data > u32 rangetree< point, data >::mainreserve private
Definition at line 706 of file ranget.h.
Referenced by rangetree< point, data >::rangetree().
maxterminals
template<class point , class data > u32 rangetree< point, data >::maxterminals private
Definition at line 704 of file ranget.h.
Referenced by rangetree< point, data >::count(), rangetree< point, data >::initpools(), and rangetree< point, data >::search().
nodepool
template<class point , class data > node* rangetree< point, data >::nodepool private
Definition at line 696 of file ranget.h.
Referenced by rangetree< point, data >::initpools(), rangetree< point, data >::isnodepooled(), rangetree< point, data >::newnode(), and rangetree< point, data >::~rangetree().
nodepoolcount
template<class point , class data > u32 rangetree< point, data >::nodepoolcount private
Definition at line 697 of file ranget.h.
Referenced by rangetree< point, data >::initpools(), rangetree< point, data >::isnodepooled(), and rangetree< point, data >::newnode().
nodepoolgiven
template<class point , class data > u32 rangetree< point, data >::nodepoolgiven private
Definition at line 698 of file ranget.h.
Referenced by rangetree< point, data >::initpools(), and rangetree< point, data >::newnode().
ptypool
template<class point , class data > pty* rangetree< point, data >::ptypool private
Definition at line 700 of file ranget.h.
Referenced by rangetree< point, data >::initpools(), rangetree< point, data >::isptypooled(), rangetree< point, data >::newpty(), and rangetree< point, data >::~rangetree().
ptypoolcount
template<class point , class data > u32 rangetree< point, data >::ptypoolcount private
Definition at line 701 of file ranget.h.
Referenced by rangetree< point, data >::initpools(), rangetree< point, data >::isptypooled(), and rangetree< point, data >::newpty().
ptypoolgiven
template<class point , class data > u32 rangetree< point, data >::ptypoolgiven mutable private
Definition at line 702 of file ranget.h.
Referenced by rangetree< point, data >::initpools(), and rangetree< point, data >::newpty().
resultreserve
template<class point , class data > u32 rangetree< point, data >::resultreserve private
Definition at line 706 of file ranget.h.
Referenced by rangetree< point, data >::search().
start
template<class point , class data > node rangetree< point, data >::start private
Definition at line 694 of file ranget.h.
Referenced by rangetree< point, data >::build(), rangetree< point, data >::count(), rangetree< point, data >::nuke(), and rangetree< point, data >::search().
totalsize
template<class point , class data > u32 rangetree< point, data >::totalsize private
Definition at line 692 of file ranget.h.
Referenced by rangetree< point, data >::build(), and rangetree< point, data >::finalize().
xtmparray
template<class point , class data > std::vector<ptx> rangetree< point, data >::xtmparray private
Definition at line 690 of file ranget.h.
Referenced by rangetree< point, data >::add(), rangetree< point, data >::build(), rangetree< point, data >::finalize(), and rangetree< point, data >::rangetree().
ytmparray
template<class point , class data > std::vector<pty> rangetree< point, data >::ytmparray private
Definition at line 691 of file ranget.h.
Referenced by rangetree< point, data >::add(), rangetree< point, data >::build(), rangetree< point, data >::finalize(), and rangetree< point, data >::rangetree().
The documentation for this class was generated from the following file:
dynosam/include/dynosam/frontend/anms/anms/range-tree/ranget.h