DynoSAM: dyno::FrontendOfflinePipeline< MODULE_TRAITS > Class Template Reference
dyno::FrontendOfflinePipeline< MODULE_TRAITS > Class Template Reference
module traits of the associated backend...
#include <FrontendPipeline.hpp>
Public Types
using This = FrontendOfflinePipeline< MODULE_TRAITS >
using Base = MIMOPipelineModule< NullPipelinePayload, FrontendOutputPacketBase >
using ModuleTraits = MODULE_TRAITS
using DerivedPacketType = typename ModuleTraits::DerivedPacketType
using DerivedPacketTypePtr = std::shared_ptr< DerivedPacketType >
using FrontendPacketMap = std::map< FrameId, DerivedPacketTypePtr >
Public Types inherited from dyno::MIMOPipelineModule< NullPipelinePayload, FrontendOutputPacketBase >
using Base = PipelineModule< NullPipelinePayload, FrontendOutputPacketBase >
using This = MIMOPipelineModule< NullPipelinePayload, FrontendOutputPacketBase >
using OutputRegistra = QueueRegistra< FrontendOutputPacketBase >
using OutputCallback = std::function< void(const OutputConstSharedPtr &output)>
using OutputConstSharedPtr = typename OutputTypeTraits::TypeConstSharedPtr
The output is instead a shared ptr, since many users might need the output.
using InputConstSharedPtr = typename InputTypeTraits::TypeConstSharedPtr
using InputQueue = typename InputTypeTraits::TypeQueue
using OutputQueue = typename OutputTypeTraits::TypeQueue
Public Types inherited from dyno::PipelineModule< INPUT, OUTPUT >
using InputTypeTraits = PipelineTypeTraits< INPUT >
using OutputTypeTraits = PipelineTypeTraits< OUTPUT >
using InputConstSharedPtr = typename InputTypeTraits::TypeConstSharedPtr
using OutputConstSharedPtr = typename OutputTypeTraits::TypeConstSharedPtr
The output is instead a shared ptr, since many users might need the output.
using InputQueue = typename InputTypeTraits::TypeQueue
using OutputQueue = typename OutputTypeTraits::TypeQueue
using OnProcessCallback = std::function< void(const InputConstSharedPtr &, const OutputConstSharedPtr &)>
Public Types inherited from dyno::PipelineBase
using OnPipelineFailureCallback = std::function< void(ReturnCode)>
Public Member Functions
FrontendOfflinePipeline (const std::string &module_name, const std::string &bsjon_file_path, int ending_frame=-1)
InputConstSharedPtr getInputPacket () override
OutputConstSharedPtr process (const InputConstSharedPtr &) override
const FrontendPacketMap & getFrontendOutputPackets () const
FrameId endingFrame () const
Public Member Functions inherited from dyno::MIMOPipelineModule< NullPipelinePayload, FrontendOutputPacketBase >
MIMOPipelineModule (const std::string &module_name)
void registerOutputQueue (OutputQueue *output_queue)
OutputRegistra::Ptr getOutputRegistra ()
Constructs an output registra for the internal vector of output queues Basically provides a way to add queues to the pipeline separate to the pipeline itself. This is useful as the registra is only templated on the OUTPUT so we can simply any external templating which only concerns itself with output types.
Public Member Functions inherited from dyno::PipelineModule< INPUT, OUTPUT >
PipelineModule (const std::string &module_name)
virtual ~PipelineModule ()=default
PipelineBase::ReturnCode spinOnce () override
Spin the pipeline once.
void registerOnProcessCallback (const OnProcessCallback &callback)
Registers a function that will be called with the input and output data packets generated from a spinOnce() call.
Public Member Functions inherited from dyno::PipelineBase
PipelineBase (const std::string &module_name)
virtual ~PipelineBase ()=default
bool spin ()
Spins the pipeline via continuous calls to spinOnce until the pipeline is shutdown.
bool isWorking () const
Returns true if the pipeline is currently processing data or if these is still data to process. Checks is_thread_working_ and the overwritten hasWork() function.
bool isShutdown () const
Returns true if the pipeline has been shutdown by shutdown().
std::string getModuleName () const
Returns the given module name (for identifcation and debug printing)
virtual void shutdown ()
void registerOnFailureCallback (const OnPipelineFailureCallback &callback_)
Registers a callback to be triggered if spinOnce returns an invalid return code.
virtual void shutdownQueues ()=0
Virtual function that should shutdown all associated queues. Generally this should shutdown input queues.
virtual bool hasWork () const =0
Virtual function that should check if (any of the) input queues have work to do.
virtual ReturnCode spinOnce ()=0
Processes for one iteration of the pipeline.
Protected Member Functions
void shutdownQueues () override
Virtual function that should shutdown all associated queues. Generally this should shutdown input queues.
bool hasWork () const override
Virtual function that should check if (any of the) input queues have work to do.
Protected Member Functions inherited from dyno::MIMOPipelineModule< NullPipelinePayload, FrontendOutputPacketBase >
bool pushOutputPacket (const OutputConstSharedPtr &output_packet) const override
virtual InputConstSharedPtr getInputPacket ()=0
virtual OutputConstSharedPtr process (const InputConstSharedPtr &input)=0
virtual bool pushOutputPacket (const OutputConstSharedPtr &output_packet) const =0
Private Attributes
FrontendPacketMap frontend_output_packets_
FrontendPacketMap::const_iterator current_packet_
int ending_frame_
Additional Inherited Members
Protected Attributes inherited from dyno::PipelineBase
const std::string module_name_
std::atomic_bool is_thread_working_ { false }
Detailed Description
template<class MODULE_TRAITS>
class dyno::FrontendOfflinePipeline< MODULE_TRAITS >
module traits of the associated backend...
Template Parameters
MODULE_TRAITS
Definition at line 41 of file FrontendPipeline.hpp.
Member Typedef Documentation
Base
template<class MODULE_TRAITS > using dyno::FrontendOfflinePipeline< MODULE_TRAITS >::Base = MIMOPipelineModule<NullPipelinePayload, FrontendOutputPacketBase>
Definition at line 45 of file FrontendPipeline.hpp.
DerivedPacketType
template<class MODULE_TRAITS > using dyno::FrontendOfflinePipeline< MODULE_TRAITS >::DerivedPacketType = typename ModuleTraits::DerivedPacketType
Definition at line 48 of file FrontendPipeline.hpp.
DerivedPacketTypePtr
template<class MODULE_TRAITS > using dyno::FrontendOfflinePipeline< MODULE_TRAITS >::DerivedPacketTypePtr = std::shared_ptr<DerivedPacketType>
Definition at line 49 of file FrontendPipeline.hpp.
FrontendPacketMap
template<class MODULE_TRAITS > using dyno::FrontendOfflinePipeline< MODULE_TRAITS >::FrontendPacketMap = std::map<FrameId, DerivedPacketTypePtr>
Map of frames to (derived) frontend packets Same format as the seralized bson from the frontend
Definition at line 55 of file FrontendPipeline.hpp.
ModuleTraits
template<class MODULE_TRAITS > using dyno::FrontendOfflinePipeline< MODULE_TRAITS >::ModuleTraits = MODULE_TRAITS
Definition at line 46 of file FrontendPipeline.hpp.
This
template<class MODULE_TRAITS > using dyno::FrontendOfflinePipeline< MODULE_TRAITS >::This = FrontendOfflinePipeline<MODULE_TRAITS>
Definition at line 44 of file FrontendPipeline.hpp.
Constructor & Destructor Documentation
FrontendOfflinePipeline()
template<class MODULE_TRAITS > dyno::FrontendOfflinePipeline< MODULE_TRAITS >::FrontendOfflinePipeline (const std::string & module_name, const std::string & bsjon_file_path, int ending_frame = -1) inline explicit
Definition at line 60 of file FrontendPipeline.hpp.
        : Base(module_name) {
            if(!JsonConverter::ReadInJson(frontend_output_packets_, bsjon_file_path, JsonConverter::BSON)) {
                LOG(FATAL) << "Failed to load frontend bson from: " << bsjon_file_path;
            }
            current_packet_ = frontend_output_packets_.cbegin();
            ending_frame_ =  getFrontendOutputPackets().rbegin()->first;
            if(ending_frame != -1) {
                ending_frame_ = (FrameId)std::min(ending_frame, (int)ending_frame_);
            }
            LOG(INFO) << "Setting frontend offline ending frame = " << ending_frame_;
        }
References dyno::JsonConverter::BSON, dyno::FrontendOfflinePipeline< MODULE_TRAITS >::current_packet_, dyno::FrontendOfflinePipeline< MODULE_TRAITS >::ending_frame_, dyno::FrontendOfflinePipeline< MODULE_TRAITS >::frontend_output_packets_, dyno::FrontendOfflinePipeline< MODULE_TRAITS >::getFrontendOutputPackets(), and dyno::JsonConverter::ReadInJson().
Member Function Documentation
endingFrame()
template<class MODULE_TRAITS > FrameId dyno::FrontendOfflinePipeline< MODULE_TRAITS >::endingFrame () const inline
Definition at line 90 of file FrontendPipeline.hpp.
{ return (FrameId)ending_frame_; }
References dyno::FrontendOfflinePipeline< MODULE_TRAITS >::ending_frame_.
getFrontendOutputPackets()
template<class MODULE_TRAITS > const FrontendPacketMap & dyno::FrontendOfflinePipeline< MODULE_TRAITS >::getFrontendOutputPackets () const inline
Definition at line 89 of file FrontendPipeline.hpp.
{ return frontend_output_packets_; }
References dyno::FrontendOfflinePipeline< MODULE_TRAITS >::frontend_output_packets_.
Referenced by dyno::FrontendOfflinePipeline< MODULE_TRAITS >::FrontendOfflinePipeline().
getInputPacket()
template<class MODULE_TRAITS > InputConstSharedPtr dyno::FrontendOfflinePipeline< MODULE_TRAITS >::getInputPacket () inline override virtual
Implements dyno::PipelineModule< INPUT, OUTPUT >.
Definition at line 74 of file FrontendPipeline.hpp.
{
        static auto output = std::make_shared<NullPipelinePayload>();
        return output;
    }
hasWork()
template<class MODULE_TRAITS > bool dyno::FrontendOfflinePipeline< MODULE_TRAITS >::hasWork () const inline override protected virtual
Virtual function that should check if (any of the) input queues have work to do.
Returns
true
false
Implements dyno::PipelineBase.
Definition at line 94 of file FrontendPipeline.hpp.
{ return current_packet_ != frontend_output_packets_.cend() && current_packet_->first <= (FrameId)ending_frame_; }
References dyno::FrontendOfflinePipeline< MODULE_TRAITS >::current_packet_, dyno::FrontendOfflinePipeline< MODULE_TRAITS >::ending_frame_, and dyno::FrontendOfflinePipeline< MODULE_TRAITS >::frontend_output_packets_.
Referenced by dyno::FrontendOfflinePipeline< MODULE_TRAITS >::process().
process()
template<class MODULE_TRAITS > OutputConstSharedPtr dyno::FrontendOfflinePipeline< MODULE_TRAITS >::process (const InputConstSharedPtr &) inline override virtual
Implements dyno::PipelineModule< INPUT, OUTPUT >.
Definition at line 79 of file FrontendPipeline.hpp.
{
        if(!hasWork()) {
            this->shutdown();
            return nullptr;
        }
        auto output = current_packet_->second;
        current_packet_++;
        return output;
    }
References dyno::FrontendOfflinePipeline< MODULE_TRAITS >::current_packet_, dyno::FrontendOfflinePipeline< MODULE_TRAITS >::hasWork(), and dyno::PipelineBase::shutdown().
shutdownQueues()
template<class MODULE_TRAITS > void dyno::FrontendOfflinePipeline< MODULE_TRAITS >::shutdownQueues () inline override protected virtual
Virtual function that should shutdown all associated queues. Generally this should shutdown input queues.
Implements dyno::PipelineBase.
Definition at line 93 of file FrontendPipeline.hpp.
{ current_packet_ = frontend_output_packets_.end();  }
References dyno::FrontendOfflinePipeline< MODULE_TRAITS >::current_packet_, and dyno::FrontendOfflinePipeline< MODULE_TRAITS >::frontend_output_packets_.
Member Data Documentation
current_packet_
template<class MODULE_TRAITS > FrontendPacketMap::const_iterator dyno::FrontendOfflinePipeline< MODULE_TRAITS >::current_packet_ private
Definition at line 102 of file FrontendPipeline.hpp.
Referenced by dyno::FrontendOfflinePipeline< MODULE_TRAITS >::FrontendOfflinePipeline(), dyno::FrontendOfflinePipeline< MODULE_TRAITS >::hasWork(), dyno::FrontendOfflinePipeline< MODULE_TRAITS >::process(), and dyno::FrontendOfflinePipeline< MODULE_TRAITS >::shutdownQueues().
ending_frame_
template<class MODULE_TRAITS > int dyno::FrontendOfflinePipeline< MODULE_TRAITS >::ending_frame_ private
Definition at line 104 of file FrontendPipeline.hpp.
Referenced by dyno::FrontendOfflinePipeline< MODULE_TRAITS >::endingFrame(), dyno::FrontendOfflinePipeline< MODULE_TRAITS >::FrontendOfflinePipeline(), and dyno::FrontendOfflinePipeline< MODULE_TRAITS >::hasWork().
frontend_output_packets_
template<class MODULE_TRAITS > FrontendPacketMap dyno::FrontendOfflinePipeline< MODULE_TRAITS >::frontend_output_packets_ private
same format as the output_packet_record_ in the frontend expected to be seralized in this form to a json file which this pipeline will then load and send directly to the frontend
Definition at line 101 of file FrontendPipeline.hpp.
Referenced by dyno::FrontendOfflinePipeline< MODULE_TRAITS >::FrontendOfflinePipeline(), dyno::FrontendOfflinePipeline< MODULE_TRAITS >::getFrontendOutputPackets(), dyno::FrontendOfflinePipeline< MODULE_TRAITS >::hasWork(), and dyno::FrontendOfflinePipeline< MODULE_TRAITS >::shutdownQueues().
The documentation for this class was generated from the following file:
dynosam/include/dynosam/frontend/FrontendPipeline.hpp