DynoSAM: dyno::ParameterDetails Class Reference
dyno::ParameterDetails Class Reference
#include <RosUtils.hpp>
Public Member Functions
const std::string & name () const
Name of the paramter.
std::string node_name () const
Name of the associated node.
rclcpp::Parameter get () const
Get the rclcpp::Parameter from the node.
template<typename ValueTypeT >
decltype(auto) get () const
Get the c++ value from the node.
template<typename ValueTypeT >
ValueTypeT get (ValueTypeT default_value) const
Get the c++ value from the node or the default value if param is not set in the node. If the default value is used, the param in the node will NOT be updated.
std::string get (const char *default_value) const
Specalisation for getting the value from the node as a std::string or a default string.
std::string get (const std::string &default_value) const
Specalisation for getting the value from the node as a std::string or a default string.
bool isSet () const
operator rclcpp::Parameter () const
Casting operator and returns the Paramter type from the node.
operator rclcpp::ParameterValue () const
Casting operator for the parameter value from the node.
Private Member Functions
ParameterDetails (rclcpp::Node *node, const rclcpp::Parameter &parameter, const rcl_interfaces::msg::ParameterDescriptor &description)
rclcpp::Parameter get_param (const rclcpp::Parameter &default_param) const
void declare ()
template<typename ValueTypeT >
decltype(auto) get_param (const rclcpp::Parameter &default_param) const
Private Attributes
rclcpp::Node * node_
const rclcpp::Parameter default_parameter_
const rcl_interfaces::msg::ParameterDescriptor description_
Friends
class ParameterConstructor
Detailed Description
Definition at line 145 of file RosUtils.hpp.
Constructor & Destructor Documentation
ParameterDetails()
dyno::ParameterDetails::ParameterDetails (rclcpp::Node * node, const rclcpp::Parameter & parameter, const rcl_interfaces::msg::ParameterDescriptor & description) private
Definition at line 209 of file RosUtils.cc.
    : node_(node), default_parameter_(parameter), description_(description) {
  declare();
}
References declare().
Member Function Documentation
declare()
void dyno::ParameterDetails::declare () private
Definition at line 233 of file RosUtils.cc.
{
  // only declare if needed
  if (!node_->has_parameter(this->name())) {
    const rclcpp::ParameterValue default_value =
        default_parameter_.get_parameter_value();
    const rclcpp::ParameterValue effective_value =
        node_->declare_parameter(this->name(), default_value, description_);
    (void)effective_value;
  }
  // add the param subscriber if we dont have one!!
  // if(!param_subscriber_) {
  //   param_subscriber_ =
  //   std::make_shared<rclcpp::ParameterEventHandler>(node_);
  //   auto cb = [&](const rclcpp::Parameter& new_parameter) {
  //       node_->set_parameter(new_parameter);
  //       //should check same type?
  //       CHECK_EQ(new_parameter.get_name(), this->name());
  //       property_handler_.update(this->name(),new_parameter);
  //   };
  //   //callback handler must be set and remain in scope for the cb's to
  //   trigger cb_handle_ =
  //   param_subscriber_->add_parameter_callback(this->name(), cb);
  // }
}
References default_parameter_, description_, name(), and node_.
Referenced by ParameterDetails().
get() [1/5]
rclcpp::Parameter dyno::ParameterDetails::get () const
Get the rclcpp::Parameter from the node.
Returns
rclcpp::Parameter
Definition at line 187 of file RosUtils.cc.
{
  return this->get_param(this->default_parameter_);
}
References default_parameter_, and get_param().
Referenced by dyno::DynoNode::createOnlineDataProvider(), dyno::DynoNode::DynoNode(), dyno::RGBDTypeCalibrationHelper::getParamsFromRos(), dyno::DynoPipelineManagerRos::initalisePipeline(), operator rclcpp::Parameter(), operator rclcpp::ParameterValue(), and dyno::DynoNode::searchForPathWithParams().
get() [2/5]
template<typename ValueTypeT > decltype(auto) dyno::ParameterDetails::get
Get the c++ value from the node.
rclcpp::exceptions::InvalidParameterTypeException if the type doesn't match
Template Parameters
ValueTypeT c++ type
Returns
decltype(auto)
Definition at line 40 of file RosUtils-inl.hpp.
{
  return this->get_param<ValueTypeT>(this->default_parameter_);
}
get() [3/5]
std::string dyno::ParameterDetails::get (const char * default_value) const
Specalisation for getting the value from the node as a std::string or a default string.
See template <typename ValueTypeT> ValueTypeT get(ValueTypeT) for details on how the default value is used.
Parameters
default_value const char *
Returns
std::string
Definition at line 191 of file RosUtils.cc.
{
  return this->get_param<std::string>(
      rclcpp::Parameter(this->name(), std::string(default_value)));
}
References name().
get() [4/5]
std::string dyno::ParameterDetails::get (const std::string & default_value) const
Specalisation for getting the value from the node as a std::string or a default string.
See template <typename ValueTypeT> ValueTypeT get(ValueTypeT) for details on how the default value is used.
Parameters
default_value const std::string
Returns
std::string
Definition at line 196 of file RosUtils.cc.
{
  return this->get_param<std::string>(
      rclcpp::Parameter(this->name(), default_value));
}
References name().
get() [5/5]
template<typename ValueTypeT > ValueTypeT dyno::ParameterDetails::get (ValueTypeT default_value) const
Get the c++ value from the node or the default value if param is not set in the node. If the default value is used, the param in the node will NOT be updated.
This default value will only be used if there is NO value in the node, i.e setting a default value from the ParameterConstructor or using paramter overwrites using NodeOptions or the launchfile will set value in the node and the default_value argument will not be used.
Template Parameters
ValueTypeT
Parameters
default_value
Returns
ValueTypeT
Definition at line 45 of file RosUtils-inl.hpp.
{
  return this->get_param<ValueTypeT>(
      rclcpp::Parameter(this->name(), default_value));
}
References name().
get_param() [1/2]
rclcpp::Parameter dyno::ParameterDetails::get_param (const rclcpp::Parameter & default_param) const private
Definition at line 216 of file RosUtils.cc.
{
  const bool is_set = isSet();
  bool has_default = default_param.get_type() != rclcpp::PARAMETER_NOT_SET;
  if (!is_set) {
    // if no default value we treat a not set parameter as a error as the use
    // MUST override it via runtime configuration
    if (!has_default) {
      throw InvalidDefaultParameter(this->name());
    } else {
      return default_param;
    }
  }
  return node_->get_parameter(this->name());
}
References isSet(), name(), and node_.
Referenced by get().
get_param() [2/2]
template<typename ValueTypeT > decltype(auto) dyno::ParameterDetails::get_param (const rclcpp::Parameter & default_param) const private
Definition at line 83 of file RosUtils-inl.hpp.
{
  const rclcpp::Parameter param = get_param(default_param);
  return param.get_value<ValueTypeT>();
}
isSet()
bool dyno::ParameterDetails::isSet () const inline
Definition at line 237 of file RosUtils.hpp.
{
    return node_->get_parameter(this->name())
               .get_parameter_value()
               .get_type() != rclcpp::PARAMETER_NOT_SET;
  }
References name(), and node_.
Referenced by get_param().
name()
const std::string & dyno::ParameterDetails::name () const
Name of the paramter.
Returns
const std::string&
Definition at line 181 of file RosUtils.cc.
{
  return default_parameter_.get_name();
}
References default_parameter_.
Referenced by declare(), get(), get_param(), and isSet().
node_name()
std::string dyno::ParameterDetails::node_name () const
Name of the associated node.
Returns
std::string
Definition at line 185 of file RosUtils.cc.
{ return node_->get_name(); }
References node_.
operator rclcpp::Parameter()
dyno::ParameterDetails::operator rclcpp::Parameter () const inline
Casting operator and returns the Paramter type from the node.
Returns
rclcpp::Parameter
Definition at line 248 of file RosUtils.hpp.
{ return this->get(); }
References get().
operator rclcpp::ParameterValue()
dyno::ParameterDetails::operator rclcpp::ParameterValue () const inline
Casting operator for the parameter value from the node.
Returns
rclcpp::ParameterValue
Definition at line 255 of file RosUtils.hpp.
{
    return this->get().get_parameter_value();
  }
References get().
Friends And Related Function Documentation
ParameterConstructor
friend class ParameterConstructor friend
Definition at line 147 of file RosUtils.hpp.
Member Data Documentation
default_parameter_
const rclcpp::Parameter dyno::ParameterDetails::default_parameter_ private
Definition at line 275 of file RosUtils.hpp.
Referenced by declare(), get(), and name().
description_
const rcl_interfaces::msg::ParameterDescriptor dyno::ParameterDetails::description_ private
the original parameter, prior to declaration with the node, as provided by ParameterConstructor
Definition at line 277 of file RosUtils.hpp.
Referenced by declare().
node_
rclcpp::Node* dyno::ParameterDetails::node_ mutable private
Definition at line 273 of file RosUtils.hpp.
Referenced by declare(), get_param(), isSet(), and node_name().
The documentation for this class was generated from the following files:
dynosam_ros/include/dynosam_ros/RosUtils.hpp
dynosam_ros/include/dynosam_ros/RosUtils-inl.hpp
dynosam_ros/src/RosUtils.cc