DynoSAM: dyno::FactorGraphManager< GRAPH > Class Template Reference
dyno::FactorGraphManager< GRAPH > Class Template Reference abstract
#include <FactorGraphTools.hpp>
Public Types
using FactorGraphType = GRAPH
using This = FactorGraphManager< FactorGraphType >
using FactorType = typename GRAPH::FactorType
using sharedFactor = typename GRAPH::sharedFactor
using value_type = sharedFactor
using iterator = typename GRAPH::iterator
using const_iterator = typename GRAPH::const_iterator
Public Member Functions
FactorGraphManager (const FactorGraphType graph)
virtual ~FactorGraphManager ()=default
FactorGraphType getAssociatedFactors (gtsam::Key key) const
virtual gtsam::GaussianFactorGraph::shared_ptr linearize () const =0
const FactorGraphType & getGraph () const
gtsam::JacobianFactor constructJacobian (const gtsam::Ordering::OrderingType &ordering_type)
gtsam::JacobianFactor constructJacobian (const gtsam::Ordering &ordering)
cv::Mat drawBlockJacobian (const gtsam::Ordering &ordering, const factor_graph_tools::DrawBlockJacobiansOptions &options) const
cv::Mat drawBlockJacobian (const gtsam::Ordering::OrderingType &ordering_type, const factor_graph_tools::DrawBlockJacobiansOptions &options) const
factor_graph_tools::SparsityStats computeJacobianSparsityStats (const gtsam::Ordering &ordering, bool save=false, const std::string &file="jacobian.txt") const
factor_graph_tools::SparsityStats computeHessianSparsityStats (const gtsam::Ordering &ordering, bool save=false, const std::string &file="hessian.txt") const
const_iterator begin () const
const_iterator end () const
Protected Attributes
const FactorGraphType graph_
Detailed Description
template<class GRAPH>
class dyno::FactorGraphManager< GRAPH >
Definition at line 444 of file FactorGraphTools.hpp.
Member Typedef Documentation
const_iterator
template<class GRAPH > using dyno::FactorGraphManager< GRAPH >::const_iterator = typename GRAPH::const_iterator
Definition at line 454 of file FactorGraphTools.hpp.
FactorGraphType
template<class GRAPH > using dyno::FactorGraphManager< GRAPH >::FactorGraphType = GRAPH
Definition at line 446 of file FactorGraphTools.hpp.
FactorType
template<class GRAPH > using dyno::FactorGraphManager< GRAPH >::FactorType = typename GRAPH::FactorType
Definition at line 449 of file FactorGraphTools.hpp.
iterator
template<class GRAPH > using dyno::FactorGraphManager< GRAPH >::iterator = typename GRAPH::iterator
Definition at line 453 of file FactorGraphTools.hpp.
sharedFactor
template<class GRAPH > using dyno::FactorGraphManager< GRAPH >::sharedFactor = typename GRAPH::sharedFactor
Definition at line 450 of file FactorGraphTools.hpp.
This
template<class GRAPH > using dyno::FactorGraphManager< GRAPH >::This = FactorGraphManager<FactorGraphType>
Definition at line 447 of file FactorGraphTools.hpp.
value_type
template<class GRAPH > using dyno::FactorGraphManager< GRAPH >::value_type = sharedFactor
Definition at line 451 of file FactorGraphTools.hpp.
Constructor & Destructor Documentation
FactorGraphManager()
template<class GRAPH > dyno::FactorGraphManager< GRAPH >::FactorGraphManager (const FactorGraphType graph) inline
Definition at line 456 of file FactorGraphTools.hpp.
: graph_(graph) {}
~FactorGraphManager()
template<class GRAPH > virtual dyno::FactorGraphManager< GRAPH >::~FactorGraphManager () virtual default
Member Function Documentation
begin()
template<class GRAPH > const_iterator dyno::FactorGraphManager< GRAPH >::begin () const inline
Definition at line 525 of file FactorGraphTools.hpp.
{ return graph_.begin(); }
References dyno::FactorGraphManager< GRAPH >::graph_.
computeHessianSparsityStats()
template<class GRAPH > factor_graph_tools::SparsityStats dyno::FactorGraphManager< GRAPH >::computeHessianSparsityStats (const gtsam::Ordering & ordering, bool save = false, const std::string & file = "hessian.txt") const inline
Definition at line 515 of file FactorGraphTools.hpp.
{
        factor_graph_tools::SparsityStats stats = factor_graph_tools::computeHessianSparsityStats(this->linearize(), ordering);
        if(save) stats.saveOnOutputPath(file);
        return stats;
    }
References dyno::factor_graph_tools::computeHessianSparsityStats(), dyno::FactorGraphManager< GRAPH >::linearize(), and dyno::factor_graph_tools::SparsityStats::saveOnOutputPath().
computeJacobianSparsityStats()
template<class GRAPH > factor_graph_tools::SparsityStats dyno::FactorGraphManager< GRAPH >::computeJacobianSparsityStats (const gtsam::Ordering & ordering, bool save = false, const std::string & file = "jacobian.txt") const inline
Definition at line 507 of file FactorGraphTools.hpp.
{
        factor_graph_tools::SparsityStats stats = factor_graph_tools::computeJacobianSparsityStats(this->linearize(), ordering);
        if(save) stats.saveOnOutputPath(file);
        return stats;
    }
References dyno::factor_graph_tools::computeJacobianSparsityStats(), dyno::FactorGraphManager< GRAPH >::linearize(), and dyno::factor_graph_tools::SparsityStats::saveOnOutputPath().
constructJacobian() [1/2]
template<class GRAPH > gtsam::JacobianFactor dyno::FactorGraphManager< GRAPH >::constructJacobian (const gtsam::Ordering & ordering) inline
Definition at line 487 of file FactorGraphTools.hpp.
{
        auto gfg = this->linearize();
        return gtsam::JacobianFactor(*gfg, ordering);
    }
References dyno::FactorGraphManager< GRAPH >::linearize().
constructJacobian() [2/2]
template<class GRAPH > gtsam::JacobianFactor dyno::FactorGraphManager< GRAPH >::constructJacobian (const gtsam::Ordering::OrderingType & ordering_type) inline
Definition at line 483 of file FactorGraphTools.hpp.
{
        return constructJacobian(gtsam::Ordering::Create(ordering_type, graph_));
    }
References dyno::FactorGraphManager< GRAPH >::constructJacobian(), and dyno::FactorGraphManager< GRAPH >::graph_.
Referenced by dyno::FactorGraphManager< GRAPH >::constructJacobian().
drawBlockJacobian() [1/2]
template<class GRAPH > cv::Mat dyno::FactorGraphManager< GRAPH >::drawBlockJacobian (const gtsam::Ordering & ordering, const factor_graph_tools::DrawBlockJacobiansOptions & options) const inline
Definition at line 493 of file FactorGraphTools.hpp.
{
        return factor_graph_tools::drawBlockJacobians(
            this->linearize(),
            ordering,
            options
        );
    }
References dyno::factor_graph_tools::drawBlockJacobians(), and dyno::FactorGraphManager< GRAPH >::linearize().
Referenced by dyno::FactorGraphManager< GRAPH >::drawBlockJacobian().
drawBlockJacobian() [2/2]
template<class GRAPH > cv::Mat dyno::FactorGraphManager< GRAPH >::drawBlockJacobian (const gtsam::Ordering::OrderingType & ordering_type, const factor_graph_tools::DrawBlockJacobiansOptions & options) const inline
Definition at line 501 of file FactorGraphTools.hpp.
{
        return drawBlockJacobian(gtsam::Ordering::Create(ordering_type, graph_), options);
    }
References dyno::FactorGraphManager< GRAPH >::drawBlockJacobian(), and dyno::FactorGraphManager< GRAPH >::graph_.
end()
template<class GRAPH > const_iterator dyno::FactorGraphManager< GRAPH >::end () const inline
Definition at line 526 of file FactorGraphTools.hpp.
{ return graph_.end(); }
References dyno::FactorGraphManager< GRAPH >::graph_.
getAssociatedFactors()
template<class GRAPH > FactorGraphType dyno::FactorGraphManager< GRAPH >::getAssociatedFactors (gtsam::Key key) const inline
Definition at line 460 of file FactorGraphTools.hpp.
{
        std::vector<sharedFactor> factors;
        //while the manager is NOT a grpah, it does complete MOST of the concept requirements of a
        //gtsam::FactorGraph but providing iterator, shared factor etc... type alias and std container definitions
        //(begin and end) so that we can use this with templated GRAPH functions
        const size_t num_connected = factor_graph_tools::getAssociatedFactors(factors, *this, key);
        if(num_connected < 1) {
            return FactorGraphType{};
        }
        FactorGraphType connected_factors;
        for(const auto& f : factors) {
            connected_factors += f;
        }
        return connected_factors;
    }
References dyno::factor_graph_tools::getAssociatedFactors().
getGraph()
template<class GRAPH > const FactorGraphType & dyno::FactorGraphManager< GRAPH >::getGraph () const inline
Definition at line 481 of file FactorGraphTools.hpp.
{ return graph_; }
References dyno::FactorGraphManager< GRAPH >::graph_.
linearize()
template<class GRAPH > virtual gtsam::GaussianFactorGraph::shared_ptr dyno::FactorGraphManager< GRAPH >::linearize () const pure virtual
Implemented in dyno::NonlinearFactorGraphManager.
Referenced by dyno::FactorGraphManager< GRAPH >::computeHessianSparsityStats(), dyno::FactorGraphManager< GRAPH >::computeJacobianSparsityStats(), dyno::FactorGraphManager< GRAPH >::constructJacobian(), and dyno::FactorGraphManager< GRAPH >::drawBlockJacobian().
Member Data Documentation
graph_
template<class GRAPH > const FactorGraphType dyno::FactorGraphManager< GRAPH >::graph_ protected
Definition at line 529 of file FactorGraphTools.hpp.
Referenced by dyno::FactorGraphManager< GRAPH >::begin(), dyno::FactorGraphManager< GRAPH >::constructJacobian(), dyno::FactorGraphManager< GRAPH >::drawBlockJacobian(), dyno::FactorGraphManager< GRAPH >::end(), and dyno::FactorGraphManager< GRAPH >::getGraph().
The documentation for this class was generated from the following file:
dynosam/include/dynosam/backend/FactorGraphTools.hpp