DynoSAM: dyno::Camera Class Reference
dyno::Camera Class Reference
#include <Camera.hpp>
Public Types
using CalibrationType = gtsam::Cal3_S2
using CameraImpl = gtsam::PinholeCamera< CalibrationType >
Public Member Functions
Camera (const CameraParams &camera_params)
virtual ~Camera ()=default
void project (const Landmark &lmk, Keypoint *kpt) const
Projects a 3D point in the camera frame into the image frame as a keypoint. Doesnt do any checks if the keypoint lands in the frame; use in conjunction with isLandmarkContained.
void project (const Landmarks &lmks, Keypoints *kpts) const
Projects a list 3D points in the camera frame into the image frame. Doesnt do any checks if the keypoint lands in the frame; use in conjunction with isLandmarkContained.
bool isKeypointContained (const Keypoint &kpt, Depth depth) const
Checks if a given keypoint is inside the image AND in front the camera (ie. depth > 0).
bool isKeypointContained (const Keypoint &kpt) const
void backProject (const Keypoints &kps, const Depths &depths, Landmarks *lmks) const
Back projects a list of keypoints from the image frame and into the camera frame given a depth.
void backProject (const Keypoint &kp, const Depth &depth, Landmark *lmk) const
Back projects a single keypoint from the image frame and into the camera frame given a depth.
void backProject (const Keypoint &kp, const Depth &depth, Landmark *lmk, const gtsam::Pose3 &X_world) const
void backProjectFromZ (const Keypoint &kp, const double Z, Landmark *lmk, gtsam::OptionalJacobian< 3, 3 > Dp={}) const
Projects a point using a keypoint measurement and a Z measurement, rather than depth.
void backProjectFromZ (const Keypoint &kp, const double Z, Landmark *lmk, const gtsam::Pose3 &X_world, gtsam::OptionalJacobian< 3, 3 > Dp={}) const
Projects a point using a keypoint measurement and a Z measurement, rather than depth.
bool isLandmarkContained (const Landmark &lmk, Keypoint *keypoint=nullptr) const
Checks if a landmark can be seen in the image frustrum. The 3D point must be in the camera frame.
CameraImpl * getImplCamera () const
CalibrationType::shared_ptr getGtsamCalibration () const
const CameraParams & getParams () const
RGBDCamera getRGBDCamera () const
std::shared_ptr< RGBDCamera > safeGetRGBDCamera () const
Static Public Member Functions
static Landmark cameraToWorldConvention (const Landmark &lmk)
Protected Attributes
const CameraParams camera_params_
std::unique_ptr< CameraImpl > camera_impl_
Detailed Description
Definition at line 43 of file Camera.hpp.
Member Typedef Documentation
CalibrationType
using dyno::Camera::CalibrationType = gtsam::Cal3_S2
Definition at line 54 of file Camera.hpp.
CameraImpl
using dyno::Camera::CameraImpl = gtsam::PinholeCamera<CalibrationType>
Definition at line 55 of file Camera.hpp.
Constructor & Destructor Documentation
Camera()
dyno::Camera::Camera (const CameraParams & camera_params)
Definition at line 39 of file Camera.cc.
    : camera_params_(camera_params) {
  camera_impl_ = std::make_unique<CameraImpl>(
      gtsam::Pose3::Identity(),  // this should be the body pose cam from the
                                 // calibration but currently we want everything
                                 // in camera frame,
      camera_params_.constructGtsamCalibration<CalibrationType>());
  CHECK(camera_impl_);
}
References camera_impl_, camera_params_, and dyno::CameraParams::constructGtsamCalibration().
~Camera()
virtual dyno::Camera::~Camera () virtual default
Member Function Documentation
backProject() [1/3]
void dyno::Camera::backProject (const Keypoint & kp, const Depth & depth, Landmark * lmk) const
Back projects a single keypoint from the image frame and into the camera frame given a depth.
Parameters
kp const Keypoint& Keypoint to back project
depth const Depth& Depth value to project along
lmk Landmark* 3D landmark to set.
Definition at line 88 of file Camera.cc.
{
  CHECK(lmk);
  backProject(kp, depth, lmk, gtsam::Pose3::Identity());
}
References backProject().
backProject() [2/3]
void dyno::Camera::backProject (const Keypoint & kp, const Depth & depth, Landmark * lmk, const gtsam::Pose3 & X_world) const
Definition at line 95 of file Camera.cc.
{
  CHECK(lmk);
  *lmk = X_world * camera_impl_->backproject(kp, depth);
}
References camera_impl_.
backProject() [3/3]
void dyno::Camera::backProject (const Keypoints & kps, const Depths & depths, Landmarks * lmks) const
Back projects a list of keypoints from the image frame and into the camera frame given a depth.
Assume that the number of keypoints and number of depth values are the same and are aligned by index.
Parameters
kps List of keypoints to back project
depths List of depth values to project along
lmks The 3D landmarks to set.
Definition at line 76 of file Camera.cc.
{
  CHECK_NOTNULL(lmks)->clear();
  lmks->reserve(kps.size());
  CHECK_EQ(kps.size(), depths.size());
  CHECK(camera_impl_);
  for (size_t i = 0u; i < kps.size(); i++) {
    Landmark lmk;
    backProject(kps[i], depths[i], &lmk);
    lmks->push_back(lmk);
  }
}
References backProject(), and camera_impl_.
Referenced by backProject().
backProjectFromZ() [1/2]
void dyno::Camera::backProjectFromZ (const Keypoint & kp, const double Z, Landmark * lmk, const gtsam::Pose3 & X_world, gtsam::OptionalJacobian< 3, 3 > Dp = {}) const
Projects a point using a keypoint measurement and a Z measurement, rather than depth.
Parameters
kp const Keypoint&
Z double Z coordinate of the 3D point in the camera frame
lmk Landmark* 3D landmark to set in the coordinate frame determined by X_world
X_world const gtsam::Pose3& pose to transform the 3D point to. If I, lmk will be in the camera frame
Dp gtsam::OptionalJacobian<3, 3> Jacobian w.r.t to the calculated lmk. Row structure is [x,y,z] of the output lmk and Col structure is [u, v, Z] (i.e [kp(0), kp(1), Z]) of the input
Definition at line 107 of file Camera.cc.
{
  CHECK(lmk);
  const auto calibration = camera_impl_->calibration();
  // Convert (distorted) image coordinates uv to intrinsic coordinates xy
  Eigen::Matrix<double, 2, decltype(calibration)::dimension> Dcal;  // unused
  gtsam::Matrix22 Dcal_point;
  gtsam::Point2 pc = calibration.calibrate(kp, Dcal, Dcal_point);
  // projection equation x = f(X/Z). The f is used to normalize the image
  // cooridinates and since we already have normalized cordinates xy, we can
  // omit the f
  const double X = pc(0) * Z;
  const double Y = pc(1) * Z;
  const gtsam::Point3 P_camera(X, Y, Z);
  // jacobian of the transforFrom function w.r.t P_camera
  gtsam::Matrix33 H_point;
  *lmk = X_world.transformFrom(P_camera, boost::none, H_point);
  if (Dp) {
    // TODO: test!!!
    // cal1 should be top row of Dcal_point which determines how the pc(0)
    // changes with input u, v
    const double dcal1_du = Dcal_point(0, 0);
    const double dcal1_dv = Dcal_point(0, 1);
    // cal1 should be top row of Dcal_point which determines how the pc(1)
    // changes with input u, v
    const double dcal2_du = Dcal_point(1, 0);
    const double dcal2_dv = Dcal_point(1, 1);
    gtsam::Matrix33 J;
    // top row is how X changes with u, v and Z
    J(0, 0) = dcal1_du * Z;
    J(0, 1) = dcal1_dv * Z;
    J(0, 2) = pc(0);
    // how Y changes with u, v and Z
    J(1, 0) = dcal2_du * Z;
    J(1, 1) = dcal2_dv * Z;
    J(1, 2) = pc(1);
    // how Z changes with Z
    J(2, 0) = 0;
    J(2, 1) = 0;
    J(2, 2) = 1;
    // J is computed as the jacobian without the affect of X_world
    //  f = X_world * C(u, v, Z)
    //    = X_world * P_camera
    // df/dfuvz = df/dC * dC/duvz
    //          = df/dC * J
    // since C -> C(u, v, z) = point in R^3, df/dC is the Jacobian of X_world *
    // P_camera -> Rotation component of X_world, or H_point
    *Dp = H_point * J;
  }
}
References camera_impl_.
backProjectFromZ() [2/2]
void dyno::Camera::backProjectFromZ (const Keypoint & kp, const double Z, Landmark * lmk, gtsam::OptionalJacobian< 3, 3 > Dp = {}) const
Projects a point using a keypoint measurement and a Z measurement, rather than depth.
Depth is the depth along a projected ray while Z is the distance the point is from the camera frame along the Z axis
             * (P)
     |      /
     |     /
     |    /
   Z |   / d (depth)
     |  /
     | /
     |/
 --------- (Camera Plane)
Parameters
kp const Keypoint&
Z const double Z distance of the point along the Z axis
lmk Landmark* 3D landmark to set.
Dp gtsam::OptionalJacobian<3, 3> Jacobian w.r.t to the calculated lmk. Row structure is [x,y,z] of the output lmk and Col structure is [u, v, Z] (i.e [kp(0), kp(1), Z]) of the input
Definition at line 101 of file Camera.cc.
{
  CHECK(lmk);
  backProjectFromZ(kp, Z, lmk, gtsam::Pose3::Identity(), Dp);
}
References backProjectFromZ().
Referenced by backProjectFromZ().
cameraToWorldConvention()
Landmark dyno::Camera::cameraToWorldConvention (const Landmark & lmk) static
Definition at line 168 of file Camera.cc.
{
  // expecting camera convention to be z forward, x, right and y down
  return Landmark(lmk(2), lmk(0), -lmk(2));
}
getGtsamCalibration()
Camera::CalibrationType::shared_ptr dyno::Camera::getGtsamCalibration () const
Definition at line 189 of file Camera.cc.
{
  return boost::make_shared<CalibrationType>(getImplCamera()->calibration());
}
References getImplCamera().
getImplCamera()
CameraImpl * dyno::Camera::getImplCamera () const inline
Definition at line 180 of file Camera.hpp.
{ return camera_impl_.get(); }
References camera_impl_.
Referenced by dyno::vision_tools::backProjectAndCovariance(), and getGtsamCalibration().
getParams()
const CameraParams & dyno::Camera::getParams () const inline
Definition at line 183 of file Camera.hpp.
{ return camera_params_; }
References camera_params_.
Referenced by dyno::vision_tools::backProjectAndCovariance(), dyno::RGBDCamera::baseline(), dyno::RGBDCamera::getFakeStereoCalib(), getRGBDCamera(), dyno::RGBDCamera::projectRight(), safeGetRGBDCamera(), and dyno::vision_tools::writeOutProjectMaskAndDepthMap().
getRGBDCamera()
RGBDCamera dyno::Camera::getRGBDCamera () const
Definition at line 193 of file Camera.cc.
{
  return RGBDCamera(this->getParams());
}
References getParams().
isKeypointContained() [1/2]
bool dyno::Camera::isKeypointContained (const Keypoint & kpt) const
Definition at line 71 of file Camera.cc.
{
  return kpt(0) >= 0.0 && kpt(0) < camera_params_.ImageWidth() &&
         kpt(1) >= 0.0 && kpt(1) < camera_params_.ImageHeight();
}
References camera_params_, dyno::CameraParams::ImageHeight(), and dyno::CameraParams::ImageWidth().
isKeypointContained() [2/2]
bool dyno::Camera::isKeypointContained (const Keypoint & kpt, Depth depth) const
Checks if a given keypoint is inside the image AND in front the camera (ie. depth > 0).
Assume that the camera is orientated with z-axis pointing along the line of sight of the camera, otherwise the depth > 0 check is invalid.
Parameters
kpts Projected Keypoint
depth Depth of the 3D point (along the z axis)
Returns
true If the keypoint is visible from the camera frustrum
false
Definition at line 67 of file Camera.cc.
{
  return isKeypointContained(kpt) && depth > 0.0;
}
References isKeypointContained().
Referenced by isKeypointContained(), and isLandmarkContained().
isLandmarkContained()
bool dyno::Camera::isLandmarkContained (const Landmark & lmk, Keypoint * keypoint = nullptr) const
Checks if a landmark can be seen in the image frustrum. The 3D point must be in the camera frame.
If keypoint is not null, it will be set with the projected u,v coordinates. The keypoint will be set regardless of whether the landmark is visible.
Parameters
lmk 3D landmark in the camera frame to check.
keypoint The projected of the landmark in the image frame.
Returns
true If the landmark is visible from the camera frame.
false
Definition at line 173 of file Camera.cc.
{
  Keypoint kp;
  try {
    project(lmk, &kp);
  } catch (const gtsam::CheiralityException&) {
    // if CheiralityException then point is behind camera
    return false;
  }
  const bool result = isKeypointContained(kp);
  if (keypoint) *keypoint = kp;
  return result;
}
References isKeypointContained(), and project().
project() [1/2]
void dyno::Camera::project (const Landmark & lmk, Keypoint * kpt) const
Projects a 3D point in the camera frame into the image frame as a keypoint. Doesnt do any checks if the keypoint lands in the frame; use in conjunction with isLandmarkContained.
Parameters
lmks A 3D landmark
kpts The 2D keypoint to be set
Definition at line 50 of file Camera.cc.
{
  CHECK_NOTNULL(kpt);
  // I believe this project call in gtsam is quite inefficient as it goes
  // through a cascade of calls... Only useful if you want gradients I guess...
  *kpt = camera_impl_->project2(lmk);
}
References camera_impl_.
Referenced by isLandmarkContained(), and project().
project() [2/2]
void dyno::Camera::project (const Landmarks & lmks, Keypoints * kpts) const
Projects a list 3D points in the camera frame into the image frame. Doesnt do any checks if the keypoint lands in the frame; use in conjunction with isLandmarkContained.
Parameters
lmks A list of 3D points
kpts A list of 2D keypoints to be set
Definition at line 57 of file Camera.cc.
{
  CHECK_NOTNULL(kpts)->clear();
  const auto& n_lmks = lmks.size();
  kpts->resize(n_lmks);
  // Can be greatly optimized with matrix mult or vectorization
  for (size_t i = 0u; i < n_lmks; i++) {
    project(lmks[i], &(*kpts)[i]);
  }
}
References project().
safeGetRGBDCamera()
std::shared_ptr< RGBDCamera > dyno::Camera::safeGetRGBDCamera () const
Definition at line 196 of file Camera.cc.
{
  try {
    return std::make_shared<RGBDCamera>(this->getParams());
  } catch (const InvalidRGBDCameraParams& e) {
    VLOG(10) << "Cannot get RGBD Camera: " << e.what();
    return nullptr;
  }
}
References getParams().
Member Data Documentation
camera_impl_
std::unique_ptr<CameraImpl> dyno::Camera::camera_impl_ protected
Definition at line 190 of file Camera.hpp.
Referenced by backProject(), backProjectFromZ(), Camera(), getImplCamera(), and project().
camera_params_
const CameraParams dyno::Camera::camera_params_ protected
Definition at line 189 of file Camera.hpp.
Referenced by Camera(), getParams(), and isKeypointContained().
The documentation for this class was generated from the following files:
dynosam_cv/include/dynosam_cv/Camera.hpp
dynosam_cv/src/Camera.cc