DynoSAM: dyno::OnlineDataProviderRos Class Reference
dyno::OnlineDataProviderRos Class Reference
Online data-provider for DynoSAM.
#include <OnlineDataProviderRos.hpp>
Public Member Functions
OnlineDataProviderRos (rclcpp::Node::SharedPtr node, const OnlineDataProviderRosParams &params)
Construct a new OnlineDataProviderRos.
int datasetSize () const override
Indicates that there is no known end to the dataset.
bool spin () override
Returns true while not shutdown.
void shutdown () override
Disconnects all subscribers.
void connect ()
Connects all subscribers.
Public Member Functions inherited from dyno::DataProviderRos
DataProviderRos (rclcpp::Node::SharedPtr node)
virtual ~DataProviderRos ()=default
const cv::Mat readRgbRosImage (const sensor_msgs::msg::Image::ConstSharedPtr &img_msg) const
Convers a sensor_msgs::msg::Image to a cv::Mat while testing that the input has the correct datatype for an RGB image (as defined by ImageType::RGBMono).
const cv::Mat readDepthRosImage (const sensor_msgs::msg::Image::ConstSharedPtr &img_msg) const
Convers a sensor_msgs::msg::Image to a cv::Mat while testing that the input has the correct datatype for an Depth image (as defined by ImageType::Depth).
const cv::Mat readFlowRosImage (const sensor_msgs::msg::Image::ConstSharedPtr &img_msg) const
Convers a sensor_msgs::msg::Image to a cv::Mat while testing that the input has the correct datatype for an Optical Flow image (as defined by ImageType::OpticalFlow).
const cv::Mat readMaskRosImage (const sensor_msgs::msg::Image::ConstSharedPtr &img_msg) const
Convers a sensor_msgs::msg::Image to a cv::Mat while testing that the input has the correct datatype for an Motion Mask image (as defined by ImageType::MotionMask).
template<class Rep = int64_t, class Period = std::milli>
const CameraParams & waitAndSetCameraParams (const std::chrono::duration< Rep, Period > &time_to_wait=std::chrono::duration< Rep, Period >(-1), const std::string &topic="image/camera_info")
Gets CameraParams from a sensor_msgs::msg::CameraInfo recieved on the specified topic. This function is blocking until a message is recieved (or until the time_to_wait) elapses.
CameraParams::Optional getCameraParams () const override
Provides functionality to get camera paramters for the main pipeline, as these may be available from the dataset.
Public Member Functions inherited from dyno::DataProvider
DataProvider ()=default
DataProvider (DataInterfacePipeline *module)
DataProvider (DataInterfacePipelineImu *module)
virtual ~DataProvider ()
void registerImuSingleCallback (const ImuSingleInputCallback &callback)
void registerImuMultiCallback (const ImuMultiInputCallback &callback)
void registerImageContainerCallback (const ImageContainerCallback &callback)
void registerGroundTruthPacketCallback (const GroundTruthPacketCallback &callback)
virtual ImageContainer::Ptr imageContainerPreprocessor (ImageContainer::Ptr image_container)
Virtual Image Container Preprocessor function that is registered to the data interface pipeline.
void registerOnFinishCallback (const std::function< void()> &callback)
virtual int datasetSize () const =0
Get the size of the dataset - if this is not valid (i.e. the provider is online) this function should return -1.
virtual bool spin ()=0
Spins the dataset for one "step" of the dataset.
virtual void shutdown ()
virtual CameraParams::Optional getCameraParams () const
Provides functionality to get camera paramters for the main pipeline, as these may be available from the dataset.
Private Types
using SyncPolicy = message_filters::sync_policies::ExactTime< sensor_msgs::msg::Image, sensor_msgs::msg::Image, sensor_msgs::msg::Image, sensor_msgs::msg::Image >
Private Member Functions
void imageSyncCallback (const sensor_msgs::msg::Image::ConstSharedPtr &rgb_msg, const sensor_msgs::msg::Image::ConstSharedPtr &depth_msg, const sensor_msgs::msg::Image::ConstSharedPtr &flow_msg, const sensor_msgs::msg::Image::ConstSharedPtr &mask_msg)
Private Attributes
FrameId frame_id_
message_filters::Subscriber< sensor_msgs::msg::Image > rgb_image_sub_
message_filters::Subscriber< sensor_msgs::msg::Image > depth_image_sub_
message_filters::Subscriber< sensor_msgs::msg::Image > flow_image_sub_
message_filters::Subscriber< sensor_msgs::msg::Image > mask_image_sub_
std::shared_ptr< message_filters::Synchronizer< SyncPolicy > > sync_
Additional Inherited Members
Public Types inherited from dyno::DataProvider
using ImageContainerCallback = std::function< void(ImageContainer::Ptr)>
using ImuSingleInputCallback = std::function< void(const ImuMeasurement &)>
using ImuMultiInputCallback = std::function< void(const ImuMeasurements &)>
using GroundTruthPacketCallback = std::function< void(const GroundTruthInputPacket &)>
Protected Member Functions inherited from dyno::DataProviderRos
const cv_bridge::CvImageConstPtr readRosImage (const sensor_msgs::msg::Image::ConstSharedPtr &img_msg) const
Helper function to convert a ROS Image message to a CvImageConstPtr via the cv bridge.
template<typename IMAGETYPE >
const cv::Mat convertRosImage (const sensor_msgs::msg::Image::ConstSharedPtr &img_msg) const
Helper function to convert a sensor_msgs::msg::Image::ConstSharedPtr& to a cv::Mat with the right datatype.
Protected Member Functions inherited from dyno::DataProvider
void emitOnFinishCallbacks ()
Protected Attributes inherited from dyno::DataProviderRos
rclcpp::Node::SharedPtr node_
CameraParams::Optional camera_params_
Protected Attributes inherited from dyno::DataProvider
ImageContainerCallback image_container_callback_
ImuSingleInputCallback imu_single_input_callback_
ImuMultiInputCallback imu_multi_input_callback_
GroundTruthPacketCallback ground_truth_packet_callback_
std::atomic_bool shutdown_ = {false}
Detailed Description
Online data-provider for DynoSAM.
Subscribes to four synchronized image topics (rgb, depth, mask and optical flow) and a camera_info topic (to define the camera intrinsics of the system).
Definition at line 58 of file OnlineDataProviderRos.hpp.
Member Typedef Documentation
SyncPolicy
using dyno::OnlineDataProviderRos::SyncPolicy = message_filters::sync_policies::ExactTime< sensor_msgs::msg::Image, sensor_msgs::msg::Image, sensor_msgs::msg::Image, sensor_msgs::msg::Image> private
Definition at line 100 of file OnlineDataProviderRos.hpp.
Constructor & Destructor Documentation
OnlineDataProviderRos()
dyno::OnlineDataProviderRos::OnlineDataProviderRos (rclcpp::Node::SharedPtr node, const OnlineDataProviderRosParams & params)
Construct a new OnlineDataProviderRos.
Constructor will block until camera info has been received (if OnlineDataProviderRosParams::wait_for_camera_params is true).
Parameters
node rclcpp::Node::SharedPtr
params const OnlineDataProviderRosParams&
Definition at line 37 of file OnlineDataProviderRos.cc.
    : DataProviderRos(node), frame_id_(0u) {
  if (params.wait_for_camera_params) {
    waitAndSetCameraParams(
        std::chrono::milliseconds(params.camera_params_timeout));
  }
  connect();
  CHECK_EQ(shutdown_, false);
}
References dyno::OnlineDataProviderRosParams::camera_params_timeout, connect(), dyno::DataProvider::shutdown_, dyno::OnlineDataProviderRosParams::wait_for_camera_params, and dyno::DataProviderRos::waitAndSetCameraParams().
Member Function Documentation
connect()
void dyno::OnlineDataProviderRos::connect ()
Connects all subscribers.
Definition at line 64 of file OnlineDataProviderRos.cc.
{
  rclcpp::Node *node_ptr = node_.get();
  CHECK_NOTNULL(node_ptr);
  rgb_image_sub_.subscribe(node_ptr, "image/rgb");
  depth_image_sub_.subscribe(node_ptr, "image/depth");
  flow_image_sub_.subscribe(node_ptr, "image/flow");
  mask_image_sub_.subscribe(node_ptr, "image/mask");
  if (sync_) sync_.reset();
  static constexpr size_t kQueueSize = 20u;
  sync_ = std::make_shared<message_filters::Synchronizer<SyncPolicy>>(
      SyncPolicy(kQueueSize), rgb_image_sub_, depth_image_sub_, flow_image_sub_,
      mask_image_sub_);
  sync_->registerCallback(std::bind(
      &OnlineDataProviderRos::imageSyncCallback, this, std::placeholders::_1,
      std::placeholders::_2, std::placeholders::_3, std::placeholders::_4));
  RCLCPP_INFO_STREAM(
      node_->get_logger(),
      "OnlineDataProviderRos has been connected. Subscribed to image topics: "
          << rgb_image_sub_.getSubscriber()->get_topic_name() << " "
          << depth_image_sub_.getSubscriber()->get_topic_name() << " "
          << flow_image_sub_.getSubscriber()->get_topic_name() << " "
          << mask_image_sub_.getSubscriber()->get_topic_name() << ".");
  shutdown_ = false;
}
References depth_image_sub_, flow_image_sub_, imageSyncCallback(), mask_image_sub_, dyno::DataProviderRos::node_, rgb_image_sub_, dyno::DataProvider::shutdown_, and sync_.
Referenced by OnlineDataProviderRos().
datasetSize()
int dyno::OnlineDataProviderRos::datasetSize () const inline override virtual
Indicates that there is no known end to the dataset.
Returns
int
Implements dyno::DataProvider.
Definition at line 77 of file OnlineDataProviderRos.hpp.
{ return -1; }
imageSyncCallback()
void dyno::OnlineDataProviderRos::imageSyncCallback (const sensor_msgs::msg::Image::ConstSharedPtr & rgb_msg, const sensor_msgs::msg::Image::ConstSharedPtr & depth_msg, const sensor_msgs::msg::Image::ConstSharedPtr & flow_msg, const sensor_msgs::msg::Image::ConstSharedPtr & mask_msg) private
Definition at line 94 of file OnlineDataProviderRos.cc.
{
  if (!image_container_callback_) {
    RCLCPP_ERROR_THROTTLE(node_->get_logger(), *node_->get_clock(), 1000,
                          "Image Sync callback triggered but "
                          "image_container_callback_ is not registered!");
    return;
  }
  const cv::Mat rgb = readRgbRosImage(rgb_msg);
  const cv::Mat depth = readDepthRosImage(depth_msg);
  const cv::Mat flow = readFlowRosImage(flow_msg);
  const cv::Mat mask = readMaskRosImage(mask_msg);
  const Timestamp timestamp = utils::fromRosTime(rgb_msg->header.stamp);
  const FrameId frame_id = frame_id_;
  frame_id_++;
  ImageContainer::Ptr image_container = ImageContainer::Create(
      timestamp, frame_id, ImageWrapper<ImageType::RGBMono>(rgb),
      ImageWrapper<ImageType::Depth>(depth),
      ImageWrapper<ImageType::OpticalFlow>(flow),
      ImageWrapper<ImageType::MotionMask>(mask));
  CHECK(image_container);
  cv::Mat of_viz, motion_viz, depth_viz;
  of_viz = ImageType::OpticalFlow::toRGB(flow);
  motion_viz = ImageType::MotionMask::toRGB(mask);
  depth_viz = ImageType::Depth::toRGB(depth);
  // cv::imshow("Optical Flow", of_viz);
  // cv::imshow("Motion mask", motion_viz);
  // cv::imshow("Depth", depth_viz);
  // cv::waitKey(1);
  // trigger callback to send data to the DataInterface!
  image_container_callback_(image_container);
}
References dyno::ImageContainer::Create(), frame_id_, dyno::utils::fromRosTime(), dyno::DataProvider::image_container_callback_, dyno::DataProviderRos::node_, dyno::DataProviderRos::readDepthRosImage(), dyno::DataProviderRos::readFlowRosImage(), dyno::DataProviderRos::readMaskRosImage(), dyno::DataProviderRos::readRgbRosImage(), and dyno::ImageType::MotionMask::toRGB().
Referenced by connect().
shutdown()
void dyno::OnlineDataProviderRos::shutdown () override virtual
Disconnects all subscribers.
Reimplemented from dyno::DataProvider.
Definition at line 51 of file OnlineDataProviderRos.cc.
{
  shutdown_ = true;
  // shutdown synchronizer
  RCLCPP_INFO_STREAM(node_->get_logger(),
                     "Shutting down OnlineDataProviderRos");
  if (sync_) sync_.reset();
  rgb_image_sub_.unsubscribe();
  depth_image_sub_.unsubscribe();
  flow_image_sub_.unsubscribe();
  mask_image_sub_.unsubscribe();
}
References depth_image_sub_, flow_image_sub_, mask_image_sub_, dyno::DataProviderRos::node_, rgb_image_sub_, dyno::DataProvider::shutdown_, and sync_.
spin()
bool dyno::OnlineDataProviderRos::spin () override virtual
Returns true while not shutdown.
Returns
true
false
Implements dyno::DataProvider.
Definition at line 49 of file OnlineDataProviderRos.cc.
{ return !shutdown_; }
References dyno::DataProvider::shutdown_.
Member Data Documentation
depth_image_sub_
message_filters::Subscriber<sensor_msgs::msg::Image> dyno::OnlineDataProviderRos::depth_image_sub_ private
Definition at line 114 of file OnlineDataProviderRos.hpp.
Referenced by connect(), and shutdown().
flow_image_sub_
message_filters::Subscriber<sensor_msgs::msg::Image> dyno::OnlineDataProviderRos::flow_image_sub_ private
Definition at line 115 of file OnlineDataProviderRos.hpp.
Referenced by connect(), and shutdown().
frame_id_
FrameId dyno::OnlineDataProviderRos::frame_id_ private
Definition at line 111 of file OnlineDataProviderRos.hpp.
Referenced by imageSyncCallback().
mask_image_sub_
message_filters::Subscriber<sensor_msgs::msg::Image> dyno::OnlineDataProviderRos::mask_image_sub_ private
Definition at line 116 of file OnlineDataProviderRos.hpp.
Referenced by connect(), and shutdown().
rgb_image_sub_
message_filters::Subscriber<sensor_msgs::msg::Image> dyno::OnlineDataProviderRos::rgb_image_sub_ private
Definition at line 113 of file OnlineDataProviderRos.hpp.
Referenced by connect(), and shutdown().
sync_
std::shared_ptr<message_filters::Synchronizer<SyncPolicy> > dyno::OnlineDataProviderRos::sync_ private
Definition at line 118 of file OnlineDataProviderRos.hpp.
Referenced by connect(), and shutdown().
The documentation for this class was generated from the following files:
dynosam_ros/include/dynosam_ros/OnlineDataProviderRos.hpp
dynosam_ros/src/OnlineDataProviderRos.cc