DynoSAM: dyno::byte_track::RectBase Class Reference
dyno::byte_track::RectBase Class Reference abstract
#include <Rect.hpp>
Public Member Functions
virtual ~RectBase ()=default
virtual float top () const =0
virtual float left () const =0
virtual float width () const =0
virtual float height () const =0
operator cv::Rect () const
Detailed Description
Definition at line 31 of file Rect.hpp.
Constructor & Destructor Documentation
~RectBase()
virtual dyno::byte_track::RectBase::~RectBase () virtual default
Member Function Documentation
height()
virtual float dyno::byte_track::RectBase::height () const pure virtual
Implemented in dyno::byte_track::TlwhRect.
Referenced by dyno::byte_track::KalmanFilter::initiate(), operator cv::Rect(), and dyno::byte_track::KalmanFilter::rect_to_xyah().
left()
virtual float dyno::byte_track::RectBase::left () const pure virtual
Implemented in dyno::byte_track::TlwhRect.
Referenced by operator cv::Rect(), and dyno::byte_track::KalmanFilter::rect_to_xyah().
operator cv::Rect()
dyno::byte_track::RectBase::operator cv::Rect () const inline
Definition at line 40 of file Rect.hpp.
{ return cv::Rect(this->left(), this->top(), this->width(), this->height()); }
References height(), left(), top(), and width().
top()
virtual float dyno::byte_track::RectBase::top () const pure virtual
Implemented in dyno::byte_track::TlwhRect.
Referenced by operator cv::Rect(), and dyno::byte_track::KalmanFilter::rect_to_xyah().
width()
virtual float dyno::byte_track::RectBase::width () const pure virtual
Implemented in dyno::byte_track::TlwhRect.
Referenced by operator cv::Rect(), and dyno::byte_track::KalmanFilter::rect_to_xyah().
The documentation for this class was generated from the following file:
dynosam/include/dynosam/common/byte_tracker/Rect.hpp