DynoSAM: dyno::utils::Timer Class Reference
dyno::utils::Timer Class Reference
#include <Timing.hpp>
Public Types
using Clock = std::chrono::high_resolution_clock
Alias for high resolution clock.
using TimePoint = Clock::time_point
Alias for time point as defined by Timer::Clock.
Static Public Member Functions
static TimePoint tic ()
template<typename T = std::chrono::milliseconds>
static T toc (const TimePoint &start)
static double now ()
Time in seconds since epoch. Uses std::chrono::high_resolution_clock::now().
template<typename T = std::chrono::milliseconds>
static double toSeconds (const T &time)
Detailed Description
Definition at line 33 of file Timing.hpp.
Member Typedef Documentation
Clock
using dyno::utils::Timer::Clock = std::chrono::high_resolution_clock
Alias for high resolution clock.
Definition at line 37 of file Timing.hpp.
TimePoint
using dyno::utils::Timer::TimePoint = Clock::time_point
Alias for time point as defined by Timer::Clock.
Definition at line 39 of file Timing.hpp.
Member Function Documentation
now()
static double dyno::utils::Timer::now () inline static
Time in seconds since epoch. Uses std::chrono::high_resolution_clock::now().
Returns
double Time in seconds
Definition at line 60 of file Timing.hpp.
  {
    auto t_now = Clock::now().time_since_epoch();
    return static_cast<double>(std::chrono::duration_cast<std::chrono::nanoseconds>(t_now).count()) / 1e9;
  }
tic()
static TimePoint dyno::utils::Timer::tic () inline static
Definition at line 41 of file Timing.hpp.
  {
    return Clock::now();
  }
Referenced by dyno::ThreadsafeImuBuffer::getImuDataInterpolatedBordersBlocking(), dyno::MIMOPipelineModule< INPUT, OUTPUT >::pushOutputPacket(), and dyno::utils::TimingStatsCollector::reset().
toc()
template<typename T = std::chrono::milliseconds> static T dyno::utils::Timer::toc (const TimePoint & start) inline static
Definition at line 50 of file Timing.hpp.
  {
    return std::chrono::duration_cast<T>(Clock::now() - start);
  }
Referenced by dyno::MIMOPipelineModule< INPUT, OUTPUT >::pushOutputPacket().
toSeconds()
template<typename T = std::chrono::milliseconds> static double dyno::utils::Timer::toSeconds (const T & time) inline static
Definition at line 67 of file Timing.hpp.
  {
    auto seconds = std::chrono::duration_cast<std::chrono::seconds>(time);
    return static_cast<double>(seconds.count());
  }
The documentation for this class was generated from the following file:
dynosam/include/dynosam/utils/Timing.hpp