DynoSAM: dyno::DSDRos Class Reference
dyno::DSDRos Class Reference
Shorthand for Dynamic Slam Display ROS.
#include <DSDCommonRos.hpp>
Public Member Functions
DSDRos (const DisplayParams &params, rclcpp::Node::SharedPtr node)
void publishVisualOdometry (const gtsam::Pose3 &T_world_camera, Timestamp timestamp, const bool publish_tf)
void publishVisualOdometryPath (const gtsam::Pose3Vector &poses, Timestamp latest_timestamp)
CloudPerObject publishStaticPointCloud (const StatusLandmarkVector &landmarks, const gtsam::Pose3 &T_world_camera)
CloudPerObject publishDynamicPointCloud (const StatusLandmarkVector &landmarks, const gtsam::Pose3 &T_world_camera)
Protected Attributes
const DisplayParams params_
rclcpp::Node::SharedPtr node_
DSDTransport dsd_transport_
Dynamic SLAM display transport for estimated object odometry.
std::unique_ptr< tf2_ros::TransformBroadcaster > tf_broadcaster_
TF broadcaster for the odometry.
OdometryPub::SharedPtr vo_publisher_
PathPub::SharedPtr vo_path_publisher_
rclcpp::Publisher< sensor_msgs::msg::PointCloud2 >::SharedPtr static_points_pub_
rclcpp::Publisher< sensor_msgs::msg::PointCloud2 >::SharedPtr dynamic_points_pub_
Detailed Description
Shorthand for Dynamic Slam Display ROS.
Facilitates publishing to the following topics:
Visual odometry: "odometry"
Visual odometry path: "odometry_path"
Static point cloud: "static_cloud"
Dynamic point cloud: "dynamid_cloud"
Additionally cointains a tf2_ros::TransformBroadcaster to broadcast the visual odometry TF and a DSDTransport to publish the object odometry.
The namespace of the topic is dependant on the effective namespace of the node parsed in via the constructor.
Definition at line 227 of file DSDCommonRos.hpp.
Constructor & Destructor Documentation
DSDRos()
dyno::DSDRos::DSDRos (const DisplayParams & params, rclcpp::Node::SharedPtr node)
Definition at line 192 of file DSDCommonRos.cc.
    : params_(params), node_(node), dsd_transport_(node) {
  vo_publisher_ =
      node_->create_publisher<nav_msgs::msg::Odometry>("odometry", 1);
  vo_path_publisher_ =
      node_->create_publisher<nav_msgs::msg::Path>("odometry_path", 1);
  tf_broadcaster_ = std::make_unique<tf2_ros::TransformBroadcaster>(*node_);
  static_points_pub_ =
      node->create_publisher<sensor_msgs::msg::PointCloud2>("static_cloud", 1);
  dynamic_points_pub_ =
      node->create_publisher<sensor_msgs::msg::PointCloud2>("dynamic_cloud", 1);
}
References dynamic_points_pub_, node_, static_points_pub_, tf_broadcaster_, vo_path_publisher_, and vo_publisher_.
Member Function Documentation
publishDynamicPointCloud()
CloudPerObject dyno::DSDRos::publishDynamicPointCloud (const StatusLandmarkVector & landmarks, const gtsam::Pose3 & T_world_camera)
Definition at line 234 of file DSDCommonRos.cc.
{
  return DisplayCommon::publishPointCloud(
      dynamic_points_pub_, landmarks, T_world_camera, params_.world_frame_id);
}
References dynamic_points_pub_, params_, dyno::DisplayCommon::publishPointCloud(), and dyno::DisplayParams::world_frame_id.
Referenced by dyno::FrontendDSDRos::processRGBDOutputpacket(), and dyno::BackendDSDRos::spinOnce().
publishStaticPointCloud()
CloudPerObject dyno::DSDRos::publishStaticPointCloud (const StatusLandmarkVector & landmarks, const gtsam::Pose3 & T_world_camera)
Definition at line 229 of file DSDCommonRos.cc.
{
  return DisplayCommon::publishPointCloud(
      static_points_pub_, landmarks, T_world_camera, params_.world_frame_id);
}
References params_, dyno::DisplayCommon::publishPointCloud(), static_points_pub_, and dyno::DisplayParams::world_frame_id.
Referenced by dyno::FrontendDSDRos::processRGBDOutputpacket(), and dyno::BackendDSDRos::spinOnce().
publishVisualOdometry()
void dyno::DSDRos::publishVisualOdometry (const gtsam::Pose3 & T_world_camera, Timestamp timestamp, const bool publish_tf)
Definition at line 206 of file DSDCommonRos.cc.
{
  DisplayCommon::publishOdometry(vo_publisher_, T_world_camera, timestamp,
                                 params_.world_frame_id,
                                 params_.camera_frame_id);
  if (publish_tf) {
    geometry_msgs::msg::TransformStamped t;
    dyno::convert<gtsam::Pose3, geometry_msgs::msg::TransformStamped>(
        T_world_camera, t);
    t.header.stamp = node_->now();
    t.header.frame_id = params_.world_frame_id;
    t.child_frame_id = params_.camera_frame_id;
    tf_broadcaster_->sendTransform(t);
  }
}
References dyno::DisplayParams::camera_frame_id, node_, params_, dyno::DisplayCommon::publishOdometry(), tf_broadcaster_, vo_publisher_, and dyno::DisplayParams::world_frame_id.
Referenced by dyno::BackendDSDRos::spinOnce(), and dyno::FrontendDSDRos::tryPublishVisualOdometry().
publishVisualOdometryPath()
void dyno::DSDRos::publishVisualOdometryPath (const gtsam::Pose3Vector & poses, Timestamp latest_timestamp)
Definition at line 223 of file DSDCommonRos.cc.
{
  DisplayCommon::publishOdometryPath(vo_path_publisher_, poses,
                                     latest_timestamp, params_.world_frame_id);
}
References params_, dyno::DisplayCommon::publishOdometryPath(), vo_path_publisher_, and dyno::DisplayParams::world_frame_id.
Referenced by dyno::FrontendDSDRos::processRGBDOutputpacket(), and dyno::BackendDSDRos::spinOnce().
Member Data Documentation
dsd_transport_
DSDTransport dyno::DSDRos::dsd_transport_ protected
Dynamic SLAM display transport for estimated object odometry.
Definition at line 255 of file DSDCommonRos.hpp.
Referenced by dyno::FrontendDSDRos::processRGBDOutputpacket(), and dyno::BackendDSDRos::spinOnce().
dynamic_points_pub_
rclcpp::Publisher<sensor_msgs::msg::PointCloud2>::SharedPtr dyno::DSDRos::dynamic_points_pub_ protected
Definition at line 265 of file DSDCommonRos.hpp.
Referenced by DSDRos(), and publishDynamicPointCloud().
node_
rclcpp::Node::SharedPtr dyno::DSDRos::node_ protected
Definition at line 253 of file DSDCommonRos.hpp.
Referenced by DSDRos(), and publishVisualOdometry().
params_
const DisplayParams dyno::DSDRos::params_ protected
Definition at line 252 of file DSDCommonRos.hpp.
Referenced by dyno::FrontendDSDRos::processRGBDOutputpacket(), publishDynamicPointCloud(), publishStaticPointCloud(), publishVisualOdometry(), publishVisualOdometryPath(), dyno::BackendDSDRos::spinOnce(), and dyno::FrontendDSDRos::tryPublishGroundTruth().
static_points_pub_
rclcpp::Publisher<sensor_msgs::msg::PointCloud2>::SharedPtr dyno::DSDRos::static_points_pub_ protected
Definition at line 263 of file DSDCommonRos.hpp.
Referenced by DSDRos(), and publishStaticPointCloud().
tf_broadcaster_
std::unique_ptr<tf2_ros::TransformBroadcaster> dyno::DSDRos::tf_broadcaster_ protected
TF broadcaster for the odometry.
Definition at line 257 of file DSDCommonRos.hpp.
Referenced by DSDRos(), and publishVisualOdometry().
vo_path_publisher_
PathPub::SharedPtr dyno::DSDRos::vo_path_publisher_ protected
Definition at line 260 of file DSDCommonRos.hpp.
Referenced by DSDRos(), and publishVisualOdometryPath().
vo_publisher_
OdometryPub::SharedPtr dyno::DSDRos::vo_publisher_ protected
Definition at line 259 of file DSDCommonRos.hpp.
Referenced by DSDRos(), and publishVisualOdometry().
The documentation for this class was generated from the following files:
dynosam_ros/include/dynosam_ros/displays/dynamic_slam_displays/DSDCommonRos.hpp
dynosam_ros/src/displays/dynamic_slam_displays/DSDCommonRos.cc