DynoSAM: dyno::OMDDataLoader Class Reference
dyno::OMDDataLoader Class Reference
Data loader for the oxford multi motion (omd) datasets as provided at: https://robotic-esp.com/datasets/omd/#tools-id.
#include <OMDDataProvider.hpp>
Public Member Functions
OMDDataLoader (const fs::path &dataset_path)
Construct a new Cluster Slam Data Loader object.
CameraParams::Optional getCameraParams () const override
Provides functionality to get camera paramters for the main pipeline, as these may be available from the dataset.
Public Member Functions inherited from dyno::DynoDatasetProvider< DataTypes >
DynoDatasetProvider (const fs::path &dataset_path)
virtual ~DynoDatasetProvider ()=default
void setStartingFrame (int starting_frame)
void setEndingFrame (int ending_frame)
void reset ()
Resets the dataset to the "start", such that the next call to spin will begin the dataset again from the starting frame id. The starting/ending id will return to whatever the last call to setStartingFrame/setEndingFrame set the values to, or default if they have not been called.
virtual int datasetSize () const override
Get the size of the dataset - if this is not valid (i.e. the provider is online) this function should return -1.
virtual bool spin () override
Spins the dataset for one "step" of the dataset.
size_t getActiveFrameId () const
size_t getEndingFrameId () const
Public Member Functions inherited from dyno::DynoDataset< DataTypes... >
DynoDataset (const fs::path &dataset_path)
Fully defined tuple type containing all the dataset types in order starting with the default types.
virtual ~DynoDataset ()
virtual void setLoaders (TimestampBaseLoader::Ptr timestamp_loader, dyno::DataFolder< cv::Mat >::Ptr rgb_loader, dyno::DataFolder< cv::Mat >::Ptr optical_flow_loader, typename DataFolder< DataTypes >::Ptr... data_folders)
bool isProviderValid () const
Returns true when setLoaders(...) has been called and the internal datasets have been constructed correctly After this point spin() and getDatasetSize() can be called as they use the laoded datasets.
virtual size_t getDatasetSize () const
const std::string getDatasetPath () const
bool processSingle (size_t frame_id)
auto getLoader ()
Public Member Functions inherited from dyno::_DynoDatasetConstructor< Timestamp, cv::Mat, cv::Mat, DataTypes... >
virtual ~_DynoDatasetConstructor ()
void setCallback (const DataInputCallback &data_input_callback)
Public Member Functions inherited from dyno::DataProvider
DataProvider ()=default
DataProvider (DataInterfacePipeline *module)
DataProvider (DataInterfacePipelineImu *module)
virtual ~DataProvider ()
void registerImuSingleCallback (const ImuSingleInputCallback &callback)
void registerImuMultiCallback (const ImuMultiInputCallback &callback)
void registerImageContainerCallback (const ImageContainerCallback &callback)
void registerGroundTruthPacketCallback (const GroundTruthPacketCallback &callback)
virtual ImageContainer::Ptr imageContainerPreprocessor (ImageContainer::Ptr image_container)
Virtual Image Container Preprocessor function that is registered to the data interface pipeline.
void registerOnFinishCallback (const std::function< void()> &callback)
virtual int datasetSize () const =0
Get the size of the dataset - if this is not valid (i.e. the provider is online) this function should return -1.
virtual bool spin ()=0
Spins the dataset for one "step" of the dataset.
virtual void shutdown ()
virtual CameraParams::Optional getCameraParams () const
Provides functionality to get camera paramters for the main pipeline, as these may be available from the dataset.
Private Attributes
CameraParams left_camera_params_
Additional Inherited Members
Public Types inherited from dyno::DynoDatasetProvider< DataTypes >
using BaseDynoDataset = DynoDataset< DataTypes... >
using This = DynoDatasetProvider< DataTypes... >
Public Types inherited from dyno::DynoDataset< DataTypes... >
using TypedGenericDataset = GenericDataset< DataTypes... >
using DefaultDataset = GenericDataset< Timestamp, cv::Mat, cv::Mat >
using Base = _DynoDatasetConstructor< Timestamp, cv::Mat, cv::Mat, DataTypes... >
using DynoDataTypesTuple = typename Base::DynoDataTypesTuple
using GenericDatasetType = typename TypedGenericDataset::DataType< I >
Index in Default Dataset.
using DefaultDatasetType = typename DefaultDataset::DataType< I >
The type stored at the tuple idnex of the DefaultDataset.
using This = DynoDataset< DataTypes... >
Public Types inherited from dyno::_DynoDatasetConstructor< Timestamp, cv::Mat, cv::Mat, DataTypes... >
using DynoDataTypesTuple = std::tuple< DynoDataTypes... >
using DataInputCallback = std::function< bool(size_t, const DynoDataTypes...)>
All the dyno datypes in one definition (default at the start and then the optional ones)
Public Types inherited from dyno::DataProvider
using ImageContainerCallback = std::function< void(ImageContainer::Ptr)>
using ImuSingleInputCallback = std::function< void(const ImuMeasurement &)>
using ImuMultiInputCallback = std::function< void(const ImuMeasurements &)>
using GroundTruthPacketCallback = std::function< void(const GroundTruthInputPacket &)>
Public Attributes inherited from dyno::_DynoDatasetConstructor< Timestamp, cv::Mat, cv::Mat, DataTypes... >
DataInputCallback data_input_callback_
Static Public Attributes inherited from dyno::DynoDataset< DataTypes... >
static constexpr size_t TimestampFileIdx
All the dataypes declared in one tuple (Timestamp, cv::Mat, cv::Mat, ....)
static constexpr size_t RGBFolderIdx
static constexpr size_t OpticalFlowFolderIdx
Index in Default Dataset.
Protected Member Functions inherited from dyno::DynoDatasetProvider< DataTypes >
void setLoaders (TimestampBaseLoader::Ptr timestamp_loader, dyno::DataFolder< cv::Mat >::Ptr rgb_loader, dyno::DataFolder< cv::Mat >::Ptr optical_flow_loader, typename DataFolder< DataTypes >::Ptr... data_folders) override
Protected Member Functions inherited from dyno::DataProvider
void emitOnFinishCallbacks ()
Protected Attributes inherited from dyno::DataProvider
ImageContainerCallback image_container_callback_
ImuSingleInputCallback imu_single_input_callback_
ImuMultiInputCallback imu_multi_input_callback_
GroundTruthPacketCallback ground_truth_packet_callback_
std::atomic_bool shutdown_ = {false}
Detailed Description
Data loader for the oxford multi motion (omd) datasets as provided at: https://robotic-esp.com/datasets/omd/#tools-id.
Definition at line 44 of file OMDDataProvider.hpp.
Constructor & Destructor Documentation
OMDDataLoader()
dyno::OMDDataLoader::OMDDataLoader (const fs::path & dataset_path)
Construct a new Cluster Slam Data Loader object.
Datasset is ordered as per the https://robotic-esp.com/datasets/omd/#tools-id and the dataset path is /path/to/dataset/ /rgbd /raw_depth /vicon.csv .... /optical_flow /instance_masks
The last two folders are not provided in the original dataset and are pre-processed using DynoSAM-Preprocessing
Parameters
dataset_path Top left path to the dataset eg /path/to/omd, where
Definition at line 1294 of file OMDDataProvider.cc.
                                                       : OMDDatasetProvider(dataset_path) {
    LOG(INFO) << "Starting OMDDataLoader with path" << dataset_path;
    //this would go out of scope but we capture it in the functional loaders
    auto loader = std::make_shared<OMDOldAllLoader>(dataset_path);
    auto timestamp_loader = std::make_shared<OMMTimestampLoader>(loader);
    left_camera_params_ = loader->getLeftCameraParams();
    CHECK(getCameraParams());
    auto rgb_loader = std::make_shared<FunctionalDataFolder<cv::Mat>>(
        [loader](size_t idx) {
            return loader->getRGB(idx);
        }
    );
    auto optical_flow_loader = std::make_shared<FunctionalDataFolder<cv::Mat>>(
        [loader](size_t idx) {
            return loader->getOpticalFlow(idx);
        }
    );
    auto depth_loader = std::make_shared<FunctionalDataFolder<cv::Mat>>(
        [loader](size_t idx) {
            return loader->getDepthImage(idx);
        }
    );
    auto instance_mask_loader = std::make_shared<FunctionalDataFolder<cv::Mat>>(
        [loader](size_t idx) {
            return loader->getInstanceMask(idx);
        }
    );
    auto gt_loader = std::make_shared<FunctionalDataFolder<GroundTruthInputPacket>>(
        [loader](size_t idx) {
            return loader->getGtPacket(idx);
        }
    );
    this->setLoaders(
        timestamp_loader,
        rgb_loader,
        optical_flow_loader,
        depth_loader,
        instance_mask_loader,
        gt_loader
    );
    auto callback = [&](size_t frame_id,
        Timestamp timestamp,
        cv::Mat rgb,
        cv::Mat optical_flow,
        cv::Mat depth,
        cv::Mat instance_mask,
        GroundTruthInputPacket gt_object_pose_gt) -> bool
    {
        CHECK_EQ(timestamp, gt_object_pose_gt.timestamp_);
        CHECK(ground_truth_packet_callback_);
        if(ground_truth_packet_callback_) ground_truth_packet_callback_(gt_object_pose_gt);
        ImageContainer::Ptr image_container = nullptr;
        image_container = ImageContainer::Create(
                timestamp,
                frame_id,
                ImageWrapper<ImageType::RGBMono>(rgb),
                ImageWrapper<ImageType::Depth>(depth),
                ImageWrapper<ImageType::OpticalFlow>(optical_flow),
                ImageWrapper<ImageType::MotionMask>(instance_mask));
        CHECK(image_container);
        CHECK(image_container_callback_);
        if(image_container_callback_) image_container_callback_(image_container);
        return true;
    };
    this->setCallback(callback);
    //first valid frame is 1
    // setStartingFrame(1u);
}
References dyno::ImageContainer::Create(), getCameraParams(), dyno::DataProvider::ground_truth_packet_callback_, dyno::DataProvider::image_container_callback_, left_camera_params_, dyno::_DynoDatasetConstructor< Timestamp, cv::Mat, cv::Mat, DataTypes... >::setCallback(), and dyno::DynoDatasetProvider< DataTypes >::setLoaders().
Member Function Documentation
getCameraParams()
CameraParams::Optional dyno::OMDDataLoader::getCameraParams () const inline override virtual
Provides functionality to get camera paramters for the main pipeline, as these may be available from the dataset.
By default returns std::nullopt but the derived data-provider can overwrite this and return the loaded params
Returns
CameraParams::Optional
Reimplemented from dyno::DataProvider.
Definition at line 68 of file OMDDataProvider.hpp.
{
        return left_camera_params_;
    }
References left_camera_params_.
Referenced by main(), and OMDDataLoader().
Member Data Documentation
left_camera_params_
CameraParams dyno::OMDDataLoader::left_camera_params_ private
Definition at line 73 of file OMDDataProvider.hpp.
Referenced by getCameraParams(), and OMDDataLoader().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/dataprovider/OMDDataProvider.hpp
dynosam/src/dataprovider/OMDDataProvider.cc