DynoSAM: dyno::DataInterfacePipeline Class Reference
dyno::DataInterfacePipeline Class Reference
Takes data, synchronizes it and sends it to the output queue which should be connected to the frontend User needs to implement InputConstSharedPtr getInputPacket() = 0; that takes data from the internal queues and processes them.
#include <DataInterfacePipeline.hpp>
Public Types
using MIMO = MIMOPipelineModule< FrontendInputPacketBase, FrontendInputPacketBase >
using OutputQueue = typename MIMO::OutputQueue
using ImageContainerPreprocesser = std::function< ImageContainer::Ptr(ImageContainer::Ptr)>
using PreQueueContainerCallback = std::function< void(const ImageContainer::Ptr)>
Public Types inherited from dyno::MIMOPipelineModule< FrontendInputPacketBase, FrontendInputPacketBase >
using Base = PipelineModule< FrontendInputPacketBase, FrontendInputPacketBase >
using This = MIMOPipelineModule< FrontendInputPacketBase, FrontendInputPacketBase >
using OutputRegistra = QueueRegistra< FrontendInputPacketBase >
using OutputCallback = std::function< void(const OutputConstSharedPtr &output)>
using OutputConstSharedPtr = typename OutputTypeTraits::TypeConstSharedPtr
The output is instead a shared ptr, since many users might need the output.
using InputConstSharedPtr = typename InputTypeTraits::TypeConstSharedPtr
using InputQueue = typename InputTypeTraits::TypeQueue
using OutputQueue = typename OutputTypeTraits::TypeQueue
Public Types inherited from dyno::PipelineModule< INPUT, OUTPUT >
using InputTypeTraits = PipelineTypeTraits< INPUT >
using OutputTypeTraits = PipelineTypeTraits< OUTPUT >
using InputConstSharedPtr = typename InputTypeTraits::TypeConstSharedPtr
using OutputConstSharedPtr = typename OutputTypeTraits::TypeConstSharedPtr
The output is instead a shared ptr, since many users might need the output.
using InputQueue = typename InputTypeTraits::TypeQueue
using OutputQueue = typename OutputTypeTraits::TypeQueue
using OnProcessCallback = std::function< void(const InputConstSharedPtr &, const OutputConstSharedPtr &)>
Public Types inherited from dyno::PipelineBase
using OnPipelineFailureCallback = std::function< void(ReturnCode)>
Public Types inherited from dyno::ImuInterfaceHandler
enum class FrameAction { Drop , Wait , Use , Shutdown }
Preferred step to take with current frame based on IMU status.
Public Member Functions
DataInterfacePipeline (bool parallel_run=false)
virtual ~DataInterfacePipeline ()=default
virtual FrontendInputPacketBase::ConstPtr getInputPacket () override
virtual void fillImageContainerQueue (ImageContainer::Ptr image_container)
void addGroundTruthPacket (const GroundTruthInputPacket &gt_packet)
void registerImageContainerPreprocessor (const ImageContainerPreprocesser &func)
void registerPreQueueContainerCallback (const PreQueueContainerCallback &func)
Public Member Functions inherited from dyno::MIMOPipelineModule< FrontendInputPacketBase, FrontendInputPacketBase >
MIMOPipelineModule (const std::string &module_name)
void registerOutputQueue (OutputQueue *output_queue)
OutputRegistra::Ptr getOutputRegistra ()
Constructs an output registra for the internal vector of output queues Basically provides a way to add queues to the pipeline separate to the pipeline itself. This is useful as the registra is only templated on the OUTPUT so we can simply any external templating which only concerns itself with output types.
Public Member Functions inherited from dyno::PipelineModule< INPUT, OUTPUT >
PipelineModule (const std::string &module_name)
virtual ~PipelineModule ()=default
PipelineBase::ReturnCode spinOnce () override
Spin the pipeline once.
void registerOnProcessCallback (const OnProcessCallback &callback)
Registers a function that will be called with the input and output data packets generated from a spinOnce() call.
Public Member Functions inherited from dyno::PipelineBase
PipelineBase (const std::string &module_name)
virtual ~PipelineBase ()=default
bool spin ()
Spins the pipeline via continuous calls to spinOnce until the pipeline is shutdown.
bool isWorking () const
Returns true if the pipeline is currently processing data or if these is still data to process. Checks is_thread_working_ and the overwritten hasWork() function.
bool isShutdown () const
Returns true if the pipeline has been shutdown by shutdown().
std::string getModuleName () const
Returns the given module name (for identifcation and debug printing)
virtual void shutdown ()
void registerOnFailureCallback (const OnPipelineFailureCallback &callback_)
Registers a callback to be triggered if spinOnce returns an invalid return code.
virtual void shutdownQueues ()=0
Virtual function that should shutdown all associated queues. Generally this should shutdown input queues.
virtual bool hasWork () const =0
Virtual function that should check if (any of the) input queues have work to do.
virtual ReturnCode spinOnce ()=0
Processes for one iteration of the pipeline.
Public Member Functions inherited from dyno::ImuInterfaceHandler
ImuInterfaceHandler ()
virtual ~ImuInterfaceHandler ()
virtual void fillImuQueue (const ImuMeasurements &imu_measurements)
virtual void fillImuQueue (const ImuMeasurement &imu_measurement)
Protected Member Functions
virtual void onShutdown ()
Protected Member Functions inherited from dyno::MIMOPipelineModule< FrontendInputPacketBase, FrontendInputPacketBase >
bool pushOutputPacket (const OutputConstSharedPtr &output_packet) const override
virtual InputConstSharedPtr getInputPacket ()=0
virtual OutputConstSharedPtr process (const InputConstSharedPtr &input)=0
virtual bool pushOutputPacket (const OutputConstSharedPtr &output_packet) const =0
Protected Member Functions inherited from dyno::ImuInterfaceHandler
FrameAction getTimeSyncedImuMeasurements (const Timestamp &timestamp, ImuMeasurements *imu_meas)
getTimeSyncedImuMeasurements Time synchronizes the IMU buffer with the given timestamp (this is typically the timestamp of a left img)
Protected Attributes
ThreadsafeQueue< ImageContainer::Ptr > packet_queue_
std::atomic_bool parallel_run_
std::map< FrameId, GroundTruthInputPacket > ground_truth_packets_
ImageContainerPreprocesser image_container_preprocessor_
PreQueueContainerCallback pre_queue_container_calback_
Protected Attributes inherited from dyno::PipelineBase
const std::string module_name_
std::atomic_bool is_thread_working_ { false }
Protected Attributes inherited from dyno::ImuInterfaceHandler
ThreadsafeImuBuffer imu_buffer_
Timestamp timestamp_last_frame_
Private Member Functions
MIMO::OutputConstSharedPtr process (const MIMO::InputConstSharedPtr &input) override
virtual bool hasWork () const override
Virtual function that should check if (any of the) input queues have work to do.
void shutdownQueues () override
Called when general shutdown of PipelineModule is triggered.
Detailed Description
Takes data, synchronizes it and sends it to the output queue which should be connected to the frontend User needs to implement InputConstSharedPtr getInputPacket() = 0; that takes data from the internal queues and processes them.
Definition at line 70 of file DataInterfacePipeline.hpp.
Member Typedef Documentation
ImageContainerPreprocesser
using dyno::DataInterfacePipeline::ImageContainerPreprocesser = std::function<ImageContainer::Ptr(ImageContainer::Ptr)>
Definition at line 81 of file DataInterfacePipeline.hpp.
MIMO
using dyno::DataInterfacePipeline::MIMO = MIMOPipelineModule<FrontendInputPacketBase, FrontendInputPacketBase>
Definition at line 77 of file DataInterfacePipeline.hpp.
OutputQueue
using dyno::DataInterfacePipeline::OutputQueue = typename MIMO::OutputQueue
Definition at line 79 of file DataInterfacePipeline.hpp.
PreQueueContainerCallback
using dyno::DataInterfacePipeline::PreQueueContainerCallback = std::function<void(const ImageContainer::Ptr)>
Definition at line 83 of file DataInterfacePipeline.hpp.
Constructor & Destructor Documentation
DataInterfacePipeline()
dyno::DataInterfacePipeline::DataInterfacePipeline (bool parallel_run = false)
Definition at line 40 of file DataInterfacePipeline.cc.
    : MIMO("data-interface"), parallel_run_(parallel_run) {}
~DataInterfacePipeline()
virtual dyno::DataInterfacePipeline::~DataInterfacePipeline () virtual default
Member Function Documentation
addGroundTruthPacket()
void dyno::DataInterfacePipeline::addGroundTruthPacket (const GroundTruthInputPacket & gt_packet) inline
Definition at line 107 of file DataInterfacePipeline.hpp.
{
    ground_truth_packets_[gt_packet.frame_id_] = gt_packet;
  }
References dyno::GroundTruthInputPacket::frame_id_, and ground_truth_packets_.
Referenced by dyno::DynoPipelineManager::DynoPipelineManager().
fillImageContainerQueue()
virtual void dyno::DataInterfacePipeline::fillImageContainerQueue (ImageContainer::Ptr image_container) inline virtual
Definition at line 94 of file DataInterfacePipeline.hpp.
{
    ImageContainer::Ptr processed_container = image_container;
    if (image_container_preprocessor_) {
      processed_container = image_container_preprocessor_(processed_container);
    }
    CHECK_NOTNULL(processed_container);
    if (pre_queue_container_calback_)
      pre_queue_container_calback_(processed_container);
    packet_queue_.push(processed_container);
  }
References image_container_preprocessor_, packet_queue_, pre_queue_container_calback_, and ThreadsafeQueue< T >::push().
Referenced by dyno::DynoPipelineManager::DynoPipelineManager().
getInputPacket()
FrontendInputPacketBase::ConstPtr dyno::DataInterfacePipeline::getInputPacket () override virtual
Implements dyno::PipelineModule< INPUT, OUTPUT >.
Definition at line 49 of file DataInterfacePipeline.cc.
{
  if (isShutdown()) {
    return nullptr;
  }
  utils::StatsCollector queue_size_stats("data-interface_queue_size #");
  queue_size_stats.AddSample(packet_queue_.size());
  bool queue_state;
  ImageContainer::Ptr packet = nullptr;
  if (parallel_run_) {
    queue_state = packet_queue_.pop(packet);
  } else {
    queue_state = packet_queue_.popBlocking(packet);
  }
  if (!queue_state) {
    //  LOG_EVERY_N(WARNING, 10)
    //     << "Module: " << MIMO::module_name_ << " - queue is down";
    return nullptr;
  }
  CHECK(packet);
  GroundTruthInputPacket::Optional ground_truth;
  if (ground_truth_packets_.find(packet->frameId()) !=
      ground_truth_packets_.end()) {
    VLOG(5) << "Gotten ground truth packet for frame id " << packet->frameId()
            << ", timestamp=" << packet->timestamp();
    ground_truth = ground_truth_packets_.at(packet->frameId());
  }
  const Timestamp& timestamp = packet->timestamp();
  ImuMeasurements::Optional imu_meas;
  imu_meas.emplace();
  FrameAction action = getTimeSyncedImuMeasurements(timestamp, &(*imu_meas));
  switch (action) {
    case FrameAction::Use:
      CHECK(imu_meas);
      break;
    case FrameAction::Wait:
    case FrameAction::Drop:
      imu_meas.reset();
      break;
  }
  auto frontend_input =
      std::make_shared<FrontendInputPacketBase>(packet, ground_truth);
  frontend_input->imu_measurements = imu_meas;
  return frontend_input;
}
References dyno::utils::StatsCollectorImpl::AddSample(), dyno::ImuInterfaceHandler::Drop, dyno::ImuInterfaceHandler::getTimeSyncedImuMeasurements(), ground_truth_packets_, dyno::PipelineBase::isShutdown(), packet_queue_, parallel_run_, ThreadsafeQueue< T >::pop(), ThreadsafeQueue< T >::popBlocking(), ThreadsafeQueueBase< T >::size(), dyno::ImuInterfaceHandler::Use, and dyno::ImuInterfaceHandler::Wait.
hasWork()
bool dyno::DataInterfacePipeline::hasWork () const override private virtual
Virtual function that should check if (any of the) input queues have work to do.
Returns
true
false
Implements dyno::PipelineBase.
Definition at line 102 of file DataInterfacePipeline.cc.
{
  return !packet_queue_.empty() && !packet_queue_.isShutdown();
}
References ThreadsafeQueueBase< T >::empty(), ThreadsafeQueueBase< T >::isShutdown(), and packet_queue_.
onShutdown()
virtual void dyno::DataInterfacePipeline::onShutdown () inline protected virtual
Definition at line 121 of file DataInterfacePipeline.hpp.
{}
Referenced by shutdownQueues().
process()
MIMO::OutputConstSharedPtr dyno::DataInterfacePipeline::process (const MIMO::InputConstSharedPtr & input) inline override private virtual
Implements dyno::PipelineModule< INPUT, OUTPUT >.
Definition at line 124 of file DataInterfacePipeline.hpp.
{
    return input;
  }
registerImageContainerPreprocessor()
void dyno::DataInterfacePipeline::registerImageContainerPreprocessor (const ImageContainerPreprocesser & func) inline
Definition at line 111 of file DataInterfacePipeline.hpp.
{
    image_container_preprocessor_ = func;
  }
References image_container_preprocessor_.
registerPreQueueContainerCallback()
void dyno::DataInterfacePipeline::registerPreQueueContainerCallback (const PreQueueContainerCallback & func) inline
Definition at line 115 of file DataInterfacePipeline.hpp.
{
    pre_queue_container_calback_ = func;
  }
References pre_queue_container_calback_.
shutdownQueues()
void dyno::DataInterfacePipeline::shutdownQueues () override private virtual
Called when general shutdown of PipelineModule is triggered.
Implements dyno::PipelineBase.
Definition at line 43 of file DataInterfacePipeline.cc.
{
  packet_queue_.shutdown();
  // call the virtual shutdown method for the derived dataprovider module
  this->onShutdown();
}
References onShutdown(), packet_queue_, and ThreadsafeQueueBase< T >::shutdown().
Member Data Documentation
ground_truth_packets_
std::map<FrameId, GroundTruthInputPacket> dyno::DataInterfacePipeline::ground_truth_packets_ protected
Definition at line 138 of file DataInterfacePipeline.hpp.
Referenced by addGroundTruthPacket(), and getInputPacket().
image_container_preprocessor_
ImageContainerPreprocesser dyno::DataInterfacePipeline::image_container_preprocessor_ protected
Definition at line 145 of file DataInterfacePipeline.hpp.
Referenced by fillImageContainerQueue(), and registerImageContainerPreprocessor().
packet_queue_
ThreadsafeQueue<ImageContainer::Ptr> dyno::DataInterfacePipeline::packet_queue_ protected
Definition at line 135 of file DataInterfacePipeline.hpp.
Referenced by fillImageContainerQueue(), getInputPacket(), hasWork(), and shutdownQueues().
parallel_run_
std::atomic_bool dyno::DataInterfacePipeline::parallel_run_ protected
Definition at line 136 of file DataInterfacePipeline.hpp.
Referenced by getInputPacket().
pre_queue_container_calback_
PreQueueContainerCallback dyno::DataInterfacePipeline::pre_queue_container_calback_ protected
Function that is called immediately before the ImageContainer is put into the packet_queue_
Definition at line 148 of file DataInterfacePipeline.hpp.
Referenced by fillImageContainerQueue(), and registerPreQueueContainerCallback().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/dataprovider/DataInterfacePipeline.hpp
dynosam/src/dataprovider/DataInterfacePipeline.cc