DynoSAM: dyno::utils::Statistics Class Reference
dyno::utils::Statistics Class Reference
#include <Statistics.hpp>
Public Types
typedef std::map< std::string, size_t > map_t
Static Public Member Functions
static std::vector< std::string > getTagByModule (std::string const &module="")
Gets a vector of tags by module. A module is the parent name of a tag separated by ".". Each tag is considered a namespace (like in ROS) so we can specify/log statistics into modules. e.g. backend.spin is a full tag, and the module would be backend. We can then write out all stats within this module. Modules are dynamically added as new timers are added and Statistics will sort out the namespacing under the the hood!
static size_t GetHandle (std::string const &tag)
static bool HasHandle (std::string const &tag)
static std::string GetTag (size_t handle)
static double GetLastValue (size_t handle)
static double GetLastValue (std::string const &tag)
static double GetTotal (size_t handle)
static double GetTotal (std::string const &tag)
static double GetMean (size_t handle)
static double GetMean (std::string const &tag)
static std::vector< double > GetAllSamples (size_t handle)
static std::vector< double > GetAllSamples (std::string const &tag)
static size_t GetNumSamples (size_t handle)
static size_t GetNumSamples (std::string const &tag)
static double GetVariance (size_t handle)
static double GetVariance (std::string const &tag)
static double GetMin (size_t handle)
static double GetMin (std::string const &tag)
static double GetMax (size_t handle)
static double GetMax (std::string const &tag)
static double GetMedian (size_t handle)
static double GetMedian (std::string const &tag)
static double GetQ1 (size_t handle)
static double GetQ1 (std::string const &tag)
static double GetQ3 (size_t handle)
static double GetQ3 (std::string const &tag)
static double GetHz (size_t handle)
static double GetHz (std::string const &tag)
static double GetMeanDeltaTime (std::string const &tag)
static double GetMeanDeltaTime (size_t handle)
static double GetMaxDeltaTime (std::string const &tag)
static double GetMaxDeltaTime (size_t handle)
static double GetMinDeltaTime (std::string const &tag)
static double GetMinDeltaTime (size_t handle)
static double GetLastDeltaTime (std::string const &tag)
static double GetLastDeltaTime (size_t handle)
static double GetVarianceDeltaTime (std::string const &tag)
static double GetVarianceDeltaTime (size_t handle)
static void WriteAllSamplesToCsvFile (const std::string &path)
static void WriteSummaryToCsvFile (const std::string &path)
static void WritePerModuleSummariesToCsvFile (const std::string &folder_path)
static void WriteToYamlFile (const std::string &path)
static void Print (std::ostream &out)
static std::string Print ()
static std::string SecondsToTimeString (double seconds)
static void Reset ()
static const map_t & GetStatsCollectors ()
Private Types
typedef std::vector< utils::StatisticsMapValue > list_t
Private Member Functions
void AddSample (size_t handle, double sample)
Statistics ()
~Statistics ()
Static Private Member Functions
static void SummaryWriterHelper (CsvWriter &writer, const map_t::value_type &tag)
static std::optional< std::string > getModuleNameFromTag (const std::string &module)
Gets the module name from the tag. If the tag does not have a module (e.g. backend-pipeline has no "." seperator) and is then considered to be in the "global" namespace and an empty string is returned.
static Statistics & Instance ()
Private Attributes
list_t stats_collectors_
map_t tag_map_
size_t max_tag_length_
std::mutex mutex_
Friends
class StatsCollectorImpl
Detailed Description
Definition at line 177 of file Statistics.hpp.
Member Typedef Documentation
list_t
typedef std::vector<utils::StatisticsMapValue> dyno::utils::Statistics::list_t private
Definition at line 285 of file Statistics.hpp.
map_t
typedef std::map<std::string, size_t> dyno::utils::Statistics::map_t
Definition at line 179 of file Statistics.hpp.
Constructor & Destructor Documentation
Statistics()
dyno::utils::Statistics::Statistics () private
Definition at line 77 of file Statistics.cc.
: max_tag_length_(0) {}
~Statistics()
dyno::utils::Statistics::~Statistics () private
Definition at line 79 of file Statistics.cc.
{}
Member Function Documentation
AddSample()
void dyno::utils::Statistics::AddSample (size_t handle, double sample) private
Definition at line 153 of file Statistics.cc.
{
  std::lock_guard<std::mutex> lock(Instance().mutex_);
  stats_collectors_[handle].AddValue(seconds);
}
References Instance(), mutex_, and stats_collectors_.
Referenced by dyno::utils::StatsCollectorImpl::AddSample(), and dyno::utils::StatsCollectorImpl::IncrementOne().
GetAllSamples() [1/2]
std::vector< double > dyno::utils::Statistics::GetAllSamples (size_t handle) static
Definition at line 185 of file Statistics.cc.
{
  std::lock_guard<std::mutex> lock(Instance().mutex_);
  return Instance().stats_collectors_[handle].GetAllValues();
}
References Instance(), mutex_, and stats_collectors_.
Referenced by GetAllSamples(), and WriteAllSamplesToCsvFile().
GetAllSamples() [2/2]
std::vector< double > dyno::utils::Statistics::GetAllSamples (std::string const & tag) static
Definition at line 189 of file Statistics.cc.
{
  return GetAllSamples(GetHandle(tag));
}
References GetAllSamples(), and GetHandle().
GetHandle()
size_t dyno::utils::Statistics::GetHandle (std::string const & tag) static
Definition at line 82 of file Statistics.cc.
{
  std::lock_guard<std::mutex> lock(Instance().mutex_);
  // Search for an existing tag.
  map_t::iterator i = Instance().tag_map_.find(tag);
  if (i == Instance().tag_map_.end()) {
    // If it is not there, create a tag.
    size_t handle = Instance().stats_collectors_.size();
    Instance().tag_map_[tag] = handle;
    Instance().stats_collectors_.push_back(StatisticsMapValue());
    // Track the maximum tag length to help printing a table of values later.
    Instance().max_tag_length_ =
        std::max(Instance().max_tag_length_, tag.size());
    return handle;
  } else {
    return i->second;
  }
}
References Instance(), max_tag_length_, mutex_, stats_collectors_, and tag_map_.
Referenced by GetAllSamples(), GetHz(), GetLastDeltaTime(), GetLastValue(), GetMax(), GetMaxDeltaTime(), GetMean(), GetMeanDeltaTime(), GetMedian(), GetMin(), GetMinDeltaTime(), GetNumSamples(), GetQ1(), GetQ3(), GetTotal(), GetVariance(), and GetVarianceDeltaTime().
GetHz() [1/2]
double dyno::utils::Statistics::GetHz (size_t handle) static
Definition at line 234 of file Statistics.cc.
{
  std::lock_guard<std::mutex> lock(Instance().mutex_);
  return Instance().stats_collectors_[handle].MeanCallsPerSec();
}
References Instance(), mutex_, and stats_collectors_.
Referenced by GetHz(), Print(), and SummaryWriterHelper().
GetHz() [2/2]
double dyno::utils::Statistics::GetHz (std::string const & tag) static
Definition at line 238 of file Statistics.cc.
{
  return GetHz(GetHandle(tag));
}
References GetHandle(), and GetHz().
GetLastDeltaTime() [1/2]
double dyno::utils::Statistics::GetLastDeltaTime (size_t handle) static
Definition at line 267 of file Statistics.cc.
{
  std::lock_guard<std::mutex> lock(Instance().mutex_);
  return Instance().stats_collectors_[handle].GetLastDeltaTime();
}
References Instance(), mutex_, and stats_collectors_.
GetLastDeltaTime() [2/2]
double dyno::utils::Statistics::GetLastDeltaTime (std::string const & tag) static
Definition at line 264 of file Statistics.cc.
{
  return GetLastDeltaTime(GetHandle(tag));
}
References GetHandle(), and GetLastDeltaTime().
Referenced by GetLastDeltaTime().
GetLastValue() [1/2]
double dyno::utils::Statistics::GetLastValue (size_t handle) static
Definition at line 157 of file Statistics.cc.
{
  std::lock_guard<std::mutex> lock(Instance().mutex_);
  return Instance().stats_collectors_[handle].GetLastValue();
}
References Instance(), mutex_, and stats_collectors_.
Referenced by GetLastValue().
GetLastValue() [2/2]
double dyno::utils::Statistics::GetLastValue (std::string const & tag) static
Definition at line 161 of file Statistics.cc.
{
  return GetLastValue(GetHandle(tag));
}
References GetHandle(), and GetLastValue().
GetMax() [1/2]
double dyno::utils::Statistics::GetMax (size_t handle) static
Definition at line 206 of file Statistics.cc.
{
  std::lock_guard<std::mutex> lock(Instance().mutex_);
  return Instance().stats_collectors_[handle].Max();
}
References Instance(), mutex_, and stats_collectors_.
Referenced by GetMax(), Print(), SummaryWriterHelper(), and WriteToYamlFile().
GetMax() [2/2]
double dyno::utils::Statistics::GetMax (std::string const & tag) static
Definition at line 210 of file Statistics.cc.
{
  return GetMax(GetHandle(tag));
}
References GetHandle(), and GetMax().
GetMaxDeltaTime() [1/2]
double dyno::utils::Statistics::GetMaxDeltaTime (size_t handle) static
Definition at line 253 of file Statistics.cc.
{
  std::lock_guard<std::mutex> lock(Instance().mutex_);
  return Instance().stats_collectors_[handle].MaxDeltaTime();
}
References Instance(), mutex_, and stats_collectors_.
GetMaxDeltaTime() [2/2]
double dyno::utils::Statistics::GetMaxDeltaTime (std::string const & tag) static
Definition at line 250 of file Statistics.cc.
{
  return GetMaxDeltaTime(GetHandle(tag));
}
References GetHandle(), and GetMaxDeltaTime().
Referenced by GetMaxDeltaTime().
GetMean() [1/2]
double dyno::utils::Statistics::GetMean (size_t handle) static
Definition at line 171 of file Statistics.cc.
{
  std::lock_guard<std::mutex> lock(Instance().mutex_);
  return Instance().stats_collectors_[handle].Mean();
}
References Instance(), mutex_, and stats_collectors_.
Referenced by GetMean(), Print(), SummaryWriterHelper(), and WriteToYamlFile().
GetMean() [2/2]
double dyno::utils::Statistics::GetMean (std::string const & tag) static
Definition at line 175 of file Statistics.cc.
{
  return GetMean(GetHandle(tag));
}
References GetHandle(), and GetMean().
GetMeanDeltaTime() [1/2]
double dyno::utils::Statistics::GetMeanDeltaTime (size_t handle) static
Definition at line 246 of file Statistics.cc.
{
  std::lock_guard<std::mutex> lock(Instance().mutex_);
  return Instance().stats_collectors_[handle].MeanDeltaTime();
}
References Instance(), mutex_, and stats_collectors_.
GetMeanDeltaTime() [2/2]
double dyno::utils::Statistics::GetMeanDeltaTime (std::string const & tag) static
Definition at line 243 of file Statistics.cc.
{
  return GetMeanDeltaTime(GetHandle(tag));
}
References GetHandle(), and GetMeanDeltaTime().
Referenced by GetMeanDeltaTime().
GetMedian() [1/2]
double dyno::utils::Statistics::GetMedian (size_t handle) static
Definition at line 213 of file Statistics.cc.
{
  std::lock_guard<std::mutex> lock(Instance().mutex_);
  return Instance().stats_collectors_[handle].Median();
}
References Instance(), mutex_, and stats_collectors_.
Referenced by GetMedian(), and WriteToYamlFile().
GetMedian() [2/2]
double dyno::utils::Statistics::GetMedian (std::string const & tag) static
Definition at line 217 of file Statistics.cc.
{
  return GetMedian(GetHandle(tag));
}
References GetHandle(), and GetMedian().
GetMin() [1/2]
double dyno::utils::Statistics::GetMin (size_t handle) static
Definition at line 199 of file Statistics.cc.
{
  std::lock_guard<std::mutex> lock(Instance().mutex_);
  return Instance().stats_collectors_[handle].Min();
}
References Instance(), mutex_, and stats_collectors_.
Referenced by GetMin(), Print(), SummaryWriterHelper(), and WriteToYamlFile().
GetMin() [2/2]
double dyno::utils::Statistics::GetMin (std::string const & tag) static
Definition at line 203 of file Statistics.cc.
{
  return GetMin(GetHandle(tag));
}
References GetHandle(), and GetMin().
GetMinDeltaTime() [1/2]
double dyno::utils::Statistics::GetMinDeltaTime (size_t handle) static
Definition at line 260 of file Statistics.cc.
{
  std::lock_guard<std::mutex> lock(Instance().mutex_);
  return Instance().stats_collectors_[handle].MinDeltaTime();
}
References Instance(), mutex_, and stats_collectors_.
GetMinDeltaTime() [2/2]
double dyno::utils::Statistics::GetMinDeltaTime (std::string const & tag) static
Definition at line 257 of file Statistics.cc.
{
  return GetMinDeltaTime(GetHandle(tag));
}
References GetHandle(), and GetMinDeltaTime().
Referenced by GetMinDeltaTime().
getModuleNameFromTag()
std::optional< std::string > dyno::utils::Statistics::getModuleNameFromTag (const std::string & module) static private
Gets the module name from the tag. If the tag does not have a module (e.g. backend-pipeline has no "." seperator) and is then considered to be in the "global" namespace and an empty string is returned.
Parameters
tag
Returns
std::string
Definition at line 506 of file Statistics.cc.
{
  size_t pos = tag.find('.');
  if (pos != std::string::npos) {
      return tag.substr(0, pos);
  }
  return {};
}
Referenced by getTagByModule(), and WritePerModuleSummariesToCsvFile().
GetNumSamples() [1/2]
size_t dyno::utils::Statistics::GetNumSamples (size_t handle) static
Definition at line 178 of file Statistics.cc.
{
  std::lock_guard<std::mutex> lock(Instance().mutex_);
  return Instance().stats_collectors_[handle].TotalSamples();
}
References Instance(), mutex_, and stats_collectors_.
Referenced by GetNumSamples(), Print(), SummaryWriterHelper(), WriteAllSamplesToCsvFile(), and WriteToYamlFile().
GetNumSamples() [2/2]
size_t dyno::utils::Statistics::GetNumSamples (std::string const & tag) static
Definition at line 182 of file Statistics.cc.
{
  return GetNumSamples(GetHandle(tag));
}
References GetHandle(), and GetNumSamples().
GetQ1() [1/2]
double dyno::utils::Statistics::GetQ1 (size_t handle) static
Definition at line 220 of file Statistics.cc.
{
  std::lock_guard<std::mutex> lock(Instance().mutex_);
  return Instance().stats_collectors_[handle].Q1();
}
References Instance(), mutex_, and stats_collectors_.
Referenced by GetQ1(), and WriteToYamlFile().
GetQ1() [2/2]
double dyno::utils::Statistics::GetQ1 (std::string const & tag) static
Definition at line 224 of file Statistics.cc.
{
  return GetQ1(GetHandle(tag));
}
References GetHandle(), and GetQ1().
GetQ3() [1/2]
double dyno::utils::Statistics::GetQ3 (size_t handle) static
Definition at line 227 of file Statistics.cc.
{
  std::lock_guard<std::mutex> lock(Instance().mutex_);
  return Instance().stats_collectors_[handle].Q1();
}
References Instance(), mutex_, and stats_collectors_.
Referenced by GetQ3(), and WriteToYamlFile().
GetQ3() [2/2]
double dyno::utils::Statistics::GetQ3 (std::string const & tag) static
Definition at line 231 of file Statistics.cc.
{
  return GetQ3(GetHandle(tag));
}
References GetHandle(), and GetQ3().
GetStatsCollectors()
static const map_t & dyno::utils::Statistics::GetStatsCollectors () inline static
Definition at line 249 of file Statistics.hpp.
{ return Instance().tag_map_; }
References Instance(), and tag_map_.
Referenced by getTagByModule().
GetTag()
std::string dyno::utils::Statistics::GetTag (size_t handle) static
Definition at line 109 of file Statistics.cc.
{
  std::lock_guard<std::mutex> lock(Instance().mutex_);
  std::string tag;
  // Perform a linear search for the tag.
  for (typename map_t::value_type current_tag : Instance().tag_map_) {
    if (current_tag.second == handle) {
      return current_tag.first;
    }
  }
  return tag;
}
References Instance(), mutex_, and tag_map_.
getTagByModule()
std::vector< std::string > dyno::utils::Statistics::getTagByModule (std::string const & module = "") static
Gets a vector of tags by module. A module is the parent name of a tag separated by ".". Each tag is considered a namespace (like in ROS) so we can specify/log statistics into modules. e.g. backend.spin is a full tag, and the module would be backend. We can then write out all stats within this module. Modules are dynamically added as new timers are added and Statistics will sort out the namespacing under the the hood!
If query module s empty, return only those tags in the global namespace.
Parameters
module
Returns
std::vector<std::string>
Definition at line 134 of file Statistics.cc.
{
  std::vector<std::string> modules;
  std::lock_guard<std::mutex> lock(Instance().mutex_);
  for(const auto&[tag, _] : GetStatsCollectors()) {
    std::optional<std::string> module = getModuleNameFromTag(tag);
    //if query module is empty match with those tags in the global namespace
    if(query_module.empty() && !module) {
      modules.push_back(tag);
    }
    else if(module && *module == query_module) {
      modules.push_back(tag);
    }
  }
  return modules;
}
References getModuleNameFromTag(), GetStatsCollectors(), Instance(), and mutex_.
GetTotal() [1/2]
double dyno::utils::Statistics::GetTotal (size_t handle) static
Definition at line 164 of file Statistics.cc.
{
  std::lock_guard<std::mutex> lock(Instance().mutex_);
  return Instance().stats_collectors_[handle].Sum();
}
References Instance(), mutex_, and stats_collectors_.
Referenced by GetTotal().
GetTotal() [2/2]
double dyno::utils::Statistics::GetTotal (std::string const & tag) static
Definition at line 168 of file Statistics.cc.
{
  return GetTotal(GetHandle(tag));
}
References GetHandle(), and GetTotal().
GetVariance() [1/2]
double dyno::utils::Statistics::GetVariance (size_t handle) static
Definition at line 192 of file Statistics.cc.
{
  std::lock_guard<std::mutex> lock(Instance().mutex_);
  return Instance().stats_collectors_[handle].LazyVariance();
}
References Instance(), mutex_, and stats_collectors_.
Referenced by GetVariance(), Print(), SummaryWriterHelper(), and WriteToYamlFile().
GetVariance() [2/2]
double dyno::utils::Statistics::GetVariance (std::string const & tag) static
Definition at line 196 of file Statistics.cc.
{
  return GetVariance(GetHandle(tag));
}
References GetHandle(), and GetVariance().
GetVarianceDeltaTime() [1/2]
double dyno::utils::Statistics::GetVarianceDeltaTime (size_t handle) static
Definition at line 274 of file Statistics.cc.
{
  std::lock_guard<std::mutex> lock(Instance().mutex_);
  return Instance().stats_collectors_[handle].LazyVarianceDeltaTime();
}
References Instance(), mutex_, and stats_collectors_.
GetVarianceDeltaTime() [2/2]
double dyno::utils::Statistics::GetVarianceDeltaTime (std::string const & tag) static
Definition at line 271 of file Statistics.cc.
{
  return GetVarianceDeltaTime(GetHandle(tag));
}
References GetHandle(), and GetVarianceDeltaTime().
Referenced by GetVarianceDeltaTime().
HasHandle()
bool dyno::utils::Statistics::HasHandle (std::string const & tag) static
Definition at line 103 of file Statistics.cc.
{
  std::lock_guard<std::mutex> lock(Instance().mutex_);
  bool tag_found = Instance().tag_map_.count(tag);
  return tag_found;
}
References Instance(), mutex_, and tag_map_.
Instance()
Statistics & dyno::utils::Statistics::Instance () static private
Definition at line 72 of file Statistics.cc.
{
  static Statistics instance;
  return instance;
}
Referenced by dyno::utils::StatsCollectorImpl::AddSample(), AddSample(), GetAllSamples(), GetHandle(), GetHz(), GetLastDeltaTime(), GetLastValue(), GetMax(), GetMaxDeltaTime(), GetMean(), GetMeanDeltaTime(), GetMedian(), GetMin(), GetMinDeltaTime(), GetNumSamples(), GetQ1(), GetQ3(), GetStatsCollectors(), GetTag(), getTagByModule(), GetTotal(), GetVariance(), GetVarianceDeltaTime(), HasHandle(), dyno::utils::StatsCollectorImpl::IncrementOne(), Print(), Reset(), WriteAllSamplesToCsvFile(), WritePerModuleSummariesToCsvFile(), WriteSummaryToCsvFile(), and WriteToYamlFile().
Print() [1/2]
std::string dyno::utils::Statistics::Print () static
Definition at line 494 of file Statistics.cc.
{
  std::stringstream ss;
  Print(ss);
  return ss.str();
}
References Print().
Referenced by dyno::DynoNode::getStats(), and Print().
Print() [2/2]
void dyno::utils::Statistics::Print (std::ostream & out) static
Definition at line 305 of file Statistics.cc.
                                      {  // NOLINT
  const map_t& tag_map = Instance().tag_map_;
  if (tag_map.empty()) {
    return;
  }
  out << "Statistics\n";
  out.width((std::streamsize)Instance().max_tag_length_);
  out.setf(std::ios::left, std::ios::adjustfield);
  out << "-----------";
  out.width(7);
  out.setf(std::ios::right, std::ios::adjustfield);
  out << "#\t";
  out << "Log Hz\t";
  out << "{avg     +- std    }\t";
  out << "[min,max]\n";
  for (const typename map_t::value_type& t : tag_map) {
    size_t i = t.second;
    out.width((std::streamsize)Instance().max_tag_length_);
    out.setf(std::ios::left, std::ios::adjustfield);
    // Print Name of tag
    out << t.first << "\t";
    out.setf(std::ios::right, std::ios::adjustfield);
    // Print #
    out << std::setw(5) << GetNumSamples(i) << "\t";
    if (GetNumSamples(i) > 0) {
      out << std::showpoint << GetHz(i) << "\t";
      double mean = GetMean(i);
      double stddev = sqrt(GetVariance(i));
      out << "{" << std::showpoint << mean;
      out << " +- ";
      out << std::showpoint << stddev << "}\t";
      double min_value = GetMin(i);
      double max_value = GetMax(i);
      //out.width(5);
      out << std::noshowpoint << "[" << min_value << "," << max_value << "]";
    }
    out << std::endl;
  }
}
References GetHz(), GetMax(), GetMean(), GetMin(), GetNumSamples(), GetVariance(), Instance(), max_tag_length_, and tag_map_.
Reset()
void dyno::utils::Statistics::Reset () static
Definition at line 500 of file Statistics.cc.
                       {
  std::lock_guard<std::mutex> lock(Instance().mutex_);
  Instance().tag_map_.clear();
}
References Instance(), mutex_, and tag_map_.
SecondsToTimeString()
std::string dyno::utils::Statistics::SecondsToTimeString (double seconds) static
Definition at line 279 of file Statistics.cc.
{
  double secs = fmod(seconds, 60);
  int minutes = (seconds / 60);
  int hours = (seconds / 3600);
  minutes = minutes - (hours * 60);
  char buffer[256];
  snprintf(buffer,
           sizeof(buffer),
#ifdef SM_TIMING_SHOW_HOURS
           "%02d:"
#endif
#ifdef SM_TIMING_SHOW_MINUTES
           "%02d:"
#endif
           "%09.6f",
#ifdef SM_TIMING_SHOW_HOURS
           hours,
#endif
#ifdef SM_TIMING_SHOW_MINUTES
           minutes,
#endif
           secs);
  return buffer;
}
SummaryWriterHelper()
static void dyno::utils::Statistics::SummaryWriterHelper (CsvWriter & writer, const map_t::value_type & tag) inline static private
Definition at line 256 of file Statistics.hpp.
{
    const size_t& index = tag.second;
    const std::string& label = tag.first;
    if (GetNumSamples(index) > 0) {
      writer << label
             << GetNumSamples(index)
             << GetHz(index)
             << GetMean(index)
             << sqrt(GetVariance(index))
             << GetMin(index)
             << GetMax(index);
    }
  }
References GetHz(), GetMax(), GetMean(), GetMin(), GetNumSamples(), and GetVariance().
Referenced by WritePerModuleSummariesToCsvFile(), and WriteSummaryToCsvFile().
WriteAllSamplesToCsvFile()
void dyno::utils::Statistics::WriteAllSamplesToCsvFile (const std::string & path) static
Definition at line 352 of file Statistics.cc.
{
  const map_t& tag_map = Instance().tag_map_;
  if (tag_map.empty()) {
    return;
  }
  static const CsvHeader header("label", "samples");
  CsvWriter writer(header);
  VLOG(1) << "Writing statistics to file: " << path;
  for (const map_t::value_type& tag : tag_map) {
    const size_t& index = tag.second;
    if (GetNumSamples(index) > 0) {
      const std::string& label = tag.first;
      // // Add header to csv file. tag.first is the stats label.
      writer << label;
      // Each row has all samples.
      std::stringstream ss;
      const std::vector<double>& samples = GetAllSamples(index);
      for (const auto& sample : samples) {
        //make space separated so not to confuse the CsvWriter
        //treat all samples as a single column
        ss << ' ' << sample;
      }
      writer << ss.str();
    }
  }
  writer.write(path);
}
References GetAllSamples(), GetNumSamples(), Instance(), tag_map_, and dyno::CsvWriter::write().
Referenced by dyno::writeStatisticsSamplesToFile().
WritePerModuleSummariesToCsvFile()
void dyno::utils::Statistics::WritePerModuleSummariesToCsvFile (const std::string & folder_path) static
Definition at line 444 of file Statistics.cc.
{
  const map_t& tag_map = Instance().tag_map_;
  if (tag_map.empty()) {
    return;
  }
  static const CsvHeader header("label", "num samples", "log Hz", "mean", "stddev", "min", "max");
  std::map<std::string, CsvWriter::Ptr> module_to_writer;
  CsvWriter global_writer(header);
  for (const map_t::value_type& tag : tag_map) {
    std::optional<std::string> module_name = getModuleNameFromTag(tag.first);
    // writer to use
    CsvWriter* writer;
    if(module_name) {
      //tag is not in global namespace so use the specificied namespace
      //if we dont have a writer for this module, make one
      if(module_to_writer.find(*module_name) == module_to_writer.end()) {
        module_to_writer[*module_name] = std::make_shared<CsvWriter>(header);
      }
      //set writer to use
      writer = module_to_writer.at(*module_name).get();
    }
    else {
      //no module name so use the global namespace
      writer = &global_writer;
    }
    CHECK_NOTNULL(writer);
    SummaryWriterHelper(*writer, tag);
  }
  //write out all summaries
  for(auto& [module_name, writer] : module_to_writer) {
    std::string full_path = fs::path(folder_path) / std::string("stats_" + module_name + ".csv");
    LOG(INFO) << "Writing out csv stats module: " << full_path;
    writer->write(full_path);
  }
  {
    std::string full_path = fs::path(folder_path) / "stats_global.csv";
    LOG(INFO) << "Writing out csv stats module: " << full_path;
    global_writer.write(full_path);
  }
}
References getModuleNameFromTag(), Instance(), SummaryWriterHelper(), tag_map_, and dyno::CsvWriter::write().
Referenced by dyno::writeStatisticsModuleSummariesToFile().
WriteSummaryToCsvFile()
void dyno::utils::Statistics::WriteSummaryToCsvFile (const std::string & path) static
Definition at line 387 of file Statistics.cc.
{
  const map_t& tag_map = Instance().tag_map_;
  if (tag_map.empty()) {
    return;
  }
  static const CsvHeader header("label", "num samples", "log Hz", "mean", "stddev", "min", "max");
  CsvWriter writer(header);
  for (const map_t::value_type& tag : tag_map) {
    SummaryWriterHelper(writer, tag);
  }
  writer.write(path);
}
References Instance(), SummaryWriterHelper(), tag_map_, and dyno::CsvWriter::write().
Referenced by dyno::writeStatisticsSummaryToFile().
WriteToYamlFile()
void dyno::utils::Statistics::WriteToYamlFile (const std::string & path) static
Definition at line 405 of file Statistics.cc.
{
  std::ofstream output_file(path);
  if (!output_file) {
    LOG(ERROR) << "Could not write statistics: Unable to open file: " << path;
    return;
  }
  const map_t& tag_map = Instance().tag_map_;
  if (tag_map.empty()) {
    return;
  }
  VLOG(1) << "Writing statistics to file: " << path;
  for (const map_t::value_type& tag : tag_map) {
    const size_t index = tag.second;
    if (GetNumSamples(index) > 0) {
      std::string label = tag.first;
      // We do not want colons or hashes in a label, as they might interfere
      // with reading the yaml later.
      std::replace(label.begin(), label.end(), ':', '_');
      std::replace(label.begin(), label.end(), '#', '_');
      output_file << label << ":\n";
      output_file << "  samples: " << GetNumSamples(index) << "\n";
      output_file << "  mean: " << GetMean(index) << "\n";
      output_file << "  stddev: " << sqrt(GetVariance(index)) << "\n";
      output_file << "  min: " << GetMin(index) << "\n";
      output_file << "  max: " << GetMax(index) << "\n";
      output_file << "  median: " << GetMedian(index) << "\n";
      output_file << "  q1: " << GetQ1(index) << "\n";
      output_file << "  q3: " << GetQ3(index) << "\n";
    }
    output_file << "\n";
  }
}
References GetMax(), GetMean(), GetMedian(), GetMin(), GetNumSamples(), GetQ1(), GetQ3(), GetVariance(), Instance(), and tag_map_.
Friends And Related Function Documentation
StatsCollectorImpl
friend class StatsCollectorImpl friend
Definition at line 180 of file Statistics.hpp.
Member Data Documentation
max_tag_length_
size_t dyno::utils::Statistics::max_tag_length_ private
Definition at line 289 of file Statistics.hpp.
Referenced by GetHandle(), and Print().
mutex_
std::mutex dyno::utils::Statistics::mutex_ private
Definition at line 290 of file Statistics.hpp.
Referenced by AddSample(), GetAllSamples(), GetHandle(), GetHz(), GetLastDeltaTime(), GetLastValue(), GetMax(), GetMaxDeltaTime(), GetMean(), GetMeanDeltaTime(), GetMedian(), GetMin(), GetMinDeltaTime(), GetNumSamples(), GetQ1(), GetQ3(), GetTag(), getTagByModule(), GetTotal(), GetVariance(), GetVarianceDeltaTime(), HasHandle(), and Reset().
stats_collectors_
list_t dyno::utils::Statistics::stats_collectors_ private
Definition at line 287 of file Statistics.hpp.
Referenced by AddSample(), GetAllSamples(), GetHandle(), GetHz(), GetLastDeltaTime(), GetLastValue(), GetMax(), GetMaxDeltaTime(), GetMean(), GetMeanDeltaTime(), GetMedian(), GetMin(), GetMinDeltaTime(), GetNumSamples(), GetQ1(), GetQ3(), GetTotal(), GetVariance(), and GetVarianceDeltaTime().
tag_map_
map_t dyno::utils::Statistics::tag_map_ private
Definition at line 288 of file Statistics.hpp.
Referenced by GetHandle(), GetStatsCollectors(), GetTag(), HasHandle(), Print(), Reset(), WriteAllSamplesToCsvFile(), WritePerModuleSummariesToCsvFile(), WriteSummaryToCsvFile(), and WriteToYamlFile().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/utils/Statistics.hpp
dynosam/src/utils/Statistics.cc