DynoSAM: dyno::ObjectMotionSovler Class Reference
dyno::ObjectMotionSovler Class Reference
#include <MotionSolver.hpp>
Classes
struct Params
Public Member Functions
ObjectMotionSovler (const Params &params, const CameraParams &camera_params)
Pose3SolverResult geometricOutlierRejection3d2d (Frame::Ptr frame_k_1, Frame::Ptr frame_k, const gtsam::Pose3 &T_world_k, ObjectId object_id)
Pose3SolverResult geometricOutlierRejection3d3d (Frame::Ptr frame_k_1, Frame::Ptr frame_k, const gtsam::Pose3 &T_world_k, ObjectId object_id)
Pose3SolverResult motionModelOutlierRejection3d2d (const AbsolutePoseCorrespondences &dynamic_correspondences, Frame::Ptr frame_k_1, Frame::Ptr frame_k, const gtsam::Pose3 &T_world_k, ObjectId object_id)
Protected Attributes
const Params object_motion_params
Protected Attributes inherited from dyno::EgoMotionSolver
const Params params_
const CameraParams camera_params_
Additional Inherited Members
Protected Member Functions inherited from dyno::EgoMotionSolver
template<typename Ref , typename Curr >
void constructTrackletInliers (TrackletIds &inliers, TrackletIds &outliers, const GenericCorrespondences< Ref, Curr > &correspondences, const std::vector< int > &ransac_inliers, const TrackletIds tracklets)
EgoMotionSolver (const Params &params, const CameraParams &camera_params)
virtual ~EgoMotionSolver ()=default
Pose3SolverResult geometricOutlierRejection2d2d (Frame::Ptr frame_k_1, Frame::Ptr frame_k, std::optional< gtsam::Rot3 > R_curr_ref={})
Runs 2d-2d PnP with optional Rotation (ie. from IMU)
Pose3SolverResult geometricOutlierRejection3d2d (Frame::Ptr frame_k_1, Frame::Ptr frame_k, std::optional< gtsam::Rot3 > R_curr_ref={})
Runs 3d-2d PnP with optional Rotation (i.e from IMU)
Pose3SolverResult geometricOutlierRejection3d2d (const AbsolutePoseCorrespondences &correspondences, std::optional< gtsam::Rot3 > R_curr_ref={})
Pose3SolverResult geometricOutlierRejection3d3d (Frame::Ptr frame_k_1, Frame::Ptr frame_k, std::optional< gtsam::Rot3 > R_curr_ref={})
Pose3SolverResult geometricOutlierRejection3d3d (const PointCloudCorrespondences &correspondences, std::optional< gtsam::Rot3 > R_curr_ref={})
Detailed Description
Definition at line 336 of file MotionSolver.hpp.
Constructor & Destructor Documentation
ObjectMotionSovler()
dyno::ObjectMotionSovler::ObjectMotionSovler (const Params & params, const CameraParams & camera_params)
Definition at line 431 of file MotionSolver.cc.
    : EgoMotionSolver(static_cast<const EgoMotionSolver::Params&>(params),
                      camera_params) {}
Member Function Documentation
geometricOutlierRejection3d2d()
Pose3SolverResult dyno::ObjectMotionSovler::geometricOutlierRejection3d2d (Frame::Ptr frame_k_1, Frame::Ptr frame_k, const gtsam::Pose3 & T_world_k, ObjectId object_id)
Definition at line 436 of file MotionSolver.cc.
{
  utils::TimingStatsCollector timer("motion_solver.object_solve3d2d");
  AbsolutePoseCorrespondences dynamic_correspondences;
  // get the corresponding feature pairs
  bool corr_result = frame_k->getDynamicCorrespondences(
      dynamic_correspondences, *frame_k_1, object_id,
      frame_k->landmarkWorldKeypointCorrespondance());
  const size_t& n_matches = dynamic_correspondences.size();
  TrackletIds all_tracklets;
  std::transform(dynamic_correspondences.begin(), dynamic_correspondences.end(),
                 std::back_inserter(all_tracklets),
                 [](const AbsolutePoseCorrespondence& corres) {
                   return corres.tracklet_id_;
                 });
  CHECK_EQ(all_tracklets.size(), n_matches);
  Pose3SolverResult geometric_result =
      EgoMotionSolver::geometricOutlierRejection3d2d(dynamic_correspondences);
  Pose3SolverResult result = geometric_result;
  // if(geometric_result.status == TrackingStatus::VALID &&
  // motion_model_result.status == TrackingStatus::VALID) {
  //     if(geometric_result.inliers.size() >=
  //     motion_model_result.inliers.size()) {
  //         VLOG(10) << "Geometric model used (inliers " <<
  //         geometric_result.inliers.size() << " vs " <<
  //         motion_model_result.inliers.size(); result = geometric_result;
  //     }
  //     else {
  //         VLOG(10) << "Motion motion model used (inliers " <<
  //         motion_model_result.inliers.size() << " vs " <<
  //         geometric_result.inliers.size(); result = motion_model_result;
  //     }
  // }
  // //if no motion model, fall back on gemoetric result
  // else {
  //     result = geometric_result;
  // }
  if (result.status == TrackingStatus::VALID) {
    TrackletIds refined_inlier_tracklets = result.inliers;
    {
      // debug only (just checking that the inlier/outliers we get from the
      // geometric rejection match the original one)
      TrackletIds extracted_all_tracklets = refined_inlier_tracklets;
      extracted_all_tracklets.insert(extracted_all_tracklets.end(),
                                     result.outliers.begin(),
                                     result.outliers.end());
      CHECK_EQ(all_tracklets.size(), extracted_all_tracklets.size());
    }
    gtsam::Pose3 G_w = result.best_result.inverse();
    if (object_motion_params.refine_motion_with_joint_of) {
      OpticalFlowAndPoseOptimizer flow_optimizer(
          object_motion_params.joint_of_params);
      // Use the original result as the input to the refine joint optical flow
      // function the result.best_result variable is actually equivalent to
      // ^wG^{-1} and we want to solve something in the form e(T, flow) =
      // [u,v]_{k-1} + {k-1}_flow_k - pi(T^{-1}^wm_{k-1}) so T must take the
      // point from k-1 in the world frame to the local frame at k-1 ^wG^{-1} =
      //^wX_k \: {k-1}^wH_k (which takes does this) but the error term uses the
      // inverse of T hence we must parse in the inverse of G
      auto flow_opt_result = flow_optimizer.optimizeAndUpdate<CalibrationType>(
          frame_k_1, frame_k, refined_inlier_tracklets, result.best_result);
      // still need to take the inverse as we get the inverse of G out
      G_w = flow_opt_result.best_result.refined_pose.inverse();
      // inliers should be a subset of the original refined inlier tracks
      refined_inlier_tracklets = flow_opt_result.inliers;
    }
    // still need to take the inverse as we get the inverse of G out
    gtsam::Pose3 H_w = T_world_k * G_w;
    // if(params_.refine_object_motion_esimate) {
    if (object_motion_params.refine_motion_with_3d) {
      MotionOnlyRefinementOptimizer motion_refinement_graph(
          object_motion_params.object_motion_refinement_params);
      auto motion_refinement_result =
          motion_refinement_graph.optimizeAndUpdate<CalibrationType>(
              frame_k_1, frame_k, refined_inlier_tracklets, object_id, H_w);
      // should be further subset
      refined_inlier_tracklets = motion_refinement_result.inliers;
      H_w = motion_refinement_result.best_result;
    }
    // a lot of weird places where we mark things as inliers,take results of
    // some functions into others etc.. and is very confusion!
    // TODO: clean up!!!
    //  result = result_copy;
    result.best_result = H_w;
    result.inliers = refined_inlier_tracklets;
    determineOutlierIds(result.inliers, all_tracklets, result.outliers);
  }
  // if not valid, return motion result as is
  return result;
}
References dyno::SolverResult< T >::best_result, dyno::determineOutlierIds(), dyno::EgoMotionSolver::geometricOutlierRejection3d2d(), dyno::SolverResult< T >::inliers, dyno::ObjectMotionSovler::Params::joint_of_params, object_motion_params, dyno::ObjectMotionSovler::Params::object_motion_refinement_params, dyno::OpticalFlowAndPoseOptimizer::optimizeAndUpdate(), dyno::MotionOnlyRefinementOptimizer::optimizeAndUpdate(), dyno::SolverResult< T >::outliers, dyno::ObjectMotionSovler::Params::refine_motion_with_3d, dyno::ObjectMotionSovler::Params::refine_motion_with_joint_of, dyno::SolverResult< T >::status, and dyno::VALID.
Referenced by dyno::RGBDInstanceFrontendModule::solveObjectMotion().
geometricOutlierRejection3d3d()
Pose3SolverResult dyno::ObjectMotionSovler::geometricOutlierRejection3d3d (Frame::Ptr frame_k_1, Frame::Ptr frame_k, const gtsam::Pose3 & T_world_k, ObjectId object_id)
Definition at line 538 of file MotionSolver.cc.
{
  PointCloudCorrespondences dynamic_correspondences;
  // get the corresponding feature pairs
  bool corr_result = frame_k->getDynamicCorrespondences(
      dynamic_correspondences, *frame_k_1, object_id,
      frame_k->landmarkWorldPointCloudCorrespondance());
  const size_t& n_matches = dynamic_correspondences.size();
  Pose3SolverResult result;
  result =
      EgoMotionSolver::geometricOutlierRejection3d3d(dynamic_correspondences);
  if (result.status == TrackingStatus::VALID) {
    const gtsam::Pose3 G_w = result.best_result.inverse();
    const gtsam::Pose3 H_w = T_world_k * G_w;
    result.best_result = H_w;
  }
  // if not valid, return motion result as is
  return result;
}
References dyno::SolverResult< T >::best_result, dyno::EgoMotionSolver::geometricOutlierRejection3d3d(), dyno::SolverResult< T >::status, and dyno::VALID.
Referenced by dyno::RGBDInstanceFrontendModule::solveObjectMotion().
motionModelOutlierRejection3d2d()
Pose3SolverResult dyno::ObjectMotionSovler::motionModelOutlierRejection3d2d (const AbsolutePoseCorrespondences & dynamic_correspondences, Frame::Ptr frame_k_1, Frame::Ptr frame_k, const gtsam::Pose3 & T_world_k, ObjectId object_id)
Definition at line 564 of file MotionSolver.cc.
{
  Pose3SolverResult result;
  // get object motions in previous frame (so k-2 to k-1)
  const MotionEstimateMap& motion_estiamtes_k_1 = frame_k_1->motion_estimates_;
  if (!motion_estiamtes_k_1.exists(object_id)) {
    result.status = TrackingStatus::INVALID;
    return result;
  }
  // previous motion model: k-2 to k-1 in w
  const gtsam::Pose3 motion_model = motion_estiamtes_k_1.at(object_id);
  using Calibration = Camera::CalibrationType;
  const auto calibration =
      camera_params_.constructGtsamCalibration<Calibration>();
  auto I = gtsam::traits<gtsam::Pose3>::Identity();
  gtsam::PinholeCamera<Calibration> camera(I, calibration);
  const double reprojection_error = params_.ransac_threshold_pnp;
  TrackletIds tracklets;
  TrackletIds inlier_tracklets;
  utils::Accumulatord total_repr_error, inlier_repr_error;
  const size_t& n_matches = dynamic_correspondences.size();
  for (size_t i = 0u; i < n_matches; i++) {
    const AbsolutePoseCorrespondence& corres = dynamic_correspondences.at(i);
    tracklets.push_back(corres.tracklet_id_);
    const Keypoint& kp_k = corres.cur_;
    // the landmark int the world frame at k-1
    const Landmark& w_lmk_k_1 = corres.ref_;
    // using the motion, put the lmk in the world frame at k
    const Landmark w_lmk_k = motion_model * w_lmk_k_1;
    // using camera pose, put the lmk in the camera frame at k
    const Landmark c_lmk_c = T_world_k.inverse() * w_lmk_k;
    try {
      double repr_error = camera.reprojectionError(c_lmk_c, kp_k).squaredNorm();
      total_repr_error.Add(repr_error);
      if (repr_error < reprojection_error) {
        inlier_tracklets.push_back(corres.tracklet_id_);
        inlier_repr_error.Add(repr_error);
      }
    } catch (const gtsam::CheiralityException&) {
    }
  }
  TrackletIds outliers;
  determineOutlierIds(inlier_tracklets, tracklets, outliers);
  VLOG(20) << "(Object) motion model inliers/total(error) "
           << inlier_tracklets.size() << "(" << inlier_repr_error.Mean()
           << ") / " << tracklets.size() << "(" << total_repr_error.Mean()
           << ")";
  result.best_result = motion_model;
  result.inliers = inlier_tracklets;
  result.outliers = outliers;
  result.status = TrackingStatus::VALID;
  return result;
}
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::Add(), dyno::SolverResult< T >::best_result, dyno::EgoMotionSolver::camera_params_, dyno::CameraParams::constructGtsamCalibration(), dyno::TrackletCorrespondance< U, V >::cur_, dyno::determineOutlierIds(), dyno::SolverResult< T >::inliers, dyno::INVALID, dyno::utils::Accumulator< SampleType, SumType, WindowSize >::Mean(), dyno::SolverResult< T >::outliers, dyno::EgoMotionSolver::params_, dyno::EgoMotionSolver::Params::ransac_threshold_pnp, dyno::TrackletCorrespondance< U, V >::ref_, dyno::SolverResult< T >::status, dyno::TrackletCorrespondance< U, V >::tracklet_id_, and dyno::VALID.
Member Data Documentation
object_motion_params
const Params dyno::ObjectMotionSovler::object_motion_params protected
Definition at line 366 of file MotionSolver.hpp.
Referenced by geometricOutlierRejection3d2d().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/frontend/vision/MotionSolver.hpp
dynosam/src/frontend/vision/MotionSolver.cc