DynoSAM: dyno::DynoNode Class Reference
dyno::DynoNode Class Reference
#include <PipelineRos.hpp>
Public Member Functions
DynoNode (const std::string &node_name, const rclcpp::NodeOptions &options=rclcpp::NodeOptions())
virtual ~DynoNode ()=default
virtual bool spinOnce ()
std::string getStats () const
const DynoParams & getDynoParams ()
std::string getParamsPath ()
std::string getDatasetPath ()
Protected Member Functions
virtual dyno::DataProvider::Ptr createDataProvider ()
Private Member Functions
std::string searchForPathWithParams (const std::string &param_name, const std::string &default_path, const std::string &description="")
Retrieves a std::string param (under param_name) which is expected to be a file path.
Private Attributes
std::unique_ptr< DynoParams > dyno_params_
Detailed Description
Definition at line 43 of file PipelineRos.hpp.
Constructor & Destructor Documentation
DynoNode()
dyno::DynoNode::DynoNode (const std::string & node_name, const rclcpp::NodeOptions & options = rclcpp::NodeOptions()) explicit
Definition at line 50 of file PipelineRos.cc.
    : Node(node_name, "dynosam", options) {
  RCLCPP_INFO_STREAM(this->get_logger(), "Starting DynoNode");
  auto params_path = getParamsPath();
  RCLCPP_INFO_STREAM(this->get_logger(),
                     "Loading Dyno VO params from: " << params_path);
  dyno_params_ = std::make_unique<DynoParams>(params_path);
}
References dyno_params_, and getParamsPath().
~DynoNode()
virtual dyno::DynoNode::~DynoNode () virtual default
Member Function Documentation
createDataProvider()
dyno::DataProvider::Ptr dyno::DynoNode::createDataProvider () protected virtual
Definition at line 60 of file PipelineRos.cc.
{
  const bool online =
      ParameterConstructor(this, "online", false)
          .description("If the online DataProvider should be used")
          .finish()
          .get<bool>();
  if (online) {
    RCLCPP_INFO_STREAM(
        this->get_logger(),
        "Online DataProvider selected. Waiting for ROS topics...");
    OnlineDataProviderRosParams online_params;
    online_params.wait_for_camera_params =
        ParameterConstructor(this, "wait_for_camera_params",
                             online_params.wait_for_camera_params)
            .description(
                "If the online DataProvider should wait for the camera params "
                "on a ROS topic!")
            .finish()
            .get<bool>();
    online_params.camera_params_timeout =
        ParameterConstructor(this, "camera_params_timeout",
                             online_params.camera_params_timeout)
            .description(
                "When waiting for camera params, how long the online "
                "DataProvider should wait before time out (ms)")
            .finish()
            .get<int>();
    return std::make_shared<OnlineDataProviderRos>(
        this->create_sub_node("dataprovider"), online_params);
  }
  auto params_path = getParamsPath();
  auto dataset_path = getDatasetPath();
  auto dyno_params = getDynoParams();
  RCLCPP_INFO_STREAM(this->get_logger(),
                     "Loading dataset from: " << dataset_path);
  dyno::DataProvider::Ptr data_loader = dyno::DataProviderFactory::Create(
      dataset_path, params_path,
      static_cast<dyno::DatasetType>(dyno_params.dataProviderType()));
  RCLCPP_INFO_STREAM(this->get_logger(), "Constructed data loader");
  return data_loader;
}
References dyno::OnlineDataProviderRosParams::camera_params_timeout, dyno::DataProviderFactory::Create(), dyno::ParameterConstructor::description(), dyno::ParameterConstructor::finish(), dyno::ParameterDetails::get(), getDatasetPath(), getDynoParams(), getParamsPath(), and dyno::OnlineDataProviderRosParams::wait_for_camera_params.
Referenced by dyno::BackendExperimentsNode::BackendExperimentsNode(), and dyno::DynoPipelineManagerRos::initalisePipeline().
getDatasetPath()
std::string dyno::DynoNode::getDatasetPath () inline
Definition at line 63 of file PipelineRos.hpp.
{
    return searchForPathWithParams("dataset_path", "dataset",
                                   "Path to the dataset.");
  }
References searchForPathWithParams().
Referenced by createDataProvider().
getDynoParams()
const DynoParams & dyno::DynoNode::getDynoParams () inline
Definition at line 53 of file PipelineRos.hpp.
{
    CHECK_NOTNULL(dyno_params_);
    return *dyno_params_;
  }
References dyno_params_.
Referenced by dyno::BackendExperimentsNode::BackendExperimentsNode(), createDataProvider(), and dyno::DynoPipelineManagerRos::initalisePipeline().
getParamsPath()
std::string dyno::DynoNode::getParamsPath () inline
Definition at line 58 of file PipelineRos.hpp.
{
    return searchForPathWithParams("params_folder_path", "dynosam/params/",
                                   "Path to the folder containing the yaml "
                                   "files with the DynoVIO parameters.");
  }
References searchForPathWithParams().
Referenced by createDataProvider(), and DynoNode().
getStats()
std::string dyno::DynoNode::getStats () const inline
Definition at line 51 of file PipelineRos.hpp.
{ return utils::Statistics::Print(); }
References dyno::utils::Statistics::Print().
Referenced by dyno::DynoPipelineManagerRos::spinOnce(), and dyno::BackendExperimentsNode::spinOnce().
searchForPathWithParams()
std::string dyno::DynoNode::searchForPathWithParams (const std::string & param_name, const std::string & default_path, const std::string & description = "") private
Retrieves a std::string param (under param_name) which is expected to be a file path.
Parameters
param_name
default_path
description
Returns
std::string
Definition at line 106 of file PipelineRos.cc.
{
  // check if we've alrady declared this param
  // use non-default version so that ParameterConstructor throws exception if no
  // parameter is provided on the param server
  const std::string path = ParameterConstructor(this, param_name)
                               .description(description)
                               .finish()
                               .get<std::string>();
  throwExceptionIfPathInvalid(path);
  return path;
}
References dyno::ParameterConstructor::description(), dyno::ParameterConstructor::finish(), dyno::ParameterDetails::get(), and dyno::throwExceptionIfPathInvalid().
Referenced by getDatasetPath(), and getParamsPath().
spinOnce()
virtual bool dyno::DynoNode::spinOnce () inline virtual
Reimplemented in dyno::DynoPipelineManagerRos, and dyno::BackendExperimentsNode.
Definition at line 49 of file PipelineRos.hpp.
{ return true; }
Member Data Documentation
dyno_params_
std::unique_ptr<DynoParams> dyno::DynoNode::dyno_params_ private
Definition at line 86 of file PipelineRos.hpp.
Referenced by DynoNode(), and getDynoParams().
The documentation for this class was generated from the following files:
dynosam_ros/include/dynosam_ros/PipelineRos.hpp
dynosam_ros/src/PipelineRos.cc