DynoSAM: dyno::OfstreamWrapper Class Reference
dyno::OfstreamWrapper Class Reference
#include <Logger.hpp>
Public Member Functions
OfstreamWrapper (const std::string &filename, const bool &open_file_in_append_mode=false)
OfstreamWrapper (const std::string &filename, const std::string &output_path, const bool &open_file_in_append_mode=false)
virtual ~OfstreamWrapper ()
void closeAndOpenLogFile ()
fs::path getFilePath () const
Static Public Member Functions
static bool WriteOutCsvWriter (const CsvWriter &csv, const std::string &filename)
Public Attributes
const std::string filename_
const std::string output_path_
const bool open_file_in_append_mode_ = false
std::ofstream ofstream_
Protected Member Functions
void openLogFile (bool open_file_in_append_mode=false)
Detailed Description
Definition at line 128 of file Logger.hpp.
Constructor & Destructor Documentation
OfstreamWrapper() [1/2]
dyno::OfstreamWrapper::OfstreamWrapper (const std::string & filename, const bool & open_file_in_append_mode = false)
Definition at line 88 of file Logger.cc.
    : OfstreamWrapper(filename, FLAGS_output_path, open_file_in_append_mode) {}
OfstreamWrapper() [2/2]
dyno::OfstreamWrapper::OfstreamWrapper (const std::string & filename, const std::string & output_path, const bool & open_file_in_append_mode = false)
Definition at line 92 of file Logger.cc.
    : filename_(filename), output_path_(output_path) {
  openLogFile(open_file_in_append_mode);
}
References openLogFile().
~OfstreamWrapper()
dyno::OfstreamWrapper::~OfstreamWrapper () virtual
Definition at line 101 of file Logger.cc.
{
  VLOG(20) << "Closing output file: " << filename_.c_str();
  ofstream_.flush();
  ofstream_.close();
}
References filename_, and ofstream_.
Member Function Documentation
closeAndOpenLogFile()
void dyno::OfstreamWrapper::closeAndOpenLogFile ()
Definition at line 107 of file Logger.cc.
{
  ofstream_.flush();
  ofstream_.close();
  CHECK(!filename_.empty());
  OpenFile(output_path_ + '/' + filename_, &ofstream_, false);
}
References filename_, ofstream_, dyno::OpenFile(), and output_path_.
getFilePath()
fs::path dyno::OfstreamWrapper::getFilePath () const
Definition at line 129 of file Logger.cc.
{
  fs::path fs_out_path(output_path_);
  if (!fs::exists(fs_out_path))
    throw std::runtime_error("OfstreamWrapper - Output path does not exist: " +
                             output_path_);
  return fs_out_path / fs::path(filename_);
}
References filename_, and output_path_.
Referenced by openLogFile().
openLogFile()
void dyno::OfstreamWrapper::openLogFile (bool open_file_in_append_mode = false) protected
Definition at line 122 of file Logger.cc.
{
  CHECK(!filename_.empty());
  CHECK(!output_path_.empty());
  LOG(INFO) << "Opening output file: " << filename_.c_str();
  OpenFile((std::string)getFilePath(), &ofstream_, open_file_in_append_mode);
}
References filename_, getFilePath(), ofstream_, dyno::OpenFile(), and output_path_.
Referenced by OfstreamWrapper().
WriteOutCsvWriter()
bool dyno::OfstreamWrapper::WriteOutCsvWriter (const CsvWriter & csv, const std::string & filename) static
Definition at line 114 of file Logger.cc.
{
  // set append mode to false as we never want to write over the top of a csv
  // file as this will upset the header
  OfstreamWrapper ofsw(filename, false);
  return csv.write(ofsw.ofstream_);
}
References ofstream_, and dyno::CsvWriter::write().
Referenced by dyno::BackendLogger::~BackendLogger(), and dyno::EstimationModuleLogger::~EstimationModuleLogger().
Member Data Documentation
filename_
const std::string dyno::OfstreamWrapper::filename_
Definition at line 145 of file Logger.hpp.
Referenced by closeAndOpenLogFile(), getFilePath(), openLogFile(), and ~OfstreamWrapper().
ofstream_
std::ofstream dyno::OfstreamWrapper::ofstream_
Definition at line 149 of file Logger.hpp.
Referenced by closeAndOpenLogFile(), openLogFile(), WriteOutCsvWriter(), and ~OfstreamWrapper().
open_file_in_append_mode_
const bool dyno::OfstreamWrapper::open_file_in_append_mode_ = false
Definition at line 147 of file Logger.hpp.
output_path_
const std::string dyno::OfstreamWrapper::output_path_
Definition at line 146 of file Logger.hpp.
Referenced by closeAndOpenLogFile(), getFilePath(), and openLogFile().
The documentation for this class was generated from the following files:
dynosam_common/include/dynosam_common/logger/Logger.hpp
dynosam_common/src/logger/Logger.cc