DynoSAM: ThreadsafeQueueBase< T > Class Template Reference
ThreadsafeQueueBase< T > Class Template Reference abstract
#include <ThreadSafeQueue.hpp>
Public Member Functions
virtual bool push (T new_value)=0
Push by value. Returns false if the queue has been shutdown. Not optimal, since it will make two move operations. But it does the job: see Item 41 Effective Modern C++.
virtual bool pushBlockingIfFull (T new_value, size_t max_queue_size=10u)=0
pushBlockingIfFull pushes a value into the queue only if the queue is not filled with more than a given maximum size.
virtual bool popBlocking (T &value)=0
Pop value. Waits for data to be available in the queue. Returns false if the queue has been shutdown.
virtual std::shared_ptr< T > popBlocking ()=0
Pop value. Waits for data to be available in the queue. If the queue has been shutdown, it returns a null shared_ptr.
virtual bool popBlockingWithTimeout (T &value, size_t duration_ms)=0
virtual bool pop (T &value)=0
Pop without blocking, just checks once if the queue is empty. Returns true if the value could be retrieved, false otherwise.
virtual std::shared_ptr< T > pop ()=0
Pop without blocking, just checks once if the queue is empty. Returns a shared_ptr to the value retrieved. If the queue is empty or has been shutdown, it returns a null shared_ptr.
int size ()
void shutdown ()
bool isShutdown ()
void resume ()
bool empty () const
Checks if the queue is empty. the state of the queue might change right after this query.
void clear ()
bool isShutdown () const
Checks if the queue is shutdown. the state of the queue might change right after this query.
Protected Types
typedef std::queue< std::shared_ptr< T > > InternalQueue
Protected Member Functions
ThreadsafeQueueBase ()
virtual ~ThreadsafeQueueBase ()=default
Protected Attributes
std::mutex mutex_
InternalQueue data_queue_
mutable for empty() and copy-constructor.
std::condition_variable data_cond_
std::atomic_bool shutdown_
Detailed Description
template<typename T>
class ThreadsafeQueueBase< T >
Definition at line 44 of file ThreadSafeQueue.hpp.
Member Typedef Documentation
InternalQueue
template<typename T > typedef std::queue<std::shared_ptr<T> > ThreadsafeQueueBase< T >::InternalQueue protected
Definition at line 46 of file ThreadSafeQueue.hpp.
Constructor & Destructor Documentation
ThreadsafeQueueBase()
template<typename T > ThreadsafeQueueBase< T >::ThreadsafeQueueBase explicit protected
Definition at line 234 of file ThreadSafeQueue.hpp.
    : mutex_(), data_queue_(), data_cond_(), shutdown_(false) {}
~ThreadsafeQueueBase()
template<typename T > virtual ThreadsafeQueueBase< T >::~ThreadsafeQueueBase () protected virtual default
Member Function Documentation
clear()
template<typename T > void ThreadsafeQueueBase< T >::clear () inline
Definition at line 135 of file ThreadSafeQueue.hpp.
               {
    std::lock_guard<std::mutex> lk(mutex_);
    InternalQueue empty;
    std::swap(data_queue_, empty);
  }
References ThreadsafeQueueBase< T >::data_queue_, ThreadsafeQueueBase< T >::empty(), and ThreadsafeQueueBase< T >::mutex_.
empty()
template<typename T > bool ThreadsafeQueueBase< T >::empty () const inline
Checks if the queue is empty. the state of the queue might change right after this query.
Definition at line 129 of file ThreadSafeQueue.hpp.
                     {
    std::lock_guard<std::mutex> lk(mutex_);
    return data_queue_.empty();
  }
References ThreadsafeQueueBase< T >::data_queue_, and ThreadsafeQueueBase< T >::mutex_.
Referenced by ThreadsafeQueueBase< T >::clear(), and dyno::DataInterfacePipeline::hasWork().
isShutdown() [1/2]
template<typename T > bool ThreadsafeQueueBase< T >::isShutdown () inline
Definition at line 114 of file ThreadSafeQueue.hpp.
{ return shutdown_; }
References ThreadsafeQueueBase< T >::shutdown_.
Referenced by dyno::DataInterfacePipeline::hasWork().
isShutdown() [2/2]
template<typename T > bool ThreadsafeQueueBase< T >::isShutdown () const inline
Checks if the queue is shutdown. the state of the queue might change right after this query.
Definition at line 144 of file ThreadSafeQueue.hpp.
{
    std::lock_guard<std::mutex> lk(mutex_);
    return shutdown_;
  }
References ThreadsafeQueueBase< T >::mutex_, and ThreadsafeQueueBase< T >::shutdown_.
pop() [1/2]
template<typename T > virtual std::shared_ptr< T > ThreadsafeQueueBase< T >::pop () pure virtual
Pop without blocking, just checks once if the queue is empty. Returns a shared_ptr to the value retrieved. If the queue is empty or has been shutdown, it returns a null shared_ptr.
Implemented in ThreadsafeQueue< T >, ThreadsafeQueue< ImageContainer::Ptr >, and ThreadsafeQueue< ImageToDisplay >.
pop() [2/2]
template<typename T > virtual bool ThreadsafeQueueBase< T >::pop (T & value) pure virtual
Pop without blocking, just checks once if the queue is empty. Returns true if the value could be retrieved, false otherwise.
Implemented in ThreadsafeQueue< ImageContainer::Ptr >, ThreadsafeQueue< ImageToDisplay >, and ThreadsafeQueue< T >.
popBlocking() [1/2]
template<typename T > virtual std::shared_ptr< T > ThreadsafeQueueBase< T >::popBlocking () pure virtual
Pop value. Waits for data to be available in the queue. If the queue has been shutdown, it returns a null shared_ptr.
Implemented in ThreadsafeQueue< T >, ThreadsafeQueue< ImageContainer::Ptr >, and ThreadsafeQueue< ImageToDisplay >.
popBlocking() [2/2]
template<typename T > virtual bool ThreadsafeQueueBase< T >::popBlocking (T & value) pure virtual
Pop value. Waits for data to be available in the queue. Returns false if the queue has been shutdown.
Implemented in ThreadsafeQueue< ImageContainer::Ptr >, ThreadsafeQueue< ImageToDisplay >, and ThreadsafeQueue< T >.
popBlockingWithTimeout()
template<typename T > virtual bool ThreadsafeQueueBase< T >::popBlockingWithTimeout (T & value, size_t duration_ms) pure virtual
Implemented in ThreadsafeQueue< ImageContainer::Ptr >, ThreadsafeQueue< ImageToDisplay >, and ThreadsafeQueue< T >.
push()
template<typename T > virtual bool ThreadsafeQueueBase< T >::push (T new_value) pure virtual
Push by value. Returns false if the queue has been shutdown. Not optimal, since it will make two move operations. But it does the job: see Item 41 Effective Modern C++.
Alternatives: Using both:
push(const T&)
with push(T&&) rvalue to the queue using move semantics. Since there is no type deduction, T&& is NOT a universal reference (typename T is not at the level of the push function). Problem: virtual keyword will make push(T&&) be discarded for push(const T&), non-copyable things will compile-complain.
Implemented in ThreadsafeQueue< ImageContainer::Ptr >, ThreadsafeQueue< ImageToDisplay >, and ThreadsafeQueue< T >.
pushBlockingIfFull()
template<typename T > virtual bool ThreadsafeQueueBase< T >::pushBlockingIfFull (T new_value, size_t max_queue_size = 10u) pure virtual
pushBlockingIfFull pushes a value into the queue only if the queue is not filled with more than a given maximum size.
*
Parameters
new_value new value to add to the queue
max_queue_size if the queue is filled with more than max_queue_size messages, it will not push to the queue, and it will wait for a consumer to remove messages.
Returns
false if the queue has been shutdown
Implemented in ThreadsafeQueue< ImageContainer::Ptr >, ThreadsafeQueue< ImageToDisplay >, and ThreadsafeQueue< T >.
resume()
template<typename T > void ThreadsafeQueueBase< T >::resume () inline
Definition at line 116 of file ThreadSafeQueue.hpp.
                {
    std::unique_lock<std::mutex> mlock(mutex_);
    // Even if the shared variable is atomic, it must be modified under the
    // mutex in order to correctly publish the modification to the waiting
    // threads.
    shutdown_ = false;
    mlock.unlock();
    data_cond_.notify_all();
  }
References ThreadsafeQueueBase< T >::data_cond_, ThreadsafeQueueBase< T >::mutex_, and ThreadsafeQueueBase< T >::shutdown_.
shutdown()
template<typename T > void ThreadsafeQueueBase< T >::shutdown () inline
Definition at line 104 of file ThreadSafeQueue.hpp.
                  {
    std::unique_lock<std::mutex> mlock(mutex_);
    // Even if the shared variable is atomic, it must be modified under the
    // mutex in order to correctly publish the modification to the waiting
    // threads.
    shutdown_ = true;
    mlock.unlock();
    data_cond_.notify_all();
  }
References ThreadsafeQueueBase< T >::data_cond_, ThreadsafeQueueBase< T >::mutex_, and ThreadsafeQueueBase< T >::shutdown_.
Referenced by dyno::DynoPipelineManager::shutdownPipelines(), and dyno::DataInterfacePipeline::shutdownQueues().
size()
template<typename T > int ThreadsafeQueueBase< T >::size () inline
Definition at line 102 of file ThreadSafeQueue.hpp.
{ return data_queue_.size(); }
References ThreadsafeQueueBase< T >::data_queue_.
Referenced by dyno::DataInterfacePipeline::getInputPacket().
Member Data Documentation
data_cond_
template<typename T > std::condition_variable ThreadsafeQueueBase< T >::data_cond_ protected
Definition at line 152 of file ThreadSafeQueue.hpp.
Referenced by ThreadsafeQueueBase< T >::resume(), and ThreadsafeQueueBase< T >::shutdown().
data_queue_
template<typename T > InternalQueue ThreadsafeQueueBase< T >::data_queue_ protected
mutable for empty() and copy-constructor.
Definition at line 151 of file ThreadSafeQueue.hpp.
Referenced by ThreadsafeQueueBase< T >::clear(), ThreadsafeQueueBase< T >::empty(), and ThreadsafeQueueBase< T >::size().
mutex_
template<typename T > std::mutex ThreadsafeQueueBase< T >::mutex_ mutable protected
Definition at line 150 of file ThreadSafeQueue.hpp.
Referenced by ThreadsafeQueueBase< T >::clear(), ThreadsafeQueueBase< T >::empty(), ThreadsafeQueueBase< T >::isShutdown(), ThreadsafeQueueBase< T >::resume(), and ThreadsafeQueueBase< T >::shutdown().
shutdown_
template<typename T > std::atomic_bool ThreadsafeQueueBase< T >::shutdown_ protected
Definition at line 153 of file ThreadSafeQueue.hpp.
Referenced by ThreadsafeQueueBase< T >::isShutdown(), ThreadsafeQueueBase< T >::resume(), and ThreadsafeQueueBase< T >::shutdown().
The documentation for this class was generated from the following file:
dynosam/include/dynosam/pipeline/ThreadSafeQueue.hpp