DynoSAM: dyno::UndistorterRectifier Class Reference
dyno::UndistorterRectifier Class Reference
The UndistorterRectifier class Computes undistortion maps and undistorts on a per-image basis. Optionally, one can also apply image rectification by providing a corresponding rotation matrix R.
#include <UndistortRectifier.hpp>
Public Member Functions
UndistorterRectifier (const cv::Mat &P, const CameraParams &cam_params, const cv::Mat &R=cv::Mat())
UndistorterRectifier.
virtual ~UndistorterRectifier ()=default
gtsam::Vector3 undistortKeypointAndGetVersor (const Keypoint &keypoint) const
Undistorts a single pixel and returns the corresponding versor (unit norm vector corresponding to bearing). The rectifciation and new camera matrix (R and P) are used from construction.
gtsam::Vector3 undistortKeypointAndGetProjectedVersor (const Keypoint &keypoint) const
void undistortRectifyImage (const cv::Mat &img, cv::Mat &undistorted_img) const
undistortRectifyImage Given distorted (and optionally non-rectified) image, returns a distortion-free rectified one.
void undistortRectifyKeypoints (const Keypoints &keypoints, Keypoints &undistorted_keypoints) const
undistortRectifyKeypoints Undistorts and rectifies a sparse set of keypoints (instead of a whole image), using OpenCV undistortPoints.
Static Public Member Functions
static void UndistortRectifyKeypoints (const Keypoints &keypoints, Keypoints &undistorted_keypoints, const CameraParams &cam_params, std::optional< cv::Mat > P={}, std::optional< cv::Mat > R={})
undistortRectifyKeypoints undistorts and rectifies
static gtsam::Vector3 UndistortKeypointAndGetVersor (const Keypoint &keypoint, const CameraParams &cam_params, std::optional< cv::Mat > R={})
UndistortKeypointAndGetVersor undistort a single pixel, and return the corresponding versor. (unit norm vector corresponding to bearing).
static gtsam::Vector3 UndistortKeypointAndGetProjectedVersor (const Keypoint &keypoint, const CameraParams &cam_params, std::optional< cv::Mat > P={}, std::optional< cv::Mat > R={})
UndistortKeypointAndGetVersor undistort a single pixel, and return the corresponding projected versor using the new camera matrix P If P is not provided, the camera matrix, K is used.
Protected Member Functions
void initUndistortRectifyMaps (const CameraParams &cam_params, const cv::Mat &R, const cv::Mat &P, cv::Mat *map_x, cv::Mat *map_y)
initUndistortRectifyMaps Initialize pixel to pixel maps for undistortion and rectification. If rectification is not needed, as is the case with a monocular camera, the identity matrix should be passed as R.
Protected Attributes
cv::Mat map_x_
cv::Mat map_y_
cv::Mat P_
cv::Mat R_
CameraParams cam_params_
bool remap_use_constant_border_type_ = false
int remap_interpolation_type_ = cv::INTER_LINEAR
Static Protected Attributes
static constexpr int kRectifyImageType = CV_32FC1
Detailed Description
The UndistorterRectifier class Computes undistortion maps and undistorts on a per-image basis. Optionally, one can also apply image rectification by providing a corresponding rotation matrix R.
Definition at line 58 of file UndistortRectifier.hpp.
Constructor & Destructor Documentation
UndistorterRectifier()
dyno::UndistorterRectifier::UndistorterRectifier (const cv::Mat & P, const CameraParams & cam_params, const cv::Mat & R = cv::Mat())
UndistorterRectifier.
Parameters
P new projection matrix after stereo rectification (identity if no stereo rectification needed). In the case of the monocular camera, P (new camera matrix) is usually equal to K (the camera matrix). See: https://docs.opencv.org/4.x/d9/d0c/group__calib3d.html#ga7dfb72c9cf9780a347fbe3d1c47e5d5a P is normally set to P1 or P2 computed by cv::stereoRectify.
cam_params Camera Parameters.
R optional rotation matrix if you want to rectify image (aka apply a rotation matrix) typically computed by cv::stereoRectify. If you have a mono camera, you typically don't set this matrix.
Definition at line 36 of file UndistortRectifier.cc.
    : map_x_(), map_y_(), P_(P), R_(R), cam_params_(cam_params) {
  initUndistortRectifyMaps(cam_params, R, P, &map_x_, &map_y_);
}
References initUndistortRectifyMaps(), map_x_, and map_y_.
~UndistorterRectifier()
virtual dyno::UndistorterRectifier::~UndistorterRectifier () virtual default
Member Function Documentation
initUndistortRectifyMaps()
void dyno::UndistorterRectifier::initUndistortRectifyMaps (const CameraParams & cam_params, const cv::Mat & R, const cv::Mat & P, cv::Mat * map_x, cv::Mat * map_y) protected
initUndistortRectifyMaps Initialize pixel to pixel maps for undistortion and rectification. If rectification is not needed, as is the case with a monocular camera, the identity matrix should be passed as R.
The function computes the joint undistortion and rectification transformation and represents the result in the form of maps for remap. The undistorted image looks like original, as if it is captured with a camera using the camera matrix = P and zero distortion. In case of a monocular camera, P is usually equal to cameraMatrix, or it can be computed by cv::getOptimalNewCameraMatrix for a better control over scaling. In case of a stereo camera, it is the output of stereo rectification (cv::stereoRectify)
NOTE: for stereo cameras, cam_params.P_ should be already computed using cv::stereoRectify().
Parameters
cam_params Camera Parameters.
R optional rotation matrix if you want to rectify image (aka apply a rotation matrix typically computed by cv::stereoRectify).
P new projection matrix after stereo rectification (identity if no stereo rectification needed). P is normally set to P1 or P2 computed by cv::stereoRectify.
Definition at line 212 of file UndistortRectifier.cc.
                  {
  CHECK_NOTNULL(map_x);
  CHECK_NOTNULL(map_y);
  // static constexpr int kImageType = CV_32FC1;
  // static constexpr int kImageType = CV_16SC2;
  const cv::Size image_size = cam_params.imageSize();
  const cv::Mat& distortion_matrix = cam_params.getDistortionCoeffs();
  const cv::Mat& camera_matrix = cam_params.getCameraMatrix();
  const DistortionModel distortion_model = cam_params.getDistortionModel();
  cv::Mat map_x_float, map_y_float;
  switch (distortion_model) {
    case DistortionModel::NONE: {
      map_x_float.create(image_size, kRectifyImageType);
      map_y_float.create(image_size, kRectifyImageType);
    } break;
    case DistortionModel::RADTAN: {
      cv::initUndistortRectifyMap(
          // Input
          camera_matrix,
          distortion_matrix,
          R,
          P,
          image_size,
          kRectifyImageType,
          // Output:
          map_x_float,
          map_y_float);
    } break;
    //TODO: Jesse should this not also be for FISH_EYE model?
    case DistortionModel::EQUIDISTANT: {
      cv::fisheye::initUndistortRectifyMap(
          // Input,
          camera_matrix,
          distortion_matrix,
          R,
          P,
          image_size,
          kRectifyImageType,
          // Output:
          map_x_float,
          map_y_float);
    } break;
    default: {
      LOG(FATAL) << "Unknown distortion model: "
                 << to_string(distortion_model) << " when constructing undistortion maps";
    }
  }
  //TODO: (Jesse) experiment with what marcus was talking about
  // TODO(marcus): can we add this in without causing errors like before?
  // The reason we convert from floating to fixed-point representations
  // of a map is that they can yield much faster (~2x) remapping operations.
  // cv::convertMaps(map_x_float, map_y_float, *map_x, *map_y, CV_16SC2, false);
  *map_x = map_x_float;
  *map_y = map_y_float;
}
References dyno::EQUIDISTANT, dyno::CameraParams::getCameraMatrix(), dyno::CameraParams::getDistortionCoeffs(), dyno::CameraParams::getDistortionModel(), dyno::CameraParams::imageSize(), kRectifyImageType, dyno::NONE, dyno::RADTAN, and dyno::to_string().
Referenced by UndistorterRectifier().
undistortKeypointAndGetProjectedVersor()
gtsam::Vector3 dyno::UndistorterRectifier::undistortKeypointAndGetProjectedVersor (const Keypoint & keypoint) const
Definition at line 152 of file UndistortRectifier.cc.
{
  return UndistortKeypointAndGetProjectedVersor(keypoint, cam_params_, P_, R_);
}
References cam_params_, P_, R_, and UndistortKeypointAndGetProjectedVersor().
UndistortKeypointAndGetProjectedVersor()
gtsam::Vector3 dyno::UndistorterRectifier::UndistortKeypointAndGetProjectedVersor (const Keypoint & keypoint, const CameraParams & cam_params, std::optional< cv::Mat > P = {}, std::optional< cv::Mat > R = {}) static
UndistortKeypointAndGetVersor undistort a single pixel, and return the corresponding projected versor using the new camera matrix P If P is not provided, the camera matrix, K is used.
The projected version is calculated as K^{-1} * [u, v, 1] and then normalized
Parameters
keypoint const Keypoints&
cam_params const CameraParams&
P std::optional<cv::Mat> new camera matrix used for the projections
R std::optional<cv::Mat> not needed in the monocular case
Returns
gtsam::Vector3
Definition at line 119 of file UndistortRectifier.cc.
{
  Keypoints distorted_keypoint;
  distorted_keypoint.push_back(keypoint);
  Keypoints undistorted_keypoint;
  UndistorterRectifier::UndistortRectifyKeypoints(
      distorted_keypoint,
      undistorted_keypoint,
      cam_params,
      std::nullopt,
      R);
  gtsam::Vector3 versor(
      undistorted_keypoint.at(0)(0), undistorted_keypoint.at(0)(1), 1.0);
  gtsam::Matrix K = gtsam::Matrix::Identity(3, 3);
  if(P) {
    //construct K from new camera matrix P
    cv::cv2eigen(*P, K);
  }
  else {
    cv::cv2eigen(cam_params.getCameraMatrix(), K);
  }
  return gtsam::Vector3 ( K.inverse() * versor).normalized();
}
References dyno::CameraParams::getCameraMatrix(), and UndistortRectifyKeypoints().
Referenced by undistortKeypointAndGetProjectedVersor().
undistortKeypointAndGetVersor()
gtsam::Vector3 dyno::UndistorterRectifier::undistortKeypointAndGetVersor (const Keypoint & keypoint) const
Undistorts a single pixel and returns the corresponding versor (unit norm vector corresponding to bearing). The rectifciation and new camera matrix (R and P) are used from construction.
Parameters
keypoint
Returns
gtsam::Vector3
Definition at line 115 of file UndistortRectifier.cc.
{
  return UndistortKeypointAndGetVersor(keypoint, cam_params_, R_);
}
References cam_params_, R_, and UndistortKeypointAndGetVersor().
UndistortKeypointAndGetVersor()
gtsam::Vector3 dyno::UndistorterRectifier::UndistortKeypointAndGetVersor (const Keypoint & keypoint, const CameraParams & cam_params, std::optional< cv::Mat > R = {}) static
UndistortKeypointAndGetVersor undistort a single pixel, and return the corresponding versor. (unit norm vector corresponding to bearing).
Parameters
cv_px keypoint
cam_params CameraParams instance
R std::optional<cv::Mat> not needed in the monocular case
Definition at line 92 of file UndistortRectifier.cc.
{
  Keypoints distorted_keypoint;
  distorted_keypoint.push_back(keypoint);
  Keypoints undistorted_keypoint;
  UndistorterRectifier::UndistortRectifyKeypoints(
      distorted_keypoint,
      undistorted_keypoint,
      cam_params,
      std::nullopt,
      R);
  // Transform to unit vector.
  gtsam::Vector3 versor(
      undistorted_keypoint.at(0)(0), undistorted_keypoint.at(0)(1), 1.0);
  return versor.normalized();
}
References UndistortRectifyKeypoints().
Referenced by undistortKeypointAndGetVersor().
undistortRectifyImage()
void dyno::UndistorterRectifier::undistortRectifyImage (const cv::Mat & img, cv::Mat & undistorted_img) const
undistortRectifyImage Given distorted (and optionally non-rectified) image, returns a distortion-free rectified one.
Parameters
img Distorted non-rectified input image
undistorted_img Undistorted Rectified output image
Definition at line 157 of file UndistortRectifier.cc.
{
  CHECK_EQ(map_x_.size, img.size);
  CHECK_EQ(map_y_.size, img.size);
  const auto original_image_type = img.type();
  //convert the input image into a CV type compatible with the rectify maps
  cv::Mat converted_img;
  img.copyTo(converted_img);
  converted_img.convertTo(converted_img, kRectifyImageType);
  cv::remap(converted_img,
            undistorted_img,
            map_x_,
            map_y_,
            remap_interpolation_type_,
            remap_use_constant_border_type_ ? cv::BORDER_CONSTANT
                                            : cv::BORDER_REPLICATE);
  //convert back to the original input image type
  undistorted_img.convertTo(undistorted_img, original_image_type);
}
References kRectifyImageType, map_x_, map_y_, remap_interpolation_type_, and remap_use_constant_border_type_.
Referenced by dyno::ImageContainer::RectifyImages().
undistortRectifyKeypoints()
void dyno::UndistorterRectifier::undistortRectifyKeypoints (const Keypoints & keypoints, Keypoints & undistorted_keypoints) const
undistortRectifyKeypoints Undistorts and rectifies a sparse set of keypoints (instead of a whole image), using OpenCV undistortPoints.
OpenCV undistortPoints (this does not use the remap function, but an iterative approach to find the undistorted keypoints...). Check OpenCV documentation for details about this function.
It uses the internal camera parameters, and the optional R_ and P_ matrices as provided at construction (by cv::stereoRectify). If R_/P_ are identity no rectification is performed and the resulting keypoints are in normalized coordinates.
Parameters
keypoints Distorted and unrectified keypoints
undistorted_keypoints Undistorted and rectified keypoints.
Definition at line 183 of file UndistortRectifier.cc.
{
  undistorted_keypoints.clear();
  UndistorterRectifier::UndistortRectifyKeypoints(
      keypoints, undistorted_keypoints, cam_params_, R_, P_);
}
References cam_params_, P_, R_, and UndistortRectifyKeypoints().
UndistortRectifyKeypoints()
void dyno::UndistorterRectifier::UndistortRectifyKeypoints (const Keypoints & keypoints, Keypoints & undistorted_keypoints, const CameraParams & cam_params, std::optional< cv::Mat > P = {}, std::optional< cv::Mat > R = {}) static
undistortRectifyKeypoints undistorts and rectifies
Definition at line 43 of file UndistortRectifier.cc.
{
    const auto distortion_model = cam_params.getDistortionModel();
    const cv::Mat& distortion_matrix = cam_params.getDistortionCoeffs();
    const cv::Mat& camera_matrix = cam_params.getCameraMatrix();
    //but slow as we have to do all conversion back and forth
    //if the Eigen matrices are aligned we might not even need to do this...
    std::vector<cv::Point2f> keypoints_cv = utils::gtsamPointsToCv(keypoints);
    std::vector<cv::Point2f> undistorted_keypoints_cv;
    switch (distortion_model) {
        case DistortionModel::RADTAN: {
        cv::undistortPoints(keypoints_cv,
                            undistorted_keypoints_cv,
                            camera_matrix,
                            distortion_matrix,
                            R ? R.value() : cv::noArray(),
                            P ? P.value() : cv::noArray());
        } break;
        case DistortionModel::EQUIDISTANT: {
        // TODO: Create unit test for fisheye / equidistant model
        cv::fisheye::undistortPoints(keypoints_cv,
                                    undistorted_keypoints_cv,
                                    camera_matrix,
                                    distortion_matrix,
                                    R ? R.value() : cv::noArray(),
                                    P ? P.value() : cv::noArray());
        } break;
        default: {
            LOG(FATAL) << "Unknown distortion model " << to_string(distortion_model) << " when rectifying keypoints";
        }
    }
    undistorted_keypoints.clear();
    undistorted_keypoints = utils::cvPointsToGtsam(undistorted_keypoints_cv);
}
References dyno::utils::cvPointsToGtsam(), dyno::EQUIDISTANT, dyno::CameraParams::getCameraMatrix(), dyno::CameraParams::getDistortionCoeffs(), dyno::CameraParams::getDistortionModel(), dyno::utils::gtsamPointsToCv(), dyno::RADTAN, and dyno::to_string().
Referenced by UndistortKeypointAndGetProjectedVersor(), UndistortKeypointAndGetVersor(), and undistortRectifyKeypoints().
Member Data Documentation
cam_params_
CameraParams dyno::UndistorterRectifier::cam_params_ protected
Definition at line 217 of file UndistortRectifier.hpp.
Referenced by undistortKeypointAndGetProjectedVersor(), undistortKeypointAndGetVersor(), and undistortRectifyKeypoints().
kRectifyImageType
constexpr int dyno::UndistorterRectifier::kRectifyImageType = CV_32FC1 static constexpr protected
Definition at line 219 of file UndistortRectifier.hpp.
Referenced by initUndistortRectifyMaps(), and undistortRectifyImage().
map_x_
cv::Mat dyno::UndistorterRectifier::map_x_ protected
Definition at line 211 of file UndistortRectifier.hpp.
Referenced by UndistorterRectifier(), and undistortRectifyImage().
map_y_
cv::Mat dyno::UndistorterRectifier::map_y_ protected
Definition at line 212 of file UndistortRectifier.hpp.
Referenced by UndistorterRectifier(), and undistortRectifyImage().
P_
cv::Mat dyno::UndistorterRectifier::P_ protected
Definition at line 214 of file UndistortRectifier.hpp.
Referenced by undistortKeypointAndGetProjectedVersor(), and undistortRectifyKeypoints().
R_
cv::Mat dyno::UndistorterRectifier::R_ protected
Definition at line 215 of file UndistortRectifier.hpp.
Referenced by undistortKeypointAndGetProjectedVersor(), undistortKeypointAndGetVersor(), and undistortRectifyKeypoints().
remap_interpolation_type_
int dyno::UndistorterRectifier::remap_interpolation_type_ = cv::INTER_LINEAR protected
Definition at line 223 of file UndistortRectifier.hpp.
Referenced by undistortRectifyImage().
remap_use_constant_border_type_
bool dyno::UndistorterRectifier::remap_use_constant_border_type_ = false protected
Definition at line 222 of file UndistortRectifier.hpp.
Referenced by undistortRectifyImage().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/frontend/vision/UndistortRectifier.hpp
dynosam/src/frontend/vision/UndistortRectifier.cc