DynoSAM: dyno::FrontendModule Class Reference
dyno::FrontendModule Class Reference abstract
Base class to actually do processing. Data passed to this module from the frontend.
#include <FrontendModule.hpp>
Classes
struct ImageValidationResult
Defines the result of checking the image container which is a done polymorphically per module (as each module has its own requirements)
Public Types
using Base = ModuleBase< FrontendInputPacketBase, VisionImuPacket >
Public Types inherited from dyno::ModuleBase< FrontendInputPacketBase, VisionImuPacket >
enum State
using Input = FrontendInputPacketBase
using Output = VisionImuPacket
using InputConstPtr = typename INPUT::ConstPtr
using OutputConstPtr = typename OUTPUT::ConstPtr
ConstPtr to an INPUT type.
using This = ModuleBase< FrontendInputPacketBase, VisionImuPacket >
ConstPtr to an OUTPUT type.
using SpinReturn = std::pair< State, OutputConstPtr >
using InputCallback = std::function< void(InputConstPtr)>
using OutputCallback = std::function< void(OutputConstPtr)>
Public Member Functions
FrontendModule (const DynoParams &params, ImageDisplayQueue *display_queue=nullptr)
virtual ~FrontendModule ()
const FrontendParams & getFrontendParams () const
void setAccessor (Accessor::Ptr accessor)
virtual void onBackendUpdateCallback (const FrameId, const Timestamp)
Public Member Functions inherited from dyno::ModuleBase< FrontendInputPacketBase, VisionImuPacket >
ModuleBase (const std::string &name)
virtual ~ModuleBase ()=default
OutputConstPtr spinOnce (InputConstPtr input)
void registerInputCallback (const InputCallback &input_callback)
Registeres a function callback to be triggered prior to nominal/bootstrapSpin being called.
void registerOutputCallback (const OutputCallback &output_callback)
Registeres a function callback to be triggered after nominal/bootstrapSpin is called.
Protected Member Functions
void validateInput (const FrontendInputPacketBase::ConstPtr &input) const override
virtual ImageValidationResult validateImageContainer (const ImageContainer::Ptr &image_container) const =0
Checks that the incoming ImageContainer meeets the minimum requirement for the derived module.
Protected Member Functions inherited from dyno::ModuleBase< FrontendInputPacketBase, VisionImuPacket >
virtual void validateInput (const InputConstPtr &input) const=0
Checks the state of the input before running any virtual spin (boostrap or nominal) functions.
virtual SpinReturn boostrapSpin (InputConstPtr input)=0
virtual SpinReturn nominalSpin (InputConstPtr input)=0
Protected Attributes
const DynoParams params_
ImageDisplayQueue * display_queue_
gtsam::Pose3Vector camera_poses_
Accessor::Ptr accessor_ {nullptr}
Accessor for the backend (i.e optimized values)
Additional Inherited Members
Public Attributes inherited from dyno::SharedModuleInterface
SharedModuleInfo & shared_module_info = SharedModuleInfo::instance()
Detailed Description
Base class to actually do processing. Data passed to this module from the frontend.
Definition at line 62 of file FrontendModule.hpp.
Member Typedef Documentation
Base
using dyno::FrontendModule::Base = ModuleBase<FrontendInputPacketBase, VisionImuPacket>
Definition at line 68 of file FrontendModule.hpp.
Constructor & Destructor Documentation
FrontendModule()
dyno::FrontendModule::FrontendModule (const DynoParams & params, ImageDisplayQueue * display_queue = nullptr)
Definition at line 39 of file FrontendModule.cc.
    : Base("frontend"), params_(params), display_queue_(display_queue) {
  // create callback to update gt_packet_map_ values so the derived classes dont
  // need to manage this
  registerInputCallback([=](FrontendInputPacketBase::ConstPtr input) {
    // if(input->optional_gt_) gt_packet_map_.insert2(input->getFrameId(),
    // *input->optional_gt_);
    if (input->optional_gt_)
      shared_module_info.updateGroundTruthPacket(input->getFrameId(),
                                                 *input->optional_gt_);
    shared_module_info.updateTimestampMapping(input->getFrameId(),
                                              input->getTimestamp());
  });
}
References dyno::ModuleBase< FrontendInputPacketBase, VisionImuPacket >::registerInputCallback(), dyno::SharedModuleInterface::shared_module_info, dyno::SharedModuleInfo::updateGroundTruthPacket(), and dyno::SharedModuleInfo::updateTimestampMapping().
~FrontendModule()
dyno::FrontendModule::~FrontendModule () virtual
Definition at line 55 of file FrontendModule.cc.
{ VLOG(5) << "Destructing frontend module"; }
Member Function Documentation
getFrontendParams()
const FrontendParams & dyno::FrontendModule::getFrontendParams () const inline
Definition at line 75 of file FrontendModule.hpp.
{
    return params_.frontend_params_;
  }
References dyno::DynoParams::frontend_params_, and params_.
Referenced by dyno::RGBDInstanceFrontendModule::createTrackingImage(), dyno::RGBDInstanceFrontendModule::RGBDInstanceFrontendModule(), and dyno::RGBDInstanceFrontendModule::solveCameraMotion().
onBackendUpdateCallback()
virtual void dyno::FrontendModule::onBackendUpdateCallback (const FrameId, const Timestamp) inline virtual
Definition at line 84 of file FrontendModule.hpp.
                                                          {}
Referenced by dyno::DynoPipelineManager::loadPipelines().
setAccessor()
void dyno::FrontendModule::setAccessor (Accessor::Ptr accessor) inline
Definition at line 79 of file FrontendModule.hpp.
{
    CHECK_NOTNULL(accessor);
    accessor_ = accessor;
  }
References accessor_.
validateImageContainer()
virtual ImageValidationResult dyno::FrontendModule::validateImageContainer (const ImageContainer::Ptr & image_container) const protected pure virtual
Checks that the incoming ImageContainer meeets the minimum requirement for the derived module.
This is specifically to check that the right image types are contained with the container. If the result is false, InvalidImageContainerException is thrown with the requirements specified by the returned ImageValidationResult.
Parameters
image_container const ImageContainer::Ptr&
Returns
ImageValidationResult
Implemented in dyno::RGBDInstanceFrontendModule.
Referenced by validateInput().
validateInput()
void dyno::FrontendModule::validateInput (const FrontendInputPacketBase::ConstPtr & input) const override protected
Definition at line 57 of file FrontendModule.cc.
{
  CHECK(input->image_container_);
  const ImageValidationResult result =
      validateImageContainer(input->image_container_);
  // throw exception if result is false
  checkAndThrow<InvalidImageContainerException>(
      result.valid_, *input->image_container_, result.requirement_);
}
References dyno::FrontendModule::ImageValidationResult::requirement_, dyno::FrontendModule::ImageValidationResult::valid_, and validateImageContainer().
Member Data Documentation
accessor_
Accessor::Ptr dyno::FrontendModule::accessor_ {nullptr} protected
Accessor for the backend (i.e optimized values)
Keeps track of current camera trajectory. Really just for (viz) and drawn everytime
Definition at line 131 of file FrontendModule.hpp.
Referenced by setAccessor().
camera_poses_
gtsam::Pose3Vector dyno::FrontendModule::camera_poses_ protected
Definition at line 128 of file FrontendModule.hpp.
display_queue_
ImageDisplayQueue* dyno::FrontendModule::display_queue_ protected
Definition at line 126 of file FrontendModule.hpp.
Referenced by dyno::RGBDInstanceFrontendModule::nominalSpin().
params_
const DynoParams dyno::FrontendModule::params_ protected
Definition at line 125 of file FrontendModule.hpp.
Referenced by dyno::RGBDInstanceFrontendModule::fillOutputPacketWithTracks(), and getFrontendParams().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/frontend/FrontendModule.hpp
dynosam/src/frontend/FrontendModule.cc