DynoSAM: dyno::EgoMotionSolver Class Reference
dyno::EgoMotionSolver Class Reference
#include <MotionSolver.hpp>
Classes
struct Params
Public Member Functions
EgoMotionSolver (const Params &params, const CameraParams &camera_params)
virtual ~EgoMotionSolver ()=default
Pose3SolverResult geometricOutlierRejection2d2d (Frame::Ptr frame_k_1, Frame::Ptr frame_k, std::optional< gtsam::Rot3 > R_curr_ref={})
Runs 2d-2d PnP with optional Rotation (ie. from IMU)
Pose3SolverResult geometricOutlierRejection3d2d (Frame::Ptr frame_k_1, Frame::Ptr frame_k, std::optional< gtsam::Rot3 > R_curr_ref={})
Runs 3d-2d PnP with optional Rotation (i.e from IMU)
Pose3SolverResult geometricOutlierRejection3d2d (const AbsolutePoseCorrespondences &correspondences, std::optional< gtsam::Rot3 > R_curr_ref={})
Pose3SolverResult geometricOutlierRejection3d3d (Frame::Ptr frame_k_1, Frame::Ptr frame_k, std::optional< gtsam::Rot3 > R_curr_ref={})
Pose3SolverResult geometricOutlierRejection3d3d (const PointCloudCorrespondences &correspondences, std::optional< gtsam::Rot3 > R_curr_ref={})
Protected Member Functions
template<typename Ref , typename Curr >
void constructTrackletInliers (TrackletIds &inliers, TrackletIds &outliers, const GenericCorrespondences< Ref, Curr > &correspondences, const std::vector< int > &ransac_inliers, const TrackletIds tracklets)
Protected Attributes
const Params params_
const CameraParams camera_params_
Detailed Description
Definition at line 245 of file MotionSolver.hpp.
Constructor & Destructor Documentation
EgoMotionSolver()
dyno::EgoMotionSolver::EgoMotionSolver (const Params & params, const CameraParams & camera_params)
Definition at line 107 of file MotionSolver.cc.
    : params_(params), camera_params_(camera_params) {}
~EgoMotionSolver()
virtual dyno::EgoMotionSolver::~EgoMotionSolver () virtual default
Member Function Documentation
constructTrackletInliers()
template<typename Ref , typename Curr > void dyno::EgoMotionSolver::constructTrackletInliers (TrackletIds & inliers, TrackletIds & outliers, const GenericCorrespondences< Ref, Curr > & correspondences, const std::vector< int > & ransac_inliers, const TrackletIds tracklets) inline protected
Definition at line 315 of file MotionSolver.hpp.
{
    CHECK_EQ(correspondences.size(), tracklets.size());
    CHECK(ransac_inliers.size() <= correspondences.size());
    for (int inlier_idx : ransac_inliers) {
      const auto& corres = correspondences.at(inlier_idx);
      inliers.push_back(corres.tracklet_id_);
    }
    determineOutlierIds(inliers, tracklets, outliers);
    CHECK_EQ((inliers.size() + outliers.size()), tracklets.size());
    CHECK_EQ(inliers.size(), ransac_inliers.size());
  }
References dyno::determineOutlierIds().
Referenced by geometricOutlierRejection2d2d(), geometricOutlierRejection3d2d(), and geometricOutlierRejection3d3d().
geometricOutlierRejection2d2d()
Pose3SolverResult dyno::EgoMotionSolver::geometricOutlierRejection2d2d (Frame::Ptr frame_k_1, Frame::Ptr frame_k, std::optional< gtsam::Rot3 > R_curr_ref = {})
Runs 2d-2d PnP with optional Rotation (ie. from IMU)
Parameters
frame_k_1
frame_k
R_curr_ref Should rotate from ref -> curr
Returns
Pose3SolverResult
Definition at line 111 of file MotionSolver.cc.
{
  // get correspondences
  RelativePoseCorrespondences correspondences;
  // this does not create proper bearing vectors (at leas tnot for 3d-2d pnp
  // solve) bearing vectors are also not undistorted atm!!
  {
    utils::TimingStatsCollector track_dynamic_timer(
        "mono_frame_correspondences");
    frame_k->getCorrespondences(correspondences, *frame_k_1,
                                KeyPointType::STATIC,
                                frame_k->imageKeypointCorrespondance());
  }
  Pose3SolverResult result;
  const size_t& n_matches = correspondences.size();
  if (n_matches < 5u) {
    result.status = TrackingStatus::FEW_MATCHES;
    return result;
  }
  gtsam::Matrix K = camera_params_.getCameraMatrixEigen();
  K = K.inverse();
  TrackletIds tracklets;
  // NOTE: currently without distortion! the correspondences should be made into
  // bearing vector elsewhere!
  BearingVectors ref_bearing_vectors, cur_bearing_vectors;
  for (size_t i = 0u; i < n_matches; i++) {
    const auto& corres = correspondences.at(i);
    const Keypoint& ref_kp = corres.ref_;
    const Keypoint& cur_kp = corres.cur_;
    gtsam::Vector3 ref_versor = (K * gtsam::Vector3(ref_kp(0), ref_kp(1), 1.0));
    gtsam::Vector3 cur_versor = (K * gtsam::Vector3(cur_kp(0), cur_kp(1), 1.0));
    ref_versor = ref_versor.normalized();
    cur_versor = cur_versor.normalized();
    ref_bearing_vectors.push_back(ref_versor);
    cur_bearing_vectors.push_back(cur_versor);
    tracklets.push_back(corres.tracklet_id_);
  }
  RelativePoseAdaptor adapter(ref_bearing_vectors, cur_bearing_vectors);
  const bool use_2point_mono = params_.ransac_use_2point_mono && R_curr_ref;
  if (use_2point_mono) {
    adapter.setR12((*R_curr_ref).matrix());
  }
  gtsam::Pose3 best_result;
  std::vector<int> ransac_inliers;
  bool success = false;
  if (use_2point_mono) {
    success = runRansac<RelativePoseProblemGivenRot>(
        std::make_shared<RelativePoseProblemGivenRot>(adapter,
                                                      params_.ransac_randomize),
        params_.ransac_threshold_mono, params_.ransac_iterations,
        params_.ransac_probability, params_.optimize_2d2d_pose_from_inliers,
        best_result, ransac_inliers);
  } else {
    success = runRansac<RelativePoseProblem>(
        std::make_shared<RelativePoseProblem>(
            adapter, RelativePoseProblem::NISTER, params_.ransac_randomize),
        params_.ransac_threshold_mono, params_.ransac_iterations,
        params_.ransac_probability, params_.optimize_2d2d_pose_from_inliers,
        best_result, ransac_inliers);
  }
  if (!success) {
    result.status = TrackingStatus::INVALID;
  } else {
    constructTrackletInliers(result.inliers, result.outliers, correspondences,
                             ransac_inliers, tracklets);
    // NOTE: 2-point always returns the identity rotation, hence we have to
    // substitute it:
    if (use_2point_mono) {
      CHECK(R_curr_ref->equals(best_result.rotation()));
    }
    result.status = TrackingStatus::VALID;
    result.best_result = best_result;
  }
  return result;
}
References dyno::SolverResult< T >::best_result, camera_params_, constructTrackletInliers(), dyno::FEW_MATCHES, dyno::CameraParams::getCameraMatrixEigen(), dyno::SolverResult< T >::inliers, dyno::INVALID, dyno::EgoMotionSolver::Params::optimize_2d2d_pose_from_inliers, dyno::SolverResult< T >::outliers, params_, dyno::EgoMotionSolver::Params::ransac_iterations, dyno::EgoMotionSolver::Params::ransac_probability, dyno::EgoMotionSolver::Params::ransac_randomize, dyno::EgoMotionSolver::Params::ransac_threshold_mono, dyno::EgoMotionSolver::Params::ransac_use_2point_mono, dyno::STATIC, dyno::SolverResult< T >::status, and dyno::VALID.
geometricOutlierRejection3d2d() [1/2]
Pose3SolverResult dyno::EgoMotionSolver::geometricOutlierRejection3d2d (const AbsolutePoseCorrespondences & correspondences, std::optional< gtsam::Rot3 > R_curr_ref = {})
Definition at line 219 of file MotionSolver.cc.
{
  utils::TimingStatsCollector timer("motion_solver.solve_3d2d");
  Pose3SolverResult result;
  const size_t& n_matches = correspondences.size();
  if (n_matches < 5u) {
    result.status = TrackingStatus::FEW_MATCHES;
    VLOG(5) << "3D2D tracking failed as there are to few matches" << n_matches;
    return result;
  }
  gtsam::Matrix K = camera_params_.getCameraMatrixEigen();
  K = K.inverse();
  TrackletIds tracklets, inliers, outliers;
  // NOTE: currently without distortion! the correspondences should be made into
  // bearing vector elsewhere!
  BearingVectors bearing_vectors;
  Landmarks points;
  for (size_t i = 0u; i < n_matches; i++) {
    const AbsolutePoseCorrespondence& corres = correspondences.at(i);
    const Keypoint& kp = corres.cur_;
    // make Bearing vector
    gtsam::Vector3 versor = (K * gtsam::Vector3(kp(0), kp(1), 1.0));
    versor = versor.normalized();
    bearing_vectors.push_back(versor);
    points.push_back(corres.ref_);
    tracklets.push_back(corres.tracklet_id_);
  }
  const double reprojection_error = params_.ransac_threshold_pnp;
  const double avg_focal_length =
      0.5 * static_cast<double>(camera_params_.fx() + camera_params_.fy());
  const double threshold =
      1.0 - std::cos(std::atan(std::sqrt(2.0) * reprojection_error /
                               avg_focal_length));
  // const double threshold = params_.ransac_threshold_pnp;
  AbsolutePoseAdaptor adapter(bearing_vectors, points);
  gtsam::Pose3 best_result;
  std::vector<int> ransac_inliers;
  bool success = runRansac<AbsolutePoseProblem>(
      std::make_shared<AbsolutePoseProblem>(adapter,
                                            AbsolutePoseProblem::KNEIP),
      threshold, params_.ransac_iterations, params_.ransac_probability,
      params_.optimize_3d2d_pose_from_inliers, best_result, ransac_inliers);
  if (success) {
    constructTrackletInliers(result.inliers, result.outliers, correspondences,
                             ransac_inliers, tracklets);
    if (result.inliers.size() < 5u) {
      result.status = TrackingStatus::FEW_MATCHES;
    } else {
      result.status = TrackingStatus::VALID;
      result.best_result = best_result;
    }
  } else {
    result.status = TrackingStatus::INVALID;
  }
  return result;
}
References dyno::SolverResult< T >::best_result, camera_params_, constructTrackletInliers(), dyno::TrackletCorrespondance< U, V >::cur_, dyno::FEW_MATCHES, dyno::CameraParams::fx(), dyno::CameraParams::fy(), dyno::CameraParams::getCameraMatrixEigen(), dyno::SolverResult< T >::inliers, dyno::INVALID, dyno::EgoMotionSolver::Params::optimize_3d2d_pose_from_inliers, dyno::SolverResult< T >::outliers, params_, dyno::EgoMotionSolver::Params::ransac_iterations, dyno::EgoMotionSolver::Params::ransac_probability, dyno::EgoMotionSolver::Params::ransac_threshold_pnp, dyno::TrackletCorrespondance< U, V >::ref_, dyno::SolverResult< T >::status, dyno::TrackletCorrespondance< U, V >::tracklet_id_, and dyno::VALID.
geometricOutlierRejection3d2d() [2/2]
Pose3SolverResult dyno::EgoMotionSolver::geometricOutlierRejection3d2d (Frame::Ptr frame_k_1, Frame::Ptr frame_k, std::optional< gtsam::Rot3 > R_curr_ref = {})
Runs 3d-2d PnP with optional Rotation (i.e from IMU)
Parameters
frame_k_1
frame_k
R_curr_ref
Returns
Pose3SolverResult
Definition at line 202 of file MotionSolver.cc.
{
  AbsolutePoseCorrespondences correspondences;
  // this does not create proper bearing vectors (at leas tnot for 3d-2d pnp
  // solve) bearing vectors are also not undistorted atm!!
  // TODO: change to use landmarkWorldProjectedBearingCorrespondance and then
  // change motion solver to take already projected bearing vectors
  {
    frame_k->getCorrespondences(correspondences, *frame_k_1,
                                KeyPointType::STATIC,
                                frame_k->landmarkWorldKeypointCorrespondance());
  }
  return geometricOutlierRejection3d2d(correspondences, R_curr_ref);
}
References geometricOutlierRejection3d2d(), and dyno::STATIC.
Referenced by dyno::ObjectMotionSovler::geometricOutlierRejection3d2d(), geometricOutlierRejection3d2d(), and dyno::RGBDInstanceFrontendModule::solveCameraMotion().
geometricOutlierRejection3d3d() [1/2]
Pose3SolverResult dyno::EgoMotionSolver::geometricOutlierRejection3d3d (const PointCloudCorrespondences & correspondences, std::optional< gtsam::Rot3 > R_curr_ref = {})
Setup adapter.
Definition at line 378 of file MotionSolver.cc.
{
  const size_t& n_matches = correspondences.size();
  Pose3SolverResult result;
  if (n_matches < 5) {
    result.status = TrackingStatus::FEW_MATCHES;
    return result;
  }
  TrackletIds tracklets;
  BearingVectors ref_bearing_vectors, cur_bearing_vectors;
  for (size_t i = 0u; i < n_matches; i++) {
    const auto& corres = correspondences.at(i);
    const Landmark& ref_lmk = corres.ref_;
    const Landmark& cur_lmk = corres.cur_;
    ref_bearing_vectors.push_back(ref_lmk);
    cur_bearing_vectors.push_back(cur_lmk);
    tracklets.push_back(corres.tracklet_id_);
  }
  Adapter3d3d adapter(ref_bearing_vectors, cur_bearing_vectors);
  if (R_curr_ref) {
    adapter.setR12((*R_curr_ref).matrix());
  }
  gtsam::Pose3 best_result;
  std::vector<int> ransac_inliers;
  bool success = runRansac<Problem3d3d>(
      std::make_shared<Problem3d3d>(adapter, params_.ransac_randomize),
      params_.ransac_threshold_stereo, params_.ransac_iterations,
      params_.ransac_probability, params_.optimize_3d3d_pose_from_inliers,
      best_result, ransac_inliers);
  if (success) {
    constructTrackletInliers(result.inliers, result.outliers, correspondences,
                             ransac_inliers, tracklets);
    result.status = TrackingStatus::VALID;
    result.best_result = best_result;
  } else {
    result.status = TrackingStatus::INVALID;
  }
  return result;
}
References dyno::SolverResult< T >::best_result, constructTrackletInliers(), dyno::FEW_MATCHES, dyno::SolverResult< T >::inliers, dyno::INVALID, dyno::EgoMotionSolver::Params::optimize_3d3d_pose_from_inliers, dyno::SolverResult< T >::outliers, params_, dyno::EgoMotionSolver::Params::ransac_iterations, dyno::EgoMotionSolver::Params::ransac_probability, dyno::EgoMotionSolver::Params::ransac_randomize, dyno::EgoMotionSolver::Params::ransac_threshold_stereo, dyno::SolverResult< T >::status, and dyno::VALID.
geometricOutlierRejection3d3d() [2/2]
Pose3SolverResult dyno::EgoMotionSolver::geometricOutlierRejection3d3d (Frame::Ptr frame_k_1, Frame::Ptr frame_k, std::optional< gtsam::Rot3 > R_curr_ref = {})
Definition at line 364 of file MotionSolver.cc.
{
  PointCloudCorrespondences correspondences;
  {
    utils::TimingStatsCollector("pc_correspondences");
    frame_k->getCorrespondences(
        correspondences, *frame_k_1, KeyPointType::STATIC,
        frame_k->landmarkWorldPointCloudCorrespondance());
  }
  return geometricOutlierRejection3d3d(correspondences, R_curr_ref);
}
References geometricOutlierRejection3d3d(), and dyno::STATIC.
Referenced by dyno::ObjectMotionSovler::geometricOutlierRejection3d3d(), geometricOutlierRejection3d3d(), and dyno::RGBDInstanceFrontendModule::solveCameraMotion().
Member Data Documentation
camera_params_
const CameraParams dyno::EgoMotionSolver::camera_params_ protected
Definition at line 333 of file MotionSolver.hpp.
Referenced by geometricOutlierRejection2d2d(), geometricOutlierRejection3d2d(), and dyno::ObjectMotionSovler::motionModelOutlierRejection3d2d().
params_
const Params dyno::EgoMotionSolver::params_ protected
Definition at line 332 of file MotionSolver.hpp.
Referenced by geometricOutlierRejection2d2d(), geometricOutlierRejection3d2d(), geometricOutlierRejection3d3d(), and dyno::ObjectMotionSovler::motionModelOutlierRejection3d2d().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/frontend/vision/MotionSolver.hpp
dynosam/src/frontend/vision/MotionSolver.cc