DynoSAM: dyno::ModuleBase< INPUT, OUTPUT > Class Template Reference
dyno::ModuleBase< INPUT, OUTPUT > Class Template Reference abstract
Defines some basic functions and behaviour for a module which will take and send input to and from a pipeline.
#include <ModuleBase.hpp>
Public Types
enum class State { Boostrap = 0u , Nominal = 1u }
using Input = INPUT
using Output = OUTPUT
using InputConstPtr = typename INPUT::ConstPtr
using OutputConstPtr = typename OUTPUT::ConstPtr
ConstPtr to an INPUT type.
using This = ModuleBase< INPUT, OUTPUT >
ConstPtr to an OUTPUT type.
using SpinReturn = std::pair< State, OutputConstPtr >
using InputCallback = std::function< void(InputConstPtr)>
using OutputCallback = std::function< void(OutputConstPtr)>
Public Member Functions
ModuleBase (const std::string &name)
virtual ~ModuleBase ()=default
OutputConstPtr spinOnce (InputConstPtr input)
void registerInputCallback (const InputCallback &input_callback)
Registeres a function callback to be triggered prior to nominal/bootstrapSpin being called.
void registerOutputCallback (const OutputCallback &output_callback)
Registeres a function callback to be triggered after nominal/bootstrapSpin is called.
Protected Member Functions
virtual void validateInput (const InputConstPtr &input) const =0
Checks the state of the input before running any virtual spin (boostrap or nominal) functions.
virtual SpinReturn boostrapSpin (InputConstPtr input)=0
virtual SpinReturn nominalSpin (InputConstPtr input)=0
Private Attributes
const std::string name_
std::atomic< State > module_state_
std::atomic< State > previous_module_state_
InputCallback input_callback_
OutputCallback output_callback_
Detailed Description
template<typename INPUT, typename OUTPUT>
class dyno::ModuleBase< INPUT, OUTPUT >
Defines some basic functions and behaviour for a module which will take and send input to and from a pipeline.
A module is intended to the core place where all the processing actually happens. Like the pipeline, we expect INPUT and OUTPUT to have certain typedefs defined, partically ::ConstPtr
Template Parameters
INPUT
OUTPUT
Definition at line 51 of file ModuleBase.hpp.
Member Typedef Documentation
Input
template<typename INPUT , typename OUTPUT > using dyno::ModuleBase< INPUT, OUTPUT >::Input = INPUT
Definition at line 53 of file ModuleBase.hpp.
InputCallback
template<typename INPUT , typename OUTPUT > using dyno::ModuleBase< INPUT, OUTPUT >::InputCallback = std::function<void(InputConstPtr)>
Definition at line 69 of file ModuleBase.hpp.
InputConstPtr
template<typename INPUT , typename OUTPUT > using dyno::ModuleBase< INPUT, OUTPUT >::InputConstPtr = typename INPUT::ConstPtr
Definition at line 55 of file ModuleBase.hpp.
Output
template<typename INPUT , typename OUTPUT > using dyno::ModuleBase< INPUT, OUTPUT >::Output = OUTPUT
Definition at line 54 of file ModuleBase.hpp.
OutputCallback
template<typename INPUT , typename OUTPUT > using dyno::ModuleBase< INPUT, OUTPUT >::OutputCallback = std::function<void(OutputConstPtr)>
Definition at line 70 of file ModuleBase.hpp.
OutputConstPtr
template<typename INPUT , typename OUTPUT > using dyno::ModuleBase< INPUT, OUTPUT >::OutputConstPtr = typename OUTPUT::ConstPtr
ConstPtr to an INPUT type.
Definition at line 56 of file ModuleBase.hpp.
SpinReturn
template<typename INPUT , typename OUTPUT > using dyno::ModuleBase< INPUT, OUTPUT >::SpinReturn = std::pair<State, OutputConstPtr>
Definition at line 67 of file ModuleBase.hpp.
This
template<typename INPUT , typename OUTPUT > using dyno::ModuleBase< INPUT, OUTPUT >::This = ModuleBase<INPUT, OUTPUT>
ConstPtr to an OUTPUT type.
Definition at line 58 of file ModuleBase.hpp.
Member Enumeration Documentation
State
template<typename INPUT , typename OUTPUT > enum class dyno::ModuleBase::State strong
Enumerator
Boostrap
Nominal
Initalize.
Definition at line 62 of file ModuleBase.hpp.
                   {
    Boostrap = 0u,
    Nominal = 1u
  };
Constructor & Destructor Documentation
ModuleBase()
template<typename INPUT , typename OUTPUT > dyno::ModuleBase< INPUT, OUTPUT >::ModuleBase (const std::string & name) inline
Definition at line 72 of file ModuleBase.hpp.
      : name_(name), module_state_(State::Boostrap) {}
~ModuleBase()
template<typename INPUT , typename OUTPUT > virtual dyno::ModuleBase< INPUT, OUTPUT >::~ModuleBase () virtual default
Member Function Documentation
boostrapSpin()
template<typename INPUT , typename OUTPUT > virtual SpinReturn dyno::ModuleBase< INPUT, OUTPUT >::boostrapSpin (InputConstPtr input) protected pure virtual
Implemented in dyno::BackendModuleType< MODULE_TRAITS >, and dyno::BackendModuleType< RGBDBackendModuleTraits >.
Referenced by dyno::ModuleBase< INPUT, OUTPUT >::spinOnce().
nominalSpin()
template<typename INPUT , typename OUTPUT > virtual SpinReturn dyno::ModuleBase< INPUT, OUTPUT >::nominalSpin (InputConstPtr input) protected pure virtual
Implemented in dyno::BackendModuleType< MODULE_TRAITS >, and dyno::BackendModuleType< RGBDBackendModuleTraits >.
Referenced by dyno::ModuleBase< INPUT, OUTPUT >::spinOnce().
registerInputCallback()
template<typename INPUT , typename OUTPUT > void dyno::ModuleBase< INPUT, OUTPUT >::registerInputCallback (const InputCallback & input_callback) inline
Registeres a function callback to be triggered prior to nominal/bootstrapSpin being called.
Parameters
input_callback const InputCallback&
Definition at line 109 of file ModuleBase.hpp.
{
    input_callback_ = input_callback;
  }
References dyno::ModuleBase< INPUT, OUTPUT >::input_callback_.
registerOutputCallback()
template<typename INPUT , typename OUTPUT > void dyno::ModuleBase< INPUT, OUTPUT >::registerOutputCallback (const OutputCallback & output_callback) inline
Registeres a function callback to be triggered after nominal/bootstrapSpin is called.
Parameters
output_callback const OutputCallback&
Definition at line 119 of file ModuleBase.hpp.
{
    output_callback_ = output_callback;
  }
References dyno::ModuleBase< INPUT, OUTPUT >::output_callback_.
spinOnce()
template<typename INPUT , typename OUTPUT > OutputConstPtr dyno::ModuleBase< INPUT, OUTPUT >::spinOnce (InputConstPtr input) inline
Definition at line 76 of file ModuleBase.hpp.
{
    CHECK(input);
    validateInput(input);
    SpinReturn spin_return{State::Boostrap, nullptr};
    if (input_callback_) input_callback_(input);
    switch (module_state_) {
      case State::Boostrap: {
        spin_return = boostrapSpin(input);
      } break;
      case State::Nominal: {
        spin_return = nominalSpin(input);
      } break;
      default: {
        LOG(FATAL) << "Unrecognized state in module " << name_;
        break;
      }
    }
    if (output_callback_) output_callback_(spin_return.second);
    module_state_ = spin_return.first;
    return spin_return.second;
  }
References dyno::ModuleBase< INPUT, OUTPUT >::Boostrap, dyno::ModuleBase< INPUT, OUTPUT >::boostrapSpin(), dyno::ModuleBase< INPUT, OUTPUT >::input_callback_, dyno::ModuleBase< INPUT, OUTPUT >::module_state_, dyno::ModuleBase< INPUT, OUTPUT >::name_, dyno::ModuleBase< INPUT, OUTPUT >::Nominal, dyno::ModuleBase< INPUT, OUTPUT >::nominalSpin(), dyno::ModuleBase< INPUT, OUTPUT >::output_callback_, and dyno::ModuleBase< INPUT, OUTPUT >::validateInput().
validateInput()
template<typename INPUT , typename OUTPUT > virtual void dyno::ModuleBase< INPUT, OUTPUT >::validateInput (const InputConstPtr & input) const protected pure virtual
Checks the state of the input before running any virtual spin (boostrap or nominal) functions.
The function is intended to be treated as a "fail hard" case, and should throw an exception if the input is not valid
Parameters
input
Referenced by dyno::ModuleBase< INPUT, OUTPUT >::spinOnce().
Member Data Documentation
input_callback_
template<typename INPUT , typename OUTPUT > InputCallback dyno::ModuleBase< INPUT, OUTPUT >::input_callback_ private
Definition at line 143 of file ModuleBase.hpp.
Referenced by dyno::ModuleBase< INPUT, OUTPUT >::registerInputCallback(), and dyno::ModuleBase< INPUT, OUTPUT >::spinOnce().
module_state_
template<typename INPUT , typename OUTPUT > std::atomic<State> dyno::ModuleBase< INPUT, OUTPUT >::module_state_ private
Definition at line 140 of file ModuleBase.hpp.
Referenced by dyno::ModuleBase< INPUT, OUTPUT >::spinOnce().
name_
template<typename INPUT , typename OUTPUT > const std::string dyno::ModuleBase< INPUT, OUTPUT >::name_ private
Definition at line 139 of file ModuleBase.hpp.
Referenced by dyno::ModuleBase< INPUT, OUTPUT >::spinOnce().
output_callback_
template<typename INPUT , typename OUTPUT > OutputCallback dyno::ModuleBase< INPUT, OUTPUT >::output_callback_ private
Definition at line 144 of file ModuleBase.hpp.
Referenced by dyno::ModuleBase< INPUT, OUTPUT >::registerOutputCallback(), and dyno::ModuleBase< INPUT, OUTPUT >::spinOnce().
previous_module_state_
template<typename INPUT , typename OUTPUT > std::atomic<State> dyno::ModuleBase< INPUT, OUTPUT >::previous_module_state_ private
Definition at line 141 of file ModuleBase.hpp.
The documentation for this class was generated from the following file:
dynosam/include/dynosam/common/ModuleBase.hpp