DynoSAM: dyno::TrackletIdManager Class Reference
dyno::TrackletIdManager Class Reference
Singleton class to manage a global tracklet id for all trackers to ensure they are unique.
#include <FeatureTrackerBase.hpp>
Public Member Functions
TrackletId getTrackletIdCount () const
void incrementTrackletIdCount ()
TrackletId getAndIncrementTrackletId ()
Static Public Member Functions
static TrackletIdManager & instance ()
Private Member Functions
TrackletIdManager ()=default
Private Attributes
TrackletId tracklet_count_ {0}
std::mutex mutex_
Global TrackletId.
Static Private Attributes
static std::unique_ptr< TrackletIdManager > instance_
Detailed Description
Singleton class to manage a global tracklet id for all trackers to ensure they are unique.
Definition at line 48 of file FeatureTrackerBase.hpp.
Constructor & Destructor Documentation
TrackletIdManager()
dyno::TrackletIdManager::TrackletIdManager () private default
Referenced by instance().
Member Function Documentation
getAndIncrementTrackletId()
TrackletId dyno::TrackletIdManager::getAndIncrementTrackletId () inline
Definition at line 68 of file FeatureTrackerBase.hpp.
{
    // tbb::mutex::scoped_lock lock(mutex_);
    auto tracklet = tracklet_count_;
    tracklet_count_++;
    return tracklet;
  }
References tracklet_count_.
Referenced by dyno::FeatureTracker::sampleDynamic().
getTrackletIdCount()
TrackletId dyno::TrackletIdManager::getTrackletIdCount () const inline
Definition at line 59 of file FeatureTrackerBase.hpp.
{
    // tbb::mutex::scoped_lock lock(mutex_);
    return tracklet_count_;
  }
References tracklet_count_.
Referenced by dyno::KltFeatureTracker::constructNewStaticFeature(), dyno::FeatureTracker::trackDynamic(), and dyno::ExternalFlowFeatureTracker::trackStatic().
incrementTrackletIdCount()
void dyno::TrackletIdManager::incrementTrackletIdCount () inline
Definition at line 63 of file FeatureTrackerBase.hpp.
{
    // tbb::mutex::scoped_lock lock(mutex_);
    tracklet_count_++;
  }
References tracklet_count_.
Referenced by dyno::KltFeatureTracker::constructNewStaticFeature(), dyno::FeatureTracker::trackDynamic(), and dyno::ExternalFlowFeatureTracker::trackStatic().
instance()
static TrackletIdManager & dyno::TrackletIdManager::instance () inline static
Definition at line 52 of file FeatureTrackerBase.hpp.
{
    if (!instance_) {
      instance_.reset(new TrackletIdManager());
    }
    return *instance_;
  }
References instance_, and TrackletIdManager().
Referenced by dyno::KltFeatureTracker::constructNewStaticFeature(), dyno::FeatureTracker::sampleDynamic(), dyno::FeatureTracker::trackDynamic(), and dyno::ExternalFlowFeatureTracker::trackStatic().
Member Data Documentation
instance_
decltype(TrackletIdManager::instance_) dyno::TrackletIdManager::instance_ static private
Definition at line 80 of file FeatureTrackerBase.hpp.
Referenced by instance().
mutex_
std::mutex dyno::TrackletIdManager::mutex_ private
Global TrackletId.
Definition at line 78 of file FeatureTrackerBase.hpp.
tracklet_count_
TrackletId dyno::TrackletIdManager::tracklet_count_ {0} private
Definition at line 77 of file FeatureTrackerBase.hpp.
Referenced by getAndIncrementTrackletId(), getTrackletIdCount(), and incrementTrackletIdCount().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/frontend/vision/FeatureTrackerBase.hpp
dynosam/src/frontend/vision/FeatureTrackerBase.cc