DynoSAM: ThreadsafeQueue< T > Class Template Reference
ThreadsafeQueue< T > Class Template Reference
#include <ThreadSafeQueue.hpp>
Public Types
using Type = T
using TQB = ThreadsafeQueueBase< T >
Public Member Functions
ThreadsafeQueue (size_t queue_size_=-1)
virtual ~ThreadsafeQueue ()=default
bool push (T new_value) override
Push by value. Returns false if the queue has been shutdown. Not optimal, since it will make two move operations. But it does the job: see Item 41 Effective Modern C++.
bool pushBlockingIfFull (T new_value, size_t max_queue_size=10u) override
pushBlockingIfFull pushes a value into the queue only if the queue is not filled with more than a given maximum size.
bool popBlocking (T &value) override
Pop value. Waits for data to be available in the queue. Returns false if the queue has been shutdown.
std::shared_ptr< T > popBlocking () override
Pop value. Waits for data to be available in the queue. If the queue has been shutdown, it returns a null shared_ptr.
bool popBlockingWithTimeout (T &value, size_t duration_ms) override
popBlockingUpToTime Same as Pop blocking, but further returns early if the given duration has passed...
bool pop (T &value) override
Pop without blocking, just checks once if the queue is empty. Returns true if the value could be retrieved, false otherwise.
std::shared_ptr< T > pop () override
Pop without blocking, just checks once if the queue is empty. Returns a shared_ptr to the value retrieved. If the queue is empty or has been shutdown, it returns a null shared_ptr.
bool popAll (std::vector< T > &data, size_t duration_ms=0u)
Public Member Functions inherited from ThreadsafeQueueBase< T >
virtual bool push (T new_value)=0
Push by value. Returns false if the queue has been shutdown. Not optimal, since it will make two move operations. But it does the job: see Item 41 Effective Modern C++.
virtual bool pushBlockingIfFull (T new_value, size_t max_queue_size=10u)=0
pushBlockingIfFull pushes a value into the queue only if the queue is not filled with more than a given maximum size.
virtual bool popBlocking (T &value)=0
Pop value. Waits for data to be available in the queue. Returns false if the queue has been shutdown.
virtual std::shared_ptr< T > popBlocking ()=0
Pop value. Waits for data to be available in the queue. If the queue has been shutdown, it returns a null shared_ptr.
virtual bool popBlockingWithTimeout (T &value, size_t duration_ms)=0
virtual bool pop (T &value)=0
Pop without blocking, just checks once if the queue is empty. Returns true if the value could be retrieved, false otherwise.
virtual std::shared_ptr< T > pop ()=0
Pop without blocking, just checks once if the queue is empty. Returns a shared_ptr to the value retrieved. If the queue is empty or has been shutdown, it returns a null shared_ptr.
int size ()
void shutdown ()
bool isShutdown ()
void resume ()
bool empty () const
Checks if the queue is empty. the state of the queue might change right after this query.
void clear ()
bool isShutdown () const
Checks if the queue is shutdown. the state of the queue might change right after this query.
Private Attributes
const size_t queue_size
std::condition_variable data_cond_
InternalQueue data_queue_
mutable for empty() and copy-constructor.
std::mutex mutex_
std::atomic_bool shutdown_
Additional Inherited Members
Protected Types inherited from ThreadsafeQueueBase< T >
typedef std::queue< std::shared_ptr< T > > InternalQueue
Protected Member Functions inherited from ThreadsafeQueueBase< T >
ThreadsafeQueueBase ()
virtual ~ThreadsafeQueueBase ()=default
Protected Attributes inherited from ThreadsafeQueueBase< T >
std::mutex mutex_
InternalQueue data_queue_
mutable for empty() and copy-constructor.
std::condition_variable data_cond_
std::atomic_bool shutdown_
Detailed Description
template<typename T>
class ThreadsafeQueue< T >
Definition at line 157 of file ThreadSafeQueue.hpp.
Member Typedef Documentation
TQB
template<typename T > using ThreadsafeQueue< T >::TQB = ThreadsafeQueueBase<T>
Definition at line 160 of file ThreadSafeQueue.hpp.
Type
template<typename T > using ThreadsafeQueue< T >::Type = T
Definition at line 159 of file ThreadSafeQueue.hpp.
Constructor & Destructor Documentation
ThreadsafeQueue()
template<typename T > ThreadsafeQueue< T >::ThreadsafeQueue (size_t queue_size_ = -1) explicit
Definition at line 238 of file ThreadSafeQueue.hpp.
    : ThreadsafeQueueBase<T>(), queue_size(queue_size_) {}
~ThreadsafeQueue()
template<typename T > virtual ThreadsafeQueue< T >::~ThreadsafeQueue () virtual default
Member Function Documentation
pop() [1/2]
template<typename T > std::shared_ptr< T > ThreadsafeQueue< T >::pop override virtual
Pop without blocking, just checks once if the queue is empty. Returns a shared_ptr to the value retrieved. If the queue is empty or has been shutdown, it returns a null shared_ptr.
Implements ThreadsafeQueueBase< T >.
Definition at line 333 of file ThreadSafeQueue.hpp.
{
  if (shutdown_) return std::shared_ptr<T>(nullptr);
  std::unique_lock<std::mutex> lk(mutex_);
  if (data_queue_.empty()) return std::shared_ptr<T>(nullptr);
  std::shared_ptr<T> result = data_queue_.front();
  data_queue_.pop();
  lk.unlock();  // Unlock before notify.
  data_cond_.notify_one();
  return result;
}
pop() [2/2]
template<typename T > bool ThreadsafeQueue< T >::pop (T & value) override virtual
Pop without blocking, just checks once if the queue is empty. Returns true if the value could be retrieved, false otherwise.
Implements ThreadsafeQueueBase< T >.
Definition at line 321 of file ThreadSafeQueue.hpp.
{
  if (shutdown_) return false;
  std::unique_lock<std::mutex> lk(mutex_);
  if (data_queue_.empty()) return false;
  value = std::move(*data_queue_.front());
  data_queue_.pop();
  lk.unlock();  // Unlock before notify.
  data_cond_.notify_one();
  return true;
}
Referenced by dyno::DataInterfacePipeline::getInputPacket().
popAll()
template<typename T > bool ThreadsafeQueue< T >::popAll (std::vector< T > & data, size_t duration_ms = 0u)
Definition at line 346 of file ThreadSafeQueue.hpp.
{
  std::unique_lock<std::mutex> lk(mutex_);
  data.clear();
  // Wait until there is data in the queue, shutdown is requested, or
  // the given time is elapsed...
  data_cond_.wait_for(lk, std::chrono::milliseconds(duration_ms),
                      [this] { return !data_queue_.empty() || shutdown_; });
  while (!data_queue_.empty()) {
    if (shutdown_) {
      break;
    }
    T value = std::move(*data_queue_.front());
    data.push_back(value);
    data_queue_.pop();
  }
  return !data.empty();
}
Referenced by dyno::OpenCVImageDisplayQueue::process().
popBlocking() [1/2]
template<typename T > std::shared_ptr< T > ThreadsafeQueue< T >::popBlocking override virtual
Pop value. Waits for data to be available in the queue. If the queue has been shutdown, it returns a null shared_ptr.
Implements ThreadsafeQueueBase< T >.
Definition at line 294 of file ThreadSafeQueue.hpp.
{
  std::unique_lock<std::mutex> lk(mutex_);
  data_cond_.wait(lk, [this] { return !data_queue_.empty() || shutdown_; });
  if (shutdown_) return std::shared_ptr<T>(nullptr);
  std::shared_ptr<T> result = data_queue_.front();
  data_queue_.pop();
  lk.unlock();  // Unlock before notify.
  data_cond_.notify_one();
  return result;
}
popBlocking() [2/2]
template<typename T > bool ThreadsafeQueue< T >::popBlocking (T & value) override virtual
Pop value. Waits for data to be available in the queue. Returns false if the queue has been shutdown.
Implements ThreadsafeQueueBase< T >.
Definition at line 280 of file ThreadSafeQueue.hpp.
{
  std::unique_lock<std::mutex> lk(mutex_);
  // Wait until there is data in the queue or shutdown requested.
  data_cond_.wait(lk, [this] { return !data_queue_.empty() || shutdown_; });
  // Return false in case shutdown is requested.
  if (shutdown_) return false;
  value = std::move(*data_queue_.front());
  data_queue_.pop();
  lk.unlock();  // Unlock before notify.
  data_cond_.notify_one();
  return true;
}
Referenced by dyno::DataInterfacePipeline::getInputPacket(), and dyno::OpenCVImageDisplayQueue::process().
popBlockingWithTimeout()
template<typename T > bool ThreadsafeQueue< T >::popBlockingWithTimeout (T & value, size_t duration_ms) override virtual
popBlockingUpToTime Same as Pop blocking, but further returns early if the given duration has passed...
Parameters
value Returned value
duration_ms Time to wait for a msg [in milliseconds]
Returns
Returns false if the queue has been shutdown or if it was timeout.
Implements ThreadsafeQueueBase< T >.
Definition at line 306 of file ThreadSafeQueue.hpp.
{
  std::unique_lock<std::mutex> lk(mutex_);
  // Wait until there is data in the queue, shutdown is requested, or
  // the given time is elapsed...
  data_cond_.wait_for(lk, std::chrono::milliseconds(duration_ms),
                      [this] { return !data_queue_.empty() || shutdown_; });
  // Return false in case shutdown is requested or the queue is empty (in which
  // case, a timeout has happened).
  if (shutdown_ || data_queue_.empty()) return false;
  value = std::move(*data_queue_.front());
  data_queue_.pop();
  return true;
}
push()
template<typename T > bool ThreadsafeQueue< T >::push (T new_value) override virtual
Push by value. Returns false if the queue has been shutdown. Not optimal, since it will make two move operations. But it does the job: see Item 41 Effective Modern C++.
Alternatives: Using both:
push(const T&)
with push(T&&) rvalue to the queue using move semantics. Since there is no type deduction, T&& is NOT a universal reference (typename T is not at the level of the push function). Problem: virtual keyword will make push(T&&) be discarded for push(const T&), non-copyable things will compile-complain.
Implements ThreadsafeQueueBase< T >.
Definition at line 242 of file ThreadSafeQueue.hpp.
{
  if (shutdown_) return false;  // atomic, no lock needed.
  std::shared_ptr<T> data(std::make_shared<T>(std::move(new_value)));
  std::unique_lock<std::mutex> lk(mutex_);
  if (queue_size > 0) {
    // greater than or equal?
    while (data_queue_.size() >= queue_size) {
      data_queue_.pop();
    }
  }
  data_queue_.push(data);
  lk.unlock();  // Unlock before notify.
  data_cond_.notify_one();
  // Thread-safe so doesn't need external mutex
  return true;
}
Referenced by dyno::DataInterfacePipeline::fillImageContainerQueue(), and dyno::RGBDInstanceFrontendModule::nominalSpin().
pushBlockingIfFull()
template<typename T > bool ThreadsafeQueue< T >::pushBlockingIfFull (T new_value, size_t max_queue_size = 10u) override virtual
pushBlockingIfFull pushes a value into the queue only if the queue is not filled with more than a given maximum size.
*
Parameters
new_value new value to add to the queue
max_queue_size if the queue is filled with more than max_queue_size messages, it will not push to the queue, and it will wait for a consumer to remove messages.
Returns
false if the queue has been shutdown
Implements ThreadsafeQueueBase< T >.
Definition at line 262 of file ThreadSafeQueue.hpp.
{
  if (shutdown_) return false;  // atomic, no lock needed.
  std::shared_ptr<T> data(std::make_shared<T>(std::move(new_value)));
  std::unique_lock<std::mutex> lk(mutex_);
  // Wait until the queue has space or shutdown requested.
  data_cond_.wait(lk, [this, max_queue_size] {
    return data_queue_.size() < max_queue_size || shutdown_;
  });
  if (shutdown_) return false;
  data_queue_.push(data);
  lk.unlock();  // Unlock before notify.
  data_cond_.notify_one();
  // Thread-safe so doesn't need external mutex.
  return true;
}
Member Data Documentation
data_cond_
template<typename T > std::condition_variable ThreadsafeQueueBase< T >::data_cond_ private
Definition at line 152 of file ThreadSafeQueue.hpp.
data_queue_
template<typename T > InternalQueue ThreadsafeQueueBase< T >::data_queue_ private
mutable for empty() and copy-constructor.
Definition at line 151 of file ThreadSafeQueue.hpp.
mutex_
template<typename T > std::mutex ThreadsafeQueueBase< T >::mutex_ mutable private
Definition at line 150 of file ThreadSafeQueue.hpp.
queue_size
template<typename T > const size_t ThreadsafeQueue< T >::queue_size private
Definition at line 230 of file ThreadSafeQueue.hpp.
shutdown_
template<typename T > std::atomic_bool ThreadsafeQueueBase< T >::shutdown_ private
Definition at line 153 of file ThreadSafeQueue.hpp.
The documentation for this class was generated from the following file:
dynosam/include/dynosam/pipeline/ThreadSafeQueue.hpp