DynoSAM: dyno::WorldPoseAccessor Class Reference
dyno::WorldPoseAccessor Class Reference
#include <WorldPoseEstimator.hpp>
Public Member Functions
WorldPoseAccessor (const SharedFormulationData &shared_data, MapVision::Ptr map)
virtual ~WorldPoseAccessor ()
StateQuery< gtsam::Pose3 > getSensorPose (FrameId frame_id) const override
Get the sensor pose (^wX_k) from theta at the requested time-step.
virtual StateQuery< gtsam::Pose3 > getObjectMotion (FrameId frame_id, ObjectId object_id) const override
Get an absolute object motion (_{k-1}^wH_k) from theta the requested time-step (k) and object (j).
virtual StateQuery< gtsam::Pose3 > getObjectPose (FrameId frame_id, ObjectId object_id) const override
Get the pose (^wL_k) of an object (j) at time-step (k).
StateQuery< gtsam::Point3 > getDynamicLandmark (FrameId frame_id, TrackletId tracklet_id) const override
Get a dynamic landmark (^wm_k) with tracklet id (i) at time-step (k).
Public Member Functions inherited from dyno::AccessorT< MapVision >
AccessorT (const SharedFormulationData &shared_data, typename Map::Ptr map)
virtual ~AccessorT ()
StateQuery< Motion3ReferenceFrame > getObjectMotionReferenceFrame (FrameId frame_id, ObjectId object_id) const override
Gets the absolute motion (_{k-1}^wH_k) from theta the requested time-step (k) and object (j) with the associated reference frame. Internally this uses getObjectMotion and constructs a Motion3ReferenceFrame using the global frame, k-1 and k. No checks are done on the underlying function call so it assumes that the virtual getObjectMotion function has been implemented correctly and returns a motion in the right representation.
virtual StateQuery< gtsam::Point3 > getStaticLandmark (TrackletId tracklet_id) const override
Get a static landmark (^wm) with tracklet id (i).
virtual EstimateMap< ObjectId, gtsam::Pose3 > getObjectPoses (FrameId frame_id) const override
Collects all object poses at some time-step (k). See Accessor::getObjectPoses(FrameId)
virtual ObjectPoseMap getObjectPoses () const override
Collects all object poses for frame 0 to K. (Non-pure)Virtual function that may be overwritten - default implementation uses the pure-virtual getObjectPoses to collect all poses.
MotionEstimateMap getObjectMotions (FrameId frame_id) const override
Collects all object motions (_{k-1}^wH_k) from time-step (k-1) to k. This is equivalent to \mathcal{H}_k. Uses the pure-virtual getObjectMotion function to collect all object motions.
virtual ObjectMotionMap getObjectMotions () const override
Collects all object motions from 1 to K (with the first motion being from k-1 to k).
StatusLandmarkVector getDynamicLandmarkEstimates (FrameId frame_id) const override
Get all dynamic landmarks for all objects (\mathcal{J}_k) at time-step k.
virtual StatusLandmarkVector getDynamicLandmarkEstimates (FrameId frame_id, ObjectId object_id) const override
Get all dynamic landmarks for object j at time-step k.
StatusLandmarkVector getStaticLandmarkEstimates (FrameId frame_id) const override
Get all static landmarks at time-step k.
StatusLandmarkVector getFullStaticMap () const override
Get all static landmarks from time-step 0 to k.
bool hasObjectMotionEstimate (FrameId frame_id, ObjectId object_id, Motion3 *motion=nullptr) const override
Check if there exists an estimate for object motion at time-step (k) for object id (j). If result is true and a motion is provided, return true and set the motion.
bool hasObjectPoseEstimate (FrameId frame_id, ObjectId object_id, gtsam::Pose3 *pose=nullptr) const override
Check if there exists an estimate for object pose at time-step (k) for object id (j). If result is true and a pose is provided, return true and set the pose.
gtsam::FastMap< ObjectId, gtsam::Point3 > computeObjectCentroids (FrameId frame_id) const override
Computes a the centroid of each object at this frame using the estimated dynamic points.
bool exists (gtsam::Key key) const
Check if the key exists in the current theta.
StateQuery< ValueType > query (gtsam::Key key) const
Access a key in the current theta.
Public Member Functions inherited from dyno::Accessor
Accessor ()=default
virtual ~Accessor ()
virtual StateQuery< gtsam::Pose3 > getSensorPose (FrameId frame_id) const =0
Get the sensor pose (^wX_k) from theta at the requested time-step.
virtual StateQuery< gtsam::Pose3 > getObjectMotion (FrameId frame_id, ObjectId object_id) const =0
Get an absolute object motion (_{k-1}^wH_k) from theta the requested time-step (k) and object (j).
virtual StateQuery< Motion3ReferenceFrame > getObjectMotionReferenceFrame (FrameId frame_id, ObjectId object_id) const =0
Gets the motion _{k-1}^wH_k attime-step (k) and object (j) with the associated reference frame.
virtual StateQuery< gtsam::Pose3 > getObjectPose (FrameId frame_id, ObjectId object_id) const =0
Get the pose (^wL_k) of an object (j) at time-step (k).
virtual StateQuery< gtsam::Point3 > getDynamicLandmark (FrameId frame_id, TrackletId tracklet_id) const =0
Get a dynamic landmark (^wm_k) with tracklet id (i) at time-step (k).
virtual StateQuery< gtsam::Point3 > getStaticLandmark (TrackletId tracklet_id) const =0
Get a static landmark (^wm) with tracklet id (i).
virtual EstimateMap< ObjectId, gtsam::Pose3 > getObjectPoses (FrameId frame_id) const =0
Collects all object poses at some time-step (k). This is equivalent to \mathcal{L}_k. Is a (non-pure) virtual function so may be overwritten - default implementation uses the pure-virtual getObjectPose function to collect all object poses.
virtual MotionEstimateMap getObjectMotions (FrameId frame_id) const =0
Collects all object motions (_{k-1}^wH_k) from time-step (k-1) to k. This is equivalent to \mathcal{H}_k.
virtual ObjectPoseMap getObjectPoses () const =0
Collects all object poses for frame 0 to K. (Non-pure)Virtual function that may be overwritten.
virtual ObjectMotionMap getObjectMotions () const =0
Collects all object motions from 1 to K (with the first motion being from k-1 to k). (Non-pure) Virtual function that may be overwritten - default implementation uses the pure-virtual getObjectPoses to collect all motions.
virtual StatusLandmarkVector getDynamicLandmarkEstimates (FrameId frame_id) const =0
Get all dynamic landmarks for all objects (\mathcal{J}_k) at time-step k.
virtual StatusLandmarkVector getDynamicLandmarkEstimates (FrameId frame_id, ObjectId object_id) const =0
Get all dynamic landmarks for object j at time-step k.
virtual StatusLandmarkVector getStaticLandmarkEstimates (FrameId frame_id) const =0
Get all static landmarks at time-step k.
virtual StatusLandmarkVector getFullStaticMap () const =0
Get all static landmarks from time-step 0 to k.
virtual bool hasObjectMotionEstimate (FrameId frame_id, ObjectId object_id, Motion3 *motion) const =0
Check if there exists an estimate for object motion at time-step (k) for object id (j). If result is true and a motion is provided, return true and set the motion.
virtual bool hasObjectPoseEstimate (FrameId frame_id, ObjectId object_id, gtsam::Pose3 *pose) const =0
Check if there exists an estimate for object pose at time-step (k) for object id (j). If result is true and a pose is provided, return true and set the pose.
virtual gtsam::FastMap< ObjectId, gtsam::Point3 > computeObjectCentroids (FrameId frame_id) const =0
Computes a the centroid of each object at this frame using the estimated dynamic points.
StatusLandmarkVector getLandmarkEstimates (FrameId frame_id) const
Get all landmarks (static and dynamic) at time-step k.
std::tuple< gtsam::Point3, bool > computeObjectCentroid (FrameId frame_id, ObjectId object_id) const
Computes the centroid of the requested object using the estimated dynamic points.
bool hasObjectPoseEstimate (FrameId frame_id, ObjectId object_id, gtsam::Pose3 &pose) const
Check if there exists an estimate for object pose at time-step (k) for object id (j). If result is true, pose reference value is set to the pose.
bool hasObjectMotionEstimate (FrameId frame_id, ObjectId object_id, Motion3 &motion) const
Check if there exists an estimate for object motion at time-step (k) for object id (j). If result is true, motion reference value is set to the motion.
Additional Inherited Members
Public Types inherited from dyno::AccessorT< MapVision >
using Map = MapVision
using This = AccessorT< Map >
Protected Member Functions inherited from dyno::AccessorT< MapVision >
auto map () const
const gtsam::Values & values () const
const FormulationHooks & hooks () const
Detailed Description
Definition at line 39 of file WorldPoseEstimator.hpp.
Constructor & Destructor Documentation
WorldPoseAccessor()
dyno::WorldPoseAccessor::WorldPoseAccessor (const SharedFormulationData & shared_data, MapVision::Ptr map) inline
Definition at line 41 of file WorldPoseEstimator.hpp.
      : AccessorT<MapVision>(shared_data, map) {}
~WorldPoseAccessor()
virtual dyno::WorldPoseAccessor::~WorldPoseAccessor () inline virtual
Definition at line 44 of file WorldPoseEstimator.hpp.
{}
Member Function Documentation
getDynamicLandmark()
StateQuery< gtsam::Point3 > dyno::WorldPoseAccessor::getDynamicLandmark (FrameId frame_id, TrackletId tracklet_id) const override virtual
Get a dynamic landmark (^wm_k) with tracklet id (i) at time-step (k).
Parameters
frame_id FrameId
tracklet_id TrackletId
Returns
StateQuery<gtsam::Point3>
Implements dyno::Accessor.
Definition at line 81 of file WorldPoseEstimator.cc.
{
  const auto lmk = map()->getLandmark(tracklet_id);
  CHECK_NOTNULL(lmk);
  return this->query<gtsam::Point3>(lmk->makeDynamicKey(frame_id));
}
References dyno::AccessorT< MapVision >::map().
getObjectMotion()
StateQuery< gtsam::Pose3 > dyno::WorldPoseAccessor::getObjectMotion (FrameId frame_id, ObjectId object_id) const override virtual
Get an absolute object motion (_{k-1}^wH_k) from theta the requested time-step (k) and object (j).
Parameters
frame_id FrameId
object_id ObjectId
Returns
StateQuery<gtsam::Pose3>
Implements dyno::Accessor.
Reimplemented in dyno::WorldMotionAccessor.
Definition at line 46 of file WorldPoseEstimator.cc.
{
  const auto frame_node_k = map()->getFrame(frame_id);
  CHECK_NOTNULL(frame_node_k);
  const auto object_motion_key = frame_node_k->makeObjectMotionKey(object_id);
  if (frame_id < 2) {
    // if the current frame is 1 then skip as we never get a frame that is 0
    // this is because the first frame (frame_id=0) is never sent to the backend
    // as at least two frames (0 and 1) are needed to track!
    return StateQuery<gtsam::Pose3>::NotInMap(object_motion_key);
  }
  const auto object_pose_k = this->getObjectPose(frame_id, object_id);
  const auto object_pose_k_1 = this->getObjectPose(frame_id - 1u, object_id);
  if (object_pose_k && object_pose_k_1) {
    // ^w_{k-1}H_k = ^wL_k \: ^wL_{k-1}^{-1}
    const gtsam::Pose3 motion =
        object_pose_k.get() * object_pose_k_1->inverse();
    return StateQuery<gtsam::Pose3>{object_motion_key, motion};
  }
  return StateQuery<gtsam::Pose3>::NotInMap(object_motion_key);
}
References getObjectPose(), dyno::AccessorT< MapVision >::map(), and dyno::StateQuery< ValueType >::NotInMap().
getObjectPose()
StateQuery< gtsam::Pose3 > dyno::WorldPoseAccessor::getObjectPose (FrameId frame_id, ObjectId object_id) const override virtual
Get the pose (^wL_k) of an object (j) at time-step (k).
Parameters
frame_id FrameId
object_id ObjectId
Returns
StateQuery<gtsam::Pose3>
Implements dyno::Accessor.
Reimplemented in dyno::WorldMotionAccessor.
Definition at line 70 of file WorldPoseEstimator.cc.
{
  const auto frame_node = map()->getFrame(frame_id);
  if (!frame_node) {
    return StateQuery<gtsam::Pose3>::InvalidMap();
  }
  // CHECK(frame_node) << "Frame Id is null at frame " << frame_id;
  return this->query<gtsam::Pose3>(frame_node->makeObjectPoseKey(object_id));
}
References dyno::StateQuery< ValueType >::InvalidMap(), and dyno::AccessorT< MapVision >::map().
Referenced by getObjectMotion().
getSensorPose()
StateQuery< gtsam::Pose3 > dyno::WorldPoseAccessor::getSensorPose (FrameId frame_id) const override virtual
Get the sensor pose (^wX_k) from theta at the requested time-step.
Parameters
frame_id FrameId
Returns
StateQuery<gtsam::Pose3>
Implements dyno::Accessor.
Definition at line 39 of file WorldPoseEstimator.cc.
{
  const auto frame_node = map()->getFrame(frame_id);
  CHECK_NOTNULL(frame_node);
  return this->query<gtsam::Pose3>(frame_node->makePoseKey());
}
References dyno::AccessorT< MapVision >::map().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/backend/rgbd/WorldPoseEstimator.hpp
dynosam/src/backend/rgbd/WorldPoseEstimator.cc