DynoSAM: dyno::MeasurementWithCovariance< T, D > Class Template Reference
dyno::MeasurementWithCovariance< T, D > Class Template Reference
Defines a measurement/value with associated covariance matrix.
#include <SensorModels.hpp>
Public Types
using This = MeasurementWithCovariance< T, D >
using Covariance = Eigen::Matrix< double, D, D >
D x D covariance matrix.
using Sigmas = Eigen::Matrix< double, D, 1 >
D x 1 sigma matrix used to construct the covariance matrix.
using Optional = std::optional< This >
Optional alias.
Public Member Functions
MeasurementWithCovariance ()=default
Empty constructor.
MeasurementWithCovariance (const T &measurement, const gtsam::SharedGaussian &model)
Construct object using a measurement and a gtsam::SharedGaussian, representing the noise model/uncertainty of the measurement.
MeasurementWithCovariance (const T &measurement)
Construct object using only a measurement type, indicatating there is no associated noise model/uncertainty. The resulting model will be none and the covariance matrix will be all zeros.
MeasurementWithCovariance (const std::pair< T, Covariance > &pair)
MeasurementWithCovariance (const T &measurement, const Covariance &covariance)
Construct object using a measurement type and associated covariance matrix. The covariance matrix is used to construct the underlying sensor noise model using gtsam::noiseModel::Gaussian.
const T & measurement () const
const gtsam::SharedGaussian & model () const
bool hasModel () const
Covariance covariance () const
operator const T & () const
Very important to have these cast operators so we can use Base::asType to cast to the internal data.
operator Covariance () const
void print (const std::string &s="") const
bool equals (const MeasurementWithCovariance &other, double tol=1e-8) const
Static Public Member Functions
static MeasurementWithCovariance FromSigmas (const T &measurement, const Sigmas &sigmas)
Construct object using a measurement type and associated sigma vector. The sigma's represent the on-diagonal values for the covariance matrix and are used to construct the underlying sensor noise model using gtsam::noiseModel::Gaussian.
Static Public Attributes
static constexpr auto dimension = D
Need to have dimension to satisfy gtsam::dimemsions.
Private Attributes
T measurement_
Measurement.
gtsam::SharedGaussian model_ {nullptr}
Friends
std::ostream & operator<< (std::ostream &os, const This &measurement_with_cov)
Detailed Description
template<typename T, int D = gtsam::traits<T>::dimension>
class dyno::MeasurementWithCovariance< T, D >
Defines a measurement/value with associated covariance matrix.
Depending on the context, this model can either represent the uncertainty on a measurement or the marginal covariance of an estimate. In the latter context, the name "Measurement"WithCovariance is misleading (as it would not be a measurement), so to all state-estimation people I profusely apologise.
The covariance can be optionally provided.
We define the dimensions of this type and provide an equals function to make it compatible with gtsam::traits<T>::dimension and gtsam::traits<T>::Equals.
Template Parameters
T measurement type
D dimension of the measurement. Used to construct the covariance matrix.
Definition at line 203 of file SensorModels.hpp.
Member Typedef Documentation
Covariance
template<typename T , int D = gtsam::traits<T>::dimension> using dyno::MeasurementWithCovariance< T, D >::Covariance = Eigen::Matrix<double, D, D>
D x D covariance matrix.
Definition at line 209 of file SensorModels.hpp.
Optional
template<typename T , int D = gtsam::traits<T>::dimension> using dyno::MeasurementWithCovariance< T, D >::Optional = std::optional<This>
Optional alias.
Definition at line 213 of file SensorModels.hpp.
Sigmas
template<typename T , int D = gtsam::traits<T>::dimension> using dyno::MeasurementWithCovariance< T, D >::Sigmas = Eigen::Matrix<double, D, 1>
D x 1 sigma matrix used to construct the covariance matrix.
Definition at line 211 of file SensorModels.hpp.
This
template<typename T , int D = gtsam::traits<T>::dimension> using dyno::MeasurementWithCovariance< T, D >::This = MeasurementWithCovariance<T, D>
Definition at line 205 of file SensorModels.hpp.
Constructor & Destructor Documentation
MeasurementWithCovariance() [1/5]
template<typename T , int D = gtsam::traits<T>::dimension> dyno::MeasurementWithCovariance< T, D >::MeasurementWithCovariance () default
Empty constructor.
Referenced by dyno::MeasurementWithCovariance< T, D >::FromSigmas().
MeasurementWithCovariance() [2/5]
template<typename T , int D = gtsam::traits<T>::dimension> dyno::MeasurementWithCovariance< T, D >::MeasurementWithCovariance (const T & measurement, const gtsam::SharedGaussian & model) inline
Construct object using a measurement and a gtsam::SharedGaussian, representing the noise model/uncertainty of the measurement.
Exceptions
DynosamException If the provided model has dimensions that do not match the templated dimensions D.
Parameters
measurement const T&
model const gtsam::SharedGaussian&
Definition at line 231 of file SensorModels.hpp.
      : measurement_(measurement), model_(CHECK_NOTNULL(model)) {
    if (static_cast<int>(model->dim()) != This::dimension) {
      DYNO_THROW_MSG(DynosamException)
          << "Invalid gtsam::SharedGaussian model provided to "
          << "MeasurementWithCovariance. Type dimensions are "
          << This::dimension << " but noise models dims are " << model->dim();
    }
  }
References dyno::MeasurementWithCovariance< T, D >::dimension, DYNO_THROW_MSG, and dyno::MeasurementWithCovariance< T, D >::model().
MeasurementWithCovariance() [3/5]
template<typename T , int D = gtsam::traits<T>::dimension> dyno::MeasurementWithCovariance< T, D >::MeasurementWithCovariance (const T & measurement) inline explicit
Construct object using only a measurement type, indicatating there is no associated noise model/uncertainty. The resulting model will be none and the covariance matrix will be all zeros.
We ensure this constructor is explicit to prevent unintended implicit conversions
Parameters
measurement const T&
Definition at line 252 of file SensorModels.hpp.
      : measurement_(measurement), model_(nullptr) {}
MeasurementWithCovariance() [4/5]
template<typename T , int D = gtsam::traits<T>::dimension> dyno::MeasurementWithCovariance< T, D >::MeasurementWithCovariance (const std::pair< T, Covariance > & pair) inline explicit
Definition at line 255 of file SensorModels.hpp.
      : MeasurementWithCovariance(pair.first, pair.second) {}
MeasurementWithCovariance() [5/5]
template<typename T , int D = gtsam::traits<T>::dimension> dyno::MeasurementWithCovariance< T, D >::MeasurementWithCovariance (const T & measurement, const Covariance & covariance) inline
Construct object using a measurement type and associated covariance matrix. The covariance matrix is used to construct the underlying sensor noise model using gtsam::noiseModel::Gaussian.
Parameters
measurement const T&
covariance const Covariance&
Returns
MeasurementWithCovariance
Definition at line 267 of file SensorModels.hpp.
      : measurement_(measurement),
        model_(gtsam::noiseModel::Gaussian::Covariance(covariance, false)) {}
Member Function Documentation
covariance()
template<typename T , int D = gtsam::traits<T>::dimension> Covariance dyno::MeasurementWithCovariance< T, D >::covariance () const inline
Definition at line 291 of file SensorModels.hpp.
{
    if (hasModel()) {
      return model_->covariance();
    } else {
      return Covariance::Zero();
    }
  }
References dyno::MeasurementWithCovariance< T, D >::hasModel(), and dyno::MeasurementWithCovariance< T, D >::model_.
Referenced by dyno::MeasurementWithCovariance< T, D >::operator Covariance().
equals()
template<typename T , int D = gtsam::traits<T>::dimension> bool dyno::MeasurementWithCovariance< T, D >::equals (const MeasurementWithCovariance< T, D > & other, double tol = 1e-8) const inline
Definition at line 330 of file SensorModels.hpp.
{
    return gtsam::traits<T>::Equals(measurement_, other.measurement_, tol) &&
           utils::equateGtsamSharedValues(model_, other.model_, tol);
  }
References dyno::utils::equateGtsamSharedValues(), dyno::MeasurementWithCovariance< T, D >::measurement_, and dyno::MeasurementWithCovariance< T, D >::model_.
FromSigmas()
template<typename T , int D = gtsam::traits<T>::dimension> static MeasurementWithCovariance dyno::MeasurementWithCovariance< T, D >::FromSigmas (const T & measurement, const Sigmas & sigmas) inline static
Construct object using a measurement type and associated sigma vector. The sigma's represent the on-diagonal values for the covariance matrix and are used to construct the underlying sensor noise model using gtsam::noiseModel::Gaussian.
Parameters
measurement const T&
covariance const Sigmas&
Returns
MeasurementWithCovariance
Definition at line 281 of file SensorModels.hpp.
{
    return MeasurementWithCovariance(
        measurement, gtsam::noiseModel::Diagonal::Sigmas(sigmas));
  }
References dyno::MeasurementWithCovariance< T, D >::measurement(), and dyno::MeasurementWithCovariance< T, D >::MeasurementWithCovariance().
Referenced by dyno::RGBDInstanceFrontendModule::fillOutputPacketWithTracks(), and dyno::CameraMeasurement::stereoMeasurement().
hasModel()
template<typename T , int D = gtsam::traits<T>::dimension> bool dyno::MeasurementWithCovariance< T, D >::hasModel () const inline
Definition at line 289 of file SensorModels.hpp.
{ return model_ != nullptr; }
References dyno::MeasurementWithCovariance< T, D >::model_.
Referenced by dyno::MeasurementWithCovariance< T, D >::covariance(), dyno::CameraMeasurement::stereoMeasurement(), and dyno::ParallelObjectISAM::updateFormulation().
measurement()
template<typename T , int D = gtsam::traits<T>::dimension> const T & dyno::MeasurementWithCovariance< T, D >::measurement () const inline
Definition at line 287 of file SensorModels.hpp.
{ return measurement_; }
References dyno::MeasurementWithCovariance< T, D >::measurement_.
Referenced by dyno::MeasurementWithCovariance< T, D >::FromSigmas(), dyno::get(), dyno::MeasurementWithCovariance< Depth >::operator const Depth &(), dyno::CameraMeasurement::stereoMeasurement(), and dyno::ParallelObjectISAM::updateFormulation().
model()
template<typename T , int D = gtsam::traits<T>::dimension> const gtsam::SharedGaussian & dyno::MeasurementWithCovariance< T, D >::model () const inline
Definition at line 288 of file SensorModels.hpp.
{ return model_; }
References dyno::MeasurementWithCovariance< T, D >::model_.
Referenced by dyno::get(), dyno::MeasurementWithCovariance< T, D >::MeasurementWithCovariance(), dyno::CameraMeasurement::stereoMeasurement(), and dyno::ParallelObjectISAM::updateFormulation().
operator const T &()
template<typename T , int D = gtsam::traits<T>::dimension> dyno::MeasurementWithCovariance< T, D >::operator const T & () const inline
Very important to have these cast operators so we can use Base::asType to cast to the internal data.
Definition at line 301 of file SensorModels.hpp.
{ return measurement(); }
operator Covariance()
template<typename T , int D = gtsam::traits<T>::dimension> dyno::MeasurementWithCovariance< T, D >::operator Covariance () const inline
Definition at line 302 of file SensorModels.hpp.
{ return covariance(); }
References dyno::MeasurementWithCovariance< T, D >::covariance().
print()
template<typename T , int D = gtsam::traits<T>::dimension> void dyno::MeasurementWithCovariance< T, D >::print (const std::string & s = "") const inline
Definition at line 326 of file SensorModels.hpp.
{
    std::cout << s << *this << std::endl;
  }
Friends And Related Function Documentation
operator<<
template<typename T , int D = gtsam::traits<T>::dimension> std::ostream & operator<< (std::ostream & os, const This & measurement_with_cov) friend
Definition at line 318 of file SensorModels.hpp.
{
    os << "m: " << measurement_with_cov.measurement()
       << ", cov: " << measurement_with_cov.covariance()
       << ", has model: " << std::boolalpha << measurement_with_cov.hasModel();
    return os;
  }
Member Data Documentation
dimension
template<typename T , int D = gtsam::traits<T>::dimension> constexpr auto dyno::MeasurementWithCovariance< T, D >::dimension = D inline static constexpr
Need to have dimension to satisfy gtsam::dimemsions.
Definition at line 207 of file SensorModels.hpp.
Referenced by dyno::MeasurementWithCovariance< T, D >::MeasurementWithCovariance().
measurement_
template<typename T , int D = gtsam::traits<T>::dimension> T dyno::MeasurementWithCovariance< T, D >::measurement_ private
Measurement.
Definition at line 338 of file SensorModels.hpp.
Referenced by dyno::MeasurementWithCovariance< T, D >::equals(), and dyno::MeasurementWithCovariance< T, D >::measurement().
model_
template<typename T , int D = gtsam::traits<T>::dimension> gtsam::SharedGaussian dyno::MeasurementWithCovariance< T, D >::model_ {nullptr} private
Noise model which can either be used to represet the covariance matrix of an estimate or the noise model of measurement
Definition at line 341 of file SensorModels.hpp.
Referenced by dyno::MeasurementWithCovariance< T, D >::covariance(), dyno::MeasurementWithCovariance< T, D >::equals(), dyno::MeasurementWithCovariance< T, D >::hasModel(), and dyno::MeasurementWithCovariance< T, D >::model().
The documentation for this class was generated from the following file:
dynosam_common/include/dynosam_common/SensorModels.hpp