DynoSAM: dyno::CameraParams Class Reference
dyno::CameraParams Class Reference
#include <CameraParams.hpp>
Public Types
using DistortionCoeffs = std::vector< double >
using IntrinsicsCoeffs = std::vector< double >
using CameraModel = std::string
Public Member Functions
CameraParams ()
Needed for IO construction.
CameraParams (const IntrinsicsCoeffs &intrinsics, const DistortionCoeffs &distortion, const cv::Size &image_size, const std::string &distortion_model, const gtsam::Pose3 &T_robot_camera=gtsam::Pose3::Identity())
Constructs the parameters for a specific camera.
CameraParams (const IntrinsicsCoeffs &intrinsics, const DistortionCoeffs &distortion, const cv::Size &image_size, const DistortionModel &distortion_model, const gtsam::Pose3 &T_robot_camera=gtsam::Pose3::Identity())
virtual ~CameraParams ()=default
double fx () const
double fy () const
double cu () const
double cv () const
int ImageWidth () const
int ImageHeight () const
const cv::Size & imageSize () const
cv::Mat getCameraMatrix () const
gtsam::Matrix3 getCameraMatrixEigen () const
cv::Mat getDistortionCoeffs () const
gtsam::Pose3 getExtrinsics () const
Get the camera extrinsics - the transform of the camera in the body frame (e.g T_robot_camera or ^RT_C)
DistortionModel getDistortionModel () const
bool equals (const CameraParams &other, double tol=1e-9) const
const std::string toString () const
template<typename CALIBRATION >
CALIBRATION constructGtsamCalibration () const
Static Public Member Functions
static void convertDistortionVectorToMatrix (const DistortionCoeffs &distortion_coeffs, cv::Mat *distortion_coeffs_mat)
static void convertIntrinsicsVectorToMatrix (const IntrinsicsCoeffs &intrinsics, cv::Mat *camera_matrix)
Converts the IntrinsicsCoeffs (in the form: fu, fy, cu, cv) to a 3x3 camera matrix in the form: [fx 0 cu] K = [ 0 fy cv] [ 0 0 1].
static void convertKMatrixToIntrinsicsCoeffs (const cv::Mat &K, IntrinsicsCoeffs &intrinsics)
Converts a 3x3 camera calibration matrix to an IntrinsicsCoeffs in the form fu, fy, cu, cv. K is expected to a be of type CV_64F;.
static DistortionModel stringToDistortion (const std::string &distortion_model, const std::string &camera_model)
stringToDistortion
static bool distortionModelToString (const DistortionModel &model, std::string &distortion_model, std::string &camera_model)
Converts the DistortionModel enum to a distortion model string and associated camera model.
Private Attributes
IntrinsicsCoeffs intrinsics_
fu, fv, cu, cv
DistortionCoeffs distortion_coeff_
cv::Size image_size_
DistortionModel distortion_model_
Distortion parameters.
gtsam::Pose3 T_robot_camera_
cv::Mat K_
Transform of the camera frame to the robot frame.
gtsam::Matrix3 K_eigen_
cv::Mat P_
cv::Mat D_
Detailed Description
Definition at line 56 of file CameraParams.hpp.
Member Typedef Documentation
CameraModel
using dyno::CameraParams::CameraModel = std::string
Definition at line 64 of file CameraParams.hpp.
DistortionCoeffs
using dyno::CameraParams::DistortionCoeffs = std::vector<double>
Definition at line 60 of file CameraParams.hpp.
IntrinsicsCoeffs
using dyno::CameraParams::IntrinsicsCoeffs = std::vector<double>
Definition at line 62 of file CameraParams.hpp.
Constructor & Destructor Documentation
CameraParams() [1/3]
dyno::CameraParams::CameraParams () inline
Needed for IO construction.
Definition at line 70 of file CameraParams.hpp.
{}
CameraParams() [2/3]
dyno::CameraParams::CameraParams (const IntrinsicsCoeffs & intrinsics, const DistortionCoeffs & distortion, const cv::Size & image_size, const std::string & distortion_model, const gtsam::Pose3 & T_robot_camera = gtsam::Pose3::Identity())
Constructs the parameters for a specific camera.
Distortion model expects a string as either "none", "plumb_bob", "radial-tangential", "radtan", "equidistant" or "kanna_brandt". The corresponding DistortionModel (enum) will then be assigned.
Parameters
intrinsics const IntrinsicsCoeffs& Coefficients for the intrinsics matrix. Should be in the form [fu fv cu cv]
distortion const DistortionCoeffs& Coefficients for the camera distortion.
image_size const cv::Size& Image width and height
distortion_model_ const std::string& Expected distortion model to be used for this camera.
T_robot_camera const gtsam::Pose3& The camera extrinsics describing the transformation of the camera in the robot frame
Definition at line 111 of file CameraParams.cc.
    : CameraParams(
          intrinsics, distortion, image_size,
          CameraParams::stringToDistortion(distortion_model, "pinhole"),
          T_robot_camera) {}
CameraParams() [3/3]
dyno::CameraParams::CameraParams (const IntrinsicsCoeffs & intrinsics, const DistortionCoeffs & distortion, const cv::Size & image_size, const DistortionModel & distortion_model, const gtsam::Pose3 & T_robot_camera = gtsam::Pose3::Identity())
Definition at line 121 of file CameraParams.cc.
    : intrinsics_(intrinsics),
      distortion_coeff_(distortion),
      image_size_(image_size),
      distortion_model_(distortion_model),
      T_robot_camera_(T_robot_camera) {
  CHECK_EQ(intrinsics_.size(), 4u)
      << "Intrinsics must be of length 4 - [fx fy cu cv]";
  CHECK_GT(distortion_coeff_.size(), 0u);
  CameraParams::convertDistortionVectorToMatrix(distortion_coeff_, &D_);
  CameraParams::convertIntrinsicsVectorToMatrix(intrinsics_, &K_);
  cv::cv2eigen(K_, K_eigen_);
  K_.copyTo(P_);
}
References convertDistortionVectorToMatrix(), convertIntrinsicsVectorToMatrix(), D_, distortion_coeff_, intrinsics_, K_, K_eigen_, and P_.
~CameraParams()
virtual dyno::CameraParams::~CameraParams () virtual default
Member Function Documentation
constructGtsamCalibration()
template<typename CALIBRATION > CALIBRATION dyno::CameraParams::constructGtsamCalibration () const
Referenced by dyno::Camera::Camera(), dyno::Frame::getFrameCamera(), dyno::RGBDBackendModule::getGtsamCalibration(), and dyno::ObjectMotionSovler::motionModelOutlierRejection3d2d().
convertDistortionVectorToMatrix()
void dyno::CameraParams::convertDistortionVectorToMatrix (const DistortionCoeffs & distortion_coeffs, cv::Mat * distortion_coeffs_mat) static
Definition at line 142 of file CameraParams.cc.
{
  *distortion_coeffs_mat = cv::Mat::zeros(1, distortion_coeffs.size(), CV_64F);
  for (int k = 0; k < distortion_coeffs_mat->cols; k++) {
    distortion_coeffs_mat->at<double>(0, k) = distortion_coeffs[k];
  }
}
Referenced by CameraParams().
convertIntrinsicsVectorToMatrix()
void dyno::CameraParams::convertIntrinsicsVectorToMatrix (const IntrinsicsCoeffs & intrinsics, cv::Mat * camera_matrix) static
Converts the IntrinsicsCoeffs (in the form: fu, fy, cu, cv) to a 3x3 camera matrix in the form: [fx 0 cu] K = [ 0 fy cv] [ 0 0 1].
The camera matrix type is CV_64F
Parameters
intrinsics const IntrinsicsCoeffs&
camera_matrix cv::Mat*
Definition at line 150 of file CameraParams.cc.
{
  *camera_matrix = cv::Mat::eye(3, 3, CV_64F);
  camera_matrix->at<double>(0, 0) = intrinsics[0];
  camera_matrix->at<double>(1, 1) = intrinsics[1];
  camera_matrix->at<double>(0, 2) = intrinsics[2];
  camera_matrix->at<double>(1, 2) = intrinsics[3];
}
Referenced by CameraParams().
convertKMatrixToIntrinsicsCoeffs()
void dyno::CameraParams::convertKMatrixToIntrinsicsCoeffs (const cv::Mat & K, IntrinsicsCoeffs & intrinsics) static
Converts a 3x3 camera calibration matrix to an IntrinsicsCoeffs in the form fu, fy, cu, cv. K is expected to a be of type CV_64F;.
Parameters
K const cv::Mat&
intrinsics IntrinsicsCoeffs&
Definition at line 159 of file CameraParams.cc.
{
  CHECK_EQ(K.type(), CV_64F) << "Cannot convert: Camera Matrix (K) is expected "
                                "to be of type CV_64F but is "
                             << utils::cvTypeToString(K.type());
  CHECK(K.rows == 3 && K.cols) << "Cannot convert: Camera Matrix (K) is "
                                  "expected to be of size (3 x 3) but is ["
                               << K.rows << " x " << K.cols << "]";
  ;
  intrinsics.resize(4);
  intrinsics[0] = K.at<double>(0, 0);
  intrinsics[1] = K.at<double>(1, 1);
  intrinsics[2] = K.at<double>(0, 2);
  intrinsics[3] = K.at<double>(1, 2);
}
References dyno::utils::cvTypeToString().
Referenced by rclcpp::TypeAdapter< dyno::CameraParams, sensor_msgs::msg::CameraInfo >::convert_to_custom().
cu()
double dyno::CameraParams::cu () const inline
Definition at line 103 of file CameraParams.hpp.
{ return intrinsics_[2]; }
References intrinsics_.
Referenced by toString().
cv()
double dyno::CameraParams::cv () const inline
Definition at line 104 of file CameraParams.hpp.
{ return intrinsics_[3]; }
References intrinsics_.
Referenced by toString().
distortionModelToString()
bool dyno::CameraParams::distortionModelToString (const DistortionModel & model, std::string & distortion_model, std::string & camera_model) static
Converts the DistortionModel enum to a distortion model string and associated camera model.
The returned distortion model (e.g. "plumb_bob", "radtan") will match distortion model's used in the ROS ecosystem which are defined in sensor_msgs/distortion_models.hpp.
Only pinhole camera models are currently supported.
Out-args are only set when the function returns true.
Parameters
model const DistortionModel&
distortion_model std::string&
camera_model std::string&
Returns
true
false
Definition at line 211 of file CameraParams.cc.
{
  switch (model) {
    case DistortionModel::NONE:
      return false;
    case DistortionModel::RADTAN:
      // in ROS only plumb_bob is defined so we use this
      distortion_model = "plumb_bob";
      camera_model = "pinhole";
      return true;
    case DistortionModel::EQUIDISTANT:
      distortion_model = "equidistant";
      camera_model = "pinhole";
      return true;
    case DistortionModel::FISH_EYE:
      distortion_model = "kannala_brandt";
      camera_model = "pinhole";
      return true;
    default:
      LOG(WARNING) << "Cannot convert distortion model to string: "
                   << to_string(model);
      return false;
  }
}
References dyno::EQUIDISTANT, dyno::FISH_EYE, dyno::NONE, dyno::RADTAN, and dyno::to_string().
Referenced by rclcpp::TypeAdapter< dyno::CameraParams, sensor_msgs::msg::CameraInfo >::convert_to_ros_message().
equals()
bool dyno::CameraParams::equals (const CameraParams & other, double tol = 1e-9) const
Definition at line 237 of file CameraParams.cc.
{
  return dyno::equals_with_abs_tol(intrinsics_, other.intrinsics_, tol) &&
         dyno::equals_with_abs_tol(distortion_coeff_, other.distortion_coeff_,
                                   tol) &&
         (image_size_.width == other.image_size_.width &&
          image_size_.height == other.image_size_.height) &&
         distortion_model_ == other.distortion_model_ &&
         T_robot_camera_.equals(other.T_robot_camera_, tol) &&
         utils::compareCvMatsUpToTol(K_, other.K_, tol) &&
         utils::compareCvMatsUpToTol(
             D_, other.D_);  // NOTE: do not comapre with P matrix as currently
                             // not calculated
}
References dyno::utils::compareCvMatsUpToTol(), D_, distortion_coeff_, distortion_model_, dyno::equals_with_abs_tol(), image_size_, intrinsics_, K_, and T_robot_camera_.
fx()
double dyno::CameraParams::fx () const inline
Definition at line 101 of file CameraParams.hpp.
{ return intrinsics_[0]; }
References intrinsics_.
Referenced by dyno::EgoMotionSolver::geometricOutlierRejection3d2d(), dyno::OMDOldAllLoader::getDepthImage(), and toString().
fy()
double dyno::CameraParams::fy () const inline
Definition at line 102 of file CameraParams.hpp.
{ return intrinsics_[1]; }
References intrinsics_.
Referenced by dyno::EgoMotionSolver::geometricOutlierRejection3d2d(), and toString().
getCameraMatrix()
cv::Mat dyno::CameraParams::getCameraMatrix () const inline
Definition at line 110 of file CameraParams.hpp.
{ return K_; }
References K_.
Referenced by dyno::StereoCamera::computeRectificationParameters(), rclcpp::TypeAdapter< dyno::CameraParams, sensor_msgs::msg::CameraInfo >::convert_to_ros_message(), dyno::Frame::Frame(), dyno::UndistorterRectifier::initUndistortRectifyMaps(), dyno::UndistorterRectifier::UndistortKeypointAndGetProjectedVersor(), dyno::UndistorterRectifier::UndistortRectifyKeypoints(), and dyno::vision_tools::writeOutProjectMaskAndDepthMap().
getCameraMatrixEigen()
gtsam::Matrix3 dyno::CameraParams::getCameraMatrixEigen () const inline
Definition at line 112 of file CameraParams.hpp.
{ return K_eigen_; }
References K_eigen_.
Referenced by dyno::EgoMotionSolver::geometricOutlierRejection2d2d(), and dyno::EgoMotionSolver::geometricOutlierRejection3d2d().
getDistortionCoeffs()
cv::Mat dyno::CameraParams::getDistortionCoeffs () const inline
Definition at line 114 of file CameraParams.hpp.
{ return D_; }
References D_.
Referenced by dyno::StereoCamera::computeRectificationParameters(), rclcpp::TypeAdapter< dyno::CameraParams, sensor_msgs::msg::CameraInfo >::convert_to_ros_message(), dyno::UndistorterRectifier::initUndistortRectifyMaps(), and dyno::UndistorterRectifier::UndistortRectifyKeypoints().
getDistortionModel()
DistortionModel dyno::CameraParams::getDistortionModel () const inline
Definition at line 124 of file CameraParams.hpp.
{
    return distortion_model_;
  }
References distortion_model_.
Referenced by dyno::StereoCamera::computeRectificationParameters(), rclcpp::TypeAdapter< dyno::CameraParams, sensor_msgs::msg::CameraInfo >::convert_to_ros_message(), dyno::UndistorterRectifier::initUndistortRectifyMaps(), and dyno::UndistorterRectifier::UndistortRectifyKeypoints().
getExtrinsics()
gtsam::Pose3 dyno::CameraParams::getExtrinsics () const inline
Get the camera extrinsics - the transform of the camera in the body frame (e.g T_robot_camera or ^RT_C)
Returns
gtsam::Pose3
Definition at line 122 of file CameraParams.hpp.
{ return T_robot_camera_; }
References T_robot_camera_.
Referenced by dyno::StereoCamera::computeRectificationParameters().
ImageHeight()
int dyno::CameraParams::ImageHeight () const inline
Definition at line 106 of file CameraParams.hpp.
{ return image_size_.height; }
References image_size_.
Referenced by rclcpp::TypeAdapter< dyno::CameraParams, sensor_msgs::msg::CameraInfo >::convert_to_ros_message(), dyno::Camera::isKeypointContained(), and toString().
imageSize()
const cv::Size & dyno::CameraParams::imageSize () const inline
Definition at line 108 of file CameraParams.hpp.
{ return image_size_; }
References image_size_.
Referenced by dyno::StereoCamera::computeRectificationParameters(), and dyno::UndistorterRectifier::initUndistortRectifyMaps().
ImageWidth()
int dyno::CameraParams::ImageWidth () const inline
Definition at line 105 of file CameraParams.hpp.
{ return image_size_.width; }
References image_size_.
Referenced by rclcpp::TypeAdapter< dyno::CameraParams, sensor_msgs::msg::CameraInfo >::convert_to_ros_message(), dyno::Camera::isKeypointContained(), and toString().
stringToDistortion()
DistortionModel dyno::CameraParams::stringToDistortion (const std::string & distortion_model, const std::string & camera_model) static
stringToDistortion
Taken from: https://github.com/ethz-asl/image_undistort
Parameters
distortion_model
camera_model
Returns
actual distortion model enum class
Definition at line 176 of file CameraParams.cc.
{
  std::string lower_case_distortion_model = distortion_model;
  std::string lower_case_camera_model = camera_model;
  std::transform(lower_case_distortion_model.begin(),
                 lower_case_distortion_model.end(),
                 lower_case_distortion_model.begin(), ::tolower);
  std::transform(lower_case_camera_model.begin(), lower_case_camera_model.end(),
                 lower_case_camera_model.begin(), ::tolower);
  if (lower_case_camera_model == "pinhole") {
    if (lower_case_distortion_model == "none") {
      return DistortionModel::NONE;
    } else if ((lower_case_distortion_model == "plumb_bob") ||
               (lower_case_distortion_model == "radial_tangential") ||
               (lower_case_distortion_model == "radtan")) {
      return DistortionModel::RADTAN;
    } else if (lower_case_distortion_model == "equidistant") {
      return DistortionModel::EQUIDISTANT;
    } else if (lower_case_distortion_model == "kannala_brandt") {
      return DistortionModel::FISH_EYE;
    } else {
      LOG(ERROR) << "Unrecognized distortion model for pinhole camera. Valid "
                    "pinhole distortion model options are 'none', 'radtan', "
                    "'equidistant', 'fish eye'.";
    }
  } else {
    LOG(ERROR)
        << "Unrecognized camera model. Valid camera models are 'pinhole'";
  }
  // Return no distortion model if invalid model is provided
  return DistortionModel::NONE;
}
References dyno::EQUIDISTANT, dyno::FISH_EYE, dyno::NONE, and dyno::RADTAN.
Referenced by dyno::declare_config(), dyno::ProjectAriaAllLoader::loadCalibration(), and dyno::OMDOldAllLoader::setCameraParams().
toString()
const std::string dyno::CameraParams::toString () const
Definition at line 251 of file CameraParams.cc.
{
  std::stringstream out;
  out << "\nIntrinsics: \n- fx " << fx() << "\n- fy " << fy() << "\n- cu "
      << cu() << "\n- cv " << cv()
      << "\nimage_size: \n- width: " << ImageWidth()
      << "\n- height: " << ImageHeight() << "\n- K: " << K_ << '\n'
      << "- Distortion Model: " << to_string(distortion_model_) << '\n'
      << "- D: " << D_ << '\n'
      << "- P: " << P_ << '\n';
  return out.str();
}
References cu(), cv(), D_, distortion_model_, fx(), fy(), ImageHeight(), ImageWidth(), K_, P_, and dyno::to_string().
Referenced by dyno::OMDOldAllLoader::setCameraParams(), and dyno::DataProviderRos::waitAndSetCameraParams().
Member Data Documentation
D_
cv::Mat dyno::CameraParams::D_ private
Definition at line 219 of file CameraParams.hpp.
Referenced by CameraParams(), equals(), getDistortionCoeffs(), and toString().
distortion_coeff_
DistortionCoeffs dyno::CameraParams::distortion_coeff_ private
Definition at line 200 of file CameraParams.hpp.
Referenced by CameraParams(), and equals().
distortion_model_
DistortionModel dyno::CameraParams::distortion_model_ private
Distortion parameters.
Definition at line 204 of file CameraParams.hpp.
Referenced by equals(), getDistortionModel(), and toString().
image_size_
cv::Size dyno::CameraParams::image_size_ private
Definition at line 201 of file CameraParams.hpp.
Referenced by equals(), ImageHeight(), imageSize(), and ImageWidth().
intrinsics_
IntrinsicsCoeffs dyno::CameraParams::intrinsics_ private
fu, fv, cu, cv
Definition at line 199 of file CameraParams.hpp.
Referenced by CameraParams(), cu(), cv(), equals(), fx(), and fy().
K_
cv::Mat dyno::CameraParams::K_ private
Transform of the camera frame to the robot frame.
OpenCV structures: needed to compute the undistortion map. 3x3 camera matrix K (last row is {0,0,1}) stored as a CV_64F (double)
Definition at line 211 of file CameraParams.hpp.
Referenced by CameraParams(), equals(), getCameraMatrix(), and toString().
K_eigen_
gtsam::Matrix3 dyno::CameraParams::K_eigen_ private
Definition at line 212 of file CameraParams.hpp.
Referenced by CameraParams(), and getCameraMatrixEigen().
P_
cv::Mat dyno::CameraParams::P_ private
New camera matrix constructed from estimateNewCameraMatrixForUndistortRectify for mono case not touched and initalised as K_
Definition at line 217 of file CameraParams.hpp.
Referenced by CameraParams(), and toString().
T_robot_camera_
gtsam::Pose3 dyno::CameraParams::T_robot_camera_ private
Definition at line 206 of file CameraParams.hpp.
Referenced by equals(), and getExtrinsics().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/common/CameraParams.hpp
dynosam/src/common/CameraParams.cc