DynoSAM: dyno::DynamicPointSymbol Class Reference
dyno::DynamicPointSymbol Class Reference
#include <DynamicPointSymbol.hpp>
Public Member Functions
DynamicPointSymbol ()
DynamicPointSymbol (const DynamicPointSymbol &key)
DynamicPointSymbol (unsigned char c, TrackletId tracklet_id, FrameId frame_id)
DynamicPointSymbol (gtsam::Key key)
gtsam::Key key () const
operator gtsam::Key () const
void print (const std::string &s="") const
Print.
bool equals (const DynamicPointSymbol &expected, double tol=0.0) const
Check equality.
unsigned char chr () const
std::uint64_t index () const
TrackletId trackletId () const
FrameId frameId () const
operator std::string () const
std::string string () const
Return string representation of the key.
bool operator< (const DynamicPointSymbol &comp) const
bool operator== (const DynamicPointSymbol &comp) const
bool operator== (gtsam::Key comp) const
bool operator!= (const DynamicPointSymbol &comp) const
bool operator!= (gtsam::Key comp) const
Protected Attributes
unsigned char c_
std::uint64_t j_
TrackletId tracklet_id_
FrameId frame_id_
Private Member Functions
gtsam::Symbol asSymbol () const
Static Private Member Functions
static std::uint64_t constructIndex (TrackletId tracklet_id, FrameId frame_id)
static void recover (std::uint64_t z, TrackletId &tracklet_id, FrameId &frame_id)
Detailed Description
Definition at line 48 of file DynamicPointSymbol.hpp.
Constructor & Destructor Documentation
DynamicPointSymbol() [1/4]
dyno::DynamicPointSymbol::DynamicPointSymbol () inline
Default constructor
Definition at line 59 of file DynamicPointSymbol.hpp.
                         :
        c_(0), j_(0), tracklet_id_(-1), frame_id_(0) {
    }
DynamicPointSymbol() [2/4]
dyno::DynamicPointSymbol::DynamicPointSymbol (const DynamicPointSymbol & key)
Copy constructor
Definition at line 47 of file DynamicPointSymbol.cc.
:   c_(key.c_), j_(key.j_), tracklet_id_(key.tracklet_id_), frame_id_(key.frame_id_) {}
DynamicPointSymbol() [3/4]
dyno::DynamicPointSymbol::DynamicPointSymbol (unsigned char c, TrackletId tracklet_id, FrameId frame_id)
Constructor
Definition at line 50 of file DynamicPointSymbol.cc.
:   c_(c), j_(constructIndex(tracklet_id, frame_id)), tracklet_id_(tracklet_id), frame_id_(frame_id)
{
    //sanity check
    const auto result = CantorPairingFunction::depair(j_);
    CHECK_EQ(result.first, tracklet_id_);
    CHECK_EQ(result.second, frame_id_);
}
References dyno::CantorPairingFunction::depair(), frame_id_, j_, and tracklet_id_.
DynamicPointSymbol() [4/4]
dyno::DynamicPointSymbol::DynamicPointSymbol (gtsam::Key key)
Constructor that decodes an integer Key
Definition at line 59 of file DynamicPointSymbol.cc.
{
    gtsam::Symbol sym(key);
    const unsigned char c = sym.chr();
    const std::uint64_t index = sym.index();
    c_ = c;
    j_ = index;
    recover(j_, tracklet_id_, frame_id_);
}
References c_, frame_id_, index(), j_, key(), recover(), and tracklet_id_.
Member Function Documentation
asSymbol()
gtsam::Symbol dyno::DynamicPointSymbol::asSymbol () const private
Definition at line 91 of file DynamicPointSymbol.cc.
{
    return gtsam::Symbol(c_, j_);
}
References c_, and j_.
Referenced by key().
chr()
unsigned char dyno::DynamicPointSymbol::chr () const inline
Retrieve key character
Definition at line 84 of file DynamicPointSymbol.hpp.
{
        return c_;
    }
References c_.
constructIndex()
std::uint64_t dyno::DynamicPointSymbol::constructIndex (TrackletId tracklet_id, FrameId frame_id) static private
Definition at line 95 of file DynamicPointSymbol.cc.
{
    if(tracklet_id == -1) {
        throw std::invalid_argument("DynamicPointSymbol cannot be constructed from invalid tracklet id (-1)");
    }
    return CantorPairingFunction::pair({tracklet_id, frame_id});
}
References dyno::CantorPairingFunction::pair().
equals()
bool dyno::DynamicPointSymbol::equals (const DynamicPointSymbol & expected, double tol = 0.0) const
Check equality.
Definition at line 79 of file DynamicPointSymbol.cc.
{
    return (*this) == expected; //lazy?
}
frameId()
FrameId dyno::DynamicPointSymbol::frameId () const inline
Definition at line 97 of file DynamicPointSymbol.hpp.
{
        return frame_id_;
    }
References frame_id_.
Referenced by dyno::DynoLikeKeyFormatterVerbose().
index()
std::uint64_t dyno::DynamicPointSymbol::index () const inline
Retrieve key index
Definition at line 89 of file DynamicPointSymbol.hpp.
{
        return j_;
    }
References j_.
Referenced by DynamicPointSymbol().
key()
gtsam::Key dyno::DynamicPointSymbol::key () const
return Key (integer) representation
Definition at line 70 of file DynamicPointSymbol.cc.
{
    return (gtsam::Key)asSymbol();
}
References asSymbol().
Referenced by DynamicPointSymbol(), and operator gtsam::Key().
operator gtsam::Key()
dyno::DynamicPointSymbol::operator gtsam::Key () const inline
Cast to integer
Definition at line 75 of file DynamicPointSymbol.hpp.
{ return key(); }
References key().
operator std::string()
dyno::DynamicPointSymbol::operator std::string () const
Create a string from the key
Definition at line 84 of file DynamicPointSymbol.cc.
{
    char buffer[20];
    snprintf(buffer, 20, "%c%ld-%lu", c_, tracklet_id_, static_cast<unsigned long>(frame_id_));
    return std::string(buffer);
}
operator!=() [1/2]
bool dyno::DynamicPointSymbol::operator!= (const DynamicPointSymbol & comp) const inline
Comparison for use in maps
Definition at line 125 of file DynamicPointSymbol.hpp.
{
        return comp.c_ != c_ || comp.j_ != j_;
    }
References c_, and j_.
operator!=() [2/2]
bool dyno::DynamicPointSymbol::operator!= (gtsam::Key comp) const inline
Comparison for use in maps
Definition at line 130 of file DynamicPointSymbol.hpp.
{
        return comp != (gtsam::Key)(*this);
    }
operator<()
bool dyno::DynamicPointSymbol::operator< (const DynamicPointSymbol & comp) const inline
Comparison for use in maps
Definition at line 110 of file DynamicPointSymbol.hpp.
{
        return c_ < comp.c_ || (comp.c_ == c_ && j_ < comp.j_);
    }
References c_, and j_.
operator==() [1/2]
bool dyno::DynamicPointSymbol::operator== (const DynamicPointSymbol & comp) const inline
Comparison for use in maps
Definition at line 115 of file DynamicPointSymbol.hpp.
{
        return comp.c_ == c_ && comp.j_ == j_;
    }
References c_, and j_.
operator==() [2/2]
bool dyno::DynamicPointSymbol::operator== (gtsam::Key comp) const inline
Comparison for use in maps
Definition at line 120 of file DynamicPointSymbol.hpp.
{
        return comp == (gtsam::Key)(*this);
    }
print()
void dyno::DynamicPointSymbol::print (const std::string & s = "") const
Print.
Definition at line 75 of file DynamicPointSymbol.cc.
{
    std::cout << s << ": " << (std::string) (*this) << std::endl;
}
recover()
void dyno::DynamicPointSymbol::recover (std::uint64_t z, TrackletId & tracklet_id, FrameId & frame_id) static private
Definition at line 103 of file DynamicPointSymbol.cc.
{
    const auto result = CantorPairingFunction::depair(z);
    tracklet_id = static_cast<TrackletId>(result.first);
    frame_id = static_cast<FrameId>(result.second);
}
References dyno::CantorPairingFunction::depair().
Referenced by DynamicPointSymbol().
string()
std::string dyno::DynamicPointSymbol::string () const inline
Return string representation of the key.
Definition at line 107 of file DynamicPointSymbol.hpp.
{ return std::string(*this); }
trackletId()
TrackletId dyno::DynamicPointSymbol::trackletId () const inline
Definition at line 93 of file DynamicPointSymbol.hpp.
{
        return tracklet_id_;
    }
References tracklet_id_.
Referenced by dyno::DynoLikeKeyFormatterVerbose(), and dyno::MotionOnlyRefinementOptimizer::optimize().
Member Data Documentation
c_
unsigned char dyno::DynamicPointSymbol::c_ protected
Definition at line 50 of file DynamicPointSymbol.hpp.
Referenced by asSymbol(), chr(), DynamicPointSymbol(), operator!=(), operator<(), and operator==().
frame_id_
FrameId dyno::DynamicPointSymbol::frame_id_ protected
Definition at line 54 of file DynamicPointSymbol.hpp.
Referenced by DynamicPointSymbol(), and frameId().
j_
std::uint64_t dyno::DynamicPointSymbol::j_ protected
Definition at line 51 of file DynamicPointSymbol.hpp.
Referenced by asSymbol(), DynamicPointSymbol(), index(), operator!=(), operator<(), and operator==().
tracklet_id_
TrackletId dyno::DynamicPointSymbol::tracklet_id_ protected
Definition at line 53 of file DynamicPointSymbol.hpp.
Referenced by DynamicPointSymbol(), and trackletId().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/backend/DynamicPointSymbol.hpp
dynosam/src/backend/DynamicPointSymbol.cc