DynoSAM: dyno::CsvReader::Row Class Reference
dyno::CsvReader::Row Class Reference
Class containg a single row of a csv file after parsing.
#include <CsvParser.hpp>
Public Member Functions
Row ()
Row (const CsvHeader &header)
Row (const std::string &line, const CsvHeader &header, const char delimiter)
template<typename T = std::string>
T at (std::size_t index) const
Row & operator<< (std::istream &str)
std::string operator[] (std::size_t index) const
std::size_t size () const
bool usableHeader () const
const CsvHeader & header () const
char delimieter () const
Static Public Member Functions
static Row FromStream (std::istream &istream, const CsvHeader &header, const char delimiter=DefaultDelimiter)
Private Attributes
std::string line_
CsvHeader header_
char delimiter_
std::vector< int > pos_data_
Detailed Description
Class containg a single row of a csv file after parsing.
Each column can be queried via the column index TODO: no checks that rows match the header length, all rows have the same length...
Definition at line 118 of file CsvParser.hpp.
Constructor & Destructor Documentation
Row() [1/3]
dyno::CsvReader::Row::Row () inline
Definition at line 120 of file CsvParser.hpp.
: delimiter_(CsvReader::DefaultDelimiter) {}
Row() [2/3]
dyno::CsvReader::Row::Row (const CsvHeader & header) inline
Definition at line 121 of file CsvParser.hpp.
        : header_(header), delimiter_(CsvReader::DefaultDelimiter) {}
Row() [3/3]
dyno::CsvReader::Row::Row (const std::string & line, const CsvHeader & header, const char delimiter)
Definition at line 41 of file CsvParser.cc.
    : line_(line), header_(header), delimiter_(delimiter) {
  pos_data_.emplace_back(-1);
  std::string::size_type pos = 0;
  while ((pos = line_.find(delimiter_, pos)) != std::string::npos) {
    pos_data_.emplace_back(pos);
    ++pos;
  }
  // This checks for a trailing comma with no data after it.
  pos = line_.size();
  pos_data_.emplace_back(pos);
  // if usable header provided (one of non zero size, ie. non default header)
  // check that the number of elements in the parsed input string matches the
  // expected number of cols in the header
  if (usableHeader() && this->size() != header_.size()) {
    std::stringstream ss;
    ss << "Invalid row construction using a valid CsvHeader: input row has "
          "length "
       << this->size() << " and header has size " << header_.size()
       << " with column values - " << header_.toString();
    throw std::runtime_error(ss.str());
  }
}
References delimiter_, header_, line_, pos_data_, size(), dyno::CsvHeader::toString(), and usableHeader().
Member Function Documentation
at()
template<typename T = std::string> T dyno::CsvReader::Row::at (std::size_t index) const inline
Definition at line 130 of file CsvParser.hpp.
{
      if (index >= this->size()) {
        throw std::out_of_range(std::to_string(index) + " >= size (" +
                                std::to_string(this->size()) + ")");
      }
      std::string value = this->operator[](index);
      std::stringstream ss;
      ss << value;
      T out_value;
      ss >> out_value;
      return out_value;
    }
delimieter()
char dyno::CsvReader::Row::delimieter () const inline
Definition at line 164 of file CsvParser.hpp.
{ return delimiter_; }
FromStream()
CsvReader::Row dyno::CsvReader::Row::FromStream (std::istream & istream, const CsvHeader & header, const char delimiter = DefaultDelimiter) static
Definition at line 77 of file CsvParser.cc.
{
  std::string line;
  std::getline(istream, line);
  return Row(line, header, delimiter);
}
Referenced by operator<<().
header()
const CsvHeader & dyno::CsvReader::Row::header () const inline
Definition at line 163 of file CsvParser.hpp.
{ return header_; }
operator<<()
Row & dyno::CsvReader::Row::operator<< (std::istream & str) inline
Definition at line 145 of file CsvParser.hpp.
{
      auto row = CsvReader::Row::FromStream(str, header(), delimieter());
      std::swap(*this, row);
      return *this;
    }
References FromStream().
operator[]()
std::string dyno::CsvReader::Row::operator[] (std::size_t index) const
Definition at line 67 of file CsvParser.cc.
{
  size_t size = pos_data_[index + 1] - (pos_data_[index] + 1);
  std::string_view view = std::string_view(&line_[pos_data_[index] + 1], size);
  std::string val = {view.begin(), view.end()};
  // removes all the leading and trailing white spaces.
  boost::algorithm::trim(val);
  return val;
}
size()
std::size_t dyno::CsvReader::Row::size () const inline
Definition at line 153 of file CsvParser.hpp.
{
      if (pos_data_.empty()) return 0;
      return pos_data_.size() - 1;
    }
Referenced by Row().
usableHeader()
bool dyno::CsvReader::Row::usableHeader () const inline
Definition at line 158 of file CsvParser.hpp.
{ return !header_.empty(); }
Referenced by Row().
Member Data Documentation
delimiter_
char dyno::CsvReader::Row::delimiter_ private
Definition at line 169 of file CsvParser.hpp.
Referenced by Row().
header_
CsvHeader dyno::CsvReader::Row::header_ private
Definition at line 168 of file CsvParser.hpp.
Referenced by Row().
line_
std::string dyno::CsvReader::Row::line_ private
Definition at line 167 of file CsvParser.hpp.
Referenced by Row().
pos_data_
std::vector<int> dyno::CsvReader::Row::pos_data_ private
Definition at line 170 of file CsvParser.hpp.
Referenced by Row().
The documentation for this class was generated from the following files:
dynosam_common/include/dynosam_common/utils/CsvParser.hpp
dynosam_common/src/utils/CsvParser.cc