DynoSAM: dyno::ProjectAriaAllLoader Class Reference
dyno::ProjectAriaAllLoader Class Reference
Public Member Functions
ProjectAriaAllLoader (const std::string &file_path)
size_t size () const
cv::Mat getOpticalFlow (size_t idx) const
cv::Mat getRGB (size_t idx) const
cv::Mat getRightRGB (size_t idx) const
cv::Mat getInstanceMask (size_t idx) const
cv::Mat getDepthImage (size_t idx) const
const CameraParams & getLeftCameraParams () const
double getTimestamp (size_t idx)
Private Member Functions
void loadFlowImagesAndSize (std::vector< std::string > &images_paths, size_t &dataset_size)
void loadOtherImages ()
void loadCalibration ()
Private Attributes
std::string rgb_images_folder_path_
std::string right_rgb_images_folder_path_
std::string depth_images_folder_path_
std::string optical_flow_folder_path_
std::string instance_masks_folder_
std::string intrinsics_file_path_
std::string rgb_timestamps_file_path_
std::vector< std::string > rgb_image_paths_
std::vector< std::string > right_rgb_image_paths_
std::vector< std::string > depth_image_paths_
std::vector< std::string > optical_flow_image_paths_
std::vector< std::string > instance_masks_image_paths_
std::vector< Timestamp > times_
size_t dataset_size_ = 0
CameraParams rgb_camera_params_
Detailed Description
Definition at line 43 of file ProjectAriaDataProvider.cc.
Constructor & Destructor Documentation
ProjectAriaAllLoader()
dyno::ProjectAriaAllLoader::ProjectAriaAllLoader (const std::string & file_path) inline
Definition at line 47 of file ProjectAriaDataProvider.cc.
      : rgb_images_folder_path_(file_path + "/rgb_sync"),
        right_rgb_images_folder_path_(file_path + "/right"),
        depth_images_folder_path_(file_path + "/depth_sync"),
        optical_flow_folder_path_(file_path + "/optical_flow"),
        instance_masks_folder_(file_path + "/instance_masks"),
        intrinsics_file_path_(file_path + "/calibration_undistort.json"),
        rgb_timestamps_file_path_(file_path + "/sync_timestamp.csv") {
    // Initialize folders and file paths
    utils::throwExceptionIfPathInvalid(rgb_images_folder_path_);
    utils::throwExceptionIfPathInvalid(depth_images_folder_path_);
    utils::throwExceptionIfPathInvalid(optical_flow_folder_path_);
    utils::throwExceptionIfPathInvalid(instance_masks_folder_);
    // utils::throwExceptionIfPathInvalid(intrinsics_file_path_);
    // utils::throwExceptionIfPathInvalid(rgb_timestamps_file_path_);
    // first load images and size
    // the size will be used as a refernce for all other loaders
    // size is number of images
    // we use flow to set the size as for this dataset, there will be one less
    // optical flow as the flow ids index t to t+1 (which is gross, I know!!)
    // TODO: code and comments replicated in ClusterSlamDataProvider
    loadFlowImagesAndSize(optical_flow_image_paths_, dataset_size_);
    // load rgb, depth and instance masks - they should all have the same
    // length!!
    loadOtherImages();
    // loadTimestamps();
    loadCalibration();
  }
References dataset_size_, depth_images_folder_path_, instance_masks_folder_, loadCalibration(), loadFlowImagesAndSize(), loadOtherImages(), optical_flow_folder_path_, optical_flow_image_paths_, rgb_images_folder_path_, and dyno::utils::throwExceptionIfPathInvalid().
Member Function Documentation
getDepthImage()
cv::Mat dyno::ProjectAriaAllLoader::getDepthImage (size_t idx) const inline
Definition at line 139 of file ProjectAriaDataProvider.cc.
{
    CHECK_LT(idx, depth_image_paths_.size());
    cv::Mat depth;
    utils::loadDepth(depth_image_paths_.at(idx), depth);
    CHECK(!depth.empty());
    return depth;
  }
References depth_image_paths_, and dyno::utils::loadDepth().
getInstanceMask()
cv::Mat dyno::ProjectAriaAllLoader::getInstanceMask (size_t idx) const inline
Definition at line 109 of file ProjectAriaDataProvider.cc.
{
    CHECK_LT(idx, rgb_image_paths_.size());
    CHECK_LT(idx, dataset_size_);
    // relabel masks from 1 to N
    static gtsam::FastMap<ObjectId, ObjectId> relabelled;
    static ObjectId current_max_label = 1u;
    cv::Mat mask;
    utils::loadMask(instance_masks_image_paths_.at(idx), mask);
    CHECK(!mask.empty());
    ObjectIds labels = vision_tools::getObjectLabels(mask);
    const ObjectIds& old_labels = labels;
    ObjectIds new_labels;
    for (ObjectId old_label : labels) {
      if (!relabelled.exists(old_label)) {
        relabelled[old_label] = current_max_label;
        current_max_label++;
      }
      ObjectId new_label = relabelled.at(old_label);
      new_labels.push_back(new_label);
    }
    cv::Mat relabelled_mask;
    vision_tools::relabelMasks(mask, relabelled_mask, old_labels, new_labels);
    return relabelled_mask;
  }
References dataset_size_, dyno::vision_tools::getObjectLabels(), instance_masks_image_paths_, dyno::utils::loadMask(), dyno::vision_tools::relabelMasks(), and rgb_image_paths_.
getLeftCameraParams()
const CameraParams & dyno::ProjectAriaAllLoader::getLeftCameraParams () const inline
Definition at line 149 of file ProjectAriaDataProvider.cc.
{ return rgb_camera_params_; }
References rgb_camera_params_.
getOpticalFlow()
cv::Mat dyno::ProjectAriaAllLoader::getOpticalFlow (size_t idx) const inline
Definition at line 80 of file ProjectAriaDataProvider.cc.
{
    CHECK_LT(idx, optical_flow_image_paths_.size());
    cv::Mat flow;
    utils::loadFlow(optical_flow_image_paths_.at(idx), flow);
    CHECK(!flow.empty());
    return flow;
  }
References dyno::utils::loadFlow(), and optical_flow_image_paths_.
getRGB()
cv::Mat dyno::ProjectAriaAllLoader::getRGB (size_t idx) const inline
Definition at line 89 of file ProjectAriaDataProvider.cc.
{
    CHECK_LT(idx, rgb_image_paths_.size());
    cv::Mat rgb;
    utils::loadRGB(rgb_image_paths_.at(idx), rgb);
    CHECK(!rgb.empty());
    return rgb;
  }
References dyno::utils::loadRGB(), and rgb_image_paths_.
getRightRGB()
cv::Mat dyno::ProjectAriaAllLoader::getRightRGB (size_t idx) const inline
Definition at line 99 of file ProjectAriaDataProvider.cc.
{
    CHECK_LT(idx, right_rgb_image_paths_.size());
    cv::Mat rgb;
    utils::loadRGB(right_rgb_image_paths_.at(idx), rgb);
    CHECK(!rgb.empty());
    return rgb;
  }
References dyno::utils::loadRGB(), and right_rgb_image_paths_.
getTimestamp()
double dyno::ProjectAriaAllLoader::getTimestamp (size_t idx) inline
Definition at line 151 of file ProjectAriaDataProvider.cc.
{
    CHECK_LT(idx, times_.size());
    return times_.at(idx);
  }
References times_.
loadCalibration()
void dyno::ProjectAriaAllLoader::loadCalibration () inline private
Definition at line 239 of file ProjectAriaDataProvider.cc.
{
    // using json = nlohmann::json;
    // std::ifstream file(intrinsics_file_path_);
    // json calibration_json;
    // file >> calibration_json;
    // int rgb_width = calibration_json["rgb_width"].template get<int>();
    // int rgb_height = calibration_json["rgb_height"].template get<int>();
    // std::vector<double> K = calibration_json["rgb_intrinsics"].template
    // get<std::vector<double>>(); CameraParams::IntrinsicsCoeffs intrinsics({
    //     K.at(0), //fu
    //     K.at(4), //fv
    //     K.at(2), //cu
    //     K.at(5)  // cv
    //     });
    // CameraParams::IntrinsicsCoeffs intrinsics({
    //     535.288025, //fu
    //     535.288025, //fv
    //     623.312256, //cu
    //     348.522400  // cv
    //     });
    // acfr_1_moving_small
    CameraParams::IntrinsicsCoeffs intrinsics({
        267.644012,  // fu
        311.656128,  // fv
        267.644012,  // cu
        174.261200   // cv
    });
    // TODO: Assume Image is undistorted!!!!!!
    CameraParams::DistortionCoeffs distortion({0, 0, 0, 0});
    // distortion_model not given
    const auto distortion_model = "plumb_bob";
    const auto camera_model = "pinhole";
    auto model =
        CameraParams::stringToDistortion(distortion_model, camera_model);
    rgb_camera_params_ = CameraParams(intrinsics, distortion,
                                      // cv::Size(1280, 720),
                                      cv::Size(640, 360), model);
  }
References rgb_camera_params_, and dyno::CameraParams::stringToDistortion().
Referenced by ProjectAriaAllLoader().
loadFlowImagesAndSize()
void dyno::ProjectAriaAllLoader::loadFlowImagesAndSize (std::vector< std::string > & images_paths, size_t & dataset_size) inline private
Definition at line 157 of file ProjectAriaDataProvider.cc.
{
    std::vector<std::filesystem::path> files_in_directory =
        utils::getAllFilesInDir(optical_flow_folder_path_);
    dataset_size = files_in_directory.size();
    CHECK_GT(dataset_size, 0);
    for (const std::filesystem::path& path : files_in_directory) {
      const std::string file_path = path;
      utils::throwExceptionIfPathInvalid(file_path);
      images_paths.push_back(file_path);
      std::string timestamp_str = path.stem();
      double timestamp_nano = std::stod(timestamp_str);
      double timestamp_seconds = timestamp_nano / 1.0e+9;
      times_.push_back(timestamp_seconds);
    }
  }
References dyno::utils::getAllFilesInDir(), optical_flow_folder_path_, dyno::utils::throwExceptionIfPathInvalid(), and times_.
Referenced by ProjectAriaAllLoader().
loadOtherImages()
void dyno::ProjectAriaAllLoader::loadOtherImages () inline private
Definition at line 176 of file ProjectAriaDataProvider.cc.
{
    auto rgb_image_files = utils::getAllFilesInDir(rgb_images_folder_path_);
    auto right_rgb_images_files =
        utils::getAllFilesInDir(right_rgb_images_folder_path_);
    auto depth_image_files = utils::getAllFilesInDir(depth_images_folder_path_);
    auto instance_masks_image_files =
        utils::getAllFilesInDir(instance_masks_folder_);
    for (auto f : rgb_image_files) {
      rgb_image_paths_.push_back(f);
    }
    // left images are sync and right images are raw so we need one less
    for (auto f : right_rgb_images_files) {
      right_rgb_image_paths_.push_back(f);
    }
    right_rgb_image_paths_.pop_back();
    for (auto f : depth_image_files) {
      depth_image_paths_.push_back(f);
    }
    for (auto f : instance_masks_image_files) {
      instance_masks_image_paths_.push_back(f);
    }
    CHECK_EQ(rgb_image_paths_.size(), depth_image_paths_.size());
    CHECK_EQ(right_rgb_image_paths_.size(), depth_image_paths_.size());
    CHECK_EQ(depth_image_paths_.size(), instance_masks_image_paths_.size());
    // dataset size is number optical flow which should be one less!!
    // or equal too!!
    //  CHECK_EQ(instance_masks_image_paths_.size() -1u, dataset_size_);
  }
References depth_image_paths_, depth_images_folder_path_, dyno::utils::getAllFilesInDir(), instance_masks_folder_, instance_masks_image_paths_, rgb_image_paths_, rgb_images_folder_path_, right_rgb_image_paths_, and right_rgb_images_folder_path_.
Referenced by ProjectAriaAllLoader().
size()
size_t dyno::ProjectAriaAllLoader::size () const inline
Definition at line 78 of file ProjectAriaDataProvider.cc.
{ return dataset_size_; }
References dataset_size_.
Member Data Documentation
dataset_size_
size_t dyno::ProjectAriaAllLoader::dataset_size_ = 0 private
Definition at line 303 of file ProjectAriaDataProvider.cc.
Referenced by getInstanceMask(), ProjectAriaAllLoader(), and size().
depth_image_paths_
std::vector<std::string> dyno::ProjectAriaAllLoader::depth_image_paths_ private
Definition at line 297 of file ProjectAriaDataProvider.cc.
Referenced by getDepthImage(), and loadOtherImages().
depth_images_folder_path_
std::string dyno::ProjectAriaAllLoader::depth_images_folder_path_ private
Definition at line 289 of file ProjectAriaDataProvider.cc.
Referenced by loadOtherImages(), and ProjectAriaAllLoader().
instance_masks_folder_
std::string dyno::ProjectAriaAllLoader::instance_masks_folder_ private
Definition at line 291 of file ProjectAriaDataProvider.cc.
Referenced by loadOtherImages(), and ProjectAriaAllLoader().
instance_masks_image_paths_
std::vector<std::string> dyno::ProjectAriaAllLoader::instance_masks_image_paths_ private
Definition at line 299 of file ProjectAriaDataProvider.cc.
Referenced by getInstanceMask(), and loadOtherImages().
intrinsics_file_path_
std::string dyno::ProjectAriaAllLoader::intrinsics_file_path_ private
Definition at line 292 of file ProjectAriaDataProvider.cc.
optical_flow_folder_path_
std::string dyno::ProjectAriaAllLoader::optical_flow_folder_path_ private
Definition at line 290 of file ProjectAriaDataProvider.cc.
Referenced by loadFlowImagesAndSize(), and ProjectAriaAllLoader().
optical_flow_image_paths_
std::vector<std::string> dyno::ProjectAriaAllLoader::optical_flow_image_paths_ private
Definition at line 298 of file ProjectAriaDataProvider.cc.
Referenced by getOpticalFlow(), and ProjectAriaAllLoader().
rgb_camera_params_
CameraParams dyno::ProjectAriaAllLoader::rgb_camera_params_ private
Definition at line 304 of file ProjectAriaDataProvider.cc.
Referenced by getLeftCameraParams(), and loadCalibration().
rgb_image_paths_
std::vector<std::string> dyno::ProjectAriaAllLoader::rgb_image_paths_ private
Definition at line 295 of file ProjectAriaDataProvider.cc.
Referenced by getInstanceMask(), getRGB(), and loadOtherImages().
rgb_images_folder_path_
std::string dyno::ProjectAriaAllLoader::rgb_images_folder_path_ private
Definition at line 287 of file ProjectAriaDataProvider.cc.
Referenced by loadOtherImages(), and ProjectAriaAllLoader().
rgb_timestamps_file_path_
std::string dyno::ProjectAriaAllLoader::rgb_timestamps_file_path_ private
Definition at line 293 of file ProjectAriaDataProvider.cc.
right_rgb_image_paths_
std::vector<std::string> dyno::ProjectAriaAllLoader::right_rgb_image_paths_ private
Definition at line 296 of file ProjectAriaDataProvider.cc.
Referenced by getRightRGB(), and loadOtherImages().
right_rgb_images_folder_path_
std::string dyno::ProjectAriaAllLoader::right_rgb_images_folder_path_ private
Definition at line 288 of file ProjectAriaDataProvider.cc.
Referenced by loadOtherImages().
times_
std::vector<Timestamp> dyno::ProjectAriaAllLoader::times_ private
Definition at line 301 of file ProjectAriaDataProvider.cc.
Referenced by getTimestamp(), and loadFlowImagesAndSize().
The documentation for this class was generated from the following file:
dynosam/src/dataprovider/ProjectAriaDataProvider.cc