DynoSAM: dyno::byte_track::Detection Class Reference
dyno::byte_track::Detection Class Reference
#include <Detection.hpp>
Public Member Functions
Detection (const TlwhRect &rect, float score)
const TlwhRect & rect () const override
float score () const override
void set_rect (const RectBase &rect) override
void set_score (float score) override
Public Member Functions inherited from dyno::byte_track::DetectionBase
virtual ~DetectionBase ()=default
virtual const RectBase & rect () const =0
virtual float score () const =0
virtual void set_rect (const RectBase &rect)=0
virtual void set_score (float score)=0
Private Attributes
TlwhRect rect_
float score_ = 0
Detailed Description
Definition at line 47 of file Detection.hpp.
Constructor & Destructor Documentation
Detection()
dyno::byte_track::Detection::Detection (const TlwhRect & rect, float score)
Definition at line 30 of file Detection.cc.
    : rect_(rect), score_(score) {}
Member Function Documentation
rect()
const TlwhRect & dyno::byte_track::Detection::rect () const override virtual
Implements dyno::byte_track::DetectionBase.
Definition at line 33 of file Detection.cc.
{ return rect_; }
References rect_.
Referenced by set_rect().
score()
float dyno::byte_track::Detection::score () const override virtual
Implements dyno::byte_track::DetectionBase.
Definition at line 34 of file Detection.cc.
{ return score_; }
References score_.
Referenced by set_score().
set_rect()
void dyno::byte_track::Detection::set_rect (const RectBase & rect) override virtual
Implements dyno::byte_track::DetectionBase.
Definition at line 36 of file Detection.cc.
{ rect_ = TlwhRect(rect); }
References rect(), and rect_.
set_score()
void dyno::byte_track::Detection::set_score (float score) override virtual
Implements dyno::byte_track::DetectionBase.
Definition at line 37 of file Detection.cc.
{ score_ = score; }
References score(), and score_.
Member Data Documentation
rect_
TlwhRect dyno::byte_track::Detection::rect_ private
Definition at line 48 of file Detection.hpp.
Referenced by rect(), and set_rect().
score_
float dyno::byte_track::Detection::score_ = 0 private
Definition at line 49 of file Detection.hpp.
Referenced by score(), and set_score().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/common/byte_tracker/Detection.hpp
dynosam/src/common/byte_tracker/Detection.cc