DynoSAM: dyno::FastMapNodeSet< NODE > Class Template Reference
dyno::FastMapNodeSet< NODE > Class Template Reference
Data structuring for fast access of map nodes, sorted by their id. We use a set to prevent objects being added multiple times.
#include <MapNodes.hpp>
Public Types
typedef std::set< NODE, MapNodePtrComparison< NODE >, typename gtsam::internal::FastDefaultAllocator< NODE >::type > Base
Public Member Functions
FastMapNodeSet ()=default
Default constructor.
template<typename INPUTCONTAINER >
FastMapNodeSet (const INPUTCONTAINER &container)
Constructor from a iterable container, passes through to base class.
FastMapNodeSet (const FastMapNodeSet< NODE > &x)
Copy constructor from another FastMapNodeSet, passes through to base class.
FastMapNodeSet (const Base &x)
Copy constructor from the base set class, passes through to base class.
template<typename Index = int>
std::vector< Index > collectIds () const
Returns all id's from the contained nodes.
template<typename Index = int>
Index getFirstIndex () const
Get the first (smallest) index stored.
template<typename Index = int>
Index getLastIndex () const
Get the last (largest) index stored.
template<typename Index = int>
Base::iterator find (Index index)
Find a NODE based on their index. Returns this->end() if not found. Non const version.
template<typename Index = int>
Base::const_iterator find (Index index) const
Find a NODE based on their index. Returns this->end() if not found. Const version.
template<typename Index = int>
bool exists (Index index) const
Check if a node with the given ID exists in the container.
void merge (const FastMapNodeSet< NODE > &other)
Merges this container with another. Will automatically be sorted.
bool continuousAscendingIndex () const
Checks if the ID's of all the nodes are containuously ascending (ie. there is no missing ID)
Static Private Member Functions
template<typename Index >
static Index getIndexSafe (const NODE &node)
Detailed Description
template<typename NODE>
class dyno::FastMapNodeSet< NODE >
Data structuring for fast access of map nodes, sorted by their id. We use a set to prevent objects being added multiple times.
Template Parameters
NODE Must be a pointer to a MapNodeBase (or equivalent concept with a getId()) function.
Definition at line 93 of file MapNodes.hpp.
Member Typedef Documentation
Base
template<typename NODE > typedef std::set<NODE, MapNodePtrComparison<NODE>, typename gtsam::internal::FastDefaultAllocator<NODE>::type> dyno::FastMapNodeSet< NODE >::Base
Definition at line 100 of file MapNodes.hpp.
Constructor & Destructor Documentation
FastMapNodeSet() [1/4]
template<typename NODE > dyno::FastMapNodeSet< NODE >::FastMapNodeSet () default
Default constructor.
FastMapNodeSet() [2/4]
template<typename NODE > template<typename INPUTCONTAINER > dyno::FastMapNodeSet< NODE >::FastMapNodeSet (const INPUTCONTAINER & container) inline explicit
Constructor from a iterable container, passes through to base class.
Template Parameters
INPUTCONTAINER
Parameters
container const INPUTCONTAINER&
Definition at line 113 of file MapNodes.hpp.
      : Base(container.begin(), container.end()) {}
FastMapNodeSet() [3/4]
template<typename NODE > dyno::FastMapNodeSet< NODE >::FastMapNodeSet (const FastMapNodeSet< NODE > & x) inline
Copy constructor from another FastMapNodeSet, passes through to base class.
Parameters
x const FastMapNodeSet<NODE>&
Definition at line 122 of file MapNodes.hpp.
: Base(x) {}
FastMapNodeSet() [4/4]
template<typename NODE > dyno::FastMapNodeSet< NODE >::FastMapNodeSet (const Base & x) inline
Copy constructor from the base set class, passes through to base class.
Parameters
x Base
Definition at line 130 of file MapNodes.hpp.
: Base(x) {}
Member Function Documentation
collectIds()
template<typename NODE > template<typename Index = int> std::vector< Index > dyno::FastMapNodeSet< NODE >::collectIds () const inline
Returns all id's from the contained nodes.
Recalculates each time O(N)
Template Parameters
Index
Returns
std::vector<Index>
Definition at line 141 of file MapNodes.hpp.
{
    std::vector<Index> ids;
    for (const auto& node : *this) {
      // ducktyping for node to have a getId function
      ids.push_back(static_cast<Index>(node->getId()));
    }
    return ids;
  }
Referenced by dyno::FastMapNodeSet< NODE >::continuousAscendingIndex().
continuousAscendingIndex()
template<typename NODE > bool dyno::FastMapNodeSet< NODE >::continuousAscendingIndex () const inline
Checks if the ID's of all the nodes are containuously ascending (ie. there is no missing ID)
Returns
true
false
Definition at line 235 of file MapNodes.hpp.
{
    auto ids = collectIds();
    if (ids.size() < 2) return true;
    bool is_continuous = true;
    for (size_t i = 1; i < ids.size(); i++) {
      const auto prev = ids.at(i - 1);
      const auto curr = ids.at(i);
      is_continuous &= (prev + 1 == curr);
    }
    return is_continuous;
  }
References dyno::FastMapNodeSet< NODE >::collectIds().
exists()
template<typename NODE > template<typename Index = int> bool dyno::FastMapNodeSet< NODE >::exists (Index index) const inline
Check if a node with the given ID exists in the container.
Template Parameters
Index
Parameters
index
Returns
true
false
Definition at line 215 of file MapNodes.hpp.
{
    return this->find(index) != this->end();
  }
References dyno::FastMapNodeSet< NODE >::find().
find() [1/2]
template<typename NODE > template<typename Index = int> Base::iterator dyno::FastMapNodeSet< NODE >::find (Index index) inline
Find a NODE based on their index. Returns this->end() if not found. Non const version.
Template Parameters
Index
Parameters
index
Returns
Base::iterator
Definition at line 184 of file MapNodes.hpp.
{
    return std::find_if(Base::begin(), Base::cend(), [index](const NODE& node) {
      return getIndexSafe<Index>(node) == index;
    });
  }
Referenced by dyno::FastMapNodeSet< NODE >::exists(), and dyno::ObjectNode< MEASUREMENT >::getLandmarksSeenAtFrame().
find() [2/2]
template<typename NODE > template<typename Index = int> Base::const_iterator dyno::FastMapNodeSet< NODE >::find (Index index) const inline
Find a NODE based on their index. Returns this->end() if not found. Const version.
Template Parameters
Index
Parameters
index
Returns
Base::const_iterator
Definition at line 199 of file MapNodes.hpp.
{
    return std::find_if(Base::cbegin(), Base::cend(),
                        [index](const NODE& node) {
                          return getIndexSafe<Index>(node) == index;
                        });
  }
getFirstIndex()
template<typename NODE > template<typename Index = int> Index dyno::FastMapNodeSet< NODE >::getFirstIndex () const inline
Get the first (smallest) index stored.
Template Parameters
Index
Returns
Index
Definition at line 158 of file MapNodes.hpp.
{
    const NODE& node = *Base::cbegin();
    return getIndexSafe<Index>(node);
  }
getIndexSafe()
template<typename NODE > template<typename Index > static Index dyno::FastMapNodeSet< NODE >::getIndexSafe (const NODE & node) inline static private
Definition at line 250 of file MapNodes.hpp.
{
    return static_cast<Index>(node->getId());
  }
getLastIndex()
template<typename NODE > template<typename Index = int> Index dyno::FastMapNodeSet< NODE >::getLastIndex () const inline
Get the last (largest) index stored.
Template Parameters
Index
Returns
Index
Definition at line 170 of file MapNodes.hpp.
{
    const NODE& node = *Base::crbegin();
    return getIndexSafe<Index>(node);
  }
merge()
template<typename NODE > void dyno::FastMapNodeSet< NODE >::merge (const FastMapNodeSet< NODE > & other) inline
Merges this container with another. Will automatically be sorted.
Parameters
other FastMapNodeSet<NODE>&
Definition at line 224 of file MapNodes.hpp.
{
    Base::insert(other.begin(), other.end());
  }
Referenced by dyno::ObjectNode< MEASUREMENT >::getSeenFrames().
The documentation for this class was generated from the following file:
dynosam/include/dynosam/common/MapNodes.hpp