DynoSAM: dyno::RGBDBackendModule Class Reference
dyno::RGBDBackendModule Class Reference
#include <RGBDBackendModule.hpp>
Classes
struct SlidingWindow
Helper struct to determine the conditions for the sliding window optimisation. Only works when called in consequative frame order as we use the last trigger frame (the last frame when the sliding window conditions were true) to determine the next one.
Public Types
enum UpdaterType { MotionInWorld = 0 , LLWorld = 1 }
using Base = BackendModuleType< RGBDBackendModuleTraits >
using RGBDMap = Base::MapType
using SpinReturn = Base::SpinReturn
Public Types inherited from dyno::BackendModuleType< RGBDBackendModuleTraits >
using ModuleTraits = RGBDBackendModuleTraits
using DerivedPacketType = typename ModuleTraits::DerivedPacketType
using DerivedPacketTypeConstPtr = typename ModuleTraits::DerivedPacketTypeConstPtr
using MeasurementType = typename ModuleTraits::MeasurementType
using This = BackendModuleType< ModuleTraits >
using Base = BackendModule
using MapType = Map< MeasurementType >
using InputConstPtr = DerivedPacketTypeConstPtr
using OutputConstPtr = Base::OutputConstPtr
Public Types inherited from dyno::BackendModule
using Base = ModuleBase< BackendInputPacket, BackendOutputPacket >
Public Types inherited from dyno::ModuleBase< BackendInputPacket, BackendOutputPacket >
enum State
using Input = BackendInputPacket
using Output = BackendOutputPacket
using InputConstPtr = typename INPUT::ConstPtr
using OutputConstPtr = typename OUTPUT::ConstPtr
ConstPtr to an INPUT type.
using This = ModuleBase< BackendInputPacket, BackendOutputPacket >
ConstPtr to an OUTPUT type.
using SpinReturn = std::pair< State, OutputConstPtr >
using InputCallback = std::function< void(InputConstPtr)>
using OutputCallback = std::function< void(OutputConstPtr)>
Public Member Functions
RGBDBackendModule (const BackendParams &backend_params, RGBDMap::Ptr map, Camera::Ptr camera, const UpdaterType &updater_type, ImageDisplayQueue *display_queue=nullptr)
~RGBDBackendModule ()
void saveGraph (const std::string &file="rgbd_graph.dot")
void saveTree (const std::string &file="rgbd_bayes_tree.dot")
std::tuple< gtsam::Values, gtsam::NonlinearFactorGraph > constructGraph (FrameId from_frame, FrameId to_frame, bool set_initial_camera_pose_prior, std::optional< gtsam::Values > initial_theta={})
SpinReturn boostrapSpinImpl (RGBDInstanceOutputPacket::ConstPtr input) override
SpinReturn nominalSpinImpl (RGBDInstanceOutputPacket::ConstPtr input) override
void updateMap (gtsam::Pose3 &T_world_cam, RGBDInstanceOutputPacket::ConstPtr input)
bool buildSlidingWindowOptimisation (FrameId frame_k, gtsam::Values &optimised_values, double &error_before, double &error_after)
Formulation< RGBDMap >::UniquePtr makeUpdater ()
auto getGtsamCalibration () const
Public Member Functions inherited from dyno::BackendModuleType< RGBDBackendModuleTraits >
BackendModuleType (const BackendParams &params, typename MapType::Ptr map, ImageDisplayQueue *display_queue)
virtual ~BackendModuleType ()
const MapType::Ptr getMap ()
Public Member Functions inherited from dyno::BackendModule
BackendModule (const BackendParams &params, ImageDisplayQueue *display_queue)
virtual ~BackendModule ()=default
std::optional< GroundTruthPacketMap > getGroundTruthPackets () const
Public Member Functions inherited from dyno::ModuleBase< BackendInputPacket, BackendOutputPacket >
ModuleBase (const std::string &name)
virtual ~ModuleBase ()=default
OutputConstPtr spinOnce (InputConstPtr input)
void registerInputCallback (const InputCallback &input_callback)
Registeres a function callback to be triggered prior to nominal/bootstrapSpin being called.
void registerOutputCallback (const OutputCallback &output_callback)
Registeres a function callback to be triggered after nominal/bootstrapSpin is called.
Public Attributes
Camera::Ptr camera_
const UpdaterType updater_type_
Formulation< RGBDMap >::UniquePtr new_updater_
SlidingWindow::UniquePtr sliding_window_condition_
FrameId first_frame_id_
BackendLogger::UniquePtr logger_ {nullptr}
DebugInfo debug_info_
Additional Inherited Members
Protected Types inherited from dyno::BackendModule
using BaseInputConstPtr = Base::InputConstPtr
using BaseInput = Base::Input
Protected Member Functions inherited from dyno::BackendModuleType< RGBDBackendModuleTraits >
virtual SpinReturn boostrapSpinImpl (InputConstPtr input)=0
virtual SpinReturn nominalSpinImpl (InputConstPtr input)=0
Protected Member Functions inherited from dyno::BackendModule
virtual void validateInput (const BackendInputPacket::ConstPtr &input) const override
void setFactorParams (const BackendParams &backend_params)
Protected Member Functions inherited from dyno::ModuleBase< BackendInputPacket, BackendOutputPacket >
virtual void validateInput (const InputConstPtr &input) const=0
Checks the state of the input before running any virtual spin (boostrap or nominal) functions.
virtual SpinReturn boostrapSpin (InputConstPtr input)=0
virtual SpinReturn nominalSpin (InputConstPtr input)=0
Protected Attributes inherited from dyno::BackendModuleType< RGBDBackendModuleTraits >
MapType::Ptr map_
Protected Attributes inherited from dyno::BackendModule
const BackendParams base_params_
GroundTruthPacketMap gt_packet_map_
ImageDisplayQueue * display_queue_ {nullptr}
BackendSpinState spin_state_
Optional display queue.
NoiseModels noise_models_
Detailed Description
Definition at line 52 of file RGBDBackendModule.hpp.
Member Typedef Documentation
Base
using dyno::RGBDBackendModule::Base = BackendModuleType<RGBDBackendModuleTraits>
Definition at line 54 of file RGBDBackendModule.hpp.
RGBDMap
using dyno::RGBDBackendModule::RGBDMap = Base::MapType
Definition at line 55 of file RGBDBackendModule.hpp.
SpinReturn
using dyno::RGBDBackendModule::SpinReturn = Base::SpinReturn
Definition at line 64 of file RGBDBackendModule.hpp.
Member Enumeration Documentation
UpdaterType
enum dyno::RGBDBackendModule::UpdaterType
Enumerator
MotionInWorld
LLWorld
Definition at line 57 of file RGBDBackendModule.hpp.
{ MotionInWorld = 0, LLWorld = 1 };
Constructor & Destructor Documentation
RGBDBackendModule()
dyno::RGBDBackendModule::RGBDBackendModule (const BackendParams & backend_params, RGBDMap::Ptr map, Camera::Ptr camera, const UpdaterType & updater_type, ImageDisplayQueue * display_queue = nullptr)
Definition at line 78 of file RGBDBackendModule.cc.
    : Base(backend_params, map, display_queue),
      camera_(CHECK_NOTNULL(camera)),
      updater_type_(updater_type) {
  CHECK_NOTNULL(map);
  CHECK_NOTNULL(map_);
  // TODO: functioanlise and streamline with BackendModule
  noise_models_.static_point_noise = gtsam::noiseModel::Isotropic::Sigma(
      3u, backend_params.static_point_noise_sigma_);
  noise_models_.dynamic_point_noise = gtsam::noiseModel::Isotropic::Sigma(
      3u, backend_params.dynamic_point_noise_sigma_);
  // set in base!
  noise_models_.landmark_motion_noise = gtsam::noiseModel::Isotropic::Sigma(
      3u, backend_params.motion_ternary_factor_noise_sigma_);
  if (backend_params.use_robust_kernals_) {
    noise_models_.static_point_noise = gtsam::noiseModel::Robust::Create(
        gtsam::noiseModel::mEstimator::Huber::Create(
            backend_params.k_huber_3d_points_),
        noise_models_.static_point_noise);
    noise_models_.dynamic_point_noise = gtsam::noiseModel::Robust::Create(
        gtsam::noiseModel::mEstimator::Huber::Create(
            backend_params.k_huber_3d_points_),
        noise_models_.dynamic_point_noise);
    // TODO: not k_huber_3d_points_ not just used for 3d points
    noise_models_.landmark_motion_noise = gtsam::noiseModel::Robust::Create(
        gtsam::noiseModel::mEstimator::Huber::Create(
            backend_params.k_huber_3d_points_),
        noise_models_.landmark_motion_noise);
  }
  CHECK_NOTNULL(noise_models_.static_point_noise);
  CHECK_NOTNULL(noise_models_.dynamic_point_noise);
  CHECK_NOTNULL(noise_models_.landmark_motion_noise);
  noise_models_.dynamic_point_noise->print("Dynamic Point Noise");
  noise_models_.landmark_motion_noise->print("Landmark motion noise");
  // CHECK(false);
  new_updater_ = std::move(makeUpdater());
  sliding_window_condition_ = std::make_unique<SlidingWindow>(
      FLAGS_opt_window_size, FLAGS_opt_window_overlap);
}
References dyno::NoiseModels::dynamic_point_noise, dyno::BackendParams::dynamic_point_noise_sigma_, dyno::BackendParams::k_huber_3d_points_, dyno::NoiseModels::landmark_motion_noise, makeUpdater(), dyno::BackendModuleType< RGBDBackendModuleTraits >::map_, dyno::BackendParams::motion_ternary_factor_noise_sigma_, new_updater_, dyno::BackendModule::noise_models_, sliding_window_condition_, dyno::NoiseModels::static_point_noise, dyno::BackendParams::static_point_noise_sigma_, and dyno::BackendParams::use_robust_kernals_.
~RGBDBackendModule()
dyno::RGBDBackendModule::~RGBDBackendModule ()
Definition at line 128 of file RGBDBackendModule.cc.
{
  LOG(INFO) << "Destructing RGBDBackendModule";
  if (base_params_.use_logger_) {
    // hack to make sure things are updated!!
    BackendMetaData backend_info;
    backend_info.params = base_params_;
    backend_info.ground_truth_packets = this->getGroundTruthPackets();
    new_updater_->accessorFromTheta()->postUpdateCallback(backend_info);
    new_updater_->logBackendFromMap(backend_info);
  }
}
References dyno::BackendModule::base_params_, dyno::BackendModule::getGroundTruthPackets(), dyno::BackendMetaData::ground_truth_packets, new_updater_, dyno::BackendMetaData::params, and dyno::BackendParams::use_logger_.
Member Function Documentation
boostrapSpinImpl()
RGBDBackendModule::SpinReturn dyno::RGBDBackendModule::boostrapSpinImpl (RGBDInstanceOutputPacket::ConstPtr input) override
Definition at line 142 of file RGBDBackendModule.cc.
{
  const FrameId frame_k = input->getFrameId();
  first_frame_id_ = frame_k;
  CHECK_EQ(spin_state_.frame_id, frame_k);
  LOG(INFO) << "Running backend " << frame_k;
  CHECK(!(bool)sliding_window_condition_->check(
      frame_k));  // trigger the check to update the first frame call. Bit
                  // gross!
  // Pose estimate from the front-end
  gtsam::Pose3 T_world_cam_k_frontend;
  updateMap(T_world_cam_k_frontend, input);
  gtsam::Values new_values;
  gtsam::NonlinearFactorGraph new_factors;
  new_updater_->setInitialPose(T_world_cam_k_frontend, frame_k, new_values);
  new_updater_->setInitialPosePrior(T_world_cam_k_frontend, frame_k,
                                    new_factors);
  return {State::Nominal, nullptr};
}
References first_frame_id_, dyno::BackendSpinState::frame_id, new_updater_, sliding_window_condition_, dyno::BackendModule::spin_state_, and updateMap().
buildSlidingWindowOptimisation()
bool dyno::RGBDBackendModule::buildSlidingWindowOptimisation (FrameId frame_k, gtsam::Values & optimised_values, double & error_before, double & error_after)
Definition at line 355 of file RGBDBackendModule.cc.
{
  auto condition_result = sliding_window_condition_->check(frame_k);
  if (condition_result) {
    const auto start_frame = condition_result.starting_frame;
    const auto end_frame = condition_result.ending_frame;
    LOG(INFO) << "Running dynamic slam window on between frames " << start_frame
              << " - " << end_frame;
    gtsam::Values values;
    gtsam::NonlinearFactorGraph graph;
    {
      utils::TimingStatsCollector timer(new_updater_->getFullyQualifiedName() +
                                        ".sliding_window_construction");
      std::tie(values, graph) = constructGraph(start_frame, end_frame, true,
                                               new_updater_->getTheta());
      LOG(INFO) << " Finished graph construction";
    }
    error_before = graph.error(values);
    gtsam::LevenbergMarquardtParams opt_params;
    if (VLOG_IS_ON(20))
      opt_params.verbosity = gtsam::NonlinearOptimizerParams::Verbosity::ERROR;
    utils::TimingStatsCollector timer(new_updater_->getFullyQualifiedName() +
                                      ".sliding_window_optimise");
    utils::StatsCollector(new_updater_->getFullyQualifiedName() +
                          ".sliding_window_optimise_num_vars_all")
        .AddSample(values.size());
    try {
      optimised_values =
          gtsam::LevenbergMarquardtOptimizer(graph, values, opt_params)
              .optimize();
      LOG(INFO) << "Finished op!";
    } catch (const gtsam::ValuesKeyDoesNotExist& e) {
      LOG(FATAL)
          << "gtsam::ValuesKeyDoesNotExist: key does not exist in the values"
          << DynoLikeKeyFormatter(e.key());
    }
    error_after = graph.error(optimised_values);
    return true;
  }
  return false;
}
References dyno::utils::StatsCollectorImpl::AddSample(), constructGraph(), dyno::DynoLikeKeyFormatter(), new_updater_, and sliding_window_condition_.
Referenced by nominalSpinImpl().
constructGraph()
std::tuple< gtsam::Values, gtsam::NonlinearFactorGraph > dyno::RGBDBackendModule::constructGraph (FrameId from_frame, FrameId to_frame, bool set_initial_camera_pose_prior, std::optional< gtsam::Values > initial_theta = {})
Definition at line 293 of file RGBDBackendModule.cc.
{
  CHECK_LT(from_frame, to_frame);
  gtsam::Values new_values;
  gtsam::NonlinearFactorGraph new_factors;
  auto updater = std::move(makeUpdater());
  if (initial_theta) {
    // update initial linearisation points (could be from a previous
    // optimisation)
    // TODO: currently cannot set theta becuase this will be ALL the previous
    // values and not just the ones in
    // TODO: for now dont do this as we have to handle covariance/santiy checks
    // differently as some modules expect values to be new and will check that
    // a value does not exist yet (becuase it shouldn't in that iteration, but
    // overall it may!)
    //  updater->setTheta(*initial_theta);
  }
  UpdateObservationParams update_params;
  update_params.do_backtrack = false;
  update_params.enable_debug_info = true;
  UpdateObservationResult results;
  CHECK_GE(from_frame, map_->firstFrameId());
  CHECK_LE(to_frame, map_->lastFrameId());
  // TODO: pick how new values are going to be used as right now they get
  // appened internallty to the thera and I think this is very slow so we should
  // not do this...
  for (auto frame_id = from_frame; frame_id <= to_frame; frame_id++) {
    LOG(INFO) << "Constructing dynamic graph at frame " << frame_id
              << " in loop (" << from_frame << " -> " << to_frame << ")";
    // pose estimate from frontend
    gtsam::Pose3 T_world_camera_k;
    CHECK(map_->hasInitialSensorPose(frame_id, &T_world_camera_k));
    // if first frame
    if (frame_id == from_frame) {
      // add first pose
      updater->setInitialPose(T_world_camera_k, frame_id, new_values);
      if (set_initial_camera_pose_prior)
        updater->setInitialPosePrior(T_world_camera_k, frame_id, new_factors);
    } else {
      updater->addOdometry(frame_id, T_world_camera_k, new_values, new_factors);
      // no backtrack
      results += updater->updateDynamicObservations(frame_id, new_values,
                                                    new_factors, update_params);
    }
    results += updater->updateStaticObservations(frame_id, new_values,
                                                 new_factors, update_params);
  }
  return {new_values, new_factors};
}
References dyno::UpdateObservationParams::do_backtrack, dyno::UpdateObservationParams::enable_debug_info, makeUpdater(), and dyno::BackendModuleType< RGBDBackendModuleTraits >::map_.
Referenced by buildSlidingWindowOptimisation().
getGtsamCalibration()
auto dyno::RGBDBackendModule::getGtsamCalibration () const inline
Definition at line 167 of file RGBDBackendModule.hpp.
{
    const CameraParams& camera_params = camera_->getParams();
    return boost::make_shared<Camera::CalibrationType>(
        camera_params.constructGtsamCalibration<Camera::CalibrationType>());
  }
References camera_, and dyno::CameraParams::constructGtsamCalibration().
makeUpdater()
Formulation< RGBDBackendModule::RGBDMap >::UniquePtr dyno::RGBDBackendModule::makeUpdater ()
Definition at line 403 of file RGBDBackendModule.cc.
{
  FormulationParams formulation_params;
  formulation_params.min_static_observations = base_params_.min_static_obs_;
  formulation_params.min_dynamic_observations = base_params_.min_dynamic_obs_;
  formulation_params.suffix = FLAGS_updater_suffix;
  if (updater_type_ == UpdaterType::MotionInWorld) {
    LOG(INFO) << "Using MotionInWorld";
    return std::make_unique<WorldMotionFormulation>(formulation_params,
                                                    getMap(), noise_models_);
  } else if (updater_type_ == UpdaterType::LLWorld) {
    LOG(INFO) << "Using LLWorld";
    return std::make_unique<WorldPoseFormulation>(formulation_params, getMap(),
                                                  noise_models_);
  } else {
    CHECK(false) << "Not implemented";
  }
}
References dyno::BackendModule::base_params_, dyno::BackendModuleType< RGBDBackendModuleTraits >::getMap(), LLWorld, dyno::BackendParams::min_dynamic_obs_, dyno::FormulationParams::min_dynamic_observations, dyno::BackendParams::min_static_obs_, dyno::FormulationParams::min_static_observations, MotionInWorld, dyno::BackendModule::noise_models_, dyno::FormulationParams::suffix, and updater_type_.
Referenced by constructGraph(), and RGBDBackendModule().
nominalSpinImpl()
RGBDBackendModule::SpinReturn dyno::RGBDBackendModule::nominalSpinImpl (RGBDInstanceOutputPacket::ConstPtr input) override
Definition at line 165 of file RGBDBackendModule.cc.
{
  const FrameId frame_k = input->getFrameId();
  LOG(INFO) << "Running backend " << frame_k;
  CHECK_EQ(spin_state_.frame_id, frame_k);
  // Pose estimate from the front-end
  gtsam::Pose3 T_world_cam_k_frontend;
  updateMap(T_world_cam_k_frontend, input);
  gtsam::Values new_values;
  gtsam::NonlinearFactorGraph new_factors;
  new_updater_->addOdometry(frame_k, T_world_cam_k_frontend, new_values,
                            new_factors);
  UpdateObservationParams update_params;
  update_params.enable_debug_info = true;
  update_params.do_backtrack =
      false;  // apparently this is v important for making the results == ICRA
  {
    LOG(INFO) << "Starting updateStaticObservations";
    utils::TimingStatsCollector timer("backend.update_static_obs");
    new_updater_->updateStaticObservations(frame_k, new_values, new_factors,
                                           update_params);
  }
  {
    LOG(INFO) << "Starting updateDynamicObservations";
    utils::TimingStatsCollector timer("backend.update_dynamic_obs");
    new_updater_->updateDynamicObservations(frame_k, new_values, new_factors,
                                            update_params);
  }
  if (FLAGS_use_full_batch_opt) {
    LOG(INFO) << " full batch frame " << base_params_.full_batch_frame;
    if (base_params_.full_batch_frame - 1 == (int)frame_k) {
      LOG(INFO) << " Doing full batch at frame " << frame_k;
      // graph.error(values);
      gtsam::LevenbergMarquardtParams opt_params;
      opt_params.verbosity = gtsam::NonlinearOptimizerParams::Verbosity::ERROR;
      const auto theta = new_updater_->getTheta();
      const auto graph = new_updater_->getGraph();
      utils::StatsCollector(new_updater_->getFullyQualifiedName() +
                            ".full_batch_opt_num_vars_all")
          .AddSample(theta.size());
      double error_before = graph.error(theta);
      utils::TimingStatsCollector timer(new_updater_->getFullyQualifiedName() +
                                        ".full_batch_opt");
      gtsam::LevenbergMarquardtOptimizer problem(graph, theta, opt_params);
      gtsam::Values optimised_values = problem.optimize();
      double error_after = graph.error(optimised_values);
      utils::StatsCollector(new_updater_->getFullyQualifiedName() +
                            ".inner_iterations")
          .AddSample(problem.getInnerIterations());
      utils::StatsCollector(new_updater_->getFullyQualifiedName() +
                            ".iterations")
          .AddSample(problem.iterations());
      new_updater_->updateTheta(optimised_values);
      LOG(INFO) << " Error before sliding window: " << error_before
                << " error after: " << error_after;
    }
  } else {
    double error_before, error_after;
    gtsam::Values optimised_values;
    if (buildSlidingWindowOptimisation(frame_k, optimised_values, error_before,
                                       error_after)) {
      LOG(INFO) << "Updating values with opt!";
      new_updater_->updateTheta(optimised_values);
      LOG(INFO) << " Error before sliding window: " << error_before
                << " error after: " << error_after;
    }
  }
  auto accessor = new_updater_->accessorFromTheta();
  utils::TimingStatsCollector timer(new_updater_->getFullyQualifiedName() +
                                    ".post_update");
  BackendMetaData backend_info;
  backend_info.params = base_params_;
  backend_info.ground_truth_packets = this->getGroundTruthPackets();
  new_updater_->accessorFromTheta()->postUpdateCallback(
      backend_info);  // force update every time (slow! and just for testing)
  auto backend_output = std::make_shared<BackendOutputPacket>();
  backend_output->timestamp_ = input->getTimestamp();
  backend_output->frame_id_ = input->getFrameId();
  backend_output->T_world_camera_ = accessor->getSensorPose(frame_k).get();
  backend_output->static_landmarks_ = accessor->getFullStaticMap();
  backend_output->dynamic_landmarks_ =
      accessor->getDynamicLandmarkEstimates(frame_k);
  for (FrameId frame_id : map_->getFrameIds()) {
    backend_output->optimized_poses_.push_back(
        accessor->getSensorPose(frame_id).get());
  }
  backend_output->composed_object_poses = accessor->getObjectPoses();
  debug_info_ = DebugInfo();
  return {State::Nominal, backend_output};
}
References dyno::utils::StatsCollectorImpl::AddSample(), dyno::BackendModule::base_params_, buildSlidingWindowOptimisation(), debug_info_, dyno::UpdateObservationParams::do_backtrack, dyno::UpdateObservationParams::enable_debug_info, dyno::BackendSpinState::frame_id, dyno::BackendParams::full_batch_frame, dyno::BackendModule::getGroundTruthPackets(), dyno::BackendMetaData::ground_truth_packets, dyno::BackendModuleType< RGBDBackendModuleTraits >::map_, new_updater_, dyno::BackendMetaData::params, dyno::BackendModule::spin_state_, and updateMap().
saveGraph()
void dyno::RGBDBackendModule::saveGraph (const std::string & file = "rgbd_graph.dot")
Definition at line 424 of file RGBDBackendModule.cc.
{
  // TODO: must be careful as there could be inconsistencies between the graph
  // in the optimzier, and the graph in the map
  // TODO:
  //  gtsam::NonlinearFactorGraph graph = map_->getGraph();
  //  // gtsam::NonlinearFactorGraph graph = smoother_->getFactorsUnsafe();
  //  graph.saveGraph(getOutputFilePath(file), DynoLikeKeyFormatter);
}
saveTree()
void dyno::RGBDBackendModule::saveTree (const std::string & file = "rgbd_bayes_tree.dot")
Definition at line 432 of file RGBDBackendModule.cc.
{
  // auto incremental_optimizer = safeCast<Optimizer<Landmark>,
  // IncrementalOptimizer<Landmark>>(optimizer_); if(incremental_optimizer) {
  //     auto smoother = incremental_optimizer->getSmoother();
  //     smoother.saveGraph(getOutputFilePath(file), DynoLikeKeyFormatter);
  //     // smoother.getISAM2().saveGraph(getOutputFilePath(file),
  //     DynoLikeKeyFormatter);
  // }
}
updateMap()
void dyno::RGBDBackendModule::updateMap (gtsam::Pose3 & T_world_cam, RGBDInstanceOutputPacket::ConstPtr input)
Definition at line 276 of file RGBDBackendModule.cc.
{
  utils::TimingStatsCollector timer("map.update_observations");
  const gtsam::Pose3 T_world_cam_k_frontend = input->T_world_camera_;
  const FrameId frame_k = input->getFrameId();
  map_->updateObservations(input->collectStaticLandmarkKeypointMeasurements());
  map_->updateObservations(input->collectDynamicLandmarkKeypointMeasurements());
  // update other measurements
  map_->updateSensorPoseMeasurement(frame_k, T_world_cam_k_frontend);
  map_->updateObjectMotionMeasurements(frame_k, input->estimated_motions_);
  T_world_cam = T_world_cam_k_frontend;
}
References dyno::BackendModuleType< RGBDBackendModuleTraits >::map_.
Referenced by boostrapSpinImpl(), and nominalSpinImpl().
Member Data Documentation
camera_
Camera::Ptr dyno::RGBDBackendModule::camera_
Definition at line 159 of file RGBDBackendModule.hpp.
Referenced by getGtsamCalibration().
debug_info_
DebugInfo dyno::RGBDBackendModule::debug_info_
Definition at line 175 of file RGBDBackendModule.hpp.
Referenced by nominalSpinImpl().
first_frame_id_
FrameId dyno::RGBDBackendModule::first_frame_id_
Definition at line 164 of file RGBDBackendModule.hpp.
Referenced by boostrapSpinImpl().
logger_
BackendLogger::UniquePtr dyno::RGBDBackendModule::logger_ {nullptr}
Definition at line 174 of file RGBDBackendModule.hpp.
new_updater_
Formulation<RGBDMap>::UniquePtr dyno::RGBDBackendModule::new_updater_
Definition at line 162 of file RGBDBackendModule.hpp.
Referenced by boostrapSpinImpl(), buildSlidingWindowOptimisation(), nominalSpinImpl(), RGBDBackendModule(), and ~RGBDBackendModule().
sliding_window_condition_
SlidingWindow::UniquePtr dyno::RGBDBackendModule::sliding_window_condition_
Definition at line 163 of file RGBDBackendModule.hpp.
Referenced by boostrapSpinImpl(), buildSlidingWindowOptimisation(), and RGBDBackendModule().
updater_type_
const UpdaterType dyno::RGBDBackendModule::updater_type_
Definition at line 160 of file RGBDBackendModule.hpp.
Referenced by makeUpdater().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/backend/RGBDBackendModule.hpp
dynosam/src/backend/RGBDBackendModule.cc