DynoSAM: dyno::ExternalFlowFeatureTracker Class Reference
dyno::ExternalFlowFeatureTracker Class Reference
#include <StaticFeatureTracker.hpp>
Public Member Functions
ExternalFlowFeatureTracker (const TrackerParams &params, Camera::Ptr camera, ImageDisplayQueue *display_queue)
FeatureContainer trackStatic (Frame::Ptr previous_frame, const ImageContainer &image_container, FeatureTrackerInfo &tracker_info, const cv::Mat &detection_mask, const std::optional< gtsam::Rot3 > &R_km1_k={}) override
Base function to perform feature tracking on static points.
Public Member Functions inherited from dyno::StaticFeatureTracker
StaticFeatureTracker (const TrackerParams &params, Camera::Ptr camera, ImageDisplayQueue *display_queue)
virtual ~StaticFeatureTracker ()
virtual FeatureContainer trackStatic (Frame::Ptr previous_frame, const ImageContainer &image_container, FeatureTrackerInfo &tracker_info, const cv::Mat &detection_mask, const std::optional< gtsam::Rot3 > &R_km1_k)=0
Base function to perform feature tracking on static points.
Public Member Functions inherited from dyno::FeatureTrackerBase
FeatureTrackerBase (const TrackerParams &params, Camera::Ptr camera, ImageDisplayQueue *display_queue)
cv::Mat computeImageTracks (const Frame &previous_frame, const Frame &current_frame, const ImageTracksParams &config=false) const
bool drawStereoMatches (cv::Mat &output_image, const Frame &current_frame) const
bool predictKeypointsGivenRotation (std::vector< cv::Point2f > &predicted_pts_k, const std::vector< cv::Point2f > &pts_km1, const gtsam::Rot3 &R_km1_k) const
Private Member Functions
Feature::Ptr constructStaticFeature (const ImageContainer &image_container, const Keypoint &kp, size_t age, TrackletId tracklet_id, FrameId frame_id) const
Private Attributes
OccupandyGrid2D static_grid_
ORBextractor::UniquePtr orb_detector_ {nullptr}
Grid used to feature bin static features.
const size_t static_cell_size
Additional Inherited Members
Protected Member Functions inherited from dyno::FeatureTrackerBase
bool isWithinShrunkenImage (const Keypoint &kp) const
Checks if a keypoint is within an image, taking into account the shrink row/col values in the params. If these values are zero, it just checks that the keypoint is within the image size, as given by the camera parameters.
bool isWithinShrunkenImage (const cv::Point2f &kp) const
Protected Attributes inherited from dyno::FeatureTrackerBase
const TrackerParams params_
const cv::Size img_size_
Camera::Ptr camera_
Expected image size from the camera.
ImageDisplayQueue * display_queue_
Detailed Description
Definition at line 81 of file StaticFeatureTracker.hpp.
Constructor & Destructor Documentation
ExternalFlowFeatureTracker()
dyno::ExternalFlowFeatureTracker::ExternalFlowFeatureTracker (const TrackerParams & params, Camera::Ptr camera, ImageDisplayQueue * display_queue)
Definition at line 49 of file StaticFeatureTracker.cc.
    : StaticFeatureTracker(params, camera, display_queue),
      static_grid_(
          static_cell_size,
          std::ceil(static_cast<double>(camera->getParams().ImageWidth()) /
                    static_cell_size),
          std::ceil(static_cast<double>(camera->getParams().ImageHeight()) /
                    static_cell_size)) {
  const auto orb_params = params.orb_params;
  orb_detector_ = std::make_unique<ORBextractor>(
      params.max_nr_keypoints_before_anms,
      static_cast<float>(orb_params.scale_factor), orb_params.n_levels,
      orb_params.init_threshold_fast, orb_params.min_threshold_fast);
  CHECK(!img_size_.empty());
}
References dyno::FeatureTrackerBase::img_size_, dyno::TrackerParams::max_nr_keypoints_before_anms, orb_detector_, and dyno::TrackerParams::orb_params.
Member Function Documentation
constructStaticFeature()
Feature::Ptr dyno::ExternalFlowFeatureTracker::constructStaticFeature (const ImageContainer & image_container, const Keypoint & kp, size_t age, TrackletId tracklet_id, FrameId frame_id) const private
Definition at line 175 of file StaticFeatureTracker.cc.
{
  // implicit double -> int cast for pixel location
  const int x = functional_keypoint::u(kp);
  const int y = functional_keypoint::v(kp);
  const cv::Mat& rgb = image_container.rgb();
  const cv::Mat& motion_mask = image_container.objectMotionMask();
  const cv::Mat& optical_flow = image_container.opticalFlow();
  CHECK(!optical_flow.empty());
  CHECK(!motion_mask.empty());
  if (motion_mask.at<int>(y, x) != background_label) {
    return nullptr;
  }
  // check flow
  double flow_xe = static_cast<double>(optical_flow.at<cv::Vec2f>(y, x)[0]);
  double flow_ye = static_cast<double>(optical_flow.at<cv::Vec2f>(y, x)[1]);
  if (!(flow_xe != 0 && flow_ye != 0)) {
    return nullptr;
  }
  OpticalFlow flow(flow_xe, flow_ye);
  // check predicted flow is within image
  Keypoint predicted_kp = Feature::CalculatePredictedKeypoint(kp, flow);
  if (!camera_->isKeypointContained(predicted_kp)) {
    return nullptr;
  }
  Feature::Ptr feature = std::make_shared<Feature>();
  (*feature)
      .objectId(background_label)
      .frameId(frame_id)
      .keypointType(KeyPointType::STATIC)
      .age(age)
      .trackletId(tracklet_id)
      .keypoint(kp)
      .measuredFlow(flow)
      .predictedKeypoint(predicted_kp);
  return feature;
}
References dyno::background_label, dyno::Feature::CalculatePredictedKeypoint(), dyno::FeatureTrackerBase::camera_, dyno::ImageContainer::objectMotionMask(), dyno::ImageContainer::opticalFlow(), dyno::ImageContainer::rgb(), dyno::STATIC, dyno::functional_keypoint::u(), and dyno::functional_keypoint::v().
Referenced by trackStatic().
trackStatic()
FeatureContainer dyno::ExternalFlowFeatureTracker::trackStatic (Frame::Ptr previous_frame, const ImageContainer & image_container, FeatureTrackerInfo & tracker_info, const cv::Mat & detection_mask, const std::optional< gtsam::Rot3 > & R_km1_k = {}) override virtual
Base function to perform feature tracking on static points.
Is not intended to be state-ful (ie. contains a reference to the last frame) and instead we pass in the previous frame everytime.
If the previous frame is null this should indicate that this is the first frame to be tracked!
Parameters
previous_frame Frame::Ptr. Previous frame (k-1) with filled-out features to be tracked.
image_container const ImageContainer&. Contains current (k) images which will be tracked from the previous frame.
tracker_info FeatureTrackerInfo&. Tracking metadata to be filled out.
detection_mask const cv::Mat& A detection mask in the opencv feature tracking form: CV_8UC1 where white pixels (255) are valid and black pixels (0) should not be detected on
Returns
FeatureContainer Contains all successsfully tracked features.
Implements dyno::StaticFeatureTracker.
Definition at line 70 of file StaticFeatureTracker.cc.
{
  const ImageWrapper<ImageType::RGBMono>& rgb_wrapper = image_container.rgb();
  const cv::Mat& rgb = rgb_wrapper.toRGB();
  cv::Mat mono = ImageType::RGBMono::toMono(rgb_wrapper);
  CHECK(!mono.empty());
  const cv::Mat& motion_mask = image_container.objectMotionMask();
  CHECK(!motion_mask.empty());
  cv::Mat descriptors;
  KeypointsCV detected_keypoints;
  (*orb_detector_)(mono, cv::Mat(), detected_keypoints, descriptors);
  // assign tracked features to grid and add to static features
  FeatureContainer static_features;
  const size_t& min_tracks =
      static_cast<size_t>(params_.max_features_per_frame);
  const FrameId frame_k = image_container.frameId();
  // appy tracking (ie get correspondences)
  // TODO: only track frames that have been tracked for some time?
  if (previous_frame) {
    // TODO: for now assume consequative frames
    const FrameId frame_k_1 = previous_frame->getFrameId();
    CHECK_EQ(frame_k_1 + 1u, frame_k);
    for (Feature::Ptr previous_feature : previous_frame->static_features_) {
      const size_t tracklet_id = previous_feature->trackletId();
      const size_t age = previous_feature->age();
      const Keypoint kp = previous_feature->predictedKeypoint();
      // check kp contained before we do a static grid look up to ensure we
      // don't go out of bounds
      if (!camera_->isKeypointContained(kp)) {
        continue;
      }
      const int x = functional_keypoint::u(kp);
      const int y = functional_keypoint::v(kp);
      const size_t cell_idx = static_grid_.getCellIndex(kp);
      const ObjectId instance_label = motion_mask.at<ObjectId>(y, x);
      if (static_grid_.isOccupied(cell_idx)) continue;
      if (previous_feature->usable() && instance_label == background_label) {
        size_t new_age = age + 1;
        Feature::Ptr feature = constructStaticFeature(
            image_container, kp, new_age, tracklet_id, frame_k);
        if (feature) {
          static_features.add(feature);
          static_grid_.occupancy_[cell_idx] = true;
        }
      }
    }
  }
  // number features tracked with optical flow
  const auto n_optical_flow = static_features.size();
  tracker_info.static_track_optical_flow = n_optical_flow;
  TrackletIdManager& tracked_id_manager = TrackletIdManager::instance();
  if (static_features.size() < min_tracks) {
    // iterate over new observations
    for (size_t i = 0; i < detected_keypoints.size(); i++) {
      if (static_features.size() >= min_tracks) {
        break;
      }
      const KeypointCV& kp_cv = detected_keypoints[i];
      const int& x = kp_cv.pt.x;
      const int& y = kp_cv.pt.y;
      // if not already tracked with optical flow
      if (motion_mask.at<int>(y, x) != background_label) {
        continue;
      }
      Keypoint kp(x, y);
      const size_t cell_idx = static_grid_.getCellIndex(kp);
      if (!static_grid_.isOccupied(cell_idx)) {
        const size_t age = 0;
        size_t tracklet_id = tracked_id_manager.getTrackletIdCount();
        Feature::Ptr feature = constructStaticFeature(image_container, kp, age,
                                                      tracklet_id, frame_k);
        if (feature) {
          tracked_id_manager.incrementTrackletIdCount();
          static_grid_.occupancy_[cell_idx] = true;
          static_features.add(feature);
        }
      }
    }
  }
  static_grid_.reset();
  size_t total_tracks = static_features.size();
  tracker_info.static_track_detections = total_tracks - n_optical_flow;
  return static_features;
}
References dyno::background_label, dyno::FeatureTrackerBase::camera_, constructStaticFeature(), dyno::ImageContainer::frameId(), dyno::OccupandyGrid2D::getCellIndex(), dyno::TrackletIdManager::getTrackletIdCount(), dyno::TrackletIdManager::incrementTrackletIdCount(), dyno::TrackletIdManager::instance(), dyno::OccupandyGrid2D::isOccupied(), dyno::TrackerParams::max_features_per_frame, dyno::ImageContainer::objectMotionMask(), dyno::OccupandyGrid2D::occupancy_, dyno::FeatureTrackerBase::params_, dyno::OccupandyGrid2D::reset(), dyno::ImageContainer::rgb(), static_grid_, dyno::FeatureTrackerInfo::static_track_detections, dyno::FeatureTrackerInfo::static_track_optical_flow, dyno::ImageType::RGBMono::toMono(), dyno::ImageWrapper< IMAGETYPE >::toRGB(), dyno::functional_keypoint::u(), and dyno::functional_keypoint::v().
Member Data Documentation
orb_detector_
ORBextractor::UniquePtr dyno::ExternalFlowFeatureTracker::orb_detector_ {nullptr} private
Grid used to feature bin static features.
Definition at line 98 of file StaticFeatureTracker.hpp.
Referenced by ExternalFlowFeatureTracker().
static_cell_size
const size_t dyno::ExternalFlowFeatureTracker::static_cell_size private
Initial value:
=
      15
Definition at line 100 of file StaticFeatureTracker.hpp.
static_grid_
OccupandyGrid2D dyno::ExternalFlowFeatureTracker::static_grid_ private
Definition at line 97 of file StaticFeatureTracker.hpp.
Referenced by trackStatic().
The documentation for this class was generated from the following files:
dynosam/include/dynosam/frontend/vision/StaticFeatureTracker.hpp
dynosam/src/frontend/vision/StaticFeatureTracker.cc