DynoSAM: dynosam_ros/nodes/dataset_node.cc File Reference
dataset_node.cc File Reference
#include <cv_bridge/cv_bridge.h>
#include <gflags/gflags.h>
#include <glog/logging.h>
#include <dynosam/common/Camera.hpp>
#include <dynosam/dataprovider/KittiDataProvider.hpp>
#include <dynosam/dataprovider/OMDDataProvider.hpp>
#include <dynosam/frontend/vision/FeatureTracker.hpp>
#include <dynosam/frontend/vision/VisionTools.hpp>
#include <dynosam/utils/OpenCVUtils.hpp>
#include "dynosam_ros/Utils.hpp"
#include "image_transport/image_transport.hpp"
#include "rclcpp/executor.hpp"
#include "rclcpp/node.hpp"
#include "rclcpp/node_options.hpp"
#include "rclcpp/rclcpp.hpp"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 49 of file dataset_node.cc.
{
  using namespace dyno;
  auto non_ros_args = dyno::initRosAndLogging(argc, argv);
  rclcpp::NodeOptions options;
  options.arguments(non_ros_args);
  options.use_intra_process_comms(true);
  auto node =
      std::make_shared<rclcpp::Node>("dynosam_dataset_example", options);
  image_transport::Publisher input_images_pub =
      image_transport::create_publisher(node.get(),
                                        "dynosam_dataset/input_images");
  image_transport::Publisher tracking_images_pub =
      image_transport::create_publisher(node.get(),
                                        "dynosam_dataset/tracking_image");
  // KittiDataLoader::Params params;
  // KittiDataLoader loader("/root/data/vdo_slam/kitti/kitti/0004/", params);
  OMDDataLoader loader(
      "/root/data/vdo_slam/omd/omd/swinging_4_unconstrained_stereo/");
  auto camera = std::make_shared<Camera>(*loader.getCameraParams());
  auto tracker = std::make_shared<FeatureTracker>(FrontendParams(), camera);
  loader.setCallback([&](dyno::FrameId frame_id, dyno::Timestamp timestamp,
                         cv::Mat rgb, cv::Mat optical_flow, cv::Mat depth,
                         cv::Mat motion, GroundTruthInputPacket) -> bool {
    // loader.setCallback([&](dyno::FrameId frame_id, dyno::Timestamp timestamp,
    //     cv::Mat rgb, cv::Mat optical_flow, cv::Mat depth, cv::Mat motion,
    //     gtsam::Pose3, GroundTruthInputPacket) -> bool {
    LOG(INFO) << frame_id << " " << timestamp;
    cv::Mat flow_viz, mask_viz, depth_viz;
    flow_viz = ImageType::OpticalFlow::toRGB(optical_flow);
    mask_viz = ImageType::MotionMask::toRGB(motion);
    depth_viz = ImageType::Depth::toRGB(depth);
    ImageContainer::Ptr container = ImageContainer::Create(
        timestamp, frame_id, ImageWrapper<ImageType::RGBMono>(rgb),
        ImageWrapper<ImageType::Depth>(depth),
        ImageWrapper<ImageType::OpticalFlow>(optical_flow),
        ImageWrapper<ImageType::MotionMask>(motion));
    auto frame = tracker->track(frame_id, timestamp, *container);
    Frame::Ptr previous_frame = tracker->getPreviousFrame();
    cv::Mat tracking;
    if (previous_frame) {
      tracking = tracker->computeImageTracks(*previous_frame, *frame, false);
      std_msgs::msg::Header hdr;
      sensor_msgs::msg::Image::SharedPtr msg =
          cv_bridge::CvImage(hdr, "bgr8", tracking).toImageMsg();
      tracking_images_pub.publish(msg);
    }
    cv::Mat combined_image = utils::concatenateImagesVertically(
        utils::concatenateImagesHorizontally(rgb, depth_viz),
        utils::concatenateImagesHorizontally(flow_viz, mask_viz));
    std_msgs::msg::Header hdr;
    sensor_msgs::msg::Image::SharedPtr msg =
        cv_bridge::CvImage(hdr, "bgr8", combined_image).toImageMsg();
    input_images_pub.publish(msg);
    return true;
  });
  rclcpp::executors::SingleThreadedExecutor exec;
  exec.add_node(node);
  while (rclcpp::ok()) {
    if (!loader.spin()) {
      break;
    }
    exec.spin_some();
  }
}
References dyno::OMDDataLoader::getCameraParams(), dyno::initRosAndLogging(), dyno::_DynoDatasetConstructor< DynoDataTypes >::setCallback(), and dyno::DynoDatasetProvider< DataTypes >::spin().