DynoSAM: dynosam/example/dyno_sam.cc File Reference
dyno_sam.cc File Reference
#include <gflags/gflags.h>
#include <glog/logging.h>
#include <Eigen/Dense>
#include <png++/png.hpp>
#include "dynosam/dataprovider/ClusterSlamDataProvider.hpp"
#include "dynosam/dataprovider/KittiDataProvider.hpp"
#include "dynosam/dataprovider/TartanAirShibuya.hpp"
#include "dynosam/dataprovider/ViodeDataProvider.hpp"
#include "dynosam/dataprovider/VirtualKittiDataProvider.hpp"
#include "dynosam/frontend/vision/FeatureTracker.hpp"
#include "dynosam/frontend/vision/Frame.hpp"
#include "dynosam/pipeline/PipelineManager.hpp"
#include "dynosam/pipeline/PipelineParams.hpp"
#include "dynosam/visualizer/OpenCVFrontendDisplay.hpp"
#include "dynosam_common/viz/Colour.hpp"
#include "dynosam_cv/Camera.hpp"
#include "dynosam_cv/ImageContainer.hpp"
#include "dynosam_nn/PyObjectDetector.hpp"
#include "dynosam/dataprovider/OMDDataProvider.hpp"
#include "dynosam/frontend/vision/VisionTools.hpp"
Functions
DEFINE_string (path_to_kitti, "/root/data/kitti", "Path to KITTI dataset")
DEFINE_string (params_folder_path, "dynosam/params", "Path to the folder containing the yaml files with the VIO parameters.")
int main (int argc, char *argv[])
Function Documentation
DEFINE_string() [1/2]
DEFINE_string (params_folder_path , "dynosam/params" , "Path to the folder containing the yaml files with the VIO parameters.")
DEFINE_string() [2/2]
DEFINE_string (path_to_kitti , "/root/data/kitti" , "Path to KITTI dataset")
main()
int main (int argc, char * argv[])
Definition at line 62 of file dyno_sam.cc.
{
  using namespace dyno;
  google::ParseCommandLineFlags(&argc, &argv, true);
  google::InitGoogleLogging(argv[0]);
  FLAGS_logtostderr = 1;
  FLAGS_colorlogtostderr = 1;
  FLAGS_log_prefix = 1;
  FLAGS_v = 30;
  KittiDataLoader::Params params;
  KittiDataLoader loader("/root/data/vdo_slam/kitti/kitti/0004/", params);
  // ClusterSlamDataLoader loader("/root/data/cluster_slam/CARLA-S2");
  // loader.setStartingFrame(600);
  // OMDDataLoader loader(
  //     "/root/data/vdo_slam/omd/omd/swinging_4_unconstrained_stereo/");
  // TartanAirShibuyaLoader
  // loader("/root/data/TartanAir_shibuya/RoadCrossing07/");
  // ViodeLoader loader("/root/data/VIODE/city_day/mid");
  // auto detector = dyno::PyObjectDetectorWrapper::CreateYoloDetector();
  // CHECK_NOTNULL(detector);
  FrontendParams fp;
  fp.tracker_params.feature_detector_type =
      TrackerParams::FeatureDetectorType::GFFT_CUDA;
  fp.tracker_params.max_dynamic_features_per_frame = 300;
  fp.tracker_params.prefer_provided_optical_flow = false;
  fp.tracker_params.prefer_provided_object_detection = false;
  // fp.tracker_params.feature_detector_type =
  // TrackerParams::FeatureDetectorType::ORB_SLAM_ORB;
  auto camera = std::make_shared<Camera>(*loader.getCameraParams());
  auto tracker = std::make_shared<FeatureTracker>(fp, camera);
  loader.setCallback([&](dyno::FrameId frame_id, dyno::Timestamp timestamp,
                         cv::Mat rgb, cv::Mat optical_flow, cv::Mat depth,
                         cv::Mat motion, gtsam::Pose3,
                         GroundTruthInputPacket) -> bool {
    // LOG(INFO) << utils::Statistics::Print();
    // loader.setCallback([&](dyno::FrameId frame_id, dyno::Timestamp timestamp,
    //                        cv::Mat rgb, cv::Mat optical_flow, cv::Mat depth,
    //                        cv::Mat motion, GroundTruthInputPacket,
    //                        std::optional<ImuMeasurements> imu_measurements,
    //                        std::optional<cv::Mat>) -> bool {
    // loader.setCallback([&](dyno::FrameId frame_id, dyno::Timestamp timestamp,
    //                        cv::Mat rgb, cv::Mat optical_flow, cv::Mat depth,
    //                        cv::Mat motion, GroundTruthInputPacket,
    //                        std::optional<cv::Mat>) -> bool {
    LOG(INFO) << frame_id << " " << timestamp;
    cv::Mat of_viz, motion_viz, depth_viz;
    of_viz = ImageType::OpticalFlow::toRGB(optical_flow);
    motion_viz = ImageType::MotionMask::toRGB(motion);
    depth_viz = ImageType::Depth::toRGB(depth);
    // ImageContainerDeprecate::Ptr container = ImageContainerDeprecate::Create(
    //     timestamp, frame_id, ImageWrapper<ImageType::RGBMono>(rgb),
    //     ImageWrapper<ImageType::Depth>(depth),
    //     ImageWrapper<ImageType::OpticalFlow>(optical_flow),
    //     ImageWrapper<ImageType::MotionMask>(motion));
    // cv::Mat boarder_mask;
    // vision_tools::computeObjectMaskBoundaryMask(
    //     motion,
    //     boarder_mask,
    //     8
    // );
    // cv::Scalar red = dyno::Color::red();
    // const ObjectIds instance_labels = vision_tools::getObjectLabels(motion);
    // for(const auto object_id : instance_labels) {
    //     std::vector<std::vector<cv::Point>> detected_contours;
    //     vision_tools::findObjectBoundingBox(motion,
    //     object_id,detected_contours);
    //     cv::drawContours(boarder_mask, detected_contours, -1, red, 8);
    // }
    // cv::imshow("Mask with boarder", boarder_mask);
    // cv::imshow("RGB", rgb);
    // cv::imshow("OF", of_viz);
    // cv::imshow("Motion", motion_viz);
    // // cv::waitKey(1);
    // cv::imshow("Depth", depth_viz);
    // auto object_detection_result = detector->process(rgb);
    // cv::imshow("Detection Result", object_detection_result.colouredMask());
    ImageContainer image_container(frame_id, timestamp);
    image_container.rgb(rgb)
        .depth(depth)
        .opticalFlow(optical_flow)
        .objectMotionMask(motion);
    // image_container.rgb(rgb).depth(depth).opticalFlow(optical_flow);
    auto frame = tracker->track(frame_id, timestamp, image_container);
    Frame::Ptr previous_frame = tracker->getPreviousFrame();
    // if(frame_id == 605) {
    //   auto all_tracks = frame->static_features_.collectTracklets();
    //   frame->static_features_.markOutliers(all_tracks);
    // }
    // // motion_viz =
    // ImageType::MotionMask::toRGB(frame->image_container_.get<ImageType::MotionMask>());
    // // // cv::imshow("Motion", motion_viz);
    cv::Mat tracking;
    if (previous_frame) {
      ImageTracksParams track_viz_params(true);
      track_viz_params.show_intermediate_tracking = true;
      tracking = tracker->computeImageTracks(*previous_frame, *frame,
                                             track_viz_params);
      // if (imu_measurements) {
      //   const auto previous_timestamp = previous_frame->getTimestamp();
      //   CHECK_GE(imu_measurements->timestamps_[0], previous_timestamp);
      //   CHECK_LT(imu_measurements
      //                ->timestamps_[imu_measurements->timestamps_.cols() - 1],
      //            timestamp);
      //   LOG(INFO) << "Gotten imu messages!";
      //   CHECK(imu_measurements->synchronised_frame_id);
      //   CHECK_EQ(imu_measurements->synchronised_frame_id.value(),
      //            frame->getFrameId());
      // }
    }
    if (!tracking.empty()) cv::imshow("Tracking", tracking);
    LOG(INFO) << to_string(tracker->getTrackerInfo());
    const std::string path = "/root/results/misc/";
    // if (previous_frame && (char)cv::waitKey(0) == 's') {
    //   LOG(INFO) << "Saving...";
    //   // cv::imwrite(path + "omd_su4_rgb.png", rgb);
    //   // cv::imwrite(path + "omd_su4_of.png", of_viz);
    //   // cv::imwrite(path + "omd_su4_motion.png", motion_viz);
    //   // cv::imwrite(path + "omd_su4_depth.png", depth_viz);
    //   // cv::imwrite(
    //   //     path + "cluster_tracking_new" + std::to_string(frame_id) +
    //   ".png",
    //   //     tracking);
    // }
    cv::waitKey(1);
    return true;
  });
  while (loader.spin()) {
  }
}
References dyno::TrackerParams::feature_detector_type, dyno::KittiDataLoader::getCameraParams(), dyno::TrackerParams::max_dynamic_features_per_frame, dyno::TrackerParams::prefer_provided_object_detection, dyno::TrackerParams::prefer_provided_optical_flow, dyno::ImageContainer::rgb(), dyno::_DynoDatasetConstructor< DynoDataTypes >::setCallback(), dyno::ImageTracksParams::show_intermediate_tracking, dyno::DynoDatasetProvider< DataTypes >::spin(), and dyno::FrontendParams::tracker_params.