DynoSAM: dynosam_utils/misc/KittiSemaniticToMotion.cc File Reference
KittiSemaniticToMotion.cc File Reference
#include <dynosam/dataprovider/KittiDataProvider.hpp>
#include <dynosam/common/GroundTruthPacket.hpp>
#include <gtsam/geometry/Pose3.h>
#include <opencv4/opencv2/core.hpp>
#include <glog/logging.h>
#include <ostream>
#include <iostream>
#include <fstream>
Functions
std::vector< int > findMovingObject (const GroundTruthInputPacket &prev_packet_vector, const GroundTruthInputPacket &curr_packet_vector, double tol_m=0.4)
cv::Mat constructMotionMask (const cv::Mat &instance_mask, const std::vector< int > &moving_labels)
void writeMask (const std::string &path, const cv::Mat &motion_mask)
int main (int argc, char *argv[])
Function Documentation
constructMotionMask()
cv::Mat constructMotionMask (const cv::Mat & instance_mask, const std::vector< int > & moving_labels)
Definition at line 76 of file KittiSemaniticToMotion.cc.
{
    cv::Mat motion_mask;
    instance_mask.copyTo(motion_mask);
    for (int i = 0; i < motion_mask.rows; i++)
    {
        for (int j = 0; j < motion_mask.cols; j++)
        {
            int label = motion_mask.at<int>(i, j);
            if(label == 0) {
                continue;
            }
            //check if label is in moving labels. if not, make zero!
            auto it = std::find(moving_labels.begin(), moving_labels.end(), label);
            if(it == moving_labels.end()) {
                motion_mask.at<int>(i, j) = 0;
            }
        }
    }
    return motion_mask;
}
Referenced by main().
findMovingObject()
std::vector< int > findMovingObject (const GroundTruthInputPacket & prev_packet_vector, const GroundTruthInputPacket & curr_packet_vector, double tol_m = 0.4)
Definition at line 39 of file KittiSemaniticToMotion.cc.
{
    //find object in previous
    std::vector<int> moving_labels;
    for(const ObjectPoseGT& object_pose_gt : curr_packet_vector.object_poses_) {
        const ObjectId object_id = object_pose_gt.object_id_;
         auto it = std::find_if(prev_packet_vector.object_poses_.begin(), prev_packet_vector.object_poses_.end(),
                           [=](const ObjectPoseGT& gt_object) { return gt_object.object_id_ == object_id; });
        if(it == prev_packet_vector.object_poses_.end()) {
            continue;
        }
        const ObjectPoseGT& object_pose_gt_in_previous = *it;
        const gtsam::Pose3 prev_L_world = prev_packet_vector.X_world_ * object_pose_gt_in_previous.L_camera_;
        const gtsam::Pose3 curr_L_world = curr_packet_vector.X_world_ * object_pose_gt.L_camera_;
        gtsam::Vector3 t_diff = curr_L_world.translation() - prev_L_world.translation();
        // const gtsam::Pose3 pose_diff = prev_L_world.inverse() * curr_L_world;
        // const gtsam::Point3& translation_error = pose_diff.translation();
        // L2 norm - ie. magnitude
        double t_error = t_diff.norm();
        if(t_error > tol_m) {
            LOG(INFO) << "Object " << object_id << " is moving!";
            moving_labels.push_back(object_id);
        }
        else {
            LOG(INFO) << "Object " << object_id << " is NOT moving!";
        }
    }
    return moving_labels;
}
References dyno::ObjectPoseGT::L_camera_, dyno::ObjectPoseGT::object_id_, dyno::GroundTruthInputPacket::object_poses_, and dyno::GroundTruthInputPacket::X_world_.
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 118 of file KittiSemaniticToMotion.cc.
{
    google::ParseCommandLineFlags(&argc, &argv, true);
    google::InitGoogleLogging(argv[0]);
    FLAGS_logtostderr = 1;
    FLAGS_colorlogtostderr = 1;
    FLAGS_log_prefix = 1;
    GroundTruthInputPacket prev_packet_vector;
    GroundTruthInputPacket curr_packet_vector;
    cv::Mat mask_cur;
    cv::Mat rgb_cur;
    const std::string path = "/root/data/vdo_slam/kitti/kitti/0020";
    //becuase this uses the KittiDataLoader, this will use whatever semantic/instance laoder is in
    KittiDataLoader::Params params;
    params.base_line = 0; //dont care
    params.depth_scale_factor = 0;
    params.mask_type = MaskType::SEMANTIC_INSTANCE;
    KittiDataLoader loader(path, params);
    size_t index = 0;
    auto callback = [&](size_t,
            Timestamp timestamp,
            cv::Mat rgb,
            cv::Mat,
            cv::Mat,
            cv::Mat instance_mask,
            gtsam::Pose3 camera_pose_gt,
            GroundTruthInputPacket gt_object_pose_gt) -> bool
        {
            CHECK(camera_pose_gt.equals(gt_object_pose_gt.X_world_));
            CHECK(timestamp == gt_object_pose_gt.timestamp_);
            // //start with all background
            // cv::Mat motion_mask = cv::Mat(instance_mask.size(), instance_mask.type(), 0);
            cv::Mat motion_mask = instance_mask;
            std::stringstream ss;
            ss << std::setfill('0') << std::setw(6) << index;
            const std::string file_path = path + "/motion/" + ss.str() + ".txt";
            if(index != 0) {
                mask_cur = instance_mask;
                rgb_cur = rgb;
                std::vector<int> moving_labels = findMovingObject(prev_packet_vector, gt_object_pose_gt,0.2);
                motion_mask = constructMotionMask(instance_mask, moving_labels);
                cv::Mat motion_mask_viz = utils::labelMaskToRGB(motion_mask, background_label, rgb_cur);
                cv::Mat instance_mask_viz = utils::labelMaskToRGB(instance_mask, background_label, rgb_cur);
                // cv::Mat disp = utils::concatenateImagesVertically(instance_mask_viz, motion_mask_viz);
                // cv::imshow("Masks", disp);
                // cv::waitKey(1);
            }
            LOG(INFO) << "Writing file to " << file_path;
            writeMask(file_path, motion_mask);
            index++;
            prev_packet_vector = gt_object_pose_gt;
            return true;
        };
    loader.setCallback(callback);
    while(loader.spin()) {}
}
References dyno::background_label, dyno::KittiDataLoader::Params::base_line, constructMotionMask(), dyno::KittiDataLoader::Params::depth_scale_factor, findMovingObject(), dyno::utils::labelMaskToRGB(), dyno::KittiDataLoader::Params::mask_type, dyno::_DynoDatasetConstructor< DynoDataTypes >::setCallback(), dyno::DynoDatasetProvider< DataTypes >::spin(), and writeMask().
writeMask()
void writeMask (const std::string & path, const cv::Mat & motion_mask)
Definition at line 100 of file KittiSemaniticToMotion.cc.
{
    std::ofstream file;
    file.open(path);
    for (int i = 0; i < motion_mask.rows; i++)
    {
        for (int j = 0; j < motion_mask.cols; j++)
        {
            int label = motion_mask.at<int>(i, j);
            file << std::to_string(label) << " ";
        }
        file << '\n';
    }
    file.close();
}
Referenced by main().