DynoSAM: dyno::internal Namespace Reference
dyno::internal Namespace Reference
Vector of feature pairs.
Classes
struct Apply
struct Apply< 0 >
struct ApplyMember
struct ApplyMember< 0 >
struct CppParameterType
Type trait to retrieve a.
struct EnableBitMaskOperators
struct EnableBitMaskOperators< RuntimeSensorOptions >
struct filter_iterator_base
struct filter_iterator_detail
struct fixed_lag_smoother_traits
struct generate_tuple_type
struct generate_tuple_type< T, 0 >
struct generate_tuple_type< T, 1 >
struct HasChildFrame
struct HasChildFrame< Msg, decltype((void) Msg::child_frame_id, 0)>
struct HasMsgHeader
struct HasMsgHeader< Msg, decltype((void) Msg::header, 0)>
struct HungarianAlgorithm
struct is_one_of
struct is_one_of< T, FrontVariant, RestVariants... >
struct is_variant
struct is_variant< std::variant< Variants... > >
struct is_variant_member
struct is_variant_member< T, std::variant< Variants... > >
struct isam2_like_traits
iOptimizationTraits for something that looks exactly like ISAM2 Really only exists becuase we have a custom dyno::ISAM2 class
struct join_tuples
struct join_tuples< std::tuple< LEFT... >, std::tuple< RIGHT... > >
struct repeat_type
struct RosParameterType
class StaticFormulationUpdater
class StaticFormulationUpdaterImpl
Base class helper for the static formulation updater. This forms the basis for "regular" Visual SLAM and creates factors between static points and camera poses.
struct tuple_element_index
struct tuple_element_index_helper
struct tuple_element_index_helper< T, std::tuple< First, Rest... > >
struct tuple_element_index_helper< T, std::tuple< T, Rest... > >
struct tuple_element_index_helper< T, std::tuple<> >
struct tuple_to_types
struct tuple_to_types< std::tuple< Ts... > >
struct type_identity
Typedefs
template<typename Container >
using filter_iterator = filter_iterator_base< Container, typename Container::iterator >
template<typename Container >
using filter_const_iterator = filter_iterator_base< Container, typename Container::const_iterator >
template<std::size_t N, typename... Ts>
using select_nth = std::tuple_element_t< N, std::tuple< Ts... > >
template<typename Iter >
using is_feature_ptr_iterator = std::is_same< Feature::Ptr, typename Iter::value_type >
Alias for checking if the parsed iterator has a value_type equivalent to Feature::Ptr, in other words, that the template iterates over Feature Ptr's.
template<typename Iter >
using enable_if_feature_ptr_iterator = typename std::enable_if< is_feature_ptr_iterator< Iter >::value, void >::type
template<class T >
using type_identity_t = typename type_identity< T >::type
Functions
template<typename INPUT >
std::pair< Timestamp, FrameId > collectTemporalData (const INPUT &)
template<>
std::pair< Timestamp, FrameId > collectTemporalData (const VisionImuPacket &input)
template<>
std::pair< Timestamp, FrameId > collectTemporalData (const BackendOutputPacket &input)
template<typename E >
constexpr std::enable_if_t< EnableBitMaskOperators< E >::value, E > operator| (E lhs, E rhs)
template<typename E >
constexpr std::enable_if_t< EnableBitMaskOperators< E >::value, E > operator& (E lhs, E rhs)
template<typename E >
constexpr std::enable_if_t< EnableBitMaskOperators< E >::value, E > operator~ (E e)
template<class Function , std::size_t... Is>
auto index_apply_impl (Function f, std::index_sequence< Is... >)
template<std::size_t N, class Function >
auto index_apply (Function f)
template<class Function , std::size_t... Is>
void for_each_apply_impl (Function f, std::index_sequence< Is... >)
template<std::size_t N, class Function >
void for_each_apply (Function f)
template<std::size_t N, class Function >
void select_apply (std::size_t i, Function f)
template<typename F , typename T >
auto apply (F &&f, T &&t)
template<typename C , typename F , typename T >
auto apply (C &&c, F &&f, T &&t) -> decltype(ApplyMember< std::tuple_size< typename std::decay< T >::type >::value >::apply(forward< C >(c), forward< F >(f), forward< T >(t)))
template<typename U , typename... T>
constexpr bool contains (std::tuple< T... >)
static void optimizeInPlace (const ISAM2::sharedClique &clique, VectorValues *result)
void updateRgProd (const ISAM2::sharedClique &clique, const gtsam::KeySet &replacedKeys, const gtsam::VectorValues &grad, gtsam::VectorValues *RgProd, size_t *varsUpdated)
Variables
template<typename U , typename Tuple >
constexpr bool tuple_contains_type = contains<U>(std::declval<Tuple>())
template<typename T , typename Tuple >
constexpr std::size_t tuple_element_index_v
Actual templated class to determine the index of a type in a tuple It asks the helper to do the work and validates that the resulting value is less than the size of the tuple, meaning that the type was found. If not, then we complain with a compile-time assertion.
Detailed Description
Vector of feature pairs.
Typedef Documentation
enable_if_feature_ptr_iterator
template<typename Iter > using dyno::internal::enable_if_feature_ptr_iterator = typedef typename std::enable_if<is_feature_ptr_iterator<Iter>::value, void>::type
Definition at line 427 of file Feature.hpp.
filter_const_iterator
template<typename Container > using dyno::internal::filter_const_iterator = typedef filter_iterator_base<Container, typename Container::const_iterator>
Definition at line 186 of file StructuredContainers.hpp.
filter_iterator
template<typename Container > using dyno::internal::filter_iterator = typedef filter_iterator_base<Container, typename Container::iterator>
Definition at line 182 of file StructuredContainers.hpp.
is_feature_ptr_iterator
template<typename Iter > using dyno::internal::is_feature_ptr_iterator = typedef std::is_same<Feature::Ptr, typename Iter::value_type>
Alias for checking if the parsed iterator has a value_type equivalent to Feature::Ptr, in other words, that the template iterates over Feature Ptr's.
Template Parameters
Iter
Definition at line 423 of file Feature.hpp.
select_nth
template<std::size_t N, typename... Ts> using dyno::internal::select_nth = typedef std::tuple_element_t<N, std::tuple<Ts...> >
Definition at line 58 of file Tuple.hpp.
type_identity_t
template<class T > using dyno::internal::type_identity_t = typedef typename type_identity<T>::type
Definition at line 82 of file RosUtils.hpp.
Function Documentation
apply() [1/2]
template<typename C , typename F , typename T > auto dyno::internal::apply (C && c, F && f, T && t) -> decltype(ApplyMember<std::tuple_size<typename std::decay<T>::type>:: value>::apply(forward<C>(c), forward<F>(f), forward<T>(t))) inline
Definition at line 140 of file Tuple.hpp.
{
  return ApplyMember<std::tuple_size<typename std::decay<T>::type>::value>::
      apply(forward<C>(c), forward<F>(f), forward<T>(t));
}
References apply().
apply() [2/2]
template<typename F , typename T > auto dyno::internal::apply (F && f, T && t) inline
Definition at line 107 of file Tuple.hpp.
{
  return Apply<::std::tuple_size<::std::decay_t<T>>::value>::apply(
      ::std::forward<F>(f), ::std::forward<T>(t));
}
References apply().
Referenced by apply().
collectTemporalData() [1/3]
template<> std::pair< Timestamp, FrameId > dyno::internal::collectTemporalData (const BackendOutputPacket & input) inline
Definition at line 51 of file Display.hpp.
{
  return {input.timestamp, input.frame_id};
}
References dyno::BackendOutputPacket::frame_id, and dyno::BackendOutputPacket::timestamp.
collectTemporalData() [2/3]
template<typename INPUT > std::pair< Timestamp, FrameId > dyno::internal::collectTemporalData (const INPUT &)
collectTemporalData() [3/3]
template<> std::pair< Timestamp, FrameId > dyno::internal::collectTemporalData (const VisionImuPacket & input) inline
Definition at line 45 of file Display.hpp.
{
  return {input.timestamp(), input.frameId()};
}
References dyno::VisionImuPacket::frameId(), and dyno::VisionImuPacket::timestamp().
contains()
template<typename U , typename... T> constexpr bool dyno::internal::contains (std::tuple< T... >) constexpr
Definition at line 149 of file Tuple.hpp.
{
  return (std::is_same_v<U, T> || ...);
}
for_each_apply()
template<std::size_t N, class Function > void dyno::internal::for_each_apply (Function f)
Definition at line 77 of file Tuple.hpp.
{
  for_each_apply_impl(f, std::make_index_sequence<N>{});
}
References for_each_apply_impl().
for_each_apply_impl()
template<class Function , std::size_t... Is> void dyno::internal::for_each_apply_impl (Function f, std::index_sequence< Is... >)
Definition at line 71 of file Tuple.hpp.
{
  (void)std::initializer_list<int>{
      (f(std::integral_constant<std::size_t, Is>{}), void(), 0)...};
}
Referenced by for_each_apply().
index_apply()
template<std::size_t N, class Function > auto dyno::internal::index_apply (Function f)
Definition at line 66 of file Tuple.hpp.
{
  return index_apply_impl(f, std::make_index_sequence<N>{});
}
References index_apply_impl().
index_apply_impl()
template<class Function , std::size_t... Is> auto dyno::internal::index_apply_impl (Function f, std::index_sequence< Is... >)
Definition at line 61 of file Tuple.hpp.
{
  return f(std::integral_constant<std::size_t, Is>{}...);
}
Referenced by index_apply().
operator&()
template<typename E > constexpr std::enable_if_t< EnableBitMaskOperators< E >::value, E > dyno::internal::operator& (E lhs, E rhs) constexpr
Definition at line 52 of file Types-inl.hpp.
                  {
  using U = std::underlying_type_t<E>;
  return static_cast<E>(static_cast<U>(lhs) & static_cast<U>(rhs));
}
References operator&().
Referenced by operator&().
operator|()
template<typename E > constexpr std::enable_if_t< EnableBitMaskOperators< E >::value, E > dyno::internal::operator| (E lhs, E rhs) constexpr
Definition at line 45 of file Types-inl.hpp.
                  {
  using U = std::underlying_type_t<E>;
  return static_cast<E>(static_cast<U>(lhs) | static_cast<U>(rhs));
}
References operator|().
Referenced by operator|().
operator~()
template<typename E > constexpr std::enable_if_t< EnableBitMaskOperators< E >::value, E > dyno::internal::operator~ (E e) constexpr
Definition at line 59 of file Types-inl.hpp.
{
  using U = std::underlying_type_t<E>;
  return static_cast<E>(~static_cast<U>(e));
}
References operator~().
Referenced by operator~().
optimizeInPlace()
static void dyno::internal::optimizeInPlace (const ISAM2::sharedClique & clique, VectorValues * result) inline static
Definition at line 49 of file ISAM2-impl.cc.
{
  // parents are assumed to already be solved and available in result
  result->update(clique->conditional()->solve(*result));
  // starting from the root, call optimize on each conditional
  for (const ISAM2::sharedClique& child : clique->children)
    optimizeInPlace(child, result);
}
References optimizeInPlace().
Referenced by optimizeInPlace(), and dyno::DeltaImpl::UpdateGaussNewtonDelta().
select_apply()
template<std::size_t N, class Function > void dyno::internal::select_apply (std::size_t i, Function f)
Definition at line 82 of file Tuple.hpp.
{
  for_each_apply<N>([&](auto&& Is) {
    if (Is == i) f(std::forward<decltype(Is)>(Is));
  });
}
updateRgProd()
void dyno::internal::updateRgProd (const ISAM2::sharedClique & clique, const gtsam::KeySet & replacedKeys, const gtsam::VectorValues & grad, gtsam::VectorValues * RgProd, size_t * varsUpdated)
Definition at line 92 of file ISAM2-impl.cc.
{
  // Check if any frontal or separator keys were recalculated, if so, we need
  // update deltas and recurse to children, but if not, we do not need to
  // recurse further because of the running separator property.
  bool anyReplaced = false;
  for (gtsam::Key j : *clique->conditional()) {
    if (replacedKeys.exists(j)) {
      anyReplaced = true;
      break;
    }
  }
  if (anyReplaced) {
    // Update the current variable
    // Get VectorValues slice corresponding to current variables
    gtsam::Vector gR =
        grad.vector(KeyVector(clique->conditional()->beginFrontals(),
                              clique->conditional()->endFrontals()));
    gtsam::Vector gS =
        grad.vector(KeyVector(clique->conditional()->beginParents(),
                              clique->conditional()->endParents()));
    // Compute R*g and S*g for this clique
    gtsam::Vector RSgProd =
        clique->conditional()->R() * gR + clique->conditional()->S() * gS;
    // Write into RgProd vector
    gtsam::DenseIndex vectorPosition = 0;
    for (gtsam::Key frontal : clique->conditional()->frontals()) {
      gtsam::Vector& RgProdValue = (*RgProd)[frontal];
      RgProdValue = RSgProd.segment(vectorPosition, RgProdValue.size());
      vectorPosition += RgProdValue.size();
    }
    // Now solve the part of the Newton's method point for this clique
    // (back-substitution)
    // (*clique)->solveInPlace(deltaNewton);
    *varsUpdated += clique->conditional()->nrFrontals();
    // Recurse to children
    for (const ISAM2::sharedClique& child : clique->children) {
      updateRgProd(child, replacedKeys, grad, RgProd, varsUpdated);
    }
  }
}
References updateRgProd().
Referenced by dyno::DeltaImpl::UpdateRgProd(), and updateRgProd().
Variable Documentation
tuple_contains_type
template<typename U , typename Tuple > constexpr bool dyno::internal::tuple_contains_type = contains<U>(std::declval<Tuple>()) inline constexpr
Definition at line 154 of file Tuple.hpp.
tuple_element_index_v
template<typename T , typename Tuple > constexpr std::size_t dyno::internal::tuple_element_index_v inline constexpr
Initial value:
=
    tuple_element_index<T, Tuple>::value
Actual templated class to determine the index of a type in a tuple It asks the helper to do the work and validates that the resulting value is less than the size of the tuple, meaning that the type was found. If not, then we complain with a compile-time assertion.
Template Parameters
T
Tuple
Definition at line 236 of file Tuple.hpp.