DynoSAM: dyno Namespace Reference
dyno Namespace Reference
Namespaces
namespace factor_graph_tools
namespace internal
Vector of feature pairs.
namespace test_hybrid
namespace utils
namespace vision_tools
Classes
struct _DynoDatasetConstructor
struct _floating_point_colour_traits
struct _int_point_colour_traits
class Accessor
Accessor defines the interface between the structured output of a BackendModule and any formulation used to construct the Dynamic SLAM problem.
class AccessorT
Derived Accessor that knows about the MAP used with the formulation. The class will inherit from DerivedAccessor (which must itself be an Accessor), which allows this class to act as an Acessor. The DerivedAccessor class allows additional functionality to be added to the accessor beyond the base functionality (i.e. the virtual functions provided by Accessor) while still being an accessor.
class AdaptiveNonMaximumSuppression
class AllImagesOnlineProviderRos
Class that subscribes to rgb, depth, motion mask and dense optical flow topics.
class ApplyFunctionalSymbol
Helper class that allows functional callbacks to be triggered based on the type of gtsam::Key provided, where the key should refer to a valid type within the DynoSAM ecosystem.
class BackendDSDRos
class BackendExperimentsNode
class BackendFactory
Factory to create the backend module and associated formulations. This class is quite complex due to the interdepencies between backend and formulations.
class BackendFormulationFactory
class BackendInbuiltDisplayRos
class BackendLogger
struct BackendMetaData
class BackendModule
Base class to actually do processing. Data passed to this module from the frontend.
class BackendModuleDisplay
Vizualisation class that can be associated with a BackendModule/formulation to allow custom vizualistions for the specifics of the BackendModule/formulation in addition to the standard frontend/backend output.
class BackendModuleDisplayRos
struct BackendModuleDisplayTraits
struct BackendModuleDisplayTraits< ParallelHybridBackendModule >
Register ParalleHybridModuleDisplay as the acting backend display for the Factory policy.
struct BackendModuleDisplayTraits< RegularHybridFormulation >
Register RegularHybridFormulationDisplay as the acting backend display for the Factory policy.
class BackendModuleFactory
class BackendModulePolicyRos
Creates a ROS based visualisation policy based on the templated type T which will almost always be a Formulation or some kind of BackendModule (e.g. in the case of ParallelHybrid).
struct BackendModuleTraits
class BackendModuleType
struct BackendOutputPacket
struct BackendParams
struct BackendSpinState
struct BackendWrapper
Wrapper containing the BackendModule, any associated additional visualizer and custom error hooks associated with this backend and (likely) its formulation. Created by the BackendModuleFactory which is the only thing that knows all the details of the particular backend and the formulation used.
struct batch_fixed_lag_traits
Struct that implements the update function (as required by iOptimizationTraits) for the gtsam::BatchFixedLagSmoother.
class BayesTreeMarginalizationHelper
class ByteObjectTracker
struct CallbackTypeHelpers
Helper to define a function definition based on many messages type.
class Camera
class CameraMeasurement
Structure to contain all possible visual measurements from a camera setup including monocular, RGBD and stereo measurements with covariance matrices.
class CameraParams
struct CantorPairingFunction
class ClusterSlamAllLoader
As there is so much interdependancy between the folders in the dataset, we just have the one loader so all the data can be accessed in the same class. This class then provides interfaces for each dyno::DataFolder<....> so that the Dynodataset can use it!
class ClusterSlamDataLoader
Data loader for the cluster slam datasets as provided at: https://huangjh-pub.github.io/page/clusterslam-dataset/.
struct ClusterSlamTimestampLoader
struct Color
struct color_traits
struct color_traits< T, std::enable_if_t< std::is_floating_point< T >::value > >
struct color_traits< T, std::enable_if_t< std::is_integral< T >::value > >
struct ConstSharedModuleInterface
class CsvHeader
class CsvReader
class CsvWriter
struct CudaMemoryAllocator
Allocates and frees GPU (device) memory using cudaMalloc.
class CudaStreamPool
struct CudaTimeGenerator
class DataFolder
Defines a set of datafiles within a folder to be laoded by a dataset (partially inspired by pytorch's dataset class). Each folder exists within a parent folder (defined by the dataset) and contains a number of files that need to be loaded by this class. As a number of different input image types (motion/instance segmenation, with and without depth etc.) exist the class is expected to handle the different types itself and return the loaded type.
class DataFolderStructure
Defines the structure, image and type of different datasets (partially inspired by pytorch's dataset class). Each dataset contains a number of datafolders which defines the data for a particular input. Each datafolder is responsible for loading the file and all must contain the same number of input files (or some equivalent "length") so the data can be packaged together.
class DataInterfacePipeline
Takes data, synchronizes it and sends it to the output queue which should be connected to the frontend User needs to implement InputConstSharedPtr getInputPacket() = 0; that takes data from the internal queues and processes them.
class DataProvider
A data provider is a module that actually gets the inididual image and/or IMU data from some source and packets it into a Frame and IMU form and sends it the the DataInterfacePipeline via callback functions where the data is synchronized and sent to the frontend.
struct DataProviderFactory
class DataProviderRos
Base Dataprovider for ROS that implements common image processing functionalities.
struct DebugImagery
Struct containing debug imagery from the frontend that (optionally) is included in the frontend output.
class DebugInfo
struct DeltaImpl
struct DenseStereoParams
class DepthDataFolder
struct DeviceMemory
Allocates and manages device (GPU) memory using the CudaMemoryAllocator.
class DisplayBase
struct DisplayCommon
Common stateless (free) functions for all ROS displays.
struct DisplayParams
class DisplayPipeline
Generic pipeline for display.
class DSDRos
Shorthand for Dynamic Slam Display ROS.
class DSDTransport
Class for managing the publishing and conversion of ObjectOdometry messages. DSD is shorthand for Dynamic SLAM Display.
class DynamicPointSymbol
class DynoDataset
Specalisation of the generic dataset for the expected dynosam dataset structure.
class DynoDatasetException
class DynoDatasetProvider
class DynoNode
class DynoParams
class DynoPipelineManager
class DynoPipelineManagerRos
struct DynosamException
class EgoMotionSolver
struct ErrorHandlingHooks
class EstimationModuleLogger
class ExternalFlowFeatureTracker
struct ExternalHooks
class ExtractorNode
class FactorGraphManager
class FastMapNodeSet
Data structuring for fast access of map nodes, sorted by their id. We use a set to prevent objects being added multiple times.
class FastUnorderedMap
class Feature
2D tracking and id information for a feature observation at a single frame.
class FeatureContainer
Basic container mapping tracklet id's to a feature (pointer).
class FeatureDetector
Base class for any feature detector.
class FeatureTracker
Feature detector that combines sparse static feature detection and tracking with dense feature detection and tracking on dynamic objects.
class FeatureTrackerBase
struct FeatureTrackerInfo
class Flags
class Formulation
Base class for a formulation that defines the structure and implementation for a factor-graph based Dynamic SLAM solution. Derived formulations construct the specific factor-graph which are solved independandtly to the formulation. The formulation is responsible for the construction of a single factor-graph with a single set of initial values and has an associated Accessor which knows how to extract these values into a common format. In the DynoSAM paper, this is referred to as the \mathbf{O}_k, which is the output of the backend. See Accessor.hpp for more details.
struct FormulationHooks
Defines a set of input hooks to the formulation that allow communication to outside the formulation.
struct FormulationParams
Basic parameters for a Formulation. Right now is just directly the BackendParams since there is lots of cross-over, but later we may add formulation specific ones.
struct FormulationVizWrapper
struct FormulationWrapper
class Frame
class FrameNode
Frame node representing all temporal data at a frame id (k) in the map-graph.
struct FrameRange
struct FrameRangeBase
class FrameRangeData
class FrontendDSDRos
class FrontendInbuiltDisplayRos
struct FrontendInputPacketBase
class FrontendModule
Base class to actually do processing. Data passed to this module from the frontend.
class FrontendOfflinePipeline
module traits of the associated backend...
struct FrontendParams
struct functional_keypoint
class FunctionalDataFolder
class FunctionalDetector
class FunctionalParallelOpenCVMat
class FunctionalSIMOPipelineModule
struct FunctionSignature
class GenericDataset
GenericDataset extends the DataFolderStructure to include functionality such as validation of each folder and implemets the runtime loading (per index) of each datafolder, updating the internal data structures containing the actual data.
class GenericObjectCentricMap
Generic mapping of Object Id to FrameId to VALUE within a nested gtsam::FastMap structure. This is a common datastrcture used to store temporal information about each object.
class GenericTrackedStatusVector
class GenericVirtualKittiImageLoader
Loading class for the Virtual Kitti 2 dataset: https://europe.naverlabs.com/research/computer-vision/proxy-virtual-worlds-vkitti-2/.
class GpuTimingStats
class GroundTruthInputPacket
class GroundTruthPacketMap
FastMap from frame id to GroundTruthInputPacket.
struct has_backend_module_display
struct has_backend_module_display< T, std::void_t< typename BackendModuleDisplayTraits< T >::type > >
class Histogram
struct HostMemoryAllocator
Allocates and free CPU (host) memory using cudaMallocHost. This allocates memory using cudaMallocHost. This memory is page-locked and therefore can be read or written with much higher bandwidth than pageable memory.
class HybridAccessor
Accessor for the Hybrid Formulation. The internal AccessorT is templated on MapVision to define the map type and HybridAccessorCommon which extends the functionality of the base Acessor with functionality specific to the Hybrid representation.
class HybridAccessorCommon
Accesor class that extends the basic functionlity of the Accessor with additional getter functions that are specific to the Hybrid formualtion.
class HybridFormulation
struct HybridFormulationProperties
class HybridFormulationV1
The original Hybrid motion implementation (as presented in "Online Dynamic SLAM with Incremental Smoothing and Mapping" from RA-L) - this is independant from the frontend and ONLY accepts frame-to-frame motion (i.e H_W_k_1_k) as input. It constructs object keyframes independantly of the front-end and therefore has slightly different embedded poses.
class HybridModuleDisplayCommon
class HybridMotionFactor
Motion factor connecting a point in the object frame (^L_m), the key-framed object motion from e to k in W (^W_eH_k) and the observing camera pose (^WX_k).
struct HybridObjectMotion
Definitions for common Hybrid formulation functions.
class HybridObjectMotionSRIF
Hybrid Object motion Square-Root Information Filter.
class HybridSmoothingFactor
Implements a 3-way smoothing factor on the (key-framed) object motion. This is analgous to a constant motion prior and minimises the change in object motion in the body frame of the object.
struct image_traits
struct image_traits< ImageType::Depth >
struct image_traits< ImageType::MotionMask >
struct image_traits< ImageType::OpticalFlow >
struct image_traits< ImageType::RGBMono >
struct image_traits< ImageType::SemanticMask >
struct image_traits_impl
struct ImageBase
class ImageContainer
Basic class to contain Images which are the input for the DynoSAM system. Instead of just containing a map of cv::Mat's we wrap each image using a ImageType which provides a way of abstracting the 'meaning' of each image given its purpose (ie. an rgb image is different in both data-type and value meaning than the motion-mask).
class ImageContainerConstructionException
class ImageKeyAlreadyExists
class ImageKeyDoesNotExist
class ImageTensorInfo
struct ImageToDisplay
class ImageTracksParams
Parameter struct to control the visualisation for FeatureTrackerBase::computeImageTracks.
struct ImageType
struct ImageWrapper
ImageWrapper for a ImageType that defines a particular type of input image. The ImageType template is used to create different types (actual c++ types) to differntial cv::Mat's from each other - eg. a type for a RGB image, Optical Flow or Motion Mask.
class ImuFrontend
class ImuInterfaceHandler
struct ImuMeasurement
struct ImuMeasurements
struct ImuParams
class InbuiltDisplayCommon
class IncorrectParallelHybridConstruction
struct incremental_fixed_lag_traits
Struct that implements the update function (as required by iOptimizationTraits) for the gtsam::IncrementalFixedLagSmoother.
class IncrementalInterface
class InstantanceSegMaskFolder
class InvalidCameraCalibration
struct InvalidCsvHeaderException
class InvalidDefaultParameter
Exception thrown when a parameter is missing a default parameter and MUST be set by the user at runtime (ie. no default value allowed)
struct InvalidImageContainerException
class InvalidImageTypeException
struct InvalidLandmarkException
struct InvalidLandmarkQuery
struct InvalidMapException
class InvalidRGBDCameraParams
struct iOptimizationTraits
Defines a traits interface to any incremental smoother. This must be defined for each type.
struct iOptimizationTraits< dyno::ISAM2 >
struct iOptimizationTraits< gtsam::BatchFixedLagSmoother >
struct iOptimizationTraits< gtsam::IncrementalFixedLagSmoother >
struct iOptimizationTraits< gtsam::ISAM2 >
struct is_optional
struct is_optional< std::optional< T > >
class ISAM2
class ISAM2BayesTree
class ISAM2Clique
struct ISAM2DoglegParams
struct ISAM2GaussNewtonParams
class ISAM2Helper
class ISAM2JunctionTree
struct ISAM2Params
struct ISAM2Result
struct ISAM2UpdateParams
struct IsStatus
class JsonConverter
class KittiCameraPoseFolder
class KittiClassSegmentationDataFolder
class KittiDataLoader
class KittiObjectPoseFolder
class KltFeatureTracker
Static feature tracking that tracks sparse feature set using the iterative Lucas-Kanade method with pyramids.
class LandmarkMotionPoseFactor
Implements the landmark motion factor that models the displacement of a tracked point, i, on a rigid body, j between consequative object poses ^wL_{k-1} and ^wL_k.
class LandmarkMotionTernaryFactor
Implements the landmark motion factor that models the displacement of a tracked point, i, on a rigid body, j with the absolute motion H.
class LandmarkNode
Landmark node representing all the measurements of a particular landmark (i) over all time (k to K) in the map-graph.
class LandmarkPoseSmoothingFactor
class LoggingShim
class LoopingSpinner
A spinner that will take a non-blocking function (spinOnce) and puts it in a loop with a given delay. Similar to timer functionality but guarantees that the function is called within a loop. Unlike a timer, the class does not take into account how long the function takes to run as the delay period will be used regardless.
class Map
A container that holds all connected information about static and dynamic entities that is build from input measurements.
class MapNodeBase
struct MapNodePtrComparison
struct MapTraits
struct measurement_traits
struct measurement_traits< CameraMeasurement >
class MeasurementWithCovariance
Defines a measurement/value with associated covariance matrix.
struct MemoryManager
Memory wrapper for cuda allocated memory of type T.
class MIMOPipelineModule
class MismatchedImageWrapperTypes
struct MissingLandmarkException
struct ModelConfig
class ModuleBase
Defines some basic functions and behaviour for a module which will take and send input to and from a pipeline.
struct ModuleParams
Params needed to make a module.
struct MotionFactorTraits
class MotionOnlyRefinementOptimizer
Jointly refined the motion of an object using the 3D-motion-residual.
struct MotionReferenceFrame
class MotionSegMaskFolder
class MultiFrameRangeData
class MultiSync
Wrapper for a message_filters::Synchronizer that encapsualtes subscribing to N topics of type Msg.
class MultiSyncBase
struct MultiSyncConfig
struct NiceColors
Palette of colours based of 'color blindness' which presents a set of colours which are optimized for color-blinded individuals. In other words, they are very easy to see and look very nice. To be used in vizualizations.
struct NoiseModels
class NonlinearFactorGraphManager
class NonMaximumSuppression
struct NoVizPolicy
struct NullPipelinePayload
The NullPipelinePayload is an empty payload, used for those modules that do not return a payload, such as the display module, which only displays images and returns nothing.
struct ObjectBBX
A struct for bounding boxes estimated by pcl - both oriented (OBB) and axis aligned (AABB). AABB does not require orientation (should be set as Identity), nor position. OBB requires all and the min/max points are w.r.t the centroid (i.e. the bbx_position_)
struct ObjectDetection
The result of an object detection from a detection network.
class ObjectDetectionEngine
Base class for a ObjectDetection network.
struct ObjectDetectionResult
Holds object detection/tracking result.
class ObjectDetectorEnginePy
Python Wrapper for ObjectDetectionEngine allowing implementation in pure python. Python classes should inherit directly from this class (i.e not from ObjectDetectionEngine)
class ObjectKinematicFactor
class ObjectMotionSolver
class ObjectMotionSolverFilter
class ObjectMotionSovlerF2F
class ObjectNode
Object node representing all object related data (j) over all time(k to K) in the map-graph.
struct ObjectPoseGT
struct ObjectStatus
class ObjectStatusMap
class ObjectTracker
struct ObjectUpdateContext
class OccupandyGrid2D
class OfstreamWrapper
class OMDDataLoader
Data loader for the oxford multi motion (omd) datasets as provided at: https://robotic-esp.com/datasets/omd/#tools-id.
class OMDOldAllLoader
struct OMMTimestampLoader
class OnlineDataProviderRos
Online data-provider for DynoSAM which handles subcription to the IMU and the interface for subscribing to images but does not implement this.
struct OnlineDataProviderRosParams
class OpenCVFrontendDisplay
class OpenCVImageDisplayQueue
class OpticalFlowAndPoseOptimizer
Joinly refines optical flow with with the given pose using the error term: e = [u,v]_{k_1} + f_{k-1, k} - \pi(X^{-1} \: m_k) where f is flow, [u,v]_{k-1} is the observed keypoint at k-1, X is the pose and m_k is the back-projected keypoint at k.
class OpticalFlowDataFolder
class ORBextractor
class ParalleHybridModuleDisplay
class ParallelHybridAccessor
Special accessor class to access all values via a single interface since the optimisation of the static scene and dynamic objects are decoupled and therefore handled by their own formulation.
class ParallelHybridBackendModule
class ParallelObjectISAM
class ParallelOpenCVMat
class ParameterConstructor
Wrapper class to define paramter details. Using these details a ParameterDetails object can be created which declares the paramter with its associated node automatically and can be used to directly access the latest value.
class ParameterDetails
struct PerObjectStatus
class PipelineBase
class PipelineModule
A PipelineModule is responsible for taking data from an input (or input queues) processing it, and sending it to an output queue (or queues)
class PipelineModuleProcessor
A SIMO (Single-in-multi-out) pipeline module that processes a data module.
struct PipelinePayload
class PipelineSpinner
struct PipelineTypeTraits
Defines type alias's for a single type (e.g INPUT or OUTPUT) which will be used within a PipelineModule.
struct PointUpdateContext
class Pose3FlowProjectionFactor
struct PostUpdateData
Metdata struct used for the Formulation::postUpdate hook.
struct PreUpdateData
Metadata struct used for the Formulation::preUpdate hook.
class ProjectAriaAllLoader
class ProjectARIADataLoader
Data loader for the PREPROCESSED Project ARIA for MP testing team (dataset so far closest source)
struct ProjectAriaTimestampLoader
class PyGILGuard
class PyObjectDetectionEngineTrampoline
Trampoline class allowing additional python specific virtual functions to be defined.
class PyObjectDetectorWrapper
A C++ wrapper for the a ObjectDetectionEngine written in python!
struct QueueRegistra
struct R
struct RansacProblemParams
struct ReferenceFrameValue
Estimate with a reference frame and operator casting.
class RegularBackendModule
class RegularHybridFormulation
class RegularHybridFormulationDisplay
struct RGBA
class RGBDataFolder
class RGBDCamera
class RGBDFrontendLogger
class RGBDInstanceFrontendModule
class RGBDOnlineProviderRos
Class that subscribes to rgb, depth, motion mask and dense optical flow topics.
class RGBDTypeCalibrationHelper
Class to help setup calibration for undistortion/resizing etc for an RGBD style input where only a single CameraParams is needed to represent a pinhole camera, rather than a stereo setup which needs different management.
struct ros_param_traits
Type trait to retrieve a c++ type from the corresponding rcl_interfaces::msg::ParameterType. ros_param_traits<rcl_interfaces::msg::ParameterType::PARAMETER_DOUBLE>::cpp_type == decltype(double)
class SegMaskFolder
struct Sensors
Encapsulation of various sensor types, giving the Formulation access to different models.
struct SharedFormulationData
Data shared between a Formulation and its accessor.
struct SharedHybridFormulationData
Information shared from the HybridFormulation to the HybridAccessor.
class SharedModuleInfo
struct SharedModuleInterface
class SIMOPipelineModule
SIMOPipelineModule Single Input Multiple Output (SIMO) pipeline module. Receives Input packets via a threadsafe queue, and sends output packets to a list of registered callbacks with a specific signature. This is useful when there are multiple modules expecting results from this module.
struct SingleDetectionResult
class SlidingWindowOptimization
class SmartMotionFactor
struct SmartMotionFactorParams
struct SolverResult
class SparseFeatureDetector
Wrapper on classic sparse feature detection method and integrates the option for adaptive non-maxima supression and sub-pixel refinement.
class Spinner
Class to handle the calling of a function within a thread. The spinner launches its own thread for each instance and is non-blocking.
class SquareRootInfoFilterGTSAM
Implements a Square Root Information Filter (SRIF) for 6-DoF pose estimation.
class StateQuery
Represents an optional value with meta-data that is retrieved from the map.
class StaticFeatureTracker
class StereoCamera
class StereoHybridMotionFactor
class StereoMatcher
struct StereoMatchingParams
struct SWOptimizationResult
class TartanAirShibuyaAllLoader
class TartanAirShibuyaLoader
Data loader for the TartanAir Shibuya datasets as provided at:https://github.com/haleqiu/tartanair-shibuya.
struct TartanAirShibuyaTimestampLoader
struct TemporalObjectMetaData
struct TensorInfo
class ThreadsafeImuBuffer
class ThreadsafeTemporalBuffer
class TimestampBaseLoader
class TimestampDataFolderDoesNotExist
class TimestampFile
class TrackedValueStatus
struct TrackerParams
Params for the feature tracker but also the feature detector.
struct TrackletCorrespondance
class TrackletIdManager
Singleton class to manage a global tracklet id for all trackers to ensure they are unique.
struct traits
A generic type trait with the dyno namespace. Here we define compile time conversions between c++ types and their corresponding rcl_interfaces::msg::ParameterType. The following properies are defined:
struct traits< std::string >
class TRTEngine
class UndistorterRectifier
The UndistorterRectifier class Computes undistortion maps and undistorts on a per-image basis. Optionally, one can also apply image rectification by providing a corresponding rotation matrix R.
struct unwrap_optional
struct unwrap_optional< std::optional< T > >
struct UpdateArguments
struct UpdateImpl
struct UpdateObservationParams
struct UpdateObservationResult
Result of a static/dynamic point update by calling Formulation<MAP>::updateStaticObservations or Formulation<MAP>::updateDynamicObservations.
class ViodeAllLoader
class ViodeLoader
struct ViodeTimestampLoader
class VirtualKittiClassSegmentationDataFolder
class VirtualKittiDataLoader
class VirtualKittiDepthDataFolder
class VirtualKittiFlowDataFolder
class VirtualKittiGenericInstanceSegFolder
class VirtualKittiGTFolder
class VirtualKittiInstanceSegFolder
class VirtualKittiMotionSegFolder
class VirtualKittiRGBDataFolder
class VirtualKittiTextGtLoader
struct VirtualKittiTimestampLoader
class VisionImuBackendModule
Class that handles the management of ego-motion (NavState) states from VO and (optionally) IMU.
class VisionImuPacket
Visual Tracking and Ego-motion information constructed by the DynoSAM frontend.
struct VisualMeasurementStatus
Defines a single visual measurement with tracking label, object id, frame id and measurement.
class WorldMotionAccessor
class WorldMotionFormulation
class WorldPoseAccessor
class WorldPoseFormulation
class YamlParser
struct YoloConfig
class YoloV8ModelInfo
class YoloV8ObjectDetector
TensorRT accelerated inference for object detection using YOLOv8.
Typedefs
using PoseToPointFactor = gtsam::PoseToPointFactor< gtsam::Pose3, Landmark >
Alias to a gtsam::PoseToPointFactor<gtsam::Pose3, Landmark>
using CalibrationType = Camera::CalibrationType
using Slot = long int
using SmartProjectionFactor = gtsam::SmartProjectionPoseFactor< CalibrationType >
Inidicates that a factor is not in the graph or uninitialised.
using GenericProjectionFactor = gtsam::GenericProjectionFactor< gtsam::Pose3, gtsam::Point3, CalibrationType >
using GenericStereoFactor = gtsam::GenericStereoFactor< gtsam::Pose3, Landmark >
using SmartProjectionFactorParams = gtsam::SmartProjectionParams
template<typename T >
using FactorMap = gtsam::FastMap< TrackletId, std::pair< T, Slot > >
template<typename MAP >
using DefaultBackendFactory = BackendFactory< NoVizPolicy, MAP >
a BackendFactory with a Policy that creates no additional displays
using DefaultRegularBackendModuleFactory = DefaultBackendFactory< RegularBackendModuleTraits::MapType >
BackendModuleFactory templated on the correct map type and with the default (NoVizPolicy) policy.
template<typename Policy >
using RegularBackendModuleFactory = BackendFactory< Policy, RegularBackendModuleTraits::MapType >
BackendModuleFactory templated on the regular map type but with a templated Policy.
using BackendInputPacket = VisionImuPacket
Define the BackendInputPacket as the output of the frontend.
using FrontendUpdateInterface = std::function< void(const FrameId, const Timestamp)>
using BackendPipeline = PipelineModuleProcessor< BackendInputPacket, BackendOutputPacket >
using json = nlohmann::json
using RegularBackendModuleTraits = BackendModuleTraits< VisionImuPacket, CameraMeasurement >
using RegularFormulationFactory = BackendFormulationFactory< RegularBackendModuleTraits::MapType >
BackendFormulationFactory templated on the regular map type.
using HybridSmartFactor = SmartMotionFactor< 3, gtsam::Pose3, gtsam::Pose3 >
using KeyFrameData = MultiFrameRangeData< ObjectId, gtsam::Pose3 >
using KeyFrameRanges = KeyFrameData::FrameRangeDataTVector
using KeyFrameRange = KeyFrameData::FrameRangeT
using ClusterSlamDatasetProvider = DynoDatasetProvider< cv::Mat, cv::Mat, GroundTruthInputPacket, std::optional< cv::Mat > >
using OMDDatasetProvider = DynoDatasetProvider< cv::Mat, cv::Mat, GroundTruthInputPacket >
using ProjectAriaDatasetProvider = DynoDatasetProvider< cv::Mat, cv::Mat, std::optional< cv::Mat > >
using TartanAirShibuyaProvider = DynoDatasetProvider< cv::Mat, cv::Mat, GroundTruthInputPacket >
using ViodeProvider = DynoDatasetProvider< cv::Mat, cv::Mat, GroundTruthInputPacket, std::optional< ImuMeasurements >, std::optional< cv::Mat > >
using VirtualKittiDatasetProvider = DynoDatasetProvider< cv::Mat, cv::Mat, cv::Mat, GroundTruthInputPacket >
using FrontendPipeline = PipelineModuleProcessor< FrontendInputPacketBase, VisionImuPacket >
using Pose3SolverResult = SolverResult< gtsam::Pose3 >
using Motion3SolverResult = SolverResult< Motion3ReferenceFrame >
using OccGrid2DPtr = std::shared_ptr< OccupandyGrid2D >
template<typename RefType , typename CurType >
using GenericCorrespondences = std::vector< TrackletCorrespondance< RefType, CurType > >
using AbsolutePoseCorrespondence = TrackletCorrespondance< Landmark, Keypoint >
using AbsolutePoseCorrespondences = std::vector< AbsolutePoseCorrespondence >
using RelativePoseCorrespondence = TrackletCorrespondance< Keypoint, Keypoint >
using RelativePoseCorrespondences = std::vector< RelativePoseCorrespondence >
using PointCloudCorrespondence = TrackletCorrespondance< Landmark, Landmark >
using PointCloudCorrespondences = std::vector< PointCloudCorrespondence >
using RuntimeSensorFlags = Flags< RuntimeSensorOptions >
using FrontendDisplay = DisplayBase< VisionImuPacket >
using BackendDisplay = DisplayBase< BackendOutputPacket >
using ImageDisplayQueue = ThreadsafeQueue< ImageToDisplay >
using FrontendVizPipeline = DisplayPipeline< VisionImuPacket >
using BackendVizPipeline = DisplayPipeline< BackendOutputPacket >
using CombinedParams = gtsam::PreintegratedCombinedMeasurements::Params
using CombinedParamSignature = FunctionSignature< decltype(CombinedParams::MakeSharedD)>
using CombinedParamPtr = CombinedParamSignature::ReturnType
template<template< typename, typename > class Container, typename Type >
using Aligned = Container< Type, Eigen::aligned_allocator< Type > >
using PropogatePoseResult = GenericObjectCentricMap< PropogateType >
using CloudPerObject = gtsam::FastMap< ObjectId, pcl::PointCloud< pcl::PointXYZRGB > >
Map of ObjectId's to XYZRGB Point Clouds.
using PointLabel = pcl::PointXYZL
Alias to XYZ point with label (std::uint32_t)
using PointLabelRGB = pcl::PointXYZRGBL
Alias to XYZ point with label (std::uint32_t) and RGB values.
using PointCloudLabelRGB = pcl::PointCloud< PointLabelRGB >
Alias to a PCL Point Cloud of type PointLabelRGB.
using BbxPerObject = gtsam::FastMap< ObjectId, ObjectBBX >
typedef MeasurementWithCovariance< gtsam::Pose3 > Pose3Measurement
(gtsam) Pose3 with covariance
typedef MeasurementWithCovariance< gtsam::Point3 > Point3Measurement
(gtsam) Point3 with covariance
typedef MeasurementWithCovariance< Keypoint > KeypointMeasurement
Keypoint with covariance.
typedef MeasurementWithCovariance< gtsam::StereoPoint2 > StereoMeasurement
Stereo Keypoint with covariance.
template<typename T >
using VisualMeasurementWithCovStatus = VisualMeasurementStatus< MeasurementWithCovariance< T > >
Alias to a visual measurement with a fixed-sized covariance matrix.
typedef VisualMeasurementWithCovStatus< Landmark > LandmarkStatus
Alias for a landmark measurement with 3x3 covariance.
typedef VisualMeasurementWithCovStatus< Keypoint > KeypointStatus
Alias for a keypoint measurement with 2x2 covariance.
typedef VisualMeasurementWithCovStatus< Depth > DepthStatus
Alias for a depth measurement with scalar covariance.
typedef VisualMeasurementWithCovStatus< gtsam::StereoPoint2 > StereoStatus
Alias for a stereo measurement with 3x3 covariance.
using CameraMeasurementStatus = TrackedValueStatus< CameraMeasurement >
typedef GenericTrackedStatusVector< LandmarkStatus > StatusLandmarkVector
A vector of LandmarkStatus.
typedef GenericTrackedStatusVector< KeypointStatus > StatusKeypointVector
A vector of KeypointStatus.
typedef GenericTrackedStatusVector< CameraMeasurementStatus > CameraMeasurementStatusVector
A vector of CameraMeasurementStatus.
using Timestamp = double
using Timestamps = Eigen::Matrix< Timestamp, 1, Eigen::Dynamic >
using ObjectId = int
Discrete object id, j.
using ObjectIds = std::vector< ObjectId >
using FrameId = size_t
Discrete time-step k.
using FrameIds = std::vector< FrameId >
using Depth = double
using Depths = std::vector< double >
using TrackletId = long int
Unique tracklet/landmark id, i.
using TrackletIds = std::vector< TrackletId >
using BearingVectors = std::vector< gtsam::Vector3, Eigen::aligned_allocator< gtsam::Vector3 > >
using Landmark = gtsam::Point3
using Landmarks = gtsam::Point3Vector
using LandmarkMap = gtsam::FastMap< TrackletId, Landmark >
using OpticalFlow = gtsam::Point2
using Keypoint = gtsam::Point2
Observed optical flow vector (ordered x, y)
using Keypoints = gtsam::Point2Vector
using Baseline = double
For RGBD/StereoCamera.
using KeypointCV = cv::KeyPoint
using KeypointsCV = std::vector< KeypointCV >
using Motion3 = gtsam::Pose3
using MotionMap = gtsam::FastMap< TrackletId, Motion3 >
using FrameIdTimestampMap = gtsam::FastMap< FrameId, Timestamp >
Map of tracklet ids to Motion3 (gtsam::Pose3)
template<typename Key , typename Estimate >
using EstimateMap = gtsam::FastMap< Key, ReferenceFrameValue< Estimate > >
Map of key to an estimate containting a reference frame.
template<typename Key , typename Estimate >
using MotionReferenceEstimateMap = gtsam::FastMap< Key, MotionReferenceFrame< Estimate > >
Map of key to a MotionReferenceFrame. Used specifically for motions.
using MotionEstimateMap = MotionReferenceEstimateMap< ObjectId, Motion3 >
Map of object id's to MotionReferenceFrame with Motion3.
using Motion3ReferenceFrame = MotionReferenceFrame< Motion3 >
Alias of a MotionReferenceFrame using Motion3 (Pose3)
using PoseEstimateMap = gtsam::FastMap< ObjectId, gtsam::Pose3 >
Map of object id's to gtsam::Pose3.
using ObjectPoseMap = GenericObjectCentricMap< gtsam::Pose3 >
Map of object poses per object per frame.
using ObjectMotionMap = GenericObjectCentricMap< Motion3ReferenceFrame >
Map of object motions per object per frame.
using OptionalString = std::optional< std::reference_wrapper< std::string > >
using FeaturePtrs = std::vector< Feature::Ptr >
using FeaturePair = std::pair< Feature::Ptr, Feature::Ptr >
using FeaturePairs = std::vector< FeaturePair >
Pair of feature (shared) pointers.
using FeatureFilterIterator = FeatureContainer::FilterIterator
filter iterator over a FeatureContainer class
using ConstFeatureFilterIterator = FeatureContainer::ConstFilterIterator
typedef ImageWrapper< ImageType::RGBMono > WrappedRGBMono
Alias to an ImageWrapper<ImageType::RGBMono>
typedef ImageWrapper< ImageType::Depth > WrappedDepth
Alias to an ImageWrapper<ImageType::Depth>
typedef ImageWrapper< ImageType::OpticalFlow > WrappedOpticalFlow
Alias to an ImageWrapper<ImageType::OpticalFlow>
typedef ImageWrapper< ImageType::SemanticMask > WrappedSemanticMask
Alias to an ImageWrapper<ImageType::SemanticMask>
typedef ImageWrapper< ImageType::MotionMask > WrappedMotionMask
Alias to an ImageWrapper<ImageType::MotionMask>
using StereoCalibPtr = gtsam::Cal3_S2Stereo::shared_ptr
using Severity = nvinfer1::ILogger::Severity
using EnginePtr = std::unique_ptr< nvinfer1::ICudaEngine >
using RuntimePtr = std::unique_ptr< nvinfer1::IRuntime >
template<typename T >
using HostMemory = MemoryManager< T, HostMemoryAllocator >
Allocates and manages host (CPU) memory allocated with HostMemoryAllocator. This allocates memory using cudaMallocHost. This memory is page-locked and therefore can be read or written with much higher bandwidth than pageable memory.
typedef gtsam::FastMap< char, gtsam::Vector > ISAM2ThresholdMap
typedef ISAM2ThresholdMap::value_type ISAM2ThresholdMapValue
using Map3d = Map< Landmark >
using ObjectNode3d = Map3d::ObjectNodeM
using LandmarkNode3d = Map3d::LandmarkNodeM
using FrameNode3d = Map3d::FrameNodeM
using Map2d = Map< Keypoint >
using ObjectNode2d = Map2d::ObjectNodeM
using LandmarkNode2d = Map2d::LandmarkNodeM
using FrameNode2d = Map2d::FrameNodeM
using MapVision = Map< CameraMeasurement >
using ObjectNodeV = MapVision::ObjectNodeM
using LandmarkNodeV = MapVision::LandmarkNodeM
using FrameNodeV = MapVision::FrameNodeM
template<typename MEASUREMENT >
using FrameNodePtr = std::shared_ptr< FrameNode< MEASUREMENT > >
template<typename MEASUREMENT >
using ObjectNodePtr = std::shared_ptr< ObjectNode< MEASUREMENT > >
template<typename MEASUREMENT >
using LandmarkNodePtr = std::shared_ptr< LandmarkNode< MEASUREMENT > >
template<typename MEASUREMENT >
using FrameNodePtrSet = FastMapNodeSet< FrameNodePtr< MEASUREMENT > >
template<typename MEASUREMENT >
using LandmarkNodePtrSet = FastMapNodeSet< LandmarkNodePtr< MEASUREMENT > >
template<typename MEASUREMENT >
using ObjectNodePtrSet = FastMapNodeSet< ObjectNodePtr< MEASUREMENT > >
using SymbolChar = unsigned char
using PointCloud2 = sensor_msgs::msg::PointCloud2
using MarkerArray = visualization_msgs::msg::MarkerArray
using Marker = visualization_msgs::msg::Marker
Typedef for MarkerArray msg.
using PointCloud2Pub = rclcpp::Publisher< sensor_msgs::msg::PointCloud2 >
Typedef for Marker msg.
using OdometryPub = rclcpp::Publisher< nav_msgs::msg::Odometry >
using PathPub = rclcpp::Publisher< nav_msgs::msg::Path >
using MarkerArrayPub = rclcpp::Publisher< MarkerArray >
typedef FrontendInbuiltDisplayRos FrontendDisplayRos
typedef BackendInbuiltDisplayRos BackendDisplayRos
using ObjectOdometry = dynamic_slam_interfaces::msg::ObjectOdometry
using ObjectOdometryPath = dynamic_slam_interfaces::msg::ObjectOdometryPath
using MultiObjectOdometryPath = dynamic_slam_interfaces::msg::MultiObjectOdometryPath
using ObjectOdometryPub = rclcpp::Publisher< ObjectOdometry >
using MultiObjectOdometryPathPub = rclcpp::Publisher< MultiObjectOdometryPath >
using ObjectOdometryMap = gtsam::FastMap< std::string, ObjectOdometry >
template<size_t N>
using MultiImageSync = MultiSync< sensor_msgs::msg::Image, N >
A MultiSync templated on sensor_msgs::msg::Image.
typedef MultiImageSync< 2 > MultiImageSync2
Some common MultiImageSync typedefs.
typedef MultiImageSync< 3 > MultiImageSync3
typedef MultiImageSync< 4 > MultiImageSync4
Enumerations
enum BackendType : int {
WCME = 0 , WCPE = 1 , HYBRID = 2 , PARALLEL_HYBRID = 3 ,
TESTING_HYBRID_SD = 4 , TESTING_HYBRID_D = 5 , TESTING_HYBRID_S = 6 , TESTING_HYBRID_SMF = 7
}
enum RegularOptimizationType : int { FULL_BATCH = 0 , SLIDING_WINDOW = 1 , INCREMENTAL = 2 }
enum DatasetType {
KITTI , VIRTUAL_KITTI , CLUSTER , OMD ,
ARIA , TARTAN_AIR_SHIBUYA , VIODE
}
enum MaskType { MOTION , SEMANTIC_INSTANCE }
enum to indicate what type of mask to load (if both are available)
enum class AnmsAlgorithmType : unsigned int {
TopN = 0 , BrownANMS = 1 , SDC = 2 , KdTree = 3 ,
RangeTree = 4 , Ssc = 5 , Binning = 6
}
enum FrontendType { kRGBD = 0 , kMono = 1 }
Determines which frontend module to load.
enum class TrackingStatus {
VALID , LOW_DISPARITY , FEW_MATCHES , INVALID ,
DISABLED
}
enum class RuntimeSensorOptions : std::uint8_t { PreferSensor = 1 << 0 , AcceptNoSensor = 1 << 1 , FailOnNoSensor = 1 << 2 }
enum class ObjectTrackingStatus { New = 0 , Tracked = 1 , ReTracked = 2 }
enum class ObjectFeatureTrackingStatus { Valid = 0 , Resampled = 1 }
enum PropogateType {
InitGT , InitCentroid , Propogate , Interpolate ,
Reinit
}
enum KeyPointType { STATIC , DYNAMIC }
enum ReferenceFrame { GLOBAL , LOCAL , OBJECT }
enum MotionRepresentationStyle { F2F , KF }
enum class DistortionModel { NONE , RADTAN , EQUIDISTANT , FISH_EYE }
enum StateQueryStatus { VALID , NOT_IN_MAP , WAS_IN_MAP , INVALID_MAP }
Status for a StateQuery<> type. This is defined outside the StateQuery class so that the type of status is independant of the StateQuery template.
enum InputImageMode : int { ALL = 0 , RGBD = 1 , STEREO = 2 }
Functions
void to_json (json &j, const ParallelObjectISAM::Result &result)
void toRightHandedTwist (gtsam::Vector3 &right_handed_linear_velocity, gtsam::Vector3 &right_handed_angular_velocity, const gtsam::Vector3 &left_handed_linear_velocity, const gtsam::Vector3 &left_handed_angular_velocity, std::optional< gtsam::Rot3 > left_handed_rotation={})
Considers the conversion from the left-handed coordiante system (e.g. unreal, VIODE, carla...) to the right-handed coordinate system (robotic).
gtsam::Rot3 toRightHandedRotation (const gtsam::Rot3 &left_handed_rotation)
Considers the conversion from left-handed system (e.g. unreal, VIODE, carla...) to right-handed system.
gtsam::Vector3 toRightHandedVector (const gtsam::Vector3 &left_handed_vector, std::optional< gtsam::Rot3 > left_handed_rotation)
Considers the conversion from a left-handed system (e.g. unreal, VIODE, carla...) vector to right-handed system with optional rotation provided in the left-handed system.
void removeStaticObjectFromMask (const cv::Mat &instance_mask, cv::Mat &motion_mask, const GroundTruthInputPacket &gt_packet)
From an instance semantic mask (one that satisfies the requirements for a SemanticMask), ie. all detected obejcts in the scene, with unique instance labels as pixel values starting from 1 (background is 0). Using the information in the ground truth, masks of detected objects that are not moving are removed. Masks are removed by setting the pixle values to 0 (background).
MaskType maskTypeFromString (const std::string &mask_type)
Converts an input string into a enun MaskType.
template<>
std::string to_string (const TrackingStatus &status)
NLOHMANN_JSON_SERIALIZE_ENUM (KeyPointType, { {STATIC, "static"}, {DYNAMIC, "dynamic"}, }) NLOHMANN_JSON_SERIALIZE_ENUM(ReferenceFrame
void declare_config (FrontendParams &config)
void declare_config (ImuParams &config)
template<class SampleConsensusProblem >
bool runRansac (std::shared_ptr< SampleConsensusProblem > sample_consensus_problem_ptr, const double &threshold, const int &max_iterations, const double &probability, const bool &do_nonlinear_optimization, gtsam::Pose3 &best_pose, std::vector< int > &inliers)
template<class SampleConsensusProblem >
bool runRansac (std::shared_ptr< SampleConsensusProblem > sample_consensus_problem_ptr, const RansacProblemParams &params, gtsam::Pose3 &best_pose, std::vector< int > &inliers)
void declare_config (OpticalFlowAndPoseOptimizer::Params &config)
void declare_config (MotionOnlyRefinementOptimizer::Params &config)
void declare_config (EgoMotionSolver::Params &config)
void declare_config (ObjectMotionSovlerF2F::Params &config)
void declare_config (TrackerParams::AnmsParams &config)
void declare_config (TrackerParams::SubPixelCornerRefinementParams &config)
void declare_config (TrackerParams::GFFTParams &config)
void declare_config (TrackerParams::OrbParams &config)
void declare_config (TrackerParams &config)
template<>
std::string to_string (const FeatureTrackerInfo &info)
void determineOutlierIds (const TrackletIds &inliers, const TrackletIds &tracklets, TrackletIds &outliers)
From a set a tracklets and a subset (of the tracklet) inliers, calculate the remaining subset of outliers.
void declare_config (DynoParams::PipelineParams &config)
std::ostream & operator<< (std::ostream &os, const DebugInfo::ObjectInfo &object_info)
std::vector< std::filesystem::path > getAllFilesInDir (const std::string &folder_path)
void loadPathsInDirectory (std::vector< std::string > &file_paths, const std::string &folder_path, const std::function< bool(const std::string &)> &condition)
int getTrackID (const std::vector< std::string > &split_string, int idx)
NOTE!!: In vitual kitti, the track id's start at 0 and then the ground truth instances in the semantic instances are indexed from trackId+1 such that a pixel value of zero means not a vehicle. In order to reduce confusion when we work with the semantic images and then associate with the ground truth labels, we will index all tracks as trackID = virtualKittiTrackID + 1 so all tracks start from 1!
const gtsam::PreintegratedCombinedMeasurements & safeCastToPreintegratedCombinedImuMeasurements (const gtsam::PreintegrationType &pim)
template<>
FunctionalDetector::Ptr FunctionalDetector::Create< cv::GFTTDetector > (const TrackerParams &tracker_params)
void declare_config (ImageTracksParams &config)
static float IC_Angle (const Mat &image, Point2f pt, const vector< int > &u_max)
static void computeOrbDescriptor (const KeyPoint &kpt, const Mat &img, const Point *pattern, uchar *desc)
static void computeOrientation (const Mat &image, vector< KeyPoint > &keypoints, const vector< int > &umax)
static void computeDescriptors (const Mat &image, vector< KeyPoint > &keypoints, Mat &descriptors, const vector< Point > &pattern)
gtsam::Vector3 calculateBodyMotion (const gtsam::Pose3 &w_k_1_H_k, const gtsam::Pose3 &w_L_k_1)
Calculate the local body velocity given the motion in world from k-1 to k and the object pose at k-1. This returns the body velocity at k-1.
void propogateObjectPoses (ObjectPoseMap &object_poses, const MotionEstimateMap &object_motions_k, const gtsam::Point3Vector &object_centroids_k_1, const gtsam::Point3Vector &object_centroids_k, FrameId frame_id_k, std::optional< GroundTruthPacketMap > gt_packet_map={}, PropogatePoseResult *result=nullptr)
Propogated a map of object poses via their motions or otherwise.
template<typename Exception = DynosamException>
void checkAndThrow (bool condition)
template<typename Exception = DynosamException>
void checkAndThrow (bool condition, const std::string &error_message)
template<typename Exception , typename... EArgs>
void checkAndThrow (bool condition, EArgs &&... eargs)
void to_json (json &j, const ObjectPoseGT::MotionInfo &motion_info)
Below is the JSON seralize/deseralize functions for all the GroundTruthPacket types. We use the nlohmann::json library (https://json.nlohmann.me/) - see the Arbitrary types conversions section in the readme (https://github.com/nlohmann/json?tab=readme-ov-file#integration) for details on the implemententation.
void from_json (const json &j, ObjectPoseGT::MotionInfo &motion_info)
Implements the required from_json (deseralizes) function for the nlohmann::json to automatically load ObjectPoseGT::MotionInfo from a json object.
void to_json (json &j, const ObjectPoseGT &object_pose_gt)
Implements the required to_json (seralize) function for the nlohmann::json to automatically convert ObjectPoseGT to a json type.
void from_json (const json &j, ObjectPoseGT &object_pose_gt)
Implements the required from_json (deseralizes) function for the nlohmann::json to automatically load ObjectPoseGT from a json object.
void to_json (json &j, const GroundTruthInputPacket &gt_packet)
Implements the required to_json (seralize) function for the nlohmann::json to automatically convert GroundTruthInputPacket to a json type.
void from_json (const json &j, GroundTruthInputPacket &gt_packet)
Implements the required from_json (deseralizes) function for the nlohmann::json to automatically load GroundTruthInputPacket from a json object.
void to_json (json &j, const GroundTruthPacketMap &gt_packet_map)
Implements the required to_json (seralize) function for the nlohmann::json to automatically convert GroundTruthPacketMap to a json type.
void from_json (const json &j, GroundTruthPacketMap &gt_packet_map)
Implements the required from_json (deseralizes) function for the nlohmann::json to automatically load GroundTruthPacketMap from a json object.
std::string getOutputFilePath (const std::string &file_name)
Constructs a file path (using the file name) where the root of the path is defined by the FLAGS_output_path param.
void writeStatisticsSamplesToFile (const std::string &file_name="statistics_samples.csv")
Writes all the statistics to a csv file on the path defined by getOutputFilePath(file_name).
void writeStatisticsSummaryToFile (const std::string &file_name="statistics.csv")
Writes a summary of the statistics to a csv file on the path defined by getOutputFilePath(file_name).
void writeStatisticsModuleSummariesToFile ()
Writes statistics per module to csv files on path defined by getOutputFilePath(). Interrnally uses WritePerModuleSummariesToCsvFile.
bool createDirectory (const std::string &path)
Create a directory at the given path.
static void OpenFile (const std::string &output_filename, std::ofstream *output_file, bool append_mode=false)
template<typename T >
std::ofstream & writeJson (std::ofstream &os, const T &t)
template<>
bool convert (const LandmarkStatus &status, pcl::PointXYZRGB &point)
template<typename Value , typename Point >
void convert_pcl (const GenericTrackedStatusVector< Value > &status_vector, pcl::PointCloud< Point > &cloud)
template<typename Point >
void convert (const StatusLandmarkVector &status_vector, pcl::PointCloud< Point > &cloud)
template<typename PointT >
bool convert (const gtsam::Point3 &gtsam_point, PointT &pcl_point)
template<typename PointT >
gtsam::Point3 pclPointToGtsam (const PointT &point)
Constructs a gtsam::Point3 from the x,y,z components of the PointT.
CloudPerObject groupObjectCloud (const StatusLandmarkVector &landmarks, const gtsam::Pose3 &T_world_camera, std::function< Color(ObjectId)> colour_generator=Color::uniqueObjectId, std::function< void(const pcl::PointXYZRGB &, ObjectId)> point_cb=nullptr)
This function goes through the input 3D landmarks and group them into point clusters based on their object labels these 3D landmarks are expected to be in the sensor reference frame, and T_world_camera puts them into the world frame CloudPerObject is in the world frame.
CloudPerObject groupObjectCloud (const StatusLandmarkVector &landmarks, const gtsam::Pose3 &T_world_camera, std::function< void(const pcl::PointXYZRGB &, ObjectId)> point_cb)
Overload of groupObjectCloud.
CloudPerObject groupObjectCloud (const StatusLandmarkVector &landmarks, const gtsam::Pose3 &T_world_camera, std::function< Color(ObjectId)> colour_generator)
Overload of groupObjectCloud.
template<typename PointT >
void computeMomentOfInertial (const typename pcl::PointCloud< PointT >::Ptr obj_cloud_ptr, pcl::MomentOfInertiaEstimation< PointT > &bbx_extractor, int mean_k=100, float std_dev_thresh=1.0)
Compute a MomentOfInertiaEstimation using an input point cloud.
template<typename PointT >
ObjectBBX findAABBFromCloud (const typename pcl::PointCloud< PointT >::Ptr obj_cloud_ptr)
Compute the Axis Aligned Bounding Box (AABB) from an input cloud.
template<typename PointT >
ObjectBBX findOBBFromCloud (const typename pcl::PointCloud< PointT >::Ptr obj_cloud_ptr)
Compute Oriented bounding box (OBB) from an input point cloud.
template<typename PointT >
pcl::PointCloud< pcl::PointXYZ > findLineListPointsFromAABBMinMax (const PointT &min_point_AABB, const PointT &max_point_AABB)
template<>
pcl::PointCloud< pcl::PointXYZ > findLineListPointsFromAABBMinMax (const gtsam::Point3 &min_point_AABB, const gtsam::Point3 &max_point_AABB)
Specalise function on gtsam::Point3 type.
template<size_t N, typename T , int D>
auto get (const MeasurementWithCovariance< T, D > &p)
template<size_t N, typename T >
auto get (const FrameRange< T > &p)
std::string demangle (const char *name)
Get demangled class name.
template<class T >
std::string type_name (const T &t)
Get demangled class name of type T from an instance.
template<class T >
std::string type_name ()
Get a demangled class name of type T from a templated type.
template<typename T >
std::string to_string (const T &t)
template<typename Input , typename Output >
bool convert (const Input &, Output &)
template<class Container >
std::string container_to_string (const Container &container, const std::string &delimiter=" ")
std::string info_string (FrameId frame_id, ObjectId object_id)
void to_json (json &j, const Histogram &histogram)
void from_json (const json &j, Histogram &histogram)
template<class T1 , class T2 >
size_t hashPair (const std::pair< T1, T2 > &p)
template<class T1 , class T2 , class T3 >
size_t hashTriplet (const T1 &p1, const T2 &p2, const T3 &p3)
bool fpEqual (double a, double b, double tol=1e-9)
Float point comparison up to a tolerance.
bool is_zero (double a)
Checks if a double value is zero up to a tolerance.
double rads2Deg (double rads)
Converts radians to degrees.
double deg2Rads (double degrees)
Converts degrees to radians.
double chi_squared_quantile (const double dofs, const double alpha)
Compute the quantile function of the Chi-Squared distribution.
template<typename T >
T mod (T x, T y)
Floating-point modulo The result (the remainder) has same sign as the divisor. Similar to matlab's mod(); Not similar to fmod() - Mod(-3,4)= 1 fmod(-3,4)= -3.
double wrapTwoPi (double ang)
Wraps an angle between [0... 2*PI].
template<typename T >
bool equals_with_abs_tol (const std::vector< T > &vec1, const std::vector< T > &vec2, double tol=1e-9)
template<typename T >
T computeCentroid (const std::vector< T > &vec)
template<typename T >
T computeCentroid (const std::vector< T, Eigen::aligned_allocator< T > > &vec)
template<typename T >
double calculateStandardDeviation (const std::vector< T, Eigen::aligned_allocator< T > > &vec)
bool writeMatrixWithPythonFormat (const gtsam::Matrix &matrix, const std::string &filename)
bool saveMatrixAsUpperTriangular (std::ostream &os, const gtsam::Matrix &matrix)
template<class Base , class Derived >
Derived safeCast (const Base &base)
template<typename Base , typename Derived >
std::shared_ptr< Derived > safeCast (std::shared_ptr< Base > base_ptr)
template<typename Base , typename Derived >
std::shared_ptr< const Derived > safeCast (std::shared_ptr< const Base > base_ptr)
template<typename Base , typename Derived >
std::unique_ptr< Derived > safeCast (std::unique_ptr< Base > &&base_ptr)
std::ostream & operator<< (std::ostream &os, const dyno::ObjectDetectionResult &res)
bool isMoving (const gtsam::Pose3 &prev_L_world, const gtsam::Pose3 &curr_L_world, double tol_m=0.4)
std::ostream & operator<< (std::ostream &os, const ObjectPoseGT &object_pose)
std::ostream & operator<< (std::ostream &os, const GroundTruthInputPacket &gt_packet)
ObjectBBX findAABBFromCloud (const pcl::PointCloud< pcl::PointXYZRGB >::Ptr obj_cloud_ptr)
template<>
std::string to_string (const ReferenceFrame &reference_frame)
template<>
std::string to_string (const MotionRepresentationStyle &style)
template<>
std::string to_string< cv::Size > (const cv::Size &t)
template<>
std::string to_string< cv::Rect > (const cv::Rect &t)
std::mt19937 gen (rd())
std::uniform_int_distribution< uint8_t > dis (0, 255)
std::array< float, 3 > rgbFromChromaHue (float chroma, float hue)
float exponentialOffsetId (size_t id, size_t ids_per_revolution)
Map a potentially infinite number of ids to a never repeating pattern in [0, 1].
std::ostream & operator<< (std::ostream &out, const Color &color)
void declare_config (CameraParams &config)
template<>
std::string to_string (const DistortionModel &distortion)
template<>
gtsam::Cal3_S2 CameraParams::constructGtsamCalibration< gtsam::Cal3_S2 > () const
template<>
gtsam::Cal3DS2 CameraParams::constructGtsamCalibration< gtsam::Cal3DS2 > () const
template<>
gtsam::Cal3Fisheye CameraParams::constructGtsamCalibration< gtsam::Cal3Fisheye > () const
std::ostream & operator<< (std::ostream &os, const ImageContainer &image_container)
void validateMask (const cv::Mat &input, const std::string &name)
void validateRGBMono (const cv::Mat &input)
void validateSingleImage (const cv::Mat &input, int expected_type, const std::string &name)
cv::Mat RGBMonoToRGB (const cv::Mat &mat)
cv::Mat RGBMonoToMono (const cv::Mat &mat)
np::ndarray ConvertMatToNDArray (const cv::Mat &mat)
cv::Mat ConvertNDArrayToMat (const np::ndarray &ndarr)
template<typename Func >
auto executePythonCall (Func &&func) -> decltype(func())
std::filesystem::path getNNWeightsPath ()
Specifies the default location of all weights used by dynosam_nn. This should in the dynosam_nn share package location + weights (e.g. /dynosam_nn/share/dynosam_nn/weights)
std::filesystem::path getNNResourcesPath ()
Specifies the default location of all weights used by dynosam_nn. This should in the dynosam_nn share package location + resources (e.g. /dynosam_nn/share/dynosam_nn/resouces)
std::ostream & operator<< (std::ostream &out, const TensorInfo &info)
std::ostream & operator<< (std::ostream &out, const ImageTensorInfo::Shape &shape)
std::ostream & operator<< (std::ostream &out, const ImageTensorInfo &info)
bool isDynamic (const nvinfer1::Dims &dims)
std::string toString (const nvinfer1::Dims &dims)
std::string toString (nvinfer1::DataType dtype)
std::string toString (nvinfer1::TensorIOMode mode)
RuntimePtr getRuntime (const std::string &verbosity)
EnginePtr deserializeEngine (nvinfer1::IRuntime &runtime, const std::filesystem::path &engine_path)
EnginePtr buildEngineFromOnnx (const ModelConfig &model_config, nvinfer1::IRuntime &runtime)
std::ostream & operator<< (std::ostream &out, const YoloV8ModelInfo &info)
fs::path getDynosamNNShareDirectory ()
std::filesystem::path getModelDirectory ()
bp::dict makeKwargs (const PyObjectDetectorWrapper::Kwargs &args)
template<typename T >
cv::Rect fromByeTrackRect (const byte_track::Rect< T > &rect)
Severity stringToSeverity (const std::string &severity)
std::optional< ImageTensorInfo::Shape > getShapeFromDimsHelper (const nvinfer1::Dims &dims)
EnginePtr deserializeEngine (IRuntime &runtime, const std::filesystem::path &engine_path)
nvinfer1::Dims replaceDynamic (const nvinfer1::Dims &dims, int64_t new_value)
EnginePtr buildEngineFromOnnx (const ModelConfig &model_config, IRuntime &runtime)
size_t optimizeWildfire (const ISAM2Clique::shared_ptr &root, double threshold, const gtsam::KeySet &replaced, gtsam::VectorValues *delta)
size_t optimizeWildfireNonRecursive (const ISAM2Clique::shared_ptr &root, double threshold, const gtsam::KeySet &replaced, gtsam::VectorValues *delta)
template<typename ValueType >
bool getSafeQuery (ValueType &result, const StateQuery< ValueType > &query, const ValueType &default_value)
Safe getter to a StateQuery object. If the StateQuery is successful, result is set to the value of the query and true is returned. Else, result is set to to the default value and false is returned.
std::string DynosamKeyFormatter (gtsam::Key)
std::string DynosamKeyFormatterVerbose (gtsam::Key)
SymbolChar DynoChrExtractor (gtsam::Key)
bool reconstructMotionInfo (gtsam::Key key, ObjectId &object_label, FrameId &frame_id)
bool reconstructPoseInfo (gtsam::Key key, ObjectId &object_label, FrameId &frame_id)
gtsam::Key H (unsigned char label, std::uint64_t j)
gtsam::Key L (unsigned char label, std::uint64_t j)
gtsam::Symbol CameraPoseSymbol (FrameId frame_id)
gtsam::Symbol StaticLandmarkSymbol (TrackletId tracklet_id)
DynamicPointSymbol DynamicLandmarkSymbol (FrameId frame_id, TrackletId tracklet_id)
gtsam::Key ObjectMotionSymbol (ObjectId object_label, FrameId frame_id)
gtsam::Key ObjectPoseSymbol (ObjectId object_label, FrameId frame_id)
size_t optimizeWildfire (const ISAM2Clique::shared_ptr &root, double threshold, const KeySet &keys, VectorValues *delta)
size_t optimizeWildfireNonRecursive (const ISAM2Clique::shared_ptr &root, double threshold, const KeySet &keys, VectorValues *delta)
template<class Rep = int64_t, class Period = std::milli>
CameraParams waitAndSetCameraParams (std::shared_ptr< rclcpp::Node > node, const std::string &topic, const std::chrono::duration< Rep, Period > &time_to_wait=std::chrono::duration< Rep, Period >(-1))
Gets CameraParams from a sensor_msgs::msg::CameraInfo recieved on the specified topic. This function is blocking until a message is recieved (or until the time_to_wait) elapses.
static HybridAccessorCommon::Ptr hybridAccessorCommonHelper (Accessor::Ptr accessor)
void updateAndCheckDynoParamsForRawImageInput (DynoParams &dyno_params)
Updates and checks that all dyno params are set correctly for when only raw image data is providd (ie. RBGD or Stereo) and no object/flow pre-processing has been done.
std::vector< std::string > initRosAndLogging (int argc, char *argv[])
Initalises ROS, gflags and glog.
template<>
const cv::Mat DataProviderRos::convertRosImage< ImageType::Depth > (const sensor_msgs::msg::Image::ConstSharedPtr &img_msg) const
template<>
std::string to_string (const InputImageMode &input_image_mode)
std::ostream & operator<< (std::ostream &stream, const ParameterDetails &param)
std::ostream & operator<< (std::ostream &stream, const rclcpp::Parameter &param)
char ** constructArgvC (const std::vector< std::string > &args)
Constructs a c-style pointer array from a vector of strings.
Variables
static constexpr Slot UninitialisedSlot
static constexpr char kRgbdFrontendOutputJsonFile []
static constexpr RuntimeSensorOptions DefaultRuntimeSensorOptions
const int PATCH_SIZE = 31
const int HALF_PATCH_SIZE = 15
const int EDGE_THRESHOLD = 19
const float factorPI = (float)(CV_PI / 180.f)
static int bit_pattern_31_ [256 *4]
static constexpr auto NaN = std::numeric_limits<double>::quiet_NaN()
static constexpr Timestamp InvalidTimestamp = 0
static constexpr ObjectId background_label = 0u
Expected label for the background in a semantic or motion mask.
template<typename DERIVEDSTATUS , typename VALUE >
constexpr bool IsDerivedTrackedValueStatus
Check if derived DERIVEDSTATUS us in factor derived from Status<Value>
template<typename T >
constexpr bool is_variant_v = internal::is_variant<T>::value
template<typename T , typename... Variants>
constexpr bool is_variant_member_v
std::random_device rd
static constexpr int MaxDetections = 8400
static constexpr auto PackageName = "dynosam_nn"
static constexpr SymbolChar kPoseSymbolChar = 'X'
static constexpr SymbolChar kVelocitySymbolChar = 'V'
static constexpr SymbolChar kObjectMotionSymbolChar = 'H'
static constexpr SymbolChar kObjectPoseSymbolChar = 'L'
static constexpr SymbolChar kStaticLandmarkSymbolChar = 'l'
static constexpr SymbolChar kDynamicLandmarkSymbolChar = 'm'
static constexpr SymbolChar kImuBiasSymbolChar = 'b'
static constexpr SymbolChar InvalidDynoSymbol = '\0'
Detailed Description
This file is part of VDO-SLAM.
Copyright (C) 2019-2020 Jun Zhang <jun doc zhang2 at anu dot edu doc au> (The Australian National University) For more information see https://github.com/halajun/VDO_SLAM
Typedef Documentation
AbsolutePoseCorrespondence
using dyno::AbsolutePoseCorrespondence = typedef TrackletCorrespondance<Landmark, Keypoint>
Correspondes format for a 3D->2D PnP solver. In the form of 3D Landmark in the world frame, and 2D observation in the current camera frame
Definition at line 59 of file Vision-Definitions.hpp.
AbsolutePoseCorrespondences
using dyno::AbsolutePoseCorrespondences = typedef std::vector<AbsolutePoseCorrespondence>
Definition at line 60 of file Vision-Definitions.hpp.
Aligned
template<template< typename, typename > class Container, typename Type > using dyno::Aligned = typedef Container<Type, Eigen::aligned_allocator<Type> >
Definition at line 76 of file ThreadSafeImuBuffer.cc.
BackendDisplay
using dyno::BackendDisplay = typedef DisplayBase<BackendOutputPacket>
Definition at line 82 of file Display.hpp.
BackendDisplayRos
typedef BackendInbuiltDisplayRos dyno::BackendDisplayRos
Definition at line 49 of file DisplaysImpl.hpp.
BackendInputPacket
using dyno::BackendInputPacket = typedef VisionImuPacket
Define the BackendInputPacket as the output of the frontend.
Definition at line 38 of file BackendInputPacket.hpp.
BackendPipeline
using dyno::BackendPipeline = typedef PipelineModuleProcessor<BackendInputPacket, BackendOutputPacket>
Definition at line 39 of file BackendPipeline.hpp.
BackendVizPipeline
using dyno::BackendVizPipeline = typedef DisplayPipeline<BackendOutputPacket>
Definition at line 76 of file VisualizerPipelines.hpp.
Baseline
using dyno::Baseline = typedef double
For RGBD/StereoCamera.
Vector of 2D keypoints using gtsam's definition for allocation
Definition at line 101 of file Types.hpp.
BbxPerObject
using dyno::BbxPerObject = typedef gtsam::FastMap<ObjectId, ObjectBBX>
Definition at line 144 of file PointCloudProcess.hpp.
BearingVectors
using dyno::BearingVectors = typedef std::vector<gtsam::Vector3, Eigen::aligned_allocator<gtsam::Vector3> >
Definition at line 85 of file Types.hpp.
CalibrationType
using dyno::CalibrationType = typedef Camera::CalibrationType
Definition at line 192 of file BackendDefinitions.hpp.
CameraMeasurementStatus
using dyno::CameraMeasurementStatus = typedef TrackedValueStatus<CameraMeasurement>
Definition at line 423 of file SensorModels.hpp.
CameraMeasurementStatusVector
typedef GenericTrackedStatusVector<CameraMeasurementStatus> dyno::CameraMeasurementStatusVector
A vector of CameraMeasurementStatus.
Definition at line 431 of file SensorModels.hpp.
CloudPerObject
using dyno::CloudPerObject = typedef gtsam::FastMap<ObjectId, pcl::PointCloud<pcl::PointXYZRGB> >
Map of ObjectId's to XYZRGB Point Clouds.
Definition at line 44 of file PointCloudProcess.hpp.
ClusterSlamDatasetProvider
using dyno::ClusterSlamDatasetProvider = typedef DynoDatasetProvider<cv::Mat, cv::Mat, GroundTruthInputPacket, std::optional<cv::Mat> >
Definition at line 42 of file ClusterSlamDataProvider.hpp.
CombinedParamPtr
using dyno::CombinedParamPtr = typedef CombinedParamSignature::ReturnType
Definition at line 63 of file ImuFrontend.cc.
CombinedParams
using dyno::CombinedParams = typedef gtsam::PreintegratedCombinedMeasurements::Params
Definition at line 60 of file ImuFrontend.cc.
CombinedParamSignature
using dyno::CombinedParamSignature = typedef FunctionSignature<decltype(CombinedParams::MakeSharedD)>
Definition at line 61 of file ImuFrontend.cc.
ConstFeatureFilterIterator
using dyno::ConstFeatureFilterIterator = typedef FeatureContainer::ConstFilterIterator
Definition at line 572 of file Feature.hpp.
DefaultBackendFactory
template<typename MAP > using dyno::DefaultBackendFactory = typedef BackendFactory<NoVizPolicy, MAP>
a BackendFactory with a Policy that creates no additional displays
Definition at line 249 of file BackendFactory.hpp.
DefaultRegularBackendModuleFactory
using dyno::DefaultRegularBackendModuleFactory = typedef DefaultBackendFactory<RegularBackendModuleTraits::MapType>
BackendModuleFactory templated on the correct map type and with the default (NoVizPolicy) policy.
Definition at line 253 of file BackendFactory.hpp.
Depth
using dyno::Depth = typedef double
Definition at line 77 of file Types.hpp.
Depths
using dyno::Depths = typedef std::vector<double>
Definition at line 78 of file Types.hpp.
DepthStatus
typedef VisualMeasurementWithCovStatus<Depth> dyno::DepthStatus
Alias for a depth measurement with scalar covariance.
Definition at line 419 of file SensorModels.hpp.
EnginePtr
using dyno::EnginePtr = typedef std::unique_ptr<nvinfer1::ICudaEngine>
Definition at line 56 of file TrtUtilities.hpp.
EstimateMap
template<typename Key , typename Estimate > using dyno::EstimateMap = typedef gtsam::FastMap<Key, ReferenceFrameValue<Estimate> >
Map of key to an estimate containting a reference frame.
Template Parameters
Key
Estimate
Definition at line 493 of file Types.hpp.
FactorMap
template<typename T > using dyno::FactorMap = typedef gtsam::FastMap<TrackletId, std::pair<T, Slot> >
Definition at line 210 of file BackendDefinitions.hpp.
FeatureFilterIterator
using dyno::FeatureFilterIterator = typedef FeatureContainer::FilterIterator
filter iterator over a FeatureContainer class
Definition at line 571 of file Feature.hpp.
FeaturePair
using dyno::FeaturePair = typedef std::pair<Feature::Ptr, Feature::Ptr>
Definition at line 301 of file Feature.hpp.
FeaturePairs
using dyno::FeaturePairs = typedef std::vector<FeaturePair>
Pair of feature (shared) pointers.
Definition at line 304 of file Feature.hpp.
FeaturePtrs
using dyno::FeaturePtrs = typedef std::vector<Feature::Ptr>
Definition at line 300 of file Feature.hpp.
FrameId
using dyno::FrameId = typedef size_t
Discrete time-step k.
Definition at line 74 of file Types.hpp.
FrameIds
using dyno::FrameIds = typedef std::vector<FrameId>
Definition at line 75 of file Types.hpp.
FrameIdTimestampMap
using dyno::FrameIdTimestampMap = typedef gtsam::FastMap<FrameId, Timestamp>
Map of tracklet ids to Motion3 (gtsam::Pose3)
Map of FrameIds (k) to Timestamps
Definition at line 112 of file Types.hpp.
FrameNode2d
using dyno::FrameNode2d = typedef Map2d::FrameNodeM
Definition at line 497 of file Map.hpp.
FrameNode3d
using dyno::FrameNode3d = typedef Map3d::FrameNodeM
Definition at line 492 of file Map.hpp.
FrameNodePtr
template<typename MEASUREMENT > using dyno::FrameNodePtr = typedef std::shared_ptr<FrameNode<MEASUREMENT> >
Definition at line 262 of file MapNodes.hpp.
FrameNodePtrSet
template<typename MEASUREMENT > using dyno::FrameNodePtrSet = typedef FastMapNodeSet<FrameNodePtr<MEASUREMENT> >
Definition at line 269 of file MapNodes.hpp.
FrameNodeV
using dyno::FrameNodeV = typedef MapVision::FrameNodeM
Definition at line 502 of file Map.hpp.
FrontendDisplay
using dyno::FrontendDisplay = typedef DisplayBase<VisionImuPacket>
Definition at line 81 of file Display.hpp.
FrontendDisplayRos
typedef FrontendInbuiltDisplayRos dyno::FrontendDisplayRos
Definition at line 48 of file DisplaysImpl.hpp.
FrontendPipeline
using dyno::FrontendPipeline = typedef PipelineModuleProcessor<FrontendInputPacketBase, VisionImuPacket>
Definition at line 41 of file FrontendPipeline.hpp.
FrontendUpdateInterface
using dyno::FrontendUpdateInterface = typedef std::function<void(const FrameId, const Timestamp)>
Definition at line 66 of file BackendModule.hpp.
FrontendVizPipeline
using dyno::FrontendVizPipeline = typedef DisplayPipeline<VisionImuPacket>
Definition at line 75 of file VisualizerPipelines.hpp.
GenericCorrespondences
template<typename RefType , typename CurType > using dyno::GenericCorrespondences = typedef std::vector<TrackletCorrespondance<RefType, CurType> >
Definition at line 54 of file Vision-Definitions.hpp.
GenericProjectionFactor
using dyno::GenericProjectionFactor = typedef gtsam::GenericProjectionFactor<gtsam::Pose3, gtsam::Point3, CalibrationType>
Definition at line 202 of file BackendDefinitions.hpp.
GenericStereoFactor
using dyno::GenericStereoFactor = typedef gtsam::GenericStereoFactor<gtsam::Pose3, Landmark>
Definition at line 205 of file BackendDefinitions.hpp.
HostMemory
template<typename T > using dyno::HostMemory = typedef MemoryManager<T, HostMemoryAllocator>
Allocates and manages host (CPU) memory allocated with HostMemoryAllocator. This allocates memory using cudaMallocHost. This memory is page-locked and therefore can be read or written with much higher bandwidth than pageable memory.
Template Parameters
T
Definition at line 312 of file TrtUtilities.hpp.
HybridSmartFactor
using dyno::HybridSmartFactor = typedef SmartMotionFactor<3, gtsam::Pose3, gtsam::Pose3>
Definition at line 1152 of file HybridEstimator.hpp.
ImageDisplayQueue
using dyno::ImageDisplayQueue = typedef ThreadsafeQueue<ImageToDisplay>
Definition at line 50 of file Visualizer-Definitions.hpp.
ISAM2ThresholdMap
typedef gtsam::FastMap<char, gtsam::Vector> dyno::ISAM2ThresholdMap
Parameters for the ISAM2 algorithm. Default parameter values are listed below.
Definition at line 141 of file ISAM2Params.hpp.
ISAM2ThresholdMapValue
typedef ISAM2ThresholdMap::value_type dyno::ISAM2ThresholdMapValue
Definition at line 142 of file ISAM2Params.hpp.
json
typedef nlohmann::json dyno::json
Definition at line 221 of file ParallelObjectISAM.hpp.
KeyFrameData
using dyno::KeyFrameData = typedef MultiFrameRangeData<ObjectId, gtsam::Pose3>
Definition at line 1160 of file HybridEstimator.hpp.
KeyFrameRange
using dyno::KeyFrameRange = typedef KeyFrameData::FrameRangeT
Definition at line 1162 of file HybridEstimator.hpp.
KeyFrameRanges
using dyno::KeyFrameRanges = typedef KeyFrameData::FrameRangeDataTVector
Definition at line 1161 of file HybridEstimator.hpp.
Keypoint
using dyno::Keypoint = typedef gtsam::Point2
Observed optical flow vector (ordered x, y)
Definition at line 96 of file Types.hpp.
KeypointCV
using dyno::KeypointCV = typedef cv::KeyPoint
Definition at line 103 of file Types.hpp.
KeypointMeasurement
typedef MeasurementWithCovariance<Keypoint> dyno::KeypointMeasurement
Keypoint with covariance.
Definition at line 351 of file SensorModels.hpp.
Keypoints
using dyno::Keypoints = typedef gtsam::Point2Vector
Definition at line 97 of file Types.hpp.
KeypointsCV
using dyno::KeypointsCV = typedef std::vector<KeypointCV>
Definition at line 104 of file Types.hpp.
KeypointStatus
typedef VisualMeasurementWithCovStatus<Keypoint> dyno::KeypointStatus
Alias for a keypoint measurement with 2x2 covariance.
Definition at line 417 of file SensorModels.hpp.
Landmark
using dyno::Landmark = typedef gtsam::Point3
Definition at line 88 of file Types.hpp.
LandmarkMap
using dyno::LandmarkMap = typedef gtsam::FastMap<TrackletId, Landmark>
Vector of Landmarks using gtsam's definition for allocation
Definition at line 91 of file Types.hpp.
LandmarkNode2d
using dyno::LandmarkNode2d = typedef Map2d::LandmarkNodeM
Definition at line 496 of file Map.hpp.
LandmarkNode3d
using dyno::LandmarkNode3d = typedef Map3d::LandmarkNodeM
Definition at line 491 of file Map.hpp.
LandmarkNodePtr
template<typename MEASUREMENT > using dyno::LandmarkNodePtr = typedef std::shared_ptr<LandmarkNode<MEASUREMENT> >
Definition at line 266 of file MapNodes.hpp.
LandmarkNodePtrSet
template<typename MEASUREMENT > using dyno::LandmarkNodePtrSet = typedef FastMapNodeSet<LandmarkNodePtr<MEASUREMENT> >
Definition at line 271 of file MapNodes.hpp.
LandmarkNodeV
using dyno::LandmarkNodeV = typedef MapVision::LandmarkNodeM
Definition at line 501 of file Map.hpp.
Landmarks
using dyno::Landmarks = typedef gtsam::Point3Vector
Definition at line 89 of file Types.hpp.
LandmarkStatus
typedef VisualMeasurementWithCovStatus<Landmark> dyno::LandmarkStatus
Alias for a landmark measurement with 3x3 covariance.
Definition at line 415 of file SensorModels.hpp.
Map2d
using dyno::Map2d = typedef Map<Keypoint>
Definition at line 494 of file Map.hpp.
Map3d
using dyno::Map3d = typedef Map<Landmark>
Definition at line 489 of file Map.hpp.
MapVision
using dyno::MapVision = typedef Map<CameraMeasurement>
Definition at line 499 of file Map.hpp.
Marker
using dyno::Marker = typedef visualization_msgs::msg::Marker
Typedef for MarkerArray msg.
Definition at line 52 of file DisplaysCommon.hpp.
MarkerArray
using dyno::MarkerArray = typedef visualization_msgs::msg::MarkerArray
Definition at line 50 of file DisplaysCommon.hpp.
MarkerArrayPub
using dyno::MarkerArrayPub = typedef rclcpp::Publisher<MarkerArray>
Definition at line 57 of file DisplaysCommon.hpp.
Motion3
using dyno::Motion3 = typedef gtsam::Pose3
Definition at line 106 of file Types.hpp.
Motion3ReferenceFrame
using dyno::Motion3ReferenceFrame = typedef MotionReferenceFrame<Motion3>
Alias of a MotionReferenceFrame using Motion3 (Pose3)
Definition at line 506 of file Types.hpp.
Motion3SolverResult
using dyno::Motion3SolverResult = typedef SolverResult<Motion3ReferenceFrame>
Definition at line 117 of file MotionSolver.hpp.
MotionEstimateMap
using dyno::MotionEstimateMap = typedef MotionReferenceEstimateMap<ObjectId, Motion3>
Map of object id's to MotionReferenceFrame with Motion3.
Definition at line 503 of file Types.hpp.
MotionMap
using dyno::MotionMap = typedef gtsam::FastMap<TrackletId, Motion3>
Definition at line 107 of file Types.hpp.
MotionReferenceEstimateMap
template<typename Key , typename Estimate > using dyno::MotionReferenceEstimateMap = typedef gtsam::FastMap<Key, MotionReferenceFrame<Estimate> >
Map of key to a MotionReferenceFrame. Used specifically for motions.
Template Parameters
Key
Estimate
Definition at line 499 of file Types.hpp.
MultiImageSync
template<size_t N> using dyno::MultiImageSync = typedef MultiSync<sensor_msgs::msg::Image, N>
A MultiSync templated on sensor_msgs::msg::Image.
Definition at line 290 of file MultiSync.hpp.
MultiImageSync2
typedef MultiImageSync<2> dyno::MultiImageSync2
Some common MultiImageSync typedefs.
Definition at line 294 of file MultiSync.hpp.
MultiImageSync3
typedef MultiImageSync<3> dyno::MultiImageSync3
Definition at line 295 of file MultiSync.hpp.
MultiImageSync4
typedef MultiImageSync<4> dyno::MultiImageSync4
Definition at line 296 of file MultiSync.hpp.
MultiObjectOdometryPath
using dyno::MultiObjectOdometryPath = typedef dynamic_slam_interfaces::msg::MultiObjectOdometryPath
Definition at line 47 of file DSDCommonRos.hpp.
MultiObjectOdometryPathPub
using dyno::MultiObjectOdometryPathPub = typedef rclcpp::Publisher<MultiObjectOdometryPath>
Definition at line 51 of file DSDCommonRos.hpp.
ObjectId
using dyno::ObjectId = typedef int
Discrete object id, j.
Definition at line 70 of file Types.hpp.
ObjectIds
using dyno::ObjectIds = typedef std::vector<ObjectId>
Definition at line 71 of file Types.hpp.
ObjectMotionMap
using dyno::ObjectMotionMap = typedef GenericObjectCentricMap<Motion3ReferenceFrame>
Map of object motions per object per frame.
Definition at line 692 of file Types.hpp.
ObjectNode2d
using dyno::ObjectNode2d = typedef Map2d::ObjectNodeM
Definition at line 495 of file Map.hpp.
ObjectNode3d
using dyno::ObjectNode3d = typedef Map3d::ObjectNodeM
Definition at line 490 of file Map.hpp.
ObjectNodePtr
template<typename MEASUREMENT > using dyno::ObjectNodePtr = typedef std::shared_ptr<ObjectNode<MEASUREMENT> >
Definition at line 264 of file MapNodes.hpp.
ObjectNodePtrSet
template<typename MEASUREMENT > using dyno::ObjectNodePtrSet = typedef FastMapNodeSet<ObjectNodePtr<MEASUREMENT> >
Definition at line 273 of file MapNodes.hpp.
ObjectNodeV
using dyno::ObjectNodeV = typedef MapVision::ObjectNodeM
Definition at line 500 of file Map.hpp.
ObjectOdometry
using dyno::ObjectOdometry = typedef dynamic_slam_interfaces::msg::ObjectOdometry
Definition at line 45 of file DSDCommonRos.hpp.
ObjectOdometryMap
using dyno::ObjectOdometryMap = typedef gtsam::FastMap<std::string, ObjectOdometry>
Map of object id link (child frame id) to ObjectOdometry (for a single frame, no frame ids)
Definition at line 55 of file DSDCommonRos.hpp.
ObjectOdometryPath
using dyno::ObjectOdometryPath = typedef dynamic_slam_interfaces::msg::ObjectOdometryPath
Definition at line 46 of file DSDCommonRos.hpp.
ObjectOdometryPub
using dyno::ObjectOdometryPub = typedef rclcpp::Publisher<ObjectOdometry>
Definition at line 50 of file DSDCommonRos.hpp.
ObjectPoseMap
using dyno::ObjectPoseMap = typedef GenericObjectCentricMap<gtsam::Pose3>
Map of object poses per object per frame.
Definition at line 690 of file Types.hpp.
OccGrid2DPtr
using dyno::OccGrid2DPtr = typedef std::shared_ptr<OccupandyGrid2D>
Definition at line 123 of file OccupancyGrid2D.hpp.
OdometryPub
using dyno::OdometryPub = typedef rclcpp::Publisher<nav_msgs::msg::Odometry>
Definition at line 55 of file DisplaysCommon.hpp.
OMDDatasetProvider
using dyno::OMDDatasetProvider = typedef DynoDatasetProvider<cv::Mat, cv::Mat, GroundTruthInputPacket>
Definition at line 42 of file OMDDataProvider.hpp.
OpticalFlow
using dyno::OpticalFlow = typedef gtsam::Point2
Definition at line 93 of file Types.hpp.
OptionalString
using dyno::OptionalString = typedef std::optional<std::reference_wrapper<std::string> >
Definition at line 700 of file Types.hpp.
PathPub
using dyno::PathPub = typedef rclcpp::Publisher<nav_msgs::msg::Path>
Definition at line 56 of file DisplaysCommon.hpp.
Point3Measurement
typedef MeasurementWithCovariance<gtsam::Point3> dyno::Point3Measurement
(gtsam) Point3 with covariance
Definition at line 348 of file SensorModels.hpp.
PointCloud2
using dyno::PointCloud2 = typedef sensor_msgs::msg::PointCloud2
Definition at line 49 of file DisplaysCommon.hpp.
PointCloud2Pub
using dyno::PointCloud2Pub = typedef rclcpp::Publisher<sensor_msgs::msg::PointCloud2>
Typedef for Marker msg.
Definition at line 54 of file DisplaysCommon.hpp.
PointCloudCorrespondence
using dyno::PointCloudCorrespondence = typedef TrackletCorrespondance<Landmark, Landmark>
Correspondes format for a 3D->3D PnP solver. In the form of a 3D Landmark in the world frame
Definition at line 69 of file Vision-Definitions.hpp.
PointCloudCorrespondences
using dyno::PointCloudCorrespondences = typedef std::vector<PointCloudCorrespondence>
Definition at line 70 of file Vision-Definitions.hpp.
PointCloudLabelRGB
using dyno::PointCloudLabelRGB = typedef pcl::PointCloud<PointLabelRGB>
Alias to a PCL Point Cloud of type PointLabelRGB.
Definition at line 52 of file PointCloudProcess.hpp.
PointLabel
using dyno::PointLabel = typedef pcl::PointXYZL
Alias to XYZ point with label (std::uint32_t)
Definition at line 48 of file PointCloudProcess.hpp.
PointLabelRGB
using dyno::PointLabelRGB = typedef pcl::PointXYZRGBL
Alias to XYZ point with label (std::uint32_t) and RGB values.
Definition at line 50 of file PointCloudProcess.hpp.
Pose3Measurement
typedef MeasurementWithCovariance<gtsam::Pose3> dyno::Pose3Measurement
(gtsam) Pose3 with covariance
Definition at line 345 of file SensorModels.hpp.
Pose3SolverResult
using dyno::Pose3SolverResult = typedef SolverResult<gtsam::Pose3>
Definition at line 116 of file MotionSolver.hpp.
PoseEstimateMap
using dyno::PoseEstimateMap = typedef gtsam::FastMap<ObjectId, gtsam::Pose3>
Map of object id's to gtsam::Pose3.
Definition at line 509 of file Types.hpp.
PoseToPointFactor
using dyno::PoseToPointFactor = typedef gtsam::PoseToPointFactor<gtsam::Pose3, Landmark>
Alias to a gtsam::PoseToPointFactor<gtsam::Pose3, Landmark>
Definition at line 53 of file BackendDefinitions.hpp.
ProjectAriaDatasetProvider
using dyno::ProjectAriaDatasetProvider = typedef DynoDatasetProvider<cv::Mat, cv::Mat, std::optional<cv::Mat> >
Definition at line 40 of file ProjectAriaDataProvider.hpp.
PropogatePoseResult
using dyno::PropogatePoseResult = typedef GenericObjectCentricMap<PropogateType>
Definition at line 136 of file DynamicObjects.hpp.
RegularBackendModuleFactory
template<typename Policy > using dyno::RegularBackendModuleFactory = typedef BackendFactory<Policy, RegularBackendModuleTraits::MapType>
BackendModuleFactory templated on the regular map type but with a templated Policy.
Definition at line 259 of file BackendFactory.hpp.
RegularBackendModuleTraits
using dyno::RegularBackendModuleTraits = typedef BackendModuleTraits<VisionImuPacket, CameraMeasurement>
Definition at line 39 of file RegularBackendDefinitions.hpp.
RegularFormulationFactory
using dyno::RegularFormulationFactory = typedef BackendFormulationFactory<RegularBackendModuleTraits::MapType>
BackendFormulationFactory templated on the regular map type.
Definition at line 43 of file RegularBackendDefinitions.hpp.
RelativePoseCorrespondence
using dyno::RelativePoseCorrespondence = typedef TrackletCorrespondance<Keypoint, Keypoint>
Correspondes format for a 2D->2D PnP solver. In the form of 2D observation in the ref camera frame, and 2D observation in the current camera frame
Definition at line 64 of file Vision-Definitions.hpp.
RelativePoseCorrespondences
using dyno::RelativePoseCorrespondences = typedef std::vector<RelativePoseCorrespondence>
Definition at line 65 of file Vision-Definitions.hpp.
RuntimePtr
using dyno::RuntimePtr = typedef std::unique_ptr<nvinfer1::IRuntime>
Definition at line 57 of file TrtUtilities.hpp.
RuntimeSensorFlags
using dyno::RuntimeSensorFlags = typedef Flags<RuntimeSensorOptions>
Definition at line 64 of file PipelineParams.hpp.
Severity
using dyno::Severity = typedef nvinfer1::ILogger::Severity
Definition at line 55 of file TrtUtilities.hpp.
Slot
using dyno::Slot = typedef long int
Definition at line 196 of file BackendDefinitions.hpp.
SmartProjectionFactor
using dyno::SmartProjectionFactor = typedef gtsam::SmartProjectionPoseFactor<CalibrationType>
Inidicates that a factor is not in the graph or uninitialised.
Definition at line 201 of file BackendDefinitions.hpp.
SmartProjectionFactorParams
using dyno::SmartProjectionFactorParams = typedef gtsam::SmartProjectionParams
Definition at line 207 of file BackendDefinitions.hpp.
StatusKeypointVector
typedef GenericTrackedStatusVector<KeypointStatus> dyno::StatusKeypointVector
A vector of KeypointStatus.
Definition at line 428 of file SensorModels.hpp.
StatusLandmarkVector
typedef GenericTrackedStatusVector<LandmarkStatus> dyno::StatusLandmarkVector
A vector of LandmarkStatus.
Definition at line 426 of file SensorModels.hpp.
StereoCalibPtr
using dyno::StereoCalibPtr = typedef gtsam::Cal3_S2Stereo::shared_ptr
Definition at line 43 of file RGBDCamera.hpp.
StereoMeasurement
typedef MeasurementWithCovariance<gtsam::StereoPoint2> dyno::StereoMeasurement
Stereo Keypoint with covariance.
Definition at line 354 of file SensorModels.hpp.
StereoStatus
typedef VisualMeasurementWithCovStatus<gtsam::StereoPoint2> dyno::StereoStatus
Alias for a stereo measurement with 3x3 covariance.
Definition at line 421 of file SensorModels.hpp.
SymbolChar
using dyno::SymbolChar = typedef unsigned char
Definition at line 13 of file Symbols.hpp.
TartanAirShibuyaProvider
using dyno::TartanAirShibuyaProvider = typedef DynoDatasetProvider<cv::Mat, cv::Mat, GroundTruthInputPacket>
Definition at line 42 of file TartanAirShibuya.hpp.
Timestamp
using dyno::Timestamp = typedef double
Definition at line 65 of file Types.hpp.
Timestamps
using dyno::Timestamps = typedef Eigen::Matrix<Timestamp, 1, Eigen::Dynamic>
Definition at line 66 of file Types.hpp.
TrackletId
using dyno::TrackletId = typedef long int
Unique tracklet/landmark id, i.
Definition at line 81 of file Types.hpp.
TrackletIds
using dyno::TrackletIds = typedef std::vector<TrackletId>
Definition at line 83 of file Types.hpp.
ViodeProvider
using dyno::ViodeProvider = typedef DynoDatasetProvider<cv::Mat, cv::Mat, GroundTruthInputPacket, std::optional<ImuMeasurements>, std::optional<cv::Mat> >
Definition at line 41 of file ViodeDataProvider.hpp.
VirtualKittiDatasetProvider
using dyno::VirtualKittiDatasetProvider = typedef DynoDatasetProvider<cv::Mat, cv::Mat, cv::Mat, GroundTruthInputPacket>
Definition at line 42 of file VirtualKittiDataProvider.hpp.
VisualMeasurementWithCovStatus
template<typename T > using dyno::VisualMeasurementWithCovStatus = typedef VisualMeasurementStatus<MeasurementWithCovariance<T> >
Alias to a visual measurement with a fixed-sized covariance matrix.
Template Parameters
T Measurement type (e.g. 2D keypoint, 3D landmark)
Definition at line 411 of file SensorModels.hpp.
WrappedDepth
typedef ImageWrapper<ImageType::Depth> dyno::WrappedDepth
Alias to an ImageWrapper<ImageType::Depth>
Definition at line 247 of file ImageTypes.hpp.
WrappedMotionMask
typedef ImageWrapper<ImageType::MotionMask> dyno::WrappedMotionMask
Alias to an ImageWrapper<ImageType::MotionMask>
Definition at line 253 of file ImageTypes.hpp.
WrappedOpticalFlow
typedef ImageWrapper<ImageType::OpticalFlow> dyno::WrappedOpticalFlow
Alias to an ImageWrapper<ImageType::OpticalFlow>
Definition at line 249 of file ImageTypes.hpp.
WrappedRGBMono
typedef ImageWrapper<ImageType::RGBMono> dyno::WrappedRGBMono
Alias to an ImageWrapper<ImageType::RGBMono>
Definition at line 245 of file ImageTypes.hpp.
WrappedSemanticMask
typedef ImageWrapper<ImageType::SemanticMask> dyno::WrappedSemanticMask
Alias to an ImageWrapper<ImageType::SemanticMask>
Definition at line 251 of file ImageTypes.hpp.
Enumeration Type Documentation
AnmsAlgorithmType
enum class dyno::AnmsAlgorithmType : unsigned int strong
Types of supported Adaptive Non Maximum Suppression algorithms
Enumerator
TopN
BrownANMS
SDC
KdTree
RangeTree
Ssc
Binning
Definition at line 48 of file NonMaximumSuppression.h.
                             : unsigned int {
  TopN = 0,
  BrownANMS = 1,
  SDC = 2,
  KdTree = 3,
  RangeTree = 4,
  Ssc = 5,
  Binning = 6
};
BackendType
enum dyno::BackendType : int
Enumerator
WCME
WCPE
HYBRID
PARALLEL_HYBRID
TESTING_HYBRID_SD
TESTING_HYBRID_D
TESTING_HYBRID_S
TESTING_HYBRID_SMF
Definition at line 55 of file BackendDefinitions.hpp.
                 : int {
  WCME = 0,             // world-centric motion estimator
  WCPE = 1,             // world-centric pose estimator
  HYBRID = 2,           // full-hybrid
  PARALLEL_HYBRID = 3,  // associated to its own special class
  // the following are test formulations that were not specifcially part of a
  // paper but were used for (internal) development/research. they may not work
  // as intended and are included for posterity
  TESTING_HYBRID_SD = 4,  // (SD) structureless-decoupled
  TESTING_HYBRID_D = 5,   // (D) decoupled
  TESTING_HYBRID_S = 6,   // (S) structureless
  TESTING_HYBRID_SMF = 7  // (SFM) smart motion factor
};
DatasetType
enum dyno::DatasetType
Enumerator
KITTI
VIRTUAL_KITTI
CLUSTER
OMD
ARIA
TARTAN_AIR_SHIBUYA
VIODE
Definition at line 37 of file DataProviderFactory.hpp.
                 {
  KITTI,
  VIRTUAL_KITTI,
  CLUSTER,
  OMD,  // oxford multi-motion dataset,
  ARIA,
  TARTAN_AIR_SHIBUYA,
  VIODE
};
DistortionModel
enum class dyno::DistortionModel strong
Enumerator
NONE
RADTAN
EQUIDISTANT
FISH_EYE
Definition at line 54 of file CameraParams.hpp.
{ NONE, RADTAN, EQUIDISTANT, FISH_EYE };
FrontendType
enum dyno::FrontendType
Determines which frontend module to load.
Enumerator
kRGBD
kMono
Definition at line 50 of file Frontend-Definitions.hpp.
{ kRGBD = 0, kMono = 1 };
InputImageMode
enum dyno::InputImageMode : int
Enumerator
ALL
Expects rgb, depth, flow and semantics to be provided.
RGBD
Expects only rgb and depth images to be provided.
STEREO
Definition at line 44 of file OnlineDataProviderRos.hpp.
                    : int {
  ALL = 0,
  RGBD = 1,
  STEREO = 2
};
KeyPointType
enum dyno::KeyPointType
Enumerator
STATIC
DYNAMIC
Definition at line 190 of file Types.hpp.
{ STATIC, DYNAMIC };
MaskType
enum dyno::MaskType
enum to indicate what type of mask to load (if both are available)
Enumerator
MOTION
SEMANTIC_INSTANCE
Definition at line 289 of file DatasetLoader.hpp.
{ MOTION, SEMANTIC_INSTANCE };
MotionRepresentationStyle
enum dyno::MotionRepresentationStyle
Enumerator
F2F
KF
Definition at line 232 of file Types.hpp.
{
  F2F,  // frame-to-frame
  KF    // keyframe representation of motion
};
ObjectFeatureTrackingStatus
enum class dyno::ObjectFeatureTrackingStatus strong
Enumerator
Valid
Resampled
New features were detected not that the object itself is retracked.
Definition at line 45 of file DynamicObjects.hpp.
{
  Valid = 0,
  Resampled = 1
  // TODO: maybe too few etc
};
ObjectTrackingStatus
enum class dyno::ObjectTrackingStatus strong
Enumerator
New
Tracked
ReTracked
Definition at line 42 of file DynamicObjects.hpp.
{ New = 0, Tracked = 1, ReTracked = 2 };
PropogateType
enum dyno::PropogateType
Enumerator
InitGT
InitCentroid
Propogate
Interpolate
Reinit
Definition at line 128 of file DynamicObjects.hpp.
                   {
  InitGT,
  InitCentroid,
  Propogate,    // Propogated via a motion
  Interpolate,  // Interpolated via a motion
  Reinit        // Reinitalisaed via a centroid
};
ReferenceFrame
enum dyno::ReferenceFrame
Enumerator
GLOBAL
LOCAL
OBJECT
Definition at line 192 of file Types.hpp.
{ GLOBAL, LOCAL, OBJECT };
RegularOptimizationType
enum dyno::RegularOptimizationType : int
Enumerator
FULL_BATCH
SLIDING_WINDOW
INCREMENTAL
Definition at line 71 of file BackendParams.hpp.
                             : int {
  FULL_BATCH = 0,
  SLIDING_WINDOW = 1,
  INCREMENTAL = 2
};
RuntimeSensorOptions
enum class dyno::RuntimeSensorOptions : std::uint8_t strong
Enumerator
PreferSensor
Use this sensor, if available.
AcceptNoSensor
if we prefer the sensor but data is not available the system will use other information
FailOnNoSensor
if we prefer a sensor but data is not available, fail hard
Definition at line 50 of file PipelineParams.hpp.
                                : std::uint8_t {
  PreferSensor = 1 << 0,
  AcceptNoSensor = 1 << 1,
  FailOnNoSensor = 1 << 2
};
StateQueryStatus
enum dyno::StateQueryStatus
Status for a StateQuery<> type. This is defined outside the StateQuery class so that the type of status is independant of the StateQuery template.
Enumerator
VALID
NOT_IN_MAP
WAS_IN_MAP
INVALID_MAP
Definition at line 278 of file MapNodes.hpp.
{ VALID, NOT_IN_MAP, WAS_IN_MAP, INVALID_MAP };
TrackingStatus
enum class dyno::TrackingStatus strong
Enumerator
VALID
LOW_DISPARITY
FEW_MATCHES
INVALID
DISABLED
Definition at line 52 of file Frontend-Definitions.hpp.
{
  VALID,
  LOW_DISPARITY,
  FEW_MATCHES,
  INVALID,
  DISABLED
};
Function Documentation
buildEngineFromOnnx() [1/2]
EnginePtr dyno::buildEngineFromOnnx (const ModelConfig & model_config, IRuntime & runtime)
Definition at line 370 of file TrtUtilities.cc.
{
  using nvinfer1::Dims3;
  using nvinfer1::OptProfileSelector;
  const auto model_path = model_config.onnxPath();
  LOG(INFO) << "Building onnx engine from " << model_path << "...";
  auto& logger = LoggingShim::instance(model_config.log_severity);
  std::unique_ptr<nvinfer1::IBuilder> builder(
      nvinfer1::createInferBuilder(logger));
  int flags = 0;
#if NV_TENSORRT_MAJOR < 10
  // required for exported models previously to tensorrt 10
  flags = (1U << static_cast<uint32_t>(
               NetworkDefinitionCreationFlag::kEXPLICIT_BATCH));
#endif
  std::unique_ptr<INetworkDefinition> net(builder->createNetworkV2(flags));
  std::unique_ptr<IParser> parser(nvonnxparser::createParser(*net, logger));
  parser->parseFromFile(model_path.c_str(),
                        static_cast<int>(Severity::kVERBOSE));
  for (int i = 0; i < parser->getNbErrors(); ++i) {
    LOG(ERROR) << "Parser Error #" << i << ": " << parser->getError(i)->desc();
  }
  // these are details specific the the YOLO model...
  if (net->getNbOutputs() != 2) {
    LOG(ERROR) << "Network does not have a single output: "
               << net->getNbOutputs() << " != 2";
    return nullptr;
  }
  auto output = net->getOutput(0);
  auto output_dtype = output->getType();
  if (output_dtype != nvinfer1::DataType::kFLOAT) {
    LOG(WARNING) << "Add extra output cast layer to INT32";
    // auto layer = net->addCast(*output, nvinfer1::DataType::kINT32);
    // net->unmarkOutput(*output);
    // layer->getOutput(0)->setName("output_int32");
    // net->markOutput(*layer->getOutput(0));
  }
  std::unique_ptr<nvinfer1::IBuilderConfig> config(
      builder->createBuilderConfig());
  auto* profile = builder->createOptimizationProfile();
  for (int i = 0; i < net->getNbInputs(); ++i) {
    const auto input_tensor = net->getInput(i);
    const auto name = input_tensor->getName();
    const auto dims = input_tensor->getDimensions();
    // if (!isDynamic(dims)) {
    //   continue;
    // }
    profile->setDimensions(name, nvinfer1::OptProfileSelector::kMIN, dims);
    profile->setDimensions(name, nvinfer1::OptProfileSelector::kOPT, dims);
    profile->setDimensions(name, nvinfer1::OptProfileSelector::kMAX, dims);
    // profile->setDimensions(name,
    //                        OptProfileSelector::kMIN,
    //                        replaceDynamic(dims,
    //                        model_config.min_optimization_size));
    // profile->setDimensions(name,
    //                        OptProfileSelector::kOPT,
    //                        replaceDynamic(dims,
    //                        model_config.target_optimization_size));
    // profile->setDimensions(name,
    //                        OptProfileSelector::kMAX,
    //                        replaceDynamic(dims,
    //                        model_config.max_optimization_size));
    config->addOptimizationProfile(profile);
  }
  std::unique_ptr<IHostMemory> memory(
      builder->buildSerializedNetwork(*net, *config));
  if (!memory) {
    LOG(FATAL) << "Failed to build network for " << model_path;
    return nullptr;
  }
  // will ovewride engine path from YOLO!
  std::ofstream fout(model_config.enginePath(), std::ios::binary);
  fout.write(reinterpret_cast<char*>(memory->data()), memory->size());
  EnginePtr engine(
      runtime.deserializeCudaEngine(memory->data(), memory->size()));
  if (!engine) {
    LOG(FATAL) << "Engine creation failed from " << model_path;
    return nullptr;
  }
  return engine;
}
References dyno::ModelConfig::enginePath(), dyno::LoggingShim::instance(), dyno::ModelConfig::log_severity, and dyno::ModelConfig::onnxPath().
buildEngineFromOnnx() [2/2]
EnginePtr dyno::buildEngineFromOnnx (const ModelConfig & model_config, nvinfer1::IRuntime & runtime)
Referenced by dyno::TRTEngine::TRTEngine().
calculateBodyMotion()
gtsam::Vector3 dyno::calculateBodyMotion (const gtsam::Pose3 & w_k_1_H_k, const gtsam::Pose3 & w_L_k_1)
Calculate the local body velocity given the motion in world from k-1 to k and the object pose at k-1. This returns the body velocity at k-1.
Parameters
w_k_1_H_k const gtsam::Pose3&
w_L_k_1 const gtsam::Pose3&
Returns
gtsam::Vector3
Definition at line 76 of file DynamicObjects.cc.
{
  const gtsam::Point3& t_motion = w_k_1_H_k.translation();
  const gtsam::Rot3& R_motion = w_k_1_H_k.rotation();
  const gtsam::Point3& t_pose = w_L_k_1.translation();
  static const gtsam::Rot3 I = gtsam::Rot3::Identity();
  return t_motion - (gtsam::Rot3(I.matrix() - R_motion.matrix())) * t_pose;
}
Referenced by dyno::DSDTransport::constructObjectOdometry().
calculateStandardDeviation()
template<typename T > double dyno::calculateStandardDeviation (const std::vector< T, Eigen::aligned_allocator< T > > & vec) inline
Definition at line 247 of file Numerical.hpp.
{
  const T mean = computeCentroid<T>(vec);
  double sum = 0;
  for (const T& t : vec) {
    T sub = t.colwise() - mean;
    sum += sub.norm();
  }
  return std::sqrt(sum / static_cast<double>(vec.size()));
}
CameraParams::constructGtsamCalibration< gtsam::Cal3_S2 >()
template<> gtsam::Cal3_S2 dyno::CameraParams::constructGtsamCalibration< gtsam::Cal3_S2 > () const
Definition at line 286 of file CameraParams.cc.
{
  static const auto requested_calibration_name =
      type_name<gtsam::Cal3_S2>();  // only used for debug so seems waste to
                                    // allocate everytime
  if (distortion_model_ != DistortionModel::RADTAN) {
    throw InvalidCameraCalibration(
        "Requested gtsam calibration was " + requested_calibration_name +
        " which is unsupported by this camera model: " +
        to_string(distortion_model_));
  }
  // if(distortion_coeff_.size() < 4u) {
  //   throw InvalidCameraCalibration("Distortion coefficients have size <4 for
  //   camera params with distortion model"
  //     + to_string(distortion_model_) + " and requested gtsam calibration of
  //     type " + requested_calibration_name);
  // }
  constexpr static double skew = 0.0;
  return gtsam::Cal3_S2(fx(), fy(), skew, cu(), cv());
}
References RADTAN, and to_string().
CameraParams::constructGtsamCalibration< gtsam::Cal3DS2 >()
template<> gtsam::Cal3DS2 dyno::CameraParams::constructGtsamCalibration< gtsam::Cal3DS2 > () const
Definition at line 310 of file CameraParams.cc.
{
  static const auto requested_calibration_name =
      type_name<gtsam::Cal3DS2>();  // only used for debug so seems waste to
                                    // allocate everytime
  if (distortion_model_ != DistortionModel::RADTAN) {
    throw InvalidCameraCalibration(
        "Requested gtsam calibration was " + requested_calibration_name +
        " which is unsupported by this camera model: " +
        to_string(distortion_model_));
  }
  if (distortion_coeff_.size() < 4u) {
    throw InvalidCameraCalibration(
        "Distortion coefficients have size <4 for camera params with "
        "distortion model" +
        to_string(distortion_model_) +
        " and requested gtsam calibration of type " +
        requested_calibration_name);
  }
  constexpr static double skew = 0.0;
  return gtsam::Cal3DS2(fx(), fy(), skew, cu(), cv(), distortion_coeff_.at(0),
                        distortion_coeff_.at(1), distortion_coeff_.at(2),
                        distortion_coeff_.at(3));
}
References RADTAN, and to_string().
CameraParams::constructGtsamCalibration< gtsam::Cal3Fisheye >()
template<> gtsam::Cal3Fisheye dyno::CameraParams::constructGtsamCalibration< gtsam::Cal3Fisheye > () const
Definition at line 338 of file CameraParams.cc.
          {
  static const auto requested_calibration_name =
      type_name<gtsam::Cal3Fisheye>();  // only used for debug so seems waste to
                                        // allocate everytime
  // jesse: not sure if gtsam well supports equidistant models!
  if (distortion_model_ != DistortionModel::FISH_EYE &&
      distortion_model_ != DistortionModel::EQUIDISTANT) {
    throw InvalidCameraCalibration(
        "Requested gtsam calibration was " + requested_calibration_name +
        " which is unsupported by this camera model: " +
        to_string(distortion_model_));
  }
  if (distortion_coeff_.size() < 4u) {
    throw InvalidCameraCalibration(
        "Distortion coefficients have size <4 for camera params with "
        "distortion model" +
        to_string(distortion_model_) +
        " and requested gtsam calibration of type " +
        requested_calibration_name);
  }
  constexpr static double skew = 0.0;
  return gtsam::Cal3Fisheye(fx(), fy(), skew, cu(), cv(),
                            distortion_coeff_.at(0), distortion_coeff_.at(1),
                            distortion_coeff_.at(2), distortion_coeff_.at(3));
}
References EQUIDISTANT, FISH_EYE, and to_string().
CameraPoseSymbol()
gtsam::Symbol dyno::CameraPoseSymbol (FrameId frame_id) inline
Definition at line 133 of file Symbols.hpp.
{
  return gtsam::Symbol(kPoseSymbolChar, frame_id);
}
References kPoseSymbolChar.
Referenced by dyno::factor_graph_tools::addBetweenFactor(), dyno::Formulation< MAP >::addSensorPoseValue(), dyno::VisionImuBackendModule< MODULE_TRAITS >::getInvolvedStates(), dyno::FrameNode< MEASUREMENT >::makePoseKey(), dyno::MotionOnlyRefinementOptimizer::optimize(), and dyno::ParallelObjectISAM::updateFormulation().
checkAndThrow() [1/3]
template<typename Exception = DynosamException> void dyno::checkAndThrow (bool condition) inline
Definition at line 66 of file Exceptions.hpp.
{
  if (!condition) {
    if constexpr (std::is_constructible_v<Exception, const char*>) {
      throw Exception("");
    } else {
      static_assert(std::is_default_constructible_v<Exception>,
                    "Exception type must be default constructible if it does "
                    "not take const char*");
      throw Exception();
    }
  }
}
Referenced by dyno::BackendModuleType< MODULE_TRAITS >::attemptCast(), dyno::PipelineSpinner::registerPipeline(), and dyno::ObjectPoseGT::setMotions().
checkAndThrow() [2/3]
template<typename Exception = DynosamException> void dyno::checkAndThrow (bool condition, const std::string & error_message) inline
Definition at line 80 of file Exceptions.hpp.
{
  if (!condition) {
    throw Exception(error_message);
  }
}
checkAndThrow() [3/3]
template<typename Exception , typename... EArgs> void dyno::checkAndThrow (bool condition, EArgs &&... eargs) inline
Definition at line 87 of file Exceptions.hpp.
{
  if (!condition) {
    throw Exception(std::forward<EArgs>(eargs)...);
  }
}
chi_squared_quantile()
double dyno::chi_squared_quantile (const double dofs, const double alpha) inline
Compute the quantile function of the Chi-Squared distribution.
Implemented Percent point function (inverse of cdf percentiles) or scipy.ppf function
Parameters
dofs Degrees of freedom
alpha Quantile value (confidence)
Returns
double
Definition at line 129 of file Numerical.hpp.
{
  boost::math::chi_squared chiSquaredDist(dofs);
  return boost::math::quantile(chiSquaredDist, alpha);
}
Referenced by dyno::factor_graph_tools::determineFactorOutliers().
computeCentroid() [1/2]
template<typename T > T dyno::computeCentroid (const std::vector< T > & vec) inline
Definition at line 228 of file Numerical.hpp.
{
  T sum{};
  for (const T& t : vec) {
    sum += t;
  }
  return sum / static_cast<double>(vec.size());
}
computeCentroid() [2/2]
template<typename T > T dyno::computeCentroid (const std::vector< T, Eigen::aligned_allocator< T > > & vec) inline
Definition at line 237 of file Numerical.hpp.
{
  T sum{};
  for (const T& t : vec) {
    sum += t;
  }
  return sum / static_cast<double>(vec.size());
}
computeDescriptors()
static void dyno::computeDescriptors (const Mat & image, vector< KeyPoint > & keypoints, Mat & descriptors, const vector< Point > & pattern) static
Definition at line 974 of file ORBextractor.cc.
{
  descriptors = Mat::zeros((int)keypoints.size(), 32, CV_8UC1);
  for (size_t i = 0; i < keypoints.size(); i++)
    computeOrbDescriptor(keypoints[i], image, &pattern[0],
                         descriptors.ptr((int)i));
}
References computeOrbDescriptor().
computeMomentOfInertial()
template<typename PointT > void dyno::computeMomentOfInertial (const typename pcl::PointCloud< PointT >::Ptr obj_cloud_ptr, pcl::MomentOfInertiaEstimation< PointT > & bbx_extractor, int mean_k = 100, float std_dev_thresh = 1.0)
Compute a MomentOfInertiaEstimation using an input point cloud.
Applies outlier rejection using the given arguments and then computes the moment of inertial from the input cloud
Template Parameters
PointT A PCL type
Parameters
obj_cloud_ptr const typename pcl::PointCloud<PointT>::Ptr
bbx_extractor pcl::MomentOfInertiaEstimation<PointT>&
mean_k int mean k argument for outlier rejection
std_dev_thresh float std-deviation argument for outlier rejection
Definition at line 208 of file PointCloudProcess.hpp.
{
  pcl::PointCloud<PointT> filtered_cloud;
  // statistical outlier removal
  pcl::StatisticalOutlierRemoval<PointT> outlier_remover;
  outlier_remover.setInputCloud(obj_cloud_ptr);
  outlier_remover.setMeanK(mean_k);
  outlier_remover.setStddevMulThresh(std_dev_thresh);
  outlier_remover.filter(filtered_cloud);
  bbx_extractor.setInputCloud(
      pcl::make_shared<pcl::PointCloud<PointT>>(filtered_cloud));
  bbx_extractor.compute();
}
Referenced by findAABBFromCloud(), and findOBBFromCloud().
computeOrbDescriptor()
static void dyno::computeOrbDescriptor (const KeyPoint & kpt, const Mat & img, const Point * pattern, uchar * desc) static
Definition at line 120 of file ORBextractor.cc.
{
  float angle = (float)kpt.angle * factorPI;
  float a = (float)cos(angle), b = (float)sin(angle);
  const uchar* center = &img.at<uchar>(cvRound(kpt.pt.y), cvRound(kpt.pt.x));
  const int step = (int)img.step;
#define GET_VALUE(idx)                                             \
  center[cvRound(pattern[idx].x * b + pattern[idx].y * a) * step + \
         cvRound(pattern[idx].x * a - pattern[idx].y * b)]
  for (int i = 0; i < 32; ++i, pattern += 16) {
    int t0, t1, val;
    t0 = GET_VALUE(0);
    t1 = GET_VALUE(1);
    val = t0 < t1;
    t0 = GET_VALUE(2);
    t1 = GET_VALUE(3);
    val |= (t0 < t1) << 1;
    t0 = GET_VALUE(4);
    t1 = GET_VALUE(5);
    val |= (t0 < t1) << 2;
    t0 = GET_VALUE(6);
    t1 = GET_VALUE(7);
    val |= (t0 < t1) << 3;
    t0 = GET_VALUE(8);
    t1 = GET_VALUE(9);
    val |= (t0 < t1) << 4;
    t0 = GET_VALUE(10);
    t1 = GET_VALUE(11);
    val |= (t0 < t1) << 5;
    t0 = GET_VALUE(12);
    t1 = GET_VALUE(13);
    val |= (t0 < t1) << 6;
    t0 = GET_VALUE(14);
    t1 = GET_VALUE(15);
    val |= (t0 < t1) << 7;
    desc[i] = (uchar)val;
  }
#undef GET_VALUE
}
References factorPI, and GET_VALUE.
Referenced by computeDescriptors().
computeOrientation()
static void dyno::computeOrientation (const Mat & image, vector< KeyPoint > & keypoints, const vector< int > & umax) static
Definition at line 484 of file ORBextractor.cc.
{
  for (vector<KeyPoint>::iterator keypoint = keypoints.begin(),
                                  keypointEnd = keypoints.end();
       keypoint != keypointEnd; ++keypoint) {
    keypoint->angle = IC_Angle(image, keypoint->pt, umax);
  }
}
References IC_Angle().
Referenced by dyno::ORBextractor::ComputeKeyPointsOctTree(), and dyno::ORBextractor::ComputeKeyPointsOld().
constructArgvC()
char ** dyno::constructArgvC (const std::vector< std::string > & args)
Constructs a c-style pointer array from a vector of strings.
Must be freed
Parameters
args
Returns
char**
Definition at line 49 of file Utils.cc.
{
  char** argv = new char*[args.size()];
  for (size_t i = 0; i < args.size(); i++) {
    const std::string& arg = args.at(i);
    argv[i] = new char[arg.size() + 1];
    strcpy(argv[i], arg.c_str());
  }
  return argv;
}
Referenced by initRosAndLogging().
container_to_string()
template<class Container > std::string dyno::container_to_string (const Container & container, const std::string & delimiter = " ") inline
Definition at line 717 of file Types.hpp.
{
  std::stringstream ss;
  for (const auto& c : container) {
    ss << c << delimiter;
  }
  return ss.str();
}
Referenced by dyno::Frame::constructDynamicObservations(), dyno::RegularBackendModule::constructOutputPacket(), dyno::WorldMotionFormulation::dynamicPointUpdateCallback(), dyno::VirtualKittiTextGtLoader::loadBBoxMetaData(), dyno::ClusterSlamAllLoader::loadLandMarkMapping(), dyno::ClusterSlamAllLoader::loadLeftLandmarks(), main(), dyno::ClusterSlamAllLoader::processPoseFile(), dyno::FeatureTracker::requiresSampling(), dyno::FrameNode< MEASUREMENT >::toString(), dyno::FeatureTracker::track(), and dyno::ParallelObjectISAM::updateStates().
convert() [1/4]
template<typename PointT > bool dyno::convert (const gtsam::Point3 & gtsam_point, PointT & pcl_point)
Definition at line 93 of file PointCloudProcess.hpp.
{
  pcl_point.x = static_cast<decltype(pcl_point.x)>(gtsam_point(0));
  pcl_point.y = static_cast<decltype(pcl_point.y)>(gtsam_point(1));
  pcl_point.z = static_cast<decltype(pcl_point.z)>(gtsam_point(2));
  return true;
}
convert() [2/4]
template<typename Input , typename Output > bool dyno::convert (const Input & , Output &)
convert() [3/4]
template<> bool dyno::convert (const LandmarkStatus & status, pcl::PointXYZRGB & point) inline
Definition at line 55 of file PointCloudProcess.hpp.
{
  const gtsam::Point3 lmk = status.value();
  const ObjectId object_id = status.objectId();
  if (status.isStatic()) {
    point =
        pcl::PointXYZRGB(static_cast<float>(lmk(0)), static_cast<float>(lmk(1)),
                         static_cast<float>(lmk(2)), 0, 0, 0);
  } else {
    // has to recalculate this every time!!
    const Color colour = Color::uniqueId(object_id);
    point = pcl::PointXYZRGB(
        static_cast<float>(lmk(0)), static_cast<float>(lmk(1)),
        static_cast<float>(lmk(2)), static_cast<std::uint8_t>(colour.r),
        static_cast<std::uint8_t>(colour.g),
        static_cast<std::uint8_t>(colour.b));
  }
  return true;
}
References dyno::RGBA< T >::b, dyno::RGBA< T >::g, dyno::TrackedValueStatus< VALUE >::isStatic(), dyno::TrackedValueStatus< VALUE >::objectId(), dyno::RGBA< T >::r, dyno::Color::uniqueId(), and dyno::TrackedValueStatus< VALUE >::value().
Referenced by dyno::DSDTransport::constructMultiObjectOdometryPaths(), dyno::DSDTransport::constructObjectOdometry(), convert_pcl(), rclcpp::TypeAdapter< dyno::ImuMeasurement, sensor_msgs::msg::Imu >::convert_to_custom(), rclcpp::TypeAdapter< dyno::ImuMeasurement, sensor_msgs::msg::Imu >::convert_to_ros_message(), dyno::InbuiltDisplayCommon::createAxisMarkers(), dyno::InbuiltDisplayCommon::createCameraMarker(), dyno::utils::fromRosTime(), dyno::DisplayCommon::objectBBXToRvizMarker(), dyno::HybridModuleDisplayCommon::publishObjectKeyFrames(), dyno::DSDTransport::Publisher::publishObjectTransforms(), dyno::utils::toRosTime(), dyno::RegularBackendModule::updateIncremental(), and dyno::ParallelObjectISAM::updateStates().
convert() [4/4]
template<typename Point > void dyno::convert (const StatusLandmarkVector & status_vector, pcl::PointCloud< Point > & cloud)
Definition at line 87 of file PointCloudProcess.hpp.
{
  convert_pcl(status_vector, cloud);
}
References convert_pcl().
convert_pcl()
template<typename Value , typename Point > void dyno::convert_pcl (const GenericTrackedStatusVector< Value > & status_vector, pcl::PointCloud< Point > & cloud)
Definition at line 75 of file PointCloudProcess.hpp.
{
  for (const auto& value : status_vector) {
    Point point;
    // call the status type to the point type explicitly
    // allows any type w
    convert(value, point);
    cloud.push_back(point);
  }
}
References convert().
Referenced by convert().
ConvertMatToNDArray()
np::ndarray dyno::ConvertMatToNDArray (const cv::Mat & mat)
Definition at line 16 of file PyBoostWrapper.cc.
{
  bp::tuple shape = bp::make_tuple(mat.rows, mat.cols, mat.channels());
  bp::tuple stride =
      bp::make_tuple(mat.channels() * mat.cols * sizeof(uchar),
                     mat.channels() * sizeof(uchar), sizeof(uchar));
  np::dtype dt = np::dtype::get_builtin<uchar>();
  np::ndarray ndImg = np::from_data(mat.data, dt, shape, stride, bp::object());
  return ndImg;
}
Referenced by dyno::PyObjectDetectorWrapper::process().
ConvertNDArrayToMat()
cv::Mat dyno::ConvertNDArrayToMat (const np::ndarray & ndarr)
Definition at line 29 of file PyBoostWrapper.cc.
{
  const Py_intptr_t* shape = ndarr.get_shape();
  char* dtype_str = bp::extract<char*>(bp::str(ndarr.get_dtype()));
  assert(dtype_str != nullptr);
  assert(shape != nullptr);
  int rows = shape[0];
  int cols = shape[1];
  int channel = 1;  // default to 1 (grayscale)
  // determine number of channels from dimensions
  int ndim = ndarr.get_nd();
  if (ndim == 3) {
    channel = shape[2];
  } else if (ndim != 2) {
    std::cerr << "Unsupported ndarray dimensions: " << ndim << std::endl;
    return cv::Mat();
  }
  int depth;
  // determine the depth type
  if (!strcmp(dtype_str, "uint8")) {
    depth = CV_8U;
  } else {
    std::cerr << "Unsupported dtype: " << dtype_str << std::endl;
    return cv::Mat();
  }
  // verify channel count
  if (channel != 1 && channel != 3) {
    std::cerr << "Unsupported number of channels: " << channel << std::endl;
    return cv::Mat();
  }
  int type = CV_MAKETYPE(depth, channel);
  cv::Mat mat(rows, cols, type);
  memcpy(mat.data, ndarr.get_data(), sizeof(uchar) * rows * cols * channel);
  return mat;
}
createDirectory()
bool dyno::createDirectory (const std::string & path)
Create a directory at the given path.
If the directory does not exist it will be created, otherwise nothing happens.
Parameters
path
Returns
true
false
Definition at line 63 of file Logger.cc.
{
  std::filesystem::path dir_path(path);
  // Check if directory already exists
  if (std::filesystem::exists(dir_path)) {
    if (std::filesystem::is_directory(dir_path)) {
      VLOG(10) << "Directory already exists: " << path;
      return true;
    } else {
      VLOG(10) << "Path exists but is not a directory: " << path;
      return false;
    }
  }
  // Create directory if it doesn't exist
  if (std::filesystem::create_directories(dir_path)) {
    VLOG(10) << "Directory created: " << path;
    return true;
  } else {
    LOG(WARNING) << "Failed to create directory: " << path;
    return false;
  }
}
Referenced by dyno::vision_tools::writeOutProjectMaskAndDepthMap().
DataProviderRos::convertRosImage< ImageType::Depth >()
template<> const cv::Mat dyno::DataProviderRos::convertRosImage< ImageType::Depth > (const sensor_msgs::msg::Image::ConstSharedPtr & img_msg) const
Definition at line 46 of file DataProviderRos.cc.
{
  const cv_bridge::CvImageConstPtr cvb_image = readRosImage(img_msg);
  const cv::Mat img = cvb_image->image;
  try {
    image_traits<ImageType::Depth>::validate(img);
    return img;
  } catch (const InvalidImageTypeException& exception) {
    // handle the case its a float32
    if (img.type() == CV_32FC1) {
      cv::Mat depth64;
      img.convertTo(depth64, CV_64FC1);
      image_traits<ImageType::Depth>::validate(depth64);
      return depth64;
    } else if (img.type() == CV_16UC1) {
      cv::Mat depth64;
      img.convertTo(depth64, CV_64FC1);
      image_traits<ImageType::Depth>::validate(depth64);
      return depth64;
    }
    RCLCPP_FATAL_STREAM(node_->get_logger(),
                        image_traits<ImageType::Depth>::name()
                            << " Image msg was of the wrong type (validate "
                               "failed with exception "
                            << exception.what() << "). "
                            << "ROS encoding type used was "
                            << cvb_image->encoding);
    rclcpp::shutdown();
    return cv::Mat();
  }
}
Referenced by dyno::DataProviderRos::readDepthRosImage().
declare_config() [1/14]
void dyno::declare_config (CameraParams & config)
Definition at line 65 of file CameraParams.cc.
{
  using namespace config;
  name("Camera Params");
  cv::Size image_size;
  field(image_size, "resolution");
  // camera to robot pose
  std::vector<double> vector_pose;
  field(vector_pose, "T_BS");
  checkCondition(
      vector_pose.size() == 16u,
      "param 'T_BS' must be a 16 length vector in homogenous matrix form");
  gtsam::Pose3 T_robot_camera = utils::poseVectorToGtsamPose3(vector_pose);
  std::vector<double> intrinsics_v;
  field(intrinsics_v, "intrinsics");
  checkCondition(intrinsics_v.size() == 4,
                 "param 'intrinsics' must be a 4 length vector.");
  CameraParams::IntrinsicsCoeffs intrinsics;
  intrinsics.resize(4u);
  // Move elements from one to the other.
  std::copy_n(std::make_move_iterator(intrinsics_v.begin()), intrinsics.size(),
              intrinsics.begin());
  CameraParams::DistortionCoeffs distortion;
  field(distortion, "distortion_coefficients");
  std::string distortion_model, camera_model;
  field(distortion_model, "distortion_model");
  field(camera_model, "camera_model");
  DistortionModel model =
      CameraParams::stringToDistortion(distortion_model, camera_model);
  if (model == DistortionModel::NONE) {
    throw InvalidCameraCalibration(
        "Invalid distortion model/camera model combination when constructing "
        "camera params from yaml file - "
        " distortion model: " +
        distortion_model + ", camera model: " + camera_model);
  }
  config =
      CameraParams(intrinsics, distortion, image_size, model, T_robot_camera);
}
References NONE, dyno::utils::poseVectorToGtsamPose3(), and dyno::CameraParams::stringToDistortion().
declare_config() [2/14]
void dyno::declare_config (DynoParams::PipelineParams & config)
Definition at line 49 of file PipelineParams.cc.
{
  using namespace config;
  name("PipelineParams");
  field(config.parallel_run, "parallel_run");
  field(config.prefer_data_provider_camera_params,
        "prefer_data_provider_camera_params");
  field(config.prefer_data_provider_imu_params,
        "prefer_data_provider_imu_params");
  config.data_provider_type = FLAGS_data_provider_type;
}
declare_config() [3/14]
void dyno::declare_config (EgoMotionSolver::Params & config)
Definition at line 94 of file MotionSolver.cc.
{
  using namespace config;
  name("EgoMotionSolver::Params");
  field(config.ransac_randomize, "ransac_randomize");
  field(config.ransac_use_2point_mono, "ransac_use_2point_mono");
  field(config.optimize_2d2d_pose_from_inliers,
        "optimize_2d2d_pose_from_inliers");
  field(config.ransac_threshold_pnp, "ransac_threshold_pnp");
  field(config.optimize_3d2d_pose_from_inliers,
        "optimize_3d2d_pose_from_inliers");
  field(config.ransac_threshold_stereo, "ransac_threshold_stereo");
  field(config.optimize_3d3d_pose_from_inliers,
        "optimize_3d3d_pose_from_inliers");
  field(config.ransac_iterations, "ransac_iterations");
  field(config.ransac_probability, "ransac_probability");
}
declare_config() [4/14]
void dyno::declare_config (FrontendParams & config)
Definition at line 47 of file FrontendParams.cc.
{
  using namespace config;
  name("FrontendParams");
  field(config.scene_flow_magnitude, "scene_flow_magnitude");
  field(config.scene_flow_percentage, "scene_flow_percentage");
  field(config.max_background_depth, "max_background_depth");
  field(config.max_object_depth, "max_object_depth");
  field(config.use_ego_motion_pnp, "use_ego_motion_pnp");
  field(config.use_object_motion_pnp, "use_object_motion_pnp");
  field(config.refine_camera_pose_with_joint_of,
        "refine_camera_pose_with_joint_of");
  field(config.object_motion_solver_params, "object_motion_solver");
  field(config.ego_motion_solver_params, "camera_motion_solver");
  field(config.tracker_params, "tracker_params");
  field(config.image_tracks_vis_params, "image_tracks_vis_params");
  // update with flags
  config.object_motion_solver_params.refine_motion_with_joint_of =
      FLAGS_refine_with_optical_flow;
  config.object_motion_solver_params.refine_motion_with_3d =
      FLAGS_refine_motion_estimate;
  LOG(INFO) << "config.object_motion_solver_params.refine_motion_with_joint_of "
            << config.object_motion_solver_params.refine_motion_with_joint_of;
}
declare_config() [5/14]
void dyno::declare_config (ImageTracksParams & config)
Definition at line 332 of file FeatureTrackerBase.cc.
{
  using namespace config;
  name("ImageTracksParams");
  field(config.feature_thickness_debug, "feature_thickness_debug");
  field(config.feature_thickness, "feature_thickness");
  field(config.bbox_thickness_debug, "bbox_thickness_debug");
  field(config.bbox_thickness, "bbox_thickness");
  field(config.show_frame_info, "show_frame_info");
  field(config.show_intermediate_tracking, "show_intermediate_tracking");
  field(config.draw_object_bounding_box, "draw_object_bounding_box");
  field(config.draw_object_mask, "draw_object_mask");
  field(config.is_debug, "is_debug");
}
declare_config() [6/14]
void dyno::declare_config (ImuParams & config)
Definition at line 38 of file ImuParams.cc.
{
  using namespace config;
  name("ImuParams");
}
declare_config() [7/14]
void dyno::declare_config (MotionOnlyRefinementOptimizer::Params & config)
Definition at line 84 of file MotionSolver.cc.
{
  using namespace config;
  name("MotionOnlyRefinementOptimizerParams");
  field(config.landmark_motion_sigma, "landmark_motion_sigma");
  field(config.projection_sigma, "projection_sigma");
  field(config.k_huber, "k_huber");
  field(config.outlier_reject, "outlier_reject");
}
declare_config() [8/14]
void dyno::declare_config (ObjectMotionSovlerF2F::Params & config)
Definition at line 111 of file MotionSolver.cc.
{
  using namespace config;
  name("ObjectMotionSovlerF2F::Params");
  base<EgoMotionSolver::Params>(config);
  field(config.refine_motion_with_joint_of, "refine_motion_with_joint_of");
  field(config.refine_motion_with_3d, "refine_motion_with_3d");
  field(config.joint_of_params, "joint_optical_flow");
  field(config.object_motion_refinement_params, "object_motion_3d_refinement");
}
declare_config() [9/14]
void dyno::declare_config (OpticalFlowAndPoseOptimizer::Params & config)
Definition at line 73 of file MotionSolver.cc.
{
  using namespace config;
  name("OpticalFlowAndPoseOptimizerParams");
  field(config.flow_sigma, "flow_sigma");
  field(config.flow_prior_sigma, "flow_prior_sigma");
  field(config.k_huber, "k_huber");
  field(config.outlier_reject, "outlier_reject");
  field(config.flow_is_future, "flow_is_future");
}
declare_config() [10/14]
void dyno::declare_config (TrackerParams & config)
Definition at line 88 of file TrackerParams.cc.
{
  using namespace config;
  name("TrackerParams");
  enum_field(config.feature_detector_type, "feature_detector_type",
             std::vector<std::string>({"GFTT", "ORB_SLAM_ORB", "GFFT_CUDA"}));
  field(config.use_anms, "use_anms");
  field(config.use_subpixel_corner_refinement,
        "use_subpixel_corner_refinement");
  field(config.use_clahe_filter, "use_clahe_filter");
  field(config.max_nr_keypoints_before_anms, "max_nr_keypoints_before_anms");
  field(config.min_distance_btw_tracked_and_detected_static_features,
        "min_distance_btw_tracked_and_detected_static_features");
  field(config.min_distance_btw_tracked_and_detected_dynamic_features,
        "min_distance_btw_tracked_and_detected_dynamic_features");
  field(config.max_features_per_frame, "max_features_per_frame");
  field(config.min_features_per_frame, "min_features_per_frame");
  field(config.max_feature_track_age, "max_feature_track_age");
  field(config.shrink_row, "shrink_row");
  field(config.shrink_col, "shrink_col");
  // update with FLAGS
  config.shrink_row = FLAGS_shrink_row;
  config.shrink_col = FLAGS_shrink_col;
  field(config.anms_params, "anms_params");
  field(config.subpixel_corner_refinement_params,
        "subpixel_corner_refinement_params");
  field(config.gfft_params, "gfft_params");
  field(config.orb_params, "orb_params");
  field(config.max_dynamic_features_per_frame,
        "max_dynamic_features_per_frame");
  field(config.max_dynamic_feature_age, "max_dynamic_feature_age");
  field(config.dynamic_feature_age_buffer, "dynamic_feature_age_buffer");
  field(config.min_dynamic_tracks, "min_dynamic_tracks");
  field(config.min_dynamic_mask_iou, "min_dynamic_mask_iou");
  field(config.use_propogate_mask, "use_propogate_mask");
  field(config.prefer_provided_optical_flow, "prefer_provided_optical_flow");
  field(config.prefer_provided_object_detection,
        "prefer_provided_object_detection");
  // update with FLAGS
  // config.semantic_mask_step_size = FLAGS_semantic_mask_step_size;
  config.use_propogate_mask = FLAGS_use_propogate_mask;
}
declare_config() [11/14]
void dyno::declare_config (TrackerParams::AnmsParams & config)
Definition at line 50 of file TrackerParams.cc.
{
  using namespace config;
  name("AnmsParams");
  enum_field(
      config.non_max_suppression_type, "non_max_suppression_type",
      {"TopN", "BrownANMS", "SDC", "KdTree", "RangeTree", "Ssc", "Binning"});
  field(config.nr_horizontal_bins, "nr_horizontal_bins");
  field(config.nr_vertical_bins, "nr_vertical_bins");
  field(config.binning_mask, "binning_mask");
}
declare_config() [12/14]
void dyno::declare_config (TrackerParams::GFFTParams & config)
Definition at line 70 of file TrackerParams.cc.
{
  using namespace config;
  name("GFFTParams");
  field(config.quality_level, "quality_level");
  field(config.block_size, "block_size");
  field(config.use_harris_corner_detector, "use_harris_corner_detector");
  field(config.k, "k");
}
declare_config() [13/14]
void dyno::declare_config (TrackerParams::OrbParams & config)
Definition at line 79 of file TrackerParams.cc.
{
  using namespace config;
  name("OrbParams");
  field(config.scale_factor, "scale_factor");
  field(config.n_levels, "n_levels");
  field(config.init_threshold_fast, "init_threshold_fast");
  field(config.min_threshold_fast, "min_threshold_fast");
}
declare_config() [14/14]
void dyno::declare_config (TrackerParams::SubPixelCornerRefinementParams & config)
Definition at line 63 of file TrackerParams.cc.
{
  using namespace config;
  name("SubPixelCornerRefinementParams");
  field(config.window_size, "window_size");
  field(config.zero_zone, "zero_zone");
}
deg2Rads()
double dyno::deg2Rads (double degrees) inline
Converts degrees to radians.
Parameters
degrees
Returns
double
Definition at line 106 of file Numerical.hpp.
{ return degrees * M_PI / 180.0; }
demangle()
std::string dyno::demangle (const char * name)
Get demangled class name.
Parameters
name
Returns
std::string
Definition at line 83 of file Types.cc.
{
  // by default set to the original mangled name
  std::string demangled_name = std::string(name);
  // g++ version of demangle
  char* demangled = nullptr;
  int status = -1;  // some arbitrary value to eliminate the compiler warning
  demangled = abi::__cxa_demangle(name, nullptr, nullptr, &status);
  demangled_name = (status == 0) ? std::string(demangled) : std::string(name);
  std::free(demangled);
  return demangled_name;
}
Referenced by type_name().
deserializeEngine() [1/2]
EnginePtr dyno::deserializeEngine (IRuntime & runtime, const std::filesystem::path & engine_path)
Definition at line 336 of file TrtUtilities.cc.
{
  std::ifstream engine_file(engine_path, std::ios::binary);
  if (engine_file.fail()) {
    LOG(INFO) << "Engine file: " << engine_path << " not found!";
    return nullptr;
  }
  const auto engine_size = std::filesystem::file_size(engine_path);
  std::vector<char> engine_data(engine_size);
  engine_file.read(engine_data.data(), engine_size);
  EnginePtr engine(
      runtime.deserializeCudaEngine(engine_data.data(), engine_size));
  if (!engine) {
    LOG(ERROR) << "Engine deserialization failed for " << engine_path;
    return nullptr;
  }
  return engine;
}
deserializeEngine() [2/2]
EnginePtr dyno::deserializeEngine (nvinfer1::IRuntime & runtime, const std::filesystem::path & engine_path)
determineOutlierIds()
void dyno::determineOutlierIds (const TrackletIds & inliers, const TrackletIds & tracklets, TrackletIds & outliers)
From a set a tracklets and a subset (of the tracklet) inliers, calculate the remaining subset of outliers.
In set notation this is: inliers \cap outliers = \empty (indicating that inliers and outliers are disjoint) inliers \cup outliers = tracklets (indicating that every element in tracklets is either in inliers or outliers)
Inliers must be a complete subset of tracklets for this function to work and inliers.size() < tracklets.size(); if these cases do not hold the behaviour is undefined!
Parameters
inliers const TrackletIds&
tracklets const TrackletIds&
outliers TrackletIds&
Definition at line 744 of file VisionTools.cc.
{
  VLOG_IF(1, inliers.size() > tracklets.size())
      << "Usage warning: inlier size (" << inliers.size()
      << ") > tracklets size (" << tracklets.size()
      << "). Are you parsing inliers as tracklets incorrectly?";
  outliers.clear();
  TrackletIds inliers_sorted(inliers.size()),
      tracklets_sorted(tracklets.size());
  std::copy(inliers.begin(), inliers.end(), inliers_sorted.begin());
  std::copy(tracklets.begin(), tracklets.end(), tracklets_sorted.begin());
  std::sort(inliers_sorted.begin(), inliers_sorted.end());
  std::sort(tracklets_sorted.begin(), tracklets_sorted.end());
  // full set A (tracklets) must be first and inliers MUST be a subset of A for
  // the set_difference function to work
  std::set_difference(tracklets_sorted.begin(), tracklets_sorted.end(),
                      inliers_sorted.begin(), inliers_sorted.end(),
                      std::inserter(outliers, outliers.begin()));
}
Referenced by dyno::EgoMotionSolver::constructTrackletInliers(), dyno::ObjectMotionSovlerF2F::geometricOutlierRejection3d2d(), dyno::MotionOnlyRefinementOptimizer::optimize(), dyno::FeatureTracker::stereoTrack(), and dyno::KltFeatureTracker::trackPoints().
dis()
std::uniform_int_distribution< uint8_t > dyno::dis (0 , 255)
Referenced by dyno::Color::random().
DynamicLandmarkSymbol()
DynamicPointSymbol dyno::DynamicLandmarkSymbol (FrameId frame_id, TrackletId tracklet_id) inline
Definition at line 139 of file Symbols.hpp.
{
  return DynamicPointSymbol(kDynamicLandmarkSymbolChar, tracklet_id, frame_id);
}
References kDynamicLandmarkSymbolChar.
Referenced by dyno::HybridFormulationProperties::makeDynamicKey(), dyno::LandmarkNode< MEASUREMENT >::makeDynamicSymbol(), and dyno::MotionOnlyRefinementOptimizer::optimize().
DynoChrExtractor()
SymbolChar dyno::DynoChrExtractor (gtsam::Key key)
Definition at line 64 of file Symbols.cc.
{
  const gtsam::LabeledSymbol asLabeledSymbol(key);
  if (asLabeledSymbol.chr() > 0 && asLabeledSymbol.label() > 0) {
    return asLabeledSymbol.chr();
  }
  const gtsam::Symbol asSymbol(key);
  if (asLabeledSymbol.chr() > 0) {
    return asSymbol.chr();
  } else {
    return InvalidDynoSymbol;
  }
}
References InvalidDynoSymbol.
DynosamKeyFormatter()
std::string dyno::DynosamKeyFormatter (gtsam::Key key)
Definition at line 135 of file Symbols.cc.
{
  const gtsam::LabeledSymbol asLabeledSymbol(key);
  if (asLabeledSymbol.chr() > 0 && asLabeledSymbol.label() > 0) {
    // if used as motion
    if (asLabeledSymbol.chr() == kObjectMotionSymbolChar ||
        asLabeledSymbol.chr() == kObjectPoseSymbolChar) {
      return (std::string)asLabeledSymbol;
    }
    return (std::string)asLabeledSymbol;
  }
  const gtsam::Symbol asSymbol(key);
  if (asLabeledSymbol.chr() > 0) {
    if (asLabeledSymbol.chr() == kDynamicLandmarkSymbolChar) {
      const DynamicPointSymbol asDynamicPointSymbol(key);
      return (std::string)asDynamicPointSymbol;
    } else {
      return (std::string)asSymbol;
    }
  } else {
    return std::to_string(key);
  }
}
References kDynamicLandmarkSymbolChar, kObjectMotionSymbolChar, and kObjectPoseSymbolChar.
Referenced by dyno::Formulation< MAP >::formatter(), dyno::BayesTreeMarginalizationHelper< BayesTree >::gatherAdditionalKeysToReEliminate(), dyno::StateQuery< ValueType >::get(), dyno::BayesTreeMarginalizationHelper< BayesTree >::getCliquesContainingKeys(), dyno::ParallelHybridBackendModule::logGraphs(), dyno::HybridFormulation::objectUpdateContext(), dyno::WorldPoseFormulation::objectUpdateContext(), dyno::ParallelHybridBackendModule::ParallelHybridBackendModule(), dyno::test_hybrid::SmartStructurlessFormulation::postUpdate(), dyno::SmartMotionFactor< DIM, MOTION, POSE >::print(), dyno::RegularBackendModule::setupUpdates(), and dyno::IncrementalInterface< SMOOTHER >::updateSmoother().
DynosamKeyFormatterVerbose()
std::string dyno::DynosamKeyFormatterVerbose (gtsam::Key key)
Definition at line 89 of file Symbols.cc.
{
  const gtsam::LabeledSymbol asLabeledSymbol(key);
  if (asLabeledSymbol.chr() > 0 && asLabeledSymbol.label() > 0) {
    // if used as motion
    if (asLabeledSymbol.chr() == kObjectMotionSymbolChar) {
      ObjectId object_label;
      FrameId frame_id;
      CHECK(reconstructMotionInfo(asLabeledSymbol, object_label, frame_id));
      std::stringstream ss;
      ss << "H: label" << object_label << ", frames: " << frame_id - 1 << " -> "
         << frame_id;
      return ss.str();
    } else if (asLabeledSymbol.chr() == kObjectPoseSymbolChar) {
      ObjectId object_label;
      FrameId frame_id;
      CHECK(reconstructPoseInfo(asLabeledSymbol, object_label, frame_id));
      std::stringstream ss;
      ss << "K: label" << object_label << ", frame: " << frame_id;
      return ss.str();
    }
    return (std::string)asLabeledSymbol;
  }
  const gtsam::Symbol asSymbol(key);
  if (asLabeledSymbol.chr() > 0) {
    if (asLabeledSymbol.chr() == kDynamicLandmarkSymbolChar) {
      const DynamicPointSymbol asDynamicPointSymbol(key);
      FrameId frame_id = asDynamicPointSymbol.frameId();
      TrackletId tracklet_id = asDynamicPointSymbol.trackletId();
      std::stringstream ss;
      ss << kDynamicLandmarkSymbolChar << ": frame " << frame_id
         << ", tracklet " << tracklet_id;
      return ss.str();
    } else {
      return (std::string)asSymbol;
    }
  } else {
    return std::to_string(key);
  }
}
References dyno::DynamicPointSymbol::frameId(), kDynamicLandmarkSymbolChar, kObjectMotionSymbolChar, kObjectPoseSymbolChar, reconstructMotionInfo(), reconstructPoseInfo(), and dyno::DynamicPointSymbol::trackletId().
equals_with_abs_tol()
template<typename T > bool dyno::equals_with_abs_tol (const std::vector< T > & vec1, const std::vector< T > & vec2, double tol = 1e-9) inline
Definition at line 195 of file Numerical.hpp.
{
  if (vec1.size() != vec2.size()) return false;
  const size_t m = vec1.size();
  for (size_t i = 0; i < m; i++) {
    if (!fpEqual(vec1[i], vec2[i], tol)) {
      return false;
    }
  }
  return true;
}
References fpEqual().
Referenced by dyno::CameraParams::equals(), and dyno::FeatureTracker::requiresSampling().
executePythonCall()
template<typename Func > auto dyno::executePythonCall (Func && func) -> decltype(func())
Definition at line 33 of file PyBoostWrapper.hpp.
{
  PyGILGuard guard;
  try {
    return func();
  } catch (bp::error_already_set&) {
    PyErr_Print();
    throw;
  }
}
Referenced by dyno::PyObjectDetectorWrapper::process(), and dyno::PyObjectDetectorWrapper::result().
exponentialOffsetId()
float dyno::exponentialOffsetId (size_t id, size_t ids_per_revolution)
Map a potentially infinite number of ids to a never repeating pattern in [0, 1].
Definition at line 158 of file Colour.cc.
{
  const size_t revolution = id / ids_per_revolution;
  const float progress_along_revolution =
      std::fmod(static_cast<float>(id) / ids_per_revolution, 1.f);
  float offset = 0.0f;
  if (ids_per_revolution < id + 1u) {
    const size_t current_episode = std::floor(std::log2(revolution));
    const size_t episode_start = std::exp2(current_episode);
    const size_t current_subdivision = revolution - episode_start;
    const float subdivision_step_size =
        1.0f / (ids_per_revolution * 2 * episode_start);
    offset = (2.0f * current_subdivision + 1) * subdivision_step_size;
  }
  return progress_along_revolution + offset;
}
Referenced by dyno::Color::rainbowId().
findAABBFromCloud() [1/2]
ObjectBBX dyno::findAABBFromCloud (const pcl::PointCloud< pcl::PointXYZRGB >::Ptr obj_cloud_ptr)
Definition at line 65 of file PointCloudProcess.cc.
{
  pcl::PointCloud<pcl::PointXYZRGB> filtered_cloud;
  // statistical outlier removal
  pcl::StatisticalOutlierRemoval<pcl::PointXYZRGB> outlier_remover;
  outlier_remover.setInputCloud(obj_cloud_ptr);
  outlier_remover.setMeanK(100);
  outlier_remover.setStddevMulThresh(1.0);
  outlier_remover.filter(filtered_cloud);
  // axis aligned bounding box
  pcl::MomentOfInertiaEstimation<pcl::PointXYZRGB> bbx_extractor;
  bbx_extractor.setInputCloud(
      pcl::make_shared<pcl::PointCloud<pcl::PointXYZRGB> >(filtered_cloud));
  bbx_extractor.compute();
  pcl::PointXYZRGB min_point_AABB;
  pcl::PointXYZRGB max_point_AABB;
  bbx_extractor.getAABB(min_point_AABB, max_point_AABB);
  ObjectBBX aabb;
  aabb.min_bbx_point_ = gtsam::Point3(static_cast<double>(min_point_AABB.x),
                                      static_cast<double>(min_point_AABB.y),
                                      static_cast<double>(min_point_AABB.z));
  aabb.max_bbx_point_ = gtsam::Point3(static_cast<double>(max_point_AABB.x),
                                      static_cast<double>(max_point_AABB.y),
                                      static_cast<double>(max_point_AABB.z));
  return aabb;
}
References dyno::ObjectBBX::max_bbx_point_, and dyno::ObjectBBX::min_bbx_point_.
findAABBFromCloud() [2/2]
template<typename PointT > ObjectBBX dyno::findAABBFromCloud (const typename pcl::PointCloud< PointT >::Ptr obj_cloud_ptr)
Compute the Axis Aligned Bounding Box (AABB) from an input cloud.
The returned ObjectBBX only has the min and max bbx point set.
Template Parameters
PointT A PCL type
Parameters
obj_cloud_ptr const typename pcl::PointCloud<PointT>::Ptr
Returns
ObjectBBX
Definition at line 236 of file PointCloudProcess.hpp.
{
  pcl::PointCloud<PointT> filtered_cloud;
  pcl::MomentOfInertiaEstimation<PointT> bbx_extractor;
  computeMomentOfInertial(obj_cloud_ptr, bbx_extractor);
  PointT min_point_AABB;
  PointT max_point_AABB;
  bbx_extractor.getAABB(min_point_AABB, max_point_AABB);
  ObjectBBX aabb;
  aabb.min_bbx_point_ = pclPointToGtsam(min_point_AABB);
  aabb.max_bbx_point_ = pclPointToGtsam(max_point_AABB);
  return aabb;
}
References computeMomentOfInertial(), dyno::ObjectBBX::max_bbx_point_, dyno::ObjectBBX::min_bbx_point_, and pclPointToGtsam().
findLineListPointsFromAABBMinMax() [1/2]
template<> pcl::PointCloud< pcl::PointXYZ > dyno::findLineListPointsFromAABBMinMax (const gtsam::Point3 & min_point_AABB, const gtsam::Point3 & max_point_AABB) inline
Specalise function on gtsam::Point3 type.
gtsam::Point3 does not follow the expect concept definition of a pcl::PointXYZ type (i.e x is a function, not a property)
Definition at line 354 of file PointCloudProcess.hpp.
{
  pcl::PointXYZ min_point_AABB_pcl =
      pcl::PointXYZ((float)min_point_AABB.x(), (float)min_point_AABB.y(),
                    (float)min_point_AABB.z());
  pcl::PointXYZ max_point_AABB_pcl =
      pcl::PointXYZ((float)max_point_AABB.x(), (float)max_point_AABB.y(),
                    (float)max_point_AABB.z());
  return findLineListPointsFromAABBMinMax<pcl::PointXYZ>(min_point_AABB_pcl,
                                                         max_point_AABB_pcl);
}
findLineListPointsFromAABBMinMax() [2/2]
template<typename PointT > pcl::PointCloud< pcl::PointXYZ > dyno::findLineListPointsFromAABBMinMax (const PointT & min_point_AABB, const PointT & max_point_AABB)
Definition at line 287 of file PointCloudProcess.hpp.
{
  pcl::PointCloud<pcl::PointXYZ> line_list_points;
  // bottom
  line_list_points.push_back(
      pcl::PointXYZ(min_point_AABB.x, min_point_AABB.y, min_point_AABB.z));
  line_list_points.push_back(
      pcl::PointXYZ(max_point_AABB.x, min_point_AABB.y, min_point_AABB.z));
  line_list_points.push_back(
      pcl::PointXYZ(max_point_AABB.x, min_point_AABB.y, min_point_AABB.z));
  line_list_points.push_back(
      pcl::PointXYZ(max_point_AABB.x, max_point_AABB.y, min_point_AABB.z));
  line_list_points.push_back(
      pcl::PointXYZ(min_point_AABB.x, min_point_AABB.y, min_point_AABB.z));
  line_list_points.push_back(
      pcl::PointXYZ(min_point_AABB.x, max_point_AABB.y, min_point_AABB.z));
  line_list_points.push_back(
      pcl::PointXYZ(min_point_AABB.x, max_point_AABB.y, min_point_AABB.z));
  line_list_points.push_back(
      pcl::PointXYZ(max_point_AABB.x, max_point_AABB.y, min_point_AABB.z));
  // top
  line_list_points.push_back(
      pcl::PointXYZ(min_point_AABB.x, min_point_AABB.y, max_point_AABB.z));
  line_list_points.push_back(
      pcl::PointXYZ(max_point_AABB.x, min_point_AABB.y, max_point_AABB.z));
  line_list_points.push_back(
      pcl::PointXYZ(max_point_AABB.x, min_point_AABB.y, max_point_AABB.z));
  line_list_points.push_back(
      pcl::PointXYZ(max_point_AABB.x, max_point_AABB.y, max_point_AABB.z));
  line_list_points.push_back(
      pcl::PointXYZ(min_point_AABB.x, min_point_AABB.y, max_point_AABB.z));
  line_list_points.push_back(
      pcl::PointXYZ(min_point_AABB.x, max_point_AABB.y, max_point_AABB.z));
  line_list_points.push_back(
      pcl::PointXYZ(min_point_AABB.x, max_point_AABB.y, max_point_AABB.z));
  line_list_points.push_back(
      pcl::PointXYZ(max_point_AABB.x, max_point_AABB.y, max_point_AABB.z));
  // vertical
  line_list_points.push_back(
      pcl::PointXYZ(min_point_AABB.x, min_point_AABB.y, min_point_AABB.z));
  line_list_points.push_back(
      pcl::PointXYZ(min_point_AABB.x, min_point_AABB.y, max_point_AABB.z));
  line_list_points.push_back(
      pcl::PointXYZ(min_point_AABB.x, max_point_AABB.y, min_point_AABB.z));
  line_list_points.push_back(
      pcl::PointXYZ(min_point_AABB.x, max_point_AABB.y, max_point_AABB.z));
  line_list_points.push_back(
      pcl::PointXYZ(max_point_AABB.x, min_point_AABB.y, min_point_AABB.z));
  line_list_points.push_back(
      pcl::PointXYZ(max_point_AABB.x, min_point_AABB.y, max_point_AABB.z));
  line_list_points.push_back(
      pcl::PointXYZ(max_point_AABB.x, max_point_AABB.y, min_point_AABB.z));
  line_list_points.push_back(
      pcl::PointXYZ(max_point_AABB.x, max_point_AABB.y, max_point_AABB.z));
  return line_list_points;
}
Referenced by dyno::InbuiltDisplayCommon::constructBoundingBoxeMarkers(), and dyno::FrontendInbuiltDisplayRos::processRGBDOutputpacket().
findOBBFromCloud()
template<typename PointT > ObjectBBX dyno::findOBBFromCloud (const typename pcl::PointCloud< PointT >::Ptr obj_cloud_ptr)
Compute Oriented bounding box (OBB) from an input point cloud.
The returned ObjectBBX has the min/max bbx point set, as well as the position and orientation
Template Parameters
PointT PointT A PCL type.
Parameters
obj_cloud_ptr const typename pcl::PointCloud<PointT>::Ptr.
Returns
ObjectBBX
Definition at line 265 of file PointCloudProcess.hpp.
{
  // oriented aligned bounding box
  pcl::MomentOfInertiaEstimation<PointT> bbx_extractor;
  computeMomentOfInertial(obj_cloud_ptr, bbx_extractor);
  PointT min_point_AABB;
  PointT max_point_AABB;
  PointT position;
  Eigen::Matrix3f orientation;
  bbx_extractor.getOBB(min_point_AABB, max_point_AABB, position, orientation);
  ObjectBBX obb;
  obb.min_bbx_point_ = pclPointToGtsam(min_point_AABB);
  obb.max_bbx_point_ = pclPointToGtsam(max_point_AABB);
  obb.bbx_position_ = pclPointToGtsam(position);
  obb.orientation_ = gtsam::Rot3(orientation.cast<double>());
  return obb;
}
References dyno::ObjectBBX::bbx_position_, computeMomentOfInertial(), dyno::ObjectBBX::max_bbx_point_, dyno::ObjectBBX::min_bbx_point_, dyno::ObjectBBX::orientation_, and pclPointToGtsam().
fpEqual()
bool dyno::fpEqual (double a, double b, double tol = 1e-9) inline
Float point comparison up to a tolerance.
Wrapper on gtsam::fpEqual
Parameters
a
b
tol
Returns
true
false
Definition at line 77 of file Numerical.hpp.
{
  return gtsam::fpEqual(a, b, tol);
}
Referenced by equals_with_abs_tol(), is_zero(), and dyno::Feature::impl::operator==().
from_json() [1/5]
void dyno::from_json (const json & j, GroundTruthInputPacket & gt_packet)
Implements the required from_json (deseralizes) function for the nlohmann::json to automatically load GroundTruthInputPacket from a json object.
Parameters
j const json&
gt_packet GroundTruthInputPacket&
Definition at line 390 of file GroundTruthPacket.cc.
{
  gt_packet.timestamp_ = j["timestamp"].template get<Timestamp>();
  gt_packet.frame_id_ = j["frame_id"].template get<FrameId>();
  gt_packet.X_world_ = j["X_world"].template get<gtsam::Pose3>();
  gt_packet.object_poses_ =
      j["objects"].template get<std::vector<ObjectPoseGT>>();
}
References dyno::GroundTruthInputPacket::frame_id_, dyno::GroundTruthInputPacket::object_poses_, dyno::GroundTruthInputPacket::timestamp_, and dyno::GroundTruthInputPacket::X_world_.
from_json() [2/5]
void dyno::from_json (const json & j, GroundTruthPacketMap & gt_packet_map)
Implements the required from_json (deseralizes) function for the nlohmann::json to automatically load GroundTruthPacketMap from a json object.
Parameters
j const json&
gt_packet_map GroundTruthPacketMap&
Definition at line 405 of file GroundTruthPacket.cc.
{
  std::map<FrameId, GroundTruthInputPacket> stl_map =
      j["ground_truths"]
          .template get<std::map<FrameId, GroundTruthInputPacket>>();
  // have to do manual conversion to stl map so the json library can do
  // automagic conversion lots of copying
  gt_packet_map = GroundTruthPacketMap(stl_map.begin(), stl_map.end());
}
from_json() [3/5]
void dyno::from_json (const json & j, Histogram & histogram)
Definition at line 66 of file Histogram.cc.
{}
from_json() [4/5]
void dyno::from_json (const json & j, ObjectPoseGT & object_pose_gt)
Implements the required from_json (deseralizes) function for the nlohmann::json to automatically load ObjectPoseGT from a json object.
Used internally when deseralizing the GroundTruthInputPacket.
Parameters
j const json&
object_pose_gt ObjectPoseGT&
Definition at line 362 of file GroundTruthPacket.cc.
{
  object_pose_gt.frame_id_ = j["frame_id"].template get<FrameId>();
  object_pose_gt.object_id_ = j["object_id"].template get<ObjectId>();
  object_pose_gt.L_camera_ = j["L_camera"].template get<gtsam::Pose3>();
  object_pose_gt.L_world_ = j["L_world"].template get<gtsam::Pose3>();
  object_pose_gt.bounding_box_ = j["bounding_box"].template get<cv::Rect>();
  object_pose_gt.object_dimensions_ =
      j["object_dimensions"].template get<std::optional<gtsam::Vector3>>();
  object_pose_gt.prev_H_current_world_ =
      j["prev_H_current_world"].template get<std::optional<gtsam::Pose3>>();
  object_pose_gt.prev_H_current_L_ =
      j["prev_H_current_L"].template get<std::optional<gtsam::Pose3>>();
  object_pose_gt.prev_H_current_X_ =
      j["prev_H_current_X"].template get<std::optional<gtsam::Pose3>>();
  object_pose_gt.motion_info_ =
      j["motion_info"].template get<std::optional<ObjectPoseGT::MotionInfo>>();
}
References dyno::ObjectPoseGT::bounding_box_, dyno::ObjectPoseGT::frame_id_, dyno::ObjectPoseGT::L_camera_, dyno::ObjectPoseGT::L_world_, dyno::ObjectPoseGT::motion_info_, dyno::ObjectPoseGT::object_dimensions_, dyno::ObjectPoseGT::object_id_, dyno::ObjectPoseGT::prev_H_current_L_, dyno::ObjectPoseGT::prev_H_current_world_, and dyno::ObjectPoseGT::prev_H_current_X_.
from_json() [5/5]
void dyno::from_json (const json & j, ObjectPoseGT::MotionInfo & motion_info)
Implements the required from_json (deseralizes) function for the nlohmann::json to automatically load ObjectPoseGT::MotionInfo from a json object.
Used internally when deseralizing the ObjectPoseGT.
Parameters
j const json&
motion_info ObjectPoseGT::MotionInfo&
Definition at line 338 of file GroundTruthPacket.cc.
{
  motion_info.is_moving_ = j["is_moving"].template get<bool>();
  motion_info.has_stopped_ = j["has_stopped"].template get<bool>();
}
References dyno::ObjectPoseGT::MotionInfo::has_stopped_, and dyno::ObjectPoseGT::MotionInfo::is_moving_.
fromByeTrackRect()
template<typename T > cv::Rect dyno::fromByeTrackRect (const byte_track::Rect< T > & rect)
Definition at line 36 of file ObjectTracker.cc.
{
  return cv::Rect(static_cast<int>(rect.x()), static_cast<int>(rect.y()),
                  static_cast<int>(rect.width()),
                  static_cast<int>(rect.height()));
}
References byte_track::Rect< T >::height(), byte_track::Rect< T >::width(), byte_track::Rect< T >::x(), and byte_track::Rect< T >::y().
Referenced by dyno::ByteObjectTracker::track().
FunctionalDetector::Create< cv::GFTTDetector >()
template<> FunctionalDetector::Ptr dyno::FunctionalDetector::Create< cv::GFTTDetector > (const TrackerParams & tracker_params)
Definition at line 103 of file FeatureDetector.cc.
{
  LOG(INFO) << "Creating cv::GFTTDetector";
  auto feature_detector_ = cv::GFTTDetector::create(
      tracker_params.max_nr_keypoints_before_anms,
      tracker_params.gfft_params.quality_level,
      tracker_params.min_distance_btw_tracked_and_detected_static_features,
      tracker_params.gfft_params.block_size,
      tracker_params.gfft_params.use_harris_corner_detector,
      tracker_params.gfft_params.k);
  auto functional_detector = [=](const cv::Mat& img, KeypointsCV& keypoints,
                                 const cv::Mat& mask) -> void {
    CHECK_NOTNULL(feature_detector_)->detect(img, keypoints, mask);
  };
  return std::make_shared<FunctionalDetector>(functional_detector);
}
References dyno::TrackerParams::GFFTParams::block_size, dyno::TrackerParams::gfft_params, dyno::TrackerParams::GFFTParams::k, dyno::TrackerParams::max_nr_keypoints_before_anms, dyno::TrackerParams::min_distance_btw_tracked_and_detected_static_features, dyno::TrackerParams::GFFTParams::quality_level, and dyno::TrackerParams::GFFTParams::use_harris_corner_detector.
gen()
std::mt19937 dyno::gen (rd())
Referenced by dyno::utils::perturbWithUniformNoise(), and dyno::Color::random().
get() [1/2]
template<size_t N, typename T > auto dyno::get (const FrameRange< T > & p)
Definition at line 419 of file StructuredContainers.hpp.
{
  if constexpr (N == 0)
    return p.dataPair().first;
  else if constexpr (N == 1)
    return p.dataPair().second;
}
References dyno::FrameRange< T >::dataPair().
get() [2/2]
template<size_t N, typename T , int D> auto dyno::get (const MeasurementWithCovariance< T, D > & p)
Definition at line 505 of file SensorModels.hpp.
{
  if constexpr (N == 0)
    return p.measurement();
  else if constexpr (N == 1)
    return p.model();
}
References dyno::MeasurementWithCovariance< T, D >::measurement(), and dyno::MeasurementWithCovariance< T, D >::model().
Referenced by dyno::Accessor::computeObjectCentroid(), and dyno::BayesTreeMarginalizationHelper< BayesTree >::getCliquesContainingKeys().
getAllFilesInDir()
std::vector< std::filesystem::path > dyno::getAllFilesInDir (const std::string & folder_path)
Definition at line 89 of file DataProviderUtils.cc.
{
  std::vector<std::filesystem::path> files_in_directory;
  std::copy(std::filesystem::directory_iterator(folder_path),
            std::filesystem::directory_iterator(),
            std::back_inserter(files_in_directory));
  std::sort(files_in_directory.begin(), files_in_directory.end());
  return files_in_directory;
}
Referenced by loadPathsInDirectory().
getDynosamNNShareDirectory()
fs::path dyno::getDynosamNNShareDirectory ()
Definition at line 12 of file ModelConfig.cc.
{
  return fs::path(ament_index_cpp::get_package_share_directory(PackageName));
}
References PackageName.
Referenced by getNNResourcesPath(), and getNNWeightsPath().
getModelDirectory()
std::filesystem::path dyno::getModelDirectory ()
Definition at line 25 of file ModelConfig.cc.
{
  const auto weights_path = getNNWeightsPath();
  utils::throwExceptionIfPathInvalid(weights_path);
  return weights_path;
}
References getNNWeightsPath(), and dyno::utils::throwExceptionIfPathInvalid().
Referenced by dyno::ModelConfig::modelPath().
getNNResourcesPath()
std::filesystem::path dyno::getNNResourcesPath ()
Specifies the default location of all weights used by dynosam_nn. This should in the dynosam_nn share package location + resources (e.g. /dynosam_nn/share/dynosam_nn/resouces)
Returns
std::filesystem::path
Definition at line 21 of file ModelConfig.cc.
{
  return getDynosamNNShareDirectory() / "resources";
}
References getDynosamNNShareDirectory().
Referenced by dyno::ModelConfig::getResouce().
getNNWeightsPath()
fs::path dyno::getNNWeightsPath ()
Specifies the default location of all weights used by dynosam_nn. This should in the dynosam_nn share package location + weights (e.g. /dynosam_nn/share/dynosam_nn/weights)
Returns
std::filesystem::path
Definition at line 16 of file ModelConfig.cc.
{ return getDynosamNNShareDirectory() / "weights"; }
References getDynosamNNShareDirectory().
Referenced by getModelDirectory(), and PYBIND11_MODULE().
getOutputFilePath()
std::string dyno::getOutputFilePath (const std::string & file_name)
Constructs a file path (using the file name) where the root of the path is defined by the FLAGS_output_path param.
This flag defines the output folder of all output log/debug files. The resulting file path with then be FLAGS_output_path/file_name
Parameters
file_name
Returns
std::string
Definition at line 46 of file Logger.cc.
{
  fs::path out_path(FLAGS_output_path);
  return out_path / file_name;
}
Referenced by dyno::BackendExperimentsNode::BackendExperimentsNode(), dyno::ParallelHybridBackendModule::logGraphs(), dyno::RegularBackendModule::logIncrementalStats(), dyno::test_hybrid::SmartStructurlessFormulation::postUpdate(), dyno::factor_graph_tools::SparsityStats::saveOnOutputPath(), dyno::ParallelObjectISAM::updateStates(), dyno::vision_tools::writeOutProjectMaskAndDepthMap(), writeStatisticsModuleSummariesToFile(), writeStatisticsSamplesToFile(), writeStatisticsSummaryToFile(), dyno::ParallelHybridBackendModule::~ParallelHybridBackendModule(), and dyno::RGBDInstanceFrontendModule::~RGBDInstanceFrontendModule().
getRuntime()
RuntimePtr dyno::getRuntime (const std::string & verbosity)
Definition at line 331 of file TrtUtilities.cc.
{
  auto& logger = LoggingShim::instance(log_severity);
  return RuntimePtr(nvinfer1::createInferRuntime(logger));
}
References dyno::LoggingShim::instance().
getSafeQuery()
template<typename ValueType > bool dyno::getSafeQuery (ValueType & result, const StateQuery< ValueType > & query, const ValueType & default_value)
Safe getter to a StateQuery object. If the StateQuery is successful, result is set to the value of the query and true is returned. Else, result is set to to the default value and false is returned.
Template Parameters
ValueType
Parameters
result
query
default_value
Returns
true
false
Definition at line 363 of file MapNodes.hpp.
{
  if (query) {
    result = query.get();
    return true;
  } else {
    result = default_value;
    return false;
  }
}
References dyno::StateQuery< ValueType >::get().
Referenced by dyno::HybridFormulation::dynamicPointUpdateCallback(), dyno::test_hybrid::SmartStructurlessFormulation::dynamicPointUpdateCallback(), dyno::WorldMotionFormulation::dynamicPointUpdateCallback(), dyno::WorldPoseFormulation::dynamicPointUpdateCallback(), dyno::Formulation< MAP >::getInitialOrLinearizedSensorPose(), and dyno::WorldPoseFormulation::objectUpdateContext().
getShapeFromDimsHelper()
std::optional< ImageTensorInfo::Shape > dyno::getShapeFromDimsHelper (const nvinfer1::Dims & dims)
Definition at line 89 of file TrtUtilities.cc.
{
  // expect something in the form [1 x C X H X W] likely from pytorch/tensorrt
  // but also maybe [1 x W X H X C] or even just [W X H X C]]
  if (dims.nbDims < 3) {
    return {};
  }
  const auto start = dims.nbDims - 3;
  const auto end = dims.nbDims - 1;
  // channels will either be the first one or the last one (which indicates CHW
  // or HWC order)
  const bool is_color = dims.d[start] == 3 || dims.d[end] == 3;
  // if is colour the number of channels is 3 otherwise 1
  const int expected_channels = is_color ? 3 : 1;
  // if the first dimension is either 1 or 3 (ie channels)
  // if not then we assume W X H X C
  const bool chw_order = dims.d[start] == expected_channels;
  ImageTensorInfo::Shape shape;
  shape.chw_order = chw_order;
  if (shape.chw_order) {
    shape.height = dims.d[start + 1];
    shape.width = dims.d[start + 2];
    shape.channels = dims.d[start];
  } else {
    shape.height = dims.d[start];
    shape.width = dims.d[start + 1];
    shape.channels = dims.d[start + 2];
  }
  return shape;
}
References dyno::ImageTensorInfo::Shape::channels, dyno::ImageTensorInfo::Shape::chw_order, dyno::ImageTensorInfo::Shape::height, and dyno::ImageTensorInfo::Shape::width.
Referenced by dyno::ImageTensorInfo::ImageTensorInfo().
getTrackID()
int dyno::getTrackID (const std::vector< std::string > & split_string, int idx) inline
NOTE!!: In vitual kitti, the track id's start at 0 and then the ground truth instances in the semantic instances are indexed from trackId+1 such that a pixel value of zero means not a vehicle. In order to reduce confusion when we work with the semantic images and then associate with the ground truth labels, we will index all tracks as trackID = virtualKittiTrackID + 1 so all tracks start from 1!
Parameters
split_string
idx
Returns
int
Definition at line 55 of file VirtualKittidataProvider.cc.
{
  return std::stoi(split_string.at(idx)) + 1;
}
Referenced by dyno::VirtualKittiTextGtLoader::loadBBoxMetaData(), and dyno::VirtualKittiTextGtLoader::loadPoseTxt().
groupObjectCloud() [1/3]
CloudPerObject dyno::groupObjectCloud (const StatusLandmarkVector & landmarks, const gtsam::Pose3 & T_world_camera, std::function< Color(ObjectId)> colour_generator) inline
Overload of groupObjectCloud.
Parameters
landmarks const StatusLandmarkVector&
T_world_camera const gtsam::Pose3&
colour_generator std::function<Color(ObjectId)>
Returns
CloudPerObject
Definition at line 189 of file PointCloudProcess.hpp.
{
  return groupObjectCloud(landmarks, T_world_camera, colour_generator, nullptr);
}
References groupObjectCloud().
groupObjectCloud() [2/3]
CloudPerObject dyno::groupObjectCloud (const StatusLandmarkVector & landmarks, const gtsam::Pose3 & T_world_camera, std::function< Color(ObjectId)> colour_generator = Color::uniqueObjectId, std::function< void(const pcl::PointXYZRGB &, ObjectId)> point_cb = nullptr)
This function goes through the input 3D landmarks and group them into point clusters based on their object labels these 3D landmarks are expected to be in the sensor reference frame, and T_world_camera puts them into the world frame CloudPerObject is in the world frame.
Parameters
landmarks const StatusLandmarkVector&
T_world_camera const gtsam::Pose3& Transform from camera to world frame
colour_generator std::function<Color(ObjectId)> functional colour generator based on the object id. Defaults to Color::uniqueId.
point_cb std::function<void(const pcl::PointXYZRGB&, ObjectId)> callback for each created PCL point. Default is nullptr
Returns
CloudPerObject XYZRGB point cloud per obect in the world frame
Definition at line 97 of file PointCloudProcess.cc.
{
  CHECK(colour_generator);
  CloudPerObject clouds_per_obj;
  for (const auto& status_estimate : landmarks) {
    Landmark lmk_world = status_estimate.value();
    const ObjectId object_id = status_estimate.objectId();
    if (status_estimate.referenceFrame() == ReferenceFrame::LOCAL) {
      lmk_world = T_world_camera * status_estimate.value();
    } else if (status_estimate.referenceFrame() == ReferenceFrame::OBJECT) {
      throw DynosamException(
          "Cannot display object point in the object reference frame");
    }
    // TODO: use convert in header!!
    pcl::PointXYZRGB pt;
    if (status_estimate.isStatic()) {
      // publish static lmk's as white
      pt = pcl::PointXYZRGB(lmk_world(0), lmk_world(1), lmk_world(2), 0, 0, 0);
    } else {
      const cv::Scalar colour = Color::uniqueId(object_id);
      pt = pcl::PointXYZRGB(lmk_world(0), lmk_world(1), lmk_world(2), colour(0),
                            colour(1), colour(2));
    }
    if (point_cb) point_cb(pt, object_id);
    clouds_per_obj[object_id].push_back(pt);
  }
  return clouds_per_obj;
}
References LOCAL, OBJECT, and dyno::Color::uniqueId().
Referenced by dyno::HybridFormulationV1::calculateObjectCentroid(), dyno::Accessor::computeObjectCentroid(), groupObjectCloud(), dyno::HybridModuleDisplayCommon::publishObjectBoundingBoxes(), dyno::DisplayCommon::publishPointCloud(), and dyno::BackendDSDRos::publishTemporalDynamicMaps().
groupObjectCloud() [3/3]
CloudPerObject dyno::groupObjectCloud (const StatusLandmarkVector & landmarks, const gtsam::Pose3 & T_world_camera, std::function< void(const pcl::PointXYZRGB &, ObjectId)> point_cb) inline
Overload of groupObjectCloud.
Parameters
landmarks const StatusLandmarkVector&
T_world_camera const gtsam::Pose3&
point_cb std::function<void(const pcl::PointXYZRGB&, ObjectId)>
Returns
CloudPerObject
Definition at line 174 of file PointCloudProcess.hpp.
{
  return groupObjectCloud(landmarks, T_world_camera, Color::uniqueObjectId,
                          point_cb);
}
References groupObjectCloud(), and dyno::Color::uniqueObjectId().
H()
gtsam::Key dyno::H (unsigned char label, std::uint64_t j) inline
Definition at line 126 of file Symbols.hpp.
{
  return gtsam::LabeledSymbol(kObjectMotionSymbolChar, label, j);
}
References kObjectMotionSymbolChar.
Referenced by dyno::ORBextractor::ComputeKeyPointsOld(), dyno::utils::cvMatToGtsamPose3(), dyno::vision_tools::depthTo3D(), dyno::Pose3FlowProjectionFactor< CALIBRATION >::evaluateError(), dyno::LandmarkMotionTernaryFactor::evaluateError(), ObjectMotionSymbol(), and dyno::FeatureTrackerBase::predictKeypointsGivenRotation().
hashPair()
template<class T1 , class T2 > size_t dyno::hashPair (const std::pair< T1, T2 > & p)
A hash function used to hash a pair of any kind: ORDER MATTERS, Hash(a, b) != Hash(b, a) Used for hashing pixel positions of vertices of the mesh 2d.
Definition at line 47 of file Numerical.hpp.
{
  // note: used to use boost::hash_combine
  const auto h1 = std::hash<T1>{}(p.first);
  const auto h2 = std::hash<T2>{}(p.second);
  return h1 ^ (h2 << 1);
}
hashTriplet()
template<class T1 , class T2 , class T3 > size_t dyno::hashTriplet (const T1 & p1, const T2 & p2, const T3 & p3)
A hash function used to hash a pair of any kind: ORDER DOESN'T MATTERS, If you want order invariance just sort your values before accessing/checking Used for hashing faces in a mesh.
Definition at line 58 of file Numerical.hpp.
{
  // return ((std::hash<T1>()(p1) ^ (std::hash<T2>()(p2) << 1)) >> 1) ^
  //        (std::hash<T3>()(p3) << 1);
  static constexpr size_t sl = 17191;
  static constexpr size_t sl2 = sl * sl;
  return static_cast<unsigned int>(p1 + p2 * sl + p3 * sl2);
}
hybridAccessorCommonHelper()
static HybridAccessorCommon::Ptr dyno::hybridAccessorCommonHelper (Accessor::Ptr accessor) static
Definition at line 13 of file HybridBackendDisplay.hpp.
{
  CHECK(accessor);
  HybridAccessorCommon::Ptr hybrid_accessor_common =
      std::dynamic_pointer_cast<HybridAccessorCommon>(accessor);
  if (!hybrid_accessor_common) {
    throw DynosamException(
        "Accessor could not be cast to HybridAccessorCommon");
  }
  return hybrid_accessor_common;
}
IC_Angle()
static float dyno::IC_Angle (const Mat & image, Point2f pt, const vector< int > & u_max) static
Definition at line 93 of file ORBextractor.cc.
{
  int m_01 = 0, m_10 = 0;
  const uchar* center = &image.at<uchar>(cvRound(pt.y), cvRound(pt.x));
  // Treat the center line differently, v=0
  for (int u = -HALF_PATCH_SIZE; u <= HALF_PATCH_SIZE; ++u)
    m_10 += u * center[u];
  // Go line by line in the circuI853lar patch
  int step = (int)image.step1();
  for (int v = 1; v <= HALF_PATCH_SIZE; ++v) {
    // Proceed over the two lines
    int v_sum = 0;
    int d = u_max[v];
    for (int u = -d; u <= d; ++u) {
      int val_plus = center[u + v * step], val_minus = center[u - v * step];
      v_sum += (val_plus - val_minus);
      m_10 += u * (val_plus + val_minus);
    }
    m_01 += v * v_sum;
  }
  return fastAtan2((float)m_01, (float)m_10);
}
References HALF_PATCH_SIZE.
Referenced by computeOrientation().
info_string()
std::string dyno::info_string (FrameId frame_id, ObjectId object_id) inline
Definition at line 726 of file Types.hpp.
{
  return "j= " + std::to_string(object_id) + ", k=" + std::to_string(frame_id);
}
Referenced by dyno::RGBDInstanceFrontendModule::fillOutputPacketWithTracks(), dyno::FeatureTracker::requiresSampling(), dyno::RegularBackendModule::setFormulation(), dyno::IncrementalInterface< SMOOTHER >::updateSmoother(), and dyno::ParallelObjectISAM::updateStates().
initRosAndLogging()
std::vector< std::string > dyno::initRosAndLogging (int argc, char * argv[])
Initalises ROS, gflags and glog.
Returns a vector of non-ROS arguments
Parameters
argc
argv
Returns
std::vector<std::string>
Definition at line 61 of file Utils.cc.
{
  // google::ParseCommandLineFlags(&argc, &argv, true);
  auto non_ros_args = rclcpp::init_and_remove_ros_arguments(argc, argv);
  google::InitGoogleLogging(argv[0]);
  FLAGS_logtostderr = 1;
  FLAGS_colorlogtostderr = 1;
  FLAGS_log_prefix = 1;
  int non_ros_argc = non_ros_args.size();
  char** non_ros_argv_c = constructArgvC(non_ros_args);
  // non_ros_argv_c is heap allocated but attempting to free it after usage in
  // the ParseCommandLineFlags function results in a "double free or corruption"
  // error. I think this is because ParseCommandLineFlags modifies it in place
  // and then free it itself somehow unsure, and may result in a minor memory
  // leak
  google::ParseCommandLineFlags(&non_ros_argc, &non_ros_argv_c, true);
  return non_ros_args;
}
References constructArgvC().
Referenced by main().
is_zero()
bool dyno::is_zero (double a) inline
Checks if a double value is zero up to a tolerance.
Uses fpEqual.
Parameters
a
Returns
true
false
Definition at line 90 of file Numerical.hpp.
{ return fpEqual(a, 0.0); }
References fpEqual().
Referenced by dyno::RGBA< T >::RGBA().
isDynamic()
bool dyno::isDynamic (const nvinfer1::Dims & dims)
Definition at line 154 of file TrtUtilities.cc.
{
  for (int i = 0; i < dims.nbDims; ++i) {
    if (dims.d[i] < 0) {
      return true;
    }
  }
  return false;
}
Referenced by dyno::TensorInfo::isDynamic().
isMoving()
bool dyno::isMoving (const gtsam::Pose3 & prev_L_world, const gtsam::Pose3 & curr_L_world, double tol_m = 0.4)
Definition at line 47 of file GroundTruthPacket.cc.
{
  gtsam::Vector3 t_diff =
      curr_L_world.translation() - prev_L_world.translation();
  // L2 norm - ie. magnitude
  double t_error = t_diff.norm();
  return t_error > tol_m;
}
Referenced by dyno::ObjectPoseGT::setMotions().
L()
gtsam::Key dyno::L (unsigned char label, std::uint64_t j) inline
Definition at line 129 of file Symbols.hpp.
{
  return gtsam::LabeledSymbol(kObjectPoseSymbolChar, label, j);
}
References kObjectPoseSymbolChar.
Referenced by ObjectPoseSymbol(), dyno::CameraMeasurement::stereoMeasurement(), and dyno::Feature::stereoPoint().
loadPathsInDirectory()
void dyno::loadPathsInDirectory (std::vector< std::string > & file_paths, const std::string & folder_path, const std::function< bool(const std::string &)> & condition)
Definition at line 99 of file DataProviderUtils.cc.
{
  std::function<bool(const std::string&)> impl_condition;
  if (condition) {
    impl_condition = condition;
  } else {
    // if no condition is provided, set condition to always return true; adding
    // all the files found
    impl_condition = [](const std::string&) -> bool { return true; };
  }
  auto files_in_directory = getAllFilesInDir(folder_path);
  for (const std::string file_path : files_in_directory) {
    utils::throwExceptionIfPathInvalid(file_path);
    // if condition is true, add
    if (impl_condition(file_path)) file_paths.push_back(file_path);
  }
}
References getAllFilesInDir(), and dyno::utils::throwExceptionIfPathInvalid().
makeKwargs()
bp::dict dyno::makeKwargs (const PyObjectDetectorWrapper::Kwargs & args)
Definition at line 78 of file PyObjectDetector.cc.
{
  bp::dict kwargs;
  for (const auto& [key, value] : args) {
    kwargs[key.c_str()] = anyToBPobject(value);
  }
  return kwargs;
}
Referenced by dyno::PyObjectDetectorWrapper::PyObjectDetectorWrapper().
maskTypeFromString()
MaskType dyno::maskTypeFromString (const std::string & mask_type) inline
Converts an input string into a enun MaskType.
Parameters
mask_type
Returns
MaskType
Definition at line 297 of file DatasetLoader.hpp.
{
  if (mask_type == "motion") {
    return MaskType::MOTION;
  } else if (mask_type == "semantic") {
    return MaskType::SEMANTIC_INSTANCE;
  }
  throw std::runtime_error(
      "Cannot load mask type from string - unknown input " + mask_type);
}
References MOTION, and SEMANTIC_INSTANCE.
Referenced by dyno::KittiDataLoader::Params::fromYaml(), and dyno::VirtualKittiDataLoader::Params::fromYaml().
mod()
template<typename T > T dyno::mod (T x, T y)
Floating-point modulo The result (the remainder) has same sign as the divisor. Similar to matlab's mod(); Not similar to fmod() - Mod(-3,4)= 1 fmod(-3,4)= -3.
https://stackoverflow.com/questions/4633177/c-how-to-wrap-a-float-to-the-interval-pi-pi
Template Parameters
T
Parameters
x
y
Returns
T
Definition at line 148 of file Numerical.hpp.
                {
  static_assert(!std::numeric_limits<T>::is_exact,
                "Mod: floating-point type expected");
  if (0. == y) return x;
  double m = x - y * floor(x / y);
  // handle boundary cases resulted from floating-point cut off:
  if (y > 0)  // modulo range: [0..y)
  {
    if (m >= y)  // Mod(-1e-16             , 360.    ): m= 360.
      return 0;
    if (m < 0) {
      if (y + m == y)
        return 0;  // just in case...
      else
        return y + m;  // Mod(106.81415022205296 , _TWO_PI ): m= -1.421e-14
    }
  } else  // modulo range: (y..0]
  {
    if (m <= y)  // Mod(1e-16              , -360.   ): m= -360.
      return 0;
    if (m > 0) {
      if (y + m == y)
        return 0;  // just in case...
      else
        return y + m;  // Mod(-106.81415022205296, -_TWO_PI): m= 1.421e-14
    }
  }
  return m;
}
Referenced by wrapTwoPi().
NLOHMANN_JSON_SERIALIZE_ENUM()
dyno::NLOHMANN_JSON_SERIALIZE_ENUM (KeyPointType , { {STATIC, "static"}, {DYNAMIC, "dynamic"}, })
References DYNAMIC, and STATIC.
ObjectMotionSymbol()
gtsam::Key dyno::ObjectMotionSymbol (ObjectId object_label, FrameId frame_id) inline
Definition at line 143 of file Symbols.hpp.
{
  unsigned char label = object_label + '0';
  return H(label, static_cast<std::uint64_t>(frame_id));
}
References H().
Referenced by dyno::ParallelHybridAccessor::getEstimatedMotion(), dyno::ParallelHybridAccessor::getObjectMotion(), dyno::FrameNode< MEASUREMENT >::makeObjectMotionKey(), and dyno::MotionOnlyRefinementOptimizer::optimize().
ObjectPoseSymbol()
gtsam::Key dyno::ObjectPoseSymbol (ObjectId object_label, FrameId frame_id) inline
Definition at line 148 of file Symbols.hpp.
{
  unsigned char label = object_label + '0';
  return L(label, static_cast<std::uint64_t>(frame_id));
}
References L().
Referenced by dyno::ParallelHybridAccessor::getObjectPose(), dyno::WorldMotionAccessor::getObjectPose(), and dyno::FrameNode< MEASUREMENT >::makeObjectPoseKey().
OpenFile()
static void dyno::OpenFile (const std::string & output_filename, std::ofstream * output_file, bool append_mode = false) inline static
Definition at line 116 of file Logger.hpp.
{
  CHECK_NOTNULL(output_file);
  output_file->open(output_filename.c_str(),
                    append_mode ? std::ios_base::app : std::ios_base::out);
  output_file->precision(20);
  CHECK(output_file->is_open()) << "Cannot open file: " << output_filename;
  CHECK(output_file->good()) << "File in bad state: " << output_filename;
}
Referenced by dyno::OfstreamWrapper::closeAndOpenLogFile(), and dyno::OfstreamWrapper::openLogFile().
operator<<() [1/12]
std::ostream & dyno::operator<< (std::ostream & os, const DebugInfo::ObjectInfo & object_info)
Definition at line 223 of file BackendDefinitions.cc.
{
  os << (std::string)object_info;
  return os;
}
operator<<() [2/12]
std::ostream & dyno::operator<< (std::ostream & os, const dyno::ObjectDetectionResult & res)
Definition at line 56 of file DynamicObjects.cc.
{
  os << "ObjectDetectionResult:\n";
  os << "  detections (" << res.detections.size() << "):\n";
  for (const auto& det : res.detections) {
    os << "    object id=" << det.object_id << ", class=" << det.class_name
       << ", confidence=" << det.confidence << ", bbox=(" << det.bounding_box.x
       << "," << det.bounding_box.y << "," << det.bounding_box.width << ","
       << det.bounding_box.height << ")\n";
  }
  // if (!res.labelled_mask.empty()) {
  //     os << "  labelled_mask: (" << res.labelled_mask.rows
  //        << "x" << res.labelled_mask.cols
  //        << ", channels=" << res.labelled_mask.channels() << ")\n";
  // } else {
  //     os << "  labelled_mask: empty\n";
  // }
  return os;
}
operator<<() [3/12]
std::ostream & dyno::operator<< (std::ostream & os, const GroundTruthInputPacket & gt_packet)
Definition at line 327 of file GroundTruthPacket.cc.
{
  os << (std::string)gt_packet;
  return os;
}
operator<<() [4/12]
std::ostream & dyno::operator<< (std::ostream & os, const ImageContainer & image_container)
Definition at line 116 of file ImageContainer.cc.
{
  os << image_container.toString();
  return os;
}
operator<<() [5/12]
std::ostream & dyno::operator<< (std::ostream & os, const ObjectPoseGT & object_pose)
Definition at line 171 of file GroundTruthPacket.cc.
{
  os << (std::string)object_pose;
  return os;
}
operator<<() [6/12]
std::ostream & dyno::operator<< (std::ostream & out, const Color & color)
Definition at line 190 of file Colour.cc.
{
  out << "[RGBA: " << static_cast<int>(color.r) << ", "
      << static_cast<int>(color.g) << ", " << static_cast<int>(color.b) << ", "
      << static_cast<int>(color.a) << "]";
  return out;
}
operator<<() [7/12]
std::ostream & dyno::operator<< (std::ostream & out, const ImageTensorInfo & info)
Definition at line 149 of file TrtUtilities.cc.
{
  out << static_cast<const TensorInfo&>(info) << ", shape: " << info.shape();
  return out;
}
References dyno::ImageTensorInfo::shape().
operator<<() [8/12]
std::ostream & dyno::operator<< (std::ostream & out, const ImageTensorInfo::Shape & shape)
Definition at line 142 of file TrtUtilities.cc.
{
  out << "w= " << shape.width << " h= " << shape.height
      << " c=" << shape.channels.value_or(-1)
      << " chw_order= " << std::boolalpha << shape.chw_order;
  return out;
}
References dyno::ImageTensorInfo::Shape::channels, dyno::ImageTensorInfo::Shape::chw_order, dyno::ImageTensorInfo::Shape::height, and dyno::ImageTensorInfo::Shape::width.
operator<<() [9/12]
std::ostream & dyno::operator<< (std::ostream & out, const TensorInfo & info)
Definition at line 83 of file TrtUtilities.cc.
{
  out << "<name=" << info.name << ", layout=" << toString(info.dims) << " ("
      << toString(info.dtype) << ")>";
  return out;
}
References dyno::TensorInfo::dims, dyno::TensorInfo::dtype, dyno::TensorInfo::name, and toString().
operator<<() [10/12]
std::ostream & dyno::operator<< (std::ostream & out, const YoloV8ModelInfo & info)
Definition at line 704 of file YoloV8ObjectDetector.cc.
{
  out << "Model: ";
  if (!info) {
    out << "(uninitialized)";
    return out;
  }
  out << "input=" << info.input();
  out << " , output0=" << info.output0();
  out << " , output1=" << info.output1();
  return out;
}
References dyno::YoloV8ModelInfo::input(), dyno::YoloV8ModelInfo::output0(), and dyno::YoloV8ModelInfo::output1().
operator<<() [11/12]
std::ostream & dyno::operator<< (std::ostream & stream, const ParameterDetails & param)
Definition at line 170 of file RosUtils.cc.
{
  stream << (std::string)param;
  return stream;
}
operator<<() [12/12]
std::ostream & dyno::operator<< (std::ostream & stream, const rclcpp::Parameter & param)
Definition at line 175 of file RosUtils.cc.
{
  stream << param.get_name() << ": " << param.value_to_string() << " ("
         << param.get_type_name() << ")";
  return stream;
}
optimizeWildfire() [1/2]
size_t dyno::optimizeWildfire (const ISAM2Clique::shared_ptr & root, double threshold, const gtsam::KeySet & replaced, gtsam::VectorValues * delta)
Optimize the BayesTree, starting from the root.
Parameters
threshold The maximum change against the PREVIOUS delta for non-replaced variables that can be ignored, ie. the old delta entry is kept and recursive backsubstitution might eventually stop if none of the changed variables are contained in the subtree.
replaced Needs to contain all variables that are contained in the top of the Bayes tree that has been redone.
Returns
The number of variables that were solved for.
Parameters
delta The current solution, an offset from the linearization point.
Referenced by optimizeWildfire().
optimizeWildfire() [2/2]
size_t dyno::optimizeWildfire (const ISAM2Clique::shared_ptr & root, double threshold, const KeySet & keys, VectorValues * delta)
Definition at line 239 of file ISAM2Clique.cc.
{
  KeySet changed;
  size_t count = 0;
  // starting from the root, call optimize on each conditional
  if (root) root->optimizeWildfire(keys, threshold, &changed, delta, &count);
  return count;
}
References optimizeWildfire().
optimizeWildfireNonRecursive() [1/2]
size_t dyno::optimizeWildfireNonRecursive (const ISAM2Clique::shared_ptr & root, double threshold, const gtsam::KeySet & replaced, gtsam::VectorValues * delta)
Referenced by optimizeWildfireNonRecursive(), and dyno::DeltaImpl::UpdateGaussNewtonDelta().
optimizeWildfireNonRecursive() [2/2]
size_t dyno::optimizeWildfireNonRecursive (const ISAM2Clique::shared_ptr & root, double threshold, const KeySet & keys, VectorValues * delta)
Definition at line 273 of file ISAM2Clique.cc.
{
  KeySet changed;
  size_t count = 0;
  if (root) {
    std::stack<ISAM2Clique::shared_ptr> travStack;
    travStack.push(root);
    ISAM2Clique::shared_ptr currentNode = root;
    while (!travStack.empty()) {
      currentNode = travStack.top();
      travStack.pop();
      bool dirty = currentNode->optimizeWildfireNode(keys, threshold, &changed,
                                                     delta, &count);
      if (dirty) {
        for (const auto& child : currentNode->children) {
          travStack.push(child);
        }
      }
    }
  }
  return count;
}
References optimizeWildfireNonRecursive().
pclPointToGtsam()
template<typename PointT > gtsam::Point3 dyno::pclPointToGtsam (const PointT & point) inline
Constructs a gtsam::Point3 from the x,y,z components of the PointT.
Casts to double type for save conversions
Template Parameters
PointT
Parameters
point
Returns
gtsam::Point3
Definition at line 110 of file PointCloudProcess.hpp.
{
  return gtsam::Point3(static_cast<double>(point.x),
                       static_cast<double>(point.y),
                       static_cast<double>(point.z));
}
Referenced by dyno::HybridFormulationV1::calculateObjectCentroid(), dyno::Accessor::computeObjectCentroid(), findAABBFromCloud(), and findOBBFromCloud().
propogateObjectPoses()
void dyno::propogateObjectPoses (ObjectPoseMap & object_poses, const MotionEstimateMap & object_motions_k, const gtsam::Point3Vector & object_centroids_k_1, const gtsam::Point3Vector & object_centroids_k, FrameId frame_id_k, std::optional< GroundTruthPacketMap > gt_packet_map = {}, PropogatePoseResult * result = nullptr)
Propogated a map of object poses via their motions or otherwise.
At its core, take a map of object poses and a current frame, as well as a map of estimation motions, H, at the current frame and propogates the object poses according to: ^wH_k = ^w_{k-1}H_K * ^wL_{k-1} which is then added to the object_poses.
If ^wL_{k-1} is not available in the ObjectPoseMap but ^w_{k-1}H_K is in the MotionEstimateMap then EITHER object_centroids_k_1 is used as the translation component of ^wL_{k-1} or the ground truth is - if GroundTruthPacketMap is provided, then initalisation with ground truth is preferred.
If ^wL_{k-1} and ^w_{k-1}H_K is not available the function will attempt to interpolate between the the last object pose available in the map and the current pose (initalised with object_centroids_k). If the last object pose is too far away, the function will just re-enit with the current centroid.
Parameters
object_poses ObjectPoseMap& map of object poses and their appearing frames
object_motions_k const MotionEstimateMap& object motions from k-1 to k (size N)
object_centroids_k_1 const gtsam::Point3Vector& estimated object centroids at k-1, must be of size N
object_centroids_k const gtsam::Point3Vector& estimated object centroids at k,. must be of size N
frame_id_k FrameId current frame id (k)
gt_packet_map std::optional<GroundTruthPacketMap> optionally provided gt map
result PropogatePoseResult* result map. If not null, will be populated with how each object new object pose was calculated
Definition at line 87 of file DynamicObjects.cc.
{
  CHECK_EQ(object_motions_k.size(), object_centroids_k_1.size());
  CHECK_EQ(object_centroids_k.size(), object_centroids_k_1.size());
  const FrameId frame_id_k_1 = frame_id_k - 1;
  // get centroid for object at k-1 using the gt pose if available, or the
  // centroid if not
  auto get_centroid = [=](ObjectId object_id, const gtsam::Point3& centroid_k_1,
                          gtsam::Pose3& pose_k_1) -> PropogateType {
    bool initalised_with_gt = false;
    // if gt packet exists for this frame, use that as the rotation
    if (gt_packet_map) {
      if (gt_packet_map->exists(frame_id_k_1)) {
        const GroundTruthInputPacket& gt_packet_k_1 =
            gt_packet_map->at(frame_id_k_1);
        ObjectPoseGT object_pose_gt_k_1;
        if (gt_packet_k_1.getObject(object_id, object_pose_gt_k_1)) {
          pose_k_1 = object_pose_gt_k_1.L_world_;
          initalised_with_gt = true;
        }
      }
    }
    if (!initalised_with_gt) {
      // could not init with gt, use identity rotation and centroid
      pose_k_1 = gtsam::Pose3(gtsam::Rot3::Identity(), centroid_k_1);
      return PropogateType::InitCentroid;
    } else {
      return PropogateType::InitGT;
    }
  };
  size_t i = 0;  // used to index the object centroid vectors
  for (const auto& [object_id, motion] : object_motions_k) {
    const auto centroid_k_1 = object_centroids_k_1.at(i);
    const gtsam::Pose3 prev_H_world_curr = motion;
    // new object - so we need to add at k-1 and k
    if (!object_poses.exists(object_id)) {
      gtsam::Pose3 pose_k_1;
      auto propgate_result = get_centroid(object_id, centroid_k_1, pose_k_1);
      if (result) result->insert22(object_id, frame_id_k_1, propgate_result);
      object_poses.insert2(object_id, gtsam::FastMap<FrameId, gtsam::Pose3>{});
      object_poses.at(object_id).insert2(frame_id_k_1, pose_k_1);
    }
    auto& per_frame_poses = object_poses.at(object_id);
    // if we have a pose at the previous frame, simply apply motion
    if (per_frame_poses.exists(frame_id_k_1)) {
      const gtsam::Pose3& object_pose_k_1 = per_frame_poses.at(frame_id_k_1);
      // assuming in world
      gtsam::Pose3 object_pose_k = prev_H_world_curr * object_pose_k_1;
      per_frame_poses.insert2(frame_id_k, object_pose_k);
      // update result map
      if (result)
        result->insert22(object_id, frame_id_k, PropogateType::Propogate);
    } else {
      // no motion at the previous frame - if close, interpolate between last
      // pose and this pose no motion used
      const size_t min_diff_frames = 3;
      // last frame SHOULD be the largest frame (as we use a std::map with
      // std::less)
      auto last_record_itr = per_frame_poses.rbegin();
      const FrameId last_frame = last_record_itr->first;
      const gtsam::Pose3 last_recorded_pose = last_record_itr->second;
      const gtsam::Point3& centroid_k = object_centroids_k.at(i);
      // construct current pose using last poses rotation (I guess?)
      gtsam::Pose3 current_pose =
          gtsam::Pose3(last_recorded_pose.rotation(), centroid_k);
      CHECK_LT(last_frame, frame_id_k_1);
      if (frame_id_k - last_frame < min_diff_frames) {
        // apply interpolation
        // need to map [last_frame:frame_id_k] -> [0,1] for the interpolation
        // function with N values such that frame_id_k - last_frame + 1= N (to
        // be inclusive)
        const size_t N = frame_id_k - last_frame + 1;
        const double divisor = (double)(frame_id_k - last_frame);
        for (size_t j = 0; j < N; j++) {
          double t = (double)j / divisor;
          gtsam::Pose3 interpolated_pose = last_recorded_pose.slerp(
              t, current_pose, boost::none, boost::none);
          FrameId frame = last_frame + j;
          per_frame_poses.insert2(frame, interpolated_pose);
          // update result map
          if (result)
            result->insert22(object_id, frame, PropogateType::Interpolate);
        }
      } else {
        gtsam::Pose3 pose_k_1;
        // last frame too far away - reinitalise with centroid!
        VLOG(20) << "Frames too far away - current frame is " << frame_id_k
                 << " previous frame is " << last_frame << " for object "
                 << object_id;
        auto propogate_result = get_centroid(object_id, centroid_k_1, pose_k_1);
        object_poses.at(object_id).insert2(frame_id_k_1, pose_k_1);
        if (result) result->insert22(object_id, frame_id_k_1, propogate_result);
        gtsam::Pose3 object_pose_k = prev_H_world_curr * pose_k_1;
        per_frame_poses.insert2(frame_id_k, object_pose_k);
        // update result map
        if (result)
          result->insert22(object_id, frame_id_k, PropogateType::Propogate);
      }
    }
    i++;
  }
}
References dyno::GenericObjectCentricMap< VALUE >::at(), dyno::GenericObjectCentricMap< VALUE >::exists(), dyno::GroundTruthInputPacket::getObject(), InitCentroid, InitGT, dyno::GenericObjectCentricMap< VALUE >::insert2(), dyno::GenericObjectCentricMap< VALUE >::insert22(), Interpolate, dyno::ObjectPoseGT::L_world_, and Propogate.
Referenced by dyno::WorldMotionAccessor::refreshPoseCache(), and dyno::ObjectMotionSovlerF2F::updatePoses().
rads2Deg()
double dyno::rads2Deg (double rads) inline
Converts radians to degrees.
Parameters
rads
Returns
double
Definition at line 98 of file Numerical.hpp.
{ return rads * 180.0 / M_PI; }
Referenced by dyno::utils::TRErrorPair::getRotationErrorDegrees().
reconstructMotionInfo()
bool dyno::reconstructMotionInfo (gtsam::Key key, ObjectId & object_label, FrameId & frame_id)
Definition at line 77 of file Symbols.cc.
{
  return internalReconstructInfo(key, kObjectMotionSymbolChar, object_label,
                                 frame_id);
}
References kObjectMotionSymbolChar.
Referenced by DynosamKeyFormatterVerbose(), dyno::HybridFormulation::objectUpdateContext(), dyno::WorldMotionFormulation::objectUpdateContext(), dyno::ApplyFunctionalSymbol::operator()(), and dyno::ParallelObjectISAM::updateStates().
reconstructPoseInfo()
bool dyno::reconstructPoseInfo (gtsam::Key key, ObjectId & object_label, FrameId & frame_id)
Definition at line 83 of file Symbols.cc.
{
  return internalReconstructInfo(key, kObjectPoseSymbolChar, object_label,
                                 frame_id);
}
References kObjectPoseSymbolChar.
Referenced by DynosamKeyFormatterVerbose(), dyno::WorldPoseFormulation::objectUpdateContext(), and dyno::ApplyFunctionalSymbol::operator()().
removeStaticObjectFromMask()
void dyno::removeStaticObjectFromMask (const cv::Mat & instance_mask, cv::Mat & motion_mask, const GroundTruthInputPacket & gt_packet)
From an instance semantic mask (one that satisfies the requirements for a SemanticMask), ie. all detected obejcts in the scene, with unique instance labels as pixel values starting from 1 (background is 0). Using the information in the ground truth, masks of detected objects that are not moving are removed. Masks are removed by setting the pixle values to 0 (background).
Expects the gt packet to be fully formed (ie. have all motion information set from setMotions()).
NOTE: function expects to find a match between the object id's in the ground truth packet, and the pixel values (instance mask values) in the image!! If there is not a 1-to-1 match between ground truth packets and the pixels, the function will fail
Parameters
instance_mask const cv::Mat&
motion_mask cv::Mat&
gt_packet const GroundTruthInputPacket&
Definition at line 120 of file DataProviderUtils.cc.
{
  try {
    ImageType::SemanticMask::validate(instance_mask);
  } catch (const InvalidImageTypeException& e) {
    throw DynosamException(
        "Input mask to removeStaticObjectFromMask as it"
        "did not meet the requirements of ImageType::SemanticMask. Error: " +
        std::string(e.what()));
  }
  ObjectIds object_ids = vision_tools::getObjectLabels(instance_mask);
  instance_mask.copyTo(motion_mask);
  const FrameId frame_id = gt_packet.frame_id_;
  // collect only moving labels
  std::vector<int> moving_labels;
  for (const ObjectPoseGT& object_pose_gt : gt_packet.object_poses_) {
    // LOG_IF(WARNING, !object_pose_gt.motion_info_)
    //     << "Object Pose GT (object " << object_pose_gt.object_id_ << ", frame
    //     " << object_pose_gt.frame_id_ << " does not have motion info set!
    //     Cannot determine of object is moving or not!";
    if (!object_pose_gt.motion_info_) {
      LOG(WARNING) << "Object Pose GT (object " << object_pose_gt.object_id_
                   << ", frame " << object_pose_gt.frame_id_
                   << " does not have motion info set! Cannot determine of "
                      "object is moving or not!";
      continue;
    }
    const auto& motion_info = *object_pose_gt.motion_info_;
    const ObjectId& object_id = object_pose_gt.object_id_;
    if (motion_info.is_moving_) {
      moving_labels.push_back(object_id);
    }
    // this is just a sanity (debug) check to ensure all the labels in the image
    // match up with the ones we have already collected in the ground truth
    // packet
    const auto& it = std::find(object_ids.begin(), object_ids.end(), object_id);
    CHECK(it != object_ids.end())
        << "Object id " << object_id
        << " appears in gt packet but"
           "is not in mask when loading motion mask for Virtual Kitti at frame "
        << frame_id;
  }
  // iterate over each object and if not moving remove
  for (int i = 0; i < motion_mask.rows; i++) {
    for (int j = 0; j < motion_mask.cols; j++) {
      int label = motion_mask.at<int>(i, j);
      if (label == 0) {
        continue;
      }
      // check if label is in moving labels. if not, make zero!
      auto it = std::find(moving_labels.begin(), moving_labels.end(), label);
      if (it == moving_labels.end()) {
        motion_mask.at<int>(i, j) = 0;
      }
    }
  }
}
References dyno::ObjectPoseGT::frame_id_, dyno::GroundTruthInputPacket::frame_id_, dyno::vision_tools::getObjectLabels(), dyno::ObjectPoseGT::motion_info_, dyno::ObjectPoseGT::object_id_, dyno::GroundTruthInputPacket::object_poses_, and dyno::ImageType::SemanticMask::validate().
Referenced by dyno::VirtualKittiMotionSegFolder::loadImage().
replaceDynamic()
nvinfer1::Dims dyno::replaceDynamic (const nvinfer1::Dims & dims, int64_t new_value) inline
Definition at line 358 of file TrtUtilities.cc.
{
  auto new_dims = dims;
  for (int i = 0; i < dims.nbDims; ++i) {
    if (dims.d[i] < 0) {
      new_dims.d[i] = new_value;
    }
  }
  return new_dims;
}
rgbFromChromaHue()
std::array< float, 3 > dyno::rgbFromChromaHue (float chroma, float hue)
Definition at line 73 of file Colour.cc.
{
  const float hue_prime = hue * 6.0f;
  const float x = chroma * (1.0f - std::abs(std::fmod(hue_prime, 2) - 1.0f));
  if (hue_prime < 1) {
    return {chroma, x, 0};
  } else if (hue_prime < 2) {
    return {x, chroma, 0};
  } else if (hue_prime < 3) {
    return {0, chroma, x};
  } else if (hue_prime < 4) {
    return {0, x, chroma};
  } else if (hue_prime < 5) {
    return {x, 0, chroma};
  }
  return {chroma, 0, x};
}
Referenced by dyno::Color::fromHLS(), and dyno::Color::fromHSV().
RGBMonoToMono()
cv::Mat dyno::RGBMonoToMono (const cv::Mat & mat)
Definition at line 92 of file ImageTypes.cc.
{
  const auto channels = mat.channels();
  if (channels == 1) {
    return mat;
  }
  if (channels == 3) {
    cv::Mat mono;
    cv::cvtColor(mat, mono, cv::COLOR_RGB2GRAY);
    return mono;
  } else if (channels == 4) {
    cv::Mat mono;
    cv::cvtColor(mat, mono, cv::COLOR_RGBA2GRAY);
    return mono;
  } else {
    return mat;
  }
}
Referenced by dyno::ImageType::RGBMono::toMono().
RGBMonoToRGB()
cv::Mat dyno::RGBMonoToRGB (const cv::Mat & mat)
Definition at line 74 of file ImageTypes.cc.
{
  const auto channels = mat.channels();
  if (channels == 3) {
    return mat;
  } else if (channels == 4) {
    cv::Mat rgb;
    cv::cvtColor(mat, rgb, cv::COLOR_RGBA2RGB);
    return rgb;
  } else if (channels == 1) {
    // grey scale but we want rgb so that we can draw colours on it or whatever
    cv::Mat rgb;
    cv::cvtColor(mat, rgb, cv::COLOR_GRAY2RGB);
    return rgb;
  } else {
    return mat;
  }
}
Referenced by dyno::ImageType::RGBMono::toRGB().
runRansac() [1/2]
template<class SampleConsensusProblem > bool dyno::runRansac (std::shared_ptr< SampleConsensusProblem > sample_consensus_problem_ptr, const double & threshold, const int & max_iterations, const double & probability, const bool & do_nonlinear_optimization, gtsam::Pose3 & best_pose, std::vector< int > & inliers)
Create ransac
Setup ransac
Run ransac
Definition at line 46 of file MotionSolver-inl.hpp.
{
  CHECK(sample_consensus_problem_ptr);
  inliers.clear();
  opengv::sac::Ransac<SampleConsensusProblem> ransac(max_iterations, threshold,
                                                     probability);
  ransac.sac_model_ = sample_consensus_problem_ptr;
  bool success = ransac.computeModel(0);
  if (success) {
    if (ransac.iterations_ >= max_iterations && ransac.inliers_.empty()) {
      success = false;
      best_pose = gtsam::Pose3();
      inliers = {};
    } else {
      best_pose = utils::openGvTfToGtsamPose3(ransac.model_coefficients_);
      inliers = ransac.inliers_;
      if (do_nonlinear_optimization) {
        opengv::transformation_t optimized_pose;
        sample_consensus_problem_ptr->optimizeModelCoefficients(
            inliers, ransac.model_coefficients_, optimized_pose);
        best_pose = Eigen::MatrixXd(optimized_pose);
      }
    }
  } else {
    CHECK(ransac.inliers_.empty());
    best_pose = gtsam::Pose3();
    inliers.clear();
  }
  return success;
}
References dyno::utils::openGvTfToGtsamPose3().
runRansac() [2/2]
template<class SampleConsensusProblem > bool dyno::runRansac (std::shared_ptr< SampleConsensusProblem > sample_consensus_problem_ptr, const RansacProblemParams & params, gtsam::Pose3 & best_pose, std::vector< int > & inliers)
Definition at line 93 of file MotionSolver.hpp.
{
  return runRansac<SampleConsensusProblem>(
      sample_consensus_problem_ptr, params.threshold, params.ransac_iterations,
      params.ransac_probability, params.do_nonlinear_optimization, best_pose,
      inliers);
}
References dyno::RansacProblemParams::do_nonlinear_optimization, dyno::RansacProblemParams::ransac_iterations, dyno::RansacProblemParams::ransac_probability, and dyno::RansacProblemParams::threshold.
safeCast() [1/4]
template<class Base , class Derived > Derived dyno::safeCast (const Base & base) inline
Definition at line 41 of file SafeCast.hpp.
{
  try {
    return dynamic_cast<const Derived&>(base);
  } catch (const std::bad_cast& e) {
    LOG(ERROR) << "Seems that you are casting an object that is not "
                  "the one you expected!";
    LOG(FATAL) << e.what();
  } catch (...) {
    LOG(FATAL) << "Exception caught when dynamic casting.";
  }
}
safeCast() [2/4]
template<typename Base , typename Derived > std::shared_ptr< Derived > dyno::safeCast (std::shared_ptr< Base > base_ptr) inline
Definition at line 56 of file SafeCast.hpp.
{
  CHECK(base_ptr);
  try {
    return std::dynamic_pointer_cast<Derived>(base_ptr);
  } catch (const std::bad_cast& e) {
    LOG(ERROR) << "Seems that you are casting an object that is not "
                  "the one you expected!";
    LOG(FATAL) << e.what();
  } catch (...) {
    LOG(FATAL) << "Exception caught when dynamic casting.";
  }
}
safeCast() [3/4]
template<typename Base , typename Derived > std::shared_ptr< const Derived > dyno::safeCast (std::shared_ptr< const Base > base_ptr) inline
Definition at line 71 of file SafeCast.hpp.
{
  CHECK(base_ptr);
  std::shared_ptr<Base> base = std::const_pointer_cast<Base>(base_ptr);
  return safeCast<Base, Derived>(base);
}
safeCast() [4/4]
template<typename Base , typename Derived > std::unique_ptr< Derived > dyno::safeCast (std::unique_ptr< Base > && base_ptr) inline
Definition at line 83 of file SafeCast.hpp.
{
  std::unique_ptr<Derived> derived_ptr;
  Derived* tmp = nullptr;
  try {
    tmp = dynamic_cast<Derived*>(base_ptr.get());
  } catch (const std::bad_cast& e) {
    LOG(ERROR) << "Seems that you are casting an object that is not "
                  "the one you expected!";
    LOG(FATAL) << e.what();
  } catch (...) {
    LOG(FATAL) << "Exception caught when dynamic casting.";
  }
  if (!tmp) return nullptr;
  base_ptr.release();
  derived_ptr.reset(tmp);
  return derived_ptr;
}
safeCastToPreintegratedCombinedImuMeasurements()
const gtsam::PreintegratedCombinedMeasurements & dyno::safeCastToPreintegratedCombinedImuMeasurements (const gtsam::PreintegrationType & pim)
Definition at line 47 of file ImuFrontend.cc.
{
  try {
    return dynamic_cast<const gtsam::PreintegratedCombinedMeasurements&>(pim);
  } catch (const std::bad_cast& e) {
    LOG(ERROR) << "Seems that you are casting PreintegratedType to "
                  "PreintegratedCombinedMeasurements, but this object is not "
                  "a PreintegratedCombinedMeasurements!";
    LOG(FATAL) << e.what();
    throw e;
  }
}
Referenced by dyno::ImuFrontend::preintegrateImuMeasurements().
saveMatrixAsUpperTriangular()
bool dyno::saveMatrixAsUpperTriangular (std::ostream & os, const gtsam::Matrix & matrix) inline
Definition at line 273 of file Numerical.hpp.
{
  const size_t rows = matrix.rows();
  const size_t cols = matrix.cols();
  if (rows != cols) {
    throw std::runtime_error(
        "Attempting to save matrix as upper triangular but input size was not "
        "square");
  }
  for (size_t i = 0; i < rows; i++) {
    for (size_t j = i; j < cols; j++) {
      os << " " << matrix(i, j);
    }
  }
  return os.good();
}
Referenced by dyno::utils::saveNoiseModelAsUpperTriangular().
StaticLandmarkSymbol()
gtsam::Symbol dyno::StaticLandmarkSymbol (TrackletId tracklet_id) inline
Definition at line 136 of file Symbols.hpp.
{
  return gtsam::Symbol(kStaticLandmarkSymbolChar, tracklet_id);
}
References kStaticLandmarkSymbolChar.
Referenced by dyno::LandmarkNode< MEASUREMENT >::makeStaticKey().
stringToSeverity()
Severity dyno::stringToSeverity (const std::string & severity)
Definition at line 55 of file TrtUtilities.cc.
{
  std::map<std::string, Severity> level_map{
      {"INTERNAL_ERROR", Severity::kINTERNAL_ERROR},
      {"ERROR", Severity::kERROR},
      {"WARNING", Severity::kWARNING},
      {"INFO", Severity::kINFO},
      {"VERBOSE", Severity::kVERBOSE}};
  auto iter = level_map.find(severity);
  return iter == level_map.end() ? Severity::kINFO : iter->second;
}
Referenced by dyno::LoggingShim::setSeverity().
to_json() [1/6]
void dyno::to_json (json & j, const GroundTruthInputPacket & gt_packet)
Implements the required to_json (seralize) function for the nlohmann::json to automatically convert GroundTruthInputPacket to a json type.
This allows code like:
GroundTruthInputPacket gt_packet; using json = nlohmann::json; json j = gt_packet; auto gt_packet_2 = j.template get<GroundTruthInputPacket>();
to work automagically.
Note: we don't use adl (argument dependant lookup) because we control the namespace here
Parameters
j json&
gt_packet const GroundTruthInputPacket&
Definition at line 383 of file GroundTruthPacket.cc.
{
  j["timestamp"] = gt_packet.timestamp_;
  j["frame_id"] = gt_packet.frame_id_;
  j["X_world"] = gt_packet.X_world_;
  j["objects"] = gt_packet.object_poses_;
}
References dyno::GroundTruthInputPacket::frame_id_, dyno::GroundTruthInputPacket::object_poses_, dyno::GroundTruthInputPacket::timestamp_, and dyno::GroundTruthInputPacket::X_world_.
to_json() [2/6]
void dyno::to_json (json & j, const GroundTruthPacketMap & gt_packet_map)
Implements the required to_json (seralize) function for the nlohmann::json to automatically convert GroundTruthPacketMap to a json type.
Parameters
j json&
gt_packet_map GroundTruthPacketMap&
Definition at line 398 of file GroundTruthPacket.cc.
{
  // have to do manual conversion to stl map so the json library can do
  // automagic conversion lots of copying
  std::map<FrameId, GroundTruthInputPacket> stl_map = gt_packet_map;
  j["ground_truths"] = stl_map;
}
to_json() [3/6]
void dyno::to_json (json & j, const Histogram & histogram)
Definition at line 37 of file Histogram.cc.
{
  // json bin;
  // bin["upper"]
  // j[histogram.name_]
  auto impl_hist = histogram.histogram_;
  std::vector<std::vector<json>> bins(impl_hist.rank());
  for (auto&& x : bh::indexed(impl_hist)) {
    for (size_t i = 0; i < impl_hist.rank(); ++i) {
      json bin;
      bin["lower"] = x.bin(i).lower();
      bin["upper"] = x.bin(i).upper();
      std::stringstream ss;
      ss << *x;
      double value;
      ss >> value;
      bin["count"] = value;
      bins.at(i).push_back(bin);
    }
  }
  j[histogram.name_] = bins;
}
References dyno::Histogram::histogram_, and dyno::Histogram::name_.
to_json() [4/6]
void dyno::to_json (json & j, const ObjectPoseGT & object_pose_gt)
Implements the required to_json (seralize) function for the nlohmann::json to automatically convert ObjectPoseGT to a json type.
Used internally when seralizing the GroundTruthInputPacket.
Parameters
j json&
object_pose_gt const ObjectPoseGT&
Definition at line 343 of file GroundTruthPacket.cc.
{
  j["frame_id"] = object_pose_gt.frame_id_;
  j["object_id"] = object_pose_gt.object_id_;
  // gtsam conversion provided by nlohmann::adl_serializer specalization in
  // JsonUtils.hpp
  j["L_camera"] = object_pose_gt.L_camera_;
  j["L_world"] = object_pose_gt.L_world_;
  j["bounding_box"] = object_pose_gt.bounding_box_;
  // we have json conversions for both std::optional AND eigen
  j["object_dimensions"] = object_pose_gt.object_dimensions_;
  j["prev_H_current_world"] = object_pose_gt.prev_H_current_world_;
  j["prev_H_current_L"] = object_pose_gt.prev_H_current_L_;
  j["prev_H_current_X"] = object_pose_gt.prev_H_current_X_;
  j["motion_info"] = object_pose_gt.motion_info_;
}
References dyno::ObjectPoseGT::bounding_box_, dyno::ObjectPoseGT::frame_id_, dyno::ObjectPoseGT::L_camera_, dyno::ObjectPoseGT::L_world_, dyno::ObjectPoseGT::motion_info_, dyno::ObjectPoseGT::object_dimensions_, dyno::ObjectPoseGT::object_id_, dyno::ObjectPoseGT::prev_H_current_L_, dyno::ObjectPoseGT::prev_H_current_world_, and dyno::ObjectPoseGT::prev_H_current_X_.
to_json() [5/6]
void dyno::to_json (json & j, const ObjectPoseGT::MotionInfo & motion_info)
Below is the JSON seralize/deseralize functions for all the GroundTruthPacket types. We use the nlohmann::json library (https://json.nlohmann.me/) - see the Arbitrary types conversions section in the readme (https://github.com/nlohmann/json?tab=readme-ov-file#integration) for details on the implemententation.
Implements the required to_json (seralize) function for the nlohmann::json to automatically convert ObjectPoseGT::MotionInfo to a json type.
Used internally when seralizing the ObjectPoseGT.
Parameters
j json&
motion_info const ObjectPoseGT::MotionInfo&
Definition at line 333 of file GroundTruthPacket.cc.
{
  j["is_moving"] = motion_info.is_moving_;
  j["has_stopped"] = motion_info.has_stopped_;
}
References dyno::ObjectPoseGT::MotionInfo::has_stopped_, and dyno::ObjectPoseGT::MotionInfo::is_moving_.
to_json() [6/6]
void dyno::to_json (json & j, const ParallelObjectISAM::Result & result)
Definition at line 366 of file ParallelObjectISAM.cc.
{
  j["was_smoother_ok"] = result.was_smoother_ok;
  j["frame_id"] = result.frame_id;
  j["isam_result"] = result.isam_result;
  j["timing"] = result.timing;
  j["motions_with_large_change"] = result.motions_with_large_change;
  j["large_motion_change_delta"] = result.large_motion_change_delta;
  j["motion_variable_status"] = result.motion_variable_status;
  j["average_clique_size"] = result.average_clique_size;
  j["max_clique_size"] = result.max_clique_size;
  j["num_factors"] = result.num_factors;
  j["num_variables"] = result.num_variables;
  j["num_landmarks_marked"] = result.num_landmarks_marked;
  j["num_motions_marked"] = result.num_motions_marked;
  j["dynamic_map"] = result.dynamic_map;
}
References dyno::ParallelObjectISAM::Result::average_clique_size, dyno::ParallelObjectISAM::Result::dynamic_map, dyno::ParallelObjectISAM::Result::frame_id, dyno::ParallelObjectISAM::Result::isam_result, dyno::ParallelObjectISAM::Result::large_motion_change_delta, dyno::ParallelObjectISAM::Result::max_clique_size, dyno::ParallelObjectISAM::Result::motion_variable_status, dyno::ParallelObjectISAM::Result::motions_with_large_change, dyno::ParallelObjectISAM::Result::num_factors, dyno::ParallelObjectISAM::Result::num_landmarks_marked, dyno::ParallelObjectISAM::Result::num_motions_marked, dyno::ParallelObjectISAM::Result::num_variables, dyno::ParallelObjectISAM::Result::timing, and dyno::ParallelObjectISAM::Result::was_smoother_ok.
to_string() [1/7]
template<> std::string dyno::to_string (const DistortionModel & distortion)
Definition at line 45 of file CameraParams.cc.
{
  switch (distortion) {
    case DistortionModel::NONE:
      return "None";
      break;
    case DistortionModel::RADTAN:
      return "Radtan";
      break;
    case DistortionModel::EQUIDISTANT:
      return "Equidistant";
      break;
    case DistortionModel::FISH_EYE:
      return "Fish-eye";
      break;
    default:
      return "Unknown distortion model";
      break;
  }
}
References EQUIDISTANT, FISH_EYE, NONE, and RADTAN.
to_string() [2/7]
template<> std::string dyno::to_string (const FeatureTrackerInfo & info) inline
Definition at line 121 of file Vision-Definitions.hpp.
{
  std::stringstream ss;
  ss << "FeatureTrackerInfo: \n"
     << " - frame id: " << info.frame_id << "\n"
     << " - timestamp: " << std::setprecision(15) << info.timestamp << "\n"
     << "\t- # optical flow: " << info.static_track_optical_flow << "\n"
     << "\t- # detections: " << info.static_track_detections << "\n"
     << "\t- # new detections: " << info.new_static_detections << "\n";
  for (const auto& [object_id, object_status] : info.dynamic_track) {
    ss << "\t- Object: " << object_id << ": \n";
    ss << "\t\t - num_track " << object_status.num_track << "\n";
    ss << "\t\t - num_sampled " << object_status.num_sampled << "\n";
    ss << "\t\t - is new " << std::boolalpha << object_status.object_new
       << "\n";
    ss << "\t\t - resampled " << std::boolalpha
       << object_status.object_resampled << "\n";
    if (VLOG_IS_ON(20)) {
      ss << "\t\t - num_previous_track " << object_status.num_previous_track
         << "\n";
      ss << "\t\t - num_outside_shrunken_image "
         << object_status.num_outside_shrunken_image << "\n";
      ss << "\t\t - num_zero_flow " << object_status.num_zero_flow << "\n";
      ss << "\t\t - num_tracked_with_different_label "
         << object_status.num_tracked_with_different_label << "\n";
      ss << "\t\t - num_tracked_with_background_label "
         << object_status.num_tracked_with_background_label << "\n";
    }
  };
  return ss.str();
}
References dyno::FeatureTrackerInfo::dynamic_track, dyno::FeatureTrackerInfo::frame_id, dyno::FeatureTrackerInfo::new_static_detections, dyno::FeatureTrackerInfo::static_track_detections, dyno::FeatureTrackerInfo::static_track_optical_flow, and dyno::FeatureTrackerInfo::timestamp.
to_string() [3/7]
template<> std::string dyno::to_string (const InputImageMode & input_image_mode)
Definition at line 39 of file OnlineDataProviderRos.cc.
{
  std::string status_str = "";
  switch (input_image_mode) {
    case InputImageMode::ALL: {
      status_str = "ALL";
      break;
    }
    case InputImageMode::RGBD: {
      status_str = "RGBD";
      break;
    }
    case InputImageMode::STEREO: {
      status_str = "STEREO";
      break;
    }
  }
  return status_str;
}
References ALL, RGBD, and STEREO.
to_string() [4/7]
template<> std::string dyno::to_string (const MotionRepresentationStyle & style)
Definition at line 72 of file Types.cc.
{
  switch (style) {
    case MotionRepresentationStyle::F2F:
      return "F2F";
    case MotionRepresentationStyle::KF:
      return "KF";
    default:
      return "Unknown MotionRepresentationStyle";
  }
};
References F2F, and KF.
to_string() [5/7]
template<> std::string dyno::to_string (const ReferenceFrame & reference_frame)
Definition at line 58 of file Types.cc.
{
  switch (reference_frame) {
    case ReferenceFrame::LOCAL:
      return "local";
    case ReferenceFrame::GLOBAL:
      return "global";
    case ReferenceFrame::OBJECT:
      return "object";
    default:
      return "Unknown reference frame";
  }
};
References GLOBAL, LOCAL, and OBJECT.
to_string() [6/7]
template<typename T > std::string dyno::to_string (const T & t)
to_string() [7/7]
template<> std::string dyno::to_string (const TrackingStatus & status) inline
Definition at line 61 of file Frontend-Definitions.hpp.
{
  std::string status_str = "";
  switch (status) {
    case TrackingStatus::VALID: {
      status_str = "VALID";
      break;
    }
    case TrackingStatus::INVALID: {
      status_str = "INVALID";
      break;
    }
    case TrackingStatus::DISABLED: {
      status_str = "DISABLED";
      break;
    }
    case TrackingStatus::FEW_MATCHES: {
      status_str = "FEW_MATCHES";
      break;
    }
    case TrackingStatus::LOW_DISPARITY: {
      status_str = "LOW_DISPARITY";
      break;
    }
  }
  return status_str;
}
References DISABLED, FEW_MATCHES, INVALID, LOW_DISPARITY, and VALID.
Referenced by CameraParams::constructGtsamCalibration< gtsam::Cal3_S2 >(), CameraParams::constructGtsamCalibration< gtsam::Cal3DS2 >(), CameraParams::constructGtsamCalibration< gtsam::Cal3Fisheye >(), dyno::StereoCamera::computeRectificationParameters(), dyno::CameraParams::distortionModelToString(), dyno::UndistorterRectifier::initUndistortRectifyMaps(), dyno::RGBDInstanceFrontendModule::nominalSpin(), dyno::RGBDInstanceFrontendModule::solveCameraMotion(), dyno::ObjectMotionSovlerF2F::solveImpl(), dyno::CameraParams::toString(), dyno::ImageBase::toString(), and dyno::UndistorterRectifier::UndistortRectifyKeypoints().
to_string< cv::Rect >()
template<> std::string dyno::to_string< cv::Rect > (const cv::Rect & t)
Definition at line 57 of file OpenCVUtils.cc.
{
  return "[x=" + std::to_string(t.x) + " y=" + std::to_string(t.y) +
         " h=" + std::to_string(t.height) + " w=" + std::to_string(t.width) +
         "]";
}
to_string< cv::Size >()
template<> std::string dyno::to_string< cv::Size > (const cv::Size & t)
Definition at line 51 of file OpenCVUtils.cc.
{
  return "[h=" + std::to_string(t.height) + " w=" + std::to_string(t.width) +
         "]";
}
toRightHandedRotation()
gtsam::Rot3 dyno::toRightHandedRotation (const gtsam::Rot3 & left_handed_rotation)
Considers the conversion from left-handed system (e.g. unreal, VIODE, carla...) to right-handed system.
Parameters
left_handed_rotation const gtsam::Rot3&
Returns
gtsam::Rot3
Definition at line 59 of file DataProviderUtils.cc.
{
  const gtsam::Vector3 left_rpy = left_handed_rotation.rpy();
  double right_roll = left_rpy[0];
  double right_pitch = -left_rpy[1];
  double right_yaw = -left_rpy[2];
  return gtsam::Rot3::Ypr(right_yaw, right_pitch, right_roll);
}
Referenced by toRightHandedVector().
toRightHandedTwist()
void dyno::toRightHandedTwist (gtsam::Vector3 & right_handed_linear_velocity, gtsam::Vector3 & right_handed_angular_velocity, const gtsam::Vector3 & left_handed_linear_velocity, const gtsam::Vector3 & left_handed_angular_velocity, std::optional< gtsam::Rot3 > left_handed_rotation = {})
Considers the conversion from the left-handed coordiante system (e.g. unreal, VIODE, carla...) to the right-handed coordinate system (robotic).
Taken from: https://github.com/carla-simulator/ros-bridge/blob/master/carla_common/src/carla_common/transforms.py#L41
Parameters
right_handed_linear_velocity gtsam::Vector3&
right_handed_angular_velocity gtsam::Vector3&
left_handed_linear_velocity const gtsam::Vector3&
left_handed_angular_velocity const gtsam::Vector3&
left_handed_rotation std::optional<gtsam::Rot3>
Definition at line 46 of file DataProviderUtils.cc.
{
  right_handed_linear_velocity =
      toRightHandedVector(left_handed_linear_velocity, left_handed_rotation);
  right_handed_angular_velocity[0] = left_handed_angular_velocity[0];
  right_handed_angular_velocity[1] = -left_handed_angular_velocity[1];
  right_handed_angular_velocity[2] = -left_handed_angular_velocity[2];
}
References toRightHandedVector().
toRightHandedVector()
gtsam::Vector3 dyno::toRightHandedVector (const gtsam::Vector3 & left_handed_vector, std::optional< gtsam::Rot3 > left_handed_rotation)
Considers the conversion from a left-handed system (e.g. unreal, VIODE, carla...) vector to right-handed system with optional rotation provided in the left-handed system.
Parameters
left_handed_vector const gtsam::Vector3&
left_handed_rotation std::optional<gtsam::Rot3>
Returns
gtsam::Vector3
Definition at line 69 of file DataProviderUtils.cc.
{
  gtsam::Vector3 tmp_vector = left_handed_vector;
  if (left_handed_rotation) {
    const gtsam::Rot3 right_handed_rotation =
        toRightHandedRotation(*left_handed_rotation);
    tmp_vector = right_handed_rotation.rotate(left_handed_vector);
  }
  gtsam::Vector3 right_handed_vector;
  right_handed_vector[0] = tmp_vector[0];
  right_handed_vector[1] = -tmp_vector[1];
  right_handed_vector[2] = tmp_vector[2];
  // apparently just swap axis according to Sephyr...
  return right_handed_vector;
}
References toRightHandedRotation().
Referenced by toRightHandedTwist().
toString() [1/3]
std::string dyno::toString (const nvinfer1::Dims & dims)
Definition at line 280 of file TrtUtilities.cc.
{
  std::stringstream ss;
  ss << "[";
  for (int32_t i = 0; i < dims.nbDims - 1; ++i) {
    ss << dims.d[i] << " x ";
  }
  ss << dims.d[dims.nbDims - 1] << "]";
  return ss.str();
}
Referenced by operator<<().
toString() [2/3]
std::string dyno::toString (nvinfer1::DataType dtype)
Definition at line 290 of file TrtUtilities.cc.
{
  switch (dtype) {
    case nvinfer1::DataType::kFLOAT:
      return "FLOAT";
    case nvinfer1::DataType::kHALF:
      return "HALF";
    case nvinfer1::DataType::kINT8:
      return "INT8";
    case nvinfer1::DataType::kINT32:
      return "INT32";
    case nvinfer1::DataType::kBOOL:
      return "BOOL";
    case nvinfer1::DataType::kUINT8:
      return "UINT8";
    case nvinfer1::DataType::kFP8:
      return "FP8";
#if NV_TENSORRT_MAJOR >= 10
    case nvinfer1::DataType::kBF16:
      return "BF16";
    case nvinfer1::DataType::kINT64:
      return "INT64";
    case nvinfer1::DataType::kINT4:
      return "INT4";
#endif
    default:
      return "UNKNOWN: '" + std::to_string(static_cast<int>(dtype)) + "'";
  }
}
toString() [3/3]
std::string dyno::toString (nvinfer1::TensorIOMode mode)
Definition at line 319 of file TrtUtilities.cc.
{
  switch (mode) {
    case nvinfer1::TensorIOMode::kINPUT:
      return "in";
    case nvinfer1::TensorIOMode::kOUTPUT:
      return "out";
    default:
    case nvinfer1::TensorIOMode::kNONE:
      return "none";
  }
}
type_name() [1/2]
template<class T > std::string dyno::type_name ()
Get a demangled class name of type T from a templated type.
Template Parameters
T
Returns
std::string
Definition at line 183 of file Types.hpp.
                      {
  return demangle(typeid(T).name());
}
References demangle().
type_name() [2/2]
template<class T > std::string dyno::type_name (const T & t)
Get demangled class name of type T from an instance.
Template Parameters
T
Parameters
t
Returns
std::string
Definition at line 172 of file Types.hpp.
{
  return demangle(typeid(t).name());
}
References demangle().
updateAndCheckDynoParamsForRawImageInput()
void dyno::updateAndCheckDynoParamsForRawImageInput (DynoParams & dyno_params)
Updates and checks that all dyno params are set correctly for when only raw image data is providd (ie. RBGD or Stereo) and no object/flow pre-processing has been done.
Parameters
dyno_params
Definition at line 219 of file OnlineDataProviderRos.cc.
{
  auto& tracker_params = dyno_params.frontend_params_.tracker_params;
  if (tracker_params.prefer_provided_optical_flow) {
    LOG(WARNING)
        << "InputImageMode not set to ALL but prefer_provided_optical_flow is "
           "true - param will be updated!";
    tracker_params.prefer_provided_optical_flow = false;
  }
  if (tracker_params.prefer_provided_object_detection) {
    LOG(WARNING)
        << "InputImageMode not set to ALL but prefer_provided_object_detection "
           "is true - param will be updated!";
    tracker_params.prefer_provided_object_detection = false;
    // TODO: should also warn in this case that gt tracking will not match!!
  }
}
References dyno::DynoParams::frontend_params_, dyno::TrackerParams::prefer_provided_optical_flow, and dyno::FrontendParams::tracker_params.
Referenced by dyno::RGBDOnlineProviderRos::updateAndCheckParams().
validateMask()
void dyno::validateMask (const cv::Mat & input, const std::string & name)
Definition at line 43 of file ImageTypes.cc.
{
  // we guanrantee with a static assert that the SemanticMask and MotionMask
  // types are the same
  const static std::string expected_type =
      utils::cvTypeToString(ImageType::MotionMask::OpenCVType);
  if (input.type() != ImageType::MotionMask::OpenCVType) {
    throw InvalidImageTypeException(name + " image was not " + expected_type +
                                    ". Input image type was " +
                                    utils::cvTypeToString(input.type()));
  }
}
References dyno::utils::cvTypeToString(), and dyno::ImageType::MotionMask::OpenCVType.
Referenced by dyno::ImageType::SemanticMask::validate(), dyno::ImageType::MotionMask::validate(), and dyno::ImageType::ClassSegmentation::validate().
validateRGBMono()
void dyno::validateRGBMono (const cv::Mat & input)
Definition at line 55 of file ImageTypes.cc.
{
  if (input.type() != CV_8UC1 && input.type() != CV_8UC3 &&
      input.type() != CV_8UC4) {
    throw InvalidImageTypeException(
        "RGBMono image was not CV_8UC1, CV_8UC3 or CV_8UC4. Input image type "
        "was " +
        utils::cvTypeToString(input.type()));
  }
}
References dyno::utils::cvTypeToString().
Referenced by dyno::ImageType::RGBMono::validate().
validateSingleImage()
void dyno::validateSingleImage (const cv::Mat & input, int expected_type, const std::string & name)
Definition at line 65 of file ImageTypes.cc.
{
  if (input.type() != expected_type) {
    throw InvalidImageTypeException(
        name + " image was not " + utils::cvTypeToString(expected_type) +
        " - Input image type was " + utils::cvTypeToString(input.type()));
  }
}
References dyno::utils::cvTypeToString().
Referenced by dyno::ImageType::Depth::validate(), and dyno::ImageType::OpticalFlow::validate().
waitAndSetCameraParams()
template<class Rep = int64_t, class Period = std::milli> CameraParams dyno::waitAndSetCameraParams (std::shared_ptr< rclcpp::Node > node, const std::string & topic, const std::chrono::duration< Rep, Period > & time_to_wait = std::chrono::duration<Rep, Period>(-1))
Gets CameraParams from a sensor_msgs::msg::CameraInfo recieved on the specified topic. This function is blocking until a message is recieved (or until the time_to_wait) elapses.
While this function returns a const ref to the CameraParams it also sets the internal camera_params_. The camera params are then returned by the overwritten getCameraParams, allowing the PipelineManager to access the correct camera paramters.
Template Parameters
Rep int64_t,
Period std::milli
Parameters
time_to_wait const std::chrono::duration<Rep, Period>&
topic const std::string&. Defaults to "image/camera_info"
Returns
const CameraParams&
Definition at line 65 of file DataProviderRos.hpp.
{
  RCLCPP_INFO_STREAM(node->get_logger(),
                     "Waiting for camera params on topic: " << topic);
  // it seems rclcpp::Adaptors do not work yet with wait for message
  sensor_msgs::msg::CameraInfo camera_info;
  if (rclcpp::wait_for_message<sensor_msgs::msg::CameraInfo, Rep, Period>(
          camera_info, node, topic, time_to_wait)) {
    using Adaptor =
        rclcpp::TypeAdapter<dyno::CameraParams, sensor_msgs::msg::CameraInfo>;
    CameraParams camera_params;
    Adaptor::convert_to_custom(camera_info, camera_params);
    RCLCPP_INFO_STREAM(node->get_logger(),
                       "Received camera params: " << camera_params.toString());
    return camera_params;
  } else {
    const auto milliseconds =
        std::chrono::duration_cast<std::chrono::milliseconds>(time_to_wait);
    throw DynosamException("Failed to receive camera params on topic " + topic +
                           " (waited with timeout " +
                           std::to_string(milliseconds.count()) + " ms).");
  }
}
References dyno::CameraParams::toString().
Referenced by main(), and dyno::RGBDTypeCalibrationHelper::RGBDTypeCalibrationHelper().
wrapTwoPi()
double dyno::wrapTwoPi (double ang) inline
Wraps an angle between [0... 2*PI].
Parameters
ang angle in radians
Returns
double
Definition at line 190 of file Numerical.hpp.
{ return mod(ang, 2.0 * M_PI); }
References mod().
Referenced by dyno::utils::TRErrorPairVector::average().
writeJson()
template<typename T > std::ofstream & dyno::writeJson (std::ofstream & os, const T & t)
Definition at line 158 of file Logger.hpp.
{
  // T must be json seralizable
  const json j = t;
  os << std::setw(4) << j;
  return os;
};
writeMatrixWithPythonFormat()
bool dyno::writeMatrixWithPythonFormat (const gtsam::Matrix & matrix, const std::string & filename) inline
Definition at line 260 of file Numerical.hpp.
{
  std::ofstream file(filename);
  if (file.is_open()) {
    file << matrix.format(Eigen::IOFormat(Eigen::StreamPrecision,
                                          Eigen::DontAlignCols, " ", "\n"));
    file.close();
    return true;
  } else {
    return false;
  }
}
writeStatisticsModuleSummariesToFile()
void dyno::writeStatisticsModuleSummariesToFile ()
Writes statistics per module to csv files on path defined by getOutputFilePath(). Interrnally uses WritePerModuleSummariesToCsvFile.
Definition at line 59 of file Logger.cc.
{
  utils::Statistics::WritePerModuleSummariesToCsvFile(getOutputFilePath(""));
}
References getOutputFilePath(), and dyno::utils::Statistics::WritePerModuleSummariesToCsvFile().
Referenced by dyno::BackendExperimentsNode::~BackendExperimentsNode(), and dyno::DynoPipelineManager::~DynoPipelineManager().
writeStatisticsSamplesToFile()
void dyno::writeStatisticsSamplesToFile (const std::string & file_name = "statistics_samples.csv")
Writes all the statistics to a csv file on the path defined by getOutputFilePath(file_name).
The output csv file has a header "label, samples" Where ALL recorded samples per label are saved to file.
Internally uses Statistics::WriteAllSamplesToCsvFile.
Default file name is statistics_samples.csv.
Parameters
file_name
Returns
true
false
Definition at line 51 of file Logger.cc.
{
  utils::Statistics::WriteAllSamplesToCsvFile(getOutputFilePath(file_name));
}
References getOutputFilePath(), and dyno::utils::Statistics::WriteAllSamplesToCsvFile().
Referenced by dyno::BackendExperimentsNode::~BackendExperimentsNode(), and dyno::DynoPipelineManager::~DynoPipelineManager().
writeStatisticsSummaryToFile()
void dyno::writeStatisticsSummaryToFile (const std::string & file_name = "statistics.csv")
Writes a summary of the statistics to a csv file on the path defined by getOutputFilePath(file_name).
Internally uses Statistics::WriteSummaryToCsvFile.
Default file name is statistics.csv.
Parameters
file_name
Returns
true
false
Definition at line 55 of file Logger.cc.
{
  utils::Statistics::WriteSummaryToCsvFile(getOutputFilePath(file_name));
}
References getOutputFilePath(), and dyno::utils::Statistics::WriteSummaryToCsvFile().
Variable Documentation
background_label
constexpr ObjectId dyno::background_label = 0u static constexpr
Expected label for the background in a semantic or motion mask.
Definition at line 188 of file Types.hpp.
Referenced by dyno::Map< MEASUREMENT >::addOrUpdateMapStructures(), dyno::ObjectDetectionResult::colouredMask(), dyno::KltFeatureTracker::constructNewStaticFeature(), dyno::ExternalFlowFeatureTracker::constructStaticFeature(), dyno::KltFeatureTracker::constructStaticFeatureFromPrevious(), dyno::KltFeatureTracker::detectFeatures(), dyno::VisualMeasurementStatus< T >::Dynamic(), dyno::VisualMeasurementStatus< T >::DynamicInGLobal(), dyno::VisualMeasurementStatus< T >::DynamicInLocal(), dyno::RGBDInstanceFrontendModule::fillOutputPacketWithTracks(), dyno::vision_tools::getObjectLabels(), dyno::TrackedValueStatus< VALUE >::isStatic(), dyno::LandmarkNode< MEASUREMENT >::isStatic(), dyno::SingleDetectionResult::isValid(), dyno::utils::labelMaskToRGB(), main(), dyno::vision_tools::makeTrackletLengthHistorgram(), dyno::Frame::projectToDenseCloud(), PYBIND11_MODULE(), dyno::vision_tools::shrinkMask(), dyno::VisualMeasurementStatus< T >::Static(), dyno::VisualMeasurementStatus< T >::StaticInGlobal(), dyno::VisualMeasurementStatus< T >::StaticInLocal(), dyno::ImageType::MotionMask::toRGB(), dyno::ImageType::SemanticMask::toRGB(), dyno::FeatureTracker::trackDynamic(), dyno::FeatureTracker::trackDynamicKLT(), dyno::KltFeatureTracker::trackPoints(), and dyno::ExternalFlowFeatureTracker::trackStatic().
bit_pattern_31_
int dyno::bit_pattern_31_[256 *4] static
Definition at line 165 of file ORBextractor.cc.
Referenced by dyno::ORBextractor::ORBextractor().
DefaultRuntimeSensorOptions
constexpr RuntimeSensorOptions dyno::DefaultRuntimeSensorOptions static constexpr
Initial value:
{
    RuntimeSensorOptions::PreferSensor | RuntimeSensorOptions::AcceptNoSensor}
Default runtime sensor options are PreferSensor AND AcceptNoSensor This means that we will try an use the most sensor data available but continue if not
Definition at line 69 of file PipelineParams.hpp.
EDGE_THRESHOLD
const int dyno::EDGE_THRESHOLD = 19
Definition at line 91 of file ORBextractor.cc.
Referenced by dyno::ORBextractor::ComputeKeyPointsOctTree(), dyno::ORBextractor::ComputeKeyPointsOld(), and dyno::ORBextractor::ComputePyramid().
factorPI
const float dyno::factorPI = (float)(CV_PI / 180.f)
Definition at line 119 of file ORBextractor.cc.
Referenced by computeOrbDescriptor().
HALF_PATCH_SIZE
const int dyno::HALF_PATCH_SIZE = 15
Definition at line 90 of file ORBextractor.cc.
Referenced by IC_Angle(), and dyno::ORBextractor::ORBextractor().
InvalidDynoSymbol
constexpr SymbolChar dyno::InvalidDynoSymbol = '\0' static constexpr
Definition at line 22 of file Symbols.hpp.
Referenced by DynoChrExtractor().
InvalidTimestamp
constexpr Timestamp dyno::InvalidTimestamp = 0 static constexpr
Definition at line 67 of file Types.hpp.
Referenced by dyno::ImuInterfaceHandler::getTimeSyncedImuMeasurements().
is_variant_member_v
template<typename T , typename... Variants> constexpr bool dyno::is_variant_member_v inline constexpr
Initial value:
=
    internal::is_variant_member<T, Variants...>::value
Definition at line 77 of file Variant.hpp.
is_variant_v
template<typename T > constexpr bool dyno::is_variant_v = internal::is_variant<T>::value inline constexpr
Definition at line 74 of file Variant.hpp.
IsDerivedTrackedValueStatus
template<typename DERIVEDSTATUS , typename VALUE > constexpr bool dyno::IsDerivedTrackedValueStatus inline constexpr
Initial value:
=
    std::is_base_of_v<TrackedValueStatus<VALUE>, DERIVEDSTATUS>
Check if derived DERIVEDSTATUS us in factor derived from Status<Value>
Template Parameters
DERIVEDSTATUS derived type
VALUE expected value to templated base Status on
Definition at line 449 of file Types.hpp.
kDynamicLandmarkSymbolChar
constexpr SymbolChar dyno::kDynamicLandmarkSymbolChar = 'm' static constexpr
Definition at line 19 of file Symbols.hpp.
Referenced by DynamicLandmarkSymbol(), DynosamKeyFormatter(), DynosamKeyFormatterVerbose(), dyno::ApplyFunctionalSymbol::operator()(), and dyno::ParallelHybridBackendModule::ParallelHybridBackendModule().
kImuBiasSymbolChar
constexpr SymbolChar dyno::kImuBiasSymbolChar = 'b' static constexpr
Definition at line 20 of file Symbols.hpp.
Referenced by dyno::VisionImuBackendModule< MODULE_TRAITS >::addInitialVisualInertialState(), dyno::VisionImuBackendModule< MODULE_TRAITS >::addVisualInertialStates(), dyno::VisionImuBackendModule< MODULE_TRAITS >::getInvolvedStates(), and dyno::VisionImuBackendModule< MODULE_TRAITS >::navState().
kObjectMotionSymbolChar
constexpr SymbolChar dyno::kObjectMotionSymbolChar = 'H' static constexpr
Definition at line 16 of file Symbols.hpp.
Referenced by DynosamKeyFormatter(), DynosamKeyFormatterVerbose(), H(), dyno::ApplyFunctionalSymbol::operator()(), dyno::ParallelHybridBackendModule::ParallelHybridBackendModule(), reconstructMotionInfo(), and dyno::ParallelObjectISAM::updateStates().
kObjectPoseSymbolChar
constexpr SymbolChar dyno::kObjectPoseSymbolChar = 'L' static constexpr
Definition at line 17 of file Symbols.hpp.
Referenced by DynosamKeyFormatter(), DynosamKeyFormatterVerbose(), L(), dyno::ApplyFunctionalSymbol::operator()(), and reconstructPoseInfo().
kPoseSymbolChar
constexpr SymbolChar dyno::kPoseSymbolChar = 'X' static constexpr
Definition at line 14 of file Symbols.hpp.
Referenced by dyno::VisionImuBackendModule< MODULE_TRAITS >::addVisualInertialStates(), CameraPoseSymbol(), dyno::ApplyFunctionalSymbol::operator()(), and dyno::ParallelHybridBackendModule::ParallelHybridBackendModule().
kRgbdFrontendOutputJsonFile
constexpr char dyno::kRgbdFrontendOutputJsonFile[] static constexpr
Initial value:
=
    "rgbd_frontend_output.bson"
Definition at line 41 of file Frontend-Definitions.hpp.
Referenced by dyno::BackendExperimentsNode::BackendExperimentsNode(), and dyno::RGBDInstanceFrontendModule::~RGBDInstanceFrontendModule().
kStaticLandmarkSymbolChar
constexpr SymbolChar dyno::kStaticLandmarkSymbolChar = 'l' static constexpr
Definition at line 18 of file Symbols.hpp.
Referenced by dyno::ApplyFunctionalSymbol::operator()(), and StaticLandmarkSymbol().
kVelocitySymbolChar
constexpr SymbolChar dyno::kVelocitySymbolChar = 'V' static constexpr
Definition at line 15 of file Symbols.hpp.
Referenced by dyno::VisionImuBackendModule< MODULE_TRAITS >::addInitialVisualInertialState(), dyno::VisionImuBackendModule< MODULE_TRAITS >::addVisualInertialStates(), dyno::VisionImuBackendModule< MODULE_TRAITS >::getInvolvedStates(), and dyno::VisionImuBackendModule< MODULE_TRAITS >::navState().
MaxDetections
constexpr int dyno::MaxDetections = 8400 static constexpr
Definition at line 75 of file YoloV8ObjectDetector.hpp.
Referenced by dyno::YoloV8ObjectDetector::Impl::Impl(), and dyno::YoloV8ObjectDetector::Impl::postprocess().
NaN
constexpr auto dyno::NaN = std::numeric_limits<double>::quiet_NaN() static constexpr
Definition at line 63 of file Types.hpp.
Referenced by dyno::ObjectMotionSovlerF2F::geometricOutlierRejection3d2d(), dyno::ParallelHybridBackendModule::nominalUpdateStaticEstimator(), dyno::RGBDInstanceFrontendModule::solveCameraMotion(), and dyno::ParallelObjectISAM::updateSmoother().
PackageName
constexpr auto dyno::PackageName = "dynosam_nn" static constexpr
Definition at line 10 of file ModelConfig.cc.
Referenced by getDynosamNNShareDirectory().
PATCH_SIZE
const int dyno::PATCH_SIZE = 31
Definition at line 89 of file ORBextractor.cc.
Referenced by dyno::ORBextractor::ComputeKeyPointsOctTree(), and dyno::ORBextractor::ComputeKeyPointsOld().
rd
std::random_device dyno::rd
Definition at line 38 of file Colour.cc.
Referenced by dyno::utils::perturbWithUniformNoise().
UninitialisedSlot
constexpr Slot dyno::UninitialisedSlot static constexpr
Initial value:
=
    -1
Definition at line 198 of file BackendDefinitions.hpp.