DynoSAM: dyno::factor_graph_tools Namespace Reference
dyno::factor_graph_tools Namespace Reference
Classes
struct DrawBlockJacobiansOptions
struct SparsityStats
struct travsersal
Functions
SmartProjectionFactor::shared_ptr constructSmartProjectionFactor (gtsam::SharedNoiseModel smart_noise, boost::shared_ptr< CalibrationType > K, SmartProjectionFactorParams projection_params)
SmartProjectionFactor::shared_ptr constructSmartProjectionFactor (gtsam::SharedNoiseModel smart_noise, boost::shared_ptr< CalibrationType > K, SmartProjectionFactorParams projection_params, Keypoint measurement, FrameId frame_id)
void addBetweenFactor (FrameId from_frame, FrameId to_frame, const gtsam::Pose3 from_pose_to, gtsam::SharedNoiseModel noise_model, gtsam::NonlinearFactorGraph &graph)
void addSmartProjectionMeasurement (SmartProjectionFactor::shared_ptr smart_factor, Keypoint measurement, FrameId frame_id)
template<typename DERIVEDFACTOR >
gtsam::FactorIndices determineFactorOutliers (const gtsam::NonlinearFactorGraph &graph, const gtsam::Values &values, double confidence=0.99)
template<typename GRAPH >
size_t getAssociatedFactors (std::vector< typename GRAPH::const_iterator > &associated_factors, const GRAPH &graph, gtsam::Key query_key)
template<typename GRAPH >
size_t getAssociatedFactors (gtsam::FactorIndices &associated_factors, const GRAPH &graph, gtsam::Key query_key)
template<typename GRAPH >
size_t getAssociatedFactors (std::vector< typename GRAPH::sharedFactor > &associated_factors, const GRAPH &graph, gtsam::Key query_key)
SparsityStats computeHessianSparsityStats (gtsam::GaussianFactorGraph::shared_ptr gaussian_fg, const std::optional< gtsam::Ordering > &ordering={})
SparsityStats computeJacobianSparsityStats (gtsam::GaussianFactorGraph::shared_ptr gaussian_fg, const std::optional< gtsam::Ordering > &ordering={})
template<class CLIQUE >
void dotBayesTree (std::ostream &s, boost::shared_ptr< CLIQUE > clique, const gtsam::KeyFormatter &keyFormatter, const gtsam::FastMap< gtsam::Key, std::string > &colour_map={}, int parentnum=0)
template<class CLIQUE >
void saveBayesTree (const gtsam::BayesTree< CLIQUE > &tree, const std::string &filename, const gtsam::KeyFormatter &keyFormatter, const gtsam::FastMap< gtsam::Key, std::string > colour_map={})
std::pair< SparsityStats, cv::Mat > computeRFactor (gtsam::GaussianFactorGraph::shared_ptr gaussian_fg, const gtsam::Ordering ordering)
cv::Mat drawBlockJacobians (gtsam::GaussianFactorGraph::shared_ptr gaussian_fg, const gtsam::Ordering &ordering, const DrawBlockJacobiansOptions &options)
template<typename T >
void toGraphFileFormat (std::ostream &os, const T &t)
template<typename T >
std::ostream & seralizeFactorToGraphFileFormat (std::ostream &os, const T &t, const std::string &tag)
template<typename T >
std::ostream & seralizeValueToGraphFileFormat (std::ostream &os, const T &t, gtsam::Key key, const std::string &tag)
template<>
void toGraphFileFormat< gtsam::Point3 > (std::ostream &os, const gtsam::Point3 &t)
template<>
void toGraphFileFormat< gtsam::Pose3 > (std::ostream &os, const gtsam::Pose3 &t)
template<>
void toGraphFileFormat< gtsam::PriorFactor< gtsam::Pose3 > > (std::ostream &os, const gtsam::PriorFactor< gtsam::Pose3 > &t)
template<>
void toGraphFileFormat< gtsam::BetweenFactor< gtsam::Pose3 > > (std::ostream &os, const gtsam::BetweenFactor< gtsam::Pose3 > &t)
template<>
void toGraphFileFormat< LandmarkMotionTernaryFactor > (std::ostream &os, const LandmarkMotionTernaryFactor &t)
template<>
void toGraphFileFormat< gtsam::PoseToPointFactor< gtsam::Pose3, Landmark > > (std::ostream &os, const gtsam::PoseToPointFactor< gtsam::Pose3, Landmark > &t)
Function Documentation
addBetweenFactor()
void dyno::factor_graph_tools::addBetweenFactor (FrameId from_frame, FrameId to_frame, const gtsam::Pose3 from_pose_to, gtsam::SharedNoiseModel noise_model, gtsam::NonlinearFactorGraph & graph)
Definition at line 73 of file FactorGraphTools.cc.
{
    CHECK(noise_model);
    CHECK_EQ(noise_model->dim(), 6u);
    graph.emplace_shared<gtsam::BetweenFactor<gtsam::Pose3>>(
        CameraPoseSymbol(from_frame),
        CameraPoseSymbol(to_frame),
        from_pose_to,
        noise_model
    );
}
References dyno::CameraPoseSymbol().
Referenced by dyno::Formulation< MAP >::addOdometry().
addSmartProjectionMeasurement()
void dyno::factor_graph_tools::addSmartProjectionMeasurement (SmartProjectionFactor::shared_ptr smart_factor, Keypoint measurement, FrameId frame_id)
Definition at line 86 of file FactorGraphTools.cc.
{
    smart_factor->add(measurement, CameraPoseSymbol(frame_id));
}
References dyno::CameraPoseSymbol().
Referenced by constructSmartProjectionFactor().
computeHessianSparsityStats()
SparsityStats dyno::factor_graph_tools::computeHessianSparsityStats (gtsam::GaussianFactorGraph::shared_ptr gaussian_fg, const std::optional< gtsam::Ordering > & ordering = {})
Definition at line 90 of file FactorGraphTools.cc.
{
    if(ordering) {
        return SparsityStats(gaussian_fg->hessian(*ordering).first);
    }
    return SparsityStats(gaussian_fg->hessian().first);
}
Referenced by dyno::FactorGraphManager< GRAPH >::computeHessianSparsityStats().
computeJacobianSparsityStats()
SparsityStats dyno::factor_graph_tools::computeJacobianSparsityStats (gtsam::GaussianFactorGraph::shared_ptr gaussian_fg, const std::optional< gtsam::Ordering > & ordering = {})
Definition at line 98 of file FactorGraphTools.cc.
{
    //NOTE: GaussianFactorGraph::jacobian(Ordering) SHOULD be the same as calling gtsam::JacobianFactor(GaussianFactorGraph, ordering)
    //and it is in the code when this was tested but I guess this could change, leading to consistencies with how the Jacobain factor is constructed
    //in differnet fg_tool functions
    if(ordering) {
        return SparsityStats(gaussian_fg->jacobian(*ordering).first);
    }
    return SparsityStats(gaussian_fg->jacobian().first);
}
Referenced by dyno::FactorGraphManager< GRAPH >::computeJacobianSparsityStats().
computeRFactor()
std::pair< SparsityStats, cv::Mat > dyno::factor_graph_tools::computeRFactor (gtsam::GaussianFactorGraph::shared_ptr gaussian_fg, const gtsam::Ordering ordering)
Not entirely sure the difference between the joint factor we get out and the inital jacobian factor we get in I believe the difference is in the ordering which we do NOT apply when constructing the jacobian_factor. I'm not sure this is correct.
Not entirely sure the difference between the joint factor we get out and the inital jacobian factor we get in I believe the difference is in the ordering which we do NOT apply when constructing the jacobian_factor. I'm not sure this is correct.
Definition at line 109 of file FactorGraphTools.cc.
{
    //TODO: why do we need to specify the ordering twice?
    //I think we should probaly construct the graph with native ordeing but then elimate with provided ordering?
    gtsam::JacobianFactor jacobian_factor(*gaussian_fg);
    gtsam::GaussianConditional::shared_ptr conditional;
    gtsam::JacobianFactor::shared_ptr joint_factor;
    std::tie(conditional, joint_factor) = jacobian_factor.eliminate(ordering);
    CHECK(conditional);
    const gtsam::VerticalBlockMatrix::constBlock R = conditional->R();
    //drawn image
    cv::Mat R_img(cv::Size(R.cols(), R.rows()), CV_8UC3, cv::viz::Color::white());
    for (int i = 0; i < R.rows(); ++i) {
        for (int j = 0; j < R.cols(); ++j) {
            //only draw if non zero
            if (std::fabs(R(i, j)) > 1e-15) {
                R_img.at<cv::Vec3b>(i, j) =  (cv::Vec3b)cv::viz::Color::black();
            }
        }
    }
    cv::imshow("R", R_img);
    cv::waitKey(0);
}
constructSmartProjectionFactor() [1/2]
SmartProjectionFactor::shared_ptr dyno::factor_graph_tools::constructSmartProjectionFactor (gtsam::SharedNoiseModel smart_noise, boost::shared_ptr< CalibrationType > K, SmartProjectionFactorParams projection_params)
Definition at line 41 of file FactorGraphTools.cc.
{
    CHECK(smart_noise);
    CHECK(K);
    return boost::make_shared<SmartProjectionFactor>(
                smart_noise,
                K,
                projection_params);
}
Referenced by constructSmartProjectionFactor().
constructSmartProjectionFactor() [2/2]
SmartProjectionFactor::shared_ptr dyno::factor_graph_tools::constructSmartProjectionFactor (gtsam::SharedNoiseModel smart_noise, boost::shared_ptr< CalibrationType > K, SmartProjectionFactorParams projection_params, Keypoint measurement, FrameId frame_id)
Definition at line 55 of file FactorGraphTools.cc.
{
    SmartProjectionFactor::shared_ptr smart_factor = constructSmartProjectionFactor(
        smart_noise,
        K,
        projection_params);
    CHECK(smart_factor);
    addSmartProjectionMeasurement(smart_factor, measurement, frame_id);
    return smart_factor;
}
References addSmartProjectionMeasurement(), and constructSmartProjectionFactor().
determineFactorOutliers()
template<typename DERIVEDFACTOR > gtsam::FactorIndices dyno::factor_graph_tools::determineFactorOutliers (const gtsam::NonlinearFactorGraph & graph, const gtsam::Values & values, double confidence = 0.99)
Definition at line 70 of file FactorGraphTools.hpp.
{
    gtsam::FactorIndices outlier_indicies;
    for (size_t k = 0; k < graph.size(); k++) {
        if (!graph[k]) continue;
        auto derived_factor = boost::dynamic_pointer_cast<DERIVEDFACTOR>(graph[k]);
        if(derived_factor) {
            double weighted_threshold = 0.5 * chi_squared_quantile(derived_factor->dim(), confidence); // 0.5 derives from the error definition in gtsam
            //NOTE: double casting as we expect DERIVEDFACTOR to be a NoiseModelFactor
            gtsam::NoiseModelFactor::shared_ptr nm_factor = boost::dynamic_pointer_cast<gtsam::NoiseModelFactor>(derived_factor);
            CHECK(nm_factor);
            // all noise models must be gaussian otherwise whittening will be reweighted
            auto robust = boost::dynamic_pointer_cast<gtsam::noiseModel::Robust>(nm_factor->noiseModel());
            auto gaussian_nm_factor = robust ? nm_factor-> cloneWithNewNoiseModel(robust->noise()) : nm_factor;
            CHECK(gaussian_nm_factor);
            double error = gaussian_nm_factor->error(values);
            if(error > weighted_threshold ) {
                outlier_indicies.push_back(k);
            }
        }
    }
    return outlier_indicies;
}
References dyno::chi_squared_quantile().
Referenced by dyno::OpticalFlowAndPoseOptimizer::optimize(), and dyno::MotionOnlyRefinementOptimizer::optimize().
dotBayesTree()
template<class CLIQUE > void dyno::factor_graph_tools::dotBayesTree (std::ostream & s, boost::shared_ptr< CLIQUE > clique, const gtsam::KeyFormatter & keyFormatter, const gtsam::FastMap< gtsam::Key, std::string > & colour_map = {}, int parentnum = 0)
Definition at line 291 of file FactorGraphTools.hpp.
                                                                                    {},
                              int parentnum = 0) {
    static int num = 0;
    bool first = true;
    std::stringstream out;
    out << num;
    std::string parent = out.str();
    parent += "[label=\"";
    //frontal key since this is what is used to add to nodes [j] (ie.e j is a frontal key)
    bool keyInColourMap = false;
    std::string colour;
    for (auto key : clique->conditional_->frontals()) {
      if (!first) parent += ", ";
      first = false;
      parent += keyFormatter(key);
      keyInColourMap = colour_map.exists(key);
      //only for the last key? Assumes all keys have the same colour?
      if(keyInColourMap) colour = colour_map.at(key);
    }
    if (clique->parent()) {
      parent += " : ";
      s << parentnum << "->" << num << "\n";
    }
    first = true;
    for (auto parentKey : clique->conditional_->parents()) {
      if (!first) parent += ", ";
      first = false;
      parent += keyFormatter(parentKey);
    }
    //  parent += "\"];\n";
    if(keyInColourMap) {
        parent += "\",color=" + colour;
        parent += "];\n";
    }
    else {
        parent += "\"];\n";
    }
    s << parent;
    parentnum = num;
    for (auto c : clique->children) {
      num++;
      dotBayesTree(s, c, keyFormatter, colour_map, parentnum);
    }
}
drawBlockJacobians()
cv::Mat dyno::factor_graph_tools::drawBlockJacobians (gtsam::GaussianFactorGraph::shared_ptr gaussian_fg, const gtsam::Ordering & ordering, const DrawBlockJacobiansOptions & options)
Definition at line 141 of file FactorGraphTools.cc.
{
    const gtsam::JacobianFactor jacobian_factor(*gaussian_fg, ordering);
    const gtsam::Matrix J = jacobian_factor.jacobian().first;
    //each cv::mat will be the drawing of a column block (associated with one variable) in the jacobian
    //Each block will have dimensions determiend by dim of the variable (determiend by the key)
    //and number of rows of the full jacobian matrix, J
    std::vector<std::pair<gtsam::Key, cv::Mat>> column_blocks;
    for(gtsam::Key key : ordering) {
        //this will have rows = J.rows(), cols = dimension of the variable
        const gtsam::VerticalBlockMatrix::constBlock Ablock = jacobian_factor.getA(jacobian_factor.find(key));
        const int var_dimensions = Ablock.cols();
        CHECK_EQ(Ablock.rows(), J.rows());
        //drawn image of each vertical block
        cv::Mat b_img(cv::Size(var_dimensions, Ablock.rows()), CV_8UC3, cv::viz::Color::white());
        for (int i = 0; i < Ablock.rows(); ++i) {
            for (int j = 0; j < var_dimensions; ++j) {
                //only draw if non zero
                if (std::fabs(Ablock(i, j)) > 1e-15) {
                    const auto colour = options.colour_selector(key);
                    b_img.at<cv::Vec3b>(i, j) =  cv::Vec3b(colour[0], colour[1], colour[2]);
                }
            }
        }
        column_blocks.push_back(std::make_pair(key, b_img));
    }
    CHECK(!options.desired_size.empty()); //cannot be empty
    const cv::Size& desired_size = options.desired_size;
    const int current_cols = J.cols();
    const int desired_cols = desired_size.width;
    const int desired_rows = desired_size.height;
    //define a ratio which which to scale each block (viz) individually
    //since we're going to add things like spacing we want to scale
    //up each block so its visible but dont want to scale up the line spacing etc.
    //the ratio ensures we get close to the final desired size of the TOTAL image
    double ratio;
    //want positive ratio
    if(current_cols < desired_cols) {
        ratio = (double)desired_cols/(double)current_cols;
    }
    else {
        ratio = (double)current_cols/(double)desired_cols;
    }
    auto scale_and_draw_label = [&options, &ratio, &desired_rows](cv::Mat& current_block, gtsam::Key key) {
        //we all each jacobiab horizintally so only need to scale the columns
        const int scaled_cols = ratio * (int)current_block.cols;
        //scale current block to the desired size with INTER_NEAREST - this keeps the pixels looking clear and visible
        cv::resize(current_block, current_block, cv::Size(scaled_cols, desired_rows), 0, 0, cv::INTER_NEAREST);
        if(options.draw_label) {
            //draw text info
            cv::Mat text_box(cv::Size(current_block.cols, options.text_box_height), CV_8UC3, cv::viz::Color::white());
            constexpr static double kFontScale = 0.5;
            constexpr static int kFontFace = cv::FONT_HERSHEY_DUPLEX;
            constexpr static int kThickness = 1;
            //draw text mid way in box
            cv::putText(text_box, options.label_formatter(key), cv::Point(2, text_box.rows/2), kFontFace, kFontScale, cv::viz::Color::black(), kThickness);
            //add text box ontop of jacobian block
            cv::vconcat(text_box, current_block, current_block);
        }
    }; //end scale_and_drawinternal::_label
    if(column_blocks.size() == 1) {
        gtsam::Key key = column_blocks.at(0).first;
        cv::Mat current_block = column_blocks.at(0).second;
        scale_and_draw_label(current_block, key);
        return current_block;
    }
    //the final drawn image
    cv::Mat concat_column_blocks;
    for(size_t i = 1; i < column_blocks.size(); i++) {
        gtsam::Key key = column_blocks.at(i).first;
        cv::Mat current_block = column_blocks.at(i).second;
        scale_and_draw_label(current_block, key);
        if(i == 1) {
            cv::Mat first_block = column_blocks.at(0).second;
            gtsam::Key key_0 = column_blocks.at(0).first;
            scale_and_draw_label(first_block, key_0);
            const cv::Mat vert_line(cv::Size(2, first_block.rows), CV_8UC3, cv::viz::Color::black());
            //concat first block with vertical loine
            cv::hconcat(first_block, vert_line, first_block);
            //concat current jacobian block with other blocks
            cv::hconcat(first_block, current_block, concat_column_blocks);
        }
        else {
            //concat current jacobian block with other blocks
            cv::hconcat(concat_column_blocks, current_block, concat_column_blocks);
        }
        //if not last, add vertical line
        if(i < column_blocks.size() - 1) {
            //concat blocks with vertial line
            const cv::Mat vert_line(cv::Size(2, concat_column_blocks.rows), CV_8UC3, cv::viz::Color::black());
            cv::hconcat(concat_column_blocks, vert_line, concat_column_blocks);
        }
    }
    return concat_column_blocks;
}
References dyno::factor_graph_tools::DrawBlockJacobiansOptions::colour_selector, dyno::factor_graph_tools::DrawBlockJacobiansOptions::desired_size, dyno::factor_graph_tools::DrawBlockJacobiansOptions::draw_label, dyno::factor_graph_tools::DrawBlockJacobiansOptions::label_formatter, and dyno::factor_graph_tools::DrawBlockJacobiansOptions::text_box_height.
Referenced by dyno::FactorGraphManager< GRAPH >::drawBlockJacobian().
getAssociatedFactors() [1/3]
template<typename GRAPH > size_t dyno::factor_graph_tools::getAssociatedFactors (gtsam::FactorIndices & associated_factors, const GRAPH & graph, gtsam::Key query_key)
Definition at line 115 of file FactorGraphTools.hpp.
{
    associated_factors.clear();
    std::vector<typename GRAPH::const_iterator> associated_factor_iters;
    size_t result = getAssociatedFactors(associated_factor_iters, graph, query_key);
    for(const typename GRAPH::const_iterator& iter : associated_factor_iters) {
        //index in graph
        associated_factors.push_back(std::distance(graph.begin(), iter));
    }
    return result;
}
References getAssociatedFactors().
getAssociatedFactors() [2/3]
template<typename GRAPH > size_t dyno::factor_graph_tools::getAssociatedFactors (std::vector< typename GRAPH::const_iterator > & associated_factors, const GRAPH & graph, gtsam::Key query_key)
Definition at line 102 of file FactorGraphTools.hpp.
{
    associated_factors.clear();
    for(auto it = graph.begin(); it != graph.end(); it++) {
        auto factor = *it;
        if(factor->find(query_key) != factor->end()) {
            associated_factors.push_back(it);
        }
    }
    return associated_factors.size();
}
Referenced by getAssociatedFactors(), and dyno::FactorGraphManager< GRAPH >::getAssociatedFactors().
getAssociatedFactors() [3/3]
template<typename GRAPH > size_t dyno::factor_graph_tools::getAssociatedFactors (std::vector< typename GRAPH::sharedFactor > & associated_factors, const GRAPH & graph, gtsam::Key query_key)
Definition at line 128 of file FactorGraphTools.hpp.
{
    associated_factors.clear();
    std::vector<typename GRAPH::const_iterator> associated_factor_iters;
    size_t result = getAssociatedFactors(associated_factor_iters, graph, query_key);
    for(const typename GRAPH::const_iterator& iter : associated_factor_iters) {
        associated_factors.push_back(*iter);
    }
    return result;
}
References getAssociatedFactors().
saveBayesTree()
template<class CLIQUE > void dyno::factor_graph_tools::saveBayesTree (const gtsam::BayesTree< CLIQUE > & tree, const std::string & filename, const gtsam::KeyFormatter & keyFormatter, const gtsam::FastMap< gtsam::Key, std::string > colour_map = {})
Definition at line 347 of file FactorGraphTools.hpp.
                                                                                                                                {})
{
  std::ofstream of(filename.c_str());
  if (tree.roots().empty())
      throw std::invalid_argument(
          "the root of Bayes tree has not been initialized!");
    of << "digraph G{\n";
    for (const auto& root : tree.roots()) dotBayesTree(of, root, keyFormatter, colour_map);
    of << "}";
    std::flush(of);
}
seralizeFactorToGraphFileFormat()
template<typename T > std::ostream & dyno::factor_graph_tools::seralizeFactorToGraphFileFormat (std::ostream & os, const T & t, const std::string & tag)
Definition at line 414 of file FactorGraphTools.hpp.
{
    static_assert(is_gtsam_factor_v<T>);
    //TAG <keys> VALUE
    //where the value is provided by toGraphFileFormat and should be in the form <measurement> <covaraince>
    os << tag << " ";
    const gtsam::Factor& factor = static_cast<const gtsam::Factor&>(t);
    for(const gtsam::Key key : factor) {
        os << key << " ";
    }
    toGraphFileFormat<T>(os, t);
    os << '\n';
    return os;
}
seralizeValueToGraphFileFormat()
template<typename T > std::ostream & dyno::factor_graph_tools::seralizeValueToGraphFileFormat (std::ostream & os, const T & t, gtsam::Key key, const std::string & tag)
Definition at line 431 of file FactorGraphTools.hpp.
{
    os << tag << " " << key << " ";
    //TAG <key> VALUE
    //where the value is provided by toGraphFileFormat and should be the value itself
    toGraphFileFormat<T>(os, t);
    os << '\n';
    return os;
}
toGraphFileFormat()
template<typename T > void dyno::factor_graph_tools::toGraphFileFormat (std::ostream & os, const T & t)
Referenced by toGraphFileFormat< gtsam::BetweenFactor< gtsam::Pose3 > >(), toGraphFileFormat< gtsam::PoseToPointFactor< gtsam::Pose3, Landmark > >(), toGraphFileFormat< gtsam::PriorFactor< gtsam::Pose3 > >(), and toGraphFileFormat< LandmarkMotionTernaryFactor >().
toGraphFileFormat< gtsam::BetweenFactor< gtsam::Pose3 > >()
template<> void dyno::factor_graph_tools::toGraphFileFormat< gtsam::BetweenFactor< gtsam::Pose3 > > (std::ostream & os, const gtsam::BetweenFactor< gtsam::Pose3 > & t)
Definition at line 281 of file FactorGraphTools.cc.
{
    const gtsam::Pose3 measurement = t.measured();
    toGraphFileFormat(os, measurement);
    auto gaussianModel = boost::dynamic_pointer_cast<gtsam::noiseModel::Gaussian>(t.noiseModel());
    gtsam::Matrix Info = gaussianModel->information();
    saveMatrixAsUpperTriangular(os, Info);
}
References dyno::saveMatrixAsUpperTriangular(), and toGraphFileFormat().
toGraphFileFormat< gtsam::Point3 >()
template<> void dyno::factor_graph_tools::toGraphFileFormat< gtsam::Point3 > (std::ostream & os, const gtsam::Point3 & t)
Definition at line 258 of file FactorGraphTools.cc.
{
    os << t.x() << " " << t.y() << " " << t.z();
}
toGraphFileFormat< gtsam::Pose3 >()
template<> void dyno::factor_graph_tools::toGraphFileFormat< gtsam::Pose3 > (std::ostream & os, const gtsam::Pose3 & t)
Definition at line 263 of file FactorGraphTools.cc.
{
    const gtsam::Point3 p = t.translation();
    const auto q = t.rotation().toQuaternion();
    os << p.x() << " " << p.y() << " " << p.z() << " " << q.x() << " " << q.y() << " " << q.z() << " " << q.w();
}
toGraphFileFormat< gtsam::PoseToPointFactor< gtsam::Pose3, Landmark > >()
template<> void dyno::factor_graph_tools::toGraphFileFormat< gtsam::PoseToPointFactor< gtsam::Pose3, Landmark > > (std::ostream & os, const gtsam::PoseToPointFactor< gtsam::Pose3, Landmark > & t)
Definition at line 301 of file FactorGraphTools.cc.
{
    const gtsam::Point3 measurement = t.measured();
    toGraphFileFormat(os, measurement);
    auto gaussianModel = boost::dynamic_pointer_cast<gtsam::noiseModel::Gaussian>(t.noiseModel());
    gtsam::Matrix Info = gaussianModel->information();
    saveMatrixAsUpperTriangular(os, Info);
}
References dyno::saveMatrixAsUpperTriangular(), and toGraphFileFormat().
toGraphFileFormat< gtsam::PriorFactor< gtsam::Pose3 > >()
template<> void dyno::factor_graph_tools::toGraphFileFormat< gtsam::PriorFactor< gtsam::Pose3 > > (std::ostream & os, const gtsam::PriorFactor< gtsam::Pose3 > & t)
Definition at line 271 of file FactorGraphTools.cc.
{
    const gtsam::Pose3 measurement = t.prior();
    toGraphFileFormat(os, measurement);
    auto gaussianModel = boost::dynamic_pointer_cast<gtsam::noiseModel::Gaussian>(t.noiseModel());
    gtsam::Matrix Info = gaussianModel->information();
    saveMatrixAsUpperTriangular(os, Info);
}
References dyno::saveMatrixAsUpperTriangular(), and toGraphFileFormat().
toGraphFileFormat< LandmarkMotionTernaryFactor >()
template<> void dyno::factor_graph_tools::toGraphFileFormat< LandmarkMotionTernaryFactor > (std::ostream & os, const LandmarkMotionTernaryFactor & t)
Definition at line 291 of file FactorGraphTools.cc.
{
    const gtsam::Point3 measurement(0, 0, 0);
    toGraphFileFormat(os, measurement);
    auto gaussianModel = boost::dynamic_pointer_cast<gtsam::noiseModel::Gaussian>(t.noiseModel());
    gtsam::Matrix Info = gaussianModel->information();
    saveMatrixAsUpperTriangular(os, Info);
}
References dyno::saveMatrixAsUpperTriangular(), and toGraphFileFormat().