DynoSAM: dyno::byte_track Namespace Reference
dyno::byte_track Namespace Reference
Classes
class ByteTracker
struct ByteTrackerParams
class Detection
class DetectionBase
class KalmanFilter
class RectBase
class TlwhRect
class Track
Enumerations
enum class TrackState { Tracked = 0 , Lost = 1 }
Functions
int lapjv_internal (const size_t n, const std::vector< float > &cost, std::vector< int > &x, std::vector< int > &y)
float calc_iou (const RectBase &A, const RectBase &B)
Enumeration Type Documentation
TrackState
enum class dyno::byte_track::TrackState strong
Enumerator
Tracked
Lost
Definition at line 38 of file Track.hpp.
                      {
  Tracked = 0,
  Lost = 1,
};
Function Documentation
calc_iou()
float dyno::byte_track::calc_iou (const RectBase & A, const RectBase & B)
Definition at line 31 of file Rect.cc.
{
  const float iw = std::min(A.left() + A.width(), B.left() + B.width()) -
                   std::max(A.left(), B.left());
  float iou = 0;
  if (iw > 0) {
    const float ih = std::min(A.top() + A.height(), B.top() + B.height()) -
                     std::max(A.top(), B.top());
    if (ih > 0) {
      const float ua =
          A.width() * A.height() + B.width() * B.height() - iw * ih;
      iou = iw * ih / ua;
    }
  }
  return iou;
}
References dyno::byte_track::RectBase::height(), dyno::byte_track::RectBase::left(), dyno::byte_track::RectBase::top(), and dyno::byte_track::RectBase::width().
Referenced by dyno::byte_track::ByteTracker::linear_assignment(), and dyno::byte_track::ByteTracker::remove_duplicate_tracks().
lapjv_internal()
int dyno::byte_track::lapjv_internal (const size_t n, const std::vector< float > & cost, std::vector< int > & x, std::vector< int > & y)
Solve dense sparse LAP.
Definition at line 303 of file Lapjv.cc.
{
  int ret;
  std::vector<int> free_rows(n);
  std::vector<double> v(n);
  ret = _ccrrt_dense(n, cost, free_rows, x, y, v);
  int i = 0;
  while (ret > 0 && i < 2) {
    ret = _carr_dense(n, cost, ret, free_rows, x, y, v);
    i++;
  }
  if (ret > 0) {
    ret = _ca_dense(n, cost, ret, free_rows, x, y, v);
  }
  return ret;
}
Referenced by dyno::byte_track::ByteTracker::exec_lapjv().