DynoSAM: dyno::utils Namespace Reference
dyno::utils Namespace Reference
Classes
class Accumulator
class DummyStatsCollector
struct Measure
class Statistics
struct StatisticsMapValue
class StatsCollectorImpl
class Timer
class TimingStatsCollector
struct TRErrorPair
Translation-Rotation error pair.
struct TRErrorPairVector
Typedefs
typedef Accumulator< double, double, kInfiniteWindowSize > Accumulatord
typedef StatsCollectorImpl StatsCollector
Functions
void throwExceptionIfPathInvalid (const std::string &image_path)
void loadRGB (const std::string &image_path, cv::Mat &img)
void loadFlow (const std::string &image_path, cv::Mat &img)
void loadDepth (const std::string &image_path, cv::Mat &img)
void loadSemanticMask (const std::string &image_path, const cv::Size &size, cv::Mat &mask)
void loadMask (const std::string &image_path, cv::Mat &mask)
std::vector< std::filesystem::path > getAllFilesInDir (const std::string &folder_path)
Returns a ORDERED vector of all files in the given directory. (jesse) is this the file name or the absolute file path?
void loadPathsInDirectory (std::vector< std::string > &file_paths, const std::string &folder_path, const std::function< bool(const std::string &)> &condition=std::function< bool(const std::string &)>())
bool getLine (std::ifstream &fstream, std::vector< std::string > &split_lines)
Gets the next line from the input ifstream and returns it as split string (using white space as the delimieter). Any newline/carriage return/trailing white space values are trimmed.
std::vector< std::string > trimAndSplit (const std::string &input, const std::string &delimiter=" ")
Takes an input string and splits it using white space (" ") as the delimiter. Trims any newline/carriage return/trailing white space values.
template<typename T >
bool equateGtsamOptionalValues (const std::optional< T > &a, const std::optional< T > &b, double tol=1e-8)
Check if two objects wrapped in std::optional are equal. If both are std::nullopt, function will return true.
template<typename T >
bool equateGtsamSharedValues (const GtsamSharedPtr< T > &a, const GtsamSharedPtr< T > &b, double tol=1e-8)
gtsam::Pose3 cvMatToGtsamPose3 (const cv::Mat &H)
gtsam::Pose3 cvMatsToGtsamPose3 (const cv::Mat &R, const cv::Mat &T)
cv::Mat gtsamPose3ToCvMat (const gtsam::Pose3 &pose)
gtsam::Rot3 cvMatToGtsamRot3 (const cv::Mat &R)
gtsam::Point3 cvMatToGtsamPoint3 (const cv::Mat &cv_t)
cv::Mat gtsamPoint3ToCvMat (const gtsam::Point3 &point)
gtsam::Pose3 poseVectorToGtsamPose3 (const std::vector< double > &vector_pose)
Converts a vector of 16 elements listing the elements of a 4x4 3D pose matrix by rows into a pose3 in gtsam.
gtsam::Cal3_S2 Cvmat2Cal3_S2 (const cv::Mat &M)
Converts a 3x3 (or 3xM, M > 3) camera matrix from opencv to gtsam::Cal3_S2.
std::pair< cv::Mat, cv::Mat > Pose2cvmats (const gtsam::Pose3 &pose)
Converts a gtsam pose3 to a 3x3 rotation matrix and translation vector in opencv format (note: the function only extracts R and t, without changing them)
cv::Mat gtsamMatrix3ToCvMat (const gtsam::Matrix3 &rot)
cv::Mat gtsamVector3ToCvMat (const gtsam::Vector3 &tran)
cv::Point3d gtsamVector3ToCvPoint3 (const gtsam::Vector3 &tran)
template<typename T >
T perturbWithUniformNoise (const T &t, double lower, double upper)
template<typename T >
T perturbWithNoise (const T &t, const gtsam::Vector &sigmas, int32_t seed=42)
Perturbs a gtsam::Value type object via sampling a normal distribution using the sigmas provided. The length of the sigmas must match the dimension of the value as given by gtsam::traits<T>::dimension.
template<typename T >
T perturbWithNoise (const T &t, double sigma, int32_t seed=42)
template<typename T >
T createRandomAroundIdentity (double sigma, int32_t seed=52)
template<typename T = double>
gtsam::Point2 cvPointToGtsam (const cv::Point_< T > &point)
gtsam::Point2 cvKeypointToGtsam (const cv::KeyPoint &point)
template<typename T = float>
gtsam::Point2Vector cvPointsToGtsam (const std::vector< cv::Point_< T > > &points)
template<typename T = float>
cv::Point_< T > gtsamPointToCv (const gtsam::Point2 &point)
cv::KeyPoint gtsamPointToKeyPoint (const gtsam::Point2 &point, float size=1, float angle=-1, float response=0, int octave=0, int class_id=-1)
template<typename T = float, typename Allocator >
std::vector< cv::Point_< T > > gtsamPointsToCv (const std::vector< gtsam::Point2, Allocator > &points)
gtsam::Pose3 openGvTfToGtsamPose3 (const opengv::transformation_t &RT)
template<class T >
static bool getEstimateOfKey (const gtsam::Values &state, const gtsam::Key &key, T *estimate)
bool saveNoiseModelAsUpperTriangular (std::ostream &os, const gtsam::noiseModel::Gaussian &noise_model)
bool opencvCudaAvailable (std::string *message=nullptr)
double calculateIoU (const cv::Rect &a, const cv::Rect &b)
bool cvSizeEqual (const cv::Size &a, const cv::Size &b)
bool cvSizeEqual (const cv::Mat &a, const cv::Mat &b)
template<typename T >
bool matContains (const cv::Mat &mat, const cv::Point_< T > &point)
Returns true of the point is inside bounds of the cv::Mat.
void drawCircleInPlace (cv::Mat &img, const cv::Point2d &point, const cv::Scalar &colour, const int radius=1, const int thickness=2)
std::string cvTypeToString (int type)
std::string cvTypeToString (const cv::Mat &mat)
bool compareCvMatsUpToTol (const cv::Mat &mat1, const cv::Mat &mat2, const double &tol=1e-7)
cv::Mat concatenateImagesHorizontally (const cv::Mat &left_img, const cv::Mat &right_img)
cv::Mat concatenateImagesVertically (const cv::Mat &top_img, const cv::Mat &bottom_img)
void flowToRgb (const cv::Mat &flow, cv::Mat &rgb)
void labelMaskToRGB (const cv::Mat &mask, const cv::Mat &rgb_input, cv::Mat &output, float alpha=0.7, int background_label=0)
Given an image that operates like a mask (ie. is a single channel image where each pixel value correspondes to a label of some type) draws the mask over an input image.
cv::Mat labelMaskToRGB (const cv::Mat &mask, int background_label, const cv::Mat &rgb)
Given an image that operates like a mask (ie. is a single channel image where each pixel value correspondes to a label of some type) draws the mask over an input image.
cv::Mat labelMaskToRGB (const cv::Mat &mask, int background_label)
Same as labelMaskToRGB(mask, background label) but instead draws the mask over a black image so only the mask values are shown.
void getDisparityVis (cv::InputArray src, cv::OutputArray dst, int unknown_disparity=16320)
Allows visualization of disparity image (which is usually outputed as CV_16S or CV_32F from stereo depth reconstruction).
void drawLabeledBoundingBox (cv::Mat &image, const std::string &label, const cv::Scalar &colour, const cv::Rect &bounding_box, const int &bb_thickness=2)
Draws a coloured bounding box and associated label onto a RGB image.
void drawObjectPoseAxes (cv::Mat &image, const cv::Mat &K, const cv::Mat &D, const std::vector< gtsam::Pose3 > &poses_c, float scale=0.2)
Projects SE(3) poses onto the image as an RGB axes. Input poses are expected to be in the camera (local) frame.
cv::Mat readOpticalFlow (const std::string &path)
The function readOpticalFlow loads a flow field from a file and returns it as a single matrix. Resulting Mat has a type CV_32FC2 - floating-point, 2-channel. First channel corresponds to the flow in the horizontal direction (u), second - vertical (v).
bool writeOpticalFlow (const std::string &path, const cv::Mat &flow)
The function stores a flow field in a file, returns true on success, false otherwise. The flow field must be a 2-channel, floating-point matrix (CV_32FC2). First channel corresponds to the flow in the horizontal direction (u), second - vertical (v).
Timestamp fromRosTime (const rclcpp::Time &time)
Convert ROS time to timestamp.
rclcpp::Time toRosTime (Timestamp timestamp)
Converts Timestamp (in seconds) to ROS time.
template<typename INPUT , typename OUTPUT , typename = std::enable_if_t< rosidl_generator_traits::is_message<OUTPUT>::value>>
bool convertWithHeader (const INPUT &input, OUTPUT &output, Timestamp timestamp, const std::string &frame_id, std::optional< std::string > child_frame_id=std::nullopt)
Converts from input type to output type where output type is a ROS message with a header. OUTPUT type MUST be a ROS message type.
Variables
static constexpr int kInfiniteWindowSize = std::numeric_limits<int>::max()
const double kNumSecondsPerNanosecond = 1.e-9
const float FLOW_TAG_FLOAT = 202021.25f
const char * FLOW_TAG_STRING = "PIEH"
Typedef Documentation
Accumulatord
typedef Accumulator<double, double, kInfiniteWindowSize> dyno::utils::Accumulatord
Definition at line 243 of file Accumulator.hpp.
StatsCollector
typedef StatsCollectorImpl dyno::utils::StatsCollector
Definition at line 305 of file Statistics.hpp.
Function Documentation
calculateIoU()
double dyno::utils::calculateIoU (const cv::Rect & a, const cv::Rect & b)
Definition at line 87 of file OpenCVUtils.cc.
{
  cv::Rect intersection = a & b;
  double intersection_area = intersection.area();
  // Calculate union area
  double union_area = a.area() + b.area() - intersection_area;
  // Handle case where unionArea is zero (e.g., no overlap and one or both rects
  // have zero area)
  if (union_area == 0) {
    return 0.0;
  }
  // Calculate IoU
  return intersection_area / union_area;
}
compareCvMatsUpToTol()
bool dyno::utils::compareCvMatsUpToTol (const cv::Mat & mat1, const cv::Mat & mat2, const double & tol = 1e-7)
Definition at line 439 of file OpenCVUtils.cc.
{
  CHECK_EQ(mat1.size(), mat2.size());
  CHECK_EQ(mat1.type(), mat2.type());
  // treat two empty mat as identical as well
  if (mat1.empty() && mat2.empty()) {
    LOG(WARNING) << "CvMatCmp: asked comparison of 2 empty matrices.";
    return true;
  }
  // Compare the two matrices!
  cv::Mat diff = mat1 - mat2;
  return cv::checkRange(diff, true, nullptr, -tol, tol);
}
Referenced by dyno::CameraParams::equals().
concatenateImagesHorizontally()
cv::Mat dyno::utils::concatenateImagesHorizontally (const cv::Mat & left_img, const cv::Mat & right_img)
Definition at line 158 of file OpenCVUtils.cc.
{
  cv::Mat left_img_tmp = left_img.clone();
  if (left_img_tmp.channels() == 1) {
    cv::cvtColor(left_img_tmp, left_img_tmp, cv::COLOR_GRAY2BGR);
  }
  cv::Mat right_img_tmp = right_img.clone();
  if (right_img_tmp.channels() == 1) {
    cv::cvtColor(right_img_tmp, right_img_tmp, cv::COLOR_GRAY2BGR);
  }
  cv::Size left_img_size = left_img_tmp.size();
  cv::Size right_img_size = right_img_tmp.size();
  CHECK_EQ(left_img_size.height, left_img_size.height)
      << "Cannot concat horizontally if images are not the same "
         "height";
  cv::Mat dual_img(left_img_size.height,
                   left_img_size.width + right_img_size.width, CV_8UC3);
  cv::Mat left(dual_img,
               cv::Rect(0, 0, left_img_size.width, left_img_size.height));
  left_img_tmp.copyTo(left);
  cv::Mat right(dual_img, cv::Rect(left_img_size.width, 0, right_img_size.width,
                                   right_img_size.height));
  right_img_tmp.copyTo(right);
  return dual_img;
}
concatenateImagesVertically()
cv::Mat dyno::utils::concatenateImagesVertically (const cv::Mat & top_img, const cv::Mat & bottom_img)
Definition at line 190 of file OpenCVUtils.cc.
{
  cv::Mat top_img_tmp = top_img.clone();
  if (top_img_tmp.channels() == 1) {
    cv::cvtColor(top_img_tmp, top_img_tmp, cv::COLOR_GRAY2BGR);
  }
  cv::Mat bottom_img_tmp = bottom_img.clone();
  if (bottom_img_tmp.channels() == 1) {
    cv::cvtColor(bottom_img_tmp, bottom_img_tmp, cv::COLOR_GRAY2BGR);
  }
  cv::Size top_img_size = bottom_img_tmp.size();
  cv::Size bottom_img_size = bottom_img_tmp.size();
  CHECK_EQ(top_img_size.width, bottom_img_size.width)
      << "Cannot concat vertically if images are not the same width";
  cv::Mat dual_img(top_img_size.height + bottom_img_size.height,
                   top_img_size.width, CV_8UC3);
  cv::Mat top(dual_img,
              cv::Rect(0, 0, top_img_size.width, top_img_size.height));
  top_img_tmp.copyTo(top);
  cv::Mat bottom(dual_img,
                 cv::Rect(0, top_img_size.height, bottom_img_size.width,
                          bottom_img_size.height));
  bottom_img_tmp.copyTo(bottom);
  return dual_img;
}
convertWithHeader()
template<typename INPUT , typename OUTPUT , typename = std::enable_if_t< rosidl_generator_traits::is_message<OUTPUT>::value>> bool dyno::utils::convertWithHeader (const INPUT & input, OUTPUT & output, Timestamp timestamp, const std::string & frame_id, std::optional< std::string > child_frame_id = std::nullopt)
Converts from input type to output type where output type is a ROS message with a header. OUTPUT type MUST be a ROS message type.
Checks if the OUTPUT type has a variable called header and then sets the timestamp and frame id Checks if the OUTPUT type has a variable called child_frame_id and, if child_frame_id provided, sets the value
Definition at line 423 of file RosUtils.hpp.
{
  if (!dyno::convert<INPUT, OUTPUT>(input, output)) return false;
  // does actually have a header
  if constexpr (internal::HasMsgHeader<OUTPUT>::value) {
    output.header.stamp = toRosTime(timestamp);
    output.header.frame_id = frame_id;
  }
  // if has child frame id
  if constexpr (internal::HasChildFrame<OUTPUT>::value) {
    if (child_frame_id) {
      output.child_frame_id = child_frame_id.value();
    }
  }
  return true;
}
References toRosTime().
Referenced by dyno::DSDTransport::constructObjectOdometry(), dyno::FrontendInbuiltDisplayRos::publishGroundTruthInfo(), dyno::DisplayCommon::publishOdometry(), dyno::DisplayCommon::publishOdometryPath(), and dyno::FrontendDSDRos::tryPublishGroundTruth().
createRandomAroundIdentity()
template<typename T > T dyno::utils::createRandomAroundIdentity (double sigma, int32_t seed = 52)
Definition at line 243 of file GtsamUtils.hpp.
{
  T t = gtsam::traits<T>::Identity();
  return perturbWithNoise(t, sigma, seed);
}
References perturbWithNoise().
cvKeypointToGtsam()
gtsam::Point2 dyno::utils::cvKeypointToGtsam (const cv::KeyPoint & point) inline
Definition at line 254 of file GtsamUtils.hpp.
{
  return gtsam::Point2(static_cast<double>(point.pt.x),
                       static_cast<double>(point.pt.y));
}
Cvmat2Cal3_S2()
gtsam::Cal3_S2 dyno::utils::Cvmat2Cal3_S2 (const cv::Mat & M)
Converts a 3x3 (or 3xM, M > 3) camera matrix from opencv to gtsam::Cal3_S2.
Parameters
M
Returns
gtsam::Cal3_S2
Definition at line 106 of file GtsamUtils.cc.
{
  CHECK_EQ(M.rows, 3);  // We expect homogeneous camera matrix.
  CHECK_GE(M.cols, 3);  // We accept extra columns (which we do not use).
  const double& fx = M.at<double>(0, 0);
  const double& fy = M.at<double>(1, 1);
  const double& s = M.at<double>(0, 1);
  const double& u0 = M.at<double>(0, 2);
  const double& v0 = M.at<double>(1, 2);
  return gtsam::Cal3_S2(fx, fy, s, u0, v0);
}
Referenced by dyno::StereoCamera::StereoCamera().
cvMatsToGtsamPose3()
gtsam::Pose3 dyno::utils::cvMatsToGtsamPose3 (const cv::Mat & R, const cv::Mat & T)
Definition at line 62 of file GtsamUtils.cc.
{
  return gtsam::Pose3(cvMatToGtsamRot3(R), cvMatToGtsamPoint3(T));
}
References cvMatToGtsamPoint3(), and cvMatToGtsamRot3().
Referenced by cvMatToGtsamPose3().
cvMatToGtsamPoint3()
gtsam::Point3 dyno::utils::cvMatToGtsamPoint3 (const cv::Mat & cv_t)
Definition at line 81 of file GtsamUtils.cc.
{
  CHECK_EQ(cv_t.rows, 3);
  CHECK_EQ(cv_t.cols, 1);
  gtsam::Point3 gtsam_t;
  gtsam_t << cv_t.at<double>(0, 0), cv_t.at<double>(1, 0),
      cv_t.at<double>(2, 0);
  return gtsam_t;
}
Referenced by cvMatsToGtsamPose3().
cvMatToGtsamPose3()
gtsam::Pose3 dyno::utils::cvMatToGtsamPose3 (const cv::Mat & H)
Definition at line 42 of file GtsamUtils.cc.
{
  CHECK_EQ(H.rows, 4);
  CHECK_EQ(H.cols, 4);
  cv::Mat R(3, 3, H.type());
  cv::Mat T(3, 1, H.type());
  for (int i = 0; i < 3; i++) {
    for (int j = 0; j < 3; j++) {
      R.at<double>(i, j) = H.at<double>(i, j);
    }
  }
  for (int i = 0; i < 3; i++) {
    T.at<double>(i, 0) = H.at<double>(i, 3);
  }
  return cvMatsToGtsamPose3(R, T);
}
References cvMatsToGtsamPose3(), and dyno::H().
Referenced by dyno::KittiObjectPoseFolder::constructObjectPoseGT(), dyno::OMDOldAllLoader::loadAll(), and dyno::KittiCameraPoseFolder::onPathInit().
cvMatToGtsamRot3()
gtsam::Rot3 dyno::utils::cvMatToGtsamRot3 (const cv::Mat & R)
Definition at line 73 of file GtsamUtils.cc.
{
  CHECK_EQ(R.rows, 3);
  CHECK_EQ(R.cols, 3);
  gtsam::Matrix rot_mat = gtsam::Matrix::Identity(3, 3);
  cv::cv2eigen(R, rot_mat);
  return gtsam::Rot3(rot_mat);
}
Referenced by cvMatsToGtsamPose3().
cvPointsToGtsam()
template<typename T = float> gtsam::Point2Vector dyno::utils::cvPointsToGtsam (const std::vector< cv::Point_< T > > & points)
Definition at line 260 of file GtsamUtils.hpp.
{
  gtsam::Point2Vector gtsam_points;
  for (const auto& p : points) {
    gtsam_points.push_back(cvPointToGtsam<T>(p));
  }
  return gtsam_points;
}
Referenced by dyno::UndistorterRectifier::UndistortRectifyKeypoints().
cvPointToGtsam()
template<typename T = double> gtsam::Point2 dyno::utils::cvPointToGtsam (const cv::Point_< T > & point) inline
Definition at line 249 of file GtsamUtils.hpp.
{
  return gtsam::Point2(static_cast<double>(point.x),
                       static_cast<double>(point.y));
}
Referenced by dyno::FeatureTrackerBase::isWithinShrunkenImage().
cvSizeEqual() [1/2]
bool dyno::utils::cvSizeEqual (const cv::Mat & a, const cv::Mat & b)
Definition at line 108 of file OpenCVUtils.cc.
{
  return cvSizeEqual(a.size(), b.size());
}
References cvSizeEqual().
cvSizeEqual() [2/2]
bool dyno::utils::cvSizeEqual (const cv::Size & a, const cv::Size & b)
Definition at line 104 of file OpenCVUtils.cc.
{
  return a.height == b.height && a.width == b.width;
}
Referenced by cvSizeEqual(), labelMaskToRGB(), and dyno::Frame::projectToDenseCloud().
cvTypeToString() [1/2]
std::string dyno::utils::cvTypeToString (const cv::Mat & mat)
Definition at line 154 of file OpenCVUtils.cc.
{
  return cvTypeToString(mat.type());
}
References cvTypeToString().
cvTypeToString() [2/2]
std::string dyno::utils::cvTypeToString (int type)
Definition at line 119 of file OpenCVUtils.cc.
{
  std::string r;
  uchar depth = type & CV_MAT_DEPTH_MASK;
  uchar chans = 1 + (type >> CV_CN_SHIFT);
  switch (depth) {
    case CV_8U:
      r = "8U";
      break;
    case CV_8S:
      r = "8S";
      break;
    case CV_16U:
      r = "16U";
      break;
    case CV_16S:
      r = "16S";
      break;
    case CV_32S:
      r = "32S";
      break;
    case CV_32F:
      r = "32F";
      break;
    case CV_64F:
      r = "64F";
      break;
    default:
      r = "User";
      break;
  }
  r += "C";
  r += (chans + '0');
  return r;
}
Referenced by dyno::CameraParams::convertKMatrixToIntrinsicsCoeffs(), cvTypeToString(), dyno::validateMask(), dyno::validateRGBMono(), dyno::validateSingleImage(), and dyno::VirtualKittiFlowDataFolder::vKittiPngToFlow().
drawCircleInPlace()
void dyno::utils::drawCircleInPlace (cv::Mat & img, const cv::Point2d & point, const cv::Scalar & colour, const int radius = 1, const int thickness = 2)
Definition at line 112 of file OpenCVUtils.cc.
{
  if (!matContains(img, point)) return;
  cv::circle(img, point, radius, colour, thickness);
}
References matContains().
Referenced by dyno::ParallelHybridBackendModule::nominalSpinImpl().
drawLabeledBoundingBox()
void dyno::utils::drawLabeledBoundingBox (cv::Mat & image, const std::string & label, const cv::Scalar & colour, const cv::Rect & bounding_box, const int & bb_thickness = 2)
Draws a coloured bounding box and associated label onto a RGB image.
Used to draw object bounding boxes and their labels.
Parameters
image cv::Mat& rgb image to modify
label const std::string& label to draw in the top-right corner of the bounding box
colour const cv::Scalar& colour to draw the bounding box with
bounding_box const cv::Rect& bounding box to draw.
bb_thickness const int& Line thickness for the boundong box
Definition at line 320 of file OpenCVUtils.cc.
{
  constexpr static double kFontScale = 0.6;
  constexpr static int kFontFace = cv::FONT_HERSHEY_SIMPLEX;
  // text thickness
  constexpr static int kThickness = 1;
  // Top left corner.
  const cv::Point& tlc = bounding_box.tl();
  // Display the label at the top of the bounding box.
  int base_line;
  cv::Size label_size =
      cv::getTextSize(label, kFontFace, kFontScale, kThickness, &base_line);
  // draw on filled black rectangle that the object label will then be drawn
  // over to make it easier to see
  constexpr static int pixel_buffer = 2;  // pixel buffer around the rectangle
  const cv::Point tlc_black_rectangle(tlc.x,
                                      tlc.y - label_size.height - pixel_buffer);
  const cv::Point brc_black_rectangle(tlc.x + label_size.width + pixel_buffer,
                                      tlc.y);
  cv::rectangle(image, tlc_black_rectangle, brc_black_rectangle,
                cv::Scalar(0, 0, 0), -1);
  // Put the label on the black rectangle.
  // Note: text origin starts from the bottom left corner of the text string in
  // the image and we add a pixel buffer along y to make it look better
  cv::putText(image, label, cv::Point(tlc.x, tlc.y - 2), kFontFace, kFontScale,
              cv::Scalar(255, 255, 255), kThickness);
  // draw bounding box with line thickness
  cv::rectangle(image, bounding_box, colour, bb_thickness);
}
Referenced by dyno::FeatureTrackerBase::computeImageTracks(), and dyno::ObjectPoseGT::drawBoundingBox().
drawObjectPoseAxes()
void dyno::utils::drawObjectPoseAxes (cv::Mat & image, const cv::Mat & K, const cv::Mat & D, const std::vector< gtsam::Pose3 > & poses_c, float scale = 0.2)
Projects SE(3) poses onto the image as an RGB axes. Input poses are expected to be in the camera (local) frame.
Parameters
image cv::Mat&
K const cv::Mat& 3x3 calibration matrix
D const cv::Mat& distortion coeeffs
poses_c const std::vector<gtsam::Pose3>& Poses in the camera (local) frame to be projected
scale float The size of the axis in 2D after projection (default: 0.2)
Definition at line 355 of file OpenCVUtils.cc.
{
  cv::Mat K_float, D_float;
  K.copyTo(K_float);
  D.copyTo(D_float);
  K_float.convertTo(K_float, CV_32F);
  D_float.convertTo(D_float, CV_32F);
  // Define the 3D points for the axis (origin and points along X, Y, Z)
  static const std::vector<cv::Point3f> axis_points = {
      {0, 0, 0},      // Origin
      {scale, 0, 0},  // X-axis (red)
      {0, scale, 0},  // Y-axis (green)
      {0, 0, scale}   // Z-axis (blue)
  };
  for (const gtsam::Pose3& pose : poses_c) {
    auto [rot_matrix, tvec] = Pose2cvmats(pose);
    rot_matrix.convertTo(rot_matrix, CV_32F);
    tvec.convertTo(tvec, CV_32F);
    cv::Mat rvec;
    cv::Rodrigues(rot_matrix,
                  rvec);  // Convert rotation matrix to Rodrigues vector
    std::vector<cv::Point2f> image_points;
    cv::projectPoints(axis_points, rvec, tvec, K_float, D_float, image_points);
    // Draw axes on the image
    cv::line(image, image_points[0], image_points[1], cv::Scalar(0, 0, 255),
             2);  // X-axis in red
    cv::line(image, image_points[0], image_points[2], cv::Scalar(0, 255, 0),
             2);  // Y-axis in green
    cv::line(image, image_points[0], image_points[3], cv::Scalar(255, 0, 0),
             2);  // Z-axis in blue
  }
}
References Pose2cvmats().
equateGtsamOptionalValues()
template<typename T > bool dyno::utils::equateGtsamOptionalValues (const std::optional< T > & a, const std::optional< T > & b, double tol = 1e-8)
Check if two objects wrapped in std::optional are equal. If both are std::nullopt, function will return true.
T MUST be a gtsam::Value type (ie. have gtsam::traits<T>::Equals) defined
Template Parameters
T a gtsam::Value concept type
Parameters
a const std::optional<T>&
b const std::optional<T>&
Returns
true
false
Definition at line 139 of file GtsamUtils.hpp.
{
  return ::equateGtsamPointerLikeValues<std::optional<T>, T>(a, b, tol);
}
Referenced by dyno::Feature::impl::operator==(), and dyno::ObjectPoseGT::operator==().
equateGtsamSharedValues()
template<typename T > bool dyno::utils::equateGtsamSharedValues (const GtsamSharedPtr< T > & a, const GtsamSharedPtr< T > & b, double tol = 1e-8)
Definition at line 145 of file GtsamUtils.hpp.
{
  return ::equateGtsamPointerLikeValues<GtsamSharedPtr<T>, T>(a, b, tol);
}
Referenced by dyno::MeasurementWithCovariance< T, D >::equals().
flowToRgb()
void dyno::utils::flowToRgb (const cv::Mat & flow, cv::Mat & rgb)
Definition at line 222 of file OpenCVUtils.cc.
{
  CHECK(flow.channels() == 2) << "Expecting flow in frame to have 2 channels";
  // Visualization part
  cv::Mat flow_parts[2];
  cv::split(flow, flow_parts);
  // Convert the algorithm's output into Polar coordinates
  cv::Mat magnitude, angle, magn_norm;
  cv::cartToPolar(flow_parts[0], flow_parts[1], magnitude, angle, true);
  cv::normalize(magnitude, magn_norm, 0.0f, 1.0f, cv::NORM_MINMAX);
  angle *= ((1.f / 360.f) * (180.f / 255.f));
  // Build hsv image
  cv::Mat _hsv[3], hsv, hsv8, bgr;
  _hsv[0] = angle;
  _hsv[1] = cv::Mat::ones(angle.size(), CV_32F);
  _hsv[2] = magn_norm;
  cv::merge(_hsv, 3, hsv);
  hsv.convertTo(hsv8, CV_8U, 255.0);
  // Display the results
  cv::cvtColor(hsv8, rgb, cv::COLOR_HSV2BGR);
}
Referenced by dyno::ImageType::OpticalFlow::toRGB().
fromRosTime()
Timestamp dyno::utils::fromRosTime (const rclcpp::Time & time)
Convert ROS time to timestamp.
Parameters
time
Returns
Timestamp time in seconds
Definition at line 296 of file RosUtils.cc.
{
  Timestamp timestamp;
  convert(time, timestamp);
  return timestamp;
}
References dyno::convert().
Referenced by dyno::OnlineDataProviderRos::connectImages().
getAllFilesInDir()
std::vector< std::filesystem::path > dyno::utils::getAllFilesInDir (const std::string & folder_path)
Returns a ORDERED vector of all files in the given directory. (jesse) is this the file name or the absolute file path?
Parameters
folder_path
Returns
std::vector<std::filesystem::path>
Definition at line 74 of file FileSystem.cc.
{
  std::vector<std::filesystem::path> files_in_directory;
  std::copy(std::filesystem::directory_iterator(folder_path),
            std::filesystem::directory_iterator(),
            std::back_inserter(files_in_directory));
  std::sort(files_in_directory.begin(), files_in_directory.end());
  return files_in_directory;
}
Referenced by dyno::ClusterSlamAllLoader::loadFlowImagesAndSize(), dyno::ProjectAriaAllLoader::loadFlowImagesAndSize(), dyno::TartanAirShibuyaAllLoader::loadFlowImagesAndSize(), dyno::ViodeAllLoader::loadFlowImagesAndSize(), dyno::ClusterSlamAllLoader::loadImages(), dyno::TartanAirShibuyaAllLoader::loadImages(), dyno::ViodeAllLoader::loadImages(), dyno::ClusterSlamAllLoader::loadInstanceMasksImages(), dyno::ClusterSlamAllLoader::loadLeftLandmarks(), dyno::ProjectAriaAllLoader::loadOtherImages(), loadPathsInDirectory(), dyno::ClusterSlamAllLoader::setGroundTruthPacket(), and dyno::ViodeAllLoader::syncFilePathsWithGroundTruth().
getDisparityVis()
void dyno::utils::getDisparityVis (cv::InputArray src, cv::OutputArray dst, int unknown_disparity = 16320)
Allows visualization of disparity image (which is usually outputed as CV_16S or CV_32F from stereo depth reconstruction).
Parameters
src cv::InputArray
dst cv::OutputArray
unknown_disparity
Definition at line 300 of file OpenCVUtils.cc.
{
  CHECK(!src.empty() && (src.depth() == CV_16S || src.depth() == CV_32F) &&
        (src.channels() == 1));
  // cv::Mat srcMat = src.getMat();
  cv::Mat srcMat = src.getMat();
  dst.create(srcMat.rows, srcMat.cols, CV_8UC1);
  cv::Mat& dstMat = dst.getMatRef();
  // Check its extreme values.
  double min_val;
  double max_val;
  cv::minMaxLoc(src, &min_val, &max_val);
  // Multiply by 1.25 just to saturate a bit the extremums.
  double scale = 2.0 * 255.0 / (max_val - min_val);
  srcMat.convertTo(dstMat, CV_8UC1, scale / 16.0);
  dstMat &= (srcMat != unknown_disparity);
}
Referenced by dyno::StereoMatcher::disparityRectifiedReconstruction().
getEstimateOfKey()
template<class T > static bool dyno::utils::getEstimateOfKey (const gtsam::Values & state, const gtsam::Key & key, T * estimate) static
Definition at line 295 of file GtsamUtils.hpp.
{
  if (state.exists(key)) {
    *CHECK_NOTNULL(estimate) = state.at<T>(key);
    return true;
  } else {
    return false;
  }
}
getLine()
bool dyno::utils::getLine (std::ifstream & fstream, std::vector< std::string > & split_lines)
Gets the next line from the input ifstream and returns it as split string (using white space as the delimieter). Any newline/carriage return/trailing white space values are trimmed.
Parameters
fstream std::ifstream&
split_lines std::vector<std::string>&
Returns
true
false
Definition at line 113 of file FileSystem.cc.
{
  std::string line;
  getline(fstream, line);
  split_lines.clear();
  if (line.empty()) return false;
  split_lines = trimAndSplit(line);
  return true;
}
References trimAndSplit().
Referenced by dyno::VirtualKittiTextGtLoader::loadBBoxMetaData(), dyno::VirtualKittiTextGtLoader::loadCameraPoses(), dyno::ClusterSlamAllLoader::loadLandMarkMapping(), dyno::ClusterSlamAllLoader::loadLeftLandmarks(), dyno::VirtualKittiTextGtLoader::loadPoseTxt(), and dyno::ClusterSlamAllLoader::processPoseFile().
gtsamMatrix3ToCvMat()
cv::Mat dyno::utils::gtsamMatrix3ToCvMat (const gtsam::Matrix3 & rot)
Definition at line 130 of file GtsamUtils.cc.
{
  cv::Mat R = cv::Mat(3, 3, CV_64F);
  cv::eigen2cv(rot, R);
  return R;
}
Referenced by Pose2cvmats(), and dyno::FeatureTrackerBase::predictKeypointsGivenRotation().
gtsamPoint3ToCvMat()
cv::Mat dyno::utils::gtsamPoint3ToCvMat (const gtsam::Point3 & point)
Definition at line 90 of file GtsamUtils.cc.
{
  cv::Mat T(3, 1, CV_32F);
  cv::eigen2cv(point, T);
  T.convertTo(T, CV_32F);
  return T.clone();
}
gtsamPointsToCv()
template<typename T = float, typename Allocator > std::vector< cv::Point_< T > > dyno::utils::gtsamPointsToCv (const std::vector< gtsam::Point2, Allocator > & points)
Definition at line 282 of file GtsamUtils.hpp.
{
  std::vector<cv::Point_<T>> cv_points;
  for (const auto& p : points) {
    cv_points.push_back(gtsamPointToCv<T>(p));
  }
  return cv_points;
}
Referenced by dyno::UndistorterRectifier::UndistortRectifyKeypoints().
gtsamPointToCv()
template<typename T = float> cv::Point_< T > dyno::utils::gtsamPointToCv (const gtsam::Point2 & point) inline
Definition at line 269 of file GtsamUtils.hpp.
{
  return cv::Point_<T>(static_cast<T>(point(0)), static_cast<T>(point(1)));
}
Referenced by dyno::ClusterSlamAllLoader::associateDetectedBBWithObject(), dyno::FeatureTrackerBase::computeImageTracks(), dyno::FeatureTrackerBase::drawStereoMatches(), and dyno::ParallelHybridBackendModule::nominalSpinImpl().
gtsamPointToKeyPoint()
cv::KeyPoint dyno::utils::gtsamPointToKeyPoint (const gtsam::Point2 & point, float size = 1, float angle = -1, float response = 0, int octave = 0, int class_id = -1) inline
Definition at line 273 of file GtsamUtils.hpp.
{
  return cv::KeyPoint(gtsamPointToCv<float>(point), size, angle, response,
                      octave, class_id);
}
gtsamPose3ToCvMat()
cv::Mat dyno::utils::gtsamPose3ToCvMat (const gtsam::Pose3 & pose)
Definition at line 66 of file GtsamUtils.cc.
{
  cv::Mat RT(4, 4, CV_64F);
  cv::eigen2cv(pose.matrix(), RT);
  RT.convertTo(RT, CV_64F);
  return RT;
}
gtsamVector3ToCvMat()
cv::Mat dyno::utils::gtsamVector3ToCvMat (const gtsam::Vector3 & tran)
Definition at line 136 of file GtsamUtils.cc.
{
  cv::Mat T = cv::Mat(3, 1, CV_64F);
  cv::eigen2cv(tran, T);
  return T;
}
Referenced by Pose2cvmats().
gtsamVector3ToCvPoint3()
cv::Point3d dyno::utils::gtsamVector3ToCvPoint3 (const gtsam::Vector3 & tran)
Definition at line 142 of file GtsamUtils.cc.
{
  return cv::Point3d(tran[0], tran[1], tran[2]);
}
labelMaskToRGB() [1/3]
void dyno::utils::labelMaskToRGB (const cv::Mat & mask, const cv::Mat & rgb_input, cv::Mat & output, float alpha = 0.7, int background_label = 0)
Given an image that operates like a mask (ie. is a single channel image where each pixel value correspondes to a label of some type) draws the mask over an input image.
The value at each pixel (labels) are treated like object labels which are used to generate a unique colour for the mask. The background label is used to indicate which pixel value should be ignored - this could be the background or simply unknown pixel values.
Alpha is used to blend with mask ontop of the rgb image.
Parameters
mask const cv::Mat&
rgb_input const cv::Mat&
output cv::Mat&
alpha float default value is 0.7
background_label int default value is 0
Definition at line 247 of file OpenCVUtils.cc.
{
  CHECK_EQ(mask.channels(), 1u) << "Expecting mask input to have channels 1";
  CHECK_EQ(rgb_input.channels(), 3) << "Expecting rgb input to have channels 3";
  CHECK(cvSizeEqual(mask, rgb_input));
  rgb_input.copyTo(output);
  FunctionalParallelOpenCVMat process(output, [&](cv::Mat& viz, int i, int j) {
    const ObjectId* mask_ptr = mask.ptr<ObjectId>(i);
    const ObjectId object_label = mask_ptr[j];
    if (object_label != background_label) {
      cv::Scalar color = Color::uniqueId(object_label).bgra();
      cv::Vec3b* viz_row = viz.ptr<cv::Vec3b>(i);
      // blend colour with existing values in viz_row size we have already
      // copied the rgb input values into the output (referenced as viz)
      for (int c = 0; c < 3; ++c) {
        viz_row[j][c] = static_cast<uchar>(alpha * color[c] +
                                           (1.0 - alpha) * viz_row[j][c]);
      }
    }
  });
  process.run();
}
References dyno::background_label, dyno::Color::bgra(), cvSizeEqual(), dyno::ParallelOpenCVMat< T >::run(), and dyno::Color::uniqueId().
Referenced by dyno::ObjectDetectionResult::colouredMask(), dyno::FeatureTrackerBase::computeImageTracks(), labelMaskToRGB(), main(), PYBIND11_MODULE(), dyno::ImageType::ClassSegmentation::toRGB(), dyno::ImageType::MotionMask::toRGB(), and dyno::ImageType::SemanticMask::toRGB().
labelMaskToRGB() [2/3]
cv::Mat dyno::utils::labelMaskToRGB (const cv::Mat & mask, int background_label)
Same as labelMaskToRGB(mask, background label) but instead draws the mask over a black image so only the mask values are shown.
Parameters
mask
background_label
Returns
cv::Mat
Definition at line 295 of file OpenCVUtils.cc.
{
  cv::Mat rgb = cv::Mat::zeros(mask.size(), CV_8UC3);
  return labelMaskToRGB(mask, background_label, rgb);
}
References dyno::background_label, and labelMaskToRGB().
labelMaskToRGB() [3/3]
cv::Mat dyno::utils::labelMaskToRGB (const cv::Mat & mask, int background_label, const cv::Mat & rgb)
Given an image that operates like a mask (ie. is a single channel image where each pixel value correspondes to a label of some type) draws the mask over an input image.
The value at each pixel (labels) are treated like object labels which are used to generate a unique colour for the mask. The background label is used to indicate which pixel value should be ignored - this could be the background or simply unknown pixel values
Parameters
mask
background_label
rgb
Returns
cv::Mat
Definition at line 274 of file OpenCVUtils.cc.
{
  cv::Mat output;
  labelMaskToRGB(mask, rgb, output, 0.7, background_label);
  // for (int i = 0; i < mask.rows; i++) {
  //   for (int j = 0; j < mask.cols; j++) {
  //     // background is zero
  //     if (mask.at<int>(i, j) != background_label) {
  //       cv::Scalar color = Color::uniqueId(mask.at<int>(i, j));
  //       // rgb or bgr?
  //       mask_viz.at<cv::Vec3b>(i, j)[0] = color[0];
  //       mask_viz.at<cv::Vec3b>(i, j)[1] = color[1];
  //       mask_viz.at<cv::Vec3b>(i, j)[2] = color[2];
  //     }
  //   }
  // }
  return output;
}
References dyno::background_label, and labelMaskToRGB().
loadDepth()
void dyno::utils::loadDepth (const std::string & image_path, cv::Mat & img)
Definition at line 29 of file FileSystem.cc.
{
  throwExceptionIfPathInvalid(image_path);
  img = cv::imread(image_path, cv::IMREAD_UNCHANGED);
  img.convertTo(img, CV_64F);
}
References throwExceptionIfPathInvalid().
Referenced by dyno::OMDOldAllLoader::getDepthImage(), dyno::ProjectAriaAllLoader::getDepthImage(), dyno::TartanAirShibuyaAllLoader::getDepthImage(), and dyno::DepthDataFolder::getItem().
loadFlow()
void dyno::utils::loadFlow (const std::string & image_path, cv::Mat & img)
Definition at line 24 of file FileSystem.cc.
{
  throwExceptionIfPathInvalid(image_path);
  img = readOpticalFlow(image_path);
}
References readOpticalFlow(), and throwExceptionIfPathInvalid().
Referenced by dyno::OpticalFlowDataFolder::getItem(), dyno::ClusterSlamAllLoader::getOpticalFlow(), dyno::OMDOldAllLoader::getOpticalFlow(), dyno::ProjectAriaAllLoader::getOpticalFlow(), dyno::TartanAirShibuyaAllLoader::getOpticalFlow(), and dyno::ViodeAllLoader::getOpticalFlow().
loadMask()
void dyno::utils::loadMask (const std::string & image_path, cv::Mat & mask)
Definition at line 68 of file FileSystem.cc.
{
  throwExceptionIfPathInvalid(image_path);
  mask = cv::imread(image_path, cv::IMREAD_UNCHANGED);
  mask.convertTo(mask, CV_32SC1);
}
References throwExceptionIfPathInvalid().
Referenced by dyno::ClusterSlamAllLoader::getInstanceMask(), dyno::ProjectAriaAllLoader::getInstanceMask(), dyno::TartanAirShibuyaAllLoader::getInstanceMask(), and dyno::ViodeAllLoader::getInstanceMask().
loadPathsInDirectory()
void dyno::utils::loadPathsInDirectory (std::vector< std::string > & file_paths, const std::string & folder_path, const std::function< bool(const std::string &)> & condition = std::function<bool(const std::string&)>())
Definition at line 84 of file FileSystem.cc.
{
  std::function<bool(const std::string&)> impl_condition;
  if (condition) {
    impl_condition = condition;
  } else {
    // if no condition is provided, set condition to always return true; adding
    // all the files found
    impl_condition = [](const std::string&) -> bool { return true; };
  }
  auto files_in_directory = getAllFilesInDir(folder_path);
  for (const std::string file_path : files_in_directory) {
    throwExceptionIfPathInvalid(file_path);
    // if condition is true, add
    if (impl_condition(file_path)) file_paths.push_back(file_path);
  }
}
References getAllFilesInDir(), and throwExceptionIfPathInvalid().
Referenced by dyno::OMDOldAllLoader::loadAll().
loadRGB()
void dyno::utils::loadRGB (const std::string & image_path, cv::Mat & img)
Definition at line 19 of file FileSystem.cc.
{
  throwExceptionIfPathInvalid(image_path);
  img = cv::imread(image_path, cv::IMREAD_UNCHANGED);
}
References throwExceptionIfPathInvalid().
Referenced by dyno::RGBDataFolder::getItem(), dyno::VirtualKittiRGBDataFolder::getItem(), dyno::VirtualKittiDepthDataFolder::getItem(), dyno::ClusterSlamAllLoader::getRGB(), dyno::OMDOldAllLoader::getRGB(), dyno::ProjectAriaAllLoader::getRGB(), dyno::TartanAirShibuyaAllLoader::getRGB(), dyno::ViodeAllLoader::getRGB(), dyno::ClusterSlamAllLoader::getRightRGB(), dyno::ProjectAriaAllLoader::getRightRGB(), dyno::ViodeAllLoader::getRightRGB(), and dyno::VirtualKittiFlowDataFolder::vKittiPngToFlow().
loadSemanticMask()
void dyno::utils::loadSemanticMask (const std::string & image_path, const cv::Size & size, cv::Mat & mask)
Definition at line 35 of file FileSystem.cc.
{
  throwExceptionIfPathInvalid(image_path);
  CHECK(!size.empty());
  mask = cv::Mat(size, CV_32SC1);
  std::ifstream file_mask;
  file_mask.open(image_path.c_str());
  int count = 0;
  while (!file_mask.eof()) {
    std::string s;
    getline(file_mask, s);
    if (!s.empty()) {
      std::stringstream ss;
      ss << s;
      int tmp;
      for (int i = 0; i < mask.cols; ++i) {
        ss >> tmp;
        if (tmp != 0) {
          mask.at<int>(count, i) = tmp;
        } else {
          mask.at<int>(count, i) = 0;
        }
      }
      count++;
    }
  }
  file_mask.close();
}
References throwExceptionIfPathInvalid().
Referenced by dyno::OMDOldAllLoader::getInstanceMask(), and dyno::SegMaskFolder::getItem().
matContains()
template<typename T > bool dyno::utils::matContains (const cv::Mat & mat, const cv::Point_< T > & point) inline
Returns true of the point is inside bounds of the cv::Mat.
Template Parameters
T Point template to work with any cv::Point type
Parameters
mat const cv::Mat&
point const cv::Point_<T>&
Returns
true
false
Definition at line 123 of file OpenCVUtils.hpp.
{
  const auto x = static_cast<int>(point.x);
  const auto y = static_cast<int>(point.y);
  return x >= 0 && y >= 0 && x < mat.cols && y < mat.rows;
}
Referenced by drawCircleInPlace().
opencvCudaAvailable()
bool dyno::utils::opencvCudaAvailable (std::string * message = nullptr)
Definition at line 65 of file OpenCVUtils.cc.
{
  if constexpr (isOpencvCudaEnabled()) {
    if (cv::cuda::getCudaEnabledDeviceCount() > 0) {
      if (message)
        *message = "OpenCV CUDA support found. Devices available: " +
                   std::to_string(cv::cuda::getCudaEnabledDeviceCount());
      return true;
    } else {
      if (message)
        *message =
            "OpenCV CUDA support found but No CUDA support or no CUDA devices";
      return false;
    }
  } else {
    if (message)
      *message =
          "OPENCV CUDA not detected from OpenCV itself. Check it has been "
          "compiled correctly!";
    return false;
  }
}
References isOpencvCudaEnabled().
Referenced by dyno::DynoPipelineManager::DynoPipelineManager(), and dyno::FunctionalDetector::FactoryCreate().
openGvTfToGtsamPose3()
gtsam::Pose3 dyno::utils::openGvTfToGtsamPose3 (const opengv::transformation_t & RT)
Definition at line 117 of file GtsamUtils.cc.
{
  gtsam::Matrix poseMat = gtsam::Matrix::Identity(4, 4);
  poseMat.block<3, 4>(0, 0) = RT;
  return gtsam::Pose3(poseMat);
}
Referenced by dyno::runRansac().
perturbWithNoise() [1/2]
template<typename T > T dyno::utils::perturbWithNoise (const T & t, const gtsam::Vector & sigmas, int32_t seed = 42)
Perturbs a gtsam::Value type object via sampling a normal distribution using the sigmas provided. The length of the sigmas must match the dimension of the value as given by gtsam::traits<T>::dimension.
Template Parameters
T
Parameters
t
sigmas
seed
Returns
T
Make static so that the generator (internal to the sampler) remains in memory during calls and that we actually get a random distribution
Definition at line 222 of file GtsamUtils.hpp.
{
  CHECK_EQ(gtsam::traits<T>::dimension, sigmas.size());
  // TODO: (jesse)yeah, but we pass different sigmas and seeds to it, so wont
  // this mean it just doesnt get updated?
  // gtsam::Sampler sample(sigmas, seed);
  static std::mt19937_64 rng(std::random_device{}());
  gtsam::Vector delta = gtsam::Sampler::sampleDiagonal(
      sigmas, &rng);  // delta should be the tangent vector
  return gtsam::traits<T>::Retract(t, delta);
}
Referenced by createRandomAroundIdentity().
perturbWithNoise() [2/2]
template<typename T > T dyno::utils::perturbWithNoise (const T & t, double sigma, int32_t seed = 42)
Definition at line 236 of file GtsamUtils.hpp.
{
  gtsam::Vector sigmas =
      gtsam::Vector::Constant(gtsam::traits<T>::dimension, sigma);
  return perturbWithNoise<T>(t, sigmas, seed);
}
perturbWithUniformNoise()
template<typename T > T dyno::utils::perturbWithUniformNoise (const T & t, double lower, double upper)
Definition at line 196 of file GtsamUtils.hpp.
{
  static std::random_device rd;
  static std::mt19937 gen(rd());
  std::uniform_real_distribution<double> dist(lower, upper);
  constexpr size_t N = gtsam::traits<T>::dimension;
  Eigen::Matrix<double, N, 1> delta;
  for (int i = 0; i < N; ++i) {
    delta[i] = dist(gen);
  }
  return gtsam::traits<T>::Retract(t, delta);
}
References dyno::gen(), and dyno::rd.
Pose2cvmats()
std::pair< cv::Mat, cv::Mat > dyno::utils::Pose2cvmats (const gtsam::Pose3 & pose)
Converts a gtsam pose3 to a 3x3 rotation matrix and translation vector in opencv format (note: the function only extracts R and t, without changing them)
Parameters
pose const gtsam::Pose3&
Returns
std::pair<cv::Mat, cv::Mat>
Definition at line 123 of file GtsamUtils.cc.
{
  const gtsam::Matrix3& rot = pose.rotation().matrix();
  const gtsam::Vector3& tran = pose.translation();
  return std::make_pair(gtsamMatrix3ToCvMat(rot), gtsamVector3ToCvMat(tran));
}
References gtsamMatrix3ToCvMat(), and gtsamVector3ToCvMat().
Referenced by dyno::StereoCamera::computeRectificationParameters(), and drawObjectPoseAxes().
poseVectorToGtsamPose3()
gtsam::Pose3 dyno::utils::poseVectorToGtsamPose3 (const std::vector< double > & vector_pose)
Converts a vector of 16 elements listing the elements of a 4x4 3D pose matrix by rows into a pose3 in gtsam.
Definition at line 97 of file GtsamUtils.cc.
{
  CHECK_EQ(vector_pose.size(), 16u);
  CHECK_EQ(vector_pose[12], 0.0);
  CHECK_EQ(vector_pose[13], 0.0);
  CHECK_EQ(vector_pose[14], 0.0);
  CHECK_EQ(vector_pose[15], 1.0);
  return gtsam::Pose3(Eigen::Matrix4d(vector_pose.data()).transpose());
}
Referenced by dyno::declare_config().
readOpticalFlow()
cv::Mat dyno::utils::readOpticalFlow (const std::string & path)
The function readOpticalFlow loads a flow field from a file and returns it as a single matrix. Resulting Mat has a type CV_32FC2 - floating-point, 2-channel. First channel corresponds to the flow in the horizontal direction (u), second - vertical (v).
I have absolutely no idea why but OpenCV seemds to have removed support for the read/write optical flow functions in 4.x I have taken this implementation from OpenCV 3.4 (https://github.com/opencv/opencv_contrib/blob/3.4/modules/optflow/src/optical_flow_io.cpp)
Parameters
path
Returns
cv::Mat
Definition at line 458 of file OpenCVUtils.cc.
{
  using namespace cv;
  Mat_<Point2f> flow;
  std::ifstream file(path.c_str(), std::ios_base::binary);
  if (!file.good()) return flow;  // no file - return empty matrix
  float tag;
  file.read((char*)&tag, sizeof(float));
  if (tag != FLOW_TAG_FLOAT) return flow;
  int width, height;
  file.read((char*)&width, 4);
  file.read((char*)&height, 4);
  flow.create(height, width);
  for (int i = 0; i < flow.rows; ++i) {
    for (int j = 0; j < flow.cols; ++j) {
      Point2f u;
      file.read((char*)&u.x, sizeof(float));
      file.read((char*)&u.y, sizeof(float));
      if (!file.good()) {
        flow.release();
        return flow;
      }
      flow(i, j) = u;
    }
  }
  file.close();
  return flow;
}
References FLOW_TAG_FLOAT.
Referenced by loadFlow().
saveNoiseModelAsUpperTriangular()
bool dyno::utils::saveNoiseModelAsUpperTriangular (std::ostream & os, const gtsam::noiseModel::Gaussian & noise_model) inline
Definition at line 305 of file GtsamUtils.hpp.
{
  const gtsam::Matrix info = noise_model.information();
  return saveMatrixAsUpperTriangular(os, info);
}
References dyno::saveMatrixAsUpperTriangular().
throwExceptionIfPathInvalid()
void dyno::utils::throwExceptionIfPathInvalid (const std::string & image_path)
Definition at line 12 of file FileSystem.cc.
{
  namespace fs = std::filesystem;
  if (!fs::exists(image_path)) {
    throw std::runtime_error("Path does not exist: " + image_path);
  }
}
Referenced by dyno::ClusterSlamAllLoader::ClusterSlamAllLoader(), dyno::KittiClassSegmentationDataFolder::getItem(), dyno::VirtualKittiRGBDataFolder::getItem(), dyno::VirtualKittiFlowDataFolder::getItem(), dyno::VirtualKittiDepthDataFolder::getItem(), dyno::VirtualKittiGenericInstanceSegFolder::getItem(), dyno::VirtualKittiClassSegmentationDataFolder::getItem(), dyno::getModelDirectory(), dyno::ModelConfig::getResouce(), dyno::OMDOldAllLoader::loadAll(), loadDepth(), loadFlow(), dyno::ClusterSlamAllLoader::loadFlowImagesAndSize(), dyno::ProjectAriaAllLoader::loadFlowImagesAndSize(), dyno::TartanAirShibuyaAllLoader::loadFlowImagesAndSize(), dyno::ViodeAllLoader::loadFlowImagesAndSize(), dyno::ClusterSlamAllLoader::loadImages(), dyno::TartanAirShibuyaAllLoader::loadImages(), dyno::ViodeAllLoader::loadImages(), dyno::ClusterSlamAllLoader::loadInstanceMasksImages(), loadMask(), dyno::loadPathsInDirectory(), loadPathsInDirectory(), loadRGB(), loadSemanticMask(), dyno::ProjectAriaAllLoader::ProjectAriaAllLoader(), dyno::DynoNode::searchForPathWithParams(), dyno::ViodeAllLoader::syncFilePathsWithGroundTruth(), dyno::TartanAirShibuyaAllLoader::TartanAirShibuyaAllLoader(), dyno::VirtualKittiDataLoader::VirtualKittiDataLoader(), dyno::VirtualKittiTextGtLoader::VirtualKittiTextGtLoader(), and dyno::YamlParser::YamlParser().
toRosTime()
rclcpp::Time dyno::utils::toRosTime (Timestamp timestamp)
Converts Timestamp (in seconds) to ROS time.
Parameters
timestamp
Returns
rclcpp::Time
Definition at line 302 of file RosUtils.cc.
{
  rclcpp::Time time;
  convert(timestamp, time);
  return time;
}
References dyno::convert().
Referenced by dyno::InbuiltDisplayCommon::constructBoundingBoxeMarkers(), dyno::DSDTransport::constructMultiObjectOdometryPaths(), convertWithHeader(), dyno::InbuiltDisplayCommon::createAxisMarkers(), dyno::InbuiltDisplayCommon::createCameraMarker(), dyno::DynoPipelineManagerRos::initalisePipeline(), dyno::DisplayCommon::objectBBXToRvizMarker(), dyno::FrontendInbuiltDisplayRos::publishGroundTruthInfo(), dyno::InbuiltDisplayCommon::publishObjectPaths(), dyno::InbuiltDisplayCommon::publishObjectPositions(), dyno::DSDTransport::Publisher::publishObjectTransforms(), dyno::DisplayCommon::publishOdometryPath(), dyno::DSDRos::publishVisualOdometry(), dyno::FrontendDSDRos::tryPublishGroundTruth(), and dyno::FrontendDSDRos::tryPublishPointClouds().
trimAndSplit()
std::vector< std::string > dyno::utils::trimAndSplit (const std::string & input, const std::string & delimiter = " ")
Takes an input string and splits it using white space (" ") as the delimiter. Trims any newline/carriage return/trailing white space values.
Parameters
input const std::string&
Returns
std::vector<std::string>
Definition at line 105 of file FileSystem.cc.
{
  std::string trim_input = boost::algorithm::trim_right_copy(input);
  std::vector<std::string> split_line;
  boost::algorithm::split(split_line, trim_input, boost::is_any_of(delimiter));
  return split_line;
}
Referenced by getLine().
writeOpticalFlow()
bool dyno::utils::writeOpticalFlow (const std::string & path, const cv::Mat & flow)
The function stores a flow field in a file, returns true on success, false otherwise. The flow field must be a 2-channel, floating-point matrix (CV_32FC2). First channel corresponds to the flow in the horizontal direction (u), second - vertical (v).
Parameters
path
flow
Returns
true
false
Definition at line 493 of file OpenCVUtils.cc.
{
  using namespace cv;
  const int nChannels = 2;
  Mat input = flow;
  if (input.channels() != nChannels || input.depth() != CV_32F ||
      path.length() == 0)
    return false;
  std::ofstream file(path.c_str(), std::ofstream::binary);
  if (!file.good()) return false;
  int nRows, nCols;
  nRows = (int)input.size().height;
  nCols = (int)input.size().width;
  const int headerSize = 12;
  char header[headerSize];
  memcpy(header, FLOW_TAG_STRING, 4);
  // size of ints is known - has been asserted in the current function
  memcpy(header + 4, reinterpret_cast<const char*>(&nCols), sizeof(nCols));
  memcpy(header + 8, reinterpret_cast<const char*>(&nRows), sizeof(nRows));
  file.write(header, headerSize);
  if (!file.good()) return false;
  //    if ( input.isContinuous() ) //matrix is continous - treat it as a single
  //    row
  //    {
  //        nCols *= nRows;
  //        nRows = 1;
  //    }
  int row;
  char* p;
  for (row = 0; row < nRows; row++) {
    p = input.ptr<char>(row);
    file.write(p, nCols * nChannels * sizeof(float));
    if (!file.good()) return false;
  }
  file.close();
  return true;
}
References FLOW_TAG_STRING.
Variable Documentation
FLOW_TAG_FLOAT
const float dyno::utils::FLOW_TAG_FLOAT = 202021.25f
Definition at line 455 of file OpenCVUtils.cc.
Referenced by readOpticalFlow().
FLOW_TAG_STRING
const char* dyno::utils::FLOW_TAG_STRING = "PIEH"
Definition at line 456 of file OpenCVUtils.cc.
Referenced by writeOpticalFlow().
kInfiniteWindowSize
constexpr int dyno::utils::kInfiniteWindowSize = std::numeric_limits<int>::max() static constexpr
Definition at line 74 of file Accumulator.hpp.
Referenced by dyno::utils::Accumulator< SampleType, SumType, WindowSize >::Accumulator(), and dyno::utils::Accumulator< SampleType, SumType, WindowSize >::RollingMean().
kNumSecondsPerNanosecond
const double dyno::utils::kNumSecondsPerNanosecond = 1.e-9
Definition at line 88 of file Statistics.hpp.
Referenced by dyno::utils::StatisticsMapValue::AddValue().