DynoSAM: dyno::vision_tools Namespace Reference
dyno::vision_tools Namespace Reference
Classes
struct ObjectBoundaryMaskResult
Functions
void getCorrespondences (FeaturePairs &correspondences, const FeatureFilterIterator &previous_features, const FeatureFilterIterator &current_features)
ObjectIds getObjectLabels (const cv::Mat &image)
Finds the unique object labels (j) as present in the instance segmentation image. Does not include the background label.
void shrinkMask (const cv::Mat &mask, cv::Mat &shrunk_mask, int erosion_size)
Shrinks all found object masks by a given ammount.
bool findObjectBoundingBox (const cv::Mat &mask, ObjectId object_id, cv::Rect &detected_rect, std::vector< std::vector< cv::Point > > &detected_contours)
From a instance/semantic mask type img, construct the bounding box for the mask of object_id.
bool findObjectBoundingBox (const cv::Mat &mask, ObjectId object_id, cv::Rect &detected_rect)
From a instance/semantic mask type img, construct the bounding box for the mask of object_id.
bool findObjectBoundingBox (const cv::Mat &mask, ObjectId object_id, std::vector< std::vector< cv::Point > > &detected_contours)
From a instance/semantic mask type img, construct the bounding box for the mask of object_id.
void computeObjectMaskBoundaryMask (ObjectBoundaryMaskResult &result, const cv::Mat &mask, int thickness, bool use_as_feature_detection_mask=true)
From an input instance/semantic mask type img construct a image mask (binary) that has True values around each object in the image, with a certain thickness.
void computeObjectMaskBoundaryMask (ObjectBoundaryMaskResult &result, const ObjectDetectionResult &detection_result, int thickness, bool use_as_feature_detection_mask=true)
Same as computeObjectMaskBoundaryMask but we construct the result from the pre-computed object mask and list of detected object labels. This saves a lot of compute and uses the detection result directly.
void relabelMasks (const cv::Mat &mask, cv::Mat &relabelled_mask, const ObjectIds &old_labels, const ObjectIds &new_labels)
gtsam::FastMap< ObjectId, Histogram > makeTrackletLengthHistorgram (const Frame::Ptr frame, const std::vector< size_t > &bins={0, 1, 2, 3, 5, 7, 10, 15, 25, 40, 60, std::numeric_limits< size_t >::max()})
Constructs a map of histograms (static features: 0, one for each dynamic object) containing the tracklet length at this frame.
cv::Mat depthTo3D (const ImageWrapper< ImageType::Depth > &depth_image, const cv::Mat &K)
Projects a dense depth map to 3D coordinates in the local frame.
void writeOutProjectMaskAndDepthMap (const ImageWrapper< ImageType::Depth > &depth_image, const ImageWrapper< ImageType::SemanticMask > &mask_image, const Camera &camera, FrameId frame_id)
Saves a re-projected 3D point cloud with labelled points to file as a cv::Mat.
std::pair< gtsam::Vector3, gtsam::Matrix33 > backProjectAndCovariance (const Feature &feature, const Camera &camera, double pixel_sigma, double depth_sigma)
From a feature with valid depth, backproject to a 3D point in the camera frame with the associated covariance (3x3) matrix.
void computeObjectMaskBoundaryMaskHelper (ObjectBoundaryMaskResult &result, const cv::Mat &mask, int thickness, bool use_as_feature_detection_mask, std::function< ObjectIds()> get_object_labels)
Function Documentation
backProjectAndCovariance()
std::pair< gtsam::Vector3, gtsam::Matrix33 > dyno::vision_tools::backProjectAndCovariance (const Feature & feature, const Camera & camera, double pixel_sigma, double depth_sigma)
From a feature with valid depth, backproject to a 3D point in the camera frame with the associated covariance (3x3) matrix.
The measurement covariance matrix for the pixel measurement is obtanied directly as a 2x2 diagonal matrix from the pixel sigma and the measurement covariance for the depth is modelled as a quadratic cost where sigma = depth
depth_sgima^2.
The final covariance matrix is in the diagonal form [x,y,z]
Parameters
feature
camera
pixel_sigma
depth_sigma
Returns
std::pair<gtsam::Vector3, gtsam::Matrix3>
Definition at line 617 of file VisionTools.cc.
{
  const auto gtsam_camera = camera.getImplCamera();
  const auto keypoint = feature.keypoint();
  const auto u = keypoint(0);
  const auto v = keypoint(1);
  CHECK(feature.hasDepth());
  const auto depth = feature.depth();
  const auto& cam_params = camera.getParams();
  const auto fx = cam_params.fx();
  const auto fy = cam_params.fy();
  const auto cx = cam_params.cu();
  const auto cy = cam_params.cv();
  // Jacobian J of backprojection w.r.t. (u, v, d) assuming pinhole camera
  gtsam::Matrix33 J;
  J << depth / fx, 0, (u - cx) / fx, 0, depth / fy, (v - cy) / fy, 0, 0, 1;
  double pixel_sigma2 = pixel_sigma * pixel_sigma;
  double depth_sigma2 = depth_sigma * depth_sigma;
  gtsam::Matrix33 sigma_uvd =
      (Eigen::Vector3d(pixel_sigma2, pixel_sigma2, depth_sigma2)).asDiagonal();
  // Propagate to 3D covariance
  gtsam::Matrix33 sigma_3d = J * sigma_uvd * J.transpose();
  // Back project point
  gtsam::Point3 landmark = gtsam_camera->backproject(keypoint, depth);
  return {landmark, sigma_3d};
}
References dyno::Feature::depth(), dyno::CameraParams::fx(), dyno::Camera::getImplCamera(), dyno::Camera::getParams(), dyno::Feature::hasDepth(), and dyno::Feature::keypoint().
computeObjectMaskBoundaryMask() [1/2]
void dyno::vision_tools::computeObjectMaskBoundaryMask (ObjectBoundaryMaskResult & result, const cv::Mat & mask, int thickness, bool use_as_feature_detection_mask = true)
From an input instance/semantic mask type img construct a image mask (binary) that has True values around each object in the image, with a certain thickness.
This is used to mark all points intside the mask as invalid and should not be tracked. Like any mask used for an feature detector the output mask is a 8-bit integer matrix with non-zero values in the region of interest.
When use_as_feature_detection_mask is True, all pixels inside the thicc boarder are set to zero, and all other values are 255. If this argument is False, the opposite is true (pixels inside the boarder are 255 and others are set to 0)
Definition at line 443 of file VisionTools.cc.
{
  computeObjectMaskBoundaryMaskHelper(
      result, mask, thickness, use_as_feature_detection_mask,
      [&mask]() -> ObjectIds { return vision_tools::getObjectLabels(mask); });
}
References computeObjectMaskBoundaryMaskHelper(), and getObjectLabels().
computeObjectMaskBoundaryMask() [2/2]
void dyno::vision_tools::computeObjectMaskBoundaryMask (ObjectBoundaryMaskResult & result, const ObjectDetectionResult & detection_result, int thickness, bool use_as_feature_detection_mask = true)
Same as computeObjectMaskBoundaryMask but we construct the result from the pre-computed object mask and list of detected object labels. This saves a lot of compute and uses the detection result directly.
Parameters
result
detection_result
thickness
use_as_feature_detection_mask
Definition at line 451 of file VisionTools.cc.
{
  if (detection_result.num() == 0) {
    return;
  }
  computeObjectMaskBoundaryMaskHelper(result, detection_result.labelled_mask,
                                      thickness, use_as_feature_detection_mask,
                                      [&detection_result]() -> ObjectIds {
                                        return detection_result.objectIds();
                                      });
}
References computeObjectMaskBoundaryMaskHelper(), dyno::ObjectDetectionResult::labelled_mask, and dyno::ObjectDetectionResult::num().
computeObjectMaskBoundaryMaskHelper()
void dyno::vision_tools::computeObjectMaskBoundaryMaskHelper (ObjectBoundaryMaskResult & result, const cv::Mat & mask, int thickness, bool use_as_feature_detection_mask, std::function< ObjectIds()> get_object_labels)
Definition at line 361 of file VisionTools.cc.
{
  cv::Mat thicc_boarder;  // god im so funny
  cv::Scalar fill_colour;
  thicc_boarder = cv::Mat::zeros(mask.size(), CV_8UC1);
  const int outer_thickness = thickness;
  // background should be 255 as we're can detect in this region and boarder
  // region should be zero
  if (use_as_feature_detection_mask) {
    result.boundary_mask = cv::Mat(mask.size(), CV_8U, cv::Scalar(255));
    fill_colour = cv::Scalar(0);
  } else {
    result.boundary_mask = cv::Mat(mask.size(), CV_8U, cv::Scalar(0));
    fill_colour = cv::Scalar(255);
  }
  cv::Mat viz = cv::Mat(mask.size(), CV_8UC3, cv::Scalar(0));
  result.objects_detected = get_object_labels();
  // this basically just creates a full mask over the existing masks using the
  // detected contours
  for (const auto object_id : result.objects_detected) {
    std::vector<std::vector<cv::Point>> detected_contours;
    // NOTE: if we use the object detection result I guess the discovered
    // rectangle here could be different to detection rectangle!
    cv::Rect detected_rect;
    CHECK(vision_tools::findObjectBoundingBox(mask, object_id, detected_rect,
                                              detected_contours));
    CHECK_LE(object_id, 255);  // works only with uint8 types...
    cv::drawContours(thicc_boarder, detected_contours, -1, object_id,
                     cv::FILLED);
    result.object_bounding_boxes.push_back(detected_rect);
  }
  // Dilate the mask to expand outwards by 'thickness' pixels
  cv::Mat dilated_mask;
  cv::dilate(thicc_boarder, dilated_mask,
             cv::getStructuringElement(
                 cv::MORPH_ELLIPSE,
                 cv::Size(2 * outer_thickness + 1, 2 * outer_thickness + 1)));
  // Compute the outer border mask
  cv::Mat thicc_outer_boarder_mask = dilated_mask - thicc_boarder;
  // Additionally erode a little but on the inner-side of the mask
  // This helps get rid of pixels directly on the boarder which often have poor
  // depth
  static constexpr int inner_thickness = 10;
  // Generate the inner border
  cv::Mat eroded_mask;
  cv::erode(thicc_boarder, eroded_mask,
            cv::getStructuringElement(
                cv::MORPH_ELLIPSE,
                cv::Size(2 * inner_thickness + 1, 2 * inner_thickness + 1)));
  cv::Mat thicc_inner_boarder_mask = thicc_boarder - eroded_mask;
  // iterate over the objects in the eroded mask again to calculate their
  // bounding box's this will be 'very approximate' area which features can be
  // detected for object j it is approximate because it may not well be
  // approximated by a bounding box
  for (const auto object_id : result.objects_detected) {
    cv::Rect detected_rect;
    vision_tools::findObjectBoundingBox(eroded_mask, object_id, detected_rect);
    result.inner_boarder_object_bounding_boxes.push_back(detected_rect);
  }
  // set boarder pixels to fill colour (e.g. zero if to be used as feature
  // detection mask)
  result.boundary_mask.setTo(fill_colour, thicc_outer_boarder_mask);
  result.boundary_mask.setTo(fill_colour, thicc_inner_boarder_mask);
  result.labelled_boundary_mask = cv::Mat(mask.size(), CV_8U, cv::Scalar(0));
  cv::bitwise_or(thicc_outer_boarder_mask, thicc_inner_boarder_mask,
                 result.labelled_boundary_mask);
  result.is_feature_detection_mask = use_as_feature_detection_mask;
}
References dyno::vision_tools::ObjectBoundaryMaskResult::boundary_mask, findObjectBoundingBox(), dyno::vision_tools::ObjectBoundaryMaskResult::inner_boarder_object_bounding_boxes, dyno::vision_tools::ObjectBoundaryMaskResult::is_feature_detection_mask, dyno::vision_tools::ObjectBoundaryMaskResult::labelled_boundary_mask, dyno::vision_tools::ObjectBoundaryMaskResult::object_bounding_boxes, and dyno::vision_tools::ObjectBoundaryMaskResult::objects_detected.
Referenced by computeObjectMaskBoundaryMask().
depthTo3D()
cv::Mat dyno::vision_tools::depthTo3D (const ImageWrapper< ImageType::Depth > & depth_image, const cv::Mat & K)
Projects a dense depth map to 3D coordinates in the local frame.
Returns a (H x W x 3) image of type CV_64F
Parameters
depth_image
K
Returns
cv::Mat
Definition at line 542 of file VisionTools.cc.
{
  const cv::Mat& depth_map = depth_image;
  int H = depth_map.rows;
  int W = depth_map.cols;
  // Camera intrinsic parameters
  double fx = K.at<double>(0, 0);
  double fy = K.at<double>(1, 1);
  double cx = K.at<double>(0, 2);
  double cy = K.at<double>(1, 2);
  // Generate pixel grid
  cv::Mat u_grid, v_grid;
  cv::Mat u = cv::Mat::zeros(H, W, CV_64F);
  cv::Mat v = cv::Mat::zeros(H, W, CV_64F);
  for (int y = 0; y < H; ++y) {
    for (int x = 0; x < W; ++x) {
      u.at<double>(y, x) = static_cast<double>(x);
      v.at<double>(y, x) = static_cast<double>(y);
    }
  }
  // Normalize pixel coordinates by the intrinsic matrix
  cv::Mat X_norm = (u - cx) / fx;
  cv::Mat Y_norm = (v - cy) / fy;
  // Depth map scaling for 3D coordinates
  cv::Mat X_3D = X_norm.mul(depth_map);
  cv::Mat Y_3D = Y_norm.mul(depth_map);
  cv::Mat Z_3D = depth_map.clone();
  std::vector<cv::Mat> channels = {X_3D, Y_3D, Z_3D};
  cv::Mat point_cloud;
  cv::merge(channels, point_cloud);
  return point_cloud;  // 3-channel float matrix (H x W x 3)
}
References dyno::H().
Referenced by writeOutProjectMaskAndDepthMap().
findObjectBoundingBox() [1/3]
bool dyno::vision_tools::findObjectBoundingBox (const cv::Mat & mask, ObjectId object_id, cv::Rect & detected_rect)
From a instance/semantic mask type img, construct the bounding box for the mask of object_id.
Differes only in output variables.
Parameters
mask
object_id
detected_rect
Returns
true
false
Definition at line 325 of file VisionTools.cc.
{
  std::vector<std::vector<cv::Point>> detected_contours;
  auto result =
      findObjectBoundingBox(mask, object_id, detected_rect, detected_contours);
  (void)detected_contours;
  return result;
}
References findObjectBoundingBox().
findObjectBoundingBox() [2/3]
bool dyno::vision_tools::findObjectBoundingBox (const cv::Mat & mask, ObjectId object_id, cv::Rect & detected_rect, std::vector< std::vector< cv::Point > > & detected_contours)
From a instance/semantic mask type img, construct the bounding box for the mask of object_id.
If object_id is not present in the mask (ie.e no pixe values with this mask), or no valid contours could be constructed, false is returned.
Parameters
mask const cv::Mat&
object_id ObjectId
detected_rect cv::Rect& The calcualted bounding box
detected_contours std::vector<std::vector<cv::Point>>& The calcualted contours used to find the bounding box
Returns
true
false
Definition at line 286 of file VisionTools.cc.
{
  cv::Mat mask_copy = mask.clone();
  cv::Mat obj_mask = (mask_copy == object_id);
  cv::Mat dilated_obj_mask;
  // dilate to fill any small holes in the mask to get a more complete set of
  // contours
  cv::Mat dilate_element = cv::getStructuringElement(
      cv::MORPH_RECT, cv::Size(1, 11));  // a rectangle of 1*5
  cv::dilate(obj_mask, dilated_obj_mask, dilate_element, cv::Point(-1, -1));
  std::vector<std::vector<cv::Point>> contours;
  std::vector<cv::Vec4i> hierarchy;
  cv::findContours(dilated_obj_mask, contours, hierarchy, cv::RETR_TREE,
                   cv::CHAIN_APPROX_NONE);
  detected_contours = contours;
  if (contours.empty()) {
    detected_rect = cv::Rect();
    return false;
  } else if (contours.size() == 1u) {
    detected_rect = cv::boundingRect(contours.at(0));
  } else {
    std::vector<cv::Rect> rectangles;
    for (auto it : contours) {
      rectangles.push_back(cv::boundingRect(it));
    }
    cv::Rect merged_rect = rectangles[0];
    for (const auto& r : rectangles) {
      merged_rect |= r;
    }
    detected_rect = merged_rect;
  }
  return true;
}
Referenced by dyno::ClusterSlamAllLoader::associateDetectedBBWithObject(), computeObjectMaskBoundaryMaskHelper(), dyno::Frame::constructDynamicObservations(), and findObjectBoundingBox().
findObjectBoundingBox() [3/3]
bool dyno::vision_tools::findObjectBoundingBox (const cv::Mat & mask, ObjectId object_id, std::vector< std::vector< cv::Point > > & detected_contours)
From a instance/semantic mask type img, construct the bounding box for the mask of object_id.
Differes only in output variables.
Parameters
mask
object_id
detected_contours
Returns
true
false
Definition at line 334 of file VisionTools.cc.
{
  cv::Rect detected_rect;
  auto result =
      findObjectBoundingBox(mask, object_id, detected_rect, detected_contours);
  (void)detected_rect;
  return result;
}
References findObjectBoundingBox().
getCorrespondences()
void dyno::vision_tools::getCorrespondences (FeaturePairs & correspondences, const FeatureFilterIterator & previous_features, const FeatureFilterIterator & current_features)
Definition at line 75 of file VisionTools.cc.
{
  correspondences.clear();
  const FeatureContainer& previous_feature_container =
      previous_features.getContainer();
  for (const auto& curr_feature : current_features) {
    // check if previous feature and is valid
    if (previous_feature_container.exists(curr_feature->trackletId())) {
      const auto prev_feature = previous_feature_container.getByTrackletId(
          curr_feature->trackletId());
      CHECK(prev_feature);
      // having checked that feature is in the previous set, also check that it
      // ahderes to the filter
      if (!previous_features(prev_feature)) {
        continue;
      }
      correspondences.push_back({prev_feature, curr_feature});
    }
  }
}
References dyno::FeatureContainer::exists(), dyno::FeatureContainer::getByTrackletId(), and dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::getContainer().
Referenced by dyno::Frame::getDynamicCorrespondences(), and dyno::Frame::getStaticCorrespondences().
getObjectLabels()
ObjectIds dyno::vision_tools::getObjectLabels (const cv::Mat & image)
Finds the unique object labels (j) as present in the instance segmentation image. Does not include the background label.
Parameters
image const cv::Mat&
Returns
ObjectIds
Definition at line 100 of file VisionTools.cc.
{
  // CHECK(!image.empty());
  // std::unordered_set<ObjectId> unique_labels;
  // for (auto it = image.begin<ObjectId>(); it != image.end<ObjectId>(); ++it)
  // {
  //   if (*it != background_label) {
  //     unique_labels.insert(*it);
  //   }
  // }
  // return ObjectIds(unique_labels.begin(), unique_labels.end());
  // std::vector<ObjectId> v(image.ptr<ObjectId>(), image.ptr<ObjectId>() +
  // image.total()); std::sort(v.begin(), v.end()); auto last =
  // std::unique(v.begin(), v.end()); v.erase(last, v.end());
  // v.erase(std::remove(v.begin(), v.end(), 0), v.end());
  // return v;
  // from testing in test_code_concepts.cc (CodeConcepts.uniqueLabelSpeed)
  // this implementation is up to 28x faster than a simple a std::set approach!!
  const int numThreads =
      std::min(std::thread::hardware_concurrency(), (unsigned int)image.rows);
  const int rowsPerThread = image.rows / numThreads;
  std::vector<std::future<std::unordered_set<int>>> futures;
  // Launch threads to process row chunks
  for (int t = 0; t < numThreads; ++t) {
    int startRow = t * rowsPerThread;
    int endRow = (t == numThreads - 1) ? image.rows : (t + 1) * rowsPerThread;
    futures.push_back(
        std::async(std::launch::async, [&image, startRow, endRow]() {
          std::unordered_set<int> localUnique;
          for (int row = startRow; row < endRow; ++row) {
            const int* rowPtr = image.ptr<int>(row);
            for (int col = 0; col < image.cols; ++col) {
              localUnique.insert(rowPtr[col]);
            }
          }
          return localUnique;
        }));
  }
  // Merge results
  std::unordered_set<int> globalUnique;
  for (auto& future : futures) {
    auto localSet = future.get();
    globalUnique.insert(localSet.begin(), localSet.end());
  }
  // dont include background label!!
  globalUnique.erase(background_label);
  // Convert to vector (NOTE: not sorted!!)
  std::vector<int> result(globalUnique.begin(), globalUnique.end());
  // std::sort(result.begin(), result.end());
  return result;
}
References dyno::background_label.
Referenced by dyno::ClusterSlamAllLoader::associateDetectedBBWithObject(), computeObjectMaskBoundaryMask(), dyno::Frame::constructDynamicObservations(), dyno::ProjectAriaAllLoader::getInstanceMask(), dyno::removeStaticObjectFromMask(), and shrinkMask().
makeTrackletLengthHistorgram()
gtsam::FastMap< ObjectId, Histogram > dyno::vision_tools::makeTrackletLengthHistorgram (const Frame::Ptr frame, const std::vector< size_t > & bins = {0, 1, 2, 3, 5, 7, 10, 15, 25, 40, 60, std::numeric_limits<size_t>::max()})
Constructs a map of histograms (static features: 0, one for each dynamic object) containing the tracklet length at this frame.
Parameters
frame
bins
Returns
gtsam::FastMap<ObjectId, Histogram>
Definition at line 491 of file VisionTools.cc.
{
  // one for every object + 1 for static points
  gtsam::FastMap<ObjectId, Histogram> histograms;
  const auto& dyamic_features = frame->dynamic_features_;
  auto itr = dyamic_features.beginObjectIterator();
  for (itr; itr != dyamic_features.endObjectIterator(); itr++) {
    auto [object_id, tracklet_ids] = *itr;
    Histogram hist(bh::make_histogram(bh::axis::variable<>(bins)));
    hist.name_ = "tacklet-length-" + std::to_string(object_id);
    for (auto tracklet_id : tracklet_ids) {
      const Feature::Ptr feature = dyamic_features.getByTrackletId(tracklet_id);
      CHECK(feature);
      if (feature->usable()) {
        hist.histogram_(feature->age());
      }
    }
    histograms.insert2(object_id, hist);
  }
  // collect dynamic features
  // for (const auto& [object_id, observations] :
  // frame->getObjectObservations()) {
  //   Histogram hist(bh::make_histogram(bh::axis::variable<>(bins)));
  //   hist.name_ = "tacklet-length-" + std::to_string(object_id);
  //   // for (auto tracklet_id : observations.object_features) {
  //   //   // const Feature::Ptr feature = frame->at(tracklet_id);
  //   //   // CHECK(feature);
  //   //   // if (feature->usable()) {
  //   //   //   hist.histogram_(feature->age());
  //   //   // }
  //   // }
  //   histograms.insert2(object_id, hist);
  // }
  // collect static features
  Histogram static_hist(bh::make_histogram(bh::axis::variable<>(bins)));
  static_hist.name_ = "tacklet-length-0";
  for (const auto& static_feature : frame->static_features_.beginUsable()) {
    static_hist.histogram_(static_feature->age());
  }
  histograms.insert2(background_label, static_hist);
  return histograms;
}
References dyno::background_label, dyno::Histogram::histogram_, and dyno::Histogram::name_.
Referenced by dyno::RGBDFrontendLogger::logTrackingLengthHistogram().
relabelMasks()
void dyno::vision_tools::relabelMasks (const cv::Mat & mask, cv::Mat & relabelled_mask, const ObjectIds & old_labels, const ObjectIds & new_labels)
Definition at line 466 of file VisionTools.cc.
{
  if (old_labels.size() != new_labels.size()) {
    throw std::invalid_argument(
        "Old labels and new labels must have the same size");
  }
  // Create a map from old labels to new labels
  std::unordered_map<ObjectId, ObjectId> label_map;
  for (size_t i = 0; i < old_labels.size(); ++i) {
    label_map[old_labels[i]] = new_labels[i];
  }
  mask.copyTo(relabelled_mask);
  // / Relabel the pixels
  for (int r = 0; r < relabelled_mask.rows; ++r) {
    for (int c = 0; c < relabelled_mask.cols; ++c) {
      ObjectId pixelValue = relabelled_mask.at<ObjectId>(r, c);
      if (label_map.find(pixelValue) != label_map.end()) {
        relabelled_mask.at<ObjectId>(r, c) = label_map[pixelValue];
      }
    }
  }
}
Referenced by dyno::ClusterSlamAllLoader::associateDetectedBBWithObject(), and dyno::ProjectAriaAllLoader::getInstanceMask().
shrinkMask()
void dyno::vision_tools::shrinkMask (const cv::Mat & mask, cv::Mat & shrunk_mask, int erosion_size)
Shrinks all found object masks by a given ammount.
Parameters
mask const cv::Mat& input object mask with pixel values 0, 1... j
shrunk_mask cv::Mat& output object mask with shrink masks.
erosion_size int erosion size
Definition at line 344 of file VisionTools.cc.
{
  shrunk_mask = cv::Mat::zeros(mask.size(), mask.type());
  shrunk_mask.setTo(background_label);
  const ObjectIds original_object_labels = getObjectLabels(mask);
  const cv::Mat element = cv::getStructuringElement(
      cv::MORPH_RECT, cv::Size(2 * erosion_size + 1, 2 * erosion_size + 1));
  for (const auto object_id : original_object_labels) {
    cv::Mat obj_mask = (mask == object_id);
    cv::Mat eroded_mask;
    cv::erode(obj_mask, eroded_mask, element);
    shrunk_mask = shrunk_mask.setTo(object_id, eroded_mask);
  }
}
References dyno::background_label, and getObjectLabels().
writeOutProjectMaskAndDepthMap()
void dyno::vision_tools::writeOutProjectMaskAndDepthMap (const ImageWrapper< ImageType::Depth > & depth_image, const ImageWrapper< ImageType::SemanticMask > & mask_image, const Camera & camera, FrameId frame_id)
Saves a re-projected 3D point cloud with labelled points to file as a cv::Mat.
The depth map is projected into the camera coordinate frame and each pixel is labelled with the tracking label from the mask.
The final image is saved as a CV_64F (double) of W X H X 4 where channels [0:3] are the xyz values of the point and [3] is the tracking label (0=background, 1....N object track label).
Used for reconstructing testing.
Write to a folder called project_mask in the OutputFolder defined by getOutputFilePath.
Parameters
depth_image NOTE: can be any mask (motion, semantic...)
mask_image
frame_id
Definition at line 583 of file VisionTools.cc.
{
  cv::Mat point_cloud =
      depthTo3D(depth_image, camera.getParams().getCameraMatrix());
  const cv::Mat& mask = mask_image;
  // new mask of double type to match the type of the output cloud
  cv::Mat mask_double;
  mask.copyTo(mask_double);
  mask_double.convertTo(mask_double, CV_64F);
  std::vector<cv::Mat> channels = {point_cloud, mask_double};
  cv::Mat projected_cloud;
  cv::merge(channels, projected_cloud);
  static const auto folder_name = "project_mask";
  const std::string output_folder = getOutputFilePath(folder_name);
  // create write out directly if it does not exist
  createDirectory(output_folder);
  const std::string file_name =
      output_folder + "/" + std::to_string(frame_id) + ".yml";
  cv::FileStorage file(file_name, cv::FileStorage::WRITE);
  file << "matrix" << projected_cloud;
  file.release();
}
References dyno::createDirectory(), depthTo3D(), dyno::CameraParams::getCameraMatrix(), dyno::getOutputFilePath(), and dyno::Camera::getParams().