DynoSAM: dyno::LandmarkNode< MEASUREMENT > Class Template Reference
dyno::LandmarkNode< MEASUREMENT > Class Template Reference
Landmark node representing all the measurements of a particular landmark (i) over all time (k to K) in the map-graph.
#include <MapNodes.hpp>
Public Types
using Base = MapNodeBase< MEASUREMENT >
using This = LandmarkNode< MEASUREMENT >
using Measurements = gtsam::FastMap< FrameNodePtr< MEASUREMENT >, MEASUREMENT >
Public Member Functions
LandmarkNode (const std::shared_ptr< Map< MEASUREMENT > > &map)
virtual ~LandmarkNode ()=default
int getId () const override
Returns the tracklet_id.
std::string toString () const override
ObjectId getObjectId () const
bool isStatic () const
Returns true if the landmark is static.
size_t numObservations () const
Number of observations of this landmark.
const FrameNodePtrSet< MEASUREMENT > & getSeenFrames () const
Get all the frame nodes this landmark was observed in.
FrameIds getSeenFrameIds () const
Get all the frame id's this landmark was observed in.
const Measurements & getMeasurements () const
Get all the measurements for this landmark.
bool seenAtFrame (FrameId frame_id) const
True if the landmark was observed at the requested frame.
bool hasMeasurement (FrameId frame_id) const
True if the landmark was a measurement at the requested frame. Should be true if seenAtFrame() is also true.
const MEASUREMENT & getMeasurement (FrameNodePtr< MEASUREMENT > frame_node) const
Get the measurement at the requested frame node. Throws DynosamException if no measurement existd at this frame; use with seenAtFrame or hasMeasurement.
const MEASUREMENT & getMeasurement (FrameId frame_id) const
Get the measurement at the requested frame id. Throws DynosamException if no measurement existd at this frame; use with seenAtFrame or hasMeasurement.
void add (FrameNodePtr< MEASUREMENT > frame_node, const MEASUREMENT &measurement)
Adds a measurement with the associated frame id.
gtsam::Key makeStaticKey () const
Construcs a static landmark key for this landmark. The tracklet id will be used to construct a unique key.
gtsam::Key makeDynamicKey (FrameId frame_id) const
Construcs a dynamic landmark key for this landmark.
DynamicPointSymbol makeDynamicSymbol (FrameId frame_id) const
Construcs a dynamic landmark symbol for this landmark. The frame id and tracklet id will be used to construct a unique key.
Public Member Functions inherited from dyno::MapNodeBase< MEASUREMENT >
MapNodeBase (const std::shared_ptr< Map< MEASUREMENT > > &map)
virtual ~MapNodeBase ()=default
virtual int getId () const =0
virtual std::string toString () const =0
Public Attributes
TrackletId tracklet_id
Unique tracklet (i) of the landmark/.
ObjectId object_id
Object label (j) of the landmark.
bool inlier {true}
bool added_to_opt {false}
Protected Attributes
FrameNodePtrSet< MEASUREMENT > frames_seen_
Measurements measurements_
Protected Attributes inherited from dyno::MapNodeBase< MEASUREMENT >
std::shared_ptr< Map< MEASUREMENT > > map_ptr_
Detailed Description
template<typename MEASUREMENT>
class dyno::LandmarkNode< MEASUREMENT >
Landmark node representing all the measurements of a particular landmark (i) over all time (k to K) in the map-graph.
The node can represent either a static or dynamic landmark and has multiple measurements associated with it.
Template Parameters
MEASUREMENT
Definition at line 671 of file MapNodes.hpp.
Member Typedef Documentation
Base
template<typename MEASUREMENT > using dyno::LandmarkNode< MEASUREMENT >::Base = MapNodeBase<MEASUREMENT>
Definition at line 673 of file MapNodes.hpp.
Measurements
template<typename MEASUREMENT > using dyno::LandmarkNode< MEASUREMENT >::Measurements = gtsam::FastMap<FrameNodePtr<MEASUREMENT>, MEASUREMENT>
Definition at line 677 of file MapNodes.hpp.
This
template<typename MEASUREMENT > using dyno::LandmarkNode< MEASUREMENT >::This = LandmarkNode<MEASUREMENT>
Definition at line 674 of file MapNodes.hpp.
Constructor & Destructor Documentation
LandmarkNode()
template<typename MEASUREMENT > dyno::LandmarkNode< MEASUREMENT >::LandmarkNode (const std::shared_ptr< Map< MEASUREMENT > > & map) inline
Definition at line 680 of file MapNodes.hpp.
      : MapNodeBase<MEASUREMENT>(map) {}
~LandmarkNode()
template<typename MEASUREMENT > virtual dyno::LandmarkNode< MEASUREMENT >::~LandmarkNode () virtual default
Member Function Documentation
add()
template<typename MEASUREMENT > void dyno::LandmarkNode< MEASUREMENT >::add (FrameNodePtr< MEASUREMENT > frame_node, const MEASUREMENT & measurement)
Adds a measurement with the associated frame id.
Parameters
frame_node FrameNodePtr<MEASUREMENT>
measurement const MEASUREMENT&
Definition at line 139 of file MapNodes-inl.hpp.
{
  frames_seen_.insert(frame_node);
  // add measurement to map
  // first check that we dont already have a measurement at this frame
  if (measurements_.exists(frame_node)) {
    throw DynosamException("Unable to add new measurement to landmark node " +
                           std::to_string(this->getId()) + " at frame " +
                           std::to_string(frame_node->getId()) +
                           " as a measurement already exists at this frame!");
  }
  measurements_.insert2(frame_node, measurement);
  CHECK_EQ(frames_seen_.size(), measurements_.size());
}
getId()
template<typename MEASUREMENT > int dyno::LandmarkNode< MEASUREMENT >::getId override virtual
Returns the tracklet_id.
LandmarkNode.
Returns
int
Implements dyno::MapNodeBase< MEASUREMENT >.
Definition at line 119 of file MapNodes-inl.hpp.
{
  return (int)tracklet_id;
}
Referenced by dyno::LandmarkNode< MEASUREMENT >::toString().
getMeasurement() [1/2]
template<typename MEASUREMENT > const MEASUREMENT & dyno::LandmarkNode< MEASUREMENT >::getMeasurement (FrameId frame_id) const
Get the measurement at the requested frame id. Throws DynosamException if no measurement existd at this frame; use with seenAtFrame or hasMeasurement.
Parameters
frame_id FrameId
Returns
const MEASUREMENT&
Definition at line 180 of file MapNodes-inl.hpp.
{
  if (!seenAtFrame(frame_id)) {
    throw DynosamException("Missing measurement in landmark node with id " +
                           std::to_string(tracklet_id) + " at frame " +
                           std::to_string(frame_id));
  }
  return getMeasurement(this->map_ptr_->template getFrame(frame_id));
}
getMeasurement() [2/2]
template<typename MEASUREMENT > const MEASUREMENT & dyno::LandmarkNode< MEASUREMENT >::getMeasurement (FrameNodePtr< MEASUREMENT > frame_node) const
Get the measurement at the requested frame node. Throws DynosamException if no measurement existd at this frame; use with seenAtFrame or hasMeasurement.
Parameters
frame_node FrameNodePtr<MEASUREMENT>
Returns
const MEASUREMENT&
Definition at line 168 of file MapNodes-inl.hpp.
{
  CHECK_NOTNULL(frame_node);
  if (!hasMeasurement(frame_node->frame_id)) {
    throw DynosamException("Missing measurement in landmark node with id " +
                           std::to_string(tracklet_id) + " at frame " +
                           std::to_string(frame_node->frame_id));
  }
  return measurements_.at(frame_node);
}
getMeasurements()
template<typename MEASUREMENT > const Measurements & dyno::LandmarkNode< MEASUREMENT >::getMeasurements () const inline
Get all the measurements for this landmark.
Returns
const Measurements&
Definition at line 758 of file MapNodes.hpp.
{ return measurements_; }
References dyno::LandmarkNode< MEASUREMENT >::measurements_.
getObjectId()
template<typename MEASUREMENT > ObjectId dyno::LandmarkNode< MEASUREMENT >::getObjectId
Definition at line 124 of file MapNodes-inl.hpp.
{
  return object_id;
}
getSeenFrameIds()
template<typename MEASUREMENT > FrameIds dyno::LandmarkNode< MEASUREMENT >::getSeenFrameIds
Get all the frame id's this landmark was observed in.
Returns
FrameIds
Definition at line 217 of file MapNodes-inl.hpp.
{
  return getSeenFrames().template collectIds<FrameId>();
}
getSeenFrames()
template<typename MEASUREMENT > const FrameNodePtrSet< MEASUREMENT > & dyno::LandmarkNode< MEASUREMENT >::getSeenFrames () const inline
Get all the frame nodes this landmark was observed in.
Returns
const FrameNodePtrSet<MEASUREMENT>&
Definition at line 742 of file MapNodes.hpp.
{
    return frames_seen_;
  }
References dyno::LandmarkNode< MEASUREMENT >::frames_seen_.
hasMeasurement()
template<typename MEASUREMENT > bool dyno::LandmarkNode< MEASUREMENT >::hasMeasurement (FrameId frame_id) const
True if the landmark was a measurement at the requested frame. Should be true if seenAtFrame() is also true.
Parameters
frame_id FrameId
Returns
true
false
Definition at line 163 of file MapNodes-inl.hpp.
{
  return this->seenAtFrame(frame_id);
}
isStatic()
template<typename MEASUREMENT > bool dyno::LandmarkNode< MEASUREMENT >::isStatic
Returns true if the landmark is static.
Simply checks the background label, so could be dangerous if the label changes (but this should never happen!!)
Returns
true
false
Definition at line 129 of file MapNodes-inl.hpp.
{
  return object_id == background_label;
}
References dyno::background_label.
Referenced by dyno::LandmarkNode< MEASUREMENT >::toString().
makeDynamicKey()
template<typename MEASUREMENT > gtsam::Key dyno::LandmarkNode< MEASUREMENT >::makeDynamicKey (FrameId frame_id) const
Construcs a dynamic landmark key for this landmark.
See also
LandmarkNode<MEASUREMENT>::makeDynamicSymbol
Parameters
frame_id
Returns
gtsam::Key
Definition at line 201 of file MapNodes-inl.hpp.
{
  return (gtsam::Key)makeDynamicSymbol(frame_id);
}
makeDynamicSymbol()
template<typename MEASUREMENT > DynamicPointSymbol dyno::LandmarkNode< MEASUREMENT >::makeDynamicSymbol (FrameId frame_id) const
Construcs a dynamic landmark symbol for this landmark. The frame id and tracklet id will be used to construct a unique key.
Exceptions
DynosamException if the landmark is not dynamic.
Parameters
frame_id FrameId
Returns
gtsam::Key DynamicPointSymbol
Definition at line 206 of file MapNodes-inl.hpp.
{
  const auto key = DynamicLandmarkSymbol(frame_id, this->tracklet_id);
  if (this->isStatic()) {
    throw InvalidLandmarkQuery(
        key, "Dynamic estimate requested but landmark is static!");
  }
  return key;
}
References dyno::DynamicLandmarkSymbol().
makeStaticKey()
template<typename MEASUREMENT > gtsam::Key dyno::LandmarkNode< MEASUREMENT >::makeStaticKey
Construcs a static landmark key for this landmark. The tracklet id will be used to construct a unique key.
Exceptions
DynosamException if the landmark is not static.
Returns
gtsam::Key
Definition at line 191 of file MapNodes-inl.hpp.
{
  const auto key = StaticLandmarkSymbol(this->tracklet_id);
  if (!this->isStatic()) {
    throw InvalidLandmarkQuery(
        key, "Static estimate requested but landmark is dynamic!");
  }
  return key;
}
References dyno::StaticLandmarkSymbol().
numObservations()
template<typename MEASUREMENT > size_t dyno::LandmarkNode< MEASUREMENT >::numObservations
Number of observations of this landmark.
Returns
size_t
Definition at line 134 of file MapNodes-inl.hpp.
{
  return frames_seen_.size();
}
Referenced by dyno::LandmarkNode< MEASUREMENT >::toString().
seenAtFrame()
template<typename MEASUREMENT > bool dyno::LandmarkNode< MEASUREMENT >::seenAtFrame (FrameId frame_id) const
True if the landmark was observed at the requested frame.
Parameters
frame_id FrameId
Returns
true
false
Definition at line 158 of file MapNodes-inl.hpp.
{
  return frames_seen_.exists(frame_id);
}
toString()
template<typename MEASUREMENT > std::string dyno::LandmarkNode< MEASUREMENT >::toString () const inline override virtual
Implements dyno::MapNodeBase< MEASUREMENT >.
Definition at line 704 of file MapNodes.hpp.
{
    std::stringstream ss;
    if (isStatic()) {
      ss << "Static point: ";
    } else {
      ss << "Dynamic point (" << object_id << "): ";
    }
    // tracklet ID
    ss << getId() << "\n";
    ss << "Num obs: " << numObservations();
    return ss.str();
  }
References dyno::LandmarkNode< MEASUREMENT >::getId(), dyno::LandmarkNode< MEASUREMENT >::isStatic(), dyno::LandmarkNode< MEASUREMENT >::numObservations(), and dyno::LandmarkNode< MEASUREMENT >::object_id.
Member Data Documentation
added_to_opt
template<typename MEASUREMENT > bool dyno::LandmarkNode< MEASUREMENT >::added_to_opt {false}
Indicates if the landmark has been added to the optimisation NOTE: does not indicate if it is still there (ie. it may have been removed due to marginalisation)
Definition at line 695 of file MapNodes.hpp.
frames_seen_
template<typename MEASUREMENT > FrameNodePtrSet<MEASUREMENT> dyno::LandmarkNode< MEASUREMENT >::frames_seen_ protected
Definition at line 839 of file MapNodes.hpp.
Referenced by dyno::LandmarkNode< MEASUREMENT >::getSeenFrames().
inlier
template<typename MEASUREMENT > bool dyno::LandmarkNode< MEASUREMENT >::inlier {true}
Indicates if the landmark has been marked an inlier at some point during the optimisation
Definition at line 691 of file MapNodes.hpp.
measurements_
template<typename MEASUREMENT > Measurements dyno::LandmarkNode< MEASUREMENT >::measurements_ protected
Definition at line 840 of file MapNodes.hpp.
Referenced by dyno::LandmarkNode< MEASUREMENT >::getMeasurements().
object_id
template<typename MEASUREMENT > ObjectId dyno::LandmarkNode< MEASUREMENT >::object_id
Object label (j) of the landmark.
Definition at line 687 of file MapNodes.hpp.
Referenced by dyno::LandmarkNode< MEASUREMENT >::toString().
tracklet_id
template<typename MEASUREMENT > TrackletId dyno::LandmarkNode< MEASUREMENT >::tracklet_id
Unique tracklet (i) of the landmark/.
Definition at line 685 of file MapNodes.hpp.
The documentation for this class was generated from the following files:
dynosam_opt/include/dynosam_opt/MapNodes.hpp
dynosam_opt/include/dynosam_opt/MapNodes-inl.hpp