DynoSAM: dyno::utils::TRErrorPair Struct Reference
dyno::utils::TRErrorPair Struct Reference
Translation-Rotation error pair.
#include <Metrics.hpp>
Public Member Functions
TRErrorPair ()=default
rads
TRErrorPair (double translation, double rot)
Construct a new TRErrorPair object.
double getRotationErrorDegrees () const
Get the rotation error in degrees.
Static Public Member Functions
static TRErrorPair CalculatePoseError (const gtsam::Pose3 &M, const gtsam::Pose3 &M_hat)
Calculates the pose error between two poses in the same frame.
static TRErrorPair CalculateRelativePoseError (const gtsam::Pose3 &M_ref, const gtsam::Pose3 &M_curr, const gtsam::Pose3 &M_hat_ref, const gtsam::Pose3 &M_hat_curr)
Calculates the relative pose error between poses.
Public Attributes
double translation_ = 0
double rot_ = 0
meters
Detailed Description
Translation-Rotation error pair.
Definition at line 38 of file Metrics.hpp.
Constructor & Destructor Documentation
TRErrorPair() [1/2]
dyno::utils::TRErrorPair::TRErrorPair () default
rads
Referenced by CalculatePoseError().
TRErrorPair() [2/2]
dyno::utils::TRErrorPair::TRErrorPair (double translation, double rot)
Construct a new TRErrorPair object.
Parameters
translation Translation error in meters
rot Rotation error in radians
Definition at line 28 of file Metrics.cc.
: translation_(translation), rot_(rot) {}
Member Function Documentation
CalculatePoseError()
TRErrorPair dyno::utils::TRErrorPair::CalculatePoseError (const gtsam::Pose3 & M, const gtsam::Pose3 & M_hat) static
Calculates the pose error between two poses in the same frame.
E = M^{-1} M_hat
t_e = L2 norm of the translation component of E r_e = axis angle of E (trace of the rotation matrix of E)
Parameters
M const gtsam::Pose3& Estimated pose
M_hat const gtsam::Pose3& Ground Truth (comparison) pose
Returns
TRErrorPair
Definition at line 34 of file Metrics.cc.
{
    const gtsam::Pose3 E = M.inverse() * M_hat;
    // L2 norm - ie. magnitude
    const double t_e = E.translation().norm();
    const gtsam::Matrix33 rotation_error = E.rotation().matrix();
    std::pair<gtsam::Unit3, double> axis_angle = gtsam::Rot3(rotation_error).axisAngle();
    //need to wrap?
    const double r_e = axis_angle.second;
    return TRErrorPair(t_e, r_e);
}
References TRErrorPair().
Referenced by CalculateRelativePoseError().
CalculateRelativePoseError()
TRErrorPair dyno::utils::TRErrorPair::CalculateRelativePoseError (const gtsam::Pose3 & M_ref, const gtsam::Pose3 & M_curr, const gtsam::Pose3 & M_hat_ref, const gtsam::Pose3 & M_hat_curr) static
Calculates the relative pose error between poses.
First calcualte the relative pose change between the reference and current frames ie. ref_T_curr and ref_T_hat_curr and then take the pose error between these two relative poses.
The ref frame is usually the previous frame when analysing frame to frame motion but is just used to calcualte the relative transformation
Parameters
M_ref const gtsam::Pose3& Estimated pose at the reference frame
M_curr const gtsam::Pose3& Estimated pose at the current frame
M_hat_ref const gtsam::Pose3& Ground truth (comparison) pose at the reference frame
M_hat_curr const gtsam::Pose3& Ground truth (comparison) pose at the current frame
Returns
TRErrorPair
Definition at line 49 of file Metrics.cc.
{
    // pose change between ref and current
    const gtsam::Pose3 ref_T_curr = M_ref.inverse() * M_curr;
    const gtsam::Pose3 ref_T_hat_curr = M_hat_ref.inverse() * M_hat_curr;
    return CalculatePoseError(ref_T_curr, ref_T_hat_curr);
}
References CalculatePoseError().
getRotationErrorDegrees()
double dyno::utils::TRErrorPair::getRotationErrorDegrees () const
Get the rotation error in degrees.
Returns
double
Definition at line 30 of file Metrics.cc.
{
    return dyno::rads2Deg(rot_);
}
References dyno::rads2Deg(), and rot_.
Member Data Documentation
rot_
double dyno::utils::TRErrorPair::rot_ = 0
meters
Definition at line 41 of file Metrics.hpp.
Referenced by dyno::utils::TRErrorPairVector::average(), and getRotationErrorDegrees().
translation_
double dyno::utils::TRErrorPair::translation_ = 0
Definition at line 40 of file Metrics.hpp.
Referenced by dyno::utils::TRErrorPairVector::average().
The documentation for this struct was generated from the following files:
dynosam/include/dynosam/utils/Metrics.hpp
dynosam/src/utils/Metrics.cc