DynoSAM: dyno::ImageType::SemanticMask Struct Reference
dyno::ImageType::SemanticMask Struct Reference
#include <ImageTypes.hpp>
Static Public Member Functions
static void validate (const cv::Mat &input)
Expected opencv image type for SemanticMask image type.
static std::string name ()
static cv::Mat toRGB (const ImageWrapper< SemanticMask > &image)
Static Public Attributes
static constexpr int OpenCVType = CV_32SC1
Detailed Description
Definition at line 118 of file ImageTypes.hpp.
Member Function Documentation
name()
static std::string dyno::ImageType::SemanticMask::name () inline static
Definition at line 121 of file ImageTypes.hpp.
{ return "SemanticMask"; }
toRGB()
cv::Mat dyno::ImageType::SemanticMask::toRGB (const ImageWrapper< SemanticMask > & image) static
Definition at line 177 of file ImageTypes.cc.
{
  const cv::Mat& semantic_mask = image;
  return utils::labelMaskToRGB(semantic_mask, background_label);
}
References dyno::background_label, and dyno::utils::labelMaskToRGB().
validate()
void dyno::ImageType::SemanticMask::validate (const cv::Mat & input) static
Expected opencv image type for SemanticMask image type.
Definition at line 173 of file ImageTypes.cc.
{
  validateMask(input, name());
}
References dyno::validateMask().
Referenced by dyno::removeStaticObjectFromMask().
Member Data Documentation
OpenCVType
constexpr int dyno::ImageType::SemanticMask::OpenCVType = CV_32SC1 static constexpr
Definition at line 119 of file ImageTypes.hpp.
The documentation for this struct was generated from the following files:
dynosam/include/dynosam/common/ImageTypes.hpp
dynosam/src/common/ImageTypes.cc