DynoSAM: dyno::internal::HungarianAlgorithm Struct Reference
dyno::internal::HungarianAlgorithm Struct Reference
#include <Algorithms.hpp>
Public Member Functions
HungarianAlgorithm ()=default
double solve (const Eigen::MatrixXd &cost_matrix, Eigen::VectorXi &assignment) const
Solve the optical assignment problem given a set of workers (row) and jobs (columns). We have to find an assignment of the jobs to the workers, such that each job is assigned to one worker and each worker is assigned one job, such that the total cost of assignment is minimum.
Private Member Functions
void assignmentoptimal (int *assignment, double *cost, double *distMatrixIn, int nOfRows, int nOfColumns) const
void buildassignmentvector (int *assignment, bool *starMatrix, int nOfRows, int nOfColumns) const
void computeassignmentcost (int *assignment, double *cost, double *distMatrix, int nOfRows) const
void step2a (int *assignment, double *distMatrix, bool *starMatrix, bool *newStarMatrix, bool *primeMatrix, bool *coveredColumns, bool *coveredRows, int nOfRows, int nOfColumns, int minDim) const
void step2b (int *assignment, double *distMatrix, bool *starMatrix, bool *newStarMatrix, bool *primeMatrix, bool *coveredColumns, bool *coveredRows, int nOfRows, int nOfColumns, int minDim) const
void step3 (int *assignment, double *distMatrix, bool *starMatrix, bool *newStarMatrix, bool *primeMatrix, bool *coveredColumns, bool *coveredRows, int nOfRows, int nOfColumns, int minDim) const
void step4 (int *assignment, double *distMatrix, bool *starMatrix, bool *newStarMatrix, bool *primeMatrix, bool *coveredColumns, bool *coveredRows, int nOfRows, int nOfColumns, int minDim, int row, int col) const
void step5 (int *assignment, double *distMatrix, bool *starMatrix, bool *newStarMatrix, bool *primeMatrix, bool *coveredColumns, bool *coveredRows, int nOfRows, int nOfColumns, int minDim) const
Detailed Description
Definition at line 42 of file Algorithms.hpp.
Constructor & Destructor Documentation
HungarianAlgorithm()
dyno::internal::HungarianAlgorithm::HungarianAlgorithm () default
Member Function Documentation
assignmentoptimal()
void dyno::internal::HungarianAlgorithm::assignmentoptimal (int * assignment, double * cost, double * distMatrixIn, int nOfRows, int nOfColumns) const private
Definition at line 71 of file Algorithms.cc.
{
  double *distMatrix, *distMatrixTemp, *distMatrixEnd, *columnEnd, value,
      minValue;
  bool *coveredColumns, *coveredRows, *starMatrix, *newStarMatrix, *primeMatrix;
  int nOfElements, minDim, row, col;
  /* initialization */
  *cost = 0;
  for (row = 0; row < nOfRows; row++) assignment[row] = -1;
  /* generate working copy of distance Matrix */
  /* check if all matrix elements are positive */
  nOfElements = nOfRows * nOfColumns;
  distMatrix = (double *)malloc(nOfElements * sizeof(double));
  distMatrixEnd = distMatrix + nOfElements;
  for (row = 0; row < nOfElements; row++) {
    value = distMatrixIn[row];
    if (value < 0)
      throw std::runtime_error(
          "HungarianAlgorithm failed: All matrix elements have to be "
          "non-negative.");
    distMatrix[row] = value;
  }
  /* memory allocation */
  coveredColumns = (bool *)calloc(nOfColumns, sizeof(bool));
  coveredRows = (bool *)calloc(nOfRows, sizeof(bool));
  starMatrix = (bool *)calloc(nOfElements, sizeof(bool));
  primeMatrix = (bool *)calloc(nOfElements, sizeof(bool));
  newStarMatrix = (bool *)calloc(nOfElements, sizeof(bool)); /* used in step4 */
  /* preliminary steps */
  if (nOfRows <= nOfColumns) {
    minDim = nOfRows;
    for (row = 0; row < nOfRows; row++) {
      /* find the smallest element in the row */
      distMatrixTemp = distMatrix + row;
      minValue = *distMatrixTemp;
      distMatrixTemp += nOfRows;
      while (distMatrixTemp < distMatrixEnd) {
        value = *distMatrixTemp;
        if (value < minValue) minValue = value;
        distMatrixTemp += nOfRows;
      }
      /* subtract the smallest element from each element of the row */
      distMatrixTemp = distMatrix + row;
      while (distMatrixTemp < distMatrixEnd) {
        *distMatrixTemp -= minValue;
        distMatrixTemp += nOfRows;
      }
    }
    /* Steps 1 and 2a */
    for (row = 0; row < nOfRows; row++)
      for (col = 0; col < nOfColumns; col++)
        if (fabs(distMatrix[row + nOfRows * col]) < DBL_EPSILON)
          if (!coveredColumns[col]) {
            starMatrix[row + nOfRows * col] = true;
            coveredColumns[col] = true;
            break;
          }
  } else /* if(nOfRows > nOfColumns) */
  {
    minDim = nOfColumns;
    for (col = 0; col < nOfColumns; col++) {
      /* find the smallest element in the column */
      distMatrixTemp = distMatrix + nOfRows * col;
      columnEnd = distMatrixTemp + nOfRows;
      minValue = *distMatrixTemp++;
      while (distMatrixTemp < columnEnd) {
        value = *distMatrixTemp++;
        if (value < minValue) minValue = value;
      }
      /* subtract the smallest element from each element of the column */
      distMatrixTemp = distMatrix + nOfRows * col;
      while (distMatrixTemp < columnEnd) *distMatrixTemp++ -= minValue;
    }
    /* Steps 1 and 2a */
    for (col = 0; col < nOfColumns; col++)
      for (row = 0; row < nOfRows; row++)
        if (fabs(distMatrix[row + nOfRows * col]) < DBL_EPSILON)
          if (!coveredRows[row]) {
            starMatrix[row + nOfRows * col] = true;
            coveredColumns[col] = true;
            coveredRows[row] = true;
            break;
          }
    for (row = 0; row < nOfRows; row++) coveredRows[row] = false;
  }
  /* move to step 2b */
  step2b(assignment, distMatrix, starMatrix, newStarMatrix, primeMatrix,
         coveredColumns, coveredRows, nOfRows, nOfColumns, minDim);
  /* compute cost and remove invalid assignments */
  computeassignmentcost(assignment, cost, distMatrixIn, nOfRows);
  /* free allocated memory */
  free(distMatrix);
  free(coveredColumns);
  free(coveredRows);
  free(starMatrix);
  free(primeMatrix);
  free(newStarMatrix);
}
References computeassignmentcost(), and step2b().
Referenced by solve().
buildassignmentvector()
void dyno::internal::HungarianAlgorithm::buildassignmentvector (int * assignment, bool * starMatrix, int nOfRows, int nOfColumns) const private
Definition at line 186 of file Algorithms.cc.
{
  int row, col;
  for (row = 0; row < nOfRows; row++)
    for (col = 0; col < nOfColumns; col++)
      if (starMatrix[row + nOfRows * col]) {
#ifdef ONE_INDEXING
        assignment[row] = col + 1; /* MATLAB-Indexing */
#else
        assignment[row] = col;
#endif
        break;
      }
}
Referenced by step2b().
computeassignmentcost()
void dyno::internal::HungarianAlgorithm::computeassignmentcost (int * assignment, double * cost, double * distMatrix, int nOfRows) const private
Definition at line 203 of file Algorithms.cc.
{
  int row, col;
  for (row = 0; row < nOfRows; row++) {
    col = assignment[row];
    if (col >= 0) *cost += distMatrix[row + nOfRows * col];
  }
}
Referenced by assignmentoptimal().
solve()
double dyno::internal::HungarianAlgorithm::solve (const Eigen::MatrixXd & cost_matrix, Eigen::VectorXi & assignment) const
Solve the optical assignment problem given a set of workers (row) and jobs (columns). We have to find an assignment of the jobs to the workers, such that each job is assigned to one worker and each worker is assigned one job, such that the total cost of assignment is minimum.
DistMatrix is nonnegative [n * m] matrix (where n <= m), representing n workers and m jobs. The element in the i-th row and j-th column represents the cost of assigning the j-th job to the i-th worker.
The result is a vector of size [n * 1], where each value is the index in the column (j) that i is assigned to such that \hat{j} = assignment[i]
Parameters
DistMatrix const Eigen::MatrixXd&
assignment Eigen::VectorXi&
Returns
double
Definition at line 42 of file Algorithms.cc.
{
  const auto nRows = cost_matrix.rows();
  const auto nCols = cost_matrix.cols();
  double *distMatrixIn = new double[nRows * nCols];
  int *assignmentArr = new int[nRows];
  double cost = 0.0;
  // Fill in the distMatrixIn. Mind the index is "i + nRows * j".
  // Here the cost matrix of size MxN is defined as a double precision array of
  // N*M elements. In the solving functions matrices are seen to be saved
  // MATLAB-internally in row-order. (i.e. the matrix [1 2; 3 4] will be stored
  // as a vector [1 3 2 4], NOT [1 2 3 4]).
  for (unsigned int i = 0; i < nRows; i++)
    for (unsigned int j = 0; j < nCols; j++)
      distMatrixIn[i + nRows * j] = cost_matrix(i, j);
  // call solving function
  assignmentoptimal(assignmentArr, &cost, distMatrixIn, nRows, nCols);
  assignment.resize(nRows);
  for (unsigned int r = 0; r < nRows; r++) assignment(r) = assignmentArr[r];
  delete[] distMatrixIn;
  delete[] assignmentArr;
  return cost;
}
References assignmentoptimal().
Referenced by dyno::ClusterSlamAllLoader::associateDetectedBBWithObject().
step2a()
void dyno::internal::HungarianAlgorithm::step2a (int * assignment, double * distMatrix, bool * starMatrix, bool * newStarMatrix, bool * primeMatrix, bool * coveredColumns, bool * coveredRows, int nOfRows, int nOfColumns, int minDim) const private
Definition at line 214 of file Algorithms.cc.
{
  bool *starMatrixTemp, *columnEnd;
  int col;
  /* cover every column containing a starred zero */
  for (col = 0; col < nOfColumns; col++) {
    starMatrixTemp = starMatrix + nOfRows * col;
    columnEnd = starMatrixTemp + nOfRows;
    while (starMatrixTemp < columnEnd) {
      if (*starMatrixTemp++) {
        coveredColumns[col] = true;
        break;
      }
    }
  }
  /* move to step 3 */
  step2b(assignment, distMatrix, starMatrix, newStarMatrix, primeMatrix,
         coveredColumns, coveredRows, nOfRows, nOfColumns, minDim);
}
References step2b().
Referenced by step4().
step2b()
void dyno::internal::HungarianAlgorithm::step2b (int * assignment, double * distMatrix, bool * starMatrix, bool * newStarMatrix, bool * primeMatrix, bool * coveredColumns, bool * coveredRows, int nOfRows, int nOfColumns, int minDim) const private
Definition at line 239 of file Algorithms.cc.
{
  int col, nOfCoveredColumns;
  /* count covered columns */
  nOfCoveredColumns = 0;
  for (col = 0; col < nOfColumns; col++)
    if (coveredColumns[col]) nOfCoveredColumns++;
  if (nOfCoveredColumns == minDim) {
    /* algorithm finished */
    buildassignmentvector(assignment, starMatrix, nOfRows, nOfColumns);
  } else {
    /* move to step 3 */
    step3(assignment, distMatrix, starMatrix, newStarMatrix, primeMatrix,
          coveredColumns, coveredRows, nOfRows, nOfColumns, minDim);
  }
}
References buildassignmentvector(), and step3().
Referenced by assignmentoptimal(), and step2a().
step3()
void dyno::internal::HungarianAlgorithm::step3 (int * assignment, double * distMatrix, bool * starMatrix, bool * newStarMatrix, bool * primeMatrix, bool * coveredColumns, bool * coveredRows, int nOfRows, int nOfColumns, int minDim) const private
Definition at line 261 of file Algorithms.cc.
{
  bool zerosFound;
  int row, col, starCol;
  zerosFound = true;
  while (zerosFound) {
    zerosFound = false;
    for (col = 0; col < nOfColumns; col++)
      if (!coveredColumns[col])
        for (row = 0; row < nOfRows; row++)
          if ((!coveredRows[row]) &&
              (fabs(distMatrix[row + nOfRows * col]) < DBL_EPSILON)) {
            /* prime zero */
            primeMatrix[row + nOfRows * col] = true;
            /* find starred zero in current row */
            for (starCol = 0; starCol < nOfColumns; starCol++)
              if (starMatrix[row + nOfRows * starCol]) break;
            if (starCol == nOfColumns) /* no starred zero found */
            {
              /* move to step 4 */
              step4(assignment, distMatrix, starMatrix, newStarMatrix,
                    primeMatrix, coveredColumns, coveredRows, nOfRows,
                    nOfColumns, minDim, row, col);
              return;
            } else {
              coveredRows[row] = true;
              coveredColumns[starCol] = false;
              zerosFound = true;
              break;
            }
          }
  }
  /* move to step 5 */
  step5(assignment, distMatrix, starMatrix, newStarMatrix, primeMatrix,
        coveredColumns, coveredRows, nOfRows, nOfColumns, minDim);
}
References step4(), and step5().
Referenced by step2b(), and step5().
step4()
void dyno::internal::HungarianAlgorithm::step4 (int * assignment, double * distMatrix, bool * starMatrix, bool * newStarMatrix, bool * primeMatrix, bool * coveredColumns, bool * coveredRows, int nOfRows, int nOfColumns, int minDim, int row, int col) const private
Definition at line 305 of file Algorithms.cc.
{
  int n, starRow, starCol, primeRow, primeCol;
  int nOfElements = nOfRows * nOfColumns;
  /* generate temporary copy of starMatrix */
  for (n = 0; n < nOfElements; n++) newStarMatrix[n] = starMatrix[n];
  /* star current zero */
  newStarMatrix[row + nOfRows * col] = true;
  /* find starred zero in current column */
  starCol = col;
  for (starRow = 0; starRow < nOfRows; starRow++)
    if (starMatrix[starRow + nOfRows * starCol]) break;
  while (starRow < nOfRows) {
    /* unstar the starred zero */
    newStarMatrix[starRow + nOfRows * starCol] = false;
    /* find primed zero in current row */
    primeRow = starRow;
    for (primeCol = 0; primeCol < nOfColumns; primeCol++)
      if (primeMatrix[primeRow + nOfRows * primeCol]) break;
    /* star the primed zero */
    newStarMatrix[primeRow + nOfRows * primeCol] = true;
    /* find starred zero in current column */
    starCol = primeCol;
    for (starRow = 0; starRow < nOfRows; starRow++)
      if (starMatrix[starRow + nOfRows * starCol]) break;
  }
  /* use temporary copy as new starMatrix */
  /* delete all primes, uncover all rows */
  for (n = 0; n < nOfElements; n++) {
    primeMatrix[n] = false;
    starMatrix[n] = newStarMatrix[n];
  }
  for (n = 0; n < nOfRows; n++) coveredRows[n] = false;
  /* move to step 2a */
  step2a(assignment, distMatrix, starMatrix, newStarMatrix, primeMatrix,
         coveredColumns, coveredRows, nOfRows, nOfColumns, minDim);
}
References step2a().
Referenced by step3().
step5()
void dyno::internal::HungarianAlgorithm::step5 (int * assignment, double * distMatrix, bool * starMatrix, bool * newStarMatrix, bool * primeMatrix, bool * coveredColumns, bool * coveredRows, int nOfRows, int nOfColumns, int minDim) const private
Definition at line 355 of file Algorithms.cc.
{
  double h, value;
  int row, col;
  /* find smallest uncovered element h */
  h = DBL_MAX;
  for (row = 0; row < nOfRows; row++)
    if (!coveredRows[row])
      for (col = 0; col < nOfColumns; col++)
        if (!coveredColumns[col]) {
          value = distMatrix[row + nOfRows * col];
          if (value < h) h = value;
        }
  /* add h to each covered row */
  for (row = 0; row < nOfRows; row++)
    if (coveredRows[row])
      for (col = 0; col < nOfColumns; col++)
        distMatrix[row + nOfRows * col] += h;
  /* subtract h from each uncovered column */
  for (col = 0; col < nOfColumns; col++)
    if (!coveredColumns[col])
      for (row = 0; row < nOfRows; row++) distMatrix[row + nOfRows * col] -= h;
  /* move to step 3 */
  step3(assignment, distMatrix, starMatrix, newStarMatrix, primeMatrix,
        coveredColumns, coveredRows, nOfRows, nOfColumns, minDim);
}
References step3().
Referenced by step3().
The documentation for this struct was generated from the following files:
dynosam_common/include/dynosam_common/Algorithms.hpp
dynosam_common/src/Algorithms.cc