DynoSAM: dyno::internal::filter_iterator_base< Container, Iter, FilterFunction > Struct Template Reference
dyno::internal::filter_iterator_base< Container, Iter, FilterFunction > Struct Template Reference
#include <StructuredContainers.hpp>
Public Types
using BaseDetail = filter_iterator_detail< typename Iter::pointer >
using iterator = Iter
using container = Container
using value_type = typename std::iterator_traits< T >::value_type
naming conventions to match those required by iterator traits
using reference_type = typename std::iterator_traits< T >::reference
using pointer = typename std::iterator_traits< T >::pointer
using difference_type = typename std::iterator_traits< T >::difference_type
using iterator_category = std::forward_iterator_tag
Public Types inherited from dyno::internal::filter_iterator_detail< Iter::pointer >
using value_type = typename std::iterator_traits< Iter::pointer >::value_type
naming conventions to match those required by iterator traits
using reference_type = typename std::iterator_traits< Iter::pointer >::reference
using pointer = typename std::iterator_traits< Iter::pointer >::pointer
using difference_type = typename std::iterator_traits< Iter::pointer >::difference_type
using iterator_category = std::forward_iterator_tag
Public Member Functions
filter_iterator_base (Container &container, const FilterFunction &filter_func)
reference_type operator* ()
reference_type operator-> ()
bool operator== (const filter_iterator_base &other) const
bool operator!= (const filter_iterator_base &other) const
bool operator== (const iterator &other) const
bool operator!= (const iterator &other) const
Container & getContainer ()
const Container & getContainer () const
bool operator() (typename Container::const_reference arg) const
filter_iterator_base & operator++ ()
filter_iterator_base & operator++ (int x)
filter_iterator_base begin ()
filter_iterator_base end ()
const filter_iterator_base begin () const
const filter_iterator_base end () const
Protected Member Functions
filter_iterator_base (Container &container, const FilterFunction &filter_func, iterator it)
Protected Attributes
Container & container_
FilterFunction filter_func_
reference to container
iterator it_
Private Member Functions
bool is_invalid () const
void find_next_valid ()
Detailed Description
template<typename Container, typename Iter, typename FilterFunction = std::function<bool(typename Container::const_reference)>>
struct dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >
Definition at line 80 of file StructuredContainers.hpp.
Member Typedef Documentation
BaseDetail
template<typename Container , typename Iter , typename FilterFunction = std::function<bool(typename Container::const_reference)>> using dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::BaseDetail = filter_iterator_detail<typename Iter::pointer>
Definition at line 83 of file StructuredContainers.hpp.
container
template<typename Container , typename Iter , typename FilterFunction = std::function<bool(typename Container::const_reference)>> using dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::container = Container
Definition at line 85 of file StructuredContainers.hpp.
difference_type
template<typename Container , typename Iter , typename FilterFunction = std::function<bool(typename Container::const_reference)>> using dyno::internal::filter_iterator_detail< T >::difference_type = typename std::iterator_traits<T>::difference_type
Definition at line 66 of file StructuredContainers.hpp.
iterator
template<typename Container , typename Iter , typename FilterFunction = std::function<bool(typename Container::const_reference)>> using dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::iterator = Iter
Definition at line 84 of file StructuredContainers.hpp.
iterator_category
template<typename Container , typename Iter , typename FilterFunction = std::function<bool(typename Container::const_reference)>> using dyno::internal::filter_iterator_detail< T >::iterator_category = std::forward_iterator_tag
Definition at line 67 of file StructuredContainers.hpp.
pointer
template<typename Container , typename Iter , typename FilterFunction = std::function<bool(typename Container::const_reference)>> using dyno::internal::filter_iterator_detail< T >::pointer = typename std::iterator_traits<T>::pointer
Definition at line 65 of file StructuredContainers.hpp.
reference_type
template<typename Container , typename Iter , typename FilterFunction = std::function<bool(typename Container::const_reference)>> using dyno::internal::filter_iterator_detail< T >::reference_type = typename std::iterator_traits<T>::reference
Definition at line 64 of file StructuredContainers.hpp.
value_type
template<typename Container , typename Iter , typename FilterFunction = std::function<bool(typename Container::const_reference)>> using dyno::internal::filter_iterator_detail< T >::value_type = typename std::iterator_traits<T>::value_type
naming conventions to match those required by iterator traits
Definition at line 63 of file StructuredContainers.hpp.
Constructor & Destructor Documentation
filter_iterator_base() [1/2]
template<typename Container , typename Iter , typename FilterFunction = std::function<bool(typename Container::const_reference)>> dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::filter_iterator_base (Container & container, const FilterFunction & filter_func) inline
Definition at line 92 of file StructuredContainers.hpp.
: filter_iterator_base(container, filter_func,container.begin()) {}
filter_iterator_base() [2/2]
template<typename Container , typename Iter , typename FilterFunction = std::function<bool(typename Container::const_reference)>> dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::filter_iterator_base (Container & container, const FilterFunction & filter_func, iterator it) inline protected
Definition at line 153 of file StructuredContainers.hpp.
        :   container_(container), filter_func_(filter_func), it_(it)
        {  find_next_valid(); }
References dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::find_next_valid().
Member Function Documentation
begin() [1/2]
template<typename Container , typename Iter , typename FilterFunction = std::function<bool(typename Container::const_reference)>> filter_iterator_base dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::begin () inline
Definition at line 135 of file StructuredContainers.hpp.
{ return filter_iterator_base(container_, filter_func_, container_.begin()); }
References dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::container_, and dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::filter_func_.
begin() [2/2]
template<typename Container , typename Iter , typename FilterFunction = std::function<bool(typename Container::const_reference)>> const filter_iterator_base dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::begin () const inline
Definition at line 138 of file StructuredContainers.hpp.
{ return filter_iterator_base(container_, filter_func_, container_.begin()); }
References dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::container_, and dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::filter_func_.
end() [1/2]
template<typename Container , typename Iter , typename FilterFunction = std::function<bool(typename Container::const_reference)>> filter_iterator_base dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::end () inline
Definition at line 136 of file StructuredContainers.hpp.
{ return filter_iterator_base(container_, filter_func_, container_.end()); }
References dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::container_, and dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::filter_func_.
end() [2/2]
template<typename Container , typename Iter , typename FilterFunction = std::function<bool(typename Container::const_reference)>> const filter_iterator_base dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::end () const inline
Definition at line 139 of file StructuredContainers.hpp.
{ return filter_iterator_base(container_, filter_func_, container_.end()); }
References dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::container_, and dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::filter_func_.
find_next_valid()
template<typename Container , typename Iter , typename FilterFunction = std::function<bool(typename Container::const_reference)>> void dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::find_next_valid () inline private
Definition at line 146 of file StructuredContainers.hpp.
{
        while(is_invalid()) {
            this->operator++();
        }
    }
References dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::is_invalid(), and dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::operator++().
Referenced by dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::filter_iterator_base().
getContainer() [1/2]
template<typename Container , typename Iter , typename FilterFunction = std::function<bool(typename Container::const_reference)>> Container & dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::getContainer () inline
Definition at line 108 of file StructuredContainers.hpp.
{ return container_; }
References dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::container_.
Referenced by dyno::vision_tools::getCorrespondences().
getContainer() [2/2]
template<typename Container , typename Iter , typename FilterFunction = std::function<bool(typename Container::const_reference)>> const Container & dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::getContainer () const inline
Definition at line 109 of file StructuredContainers.hpp.
{ return container_; }
References dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::container_.
is_invalid()
template<typename Container , typename Iter , typename FilterFunction = std::function<bool(typename Container::const_reference)>> bool dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::is_invalid () const inline private
Definition at line 142 of file StructuredContainers.hpp.
{
        return it_ != container_.end() && !filter_func_(*it_);
    }
References dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::container_, dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::filter_func_, and dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::it_.
Referenced by dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::find_next_valid(), and dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::operator++().
operator!=() [1/2]
template<typename Container , typename Iter , typename FilterFunction = std::function<bool(typename Container::const_reference)>> bool dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::operator!= (const filter_iterator_base< Container, Iter, FilterFunction > & other) const inline
Definition at line 100 of file StructuredContainers.hpp.
{ return it_ != other.it_; }
References dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::it_.
operator!=() [2/2]
template<typename Container , typename Iter , typename FilterFunction = std::function<bool(typename Container::const_reference)>> bool dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::operator!= (const iterator & other) const inline
Definition at line 105 of file StructuredContainers.hpp.
{ return it_ != other; }
References dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::it_.
operator()()
template<typename Container , typename Iter , typename FilterFunction = std::function<bool(typename Container::const_reference)>> bool dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::operator() (typename Container::const_reference arg) const inline
Definition at line 111 of file StructuredContainers.hpp.
{
        return filter_func_(arg);
    }
References dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::filter_func_.
operator*()
template<typename Container , typename Iter , typename FilterFunction = std::function<bool(typename Container::const_reference)>> reference_type dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::operator* () inline
Definition at line 94 of file StructuredContainers.hpp.
{ return *it_; }
References dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::it_.
operator++() [1/2]
template<typename Container , typename Iter , typename FilterFunction = std::function<bool(typename Container::const_reference)>> filter_iterator_base & dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::operator++ () inline
Definition at line 117 of file StructuredContainers.hpp.
{
        do {
            ++it_;
        }
        while(is_invalid());
        return *this;
    }
References dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::is_invalid(), and dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::it_.
Referenced by dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::find_next_valid().
operator++() [2/2]
template<typename Container , typename Iter , typename FilterFunction = std::function<bool(typename Container::const_reference)>> filter_iterator_base & dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::operator++ (int x) inline
Definition at line 126 of file StructuredContainers.hpp.
{
        do {
            it_+=x;
        }
        while(is_invalid());
        return *this;
    }
References dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::is_invalid(), and dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::it_.
operator->()
template<typename Container , typename Iter , typename FilterFunction = std::function<bool(typename Container::const_reference)>> reference_type dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::operator-> () inline
Definition at line 95 of file StructuredContainers.hpp.
{ return *it_; }
References dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::it_.
operator==() [1/2]
template<typename Container , typename Iter , typename FilterFunction = std::function<bool(typename Container::const_reference)>> bool dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::operator== (const filter_iterator_base< Container, Iter, FilterFunction > & other) const inline
Definition at line 97 of file StructuredContainers.hpp.
{
        return it_ == other.it_;
    }
References dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::it_.
operator==() [2/2]
template<typename Container , typename Iter , typename FilterFunction = std::function<bool(typename Container::const_reference)>> bool dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::operator== (const iterator & other) const inline
Definition at line 102 of file StructuredContainers.hpp.
{
        return it_ == other;
    }
References dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::it_.
Member Data Documentation
container_
template<typename Container , typename Iter , typename FilterFunction = std::function<bool(typename Container::const_reference)>> Container& dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::container_ protected
Definition at line 158 of file StructuredContainers.hpp.
Referenced by dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::begin(), dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::end(), dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::getContainer(), and dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::is_invalid().
filter_func_
template<typename Container , typename Iter , typename FilterFunction = std::function<bool(typename Container::const_reference)>> FilterFunction dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::filter_func_ protected
reference to container
Definition at line 159 of file StructuredContainers.hpp.
Referenced by dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::begin(), dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::end(), dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::is_invalid(), and dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::operator()().
it_
template<typename Container , typename Iter , typename FilterFunction = std::function<bool(typename Container::const_reference)>> iterator dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::it_ mutable protected
Definition at line 160 of file StructuredContainers.hpp.
Referenced by dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::is_invalid(), dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::operator!=(), dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::operator*(), dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::operator++(), dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::operator->(), and dyno::internal::filter_iterator_base< Container, Iter, FilterFunction >::operator==().
The documentation for this struct was generated from the following file:
dynosam/include/dynosam/common/StructuredContainers.hpp