DynoSAM: dyno::CantorPairingFunction Struct Reference
dyno::CantorPairingFunction Struct Reference
#include <Symbols.hpp>
Public Types
using Pair = std::pair< std::uint64_t, std::uint64_t >
Static Public Member Functions
static std::uint64_t pair (const Pair &input)
static Pair depair (const std::uint64_t z)
Detailed Description
Definition at line 42 of file Symbols.hpp.
Member Typedef Documentation
Pair
using dyno::CantorPairingFunction::Pair = std::pair<std::uint64_t, std::uint64_t>
Definition at line 43 of file Symbols.hpp.
Member Function Documentation
depair()
CantorPairingFunction::Pair dyno::CantorPairingFunction::depair (const std::uint64_t z) static
Definition at line 166 of file Symbols.cc.
{
  std::uint64_t w =
      static_cast<std::uint64_t>(floor(((sqrt((z * 8) + 1)) - 1) / 2));
  std::uint64_t t = static_cast<std::uint64_t>((w * (w + 1)) / 2);
  std::uint64_t k2 = z - t;
  std::uint64_t k1 = w - k2;
  return std::make_pair(k1, k2);
}
Referenced by dyno::DynamicPointSymbol::DynamicPointSymbol(), and dyno::DynamicPointSymbol::recover().
pair()
std::uint64_t dyno::CantorPairingFunction::pair (const Pair & input) static
Definition at line 160 of file Symbols.cc.
{
  const auto k1 = (input.first);
  const auto k2 = (input.second);
  return ((k1 + k2) * (k1 + k2 + 1) / 2) + k2;
}
Referenced by dyno::DynamicPointSymbol::constructIndex().
The documentation for this struct was generated from the following files:
dynosam_opt/include/dynosam_opt/Symbols.hpp
dynosam_opt/src/Symbols.cc