DynoSAM: dyno::functional_keypoint Struct Reference
dyno::functional_keypoint Struct Reference
#include <Feature.hpp>
Static Public Member Functions
template<typename T = int>
static T u (const Keypoint &kp)
template<typename T = int>
static int v (const Keypoint &kp)
template<typename ImageWrapperType , typename AccessType = typename ImageWrapperType::OpenCVType>
static AccessType at (const Keypoint &kp, const ImageWrapper< ImageWrapperType > &image_wrapper)
template<typename AccessType >
static AccessType at (const Keypoint &kp, const cv::Mat &img)
Detailed Description
Definition at line 44 of file Feature.hpp.
Member Function Documentation
at() [1/2]
template<typename AccessType > static AccessType dyno::functional_keypoint::at (const Keypoint & kp, const cv::Mat & img) inline static
Definition at line 64 of file Feature.hpp.
{
    const int x = functional_keypoint::u<int>(kp);
    const int y = functional_keypoint::v<int>(kp);
    return img.at<AccessType>(y, x);
  }
at() [2/2]
template<typename ImageWrapperType , typename AccessType = typename ImageWrapperType::OpenCVType> static AccessType dyno::functional_keypoint::at (const Keypoint & kp, const ImageWrapper< ImageWrapperType > & image_wrapper) inline static
Definition at line 58 of file Feature.hpp.
{
    return at<AccessType>(kp, static_cast<const cv::Mat&>(image_wrapper));
  }
u()
template<typename T = int> static T dyno::functional_keypoint::u (const Keypoint & kp) inline static
Definition at line 46 of file Feature.hpp.
{
    return static_cast<T>(kp(0));
  }
Referenced by dyno::ExternalFlowFeatureTracker::constructStaticFeature(), dyno::KltFeatureTracker::detectFeatures(), dyno::FeatureTrackerBase::isWithinShrunkenImage(), dyno::FrontendInbuiltDisplayRos::processRGBDOutputpacket(), dyno::FeatureTracker::propogateMask(), dyno::FeatureTracker::trackDynamic(), dyno::KltFeatureTracker::trackPoints(), dyno::ExternalFlowFeatureTracker::trackStatic(), and dyno::OpticalFlowAndPoseOptimizer::updateFrameOutliersWithResult().
v()
template<typename T = int> static int dyno::functional_keypoint::v (const Keypoint & kp) inline static
Definition at line 51 of file Feature.hpp.
{
    return static_cast<T>(kp(1));
  }
Referenced by dyno::ExternalFlowFeatureTracker::constructStaticFeature(), dyno::KltFeatureTracker::detectFeatures(), dyno::FeatureTrackerBase::isWithinShrunkenImage(), dyno::FrontendInbuiltDisplayRos::processRGBDOutputpacket(), dyno::FeatureTracker::propogateMask(), dyno::FeatureTracker::trackDynamic(), dyno::KltFeatureTracker::trackPoints(), dyno::ExternalFlowFeatureTracker::trackStatic(), and dyno::OpticalFlowAndPoseOptimizer::updateFrameOutliersWithResult().
The documentation for this struct was generated from the following file:
dynosam/include/dynosam/frontend/vision/Feature.hpp