DynoSAM: dyno::DataProviderFactory Struct Reference
dyno::DataProviderFactory Struct Reference
#include <DataProviderFactory.hpp>
Static Public Member Functions
static DataProvider::Ptr Create (const std::string &dataset_folder_path, const std::string &params_folder_path, DatasetType dataset_type)
Detailed Description
Definition at line 47 of file DataProviderFactory.hpp.
Member Function Documentation
Create()
DataProvider::Ptr dyno::DataProviderFactory::Create (const std::string & dataset_folder_path, const std::string & params_folder_path, DatasetType dataset_type) static
Definition at line 54 of file DataProviderFactory.cc.
{
  if (dataset_type == DatasetType::KITTI) {
    LOG(INFO) << "Using KITTI dataset at path: " << dataset_folder_path;
    KittiDataLoader::Params params =
        KittiDataLoader::Params::fromYaml(params_folder_path);
    auto loader =
        std::make_shared<KittiDataLoader>(dataset_folder_path, params);
    loader->setStartingFrame(FLAGS_starting_frame);
    loader->setEndingFrame(FLAGS_ending_frame);
    return loader;
  } else if (dataset_type == DatasetType::VIRTUAL_KITTI) {
    LOG(INFO) << "Using Virtual KITTI dataset at path: " << dataset_folder_path;
    VirtualKittiDataLoader::Params params =
        VirtualKittiDataLoader::Params::fromYaml(params_folder_path);
    auto loader =
        std::make_shared<VirtualKittiDataLoader>(dataset_folder_path, params);
    loader->setStartingFrame(FLAGS_starting_frame);
    loader->setEndingFrame(FLAGS_ending_frame);
    return loader;
  } else if (dataset_type == DatasetType::CLUSTER) {
    LOG(INFO) << "Using Cluster (SLAM) dataset at path: "
              << dataset_folder_path;
    auto loader = std::make_shared<ClusterSlamDataLoader>(dataset_folder_path);
    loader->setStartingFrame(FLAGS_starting_frame);
    loader->setEndingFrame(FLAGS_ending_frame);
    return loader;
  } else if (dataset_type == DatasetType::OMD) {
    LOG(INFO) << "Using Oxford Multi-motion Dataset dataset at path: "
              << dataset_folder_path;
    auto loader = std::make_shared<OMDDataLoader>(dataset_folder_path);
    loader->setStartingFrame(FLAGS_starting_frame);
    loader->setEndingFrame(FLAGS_ending_frame);
    return loader;
  } else if (dataset_type == DatasetType::ARIA) {
    LOG(INFO) << "Using ARIA dataset at path: " << dataset_folder_path;
    auto loader = std::make_shared<ProjectARIADataLoader>(dataset_folder_path);
    loader->setStartingFrame(FLAGS_starting_frame);
    loader->setEndingFrame(FLAGS_ending_frame);
    return loader;
  } else if (dataset_type == DatasetType::TARTAN_AIR_SHIBUYA) {
    LOG(INFO) << "Using TARTAN_AIR_SHIBUYA dataset at path: "
              << dataset_folder_path;
    auto loader = std::make_shared<TartanAirShibuyaLoader>(dataset_folder_path);
    loader->setStartingFrame(FLAGS_starting_frame);
    loader->setEndingFrame(FLAGS_ending_frame);
    return loader;
  } else if (dataset_type == DatasetType::VIODE) {
    LOG(INFO) << "Using VIODE dataset at path: " << dataset_folder_path;
    auto loader = std::make_shared<ViodeLoader>(dataset_folder_path);
    loader->setStartingFrame(FLAGS_starting_frame);
    loader->setEndingFrame(FLAGS_ending_frame);
    return loader;
  } else {
    throw std::runtime_error(
        "Unable to construct Dataprovider - unknown dataset type: " +
        static_cast<int>(dataset_type));
  }
}
References dyno::ARIA, dyno::CLUSTER, dyno::KittiDataLoader::Params::fromYaml(), dyno::VirtualKittiDataLoader::Params::fromYaml(), dyno::KITTI, dyno::OMD, dyno::TARTAN_AIR_SHIBUYA, dyno::VIODE, and dyno::VIRTUAL_KITTI.
Referenced by dyno::DynoNode::createDatasetDataProvider().
The documentation for this struct was generated from the following files:
dynosam/include/dynosam/dataprovider/DataProviderFactory.hpp
dynosam/src/dataprovider/DataProviderFactory.cc