DynoSAM: dyno::ImageType::MotionMask Struct Reference
dyno::ImageType::MotionMask Struct Reference
#include <ImageTypes.hpp>
Static Public Member Functions
static void validate (const cv::Mat &input)
Expected opencv image type for MotionMask image type.
static std::string name ()
static cv::Mat toRGB (const ImageWrapper< MotionMask > &image)
Static Public Attributes
static constexpr int OpenCVType = CV_32SC1
Detailed Description
Definition at line 125 of file ImageTypes.hpp.
Member Function Documentation
name()
static std::string dyno::ImageType::MotionMask::name () inline static
Definition at line 128 of file ImageTypes.hpp.
{ return "MotionMask"; }
toRGB()
cv::Mat dyno::ImageType::MotionMask::toRGB (const ImageWrapper< MotionMask > & image) static
Definition at line 187 of file ImageTypes.cc.
{
  const cv::Mat motion_mask = image.clone();
  return utils::labelMaskToRGB(motion_mask, background_label);
}
References dyno::background_label, dyno::ImageWrapper< IMAGETYPE >::clone(), and dyno::utils::labelMaskToRGB().
Referenced by dyno::RGBDInstanceFrontendModule::nominalSpin().
validate()
void dyno::ImageType::MotionMask::validate (const cv::Mat & input) static
Expected opencv image type for MotionMask image type.
Definition at line 183 of file ImageTypes.cc.
{
  validateMask(input, name());
}
References dyno::validateMask().
Member Data Documentation
OpenCVType
constexpr int dyno::ImageType::MotionMask::OpenCVType = CV_32SC1 static constexpr
Definition at line 126 of file ImageTypes.hpp.
Referenced by dyno::VirtualKittiGenericInstanceSegFolder::loadSemanticInstanceUnchanged(), and dyno::validateMask().
The documentation for this struct was generated from the following files:
dynosam/include/dynosam/common/ImageTypes.hpp
dynosam/src/common/ImageTypes.cc