DynoSAM: dyno::ObjectNode< MEASUREMENT > Class Template Reference
dyno::ObjectNode< MEASUREMENT > Class Template Reference
Object node representing all object related data (j) over all time(k to K) in the map-graph.
#include <MapNodes.hpp>
Public Types
using Base = MapNodeBase< MEASUREMENT >
using This = ObjectNode< MEASUREMENT >
Public Member Functions
ObjectNode (const std::shared_ptr< Map< MEASUREMENT > > &map)
int getId () const override
Returns the object_id.
std::string toString () const override
FrameId getFirstSeenFrame () const
Get the first frame this object was observed in.
FrameId getLastSeenFrame () const
Get the last frame this object was observed in.
FrameNodePtrSet< MEASUREMENT > getSeenFrames () const
Get all the frame nodes that have observed this object.
FrameIds getSeenFrameIds () const
Get all the frame ids that have observed this object.
LandmarkNodePtrSet< MEASUREMENT > getLandmarksSeenAtFrame (FrameId frame_id) const
Get all the landmarks that observed this object at a particular frame id. This should be a subset of the dynamic_landmarks stored.
Public Member Functions inherited from dyno::MapNodeBase< MEASUREMENT >
MapNodeBase (const std::shared_ptr< Map< MEASUREMENT > > &map)
virtual ~MapNodeBase ()=default
virtual int getId () const =0
virtual std::string toString () const =0
Public Attributes
ObjectId object_id
Object labek (j)
LandmarkNodePtrSet< MEASUREMENT > dynamic_landmarks
All landmarks associated with the object over time.
Additional Inherited Members
Protected Attributes inherited from dyno::MapNodeBase< MEASUREMENT >
std::shared_ptr< Map< MEASUREMENT > > map_ptr_
Detailed Description
template<typename MEASUREMENT>
class dyno::ObjectNode< MEASUREMENT >
Object node representing all object related data (j) over all time(k to K) in the map-graph.
Template Parameters
MEASUREMENT
Definition at line 523 of file MapNodes.hpp.
Member Typedef Documentation
Base
template<typename MEASUREMENT > using dyno::ObjectNode< MEASUREMENT >::Base = MapNodeBase<MEASUREMENT>
Definition at line 525 of file MapNodes.hpp.
This
template<typename MEASUREMENT > using dyno::ObjectNode< MEASUREMENT >::This = ObjectNode<MEASUREMENT>
Definition at line 526 of file MapNodes.hpp.
Constructor & Destructor Documentation
ObjectNode()
template<typename MEASUREMENT > dyno::ObjectNode< MEASUREMENT >::ObjectNode (const std::shared_ptr< Map< MEASUREMENT > > & map) inline
Definition at line 529 of file MapNodes.hpp.
      : MapNodeBase<MEASUREMENT>(map) {}
Member Function Documentation
getFirstSeenFrame()
template<typename MEASUREMENT > FrameId dyno::ObjectNode< MEASUREMENT >::getFirstSeenFrame () const inline
Get the first frame this object was observed in.
Returns
FrameId
Definition at line 559 of file MapNodes.hpp.
{
    return getSeenFrames().template getFirstIndex<FrameId>();
  }
References dyno::ObjectNode< MEASUREMENT >::getSeenFrames().
Referenced by dyno::ObjectNode< MEASUREMENT >::toString().
getId()
template<typename MEASUREMENT > int dyno::ObjectNode< MEASUREMENT >::getId override virtual
Returns the object_id.
ObjectNode.
Returns
int
Implements dyno::MapNodeBase< MEASUREMENT >.
Definition at line 230 of file MapNodes-inl.hpp.
{
  return (int)object_id;
}
Referenced by dyno::ObjectNode< MEASUREMENT >::toString().
getLandmarksSeenAtFrame()
template<typename MEASUREMENT > LandmarkNodePtrSet< MEASUREMENT > dyno::ObjectNode< MEASUREMENT >::getLandmarksSeenAtFrame (FrameId frame_id) const
Get all the landmarks that observed this object at a particular frame id. This should be a subset of the dynamic_landmarks stored.
Parameters
frame_id FrameId
Returns
LandmarkNodePtrSet<MEASUREMENT>
Definition at line 250 of file MapNodes-inl.hpp.
{
  LandmarkNodePtrSet<MEASUREMENT> seen_lmks;
  for (const auto& lmk : dynamic_landmarks) {
    // all frames this lmk was seen in
    const FrameNodePtrSet<MEASUREMENT>& frames = lmk->getSeenFrames();
    // lmk was observed at this frame
    if (frames.find(frame_id) != frames.end()) {
      seen_lmks.insert(lmk);
    }
  }
  return seen_lmks;
}
References dyno::FastMapNodeSet< NODE >::find().
getLastSeenFrame()
template<typename MEASUREMENT > FrameId dyno::ObjectNode< MEASUREMENT >::getLastSeenFrame () const inline
Get the last frame this object was observed in.
Returns
FrameId
Definition at line 568 of file MapNodes.hpp.
{
    return getSeenFrames().template getLastIndex<FrameId>();
  }
References dyno::ObjectNode< MEASUREMENT >::getSeenFrames().
Referenced by dyno::ObjectNode< MEASUREMENT >::toString().
getSeenFrameIds()
template<typename MEASUREMENT > FrameIds dyno::ObjectNode< MEASUREMENT >::getSeenFrameIds
Get all the frame ids that have observed this object.
Returns
FrameIds
Definition at line 244 of file MapNodes-inl.hpp.
{
  return getSeenFrames().template collectIds<FrameId>();
}
getSeenFrames()
template<typename MEASUREMENT > FrameNodePtrSet< MEASUREMENT > dyno::ObjectNode< MEASUREMENT >::getSeenFrames
Get all the frame nodes that have observed this object.
Returns
FrameNodePtrSet<MEASUREMENT>
Definition at line 235 of file MapNodes-inl.hpp.
{
  FrameNodePtrSet<MEASUREMENT> seen_frames;
  for (const auto& lmks : dynamic_landmarks) {
    seen_frames.merge(lmks->getSeenFrames());
  }
  return seen_frames;
}
References dyno::FastMapNodeSet< NODE >::merge().
Referenced by dyno::ObjectNode< MEASUREMENT >::getFirstSeenFrame(), dyno::ObjectNode< MEASUREMENT >::getLastSeenFrame(), and dyno::ObjectNode< MEASUREMENT >::toString().
toString()
template<typename MEASUREMENT > std::string dyno::ObjectNode< MEASUREMENT >::toString () const inline override virtual
Implements dyno::MapNodeBase< MEASUREMENT >.
Definition at line 543 of file MapNodes.hpp.
{
    std::stringstream ss;
    ss << "Object Id: " << getId() << "\n";
    ss << "First seen: " << getFirstSeenFrame() << " last seen "
       << getLastSeenFrame() << "\n";
    ss << "Seen continuously: " << std::boolalpha
       << getSeenFrames().continuousAscendingIndex() << "\n";
    ss << "Total landmarks: " << dynamic_landmarks.size();
    return ss.str();
  }
References dyno::ObjectNode< MEASUREMENT >::dynamic_landmarks, dyno::ObjectNode< MEASUREMENT >::getFirstSeenFrame(), dyno::ObjectNode< MEASUREMENT >::getId(), dyno::ObjectNode< MEASUREMENT >::getLastSeenFrame(), and dyno::ObjectNode< MEASUREMENT >::getSeenFrames().
Member Data Documentation
dynamic_landmarks
template<typename MEASUREMENT > LandmarkNodePtrSet<MEASUREMENT> dyno::ObjectNode< MEASUREMENT >::dynamic_landmarks
All landmarks associated with the object over time.
Definition at line 535 of file MapNodes.hpp.
Referenced by dyno::ObjectNode< MEASUREMENT >::toString().
object_id
template<typename MEASUREMENT > ObjectId dyno::ObjectNode< MEASUREMENT >::object_id
Object labek (j)
Definition at line 533 of file MapNodes.hpp.
The documentation for this class was generated from the following files:
dynosam/include/dynosam/common/MapNodes.hpp
dynosam/include/dynosam/common/MapNodes-inl.hpp