DynoSAM: dyno::factor_graph_tools::travsersal Struct Reference
dyno::factor_graph_tools::travsersal Struct Reference
#include <FactorGraphTools.hpp>
Classes
struct Data
struct NodeVisitor
Definition of VISITOR_PRE struct as per gtsam::treeTraversal.
Public Types
template<typename CLQUE >
using CliqueVisitor = std::function< void(const boost::shared_ptr< CLQUE > &)>
Static Public Member Functions
template<typename CLQUE >
static void NoopCliqueVisitor (const boost::shared_ptr< CLQUE > &)
template<typename CLIQUE >
static void depthFirstTraversal (const gtsam::BayesTree< CLIQUE > &bayes_tree, const CliqueVisitor< CLIQUE > &post_op_visitor, const CliqueVisitor< CLIQUE > &pre_op_visitor)
Traverses a tree and calls the user defined visitor function at every pre-visit.
template<typename CLIQUE >
static void depthFirstTraversalEliminiationOrder (const gtsam::BayesTree< CLIQUE > &bayes_tree, const CliqueVisitor< CLIQUE > &visitor)
template<typename CLIQUE >
static gtsam::KeySet getEliminatonOrder (const gtsam::BayesTree< CLIQUE > &bayes_tree)
Gets keys in elimination order by traversing the tree in post-order.
template<typename CLIQUE >
static gtsam::KeySet getLeafKeys (const gtsam::BayesTree< CLIQUE > &bayes_tree)
Detailed Description
Definition at line 161 of file FactorGraphTools.hpp.
Member Typedef Documentation
CliqueVisitor
template<typename CLQUE > using dyno::factor_graph_tools::travsersal::CliqueVisitor = std::function<void(const boost::shared_ptr<CLQUE>&)>
Definition at line 164 of file FactorGraphTools.hpp.
Member Function Documentation
depthFirstTraversal()
template<typename CLIQUE > static void dyno::factor_graph_tools::travsersal::depthFirstTraversal (const gtsam::BayesTree< CLIQUE > & bayes_tree, const CliqueVisitor< CLIQUE > & post_op_visitor, const CliqueVisitor< CLIQUE > & pre_op_visitor) inline static
Traverses a tree and calls the user defined visitor function at every pre-visit.
Template Parameters
CLIQUE
Parameters
bayes_tree
pre_op_visitor
Definition at line 211 of file FactorGraphTools.hpp.
{
    Data rootdata;
    NodeVisitor<CLIQUE> post_visitor(post_op_visitor);
    NodeVisitor<CLIQUE> pre_visitor(pre_op_visitor);
    // TODO: see gtsam/inference/inference-inst.h where the elimate function is
    // actually called they have both post and pre order traversal and i'm not
    // sure which one is used... the bayes tree paper talkes about solving where
    // a parse up from the leaves is computed and then a pass down where the
    // optimal assignment is retrieved I believe that the pass up (which must be
    // post-order) is also equivalent to the elimination ordering
    // NOTE: not using threaded version
    // TbbOpenMPMixedScope threadLimiter; // Limits OpenMP threads since we're
    // mixing TBB and OpenMP treeTraversal::DepthFirstForestParallel(bayesTree,
    // rootData, preVisitor, postVisitor);
    gtsam::treeTraversal::DepthFirstForest(bayes_tree, rootdata, pre_visitor,
                                           post_visitor);
  }
Referenced by depthFirstTraversalEliminiationOrder().
depthFirstTraversalEliminiationOrder()
template<typename CLIQUE > static void dyno::factor_graph_tools::travsersal::depthFirstTraversalEliminiationOrder (const gtsam::BayesTree< CLIQUE > & bayes_tree, const CliqueVisitor< CLIQUE > & visitor) inline static
Definition at line 233 of file FactorGraphTools.hpp.
{
    depthFirstTraversal(bayes_tree, visitor, NoopCliqueVisitor<CLIQUE>);
  }
References depthFirstTraversal().
Referenced by getEliminatonOrder(), and getLeafKeys().
getEliminatonOrder()
template<typename CLIQUE > static gtsam::KeySet dyno::factor_graph_tools::travsersal::getEliminatonOrder (const gtsam::BayesTree< CLIQUE > & bayes_tree) inline static
Gets keys in elimination order by traversing the tree in post-order.
Definition at line 241 of file FactorGraphTools.hpp.
{
    gtsam::KeySet keys;
    CliqueVisitor<CLIQUE> visitor =
        [&keys](const boost::shared_ptr<CLIQUE>& clique) -> void {
      auto conditional = clique->conditional();
      // it is FACTOR::const_iterator
      for (auto it = conditional->beginFrontals();
           it != conditional->endFrontals(); it++) {
        keys.insert(*it);
      }
    };
    depthFirstTraversalEliminiationOrder(bayes_tree, visitor);
    return keys;
  }
References depthFirstTraversalEliminiationOrder().
getLeafKeys()
template<typename CLIQUE > static gtsam::KeySet dyno::factor_graph_tools::travsersal::getLeafKeys (const gtsam::BayesTree< CLIQUE > & bayes_tree) inline static
Definition at line 260 of file FactorGraphTools.hpp.
{
    gtsam::KeySet keys;
    CliqueVisitor<CLIQUE> visitor =
        [&keys](const boost::shared_ptr<CLIQUE>& clique) -> void {
      if (clique->children.size() == 0u) {
        auto conditional = clique->conditional();
        // it is FACTOR::const_iterator
        for (auto it = conditional->beginFrontals();
             it != conditional->endFrontals(); it++) {
          keys.insert(*it);
        }
      }
    };
    depthFirstTraversalEliminiationOrder(bayes_tree, visitor);
    return keys;
  }
References depthFirstTraversalEliminiationOrder().
NoopCliqueVisitor()
template<typename CLQUE > static void dyno::factor_graph_tools::travsersal::NoopCliqueVisitor (const boost::shared_ptr< CLQUE > &) inline static
Definition at line 168 of file FactorGraphTools.hpp.
{}
The documentation for this struct was generated from the following file:
dynosam/include/dynosam/backend/FactorGraphTools.hpp