DynoSAM: dyno::ImageType::RGBMono Struct Reference
dyno::ImageType::RGBMono Struct Reference
Defines the input RGB/greyscale (mono) image.
#include <ImageTypes.hpp>
Static Public Member Functions
static void validate (const cv::Mat &input)
static std::string name ()
static cv::Mat toRGB (const ImageWrapper< RGBMono > &image)
static cv::Mat toMono (const ImageWrapper< RGBMono > &image)
Detailed Description
Defines the input RGB/greyscale (mono) image.
Definition at line 167 of file ImageTypes.hpp.
Member Function Documentation
name()
static std::string dyno::ImageType::RGBMono::name () inline static
Definition at line 169 of file ImageTypes.hpp.
{ return "RGBMono"; }
toMono()
cv::Mat dyno::ImageType::RGBMono::toMono (const ImageWrapper< RGBMono > & image) static
Definition at line 119 of file ImageTypes.cc.
{
  return RGBMonoToMono(image);
}
References dyno::RGBMonoToMono().
Referenced by dyno::StereoMatcher::disparityRectifiedReconstruction(), dyno::KltFeatureTracker::equalizeImage(), dyno::FeatureTracker::stereoTrack(), dyno::FeatureTracker::trackDynamicKLT(), and dyno::ExternalFlowFeatureTracker::trackStatic().
toRGB()
cv::Mat dyno::ImageType::RGBMono::toRGB (const ImageWrapper< RGBMono > & image) static
Definition at line 115 of file ImageTypes.cc.
{
  return RGBMonoToRGB(image);
}
References dyno::RGBMonoToRGB().
Referenced by dyno::RGBDInstanceFrontendModule::nominalSpin().
validate()
void dyno::ImageType::RGBMono::validate (const cv::Mat & input) static
Definition at line 111 of file ImageTypes.cc.
{
  validateRGBMono(input);
}
References dyno::validateRGBMono().
The documentation for this struct was generated from the following files:
dynosam_cv/include/dynosam_cv/ImageTypes.hpp
dynosam_cv/src/ImageTypes.cc