DynoSAM: dyno::VisualMeasurementStatus< T > Struct Template Reference
dyno::VisualMeasurementStatus< T > Struct Template Reference
Defines a single visual measurement with tracking label, object id, frame id and measurement.
#include <SensorModels.hpp>
Public Types
using Base = TrackedValueStatus< T >
Public Types inherited from dyno::TrackedValueStatus< T >
using Value = T
using This = TrackedValueStatus< Value >
Public Member Functions
VisualMeasurementStatus ()=default
Default constructor for IO.
VisualMeasurementStatus (const Base &base)
Construct a new Visual Measurement Status from the Base type.
VisualMeasurementStatus (const T &m, FrameId frame_id, TrackletId tracklet_id, ObjectId label, ReferenceFrame reference_frame)
Construct a new Visual Measurement Status object.
Public Member Functions inherited from dyno::TrackedValueStatus< T >
TrackedValueStatus ()
TrackedValueStatus (const Value &value, FrameId frame_id, TrackletId tracklet_id, ObjectId label, ReferenceFrame reference_frame)
virtual ~TrackedValueStatus ()=default
TrackedValueStatus< U > asType () const
Allows the casting of the internal value type to another using static casting.
const Value & value () const
Get value. Const version.
Value & value ()
Get value. Reference version.
TrackletId trackletId () const
Get tracklet id (i) for this status.
ObjectId objectId () const
Get object id (j) for this status.
FrameId frameId () const
Get frame id (k) for this status.
const ReferenceFrame & referenceFrame () const
Get the reference frame the value is in. Const version.
ReferenceFrame & referenceFrame ()
Get the reference frame the value is in.
ReferenceFrameValue< Value > & referenceFrameValue ()
Get the full reference frame and value.
const ReferenceFrameValue< Value > & referenceFrameValue () const
Get the full reference frame and value. Const version.
bool operator== (const This &other) const
bool isStatic () const
Returns true if the object lavel is equal to dyno::background_label.
bool isTimeInvariant () const
Returns true if frame_id is equal to MeaninglessFrame (e.g. std::numeric_limits<FrameId>::quiet_NaN) and should indicatate that the value represented by this TrackedValueStatus is time-invariant, e.g. for a static point which does not change overtime.
Static Public Member Functions
static VisualMeasurementStatus Static (const T &m, FrameId frame_id, TrackletId tracklet_id, ReferenceFrame reference_frame)
Constructs a static Visual Measurement Status.
static VisualMeasurementStatus Dynamic (const T &m, FrameId frame_id, TrackletId tracklet_id, ObjectId label, ReferenceFrame reference_frame)
Constructs a dynamic Visual Measurement Status.
static VisualMeasurementStatus StaticInLocal (const T &m, FrameId frame_id, TrackletId tracklet_id)
Constructs a static Visual Measurement Status in the local frame.
static VisualMeasurementStatus DynamicInLocal (const T &m, FrameId frame_id, TrackletId tracklet_id, ObjectId label)
Constructs a dynamic Visual Measurement Status in the local frame.
static VisualMeasurementStatus StaticInGlobal (const T &m, FrameId frame_id, TrackletId tracklet_id)
Constructs a static Visual Measurement Status in the global frame.
static VisualMeasurementStatus DynamicInGLobal (const T &m, FrameId frame_id, TrackletId tracklet_id, ObjectId label)
Constructs a dynamic Visual Measurement Status in the global frame.
Static Public Attributes
static constexpr int dim = gtsam::traits<T>::dimension
dimension of the measurement. Must have gtsam::dimension traits
Static Public Attributes inherited from dyno::TrackedValueStatus< T >
static constexpr auto MeaninglessFrame
Additional Inherited Members
Protected Attributes inherited from dyno::TrackedValueStatus< T >
ReferenceFrameValue< Value > value_
FrameId frame_id_
TrackletId tracklet_id_
ObjectId label_
Detailed Description
template<typename T>
struct dyno::VisualMeasurementStatus< T >
Defines a single visual measurement with tracking label, object id, frame id and measurement.
Template Parameters
T
Definition at line 54 of file SensorModels.hpp.
Member Typedef Documentation
Base
template<typename T > using dyno::VisualMeasurementStatus< T >::Base = TrackedValueStatus<T>
Definition at line 55 of file SensorModels.hpp.
Constructor & Destructor Documentation
VisualMeasurementStatus() [1/3]
template<typename T > dyno::VisualMeasurementStatus< T >::VisualMeasurementStatus () default
Default constructor for IO.
Referenced by dyno::VisualMeasurementStatus< T >::Dynamic(), dyno::VisualMeasurementStatus< T >::DynamicInGLobal(), dyno::VisualMeasurementStatus< T >::DynamicInLocal(), dyno::VisualMeasurementStatus< T >::Static(), dyno::VisualMeasurementStatus< T >::StaticInGlobal(), and dyno::VisualMeasurementStatus< T >::StaticInLocal().
VisualMeasurementStatus() [2/3]
template<typename T > dyno::VisualMeasurementStatus< T >::VisualMeasurementStatus (const Base & base) inline
Construct a new Visual Measurement Status from the Base type.
Parameters
base TrackedValueStatus<T>
Definition at line 68 of file SensorModels.hpp.
      : VisualMeasurementStatus(base.value(), base.frameId(), base.trackletId(),
                                base.objectId(), base.referenceFrame()) {}
VisualMeasurementStatus() [3/3]
template<typename T > dyno::VisualMeasurementStatus< T >::VisualMeasurementStatus (const T & m, FrameId frame_id, TrackletId tracklet_id, ObjectId label, ReferenceFrame reference_frame) inline
Construct a new Visual Measurement Status object.
Parameters
m const T&
frame_id FrameId
tracklet_id TrackletId
label ObjectId
reference_frame ReferenceFrame
Definition at line 81 of file SensorModels.hpp.
      : Base(m, frame_id, tracklet_id, label, reference_frame) {}
Member Function Documentation
Dynamic()
template<typename T > static VisualMeasurementStatus dyno::VisualMeasurementStatus< T >::Dynamic (const T & m, FrameId frame_id, TrackletId tracklet_id, ObjectId label, ReferenceFrame reference_frame) inline static
Constructs a dynamic Visual Measurement Status.
Parameters
m const T&
frame_id FrameId
tracklet_id TrackletId
reference_frame ReferenceFrame
Returns
VisualMeasurementStatus
Definition at line 110 of file SensorModels.hpp.
{
    CHECK(label != background_label);
    return VisualMeasurementStatus(m, frame_id, tracklet_id, label,
                                   reference_frame);
  }
References dyno::background_label, and dyno::VisualMeasurementStatus< T >::VisualMeasurementStatus().
DynamicInGLobal()
template<typename T > static VisualMeasurementStatus dyno::VisualMeasurementStatus< T >::DynamicInGLobal (const T & m, FrameId frame_id, TrackletId tracklet_id, ObjectId label) inline static
Constructs a dynamic Visual Measurement Status in the global frame.
Parameters
m const T&
frame_id FrameId
tracklet_id TrackletId
Returns
VisualMeasurementStatus
Definition at line 173 of file SensorModels.hpp.
{
    CHECK(label != background_label);
    return VisualMeasurementStatus(m, frame_id, tracklet_id, label,
                                   ReferenceFrame::GLOBAL);
  }
References dyno::background_label, dyno::GLOBAL, and dyno::VisualMeasurementStatus< T >::VisualMeasurementStatus().
Referenced by dyno::HybridFormulation::calculateObjectCentroid(), dyno::AccessorT< MAP >::getDynamicLandmarkEstimates(), and dyno::HybridAccessor::getDynamicLandmarkEstimates().
DynamicInLocal()
template<typename T > static VisualMeasurementStatus dyno::VisualMeasurementStatus< T >::DynamicInLocal (const T & m, FrameId frame_id, TrackletId tracklet_id, ObjectId label) inline static
Constructs a dynamic Visual Measurement Status in the local frame.
Parameters
m const T&
frame_id FrameId
tracklet_id TrackletId
Returns
VisualMeasurementStatus
Definition at line 141 of file SensorModels.hpp.
{
    CHECK(label != background_label);
    return VisualMeasurementStatus(m, frame_id, tracklet_id, label,
                                   ReferenceFrame::LOCAL);
  }
References dyno::background_label, dyno::LOCAL, and dyno::VisualMeasurementStatus< T >::VisualMeasurementStatus().
Referenced by dyno::HybridAccessor::getLocalDynamicLandmarkEstimates().
Static()
template<typename T > static VisualMeasurementStatus dyno::VisualMeasurementStatus< T >::Static (const T & m, FrameId frame_id, TrackletId tracklet_id, ReferenceFrame reference_frame) inline static
Constructs a static Visual Measurement Status.
Parameters
m const T&
frame_id FrameId
tracklet_id TrackletId
reference_frame ReferenceFrame
Returns
VisualMeasurementStatus
Definition at line 94 of file SensorModels.hpp.
{
    return VisualMeasurementStatus(m, frame_id, tracklet_id, background_label,
                                   reference_frame);
  }
References dyno::background_label, and dyno::VisualMeasurementStatus< T >::VisualMeasurementStatus().
StaticInGlobal()
template<typename T > static VisualMeasurementStatus dyno::VisualMeasurementStatus< T >::StaticInGlobal (const T & m, FrameId frame_id, TrackletId tracklet_id) inline static
Constructs a static Visual Measurement Status in the global frame.
Parameters
m const T&
frame_id FrameId
tracklet_id TrackletId
Returns
VisualMeasurementStatus
Definition at line 158 of file SensorModels.hpp.
{
    return VisualMeasurementStatus(m, frame_id, tracklet_id, background_label,
                                   ReferenceFrame::GLOBAL);
  }
References dyno::background_label, dyno::GLOBAL, and dyno::VisualMeasurementStatus< T >::VisualMeasurementStatus().
Referenced by dyno::AccessorT< MAP >::getFullStaticMap(), and dyno::AccessorT< MAP >::getStaticLandmarkEstimates().
StaticInLocal()
template<typename T > static VisualMeasurementStatus dyno::VisualMeasurementStatus< T >::StaticInLocal (const T & m, FrameId frame_id, TrackletId tracklet_id) inline static
Constructs a static Visual Measurement Status in the local frame.
Parameters
m const T&
frame_id FrameId
tracklet_id TrackletId
Returns
VisualMeasurementStatus
Definition at line 126 of file SensorModels.hpp.
{
    return VisualMeasurementStatus(m, frame_id, tracklet_id, background_label,
                                   ReferenceFrame::LOCAL);
  }
References dyno::background_label, dyno::LOCAL, and dyno::VisualMeasurementStatus< T >::VisualMeasurementStatus().
Member Data Documentation
dim
template<typename T > constexpr int dyno::VisualMeasurementStatus< T >::dim = gtsam::traits<T>::dimension static constexpr
dimension of the measurement. Must have gtsam::dimension traits
Definition at line 58 of file SensorModels.hpp.
The documentation for this struct was generated from the following file:
dynosam_common/include/dynosam_common/SensorModels.hpp