DynoSAM: rclcpp::TypeAdapter< dyno::CameraParams, sensor_msgs::msg::CameraInfo > Struct Reference
rclcpp::TypeAdapter< dyno::CameraParams, sensor_msgs::msg::CameraInfo > Struct Reference
#include <CameraParamsAdaptor.hpp>
Public Types
using is_specialized = std::true_type
using custom_type = dyno::CameraParams
using ros_message_type = sensor_msgs::msg::CameraInfo
Static Public Member Functions
static void convert_to_ros_message (const custom_type &source, ros_message_type &destination)
static void convert_to_custom (const ros_message_type &source, custom_type &destination)
Detailed Description
Definition at line 40 of file CameraParamsAdaptor.hpp.
Member Typedef Documentation
custom_type
using rclcpp::TypeAdapter< dyno::CameraParams, sensor_msgs::msg::CameraInfo >::custom_type = dyno::CameraParams
Definition at line 42 of file CameraParamsAdaptor.hpp.
is_specialized
using rclcpp::TypeAdapter< dyno::CameraParams, sensor_msgs::msg::CameraInfo >::is_specialized = std::true_type
Definition at line 41 of file CameraParamsAdaptor.hpp.
ros_message_type
using rclcpp::TypeAdapter< dyno::CameraParams, sensor_msgs::msg::CameraInfo >::ros_message_type = sensor_msgs::msg::CameraInfo
Definition at line 43 of file CameraParamsAdaptor.hpp.
Member Function Documentation
convert_to_custom()
static void rclcpp::TypeAdapter< dyno::CameraParams, sensor_msgs::msg::CameraInfo >::convert_to_custom (const ros_message_type & source, custom_type & destination) inline static
Definition at line 66 of file CameraParamsAdaptor.hpp.
{
    // bit gross but cv::Mat does not accept a const void* for data (which
    // source.k.data()) is so to ensure the data is safe (ie. rather than doing
    // a const conversion), I decide to copy the data into std::vector and then
    // copy into cv::Mat. this is inefficient but this conversion happens so
    // rarely and the data pakcet is tiny...
    std::vector<double> k_vector(source.k.begin(), source.k.end());
    cv::Mat K(3, 3, CV_64F, std::data(k_vector));
    dyno::CameraParams::IntrinsicsCoeffs intrinsics;
    // TODO: should make this a constructor...
    dyno::CameraParams::convertKMatrixToIntrinsicsCoeffs(K, intrinsics);
    dyno::CameraParams::DistortionCoeffs distortion(source.d.begin(),
                                                    source.d.end());
    cv::Size size(source.width, source.height);
    const std::string& distortion_model = source.distortion_model;
    destination =
        dyno::CameraParams(intrinsics, distortion, size, distortion_model);
  }
References dyno::CameraParams::convertKMatrixToIntrinsicsCoeffs().
convert_to_ros_message()
static void rclcpp::TypeAdapter< dyno::CameraParams, sensor_msgs::msg::CameraInfo >::convert_to_ros_message (const custom_type & source, ros_message_type & destination) inline static
Definition at line 45 of file CameraParamsAdaptor.hpp.
{
    // intrisincs
    const cv::Mat& K = source.getCameraMatrix();
    std::copy(K.begin<double>(), K.end<double>(), destination.k.begin());
    // distortion
    const cv::Mat& D = source.getDistortionCoeffs();
    destination.d.resize(D.total());
    destination.d = std::vector<double>(D.begin<double>(), D.end<double>());
    destination.height = source.ImageHeight();
    destination.width = source.ImageWidth();
    std::string camera_model;
    CHECK(dyno::CameraParams::distortionModelToString(
        source.getDistortionModel(), destination.distortion_model,
        camera_model));
    (void)camera_model;
  }
References dyno::CameraParams::distortionModelToString(), dyno::CameraParams::getCameraMatrix(), dyno::CameraParams::getDistortionCoeffs(), dyno::CameraParams::getDistortionModel(), dyno::CameraParams::ImageHeight(), and dyno::CameraParams::ImageWidth().
The documentation for this struct was generated from the following file:
dynosam_ros/include/dynosam_ros/adaptors/CameraParamsAdaptor.hpp