DynoSAM: dyno::RGBDInstanceOutputPacket Struct Reference
dyno::RGBDInstanceOutputPacket Struct Reference
#include <RGBDInstance-Definitions.hpp>
Public Member Functions
RGBDInstanceOutputPacket (const StatusKeypointVector &static_keypoint_measurements, const StatusKeypointVector &dynamic_keypoint_measurements, const StatusLandmarkVector &static_landmarks, const StatusLandmarkVector &dynamic_landmarks, const gtsam::Pose3 T_world_camera, const Timestamp timestamp, const FrameId frame_id, const MotionEstimateMap &estimated_motions, const ObjectPoseMap propogated_object_poses={}, const gtsam::Pose3Vector camera_poses={}, const Camera::Ptr camera=nullptr, const GroundTruthInputPacket::Optional &gt_packet=std::nullopt, const DebugImagery::Optional &debug_imagery=std::nullopt)
Vector of ego-motion poses (drawn everytime)
GenericTrackedStatusVector< LandmarkKeypointStatus > collectStaticLandmarkKeypointMeasurements () const
GenericTrackedStatusVector< LandmarkKeypointStatus > collectDynamicLandmarkKeypointMeasurements () const
bool hasObject (ObjectId object_id) const
Checks if an object id exists within the frontend output.
const pcl::PointCloud< pcl::PointXYZRGB > & getDynamicObjectPointCloud (ObjectId object_id) const
const ObjectBBX & getDynamicObjectBBX (ObjectId object_id) const
const CloudPerObject & getObjectClouds () const
const BbxPerObject & getObjectBbxes () const
bool operator== (const RGBDInstanceOutputPacket &other) const
Public Member Functions inherited from dyno::FrontendOutputPacketBase
FrontendOutputPacketBase (const FrontendType frontend_type, const StatusKeypointVector &static_keypoint_measurements, const StatusKeypointVector &dynamic_keypoint_measurements, const gtsam::Pose3 &T_world_camera, const Timestamp timestamp, const FrameId frame_id, const Camera::Ptr camera=nullptr, const GroundTruthInputPacket::Optional &gt_packet=std::nullopt, const DebugImagery::Optional &debug_imagery=std::nullopt)
virtual ~FrontendOutputPacketBase ()
bool hasCamera () const
Timestamp getTimestamp () const
FrameId getFrameId () const
bool operator== (const FrontendOutputPacketBase &other) const
Public Attributes
const StatusLandmarkVector static_landmarks_
const StatusLandmarkVector dynamic_landmarks_
in the camera frame
const MotionEstimateMap estimated_motions_
in the camera frame
const ObjectPoseMap propogated_object_poses_
Estimated motions in the world frame.
const gtsam::Pose3Vector camera_poses_
Public Attributes inherited from dyno::FrontendOutputPacketBase
const FrontendType frontend_type_
const StatusKeypointVector static_keypoint_measurements_
const StatusKeypointVector dynamic_keypoint_measurements_
const gtsam::Pose3 T_world_camera_
const Timestamp timestamp_
const FrameId frame_id_
const Camera::Ptr camera_
const GroundTruthInputPacket::Optional gt_packet_
const DebugImagery::Optional debug_imagery_
Private Attributes
CloudPerObject object_clouds_
BbxPerObject object_bbxes_
Detailed Description
Definition at line 49 of file RGBDInstance-Definitions.hpp.
Constructor & Destructor Documentation
RGBDInstanceOutputPacket()
dyno::RGBDInstanceOutputPacket::RGBDInstanceOutputPacket (const StatusKeypointVector & static_keypoint_measurements, const StatusKeypointVector & dynamic_keypoint_measurements, const StatusLandmarkVector & static_landmarks, const StatusLandmarkVector & dynamic_landmarks, const gtsam::Pose3 T_world_camera, const Timestamp timestamp, const FrameId frame_id, const MotionEstimateMap & estimated_motions, const ObjectPoseMap propogated_object_poses = {}, const gtsam::Pose3Vector camera_poses = {}, const Camera::Ptr camera = nullptr, const GroundTruthInputPacket::Optional & gt_packet = std::nullopt, const DebugImagery::Optional & debug_imagery = std::nullopt) inline
Vector of ego-motion poses (drawn everytime)
Definition at line 62 of file RGBDInstance-Definitions.hpp.
                                                    {},
      const gtsam::Pose3Vector camera_poses = {},
      const Camera::Ptr camera = nullptr,
      const GroundTruthInputPacket::Optional& gt_packet = std::nullopt,
      const DebugImagery::Optional& debug_imagery = std::nullopt)
      : FrontendOutputPacketBase(
            FrontendType::kRGBD, static_keypoint_measurements,
            dynamic_keypoint_measurements, T_world_camera, timestamp, frame_id,
            camera, gt_packet, debug_imagery),
        static_landmarks_(static_landmarks),
        dynamic_landmarks_(dynamic_landmarks),
        estimated_motions_(estimated_motions),
        propogated_object_poses_(propogated_object_poses),
        camera_poses_(camera_poses) {
    // they need to be the same size as we expect a 1-to-1 relation between the
    // keypoint and the landmark (which acts as an initalisation point)
    CHECK_EQ(static_landmarks_.size(), static_keypoint_measurements_.size());
    CHECK_EQ(dynamic_landmarks_.size(), dynamic_keypoint_measurements_.size());
    object_clouds_ = groupObjectCloud(dynamic_landmarks_, T_world_camera_);
    for (const auto& [object_id, this_object_cloud] : object_clouds_) {
      pcl::PointCloud<pcl::PointXYZRGB>::Ptr obj_cloud_ptr =
          pcl::make_shared<pcl::PointCloud<pcl::PointXYZRGB>>(
              this_object_cloud);
      // ObjectBBX this_object_bbx = findOBBFromCloud(obj_cloud_ptr);
      // TODO: currently axis-aligned bounding box (not orientated bbx)
      ObjectBBX this_object_bbx =
          findAABBFromCloud<pcl::PointXYZRGB>(obj_cloud_ptr);
      object_bbxes_.insert2(object_id, this_object_bbx);
    }
  }
Member Function Documentation
collectDynamicLandmarkKeypointMeasurements()
GenericTrackedStatusVector< LandmarkKeypointStatus > dyno::RGBDInstanceOutputPacket::collectDynamicLandmarkKeypointMeasurements () const
Definition at line 74 of file RGBDInstance-Definitions.cc.
{
  return collectLandmarkKeypointMeasurementsHelper(
      dynamic_landmarks_, dynamic_keypoint_measurements_);
}
References dyno::collectLandmarkKeypointMeasurementsHelper(), dyno::FrontendOutputPacketBase::dynamic_keypoint_measurements_, and dynamic_landmarks_.
collectStaticLandmarkKeypointMeasurements()
GenericTrackedStatusVector< LandmarkKeypointStatus > dyno::RGBDInstanceOutputPacket::collectStaticLandmarkKeypointMeasurements () const
Definition at line 69 of file RGBDInstance-Definitions.cc.
{
  return collectLandmarkKeypointMeasurementsHelper(
      static_landmarks_, static_keypoint_measurements_);
}
References dyno::collectLandmarkKeypointMeasurementsHelper(), dyno::FrontendOutputPacketBase::static_keypoint_measurements_, and static_landmarks_.
getDynamicObjectBBX()
const ObjectBBX & dyno::RGBDInstanceOutputPacket::getDynamicObjectBBX (ObjectId object_id) const inline
Definition at line 128 of file RGBDInstance-Definitions.hpp.
{
    CHECK(hasObject(object_id))
        << "Cannot get dynamic object bbx as id missing: " << object_id;
    return object_bbxes_.at(object_id);
  }
References hasObject(), and object_bbxes_.
getDynamicObjectPointCloud()
const pcl::PointCloud< pcl::PointXYZRGB > & dyno::RGBDInstanceOutputPacket::getDynamicObjectPointCloud (ObjectId object_id) const inline
Definition at line 121 of file RGBDInstance-Definitions.hpp.
{
    CHECK(hasObject(object_id))
        << "Cannot get dynamic object as id missing: " << object_id;
    return object_clouds_.at(object_id);
  }
References hasObject(), and object_clouds_.
getObjectBbxes()
const BbxPerObject & dyno::RGBDInstanceOutputPacket::getObjectBbxes () const inline
Definition at line 136 of file RGBDInstance-Definitions.hpp.
{ return object_bbxes_; }
References object_bbxes_.
getObjectClouds()
const CloudPerObject & dyno::RGBDInstanceOutputPacket::getObjectClouds () const inline
Definition at line 134 of file RGBDInstance-Definitions.hpp.
{ return object_clouds_; }
References object_clouds_.
hasObject()
bool dyno::RGBDInstanceOutputPacket::hasObject (ObjectId object_id) const inline
Checks if an object id exists within the frontend output.
Actually looks in the map of objectids -> object_clouds_, does not check the status keypoints/landmarks for this id.
Parameters
object_id
Returns
true
false
Definition at line 117 of file RGBDInstance-Definitions.hpp.
{
    return object_clouds_.exists(object_id);
  }
References object_clouds_.
Referenced by getDynamicObjectBBX(), and getDynamicObjectPointCloud().
operator==()
bool dyno::RGBDInstanceOutputPacket::operator== (const RGBDInstanceOutputPacket & other) const inline
Definition at line 138 of file RGBDInstance-Definitions.hpp.
{
    return static_cast<const FrontendOutputPacketBase&>(*this) ==
               static_cast<const FrontendOutputPacketBase&>(other) &&
           static_landmarks_ == other.static_landmarks_ &&
           dynamic_landmarks_ == other.dynamic_landmarks_;
    // TODO: no estimated_motions_, propogated_object_poses_... becuase of
    // gtsam...
  }
References dynamic_landmarks_, and static_landmarks_.
Member Data Documentation
camera_poses_
const gtsam::Pose3Vector dyno::RGBDInstanceOutputPacket::camera_poses_
Propogated poses using the esimtate from the frontend
Definition at line 60 of file RGBDInstance-Definitions.hpp.
dynamic_landmarks_
const StatusLandmarkVector dyno::RGBDInstanceOutputPacket::dynamic_landmarks_
in the camera frame
Definition at line 54 of file RGBDInstance-Definitions.hpp.
Referenced by collectDynamicLandmarkKeypointMeasurements(), and operator==().
estimated_motions_
const MotionEstimateMap dyno::RGBDInstanceOutputPacket::estimated_motions_
in the camera frame
Definition at line 56 of file RGBDInstance-Definitions.hpp.
object_bbxes_
BbxPerObject dyno::RGBDInstanceOutputPacket::object_bbxes_ private
Point clouds per object extracted from dynamic_landmarks_ in the world frame
Definition at line 150 of file RGBDInstance-Definitions.hpp.
Referenced by getDynamicObjectBBX(), and getObjectBbxes().
object_clouds_
CloudPerObject dyno::RGBDInstanceOutputPacket::object_clouds_ private
Definition at line 148 of file RGBDInstance-Definitions.hpp.
Referenced by getDynamicObjectPointCloud(), getObjectClouds(), and hasObject().
propogated_object_poses_
const ObjectPoseMap dyno::RGBDInstanceOutputPacket::propogated_object_poses_
Estimated motions in the world frame.
Definition at line 57 of file RGBDInstance-Definitions.hpp.
static_landmarks_
const StatusLandmarkVector dyno::RGBDInstanceOutputPacket::static_landmarks_
Definition at line 53 of file RGBDInstance-Definitions.hpp.
Referenced by collectStaticLandmarkKeypointMeasurements(), and operator==().
The documentation for this struct was generated from the following files:
dynosam/include/dynosam/frontend/RGBDInstance-Definitions.hpp
dynosam/src/frontend/RGBDInstance-Definitions.cc