DynoSAM: dyno::VirtualKittiDataLoader::Params Struct Reference
dyno::VirtualKittiDataLoader::Params Struct Reference
#include <VirtualKittiDataProvider.hpp>
Static Public Member Functions
static Params fromYaml (const std::string &params_folder)
Public Attributes
std::string scene
std::string scene_type
MaskType mask_type = MaskType::MOTION
Detailed Description
Definition at line 60 of file VirtualKittiDataProvider.hpp.
Member Function Documentation
fromYaml()
VirtualKittiDataLoader::Params dyno::VirtualKittiDataLoader::Params::fromYaml (const std::string & params_folder) static
Definition at line 958 of file VirtualKittidataProvider.cc.
{
    YamlParser yaml_parser(params_folder + "DatasetParams.yaml");
    Params params;
    std::string mask_type;
    yaml_parser.getYamlParam("mask_type", &mask_type);
    params.mask_type = maskTypeFromString(mask_type);
    yaml_parser.getYamlParam("scene", &params.scene);
    yaml_parser.getYamlParam("scene_type", &params.scene_type);
    return params;
}
References dyno::YamlParser::getYamlParam(), mask_type, dyno::maskTypeFromString(), scene, and scene_type.
Referenced by dyno::DataProviderFactory::Create().
Member Data Documentation
mask_type
MaskType dyno::VirtualKittiDataLoader::Params::mask_type = MaskType::MOTION
Definition at line 63 of file VirtualKittiDataProvider.hpp.
Referenced by fromYaml(), and dyno::VirtualKittiDataLoader::VirtualKittiDataLoader().
scene
std::string dyno::VirtualKittiDataLoader::Params::scene
Definition at line 61 of file VirtualKittiDataProvider.hpp.
Referenced by fromYaml(), and dyno::VirtualKittiDataLoader::VirtualKittiDataLoader().
scene_type
std::string dyno::VirtualKittiDataLoader::Params::scene_type
Definition at line 62 of file VirtualKittiDataProvider.hpp.
Referenced by fromYaml(), and dyno::VirtualKittiDataLoader::VirtualKittiDataLoader().
The documentation for this struct was generated from the following files:
dynosam/include/dynosam/dataprovider/VirtualKittiDataProvider.hpp
dynosam/src/dataprovider/VirtualKittidataProvider.cc