DynoSAM: dyno::FrontendParams Struct Reference
dyno::FrontendParams Struct Reference
#include <FrontendParams.hpp>
Public Attributes
double scene_flow_magnitude = 0.12
double scene_flow_percentage = 0.5
double max_background_depth = 40.0
double max_object_depth = 25.0
bool use_ego_motion_pnp = true
bool use_object_motion_pnp = true
bool refine_camera_pose_with_joint_of = true
ObjectMotionSovlerF2F::Params object_motion_solver_params
EgoMotionSolver::Params ego_motion_solver_params = EgoMotionSolver::Params()
TrackerParams tracker_params = TrackerParams()
ImageTracksParams image_tracks_vis_params = ImageTracksParams()
ImuParams imu_params = ImuParams()
Detailed Description
Definition at line 43 of file FrontendParams.hpp.
Member Data Documentation
ego_motion_solver_params
EgoMotionSolver::Params dyno::FrontendParams::ego_motion_solver_params = EgoMotionSolver::Params()
Definition at line 68 of file FrontendParams.hpp.
image_tracks_vis_params
ImageTracksParams dyno::FrontendParams::image_tracks_vis_params = ImageTracksParams()
Definition at line 71 of file FrontendParams.hpp.
imu_params
ImuParams dyno::FrontendParams::imu_params = ImuParams()
Definition at line 72 of file FrontendParams.hpp.
Referenced by dyno::DynoPipelineManager::DynoPipelineManager().
max_background_depth
double dyno::FrontendParams::max_background_depth = 40.0
Definition at line 49 of file FrontendParams.hpp.
Referenced by dyno::FeatureTracker::track().
max_object_depth
double dyno::FrontendParams::max_object_depth = 25.0
Definition at line 50 of file FrontendParams.hpp.
Referenced by dyno::FeatureTracker::track().
object_motion_solver_params
ObjectMotionSovlerF2F::Params dyno::FrontendParams::object_motion_solver_params
Initial value:
=
      ObjectMotionSovlerF2F::Params()
Definition at line 66 of file FrontendParams.hpp.
Referenced by dyno::RGBDInstanceFrontendModule::RGBDInstanceFrontendModule().
refine_camera_pose_with_joint_of
bool dyno::FrontendParams::refine_camera_pose_with_joint_of = true
Definition at line 64 of file FrontendParams.hpp.
scene_flow_magnitude
double dyno::FrontendParams::scene_flow_magnitude = 0.12
Definition at line 45 of file FrontendParams.hpp.
scene_flow_percentage
double dyno::FrontendParams::scene_flow_percentage = 0.5
Definition at line 46 of file FrontendParams.hpp.
tracker_params
TrackerParams dyno::FrontendParams::tracker_params = TrackerParams()
Definition at line 70 of file FrontendParams.hpp.
Referenced by dyno::FeatureTracker::FeatureTracker(), main(), and dyno::updateAndCheckDynoParamsForRawImageInput().
use_ego_motion_pnp
bool dyno::FrontendParams::use_ego_motion_pnp = true
When using RGBD pipeline, ego-motion will be sovled using pnp (3d2d correspondences). Else, stereo
Definition at line 57 of file FrontendParams.hpp.
use_object_motion_pnp
bool dyno::FrontendParams::use_object_motion_pnp = true
When using RGBD pipeline, object motion will be sovled using pnp (3d2d correspondences). Else, stereo
Definition at line 61 of file FrontendParams.hpp.
The documentation for this struct was generated from the following file:
dynosam/include/dynosam/frontend/FrontendParams.hpp