DynoSAM: dyno::FrameNode< MEASUREMENT > Class Template Reference
dyno::FrameNode< MEASUREMENT > Class Template Reference
Frame node representing all temporal data at a frame id (k) in the map-graph.
#include <MapNodes.hpp>
Public Types
using Base = MapNodeBase< MEASUREMENT >
using This = FrameNode< MEASUREMENT >
using LandmarkMeasurementPair = std::pair< const LandmarkNodePtr< MEASUREMENT >, MEASUREMENT >
Const LandmarkNodePtr with corresponding Measurement value.
Public Member Functions
FrameNode (const std::shared_ptr< Map< MEASUREMENT > > &map)
int getId () const override
Returns the frame_id.
std::string toString () const override
bool objectObserved (ObjectId object_id) const
True if the requested object was observed in this frame.
bool objectObservedInPrevious (ObjectId object_id) const
True if the requested object was observed at the previous frame.
bool objectMotionExpected (ObjectId object_id) const
True if the object appears at this (k) and the previous frame (k-1) and therefore we expect a motion to exist taking us from k-1 to k.
gtsam::Key makePoseKey () const
Constructs a robot/sensor pose key.
gtsam::Key makeObjectMotionKey (ObjectId object_id) const
Consturcts an object motion key. The associated motion will be from k-1 to k.
gtsam::Key makeObjectPoseKey (ObjectId object_id) const
Construct an object pose key. The associated pose will be for frame k.
std::vector< LandmarkMeasurementPair > getStaticMeasurements () const
Get all static measurements for this frame.
std::vector< LandmarkMeasurementPair > getDynamicMeasurements () const
Get all (over all objects) dynamic measurements for this frame.
std::vector< LandmarkMeasurementPair > getDynamicMeasurements (ObjectId object_id) const
Get the Dynamic Measurements object.
size_t numObjects () const
Number of observed objects at this frame.
size_t numDynamicMeasurements () const
Number of dynamic measurements for this frame.
size_t numStaticMeasurements () const
Number of static measurements for this frame.
Public Member Functions inherited from dyno::MapNodeBase< MEASUREMENT >
MapNodeBase (const std::shared_ptr< Map< MEASUREMENT > > &map)
virtual ~MapNodeBase ()=default
virtual int getId () const =0
virtual std::string toString () const =0
Public Attributes
FrameId frame_id
FrameId (k)
LandmarkNodePtrSet< MEASUREMENT > dynamic_landmarks
All dynamic landmarks observed at this frame.
LandmarkNodePtrSet< MEASUREMENT > static_landmarks
All static landmarks observed at this frame.
ObjectNodePtrSet< MEASUREMENT > objects_seen
All objects seen at this frame. NOTE that this means that we have point observations at this frame, but not necessarily a motion (e.g. if we only observe this object once)
std::optional< gtsam::Pose3 > X_world
Optional initial camera pose in world, provided by the front-end.
std::optional< MotionEstimateMap > motions_world
Optional initial object motions in the world, provided by the front-end.
Additional Inherited Members
Protected Attributes inherited from dyno::MapNodeBase< MEASUREMENT >
std::shared_ptr< Map< MEASUREMENT > > map_ptr_
Detailed Description
template<typename MEASUREMENT>
class dyno::FrameNode< MEASUREMENT >
Frame node representing all temporal data at a frame id (k) in the map-graph.
Template Parameters
MEASUREMENT
Definition at line 367 of file MapNodes.hpp.
Member Typedef Documentation
Base
template<typename MEASUREMENT > using dyno::FrameNode< MEASUREMENT >::Base = MapNodeBase<MEASUREMENT>
Definition at line 369 of file MapNodes.hpp.
LandmarkMeasurementPair
template<typename MEASUREMENT > using dyno::FrameNode< MEASUREMENT >::LandmarkMeasurementPair = std::pair<const LandmarkNodePtr<MEASUREMENT>, MEASUREMENT>
Const LandmarkNodePtr with corresponding Measurement value.
Definition at line 464 of file MapNodes.hpp.
This
template<typename MEASUREMENT > using dyno::FrameNode< MEASUREMENT >::This = FrameNode<MEASUREMENT>
Definition at line 370 of file MapNodes.hpp.
Constructor & Destructor Documentation
FrameNode()
template<typename MEASUREMENT > dyno::FrameNode< MEASUREMENT >::FrameNode (const std::shared_ptr< Map< MEASUREMENT > > & map) inline
Definition at line 373 of file MapNodes.hpp.
      : MapNodeBase<MEASUREMENT>(map) {}
Member Function Documentation
getDynamicMeasurements() [1/2]
template<typename MEASUREMENT > std::vector< typename FrameNode< MEASUREMENT >::LandmarkMeasurementPair > dyno::FrameNode< MEASUREMENT >::getDynamicMeasurements
Get all (over all objects) dynamic measurements for this frame.
Returns
std::vector<LandmarkMeasurementPair>
Definition at line 107 of file MapNodes-inl.hpp.
{
  std::vector<LandmarkMeasurementPair> measurements;
  for (const auto& lmk_ptr : dynamic_landmarks) {
    const MEASUREMENT m = lmk_ptr->getMeasurement(this->frame_id);
    measurements.push_back(std::make_pair(lmk_ptr, m));
  }
  return measurements;
}
getDynamicMeasurements() [2/2]
template<typename MEASUREMENT > std::vector< typename FrameNode< MEASUREMENT >::LandmarkMeasurementPair > dyno::FrameNode< MEASUREMENT >::getDynamicMeasurements (ObjectId object_id) const
Get the Dynamic Measurements object.
Parameters
object_id
Returns
std::vector<LandmarkMeasurementPair>
Definition at line 118 of file MapNodes-inl.hpp.
{
  std::vector<LandmarkMeasurementPair> measurements;
  for (const auto& lmk_ptr : dynamic_landmarks) {
    if (lmk_ptr->getObjectId() == object_id) {
      const MEASUREMENT m = lmk_ptr->getMeasurement(this->frame_id);
      measurements.push_back(std::make_pair(lmk_ptr, m));
    }
  }
  return measurements;
}
getId()
template<typename MEASUREMENT > int dyno::FrameNode< MEASUREMENT >::getId override virtual
Returns the frame_id.
Returns
int
Implements dyno::MapNodeBase< MEASUREMENT >.
Definition at line 39 of file MapNodes-inl.hpp.
{
  return (int)frame_id;
}
getStaticMeasurements()
template<typename MEASUREMENT > std::vector< typename FrameNode< MEASUREMENT >::LandmarkMeasurementPair > dyno::FrameNode< MEASUREMENT >::getStaticMeasurements
Get all static measurements for this frame.
Returns
std::vector<LandmarkMeasurementPair>
Definition at line 96 of file MapNodes-inl.hpp.
{
  std::vector<LandmarkMeasurementPair> measurements;
  for (const auto& lmk_ptr : static_landmarks) {
    MEASUREMENT m = lmk_ptr->getMeasurement(this->frame_id);
    measurements.push_back(std::make_pair(lmk_ptr, m));
  }
  return measurements;
}
makeObjectMotionKey()
template<typename MEASUREMENT > gtsam::Key dyno::FrameNode< MEASUREMENT >::makeObjectMotionKey (ObjectId object_id) const
Consturcts an object motion key. The associated motion will be from k-1 to k.
Parameters
object_id ObjectId
Returns
gtsam::Key
Definition at line 67 of file MapNodes-inl.hpp.
{
  // TODO: no point checking if this key exists yet as we might want it
  // arbiratarily!!
  //  if(!objectObserved(object_id)) {
  //      throw DynosamException("Object motion key requested" +
  //      std::to_string(object_id) + " at frame " +  std::to_string(frame_id) +
  //      " but object is not observed in this frame");
  //  }
  return ObjectMotionSymbol(object_id, this->frame_id);
}
References dyno::ObjectMotionSymbol().
makeObjectPoseKey()
template<typename MEASUREMENT > gtsam::Key dyno::FrameNode< MEASUREMENT >::makeObjectPoseKey (ObjectId object_id) const
Construct an object pose key. The associated pose will be for frame k.
Parameters
object_id ObjectId
Returns
gtsam::Key
Definition at line 80 of file MapNodes-inl.hpp.
{
  //  if(!objectObserved(object_id)) {
  //     throw DynosamException("Object pose key requested" +
  //     std::to_string(object_id) + " at frame " +  std::to_string(frame_id) +
  //     " but object is not observed in this frame");
  // }
  return ObjectPoseSymbol(object_id, this->frame_id);
}
References dyno::ObjectPoseSymbol().
makePoseKey()
template<typename MEASUREMENT > gtsam::Key dyno::FrameNode< MEASUREMENT >::makePoseKey
Constructs a robot/sensor pose key.
Returns
gtsam::Key
Definition at line 62 of file MapNodes-inl.hpp.
{
  return CameraPoseSymbol(frame_id);
}
References dyno::CameraPoseSymbol().
numDynamicMeasurements()
template<typename MEASUREMENT > size_t dyno::FrameNode< MEASUREMENT >::numDynamicMeasurements () const inline
Number of dynamic measurements for this frame.
Returns
size_t
Definition at line 502 of file MapNodes.hpp.
{
    return dynamic_landmarks.size();
  }
References dyno::FrameNode< MEASUREMENT >::dynamic_landmarks.
Referenced by dyno::FrameNode< MEASUREMENT >::toString().
numObjects()
template<typename MEASUREMENT > size_t dyno::FrameNode< MEASUREMENT >::numObjects () const inline
Number of observed objects at this frame.
Returns
size_t
Definition at line 495 of file MapNodes.hpp.
{ return objects_seen.size(); }
References dyno::FrameNode< MEASUREMENT >::objects_seen.
numStaticMeasurements()
template<typename MEASUREMENT > size_t dyno::FrameNode< MEASUREMENT >::numStaticMeasurements () const inline
Number of static measurements for this frame.
Returns
size_t
Definition at line 511 of file MapNodes.hpp.
{
    return static_landmarks.size();
  }
References dyno::FrameNode< MEASUREMENT >::static_landmarks.
Referenced by dyno::FrameNode< MEASUREMENT >::toString().
objectMotionExpected()
template<typename MEASUREMENT > bool dyno::FrameNode< MEASUREMENT >::objectMotionExpected (ObjectId object_id) const
True if the object appears at this (k) and the previous frame (k-1) and therefore we expect a motion to exist taking us from k-1 to k.
Parameters
object_id ObjectId
Returns
true
false
Definition at line 90 of file MapNodes-inl.hpp.
{
  return objectObserved(object_id) && objectObservedInPrevious(object_id);
}
objectObserved()
template<typename MEASUREMENT > bool dyno::FrameNode< MEASUREMENT >::objectObserved (ObjectId object_id) const
True if the requested object was observed in this frame.
Parameters
object_id ObjectId
Returns
true
false
Definition at line 44 of file MapNodes-inl.hpp.
{
  return objects_seen.exists(object_id);
}
objectObservedInPrevious()
template<typename MEASUREMENT > bool dyno::FrameNode< MEASUREMENT >::objectObservedInPrevious (ObjectId object_id) const
True if the requested object was observed at the previous frame.
Parameters
object_id ObjectId
Returns
true
false
Definition at line 49 of file MapNodes-inl.hpp.
{
  const auto frame_id_k_1 = frame_id - 1u;
  FrameNodePtr<MEASUREMENT> frame_node_k_1 =
      this->map_ptr_->template getFrame(frame_id_k_1);
  if (!frame_node_k_1) {
    return false;
  }
  return frame_node_k_1->objectObserved(object_id);
}
toString()
template<typename MEASUREMENT > std::string dyno::FrameNode< MEASUREMENT >::toString () const inline override virtual
Implements dyno::MapNodeBase< MEASUREMENT >.
Definition at line 399 of file MapNodes.hpp.
{
    std::stringstream ss;
    ss << "Frame Id: " << frame_id << "\n";
    ss << "Objects seen: "
       << container_to_string(objects_seen.template collectIds<ObjectId>())
       << "\n";
    ss << "Num dynamic measurements: " << numDynamicMeasurements() << "\n";
    ss << "Num static measurements: " << numStaticMeasurements();
    return ss.str();
  }
References dyno::container_to_string(), dyno::FrameNode< MEASUREMENT >::frame_id, dyno::FrameNode< MEASUREMENT >::numDynamicMeasurements(), dyno::FrameNode< MEASUREMENT >::numStaticMeasurements(), and dyno::FrameNode< MEASUREMENT >::objects_seen.
Member Data Documentation
dynamic_landmarks
template<typename MEASUREMENT > LandmarkNodePtrSet<MEASUREMENT> dyno::FrameNode< MEASUREMENT >::dynamic_landmarks
All dynamic landmarks observed at this frame.
Definition at line 379 of file MapNodes.hpp.
Referenced by dyno::FrameNode< MEASUREMENT >::numDynamicMeasurements().
frame_id
template<typename MEASUREMENT > FrameId dyno::FrameNode< MEASUREMENT >::frame_id
FrameId (k)
Definition at line 377 of file MapNodes.hpp.
Referenced by dyno::FrameNode< MEASUREMENT >::toString().
motions_world
template<typename MEASUREMENT > std::optional<MotionEstimateMap> dyno::FrameNode< MEASUREMENT >::motions_world
Optional initial object motions in the world, provided by the front-end.
Definition at line 391 of file MapNodes.hpp.
objects_seen
template<typename MEASUREMENT > ObjectNodePtrSet<MEASUREMENT> dyno::FrameNode< MEASUREMENT >::objects_seen
All objects seen at this frame. NOTE that this means that we have point observations at this frame, but not necessarily a motion (e.g. if we only observe this object once)
Definition at line 385 of file MapNodes.hpp.
Referenced by dyno::FrameNode< MEASUREMENT >::numObjects(), and dyno::FrameNode< MEASUREMENT >::toString().
static_landmarks
template<typename MEASUREMENT > LandmarkNodePtrSet<MEASUREMENT> dyno::FrameNode< MEASUREMENT >::static_landmarks
All static landmarks observed at this frame.
Definition at line 381 of file MapNodes.hpp.
Referenced by dyno::FrameNode< MEASUREMENT >::numStaticMeasurements().
X_world
template<typename MEASUREMENT > std::optional<gtsam::Pose3> dyno::FrameNode< MEASUREMENT >::X_world
Optional initial camera pose in world, provided by the front-end.
Definition at line 388 of file MapNodes.hpp.
The documentation for this class was generated from the following files:
dynosam/include/dynosam/common/MapNodes.hpp
dynosam/include/dynosam/common/MapNodes-inl.hpp