DynoSAM: dyno::UpdateObservationResult Struct Reference
dyno::UpdateObservationResult Struct Reference
Result of a static/dynamic point update by calling Formulation<MAP>::updateStaticObservations or Formulation<MAP>::updateDynamicObservations.
#include <Formulation.hpp>
Public Member Functions
UpdateObservationResult ()
UpdateObservationResult (const UpdateObservationParams &update_params)
void updateAffectedObject (FrameId frame_id, ObjectId object_id)
Public Attributes
gtsam::FastMap< ObjectId, std::set< FrameId > > objects_affected_per_frame
DebugInfo::Optional debug_info {}
gtsam::ISAM2UpdateParams isam_update_params
Detailed Description
Result of a static/dynamic point update by calling Formulation<MAP>::updateStaticObservations or Formulation<MAP>::updateDynamicObservations.
The objects affected per frame should be specified and any additional paramters for the optimisation (i.e gtsam::ISAM2UpdateParams) can be set, which will then be parsed to the optimiser by the BackendModule.
Definition at line 88 of file Formulation.hpp.
Constructor & Destructor Documentation
UpdateObservationResult() [1/2]
dyno::UpdateObservationResult::UpdateObservationResult () inline
Definition at line 96 of file Formulation.hpp.
{}
UpdateObservationResult() [2/2]
dyno::UpdateObservationResult::UpdateObservationResult (const UpdateObservationParams & update_params) inline
Definition at line 98 of file Formulation.hpp.
{
    if (update_params.enable_debug_info) {
      this->debug_info = DebugInfo();
    }
  }
References debug_info, and dyno::UpdateObservationParams::enable_debug_info.
Member Function Documentation
updateAffectedObject()
void dyno::UpdateObservationResult::updateAffectedObject (FrameId frame_id, ObjectId object_id) inline
Definition at line 104 of file Formulation.hpp.
{
    if (!objects_affected_per_frame.exists(object_id)) {
      objects_affected_per_frame.insert2(object_id, std::set<FrameId>{});
    }
    objects_affected_per_frame[object_id].insert(frame_id);
  }
References objects_affected_per_frame.
Referenced by dyno::internal::StaticFormulationUpdater< MAP >::StereoProjection::addLandmark(), dyno::internal::StaticFormulationUpdater< MAP >::PTP::addLandmark(), dyno::HybridFormulation::dynamicPointUpdateCallback(), dyno::test_hybrid::SmartStructurlessFormulation::dynamicPointUpdateCallback(), dyno::WorldMotionFormulation::dynamicPointUpdateCallback(), and dyno::WorldPoseFormulation::dynamicPointUpdateCallback().
Member Data Documentation
debug_info
DebugInfo::Optional dyno::UpdateObservationResult::debug_info {}
Definition at line 91 of file Formulation.hpp.
Referenced by dyno::HybridFormulation::dynamicPointUpdateCallback(), dyno::test_hybrid::SmartStructurlessFormulation::dynamicPointUpdateCallback(), dyno::WorldMotionFormulation::dynamicPointUpdateCallback(), dyno::WorldPoseFormulation::dynamicPointUpdateCallback(), dyno::HybridFormulation::objectUpdateContext(), dyno::WorldMotionFormulation::objectUpdateContext(), dyno::WorldPoseFormulation::objectUpdateContext(), and UpdateObservationResult().
isam_update_params
gtsam::ISAM2UpdateParams dyno::UpdateObservationResult::isam_update_params
Definition at line 94 of file Formulation.hpp.
Referenced by dyno::test_hybrid::SmartStructurlessFormulation::dynamicPointUpdateCallback(), and dyno::RegularBackendModule::updateIncremental().
objects_affected_per_frame
gtsam::FastMap<ObjectId, std::set<FrameId> > dyno::UpdateObservationResult::objects_affected_per_frame
Definition at line 90 of file Formulation.hpp.
Referenced by dyno::RegularHybridFormulation::postUpdate(), and updateAffectedObject().
The documentation for this struct was generated from the following file:
dynosam/include/dynosam/backend/Formulation.hpp