DynoSAM: dyno::Color Struct Reference
dyno::Color Struct Reference
#include <Colour.hpp>
Classes
struct Hash
Hash function for colors to use colors as keys in maps, sets, etc.
Public Member Functions
Color ()=default
Color (uint8_t r, uint8_t g, uint8_t b, uint8_t a=max())
virtual ~Color ()=default
bool operator== (const Color &other) const
bool operator!= (const Color &other) const
bool operator< (const Color &other) const
bool operator> (const Color &other) const
operator cv::Scalar () const
cv::Scalar rgba () const
Return in rgba format.
cv::Scalar bgra () const
Return in BGRA format.
RGBA< double > toDouble () const
Return the RGBA values as a double. Note this will change the range from 0-255 to 0-1.
Color blend (const Color &other, float weight=0.5f) const
Blend another color with this one.
void merge (const Color &other, float weight=0.5f)
Merge another color into this one.
Public Member Functions inherited from dyno::RGBA< uint8_t >
RGBA ()=default
RGBA (uint8_t r, uint8_t g, uint8_t b, uint8_t a=max())
RGBA (const RGBA< U > &other)
Static Public Member Functions
static Color black ()
static Color white ()
static Color red ()
static Color green ()
static Color blue ()
static Color yellow ()
static Color orange ()
static Color purple ()
static Color cyan ()
static Color magenta ()
static Color pink ()
static Color random ()
static Color fromHSV (float hue, float saturation, float value)
static Color fromHLS (float hue, float luminance, float saturation)
static Color gray (float value=0.5f)
Generate a gray-scale color.
static Color quality (float value)
Generate a color based on a quality value.
static Color spectrum (float value, const std::vector< Color > &colors)
Generate a color based on a spectrum of colors.
static Color ironbow (float value)
Generate a color based on a ironbow value.
static Color rainbow (float value)
Generate a color based on a rainbow value.
static Color rainbowId (size_t id, size_t ids_per_revolution=16)
Generate a sequence of never repeating colors in the rainbow spectrum.
static Color uniqueId (size_t id, float saturation=unique_id_default_saturation, float value=unique_id_default_value)
Generates a sequence of never repeating colors using the golden ratio to seperate the colours along the HSV ring spectrum.
static Color uniqueObjectId (ObjectId id)
Overload of uniqueId that uses types specific for ObjectId. To allow a simpler function signature, this function only takes one argument where the saturation=0.5f and value=0.95f.
Static Public Member Functions inherited from dyno::RGBA< uint8_t >
static constexpr uint8_t max ()
Static Public Attributes
static constexpr float unique_id_default_value = 0.95f
static constexpr float unique_id_default_saturation = 0.5f
Static Private Attributes
static const std::vector< Color > ironbow_colors_
Friends
std::ostream & operator<< (std::ostream &, const Color &)
Additional Inherited Members
Public Attributes inherited from dyno::RGBA< uint8_t >
uint8_t r
uint8_t g
uint8_t b
uint8_t a
Detailed Description
Definition at line 109 of file Colour.hpp.
Constructor & Destructor Documentation
Color() [1/2]
dyno::Color::Color () default
Referenced by black(), blend(), blue(), cyan(), fromHLS(), fromHSV(), gray(), green(), magenta(), orange(), pink(), purple(), random(), red(), white(), and yellow().
Color() [2/2]
dyno::Color::Color (uint8_t r, uint8_t g, uint8_t b, uint8_t a = max()) inline
Definition at line 114 of file Colour.hpp.
      : RGBA(r, g, b, a) {}
~Color()
virtual dyno::Color::~Color () virtual default
Member Function Documentation
bgra()
cv::Scalar dyno::Color::bgra () const inline
Return in BGRA format.
Returns
cv::Scalar
Definition at line 140 of file Colour.hpp.
{ return cv::Scalar(b, g, r, a); }
References dyno::RGBA< uint8_t >::a, dyno::RGBA< uint8_t >::b, dyno::RGBA< uint8_t >::g, and dyno::RGBA< uint8_t >::r.
Referenced by dyno::FeatureTrackerBase::computeImageTracks(), dyno::ObjectPoseGT::drawBoundingBox(), dyno::utils::labelMaskToRGB(), dyno::ParallelHybridBackendModule::nominalSpinImpl(), and dyno::FrontendInbuiltDisplayRos::processRGBDOutputpacket().
black()
static Color dyno::Color::black () inline static
Definition at line 176 of file Colour.hpp.
{ return Color(0, 0, 0); }
References Color().
Referenced by dyno::Frame::projectToDenseCloud(), and spectrum().
blend()
Color dyno::Color::blend (const Color & other, float weight = 0.5f) const
Blend another color with this one.
Parameters
other The other color to blend.
weight The weight of the other color [0,1].
Returns
The resulting blended color.
Definition at line 63 of file Colour.cc.
{
  weight = std::clamp(weight, 0.0f, 1.0f);
  return Color(static_cast<uint8_t>(r * (1.0f - weight) + other.r * weight),
               static_cast<uint8_t>(g * (1.0f - weight) + other.g * weight),
               static_cast<uint8_t>(b * (1.0f - weight) + other.b * weight),
               static_cast<uint8_t>(a * (1.0f - weight) + other.a * weight));
}
References dyno::RGBA< T >::a, dyno::RGBA< uint8_t >::a, dyno::RGBA< T >::b, dyno::RGBA< uint8_t >::b, Color(), dyno::RGBA< T >::g, dyno::RGBA< uint8_t >::g, dyno::RGBA< T >::r, and dyno::RGBA< uint8_t >::r.
Referenced by merge().
blue()
static Color dyno::Color::blue () inline static
Definition at line 180 of file Colour.hpp.
{ return Color(0, 0, 255); }
References Color().
Referenced by dyno::FeatureTrackerBase::computeImageTracks().
cyan()
static Color dyno::Color::cyan () inline static
Definition at line 184 of file Colour.hpp.
{ return Color(0, 255, 255); }
References Color().
fromHLS()
Color dyno::Color::fromHLS (float hue, float luminance, float saturation) static
Definition at line 102 of file Colour.cc.
{
  hue = std::clamp(hue, 0.0f, 1.0f);
  luminance = std::clamp(luminance, 0.0f, 1.0f);
  saturation = std::clamp(saturation, 0.0f, 1.0f);
  const float chroma = (1.0f - std::abs(2.0f * luminance - 1.0f)) * saturation;
  const auto [r1, g1, b1] = rgbFromChromaHue(chroma, hue);
  const float m = luminance - chroma / 2.0f;
  return Color(static_cast<uint8_t>((r1 + m) * 255),
               static_cast<uint8_t>((g1 + m) * 255),
               static_cast<uint8_t>((b1 + m) * 255));
}
References Color(), and dyno::rgbFromChromaHue().
Referenced by rainbow().
fromHSV()
Color dyno::Color::fromHSV (float hue, float saturation, float value) static
Definition at line 90 of file Colour.cc.
{
  hue = std::clamp(hue, 0.0f, 1.0f);
  saturation = std::clamp(saturation, 0.0f, 1.0f);
  value = std::clamp(value, 0.0f, 1.0f);
  const float chroma = value * saturation;
  const auto [r1, g1, b1] = rgbFromChromaHue(chroma, hue);
  const float m = value - chroma;
  return Color(static_cast<uint8_t>((r1 + m) * 255),
               static_cast<uint8_t>((g1 + m) * 255),
               static_cast<uint8_t>((b1 + m) * 255));
}
References Color(), and dyno::rgbFromChromaHue().
Referenced by uniqueId().
gray()
Color dyno::Color::gray (float value = 0.5f) static
Generate a gray-scale color.
Parameters
value The value of the gray [0,1, where 0 is black and 1 is white].
Definition at line 114 of file Colour.cc.
{
  value = std::clamp(value, 0.0f, 1.0f);
  return Color(static_cast<uint8_t>(value * 255),
               static_cast<uint8_t>(value * 255),
               static_cast<uint8_t>(value * 255));
}
References Color().
green()
static Color dyno::Color::green () inline static
Definition at line 179 of file Colour.hpp.
{ return Color(0, 255, 0); }
References Color().
Referenced by dyno::FeatureTrackerBase::computeImageTracks().
ironbow()
Color dyno::Color::ironbow (float value) static
Generate a color based on a ironbow value.
Parameters
value The temperature value [0,1], where 0 is dark and 1 is light.
Definition at line 148 of file Colour.cc.
{ return spectrum(value, ironbow_colors_); }
References ironbow_colors_, and spectrum().
magenta()
static Color dyno::Color::magenta () inline static
Definition at line 185 of file Colour.hpp.
{ return Color(255, 0, 255); }
References Color().
merge()
void dyno::Color::merge (const Color & other, float weight = 0.5f)
Merge another color into this one.
Parameters
other The other color to merge.
weight The weight of the other color [0,1].
Definition at line 59 of file Colour.cc.
{
  *this = blend(other, weight);
}
References blend().
operator cv::Scalar()
dyno::Color::operator cv::Scalar () const inline
Definition at line 126 of file Colour.hpp.
{ return rgba(); }
References rgba().
operator!=()
bool dyno::Color::operator!= (const Color & other) const inline
Definition at line 120 of file Colour.hpp.
{ return !(*this == other); }
operator<()
bool dyno::Color::operator< (const Color & other) const
Definition at line 46 of file Colour.cc.
{
  if (r != other.r) {
    return r < other.r;
  }
  if (g != other.g) {
    return g < other.g;
  }
  if (b != other.b) {
    return b < other.b;
  }
  return a < other.a;
}
References dyno::RGBA< T >::a, dyno::RGBA< uint8_t >::a, dyno::RGBA< T >::b, dyno::RGBA< uint8_t >::b, dyno::RGBA< T >::g, dyno::RGBA< uint8_t >::g, dyno::RGBA< T >::r, and dyno::RGBA< uint8_t >::r.
operator==()
bool dyno::Color::operator== (const Color & other) const
Definition at line 42 of file Colour.cc.
{
  return r == other.r && g == other.g && b == other.b && a == other.a;
}
References dyno::RGBA< T >::a, dyno::RGBA< uint8_t >::a, dyno::RGBA< T >::b, dyno::RGBA< uint8_t >::b, dyno::RGBA< T >::g, dyno::RGBA< uint8_t >::g, dyno::RGBA< T >::r, and dyno::RGBA< uint8_t >::r.
operator>()
bool dyno::Color::operator> (const Color & other) const inline
Definition at line 122 of file Colour.hpp.
{ return other < *this; }
orange()
static Color dyno::Color::orange () inline static
Definition at line 182 of file Colour.hpp.
{ return Color(255, 127, 0); }
References Color().
pink()
static Color dyno::Color::pink () inline static
Definition at line 186 of file Colour.hpp.
{ return Color(255, 127, 127); }
References Color().
purple()
static Color dyno::Color::purple () inline static
Definition at line 183 of file Colour.hpp.
{ return Color(127, 0, 255); }
References Color().
quality()
Color dyno::Color::quality (float value) static
Generate a color based on a quality value.
Parameters
value The quality value [0,1], where 0 is red, 0.5 is yellow, and 1 is green.
Definition at line 121 of file Colour.cc.
{
  value = std::clamp(value, 0.0f, 1.0f);
  Color color;
  if (value > 0.5f) {
    color.r = (1.f - value) * 2 * 255;
    color.g = 255;
  } else {
    color.r = 255;
    color.g = value * 2 * 255;
  }
  return color;
}
References dyno::RGBA< T >::g, and dyno::RGBA< T >::r.
rainbow()
Color dyno::Color::rainbow (float value) static
Generate a color based on a rainbow value.
Parameters
value The rainbow value [0,1], where 0 is red, 0.5 is green, and 1 is blue.
Definition at line 150 of file Colour.cc.
{
  return fromHLS(std::clamp(value, 0.0f, 1.0f), 0.5f, 1.0f);
}
References fromHLS().
Referenced by rainbowId().
rainbowId()
Color dyno::Color::rainbowId (size_t id, size_t ids_per_revolution = 16) static
Generate a sequence of never repeating colors in the rainbow spectrum.
Parameters
id The id of the color in the sequence.
ids_per_revolution The number of colors per revolution of the hue.
Definition at line 174 of file Colour.cc.
{
  return Color::rainbow(exponentialOffsetId(id, ids_per_revolution));
}
References dyno::exponentialOffsetId(), and rainbow().
random()
Color dyno::Color::random () static
Definition at line 71 of file Colour.cc.
{ return Color(dis(gen), dis(gen), dis(gen), dis(gen)); }
References Color(), dyno::dis(), and dyno::gen().
red()
static Color dyno::Color::red () inline static
Definition at line 178 of file Colour.hpp.
{ return Color(255, 0, 0); }
References Color().
Referenced by dyno::FeatureTrackerBase::computeImageTracks().
rgba()
cv::Scalar dyno::Color::rgba () const inline
Return in rgba format.
Returns
cv::Scalar
Definition at line 133 of file Colour.hpp.
{ return cv::Scalar(r, g, b, a); }
References dyno::RGBA< uint8_t >::a, dyno::RGBA< uint8_t >::b, dyno::RGBA< uint8_t >::g, and dyno::RGBA< uint8_t >::r.
Referenced by operator cv::Scalar().
spectrum()
Color dyno::Color::spectrum (float value, const std::vector< Color > & colors) static
Generate a color based on a spectrum of colors.
Parameters
value The spectrum value [0,1], where 0 is the first color and 1 is the last color.
colors The list of colors in the spectrum. Colors are assumed equidistant.
Definition at line 134 of file Colour.cc.
{
  if (colors.empty()) {
    return Color::black();
  }
  value = std::clamp(value, 0.0f, 1.0f);
  const size_t num_steps = colors.size() - 1;
  const size_t index = static_cast<size_t>(value * num_steps);
  if (index >= num_steps) {
    return colors.at(num_steps);
  }
  const float weight = value * num_steps - index;
  return colors.at(index).blend(colors.at(index + 1), weight);
}
References black().
Referenced by ironbow().
toDouble()
RGBA< double > dyno::Color::toDouble () const inline
Return the RGBA values as a double. Note this will change the range from 0-255 to 0-1.
Returns
RGBA<double>
Definition at line 148 of file Colour.hpp.
{ return RGBA<double>(*this); }
uniqueId()
Color dyno::Color::uniqueId (size_t id, float saturation = unique_id_default_saturation, float value = unique_id_default_value) static
Generates a sequence of never repeating colors using the golden ratio to seperate the colours along the HSV ring spectrum.
Parameters
id The id of the color in the sequence.
saturation Saturation value
value Value value ;)
Returns
Color
Definition at line 178 of file Colour.cc.
{
  constexpr static float phi = (1 + std::sqrt(5.0)) / 2.0;
  auto n = (float)id * phi - std::floor((float)id * phi);
  // want in 255 mode
  float hue = std::floor(n * 256.0) / 255.0;
  return Color::fromHSV(hue, saturation, value);
}
References fromHSV().
Referenced by dyno::FeatureTrackerBase::computeImageTracks(), dyno::InbuiltDisplayCommon::constructBoundingBoxeMarkers(), dyno::DSDTransport::constructMultiObjectOdometryPaths(), dyno::convert(), dyno::ObjectPoseGT::drawBoundingBox(), dyno::groupObjectCloud(), dyno::utils::labelMaskToRGB(), dyno::ParallelHybridBackendModule::nominalSpinImpl(), dyno::DisplayCommon::objectBBXToRvizMarker(), dyno::FrontendInbuiltDisplayRos::processRGBDOutputpacket(), dyno::Frame::projectToDenseCloud(), dyno::HybridModuleDisplayCommon::publishObjectKeyFrames(), dyno::InbuiltDisplayCommon::publishObjectPaths(), dyno::InbuiltDisplayCommon::publishObjectPositions(), dyno::BackendDSDRos::publishTemporalDynamicMaps(), and uniqueObjectId().
uniqueObjectId()
static Color dyno::Color::uniqueObjectId (ObjectId id) inline static
Overload of uniqueId that uses types specific for ObjectId. To allow a simpler function signature, this function only takes one argument where the saturation=0.5f and value=0.95f.
Parameters
id ObjectId
Returns
Color
Definition at line 261 of file Colour.hpp.
{
    return uniqueId(static_cast<size_t>(id));
  }
References uniqueId().
Referenced by dyno::groupObjectCloud().
white()
static Color dyno::Color::white () inline static
Definition at line 177 of file Colour.hpp.
{ return Color(255, 255, 255); }
References Color().
yellow()
static Color dyno::Color::yellow () inline static
Definition at line 181 of file Colour.hpp.
{ return Color(255, 255, 0); }
References Color().
Friends And Related Function Documentation
operator<<
std::ostream & operator<< (std::ostream & out, const Color & color) friend
Definition at line 190 of file Colour.cc.
{
  out << "[RGBA: " << static_cast<int>(color.r) << ", "
      << static_cast<int>(color.g) << ", " << static_cast<int>(color.b) << ", "
      << static_cast<int>(color.a) << "]";
  return out;
}
Member Data Documentation
ironbow_colors_
const std::vector< Color > dyno::Color::ironbow_colors_ static private
Initial value:
= {
    {0, 0, 0}, {145, 20, 145}, {255, 138, 0}, {255, 230, 40}, {255, 255, 255}}
Definition at line 266 of file Colour.hpp.
Referenced by ironbow().
unique_id_default_saturation
constexpr float dyno::Color::unique_id_default_saturation = 0.5f static constexpr
Definition at line 238 of file Colour.hpp.
Referenced by dyno::BackendDSDRos::publishTemporalDynamicMaps().
unique_id_default_value
constexpr float dyno::Color::unique_id_default_value = 0.95f static constexpr
Definition at line 237 of file Colour.hpp.
Referenced by dyno::BackendDSDRos::publishTemporalDynamicMaps().
The documentation for this struct was generated from the following files:
dynosam_common/include/dynosam_common/viz/Colour.hpp
dynosam_common/src/viz/Colour.cc