DynoSAM: dyno::ImageWrapper< IMAGETYPE > Struct Template Reference
dyno::ImageWrapper< IMAGETYPE > Struct Template Reference
ImageWrapper for a ImageType that defines a particular type of input image. The ImageType template is used to create different types (actual c++ types) to differntial cv::Mat's from each other - eg. a type for a RGB image, Optical Flow or Motion Mask.
#include <ImageTypes.hpp>
Public Types
using Type = IMAGETYPE
using This = ImageWrapper< Type >
using Base = ImageBase
Public Member Functions
ImageWrapper ()=default
ImageWrapper (const cv::Mat &img)
ImageWrapper (const ImageBase &image_base)
virtual std::unique_ptr< ImageBase > shallowCopy () const override
virtual std::unique_ptr< ImageBase > deepCopy () const override
ImageWrapper< Type > clone () const
cv::Mat toRGB () const
virtual std::string toString () const override
Public Member Functions inherited from dyno::ImageBase
ImageBase ()=default
Underlying image.
ImageBase (const cv::Mat &img)
virtual ~ImageBase ()
operator cv::Mat & ()
operator const cv::Mat & () const
template<typename IMAGETYPE >
const ImageWrapper< IMAGETYPE > & cast () const
template<typename IMAGETYPE >
ImageWrapper< IMAGETYPE > & cast ()
bool exists () const
virtual std::unique_ptr< ImageBase > shallowCopy () const
virtual std::unique_ptr< ImageBase > deepCopy () const
virtual std::string toString () const
Additional Inherited Members
Public Attributes inherited from dyno::ImageBase
cv::Mat image
Detailed Description
template<typename IMAGETYPE>
struct dyno::ImageWrapper< IMAGETYPE >
ImageWrapper for a ImageType that defines a particular type of input image. The ImageType template is used to create different types (actual c++ types) to differntial cv::Mat's from each other - eg. a type for a RGB image, Optical Flow or Motion Mask.
ImageType must define a static validate(const cv::Mat&) function which throws an expcetion if the cv::Mat does not meed the requirements of the ImageType and a static name() function which returns a string. Must also have a static toRGB(const ImageWrapper<Type>& image) fucntion.
Template Parameters
IMAGETYPE
Definition at line 122 of file ImageTypes.hpp.
Member Typedef Documentation
Base
template<typename IMAGETYPE > using dyno::ImageWrapper< IMAGETYPE >::Base = ImageBase
Definition at line 125 of file ImageTypes.hpp.
This
template<typename IMAGETYPE > using dyno::ImageWrapper< IMAGETYPE >::This = ImageWrapper<Type>
Definition at line 124 of file ImageTypes.hpp.
Type
template<typename IMAGETYPE > using dyno::ImageWrapper< IMAGETYPE >::Type = IMAGETYPE
Definition at line 123 of file ImageTypes.hpp.
Constructor & Destructor Documentation
ImageWrapper() [1/3]
template<typename IMAGETYPE > dyno::ImageWrapper< IMAGETYPE >::ImageWrapper () default
ImageWrapper() [2/3]
template<typename IMAGETYPE > dyno::ImageWrapper< IMAGETYPE >::ImageWrapper (const cv::Mat & img)
Definition at line 38 of file ImageTypes-inl.hpp.
                                                      : ImageBase(img) {
  const std::string name = Type::name();
  if (img.empty()) {
    throw InvalidImageTypeException("Image was empty for type " + name);
  }
  // should throw excpetion if problematic
  Type::validate(img);
}
ImageWrapper() [3/3]
template<typename IMAGETYPE > dyno::ImageWrapper< IMAGETYPE >::ImageWrapper (const ImageBase & image_base)
Definition at line 49 of file ImageTypes-inl.hpp.
    : ImageBase(image_base) {}
Member Function Documentation
clone()
template<typename IMAGETYPE > ImageWrapper< Type > dyno::ImageWrapper< IMAGETYPE >::clone () const inline
Definition at line 139 of file ImageTypes.hpp.
{ return *(this->deepCopy()); }
References dyno::ImageWrapper< IMAGETYPE >::deepCopy().
Referenced by dyno::ImageType::Depth::toRGB(), and dyno::ImageType::MotionMask::toRGB().
deepCopy()
template<typename IMAGETYPE > virtual std::unique_ptr< ImageBase > dyno::ImageWrapper< IMAGETYPE >::deepCopy () const inline override virtual
Reimplemented from dyno::ImageBase.
Definition at line 135 of file ImageTypes.hpp.
{
    return std::make_unique<ImageWrapper<IMAGETYPE>>(image.clone());
  }
References dyno::ImageBase::image.
Referenced by dyno::ImageWrapper< IMAGETYPE >::clone().
shallowCopy()
template<typename IMAGETYPE > virtual std::unique_ptr< ImageBase > dyno::ImageWrapper< IMAGETYPE >::shallowCopy () const inline override virtual
Reimplemented from dyno::ImageBase.
Definition at line 131 of file ImageTypes.hpp.
{
    return std::make_unique<ImageWrapper<IMAGETYPE>>(image);
  }
References dyno::ImageBase::image.
toRGB()
template<typename IMAGETYPE > cv::Mat dyno::ImageWrapper< IMAGETYPE >::toRGB () const inline
Definition at line 141 of file ImageTypes.hpp.
{ return IMAGETYPE::toRGB(*this); }
Referenced by dyno::FeatureTrackerBase::computeImageTracks(), dyno::FeatureTrackerBase::drawStereoMatches(), dyno::KltFeatureTracker::equalizeImage(), and dyno::ExternalFlowFeatureTracker::trackStatic().
toString()
template<typename IMAGETYPE > virtual std::string dyno::ImageWrapper< IMAGETYPE >::toString () const inline override virtual
Reimplemented from dyno::ImageBase.
Definition at line 143 of file ImageTypes.hpp.
{
    std::stringstream ss;
    ss << type_name<This>() << ": " << Base::toString();
    return ss.str();
  }
References dyno::ImageBase::toString().
The documentation for this struct was generated from the following files:
dynosam_cv/include/dynosam_cv/ImageTypes.hpp
dynosam_cv/include/dynosam_cv/ImageTypes-inl.hpp