DynoSAM: dyno::factor_graph_tools::SparsityStats Struct Reference
dyno::factor_graph_tools::SparsityStats Struct Reference
#include <FactorGraphTools.hpp>
Public Member Functions
SparsityStats ()
template<typename Derived >
SparsityStats (const Eigen::MatrixBase< Derived > &M)
Construct details from a matrix.
void saveOnOutputPath (const std::string &file_name)
void save (const std::string &file_path)
Public Attributes
gtsam::Matrix matrix
size_t nr_zero_elements {0}
Number of zero elements.
size_t nr_elements {0}
Number total elements in the matrix (rows * cols)
size_t nnz_elements {0}
Number of non-zero elements.
Detailed Description
Definition at line 308 of file FactorGraphTools.hpp.
Constructor & Destructor Documentation
SparsityStats() [1/2]
dyno::factor_graph_tools::SparsityStats::SparsityStats () inline
Definition at line 317 of file FactorGraphTools.hpp.
{};
SparsityStats() [2/2]
template<typename Derived > dyno::factor_graph_tools::SparsityStats::SparsityStats (const Eigen::MatrixBase< Derived > & M) inline
Construct details from a matrix.
Stat values are set upon construction
Template Parameters
Derived
Parameters
M
Definition at line 328 of file FactorGraphTools.hpp.
      : matrix(M.template cast<double>()), nr_zero_elements(0), nr_elements(0) {
    nr_elements = M.rows() * M.cols();
    for (int i = 0; i < M.rows(); ++i) {
      for (int j = 0; j < M.cols(); ++j) {
        if (std::fabs(M(i, j)) < 1e-15) {
          nr_zero_elements++;
        } else {
          nnz_elements++;
        }
      }
    }
  }
References nnz_elements, nr_elements, and nr_zero_elements.
Member Function Documentation
save()
void dyno::factor_graph_tools::SparsityStats::save (const std::string & file_path) inline
Definition at line 346 of file FactorGraphTools.hpp.
{
    VLOG(20) << "Writing matrix matrix to file_path " << file_path;
    gtsam::save(matrix, "sparse_matrix", file_path);
  }
References matrix.
Referenced by saveOnOutputPath().
saveOnOutputPath()
void dyno::factor_graph_tools::SparsityStats::saveOnOutputPath (const std::string & file_name) inline
Definition at line 342 of file FactorGraphTools.hpp.
{
    save(getOutputFilePath(file_name));
  }
References dyno::getOutputFilePath(), and save().
Referenced by dyno::FactorGraphManager< GRAPH >::computeHessianSparsityStats(), and dyno::FactorGraphManager< GRAPH >::computeJacobianSparsityStats().
Member Data Documentation
matrix
gtsam::Matrix dyno::factor_graph_tools::SparsityStats::matrix
Definition at line 309 of file FactorGraphTools.hpp.
Referenced by save().
nnz_elements
size_t dyno::factor_graph_tools::SparsityStats::nnz_elements {0}
Number of non-zero elements.
Definition at line 315 of file FactorGraphTools.hpp.
Referenced by SparsityStats().
nr_elements
size_t dyno::factor_graph_tools::SparsityStats::nr_elements {0}
Number total elements in the matrix (rows * cols)
Definition at line 313 of file FactorGraphTools.hpp.
Referenced by SparsityStats().
nr_zero_elements
size_t dyno::factor_graph_tools::SparsityStats::nr_zero_elements {0}
Number of zero elements.
Definition at line 311 of file FactorGraphTools.hpp.
Referenced by SparsityStats().
The documentation for this struct was generated from the following file:
dynosam/include/dynosam/backend/FactorGraphTools.hpp