DynoSAM: dyno::utils::StatisticsMapValue Struct Reference
dyno::utils::StatisticsMapValue Struct Reference
#include <Statistics.hpp>
Public Member Functions
StatisticsMapValue ()
void AddValue (double sample)
double GetLastDeltaTime () const
double GetLastValue () const
double Sum () const
int TotalSamples () const
double Mean () const
double RollingMean () const
double Max () const
double Min () const
double Median () const
double Q1 () const
double Q3 () const
double LazyVariance () const
double MeanCallsPerSec () const
double MeanDeltaTime () const
double RollingMeanDeltaTime () const
double MaxDeltaTime () const
double MinDeltaTime () const
double LazyVarianceDeltaTime () const
const std::vector< double > & GetAllValues () const
Static Public Attributes
static const int kWindowSize = 1000
Private Attributes
Accumulator< double, double, kWindowSize > values_
Accumulator< double, double, kWindowSize > time_deltas_
std::chrono::time_point< std::chrono::system_clock > time_last_called_
Detailed Description
Definition at line 83 of file Statistics.hpp.
Constructor & Destructor Documentation
StatisticsMapValue()
dyno::utils::StatisticsMapValue::StatisticsMapValue () inline
Definition at line 87 of file Statistics.hpp.
{
    time_last_called_ = std::chrono::system_clock::now();
  }
References time_last_called_.
Member Function Documentation
AddValue()
void dyno::utils::StatisticsMapValue::AddValue (double sample) inline
Definition at line 91 of file Statistics.hpp.
{
    std::chrono::time_point<std::chrono::system_clock> now =
        std::chrono::system_clock::now();
    double dt = static_cast<double>(
                    std::chrono::duration_cast<std::chrono::nanoseconds>(
                        now - time_last_called_)
                        .count()) *
                kNumSecondsPerNanosecond;
    time_last_called_ = now;
    values_.Add(sample);
    time_deltas_.Add(dt);
  }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::Add(), dyno::utils::kNumSecondsPerNanosecond, time_deltas_, time_last_called_, and values_.
GetAllValues()
const std::vector< double > & dyno::utils::StatisticsMapValue::GetAllValues () const inline
Definition at line 142 of file Statistics.hpp.
{ return values_.GetAllSamples(); }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::GetAllSamples(), and values_.
GetLastDeltaTime()
double dyno::utils::StatisticsMapValue::GetLastDeltaTime () const inline
Definition at line 104 of file Statistics.hpp.
{
    if (time_deltas_.total_samples()) {
      return time_deltas_.GetMostRecent();
    } else {
      return 0;
    }
  }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::GetMostRecent(), time_deltas_, and dyno::utils::Accumulator< SampleType, SumType, WindowSize >::total_samples().
GetLastValue()
double dyno::utils::StatisticsMapValue::GetLastValue () const inline
Definition at line 111 of file Statistics.hpp.
{
    if (values_.total_samples()) {
      return values_.GetMostRecent();
    } else {
      return 0;
    }
  }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::GetMostRecent(), dyno::utils::Accumulator< SampleType, SumType, WindowSize >::total_samples(), and values_.
LazyVariance()
double dyno::utils::StatisticsMapValue::LazyVariance () const inline
Definition at line 127 of file Statistics.hpp.
{ return values_.LazyVariance(); }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::LazyVariance(), and values_.
LazyVarianceDeltaTime()
double dyno::utils::StatisticsMapValue::LazyVarianceDeltaTime () const inline
Definition at line 141 of file Statistics.hpp.
{ return time_deltas_.LazyVariance(); }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::LazyVariance(), and time_deltas_.
Max()
double dyno::utils::StatisticsMapValue::Max () const inline
Definition at line 122 of file Statistics.hpp.
{ return values_.max(); }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::max(), and values_.
MaxDeltaTime()
double dyno::utils::StatisticsMapValue::MaxDeltaTime () const inline
Definition at line 139 of file Statistics.hpp.
{ return time_deltas_.max(); }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::max(), and time_deltas_.
Mean()
double dyno::utils::StatisticsMapValue::Mean () const inline
Definition at line 120 of file Statistics.hpp.
{ return values_.Mean(); }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::Mean(), and values_.
MeanCallsPerSec()
double dyno::utils::StatisticsMapValue::MeanCallsPerSec () const inline
Definition at line 128 of file Statistics.hpp.
{
    double mean_dt = time_deltas_.Mean();
    if (mean_dt != 0) {
      return 1.0 / mean_dt;
    } else {
      return -1.0;
    }
  }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::Mean(), and time_deltas_.
MeanDeltaTime()
double dyno::utils::StatisticsMapValue::MeanDeltaTime () const inline
Definition at line 137 of file Statistics.hpp.
{ return time_deltas_.Mean(); }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::Mean(), and time_deltas_.
Median()
double dyno::utils::StatisticsMapValue::Median () const inline
Definition at line 124 of file Statistics.hpp.
{ return values_.median(); }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::median(), and values_.
Min()
double dyno::utils::StatisticsMapValue::Min () const inline
Definition at line 123 of file Statistics.hpp.
{ return values_.min(); }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::min(), and values_.
MinDeltaTime()
double dyno::utils::StatisticsMapValue::MinDeltaTime () const inline
Definition at line 140 of file Statistics.hpp.
{ return time_deltas_.min(); }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::min(), and time_deltas_.
Q1()
double dyno::utils::StatisticsMapValue::Q1 () const inline
Definition at line 125 of file Statistics.hpp.
{ return values_.q1(); }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::q1(), and values_.
Q3()
double dyno::utils::StatisticsMapValue::Q3 () const inline
Definition at line 126 of file Statistics.hpp.
{ return values_.q3(); }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::q3(), and values_.
RollingMean()
double dyno::utils::StatisticsMapValue::RollingMean () const inline
Definition at line 121 of file Statistics.hpp.
{ return values_.RollingMean(); }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::RollingMean(), and values_.
RollingMeanDeltaTime()
double dyno::utils::StatisticsMapValue::RollingMeanDeltaTime () const inline
Definition at line 138 of file Statistics.hpp.
{ return time_deltas_.RollingMean(); }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::RollingMean(), and time_deltas_.
Sum()
double dyno::utils::StatisticsMapValue::Sum () const inline
Definition at line 118 of file Statistics.hpp.
{ return values_.sum(); }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::sum(), and values_.
TotalSamples()
int dyno::utils::StatisticsMapValue::TotalSamples () const inline
Definition at line 119 of file Statistics.hpp.
{ return values_.total_samples(); }
References dyno::utils::Accumulator< SampleType, SumType, WindowSize >::total_samples(), and values_.
Member Data Documentation
kWindowSize
const int dyno::utils::StatisticsMapValue::kWindowSize = 1000 static
Definition at line 85 of file Statistics.hpp.
time_deltas_
Accumulator<double, double, kWindowSize> dyno::utils::StatisticsMapValue::time_deltas_ private
Definition at line 147 of file Statistics.hpp.
Referenced by AddValue(), GetLastDeltaTime(), LazyVarianceDeltaTime(), MaxDeltaTime(), MeanCallsPerSec(), MeanDeltaTime(), MinDeltaTime(), and RollingMeanDeltaTime().
time_last_called_
std::chrono::time_point<std::chrono::system_clock> dyno::utils::StatisticsMapValue::time_last_called_ private
Definition at line 148 of file Statistics.hpp.
Referenced by AddValue(), and StatisticsMapValue().
values_
Accumulator<double, double, kWindowSize> dyno::utils::StatisticsMapValue::values_ private
Definition at line 146 of file Statistics.hpp.
Referenced by AddValue(), GetAllValues(), GetLastValue(), LazyVariance(), Max(), Mean(), Median(), Min(), Q1(), Q3(), RollingMean(), Sum(), and TotalSamples().
The documentation for this struct was generated from the following file:
dynosam/include/dynosam/utils/Statistics.hpp